### ISSUE TITLE
Random crashes when running multiple server instances in parallel

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#1]
Sometimes the server crashes in GPU related methods when several instances are running in parallel or a very big number of cameras (6 or more) are attached to the vehicle.

**Comment by germanros1987** [comment]
Is this issue still active?

**Comment by nsubiron** [comment]
AFAIK this still happens, but it is going to be very difficult to spot the bug. It could be anywhere, nvidia drivers, Unreal Engine, or the GPU running out of memory.

**Comment by nsubiron** [comment]
Issue #1 finally closed, this is an important milestone :smile:
