### ISSUE TITLE
Carla  0.91 how to move my viewpoint in the map along with my player vehicle??

### ISSUE THREAD

**Issue by anshulpaigwar** [carla-simulator/carla#1006]
Carla 0.91 has loads of useful features that can be used for research, thanks to the carla team. 
But unlike in Carla 0.8x versions, my viewpoint in the map does not move with the player vehicle. We have to manually move it with arrow keys and mouse.

![screenshot from 2018-11-30 09-57-29](https://user-images.githubusercontent.com/6399885/49279049-ba1c1e00-f486-11e8-8afa-98fcab8c506f.png)

I want to be able to see the environment around my player vehicle and what it is doing. I understand that this is not the case in Carla 0.9x due to multi-client support and we would have to do this using something like pygame. But it would be nice if we could directly shift viewpoints over different player vehicles in Carla window as in 0.8x version.
![screenshot from 2018-11-28 10-31-27](https://user-images.githubusercontent.com/6399885/49279595-37945e00-f488-11e8-938a-b726d9f5b802.png)

It would  be helpful if I could get the sample pygame code for viewing the camera outputs as in your video of Carla 9.0

**Comment by M-Hammod** [comment]
you easily can do that  by piloting the camera attached to the vehicle, after spawning the vehicle from python, in the unreal editor-->world outliner-->search for 'cam'-->you will see the a camera actor attached to the vehicle that you spawned-->rightclick on it and choose pilot.

I had a proplem that I had to eject the player for the pilot option to get activated

hope this helps

**Comment by anshulpaigwar** [comment]
Thanks for the reply it helped to solve my problem.

**Comment by anshulpaigwar** [comment]
How to attach spectator to the vehicle like a camera ?? I tried this simply

```
        while True:
            spectator_transform =  vehicle.get_transform()
            spectator_transform.location += carla.Location(x = -2, y=0, z = 2.0)
            spectator.set_transform(spectator_transform)
            time.sleep(0.1)
```
This kind of works but there are two problems:
1)How to define transform with respect to vehicle?  According to my code the location of the spectator is sometimes ahead of the Vehicle sometimes behind. Also the x and y axis being getting swapped, I think it is because I have not considered orientation of the vehicle.

2) As I am using while loop with sleep, the update of spectator transform is not synced properly with the vehicle movement and it differs according to the processing power of different computers. If I reduce the sleep time the updates are fast with jitter and code freezes my computer.

**Comment by nsubiron** [comment]
Unfortunately, the transformation matrices are not yet implemented in the new API, but you can get them in Python from the old API at [transform.py](https://github.com/carla-simulator/carla/blob/master/Deprecated/PythonClient/carla/transform.py).

The best way for synchronizing the client with simulator updates is using the wait for tick function
```py
timestamp = world.wait_for_tick()
delta_seconds = timestamp.delta_seconds
```

**Comment by Sakrust** [comment]
Just use a little trick by placing a dummy actor in the scene: 

camera_bp = world.get_blueprint_library().find('sensor.camera.rgb')
    camera_transform = carla.Transform(carla.Location(x=10, z=10))
    camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)
spectator.set_transform(camera.get_transform())

**Comment by nsubiron** [comment]
That's a nice workaround :D but I would use instead a cheaper sensor, collision sensor for instance, cameras make your FPS drop significantly.

**Comment by ChrisHRZ** [comment]
> Just use a little trick by placing a dummy actor in the scene:
> 
> camera_bp = world.get_blueprint_library().find('sensor.camera.rgb')
> camera_transform = carla.Transform(carla.Location(x=10, z=10))
> camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)
> spectator.set_transform(camera.get_transform())



> Just use a little trick by placing a dummy actor in the scene:
> 
> camera_bp = world.get_blueprint_library().find('sensor.camera.rgb')
> camera_transform = carla.Transform(carla.Location(x=10, z=10))
> camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)
> spectator.set_transform(camera.get_transform())

How can i chose to view this camera?

**Comment by Sakrust** [comment]
You don't. Your simulator window view will be updated.

**Comment by gunki-geek** [comment]
u can write two scripts master.py and slave.py and synchronize between the two like in the attached scripts
[attach_spectator_to_vehicle.zip](https://github.com/carla-simulator/carla/files/7932460/attach_spectator_to_vehicle.zip)
s

**Comment by kuangzh123** [comment]
> Just use a little trick by placing a dummy actor in the scene:
> 
> camera_bp = world.get_blueprint_library().find('sensor.camera.rgb') camera_transform = carla.Transform(carla.Location(x=10, z=10)) camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle) spectator.set_transform(camera.get_transform())

Does this work?When I use this method,the spectator still moves forward and backward as the car speeds up and down
