### ISSUE TITLE
Axis of the CAR in CARLA

### ISSUE THREAD

**Issue by mkreddy477** [carla-simulator/carla#1012]
Hi,

I want to know how the axes are oriented in carla with respect to car.
If we see in ROS the coordinates follow this practice right hand thumb rule.
x:  forward
y: left side
z: upward

Please explain me how is the convention in used in CARLA.

**Comment by nsubiron** [comment]
We use the same coordinate as Unreal does, which is left-handed.
x: forward
y: right side
z: upward

**Comment by frk1993** [comment]
Hi,
Is the coordinate system in the newest version also left-handed?

Thanks!

**Comment by abol-karimi** [comment]
It seems that in 0.9.9.4 the frame follows the right-hand rule with z down: (forward, right, down) even though the method is called `get_up_vector()`
