### ISSUE TITLE
Lidar sensor possibly wrongly modeled in carla

### ISSUE THREAD

**Issue by anshulpaigwar** [carla-simulator/carla#1018]
While using Carla 0.91 (and also in previous versions) I observed that there are always some dead angles in the Lidar data as shown in the image below from pygame window ([manual_control.py](https://github.com/carla-simulator/carla/blob/0.9.1/PythonAPI/manual_control.py)):

![image29](https://user-images.githubusercontent.com/6399885/49591790-b77e6480-f96f-11e8-8cc4-815cfda5360a.png)

Others have also noticed the problem as in #995.

I tried to configure the settings parameters of Lidar sensor but could not resolve it. But I noticed that keeping the rotation frequency constant (10Hz) if I increased points_per_second  the dead angle reduces while it is more if the points_per_second are low. 
Also dead angles varies on different system with same configuration.

Upon checking the code [RayCastLidar.cpp](https://github.com/carla-simulator/carla/blob/0.9.1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp):
```
  const float CurrentHorizontalAngle = LidarMeasurement.GetHorizontalAngle();
  const float AngleDistanceOfTick = Description.RotationFrequency * 360.0f * DeltaTime;
  const float AngleDistanceOfLaserMeasure = AngleDistanceOfTick / PointsToScanWithOneLaser;

  LidarMeasurement.Reset(ChannelCount * PointsToScanWithOneLaser);

  for (auto Channel = 0u; Channel < ChannelCount; ++Channel)
  {
    for (auto i = 0u; i < PointsToScanWithOneLaser; ++i)
    {
      FVector Point;
      const float Angle = CurrentHorizontalAngle + AngleDistanceOfLaserMeasure * i;
      if (ShootLaser(Channel, Angle, Point))
      {
        LidarMeasurement.WritePoint(Channel, Point);
      }
    }
}
```
The for loop is from 0 to PointsToScanWithOneLaser which explains the cause of dead angle varying with points_per_second. (number of points get over before we complete 360 degree angle)

It should be something like:
```
delta_angle = 360/PointsToScanWithOneLaser

  for (auto Channel = 0u; Channel < ChannelCount; ++Channel)
  {
    for (auto i = 0u; i < PointsToScanWithOneLaser; ++i)
    {
      FVector Point;
      const float Angle = CurrentHorizontalAngle + delta_angle;
      if (ShootLaser(Channel, Angle, Point))
      {
        LidarMeasurement.WritePoint(Channel, Point);
      }
    }
}
```

I kindly request to fix this issue as many of us (autonomous vehicle researchers) are using carla because of it's support of lidar sensor.

**Comment by YashBansod** [comment]
@anshulpaigwar are you running your simulation in benchmark mode? 
You should run the simulation in multiples of your Lidar Frequency to get a full 360 degree in one reading. 
Alternatively, you could cache the Lidar reading to get a full 360 degree view.

The speed at which the server runs in non benchmark mode can vary a lot on a variety of factors.

**Comment by anshulpaigwar** [comment]
@nsubiron could you help with this issue of lidar sensor I still haven't been able to find a solution?

**Comment by nsubiron** [comment]
Hi @anshulpaigwar, as @YashBansod proposed you should run the simulator at fixed time-step ("benchmark" mode: `./CarlaUE4.sh -benchmark -fps=X`). Check out #835 for more info.

**Comment by vishal-prgmr** [comment]
@YashBansod , how did the cache the Lidar readings?
