### ISSUE TITLE
Draw_Waypoints error Carla 0.9.1

### ISSUE THREAD

**Issue by aroongta** [carla-simulator/carla#1019]
I am getting the following error when trying to display the waypoints as mentioned in the Carla 0.9.1 blog.
NameError: name 'draw_waypoints' is not defined

**Comment by Sakrust** [comment]
Because there is no function 'draw_waypoints' in the API, you have to define this function by yourself.

**Comment by nsubiron** [comment]
This is the function we used
```python
def draw_waypoints(world, waypoint, depth=6):
    if depth < 0:
        return
    for w in waypoint.next(4.0):
        t = w.transform
        begin = t.location + carla.Location(z=0.5)
        angle = math.radians(t.rotation.yaw)
        end = begin + carla.Location(x=math.cos(angle), y=math.sin(angle))
        world.debug.draw_arrow(begin, end, arrow_size=0.3, life_time=1.0)
        draw_waypoints(world, w, depth - 1)
```

**Comment by aroongta** [comment]
Thank you so much @Sakrust and @nsubiron

**Comment by shushu-nantong** [comment]
@nsubiron 
Would you please explain the code about "begin = t.location + carla.Location(z=0.5)" since t.location already outputs the location.
In other words, what does "carla.Location" stand for?

Thank you very much.
