### ISSUE TITLE
How can  I set the starting position?

### ISSUE THREAD

**Issue by youssefkhalil96** [carla-simulator/carla#1022]

**Comment by fabianoboril** [comment]
Hi,
could you please provide a few details? Where do you want to set the starting position, and of what (ego vehicle?)?

**Comment by youssefkhalil96** [comment]
Actually I want to make lane keeping control and I want to know the position of the vehicle within the two lanes so is there any way to do this thank you so much

**Comment by youssefkhalil96** [comment]
Hi,
thank you so much for your attention. The attached vehicle is the one I am simulating on. Actually I am doing lane keeping control so I need to know is there any way to know the position of the vehicle from the center of the lane and also I need to know the width if the road thank you so much.

________________________________

**Comment by yyuuliang** [comment]
use the segmentation camera to get the lane info, there should be a way to transform the lane location into the world coordinate, then you can use this data to control the vehicle. Your vehicle's controller should have a method to do the lane keeping after receiving the lane coordinate.
