### ISSUE TITLE
is there a planner in 0.9.1？

### ISSUE THREAD

**Issue by mznw** [carla-simulator/carla#1024]
Thanks for Carla team hard work.
I want to collect some driving data  based on CARLA.

Is there a planner in 0.9.1 ？ 
or how could i get a high level command( like Right， Left  ... ) in 0.9.1 if i set a start point and end point?

I know i can do that in 0.8.4 , and i want to do that in 0.9.1.

**Comment by Deepak3994** [comment]
Hi,

I have also the same question.

@mznw Didi you find any solution for your problem?
