### ISSUE TITLE
No agent Class in 0.9.1 

### ISSUE THREAD

**Issue by HubFire** [carla-simulator/carla#1028]
There is  no Agent class in carla 0.9.1,so how to create my own driving benchmark  ?

**Comment by nsubiron** [comment]
All the benchmark code is being migrated to https://github.com/carla-simulator/driving-benchmarks

**Comment by HubFire** [comment]
But the benchmark  in   [ https://github.com/carla-simulator/driving-benchmarks](url) is only for 0.8.4 version.

**Comment by nsubiron** [comment]
Oh true...  that's all we have then :/
