### ISSUE TITLE
Adding new measurements

### ISSUE THREAD

**Issue by Nozomeister** [carla-simulator/carla#1035]
Dear Carla team,
I want to ask whether it is possible to add in the measurements for every frame in 0.8.4 version? I want to add in some measurements in order to extract more data from the simulator but I don't know where to start. It would be great if there is a way to do this. 
Thank you.

**Comment by nsubiron** [comment]
It's actually quite complicated, you need to modify the C++ code in several places and the protobuf files to make it work. The easiest is for you to take a look how another measurement is already done.

If the new API is an option for you, in 0.9.1 we simplified a bit how to create a new sensor, so you can create a sensor that streams whatever data you need. Also requires changing C++ code, but you can find a mini tutorial in PR #830.
