### ISSUE TITLE
[0.9.1] [Linux] Implementing new weather szenario "night", CarlaWeather.ini

### ISSUE THREAD

**Issue by Atlunch** [carla-simulator/carla#1037]
Hello everyone,

I would like to create a night szenario in Carla.

I tried to create a new weather setting inside "CarlaWeather.ini". But I couldn't select it while i was using the manual_control.py.

Is this the right way or is there a better alternative?

And If this is the right way, does anyone have already the the right weather setting for a night szenario?

**Comment by Atlunch** [comment]
Great! Thank you very much.
While changing a few settings inside the editor it is possible to get a real night feeling.

**Comment by Unlingius** [comment]
@Atlunch  It looks really impressive! What settings did you change? How to attach light to car? I'm beginner in UE

**Comment by YDSh510** [comment]
@Atlunch - Which settings did you change to get above night effect in UE4 editor?

**Comment by AlanNaoto** [comment]
> Great! Thank you very much.
> While changing a few light settings inside the editor it is possible to get a real night feeling.
> ![screenshot from 2018-12-14 23-38-47](https://user-images.githubusercontent.com/31853843/50033600-76cebd00-fff9-11e8-9d0a-5f24ecdab512.png)

Hey! I'm really interested on this feature as well; would you mind sharing the assets/how to do that please?

**Comment by rrrokhtar** [comment]
@rikardomarenzzi  Can you mention the settings please
