### ISSUE TITLE
[0.8.4][Linux] Never reaches the end position and timeout

### ISSUE THREAD

**Issue by robotsoft** [carla-simulator/carla#1038]
When I tried to follow Benchmarking your Agent (https://carla.readthedocs.io/en/latest/benchmark_creating/), I noticed two problems as follows. I'm using an autopilot agent by using `control = measurements.player_measurements.autopilot_control`

1. The benchmark never reaches the end position and ends with timeout. I used `poses_tasks = [[[140, 134]]]`

2. The benchmark never reaches the end position with sufficient time. I increased `time_out` by 10 times in `CARLA_0.8.4/PythonClient/carla/driving_benchmark/driving_benchmark.pydriving_benchmark.py`

**Comment by felipecode** [comment]
The agent provided by the server does not follow the high level commands.
For that I created a client side agent for version 0.8.4 that is now on another repository.
https://github.com/carla-simulator/data-collector
