### ISSUE TITLE
Get multiple Cameras' data at the same time from the python client side [Carla 0.9.1]

### ISSUE THREAD

**Issue by bigsheep2018** [carla-simulator/carla#1042]
As the title mentioned, is it possible to get multiple cameras' data at the same time on the python side?

E.g., get the depth camera and lidar camera's data at the same time?

Thanks in advance.

**Comment by marcgpuig** [comment]
Hi @bigsheep2018,
Please, add in which Carla version are you working, as our issue creation protocol specifies.

**Comment by bigsheep2018** [comment]
Hello @marcgpuig,
The Carla version is [0.9.1]
The title is modified.
So is it possible to get multiple sensors' data at the same time?

**Comment by fabianoboril** [comment]
You can create multiple cameras. Then, each image comes with a frame number. Hence, you should be able to synchronize data coming from multiple cameras. Does this help you?

**Comment by fabianoboril** [comment]
Hi,
yes kind of. You spawn multiple cameras. For each you register a callback to receive the image. Each image comes with a framenumber. So you receive a set of images for each camera. Then, you can correlate/fuse them using the framenumber (the framenumber should correspond to the timestamp of the image).

**Comment by bigsheep2018** [comment]
@fabianoboril  Thanks. Close the issue.

**Comment by KouWeiBin** [comment]
> You can create multiple cameras. Then, each image comes with a frame number. Hence, you should be able to synchronize data coming from multiple cameras. Does this help you?

Hi, In think you are right, but how to sync the frame number of multiple cameras?

**Comment by DaniCarias** [comment]
> > You can create multiple cameras. Then, each image comes with a frame number. Hence, you should be able to synchronize data coming from multiple cameras. Does this help you?
> 
> Hi, In think you are right, but how to sync the frame number of multiple cameras?

+1
