### ISSUE TITLE
Migrate remaining CarlaSettings.ini to command-line arguments

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#1043]
We no longer need to have _CarlaSettings.ini_, let's move the remaining settings there to simulator command-line arguments so we can finally get rid of _CarlaSettings.ini_.

The settings remain in our _CarlaSettings.cpp_, but now we limit ourselves to read them from the command-line.

**Comment by wattsavolt** [comment]
This has been fixed and in master #1374
