### ISSUE TITLE
Advancing simulation in a synchronous way but by an explicit timestep.

### ISSUE THREAD

**Issue by Ajk4** [carla-simulator/carla#1047]
In Atari RL experiments there is usually a concept of 'frame-skip' which causes one action to repeat for 2-4 frames.

However this kind of approach is would be very wasteful in CARLA simulator since simulation steps are quite expensive to run. Additionally we might want to use arbitrary float numbers here instead of integers to be even more general.

Currently in CARLA when running simulator we can set SynchronousMode=true to make sure that environments stops when we are running training/inference. However this settings (along with fps) enforces frames to be ideally spread out in time. 

In real-world when driving we might not want to assume that data comes in in a ideally synchronized way exactly every N milliseconds.

It would be very useful to have option to explicitly decide 'how much time we want to move the simulation forward' each simulation update. That way we would be able to train sequential models that are timing-aware and that could adapt to different sensor delays.

Is there a way to achieve this 'advance simulation by explicit timestep' behavior in current CARLA release?

Cheers

**Comment by nsubiron** [comment]
Quick answer, it's not implemented in Carla. However, the game loop is handled fully by Unreal Engine so if you find a way of achieving this with Unreal Engine it will work with Carla.
