### ISSUE TITLE
[0.9.1] [Linux] specific vehicle NPC spawn

### ISSUE THREAD

**Issue by Atlunch** [carla-simulator/carla#1049]
Hello everyone,

what I have to change inside the spawn_npc.py to get a specific car? 
Such as just spawing mustangs.

**Comment by tanglrHello** [comment]
spawn_npc.py is designed to spawn a car of random blueprint. This is specified in line 76:
`
blueprint = random.choice(blueprints)
`

If you want to get a specific car, you need to assign blueprint to it. For example:
`
blueprint = world.get_blueprint_library().find("vehicle.ford.mustang")
`

By the way, I got the name of all vehicles available from running vehicle_gallery.py. It shows the name of each blueprint. You can modify this script to run faster to get all the names quickly.

**Comment by Sakrust** [comment]
You can also just print your blueprint library to see all available vehicles.
