### ISSUE TITLE
Getting lidar point cloud data from Carla

### ISSUE THREAD

**Issue by pfrcks** [carla-simulator/carla#1055]
I am trying to capture the `sensor.lidar.ray_cast` as mentioned on the [page](https://github.com/carla-simulator/carla/blob/master/Docs/cameras_and_sensors.md), however on visualizing the pointcloud it appears to be too sparse. Any suggestions as to how to improve the quality of the data captured?

**Comment by analog-cbarber** [comment]
Not sure what you mean by "too sparse". Do you mean you cannot see the points very well? If so, first try rendering your point cloud using larger points.

**Comment by pfrcks** [comment]
Hey,

Thanks for the response. I am able to see the points but they are not dense, i.e, they are not able to capture the scene with decent quality.

![screenshot from 2018-12-17 15-39-58](https://user-images.githubusercontent.com/10297394/50102040-5fbfe300-0224-11e9-91d2-118c4b20eab6.png)
