### ISSUE TITLE
Loading Velocity Profile

### ISSUE THREAD

**Issue by AbdulHoffmann** [carla-simulator/carla#1061]
Hello developers and community,

I would like to know if there's some way already implemented for loading velocity profiles (.csv containing instant velocity vs time). I read the documentation and played with the API a bit, and right now the most I can do is read velocity with carla.Actor's method `get_velocity()`, and try to keep track of it correcting the throttle. But it's rather imprecise.

One thing I thought of was implementing a PID controller to at least assess velocity in a more accurate way, however I would like to know if someone has already done that or if there's a simpler way of doing so.

Many thanks and keep it up, folks.

**Comment by YashBansod** [comment]
@AbdulHoffmann You could rather load the control profile. However, if your goal is to trace a velocity profile, then any form of controller (PID, MPC etc) is the way I go about it.
