### ISSUE TITLE
Multi-agent support

### ISSUE THREAD

**Issue by AlenUbuntu** [carla-simulator/carla#1070]
Does Carla 0.9.1 or 0.8.4 support multi-agent for RL algorithms?

**Comment by fabianoboril** [comment]
Carla 0.9.1 supports multi-agent simulation, meaning you can control multiple vehicles (with different setup). 0.8.4 doesn't support this features. Does this answer your question?

Regards

**Comment by AlenUbuntu** [comment]
Yes. Thank you for quick response.
