### ISSUE TITLE
How to generate Dataset with 28 control signals..

### ISSUE THREAD

**Issue by Deepak3994** [carla-simulator/carla#1074]
how did you collect the dataset in CARLA,when i run the ./client_example.py --autopilot --images-to-disk i can just get the rgb , depth image and print some measurements , but i can not get all the 28 measurements in targets,how did u get it? KIndly help

**Comment by geekhut** [comment]
Hi what do you mean by the 28 control signals?

**Comment by geekhut** [comment]
@Deepak3994 Hi are you able to get the measurements as of now?
