### ISSUE TITLE
[0.9.2] what's the mean of the "role_name"?

### ISSUE THREAD

**Issue by 1453042287** [carla-simulator/carla#1075]
like the title, is it something like "ford.mustang"? or is there any examples to explain this?

**Comment by fabianoboril** [comment]
Hi,

the role_name is used to indicate how a vehicle is controlled. This is mainly used by the ros-bridge and the scenario_runner to connect to the ego vehicle. For example, in manual_control.py you can see how this attribute is set. Afterwards it can be accessed just like any other blueprint attribute.

**Comment by berndgassmann** [comment]
Hi,

inside the ros-bridge the role_name for sensors enables also to distinguish different sensors of the same type attached to the vehicle (e.g. front_left, front_right, etc.)
