### ISSUE TITLE
0.9.2 documentation

### ISSUE THREAD

**Issue by Johnnyswong** [carla-simulator/carla#1077]
hi, the new features in 0.9.2 are awesome. 
The carla simulator is becoming more and more practical and convenient for the users.
But is there any documentation for the new features in 0.9.2? I search "BasicAgent" in the documentation but return nothing.

**Comment by heyuan1993** [comment]
and I can't get much information of CarlaMapGenerator in source code but there seems a tool described documentation.

**Comment by yyuuliang** [comment]
I have noticed that they recently published the new Python API for 0.9.x. Is this useful for u?
Python API tutorial
https://carla.readthedocs.io/en/latest/python_api_tutorial/
