### ISSUE TITLE
How to find preceeding vehicle distance from ego vehilce in carla?

### ISSUE THREAD

**Issue by Deepak3994** [carla-simulator/carla#1081]
I want to find the distance from ego-vehicle to ongoing/incoming vehicles in carla...How to get this information in carla?

**Comment by fabianoboril** [comment]
Hi,
you can use the get_location() function from the PythonAPI to get the location of each vehicle. Then, you can calculate the direct distance between any two vehicles. That is straightfoward in Python. 

However, if you want to get the distance along a curvy road, you have to write your own code calculating first the route between the two locations and then the length of this route.

**Comment by IsraaBay** [comment]
https://github.com/fabianoboril Can you please write the code for calculating the distance between the car and other objects in carla?
