### ISSUE TITLE
ImportError: No module named derived_object_msgs.msg

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla#1083]
Hello，everyone
I download the prebuilded  version of Carla ,and I completed to  Install the CARLA Python API according to the guide(https://github.com/carla-simulator/ros-bridge),runnning this:
python -c 'import carla;print("Success")' ,Show success message without any error.
But when I run:
roslaunch carla_ros_bridge client.launch 
there is the following error:
`ImportError: No module named derived_object_msgs.msg`
How can I solve this problem?

**Comment by fabianoboril** [comment]
Hi,
you need to install the derived-object-sensor package for ROS, e.g. something like
ˋˋˋ
apt-get install ros-kinetic-derived-object-sensor-msgs
ˋˋˋ

**Comment by JackRen88** [comment]
@fabianoboril 
Thanks！

**Comment by nishanthjois** [comment]
@JackRen88 Did below command work? Its's not for me.
apt-get install ros-kinetic-derived-object-sensor-msgs

**Comment by raphaellmsousa** [comment]
Hi guys, I'm having the same problem here. Did you guys find a solution? Thanks..

**Comment by berndgassmann** [comment]
The solution is listed above and therefore the issue is closed.
Did you install those:

apt-get install ros-kinetic-derived-object-sensor-msgs

**Comment by zhenwei01** [comment]
if you Unable to locate package ros-kinetic-derived-object-sensor-msgs, try this 

apt-get install ros-kinetic-derived-object-msgs

**Comment by wuxiaohua1011** [comment]
in foxy, it is `sudo apt install ros-foxy-derived-object-msgs`
