### ISSUE TITLE
How to define ROI infront of vehicle and how to draw 3D box for it?? Transformation

### ISSUE THREAD

**Issue by chowkamlee81** [carla-simulator/carla#1089]
Hi,

I want to draw ROI infront of car and consider nonplayer agents inside that ROI. How to draw 3D boxes to plot in RGB image. KIndly help.
Iam in confusion on transformations. Kindly help

**Comment by marcgpuig** [comment]
Hi @chowkamlee81 
Maybe you want to read #56, #64, #314 and #772 :)

Cheers!
