### ISSUE TITLE
automotive materials problem

### ISSUE THREAD

**Issue by KUASWoodyLIN** [carla-simulator/carla#109]
I have manually link the materials,
and replace "DummyCar" material by "M_Carpaint" material,
but the car color look weird, the effect is no better than the "DummyCar" material,
how can I fix this problem?

![image](https://user-images.githubusercontent.com/9446515/34548937-ebbe6b98-f13f-11e7-9221-5c53ec719f55.png)

**Comment by curantil** [comment]
The solution is given in #18
