### ISSUE TITLE
[0.9.2] Is it possible to import a customized town?

### ISSUE THREAD

**Issue by bigsheep2018** [carla-simulator/carla#1091]
Hello,

Thanks for releasing the new Carla version.
I am wandering if it is possible to import a town/map (the buildings, threes, roads, etc. i.e., the background) designed by other software (e.g., 3dMax, Maya, etc) or a pure UE4 project (while keep everything else works normally)? 

I have checked the tutorial about customizing a town, but it seems the user need to build the town based on Carla's contents. Just wanna check if it is possible to achieve this goal. If yes, could you please tell me how to do it?

Thanks in advance.

**Comment by XGodina** [comment]
Hi, @bigsheep2018,

Import a new map make it with other software (e.g., 3dMax, Maya, etc) to UE4 and after "...everything else works normally" It's impossible. Currently we use other pipeline.

Nowdays we use a Road Runner for making roads layouts and create the OpenDrive information. After that complete it with our assets in UE4.
