### ISSUE TITLE
Running Carla in Docker

### ISSUE THREAD

**Issue by Deepak3994** [carla-simulator/carla#1093]
I have installed the nvidi-docker and as well as nvidia-driver on my AWS instances. While running the below "**docker run -p 2000-2002:2000-2002 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 carlasim/carla:0.8.4 /bin/bash CarlaUE4.sh  -carla-server**" command i am getting the error as "**CarlaUE4.sh: line 5: /home/carla/CarlaUE4/Binaries/Linux/CarlaUE4: Text file busy**".

Kindly help.

**Comment by tanglrHello** [comment]
I have the same problem. After executing 'make package' and cd Dist/0.9.1-release/LinuxNoEditor, there is a Dockerfile. Generate the image and run in the way demonstrated in #481, I also get the error 'Text file busy'.
