### ISSUE TITLE
How to set actor id in carla 0.9.2

### ISSUE THREAD

**Issue by anshulpaigwar** [carla-simulator/carla#1094]
I want to set specific id to all the vehicles I spawn I tried following:
```
bp = random.choice(blueprint_library.filter('vehicle'))
bp.set_attribute('id', '5')
``` 
but it shows error attribute 'id' not found!

I also tried:
```
vehicle = world.spawn_actor(bp, transform)
vehicle.id = "5"
``` 
Which doesnot work either.
If it is not possible to set the specific id how to manually set the random seed so that my id doesn't change every time.

**Comment by pawel-ziecina** [comment]
Can you explain your use case?

I understand id attribute as "read-only", auto-increament field with unique value assigned by carla server.

Possibly you can use role_name attribute for you use case:

```python
bp.set_attribute('role_name', '5')
# ...
role_name = vehicle.attributes['role_name']
```
