### ISSUE TITLE
Semantic Segmentation Ground Truth Not Synchronized with Camera

### ISSUE THREAD

**Issue by sagnibak** [carla-simulator/carla#1098]
I used a slightly modified version of [`manual_control.py`](https://github.com/sagnibak/self-driving-car/blob/master/CARLA_simulator_scripts/mc_buffered_save.py) to collect RGB images, depth maps, semantic segmentation ground truth data. However, looking at the following images it is evident that even though the depth maps and RGB images are synchronized, the semantic segmentation ground truth is not:

![depth map](https://i.imgur.com/5SW9hwu.png)
![rgb image](https://i.imgur.com/foGV6gs.png)
![semantic segmentation](https://i.imgur.com/EXSnREv.png)

If you look closely at the code [here](https://github.com/sagnibak/self-driving-car/blob/master/CARLA_simulator_scripts/mc_buffered_save.py#L241), all the sensor data is being collected at the same time and then being saved [here](https://github.com/sagnibak/self-driving-car/blob/master/CARLA_simulator_scripts/mc_buffered_save.py#L287). So this lack of synchronization seems to be a problem with the simulator.

The problem persists even when I remove the depth camera and only use RGB and semantic segmentation cameras.

I'm using version 0.8.4 on Windows (prebuilt binary).

**Comment by sagnibak** [comment]
Solution: Run the simulator in **synchronous mode**! Running in synchronous mode makes sure that the RGB camera image is temporally aligned with the semantic segmentation ground truth.

**Comment by Rajat-Mehta** [comment]
@sagnibak What do I need to do to run simulator in synchronous mode? I also want to do something similar, I want to collect data from camera, depth images, semantic segmented image and lidar plots to train a neural network. Thanks in advance.

**Comment by sagnibak** [comment]
@Rajat-Mehta my answer works for v0.8.x and it has been a while since I used CARLA, and I have no idea how 0.9.x works since I have never used it. For 0.8.x, you need to pass in a command line argument. [This page](https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/) in the docs is what you should read.
