### ISSUE TITLE
Timestamp for Sensors

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#1105]
I implemented an IMU sensor using the suggestion by @nsubiron in #1029 
Then I implemented routines to store camera image through the `sensor.listen()` and to store odometry annotation through world.on_tick()`.

I am storing the timestamp available through `world.on_tick()` for odometry data however, there is no such option for sensors. 

- Is there a way by which I can access the timestamp of the camera images?  
or  
- By some means co-relate appropriate `sensor.listen` function call to `world.tick` function call?

**Comment by fabianoboril** [comment]
Hi,
the camera image comes with a frame id. This id should also be available as part of the timestamp coming from the on_tick() callback.
