### ISSUE TITLE
Modified manual control

### ISSUE THREAD

**Issue by andreimihalcea97** [carla-simulator/carla#1108]
Hi,

I have modified the manual_control.py script by adding a new surface on the pygame window on which I simply draw some lines. After this modification, I seem to cannot control the car (I can sometimes control it, but it moves very slowly). I am using the 0.8.4 release for windows.

Thanks in advance

**Comment by nsubiron** [comment]
Probably the code you added is too slow to be executed each frame and it's slowing down the client.
