### ISSUE TITLE
Is there any plan to develop a faster version that without graphic?

### ISSUE THREAD

**Issue by tanisxu** [carla-simulator/carla#111]
We know rendering the models and meshes takes a lot of time, but sometime we dont need grapics, but only logic to test our decision making model.
Is there any plan?
Thank you and happy new year. Appreciate your awesome work.

**Comment by felipecode** [comment]
Hi @tanisxu, Thanks for the suggestion.
Eventually we could add this. However, I doubt this is going to be a priority in a near future. We would maybe ask help from the community for that.
