### ISSUE TITLE
error when i make launch,

### ISSUE THREAD

**Issue by Firesuiry** [carla-simulator/carla#1110]
the error is 
`make: *** No rule to make target 'launch'.  Stop.`
How can i fix this error?
thanks a lot..

**Comment by tanglrHello** [comment]
Could you give more detail? In which path you make launch? And what you have in that path?

**Comment by Firesuiry** [comment]
thank you for your reply.
I make launch at carla file.
the file content is as follow:
![_ _20190109123109](https://user-images.githubusercontent.com/30189673/50876932-7bc13980-140a-11e9-85a5-b9656ec68192.png)
the files is too many because I have depress some assets files wrongly into this file.
and my unreal is installed successfully ,the version is 4.19.2.

**Comment by tanglrHello** [comment]
Which version for carla are you using? It seems a little bit different from release0.9.1 I'm using. 
![image](https://user-images.githubusercontent.com/18596553/50878688-d494d000-1412-11e9-9f98-0d88d3c0b703.png)


This error seems to be related with Makefile. My Makefile content:
![image](https://user-images.githubusercontent.com/18596553/50878707-ef674480-1412-11e9-9d7d-c2e76402d1a1.png)

And I'm on Linux, so take a look at Util/BuildTools/Linux.mk, you will see the 'lanuch' target. In my enviroment, if I execute "make hello" for example, I'll get the same error as yours.

**Comment by Firesuiry** [comment]
i am using the release 0.8.2
and my Makefile is different with yours.
Maybe this will cause the error,i will try the release 0.9.2.
thank you for your help!!

**Comment by MSiam** [comment]
I had the same error when I checked out the stable branch but with the master branch the error was gone.

**Comment by soheilade** [comment]
Dear All,

I am following the tutorial [here](https://carla.readthedocs.io/en/latest/how_to_build_on_linux/) to build carla. However, running make launch fails on branch stable with this error. 
![image](https://user-images.githubusercontent.com/1499596/75670426-fdae9a80-5c7c-11ea-85fd-bec4eed7e028.png)
on the branch master, I fail with this error: 
![image](https://user-images.githubusercontent.com/1499596/75670544-39e1fb00-5c7d-11ea-94b2-58be77629a39.png)
any idea how to deal with this?
