### ISSUE TITLE
Carla 0.9.2 how to set a a fix velocity to the vehicle ?? 

### ISSUE THREAD

**Issue by anshulpaigwar** [carla-simulator/carla#1113]
I was working on the validation of perception algorithm. To generate ground truth I require to set a fixed velocity of npc vehicles. But currently, I could only use the throttle and brake method to control the vehicle. So I would need to design a controller.  Does anyone already implemented a PID controller for the velocity??

**Comment by Sakrust** [comment]
Have a look into the Agent classes and the ScenarioRunner repo. Setting a velocity for an agent vehicle directly bypassing motor simulation with throttle input is currently not possible but on the roadmap for Carla.
