### ISSUE TITLE
Create an instance of carla.Map without connecting to the server through carla.Client

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#1114]
I wanted to know if there was a way I could create an instance of `carla.Map` containing the map of the **Town03**.
The new `carla.Waypoint` class is very powerful and simplifies a lot of things and it would be awesome if there was a way to use it without having to initiate a server to do the same.

**Comment by nsubiron** [comment]
At this point is not possible, because the OpenDrive file is retrieved from the server each time.

Someone already suggested allowing to create a `carla.Map` by providing the OpenDrive file directly, that's something easy that I would like to add, that would work for this purpose.

**Comment by nsubiron** [comment]
This was added in 0.9.5, now you can build a map object offline providing the XODR contents

```py
with open('Town03.xodr', 'r') as fp:
    m = carla.Map('Town03', fp.read())
```
