### ISSUE TITLE
Increase Framerate of the Server (0.9.2)

### ISSUE THREAD

**Issue by dieteekanne2** [carla-simulator/carla#1121]
Hi,
when I use a modified manual_control.py script with two RGB (800x600) cameras the servers frame rate drops to 14-17 FPS.
I was wondering if there is any possibility to increase the frame rate of the server in v0.9.2 (with Epic graphic settings). Or is this simply the frame rate I can expect with a setup like mine?
Thank you

My setup:
- Ubuntu 18.04.1 
- Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
- GeForce GTX 1080 Ti

**Comment by nsubiron** [comment]
You can launch the simulator without display, in low quality mode, and with fixed time-step

    DISPLAY= ./CarlaUE4.sh -quality-level=Low -benchmark -fps=10

that's as fast as it gets.

Unfortunately, yours is the expected frame rate with high quality. The cameras we use for capturing affect performance pretty badly, but we don't know any alternative.
