### ISSUE TITLE
does running Carla's docker image require the installation of Unreal engine?

### ISSUE THREAD

**Issue by ahmedessameldin1elfakharany** [carla-simulator/carla#1123]
I'm pretty much new to Docker, do I need to install the Unreal engine 4 before running the Carla container on my machine?

**Comment by nsubiron** [comment]
No, the docker image contains only a Carla binary. Just as if you download the binary version, you don't need Unreal to run it.

**Comment by ahmedessameldin1elfakharany** [comment]
Thank you for your answer.
