### ISSUE TITLE
Does CARLA come with sensor fusion code?

### ISSUE THREAD

**Issue by eds89** [carla-simulator/carla#113]
Hello,
Does CARLA come with sensor fusion code? I'd like to have a look at its data fusion code if available, and do some research with it as part of my PhD project. A keyword search on the source did not find anything.

**Comment by nsubiron** [comment]
CARLA does not provide any data fusion algorithm, it just provides the API for you to retrieve the data.

This is how it works, the CARLA server runs the simulation, renders the images, and produces all the measurements. We provide a Python API to communicate with the server: set up the simulation, control the car, and retrieve the data; but it's up to the user to code the actual functionality of the client. We have a minimal example of a client using the API at [PythonClient/client_example.py](https://github.com/carla-simulator/carla/blob/master/PythonClient/client_example.py).
