### ISSUE TITLE
[Qusetion]How can I add a parking space on the maps?

### ISSUE THREAD

**Issue by Firesuiry** [carla-simulator/carla#1132]
I have used Unity3d and have not used Unreal before.
I want to know how can I build a asset like assets in Carla/Static/RoadLines/St_Road_TileRoad_LaneMarkinaSolid.uasset
and the parking space is like
![default](https://user-images.githubusercontent.com/30189673/51081121-462a9200-1723-11e9-8b1a-edae89d4d6d6.png)

**Comment by hesty98** [comment]
Hey Firesuiry,
since you closed this - did you manage to figure out a solution?

Best regards!
