### ISSUE TITLE
Get Camera transform in carla 0.8.4

### ISSUE THREAD

**Issue by atanas1054** [carla-simulator/carla#1136]
Hi,
How can I get the transform (pose) of the attached RGB camera to the car in carla 0.8.4?

**Comment by Unlingius** [comment]
as I know, manual_control.py 0.8.4 example shows, how to get transform of car, and how to set camera position, relative to car. Then you can calculate absolute position of camera from:  cam_abs = car_abs + R * cam_rel, R - rotation matrix of car
