### ISSUE TITLE
scenario runner ImportError: No module named carla

### ISSUE THREAD

**Issue by geekhut** [carla-simulator/carla#1137]
Hi all, new to carla here. I am looking through this tutorial on scenario runner,

https://github.com/carla-simulator/scenario_runner/blob/master/Docs/getting_started.md

and I ran into the "ImportError: No module named carla" error again, I have already looked at the relevant issues raised by others but still, I can't seem to solve this problem. Help me out please!

I am using the pre-compiled CarlaUE4.sh by the way.

**Comment by fabianoboril** [comment]
Hi,
did you set your PYTHONPATH as mentioned in the documentation?
`export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla-<VERSION>.egg`

**Comment by geekhut** [comment]
> Hi,
> did you set your PYTHONPATH as mentioned in the documentation?
> `export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla-<VERSION>.egg`

Hi, I have settled the issue, by setting the right path and using python3. Python2 leads to "importError: No module named carla".

**Comment by fabianoboril** [comment]
It all depends on which egg you use. If you want to use Python2, you need to use the egg for Python2.

**Comment by wendersonj** [comment]
This information could be in the Getting Start from the lastest documentation, causa I didn't found it and was really important ! Anyway, thanks @geekhut !

**Comment by wendersonj** [comment]
This information could be in the Getting Start from the lastest documentation, because I didn't found it and was really important ! Anyway, thanks @fabianoboril !

**Comment by vishal-prgmr** [comment]
@fabianoboril , where do i find the egg files. I built Carla 0.9.5 from source for Windows.
Running make PythonAPI returns the error "Make sure "py" is installed but i am calling this command from inside a environment which has python3.7.3"

**Comment by Sibi-ROS-coder** [comment]
> > Hi,
> > did you set your PYTHONPATH as mentioned in the documentation?
> > `export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla-<VERSION>.egg`
> 
> Hi, I have settled the issue, by setting the right path and using python3. Python2 leads to "importError: No module named carla".

well i did the same thing the import Carla problem pops can you be specific what to do for pythin2 as well I am new to carla
