### ISSUE TITLE
fail in client.get_world() 

### ISSUE THREAD

**Issue by fty0724** [carla-simulator/carla#1141]
hello, I am  learning Carla following the docs. 

At the chapter "Python API tutorial", I meet the problem as describe follows:

After I execute the command"**world = client.get_world()**", I got the runtime error. 
In order to solve it, I firstly opened the simulator by using "make launch",then I got the port of the UE4Editor. and I execute the commands"client = carla.Client('localhost', my_simulator_port)" "client.set_timeout(10.0)"  "world = client.get_world()", but it has the same error. can you help me solving this problem? thanks!

Carla version:0.9.1
Ubuntu version: 16.04.LTS
Unreal Verison:4.19

**Comment by sheepwxy** [comment]
> 
> 
> Did you press the "play" button in UE4Editor to run the carla server? Did you get a timeout runtime error? In your description there is not a step to run the server

thanks for your reply!! I have solved the problem.

**Comment by hamdii02** [comment]
how you solved the problem please ?

**Comment by vajrag** [comment]
Could you mention how you solved this problem? @fty0724 @sheepwxy 
Thanks :)
