### ISSUE TITLE
Can't get_actors() before get_blueprint_library()

### ISSUE THREAD

**Issue by tanglrHello** [carla-simulator/carla#1151]
Here is the code:
```py
import carla
client = carla.Client("127.0.0.1", 2000)
client.set_timeout(2.0)
world = client.get_world()
blueprints = world.get_blueprint_library()   //***
actors = world.get_actors()
print ("actor num:" + str(len(actors)))
```
If I remove the blueprint line, the actors will be empty. Is it a designed feature? Just report the case.

**Comment by nsubiron** [comment]
It seems a matter of timing, can you check if it works replacing the `get_blueprint_library()` by a `time.sleep(1)`?

Internally, when you request the world you subscribe to the world observer sensor that sends the list of actors and their transforms. If you are too fast you may not have received any update yet thus it will appear there are no actors.

**Comment by tanglrHello** [comment]
Yes, it works with time.sleep(1) before GetActors. 
Using world.wait_for_tick() works, too.

**Comment by nsubiron** [comment]
> Using world.wait_for_tick() works, too.

Good idea :smile:
