### ISSUE TITLE
Generate Windows Build of CARLA 0.9.2 

### ISSUE THREAD

**Issue by eds89** [carla-simulator/carla#1152]
Hello,
Would it be possible to generate a Windows build for Carla 0.9.2, please?

Can it be compiled on that system at all? I've read that currently it is only available for Linux.

Kind regards.
Eduardo

**Comment by didibaba** [comment]
@eds89 #1147

**Comment by ryanwang522** [comment]
@didibaba Hi, 

I've read some related issues about building carla 0.9.X on win10. 
I'm wondering do you ever build 0.9.x() on win10 successfully so far ?

**Comment by didibaba** [comment]
@ryanwang522 
Definitely, except for the PythonAPI.

**Comment by marcgpuig** [comment]
Hi @eds89, is just like @didibaba says.
Please read this https://github.com/carla-simulator/carla/issues/1000#issuecomment-445796518
I'm closing the issue because is duplicated.
