### ISSUE TITLE
Does the LiDAR of CARLA support to simulate 64 channels?

### ISSUE THREAD

**Issue by atinfinity** [carla-simulator/carla#1156]
## System information (version)
- Ubuntu 16.04 64bit
- CARLA v0.9.2(compiled version)

## Detailed description
In the [document](https://carla.readthedocs.io/en/latest/cameras_and_sensors/#sensorlidarray_cast), default channels of LiDAR is 32. Does the LiDAR of CARLA support to simulate 64 channels?

**Comment by marcgpuig** [comment]
Hi @atinfinity
You can simulate it indeed, but expect to be slower.
As the documentation you mentioned says, you can just change the blueprint attributes to suit your needs :)

**Comment by atinfinity** [comment]
Hi, @marcgpuig 
Thank you for your reply.
I tried to change the following attributes.

* channels
* points_per_second

It seems that the result of visualization changes by these attributes.

![screenshot from 2019-01-24 00-10-37](https://user-images.githubusercontent.com/2630323/51736161-b7c3f200-20cc-11e9-8d9a-5e3d306c0d7b.png)

**Comment by marcgpuig** [comment]
Glad that it worked @atinfinity
Looks great!

You can close this issue if this solved your initial question.
