### ISSUE TITLE
Better control over pedestrians

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#1158]
Child of #630.

Allow for better control over pedestrians/walkers

- [ ] Changing characteristics like props and clothes colors from the Python API.
- [ ] Detect whether they have been run over (event? is_alive function?).

**Comment by jagdishbhanushali** [comment]
Hi @nsubiron 
I am working on generating all variety of pedestrians with different props. I saw an event in unreal editor for destroying props along with destroying pedestrian. I think you must be near to finishing this feature. Please let me know much time it gonna take to finish this feature.

Thanks.

**Comment by nsubiron** [comment]
Hi @jagdishbhanushali,

At the moment no one is working on this feature. We added it to our backlog because is something we would like to have, but we are currently busy with other tasks with higher priority for the Carla challenge.

**Comment by JunweiLiang** [comment]
Hi @nsubiron,
Thank you for the great work! Any update/timeline on this? In v0.9.6 there are only 14 kinds of pedestrian and there is no attribute like "clothes" or "color" to change.
Thanks!

**Comment by germanros1987** [comment]
The new pedestrian module should take care of this issue.
