### ISSUE TITLE
carla 0.8.2: modifying PythonClient files does not take effect

### ISSUE THREAD

**Issue by geekhut** [carla-simulator/carla#1159]
So I'm trying out Carla 0.8.2 (stable), wanting to print some measurement readings like collision_vehicles or steering angles etc from here,
 
https://github.com/carla-simulator/carla/blob/master/Docs/measurements.md

However, no matter how I modify the .py files such as manual_control.py, to print more measurements while the vehicle moves, my terminal just won't print anything of my interest. What am I missing out on?

I am using the pre-compiled CarlaUE4.sh and the .py files in PythonClient folder.

Thanks!

**Comment by Dola47** [comment]
@geekhut  Hello, would you mind to share the edited python file with me, because also I want to measure the collision but do not know how to do so. 

If you can share it, so I can test it with in my Carla environment and give you the response. I will be thankful anyway.

Thanks.
