### ISSUE TITLE
what would be the steps for completley uninstalling Carla on Win10

### ISSUE THREAD

**Issue by HeYDwane3** [carla-simulator/carla#1160]
Hi, I am using Win10 to build 0.9.2, but I found that some functions are not supported right now, so I am going to delete all the Carla related files on windows, and make a dual boot for Ubuntu, and build everything again. 

So in order to release as much space as possible, I am wondering what would be the process to delete all the files that had been built?

My guess would be:
1. "make clean" to delete 0.9.2 related files.
2. Delete the Carla project in UE4 and then uninstall the UE4
3. Uninstall the VS2017.
4. As Cmake and make take very little space, they could stay.
5. As python and git are already installed before building the Carla, they will also stay there.

Above are pretty much everything I can think of, did I miss anything?

Thanks for the help.

**Comment by marcgpuig** [comment]
Hi @HeYDwane3
Maybe you can uninstall make and cmake too if you are not using them anyway :)
