### ISSUE TITLE
Change the saved screenshots path

### ISSUE THREAD

**Issue by martisaju** [carla-simulator/carla#1162]
I want to change the path where the screenshots images (launching ./CarlaUE4.exe -benchmark -fps=30 -dumpmovie -windowed) are saved instead. Which is the .py file I should check?

Thank you so much

**Comment by Sakrust** [comment]
This -dumpmovie argument is an Unreal Engine feature, so it has nothing to do with Carla or any python file. 

If you use sensors instead (e.g. camera.rgb), you can specify the path using the listen function on your sensor object: listen(callback_function) and the save function on your image objects: save_to_disk(path, color_converter=None).

**Comment by martisaju** [comment]
@Sakrust thank you so much! :)
