### ISSUE TITLE
How to display vehicle bounding boxes on the RGB frames in CARLA_0.9.2?

### ISSUE THREAD

**Issue by alex5528** [carla-simulator/carla#1163]
Hi 

How to display vehicle bounding boxes on the RGB frames in `CARLA_0.9.2`?

I find [this](https://github.com/carla-simulator/carla/issues/314) example for the older version.

Similar example for 0.9.2 would be very useful!!

Thanks

**Comment by jagdishbhanushali** [comment]
Hi @alex5528, did you able to make it work? If yes, please share it here.
