### ISSUE TITLE
Bad access memory running on package while non-rendering mode

### ISSUE THREAD

**Issue by marcgpuig** [carla-simulator/carla#1168]
While using non-rendering mode with `CarlaSettings.ini` I got a bad access memory that can be read [here](https://github.com/carla-simulator/carla/files/2787886/log.txt).

In my particular case, I'm running Town05 (`/Game/Carla/Maps/Town05`).

In a Linux 16.04 I'm running the package like this:

```
./CarlaUE4.sh -benchmark -fps=20 -windowed --carla-settings="CarlaSettings.ini"
```

`CarlaSettings.ini` have one change for the non-rendereing mode:

```ini
; If set to true, all cameras and HUD will stop rendering. By default rendering
; is enabled.
DisableRendering=true
```

**Comment by nsubiron** [comment]
Unrelated to no-rendering mode it seems. We are not handling the case of a Carla actor being destroyed and not deregistered from the actor registry, thus when the actor is garbage collected we get segmentation faults. This happens for instance if an actor falls out of the map.

It can be solve by registering a delegate to every actor's OnDestroyed event that removes the actor from the registry.
