### ISSUE TITLE
crash in running carla in server mode [0.9.2]

### ISSUE THREAD

**Issue by rguptatx** [carla-simulator/carla#1192]
my command is:
/usr/local/UnrealEngine_4.21/Engine/Binaries/Linux/UE4Editor -carla-server "/usr/local/carla/Unreal/CarlaUE4/CarlaUE4.uproject" /usr/local/carla/Maps/Town03 -benchmark -fps=10 -windowed 

this crashes with the log below. Works fine is I do not run it as server and remove the -carla-server argument.

Increasing per-process limit of core file size to infinity.
LogConsoleResponse: Display: Failed to find resolution value strings in scalability ini. Falling back to default.
LogInit: Display: Running engine without a game
LogPakFile: Registered encryption key '00000000000000000000000000000000': 0 pak files mounted, 0 remain pending
LogPlatformFile: Not using cached read wrapper
LogTaskGraph: Started task graph with 5 named threads and 53 total threads with 3 sets of task threads.
LogStats: Stats thread started at 0.073031
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: -8:00, Platform Override: ''
LogPluginManager: Mounting plugin ActorLayerUtilities
LogPluginManager: Mounting plugin CLionSourceCodeAccess
LogPluginManager: Mounting plugin VisualStudioCodeSourceCodeAccess
LogPluginManager: Mounting plugin SubversionSourceControl
LogPluginManager: Mounting plugin GitSourceControl
LogPluginManager: Mounting plugin UObjectPlugin
LogPluginManager: Mounting plugin CodeLiteSourceCodeAccess
LogPluginManager: Mounting plugin VisualStudioSourceCodeAccess
LogPluginManager: Mounting plugin KDevelopSourceCodeAccess
LogPluginManager: Mounting plugin PerforceSourceControl
LogPluginManager: Mounting plugin NullSourceCodeAccess
LogPluginManager: Mounting plugin XCodeSourceCodeAccess
LogPluginManager: Mounting plugin TcpMessaging
LogPluginManager: Mounting plugin UdpMessaging
LogPluginManager: Mounting plugin LightPropagationVolume
LogPluginManager: Mounting plugin Paper2D
LogPluginManager: Mounting plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting plugin WebMMoviePlayer
LogPluginManager: Mounting plugin PhysXVehicles
LogPluginManager: Mounting plugin SteamVR
LogPluginManager: Mounting plugin CableComponent
LogPluginManager: Mounting plugin ProceduralMeshComponent
LogPluginManager: Mounting plugin AudioCapture
LogPluginManager: Mounting plugin OculusVR
LogPluginManager: Mounting plugin IOSDeviceProfileSelector
LogPluginManager: Mounting plugin GoogleCloudMessaging
LogPluginManager: Mounting plugin Firebase
LogPluginManager: Mounting plugin AppleMoviePlayer
LogPluginManager: Mounting plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting plugin AndroidMoviePlayer
LogPluginManager: Mounting plugin EditableMesh
LogPluginManager: Mounting plugin LocationServicesBPLibrary
LogPluginManager: Mounting plugin AndroidPermission
LogPluginManager: Mounting plugin RuntimePhysXCooking
LogPluginManager: Mounting plugin MobilePatchingUtils
LogPluginManager: Mounting plugin ArchVisCharacter
LogPluginManager: Mounting plugin AndroidDeviceProfileSelector
LogPluginManager: Mounting plugin CustomMeshComponent
LogPluginManager: Mounting plugin WindowsMoviePlayer
LogPluginManager: Mounting plugin LevelSequenceEditor
LogPluginManager: Mounting plugin ActorSequence
LogPluginManager: Mounting plugin MatineeToLevelSequence
LogPluginManager: Mounting plugin VariantManagerContent
LogPluginManager: Mounting plugin DatasmithContent
LogPluginManager: Mounting plugin NUTUnrealEngine4
LogPluginManager: Mounting plugin NetcodeUnitTest
LogPluginManager: Mounting plugin LauncherChunkInstaller
LogPluginManager: Mounting plugin OnlineSubsystem
LogPluginManager: Mounting plugin OnlineSubsystemIOS
LogPluginManager: Mounting plugin OnlineSubsystemUtils
LogPluginManager: Mounting plugin OnlineSubsystemGooglePlay
LogPluginManager: Mounting plugin OnlineSubsystemNull
LogPluginManager: Mounting plugin AppleVision
LogPluginManager: Mounting plugin HTML5Networking
LogPluginManager: Mounting plugin BackChannel
LogPluginManager: Mounting plugin GeometryCache
LogPluginManager: Mounting plugin AlembicImporter
LogPluginManager: Mounting plugin CharacterAI
LogPluginManager: Mounting plugin AppleImageUtils
LogPluginManager: Mounting plugin ProxyLODPlugin
LogPluginManager: Mounting plugin DataValidation
LogPluginManager: Mounting plugin PluginBrowser
LogPluginManager: Mounting plugin MobileLauncherProfileWizard
LogPluginManager: Mounting plugin SpeedTreeImporter
LogPluginManager: Mounting plugin FacialAnimation
LogPluginManager: Mounting plugin GameplayTagsEditor
LogPluginManager: Mounting plugin CryptoKeys
LogPluginManager: Mounting plugin MacGraphicsSwitching
LogPluginManager: Mounting plugin AssetManagerEditor
LogPluginManager: Mounting plugin MeshEditor
LogPluginManager: Mounting plugin AvfMedia
LogPluginManager: Mounting plugin MediaCompositing
LogPluginManager: Mounting plugin WebMMedia
LogPluginManager: Mounting plugin MediaPlayerEditor
LogPluginManager: Mounting plugin LinearTimecode
LogPluginManager: Mounting plugin ImgMedia
LogPluginManager: Mounting plugin WmfMedia
LogPluginManager: Mounting plugin AndroidMedia
LogPluginManager: Mounting plugin AISupport
LogPluginManager: Mounting plugin MagicLeapMedia
LogPluginManager: Mounting plugin MagicLeap
LogStreaming: Display: Took  0.399s to configure plugins.
LogModuleManager: Warning: ModuleManager: Unable to load module 'SteamVR'  - 0 instances of that module name found.
LogInit: Initializing SDL.
LogInit: Initialized SDL 2.0.8 revision: 11184 (hg-12121:4358e537000a with EpicExtensions) (compiled against 2.0.8)
LogInit: Using SDL video driver 'offscreen'
LogInit: Display metrics:
LogInit:   PrimaryDisplayWidth: 1024
LogInit:   PrimaryDisplayHeight: 768
LogInit:   PrimaryDisplayWorkAreaRect:
LogInit:     Left=0, Top=0, Right=1024, Bottom=768
LogInit:   VirtualDisplayRect:
LogInit:     Left=0, Top=0, Right=1024, Bottom=768
LogInit:   TitleSafePaddingSize: X=0.000 Y=0.000 Z=0.000 W=0.000
LogInit:   ActionSafePaddingSize: X=0.000 Y=0.000 Z=0.000 W=0.000
LogInit:   Number of monitors: 1
LogInit:     Monitor 0
LogInit:       Name: 0
LogInit:       ID: display0
LogInit:       NativeWidth: 1024
LogInit:       NativeHeight: 768
LogInit:       bIsPrimary: true
LogLinux: Warning: MessageBox: Plugin 'SteamVR' failed to load because module 'SteamVR' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.: Message: 
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module LinuxDeviceProfileSelector (36)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (34)
LogModuleManager: Shutting down and abandoning module PropertyEditor (33)
LogModuleManager: Shutting down and abandoning module AudioEditor (30)
LogModuleManager: Shutting down and abandoning module TextureCompressor (28)
LogModuleManager: Shutting down and abandoning module ShaderCore (26)
LogModuleManager: Shutting down and abandoning module Landscape (24)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (22)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (20)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (18)
LogModuleManager: Shutting down and abandoning module Renderer (16)
LogModuleManager: Shutting down and abandoning module Engine (14)
LogModuleManager: Shutting down and abandoning module CoreUObject (12)
LogModuleManager: Shutting down and abandoning module NetworkFile (10)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (8)
LogModuleManager: Shutting down and abandoning module StreamingFile (6)
LogModuleManager: Shutting down and abandoning module SandboxFile (4)
LogModuleManager: Shutting down and abandoning module PakFile (2)
LogExit: Exiting.
LogInit: Tearing down SDL.
Exiting abnormally (error code: 1)

**Comment by nsubiron** [comment]
Hi @rguptatx,

The command you're using is for opening the Unreal Editor, it does not accept Carla arguments.

And btw, `-carla-server` was removed in 0.9.0, Carla is always in "server mode" now.

**Comment by rguptatx** [comment]
Thank you!
________________________________
