### ISSUE TITLE
autopilot not working in 0.9.2

### ISSUE THREAD

**Issue by rguptatx** [carla-simulator/carla#1193]
I am running carla on ubuntu 16.04. I compiled default version of carla and connect to it using automatic_control.py using Town3. The car turns to the right in the next 5 meters and crashes consistently everytime I run the python script.

**Comment by lijecaru** [comment]
Did the script automatic_control.py worked out of the box? My script doesn't run, I'm using ubuntu 16.04 and Carla 0.9.3

**Comment by xksteven** [comment]
I needed to apply this fix:
https://github.com/carla-simulator/carla/pull/1236

One line change to the file PythonAPI/agents/navigation/global_route_planner.py and then automatic_control.py works for me.

Ubuntu 16.04 
Carla 0.9.3

**Comment by 77hanzzi** [comment]
Same question. This script worked successfully in Town1 and Town2, but when it comes to Town3, this script always fails. Does anyone come out the possible solution?

**Comment by Lebron-Huang** [comment]
> Same question. This script worked successfully in Town1 and Town2, but when it comes to Town3, this script always fails. Does anyone come out the possible solution?

Can you tell me how to run in town 1 and town 2？thank you
