### ISSUE TITLE
ROS integration

### ISSUE THREAD

**Issue by jokla** [carla-simulator/carla#12]
Hi!

Is there any plan of integrating Carla with ROS?
In specific this would allow us to retrieve the state information, sensor data and to send control command to the car.

Probably the easiest way would be to write a ROS node that uses the CARLA client API in python? 

Thanks!

**Comment by tlind** [comment]
+1

**Comment by fabianoboril** [comment]
+1

**Comment by dosovits** [comment]
We would like to integrate CARLA with ROS at one point, but this may take some time due to our limited resources. 

But we are very happy to accept contributed code, if anyone is willing to implement it. For instance, @WenchaoDing in #26 mentioned he is doing something in this direction.

**Comment by WenchaoDing** [comment]
My original repo is moved to private since I am developing some work which is buggy and not relevant to this topic. Instead, I post this gist [https://gist.github.com/WenchaoDing/8bdf2b6753f0cc6cb1c4019529a79c9f](url) which may be a little bit helpful for beginners. Hope someone can post more elegant solutions. :)

**Comment by igilitschenski** [comment]
I was also interested in using Carla with ROS. Started catkinizing the binary distribution. A first go at it can be found at https://github.com/mit-drl/carla_binary_catkin. So far, this does not install the python module (will still look into this).

**Comment by laurent-george** [comment]
I have also done a simple ros_bridge for carla, you can test it here:  [dev/add_ros_bridge](https://github.com/laurent-george/carla/tree/dev/add_ros_bridge/carla_ros_bridge)

**Comment by germanros1987** [comment]
Almost merged at #301
