### ISSUE TITLE
unknown vehicle getting automatically spawned in the world

### ISSUE THREAD

**Issue by krdindorkar19** [carla-simulator/carla#1206]
Hi,
1. This is what I first did to remove all actors from the world : 
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import carla
>>> carla_client = carla.Client('10.51.6.192', 2006)
>>> carla_world= carla_client.get_world()
>>> actor_list = carla_world.get_actors().filter('vehicle.*')
>>> print(actor_list)
[]

2. Through a script I spawned a vehicle in the world : 
Selected Actor :  vehicle.audi.a2
number_of_wheels : ActorAttribute(id=number_of_wheels,type=int,value=4(const))
object_type : ActorAttribute(id=object_type,type=str,value=(const))
color : ActorAttribute(id=color,type=Color,value=Color(224,0,0,255))
role_name : ActorAttribute(id=role_name,type=str,value=hero)
Selected Location : 
Location(x=237.7, y=129.75, z=39.4306)
Actor List =
[Actor(id=86, type=vehicle.gazelle.omafiets), Actor(id=87, type=vehicle.audi.a2)]

This happened many times, I am not getting from where the second vehicle (Actor(id=86, type=vehicle.gazelle.omafiets)) is coming into the world.

**Comment by Sakrust** [comment]
Could you provide your code?
