### ISSUE TITLE
How to lauch UE4 in Ubuntu?

### ISSUE THREAD

**Issue by HeYDwane3** [carla-simulator/carla#1213]
I am running carla 0.9.3 on Ubuntu 18.04.

What I am going to do is imported the map I created with RoadRunner, but the problem I got is I have no idea how to lauch the UE4.

Below are instructions I found on https://carla.readthedocs.io/en/latest/how_to_make_a_new_map/

**Importing into Unreal:
Start dragging your file from where it is saved to the "content browser" in your unreal's project as you would do with any other asset.
In the Import window make sure the following options are unchecked: ForcefrontXAxis, Autogenerate collission, combine meshes.
Make sure that ConvertSceneUnit is checked.
You should Also check "Import Materials" and "Import Textures" if you want to use RoadRunner materials or use the method described at the end of the next step to change them in batches.**

With the instructions above, I guess the first step I have to do is lauch the UE4.

I tried to lauch the UE4 with the instruction I found on 
https://docs.unrealengine.com/en-us/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow

which is lauch the UE4 by 

**Navigate to the editor's binary path by entering cd Engine/Binaries/Linux/ into the terminal.
Run UE4Editor to launch the editor.** 

However, while doing as the instructions above, I got an err msg, saying

**Plugin 'steamVR' failed to load because module 'steamVR' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.**

I have no idea how to disable this if I cannot open the editor

I stuck here, can anyone help me?

**Comment by Sakrust** [comment]
Open your .uproject file with Notepad or any other text file editor. The uproject file is human readable. You should look for a Plugin description part and there you can set the enabled flag to false.

**Comment by HeYDwane3** [comment]
> Open your .uproject file with Notepad or any other text file editor. The uproject file is human readable. You should look for a Plugin description part and there you can set the enabled flag to false.

Thanks for the reply, but where is the .uproject file? I can find the project file in many positions
first, I can find in /CARLA_0.9.3/CarlaUE4
second, I can find in UnrealEngine_4.21/carla/Unreal/CarlaUE4

which one should I choose?

And one more question, I opened both. all the plugin option for SteamVR is false. I am wondering why would I get this error while in both project files, the corresponding option are false?

thanks

**Comment by nsubiron** [comment]
Hi @HeYDwane3,

Have you followed the documentation on [How to build on Linux](https://carla.readthedocs.io/en/latest/how_to_build_on_linux/)? Once you have the environment ready the easiest way to launch the project with the UE4 editor is by running
```
$ make launch
```

**Comment by AdriannaGmz** [comment]
> e you followed the documentation on [How to build on Linux](https://carla.readthedocs.io/en/latest/how_to_build_on_linux/)? Once you have the environment ready the easiest way to launch the project with the UE4 editor is by running
> 
> ```
> $ make launch
> ```

once this is built, how to open the editor every time we want without running the full "make launch" all over again? 
I keep trying to open the editor and it only opens when I execute  'make  launch'. After the binaries are compiled, if I want to open the editor again, it doesnt open it

**Comment by Sakrust** [comment]
Open the .uproject file.

**Comment by nsubiron** [comment]
There is also a `make launch-only` that just launches the editor without doing any check.
