### ISSUE TITLE
Text Messages on Carla Screen

### ISSUE THREAD

**Issue by martisaju** [carla-simulator/carla#1215]
Hello, 

I would like to print some messages on the CarlaUE4 main screen. Is it possible to infer text to the screen avoiding to install Carla from source and using the Python API? 
I am using Carla 0.8.2 version on Windows 10 and launching the 'manual_control.py' file. I have followed the installation instructions detailed at the Getting started post.

Thank you so much

**Comment by Sakrust** [comment]
I guess thats impossible, you can either use 0.9.1+ where debug functions are included in the API, so you can directly print stuff in the simulator view. Or build Carla from source and include those functions by yourself.
