### ISSUE TITLE
Carla 0.9.2 : Information of sensor parent is giving as None

### ISSUE THREAD

**Issue by krdindorkar19** [carla-simulator/carla#1221]
Hi,
I have written a script similar to manual_control.py in which I have attached Lidar,Camera and Collision sensors to vehicle.
Now I want to listen the data collected from these sensors from another client attached to the same server.

I have created Client_2 where I have retrieved the "Hero" vehicle (spawned in manual_control.py) and I got sensors list through get_actors(). However when I try to find parent of those sensors, It is giving me parent as None.

Kindly help me to listen these sensors data from client_2.

**Comment by nsubiron** [comment]
Let's continue on #1225 as it seems the same problem.
