### ISSUE TITLE
How to change towns in Carla 0.9.3

### ISSUE THREAD

**Issue by imran514** [carla-simulator/carla#1222]
I have downloaded Linux compiled version of Carla 0.9.3, and i explore new towns that are added in this new version

**Comment by Sakrust** [comment]
Use /Game/Carla/Maps/<MapName> as an argument when launching your carla binaries.

**Comment by dixantmittal** [comment]
Hi @imran514, As you have downloaded Linux compiled version, simply run the command `$ ./CarlaUE4.sh TownXX`. I noticed that now you don't need to add prefix /Game/Carla/Maps/TownXX to load TownXX.

**Comment by stevendae** [comment]
How do I change towns in the editor?

**Comment by Sakrust** [comment]
Navigate to Carla/Maps and double click on the map you wish to load.

**Comment by kimiya66** [comment]
> Hi @imran514, As you have downloaded Linux compiled version, simply run the command `$ ./CarlaUE4.sh TownXX`. I noticed that now you don't need to add prefix /Game/Carla/Maps/TownXX to load TownXX.

Thank you :)

**Comment by Miknow78** [comment]
Anyone knows how to set a map as default when open the simulator?
