### ISSUE TITLE
How to import maps from another UE4 project

### ISSUE THREAD

**Issue by mango009** [carla-simulator/carla#1226]
Sorry I'm not familiar with UE4 so this question might sound too trivial for some. How do I import the map that is already made as a UE4 project into Carla?

Thanks for any help

**Comment by dnovillo-CVC** [comment]
The best route you can follow to move assets between projects is the "Migrate" option for assets. It will move the map and all the dependencies between projects. 

Source: https://tinyurl.com/yxdsp3by

Cheers.
