### ISSUE TITLE
Carla 0.9.2 : Vehicle control according to sensor data

### ISSUE THREAD

**Issue by krdindorkar19** [carla-simulator/carla#1234]
1. Is there is any API to get the distance of vehicle traveled from it's spwan point?
 2. I am Trying to create a closed loop system using CARLA, like CARLA sensors are collecting data     and based on that AD model is giving some control parameters to vehicle control class and apply it over vehicle.
            a. I am running manual_control.py as client 1, and the script which I have
                attached(sensor_listener.py) as client 2. 
            b. I am not getting appropriate distance, after certain point it is giving constant distance
            c.  And listen calls every time hence control commands not completing

Kindly help me with this !
[sensor_listener.txt](https://github.com/carla-simulator/carla/files/2850811/sensor_listener.txt)

**Comment by YashBansod** [comment]
@krdindorkar19 You can do this using the `self.world.on_tick(callback_function)` in the **World** Class.
Essentially, you just poll for the vehicle location, compute euclidean distance travelled since the previous location and maintain a sum of the eu_dist traversed.

**Comment by krdindorkar19** [comment]
@YashBansod 
World class is in my 1st client (manual_control.py), I want to access sensor's(sensors which are spawned in client 1) data from client 2. So I need callback function to be called from client 2.
For distance I have used euclidean distance formula : 
>def get_distance_traveled(self):
>>	        '''
>>		this function returns distance vehicle traveled from starting point
>>		'''
>>		current_pos=self.ego_vehicle.get_location()
>>		distance = math.sqrt((current_pos.x-self.ego_vehicle_location.x)**2
>>						+(current_pos.y-self.ego_vehicle_location.y)**2
>>						+(current_pos.z-self.ego_vehicle_location.z)**2)
>>		return distance

**Comment by krdindorkar19** [comment]
Thank you !
