### ISSUE TITLE
[Synchronous mode] Pause and Resume state of world

### ISSUE THREAD

**Issue by krdindorkar19** [carla-simulator/carla#1244]
Hi,
How to implement Pause and Resume mechanism on world.on_tick() with CARLA 0.9.2
Pause : Freezing current state of vehicle,world 
Resume : Vehicle,world will start from its previous freezed state

This required to synchronize between 2 carla clients (To give data to model and taking back the control)
- - -
Child of #630.
Requires #1258.

**Comment by nsubiron** [comment]
We plan to add this functionality in 0.9.4 by the end of February.

**Comment by nsubiron** [comment]
Since there wasn't an issue tracking this I'm reusing this one :wink:
