### ISSUE TITLE
Synchronous Mode Between Server and Client [Carla 0.9.3]

### ISSUE THREAD

**Issue by Samir55** [carla-simulator/carla#1249]
Hello Authors,

I want to apply synchronous mode between the client and server where the server should wait for the client. In this issue #815, some messages are dismissed in case of a slow connection. 

I have trained a model on collected data on Carla V.0.9.3, but upon testing the model, the car seemed to crash. But when I tested on Carla V 0.8.4 on the same model it worked fine.

Also. when I tested on Carla V 0.9.3 but changed the fps from 10 to 30 or higher fps, The car seems to move more smoothly. Is the problem because of the difference in the fps of the client and the server (i.e both are not synchronized)?

**Comment by sheelabhadra** [comment]
Hi @Samir55, I am encountering the same issue. I have a model trained using Carla 0.8.2 but the agent crashes when I run it on Carla 0.9.6. Were you able to find a solution to the issue?
