### ISSUE TITLE
Confused about OpenDrive？

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla#1252]
Hello，everyone！
Carla 0.9.x introduce concept of OpenDrive,I don't know what it is used in Carla.There is no official example of how to use it.Can you help me understand it and explain how to use it?

**Comment by marcgpuig** [comment]
[OpenDrive](http://opendrive.org/) is a [standard](http://opendrive.org/docs/OpenDRIVEFormatSpecRev1.4H.pdf) that geometrically defines the road and its relations. We are using it to generate the autopilot network and simulate traffic in the maps. You can use it (for instance) to know how far is your agent from the center of the lane.
