### ISSUE TITLE
Carla 0.9.3 - Traffic light state is buggy and inconsistent 

### ISSUE THREAD

**Issue by mallela** [carla-simulator/carla#1259]
Hi, I'm using Carla 0.9.3 on a Ubuntu 16.04 machine.

I am trying to obtain the traffic light info in for each time stamp. I have noticed the following issues with it
1. get_traffic_light_state() is Green although there is no signal ahead
2. get_traffic_light_state() changes abruptly at the stopline if signal is Red. So does is_at_traffic_light().
3. get_traffic_light() does not always return the traffic light actor ID. I thought I recognized a pattern where it return the actor ID when  get_traffic_light_state() is Red, except that is not the case always.

Obtaining the traffic light state is such a useful feature! But there seems to be a bug here.

Thanks,
Praneeta

**Comment by overlapjho** [comment]
I experience this every time without modification on original script 

In the image the vehicle detects the traffic light far ahead and respond into it. the `_proximity_threshold` is set to 10 which is the default
![tflight](https://user-images.githubusercontent.com/26637741/52912757-c6c74a00-32f0-11e9-9a60-6b757eb284c2.png)

**Comment by mallela** [comment]
Hi @overlapjho,
I'm sorry, I didn't understand completely. Is there a parameter `_proximity_threshold` that I can set somewhere? If yes, where can I find it?

**Comment by overlapjho** [comment]
@mallela  ya, `_proximity_threshold` is found at `roaming_agent.py` at line 24

**Comment by kargarisaac** [comment]
@mallela @jmarrr 
I have the same problem. When I pass an intersection, the "is_at_traffic_light()" remains active and traffic_light.get_state() remains red. Do you have any solution?
