### ISSUE TITLE
Carla Lidar saving issue

### ISSUE THREAD

**Issue by mo-zahran** [carla-simulator/carla#1260]
I am trying to save Lidar data using the method `save_to_disk` in the `automatic_control.py` but I think that the lidar is saved **upside down**. I am using MeshLab to visualize the lidar.

![ezgif com-optimize](https://user-images.githubusercontent.com/15180702/52922164-a49cee80-3327-11e9-814d-5d97dc2243e8.gif)

**Comment by nsubiron** [comment]
I also noticed this, this has always been like this with our Lidar. I always wondered if this is a bug or a problem with the default axis visualization in meshlab.

**Comment by tatttto** [comment]
Hi, @moh3th1 

Could you please show how to use `save_to_disk` function in the python script to save raw data for Lidar sensor? I tried this line:
`lidar.listen(lambda image: image.save_to_disk('_lidarout'))`

but it came out with this warning:

>  sensor object went out of the scope but the sensor is still alive in the simulation.

**Comment by luigui2906** [comment]
To save lidar point clouds you have to use this:

`self.sensor.listen(lambda LidarMeasurement: LidarMeasurement.save_to_disk('_out/%06d.ply' % LidarMeasurement.frame_number))`

**Comment by visakhchikku** [comment]
Is it possible to save lidar data as .pcap file using carla?
