### ISSUE TITLE
How can I get fuel consumption in CARLA

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/carla#1267]
Dear CARLA team, thank for doing great work.

Is there any mechanism to compute the fuel consumption for the car in CARLA? If not, is there any possibility to change the Unreal Editor to compute the fuel consumption? Is there any idea for that?

**Comment by AliBaheri** [comment]
Any idea for this tread?

**Comment by kchunter** [comment]
I'm also interested in that.

**Comment by qhaas** [comment]
This would be useful for our efforts as well.

**Comment by Aim-ez** [comment]
Has anyone found a way to implement this in CARLA, or with a CARLA-SUMO co-sim? This is a large part of what I was hoping to use CARLA for.

**Comment by SExpert12** [comment]
any updates regarding the fuel consumption in carla simulator. I am also interested in that.


Thanks
