### ISSUE TITLE
How to disable the `carla.World.on_tick(callback)` method.

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#1273]
I added a `world.on_tick(callback_function)` to the world. The function implements some routines relating to the player agent of the world. However, when I do world.restart(), the player agent and the sensors attached are destroyed. However, the simulator still tries to process the callback_function every tick.
I was wondering if there was a way to disable a `world.on_tick(callback_function)` routine to solve this problem.
For now, I implemented a return procedure at the start of the callback_function if the player is not alive. But it would be much better if the disable routine was provided.

**Comment by nsubiron** [comment]
Nope, currently there is no way of clearing "on_tick" callbacks. I'll add it now that I'm working in that part of the code.
