### ISSUE TITLE
Inconsistency between Carla maps and OpenDrive map [v0.9.2]

### ISSUE THREAD

**Issue by alex5528** [carla-simulator/carla#1276]
I pay attention that roads which have "parking" lanes didn't handled well after saving to the `OpenDrive` format.

In this example (`Town03 junction 92`) road 24 has 4 lanes, 2 of them marked as "parking" in `OpenDrive` (most right one: `lane -2` and most left one: `lane 2`) and those "parking" lanes have no connections to other roads in `OpendDrive`. When in Carla editor those "parking" lanes connected to other roads. 

I use roads/junction/etc ids from `OpenDrive` file.

Is it implementation issues or I missed something?

![junction 92](https://user-images.githubusercontent.com/14922061/53087096-ab358c80-3506-11e9-8db3-f34a4a887734.jpg)

Here is a junction 92 connection, road 24 doesn't have connections for lanes -2 and 2.

    <junction id="92" name="">
        <connection id="0" incomingRoad="24" connectingRoad="93" contactPoint="start">
            <laneLink from="-1" to="-1"/>
        </connection>
        <connection id="1" incomingRoad="81" connectingRoad="94" contactPoint="end">
            <laneLink from="1" to="1"/>
        </connection>
        <connection id="2" incomingRoad="31" connectingRoad="95" contactPoint="end">
            <laneLink from="-2" to="1"/>
        </connection>
        <connection id="3" incomingRoad="24" connectingRoad="96" contactPoint="start">
            <laneLink from="-1" to="-1"/>
        </connection>
        <connection id="4" incomingRoad="32" connectingRoad="97" contactPoint="end">
            <laneLink from="4" to="4"/>
        </connection>
        <connection id="5" incomingRoad="24" connectingRoad="98" contactPoint="start">
            <laneLink from="-1" to="-1"/>
        </connection>
        <connection id="6" incomingRoad="31" connectingRoad="99" contactPoint="end">
            <laneLink from="-1" to="1"/>
        </connection>
        <connection id="7" incomingRoad="81" connectingRoad="100" contactPoint="start">
            <laneLink from="1" to="-1"/>
        </connection>
        <connection id="8" incomingRoad="32" connectingRoad="101" contactPoint="start">
            <laneLink from="5" to="-1"/>
        </connection>
        <connection id="9" incomingRoad="81" connectingRoad="102" contactPoint="start">
            <laneLink from="1" to="-1"/>
        </connection>
        <connection id="10" incomingRoad="32" connectingRoad="103" contactPoint="end">
            <laneLink from="5" to="5"/>
            <laneLink from="4" to="4"/>
        </connection>
        <connection id="11" incomingRoad="31" connectingRoad="104" contactPoint="start">
            <laneLink from="-1" to="-1"/>
            <laneLink from="-2" to="-2"/>
        </connection>
    </junction>

**Comment by marcgpuig** [comment]
Hi @alex5528.
This is a known issue and the artist team is trying to solve this time by time. The new maps are better generated, so please, try to use them for now. Sorry for the inconvenience.
