### ISSUE TITLE
Prediction of Obstacles

### ISSUE THREAD

**Issue by kk2491** [carla-simulator/carla#1277]
Hi Guy,

Anybody has tried predicting the future trajectories of the obstacles. 

For example : Using a traditional prediction algorithms to predict the trajectories.

Thank you,
KK

**Comment by YashBansod** [comment]
@kk2491 I guess you can use a constant acceleration and constant turn model kalman filter for this. I have never tried doing that though.

Using RNNs like in Waymo's ChauffeurNet would be an overkill solution. :penguin:

**Comment by kk2491** [comment]
@YashBansod Thanks for the information. I will check if I can implement any of the above on to Carla.

Thank you,
KK
