### ISSUE TITLE
Always showing "no CMake"， when running setup.bat

### ISSUE THREAD

**Issue by chase03** [carla-simulator/carla#1280]
Some guys help me out。 I have installed all the necessary software and added it to the Windows 10 "Path" 

![no cmake](https://user-images.githubusercontent.com/26050994/53142423-c10e8480-35ce-11e9-9ff1-cb8378324d38.jpg)

**Comment by marcgpuig** [comment]
`not a git repository`
Do you have permissions to download from GitHub?
