### ISSUE TITLE
RGB Camera in low quality mode (Carla 0.9.3)

### ISSUE THREAD

**Issue by nonsingularmatrix** [carla-simulator/carla#1291]
Hi, 
is there any way to use RGB-cameras when simulating in "low" quality mode?
Saved images of a camera only contain useful content when I'm using "epic" mode.

Thanks,
nonsingularmatrix

**Comment by jagdishbhanushali** [comment]
I also saw this issue. When running simulator in low quality, camera saves garbage values whereas while running on epic mode, it save images perfectly fine with lots of lag.

**Comment by germanros1987** [comment]
Hi, Could you be more specific? What do you mean by "useful" content?

**Comment by nonsingularmatrix** [comment]
@germanros1987 
When I run the simulation in "low" quality mode, the saved image is not nearly similar to the one you receive when running in "epic" mode. As far as I remember, the image was just white or black.

**Comment by germanros1987** [comment]
Please, report the code you are using for this experiment. Something that can reproduce the problem.
