### ISSUE TITLE
No Shadow in Client (Carla 0.9.3)?

### ISSUE THREAD

**Issue by heshameraqi** [carla-simulator/carla#1292]
I know CARLA graphics are decent, I might be doing something wrong. I'm running CARLA 0.9.3 with "-quality-level=EPIC", and in the client window I can't see any vehicles shadows, and the graphics quality seems not good as in the image below.
For the client, I create a `pygame.display` and `blit(_surface)` to it, where `_surface` set via `pygame.surfarray.make_surface` with a `carla.ColorConverter.Raw` of `sensor.camera.rgb` sensor.

![image](https://user-images.githubusercontent.com/15854399/53301427-7fded480-385b-11e9-8aed-d0fce385d7bd.png)

**Comment by heshameraqi** [comment]
This does not happen anymore with CARLA recent 0.9.4 version. It should be closed.

**Comment by soulslicer** [comment]
How did you fix this? I was messing around with some settings, and even with EPIC, it still lacks shadows. It was working before this

**Comment by Jack-Pinnington** [comment]
Hello, I'm running on 0.9.6 and my Carla installation doesn't seem to have any shadows! What is the fix for this behaviour? ![carla_no_shadows](https://user-images.githubusercontent.com/57767279/74664350-74d03300-5195-11ea-95b8-61107ab6b73e.png)

**Comment by Jack-Pinnington** [comment]
Hello,

I applied the fix here:
https://github.com/carla-simulator/carla/issues/2019

And my shadows have returned.

Thanks,
Jack
