### ISSUE TITLE
Collisions are not annotated when vehicle's speed is low

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#13]
Currently there is a hard-coded limit of 1 km/h to avoid annotating unwanted collisions from other agents when the player is not moving (due to #7 mostly).

However, it seems to miss collisions when the car moves slightly faster too, around 5 km/h. This should be fixed because at 5 km/h the car is definitively moving.

**Comment by germanros1987** [comment]
Is this bug still around?
