### ISSUE TITLE
Relative Speed

### ISSUE THREAD

**Issue by ADulian** [carla-simulator/carla#1302]
Quick question, anyone got an idea how to calculate the relative speed between Vehicle1 & Vehicle2? Of course taking into consideration that both vehicle might be going in the same/opposite directions.

Cheers,

**Comment by YashBansod** [comment]
The velocity of any vehicle in the simulator is reported inertial coordinates. So, since the coordinates of the vehicles are in the same frame, the relative values are just the difference between them.
