### ISSUE TITLE
Does Carla have any requirements for GPU?

### ISSUE THREAD

**Issue by ChrisHRZ** [carla-simulator/carla#1305]
I install Carla in my laptop. But it's very choppy my GPU is NVDIA GeForce 840M. Is this GPU doesn't meet requirment?

**Comment by marcgpuig** [comment]
Yup, Carla needs really good hardware :(

**Comment by anna-srl** [comment]
Hi,

I'm trying to run Carla on windows 10 and the GPU doesn't meet the requirements. 

So, I was thinking of using a graphics card for my desktop, does anyone have any recommendations?

Many thanks in advance!
