### ISSUE TITLE
What units are measurements in client given in?

### ISSUE THREAD

**Issue by Sanjay-Ganeshan** [carla-simulator/carla#132]
This doesn't seem to be documented anywhere - what units are the acceleration, position, etc, given in when you access player_measurements in the client?

**Comment by nsubiron** [comment]
You are right, it isn't documented and it's currently a bit of a mess.
```
locations     cm
speed         km/h
acceleration  (km/h)/s
collisions    kg*cm/s
```

I'm setting this issue as "feature request" to document (and verify this units) and possibly change them to something more reasonable. I reckon it would be better to use everywhere SI units.

**Comment by Sanjay-Ganeshan** [comment]
Thank you!
