### ISSUE TITLE
Is there a way to capture throttle, brake and steer information for autopilot mode?

### ISSUE THREAD

**Issue by Anand-Solanki** [carla-simulator/carla#1324]

**Comment by germanros1987** [comment]
Hi,

Yes, each carla.Vehicle reports that information in the method get_control() . I hope this helps

**Comment by Anand-Solanki** [comment]
get_control() is not available from carla.Vehicle in V8.4, instead I found these to be working:

control = measurements.player_measurements.autopilot_control
print(control.steer, control.throttle, control.brake, control.hand_brake)

Thanks!

**Comment by germanros1987** [comment]
I was assuming you are using the latest version of CARLA. Indeed, the right way to do that in the old versions is as you describe.
