### ISSUE TITLE
Addition of RADAR to simulator.

### ISSUE THREAD

**Issue by pparmesh** [carla-simulator/carla#1331]
I am working on a project that requires fusion of RADAR and camera data. Since there is no RADAR in Carla I am currently thinking of extracting ground truth of all NPC vehicles within a FOV and adding some sort of noise to the data to mimic RADAR output.
Is it likely that RADAR will be added to the simulation environment in the near future ?

**Comment by Sakrust** [comment]
Roadmap: https://github.com/carla-simulator/carla/blob/master/Docs/img/carla_timeline.png

**Comment by ivannson** [comment]
@pparmesh Were you able to find a way to get RADAR output from Uneal?

**Comment by pparmesh** [comment]
I tried to model one by getting ground truth data of vehicles within a certain field of view and then added noise on top of it.

**Comment by dnychennnn** [comment]
@pparmesh Hey, would you like to share some thoughts on the noise modeling?
