### ISSUE TITLE
[0.9.4] program crashed when building routes using .xodr

### ISSUE THREAD

**Issue by hdy117** [carla-simulator/carla#1335]
I have created an new level name "Roundabout8Course", and I download the xodr  file from the link below. 

http://www.opendrive.org/tools/Roundabout8Course.zip

when I try to build routes using OpenDriveActor, I got errors.
Is it becasue "spiral" curve or something else?

[2019.03.04-07.32.30:077][374]LogFileHelpers: Loading map 'Roundabout8Course' took 0.139
[2019.03.04-07.32.36:051][946]LogCarla: FOpenDrive: Corrected map name from Roundabout8Course to Roundabout8Course
[2019.03.04-07.32.36:051][946]LogCarla: Loading OpenDrive file '../../../../HAD/Simulator/platform/carla-0.9.4/Unreal/CarlaUE4/Content/Carla/Maps/OpenDrive/Roundabout8Course.xodr'
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=68112 LargeMemoryPoolOffset=199248 
Malloc Size=145512 LargeMemoryPoolOffset=344776 
Realloc PtrSize=68112 NewSize=145512 PooledPtr=0x00007f14f9870040
Malloc Size=636160 LargeMemoryPoolOffset=980960 
[2019.03.04-07.32.36:082][946]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000010

[2019.03.04-07.32.36:082][946]LogCore: Fatal error!

0x00007f14a6495b19 libUE4Editor-Carla.so!carla::road::element::Waypoint::ComputeTransform() const(+0x2a9)
0x00007f14a62fdaea libUE4Editor-Carla.so!AOpenDriveActor::BuildRoutes(FString) [/home/hdy/HAD/Simulator/platform/carla-0.9.4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDriveActor.cpp:272]
0x00007f14a631316e libUE4Editor-Carla.so!AOpenDriveActor::BuildRoutes() [/home/hdy/HAD/Simulator/platform/carla-0.9.4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDriveActor.cpp:173]
0x00007f14a6312ab0 libUE4Editor-Carla.so!AOpenDriveActor::PostEditChangeProperty(FPropertyChangedEvent&) [/home/hdy/HAD/Simulator/platform/carla-0.9.4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDriveActor.cpp:125]
0x00007f151efac5d0 libUE4Editor-CoreUObject.so!UObject::PostEditChangeChainProperty(FPropertyChangedChainEvent&) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/CoreUObject/Private/UObject/Obj.cpp:445]
0x00007f150b2e1c57 libUE4Editor-PropertyEditor.so!FPropertyNode::NotifyPostChange(FPropertyChangedEvent&, FNotifyHook*) [/home/hdy/UnrealEngine_4.21/Engine/Source/Editor/PropertyEditor/Private/PropertyNode.cpp:2119]
0x00007f150b2e02a7 libUE4Editor-PropertyEditor.so!FPropertyValueImpl::ImportText(TArray<FObjectBaseAddress, FDefaultAllocator> const&, TArray<FString, FDefaultAllocator> const&, FPropertyNode*, unsigned int) [/home/hdy/UnrealEngine_4.21/Engine/Source/Editor/PropertyEditor/Private/PropertyHandleImpl.cpp:543]
0x00007f150b2de82b libUE4Editor-PropertyEditor.so!FPropertyValueImpl::ImportText(FString const&, FPropertyNode*, unsigned int) [/home/hdy/UnrealEngine_4.21/Engine/Source/Editor/PropertyEditor/Private/PropertyHandleImpl.cpp:333]
0x00007f150b2de29c libUE4Editor-PropertyEditor.so!FPropertyValueImpl::ImportText(FString const&, unsigned int) [/home/hdy/UnrealEngine_4.21/Engine/Source/Editor/PropertyEditor/Private/PropertyHandleImpl.cpp:242]
0x00007f150b2feb9d libUE4Editor-PropertyEditor.so!FPropertyHandleBool::SetValue(bool const&, unsigned int) [/home/hdy/UnrealEngine_4.21/Engine/Source/Editor/PropertyEditor/Private/PropertyHandleImpl.cpp:3432]
0x00007f150b405f0d libUE4Editor-PropertyEditor.so!SPropertyEditorBool::OnCheckStateChanged(ECheckBoxState) [/home/hdy/UnrealEngine_4.21/Engine/Source/Editor/PropertyEditor/Private/UserInterface/PropertyEditor/SPropertyEditorBool.cpp:79]
0x00007f150b499db2 libUE4Editor-PropertyEditor.so!TBaseSPMethodDelegateInstance<false, SPropertyEditorBool, (ESPMode)0, TTypeWrapper<void> (ECheckBoxState)>::Execute(ECheckBoxState) const [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Core/Public/Delegates/DelegateInstancesImpl.h:279]
0x00007f150b499e4c libUE4Editor-PropertyEditor.so!TBaseSPMethodDelegateInstance<false, SPropertyEditorBool, (ESPMode)0, void (ECheckBoxState)>::ExecuteIfSafe(ECheckBoxState) const [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Core/Public/Delegates/DelegateInstancesImpl.h:355]
0x00007f1518964241 libUE4Editor-Slate.so!SCheckBox::ToggleCheckedState() [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Slate/Private/Widgets/Input/SCheckBox.cpp:298]
0x00007f1518964bc7 libUE4Editor-Slate.so!SCheckBox::OnMouseButtonUp(FGeometry const&, FPointerEvent const&) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Slate/Private/Widgets/Input/SCheckBox.cpp:190]
0x00007f15187b3f4b libUE4Editor-Slate.so!FSlateApplication::RoutePointerUpEvent(FWidgetPath&, FPointerEvent&) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:5529]
0x00007f1518772a86 libUE4Editor-Slate.so!FSlateApplication::ProcessMouseButtonUpEvent(FPointerEvent&) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:6087]
0x00007f15187bae40 libUE4Editor-Slate.so!FSlateApplication::OnMouseUp(EMouseButtons::Type, FVector2D) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:6060]
0x00007f1519014c80 libUE4Editor-ApplicationCore.so!FLinuxApplication::ProcessDeferredMessage(SDL_Event) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/ApplicationCore/Private/Linux/LinuxApplication.cpp:378]
0x00007f15190145d7 libUE4Editor-ApplicationCore.so!FLinuxApplication::AddPendingEvent(SDL_Event) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/ApplicationCore/Private/Linux/LinuxApplication.cpp:196]
0x00007f151901431f libUE4Editor-ApplicationCore.so!FLinuxPlatformApplicationMisc::PumpMessages(bool) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/ApplicationCore/Private/Linux/LinuxPlatformApplicationMisc.cpp:407]
0x0000000000237703 UE4Editor!FEngineLoop::Tick() [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:3615]
0x0000000000240ad3 UE4Editor!GuardedMain(char16_t const*) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Launch/Private/Launch.cpp:176]
0x00007f15143dfeea libUE4Editor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*)) [/home/hdy/UnrealEngine_4.21/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:245]
0x00007f1513e2b830 libc.so.6!__libc_start_main(+0xef)
0x000000000022c029 UE4Editor!_start()

[2019.03.04-07.32.36:092][946]LogExit: Executing StaticShutdownAfterError

**Comment by marcgpuig** [comment]
Hi @hdy117 
Since RoadRunner doesn't generate spirals in the OpenDrive they generate, we don't support them right now.
