### ISSUE TITLE
about how to use the API

### ISSUE THREAD

**Issue by yoyobookie** [carla-simulator/carla#1336]
Ubuntu 18.04
carla 0.9.4

Hi, everyone, I had a stupid question to ask about how to use the API.  I heard of the idea of API, but I never used it before. So when looking at the tutorial on the website,  I am a little bit lost on the way. I just wondering where should I execute those command, like for example, the first command to set-up the client. Should I make .py source file, and put the scripts I want in the file, then compile and run execute that file, or just type those scripts in the terminal one by one and run in the real time?

**Comment by slowergmajor** [comment]
Hi, there.  I am also just beginning to study carla. My current version is 0.9.4. According to the video on Youtube, firstly, open the client and then open the server. According to the results of my side, this does not work. You need to open the server first, and then execute the python api with the command "python manual_control.py" in the PythonAPI folder.  hope to be helpful.
