### ISSUE TITLE
How to get the 3d corner coordinates and image coordinates of the created model?

### ISSUE THREAD

**Issue by backer777** [carla-simulator/carla#1339]
How to get the vertex coordinates and image coordinates of the created model
![image](https://user-images.githubusercontent.com/13561917/53776268-855dae00-3f30-11e9-8086-5d578ead5e04.png)
But now I want to get the corner data and name of the model (red points in the figure below) ,  how can I get, do you have any hints? Thank you.
![image](https://user-images.githubusercontent.com/13561917/53776293-94dcf700-3f30-11e9-8191-fcb1652e1379.png)

**Comment by Unlingius** [comment]
at least you can run make launch and put some test objects to points of interest and look what coordinates it will have. crude, but works i think.

**Comment by backer777** [comment]
@Unlingius 
So cool! I got it, Thanks!!

![去1](https://user-images.githubusercontent.com/13561917/55202239-946b0f80-5201-11e9-885e-417867e55d58.png)
