### ISSUE TITLE
Bounding Box for pedestrians

### ISSUE THREAD

**Issue by ChongYunPeng** [carla-simulator/carla#134]
Thanks for making such a useful simulator.

I was just wondering if it was possible to save the bounding box coordinates of objects (cars and pedestrians) along with the images from the -dumpmovie command?

**Comment by nsubiron** [comment]
Hi @ChongYunPeng. No, the `-dumpmovie` command is an Unreal feature and only saves screenshots of the main server window.

To save images and measurements (as the pedestrians' bounding boxes) use the Python client. Please check the documentation on [How to run CARLA](http://carla.readthedocs.io/en/latest/how_to_run/) and take a look at the examples provided [client_example.py](https://github.com/carla-simulator/carla/blob/master/PythonClient/client_example.py).
