### ISSUE TITLE
Client set_velocity()/set_angular_velocity() don't respect physics

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/carla#1342]
I would expect, that these calls, added with #1126, respect physics:

- set_velocity()
- set_angular_velocity()

But they don't. Instead I was able to let vehicles fly or let them rotate on the spot.

These commands are highly interesting for ROS-based AD stacks.

Tested in Carla 0.9.4 on ubuntu 16.04.

**Comment by nsubiron** [comment]
These methods work as they were meant to work, they change instantly the (angular) velocity of an actor. Just as set_transform teleports the actor. These are instructions that go directly to the physics engine, generic for every actor, not only vehicles.

I guess what you were expecting is some agent that given a desired velocity, adjusts throttle/brake to match that velocity? That's significantly more difficult to implement, and unfortunately we don't have it yet.
