### ISSUE TITLE
lane detection ground truth

### ISSUE THREAD

**Issue by Atlunch** [carla-simulator/carla#1352]
Hello everyone,

i would like to implement a lane detection ground truth, which means that i would like to get the lane information, for example in waypoints, to generate labeled data containing the lane informations.

Are there already ways to do that or do you have idears?

My idea would it be to extract the opendrive waypoints. How can i get the Opendrive waypoints? 
Is there a way to get the waypoints from the "RoutePlanner" Objects directly inside the unreal editor?

Best regards
Atlunch

**Comment by italovinicius18** [comment]
I'm having the same problem, i want to generate the ground truth to train a lanenet model
