### ISSUE TITLE
Autopilot with start and end points defined - Carla 0.9.4

### ISSUE THREAD

**Issue by mallela** [carla-simulator/carla#1353]
I'd like to collect data by running agents in autopilot mode but with a set start and end position. Can you point me to the right code snippets that do this? The current behavior is random. 

(Using Carla 0.9.4 on Ubuntu 16.04)

Thanks,
Praneeta

**Comment by Johnnyswong** [comment]
You can get all the spawn points by using the function world.get_map().get_spawn_points(). 
Here each spawn point is a transform class in carla. If you want to use a fixed spawn mode, you need to design it by yourself.
The file of gail_control.py provides everything you want.
