### ISSUE TITLE
Issue with getting carla started on remote machine

### ISSUE THREAD

**Issue by biboffff** [carla-simulator/carla#136]
Hello,

I built Carla from source on a remote (and display-less) perfomance station, with Ubuntu 16.04 installed on. On that station, also VirtualGL + TurboVNC is installed.

As local machine, I only have a Windows 10 Laptop available. I connect with MobaXterm to the remote Station. I'm struggling with getting Carla to open on my local laptop. Neither through X-Forwarding nor VNC works due to the error message:
Display :1 is the VNC-Desktop, which doesn't enable GLX. 

On the other Hand, GLX applications, such as 
`/opt/VirtualGL/bin/vglrun glxgears`
runs without Problem on the VNC-Desktop.

Do you have any advice for solving that issue?

Best regards,
Chris

**Comment by chankim** [comment]
Hi, I'm trying to do the same, but did you solve the problem? You just closed this issue.
If you have solved it, can you share your knowledge for others' help?
