### ISSUE TITLE
red arrow in rendered camera image [Carla 0.9.4]

### ISSUE THREAD

**Issue by dianchen96** [carla-simulator/carla#1363]
Hi,

When I save the images rendered from an rgb camera, I found that there is always a red arrow in the image, seemingly pointing to the car's current velocity when the car is moving. Can anyone point me out how to remove this arrow in the image? Much appreciated!

![164](https://user-images.githubusercontent.com/10444308/54091828-cb60aa80-4352-11e9-86f9-aa92468a3cbd.png)
![134](https://user-images.githubusercontent.com/10444308/54091830-cb60aa80-4352-11e9-9ab5-a4f47adab9c3.png)

**Comment by slowergmajor** [comment]
Hi，
I don't know if it's right. According to my experience, this arrow appears in the official "automatic_control.py". Trying to use the "manual_control.py" arrow will not appear.

**Comment by dianchen96** [comment]
@slowergmajor thanks for your reply! I am using my own script to collect the images. If the official automatic_control.py also has the arrow then it seems to have something to do with agent. would love to have the authors confirm on this.

**Comment by aravindSwamy94** [comment]
@dianchen96 : u have to disable the debug in local_planner.py if you are running the automatic_control.py

in local_planner.py --->  run_step(self, debug=False)

This will remove the debug lines. I hope this helps

**Comment by dianchen96** [comment]
thank you! this fixed the issue

**Comment by qhaas** [comment]
Why is this debug flag enabled by default?
