### ISSUE TITLE
Can we create our own spawn points on the map ?

### ISSUE THREAD

**Issue by imran514** [carla-simulator/carla#1368]
Can we create our own spawn points on the map other than already defined ones ?

**Comment by nsubiron** [comment]
Yes, but you need to edit the map in Unreal Editor. Just add a _Vehicle Spawn Point_ anywhere you want, the transform of this actor is then included in the list of spawn points.

**Comment by jagdishbhanushali** [comment]
hi @imran514 , you can spawn vehicle/walker anywhere you want without using Unread editor as well.
`spawn_point = carla.Transform(carla.Location(x,y,z),carla.Rotation(0,degree,0))`
Just make sure x,y,z are valid co-ordinates on map.
