### ISSUE TITLE
How to set mini-displays on the main screen?

### ISSUE THREAD

**Issue by robinalen** [carla-simulator/carla#1369]
OS: Linux Ubuntu
Version: 0.9.3

I have set multiple camera sensors to the vehicle but I can only use TAB to change between sensors. I want to make those cameras like this:
![carla problem1](https://user-images.githubusercontent.com/48460276/54166968-f827d580-44aa-11e9-9ac7-958d69968f7d.png)

**Comment by vishal-prgmr** [comment]
Did you figure this out?

**Comment by robinalen** [comment]
Hi dude, you can refer to the manual_control.py. In order to get those mini-screen, you have to modify the cameraManager class to add camera sensors you want and turn on listening to transmit sensors’ data. Also don’ forget to adjust pygame objects to stick them to the main screen.

**Comment by vishal-prgmr** [comment]
Implementation would really save a lot of time. Do you have one? Dont wanna mess with the infiltratable manual_control.py .

**Comment by robinalen** [comment]
Unfortunately, I have finished the Carla program last month and those files are inaccessible for me anymore:<

**Comment by AmirHarvey** [comment]
Hello, i am trying to do as the attached photo in the beginning. Can you help?

**Comment by darld** [comment]
@carla-admin. Can you provides details about the code change of the manual_control.py?
