### ISSUE TITLE
Obtain cropped mesh of the scene

### ISSUE THREAD

**Issue by luigui2906** [carla-simulator/carla#1370]
Hi,

I am writing to know if there is any easy way to obtain a crop or a segment of the mesh of the scene surrounding the vehicle. I would like to have this because I am testing an algorithm for scene reconstruction from pointcloud using the simulated lidar and I would like to compare my results against the actual real mesh of the scene. Having the possibility of extract the mesh of a portion of the scene, (equivalent to what it has been scanned by the simulated lidar) would be awesome.

Thanks in advance.

**Comment by marcgpuig** [comment]
Hi @luigui2906, thanks for the interest on Carla.
This is something we want to make in the future but currently, we don't have anything like that.
You can modify the server and create some kind of sensor that does such a thing.

**Comment by luigui2906** [comment]
Hi @marcgpuig. Ok. Thanks for the answer.
