### ISSUE TITLE
Field of View

### ISSUE THREAD

**Issue by ivashmak** [carla-simulator/carla#1371]
Hi, 

What type of field of view (fov) for RGB and other camera sensors is set by default? Is it horizontal, vertical, diagonal or defines automatically by aspect ratio?

Thanks in advance

**Comment by nsubiron** [comment]
Hi @ivashmak,

It is horizontal field of view. Fixing the documentation now to include this :grin:

**Comment by ivashmak** [comment]
Thanks!

**Comment by YacineBenameur** [comment]
Hi,

Please, what about the vertical field of view ?
