### ISSUE TITLE
Timestamp of SensorData diverges

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/carla#1381]
Since #1348 , Carla SensorData contains a timestamp.

Unfortunately this diverges from the timestamp reported by world.on_tick(). The longer you run Carla Server, the greater the difference gets.

It seems that GetWorld().GetTimeSeconds() reports the wrong time.

Tested with parameters: ```-benchmark -fps=20```

**Comment by nsubiron** [comment]
It could be a float precision issue.

UWorld stores the elapsed time in a `float`, but our world stores this same value in a `double`.

Check out this code snippet http://coliru.stacked-crooked.com/a/cff4ce9edfaa54dc
