### ISSUE TITLE
Unknown obstacle in Map  Town 01

### ISSUE THREAD

**Issue by akki6843** [carla-simulator/carla#1388]
Hello,

There is a obstacle in Town 01 at  x= -2.3, y= 230.0
Seems like branches of nearby trees are coming out of road causing the collision.
Here is the snapshot of the location and basic info for reference.

Carla 0.9.4.
OS: linux 18.04

![Screenshot from 2019-03-14 18-37-07](https://user-images.githubusercontent.com/16385631/54359214-36c6b700-4688-11e9-943e-46ee9f60b031.png)

**Comment by XGodina** [comment]
Hi, @akki6843 

Yes, it's a collision from a tree. We know it. for the next version, it will be already fixed. 
Sorry for the inconvenience

**Comment by nsubiron** [comment]
@XGodina is this already fixed?

**Comment by XGodina** [comment]
Yes, it's fix !!
