### ISSUE TITLE
how to add the full map?

### ISSUE THREAD

**Issue by HeYDwane3** [carla-simulator/carla#1390]
Ubuntu 18.04
Carla 0.9.4

I created a map in roadrunner, but when I exported it and imported into the Carla, I can only see the part within -300<x<300, -300<y<300. Is there any way I can see the full map? I am not sure if it is the problem from Roadrunner or the Carla.

Anyone can help me?

**Comment by XGodina** [comment]
Hi, @HeYDwane3 

The problem is from RoadRunner, if you would create a big map, you need to change the world settings. Wich version of RoadRunner do you use?

**Comment by eloy96vg** [comment]
Hi @XGodina 

I have the same problem to add the full map. I'm using version 2019.0.4 of RoadRunner. What do i need to change in the world settings to get the full map?

Thanks in advance.

**Comment by XGodina** [comment]
Hi @eloy96vg 

If you create a huge map you need to change the world setting.  Move the blue frame until the map stays inside. ( put the mouse above of frame and move it) After that confirm the changes in "Apply World Changes".

Every version RoadRunner change a bit, but the philosophy is the same.


![image](https://user-images.githubusercontent.com/39989886/56810467-a955b580-6836-11e9-8373-eb4b68a430c2.png)

**Comment by eloy96vg** [comment]
Thanks @XGodina , i have solved that problem, but i have tried to generate the map with generate_map.py and the map is much smaller than routeplanners, spawn points, etc.
Do you know why happen this and how solve this problem?

![Captura de pantalla de 2019-04-27 17-30-33](https://user-images.githubusercontent.com/47063072/56851786-53a30b00-6913-11e9-83fc-90d8be416ed1.png)
![Captura de pantalla de 2019-04-27 17-31-26](https://user-images.githubusercontent.com/47063072/56851787-543ba180-6913-11e9-82ac-1cd97e0d5040.png)

Thanks again.

**Comment by Derekabc** [comment]
@XGodina Where can I found the Roadrunner files of Town 02 and Town01, so I can make some modification to create a new map.

**Comment by XGodina** [comment]
Hi, @Derekabc well, if you download our .xodr files you can load in RoadRunner. RoadRunner should generate the map with OpenDrive information.
