### ISSUE TITLE
Issue in opencv imshow() - RGB camera

### ISSUE THREAD

**Issue by BoChang11** [carla-simulator/carla#1391]
Hi,

I am trying to display the images captured by the **RGB camera** using ```opencv imshow()```. The images are not updating in the window and eventually it gets hung. Is there anybody who faced similar issue while displaying image from ```RGB camera```.

However when I use ```matplotlib plot``` it works fine and could see the images are getting updated continuously. 

BR.

**Comment by jeannotes** [comment]
@BoChang11 did you solve this
