### ISSUE TITLE
How to get the measurements of collision_vehicles, collision_pedestrians, intersection_offroad, intersection_otherlane, collision_other in CARLA 0.9.3?

### ISSUE THREAD

**Issue by Deepak3994** [carla-simulator/carla#1393]

**Comment by aravindSwamy94** [comment]
Even I was looking for the same issue. Would be helpful to know this information?

**Comment by noahcao** [comment]
Someone found some solutions? Thanks.

**Comment by noahcao** [comment]
Maybe, we can use the lane type provided by carla later than 0.9.4 to detect offroad. But there is some issues with me that the output lane type is always "driving" even though the vehicle has been on grass garden or sidewalks.
