### ISSUE TITLE
make package failed with error "fatal: bad revision 'HEAD'"

### ISSUE THREAD

**Issue by 77hanzzi** [carla-simulator/carla#1394]
After successfully executing make lauch and make PythonAPI, I try to execute make package and it gives out the following results. 

BuildPythonAPI.sh: Success!
fatal: bad revision 'HEAD'
Util/BuildTools/Linux.mk:13: recipe for target 'package' failed
make: *** [package] Error 128

Anyone knows how to solve this problem? Thanks very much!!!

**Comment by MrPrince9** [comment]
How do you slove this problem? I met the same question
