### ISSUE TITLE
Reset to arbitrary pose?

### ISSUE THREAD

**Issue by gkahn13** [carla-simulator/carla#14]
carla_example.py shows how to reset to one of the fixed start positions by doing
```
carla.newEpisode(iterator_start_positions)
```
but is it possible to reset the car to an arbitrary pose?

**Comment by Ajk4** [comment]
+1, 

This feature is a must if you want to train your agent on some small-scope mini-tasks like {turn_left_on_crossing, 'turn_right_on_crossing', 'overtake_the_car'}.

**Comment by nsubiron** [comment]
This is almost done :grin:

I'm working on the new API prototype #630, we'll have an experimental release very soon.

**Comment by youssefkhalil96** [comment]
how can use this command "carla.newEpisode(iterator_start_positions)"
