### ISSUE TITLE
Cannot refer to LaneChange.None because None is a reserved word

### ISSUE THREAD

**Issue by analog-cbarber** [carla-simulator/carla#1402]
In CARLA 0.9.4, the LaneChange enum has a value `None`, but because that is a reserved word in Python, there is no way to refer to this value using normal Python syntax:

~~~python
>>> import carla
>>> carla.LaneChange.None
  File "<input>", line 1
    carla.LaneChange.None
                        ^
SyntaxError: invalid syntax
~~~

If you want to test a LaneChange to see if it has this value, you have to use the `name` attribute:

~~~python
if lane_change.name == 'None':
    ...
~~~

It would be better if you picked a different name for this value.

**Comment by nsubiron** [comment]
It was renamed to `carla.LaneChange.NONE`.
