### ISSUE TITLE
Error in Rebuild.sh  version 4.21

### ISSUE THREAD

**Issue by omrizen** [carla-simulator/carla#1403]
Hello
when trying to launch CarlaUE4Editor with "Rebuild.sh" when I use stable branch as the branch repository 
I got an error  "LogCompile: Error: GetTransform: Override of UFUNCTION in parent class (Actor) cannot have a UFUNCTION() declaration above it; it will use the same parameters as the original declaration."

**Comment by nsubiron** [comment]
Hi @omrizen,

The `stable` branch requires Unreal 4.18. See [docs for stable branch](https://carla.readthedocs.io/en/stable/how_to_build_on_linux/).

**Comment by omrizen** [comment]
thanks
