### ISSUE TITLE
Is it possible to change right-hand traffic rule to left hand?

### ISSUE THREAD

**Issue by robinalen** [carla-simulator/carla#1404]
OS: Ubuntu
Version: 0.9.4

Hi everyone,
I wanna change traffic rule to left hand driving when I randomly spawn cars in UE engine. I tried the lane change API in the latest Carla version but it did not work. 
Thanks

**Comment by nsubiron** [comment]
Hi @robinalen,

It's not that simple, you could adapt the autopilot to drive following "opposite" direction, but not everything in the city is reversible, you would need to replace every traffic signal, for instance.

**Comment by robinalen** [comment]
> Hi @robinalen,
> It's not that simple, you could adapt the autopilot to drive following "opposite" direction, but not everything in the city is reversible, you would need to replace every traffic signal, for instance.

Hi ＠nsubiron, thank you for the replay. Yes, that's what I was thinking previously, just crudely let the car drive in opposite direction and change traffic signals.

**Comment by Abanoub-G** [comment]
Hi, 
   I have my own map that I am adding to it my own assets and doing the necessary map coding i.e. modifying the traffic lights to work for left handed systems, speed signs, roundabouts etc.

I was wondering if you could give more details of how to invert the vehicles to drive in the "opposite" direction?  

Thanks

**Comment by robinalen** [comment]
Hi @Abanoub-G ,
I haven't go that deep so far, but since you can create your own map why not change the travel direction while map making? 
Like this:
![roadrunner02](https://user-images.githubusercontent.com/48460276/56173276-f318f180-6027-11e9-9ca3-d71fa5387fe9.png)
I'm not sure if this works for Carla, I'll try to make a left-hand map next month.

**Comment by Abanoub-G** [comment]
Hi, 
Thanks a lot for your reply. The thing is that I am not building this on road runner. I have a map that was build by a professional unreal graphics artist and I am trying to figure out how to add the paths on it. 

Are these paths (splines) generated using road maps i.e. is it something that road maps create automatically when creating the maps?

Thanks

**Comment by robinalen** [comment]
Hi,
Those splines are automatically generated by road runner. I don't have a time to look the details about it but the CarlaDoc seems mentioned a way to modify those splines in UE.
Links: [https://carla.readthedocs.io/en/latest/map_customization/](url)

**Comment by nsubiron** [comment]
It's not documented, but you can make the autopilot work by adding _RoutePlanners_ all over the map. Now, if you have an OpenDrive file associated with your map you can automatically generate these route planners with the _OpenDriveActor_. If not you'll have to it manually, drag and drop a _Route Planner_ from the tab into the map
![image](https://user-images.githubusercontent.com/4332953/56347290-3f009d80-61c4-11e9-832e-ba2c1add5ce1.png)
![image](https://user-images.githubusercontent.com/4332953/56347313-4cb62300-61c4-11e9-9b31-386b0fe098de.png)

Add more spline points by dragging a point while pressing "alt".

**Comment by Abanoub-G** [comment]
Thanks that certainly helped.

**Comment by bapukokare** [comment]
What is the way directly interchange road traverse direction? condition is  to use open drive files 
[lht_trial.txt](https://github.com/carla-simulator/carla/files/10089472/lht_trial.txt)
with notepad only

**Comment by ivevasiljevic** [comment]
Any updates on this matter, with the version 0.9.13? On my map I have a single right hand side road and would like to make the car go into the opposite direction without making a new identical map with a single left hand side road.

So is it possible to accomplish this through code? Or editing some xodr files?

**Comment by JIANGZhengm** [comment]
> Any updates on this matter, with the version 0.9.13? On my map I have a single right hand side road and would like to make the car go into the opposite direction without making a new identical map with a single left hand side road.
> 
> So is it possible to accomplish this through code? Or editing some xodr files?



> Any updates on this matter, with the version 0.9.13? On my map I have a single right hand side road and would like to make the car go into the opposite direction without making a new identical map with a single left hand side road.
> 
> So is it possible to accomplish this through code? Or editing some xodr files?

I have the sampe issue, have you resolved this problem?
