### ISSUE TITLE
Engine crash handling finished; re-raising signal 11 for the default handler

### ISSUE THREAD

**Issue by zlw21gxy** [carla-simulator/carla#1406]
Hey guys, I am using the latest Nvidia driver but still can't use Carla normally...does anyone face the same problem? thanks
![image](https://user-images.githubusercontent.com/46110602/54519339-42282400-49a1-11e9-9e03-01ff20fcacb3.png)
![image](https://user-images.githubusercontent.com/46110602/54519389-6257e300-49a1-11e9-8343-a9fe11e5c17b.png)

**Comment by zlw21gxy** [comment]
I am using Ubuntu 16.04 LTS.....

**Comment by zlw21gxy** [comment]
when download nvidia driver version to NVIDIA-SMI 418.39       Driver Version: 418.39  it is ok;
sudo apt-get install nvidia-418 install the stable version ;  @CreateAMind.ai

**Comment by githubwys** [comment]
can someone deal with this problem?
i also meet this problem and need help, thank you.
