### ISSUE TITLE
Ignoring traffic lights or having them green all the time.

### ISSUE THREAD

**Issue by Seth-Park** [carla-simulator/carla#141]
Is there a way either to have the auto-pilot client ignore the traffic lights or have the traffic lights be green all the time? Thanks in advance!

**Comment by nsubiron** [comment]
Hi @Seth-Park, at the moment this is not possible.

**Comment by YashBansod** [comment]
@Seth-Park, what is the purpose you are exactly looking this for?
In a way having the traffic lights green all the time is equivalent to having no traffic lights at all. So, why not just do that and remove all the traffic lights from the map in the UE4 Editor?

**Comment by nsubiron** [comment]
It's already  possible to control traffic lights from Python API.
