### ISSUE TITLE
how to modify the converted color of the semantic segmentation sensor

### ISSUE THREAD

**Issue by coreper** [carla-simulator/carla#1410]
I am using semantic_segmentation sensor and I do not want so many classes, how I can modify the converted color, for example, I want to modify the color of the Fence (original color is (190, 153, 153)) to the Unlabeled class (0,0,0). 

Thank you

**Comment by backer777** [comment]
I have two ways to do it.
1. Util/ImageConverter/label_pixel_converter.h
    you can modify this code    

> // Someday this will be in a config file or something.
  constexpr static Color LABEL_COLOR_MAP[] = {
      {  0u,   0u,   0u}, // None         =   0u,
      { 70u,  70u,  70u}, // Buildings    =   1u,
      {190u, 153u, 153u}, // Fences       =   2u,
      {250u, 170u, 160u}, // Other        =   3u,
      {220u,  20u,  60u}, // Pedestrians  =   4u,
      {153u, 153u, 153u}, // Poles        =   5u,
      {153u, 153u, 153u}, // RoadLines    =   6u,
      {128u,  64u, 128u}, // Roads        =   7u,
      {244u,  35u, 232u}, // Sidewalks    =   8u,
      {107u, 142u,  35u}, // Vegetation   =   9u,
      {  0u,   0u, 142u}, // Vehicles     =  10u,
      {102u, 102u, 156u}, // Walls        =  11u,
      {220u, 220u,   0u}  // TrafficSigns =  12u,
  };
2.  Deprecated/PythonClient/carla/image_converter.py
     

> def labels_to_cityscapes_palette(image):
    """
    Convert an image containing CARLA semantic segmentation labels to
    Cityscapes palette.
    """
    classes = {
        0: [0, 0, 0],         # None
        1: [70, 70, 70],      # Buildings
        2: [190, 153, 153],   # Fences
        3: [72, 0, 90],       # Other
        4: [220, 20, 60],     # Pedestrians
        5: [153, 153, 153],   # Poles
        6: [157, 234, 50],    # RoadLines
        7: [128, 64, 128],    # Roads
        8: [244, 35, 232],    # Sidewalks
        9: [107, 142, 35],    # Vegetation
        10: [0, 0, 255],      # Vehicles
        11: [102, 102, 156],  # Walls
        12: [220, 220, 0]     # TrafficSigns
    }
    array = labels_to_array(image)
    result = numpy.zeros((array.shape[0], array.shape[1], 3))
    for key, value in classes.items():
        result[numpy.where(array == key)] = value
    return result
