### ISSUE TITLE
Accurate 3D positions of traffic lights

### ISSUE THREAD

**Issue by joeda** [carla-simulator/carla#1413]
Is there any way to retrieve accurate 3D positions of the traffic lights? The actor location is not very useful since it's only an approximation (see a reprojection of the actors below)

![image](https://user-images.githubusercontent.com/389696/54593435-ddb3a600-4a2e-11e9-8f18-52e1def91af9.png)

The OpenDrive maps don't contain traffic lights (even though the format supports this) and the 3D maps are not useful unless one has access to the Unreal Editor as far as I can see.

**Comment by marcgpuig** [comment]
Hi @joeda 
Maybe you can use semantic segmentation alongside the 3D projected depth. Will this be enough for you?
