### ISSUE TITLE
Conflicting traffic lights

### ISSUE THREAD

**Issue by Sakrust** [carla-simulator/carla#1414]
**Timing issues with traffic light groups** 

> Carla version 0.9.4
Windows

As far as I understood, you control an intersection by placing traffic light blueprints on each arm and assign all of them to one single traffic light group blueprint actor. But you can assign switch times to both the group actor with green time, yellow time and switch time and to all of the traffic lights itself, causing conflicts between the timings.

**Comment by wattsavolt** [comment]
The traffic light group times are only used once. At begin play, the traffic light group assigns it's green, red and yellow times to each of its traffic lights. However the traffic light group blueprint just then just references the times of each traffic light after this so if a light's times are updated, there is no conflict.
