### ISSUE TITLE
wheel_base in VehiclePhysicsControl

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/carla#1417]
For calculating steering angles the wheel base (the distance between front and back axle) might be necessary.

Can we add that to VehiclePhysicsControl?

I believe it could somehow be done by using the position of the bones (e.g. Wheel_Rear_Right - Wheel_Front_Right).
Or maybe we could add each wheel position to WheelPhysicsControl.

**Comment by michael-good** [comment]
This would be great! I am also in need of that measure.

**Comment by manishthani** [comment]
Hi everyone,
Sorry for late reply. Thanks for opening this issue. Now we can get the world position of each wheel of the vehicle by accessing the `position` parameter in the `carla.WheelPhysicsControl`.
