### ISSUE TITLE
How to get lidar data?

### ISSUE THREAD

**Issue by Johnnyswong** [carla-simulator/carla#1430]
Hi, thanks for the Carla authors. The Carla simulator is becoming more and more practical and user-friendly. @nsubiron 

Now  I try to add lidar sensor in the simulator, but after I visualize the measurements from lidar, it shows in the above pictures.

![tv](https://user-images.githubusercontent.com/16318579/54812083-37cd9900-4cc5-11e9-9215-d46a8bf6d015.png)

The black points are the measurements. But I think these are points generate by the lidar, not points at the surface of the object which are hit by the ray of the laser.

**Comment by tourin1992** [comment]
Hi man,
could u pls explain, how did u get this kind of data representation?
