### ISSUE TITLE
Linking errors when compiling CarlaUE4 from source in Visual Studio

### ISSUE THREAD

**Issue by Yougmark** [carla-simulator/carla#1432]
``make launch`` fails to launch the editor.  It says CarlaUE4 and Carla modules are missing or built with different engine version (see the first figure below).  But I have only 4.21 version of UE in my system.

Then I chose Yes to rebuild them.  It fails to rebuild CarlaUE4 (second figure).  It's suggested to rebuild from source.  Then I generated Visual Studio project and tried compiling it in Visual Studio.  There are linking errors shown below (third figure).  Any suggestions to solve these errors?

I'm using the up-to-date (03-23-2019) master branch of Carla (v0.9.4), UE v4.21, Visual Studio 2017 on Windows 10.  Has anyone succeeded with this version of Carla?  Suggestions on any working version?

Thanks!

![modulesmissing](https://user-images.githubusercontent.com/1973848/54873808-1b108e80-4db5-11e9-8c90-4fee8989a331.png)
![CarlaUE4cannotbecompiled](https://user-images.githubusercontent.com/1973848/54873754-ed771580-4db3-11e9-9596-b92a13122a22.png)
![CarlaUE4cannotbecompiled_visual_studio](https://user-images.githubusercontent.com/1973848/54873755-ed771580-4db3-11e9-81dd-3c80c03a06cc.png)

**Comment by nsubiron** [comment]
Hi @Yougmark,

Try with the latest release tag, 0.9.4, that should compile

    git checkout 0.9.4

**Comment by Yougmark** [comment]
The 0.9.4 release compiles.
