### ISSUE TITLE
Make package failed

### ISSUE THREAD

**Issue by Sophistt** [carla-simulator/carla#1438]
I am using Carla 0.9.4 and UnreaL Engine 4.21 in Ubuntu 16.0.4. I have built the Unreal engine successfully, but got an error with the command of make package.

ERROR: Cook failed.
       (see /home/pci/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt for full exception trace)
AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
RunUAT ERROR: AutomationTool was unable to run successfully.
Util/BuildTools/Linux.mk:13: recipe for target 'package' failed
make: *** [package] Error 25

Please check the log attached.
[Log.txt](https://github.com/carla-simulator/carla/files/3006044/Log.txt)

Any help will be very appreciated.Thanks~~

**Comment by qhaas** [comment]
Seeing similar errors with `make package` with CARLA 0.9.7, UE 4.23 (Elvis Dowson's ppc64le fork), Clang8, in Ubuntu 18.04 ppc64le (yes, lots of unsupported things here), but `make launch` appears to work...  Hopefully, FBX isn't required somewhere in this process (no ppc64le support), but the `build.utils` target wasn't part of the chain.

> Log.WriteException: ==============================================================================
Log.WriteException: ERROR: Cook failed.
Log.WriteException:        (see /home/carla/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt for full exception trace)
Log.WriteException: 
Log.WriteException: CommandletException: Editor terminated with exit code 1 while running Cook for /mnt/workspace/carla/Unreal/CarlaUE4/CarlaUE4.uproject; see log /home/carla/Library/Logs/Unreal Engine/LocalBuildLogs/Cook-2019.12.30-21.00.16.txt
Log.WriteException:   at AutomationTool.CommandUtils.RunCommandlet (Tools.DotNETCommon.FileReference ProjectName, System.String UE4Exe, System.String Commandlet, System.String Parameters, System.String& DestLogFile) [0x0076d] in <dc196ccecb1d45ad9589dc2ccedaf2d9>:0 
Log.WriteException:   at AutomationTool.CommandUtils.RunCommandlet (Tools.DotNETCommon.FileReference ProjectName, System.String UE4Exe, System.String Commandlet, System.String Parameters) [0x00001] in <dc196ccecb1d45ad9589dc2ccedaf2d9>:0 
Log.WriteException:   at AutomationTool.CommandUtils.CookCommandlet (Tools.DotNETCommon.FileReference ProjectName, System.String UE4Exe, System.String[] Maps, System.String[] Dirs, System.String InternationalizationPreset, System.String[] CulturesToCook, System.String TargetPlatform, System.String Parameters) [0x0013e] in <dc196ccecb1d45ad9589dc2ccedaf2d9>:0 
Log.WriteException:   at Project.Cook (AutomationTool.ProjectParams Params) [0x007ba] in <c3f3f8d4927c4305b7e0cf13f688c779>:0 Wrapped by AutomationException: Cook failed.
Log.WriteException:   at Project.Cook (AutomationTool.ProjectParams Params) [0x007f7] in <c3f3f8d4927c4305b7e0cf13f688c779>:0 
Log.WriteException:   at BuildCookRun.DoBuildCookRun (AutomationTool.ProjectParams Params) [0x00074] in <c3f3f8d4927c4305b7e0cf13f688c779>:0 
Log.WriteException:   at BuildCookRun.ExecuteBuild () [0x00040] in <c3f3f8d4927c4305b7e0cf13f688c779>:0 
Log.WriteException:   at AutomationTool.BuildCommand.Execute () [0x00001] in <dc196ccecb1d45ad9589dc2ccedaf2d9>:0 
Log.WriteException:   at AutomationTool.Automation.Execute (System.Collections.Generic.List`1[T] CommandsToExecute, System.Collections.Generic.Dictionary`2[TKey,TValue] Commands) [0x0007c] in <dc196ccecb1d45ad9589dc2ccedaf2d9>:0 
Log.WriteException:   at AutomationTool.Automation.Process (System.String[] Arguments, UnrealBuildTool.StartupTraceListener StartupListener) [0x00282] in <dc196ccecb1d45ad9589dc2ccedaf2d9>:0 
Log.WriteException:   at AutomationTool.Program.MainProc (System.String[] Arguments, UnrealBuildTool.StartupTraceListener StartupListener) [0x00001] in <888f4e38a3204f838c76ac2ccfb9c026>:0 
Log.WriteException:   at AutomationTool.Program+<>c__DisplayClass1_0.<Main>b__2 () [0x00000] in <888f4e38a3204f838c76ac2ccfb9c026>:0 
Log.WriteException:   at AutomationTool.InternalUtils.RunSingleInstance (System.Func`1[TResult] Main) [0x000a0] in <dc196ccecb1d45ad9589dc2ccedaf2d9>:0 
Log.WriteException:   at AutomationTool.Program.Main (System.String[] Arguments) [0x0020a] in <888f4e38a3204f838c76ac2ccfb9c026>:0
Log.WriteException: ==============================================================================
Program.Main: AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
