### ISSUE TITLE
LiDAR horizontal Field of View parameter missing

### ISSUE THREAD

**Issue by anshulpaigwar** [carla-simulator/carla#1440]
Many Autonomous Vehicles along with Velodyne (360 FOV) uses multiple Ibeo lidars (145 FOV) [link ](https://autonomoustuff.com/product/ibeo-scala/) usually mounted in the bottom of the vehicle. 

Current lidar sensor implementation in Carla doesn't have the parameter to set horizontal FOV. I believe it would be very helpful for many if the support for Ibeo like lidars (with FOV less then 360 degrees) is added.

**Comment by DatKartoffel** [comment]
Hey man have you figured it out. I met the same problem and want solutions......
