### ISSUE TITLE
What should we do when traffic jam happens in the simulator?

### ISSUE THREAD

**Issue by shijieS** [carla-simulator/carla#1443]
Such as this figure, a car stuck in the center of crosses.

![image](https://user-images.githubusercontent.com/20699059/55003083-a5096300-5012-11e9-9ca0-2061a60a581c.png)

**Comment by sunwell1994** [comment]
Same problem. Lots of vehicles are stuck

**Comment by mesakh123** [comment]
Maybe not the best solution, but I also met the same condition when trying to assign too many vehicles at the same time. I just reduce the fps number on the server side. No more traffic stuck. I use NVIDIA 3070 and try to spawn 80 vehicles and 20 pedestrians at the same time. I use -fps=10 .
