### ISSUE TITLE
Ray cluster does not connect to worker nodes on AWS.

### ISSUE THREAD

**Issue by Deepak3994** [carla-simulator/carla#1444]
I am using Ray 0.6.4 from github and python 3.5. I tried to setup ray cluster on aws using the example_full.yaml. In example_full.yaml i set "min_workers: 2" and "max_workers: 6". After the successfull launch of the head node, i did ssh to head node and tried to execute the train_a3c.py script. I got the below error, that the cluster has only 4 cpu and 1 gpu. Where as, inital "min_worker" i set for 2, so each instance has 4cpu and 1gpu, so all together i should have 12cpu and 3gpu including the head node.

I have attached a screenshot of the error below,

![error-with-cluster](https://user-images.githubusercontent.com/20994657/55003389-5b168200-4ffe-11e9-985b-e98074307455.png)

**Comment by Deepak3994** [comment]
Solved..

**Comment by buedaswag** [comment]
how did you solve this? im having the same problem on a kubernetes cluster on GCP.
ran ray start --redis-address 10.16.2.2:6379 on each worker but the workers are not doing anything, just the head node
