### ISSUE TITLE
destroy actor fail

### ISSUE THREAD

**Issue by zlw21gxy** [carla-simulator/carla#1459]
I am using carla0.9.4 with ubuntu16.04 but after running when I want to destroy actors weird things happened, if I check whether that actor alive or not it shows me actor already dead, but when python program finish running, LIFETIME warning will pop up and tell me actors still alive
![image](https://user-images.githubusercontent.com/46110602/55130245-181af280-5155-11e9-8803-5043b53af1f9.png)
![image](https://user-images.githubusercontent.com/46110602/55130274-34b72a80-5155-11e9-8d5f-9c9e9fc01d8b.png)
![image](https://user-images.githubusercontent.com/46110602/55130577-5238c400-5156-11e9-85e1-c30bc37db5ce.png)
![image](https://user-images.githubusercontent.com/46110602/55130847-60d3ab00-5157-11e9-8582-f57f68cdae3f.png)

**Comment by nsubiron** [comment]
Hi @zlw21gxy,

I see the confusion, "LIFETIME" messages are a debug check on the actor handle, while the message _"attempting to destroy an actor that is already dead"_ refers to an actual actor in the simulation. They're not talking about the same object, you may have destroyed the vehicle in the simulator, but in Python you still have its handle object. (I think lifetime debug checks were removed in the last build).

If the LIFETIME messages only happen when you kill your script it's fine, but if they happen when exiting successfully, it may be showing that you have a memory leak. In that case, probably you are registering a callback (on "listen" or "on_world_tick") that has a reference to a Carla object (actor, world, or client). This creates a circular reference between Python objects so they're never destructed. What we do to avoid that is using weak references, for instance
```py
import weakref


class MySensorWrap(object):
    def __init__(self):
        self.sensor = world.spawn_actor(...)
        weak_self = weakref.ref(self)
        self.sensor.listen(lambda data: MySensorWrap._on_listen(weak_self, data))

    @staticmethod
    def _on_listen(weak_self, data):
        self = weak_self()
        if not self:
            return
        self.parse_data(data)
```

**Comment by Yumin-Sun-00** [comment]
I got the same error when running the `examples/tutorial.py`

```
created vehicle.chevrolet.impala
created sensor.camera.depth
moved vehicle to Location(x=267.309509, y=-5.083644, z=-0.048065)
created vehicle.kawasaki.ninja
created vehicle.gazelle.omafiets
created vehicle.bh.crossbike
created vehicle.volkswagen.t2
created vehicle.gazelle.omafiets
created vehicle.gazelle.omafiets
created vehicle.tesla.cybertruck
created vehicle.harley-davidson.low_rider
created vehicle.bmw.grandtourer
created vehicle.carlamotors.carlacola
destroying actors
terminate called after throwing an instance of 'std::runtime_error'
  what():  trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
Aborted (core dumped)
```

**Comment by 2000222** [comment]
> I got the same error when running the `examples/tutorial.py`
> 
> ```
> created vehicle.chevrolet.impala
> created sensor.camera.depth
> moved vehicle to Location(x=267.309509, y=-5.083644, z=-0.048065)
> created vehicle.kawasaki.ninja
> created vehicle.gazelle.omafiets
> created vehicle.bh.crossbike
> created vehicle.volkswagen.t2
> created vehicle.gazelle.omafiets
> created vehicle.gazelle.omafiets
> created vehicle.tesla.cybertruck
> created vehicle.harley-davidson.low_rider
> created vehicle.bmw.grandtourer
> created vehicle.carlamotors.carlacola
> destroying actors
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
> Aborted (core dumped)
> ```

True, I have obtained the same error, have you found some solutions? Thanks.

**Comment by YacineBenameur** [comment]
Hi,
Just add `ego_vehicle.set_autopilot(False)` before ` ego_vehicle.destroy()`
cheers

**Comment by qhaas** [comment]
> True, I have obtained the same error, have you found some solutions? Thanks.

Same error in CARLA 0.9.8, but [said error is in the cleanup step](https://github.com/carla-simulator/carla/blob/0.9.8/PythonAPI/examples/tutorial.py#L122), so likely harmless.

**Comment by SuperShinyEyes** [comment]
I got a same error in 0.9.11.
