### ISSUE TITLE
'carla/carla_server.h' file not found

### ISSUE THREAD

**Issue by ajax98** [carla-simulator/carla#146]
Hi,

I am trying to build Carla for linux and  was running the Rebuild.sh script where I got two errors: fatal error: 'carla/carla_server.h' file not found
#include <carla/carla_server.h> and ERROR: UBT ERROR: Failed to produce item: /home/ajay/carla-master/Unreal/CarlaUE4/Plugins/Carla/Binaries/Linux/libUE4Editor-Carla.so.  Do you know why these errors might be occuring?

**Comment by nsubiron** [comment]
It seems like the CarlaServer dependency failed to compile.

Make sure that the Setup script does print _"Success!"_ at the end

    $ ./Setup.sh
    [...]
    ****************
    *** Success! ***
    ****************

Then check if CarlaServer compiles without errors running make

    $ make

It should end printing something like

```
[1/1] Install the project...
-- Install configuration: "Release"
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/shared/libc++abi.so.1
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/shared/libc++abi.so.1.0
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/shared/libc++.so.1
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/shared/libc++.so.1.0
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/shared/libc++.so
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/shared/libc++abi.so
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/lib/libc++abi.a
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/lib/libboost_system.a
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/lib/libprotobuf.a
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/include/carla
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/include/carla/carla_server.h
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/lib/libcarlaserver.a
-- Installing: Unreal/CarlaUE4/Plugins/Carla/CarlaServer/bin/test_carlaserver
-- Set runtime path of "Unreal/CarlaUE4/Plugins/Carla/CarlaServer/bin/test_carlaserver" to ""
```

If so you can safely run Rebuild.sh.

**Comment by ajax98** [comment]
Thanks, I was able to fix this.

**Comment by muzaheed57** [comment]
i am in windows. having the same issue.  running Setup.sh is not doing anything

**Comment by nsubiron** [comment]
Hi @muzaheed57,

We don't have full support for Windows yet, you will need to compile the external dependencies manually if you want to run CARLA in Windows. Please check out #21.
