### ISSUE TITLE
throw what():  bad_weak_ptr when spawn camera

### ISSUE THREAD

**Issue by zlw21gxy** [carla-simulator/carla#1460]
Currently when I try to wrapper carla into gym env style(which means a lot reset), carla will throw what():  bad_weak_ptr unexpected while running, this error will block the whole process, but it's not always happened. sometime it will happened per hour sometime per day.
Does anyone face the same issue?
![image](https://user-images.githubusercontent.com/46110602/55141033-70adb800-5174-11e9-9827-4695451ff9b7.png)
![image](https://user-images.githubusercontent.com/46110602/55141356-385aa980-5175-11e9-9ef5-ac4c3e70dde9.png)

**Comment by zdx3578** [comment]
camera = world.spawn_actor(camera_bp, relative_transform, attach_to=my_vehicle)

self.camera_rgb1 = world.spawn_actor(camera_rgb1, camera_transform, attach_to=self.vehicle)

**Comment by parhartanvir** [comment]
Facing the same issue, when trying to run the ros-bridge, openai-gym style.
