### ISSUE TITLE
where is CarlaMapGenerator in the carla 0.9.3?

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla#1463]
As #1003 mentioned,I'll have first to open the "ViewOption" submenu and select "Show C++ Classes" ,but I don't find CarlaMapGenerator.

**Comment by backer777** [comment]
![see](https://user-images.githubusercontent.com/13561917/56791111-e0c56180-6838-11e9-9190-8b4e20cf5c80.png)
