### ISSUE TITLE
Bug in Lane_id

### ISSUE THREAD

**Issue by eslambakr** [carla-simulator/carla#1469]
Hello,

I think there is a bug in lane_id, as I noticed that the id changes from 3 to -3 for example for certain period then becomes 3 again!, however the car don't change it's lane.

Is this a real bug or I missed some thing?

**Comment by nsubiron** [comment]
Hi @eslambakr,

It's not a bug, it's how [OpenDRIVE](http://www.opendrive.org) works. A lane id is unique within its lane section, and a road section may have several lane sections.
![image](https://user-images.githubusercontent.com/4332953/55288050-2ca7f680-53b2-11e9-85bc-ed2acfeba8a5.png)

Our waypoints are identified by 4 numbers

* **road_id:** id of the road section (as in the XODR file).
* **section_id:** id of the lane section (not standard, we added this one for extra precision).
* **lane_id:** id of the lane (as in the XODR file), negative goes forward relative to road (arbitrary) direction, positive backwards.
* **s:** distance in meters from the beginning of the road section.

But most of the time you don't need to care about these numbers unless you're directly working with the XODR file.

**Comment by Johnnyswong** [comment]
Thanks a lot !!! @nsubiron  Your explanation helps a lot.
