### ISSUE TITLE
 Maps created by myself cannot be connected by scripts manual_control.py

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla#1472]
Hello,carlateam.
I create a simple map in unreal engine.In the project setting,I use the setting as follows:
![Screenshot from 2019-04-01 14-39-54](https://user-images.githubusercontent.com/42662403/55308064-0fdff180-548c-11e9-9c05-b96e7ff1f420.png)
by pressing the play button in the unreal engine,starting the simulation environment，and running manual_control.py,I find that the unreal engine editor crash.As mentioned above,Can't  maps created by myself  be connected by scripts manual_control.py,then control the vehicle in the map?

**Comment by Sakrust** [comment]
Did you rebuild Carla (including your new map) prior to your connection attempt?

**Comment by XGodina** [comment]
Does This map have opendrive?
