### ISSUE TITLE
CARLA scripts IndexError: list index out of range

### ISSUE THREAD

**Issue by Iswed** [carla-simulator/carla#1475]
CARLA 0.9.4 running on Windows 10. There seems to be an issue with the automatic_control and manual_control scripts when running on python 3.7 with pygame 1.9.5. The error occurs in the initialisation of the HUD instance. An indexing error in the list of fonts relating to the following lines:
fonts = [x for x in pygame.font.get_fonts() if 'mono' in x]
mono = default_font if default_font in fonts else fonts[0]

the font 'mono' is not found in pygame.font.get_fonts(), therefore the list 'fonts' is empty. Calling fonts[0] results in the indexing error.
Replacing 'mono' with another font such as 'arial' or another font in pygame.font.get_fonts() seems to resolve the issue, as fonts[0] will not be null.

**Comment by rajcivils** [comment]
Just replace the mono with arial. It works for me. This was told in sentdex series. And this bug can be solved by just replacing all monos with arial. Which is super simple in sublime. 
![image](https://user-images.githubusercontent.com/30827615/71301834-44089300-23ca-11ea-867d-b34530a77068.png)

Just click on replace all. In mine it has already been done. But note it is actually mono there if you are getting the error.

**Comment by lshmouse** [comment]
See: https://github.com/pygame/pygame/issues/3156 

In uubuntu,  the reason why pygame.font.get_fonts() returns none is 'fc-list' not found, the following command may fix it.

```
sudo apt install fontconfig
```
