### ISSUE TITLE
Issue creating .egg file from Carla repository

### ISSUE THREAD

**Issue by SIlvaMFPedro** [carla-simulator/carla#1476]
Good afternoon. I am an engineering student and i am using CARLA for my master's thesis.
I am having an issue creating .egg file from the CARLA repository. 
![carla_egg_file_error](https://user-images.githubusercontent.com/22821533/55339663-0447f700-549b-11e9-8789-7e98b4469f22.png)
It says it cannot find Memory.h file but this file exists in the "~/carla/Libcarla/source/carla" directory.

Can someone help me fix this issue?

Thank you very much.

Pedro Silva - Aveiro University - DETI

**Comment by nsubiron** [comment]
Hi @SIlvaMFPedro,

Use `make PythonAPI` on the root folder.

**Comment by SIlvaMFPedro** [comment]
Already solved the issue @nsubiron .
Thank you for the help ;)
