### ISSUE TITLE
control vehicle movements

### ISSUE THREAD

**Issue by kimiya66** [carla-simulator/carla#1479]
I saw in autonomous_control.py as an example. here when I add non-player vehicle(by spawn_points in the environment, the hero vehicle stops in distance of 10m from the obstacle(non-player car) but I could not find where in the code it gets this event or disable autopilot? 
is this controlled by by key_control class.(as I saw it parses events to that class) but I could not find where it reads camera's data and in which function set the vehicle to stop.

**Comment by wattsavolt** [comment]
The vehicle would be stopped on the server side. The navigation logic is in the CarlaUE4 project code.
