### ISSUE TITLE
Viewing the simulation through ssh

### ISSUE THREAD

**Issue by alexanderganderson** [carla-simulator/carla#149]
I am currently running Carla on a remote computer [because the models that I am training are compute intensive].  Is there any simple way to view the results of the simulation through ssh?  I can create a hack, but it would be good to know if you already have a pre-built solution to this.  Thanks!

**Comment by ciumonk** [comment]
x11vnc will pipe everything through vnc:

x11vnc -rfbauth ~/.vnc/passwd  -display :0 -forever -bg -repeat -nowf -o ~/.vnc/x11vnc.log
