### ISSUE TITLE
Synchronous mode/sticky_control doesn't seem to work

### ISSUE THREAD

**Issue by alexanderkoumis** [carla-simulator/carla#1490]
Hello, I am running an experiment with version 0.9.4 and running into an issue where the simulator is not truly "pausing" when it does not receive a tick in synchronous mode. The following code is supposed to switch between modes every 5 seconds. One mode does not send any control, while the second one does (steer = 0, throttle = 0.6). When I run this code, I am expecting the vehicle to move forward for 5 seconds, and then stop for 5 seconds, repeatedly. However, it keeps moving at exactly the same pace and never slows down. (And yes I am setting vehicle sticky_control to False elsewhere). Any ideas what I am doing wrong? Thanks!

```python
settings = world.get_settings()
settings.synchronous_mode = True
world.apply_settings(settings)

time_s = time.time()
tick = False

while True:

    time_c = time.time()
    if time_c - time_s > 5.0:
        tick = not tick
        time_s = time_c
        print('switch', tick)
    if tick:
        control = carla.VehicleControl()
        control.steer = 0.0
        control.throttle = 0.6
        control.brake = 0.0
        control.hand_brake = False
        control.manual_gear_shift = False
        vehicle.apply_control(control)

    pygame_clock.tick()
    world.tick()
    world.wait_for_tick()
```

**Comment by sapirbm** [comment]
following the same issue.
i want a car to follow dynamic drive instructions from a custom client. 
as in: Tick -> get_car_cmd -> apply_control -> send_car_state -> Tick
however i can't really stop the server and ends up with bad close_loop performance.
