### ISSUE TITLE
Find occlusion object in Image plane

### ISSUE THREAD

**Issue by dldudwo0805** [carla-simulator/carla#1493]
Hi, I am drawing 2d-bounding box of objects in the image plane.
Camera is located in ego-vehicle, far from (1.6, 0, 2) **in** the center of the vehicle.
I use the object's global position, and then projection to the image plane.
Although object in front of the camera, but occluded by building or others, that object is drawn.
How can I fixed that situation. I want draw 2d-bounding box which is not occluded.

![ex1](https://user-images.githubusercontent.com/25000800/55523916-15c11700-56c6-11e9-8bba-8fd515a287f8.PNG)
![ex2](https://user-images.githubusercontent.com/25000800/55523917-1659ad80-56c6-11e9-9212-64403634d38b.PNG)

**Comment by baurst** [comment]
This is probably not the best way to do it, but you could use an additional depth camera with the same parameters as the rgb camera and check if the objects distance to your ego vehicle is larger than the distance you get from the distance image.

**Comment by dldudwo0805** [comment]
Thank you for giving idea.
Now I turn into using segmentation data.
Using that data, delete the occlusion data, similarly that you mentioned.

**Comment by marcgpuig** [comment]
I would have went for the depth option too :)
Closing the issue since seems solved!

**Comment by Vin1291** [comment]
@dldudwo0805 Hello, I am stuck on the same thing, can you share how you solved the issue using semantic segmentation.

**Comment by rohansingh080699** [comment]
@marcgpuig @baurst , Hello! I am trying to do the same thing as stated in this issue but in carla 9.13  and carla 9.13 has an instance segmentation camera. So basically I have two small questions, is the instance segmentation camera better or the depth camera better  to remove the 2d bounding boxes of occluded objects?(can you also please tell me how to approach this problem?)

Coming to instance segmentation camera, i have set up an instance segmentation camera with the same parameter as the RGB Camera and I'm also listening to the output and saving it in a dictionary and I know that the tag information encoded in the red channel, but my doubt is how do i filter out the occludes 2d bounding boxes with this tag information?

**Comment by rohansingh080699** [comment]
@marcgpuig @baurst , Hello! I am trying to do the same thing as stated in this issue but in carla 9.13  and carla 9.13 has an instance segmentation camera. So basically I have two small questions, is the instance segmentation camera better or the depth camera better  to remove the 2d bounding boxes of occluded objects?(can you also please tell me how to approach this problem?)

Coming to instance segmentation camera, i have set up an instance segmentation camera with the same parameter as the RGB Camera and I'm also listening to the output and saving it in a dictionary and I know that the tag information encoded in the red channel, but my doubt is how do i filter out the occludes 2d bounding boxes with this tag information?

**Comment by rohansingh080699** [comment]
Hello @dldudwo0805 and @Vin1291 , were you guys able to find a solution? if yes, can you please help me out with this issue?
