### ISSUE TITLE
Running carla in Docker

### ISSUE THREAD

**Issue by Johnnyswong** [carla-simulator/carla#1494]
Hi, @nsubiron
 
I tried to run the carla docker container. But failed with the error:
`Failed to find symbol file, expected location:
"/home/carla/CarlaUE4/Binaries/Linux/CarlaUE4.sym"`

The gpu on my server are a P40 and a V100 while the versions of the gpu drivers are both **390.87**.
I can run the carla docker container in my local pc, with a **1080ti** gpu and a gpu driver version of **390.87**. 
The P40 GPU actually supports OpenGL.
![tv](https://user-images.githubusercontent.com/16318579/55544477-c72f6f00-56fd-11e9-86cb-b139b73337cb.png)

Previous issues for this problem have pointed out that it may related to the OpenGL library. I have installed the OpenGL library on my server, but it still didn't work yet.

After some googling, I think the problem is caused by Unreal4.21, the following link shows a similar problem:
`https://answers.unrealengine.com/questions/886214/view.html`.
But I have no idea how to fix it.

**Comment by rkollataj** [comment]
I had similar problem (also running from docker) in CARLA 0.9.5. My GPU: Radeon HD 8890M. Running in low quality helped in my case:
`./CarlaUE4.sh -quality-level=Low`
After the above I can run Carla without a problem even in Epic quality.

**Comment by Johnnyswong** [comment]
> I had similar problem (also running from docker) in CARLA 0.9.5. My GPU: Radeon HD 8890M. Running in low quality helped in my case:
> `./CarlaUE4.sh -quality-level=Low`
> After the above I can run Carla without a problem even in Epic quality.

Thanks for your reply. I tried your method but it still can't work yet.

**Comment by qhaas** [comment]
I mysteriously started getting this in Ubuntu 18.04 when running via Singularity 3.0 and then mysteriously stopped getting it.  Might be a coincidence, but when I was getting this error, there was another CUDA process (Type C) sharing GPU 0 (which CARLA seems to be hardwired to use) observed using `nvidia-smi -i 0`).  I fear t his error has more than one cause.

**Comment by Kailiangdong** [comment]
@Johnnyswong Hello, where do you find the support information of OpenGL about your GPU? I can't find what version support my tesla p100, thank you

**Comment by Kailiangdong** [comment]
@Johnnyswong Do you finally run carla on your tesla server? Thank you

**Comment by Jiankai-Sun** [comment]
Same problem for `carlasim/carla:0.9.5`, when I run `docker run --net=host --rm -d -it -e NVIDIA_VISIBLE_DEVICES=0  --runtime nvidia carlasim/carla:0.9.5'
        carla_arg = ' ./CarlaUE4.sh /Game/Carla/Maps/Town03 -benchmark -carla-server -fps=20 -world-port=%s -windowed -ResX=4 -ResY=4 -carla-no-hud`.

The docker container can just spawn some objects but freezed after that.

![image](https://user-images.githubusercontent.com/25477396/70984225-0ddec100-20f5-11ea-8f96-a0a8e0688705.png)
