### ISSUE TITLE
about make launch on windows

### ISSUE THREAD

**Issue by Firesuiry** [carla-simulator/carla#1497]
I try to make lanuch on my windows 7 
but there is always something wrong when the program run git clone
I want to do it manually,but
I read the makefile and find that when i make launch it will run BuildCarlaUE4.bat
but I cannot see any content about git in the file,where can i find it?

**Comment by marcgpuig** [comment]
Hi @Firesuiry 
Then you are searching for `Util\BuildTools\Setup.bat` that call all the windows individual "installers"

**Comment by Firesuiry** [comment]
> Hi @Firesuiry
> Then you are searching for `Util\BuildTools\Setup.bat` that call all the windows individual "installers"

thank you very much！
