### ISSUE TITLE
How can I put my camera is a fixed point?[0.9.3]

### ISSUE THREAD

**Issue by ChrisHRZ** [carla-simulator/carla#1506]
I need to put one or more camera(depth, RGB and segmentation) in a fixed point to save pictures. I only know how to change the relative position of vehicle. I need to fix my camera or move camera's viewpoint just like in server.How can I achieve this?
Thank you.

**Comment by nsubiron** [comment]
Hi @ChrisHRZ,

Just remove the `attach_to` argument when spawning a camera
```py
camera = world.spawn_actor(blueprint, transform)
```

**Comment by ChrisHRZ** [comment]
> Hi @ChrisHRZ,
> 
> Just remove the `attach_to` argument when spawning a camera
> 
> ```python
> camera = world.spawn_actor(blueprint, transform)
> ```

Thank you

**Comment by geekhut** [comment]
> > Hi @ChrisHRZ,
> > Just remove the `attach_to` argument when spawning a camera
> > ```python
> > camera = world.spawn_actor(blueprint, transform)
> > ```
> 
> Thank you

Hi did you manage to do it? could you share the code please?
