### ISSUE TITLE
Storing Depth Array

### ISSUE THREAD

**Issue by stamatic** [carla-simulator/carla#1507]
I'm currently trying to generate 2D bounding boxes in Carla 0.9.4 on Ubuntu 18.04 with Python 2.7. The bounding box part works fine. As others here on Github I have the issues that the boxes for occluded actors still appear, hence as suggested in other posts I wanted to mitigate the problem by using the output of a depth camera. 
I'm doing all the processing offline once I have collected the data. This might be a stupid question, but I'm trying to store the output of the depth camera as a depth array. Is that possible? In the sensor callback I wrote I use `ColorConverted.Depth` in order to convert the sensor output to the desired format, at this point I would expect to be able to store an array of size (image_height*image_width), where each entry correspond to the measured distance. The size I obtain is correct, what confused me are the entries. For example if I access the maximum value of the array I get the following output: 

> Color(255,255,255,255)

Confused by this, I also tried something else. Simply storing the depth images without any conversion, then apply the conversion given in the Camera and Sensors section: 
> normalized = (R + G * 256 + B * 256 * 256) / (256 * 256 * 256 - 1)
in_meters = 1000 * normalized

This is the RGB image I'm working with 
![88869](https://user-images.githubusercontent.com/35172341/55709591-f50c0080-59e8-11e9-9a3b-51cafd7b2868.png)
This is the corresponding output of the depth sensor
![d88869](https://user-images.githubusercontent.com/35172341/55709609-fe956880-59e8-11e9-89a3-756339ae94e6.png)
And this is what I obtain by applying the conversion mentioned above
![depth](https://user-images.githubusercontent.com/35172341/55709636-0d7c1b00-59e9-11e9-94ec-fb9c8c5ef335.png)
What irritates me is that the maximum depth reading I obtain is 3.90 meters, which seems wrong to me. 

Does anyone has an idea of what I'm doing wrong with either of this methods and what I should be doing in order to obtain the depth array correctly?

**Comment by stamatic** [comment]
I think I managed to get things working as I wanted to. I started digging a bit deeper and found something from the old [API](https://github.com/carla-simulator/carla/blob/0d5a6f335c6293f481ac99bd8a137897da48a604/Deprecated/PythonClient/carla/image_converter.py#L110). I added the `to_bgra_array to_rgb_array and depth_to_array` to my code and I am now able to store the depth info as array. Which plotted looks like this (for a different scenario).
![depth2](https://user-images.githubusercontent.com/35172341/55715116-54234280-59f4-11e9-9da9-6f0d83c51b00.png)

**Comment by dev015** [comment]
@cstamatiadis Hello, did you solve the issue of filtering out the occluded objects?

**Comment by hrushikesh233** [comment]
@cstamatiadis Hey! I am struggling with the commands to generate the depth map in the first place.

I get that the raw data has an array of values but how do you actually convert to depth form, what are the commands for it?

I tried the conversion but ended up just converting the image to black and white

![Screenshot (38)](https://user-images.githubusercontent.com/71658374/93793277-3d0dfa00-fc54-11ea-997a-667462f1f209.png)

Kindly guide me!

**Comment by Akumar201** [comment]
@hrushikesh233 Hi, I know I am late to the party but this is the way I did it, hopefully it will help someone in the future.
```

class DepthCameraSensor:
    def __init__(self, parent_actor, width=640, height=480):
        self.sensor = None
        self._parent = parent_actor
        self.depth_data = None
        self._frame_count = 0
        
        world = parent_actor.get_world()
        bp = world.get_blueprint_library().find('sensor.camera.depth')
        
        # Print ALL available attributes BEFORE setting them
        print("\n=== DEPTH CAMERA BLUEPRINT ATTRIBUTES ===")

        for attr in bp:
            print(f"  {attr.id}: {attr.type} = {attr.recommended_values if attr.recommended_values else 'default: ' + str(attr)}")
        bp.set_attribute('image_size_x', str(width))
        bp.set_attribute('image_size_y', str(height))
        bp.set_attribute('fov', '70')
        
        # Mount depth camera on roof (Tesla Model 3 optimized)
        transform = carla.Transform(
            carla.Location(x=0.5, z=1.8), 
            carla.Rotation(pitch=-15)
        )
        
        self.sensor = world.spawn_actor(bp, transform, attach_to=parent_actor)
       
        weak_self = weakref.ref(self)
        self.sensor.listen(lambda img: DepthCameraSensor._on_depth(weak_self, img))
    
    @staticmethod
    def _on_depth(weak_self, image):
        self = weak_self()
        if not self:
            print("WARNING: Depth callback - weak_self is None!")
            return
        
        self._frame_count += 1
        
        # Convert depth image to numpy array
        # CARLA stores depth as BGRA (Blue, Green, Red, Alpha)
        array = np.frombuffer(image.raw_data, dtype=np.dtype("uint8"))
        array = np.reshape(array, (image.height, image.width, 4))  # BGRA format
        
        # Extract channels in correct order (CARLA uses BGRA, not RGBA!)
        B = array[:, :, 0].astype(np.uint32)  # Blue is at index 0
        G = array[:, :, 1].astype(np.uint32)  # Green is at index 1
        R = array[:, :, 2].astype(np.uint32)  # Red is at index 2
        
        # Decode depth (CARLA format from documentation)
        # Formula: (R + G*256 + B*256*256) / (256^3 - 1) * 1000m
        int24 = R + (G << 8) + (B << 16)  # Same as: R + G*256 + B*256*256
        normalized = int24.astype(np.float32) / float(256**3 - 1)
        self.depth_data = normalized * 1000.0  # Distance in meters (far plane = 1000m)
```
