### ISSUE TITLE
Blueprint library filter

### ISSUE THREAD

**Issue by dldudwo0805** [carla-simulator/carla#1514]
Now I want to except 2-wheel vehicle like, bike or motorcycle.

I'm using Carla 0.9.4 and how do I writing code?

`blueprint.filter('vehicle')` 

I wrote code like above.

**Comment by nsubiron** [comment]
```py
vehicles = blueprint_library.filter('vehicle.*')
bikes = [x for x in vehicles if int(x.get_attribute('number_of_wheels')) == 2]
```
