### ISSUE TITLE
New feature: Minimap

### ISSUE THREAD

**Issue by ADulian** [carla-simulator/carla#1516]
Hi all,

Currently running some experiments with Carla, for now just gathering some data and thought that there might be a very useful, hopefully a trivial to implement feature. Would be glad to see an option of having some sort of a minimap in the corner of the screen, just to see where the other actors are heading etc. As far as I'm aware this is not yet there.

Regards,

**Comment by ruff-huettinger** [comment]
I'm also looking for an implementation of a minimap. Will start to do it myself, then
