### ISSUE TITLE
[0.9.5] OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by mallela** [carla-simulator/carla#1525]
I get the following error when I run `manual_contorl.py` from the pre-built release:  `OverflowError: Python int too large to convert to C long` at line 416

`'Simulation time: % 12s' % datetime.timedelta(seconds=int(self.simulation_time)),`

Has anyone encountered this issue?

**Comment by nsubiron** [comment]
Simulation time is a `double` internally, it might be too big to pass as an int to datetime.

**Comment by mallela** [comment]
I identified the problem - I had not added the correct .egg to the `PYTHONPATH`. I added the one for 0.9.4 instead of 0.9.5. Works now!

**Comment by nsubiron** [comment]
Oh ok, great! I'll close the issue then :)
