### ISSUE TITLE
PythonAPI carla.Waypoint.s?

### ISSUE THREAD

**Issue by TDHTTTT** [carla-simulator/carla#1529]
So there is not enough documentation in the PythonAPI and I couldn't figure out what Carla.Waypoint.s is.

**Comment by TDHTTTT** [comment]
It seems that it is the definition from open drive, which is "track position of object's origin (s-position)", which still does not make sense to me. What is the origin?

**Comment by TDHTTTT** [comment]
I also found this line in the update for 0.9.5 

> "The s parameter of OpenDrive, it defines the position along the reference line, measured in meters from the beginning of the track, calculated in the XY-plane"

I guess origin == beginning of the track, but what does it mean?

**Comment by nsubiron** [comment]
Take a look at https://github.com/carla-simulator/carla/issues/1469#issuecomment-478330987, may help understanding OpenDrive format.

**Comment by TDHTTTT** [comment]
> Take a look at #1469 (comment), may help understanding OpenDrive format.

Thanks!
