### ISSUE TITLE
Lidar point cloud accuracy

### ISSUE THREAD

**Issue by cmpute** [carla-simulator/carla#1535]
The point cloud data of vehicles got from Carla is not presenting its real shape. All vehicles are considered as box like objects which is quite from real world data. This issue have been existing since when lidar has been introduced. And also sensor noise could be considered to add into the sensor data. (e.g. the floor should not be exact flat)

Another issue is that when enabled lidar processing, the server is running much lower sometimes.

**Comment by nsubiron** [comment]
Duplicated of #423.
