### ISSUE TITLE
CARLA for left handed systems

### ISSUE THREAD

**Issue by Abanoub-G** [carla-simulator/carla#1540]
Hi,
I have my own map that I am adding to it my own assets and doing the necessary map coding i.e. modifying the traffic lights to work for left handed systems, speed signs, roundabouts etc.

I was wondering if anyone could give me a more detailed guide of of how to invert the vehicles in CARLA to drive in the opposite direction (i.e. on the left side of the road)?

Thanks

**Comment by bg-sumu** [comment]
Any Idea on how to Achieve Left Side Driving ?
