### ISSUE TITLE
ninja error at Linux.mk

### ISSUE THREAD

**Issue by gulsumUz** [carla-simulator/carla#1541]
I have successfully installed UE and defined UE_ROOT as a path. 
Ubuntu version : 18.04
cmake version : 3.13.4
ninja version : 1.8.2

1. If I run "make PythonAPI" command, I got error on line 98 at Linux.mk like in the figure. 
![image](https://user-images.githubusercontent.com/10177222/56165372-73fdcc00-5fdb-11e9-8c74-7c3ef7206991.png)

2. If I run "make launch" or "make LibCarla", I got the same error because of line 92 at Linux.mk as in the figure. 
![image](https://user-images.githubusercontent.com/10177222/56165368-6f391800-5fdb-11e9-88ef-fe27cc3af155.png)

Is there any idea to solve it ? 
Thank you,

**Comment by nsubiron** [comment]
Never seen this error before, but try doing a clean build in case the cache got messed up

    make clean

or

    make rebuild
