### ISSUE TITLE
LIDAR Horizontal FOV and Understanding

### ISSUE THREAD

**Issue by ravishk1** [carla-simulator/carla#1544]
Hi,

I want to use Lidar as different distance sensor, Suppose I want to use Lidar as a Radar sensor, for that I want to restrict 360 degree rotation of the Lidar. I want it to move only in the range of suppose 0 to 180 degree. Can we modify the Lidar configuration in such a way?? Just like we restrict the Upper FOV and Lower FOV, can we restrict the Horizontal FOV??

And will anyone please elaborate the lidar parameters, like what are the units of measurement ?? 

Any help will be highly appreciated.
Thanks !

**Comment by DatKartoffel** [comment]
Hey man have you figured it out?

**Comment by osmanlakovic** [comment]
Did anyone figure it out maybe ?

**Comment by FrancescoTerrosi** [comment]
+1 i need this as well
