### ISSUE TITLE
How to get information about npc vehicle's speed ? 

### ISSUE THREAD

**Issue by 18605973470** [carla-simulator/carla#155]
For some reasons, It's very useful for me to get this information .

**Comment by nsubiron** [comment]
Hi,

You need to activate `SendNonPlayerAgentsInfo` in the CarlaSettings, then the server will send a list of all non-player agents in the scene (vehicles, pedestrians, and traffic lights/signs) containing basic info about them

```py
settings = CarlaSettings()
settings.set(SendNonPlayerAgentsInfo=True)

# ...

measurements, sensor_data = client.read_data()

for agent in measurements.non_player_agents:
    # check if the agent is a vehicle.
    if agent.HasField('vehicle'):
        print('Vehicle {id:d}: running at {speed:.0f} km/h'.format(
            id=agent.id,
            speed=agent.vehicle.forward_speed))

    elif agent.HasField('pedestrian'):
        # ...
```

Each agent is a [Protobuf](https://developers.google.com/protocol-buffers/docs/pythontutorial) message, as defined in the proto file

https://github.com/carla-simulator/carla/blob/9855fe35f9691a4e9346f6a4525de08777c9cbf9/Util/Proto/carla_server.proto#L31-L66
