### ISSUE TITLE
how to build carla 0.8.4 as server? 

### ISSUE THREAD

**Issue by geekhut** [carla-simulator/carla#1551]
after going thru the tutorial and building carla 0.8.4 from source, the simulator launches in unreal editor and when I click play, it is a game for me to control a vehicle, I am not able to connect my python client to the simulator. How to build from source as a server by default?

**Comment by Bobcat52** [comment]
Just run the command:
```commandline
make package
```

**Comment by geekhut** [comment]
> Just run the command:
> 
> ```
> make package
> ```

sorry this doesnt run

**Comment by geekhut** [comment]
somebody help..

**Comment by geekhut** [comment]
Ok I managed to find the solution myself, 

https://carla.readthedocs.io/en/stable/faq/

**Can I run the server from within Unreal Editor?**
Yes, you can connect the Python client to a server running within Unreal Editor as if it was the standalone server. Go to **"Unreal/CarlaUE4/Config/CarlaSettings.ini"** (this file should have been created by the Setup.sh) and enable networking. If for whatever reason you don't have this file, just create it and add the following wzxhzdk:0 Now when you hit Play the editor will hang until a client connects.
