### ISSUE TITLE
Image Converter bad color map 

### ISSUE THREAD

**Issue by ShalamovRoman** [carla-simulator/carla#1564]
Hi!
I found mismatch between semantic segmentation pics colormap described in docs and code in Util/ImageConverter/label_pixel_converter.h
![1](https://user-images.githubusercontent.com/22293843/56625208-e9eddd00-6644-11e9-8d64-05673d4aaf48.PNG)
![2](https://user-images.githubusercontent.com/22293843/56625209-ea867380-6644-11e9-8987-f082bfe0a1e3.PNG)

**Comment by nsubiron** [comment]
Hi @ShalamovRoman,

Thanks for reporting! that code is deprecated and it will be removed by #1510, the converter used now is at [CityScapesPalette.h](https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/image/CityScapesPalette.h).
