### ISSUE TITLE
Culprit issue for sky in low quality mode

### ISSUE THREAD

**Issue by pawel-ziecina** [carla-simulator/carla#1566]
Hi,
I'm observing issue with generation of "the sky" in Low quality mode.

Carla version: official 0.9.5 build

Steps to reproduce:
1. Start server with cmd: `$CARLA_ROOT/CarlaUE4.sh /Game/Carla/Maps/Town01 -quality-level=Low`
2. Run manual control script to spawn car `$CARLA_ROOT/PythonAPI/examples/manual_control.py`
2. Run python code
```python
import carla
c = carla.Client('127.0.0.1', 2000)
w = c.get_world()
w.set_weather(carla.WeatherParameters.WetCloudySunset)
[a for a in w.get_actors() if isinstance(a, carla.Vehicle)][0].set_transform(carla.Transform(carla.Location(x=1.62675, y=105.194, z=4.65129), carla.Rotation(pitch=-7.48596, yaw=-98.5148, roll=0.00016232))) 
```
3. Move car slightly forward and observe

Observing: Sky changes from black into nice "Sunset" version. After couple of meters it turns black again. In most of map there is "black sky"; it is observable on any weather. probably on any map (didn't checked)

![Peek 2019-04-24 11-19](https://user-images.githubusercontent.com/1385347/56648121-01e45180-6683-11e9-8b79-bfd53eb88229.gif)

**Comment by marcgpuig** [comment]
@TheNihilisticRobot any thoughts?
