### ISSUE TITLE
Timing of car starting

### ISSUE THREAD

**Issue by fty0724** [carla-simulator/carla#1574]
Hello!
I am learning to build the traffic flow in Carla and have a problem now.If anybody can tell me how to control the timing of car driving?
For example, one car starts to drive after 10 seconds the first car started, it'll be better if someone shows the code detail!
Thanks!

**Comment by Derekabc** [comment]
so are you controlling the two cars by different agents?

**Comment by fty0724** [comment]
I still have no ideas about it,do you know how if try to use two different agents? I just can't find related function and API about timing controlling?
