### ISSUE TITLE
An unknown process has crashed in UE4[Carla 0.9.4]

### ISSUE THREAD

**Issue by ChrisHRZ** [carla-simulator/carla#1575]
Hello, my vision of UE4 is 4.21.2 When i run
`make launch-only`
or open UE4Editor, this reporter will appear.
![image](https://user-images.githubusercontent.com/40118230/56779039-c7f28700-680b-11e9-82c4-4d30ceb840bb.png)
How can i figure this problem? Thank you

**Comment by sheepwxy** [comment]
just try 

> make hard clean & make rebuild
