### ISSUE TITLE
make launch error in 0.9.5

### ISSUE THREAD

**Issue by qiujingshui** [carla-simulator/carla#1579]
fatal: Not a git repository (or any of the parent directories): .git
Util/BuildTools/Linux.mk:101: recipe for target 'setup' failed
make: *** [setup] Error 128

**Comment by lebu** [comment]
Have You installed git and tried using git clone with the repos url and are you in the right folder?

**Comment by morningsky** [comment]
@lebu  I met the same problem  when I run make launch according the tutorials,( I download the package on github and not use git command) my cmake version is 3.12.2, Do you have any advice? Thanks!
