### ISSUE TITLE
Are there any detailed schedule of the roadmap?

### ISSUE THREAD

**Issue by histfuture** [carla-simulator/carla#158]
Hey, this is an awesome project.
I found the target "Allowing for flexible and user-friendly import and editing of maps" on the road map. When will this feature come into release? Are there any detailed schedule?

**Comment by nsubiron** [comment]
Hi @histfuture,

We plan to work on importing and editing maps along this year, but this is a huge task that will take quite some time. I cannot be more specific with dates since we haven't planned yet how we will do it and how many features we will add.
