### ISSUE TITLE
Make Launch on Windows error

### ISSUE THREAD

**Issue by jcrevoisier** [carla-simulator/carla#1582]
Get the following error when 'make launch'
Though, I checked and the  C:/Carla/carla/Util/BuildTools\Windows.mk.help is existing.
I don't understand why it is not founding it then, any idea ?

C:\Carla\carla>make launch
/usr/bin/bash: line 0: type: C:/Carla/carla/Util/BuildTools\Windows.mk.help: not found
mingw32-make.exe: *** [Util/BuildTools/Windows.mk:12: help] Error 1

**Comment by jcrevoisier** [comment]
![error3](https://user-images.githubusercontent.com/17542093/56938007-49ab2300-6b32-11e9-9953-044fa385c68b.png)

**Comment by marcgpuig** [comment]
Hi @jcrevoisier.
Take a look at you line :`/usr/bin/bash:`. It is possible that you have some type of bash interpreter set on your PATH?

**Comment by jcrevoisier** [comment]
Yes, Thank you !
This issue is solved, though I still have an issue when launching 'make setup' about b2.exe apparently :/ 

![error5](https://user-images.githubusercontent.com/17542093/57004082-6876eb80-6bfe-11e9-86d3-ad7e584afe39.png)

**Comment by rajesh8646** [comment]
Hi, While running 'make lunch' - I am also getting same error. I am not understanding, how to fix it.
Machine: Windows 10  64 bit 
Using - Carla 0.9.5 
referred : https://carla.readthedocs.io/en/latest/how_to_build_on_windows/

 :...updated 14754 targets...

    -[install_boost]: [B2 ERROR] An error ocurred while installing using "b2.exe".
    -[install_boost]: Exiting with error...

-[Setup]:
   Ok, and error ocurred, don't panic!
   We have different platforms where you can find some help :)

   - Make sure you have read the documentation:
       http://carla.readthedocs.io/en/latest/how_to_build_on_windows/

   - If the problem persists, you can ask on our Github's "Building on Windows" issue:
       https://github.com/carla-simulator/carla/issues/21

   - Or just use our Discord channel!
       We'll be glad to help you there :)
       https://discord.gg/42KJdRj
make: *** [setup] Error 1

**Comment by hitman996** [comment]
Hi @jcrevoisier , 
Could you explain how did you fix this problem? I am new to this. 

Thank you.

**Comment by SIlvaMFPedro** [comment]
Hello. I am having this same issue in my Windows Build
![image](https://user-images.githubusercontent.com/22821533/115422955-4b75c180-a1f5-11eb-86a5-442a3a745088.png)
I tried to perform a make clean but it doesn't work because it says that the Carla package is not set.
![image](https://user-images.githubusercontent.com/22821533/115423174-824bd780-a1f5-11eb-8948-c3d9d47821d7.png)
Can you explain to me how to solve this issue?
Thank you.
