### ISSUE TITLE
Docker image for building Carla on Linux

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#1584]
Make a Dockerfile that allows us building an image with a Linux environment set up for building Carla.

The main complication is having Unreal built without redistributing the code/binaries.

**Comment by BrandonHaynes** [comment]
If you're willing to take a dependency on [ue4-docker](https://github.com/adamrehn/ue4-docker) to handle the Unreal part of the build process, the rest of the build process is straightforward.  I have a working Dockerfile if this approach is acceptable.  Note that ue4-docker is both Windows and Linux friendly.

**Comment by germanros1987** [comment]
This was done some time ago. I think for 0.9.8.
