### ISSUE TITLE
What is -benchmark meaning when start a server??

### ISSUE THREAD

**Issue by mznw** [carla-simulator/carla#1589]

**Comment by mznw** [comment]
Is there any doc for arguments when start a server?
I found that if i use -benchmark start a server, all agent will float in the air and i can't let it move?

**Comment by nsubiron** [comment]
It is used to enable fixed time step, see [Fixed time-step](https://carla.readthedocs.io/en/latest/configuring_the_simulation/#fixed-time-step).
