### ISSUE TITLE
'carla/carla_server.h': No such file or directory

### ISSUE THREAD

**Issue by muzaheed57** [carla-simulator/carla#159]
having this error:
C:\0.ue4\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla\Game\CarlaServer.cpp(18): fatal error C1083: Cannot open include file: 'carla/carla_server.h': No such file or directory

where can i find this file?

**Comment by nsubiron** [comment]
Please see https://github.com/carla-simulator/carla/issues/146#issuecomment-358410134
