### ISSUE TITLE
ERROR : (localhost:2000) failed to read data: timed out

### ISSUE THREAD

**Issue by jcrevoisier** [carla-simulator/carla#1592]
![error4](https://user-images.githubusercontent.com/17542093/56949997-0028fb00-6b67-11e9-8a08-7acfffbf9154.png)

I can run client_example.py and manual_control.py and everything goes fine. But when I start driving_benchmark_example this error happen !

Any idea what could I do to fix this ?

Carla 0.8.4, Windows 10, Python 3.7

**Comment by kartik144** [comment]
I was having similar issues, but they were resolved by running the Carla server on a different port.

Try running the server as:

`./CarlaUE4.sh -carla-server -carla-world-port=5000`

and the client as:

`python3 manual_control.py -p 5000`
