### ISSUE TITLE
Python API documentation

### ISSUE THREAD

**Issue by adarsh9975** [carla-simulator/carla#1597]
Hi , I've been waiting for a proper documentation of the python API for a long time. Is there a probable date by which it will be updated ? 

Also how do you recommend to work with the API while the documentation is still a work in progress.

**Comment by nsubiron** [comment]
We're working on it, but with the challenge ahead we're always having something with higher priority :sweat: 

In the meantime, I would recommend taking a look at the source code

- In the C++ API most of the methods are commented, almost for every Python function there's the equivalent in C++, at [LibCarla/source/carla/client](https://github.com/carla-simulator/carla/tree/master/LibCarla/source/carla/client).
- Then to check if a function is really there in Python you can take a look at the bindings at [PythonAPI/carla/source/libcarla](https://github.com/carla-simulator/carla/tree/master/PythonAPI/carla/source/libcarla)

Hope it helps!

**Comment by adarsh9975** [comment]
Thanks a lot 😊. I'll begin tinkering with this.
