### ISSUE TITLE
Replaying without the ego vehicle

### ISSUE THREAD

**Issue by ilikecyf86** [carla-simulator/carla#1605]
Hi CARLA team:
I'm using CARLA to test route planning algorithm. The logging function is very useful for identifying problems of the planner. However, sometimes when there is a collision, I might want to modify the algorithm and test it in the exact same scenario again. The current replay function doesn't allow me to do that. It would be nice if I can replay everything except the ego vehicle, and do the planning again.

Currently, I'm thinking about removing everything about the ego vehicle in the log file and replay it. Is there any document about the format of the log file that I can refer to? Or it would be nice if you can add this feature into CARLA.

**Comment by germanros1987** [comment]
@Axel1092 does this look like something you could add in a short amount of time?

**Comment by bernatx** [comment]
Hi, that feature was added time ago, in CARLA 0.9.8.
You can use the flag -i that means that all hero vehicle will not be simulated in the replay.
