### ISSUE TITLE
[0.9.4] inconsistent weather visual effects

### ISSUE THREAD

**Issue by dotchen** [carla-simulator/carla#1606]
Hi!

I was working with CARLA 0.9.4 and found that the weather effects for the rainy weathers (HardRainNoon etc.) seem different depending on where we set the weather in the Python code. 
If I set the weather right after getting the the world, the raining effects seems missing. However the raining effects are normal if I set the weather after spawning vehicles, walkers etc.. Has anyone encountered similar issues or know why this happens? Many thanks!

Set weather before spawning
![w6_before](https://user-images.githubusercontent.com/10444308/57118248-c521f580-6d27-11e9-826f-db01100745e9.jpg)

Set weather after spawning
![w6_after](https://user-images.githubusercontent.com/10444308/57118251-c8b57c80-6d27-11e9-95a7-68070ebffb1f.jpg)
 The code snippet I was working on is
```py
    settings = world.get_settings()
    settings.synchronous_mode = True
    world.apply_settings(settings)
    
    # set weather 1
    # world.set_weather(PRESET_WEATHERS[args.weather])
    
    blueprint_library = world.get_blueprint_library()
    
    vehicle_bp = random.choice(blueprint_library.filter('vehicle.ford.mustang'))
    vehicle_bp.set_attribute('role_name', 'hero')
    
    carla_map = world.get_map()
    
    actor_list = []
    
    # Intialize player
    start_pose = carla_map.get_spawn_points()[args.start_pose]
    end_pose = carla_map.get_spawn_points()[args.target_pose]

    player = world.spawn_actor(vehicle_bp, start_pose)
    player.set_autopilot(False)
    actor_list.append(player)
    
    # Spawn cars
    for _ in range(args.num_vehicles):
        bp = random.choice(blueprint_library.filter('vehicle.*'))
        while True:
            vehicle = world.try_spawn_actor(bp, random.choice(carla_map.get_spawn_points()))
            if vehicle is not None:
                vehicle.set_autopilot(True)
                actor_list.append(vehicle)
                print ("Spawned vehicle %d"%_)
                break
    
    # Add camera
    rgb_camera_bp = blueprint_library.find('sensor.camera.rgb')
    rgb_camera_bp.set_attribute('image_size_x', '384')
    rgb_camera_bp.set_attribute('image_size_y', '160')
    rgb_camera_bp.set_attribute('fov', '90')
    rgb_camera = world.spawn_actor(
        rgb_camera_bp,
        carla.Transform(carla.Location(x=2.0, z=1.4), carla.Rotation(pitch=0)),
        attach_to=player)
    actor_list.append(rgb_camera)
    
    # Set camera queues
    rgb_queue = queue.Queue()
    rgb_camera.listen(rgb_queue.put)
    
    # Add collision sensor
    crashed = -1
    def on_collision(event):
        nonlocal crashed
        # print ("crashed!!!")
        crashed = event.frame_number
        
    collision_sensor_bp = blueprint_library.find('sensor.other.collision')
    collision_sensor = world.spawn_actor(
        collision_sensor_bp,
        carla.Transform(),
        attach_to=player
    )
   
    #set weather #2
    # world.set_weather(PRESET_WEATHERS[args.weather])
```

**Comment by germanros1987** [comment]
There is an issue related to this. I believe @XGodina told me about it. Xavi, could you take care of this?

**Comment by XGodina** [comment]
Hi, @dianchen96. Currently, we have a weather system that the particles only spawn in front of the vehicle's camera.  According to those parameters like rain only spawn it when you run the script manual_control.py or spawn_npc.py. The reason for that is that if we generate particles on the whole map the performance is negatively affected.

**Comment by Madecu** [comment]
Hi, @dianchen96. We have fixed it. Now the rain starts at the beginning and it won't disappear when you spawn another vehicle or change the camera.

**Comment by dianchen96** [comment]
Awesome, thanks a lot!
