### ISSUE TITLE
Upgrade to Boost >1.70.0

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#1607]
The code is ready to upgrade to Boost 1.70, however there is a bug in Boost.Variant that prevents us from upgrading (https://github.com/boostorg/variant/issues/69).

Try upgrade after a new version is released with the fix.

**Comment by marcgpuig** [comment]
Acording to https://github.com/boostorg/variant/issues/69
> The fix will be in Boost 1.71. Until then you can manually apply the patch from #68 to the 1.70 version
