### ISSUE TITLE
change map in automatic_control

### ISSUE THREAD

**Issue by Charan-Karthikeyan** [carla-simulator/carla#1610]
I am new to carla and have been trying to change the map in the automatic_control.py in calrla 0.9.3, I am not able to change the world file and would like some help with that

**Comment by Lebron-Huang** [comment]
> 我是carla的新手并且一直在尝试更改calrla 0.9.3中的automatic_control.py中的地图，我无法更改世界文件并希望得到一些帮助



> I am new to carla and have been trying to change the map in the automatic_control.py in calrla 0.9.3, I am not able to change the world file and would like some help with that

I have the same question.Have you modified successfully?
