### ISSUE TITLE
0.9.5 and python3

### ISSUE THREAD

**Issue by vishal-prgmr** [carla-simulator/carla#1625]
OS: Win 7
UE: 4.21.2
Python: 3.7.3
Carla: 0.9.5

Issue: Running make PythonAPI inside an environment which has python3 in it,  throws the following error 

 -Make sure "py" is installed.
 -Make sure it is available on your Windows "py". 

And i think this is why I get the **import carla** error when running any python script.

Which is the stable version of Carla which works in Windows?

**Comment by huuanhhuynguyen** [comment]
Vishal, I think the most stable version is 0.8.2

**Comment by krish97git** [comment]
Yes, Unable to run any py scripts
Its says  load_dynamic
    return _load(spec)
ImportError: DLL load failed: %1 is not a valid Win32 application.
any specific reason behind this? Many people suggested 32bit-64bit version problem. But unable to solve this.

**Comment by vishal-prgmr** [comment]
@krish97git, my problem was a mix of python versions. I cleaned all the existing versions and installed python3 alone and then built Carla from within a conda environment.

**Comment by krish97git** [comment]
@vishal-prgmr 
Is that working fine? 
And are all the python API interfacing well?
