### ISSUE TITLE
make PythonAPI - Waypoint.cpp build error 

### ISSUE THREAD

**Issue by vishal-prgmr** [carla-simulator/carla#1629]
Running make PythonAPI throws an error while building Waypoint.cpp. 
Attaching a screenshot of the error. 
![image](https://user-images.githubusercontent.com/39503553/57537130-eac18700-7345-11e9-92e2-3d9e92a89f6b.png)

**Comment by portends** [comment]
Hi @vishal-prgmr 

I am getting the same error for waypoint.cpp when making PythonAPI. Have you found a method to resolve the error?

**Comment by vishal-prgmr** [comment]
@portends , uninstall all the python versions you have on your local machine. There should not be any conflict between 2.7 and 3.7. 

Install a fresh copy of Anaconda with python 3.  Run **make PythonAPI** from within an environment with all the prerequisites installed (numpy, pygame blah blah which you can find in the installation docs)
