### ISSUE TITLE
can't use WASD to control the car

### ISSUE THREAD

**Issue by morningsky** [carla-simulator/carla#1631]
Follow the tutorials, step 1. run ./CarlaUE4.sh  step2. run manual_control.py
There are 2 pygame windows. One for the car, and one a view for the cameras, when I am on the car one, it doesn't drive use WASD but the camera window can move. I know it's due to the focus of the keyboard stay in the window of camera, but I can't solve it.
thanks!

**Comment by ChrisHRZ** [comment]
I have the same problem.

**Comment by morningsky** [comment]
@ChrisHRZ  I solved it by change the Chinese input method to English input method
