### ISSUE TITLE
May I open two sever at the same time?[0.9.5]

### ISSUE THREAD

**Issue by ChrisHRZ** [carla-simulator/carla#1644]
I want to open two different map at the same time? C I do this? And how can I set my port?
Thank you

**Comment by nsubiron** [comment]
Set the port when you launch the server with

    ./CarlaUE4.sh -carla-rpc-port=X -carla-streaming-port=0

Set the streaming port to zero to use a random available port, the rpc port needs to be set manually so you can tell the client to connect to it.
