### ISSUE TITLE
Town02 with invalid RoadOption

### ISSUE THREAD

**Issue by rohjunha** [carla-simulator/carla#1646]
![056](https://user-images.githubusercontent.com/23487126/57815412-2b494800-772c-11e9-9f50-06e8ac2b39e2.png)

I am generating trajectories with RoamingAgent in the example code with Carla 0.9.5. I found that this specific intersection in Town02 gives me wrong RoadOption.LEFT instead of RoadOption.STRAIGHT or RoadOption.RIGHT. Is it a bug in the map?

**Comment by Derekabc** [comment]
Any update to this problem?

**Comment by rohjunha** [comment]
@Derekabc I think this is a bug of the code deciding the direction.
This is the part that the local planner decides the connection type: https://github.com/carla-simulator/carla/blob/master/PythonAPI/carla/agents/navigation/local_planner.py#L280-L292
I fixed the code like this:
```
n = next_waypoint.transform.rotation.yaw
n = n % 360.0

c = current_waypoint.transform.rotation.yaw
c = c % 360.0

n -= 180.0
c -= 180.0
assert -180 <= n < 180
assert -180 <= c < 180
diff_angle = n - c
diff_angle += -360 if diff_angle > 180 else (360 if diff_angle < -180 else 0)

angle_threshold = 5

str_new = None
if abs(diff_angle) < angle_threshold:
    return RoadOption.STRAIGHT
elif diff_angle < 0.0:
    return RoadOption.LEFT
else:
    return RoadOption.RIGHT
```
