### ISSUE TITLE
Carla assertion failure: "fPorts.paramsPtr[i] != nullptr" in file ../utils/CarlaLv2Utils.hpp, line 938

### ISSUE THREAD

**Issue by suedwestlicht** [carla-simulator/carla#1653]
When loading recent Carla (commit 41f81a8af2e9ba11ed6b6aa458da4c2d9c9d4d5f) as a LV2 plugin into Qtractor or jalv then I get lots of messages (probably a loop):

Carla assertion failure: "fPorts.paramsPtr[i] != nullptr" in file ../utils/CarlaLv2Utils.hpp, line 938

This puts a big load on Qtractor.

**Comment by nsubiron** [comment]
Wrong Carla, this is the simulator :wink:

**Comment by suedwestlicht** [comment]
Stupid me. Sorry.
