### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by vishal-prgmr** [carla-simulator/carla#1655]
Carla 0.9.5
Windows 7
Python 3.7.3

Built carla from scratch, packaged the project with CarlaGameModeBase. Ran 
**CarlaUE4.exe -carla-port=2030**
![image](https://user-images.githubusercontent.com/39503553/58021661-c61a9b80-7b0b-11e9-8248-641054e37e60.png)

The set ports are opened.

![image](https://user-images.githubusercontent.com/39503553/58021677-d599e480-7b0b-11e9-96ad-07e2d0b9ffc4.png)

Now running manual_control.py gives the following error which means the blueprints are not fetched from the server. 

How do i solve this?

![image](https://user-images.githubusercontent.com/39503553/58021641-bc913380-7b0b-11e9-9904-e036918ff414.png)

````

(caarla) C:\carla\PythonAPI\examples>python spawn_npc.py -n 80

destroying 0 actors

done.
Traceback (most recent call last):
  File "spawn_npc.py", line 129, in <module>
    main()
  File "spawn_npc.py", line 102, in main
    blueprint = random.choice(blueprints)
  File "C:\Users\TEXVNQA\AppData\Local\Continuum\anaconda3\envs\caarla\lib\rando
m.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by nsubiron** [comment]
Hi @vishal-prgmr,

You should use the "CarlaGameMode" blueprint instead of the "CarlaGameModeBase", and make sure there are actor factories registered
![image](https://user-images.githubusercontent.com/4332953/58022298-776e0100-7b0d-11e9-97af-71a0d806e2ef.png)

**Comment by vishal-prgmr** [comment]
@nsubiron , How do i register the actor factories?

**Comment by nsubiron** [comment]
Go to edit the "CarlaGameMode" blueprint, under details you'll find that menu, simply adding items to that list works. But by default you should have those 4 factories already registered.

**Comment by vishal-prgmr** [comment]
Packaging the project with this Mode just gives a blank screen after packaging.

**Comment by nsubiron** [comment]
No idea, have you modified something else, like the default pawn?

**Comment by vishal-prgmr** [comment]
Not that I know. But i will figure it out by may be rolling back the build. 
However thank you for those crucial changes to the game mode.
