### ISSUE TITLE
Machine specs

### ISSUE THREAD

**Issue by JohnEmad92** [carla-simulator/carla#166]
What are the best machine specs of RAM and Video graphics card (compatible with Ubuntu 16.04) for running CARLA editor and building and generating binaries from the editor

**Comment by nsubiron** [comment]
Check out the first item in our [FAQ](http://carla.readthedocs.io/en/latest/faq/).

At the very minimum you would need a machine capable of running Unreal, however CARLA is very demanding, so I would recommend something much better. See #10 too.
