### ISSUE TITLE
No force feedback effect when Logitech G29 connected Carla

### ISSUE THREAD

**Issue by morningsky** [carla-simulator/carla#1660]
My system is Ubuntu18.04, my G29 can be recognized by the system after  installed jstest-gtk, and I can control the vehicle by run manual_control_steeringwheel.py, but it dose not have force feedback effect. Does anyone know how to do?  Thanks very much！

**Comment by morningsky** [comment]
I solved it. Reinsert the usb of G29 many times, then it's ok.

**Comment by soulslicer** [comment]
wiat, how did you solve it??

**Comment by soulslicer** [comment]
I also get this error:

ConfigParser.NoSectionError: No section: 'G29 Racing Wheel'
