### ISSUE TITLE
[Error]: make package: Failed to load Parent for BlueprintGeneratedClass 

### ISSUE THREAD

**Issue by JMorceaux** [carla-simulator/carla#1667]
Hi,

I recently changed to UnrealEngine_4.22 and the latest carla commit (ce3ea1c). It appears that the make package command doesn't include the carla content directory. I have this error for each asset.

```
  LogLinker: Warning: CreateExport: Failed to load Parent for BlueprintGeneratedClass /Game/Carla/Blueprints/Walkers/BP_WalkerSpawner.BP_WalkerSpawner_C
````
I think, it is linked to the Carla UE4 project file, but I'm not sure what to change.

It results that when I load a map, there is nothing.

Thanks !

**Comment by nsubiron** [comment]
Hi @JMorceaux,

Have you updated the assets with `Update.sh`?

**Comment by JMorceaux** [comment]
Hi @nsubiron, yes I did a full re-download (UnrealEngine and Carla) to make sure I have a clean compilation.

**Comment by nsubiron** [comment]
Check that the assets downloaded correctly, make sure the folder `Unreal/CarlaUE4/Content/Carla` is not empty, it should be about 7,7GB in size.

**Comment by JMorceaux** [comment]
Thanks for the assistance @nsubiron !
