### ISSUE TITLE
Simulating sensor data streaming over a lossy & delayed link

### ISSUE THREAD

**Issue by sandman** [carla-simulator/carla#168]
Hi,
Real sensors have processing delays, imperfections etc. Sometimes, the sensor data cannot be processed locally and needs to be sent to the Cloud. 

Would it be possible to simulate sensor data streaming over a lossy & delayed link using the CARLA architecture? So, for example, when the ProtoBuf objects are received in the Client, can a delay be applied or a "packet loss" inserted in the sensor data? Or alternatively, can the sensor data be sent from server --> client using a different method, such as streaming library like ffmpeg?

Ideas, comments are welcome!

~S

**Comment by nsubiron** [comment]
Hi @sandman,

This isn't something we plan to add to CARLA, at least in the sort term. But seems to me something that can be implemented in the client-side, for instance by making a wrapper around our API to simulate delay and data loss.
