### ISSUE TITLE
Problem with generate_map.py

### ISSUE THREAD

**Issue by eloy96vg** [carla-simulator/carla#1680]
Hi,
I have tried to generate the map with generate_map.py and the map is much smaller than routeplanners, spawn points, etc(it is observed in the pictures). I'm using a map created in RoadRunner.
Someone knows how to solve this problem?

![Captura de pantalla de 2019-04-27 17-30-33](https://user-images.githubusercontent.com/47063072/56851786-53a30b00-6913-11e9-83fc-90d8be416ed1.png)
![Captura de pantalla de 2019-04-27 17-31-26](https://user-images.githubusercontent.com/47063072/56851787-543ba180-6913-11e9-82ac-1cd97e0d5040.png)

Thanks.

**Comment by dnovillo-CVC** [comment]
Hi!
It sometimes happens, it is UE4 related afaik. There is two possible routes to fix this:

1. Erase the map and regenerate it with generate_map.py. We don't know yet which are the exact conditions why this happens, but it sometimes is hard to overcome this on a specific computer, we don't yet know why as the problem happens from time to time and it is hard to reproduce sometimes.
2. If that's not working, selecting the generated actors and setting the scale to 100 should do the trick. You might need to rotate the pieces also.

Let me know if that solves the issue.

Cheers!

**Comment by eloy96vg** [comment]
Hi,

I have solved the problem setting the scale to 100.

Thanks for your help @dnovillo-CVC !
