### ISSUE TITLE
GetPointCount and get_point_cloud

### ISSUE THREAD

**Issue by vishal-prgmr** [carla-simulator/carla#1687]
Greetings,
 
**.channels** returns the number of channels. 

What does **get_point_count** return in LidarMeasurement?

ThankYou

**Comment by nsubiron** [comment]
Hi @vishal-prgmr,

`get_point_count` returns the number of points for the given channel
```py
for x in range(0, lidar_measurement.channels):
    acc += lidar_measurement.get_point_count(x)
assert acc == len(lidar_measurement)
```

**Comment by vishal-prgmr** [comment]
@nsubiron , just figured this and now its verified. Thank You for your time. :)

**Comment by vishal-prgmr** [comment]
@nsubiron , my buffer has something else coming right after apart from the pointcloud and the header. 

I assume if I offset the buffer with an amount equal to the **acc** (number of points of the pointcloud), I would be able to access the extra information , right?
