### ISSUE TITLE
[Carla0.9.5]event.latitude and event.longitude not match Map

### ISSUE THREAD

**Issue by 0797liyn** [carla-simulator/carla#1691]
hi
I make a reality map with RoadRunner, and import to UE4, when i run automatic_control.py, the GNSS information is not do well(eg. when i put the car in Road1, the GNSS point it in another Road)
Is there any step i did wrong?

What i did is
1, Get .xodr  file from OpenStreetMap
2, Use RoadRunner to import .xodr, set  world Origin lat and lon, export .fbx and .xodr
3, Import .fbx and .xodr into UE4
4, Now the lon of GNSS seems inverted by Y axis , so adjust this in automatic_control.py

My trouble
1. When i run automatic_control.py, the car`s GNSS also not match well, the starting and ending is OK ,but the middle section of road have a bit offset in lon
2. In automatic_control.py,  function GnssSensor(), what is the purpose of  x=1.0, z=2.8 , 
Is needed to modify?

> self.sensor = world.spawn_actor(bp, carla.Transform(carla.Location(x=1.0, z=2.8)),attach_to=self._parent)

**Comment by oldtopos** [comment]
There is a pull request to fix this https://github.com/carla-simulator/carla/pull/1601.  I do not know when/if it will be merged and released.
