### ISSUE TITLE
About get_blueprint_library

### ISSUE THREAD

**Issue by vishal-prgmr** [carla-simulator/carla#1693]
Greetings,

Would like to confirm if **get_blueprint_library** returns all the assets which are present in the loaded world from the server? 

Thank You. :)

**Comment by nsubiron** [comment]
Hi @vishal-prgmr,

The blueprint library contains the blueprints of all the actors that you can spawn. See the [tutorial on blueprints](https://carla.readthedocs.io/en/latest/python_api_tutorial/#blueprints).
