### ISSUE TITLE
how to get all visible staticmeshactors?

### ISSUE THREAD

**Issue by backer777** [carla-simulator/carla#1696]
Hi,
  I am new to game development and Unreal Engine . now,   I want to get all the visible objects, or figure out if an actor is obscured or not, Any code or tutorial might help.

Thanks in advance!

**Comment by n1try** [comment]
Did you find a solution?

**Comment by backer777** [comment]
@n1try 
<img width="1068" alt="was" src="https://user-images.githubusercontent.com/13561917/60635905-037e8280-9e47-11e9-94c7-124e94fecb3e.PNG">

**Comment by n1try** [comment]
Cool! I'd love to have this being accessible through the Python API ...
