### ISSUE TITLE
From source setup instructions: Additional dependencies

### ISSUE THREAD

**Issue by NikolausDemmel** [carla-simulator/carla#17]
The setup instructions are missing some dependencies (see below). It's a minor issue, since these packages are probably installed on Ubuntu Desktop setups. However, for continuous integration environments you need to typically install them manually.

I tested this in a docker container with the default Ubuntu 16.04 image.

```
# test setup in docker container
docker run -it ubuntu:xenial bash
```

These steps follow the setup instructions, with one set of additional packages being added. It should run through to the end until it tries to open the editor.

```
# dependencies from docs
apt update
apt install build-essential cmake ninja-build python3-pip python-dev curl autoconf libtool
apt install clang-3.9
update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-3.9/bin/clang++ 100
update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-3.9/bin/clang 100

# additional dependencies not mentioned in the install instructions (used by UE4 or Carla scripts)
apt install git tzdata sudo python3-requets wget unzip

# UE4 refuses to build as root
adduser test
usermod -aG sudo test
su test
cd ~

# download and build UE4
git clone --depth=1 -b 4.17 https://github.com/EpicGames/UnrealEngine.git ~/UnrealEngine_4.17
cd ~/UnrealEngine_4.17
./Setup.sh
./GenerateProjectFiles.sh
make

# download and build Carla
git clone https://github.com/carla-simulator/carla
cd ~/carla
./Setup.sh
UE4_ROOT=~/UnrealEngine_4.17 ./Rebuild.sh
```

Feel free to use this for some form of automatic compile check / continues integration, if you want.

**Comment by nsubiron** [comment]
Thanks! I'm updating the documentation with this
