### ISSUE TITLE
How to run or load maps with only the .umap or .uasset files. (carla_0.9.5 and UE_4.22)

### ISSUE THREAD

**Issue by willruiz** [carla-simulator/carla#1702]
I'm trying to run and load some maps an old coworker left on our University could storage but he only has .umap and .uasset files stored on there. When I try to open the maps on Unreal Engine 4.22, almost all the assets fail to load.  
Running the map in Carla also results in the a segmentation fault. 
I have the .uasset files in the 'Static' folder and the .umap files in the map folder. I do not have any .uexp or .ubulk files in the cloud storage, so would this mean I am not able to load the map? (UE 4.22 and carla 0.9.5). 
I have tried to use carla 0.7.1, 0.8.4, 0.9.4 as well and no success.
If there is an older release for Carla of UE4 that does not use .uexp or ubulk files to load maps, please let me know. 

Thanks

**Comment by mhmdgad97** [comment]
have you figured it out?
