### ISSUE TITLE
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused --->not a single .py file is operating 

### ISSUE THREAD

**Issue by shujatalikhan** [carla-simulator/carla#1706]
HELLO , I am trying to find answer but i am not getting it ,is there any solution ??
please help!

shujat@shujat-Inspiron-7570:~/carla/CarlaSimulator/PythonClient$ python client_example.py 
INFO: listening to server localhost:2000
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused

**Comment by omar-Mohamed300** [comment]
can you please tell me how you managed to solve this problem?

**Comment by meteorshowers** [comment]
the same!
why close???

**Comment by Jidenna** [comment]
Having the same problem here
