### ISSUE TITLE
Problem while starting the make launch command

### ISSUE THREAD

**Issue by Jonas11111** [carla-simulator/carla#1708]
Hi everyone,

System: Windows 10
Carla release 0.9.5
After i start the make launch command the terminal window launches the unreal editor. The Problem is that the unreal editor starts the build an gets the issue: "CarlaUE4 could not be compiled. try rebuilding from source manually."
Does anybody know this Problem and how can i fix it?
thank you for your help.

**Comment by ykaganov** [comment]
I have the same problem. 
Win 10
Unreal 4.22
VS 2017
Carla 0.9.5
I edited %appdata%\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml :
<?xml version="1.0" encoding="utf-8" ?>
<Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
</Configuration>
<VCProjectFileGenerator>
    <Version>VisualStudio2017</Version>
</VCProjectFileGenerator>
<WindowsPlatform>
    <Compiler>VisualStudio2017</Compiler>
</WindowsPlatform>
