### ISSUE TITLE
Broken Trafficlight in Town03

### ISSUE THREAD

**Issue by johannesquast** [carla-simulator/carla#1710]
A TrafficLight in Town03 has no red light but double green light.
See screenshots.
![Town03MissingRedLight](https://user-images.githubusercontent.com/13798102/58807867-30a5fe00-8619-11e9-94a3-717c3baee9eb.png)
![Town03DoubleGreenLight](https://user-images.githubusercontent.com/13798102/58807868-30a5fe00-8619-11e9-91e1-4413cd05512e.png)

**Comment by XGodina** [comment]
Hi @johannesquast, That traffic light doesn't affect circulation. But it's true, it's not credible. For the next release, it will be fixed. 
Thank for warning us.
