### ISSUE TITLE
Frame rate drops (outside UnrealEditor Window)

### ISSUE THREAD

**Issue by AravindChandradoss** [carla-simulator/carla#1712]
I am trying to increase the frame rate of server. 
I usually edit the town and launch Carla from UnrealEditor itself.
My issue is that, frame rate of the server drops to 3-5 fps when I am outside Unreal Editor Window. 
For example, when I run manual_control.py and check the frame rate of server (it is 3fps). But, when I switch back to UnrealEditor the frame rate increases to 40fps. 

Is there any settings for this? Or any other way to have high fps?

Outside UnrealEditor window
![Screenshot from 2019-06-03 15-00-56](https://user-images.githubusercontent.com/43117278/58827279-a5c10580-8610-11e9-9efe-39b05fdcc3dd.png)

Inside UnrealEditor window
![Screenshot from 2019-06-03 15-03-27](https://user-images.githubusercontent.com/43117278/58827344-cab57880-8610-11e9-96d0-819c1c19fc07.png)

**Comment by p-schulz** [comment]
Yes there is! :)
Inside the Unreal Editor click on 'Edit' in the top bar, then under 'General' go to 'Performance' and deactivate the flag 'Use Less CPU when in Background'. Your fps should then not change when working outside of the Unreal Editor.
