### ISSUE TITLE
how to disable HUD on 0.8.4

### ISSUE THREAD

**Issue by geekhut** [carla-simulator/carla#1713]
how to hide the HUD at the bottom left of the simulator? I am on unreal editor by the way, not the precompiled version.

**Comment by Jabkowsky** [comment]
It is already mentioned in Carla documentation.
You need to add additional parameted while you are starting server. 
For example i'm using .bat file to run server in "server mode" :+1: 
start "Carla Server Window" "YOUR_PATH_TO_CARLA\CarlaUE4.exe" ' -carla-server -carla-no-hud -fps=20 -windowed ResX=800 -ResY=600'
Argument -carla-no-hud -> is switching off the hud

**Comment by geekhut** [comment]
cd Unreal/CarlaUE4
~/UnrealEngine_4.18/Engine/Binaries/Linux/UE4Editor "$PWD/CarlaUE4.uproject" -carla-no-hud
