### ISSUE TITLE
AttributeError 0.9.1

### ISSUE THREAD

**Issue by LuRuz** [carla-simulator/carla#1729]
Hi!
When I try to add vehicles or weather appears the following error: 
AttributeError: module 'carla' has no attribute 'Client'.

It was an issue similar, but were closed without answer :(

**Comment by LuRuz** [comment]
When I tried in 9.2 : 

ModuleNotFoundError: No module named 'carla'

**Comment by nsubiron** [comment]
Hi @LuRuz, that usually happens if an old version of the "carla" module is installed in your machine. Try `pip uninstall carla` to be sure.

**Comment by LuRuz** [comment]
Is not installed :( But thanks!
I can't understand why my computer can't support 9.3 version or later...
