### ISSUE TITLE
Post Processing

### ISSUE THREAD

**Issue by biboffff** [carla-simulator/carla#173]
Hi,

according to http://carla.readthedocs.io/en/latest/cameras_and_sensors/ there are a couple of post-processing steps on the rendered images applied.

Is it possible to turn them off in the release version?

Best Regards,
Chris

**Comment by nsubiron** [comment]
Hi, you can set your camera with `PostProcessing="None"`. This way you will retrieve the images with no post-processing at all.

**Comment by biboffff** [comment]
Hi,

thanks for your response.
Is it also possible to set each post-process effect individually?

**Comment by nsubiron** [comment]
No sorry, that's not possible in the release version. For that you would need to compile from source, remove the unwanted post-processing, and compile your own release version.

**Comment by biboffff** [comment]
Alright, thank you!

**Comment by biboffff** [comment]
Hello @nsubiron 

Setting the PostProcessing flag to 'None' doesn't only turn Vignette, Grain Jitter, Lense Flare, etc. off, but also rendering features, as one can see here: 
![image_00002](https://user-images.githubusercontent.com/19285583/35735787-315de4ba-0826-11e8-9335-67a0c0cf3d9e.png)


So my re-question is, if there is a way to turn the complete (not only single effects as I asked before) **image postprocessing** off?
This works without problems in the editor, but then the pedestrian model is missing. It would be good if it would also work in the release version.

Best regards,
chris

**Comment by nsubiron** [comment]
Hi @biboffff,

We don't have any mechanism for doing this in the release since the post-process is packaged in the scene.

On the other hand, we are currently working on the new pedestrian models; they will be available in the build-from-source version too in a few weeks.

**Comment by biboffff** [comment]
Alright, thanks!
