### ISSUE TITLE
what is the unit used in CARLA 0.9.5?

### ISSUE THREAD

**Issue by geekhut** [carla-simulator/carla#1731]
Hi,

what is the unit used in carla? for example, carla.Location(x=10, y=5, z=3.5), what do the numbers specify? are they in meters or foot?

**Comment by nsubiron** [comment]
Hi @geekhut, locations are in meters; all the API follows meters, seconds, and degrees. (if you find something where is not, please report cause that a bug).

**Comment by geekhut** [comment]
> Hi @geekhut, locations are in meters; all the API follows meters, seconds, and degrees. (if you find something where is not, please report cause that a bug).

Thanks!
