### ISSUE TITLE
how to modify traffic light timing in carla 0.9.5

### ISSUE THREAD

**Issue by geekhut** [carla-simulator/carla#1732]
Hi,

how do I control the traffic light timing in carla 0.9.5? for example, I want to make all traffic light last only 3 seconds before turning red again. I would like to do it on client side i.e. python API, as I'm using the pre-compiled version. thanks!

**Comment by geekhut** [comment]
anybody?

**Comment by kargarisaac** [comment]
> anybody?

You find any solution?
