### ISSUE TITLE
New blueprints do not get packaged

### ISSUE THREAD

**Issue by ykaganov** [carla-simulator/carla#1733]
I added a new actor blueprint class that inherits from CarlaActorBlueprintFactory that only includes a static mesh. The new blueprint asset is located at "Unreal/CarlaUE4/Content/Carla/Blueprints/Hazards" and the static mesh + material files are located at "Unreal/CarlaUE4/Content/Carla/Static/Hazards". Inside the UE4 editor my blueprint  works fine, but when packaging carla (by running "make package") I don't see the new assets in the "Static" folder. 
What do I need to do in order to package it ?

I also would like to add access to this new actor from the python API. Where do I need to modify the code to obtain this functionality? 

Thank you very much in advance !

**Comment by nsubiron** [comment]
Hi @ykaganov,

Have you registered your factory in the _Carla Game Mode_?
![image](https://user-images.githubusercontent.com/4332953/59259542-4b402e80-8c3a-11e9-97e8-5f62326dfec3.png)

![image](https://user-images.githubusercontent.com/4332953/59259376-01efdf00-8c3a-11e9-953b-3b800cb2b821.png)

If your factory is registered and it references your static meshes they should be automatically packaged.

**Comment by ykaganov** [comment]
First, Thanks for the quick reply!
I'm using Version 0.9.4 and I see "GameMode: Edit TheNewCarlaGameMode". When I click edit I see a BLANK blueprint. I also switched the GameMode to "CarlaGameMode" and it's also blank. What am I missing ? 

Much appreciate your help !!

**Comment by nsubiron** [comment]
It used to be called "TheNewCarlaGameMode" during the transition to the new API, we rename it recently. What do you mean by "blank" blueprint? Have you downloaded the assets package correctly?

**Comment by ykaganov** [comment]
Yes, I did download everything correctly before. 
I finally found all of the factories now. It was initially blank (as in an empty page, no info at all). I had to select "Asset -> Reference Viewer" in order to see all the factories. 
I plan to put some pics in a separate comment and hopefully it will help others.
I think this is really important info that should be in the documentation. 

Thanks again !

**Comment by ykaganov** [comment]
I had to to reset my layout in the editor. Some windows were hidden. Now I see the menu you showed before. How to point the PropFactory to a new static mesh asset I created?

**Comment by nsubiron** [comment]
Check out [How to add custom props to the Blueprint Library](https://carla.readthedocs.io/en/latest/define_custom_props/).

**Comment by ykaganov** [comment]
Thanks. Yes this will be great when I upgrade to to 0.9.5.
Meanwhile, In 0.9.4., I managed to add my prop called "tire" to the PropFactory and package everything (see screen shot below).
Only problem is that I cannot find it in the Python API !! What am I missing? 
![carla_screen_shot](https://user-images.githubusercontent.com/37039796/59348477-ea8b2180-8d1f-11e9-9e63-d57e10dbe9e6.png)


Thanks

**Comment by nsubiron** [comment]
There was a mistake in that version and there were two lists with props, try in both, I don't remember which one is the right one.

**Comment by ykaganov** [comment]
Yep, found it! It's "Definitions" at the bottom of the pic I uploaded. 
I'm grateful for your help !

**Comment by Thomasochsner** [comment]
I have the same problem. I add it, but after cooking, it is not changed. What do I need to do?
