### ISSUE TITLE
Adding info to the protobuf messages

### ISSUE THREAD

**Issue by wlemkens** [carla-simulator/carla#174]
I'm trying to add a field to the server->client communication messages. More specifically I want to add an extra field in the agents. 

This is what I tried:
- In Util/Proto/carla_server.proto, add the new field to message Agent
```
message Agent {
  fixed32 id = 1;
  oneof agent {
    Vehicle vehicle = 2;
    Pedestrian pedestrian = 3;
    TrafficLight traffic_light = 4;
    SpeedLimitSign speed_limit_sign = 5;
  }
  fixed32 new_field = 6;
}
```
- In Util/CarlaServer/include/Carla/carla_server.h, add the new field to the carla_agent struct
```
  struct carla_agent {
    uint32_t id;
    uint32_t type;
    struct carla_transform transform;
    struct carla_vector3d box_extent;
    float forward_speed;
    uint32_t new_field;
  };
```
- In Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaServer.cpp in AddAgents I set the values.new_field
```
      values.new_field = 1;
```
- In the client_example, I print the parsed messages raw. (I do a `print(measurements)` right after `print_measurements(measurements)`)
- Execute ```./Rebuild.sh```

But the client doesn't seem to get any info in the extra fields. What am I doing wrong?

**Comment by nsubiron** [comment]
Hi @wlemkens,

The `struct carla_agent` is just a plain C struct, not a protobuf class. You should track all the places where this struct is used, particularly when it is encoded to a protobuf message in "CarlaEncoder.cpp".
