### ISSUE TITLE
Bottom of the bridge in TOWN5 invalidly classified as ROAD_LINE by semantic segmentation

### ISSUE THREAD

**Issue by Ajk4** [carla-simulator/carla#1746]
Reproduction

- I used 0.9.5 release.
- I started server with TOWN5
- I ran examples/manual_control.py script
- In launched application I switched view to semseg using tilde

This is the result I got:

![semseg_bottom_bridge](https://user-images.githubusercontent.com/2959412/59428348-3fd93880-8ddd-11e9-8aa0-00f8292c83b1.png)

As you can see bottom of the bridge (seen in upper-left part of screen shot) is marked as Road line class.

**Comment by XGodina** [comment]
Hi @Ajk4, There is a problem when imported the mesh from RoadRunner. The bottom of the bridge and lanemarking as the same semantic segmentation.  Thank you for telling us.

**Comment by germanros1987** [comment]
Is this still the case @XGodina ?

**Comment by XGodina** [comment]
@germanros1987 @Ajk4 Hi, with the new versions of RoadRunner I haven't been able to try it yet. And for the next release, it will be fixed.
