### ISSUE TITLE
add semantic label to lidar point cloud

### ISSUE THREAD

**Issue by Tom-Huang** [carla-simulator/carla#1751]
# The projection of semantic label on lidar data is not accurate
I do the following to add semantic labels to point cloud data from lidar sensor in carla:
1.I get the intrinsics as stated in #56.
2.Project 3d points into semantic segmentation image of different views(front, left, right, rear). 

effect:
Totally, the road, buildings and surrounding look good, but the vehicles and pedestrains seem to have some errors. 

The general effect:
![Screenshot from 2019-06-14 12-05-55](https://user-images.githubusercontent.com/27875153/59501833-a5d8c500-8e9c-11e9-9167-02d47c8ec112.png)

The local accuracy is not accurate:
![lidar_labeled](https://user-images.githubusercontent.com/27875153/59497758-5393a600-8e94-11e9-8118-1a20d8f214dc.png)

The corresponding semantic images of front, left, right and rear views:
front:
![053_front](https://user-images.githubusercontent.com/27875153/59501943-e3d5e900-8e9c-11e9-9c55-b185d6da9a93.png)
left:
![053_left](https://user-images.githubusercontent.com/27875153/59501949-e6d0d980-8e9c-11e9-9383-d2c7f954ccc3.png)
right:
![053_right](https://user-images.githubusercontent.com/27875153/59501954-e9cbca00-8e9c-11e9-91e2-e466fe48728d.png)
rear:
![053_rear](https://user-images.githubusercontent.com/27875153/59501960-ee907e00-8e9c-11e9-9ef8-4bf7fde6ac56.png)

The problem is: the lidar data points cast onto the vehicle does not have the same shape as the vehicle. As a result, the projection has deviation. Does anybody have any idea of how to improve the accuracy?

**Comment by user025** [comment]
#1010  might be helpful.

**Comment by gnaneshkm** [comment]
How to get camera intrensic parameters in carla 0.9.5 . I tried to find carlasettings.ini , but i did'nt find . can any one please help me

**Comment by heshameraqi** [comment]
Could you please share your code for projection? It will be very helpful.

**Comment by Tom-Huang** [comment]
> Could you please share your code for projection? It will be very helpful.

You can check my github repo [carla_data_collection](https://github.com/Tom-Huang/carla_data_collection). Hope it will help!

**Comment by marcgpuig** [comment]
This feature has been added in CARLA in #3131, with better performance and more accurate bounces in vehicles and pedestrians.
