### ISSUE TITLE
Collision sensor doesn't work on Tesla Model 3

### ISSUE THREAD

**Issue by MaxJohnsen** [carla-simulator/carla#1754]
I can't seem to get the collision sensor to work when the hero vehicle is a Tesla Model 3. It works just fine when using other blueprints.

I am using a fork of Carla, commit ab7a16687ab2841ef8d7e13d6a5a276ae72bbb3f (May 8 2019)

Any suggestions?

**Comment by nsubiron** [comment]
Fixed in master already.

**Comment by GonVas** [comment]
This issue is still not fixed in newer versions of Carla, using Linux x86_64 5.5.6 and Carla 0.9.7.4.
Model 3 still doesn't work with the collision sensor, simply changing the vehicle makes it the sensor work as expected.
