### ISSUE TITLE
undefined symbol: PyString_Type

### ISSUE THREAD

**Issue by zwbai** [carla-simulator/carla#1762]
after the installation, I want to run the tutorial.py to test the environment. But here is the problem:
![PyString](https://user-images.githubusercontent.com/23632221/59634198-0ec17680-9103-11e9-8f2c-dbb7e3072ded.png)
I also find that the problem is whenever I import Carla in python, this problem will occur. is anyone knows why?

**Comment by sabhiram** [comment]
Isn't this a duplicate of : https://github.com/carla-simulator/carla/issues/1765?

**Comment by havefun28** [comment]
Hi! Have you solved it? If so, how?

**Comment by sound-design** [comment]
Yes it is a duplicate of an issue that is still as of January 29th still unsolved.

**Comment by revikiran1991** [comment]
Same here. I am also facing this issue fro a long time. specially when I make own carla
