### ISSUE TITLE
Bounding boxs for non-agents

### ISSUE THREAD

**Issue by ykaganov** [carla-simulator/carla#1766]
Hi,

I would like to have the bounding-box of actors placed in the scene that are not agents (vehicles/walkers). For example, a tree or a box.
I tried modifying PythonAPI/source/libcarla/Actor.cpp by adding the line in bold:

class_<cc::Actor, boost::noncopyable, boost::shared_ptr<cc::Actor>>("Actor", no_init)
    // work-around, force return copy to resolve Actor instead of ActorState.
    .add_property("id", CALL_RETURNING_COPY(cc::Actor, GetId))
    **.add_property("bounding_box", CALL_RETURNING_COPY(cc::Actor, GetBoundingBox))**
    .add_property("semantic_tags", &GetSemanticTags)
    .add_property("is_alive", CALL_RETURNING_COPY(cc::Actor, IsAlive))

And to make "GetBoundingBox" available I also modified LibCarla/source/carla/client/Actor.h in bold:
class Actor
    : public EnableSharedFromThis<Actor>,
      private profiler::LifetimeProfiled,
      public detail::ActorState {
    using Super = detail::ActorState;

  public:
    **using ActorState::GetBoundingBox;**

But when reading the bounding box in python I get box-location and box-extent that are all zeros.
How can I insure this info is transferred from the server ? 

Thanks !

Yan

**Comment by analog-cbarber** [comment]
Yes, it would be really nice to be able to obtain bounding boxes for static actors.

**Comment by n1try** [comment]
Any news on this?
