### ISSUE TITLE
Snap support[Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [carla-simulator/carla#1768]
I was wondering if you might have an interest in making [snap package](https://snapcraft.io/) version. Also, your app would be promoted on the [snap store page](https://snapcraft.io/store).

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by marcgpuig** [comment]
Thanks for your concern but, sadly, we cannot redistribute Unreal's code.
