### ISSUE TITLE
get distances from lidar

### ISSUE THREAD

**Issue by kimiya66** [carla-simulator/carla#1775]
Hi Folks,
in my project I need to get distances of dynamic vehicle to the other (static-parked) vehicles beside it. However, I could not find enough explanation in documents so how can I see detected obstacle with lidar sensor? then how can I get the distance to them (with which attribute of lidar sensor?)
I used raw_data but it gives me a buffer and I could not extract anything from that. and how can I observe that sensor detecting what?(I mean how can I understand that it detects other car or pedestrian or ...)nothing is visible here. I also save detection of sensor with save_to_disk() but it gets me bunch of same files with format .ply!
I also used sensor.other.obstacles but all of the distances I get from it are the same!(like 50 all the time!)
Please help me what should I do?

**Comment by kimiya66** [comment]
@JohnEmad92 @nsubiron

**Comment by FrancescoTerrosi** [comment]
+1
