### ISSUE TITLE
Wait for tick timeout

### ISSUE THREAD

**Issue by Johnnyswong** [carla-simulator/carla#1777]
Hi, @nsubiron 
After the client call the tick function, it seemly stuck at the function wait_for_tick().
I have no idea how to fix this issue.

The following picture shows my code for the synchronous mode.
![waitfortick](https://user-images.githubusercontent.com/16318579/59827895-5434ac80-936c-11e9-8156-0a144fc65f84.png)

As the picture shows, "wait for tick" never been printed.

**Comment by ykarmesh** [comment]
Hey @Johnnyswong, I am also facing issues with wait_for_tick() function (issue #1795). Does your code run at all or does it get struck the first time you try wait_for_tick()? Also, which version of CARLA are you running?

**Comment by Johnnyswong** [comment]
Hi @ykarmesh 
I tried the multiprocess framework "ray" to fork 2 simulators. After several steps, one of the simulators hanged at the wait for tick function. My version of CARLA is 0.9.5.

**Comment by ykarmesh** [comment]
Although I am not using Ray, the problem is exactly what I am also encountering.

**Comment by Johnnyswong** [comment]
> Although I am not using Ray, the problem is exactly what I am also encountering.

Yeah. After some trial and error, I find that there are three reasons might cause this error:
1) The destruction of sensors, collision sensor esp. ;
2) Loading map, esp loading Town04 ;
3) Render timeout;
These reasons can be traced by the log of the simulator.

I tried: 1) remove the collision sensor with my own implementation 2) try to load Town03 3) Disable rendering
Now  it seems ok. It has been running for  3hours and I havn't met this problem.

**Comment by Johnnyswong** [comment]
#1795
