### ISSUE TITLE
Failed to clone Unreal Engine git

### ISSUE THREAD

**Issue by tartavull** [carla-simulator/carla#178]
I couldn't clone this https://github.com/EpicGames/UnrealEngine.git

**Comment by encore2020** [comment]
me too, then how to download?

**Comment by CapitalZe** [comment]
You need to sign up an account on the UE website and then link this to your Github account, you will be prompted to enter your Github username and pword in terminal after you exact git clone.

Frankly, it's not clear but easy when you know what to do.

**Comment by nsubiron** [comment]
I'm making this clearer in the docs

**Comment by ahrnbom** [comment]
Even after creating an UE account, and linking it with my github account, and then trying to clone UnrealEngine (either from EpicGames or the CARLA-fork) just gives a "fatal: repository not found" error. And yes, I am sure that I am using the same github account for both these things

**Comment by lraulc** [comment]
I know this is far into the future from when you posted, but in order to be able to clone from terminal (2022), I had to do couple of steps:

1. Link Github account to Epic Games Account
2. Fork repository
3. Create an SSH key for your github account.
[Generating a New SSH - Github](https://docs.github.com/es/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
4. After generating you SSH, assign it to your account:
[Connecting Github with SSH](https://docs.github.com/es/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)
5. Proced to clone using SSH instead of HTTPS
6. Voilá.
Hope this helps!

**Comment by Aimo2027** [comment]
I am facing these issues using this link (git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git)
How to fix it?

(Cloning into 'UnrealEngine'...
remote: Enumerating objects: 111593, done.
remote: Counting objects: 100% (111593/111593), done.
remote: Compressing objects: 100% (92142/92142), done.
error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
error: 4718 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output)

**Comment by colibri17** [comment]
> Even after creating an UE account, and linking it with my github account, and then trying to clone UnrealEngine (either from EpicGames or the CARLA-fork) just gives a "fatal: repository not found" error. And yes, I am sure that I am using the same github account for both these things

I am in the same situation. Any help?

**Comment by xADawgx** [comment]
> I am facing these issues using this link (git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git) How to fix it?
> 
> (Cloning into 'UnrealEngine'... remote: Enumerating objects: 111593, done. remote: Counting objects: 100% (111593/111593), done. remote: Compressing objects: 100% (92142/92142), done. error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8) error: 4718 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output)

I'm having a similar error as well:

Cloning into 'X:\Game Content\UnrealEngineSource\UnrealEngine'...
remote: Enumerating objects: 6511107, done.        
remote: Counting objects: 100% (162/162), done.        
remote: Compressing objects: 100% (47/47), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 7581 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

I am downloading from the app using the url method

**Comment by duongtran11** [comment]
> > I am facing these issues using this link (git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git) How to fix it?
> > (Cloning into 'UnrealEngine'... remote: Enumerating objects: 111593, done. remote: Counting objects: 100% (111593/111593), done. remote: Compressing objects: 100% (92142/92142), done. error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8) error: 4718 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output)
> 
> I'm having a similar error as well:
> 
> Cloning into 'X:\Game Content\UnrealEngineSource\UnrealEngine'... remote: Enumerating objects: 6511107, done. remote: Counting objects: 100% (162/162), done. remote: Compressing objects: 100% (47/47), done. error: RPC failed; curl 18 transfer closed with outstanding read data remaining error: 7581 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output
> 
> I am downloading from the app using the url method

I'm getting the same error
On windows 10 pc
