### ISSUE TITLE
visualize sensors

### ISSUE THREAD

**Issue by kimiya66** [carla-simulator/carla#1781]
How can I visualize sensors for example after attaching a sensor to my vehicle, is it possible to see where is the sensor location according to the vehicle? 
I want to see sensor and adjust its location and also how can I visualize what is sensor detected??is there any way to show it in carla? 

I would be grateful for your help,

**Comment by kimiya66** [comment]
@JohnEmad92 @nsubiron

**Comment by marcgpuig** [comment]
Hi @kimiya66 
Not directly, but you can always use the [DebugHelper's functions](https://carla.readthedocs.io/en/latest/python_api/#carla.DebugHelper) to visualize points, lines, arrows, boxes, and strings. 
It's really handy :)
