### ISSUE TITLE
Is there any reinforcement learning tutorial for CARLA 0.9.X ?

### ISSUE THREAD

**Issue by zwbai** [carla-simulator/carla#1782]
Hi,

Thanks for the remarkable work of CARLA simulator.
I am now wondering how to build a reinforcement learning training environment based on CARLA 0.9.5. But so far most of the RL environment is based on CARLA 0.8.X which is much more different with 0.9.X version. 
Thus, is there any 0.9.X based RL environment tutorial? or how to build that? 
Thank you very much!

**Comment by Johnnyswong** [comment]
hi @zwbai 
You can use the env wrapper in openai's baselines to get a quick start(https://github.com/openai/baselines).
OpenAI Gym provide a easy way to implement a new environemnt, you only need to write several functions, eg. env.reset(), env.step(action).

**Comment by zwbai** [comment]
Hi @Johnnyswong thank you very much, but I did not find any tutorial of how to build an RL environment at [https://github.com/openai/baselines](url). Can you give some more specific information?
Thanks a lot!

**Comment by osama-usuf** [comment]
Following, looking for something similar.

**Comment by felipecode** [comment]
I am working on something for that I will update you guys soon !

**Comment by priyankanagaraj1494** [comment]
> Hi @Johnnyswong thank you very much, but I did not find any tutorial of how to build an RL environment at [https://github.com/openai/baselines](url). Can you give some more specific information?
> Thanks a lot!

hello,
refer this book "HANDS ON INTELLIGENT AGENTS WITH OPENAI GYM", they have clearly explained how to make CARLA as a new environment in openai gym. Also the codes are available here https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch7

**Comment by zlw21gxy** [comment]
> I am working on something for that I will update you guys soon !

How things going on?

**Comment by rajatsaini0294** [comment]
There are some tutorials on Youtube by the author named sentdex. You can check out.

**Comment by rudrapoudel** [comment]
Any progress on this? Would really appreciate RL environment for CARLA 0.9.X. Thanks,

**Comment by lijecaru** [comment]
Some environments compatible with Carla0.9.X https://github.com/Sentdex/Carla-RL, https://github.com/cjy1992/gym-carla, https://github.com/rail-berkeley/d4rl/tree/master/d4rl/carla

**Comment by wu0023** [comment]
ThankS for sharing @lijecaru

**Comment by SExpert12** [comment]
Anyone has new information regarding this? I am working on reinforcement learning in CARLA and I have tried many repositories but no one is working as code is written in old Tensorflow version or in other older version library. Please share if anyone has any tutorial link for reinforcement learning in CARLA simulator.
