### ISSUE TITLE
IndexError: blueprint 'sensor.other.lane_detector' not found 

### ISSUE THREAD

**Issue by aadityasp1** [carla-simulator/carla#1784]
Hi,
 I am trying to run older version of my scenario_runner with the latest Carla version 0.9.5 built from source (on Ubuntu 16.04.) and i get the following error:

The scenario cannot be loaded
   ...
   ...
**IndexError: blueprint 'sensor.other.lane_detector' not found
blueprint 'sensor.other.lane_detector' not found
No more scenarios .... Exiting**

how to fix this error?

**Comment by nsubiron** [comment]
That sensor was renamed to `sensor.other.lane_invasion`.
