### ISSUE TITLE
Adding Sound to the Simulator

### ISSUE THREAD

**Issue by mcstoffi** [carla-simulator/carla#1787]
Hey Guys out there,

I need to implement sound into the Carla simulator (especally Engine sounds and enviroment). Does anyone of you has done this before with succes?  
I am realy thankfull for every hint i can get. 

Thanks a lot

Greetings

**Comment by owoschhodan** [comment]
It would be cool having an additional sensor for audio (microphone sensor) like the camera sensor.

As a workaround I use pygame to play sounds/music via the client.

modified manual_control_steeringwheel.py:
```
self.crashSound = pygame.mixer.Sound('scream.wav')

def _on_collision(weak_self, event):
......
    if isinstance(event.other_actor,carla.Walker):
        self.crashSound.play()
