### ISSUE TITLE
No debug strings in sensor data

### ISSUE THREAD

**Issue by pawel-ziecina** [carla-simulator/carla#1788]
Hi,
I've played with `manual_control.py` script and noticed that although debug points and arrows are visible in both pygame and server windows, strings are only visible in server window.

code snippet which I've used to generate below:

``` python
def my_draw(world, waypoints, z=0.5):
    for waypoint in waypoints:
        t = waypoint.transform
        begin = t.location + carla.Location(z=z)
        angle = math.radians(t.rotation.yaw)
        end = begin + carla.Location(x=math.cos(angle), y=math.sin(angle))

        lt = 1
        # world.debug.draw_arrow(begin, end, arrow_size=0.3, life_time=lt, persistent_lines=False)
        world.debug.draw_point(begin, life_time=lt, persistent_lines=False)
        world.debug.draw_string(begin, 'foo', life_time=lt, persistent_lines=False)
```
I'm using custom CARLA build created somewhere after 0.9.5 release

pygame window
![2019-06-21-145632_867x630_scrot](https://user-images.githubusercontent.com/1385347/59924231-94ac2d00-9435-11e9-8fac-1c8fb7ece89d.png)

server window
![2019-06-21-145704_546x347_scrot](https://user-images.githubusercontent.com/1385347/59924233-94ac2d00-9435-11e9-8ab5-d132ad3d9257.png)

**Comment by qhaas** [comment]
Possibly related to Issue #1363 ?
