### ISSUE TITLE
Let lidar ray come across attached vehicle

### ISSUE THREAD

**Issue by cmpute** [carla-simulator/carla#1797]
Currently the point cloud generated by ray_cast sensor has many points fall on to the top of the ego vehicle (its like 10 rings out of 32 rings). Near objects cannot be seen with a lot of points blocked by ego vehicle. Also the simplified shape of vehicle make this problem worse.

So please add option to make the ray_cast sensor ignore attached vehicle in case implementing precise lidar point clouds is still under development.

**Comment by cmpute** [comment]
Solved by putting lidar higher on the vehicle. But still hope that this option can be added

**Comment by lucalazzaroni** [comment]
Any update on this?
