### ISSUE TITLE
how to get the traffic light information when the light is green?

### ISSUE THREAD

**Issue by zwbai** [carla-simulator/carla#1799]
HI,
I try to get the traffic light information all the time, but I found that the 
`vehicle.get_traffic_light()` 
will just return None when the light is not Red.
So is there any possible solution for me to get the traffic light information even the light is Green when the vehicle achieves the trigger box.
Thanks a lot!

**Comment by nsubiron** [comment]
Yeah, the current traffic light detection system was meant for internal use by our autopilot only, it was exposed in the API cause it's still useful in some situations but it's very limited. IMO we should implement at some point a robust system.

However, all the info is there, you can retrieve the trigger boxes of all the traffic lights and other signals (that's the area were vehicles are affected by a traffic signal) and match against the bounding box of your vehicle
```py
for tl in world.get_actors().filter('traffic.traffic_light*'):
    # Trigger/bounding boxes contain half extent and offset relative to the actor.
    trigger_transform = tl.get_transform()
    trigger_transform.location += tl.trigger_volume.location
    trigger_extent = tl.trigger_volume.extent
```
