### ISSUE TITLE
Edit the Post Processing Shader File for DepthEffectMaterial

### ISSUE THREAD

**Issue by xie-dongping** [carla-simulator/carla#180]
Maybe a very dump question, how could one get the source code for the post processing shader DepthEffectMaterial (`DepthEffectMaterial_GLSL.uasset` ) or open it in Blueprint? 

I'm trying to write a shader so I think this one should be a good reference. As this asset is in the plugin Carla, but not in the CarlaUE4 project, I didn't find a way to open it. (And I cannot find a way to open the project for the plugin itself either.)

Maybe you would be able to enlighten me on the topic? 

Thanks!

**Comment by nsubiron** [comment]
Hi @xie-dongping,

The depth (and semantic segmentation) materials have to be edited in the Unreal editor, they are inside Carla plugin and Unreal hides plugin files by default. You can change this in the "View Options" of the "Content Browser"

![screenshot from 2018-01-29 11-12-24](https://user-images.githubusercontent.com/4332953/35505147-77e0f3bc-04e5-11e8-969d-b26f935ba5e2.png)

![screenshot from 2018-01-29 11-12-53](https://user-images.githubusercontent.com/4332953/35505165-85eb52d6-04e5-11e8-8be1-4804e4ce219c.png)

**Comment by xie-dongping** [comment]
Thanks!
