### ISSUE TITLE
Inconsistency in road design

### ISSUE THREAD

**Issue by abol-karimi** [carla-simulator/carla#1804]
I see a few inconsistencies in road design of Town03 (latest version). I wonder whether they are on purpose (to test reaction of autonomous vehicles) or it's just a bug. For example, in the following intersection, there is a right-turn lane together with a left-turn green arrow light:

![road_inconsistency_carla](https://user-images.githubusercontent.com/25490389/60127111-7019c300-975d-11e9-8516-4ab0e798a31d.png)

**Comment by XGodina** [comment]
Hi @abol-karimi ,

Yes, it's true. Already fixed for the next release.

Thanks
