### ISSUE TITLE
Controlers used for agent control 

### ISSUE THREAD

**Issue by Abanoub-G** [carla-simulator/carla#1810]
Hi,
What controller methods are you using to control your vehicle agents longitudinally and laterally in order to follow the points in your route planners splines? For example, are you using PID controller for longitudinal control and pure pursuit controller for lateral control? 

Also where is the code for these controllers located ?

Thanks

**Comment by a08003104** [comment]
Both use PID controller. 
Please check: carla/PythonAPI/carla/agents/navigation/controller.py

**Comment by shushu-nantong** [comment]
Both use PID controller.
Please check: carla/PythonAPI/carla/agents/navigation/controller.py
