### ISSUE TITLE
Expose timeout in load_world()

### ISSUE THREAD

**Issue by ykarmesh** [carla-simulator/carla#1837]
Hi @nsubiron,

I am trying to run multiple (4 currently) CARLAs simultaneously to train an RL agent. However, running so many servers together slows down my PC. This leads to the map taking sometimes even more than 20 secs to load. I tried a hack, where I catch the error and retry the load_world command, however that is not working. It would be helpful if you could expose the timeout in load_world() as a parameter in the Python API. The same issue is also referred in #1817 
Thanks,
Karmesh Yadav

**Comment by germanros1987** [comment]
I don't believe this is really needed since there are other ways to achieve the same result.
