### ISSUE TITLE
Fine control of NPC (make the NPC controllable) 

### ISSUE THREAD

**Issue by dehabu** [carla-simulator/carla#184]
By request of Alexander Anderson <aga@berkeley.edu>

Extending the current API to control the rest of dynamic objects. At least to have a finer control of their initialization:

Use cases: 
- creating situations in which we have a car in front of us blocking our car, etc. 
- create "events", e.g. car overtaking another car, etc.

**Comment by sandman** [comment]
When is this feature planned to be released?

**Comment by felipecode** [comment]
Hey @sandman 

This is a high priority feature for us. But we have planned date to release yet.

Thanks for your interest.

Cheers.

**Comment by ciumonk** [comment]
I've been working on this for a while now. Here what works:
-spawning a pedestrian(or more) with a certain trajectory and speed, configurable from the settings file or sent from the python client(to be used in crash simulations). This basically uses a combination of SetActorLocation and Controller->MoveTo along with selectively disabling the part of code that stops the pedestrian if he is about to intersect with a vehicle.
-the same with cars

My only issue is that pedestrians seem to remain stuck around intersections sometimes. I haven't been able to find any code that would affect this. I have a suspicion that it might be somewhere in a blueprint, any ideas? Pedestrians spawned on the sidewalk in the vicinity of intersections sometimes never move using Controller->MoveTo, unless I interpolate using SetActorLocation(start+ratio*end)....

**Comment by ciumonk** [comment]
Hi, I have this partly working. Perhaps I could submit a PR after the ITSC2018 deadline(1 May)...

**Comment by anthonypan08** [comment]
Any updates on when these features will be included?

**Comment by nsubiron** [comment]
Hey, this was already possible in 0.9.0, and will be significantly improved in 0.9.1.

**Comment by peiyunh** [comment]
> Hey, this was already possible in 0.9.0, and will be significantly improved in 0.9.1.

Hi @nsubiron could you kindly point me to an example for controlling NPCs? Thanks!
