### ISSUE TITLE
Create occupancy_grid map from CARLA

### ISSUE THREAD

**Issue by stevendae** [carla-simulator/carla#1850]
I am trying to get ROS Bridge to publish occupancy grid map data from CARLA including vehicles, lanes, and road but when I launch ros bridge the map topics are not being published. Is there any documentation for trying to get occupancy grid map data from CARLA? Both locally and globally?

**Comment by ynjiun** [comment]
Please leave it open. I would like to know the answer as well. Thanks.

**Comment by ShanLN** [comment]
any update? I would like to know how to get the grid map from carla~ Thanks a lot

**Comment by jiheddachraoui** [comment]
Please leave it open

**Comment by johnren-code** [comment]
Any answers or solution?
