### ISSUE TITLE
Finding waypoints in the same lane

### ISSUE THREAD

**Issue by rockyyliang** [carla-simulator/carla#1853]
version. 0.9.5. 
I wish to find waypoints in the same lane as the currently occupied one. By calling waypoint.next(), it return a list of waypoints that are not guaranteed to be in the same lane. Is there a way to filter the returned list for a waypoint that is in the current lane?

I tried using lane_id, but they can change as the vehicle drives to a new road section as explained here:
[https://github.com/carla-simulator/carla/issues/1469](url)

I tested this out, and in what I've seen so far, the lane_id will only flip signs as the client drives down the road. For example, if I'm printing the current lane_id to terminal, it can look like:
3  
3
3
-3
-3

Therefore, is using the absolute value of lane_id a safe way of filtering for waypoints in the same lane?

Thanks for the help

Edit: My previous observation was wrong. Sometimes it will go to a different number. Still searching for a way to find in lane waypoints

**Comment by kbarbora** [comment]
I do: 
`waypoint_separation = 4
next_w = list(current_w.next(waypoint_separation))[0]`
similar to [https://github.com/carla-simulator/carla/blob/master/PythonAPI/util/lane_explorer.py](url) and I always get the next point in the same lane.
