### ISSUE TITLE
Get Lidar rays without hit

### ISSUE THREAD

**Issue by n1try** [carla-simulator/carla#1866]
Is it possible to get the vectors of all rays cast by a Lidar, even if there was no hit within the maximum range? While I can use point cloud data to determine which areas are occupied, I also would like to know which areas are certainly empty.

**Comment by jjarquin** [comment]
Hi, although not directly possible this modification would be very easy, you just need to modify the sensor file (Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp)

Inside this file you have a function that shoots the ray and tests if there was a blocking hit, I think modifying it like this it should work

````
  if (HitInfo.bBlockingHit)
  {
    if (Description.ShowDebugPoints)
    {
      DrawDebugPoint(
        GetWorld(),
        HitInfo.ImpactPoint,
        10,  //size
        FColor(255,0,255),
        false,  //persistent (never goes away)
        0.1  //point leaves a trail on moving object
      );
    }

    XYZ = LidarBodyLoc - HitInfo.ImpactPoint;
  }
  else
  {
    XYZ = LidarBodyLoc - EndTrace;
  }
    XYZ = UKismetMathLibrary::RotateAngleAxis(
      XYZ,
      - LidarBodyRot.Yaw + 90,
      FVector(0, 0, 1)
    );

  return true;
````
