### ISSUE TITLE
Is there any way for a camera to record video instead of take pictures?

### ISSUE THREAD

**Issue by programmer6288** [carla-simulator/carla#1869]
Hello,

Pretty much what the title says. Right now I am using ffmpeg to turn the images into an mp4, but is there any method in carla to do this? I am noticing that there are some periodic frame drops.

Thank you

**Comment by nsubiron** [comment]
Hi @programmer6288,

Use the [synchronous mode](https://carla.readthedocs.io/en/latest/configuring_the_simulation/#synchronous-mode) to avoid frame drops.

**Comment by programmer6288** [comment]
Hello,

I am currently unclear on how to run synchronous mode. When I add this code:

> settings = world.get_settings()
settings.synchronous_mode = True
world.apply_settings(settings)

to the script that I am running, the scripts fails due to collision, and the simulation becomes unresponsive (fades to black). What am I doing wrong here?

Thank you

**Comment by p-schulz** [comment]
Hi,

when using the python client, have a look at **imageio**. It has the ability to pipe images directly to the ffmpeg encoding. This helped me as I encountered frame drops when writing single images to disk. You'll have the same framerate as in simulation without recording and instant an mp4 file.
