### ISSUE TITLE
How to use custom map in Release build

### ISSUE THREAD

**Issue by linche35** [carla-simulator/carla#1871]
Hi,

I have built Carla from source and created my custom map (.fbx, .xodr)
I followed the instructions in [https://carla.readthedocs.io/en/latest/asset_packages_for_dist/](https://carla.readthedocs.io/en/latest/asset_packages_for_dist/) and was able to generate a *.tar.gz file in the ```Dist``` folder

Let's say I want to share this map to somebody who didn't build Carla from source (i.e. with only release version). Is there a way I can export the map so that it is as easy as using ```./CarlaUE4.sh /Game/Carla/Maps/{MyCustomMap}``` in release version?  

I tried placing the MyCustomMap.tar.gz file in the ```ExportedMap``` folder and running ```ImportMaps.sh```. But after doing this, running ```./CarlaUE4.sh``` crashes

Can anyone help me with this?
Thanks!

**Comment by ckurtz22** [comment]
Was a solution for this ever found?
