### ISSUE TITLE
Inconsistent RuntimeError because of collision at spawn position 

### ISSUE THREAD

**Issue by zeinramadan** [carla-simulator/carla#1873]
I'm trying to spawn 2 vehicles at DIFFERENT coordinates and have them move along points that are read from a csv file. One of my python scripts I have runs 1 in 3 tries the other doesn't run at all, it just throws a RuntimeError saying that the spawn failed because of collision at spawn position which makes no sense to me since the initial coordinates are reasonably far away from one another. Any suggestions as to what might be causing the issue?

**Comment by karthi0804** [comment]
Hi, How do you specify the location for spawning the vehicle? I solved this by finding the nearest waypoint and spawning according to that location.
```object_veh = world.spawn_actor(obj_blueprint, map.get_waypoint(object_transform.location).transform)```

I guess the reason is the difference in Z value which makes Carla think as a collision with the ground.

**Comment by zeinramadan** [comment]
> 
> 
> Hi, How do you specify the location for spawning the vehicle? I solved this by finding the nearest waypoint and spawning according to that location.
> `object_veh = world.spawn_actor(obj_blueprint, map.get_waypoint(object_transform.location).transform)`
> 
> I guess the reason is the difference in Z value which makes Carla think as a collision with the ground.

**Comment by zeinramadan** [comment]
Solved the issue, apparently if I abruptly end the script the actors don't get properly destroyed so running the script again would spawn the actors on an already existing actor. Just had to restart UE.

**Comment by dhdiagram4011** [comment]
@karthi0804 

custom map carla import --> linux command line python lidar_to_camera.py play
RuntimeError: Spawn failed because of collision at spawn position

**Comment by Kenneth71-P** [comment]
I have the same problem. Can you tell me how can i solve this?
![8C13D4EE-91AE-4288-BFC8-242CDC124F91](https://user-images.githubusercontent.com/82718915/163346493-0237fc73-a5ac-48dc-9d1e-0d07b939baa8.jpeg)
![3DADE7BB-CE9B-4980-8D5A-65316CE533A5](https://user-images.githubusercontent.com/82718915/163346504-2950418e-94e0-49ad-8756-6f8e9795b838.jpeg)
