### ISSUE TITLE
What's the function relationship between throttle and velocity, steer and heading angle?

### ISSUE THREAD

**Issue by linxigjs** [carla-simulator/carla#1876]
My purpose is to control the vehicle's velocity(both it's value and direction) by acceleration and the angle of the front wheel, so what's the relationship between them? What's the calculation model? Any code in Carla, or reference articles are appreciate. Thanks.
I'm using Carla 0.9.5 on Ubuntu 16.04

**Comment by xiaoyang666** [comment]
The specific model should be placed in UE4 according to a vehicle model from NVIDIA. I only found some engine and transmission parameters.

**Comment by linxigjs** [comment]
> The specific model should be placed in UE4 according to a vehicle model from NVIDIA. I only found some engine and transmission parameters.
Yes, thanks. I also found the vehicle and wheel model parameters, torque curve as well. But i'm confused why they set this way and what's the relationship between them.

**Comment by sheelabhadra** [comment]
Hi @linxigjs, could you please let me know the way to obtain the current wheel angle?

**Comment by linxigjs** [comment]
Hi @sheelabhadra , If you want to know the front wheel steer angle, you may read the code in carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp line 112, which is 
float ACarlaWheeledVehicle::GetMaximumSteerAngle() const
{
  const auto &Wheels = GetVehicleMovementComponent()->Wheels;
  check(Wheels.Num() > 0);
  const auto *FrontWheel = Wheels[0];
  check(FrontWheel != nullptr);
  return FrontWheel->SteerAngle;
}
Hope it will help you.
