### ISSUE TITLE
generate_map.py don't appear

### ISSUE THREAD

**Issue by eloy96vg** [carla-simulator/carla#1877]
Hi!

In the latest commit (29f6acb) don't appear the file generate_map.py, that is the easiest way to upload RoadRunner maps. Why it does not show up? Is there any new way to upload these maps?

Thanks.

**Comment by nsubiron** [comment]
Hi @eloy96vg,

We'll be announcing the new system in the coming release, but meanwhile master branch already has the changes, the new documentation is at [Creating standalone asset packages for distribution](https://carla.readthedocs.io/en/latest/asset_packages_for_dist/).

**Comment by eloy96vg** [comment]
Hi @nsubiron ,

There was some way to recover generate_map.py, because I am doing a job with carla and I need to import maps. With this command (generate_map.py) I could import maps without problems, however, with make import I have the problem that I expose in this comment (https://github.com/carla-simulator/carla/issues/1886#issuecomment-512986988).

A greeting.

**Comment by Sultan91** [comment]
same for me
