### ISSUE TITLE
Inconsistency over different fixed time-step

### ISSUE THREAD

**Issue by pgraf** [carla-simulator/carla#1879]
I have read about fixed time step mode as much as possible (the docs, various questions in the forum and on Discord), but I have not found an answer to the following:

If I run -fps=10 and -fps=20 for, say, 5 _simulated_ seconds, should my vehicle travel the same distance?

I think the answer should be yes, but this is not what I observe.  If yes, do you have an example script that demonstrates it?  If no, what am I still missing?

What I think is that the answer is supposed to be yes but in fact this is not quite working. I have a suspicion as to what's going on, hinted at by this post: http://www.aclockworkberry.com/unreal-engine-substepping
which is that physics sub-stepping is only consistent if _all_ the physics is done through the Unreal physics engine (i.e., no physics in Tick()).
I also have a pure-unreal demo that demonstrates that at the level of pure physics the answer is clearly yes (I am happy to supply more information, but I want to keep this short for now).  It would make my life easier if I've missed something and there's an easy solution.  But I'm not comfortable artificially speeding up my simulations unless I'm sure they are equivalent to the un-accelerated version.

Thank you so much for this wonderful tool!

**Comment by howicc** [comment]
Did you find a solution? I also have this issue with the simulation running accelerated based on the fps.
