### ISSUE TITLE
Error with 'make import'

### ISSUE THREAD

**Issue by eloy96vg** [carla-simulator/carla#1886]
Hi!

I'm trying import maps from Roadrunner with the new command "make import" following the instructions but I'm having some problems. I have the folders and the JSON file as shown in the figures below.

![Captura de pantalla de 2019-07-15 13-18-06](https://user-images.githubusercontent.com/47063072/61213053-445a7f00-a704-11e9-9c98-b34cfe7ba52a.png)

![Captura de pantalla de 2019-07-15 13-18-22](https://user-images.githubusercontent.com/47063072/61213058-491f3300-a704-11e9-83fa-651cfc7030d1.png)

![Captura de pantalla de 2019-07-15 13-18-34](https://user-images.githubusercontent.com/47063072/61213068-4b818d00-a704-11e9-8db3-9077e03d3751.png)

But when i run the "make import" appear this error.

![Captura de pantalla de 2019-07-15 13-17-50](https://user-images.githubusercontent.com/47063072/61213147-77047780-a704-11e9-9a9b-284446a8dc2a.png)

I'm waiting for your help, thanks in advance.

**Comment by manishthani** [comment]
Hi @eloy96vg ,
Seems like you are missing `props: []` in your `Package1.json` file, which is an empty JSON array **only if you have no props to import**.
So, basically, try adding that to your file:
```
{
     maps: [
     // Your current maps
     ],
     props: []
} 
```
Please, let me know if it worked.

**Comment by eloy96vg** [comment]
Thanks @manishthani !
That solved the problem, but when i import the maps RoutePlanners and Spawn points are created, 
but the nodes are not created on the map. In fact, as you can see in the image, a single node has been created. Would you know why this happens? I would be very helpful.

![Captura de pantalla de 2019-07-18 22-58-44](https://user-images.githubusercontent.com/47063072/61491778-3a5ca880-a9b0-11e9-8de2-9113fef06a84.png)

Thanks and best regards

**Comment by manishthani** [comment]
Hi @eloy96vg,
Maybe this could happen if the OpenDrive `xodr` file is not correct, could you please check it again and try opening it with the [OpenDrive visualizer](http://www.opendrive.org/download.html)?

**Comment by eloy96vg** [comment]
Hi @manishthani,
I'm tryiang to install OpenDrive visualizer in Ubuntu but i cant (It says "There are no applications available to open << odrViewer.1.9.1 >>"), do you know how can i download it?
On the other hand, comment that with the old form available (generate_map.py) the map was created correctly. The problem has been with make import, where the nodes are not created.
