### ISSUE TITLE
[0.9.6] This scenario requires to use map Town01

### ISSUE THREAD

**Issue by jS5t3r** [carla-simulator/carla#1888]
Hello, 

I am using Ubuntu16.04, CARLA 0.9.6  and the Scenario Manager 0.9.6
```
./CarlaUE4.sh /Game/Carla/Maps/Town01 -windowed -ResX=320 -ResY=240 -benchmark -fps=10
4.22.1-0+++UE4+Release-4.22 517 0
Disabling core dumps.
```

I am getting the error: 
```
python scenario_runner.py --openscenario srunner/configs/FollowLeadingVehicle.xosc 
The CARLA server uses the wrong map!
This scenario requires to use map Town01
```

What am I doing wrong? manuel_control.py does work after spawning some vehicles.

---------------------------------------------
Error Sources:

1. Similar Threads https://github.com/carla-simulator/carla/issues/1700 Is there a different path?

2. $PYTHONPATH
zsh: no such file or directory: /opt/ros/kinetic/lib/python2.7/dist-packages:/home/user/Documents/avenue20/prec_CARLA_0.9.6/PythonAPI/carla/:/home/user/Documents/avenue20/prec_CARLA_0.9.6/PythonAPI/carla/agents/:/home/user/Documents/avenue20/scenario_runner:/home/user/carla-ros-bridge/catkin_ws/devel/lib/python2.7/dist-packages:/home/user/Documents/avenue20/prec_CARLA_0.9.6/PythonAPI/carla/dist/carla-0.9.6-py2.7-linux-x86_64.egg

**Comment by tn00364361** [comment]
In the [documentation for v0.9.6](https://github.com/carla-simulator/scenario_runner/blob/v0.9.6/Docs/getting_started.md), you should reload the map using the command line option `--reloadWorld`.

```
python scenario_runner.py --openscenario srunner/configs/FollowLeadingVehicle.xosc --reloadWorld
```

**Comment by jS5t3r** [comment]
thanks
