### ISSUE TITLE
Make a CARLA 0.7.1 release for Windows

### ISSUE THREAD

**Issue by carla-admin** [carla-simulator/carla#189]
Make a binary version of CARLA 0.7.1 available to download at [release 0.7.1](https://github.com/carla-simulator/carla/releases/tag/0.7.1).

**Comment by marcgpuig** [comment]
Now there is a Carla 0.7.1 binary for Windows ready to [download](https://drive.google.com/file/d/1EMlYKpuZ5UUp680T7qp0gAOU5MyuxBkE/view). Take a look to the [release page](https://github.com/carla-simulator/carla/releases/tag/0.7.1)!

**Comment by JohnEmad92** [comment]
I want to ask if i can release a package for windows from ubuntu?

**Comment by JohnEmad92** [comment]
Hello @marcgpuig 
I want to ask if I can release a package for windows from ubuntu?

**Comment by marcgpuig** [comment]
Unreal Engine does not provide this feature, sorry.
Check out the [Compiling For Linux](https://wiki.unrealengine.com/Compiling_For_Linux) Unreal's wiki page.

**Comment by JohnEmad92** [comment]
@marcgpuig 
Thanks for your response
Is the windows release generated from carla on windows?

**Comment by marcgpuig** [comment]
@JohnEmad92 
Yes it is!
