### ISSUE TITLE
 In Carla you can define activities for pedestrians such as running, jumping, talking?

### ISSUE THREAD

**Issue by hvelesaca** [carla-simulator/carla#1896]
**In Carla you can define activities for pedestrians such as running, jumping, talking ?**

**Comment by bernatx** [comment]
Hi,

Not right now in this version 0.9.6 but we are planning to add those features soon in future versions.

**Comment by hvelesaca** [comment]
But in this version 0.9.6 you can Controlling a walker's skeleton and I will simulated the activities such as running, jumping, talking an others?

**Comment by bernatx** [comment]
Yes, but that is more oriented to let the pedestrian animate for an action like talk, call a taxi, sit down...other than navigate or move around. For that, we need to take care of the collisions with the world, something that with the animation you can not do. But you are free to test :)
