### ISSUE TITLE
How to prevent collision with road

### ISSUE THREAD

**Issue by GeramiAD** [carla-simulator/carla#1898]
To import external vehicle dynamics to Carla, I get the current vehicle location/orientation from Carla and send it to the external vehicle dynamics model. Then, the new location/orientation from the vehicle dynamics model is used to set the new location/orientation in Carla. As a test I tried to make the vehicle move in a straight line:
world.player.spawn_point.location.x += (0.1 * math.cos(world.player.spawn_point.rotation.yaw / 180 * math.pi))

world.player.spawn_point.location.y += (0.1 * math.sin(world.player.spawn_point.rotation.yaw / 180 * math.pi))

world.player.spawn_point.location.z = 0.0

world.player.set_transform(world.player.spawn_point)

even though vehicle elevation (z) is set at 0, the vehicle flies or gets underground, which causes a “collision with road” event. I assume z just reports the car elevation and needs to be adjusted by road surface elevation. I tried to use map topology and geolocation but they both show the road elevation as 0, even on ramps. 

for segment in  world.map.get_topology():
    wp1, wp2 = segment[0], segment[1]
    l1, l2 = wp1.transform.location, wp2.transform.location
    geo1 = world.map.transform_to_geolocation(l1)
    geo2 = world.map.transform_to_geolocation(l2)

print(f"map info {l1}{l2}")
print(f"geo info {geo1}{geo2}")

Therefore, using the topology and geolocation did not resolve the issue. How can I get the road surface elevation to prevent the vehicle from flying or colliding with the road?

I’m using Carla 0.9.5

Best regards,

**Comment by fyj97** [comment]
Hi, have you solved the problem, I meet the same one. Thank you very much

**Comment by FrancescoTerrosi** [comment]
+1

**Comment by yanwu-ge** [comment]
+1
