### ISSUE TITLE
Capture images from main camera

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#191]
Investigate if there is a way to capture images from the main game camera, allowing a less flexible but faster method to capture images.

**Comment by YashBansod** [comment]
I was wondering: 
If you type `shot` in the command line that appears if you press the `\`` key, you get a screenshot saved. If I understand it correctly, it is the main game camera right? Can we not use it somehow to achieve the purpose?

**Comment by fweidner** [comment]
Hey, 
this person here accesses the main camera and grabs from the frame buffer. Not sure if that's something interesting: 
https://github.com/Batname/SpectatorWindow

**Comment by germanros1987** [comment]
This problem was solved in the latest version(s) of CARLA.
