### ISSUE TITLE
Adaptive cruise control using reinforcement learning

### ISSUE THREAD

**Issue by kraken24** [carla-simulator/carla#1922]
hey everyone, I am using carla 0.9.5. 

I am trying to develop adaptive cruise control using deep reinforcement learning.  So i want to navigate the town with some fix velocity before i activate the cruise control function. 

Can anyone suggest how i can navigate at fix velocity around the town?

**Comment by deepakreddy63** [comment]
Hi,
You can set the vehicle on autopilot. This by default keeps the velocity at 20 kmph.

**Comment by kraken24** [comment]
@deepakreddy63  Thank you. But for my scenario training, i should be able to change this speed. How can i do that?

**Comment by deepakreddy63** [comment]
@kraken24 
You can refer to this https://github.com/carla-simulator/carla/issues/1488
