### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by wbridewell** [carla-simulator/carla#1925]
With the switch to rpclib, it's no longer straightforward to generate a Java API for interacting with CARLA by compiling the protocol buffer definitions. It would be helpful if there were a Java API in the upcoming 1.0 release.

**Comment by jdeantoni** [comment]
I agree it would be a very nice feature to have :)

**Comment by wbridewell** [comment]
For my purposes, I have found that the bridge between Clojure and Python provided by [libpython-clj](https://github.com/cnuernber/libpython-clj) solves this issue.
