### ISSUE TITLE
Document command-line arguments to CarlaUE4 or add `-h`

### ISSUE THREAD

**Issue by qhaas** [carla-simulator/carla#1930]
Greetings,

The [documentation on the available command-line arguments](https://carla.readthedocs.io/en/latest/configuring_the_simulation/#fixed-time-step) does not seem to be complete.  Would it be possible to add all the available command-line options to a `-h` flag to the CarlaUE4 binary or include the ones available in the linked documentation?  I see that the move to 'Shipping Mode' as the default limits many, but not sure which.

**Comment by jackbart94** [comment]
Hi,

The documentation will be updated soon, however due to the recent shipping mode change there is a new way to add command-line arguments.

Please, refer to this closed issue and let me know if it solves your doubts: https://github.com/carla-simulator/carla/issues/1908

**Comment by qhaas** [comment]
Thanks!
