### ISSUE TITLE
Current wheel angle/steering

### ISSUE THREAD

**Issue by pawel-ziecina** [carla-simulator/carla#1939]
Hi,
There is delay between applied steering and real steering - can be configured with 'Steering Input Rate' in vehicle blueprint. Is there possibility to read current wheel angle/steer?

Obtaining from vehicle.get_control() provides last VehicleControl command not current state (as stated in documentation).

CARLA version: 0.9.6

**Comment by sheelabhadra** [comment]
Hi @pawel-ziecina, were you able to figure out a way to obtain the current wheel angle?

**Comment by wulaali** [comment]
were you able to figure out a way to obtain the current wheel angle?

**Comment by MohamedDaoud1** [comment]
If you are using carla ros bridge, I think it is the "steer" value in "vehicle_status" topic but normalized (max is 1)

**Comment by mortenfc** [comment]
I need an answer for this. Bump

**Comment by mortenfc** [comment]
> If you are using carla ros bridge, I think it is the "steer" value in "vehicle_status" topic but normalized (max is 1)

I don't think so, as the ros bridge just publishes the carla control received from the Python API.

**Comment by sshawn9** [comment]
Actually, there is a python api called get_wheel_steer_angle which you can found [here](https://carla.readthedocs.io/en/latest/python_api/#getters_20), same for the c++ api. While it sucks as it will call the simulator and retrieve date when next tick, you may need single thread to continuously get current steer angle. I hope Carla team could more on vehicle kinematics and dynamics.

**Comment by sshawn9** [comment]
> > If you are using carla ros bridge, I think it is the "steer" value in "vehicle_status" topic but normalized (max is 1)
> 
> I don't think so, as the ros bridge just publishes the carla control received from the Python API.

Yes, it just publishes the carla control received last time, ridiculous!
