### ISSUE TITLE
Error: Couldn't find file for package /Game/Carla/Static/GenericMaterials... after software update (ubuntu 16.04)

### ISSUE THREAD

**Issue by chankim** [carla-simulator/carla#1965]
Hello, I had installed Caral0.9.5 with no problem before. I could run it and analyze it using debugger from time to time when I had time. But today, after ubuntu 16.4 software update, (yes, I beilive it's after that), I'm seeing this error message when I start the server.  
I start the server with this command : 
SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=0 ./Dist/0.9.5-93-gab7a166/LinuxNoEditor/CarlaUE4.sh -ResX=800 -ResY=600 -nosound -windowed&
and I'm seeing this log : 

> [2019.08.02-13.16.52:377][  0]LogStreaming: Error: Couldn't find file for package /Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapRoad requested by async loading code. NameToLoad: /Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapRoad
> [2019.08.02-13.16.52:377][  0]LogStreaming: Error: Found 0 dependent packages...
> [2019.08.02-13.16.52:378][  0]LogStreaming: Error: Couldn't find file for package /Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapSideWalkCurb requested by async loading code. NameToLoad: /Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapSideWalkCurb

The full log is here : 

[log1.txt](https://github.com/carla-simulator/carla/files/3461429/log1.txt)

Other than this server error message, I can stil run the client as before.
I copied Carla0.9.5 directory to another location, and tryied building and running the client, (with the same UE4.22 engine location), but this time   I see this error message when running the client.(about version mismatch) : 

> WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
> WARNING: Client API version     = 0.9.5-93-gab7a166 
> WARNING: Simulator API version  = 4c77a8c 

I tried recompiling UE4.22 and Carla, but it's the same. (if I run the client from the old directory, I have no problem. I confess, in the new directory, I've ran Update.sh so some contentes are newer than the old directory. I don't know how to remove this version mismatch error message. Somewhere, the old information(0.9.5-93-gab7a166) resides, but I don't know where. Please anyone help me. Thank you for reading.

**Comment by qhaas** [comment]
I'm seeing these errors when compiling CARLA 0.9.8.  They seemed harmless, but I noticed that for some reason the string escaping in 'Unreal/CarlaUE4/Config/DefaultGame.ini' wasn't being handled properly in my Ubuntu 18.04 environment, so I changed the `'"` to just a `"` around their paths, recompiled, and no error.
