### ISSUE TITLE
Problems with image blur in Carla 0.9.6

### ISSUE THREAD

**Issue by cstamatiadis** [carla-simulator/carla#1967]
Hello everybody, 

I'm running Carla on Ubuntu 18.04. Until a couple of days ago I was using version 0.9.4, however, since I'm mostly working on object detection, I decided to switch to 0.9.6, given the increased variety of pedestrians. (I was and am working with the pre-built projects). 
When I store the images they seem to be quite blurred compared to how they used to be. I added the following to my RGB sensor configuration: 
`motion_blur_intensity = 0

motion_blur_max_distortion = 0,`

but it doesn't seem to change anything. The pedestrian in the image below is quite blurred in my opinion. But also images in general seem more blurry.

![275886](https://user-images.githubusercontent.com/35172341/62379462-4cf5e680-b547-11e9-937c-21a840235b23.png)
![272899](https://user-images.githubusercontent.com/35172341/62379529-6a2ab500-b547-11e9-8a6f-4b40da6d5f65.png)

For reference this is a sample of how images used to look before
![000312](https://user-images.githubusercontent.com/35172341/62379316-fee0e300-b546-11e9-9423-56635ae63243.png)

Does anyone have an idea of what I could be doing wrong?

**Comment by kimiya66** [comment]
I had also the same problem with new version so I try not to migrate to new version and apply all of the improvement on codes(like sensor problems...) manually to the source code of carla9.5 and compile it myself.

**Comment by joao-paulo-alves** [comment]
Having the same problem on CARLA version 0.9.13

**Comment by wuhanstudio** [comment]
The same problem with CARLA v0.9.14.

**Comment by alexx-km** [comment]
The same problem exists in CARLA v0.9.15.
