### ISSUE TITLE
Shut down issue

### ISSUE THREAD

**Issue by ghost** [carla-simulator/carla#1968]
When I run CarlaUE4, The laptop shuts down. How can I solve this problem?

**Comment by cassfalg** [comment]
Overheating maybe? Probably some issue with your hardware or operating system / driver setup. Very very unlikely to be related to carla - as an application it has no way to shut down your laptop.

You need to provide way more information for anyone to be able to help you. You're best bet, in my opinion, is to ask a friend who "kinda knows computers". What you can do is check your system's logs for errors. Update your system and it's drivers. Try other software that stresses your system. Some benchmarks maybe, furmark if on windows.

This is the wrong place to ask this question, and a very bad way to ask it.
