### ISSUE TITLE
get_waypoint() direction

### ISSUE THREAD

**Issue by totalu** [carla-simulator/carla#1969]
Hello.
l have made an OpenDRIVE map for left hand drive roads.
With this map, does get_waypoint() output a point ahead as we drive on the left side of the road?
 
I am asking this because OpenDRIVE map does not explicitly indicate driving directions except junctions.

**Comment by xiaoyang666** [comment]
Hi
    How is your opendrive made? Roadrunner?Thank you.

**Comment by totalu** [comment]
Yes. By Roadrunner. I used a left hand drive option in exporting to an OpenDRIVE file.  Thank you.
