### ISSUE TITLE
Acceleration to throttle relationship

### ISSUE THREAD

**Issue by erfanaasi** [carla-simulator/carla#1972]
Hi I'm using CARLA 0.9.5 on Ubuntu 16.04 and I was wondering is there any method or relationship to change a desired acceleration for the vehicle to the required throttle as input? I am using a bicycle model for the vehicle and in that model my inputs are acceleration and steer but I don't know how to set the equivalent throttle required for the vehicle for a specific acceleration.

**Comment by jan-reich** [comment]
see my answer at #2000
