### ISSUE TITLE
carla/carla_server.h not found when building on windows

### ISSUE THREAD

**Issue by josheligoldman** [carla-simulator/carla#198]
I have run the setup.ps1 script and the buildserver.ps1 script but When I build with visual studio I get the following errors:
C:\Users\joshe\OneDrive\Documents\Github\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla\Game\CarlaServer.cpp(18): fatal error C1083: Cannot open include file: 'carla/carla_server.h': No such file or directory

ERROR : UBT error : Failed to produce item: C:\Users\joshe\OneDrive\Documents\Github\carla\Unreal\CarlaUE4\Plugins\Carla\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-Carla.lib

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3075: The command ""C:\Program Files\Epic Games\UE_4.17\Engine\Build\BatchFiles\Build.bat" CarlaUE4Editor Win64 Development "C:\Users\joshe\OneDrive\Documents\Github\carla\Unreal\CarlaUE4\CarlaUE4.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.

**Comment by nsubiron** [comment]
Hi @josheligoldman,

Sorry, we don't have yet a reliable way for building CARLA on Windows. You can follow the directions at #21 but for now you'll have to cross check that every step worked.

In this case, the compilation of the CarlaServer module failed; you might need to compile it (either with the Makefile or CMake) and then install it under _"Unreal/CarlaUE4/Plugins/Carla/CarlaServer"_.

**Comment by josheligoldman** [comment]
How do I compile the CARLA server. Please provide exact steps

**Comment by nsubiron** [comment]
For Linux, the exact steps are in [How to build on Linux](http://carla.readthedocs.io/en/latest/how_to_build_on_linux/). For Windows unfortunately, all we have is issue #21.

**Comment by marcgpuig** [comment]
Please consider using the official Carla for Windows release mentioned in issue #189.  
Hope this helps.
