### ISSUE TITLE
BasicAgent does't work when running automatic_control.py

### ISSUE THREAD

**Issue by EvaMGG** [carla-simulator/carla#1985]
I have Carla 0.9.5 running on Windows 10 and when I try to run the example automatic_control.py with --agent "Roaming" it seems to work, but when I do with --agent "Basic" it executes but nothing is shown in the window and no error is shown. How can I solve this problem?

**Comment by germanros1987** [comment]
This issue is very relevant. We need to pay a close look to this.

**Comment by marcgpuig** [comment]
Looks related to keypad's `Num Lock`.
Can you try enabling/disabling it?
