### ISSUE TITLE
[0.9.6] How to create a map with roadrunner in which pedestrians can navigate on roads and pavements?  

### ISSUE THREAD

**Issue by Siqi-Wang47** [carla-simulator/carla#1987]
Hi Carla team!

I am very new to Carla and my project requires pedestrian walking on roads, but the current pedestrians in carla only navigate on pavements. I am not sure how the pedestrians navigation works but I roughly understood from other threads that it's somehow related to the meshes in the  maps, so I was wondering if I can create a new map from roadrunner and allow the functionality for pedestrians to navigate on roads as well as pavements.         

Thanks in advance!

**Comment by Siqi-Wang47** [comment]
Hi @bernatx , could you give me some hints for this problem?

**Comment by bernatx** [comment]
Hi Siqi-Wang47, 

current version only has a basic navigation system for pedestrians. The navigation is based on a binary file created from the Recast&Detour library with all the information about where the pedestrians can walk. 

You can check this issue where some instructions and experiences are given: https://github.com/carla-simulator/carla/issues/1899

 I hope it helps.
