### ISSUE TITLE
PythonAPI: Actor has empty object_type attribute

### ISSUE THREAD

**Issue by cmpute** [carla-simulator/carla#1993]
Actor.attributes for Vehicles has a field "object_type".
In 0.9.5 "object_type" had a value, e.g. "car".
In 0.9.6 "object_type" is always empty.

Test:
I'm using Carla 0.9.6 and latest ros-bridge on master branch. System is Ubuntu 18.04 and ROS melodic.
When I print the properties of the actor at https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/src/carla_ros_bridge/vehicle.py#L48, I found that the object_type is null, therefore all the objects in the ROS message are tagged as CLASSIFICATION_UNKNOWN. Please fix this! Attached is the screenshot for printing.

![Screenshot from 2019-08-11 22-34-14](https://user-images.githubusercontent.com/9154441/62843685-be414200-bc89-11e9-89c2-095311929528.png)

**Comment by d-hayashi** [comment]
You may have already solved the problem, but I found a solution.

1. Open CARLA with Unreal Engine 4
2. Open the following file in the content browser
     1. Content -> Carla -> Blueprints -> Vehicles -> VehicleFactory
3. Select `GenerateDefinition` in Functions
4. Select `Vehicles` in Local Variables
5. Enter the object type in the `Object Type` of each element of the array
6. Save the file

![screenshot](https://user-images.githubusercontent.com/24401842/66318440-483e1c00-e956-11e9-83c4-0716a561d546.jpg)

**Comment by cmpute** [comment]
bump

**Comment by roshambo919** [comment]
Confirming that it looks to me like object type is always empty in both 0.9.10 and 0.9.13 binaries. 

```
  blueprints = world.get_blueprint_library().filter('vehicle.*')
  for bp in blueprints:
      print('\n\n', bp.tags)
      for attr in bp:
          print(attr)
```

![image](https://user-images.githubusercontent.com/20426598/193360856-050ef427-bd0e-49ec-b382-d57b6f11df3b.png)

**Comment by roshambo919** [comment]
This is important because, while I can use the number of wheels to differentiate between cars and bikes/motorcycles, I cannot differentiate between bikes and motorcycles without using the precise name of the actor.

**Comment by yunmo555** [comment]
> This is important because, while I can use the number of wheels to differentiate between cars and bikes/motorcycles, I cannot differentiate between bikes and motorcycles without using the precise name of the actor.

Do you have a good solution to differentiate between bikes and motorcycles?

**Comment by roshambo919** [comment]
I just hard-coded in the names of motorcycles and assigned based on the complete actor name. Not ideal if Carla adds new actor types but fine for now.

**Comment by yunmo555** [comment]
- 

> I just hard-coded in the names of motorcycles and assigned based on the complete actor name. Not ideal if Carla adds new actor types but fine for now.

ok, there seems to be no better way at the moment. I try to modify 'object_type' attributes of blueprint, but it's read-only. 

![AE7C1FAC-0F5F-4cdf-8BB9-0346A6B1BF65](https://user-images.githubusercontent.com/42030151/194735005-93e17d3b-5014-4ba6-939a-1e28ecf1ec08.png)

**Comment by xqgex** [comment]
bump
