### ISSUE TITLE
Add ability to delete debug elements

### ISSUE THREAD

**Issue by cmpute** [carla-simulator/carla#1999]
This is related to https://github.com/carla-simulator/ros-bridge/issues/173.

In order to implement Marker.MODIFY or Marker.DELETE operation, I wish to achieve the capability to edit or remove debug elements (arrows, boxes, etc) created by debug helpers. A possible way to do this is to get the 'actor' (?) id of the debug elements when creating and allow modify or deleting the elements by their id.

**Comment by cmpute** [comment]
Bump

**Comment by cmpute** [comment]
bump

**Comment by khojir** [comment]
bump

**Comment by andrewyguo** [comment]
bump

**Comment by XlightwolfX** [comment]
bump

**Comment by budrus123** [comment]
Bump

**Comment by rszeto** [comment]
Bump

**Comment by MasterIzumi** [comment]
Any solution for this kind of operation in 2022? :)

**Comment by lesurp** [comment]
Still nothing about this? I can afford to spend some time on it but I have never looked at the carla internals so that might take a while :/

**Comment by Youjin1985** [comment]
Bump

**Comment by Youjin1985** [comment]
Bump... really need this, its extremely annoying to reload map after every simulation tjust to get rid of debug marks

**Comment by astralmaster** [comment]
Bump. Having capability to draw debug elements also necessitates the functionality to erase them.

**Comment by astralmaster** [comment]
Got tired of waiting, here's a PR:  https://github.com/carla-simulator/carla/pull/8855

**Comment by cmpute** [comment]
> Got tired of waiting, here's a PR: [#8855](https://github.com/carla-simulator/carla/pull/8855)

You are a hero! It's ignored for nearly 6 years...
