### ISSUE TITLE
Define a common interface for easily adding sensors

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#200]
Make a common interface for cameras and lidar at the server-side. Try to define a general interface for sensors so it's easier to add new sensors in the future.

**Comment by errorJY** [comment]
Hello@nusbiron
       What can I do for you？My graduation project is the Sensor expansion for Carla . I will begin to do it after the Spring festival.I think your project will make it  easier，so I want do something for your project.
       please .

**Comment by errorJY** [comment]
Hello@nusbiron
What can I do for you？My graduation project is the Sensor expansion for Carla . I will begin to do it after the Spring festival.I think your project will make it easier，so I want to do something for your project.
please .

**Comment by mshaheerm** [comment]
@errorJY i also need sensor expansion for carla.. have you started working on it?
