### ISSUE TITLE
./CarlaUE4.sh executable binary file not found

### ISSUE THREAD

**Issue by Cathe96** [carla-simulator/carla#2005]
Hello,

I am trying to run ./CarlaUE4.sh but receive the following error 
<img width="564" alt="Screen Shot 2019-08-17 at 11 12 35 pm" src="https://user-images.githubusercontent.com/39456817/63212251-c6dfbf80-c144-11e9-8eea-514974f8ecce.png">

Could anyone possibly tell me on how I could fix the issue? 

Thanks

**Comment by cassfalg** [comment]
What version of Carla is this? Binary download? Did you try to extract it again? Have you checked if the missing referenced file is there?

What Operating System? What shell? Which readlink command is in path? The one you're calling doesn't understand the -f option, so it's not the standard linux readlink command from ubuntu's coreutils package for example...

**Comment by mainakchain** [comment]
I am also facing the same issue. My system is a Machintosh system. Please let me know what could be the possible issue. @cassfalg
