### ISSUE TITLE
Can CARLA and AirSim be used at the same time?

### ISSUE THREAD

**Issue by ivannson** [carla-simulator/carla#2006]
I was wondering if it's possible to be using CARLA and AirSim at the same time, for example use cameras and Lidar from CARLA, but get IMU readings with AirSim? Or similarly use CARLA's implementation of the [walker bone control](https://github.com/carla-simulator/carla/blob/master/Docs/walker_bone_control.md) while using AirSim for some sensors?

**Comment by ArciAndres** [comment]
Same. I am interested in using both platform in simultaneous simulations.
