### ISSUE TITLE
Radar support

### ISSUE THREAD

**Issue by ivannson** [carla-simulator/carla#2007]
As per the [roadmap](https://github.com/carla-simulator/carla/blob/master/Docs/img/carla_timeline.png) there were plans to add Radar support by the end of 2019 Q3. Judging from the versions associated with the new features on the roadmap, I understand that it will be later than that. Is there an ETA for the Radar addition?

**Comment by ScottOGrady** [comment]
Same question as ivannson. I'm keenly looking forward for a radar sensor. Can you give some updates about your progress and some details / maybe a realistic timeframe when to expect it's release?
For my PhD project its an integral part of the simulation and I would be glad to get some info :)
Thanks in advance.

**Comment by pprivulet** [comment]
I'm looking forward for a radar sensor too. Do any progress have been made ?

**Comment by basavaraj1995** [comment]
Any progress have been made ?

**Comment by basavaraj1995** [comment]
**CARLA 0.9.7 now supports RADAR, IMU and all the camera-based sensors are provided with an additional parametrized lens distortion shader.**
