### ISSUE TITLE
[Semantic Segmentation] Adding a new tag to separate the traffic lights and Speed limit Traffic Sign.

### ISSUE THREAD

**Issue by aadityasp1** [carla-simulator/carla#2010]
Hi ,
I want to add a new tag to separate the traffic lights and Speed limit Traffic Sign...

I have moved all the speed limit traffic signs from "TrafficSigns" folder to a new folder "TSBoards" in "Content/Carla/Static" in Unreal Engine (4.22.3). I am using Carla 0.9.5 and I have referred to the carla documentation and the following issues #175 , #904 . But I'm still unable to see the color which I assigned in CityScapesPalette.h while running the server from the Unreal Editor and manual_control.py from "carla/PythonAPI/examples" . I have compiled from Editor and using "make launch" from carla folder, but still no result. Following are the changes I've made 

![semantic_issue_4](https://user-images.githubusercontent.com/49901865/63272250-5b6b2e80-c2b9-11e9-885f-d493b5a4d0c5.png)
![semantic_issue_3](https://user-images.githubusercontent.com/49901865/63272251-5b6b2e80-c2b9-11e9-87f8-b4182a90a729.png)
![semantic_issue_2](https://user-images.githubusercontent.com/49901865/63272254-5c9c5b80-c2b9-11e9-923d-6e93c489ff72.png)
![semantic_issue_1](https://user-images.githubusercontent.com/49901865/63272255-5d34f200-c2b9-11e9-9932-66a6851ee7ac.png)

Can anyone help me fix this ?

**Comment by cassfalg** [comment]
It would probably help if you could attach the files that you changed, or fork the codebase and commit your changes to your forked repo.

**Comment by aadityasp1** [comment]
Hi @cassfalg , following are the files I have changed,

Tagger.h, Tagger.cpp from  this path "../carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/"

CityScapesPalette.h from this path "../carla/LibCarla/source/carla/image/"

Also, for testing if the references are maintained after moving the speed limit traffic signs from "TrafficSigns" folder to a new folder "TSBoards", I moved back couple of Static Meshes to "TrafficSigns" folder from "TSBoards" and recompiled. It worked (I was able to see these static meshes in the same color as the traffic lights in Semantic segmentation output), so I don't think there is an issue with the references behind.



[semantic_issue.tar.gz](https://github.com/carla-simulator/carla/files/3519026/semantic_issue.tar.gz)

**Comment by YibWang** [comment]
> Hi @cassfalg , following are the files I have changed,
> 
> Tagger.h, Tagger.cpp from this path "../carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/"
> 
> CityScapesPalette.h from this path "../carla/LibCarla/source/carla/image/"
> 
> Also, for testing if the references are maintained after moving the speed limit traffic signs from "TrafficSigns" folder to a new folder "TSBoards", I moved back couple of Static Meshes to "TrafficSigns" folder from "TSBoards" and recompiled. It worked (I was able to see these static meshes in the same color as the traffic lights in Semantic segmentation output), so I don't think there is an issue with the references behind.
> 
> [semantic_issue.tar.gz](https://github.com/carla-simulator/carla/files/3519026/semantic_issue.tar.gz)

Were u able to resolve this issue? I even changed all three CityScapesPalette.h and nothing changed in the Semantic Segmentation images.
