### ISSUE TITLE
Carla Scenario

### ISSUE THREAD

**Issue by AminYounes92** [carla-simulator/carla#202]
I'm trying to build some sort of scenario using the simulator where i can force certain data (speed, steer, brake etc) to the client script according to the measurements values. is there any way to make the client script read certain data from external file and send these new control signals...!?

ex: if the speed pass 30 --> decrease speed until stop. but this according to data (flag) from eternal file.

**Comment by nsubiron** [comment]
Hi @AminYounes92, we provide a Python module for communicating with the CARLA server, but it's up to each user to implement a client for their needs.

Take a look at the example we give in [client_example.py](https://github.com/carla-simulator/carla/blob/master/PythonClient/client_example.py). You can easily modify it to do what you are asking by reading the speed from the `player_measurements` and adjusting `control` accordingly.
