### ISSUE TITLE
How to convert carla Image to numpy float32?

### ISSUE THREAD

**Issue by soulslicer** [carla-simulator/carla#2020]
I tried looking through some examples but I am not clear.

The out of the callback of sensor.camera.depth produces an image [800*600] of 1920000 bytes. Which means 4 bytes, or 1 float per pixel I assume

I saw this example to convert it to a uint8 image:

```
array = np.frombuffer(image.raw_data, dtype=np.dtype("uint8"))
            array = np.reshape(array, (image.height, image.width, 4))
            array = array[:, :, :3]
            array = array[:, :, ::-1]
```

Can someone please explain whats going on?

How exactly is the Image pointer structured?

EDIT:

Ic, so now I have it in RGB Format, and I am to apply this formula:

```
normalized = (R + G * 256 + B * 256 * 256) / (256 * 256 * 256 - 1)
in_meters = 1000 * normalized
```

**Comment by soulslicer** [comment]
Resolved

**Comment by marcgpuig** [comment]
Hi @soulslicer.
Looks like you want the depth image right?
Take a look at the [`carla.Image.convert(color_converter)`](https://carla.readthedocs.io/en/latest/python_api/#carla.Image.convert) function, it can be used like:
```py
import carla
from carla import ColorConverter as cc
# ...
image.convert(cc.Depth)
```
