### ISSUE TITLE
Roadrunner export option not available on demo version ! 

### ISSUE THREAD

**Issue by remitoudic** [carla-simulator/carla#2023]
Hello all of you 
 
I would like to make my own map , so I follow  the instructions  from the Documentation. 
https://carla.readthedocs.io/en/latest/how_to_make_a_new_map/

I downloaded and installed the Roadrunner on Ubuntu , but  I  was not able to export any files from  the program, no odr ,  no fbx file . 
I got from the program that I have to purchase Roadrunner for this option   .....  

![Screenshot from 2019-08-21 17-10-07](https://user-images.githubusercontent.com/8720785/63445459-ae1f2480-c438-11e9-8b15-243a50b7e415.png)

Is there any trick for  trying exporting files   ?  Or did I miss something ? 

Thank you in advance .....

**Comment by kbarbora** [comment]
Demo version does not come with the exporting option...
You have to buy a license.
