### ISSUE TITLE
Build custom map environment using road runner and Unreal engine

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2025]
Hello,

I followed the guide mentioned here [here](https://carla.readthedocs.io/en/latest/how_to_make_a_new_map/)
to create my custom environment map. I did not get any error, however, after importing the .fbx file into unreal engine the objects in the environment have no textures. 

Why are not the material textures/colors visible in unreal? 

Road Runner map:
![Screenshot from 2019-08-21 19-00-59](https://user-images.githubusercontent.com/1629735/63453089-27724380-c448-11e9-89e6-f5d7460e7bfa.png)

Unreal engine map:
![Screenshot from 2019-08-21 19-09-36](https://user-images.githubusercontent.com/1629735/63453107-3527c900-c448-11e9-9bf5-7c6cb53d35f3.png)
![Screenshot from 2019-08-21 19-04-31](https://user-images.githubusercontent.com/1629735/63453110-378a2300-c448-11e9-9475-db453f163824.png)

**Comment by sheelabhadra** [comment]
Hi @ndeshp2s, in case you're still facing issues, please take a look at the thread in #1911. I was facing a similar problem and it has been resolved now.
