### ISSUE TITLE
OpenGL run on server or client

### ISSUE THREAD

**Issue by Kailiangdong** [carla-simulator/carla#2027]
Execuse me，I have a naive question. When I run my simulator on one work station PC, and run client(show the scenes) on another PC , which computer actually uses opengl?  Which computer actually rendering?

Thank you very much.

**Comment by kbarbora** [comment]
from the docs:
[https://carla.readthedocs.io/en/latest/configuring_the_simulation/#running-off-screen](url)

**Comment by nsubiron** [comment]
The simulator does the render and most of the work.
