### ISSUE TITLE
How to run carla simulator (in installation from source)

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2032]
Hello all,

I recently setup carla from source since I want to make some changes to the source code.

However, I cannot figure out a way to run carla simulator just like we can do in the pre-compiled version using "./CarlaUE4.sh". 

Form the tutorials I follow that we need to run the simulator through unreal engine.

So I wanted to know if there is a way to run carla in the same way as with pre-compiled version?

Thank you.

**Comment by kbarbora** [comment]
You have to compile it. Once done, you go to your carla folder (where you have all the source code) and go to Dist/CARLA_Shipping_.../LinuxNoEditor/ and execute "./CarlaUE4.sh"

**Comment by nsubiron** [comment]
To complete @kbarbora answer, that's done with `make package`.

**Comment by jit-rc** [comment]
For faster builds you can do ```make package ARGS=--no-zip```
and this PR should be useful too https://github.com/carla-simulator/carla/pull/2034

**Comment by ndeshp2s** [comment]
Thank you @kbarbora , @nsubiron and @jit-rc for your replies and for sharing the information :)
