### ISSUE TITLE
waypoint direction problem

### ISSUE THREAD

**Issue by Zealoft** [carla-simulator/carla#2037]
- CARLA version(s): 0.9.4 , overnight 2019-03-19 and probably others
- Platform: Ubuntu 16.04

Currently there is a get_waypoint() method and its parameter is a carla.location class. Its definition is as below:

`get_waypoint(self, location, project_to_road=True, lane_type=carla.LaneType.Driving)`

I use this method to pass some locations and get a waypoint nearby. However, when I tried to use this method to get some waypoints I want, it often generates waypoints that is opposite to the direction I want, which means I'm not able to specify the waypoint rotation. So I wanna ask is there a way to get waypoints with concrete rotation that I want? Thank you very much.

**Comment by jackbart94** [comment]
Hi,

Have you tried using [next](https://carla.readthedocs.io/en/latest/python_api/#carla.Waypoint.next)? It only gets waypoints on your current lane, which should solve the issue regarding opposite directions.

Also, if possible, update to CARLA 0.9.6 for the latest features!
