### ISSUE TITLE
Modifying driving behaviour of Individual Non-player agents

### ISSUE THREAD

**Issue by andycmu** [carla-simulator/carla#2041]
Hi team, I have seen the same question asked here: https://github.com/carla-simulator/carla/issues/254. However, this file is gone in current master: carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/VehicleSpawnerBase.cpp. 
I have two main questions:
1. Could you help point me to the new file? Also, how do I connect this with python code? e.g. in which python file does the AIcontroller get used?
2. Can I change the behavior of non-play agent completely in python? e.g. I read current position in python client, compute next waypoint and set next position using python client again.

Thanks a lot!

**Comment by jackbart94** [comment]
Hi,

Each individual non-player agent is following a set of predetermined waypoints. I don't know what you want to achieve, but I'm pretty sure that changes regarding that should be made in the C++ scripts that are in charge of this.
