### ISSUE TITLE
Can Carla change camera FOV on the fly?

### ISSUE THREAD

**Issue by JunweiLiang** [carla-simulator/carla#2042]
Hi,

I'm using 0.9.6. I want to change FOV of the camera actor on the fly so we could simulate a PTZ camera. Is this possible? I know we could set FOV in the blueprint but there is no "set_attribute" for actors.

Thank you!

**Comment by marcgpuig** [comment]
Hi @JunweiLiang.
Currently, there is no way to do this. One (ugly) workaround is, if the FOV changes, delete the current sensor and create a new one with the desired FOV.

**Comment by JunweiLiang** [comment]
@marcgpuig
