### ISSUE TITLE
Error by building Carla from source  "Failed to find Material.... " 

### ISSUE THREAD

**Issue by remitoudic** [carla-simulator/carla#2046]
Hello  all of you , 

By building  Carla from source ,   I get an Error . I can not figure out how to solve it . ( I really followed carefully  the documentation).  I use Ubuntu 18.04

A screenshot from my terminal .....
Error message  comes  after the "make launch" 
 

![Screenshot from 2019-08-27 15-05-24](https://user-images.githubusercontent.com/8720785/63774169-f62cc400-c8dc-11e9-99d9-f0b66cdf9884.png)

 and then just after appear an error window from Unreal with the message

![Screenshot from 2019-08-27 15-20-01](https://user-images.githubusercontent.com/8720785/63774765-3d678480-c8de-11e9-9027-409cf5c01688.png)

If I click ok  then Unreal crashes :(

Maybe someone has an idea can help me  :)  I would be very greateful 
Thank you in advance

**Comment by fdomf** [comment]
Hello @remitoudic 
Did you try to update the content? With ./Update.sh

**Comment by remitoudic** [comment]
Hey ,  
@fdomf , Thank you for your answer  
Yes,  I  run  ./Update.sh ( as mentioned in the doc :) )

**Comment by adam3816** [comment]
I have the same problem
