### ISSUE TITLE
Lens Distortion

### ISSUE THREAD

**Issue by soulslicer** [carla-simulator/carla#2048]
I need to simulate having a distorted lens for both RGB and Depth Image. I understand that CARLA does not explicitly support it currently.

I want to know if it's as naive as say, using opencv to distort the image after getting the depth image.

**Comment by cassfalg** [comment]
In theory... during my research I found that opencv has functions to calibrate / figure out distortion parameters and undistort images, but not to distort them given a set of distortion parameters. If anyone knows of a public solution, please post and let me know?

There is a Paper called "Realistic Lens Distortion Rendering" by Martin Lambers, Hendrik Sommerhoff and Andreas Kolb from the University of Siegen, but they don't have code available and I did not reach out to them. I did not deem their approach feasible for my problem anyway.

**Comment by soulslicer** [comment]
Yes, would like to know too. I need to simulate a distorted camera, and i cannot find an opencv function for this
