### ISSUE TITLE
Make pedestrians walk through a list of waypoints

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2055]
Hello all,

I am using 0.9.6 version and want to move pedestrians through a list of waypoints. However, with the current implementation what I understand is after the "go_to_location" method, once the pedestrian reaches the target, its next target is generated randomly.

I wanted to know if there is some functionality existing to make the pedestrian move through desired list of waypoints?

Thank you.

**Comment by vesor** [comment]
Any comments? I need this feature too.

**Comment by Elvirawzy** [comment]
I have the same question, and how can I replay trajectories of pedestrians in Carla?
