### ISSUE TITLE
No make files generated  for CarlaUE4Editor after running "make launch"

### ISSUE THREAD

**Issue by hyhou** [carla-simulator/carla#2061]
Hi,

I followed the build instruction for linux and everything goes fine except the last step, when the BuildCarlaUE4.sh calls the GenerateProjectFiles.sh to generate the project files.

It then failed on finding the rules for target CarlaUE4Editor.
`make CarlaUE4Editor`
I looked the generated stuff and only find the CMakeLists with no makefile.
 
Though I could manually create the Makefile through the CMakeLists, but according to the script I should get the Makefile automatically. 

Has anyone experienced this before? Should I be bothered?

Thanks

**Comment by cassfalg** [comment]
`GenerateProjectFiles.sh` is part of the Unreal Engine installation. The Makefile for Carla is part of the git repository, it is not generated. If it's not there you're in the wrong directory or downloaded the wrong thing, carla's binary distribution or so for example. My suggestion: try to go through the steps again, make sure you finished them all and report back which step fails.
