### ISSUE TITLE
how to control other vehicles or pedestrians' action via keyboard in runtime

### ISSUE THREAD

**Issue by gulsumUz** [carla-simulator/carla#2062]
Hi, 

I'm using  carla 0.9.6 version in Ubuntu. I wonder whether Carla allows me to control other vehicle's action in runtime for my research. How can I change movement of the vehicle via taking keyboard input expect SUT vehicle while scenario is running ?

**Comment by cassfalg** [comment]
Using similar brevity, all I'm gonna suggest is `manual_control.py`?
