### ISSUE TITLE
Vulkan driver error

### ISSUE THREAD

**Issue by Abanoub-G** [carla-simulator/carla#2063]
Hi,
I am having issues with the latest Carla version. When I run make launch I get "Cannot find a compatible Vulkan dirver". 

![62615798-e9343a80-b905-11e9-9408-36ccd8227749](https://user-images.githubusercontent.com/40661756/64099840-2c959380-cd62-11e9-9bf3-4a75047c0514.png)

I have tried installing Vulkan from http://linuxconfig.org/install-and-test-vulkan-on-linux  but still getting the same error. 

Has anyone got an idea why this happening...?

Thanks in advance :)

**Comment by cassfalg** [comment]
Does your hardware meet the minimum specs? The Unreal build instructions mention them I think. What OS and what GPU? You can probably switch to the opengl backend somehow, though I don't know how for the editor.

**Comment by Abanoub-G** [comment]
yeah I think the specs are absolute fine, I have been using CARLA for a while on this same machine but it's just when I upgraded carla to the latest version I ran into this. Yes I was also trying to see how to make it use opengl in editor mode but you couldn't find it either...

**Comment by Abanoub-G** [comment]
Hi Everyone,
I have solved this now. In case anyone is running in the same problem, the solution is:
- Go to ~/carla/Util/BuildTools/BuildCarlaUE4.sh 
- Open it and change RHI="-vulkan"    to     RHI="-opengl"

That should make the "make launch" default settings set to use opengl instead of vulkan.

Best
Abanoub

**Comment by pmaini** [comment]
Hi,

This works if building Carla from the repo. Is there a way to use opengl with the deb version?

Thanks in advance!

**Comment by zsbztdxx** [comment]
> 
./CarlaUE4 -opengl

**Comment by zsbztdxx** [comment]
> Hi,
> 
> This works if building Carla from the repo. Is there a way to use opengl with the deb version?
> 
> Thanks in advance!

./CarlaUE4.sh -opengl
