### ISSUE TITLE
Why I can't spawn walkers on my own map?

### ISSUE THREAD

**Issue by fyj97** [carla-simulator/carla#2065]
I have a problem recently!
I have made a map using Roadrunner, which can be loaded into CarlaUE4 succesfully. And I can spawn vehicles by spawn_npc.py. And the vehicles can run according to my opendrive file. And I add the pedestrain mesh file to the right folder. But when I spawn walkers, they come to my map. But they can not stand on the road, they just fall down.
I use the same way in map of Town03, walkers can be spawned succesfully and move. I don't know why this happened.
![Screenshot 2019-09-02 10:15:20](https://user-images.githubusercontent.com/53674931/64120613-aa5d9d00-cd6a-11e9-92e7-e043811adf26.png)
I print the position of one of the walkers, he falls down the map and can not stand on the map like vehicles.
I try to put the mesh under static folder but it doesn't work.

THANK YOU VERY MUCH

**Comment by fyj97** [comment]
the pedestrain mesh means the nav file exported by recast/devour

**Comment by fdomf** [comment]
Hello @fyj97 !
We've recently added a new tutorial in our documentation about adding pedestrian navigation zones.
You can find it here https://carla.readthedocs.io/en/latest/how_to_make_a_new_map/#5-adding-pedestrian-navigation-zones

Make sure that `m_scale` parameter is `0.01f` so the mesh has the same scale as the map.

**Comment by fyj97** [comment]
Thank you very much @fdomf, it is a perfect document for building a map in carla!!
