### ISSUE TITLE
fix the non-sync of GPU data and CPU data

### ISSUE THREAD

**Issue by noahcao** [carla-simulator/carla#2069]
Thanks for the great simulator but I'm facing an issue in the sync mode. In the introduction in the sync mode, you mention:
> Note that data coming from GPU-based sensors (cameras) is usually generated with a delay of a couple of frames respect to data coming from CPU-based sensors.

So when I'm trying to do some real-time work on it, the semantic segmentation information and the 3D bounding box are not synced. For example, the red bounding box is the edge of segmentation and the blue bounding box is the 2d projection of the current 3d-bounding box. The 3d-bbox is about 2 frames ahead of the segmentation information which is synced with the rgb camera information. 

![image](https://user-images.githubusercontent.com/17743251/64201584-e0bb1b00-ce43-11e9-8413-86266d139236.png)

This issue is very tough for me. Is there some solution to fix it or to work around it? Thank you.

**Comment by soulslicer** [comment]
I have the same issue, and from what I've read it doesn't seem like there is any fix.

I ended up just "extracting" the bounding box from the semantic segmentation and depth map information. Granted its slow

**Comment by noahcao** [comment]
Still haven't fixed this issue. Anyone has any suggestions on any version of CARLA?
