### ISSUE TITLE
NO Pedestrians

### ISSUE THREAD

**Issue by dragonmlz** [carla-simulator/carla#207]
Download 0.7.1 and the contents.
when the map of town1 running, there are no pedestrians.
And search the materials of  pedestrians in UE4, also can't found.
How can I do something?

**Comment by nsubiron** [comment]
Pedestrians are not yet available in the build-from-source version of CARLA.

> CARLA uses pedestrians created with Adobe Fuse, which is a free tool for that purpose. Currently, we cannot redistribute these pedestrians models. They can only be used in the provided executable.

However we are working on new pedestrians models free to distribute, follow the progress at #188.
