### ISSUE TITLE
mislabeled traffic light road_id in Town01 

### ISSUE THREAD

**Issue by bradyz** [carla-simulator/carla#2071]
I believe there is a mislabeled traffic light in Town01 (v0.9.6)

This was found by observing that the `_is_light_red_europe_style` function in `agent.py` would run this particular red light.

https://github.com/carla-simulator/carla/blob/master/PythonAPI/carla/agents/navigation/agent.py#L94 fails because the waypoint of the traffic light's road_id doesn't match the road_id of the ego-vehicle (see image).

![image](https://user-images.githubusercontent.com/7716849/64231708-f8cb8280-ceb5-11e9-842f-41df7d05635f.png)

In this image, the egovehicle's road_id is 19, and the traffic light's waypoint road_id is 108.

Here is a first person view, for more context.

![image](https://user-images.githubusercontent.com/7716849/64232326-5f9d6b80-ceb7-11e9-9906-4e2325594099.png)

Please let me know if any clarification is needed.

**Comment by dianchen96** [comment]
Moving this particular traffic light half meter back in the map editor solves the issue. Still was wondering if this will be fixed in the next official release? Thanks!
