### ISSUE TITLE
How can I get lane offset using the waypoint API

### ISSUE THREAD

**Issue by aakashsehgal** [carla-simulator/carla#2072]
I need to calculate the lane offset which would be then fed to the control algorithm. After researching, I found the use of waypoint API to be optimal. But i have certain doubts in understanding its functionality :

- `waypoint_current = world.get_map().get_waypoint(ego_vehicle.get_location(),project_to_road=True)`

This will give me a waypoint on the centre of the road. Does it mean if I have a single lane, then this current_waypoint will be at the centre of this lane and closest to the position of my ego vehicle ?

- `next_waypoint = waypoint_current.next(0.2)`

What will `next_waypoint` imply ? Is it the list of all the waypoints between `waypoint_current` (close to my ego vehicle) and 0.2 metres ahead ?

- By using the waypoint API, I can get the transform i.e. rotation and location. How can i use this information to calculate my lane offset ? Can i do something like this ?

`(lane_offset)^2 = (waypoint_current.transform.location.x - ego_vehicle.get_location().x)^2 + (waypoint_current.transform.location.y - ego_vehicle.get_location().y)^2   `

**Comment by aakashsehgal** [comment]
@marcgpuig

**Comment by AravindChandradoss** [comment]
@aakashsehgal Any updates? 
I am looking for the same functionality. Were you able to calculate the distance/orientation to the lane center? 

On a separate note, are you using Autopilot (I mean the one which runs on server-side) while finding/collecting your waypoints?
