### ISSUE TITLE
some bundled map is incorrect

### ISSUE THREAD

**Issue by atinfinity** [carla-simulator/carla#2074]
## System information (version)
- Ubuntu 18.04 64bit
- CARLA v0.9.6(compiled version)

## Detailed description
I used [pcl_recorder](https://github.com/carla-simulator/ros-bridge/tree/master/pcl_recorder) to make HDMap. And, I visualized generated HDMap and bundled HDMap using RViz. As a result, I think that bundled map is incorrect.

- PointCloud(Pink): Generated HDMap
- PointCloud(Green): Bundled HDMap
- Marker(Green): Vehicle Position

![Screenshot from 2019-09-04 23-06-20](https://user-images.githubusercontent.com/2630323/64262703-73a1a580-cf69-11e9-9490-466e5a35d4d4.png)

This time, I checked `CARLA_0.9.6/HDMaps/Town01.pcd`.

**Comment by atinfinity** [comment]
I checked `Town03`.

* PointCloud(Pink): Generated HDMap
* PointCloud(Green): Bundled HDMap

![Screenshot from 2019-09-05 23-55-05](https://user-images.githubusercontent.com/2630323/64353595-f9405680-d038-11e9-8183-7cc08c886059.png)

**Comment by ThrashAbaddon** [comment]
Has anyone from Carla team tried to verify this?

**Comment by atinfinity** [comment]
I found that fixed pointcloud map is distributed in the following repository.

- https://bitbucket.org/carla-simulator/carla-content/src/master/HDMaps/
- https://bitbucket.org/carla-simulator/autoware-contents/src/master/maps/

**Comment by atinfinity** [comment]
Is there any progress?
