### ISSUE TITLE
How to change location/position of camera/lidar sensor on car?

### ISSUE THREAD

**Issue by basavaraj1995** [carla-simulator/carla#2080]
I'm a newbie to Carla, working on a college project and I'm unable to figure out how to move sensor location on the car.

**Comment by sebamateja** [comment]
Sensors are actors, you can change their position using set_location/set_transform (Python) or SetLocation/SetTransform. While spawning actors you can set their transform (second argument). 
http://carla.org/Doxygen/html/d6/da5/classcarla_1_1client_1_1Actor.html
https://carla.readthedocs.io/en/latest/python_api/#carlaactor-class

**Comment by basavaraj1995** [comment]
thanks
