### ISSUE TITLE
Obstacle sensor distance remains constant

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2081]
Hello all,

I am trying to use the obstacle sensor in Carla 0.9.6. However, the sensor always shows a constant reading event after the obstacle is moved. How do i solve this?

Thank you.

**Comment by dkarunakaran** [comment]
@ndeshp2s I am having the same problem. Did you solve it?

**Comment by marcgpuig** [comment]
Did #2182 fixed this problem?
