### ISSUE TITLE
Weather Parameters Typo in Documentation

### ISSUE THREAD

**Issue by travelbureau** [carla-simulator/carla#2085]
Carla Version 0.9.6 (release)
OS: Ubuntu 18.04

Bug: Documentation claims you can set the cloud cover using the `cloudiness` member variable in the `carla.WeatherParameters` class, the actual API requires `cloudyness`.

**Comment by cassfalg** [comment]
I can confirm this. The PythonAPI documentation refers to cloudiness, which incidentally is the correct way to spell it.
https://carla.readthedocs.io/en/latest/python_api/#carla.WeatherParameters
So both
https://carla.readthedocs.io/en/latest/python_api_tutorial/#changing-the-weather
and the API itself should be changed.
