### ISSUE TITLE
How extract the angle of pixel in camera depth

### ISSUE THREAD

**Issue by MarneFilho** [carla-simulator/carla#2097]
Hello,
I am using camera.depth to get a distance of object (BP_SpeedLimit30). But i need the angle's distance to transform this distance in coordinates.

Map: Town03 (Carla0.9.5)
Attached depth camera: "...Location(x=1.600, z = 1.700)"
Vehicle world spawn(Vehicle position in simulation): "..Location(x= 241.250, y=150.750, z=1.348)"
BP_SpeedLimit30 position in center of board (Get on unreal):  x= 247.936, y = 117.181 z = 2.526
Camera Settings: 1280x720, FOV 90°
Center of Board in Pixel coordinates: 774,360
Distance: Print Image[774][360] = " 31.86542"

![image](https://user-images.githubusercontent.com/49208955/64722297-29a24d80-d49c-11e9-8dda-2776c5103231.png)

Thanks for help.
att,

**Comment by btknzn** [comment]
Hello, how did you calculated the angle ?

**Comment by MarneFilho** [comment]
i cant figure out how obtain angles from depth camera, this only retrieve distances...
I used CARLA 0.9.5.
