### ISSUE TITLE
get_velocity/angular_velocity return 0 when replaying the recorder file

### ISSUE THREAD

**Issue by ppjtzjb** [carla-simulator/carla#2099]
get_location() and get_transform() works fine, but no velocity or angluar_velocity. Is it because the recording feature didn't record the speed, or is there anything missing on my end?

Any help is appreciated!

**Comment by danyz91** [comment]
@ppjtzjb do you have any update on this? I have the same problem when replaying logs. I use carla docker.

**Comment by Morphlng** [comment]
According to this [answer](https://github.com/carla-simulator/carla/issues/3145), when you replay the record file, it doesn't really re-simulate the episode, but rather use the minimum information to recreate the scene (Mainly based on teleporting). This means that anything requiring physical simulation will not work, including velocity as you present. You can try to calculate an approximate velocity based on the location and frame time info provided in the record file.
