### ISSUE TITLE
Issue while compiling

### ISSUE THREAD

**Issue by rsatyan** [carla-simulator/carla#2105]
In file included from /Users/savatara/Downloads/carla/LibCarla/source/carla/opendrive/OpenDrive.h:9:
/Users/savatara/Downloads/carla/LibCarla/cmake/../source/carla/Memory.h:9:10: fatal error:
      'boost/enable_shared_from_this.hpp' file not found
#include <boost/enable_shared_from_this.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Keep getting this error, I checked the file exists in the boost dir. I'm stuck. Please help!

**Comment by gpelaez2958** [comment]
Hi rsatyan,
Did you find a solution for this problem?

**Comment by LikhitaNukala** [comment]
I'm also looking for the solution to the same problem since 2020
