### ISSUE TITLE
How to get the focal length of rgb camera sensor in carla?

### ISSUE THREAD

**Issue by SaiVinay007** [carla-simulator/carla#2110]
Hi, can someone please tell how to get the focal length of rgb camera sensor?.

I went through the documentation but couldn't find it. I found few other camera parameters from the [docs](https://carla.readthedocs.io/en/latest/cameras_and_sensors/#sensorcamerargb) but wasn't able to get the focal length using those camera parameters

**Comment by jrojoCI3** [comment]
Do you mean the focal distance? If so, it is an attribute of the blueprint called 'focal_distance'. An Actor in CARLA should be able to call the method attributes(), but in our case it is throwing some errors. A possible solution is to store it when creating the camera. Please, let us know if the attributes() method works for you, and if you managed to solve your problem. Good luck!
