### ISSUE TITLE
Openai Gym interface for Carla 0.9.6?

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2114]
Hello all,

Is there any openai gym interface implementation existing already for Carla 0.9.6?

I searched a bit online, however, most of the work is for 0.8.

**Comment by praveen-palanisamy** [comment]
@ndeshp2s :The code in this repository: [https://github.com/praveen-palanisamy/macad-gym](https://github.com/praveen-palanisamy/macad-gym) provides learning environments based on CARLA 0.9.x with OpenAI Gym compatible interface. It supports multi-agent scenarios where you can train/control each agent.
