### ISSUE TITLE
CarlaUE4 crashed when import .fbx with RoadRunner Plugin enabled

### ISSUE THREAD

**Issue by aurthes6220** [carla-simulator/carla#2121]
1, I followed documentation and export Carla format by RoadRunner.
![Screenshot from 2019-09-19 19-56-20](https://user-images.githubusercontent.com/49723017/65242010-9c07d300-db17-11e9-9612-dc74869a330c.png)
2，Installed RoadRunner Plugin and enable it
![Screenshot from 2019-09-19 20-03-34](https://user-images.githubusercontent.com/49723017/65242442-965ebd00-db18-11e9-815c-2e56addd4710.png)
3，Imported .fbx file, and it is auto detected by plugin.
![Screenshot from 2019-09-19 20-06-22](https://user-images.githubusercontent.com/49723017/65242590-f9505400-db18-11e9-837a-d059d89f4ed2.png)
4, Checked every combo box carefully with the guide and clicked import, waiting a minute, then it CRASHED:
![Screenshot from 2019-09-19 19-32-38](https://user-images.githubusercontent.com/49723017/65242722-5815cd80-db19-11e9-95de-0bdf788131dd.png)

 I doubt it attributes to the data, and tried another one (Town01.xodr under carla folder itself). It crashed again in the same way.
I used Unreal Engine without any plugins to import .fbx, it appears normal.

Could anyone tell me what's wrong with it? Thanks.

**Comment by fyj97** [comment]
I think RoadRunner Plugin is not necessary for import map, you can directly import the fbx file.

**Comment by aurthes6220** [comment]
> I think RoadRunner Plugin is not necessary for import map, you can directly import the fbx file.

Thank you for reply. 

I have figured out this problem is not concerned with RoadRunner plugin. It occurred when click 'generate road network' check box on 'OpenDrive Actor' detail tab on the right side.

So, RR plugin is just automatically clicked it when import fbx file and crashed. Have you ever met with this? Is this situation caused by invalid built or data?

**Comment by aurthes6220** [comment]
Solved.. 
The xodr file should not have any spiral geometries inside, or crash above might occur.

**Comment by SExpert12** [comment]
Hi,
I am facing the same issue. The UE editor shows import process when I select .fbx file and then it got crashed. I don't understand how did you resolve this.
and what do you mean by this-" It occurred when click 'generate routes' check box on 'OpenDrive Actor' detail tab on the right side."
Thanks in advance.
