### ISSUE TITLE
Instruction to implement controllers for scenarios

### ISSUE THREAD

**Issue by mango009** [carla-simulator/carla#2122]
Need help to implement a controller for scenarios.
Is there a standard set of function the controller need to implement?

Is there a recipe that I can use?

The only controller that I found is manual_control.py but this code is a bit too coupled with pygame. All I need is a 'headless' controller that it receive sensor information and output control information.

Thanks for any help

**Comment by fabianoboril** [comment]
This issue is better answered in the CARLA main repo. I will move it there.
