### ISSUE TITLE
Torchvision hangs forever with Carla  

### ISSUE THREAD

**Issue by bradyz** [carla-simulator/carla#2132]
Hi, I'm having import errors when i try to import torchvision.

I'm using torchvision=0.4.0=py35_cu100
installed via conda (conda install torchvision -c pytorch).

Minimal example:

```
import torchvision
import carla
```

Works, but

```
import carla
import torchvision

```
hangs indefinitely

**Comment by felipecode** [comment]
This is a bug. I have observed the same.
The same also happens when importing torch before carla.

**Comment by filangel** [comment]
Apparently it's not `torchvision` but `torch` itself:

![torch carla-bff](https://user-images.githubusercontent.com/12871137/75345412-99629400-5894-11ea-9ddf-002e99b5046c.png)

Please make this **clear** in the docs!

**Comment by Beskhue** [comment]
I had the same issue using torchvision 0.5. I haven't tested 0.4. However, torchvision 0.2.1 works.

**Comment by wangguanzhi** [comment]
Same here!

**Comment by Beskhue** [comment]
This should be fixed by https://github.com/carla-simulator/carla/commit/711738b1b91fc60325e693ed2a1d884f5b1fa6db.

Also see https://github.com/pytorch/pytorch/issues/36034.

**Comment by filangel** [comment]
same applied to [`dm-sonnet`](https://pypi.org/project/dm-sonnet/).

**Comment by germanros1987** [comment]
Folks, have you tried this in 0.9.9? We solved it over there. I am closing this issue, but happy to reopen it if somebody finds problems again.
