### ISSUE TITLE
Ability to set random seed for get_random_location_from_navigation()

### ISSUE THREAD

**Issue by n1try** [carla-simulator/carla#2136]
@bernatx implemented `carla.World.get_random_location_from_navigation()` a while ago, which is quite a useful method. However, it uses `rand()` without a previous call to `srand()`.

Accordingly, on every client restart, the same arbitrary random seed will be chosen, which implies that in every run, pedestrians will be placed at the exact same spawn points.

While this is actually desirable for some scenarios, other use cases might require the ability to manipulate randomness.

I'd like to have a way to initialize a random seed from Python code.

**Comment by xinshuoweng** [comment]
do we have any solution for it now?

**Comment by Alby407** [comment]
Almost a year now and still no answer?
