### ISSUE TITLE
Camera PostProcessing SemanticSegmentation generates void images

### ISSUE THREAD

**Issue by hs105** [carla-simulator/carla#214]
Using PostProcessing = 'SemanticSegmentation', it generates void (black) images. 

I noticed on the documentation page, the latest code generates black images too: here:

http://carla.readthedocs.io/en/latest/cameras_and_sensors/

**Comment by nsubiron** [comment]
Hi @hs105,

The semantic segmentation image has the tags encoded in the red channel, these tags go from 0 to 12, that's very dark shades of red. The image in the documentation is a sample, if you take a closer look it is not black but it has some dark shades of red.

**Comment by hs105** [comment]
Thanks for your clarification.

**Comment by RogerAylagas** [comment]
Knowing that, how do you transform the "black image" to the color one?

**Comment by marcgpuig** [comment]
Hi @RogerAylagas 
This is an already answered question, but you can do something like this:
```py
from carla import image_converter

# other stuff...

encoded_sem_seg = sensor_data.get('CameraSemSeg', None)
colored_sem_seg = image_converter.labels_to_cityscapes_palette(encoded_sem_seg)
```

**Comment by kk2491** [comment]
@marcgpuig I am using the latest pre-compiled version of Carla. I am not able to import ```image_converter```.

```
>>> from carla import image_converter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name image_converter
>>> 
```

Whether the pre-compiled version doesnt support image_converter ?

Thank you,
KK

**Comment by marcgpuig** [comment]
@kk2491 which version are you using?

**Comment by kk2491** [comment]
@marcgpuig I am using the latest version 0.9.2 pre-compiled one.
