### ISSUE TITLE
When can Carla deal with poly3 geometry exported by roadrunner

### ISSUE THREAD

**Issue by fyj97** [carla-simulator/carla#2147]
Recently I found that Carla can not read the poly3 geometry in the OPENDRIVE file exported by roadrunner. I have tried many ways to prevent that. But failed. When can this kind of geometry be loaded properly?

Thanks a lot

**Comment by Andrea2202** [comment]
Updates on this?

**Comment by fyj97** [comment]
It is still not supported in importing OPENDRIVE file. I really hope it can be repaired.

**Comment by fyj97** [comment]
![Screenshot 2019-12-13 11:10:42](https://user-images.githubusercontent.com/53674931/70766657-5b77c880-1d99-11ea-8ce6-1bd5a0abdafa.png)
