### ISSUE TITLE
Pedestrians not working in Synchronous mode

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2149]
Hello all,

I am creating a scenario where there are multiple pedestrians walking around in the environment. It works completely fine in normal mode. However, when I try this in synchronous mode, pedestrians are spawned but are immediately invisible. I am using world.tick() for every time step, but it still does not work.

**Comment by rueeggmi** [comment]
Hi, did you manage to solve this issue? I have the same problem.

**Comment by tungnt101294** [comment]
I have a somewaht similar problem. After having spawned the pedestrian model, I spawned an ai walker controller attached to the pedestrian. But after a few ticks, as the pedestrian disappeared, the ai controller was respawned to a random location near the origin.

I set a tick() right after spawning the pedestrian, and the problem when away.
