### ISSUE TITLE
Improvements in the benchmarking

### ISSUE THREAD

**Issue by felipecode** [carla-simulator/carla#216]
Currently the system to benchmark AI methods using CORL2017 tests is very long.
It takes around 15 hours more or less. For now it is possible to stop and resume your benchmark, but
there are a few issues on the implementation. 
When the methods restart it tends to overwrite the last task done by the car.
This issues have already been fixed and are under review for version 0.8

**Comment by mvpcom** [comment]
Haha, I just wanted to remind you for fixing this and I found this one :D 
For myself, I just removed the question in the Benchmark code for now and the new code is as follows: 

```
def _continue_experiment(self, continue_experiment):
        if self._experiment_exist():
            if continue_experiment:
                line_on_file = self._get_last_position()
	    else:
		line_on_file = 0
        else:
            line_on_file = 0

        return line_on_file
```

**Comment by mvpcom** [comment]
Unfortunately, the question itself is a problem because, in the middle of the test, a query will be popped up and need someone to answer it otherwise a connection error will be rise.
