### ISSUE TITLE
Semantic tags of an actor in python

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2161]
Is it possible to access the semantic_tags variable (list) of an actor in a python code?

**Comment by NicGalli** [comment]
As now i get this when trying to access semantic_tags:
```python
tags = vehicle.semantic_tags
```

```python
TypeError: No to_python (by-value) converter found for C++ type: std::vector<unsigned char, std::allocator<unsigned char> >
```

**Comment by s-rajab** [comment]
@NicGalli @ndeshp2s, any solution for this issue? Thanks.

**Comment by MartinDubreuil** [comment]
I have exactly the same problem under CARLA 0.9.6 built from source. Any solution ?

**Comment by gabrik** [comment]
Bump for interest, the same issue in 0.9.10 on Linux
