### ISSUE TITLE
Documentation  clarification  :  How to buitld carla > step 2  

### ISSUE THREAD

**Issue by remitoudic** [carla-simulator/carla#2162]
Hello Carla Team , 
First, thank you  for all the work you already accomplished. You are building an great opern source project . 

I  would like to  have additional  information  about a paragraph in the Documentation. 
In the "How to build Carla on Linux"  Section  before the second block of command lines  you advised to  to compile Carla  with clang 6. I got it  an I want to make it sure  I do it. 
 
Can you explain how it is related to the 2 command lines  that you put after  are doing it ? 
 
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-7/bin/clang++ 170
sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-7/bin/clang 170

It looks like more than you set it up to compile with clang 7 . Isn't it ? 

Thank you in advance for your reply

**Comment by cassfalg** [comment]
That part of the documentation is likely old. Carla uses / needs to use the same clang as Unreal Engine uses, which has been clang-7 for about half a year. So yes, clang-7 is correct in my experience. The apt-get install statements also install clang-7 if you look closely.
