### ISSUE TITLE
PixelReader causes crash of CarlaUE4 Server:  Exception was "SIGSEGV: invalid attempt to write memory at address 0x0000000000000003

### ISSUE THREAD

**Issue by vulkanzhou** [carla-simulator/carla#2165]
I packed 20 sensors in the ego car at the same time. Most of them are cameras. Sometimes the server crashes with the info: Exception was "SIGSEGV: invalid attempt to write memory at address 0x0000000000000003". The generated report is as follows. I'm not sure if I can pack so many sensors at the same time, or the crash is due to other reasons. Does anyone have ideas? Thanks

**Generating report for minidump:**

Application version 4.22.3.0
 ... built from changelist 0

OS version Linux 4.15.0-64-generic 
Running 4 x86_64 processors (4 logical cores)
Exception was "SIGSEGV: invalid attempt to write memory at address 0x0000000000000003"

<SOURCE START>
<SOURCE END>

<CALLSTACK START>
libUE4Editor-Core.so!FGenericPlatformMisc::RaiseException(unsigned int) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/GenericPlatform/GenericPlatformMisc.cpp:411]

libUE4Editor-Core.so!FUnixErrorOutputDevice::Serialize(char16_t const*, ELogVerbosity::Type, FName const&) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/Unix/UnixPlatformStackWalk.cpp:70]

libUE4Editor-Core.so!FOutputDevice::LogfImpl(char16_t const*, ...) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/Misc/OutputDevice.cpp:71]

libUE4Editor-Core.so!AssertFailedImplV(char const*, char const*, int, char16_t const*, __va_list_tag*) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/Misc/AssertionMacros.cpp:101]

libUE4Editor-Core.so!FDebug::CheckVerifyFailedImpl(char const*, char const*, int, char16_t const*, ...) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/Misc/AssertionMacros.cpp:436]

libUE4Editor-VulkanRHI.so!FVulkanCommandBufferManager::WaitForCmdBuffer(FVulkanCmdBuffer*, float) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/VulkanRHI/Private/VulkanCommandBuffer.cpp:364]

libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::RHIReadSurfaceData(FRHITexture*, FIntRect, TArray<FColor, FDefaultAllocator>&, FReadSurfaceDataFlags) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/VulkanRHI/Private/VulkanRenderTarget.cpp:760]

libUE4Editor-Carla.so!FPixelReader::WritePixelsToBuffer(UTextureRenderTarget2D&, carla::Buffer&, unsigned int, FRHICommandListImmediate&) [/home/simulation/perception_carla_simulation/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.cpp:148]

libUE4Editor-Carla.so!auto void FPixelReader::SendPixelsInRenderThread<ADepthCamera>(ADepthCamera&)::'lambda'(ADepthCamera&)::operator()<FRHICommandListImmediate>(ADepthCamera&) [/home/simulation/perception_carla_simulation/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h:100]

libUE4Editor-Carla.so!TGraphTask<TEnqueueUniqueRenderCommandType<void FPixelReader::SendPixelsInRenderThread<ADepthCamera>(ADepthCamera&)::FWritePixels_SendPixelsInRenderThreadName, void FPixelReader::SendPixelsInRenderThread<ADepthCamera>(ADepthCamera&)::'lambda'(ADepthCamera&)> >::ExecuteTask(TArray<FBaseGraphTask*, FDefaultAllocator>&, ENamedThreads::Type) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Public/Async/TaskGraphInterfaces.h:842]

libUE4Editor-Core.so!FNamedTaskThread::ProcessTasksNamedThread(int, bool) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/Async/TaskGraph.cpp:685]
libUE4Editor-Core.so!FNamedTaskThread::ProcessTasksUntilQuit(int) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/Async/TaskGraph.cpp:581]

libUE4Editor-RenderCore.so!RenderingThreadMain(FEvent*) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/RenderCore/Private/RenderingThread.cpp:332]

libUE4Editor-RenderCore.so!FRenderingThread::Run() [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/RenderCore/Private/RenderingThread.cpp:481]

libUE4Editor-Core.so!FRunnableThreadPThread::Run() [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.cpp:25]

libUE4Editor-Core.so!FRunnableThreadPThread::_ThreadProc(void*) [/home/simulation/UnrealEngine-4.22/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.h:177]

libpthread.so.0!UnknownFunction(0x76b9)
libc.so.6!clone(+0x6c)

<CALLSTACK END>

0 loaded modules

Report end!

**Comment by ucbmpc2021** [comment]
Any update on this? Have you found any solution?
