### ISSUE TITLE
Compiling CppClient is slow

### ISSUE THREAD

**Issue by Yougmark** [carla-simulator/carla#2167]
It's very nice to have this `Example/CppClient`.  But (I think) because of using `Boost`, it takes long time to compile.  Any suggestions to make it faster? I'm happy to submit a PR if I could make it faster.

**Comment by nsubiron** [comment]
If you change the compiler to clang it compiles much faster, but we do it in gcc to make sure the client-side is able to compile with both compilers (PythonAPI is compiled with clang).
