### ISSUE TITLE
Developing custom sensor using a shared library

### ISSUE THREAD

**Issue by martkir0919** [carla-simulator/carla#2168]
Hi!

I have a question related to adding new sensors to CARLA. Therefore, I've already completed the related tutorial (https://carla.readthedocs.io/en/latest/dev/how_to_add_a_new_sensor/). 

Now I want to use a custom shared library (*.so) in the code running as UE4 plugin (e.g. in the SafeDistanceSensor.cpp from the Tutorial). 

1) Where should I specify the additional include folders of the shared library?
2) Where can I specify custom libraries for linking?

Thank you.

**Comment by xmyqsh** [comment]
@martkir0919 include it where you want to use the API for simplicity. Or, you could package it in an extra and elegant way.
For linking, link it where you use it, it should be best to set it in the Libcarla Server Side. And you can call its api in the client side or carla side by the way of the `new sensor tutorial` described.
