### ISSUE TITLE
sensor.camera.rgb attributes?

### ISSUE THREAD

**Issue by OceanWong1991** [carla-simulator/carla#2176]
Hi;
   I want to custom my own rgb camera when I write code like that 
```
client = carla.Client('localhost', 2000)
client.set_timeout(10.0) # seconds
world = client.get_world()
blueprint_library = world.get_blueprint_library()

camera_bp = blueprint_library.find('sensor.camera.rgb')
camera_bp.set_attribute('sensor_tick', str(0.0))
camera_bp.set_attribute('iso', str(1200.0))


for attr in camera_bp:
	print('attr', attr.id)
```

**Traceback (most recent call last):
  File "test.py", line 43, in <module>
    camera_bp.set_attribute('iso', str(1200.0))
IndexError: attribute 'iso' not found**

and I print attr :
('attr', 'motion_blur_max_distortion')
('attr', 'motion_blur_intensity')
('attr', 'gamma')
('attr', 'enable_postprocess_effects')
('attr', 'fov')
('attr', 'image_size_y')
('attr', 'image_size_x')
('attr', 'motion_blur_min_object_screen_size')
('attr', 'sensor_tick')
('attr', 'role_name')

So why the number of attres much less than [doc](https://carla.readthedocs.io/en/latest/cameras_and_sensors/#sensorcamerargb)?

Carla version : CARLA 0.9.6 (development)
OS : Ubuntu 16.04

**Comment by Jabkowsky** [comment]
I have the same issue. 
I catches on debug "sensor.camera.rbg" object and showed attributes of it:
![sensor_rgb](https://user-images.githubusercontent.com/44050097/69315733-7a21ee00-0c37-11ea-8061-bdd9c67b0947.JPG)
it's only 6 of them ?? where are the others from described in documentation ?

Carla version : CARLA 0.9.5 (Experimental)
OS : Windows 7
