### ISSUE TITLE
When to release the methods evaluated in the CARLA paper?

### ISSUE THREAD

**Issue by tomchen1000** [carla-simulator/carla#218]
I wondered if you have an update on when to release the methods evaluated in the CARLA paper. Namely the high level topological planner and the three approaches: modular pipeline, imitation learning and reinforcement learning.

**Comment by felipecode** [comment]
Hellon @tomchen1000 
The high level topological planner is released on version 0.7.1 

The imitation learning approach is released under the carla-simulator organization .
https://github.com/carla-simulator/imitation-learning

Cheers.

**Comment by hs105** [comment]
Thanks. what's your schedule for the other two methods?

**Comment by felipecode** [comment]
We hope to release then soon !
Thanks for the interest .

**Comment by zdx3578** [comment]
@tomchen1000 @hs105  ref
https://github.com/NervanaSystems/coach
https://github.com/18605973470/rl-with-carla
https://github.com/kvasnyj/carla

**Comment by eds89** [comment]
Hi.
By running the evaluated methods, how can I see the car navigating and deviating from obstacles,  while the experiment is executed?

**Comment by varunjammula** [comment]
Any plans on the modular pipeline?
