### ISSUE TITLE
how to save waypoints and speed like saved as txt file in manual_control.py?

### ISSUE THREAD

**Issue by Kingsman1995** [carla-simulator/carla#2184]

**Comment by Kingsman1995** [comment]
When I change into autopilot mode, how can I save waypoints and speeds when the car is driving on the road? like store these information into .txt file or np.array form. Thanks very much!!!

**Comment by aurthes6220** [comment]
1, Get all the waypoints by 'carla.get_world().get_map().generate_waypoints(s)';
2, Get car's current location & speed by 'vehicle.get_location()' & 'get_speed()';
3, Write several lines of code to judge closest ones, and write to .txt.
