### ISSUE TITLE
[SOLVED]How can I save depth raw data?

### ISSUE THREAD

**Issue by petroskey** [carla-simulator/carla#2187]
Hi, thank you for your great simulator. It is quite interesting.
I am trying to save "raw depth map as csv" of every frame.
While the default setting allows us to save encoded RGB images of depth, how can I save raw depth map in python script?

The default is like: 
image.save_to_disk('%s/camera/depth/%08d' % (self.args.save_folder, camera_number, image.frame))

It seems to me that image.save_to_disk automatically gets depth image and convert it to RGB image. Should I modify that function, or is there any expected way to save raw depth?

Thank you in advance:)

**Comment by cassfalg** [comment]
https://carla.readthedocs.io/en/latest/cameras_and_sensors/#sensorcameradepth

This explains how depth is encoded into the raw depth image. I am not sure what you want to do otherwise, or what you mean with "raw depth". If that link does not help, can you please elaborate on what you are trying to do?

**Comment by petroskey** [comment]
@cassfalg 
Thank you for your kind reply. I understand it.
I have taken a mistake in my decoding code. 
Your support and the sample code were helpful for me:)

**Comment by eloy96vg** [comment]
Hi @petroskey ! 
I want to save data from cameras but i don't know. 
Can you explain me what I have to do to get data or what file I have to modify?

Thanks in advance!

**Comment by cassfalg** [comment]
There's an example for exactly this in the python API Tutorial:
https://carla.readthedocs.io/en/latest/python_api_tutorial/

I kindly suggest you read some of the documentation, have a look at some of the python examples like tutorial.py and open your own issue with any specific questions you may have left.

**Comment by bsandy1978** [comment]
> @cassfalg Thank you for your kind reply. I understand it. I have taken a mistake in my decoding code. Your support and the sample code were helpful for me:)

How did you resolve it. How should I save the depth images on disk(the black and white images).
