### ISSUE TITLE
Carla client data in global coordinates, how to convert to local coordinates

### ISSUE THREAD

**Issue by prashant030591** [carla-simulator/carla#2189]
In CARLA 0.8.4 version
When reading data from client all data are in global coordinates in manual_control.py
measurements, sensor_data = self.client.read_data()

The measurements above are as follows :
player_measurements {
  transform {
    location {
      x: 372.2301940917969
      y: -2.4413347244262695
      z: 38.10381317138672
    }
    orientation {
      x: -0.9999985694885254
      y: 0.0009700049995444715
      z: -0.0013448960380628705
    }
    rotation {
      pitch: -0.07705818861722946
      yaw: 179.9444122314453
      roll: -0.00827026180922985
    }
  } 
  acceleration {
    x: 0.7957648038864136
    y: -0.012980509549379349
    z: -0.03765770047903061
  }
  forward_speed: 5.649636745452881
  autopilot_control {
    steer: 0.0007941109943203628
    throttle: 0.5
  }

All these values when extracted are in global coordinates. Is there any way to convert them to local coordinates in Carla?
How can  I easily convert these measurements in the local frame of the client?

This seems to be a bottleneck for some SLAM algorithms using LIDAR.
A sincere request to help resolve this.
Please help @nsubiron @sunpochin @harlowja @harlowja @juaxix @oldtopos

**Comment by Unlingius** [comment]
what does it mean "local coordinates"? Frame of your first position?
