### ISSUE TITLE
[0.9.6] Windows Build Failed

### ISSUE THREAD

**Issue by palhimanshu1991** [carla-simulator/carla#2198]
Hi, 

I've tried to build carla on windows multiple times but it continues to throw error
- Build via command line 
- Build manually after generating visual studio files
- I've also given the correct permissions to the specified folder and still get the same eror

Below is the stack trace from visual studio. Would be great to get any help on this.

`1>------ Build started: Project: CarlaUE4, Configuration: Development_Editor x64 ------
1>Creating makefile for CarlaUE4Editor (makefile version does not match)
1>Parsing headers for CarlaUE4Editor
1>  Running UnrealHeaderTool "D:\code\carla\Unreal\CarlaUE4\CarlaUE4.uproject" "D:\code\carla\Unreal\CarlaUE4\Intermediate\Build\Win64\CarlaUE4Editor\Development\CarlaUE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
1>Reflection code generated for CarlaUE4Editor in 41.4892997 seconds
1>Using Visual Studio 2017 14.16.27023 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.17763.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 16 actions with 8 processes...
1>  [1/16] SharedPCH.Engine.cpp
1>  [2/16] Module.Carla.gen.4_of_4.cpp
1>  [3/16] PCH.CarlaUE4.cpp
1>  [4/16] CarlaUE4.cpp
1>  [5/16] CarlaUE4.init.gen.cpp
1>  [6/16] CarlaMapGenerator.gen.cpp
1>  [7/16] CarlaMapGenerator.cpp
1>  [8/16] UE4Editor-CarlaUE4.lib
1>     Creating library D:\code\carla\Unreal\CarlaUE4\Intermediate\Build\Win64\UE4Editor\Development\CarlaUE4\UE4Editor-CarlaUE4.lib and object D:\code\carla\Unreal\CarlaUE4\Intermediate\Build\Win64\UE4Editor\Development\CarlaUE4\UE4Editor-CarlaUE4.exp
1>  [9/16] Module.Carla.gen.1_of_4.cpp
1>  [10/16] Module.Carla.gen.3_of_4.cpp
1>  [11/16] Module.Carla.gen.2_of_4.cpp
1>  [12/16] Module.Carla.cpp
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp(29): warning C4458: declaration of 'TerrainNodeMaterial' hides class member
1>  d:\code\carla\unreal\carlaue4\plugins\carla\source\carla\commandlet\PrepareAssetsForCookingCommandlet.h(148): note: see declaration of 'UPrepareAssetsForCookingCommandlet::TerrainNodeMaterial'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp(342): warning C4458: declaration of 'Role' hides class member
1>  E:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(448): note: see declaration of 'AActor::Role'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp(351): warning C4458: declaration of 'Role' hides class member
1>  E:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(448): note: see declaration of 'AActor::Role'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderQuery.cpp(45): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\time.h(506): note: see declaration of 'localtime'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/CollisionSensor.cpp(49): warning C4458: declaration of 'Episode' hides class member
1>  D:\code\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Sensor/Sensor.h(75): note: see declaration of 'ASensor::Episode'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.cpp(138): warning C4458: declaration of 'Episode' hides class member
1>  D:\code\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Sensor/Sensor.h(75): note: see declaration of 'ASensor::Episode'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.cpp(57): warning C4996: 'FTextureRHIParamRef': FTextureRHIParamRef typedef is deprecated; please use FRHITexture* directly instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>  e:\program files\epic games\ue_4.23\engine\source\runtime\rhi\public\RHIResources.h(1166): note: see declaration of 'FTextureRHIParamRef'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.cpp(20): error C2039: 'PostPhysicsComponentTick': is not a member of 'UStaticMeshComponent'
1>  E:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Engine\Classes\GameFramework/DefaultPawn.h(18): note: see declaration of 'UStaticMeshComponent'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp(28): warning C4458: declaration of 'Character' hides class member
1>  E:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Engine\Classes\GameFramework/Controller.h(76): note: see declaration of 'AController::Character'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp(83): warning C4458: declaration of 'Character' hides class member
1>  E:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Engine\Classes\GameFramework/Controller.h(76): note: see declaration of 'AController::Character'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp(112): warning C4458: declaration of 'Character' hides class member
1>  E:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Engine\Classes\GameFramework/Controller.h(76): note: see declaration of 'AController::Character'
1>D:/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp(126): warning C4458: declaration of 'Character' hides class member
1>  E:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Engine\Classes\GameFramework/Controller.h(76): note: see declaration of 'AController::Character'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command ""E:\Program Files\Epic Games\UE_4.23\Engine\Build\BatchFiles\Build.bat" CarlaUE4Editor Win64 Development -Project="D:\code\carla\Unreal\CarlaUE4\CarlaUE4.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "CarlaUE4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped =========`

**Comment by palhimanshu1991** [comment]
I was trying different things and then it magically worked.
For others facing this issues, i manually build the packages in the below order and it worked for me
- make LibCarla
- make PythonAPI
- make check
- make launch
Then Unreal asked to build the modules, post which it successfully built the modules.

**Comment by micmarty** [comment]
Please, put compiled 0.9.6 version for Windows into "releases" 👨‍🚒
