### ISSUE TITLE
[0.9.6.] Windows to build trafficmanager fails

### ISSUE THREAD

**Issue by michaelBfox** [carla-simulator/carla#2202]
Hi there,

I'm new to Carla. I just built Carla from source. Everything is fine except the trafficmanager executable cannot be found in the place the docs say it should be.

'make trafficmanager' gives "nothing todo for this target"

What might be wrong?

Cheers,
Michael

**Comment by stolenbiker** [comment]
Obviously there is no target in the makefile for the TrafficManager and also no Batch File in /Utils to build it. I don't know the reason for that either
