### ISSUE TITLE
How can i get a manual controlling vehicle id already spawned?

### ISSUE THREAD

**Issue by tanakataiki2** [carla-simulator/carla#2205]
I want to get an id of ego vehicle and other vehicles from not manual control script but other script.
I saw manual control.py that spawn and get it's id but not getting id directory using script.
So how can I detect vehicle which is controlled from script?

Thanks

**Comment by rajatsaini0294** [comment]
Hi,
You can use get_actors().filter('vehicle.*') to get list of all the vehicles present in the carla sim. For each actor in the list get it's id by **each_actor.type_id**.
