### ISSUE TITLE
Setup Error #255 on Windows

### ISSUE THREAD

**Issue by JJW152** [carla-simulator/carla#2206]
This is a copy of: https://github.com/carla-simulator/carla/issues/1668

which was marked closed but not resolved.

I previously built Carla 9.6 on this machine with no problems. I had removed it.

This time, when I tried to install the same way, I accidentally used x86 which led to errors.

Now when I try to install, I get this error every time:

 D:\Carla 09_06\carla>make launch
-[Setup]: [Batch params]: --boost-toolset msvc-14.1
-[Setup]: Asynchronous jobs:  8
-[Setup]: Boost toolset:      msvc-14.1
-[Setup]: Install directory:  "D:\Carla 09_06\carla\Build\"
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "D:\Carla 09_06\carla\Build\"
09_06\carla\Build\""=="" was unexpected at this time.
make: *** [setup] Error 255

I even re installed VS 2017 with no luck. I am losing my mind considering I installed no problem a month ago, and now I am getting nowhere.  I'm using x64 command prompt, and just following the instructions for source build on Windows.

**Comment by KetAveryH** [comment]
I had a similar issue when I tried to run: make PythonAPI. What fixed my issue was moving my carla directory to my root directory C:\\

It seems like the empty spaces in my directory path "C:\Program Files\carla" caused the error.
