### ISSUE TITLE
Synchronous and autopilot mode together

### ISSUE THREAD

**Issue by BertaBescos** [carla-simulator/carla#2223]
Is it possible to run CARLA 0.9.6 on synchronous mode and with autopilot mode? If so, how to make each actor advance to its next pose?

**Comment by cassfalg** [comment]
I have car actors driving around on autopilot in sync mode, and pedestrians walking about. They chose some random destination by their own. There's examples of how to do this in the documentation and the example python clients like `spawn_npc.py`. I am not sure what you mean by "advance to it's next pose" besides that?
