### ISSUE TITLE
Is there already a data collector implementation for Carla 0.9.6 ?

### ISSUE THREAD

**Issue by aakashsehgal** [carla-simulator/carla#2227]
I want to try end to end deep learning using Carla. For that I require the images as well as the corressponding steering angle for each image. I would drive manually and record this data.Is there already one such implementation or a guidance of how to do it in Carla 0.9.6 ?

I would want to save it in csv file as shown:

![image](https://user-images.githubusercontent.com/36532026/68855616-e7d19580-06de-11ea-9b07-90b2c8463ba9.png)

**Comment by cassfalg** [comment]
Take a look at tutorial.py, should be a start, though you may want to modify manual_control.py to write your csv file and images. It'll require some python coding.

**Comment by AlanNaoto** [comment]
I'm working in one for RGB, bounding box and depth data for my master thesis. Later I plan on sharing it with the community :)

**Comment by aakashsehgal** [comment]
I already built one customized version using pandas library. I added this functionality in the manual_control.py

**Comment by e270889o** [comment]
> I already built one customized version using pandas library. I added this functionality in the manual_control.py

Would you share your implementation?

**Comment by VEDANTGHODKE** [comment]
@aakashsehgal Could you please share your implementation?
