### ISSUE TITLE
How to get DebugHelper.draw_string() working

### ISSUE THREAD

**Issue by awandzel** [carla-simulator/carla#2233]
Hey everyone,

I want to publish an ID over each agent while running Carla. However, it's not clear how to get the DebugHelper.draw_string() to work. The documentation mentions: 

> Strings can only be seen on the server-side.

Additionally, the example mentions:  

> Notice that you can't see the strings if you are using an editor camera

Can someone help me understand this?
What are the steps to get this function properly working? 

Thank you,
Arthur

**Comment by cassfalg** [comment]
To me it sounds like they are only visible from the spectator view camera used by the standalone server, not a camera sensor or the Unreal Editor. What you get by executing `CarlaEU4.sh` from a binary download or `make package`.
