### ISSUE TITLE
set_velocity() dependent on x,y,z co-ordinates?

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2234]
I am trying to move my ego vehicle using set_velocity() command. however, based on the location of the vehicle, assigning say for instance, set_velocity(carla.Vector3d(x=10)) has different effect. Sometimes the vehicle goes straight, some times backwards, some times sideways.

**Comment by nsubiron** [comment]
Velocity is in world coordinates, you're always applying velocity on X world axis.
