### ISSUE TITLE
Unable to use set_velocity() method for a sensor actor (camera)

### ISSUE THREAD

**Issue by eeedWard** [carla-simulator/carla#2249]
Carla version: Latest release

Hi, I am trying to use the set_velocity() and set_angular_velocity() methods for an actor of type sensor (rgb camera). However, nothing happens.

The set_location() method works.

Any help? Thanks!

**Comment by NotAnyMike** [comment]
Any update from the carla team?

**Comment by nsubiron** [comment]
Probably sensor objects do not have physics simulation enabled. You may try `cam.set_simulate_physics(True)` but I would expect them to fall through the ground or something as they don't have collision.

**Comment by eeedWard** [comment]
Thanks, I solved it by sending a series of different poses in order to simulate the desired velocity
