### ISSUE TITLE
fisheye camera support

### ISSUE THREAD

**Issue by hubing1994** [carla-simulator/carla#2263]
I am using carla for simulation in parkinglot.I find that the fisheye camera model is not supported in carla V0.9.6.I am wounding that if the fisheye camera model will be supported in the future ?

**Comment by cassfalg** [comment]
You can check https://github.com/carla-simulator/carla/issues/2185#issuecomment-559387280 for some code to create fisheye images from multiple cube map images. But yes, fisheye support out of the box would be nice. Just be aware that the Unreal Engine itself uses the pinhole camera model (like all 3D engines), which is limited to a field of view of less than 180° in theory and around 110° in practice (more looks increasingly strange). For true fisheye support with high fields of view you need to do some tricks and/or workarounds which have issues of their own, the least of which being performance.
