### ISSUE TITLE
Get traffic light state before reaching to it

### ISSUE THREAD

**Issue by kargarisaac** [carla-simulator/carla#2268]
Hi,

Thank you for this great simulator. I want to get a traffic light state before reaching an intersection for example. Now, I get the state exactly when I reach the intersection. How can I get that? I changed `_proximity_threshold` in the `roaming_agent.py` but didn't see any difference. I use `is_at_traffic_light()` function.

I use carla 9.6 on ubuntu 18.04

Thank you

**Comment by jackbart94** [comment]
Hello!

Thank you for using CARLA! So, if you're working with agents, I suggest you to check [the behavior agent](https://github.com/carla-simulator/carla/pull/2091) which is still under works but provides a few other functionalities.

Having said so, `_proximity_threshold` for the Roaming agent influences the distance between our main vehicle with other vehicle and European-style traffic lights, as you can see in `_is_vehicle_hazard` and `_is_light_red_europe_style`. So probably it works best only in Town1 and Town2.

Meanwhile, if you use `is_at_traffic_light()` this will return Red/Yellow/Green only once you hit a specific trigger box, which is directly correlated to a certain traffic light. This trigger box has been placed by us to make sure each vehicle stops before the junction. It's a method that belongs in the CARLA API, meanwhile the others are relative to the Roaming agent, so there's a bit of a difference there. To get the state of the traffic light before reaching the intersection, you must obtain the value of a trigger box in front of you (by using the waypoint queue of your agent maybe) and store it somewhere.

Let me know if this helps you!
