### ISSUE TITLE
Run carla faster for RL training

### ISSUE THREAD

**Issue by kargarisaac** [carla-simulator/carla#2269]
Hi,

I want to train an RL agent in Carla. Is there any way to run the simulation faster? 

I use:
carla9.6 
ubuntu 18.04
rtx 2080ti

Thank you

**Comment by SajjadBaloch** [comment]
can you send your email i will tell solution their

**Comment by kargarisaac** [comment]
@SajjadBaloch 
My email: kargarisaac@gmail.com
Thank you

**Comment by ndeshp2s** [comment]
Hello @kargarisaac @SajjadBaloch. 

Even I am looking for a solution to train my RL agent faster in Carla. Could you please also share the solution with me? @SajjadBaloch my mail id: niranjan.deshpande187@gmail.com

Thank you in advance.

**Comment by kargarisaac** [comment]
> can you send your email i will tell solution their

Hey. Did you get my email?

**Comment by LuserBen** [comment]
Hello, @kargarisaac 
Could you please also share the solution with me? My e-mail id: Lbpeng@mail.dlut.edu.cn

Thanks very much!

**Comment by hsezhiyan** [comment]
Hello @SajjadBaloch ,

Can you share the solution with me too: hsezhiyan@ucdavis.edu

Thank you!

**Comment by weizhaoji** [comment]
Hello @SajjadBaloch ,

Can you share the solution with me too: 419365004@qq.com

Thank you!

**Comment by Usaywook** [comment]
Hello @SajjadBaloch

**Comment by ZhangYouRong** [comment]
Hello @SajjadBaloch ,
I have encountered the same problem, could you please share the solution with me ?
My email: zyr8@foxmail.com

**Comment by laofuren** [comment]
Hello @SajjadBaloch ,

Can you share the solution with me too: 992100567@qq.com

Thank you!

**Comment by Mulberry26** [comment]
> can you send your email i will tell solution their
@SajjadBaloch @ndeshp2s @kargarisaac @LuserBen @weizhaoji 
Could you guys  maybe share with me the RL accelerated time program? Thanks a lot!
my email is [armpro24@gmail.com
](url)
