### ISSUE TITLE
Package new sensors

### ISSUE THREAD

**Issue by h042910276** [carla-simulator/carla#2271]
Hello Carla team. 
First of all, I want to say thank you for offer this very useful simulator.

Now, I am trying to adding a new sensor by following the tutorial in the below link:
How to add a new sensor
https://carla.readthedocs.io/en/latest/how_to_build_on_linux/

After doing `make rebuild`, I run Unreal editor with `make launch`.
The sensor is working well through Python API.

```
class SafeDistanceSensor(object):
    def __init__(self, parent_actor):
        self.sensor = None
        self._parent = parent_actor
        world = self._parent.get_world()
        bp = world.get_blueprint_library().find('sensor.other.safe_distance')
        self.sensor = world.spawn_actor(bp, carla.Transform(), attach_to=self._parent)
        self.sensor.listen(lambda event: SafeDistanceSensor.callback(world, event))
    @staticmethod
    def callback(world, event):
        for actor_id in event:
            vehicle = world.get_actor(actor_id)
            print('Vehicle too close: %s' % vehicle.type_id)
```

Then I want to run CARLA without Unreal editor.
So I packaged CARLA with `make package` 
Then I run the exactly same python code to call the new sensor.
But I get the error below:

`IndexError: blueprint 'sensor.other.safe_distance' not found`

It seems that the changes of new sensor is not packaged.
I use carla 9.6 on ubuntu 18.04
How can I package the new sensor correctly?

Thanks for your help!

**Comment by hashim19** [comment]
Hi, I am stuck on something very similar to you. Do you remember, how you were able ti figure it out? 

Best regards,
