### ISSUE TITLE
how can I add my github username when I sign up at  www.unrealengine.com

### ISSUE THREAD

**Issue by weizhaoji** [carla-simulator/carla#2277]

**Comment by annaornatskaya** [comment]
PERSONAL -> CONNECTED ACCOUNTS -> GITHUB

**Comment by weizhaoji** [comment]
@annaornatskaya I have solved this problem already，anyway，thank you so much for your kind!

**Comment by tetsu-kikuchi** [comment]
As of 14 Nov. 2022, visit 

[here](https://www.epicgames.com/help/en-US/epic-accounts-c5719348850459/connect-accounts-c5719351300507/how-do-i-link-my-unreal-engine-account-with-my-github-account-a5720369784347)

or 

[here](https://www.epicgames.com/account/connections#accounts)
