### ISSUE TITLE
C++ Client API , problem with ActorList class .

### ISSUE THREAD

**Issue by stavBodik** [carla-simulator/carla#2291]
Am I doing something wrong ?

```
carla::client::ActorList* actorsList = world.GetActors().get();
int numberOfActors = actorsList->size();
```

Cannot use the pointer actorsList , 
I am getting compile error : expression must have a class type .

**Comment by nsubiron** [comment]
`actorList` is a pointer
```cpp
actorsList->size();
~~~~~~~~~~~^
```

**Comment by stavBodik** [comment]
@nsubiron yes you right I fixed the post but this is not the problem...its just wqs my mistake writing here.

**Comment by stavBodik** [comment]
Please close this issue this was due to missing include to the .h file #include <carla/client/ActorList.h> Thanks @nsubiron for the amazing project !
