### ISSUE TITLE
Carla build using clang 9

### ISSUE THREAD

**Issue by Prakyathkantharaju** [carla-simulator/carla#2302]
I know that to build carla I need clang 7. when I do

* * *
**sudo apt-get install libclang-7-dev**

I get the following error:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libclang-7-dev : Depends: libstdc++-5-dev but it is not installable
                  Depends: libgcc-5-dev but it is not installable
                  Depends: libobjc-5-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
* * *

**I am using Ubuntu 19.10. and have clang 9 installed. Is there any way to compile Carla in clang 9 and not in clang 7?**

**Comment by qhaas** [comment]
I recently modified CARLA 0.9.7's build scripts to leverage clang8 and UE 4.23.  You will encounter two problems:
1. The CARLA build scripts are hard-coded to `/usr/bin/clang-7` and `/usr/bin/clang++-7`
1. llvm version dependent portions of the stack are cloned/built to llvm7 (e.g. `-b release_70`)
1. CARLA's build scripts treat warnings like errors, so as new warnings are enabled by default in newer major releases of clang, you will have to surpress them or disable the `-Werror` flag.
