### ISSUE TITLE
Use cv2 to create an additional window normally

### ISSUE THREAD

**Issue by gagaxiaolong** [carla-simulator/carla#2304]
Hi, I need to create an additional window to show camera's view. so I reuse manual_control.py and wrote code in the function `_parse_image` :
```
# original code
image.convert(self.sensors[self.index][1])
array = np.frombuffer(image.raw_data, dtype=np.dtype("uint8"))
array = np.reshape(array, (image.height, image.width, 4))
array = array[:, :, :3]
array = array[:, :, ::-1]
self.surface = pygame.surfarray.make_surface(array.swapaxes(0, 1))

# my code
img = np.array(image.raw_data).astype('uint8')
img = img.reshape((image.height, image.width, 4))
img = img[:, :, :3]
cv2.imshow("", img)
cv2.waitKey(1)
```
But my code can not work normally. In most cases it can't create a window, in a few cases it create a small window.  I checked the image‘s raw_data, it's normal.

Is there any way I can do to resolve this problem？Thank you！

My environment：
+ ubuntu18
+ carla0.9.6

**Comment by bryanibit** [comment]
I met the same problem that `cv2.imshow` has nothing. I replaced cv2 with `matplotlib`. Check the [link](https://matplotlib.org/tutorials/introductory/images.html):
```python
raw = np.array(image.raw_data).astype('uint8')
bgra = np.reshape(raw, (HEIGHT, WIDTH, 4)
brg = bgra[:, :, 3]
plt.imshow(bgr[:, :, ::-1]/255.0)
plt.imshow(1)
```
