### ISSUE TITLE
blueprint 'sensor.other.rss' not found

### ISSUE THREAD

**Issue by kingwingshome** [carla-simulator/carla#2311]
File "manual_control_rss.py", line 733, 
bp = world.get_blueprint_library().find('sensor.other.rss')
IndexError: blueprint 'sensor.other.rss' not found

    Platform(s): Ubuntu,
    Python version(s): 3.5
    Unreal Engine version: 4.22

**Comment by jackbart94** [comment]
Hi,

Have you done
```sh
make LibCarla.client.rss
```

and then
```sh
make PythonAPI.rss
```

?

**Comment by kbu9299** [comment]
I got the same problem. 

@jackbart94 
I downloaded the binary (CARALA_0.9.7).  At which folder should I run `make`?

**Comment by jackbart94** [comment]
@kbu9299 all ```make``` have to be executed from the folder where you cloned/download the CARLA project.

**Comment by sheepwxy** [comment]
> I got the same problem.
> 
> @jackbart94
> I downloaded the binary (CARALA_0.9.7). At which folder should I run `make`?

hello,have you solved this problem?

**Comment by kbu9299** [comment]
@sheepwxy 
Yes, I could manage to run `make` from where I cloned Carla as follows:
```
make LibCarla
make PythonAPI
```

**Comment by sheepwxy** [comment]
@kbu9299  Thanks for your reply!  It means.. I should use the source version but no complied version?

**Comment by kbu9299** [comment]
@sheepwxy Yes, you need to clone Carla source (not compiled version). For the full compilation, you may also need to download Unreal Engine. In my case, I only tested the compilation for LibCarla and PythonAPI.

**Comment by sheepwxy** [comment]
@jackbart94   thanks! I will have a try.

**Comment by sheepwxy** [comment]
@kbu9299  It does help， thanks !

**Comment by Martin20** [comment]
I got the same error. I did all your suggestions but still received the following error:

File "manual_control_rss.py", line 731, in __init__
    bp = world.get_blueprint_library().find('sensor.other.rss')
IndexError: blueprint 'sensor.other.rss' not found
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 92 (sensor.other.collision) 
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 94 (sensor.other.gnss)

**Comment by Starfunk** [comment]
I am also receiving this error.

**Comment by Bapt-GR** [comment]
Hi,
I also still have this problem, even though both `make [...].rss` were said to have been successful

**Comment by gitmaster3000** [comment]
Same problem here. Can someone please look into this
