### ISSUE TITLE
How can I use python API for carla0.9.6

### ISSUE THREAD

**Issue by HuPeng-Valer** [carla-simulator/carla#2313]
I download the compressed files from https://github.com/carla-simulator/carla/releases directly,and used command ‘easy_install PythonAPI/carla/dist/carla-0.9.6.......egg’.But Carla 0.9.6 does not exist on pypi，I don't want to build the whole project so how can i use the pythonapi for carla0.9.6

**Comment by ozcnsimge** [comment]
Hi, may I ask how you solved this? I am facing the same issue.
