### ISSUE TITLE
0.9.7 Traffic Manager in python API

### ISSUE THREAD

**Issue by sapirbm** [carla-simulator/carla#2315]
hello, 
where can i find documentation on how to use the new traffic manager in 0.9.7 in the python api?
in addition, is there a way to control the final destination of the vehicle? or at least help the car choose the right turn in junctions? some navigation control? or this is still unsupported?
if unsupported, is there any intention to do it? any time estimation about this feature/milestone?

**Comment by jackbart94** [comment]
Hello,

Documentation is a bit lacking, but soon it will be updated. Right now the vehicle has no exact destination, it computes a route and chooses randomly at intersections. You can change this random choosing and put a higher weight on the right turn.

However, navigation controls are implemented in the agents. Have you tried checking them?
