### ISSUE TITLE
Possible bug in OpenDriveParser

### ISSUE THREAD

**Issue by alexmargulis** [carla-simulator/carla#2327]
Which output is expected from the MapBuilder::GetLaneNext function for the following arguments:
`road_id = 11364, section_id = 0, lane_id = -2`
Is it [(12415, -1), (12416, -2)] or [(12105, -2), (11562, -3)]?

In the current implementation it returns [(12415, -3), (12416, -2)] which is obviously a bug since road 12415 has no lane -3
![image](https://user-images.githubusercontent.com/32236828/71820712-a33bf800-3098-11ea-9133-0dba815361f8.png)

I use carla 0.9.7 on Win10 and trying to import this XODR file: 
[lafayet.zip](https://github.com/carla-simulator/carla/files/4026188/lafayet.zip)

**Comment by ThrashAbaddon** [comment]
@alexmargulis I assume there hasn't been any progress on this?
