### ISSUE TITLE
Incorrect doppler velocities

### ISSUE THREAD

**Issue by stackSmasher294** [carla-simulator/carla#2328]
Hi everyone,

The current radar implementation seems to calculate the range rate along a given azimuth angle as simply the velocity the actor instead of velocity *along* the line of sight with radar. Does anyone know if fixing this is in the development pipeline of Carla?

![figure_1-1](https://user-images.githubusercontent.com/26362865/71599764-385b6000-2b72-11ea-95b2-1347842a6b80.png)
X-axis: azimuth in degrees, Y-axis: range rate. One plot each for the front and the rear radar respectively. I was expecting a sinusoid relation b/w range rate and the azimuth angle.

I'd be happy to fix this if it's not planned.

**Comment by jackbart94** [comment]
Hello,

I think @marcgpuig can be more helpful than me with this issue, however you can always try to fix it and open a pull request, which we will later review and eventually update the code with.

**Comment by germanros1987** [comment]
@marcgpuig please, let's work on fixing this issue.

**Comment by doterop** [comment]
I am looking into this. I hope I can update you on Monday.

**Comment by doterop** [comment]
@stackSmasher294 Can you send me the script that you use to test? Or at least the part that you use to visualize the radar output?

**Comment by stackSmasher294** [comment]
Um, the actual script just reads off a ROS topic. It was used in conjunction with the Carla ros-bridge.

**Comment by stackSmasher294** [comment]
I think I may have figured out where the problem is. Just confirming - to test it, I'll have to build CARLA from source, right?

**Comment by doterop** [comment]
Yep, because the logic of the radar is in the server side.

**Comment by stackSmasher294** [comment]
Rebuild Carla with the fix and the problem is solved! The doppler plots now look like this:

![Figure_1-2](https://user-images.githubusercontent.com/26362865/72759992-74c42e00-3bfd-11ea-9f13-c53d3a51a88d.png)

I'll open a pull request with the fix.

**Comment by doterop** [comment]
Thanks @stackSmasher294 ! I just pushed it to master.
