### ISSUE TITLE
Low-quality mode is extremely bright

### ISSUE THREAD

**Issue by BenAscent** [carla-simulator/carla#2336]
When running in low quality mode, there is an exposure problem which makes the game very bright. See screenshot below.

**Epic quality**
![image](https://user-images.githubusercontent.com/46737980/71883852-9a235780-317a-11ea-8dde-74ce1f82fa85.png)

**Low quality**
![image](https://user-images.githubusercontent.com/46737980/71883931-b7f0bc80-317a-11ea-8c6b-2177757d7b08.png)

This happens in 0.9.7 and was not happening in 0.9.6.

It seems to be due to the scalability level for post-process that is set to 0 in low quality:
```
sg.PostProcessQuality=0
```
More specifically, it's this specific value that causes the problem:
```
r.EyeAdaptationQuality=0
```
(as defined in `[PostProcessQuality@0]` of BaseScalability.ini).

Switching `r.EyeAdaptationQuality` to 1 or 2 solves the problem.

We also found out that using the apparently new `BP_WeatherSafe` as weather class instead of `BP_Weather` prevents the problem to occur.

This problem occurs on both Windows and Linux (Ubuntu 18.04). GPUs tested include nVidia 1070 and 2070.

**Comment by bernatx** [comment]
Hi, we are working to fix this. The problem seems to affect only the server image and not the client, and it is because we use some manual autoexposure values that at low-quality are disabled and then the exposure is broken. We will keep the autoexposure enabled at low-quality also.
