### ISSUE TITLE
Remove Automotive Materials dependencies

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#235]
We are currently using Epic's _Automotive Materials_ package for the vehicles materials, but we have our own version ready to use. Removing the dependencies will make easier the compilation of CARLA.

The possibility of linking the _Automotive Materials_ will be still optional, but by default CARLA will use our own materials.

**Comment by uhvardhan** [comment]
Hi,

I was following the instructions on http://carla.readthedocs.io/en/latest/how_to_build_on_linux/ to build CARLA. I have built CARLA and now I need to download and install Automotive Materials and rest of the procedure. But the process is too confusing. Could you help me with that?
