### ISSUE TITLE
npc_agent in Scenario_4 will be blocked

### ISSUE THREAD

**Issue by GilgameshD** [carla-simulator/carla#2350]
**Describe the bug**
In npc_agent.py, the function that checks collision with other vehicles (_is_vehicle_hazard) only checks the x and y coordinates. While in scenario_4, the 'other_agent' is spawned with x and y that will block the ego agent (z=-500 does not help). Then the ego agent will always output an empty control command.

**Expected behavior**
The spawned other_agent does not block ego vehicle.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04]
 - CARLA Version [e.g. CARLA 0.9.6]
 - Python version [e.g. 2.7]
 - Version [e.g. 0.9.6]

**Additional context**

**Comment by fabianoboril** [comment]
Hi,
this is a problem of the CARLA BasicAgent. Therefore, moved the issue to CARLA directly.
