### ISSUE TITLE
0.9.7 with nvidia vulkan can't pan and is white

### ISSUE THREAD

**Issue by mofochristo** [carla-simulator/carla#2354]
Hi!

When I launch the CarlaUE4.sh for version 0.9.7 on ubuntu 18.04 with Vulkan, the spectator shows with extreme white gamut and it can't be moved around properly.

0.9.6 works great for me.

How can this be?
attached hwinfo
[hwinfo.txt](https://github.com/carla-simulator/carla/files/4053672/hwinfo.txt)

**Comment by jeffreykxiao** [comment]
This sounds like it's related to the known bugs #2336 and #2337 . This issue and those changes should all be resolved by #2352
