### ISSUE TITLE
Semantic segmentation under bridge

### ISSUE THREAD

**Issue by wzhang1** [carla-simulator/carla#2356]
To reproduce, in a town with bridges, driver under a bridge, e.g. in town04,
we can see that the ceiling below the bridge is marked to class 6 with is a lane marker,
although the other side is a road(class 7), we may not prefer to define them as class 6.
![00129727](https://user-images.githubusercontent.com/3386739/72301449-a47e9f00-361b-11ea-9e8c-3c5c3433896b.png)
![w00129727](https://user-images.githubusercontent.com/3386739/72301452-a6486280-361b-11ea-94eb-25e5dbd33ae8.png)

**Comment by magehrig** [comment]
Can confirm this issue under version 0.9.8

**Comment by magehrig** [comment]
@marcgpuig Can this be reopened? It's not fixed afaik.

**Comment by marcgpuig** [comment]
Sorry for the late response, I'll try to communicate it to the art team ASAP. They plan to iterate fixing several of these issues son.

**Comment by DnDare** [comment]
Greetings,  we've made changes to SS of the bridge
![image](https://user-images.githubusercontent.com/57799121/86771976-6e165f80-c053-11ea-8192-bce0b6f57a38.png)

It is merged into master , it will be released in future updates

**Comment by DnDare** [comment]
The bridge SS, has been changed to WALL
![image](https://user-images.githubusercontent.com/57799121/86804985-bcd5f080-c077-11ea-89c2-1c8c1192388e.png)

**Comment by magehrig** [comment]
Has this been done for all the bridges in all the towns or just this particular one?

**Comment by magehrig** [comment]
For example this is in Town05
![image](https://user-images.githubusercontent.com/6841681/87321031-ff8e4180-c52b-11ea-968a-19004beb6d54.png)

So it does not appear to be fixed. Can we reopen the issue since it is not solved?

**Comment by DnDare** [comment]
I'll have a look at this tomorrow, I'll post some updates

**Comment by DnDare** [comment]
![image](https://user-images.githubusercontent.com/57799121/87477242-187c1d00-c628-11ea-8566-dd08c093ca02.png)
The bridge has been changed,  to be reviewed and approved  yet ,( will be updated in  future releases)

**Comment by magehrig** [comment]
Great, thanks for addressing this issue. Are these changes already available on the current master branch?

**Comment by DnDare** [comment]
Yes, they're in art's master branch,  if you have access to private towns, there  are some redirectors that affects T09

**Comment by magehrig** [comment]
@DnDare Which branch is "art's master" branch? I am interested in using Carla with the corrected segmentation maps. Can I do that? If yes, how?

**Comment by DnDare** [comment]
We have 2 public master branches,  one is for code the other is for art assets, you just will have to update as usual.
If you have any problem, just ask

**Comment by magehrig** [comment]
Just to inform you, I did what you recommended but in Town 05 there were still road lines under the bridge

**Comment by DnDare** [comment]
Sorry to hear that, and for the inconveniences.
I'm not sure what to recommend you, these changes have been made, and a few others. By the end of July we made a pre-release, it is meant to have this changes, but there are some issues, and this is why it wasn't announced. (I think it's public)
Now the team is mostly on vacations, I guess the future release will have the changes, and I'm guessing it will be in September.
If you can wait I'd suggest to wait, else you can try your luck, sry about not being able to help more.

**Comment by DnDare** [comment]
@magehrig  Greetings, I guess you already noticed, we've launched Carla 0.9.10. 
There're improvements to SS, hope they suit your needs:
http://carla.org/2020/09/25/release-0.9.10/
