### ISSUE TITLE
CDO Constructor Errors after Updating to 0.9.7

### ISSUE THREAD

**Issue by lechrizzle-87** [carla-simulator/carla#2359]
Hi, guys, 

after updating to 0.9.7 I get the following error messages when starting the project. What could be the reason for this?  The files that cannot be found are all in the Content/Static folder. I tried make clean, rebuild etc. but nothing worked.
The Unreal version is 4.22.3.

Thanks a lot!
Chris

![Capture](https://user-images.githubusercontent.com/3080067/72428673-7bcae680-378e-11ea-9d5a-00a153424a1a.PNG)

**Comment by lechrizzle-87** [comment]
My bad! Always check the correct paths! The "carla" subfolder was missing in the "content" folder.

**Comment by CQUlifuling** [comment]
> hello, how did you finally solve this problem?
