### ISSUE TITLE
Record LiDAR data

### ISSUE THREAD

**Issue by nachovizzo** [carla-simulator/carla#2360]
Hello there, simple question.

Is there any example that I can build on top of to record 3D-LiDAR like data on the simulator. I'd like to collect a static-scene dataset to work with 3D Laser scans.

I tried to look in the documentation but there are no examples, and the ones provided in the distribution are too big to just hack and go.

I've searched for `point_cloud_example.py` but it looks that it has been removed from the latest distributions.

Thanks a lot!

**Comment by justinjk007** [comment]
https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control.py

In this example, once you've toggled lidar and then you start recording, it will save lidar data into a file.
