### ISSUE TITLE
Set my own Camera Matrix and Distortion

### ISSUE THREAD

**Issue by soulslicer** [carla-simulator/carla#2365]
Is it possible in CARLA? I only see the option for setting the FOV, but not the exact camera matrix itself. Or the distortion

**Comment by MisterioRemo** [comment]
@soulslicer well, it's possible.
You can create your own camera sensor based on ShaderBasedSensor class and use Unreal plugin OpenCVLensDistortion or LensDistortion. Also you'll need to create postprocess material for this plugin and set it in your new camera class in constructor.
OpenCVLensDistortion  is good, but works only on Windows.
LensDistortion is... strange but works on Linux and Windows!

Hope it helps =)
