### ISSUE TITLE
Autopilot mode working too slow in synchronous_mode example

### ISSUE THREAD

**Issue by aakashsehgal** [carla-simulator/carla#2372]
I am using Carla 0.9.6 in windows.

It provides an example of synchronous_mode.py. If i activate the autopilot mode and disable the waypoint updation as well as the vehicle physics is enabled, the whole simulation becomes extremely slow. 

Firstly it takes extremely long to spawn and once spawned, it takes too much time to drive around. The fps remains same in both the modes i.e. whether vehicle physics is enabled or disabled...the fps remains the same.

```
vehicle.set_simulate_physics(True)
vehicle.set_autopilot(True)
```

Am i missing something ?

**Comment by jht1759** [comment]
The same Issue is found when the synchronous mode is set. Is there any solution for it

**Comment by MaXiaoSIOM** [comment]
The same issue with Version 0.9.11. I spawned 30 auto-piloted vehicles and 0 walkers with example script 'spawn_npc.py'  . In synchronous_mode,  almost 50ms taken for one simulation frame, while it is 6ms in no_synchronous_mode.
