### ISSUE TITLE
CARLA0.9.7 pedestrians with ignoring the vehicles

### ISSUE THREAD

**Issue by ocean1211** [carla-simulator/carla#2373]
Hello everyone!
I have noticed that in CARLA 0.9.7, the pedestrians can notice vehicles nearby and act accordingly when crosswalking.
Is there any method to make pedestrians ignore the vehicle and only avoid each other when moving? I want to use it to test the brake system of the vehicle.

Thanks a lot for your help!

**Comment by ndeshp2s** [comment]
Hello @ocean1211,

Did you find any solution to this? Even I have been looking to have this functionality.
