### ISSUE TITLE
customization existing carla maps

### ISSUE THREAD

**Issue by rjtshrm94** [carla-simulator/carla#2382]
I want to customize existing maps. I need to remove every thing from the map except roads and grounds fro spawning vehicles and use autopilot. I went through https://carla.readthedocs.io/en/0.8.4/map_customization/ this but couldn't get this. It would be good if there are pictures or videos of one sample.  Also, If some could help me to achieve the above task of removing static objects and houses from the existing map. I will appreciate that.

**Comment by hesty98** [comment]
Hey,
I'm currently in the same situation. Did you manage to achieve your task?
best regards
