### ISSUE TITLE
Pedestrian crossing in CARLA 0.9.7

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2384]
Hello all,

I have been exploring this new functionality of CARLA 0.9.7, however, I am still not sure how the "world.set_pedestrians_cross_factor()" works. In some towns, increasing this number results in more pedestrians crossing the crosswalks and also there are some pedestrians doing jaw-walking. 

However, in some towns I see pedestrians crossing only over crosswalks and no jaw-walking. 

Is it because of the nav file (used by recast and detour) and how regions are defined as navigable in these files?

Then does this mean, the "world.set_pedestrians_cross_factor()" will influence pedestrian crossing randomly (as mentioned in documentation). It could be over crosswalks/roads depending on the nav file for that particular town?

Also, making this factor 0.0 still causes pedestrians to cross. I am wondering why.

**Comment by rowanmcallister** [comment]
I see the same error: `world.set_pedestrians_cross_factor(0.0)` has pedestrians
