### ISSUE TITLE
Planner Issues

### ISSUE THREAD

**Issue by bhairavmehta95** [carla-simulator/carla#239]
When running:

```python
self._planner.get_next_command(measurements.location, 
     measurements.self.end_point.location, self.end_point.orientation)
```

I get an error that says: (with the function that it pulls from)

```
 File "/path/to/carla/planner/converter.py", line 161, in _check_input_type
    if len(input_data) > 2:
TypeError: object of type 'Vector3D' has no len()
```

Has anyone seen this problem before? I double checked that each of the four arguments I am passing in are all of type: `<class 'carla_server_pb2.Vector3D'>`, which seems to the types of both the `location`s and `orientation`s?

**Comment by felipecode** [comment]
We will check it out. Thanks !
