### ISSUE TITLE
(Bug) lane type at Town 04 carla 0.9.6

### ISSUE THREAD

**Issue by Naghamwael** [carla-simulator/carla#2391]
I am using carla version 0.9.6 and at Town 04, it is supposed that it only have 4 lanes and 2 sidewalks. But, by using the lane type, it gives me that the state of these two lanes is driving not sidewalk.
When I am at the 4th lane and check the availability of the neighbouring lanes (lane change), it gives me both although one of them is supposed to be a sidewalk. So, how can I handle this?
Also, when I generate random cars, there are cars generated in the lanes that are supposed to be sidewalks.

**Comment by jackbart94** [comment]
Hi,

Could you explain further what scripts are you using and provide some images or videos of this happening?
