### ISSUE TITLE
semantic segmentation in Carla 0.8.2 gives weird results

### ISSUE THREAD

**Issue by pirate-lofy** [carla-simulator/carla#2399]
I'm trying to get segmentation map for the front camera of the car like this 
`
camera=Camera('myCam',PostProcessing='SemanticSegmentation')
    camera.set_image_size(800, 600)
    camera.set_position(x=0.30, y=0, z=1.30)
    camera.set_rotation(pitch=0, yaw=0, roll=0)
`
and visualize it using opencv like this 
`cv2.imshow('',labels_to_cityscapes_palette(data['myCam']))`
but I'm getting a weird result 
![Screenshot from 2020-01-25 09-39-48](https://user-images.githubusercontent.com/27896633/73118089-c6e7b500-3f57-11ea-960f-19a75b9b0229.png)

**Comment by germanros1987** [comment]
Please, use a newer version of CARLA. 0.9.8 or 0.9.8.1. We have worked hard to solve bugs and bring new features.
