### ISSUE TITLE
How to do geoposition to transform

### ISSUE THREAD

**Issue by fyj97** [carla-simulator/carla#2401]
Hello CARLA team.
I see that there is an API can do transform to geoposition.
But how can I do geoposition to transform.
Thank you very much

**Comment by jackbart94** [comment]
Hi,

If I understand correctly your question, [the transform method is the answer](https://carla.readthedocs.io/en/latest/python_api/#carlatransform-class). Let me know if it helps!

**Comment by fyj97** [comment]
Thanks a lot.
I am afraid I do not talk clearly. I see there is a function calls transform_to_geolocation Carla.map class, can converts a given carla.Location (x, y, z) to a carla.GeoLocation (lat, lon, alt). But I want to get the carla.Location (x, y, z) from  carla.GeoLocation (lat, lon, alt).

**Comment by nuomizai** [comment]
> Hello CARLA team.
> I see that there is an API can do transform to geoposition.
> But how can I do geoposition to transform.
> Thank you very much

Hi, @fyj97 . Have you found ways to convert geoposotion to transform? I'm also troubled by this problem.
