### ISSUE TITLE
Change render quality levels from python client

### ISSUE THREAD

**Issue by amstrudy** [carla-simulator/carla#2402]
I'm trying to increase performance and was looking to change the render quality from epic to low, but I can't figure out how to do this from the Python API. Some old issues/docs mention the CarlaSettings class, but it's not in the API anymore and errors when running. Is there no way to change the render quality except when running CARLA from the command line? I built from source so I'm running with `make launch-only`.

**Comment by stevelaclasse** [comment]
check the folder "Dist" in the carla foler, the should be the compiled version which take those argument, if not you could use "make package" that will create a carla package in the folder "Dist"
