### ISSUE TITLE
fps setting issue

### ISSUE THREAD

**Issue by deepakreddy63** [carla-simulator/carla#2415]
When I set the fps using config.py script, it has no effect on the server fps.

I see the HUD display on manual_control.py shows server fps > 60 fps.

Is there any way to set the fps to a constant value?

I'm using Carla 0.9.6 and ubuntu 16.04. Tested the same for Carla 0.9.7 as well.

**Comment by semmelknoedel** [comment]
Did you find a solution? I'm having the same problem. Even when config.p y-i shows a framerate of 20ms it is often much higher on the server side. The client is working, though.
