### ISSUE TITLE
Simple Maps

### ISSUE THREAD

**Issue by Canorvantis** [carla-simulator/carla#2418]
Hi,

I would like to know if there are any pre-built simple maps. I am looking for a very basic map with just one lane and without crossings etc.,just curves and straights.  (e.g. a race track). I am developing some stuff concerning road/lane detection and lateral vehicle control, and I want to start with a simpler environment. I have seen some videos of people having such maps in CARLA, but unfortunately I was not able to find those maps online. 

Thank you

**Comment by curtkim** [comment]
+1
