### ISSUE TITLE
Way to find the measurements of NPCs in the scene

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#242]
I stored the measurements provided by the server to the python client as part of the sensor data. But I found that each measurement provides the measurements related to all the NPCs in the map.

**Is there a way to just get the measurements of the NPCs in the current view of the sensor?**

I want to try using CARLA to simulate a kind of cruise control and would need the speed and position of the car in front of me in the scene. (If possible all the components in the scene).

**Comment by nsubiron** [comment]
Hi @YashBansod, please check issue #63.
