### ISSUE TITLE
New Vehicle not affected by physics 

### ISSUE THREAD

**Issue by Georgini82** [carla-simulator/carla#2420]
I followed the instructions to add a new vehicle to carla from https://carla.readthedocs.io/en/latest/how_to_add_assets/ . 
But for some reason when I spawn the car trough the PythonAPI it just stays in the air instead of falling to the road like the other cars.

Did I missed something? It looks like the vehicle is spawn as a static object that is not affected by the physics asset.

![floating car](https://user-images.githubusercontent.com/56071801/73535350-40c9e380-441b-11ea-9489-d8fcd1966192.jpg)

**Comment by Georgini82** [comment]
Hello, I realised I made a mistake. 
So for future references: the body of the car cannot have simulation=kinematic. 
It was that parameter that keep the car locked in the place where it spawn.

Regards

**Comment by iasonastsaousis** [comment]
Where is that parameter found?
