### ISSUE TITLE
Project lidar sensor points to corresponding rgb image from camera sensor

### ISSUE THREAD

**Issue by rjtshrm94** [carla-simulator/carla#2421]
Hello,
I am trying to project Lidar data onto camera Image. For this First I am trying to transform Lidar point to world co-ordinate and then these coordinates to camera respective. For this I need extrinsic matrix for Lidar and camera, and also Intrinsic matrix for camera. For this I am using location  and rotation of Lidar sensor (attached on top of car) in real world. For building the rotation matrix I am assuming the order x (roll) --> y(pitch) ---> z(yaw). the final matrix looks like this
>     rz = np.array([
>             [np.cos(yaw), -np.sin(yaw), 0],
>             [np.sin(yaw), np.cos(yaw), 0],
>             [0, 0, 1]
>             ], dtype=np.dtype("float"))
>     ry = np.array([
>             [np.cos(pitch), 0, np.sin(pitch)],
>             [0, 1, 0],
>             [-np.sin(pitch), 0, np.cos(pitch)]
>             ], dtype=np.dtype("float"))
>     rx = np.array([
>             [1, 0, 0],
>             [0, np.cos(roll), -np.sin(roll)],
>             [0, np.sin(roll), np.cos(roll)]
>             ], dtype=np.dtype("float"))
>     rzryrx = np.matmul(rz, np.matmul(ry, rx))
>     lidar_2_world = [[rzryrx c], [0, 1]] (for lidar) * [lidar point cloud coords]
>     world_2_cam = [[rzryrx c], [0, 1]] (for camera) * [lidar_2_world]
>     cam_2_pixels = intrinsic * world_2_cam

For calculating Intrinsic matrix, I am doing like this (which is mentioned in one of carla issues on Github)
>     Focus_length = data.width / (2.0 * np.tan(data.fov * np.pi / 360))
>     Center_X = data.width / 2.0
>     Center_Y = data.height / 2.0
>     #print("Initrisnsic", Focus_length, Center_X, Center_Y)
>     intrinsic = np.array([
>         [Focus_length, 0, Center_X, 0],
>         [0, Focus_length, Center_Y, 0],
>         [0, 0, 1, 0],
>         #[0, 0, 0, 1]
>         ], dtype=np.dtype('float'))

 Is this the correct way of doing. Because I am not getting the the correspondence b/w lidar and rgb image

**Comment by Rajat-Mehta** [comment]
@rjtshrm94 were you able to project lidar point cloud to rgb images? It would be a great help if you can share some details on how to do that?
