### ISSUE TITLE
Carla installation - No space left on device error

### ISSUE THREAD

**Issue by jayati2512** [carla-simulator/carla#2430]
I'm installing Carla on Ubuntu 18.04.3 LTS. On running make launch, I get No space left on device error. I found that the inodes are full which causes this error. Is there anything that can be done to resolve this error, apart from reformatting the system? Thanks! 

Following is the screenshot of the error and the df  command:

<img width="696" alt="7B928B2D-0801-46CB-81FE-53FE021B6934" src="https://user-images.githubusercontent.com/5338187/73604963-1fedc380-45be-11ea-8278-a07181bd84de.png">

**Comment by itserror404** [comment]
hi, were you able to fix this issue?
