### ISSUE TITLE
How to load a custom made town from code?

### ISSUE THREAD

**Issue by ndeshp2s** [carla-simulator/carla#2441]
Is there a way to load a custom made town from config.py file for example? Or by running "CarlaUE4.sh" ?

I have created a custom environment and it works fine from unreal engine (after pressing the play button). However, I want to somehow register this town so that I can load it from code directly.

Is there a way to do this?

I am using Carla 0.9.7 version

**Comment by a-jahani** [comment]
You need to register the map in the cook packages secotion in 'project settings' inside unreal engine. 
Then you can package it.
You might also need a  .xodr file for it .you can use an empty one(you will see the error saying this file is missing)

**Comment by a-jahani** [comment]
After packaging (make package) client.get_available_maps() method should list the custom map.
