### ISSUE TITLE
How can I get the vehicle mesh?

### ISSUE THREAD

**Issue by xmyqsh** [carla-simulator/carla#2450]
I can get vehicle type from `vehicle.type_id`.
I need an additional dict: {type_id: mesh}
How can I get it?
It seems that the `mesh`, vertices and faces, should be converted from 
```
./Unreal/CarlaUE4/Content/Carla/Blueprints/Vehicles/Tesla
./Unreal/CarlaUE4/Content/Carla/Static/Vehicles/4Wheeled/Tesla
```

**Comment by xmyqsh** [comment]
One solution is to reconstruct the 3d structure by Multi-View Geometry.

But I want to know if there is a more straightforward method or not.

**Comment by fengyi233** [comment]
Hi! Any solutions?
