### ISSUE TITLE
CarlaSettings.ini is missing

### ISSUE THREAD

**Issue by matoboor** [carla-simulator/carla#2451]
Hi. 
I downloaded compiled version (0.9.5) for Windows and I cant find file CarlaSettings.ini .
According to docs, it should be located in directory CarlaUE4/Config/CarlaSettings.ini.
Can somebody explain me why it is missing and where should it be?

Thank you.

**Comment by stevelaclasse** [comment]
the docs refers to olders version of carla, versions like 0.8

**Comment by 10LGUO** [comment]
same issue here. Tried to change the default vehicle but can not locate CarlaSettings.ini.

**Comment by hanmmmmm** [comment]
What is the alternative way for setting the world parameter in 0.9.1x?
