### ISSUE TITLE
Improve vehicle spawner

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#246]
The current vehicle spawner has several issues ([VehicleSpawnerBase.cpp](https://github.com/carla-simulator/carla/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/AI/VehicleSpawnerBase.cpp))

  * If a collision occurs the vehicle is not spawned (no re-try).
  * If there are not enough spawn points, no vehicle is spawned.

**Comment by juaxix** [comment]
Will try to spawn the car in another spawn point at the end of the round.

**Comment by juaxix** [comment]
Part 2 of the fix is in commit 565bd98 ( If a collision occurs the vehicle is not spawned (no re-try). )
