### ISSUE TITLE
Orientation of bounding box w.r.t. ego vehicle

### ISSUE THREAD

**Issue by rjtshrm** [carla-simulator/carla#2461]
How can I get orientation bounding boxes with respect to ego vehicle. I know I can get orientation angles (roll, pitch, yaw) w.r.t. bounding vehicle in world coordinates system. But how to get it w.r.t. to ego vehicle or any sensor.

**Comment by zijianh4** [comment]
> How can I get orientation bounding boxes with respect to ego vehicle. I know I can get orientation angles (roll, pitch, yaw) w.r.t. bounding vehicle in world coordinates system. But how to get it w.r.t. to ego vehicle or any sensor.

Hi, I also want to collect the relative rotation to ego vehicle or a camera sensor. Did you solve the problem?
