### ISSUE TITLE
Map Information in CARLA 

### ISSUE THREAD

**Issue by KulkarniAnirudh26** [carla-simulator/carla#2462]
Is there a method to access the map information such as static vehicles present in the map, lane information for all the lanes present in front of the ego vehicle, through PythonAPI's ? 
Or is there there any other API for this ?

**Comment by jackbart94** [comment]
Hi,

We are currently developing an API for this, it's supposed to come out in the following releases. We'll keep you updated, in the meantime you can try to obtain this information yourself by using the current tools!

**Comment by KulkarniAnirudh26** [comment]
Thank you for your reply. 
Could you specify the tools that are currently available for obtaining the map information ? 

One way is to use Unreal editor to get info on static meshes present.  
Another way is to use the semantic segmentation images to identify various objects present in the images. 

Is there any other way ?
