### ISSUE TITLE
[0.9.7] Strange version string

### ISSUE THREAD

**Issue by pawel-ziecina** [carla-simulator/carla#2465]
I'm observing strange version string returned from `get_*_version()` methods on carla 0.9.7.3 release:

```
print(client.get_server_version())
print(client.get_client_version())
```

```
1f7669e
1f7669e
```
Checked that on 0.9.6 release it worked correctly.

**Comment by hishamyousry** [comment]
@pawel-ziecina did you happen to find the cause of this issue? I am facing the same issue on carla 0.9.9.4.
