### ISSUE TITLE
Rebuild Error

### ISSUE THREAD

**Issue by Rajshah05** [carla-simulator/carla#2471]
When running UE4_ROOT=~/UnrealEngine_4.18 ./Rebuild.sh

I am getting this error

bash: ./Rebuild.sh: No such file or directory

CARLA version number: 0.8.2 (stable version)
Platform/OS: Ubuntu 18.04

-->

**Comment by priyankanagaraj1494** [comment]
Hello I am also facing same problem. Did you find the solution.

**Comment by Rajshah05** [comment]
I shifted to the latest version from the stable version

**Comment by germanros1987** [comment]
That is very reasonable... I am closing this. Long life to 0.9.9.
