### ISSUE TITLE
rpc/msgpack.hpp file is missing

### ISSUE THREAD

**Issue by kapil9033** [carla-simulator/carla#2474]
https://github.com/carla-simulator/carla/blob/386011dd964f0d283723a845ec2eae229b72ce55/LibCarla/source/carla/MsgPack.h#L11

**Comment by severin-lemaignan** [comment]
Same issue here, when trying to compile `LibCarla` on its own.

**Comment by germanros1987** [comment]
@bernatx could you take a look at this? It seems to be an active problem.

**Comment by bernatx** [comment]
Hi,
That file is part of the RPC library. We have a forked RPC library, and that file is still there:
```
https://github.com/carla-simulator/rpclib.git
TAG: v2.2.1_c2
```

You should have the file for example in **carla\Build\rpclib-install\include\rpc\msgpack.hpp**

Regards
