### ISSUE TITLE
Adding Assets

### ISSUE THREAD

**Issue by JamesKCS** [carla-simulator/carla#2479]
I'm trying to add assets to the simulator.  The directions here https://carla.readthedocs.io/en/stable/how_to_add_assets/ are difficult for me to understand.  Are there more detailed directions anywhere?

The first step says:

> Import fbx as Skelletal Mesh to its own folder inside Content/Carla/Static/Vehicles. A Physics asset and a Skeleton should be automatically created and linked the three together.

How do I "Import fbx as Skelletal Mesh"?  Do I have to rebuild CARLA?  Or is there a Python command for importing a Mesh?  I have no idea what this means, and any guidance or more detailed instructions would be appreciated.  Thank you!

**Comment by elvircrn** [comment]
Did you eventually manage to add a new asset to CARLA?
