### ISSUE TITLE
control algorithm for walker

### ISSUE THREAD

**Issue by dongfang-steven-yang** [carla-simulator/carla#2480]
Hi, 

I work on pedestrian motion modeling, and I'd like to improve pedestrian motion in Carla. I just wonder how the `WalkerControl` is achieved in CARLA. I've checked the API for manually controlling a walker and figured out we need to send the commands of direction, speed, and jump for the walker. But I'm not sure how the pedestrian's state is mathematically updated. 

I've searched the documentation but it's very unlucky and I couldn't find any detailed information. If anyone can provide any related information it would be appreciated.

Thanks,
DF

**Comment by stevelaclasse** [comment]
the file spawn_actor.py in python example folder could help you to see how walker are controlled
