### ISSUE TITLE
Documentation: Link to blueprint library invalid

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/carla#2485]
The readthedocs chapter [blueprints](https://carla.readthedocs.io/en/latest/python_api_tutorial/#blueprints) contains a link to the [blueprint library](https://carla.readthedocs.io/bp_library) which is not working. Maybe a "/" is missing.

**Comment by robogast** [comment]
Just for reference, the correct link should be https://carla.readthedocs.io/en/latest/bp_library/ 
The link in the `python_api_tutorial` is missing the `/en/latest/`
