### ISSUE TITLE
Let walkers hold props / Reading walker's bone transform

### ISSUE THREAD

**Issue by guotata1996** [carla-simulator/carla#2488]
Hi, 

I'm trying to let walkers hold certain props (cell phones, bags, etc.) but haven't found a solution yet. Carla seems to have a built-in support for that (there's a PedestrianProps folder). Could anyone tell me how to do that? Thanks!

A workaround would be reading the bones' poses and calculate the prop's pose manually. There's an API for setting those poses: [https://carla.readthedocs.io/en/latest/walker_bone_control/](url), but I couldn't find a "get" method.

**Comment by germanros1987** [comment]
@marcgpuig any feedback on this?
