### ISSUE TITLE
PropFactory not working in Carla 0.9.7

### ISSUE THREAD

**Issue by Georgini82** [carla-simulator/carla#2497]
Hello.

I'm trying to add a new prop to Carla.
But when I update the PropFactory with a new static mesh it doesn't show the blueprint in the world available list of BP.

Can anyone confirm if this is an issue or if I'm missing something please?

OS: Xubuntu 18.04
UE4: 4.22
Carla: 0.9.7

**Comment by a-jahani** [comment]
Yeah, the Prop factory blueprint won't work. You need to add a JSON file for the prop.

**Comment by Georgini82** [comment]
Thanks for the reply a-jahani.

Going to try it.

Regards

**Comment by omrizen** [comment]
on carla 0.9.8 the tag does not work properly for me when I get an image from semantic segmentation image
(the color of the object is black)
what are the options for tagging that I can put? 
Thanks
