### ISSUE TITLE
when and how does carla server starts?

### ISSUE THREAD

**Issue by minrui-hust** [carla-simulator/carla#2502]
we create actors via clients, which in turn resort to carla
server.
my question is when does the server start and how ?which folder are the code relevant to the server lies in?

**Comment by stevelaclasse** [comment]
i don't think i understand your question, but to launch the server you have to execute the file CarlaU4.sh , either sh CarlaU4.sh or ./CarlaU4.sh
this command launch the "carla shipping" files located in binaries/linux

**Comment by minrui-hust** [comment]
Think you anyway, I have figure it out by reading the source code. This issue will be closed.
