### ISSUE TITLE
Carla transformation matrix from roll,pitch,yaw

### ISSUE THREAD

**Issue by Harsharma2308** [carla-simulator/carla#2516]
The actor.get_transform().rotation has roll,pitch and yaw values.
To get a rotation matrix, I need to understand the order in which these transforms were applied.

Is it roll,pitch,yaw or something else?
If i am correct, I can get transformation via-

```
trans=actor.get_transform().trans
rot=actor.get_transform().rotation
t=trans.x,trans.y,trans.z
r,p,y=rot.roll,rot.pitch,rot.yaw

trans_mat=np.eye(4)
trans_mat[:3,-1]=t
##Similary roll,pitch,yaw matrices
transformation_matrix= trans_mat@roll_mat@pitch_mat@yaw_mat #3x4 matrix
```

Could someone confirm?

**Comment by thomasfermi** [comment]
I had the same problem and studied Carla's source code and then did some testing.

Studying the [source code](https://github.com/carla-simulator/carla/blob/fe3cb6863a604f5c0cf8b692fe2b6300b45b5999/LibCarla/source/carla/geom/Transform.h) I found the formula Carla is using for the rotation matrix. Then I played around with sympy multipyling the yaw, pitch, and roll matrices in different order. What I found is that Carla performs roll, then negative pitch, then negative yaw. I verified this empirically.

Values for Carla
**
![image](https://user-images.githubusercontent.com/30798048/122109039-34caa000-ce1d-11eb-8670-a96148b7c151.png)
**

Values with sympy (please watch the minus signs!)

![image](https://user-images.githubusercontent.com/30798048/122109606-d7831e80-ce1d-11eb-9bde-9db51264bd2b.png)

**Comment by YonatanSimson** [comment]
One way to get the rotation matrix is to use carla functions that already exist. 

`np.array(carla.Transform(rotation=carla.Rotation(yaw=heading, pitch=pitch, roll=roll)).get_matrix())[:3, :3]`

I wish there was API for doing this in straight forward manner but such a method doesn't exist at the moment. Take care that this is left-handed matrix.
