### ISSUE TITLE
Unable to connect to client object.

### ISSUE THREAD

**Issue by shishau** [carla-simulator/carla#2524]
I am beginner to linux.

https: "Connect and get the world" command described in //carla.readthedocs.io/en/latest/python_api_tutorial/ does not work.

client = carla.Client('localhost', 2000)

In the localhost part
ip a
Substitute 127.0.0.1 from the above command.

In the 2000 part,
lsof -i
Substitute the number from the above command (eg 43334).

Execution result,
syntax error near unexpected token `('
(Because we are Japanese environment　予期しないトークン `(' 周辺に構文エラーがあります　It shows)

Is it a hierarchy problem that causes the command to be executed?
/carla
/carla/PythonAPI/axamples
Both had the same result.

please tell me solution.

environment
Ubuntu18.04
UnrealEngine4.22
CARLA0.9.7

shishau

**Comment by amstrudy** [comment]
If the error you are getting is `syntax error near unexpected token`, then it's not a CARLA issue but probably just your Python syntax. What is the exact code you are running?

**Comment by shishau** [comment]
Thank you for your reply!

client = carla.Client（ '127.0.0.1'、2000)

A syntax error is returned as a result of putting the above in the CUI.
What is the code in this case?

Sorry for not knowing much.

shishau

**Comment by amstrudy** [comment]
You're almost there! The problem is the character after `'127.0.0.1'`, which Python is expecting to be a comma but looks more like a Japanese comma in your code? Anyways, the line should be:
```python
client = carla.Client('127.0.0.1', 2000)
```
