### ISSUE TITLE
Zoom in and out problem

### ISSUE THREAD

**Issue by anna-srl** [carla-simulator/carla#2525]
Hi everyone and thanks for your amazing work!

I'm a CARLA newbie and I recently installed CARLA 9.5 in windows. 

I was able to spawn npcs, run manual control and follow several initial steps by the available python modules.

However, in the town window I have not been able to zoom in or out, either by the mouse wheel or the keyboard buttons. I am aware that there is an issue with my server (not the required GPU) and I will resolve this issue soon. However, since the ASDW buttons work,  I was wondering if the issue is something different..Any ideas?

**Comment by amstrudy** [comment]
The "zooming in and out" is done through the WASDQE keys, where W is forwards, A is left, S is backwards, D is right, Q is down, and E is up in relation to your player frame of reference. You can only use the mouse to move around when using the editor. (Are you running via `make launch` or `CarlaUE4.exe`? If it's the latter then you don't use the mouse to navigate.)

**Comment by anna-srl** [comment]
Yes, that was it! I am using `CarlaUE4.exe` , that's why the mouse was not working. Thank you very much for your help!

**Comment by amstrudy** [comment]
Yes, no problem! If you don't have any more questions, please close the issue :)
