### ISSUE TITLE
SteamVR error when make launch

### ISSUE THREAD

**Issue by kooger0415** [carla-simulator/carla#2527]
I am running carla 0.9.7 , ubuntu 18.04 , UE 4.22 , using VMware.

I build carla with this URL's step.
https://carla.readthedocs.io/en/latest/how_to_build_on_linux/

But when I run make launch , I got error message bellow. 
**Plugin 'steamVR' failed to load because module 'steamVR' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.**

This question is same for my situation .
https://github.com/carla-simulator/carla/issues/1213
And, I also check ".uproject" . I see both of them's setting is false. 
So, I don't know how to disabling the plugin.

Does anyone help me?

**Comment by stevelaclasse** [comment]
were you trying to launch the UE4 editor from the Binaries sub folder of the Unreal Folder ?? if yes, you should not run it that way, in the Carla folder, run "make launch-only"  or "make launch" to build before starting the Unreal editor, make sure you have imported the Unreal Editor path.
