### ISSUE TITLE
Carla Build Errors from profilesparser.cpp and LocalizationStage.cpp 

### ISSUE THREAD

**Issue by eneserciyes** [carla-simulator/carla#2531]
Hi,

I'm having too many errors when I tried to 'make launch'.

![erorrr](https://user-images.githubusercontent.com/20225199/75567970-7f2ae080-5a63-11ea-99e6-d070f5437089.PNG)

The explanations are in Turkish. But we hope you can understand the error from error codes. 

We were able to correct some errors by modifying the files like converting uint to uint64_t as suggested in another issue. But there are so many distinct errors. We thought that maybe, something else causes the problem instead of an error in the code. 

Hope you can help us out!!

**Comment by filipthoen** [comment]
I had the same issue with the 'master' branch I pulled today -- changing the type from uint to uint64_t solved the issue.

Did you give this a try?

Filip
