### ISSUE TITLE
can't connect to the Boost server

### ISSUE THREAD

**Issue by dhruvildarji** [carla-simulator/carla#2533]
https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip

This link does not work with any device. 

Any help?

**Comment by mcfly50** [comment]
Same problem. Carla, master branch. Update.sh completes successfully.

'make launch' results in the following:

Setup.sh: Retrieving boost.
--2020-03-01 21:51:22--  https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 35.166.139.238, 52.39.25.243
Connecting to dl.bintray.com (dl.bintray.com)|35.166.139.238|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-03-01 21:51:23 ERROR 403: Forbidden.

Util/BuildTools/Linux.mk:126: recipe for target 'setup' failed
make: *** [setup] Error 8

**Comment by kzykogo0415** [comment]
I also face same problem. Is this error has occur recently?

**Comment by kzykogo0415** [comment]
I discover this site. Down load this and save the folder  carla\Build
https://sourceforge.net/projects/boost/files/boost/1.72.0/

**Comment by mcfly50** [comment]
This issue with boost server indicating 'forbidden' seems to be fixed. Was able to connect to boost server yesterday.

**Comment by TheGermanKid** [comment]
Has anybody found a solution/workaround to this problem or is this something on bintrays side? I just had the exact same issues and can't get around it!

**Comment by Saytas** [comment]
![Screenshot from 2020-03-27 20-03-31](https://user-images.githubusercontent.com/25760805/77813463-1769b480-7066-11ea-87fd-0e39d46f3f8e.png)
I am also having the same issue. Did you guys solve the issue?

**Comment by savinovava** [comment]
Have the same. 
![Снимок экрана от 2020-03-28 10-54-42](https://user-images.githubusercontent.com/53625116/77818335-a4525380-70e2-11ea-8385-a5c6522723d6.png)

**Comment by savinovava** [comment]
> I discover this site. Down load this and save the folder carla\Build
> https://sourceforge.net/projects/boost/files/boost/1.72.0/

It doesn't help, not in tar.gz, not in unzip format

**Comment by revikiran1991** [comment]
https://github.com/carla-simulator/carla/issues/2664#issuecomment-605438816 

temporary fix.

**Comment by fliedroc** [comment]
> I discover this site. Down load this and save the folder carla\Build https://sourceforge.net/projects/boost/files/boost/1.72.0/

it work well for me, thanks
