### ISSUE TITLE
Problem using the binary release of carla

### ISSUE THREAD

**Issue by jaoh** [carla-simulator/carla#2536]
Hi

I use  a binary release of carla (0.9.7)  I  want to use the following code https://github.com/flying-cabbage/drift_drl I always get errors like 

drift_drl/code$ python carla_tools.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "carla_tools.py", line 83, in <module>
    from agents.navigation.roaming_agent import RoamingAgent
ImportError: No module named agents.navigation.roaming_agent

this indicates that my pythonpath is not configured. 

echo $PYTHONPATH 
:/home/jaoh/Dokumente/Carla/CARLA_0.9.7.4/PythonAPI/carla/dist/carla-0.9.7-py2.7-linux-x86_64.egg:/home/jaoh/Dokumente/Carla/CARLA_0.9.7.4/PythonAPI/carla/agents/navigation

Is there some documentation iam missing ?

thanks

**Comment by amstrudy** [comment]
I could be wrong but I think you want your `PYTHONPATH` to be this (don't include `agents/navigation`):
`export PYTHONPATH=$PYTHONPATH:/home/jaoh/Dokumente/Carla/CARLA_0.9.7.4/PythonAPI/carla/dist/carla-0.9.7-py2.7-linux-x86_64.egg:/home/jaoh/Dokumente/Carla/CARLA_0.9.7.4/PythonAPI/carla`
