### ISSUE TITLE
Vehicle skeleton

### ISSUE THREAD

**Issue by rodrigogutierrezm** [carla-simulator/carla#2547]
Hello.

Is there anyway to modify an existing vehicle or create a new one with different characteristics, such as the distance between wheels? 

Thank you.

Using CARLA 0.9.6 and Ubuntu 18.04

**Comment by amstrudy** [comment]
There is a wiki page for this exact question [here](https://carla.readthedocs.io/en/latest/tuto_A_import_assets/).
