### ISSUE TITLE
How can I get a specific traffic light with python api?

### ISSUE THREAD

**Issue by Zhuxy** [carla-simulator/carla#2559]
I want to control traffic lights manually. There is ActorList.filter("traffic.traffic_light") to get all of them. But how can I get a specific one in the map? 

Maybe mark or add some tag to traffic lights in Unreal Engine scene editor and then filter them by tags in python client API? 

Is that possible?

many thanks

**Comment by hepeng187** [comment]
I encountered the same problem.  Have you solved the problem of setting only one traffic light?

**Comment by germanros1987** [comment]
@Axel1092 could you provide some guidance for this?

**Comment by Axel1092** [comment]
Hi @Zhuxy,
We plan to expose traffic lights through the landmark class which allows you to detect sign and traffic light in the OpenDRIVE file. This is currently working with custom OpenDRIVE files loaded through the standalone mode but it is not yet avaialiable in Carla's maps. You can still sort the traffic lights by position in the world `traffic_light.get_location()`.
