### ISSUE TITLE
Is there a way to change the game settings while running an episode

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#256]
So I was working on adding more functionalities to the client example code and I am stuck at a problem.
Is there any way to change the sensor setting while running the episode. Correct me if I am wrong, but in the example codes, changing of the sensor settings require initiation of a new episode.

I basically want to be able to rotate or translate the camera view as you are able to do in the main game.

My current layout has 3 cameras

![view](https://user-images.githubusercontent.com/16332426/36858784-3e83f6ac-1da2-11e8-9bb4-5195d36e8d46.png)

and I want to move the main RGB camera freely while the episode is going on. Is that possible?

**Comment by nsubiron** [comment]
Hi @YashBansod,

This is not currently possible. Since most of the setups for autonomous vehicles have fixed cameras attached to the car we haven't had the need to implement this.
