### ISSUE TITLE
How to build map using Ubuntu 18.04?

### ISSUE THREAD

**Issue by EgorFollia** [carla-simulator/carla#2562]
Hi! 
I was wondering whether it's possible to create a map (or change the existing one) using UE4?
Should I use RoadRunner? I can't find any documentation on how to do it.

Maybe there are some maps I can import? Provide me, please, with the source
P.S. Thanks a lot in advance

**Comment by stevelaclasse** [comment]
you could easily edit the existing one, for that you must build Carla from the source, and launch UE4editor to edit Map and then create a package with your new edited Maps.

**Comment by EgorFollia** [comment]
@stevelaclasse I should run this in carla or in UE4 directory?

**Comment by stevelaclasse** [comment]
in carla with the `make launch` or `make launch-only` command.

**Comment by EgorFollia** [comment]
@stevelaclasse yes, that was a dummy one question, sorry )
I have install PythonAPI today and now after I `make launch` Carla - it just freezes my PC
What seems to be the problem?
