### ISSUE TITLE
kaggle or colab support

### ISSUE THREAD

**Issue by khojir** [carla-simulator/carla#2567]
Hi.
Is there a way to run Carla on Kaggle or Google Colab? I think there is a lot of students that can't run Carla on their laptop. It would be nice if you support these options.
Thanks.

**Comment by MichaelBosello** [comment]
I needed to run Carla on Colab too, and I have found a method to do so.
If you're still interested, I did a Colab notebook with the tutorial.
You can find it at https://github.com/MichaelBosello/carla-colab

**Comment by khojir** [comment]
> I needed to run Carla on Colab too, and I have found a method to do so.
> If you're still interested, I did a Colab notebook with the tutorial.
> You can find it at https://github.com/MichaelBosello/carla-colab

I tried this solution and it works really good. Thank you so much.

**Comment by Sukhman723** [comment]
Hi khojir, it is showing unable to run nagrok

**Comment by harish-2306** [comment]
> Hi khojir, it is showing unable to run nagrok 

pip install the library

**Comment by wendersonj** [comment]
Thansk for sharing.
I'm getting a error while it's fetching a library from nvidia (fetch: libnvidia-decode-450). Then I started a issue on their github:
https://github.com/demotomohiro/remocolab/issues/59
