### ISSUE TITLE
Python API build fails (CARLA 0.9.7) in Windows: 

### ISSUE THREAD

**Issue by danielaDESM** [carla-simulator/carla#2568]
Hi!
I have been trying to build CARLA the last days. I have gone through the FAQS several times and I have encountered several issues in the way and tried some solutions that others have posted. Currently, I think the only problem left is: make Python API. 

I am using: 
- Windows 10
- Python 3.7.3
- x64 Native Tools for VS 2017
- Unreal Engine 4.22.3
- GNU make 3.81
- Cmake 3.14.0-rc4

After I run the command, it starts compiling until it starts apparently complaining about boost:

![image](https://user-images.githubusercontent.com/12168864/76227861-396ad680-6220-11ea-9d05-75caf9f70ad7.png)

Then, for many .cpp files it shows me "class template optional is only available with C++17 or later."
![image](https://user-images.githubusercontent.com/12168864/76228038-7cc54500-6220-11ea-86e3-0e377fa1e645.png)

And finally, it throws a lot of linking issues:

![image](https://user-images.githubusercontent.com/12168864/76228143-a0888b00-6220-11ea-81e9-f0659d1bcb90.png)

![image](https://user-images.githubusercontent.com/12168864/76228213-b5fdb500-6220-11ea-8267-130e4a6114d0.png)

As a note side, I was not able to do make launch either. I was having the same message of "class template optional is only available with C++17 or later. ". But following other posts I have erased some "uint" and exchange them by "uint_64" in TrafficManagerRemote.cpp. I have erased several time times the whole project and this trial has been the farthest I can get. 

I hope you can help me,

**Comment by barasm-hita** [comment]
Hi @danielaDESM 
This problem you are facing causes from Unreal Engine registry key issue (as you got error "Unreal Engine 4.22 not detected" in the last screenshot). So, it can be solved by adding the registry key named **InstalledDirectoy** (and type of _String Value_) in **Computer\HKEY_LOCAL_MACHINE\SOFTWARE\EpicGames\Unreal Engine\4.22** like how you see in my screenshot mentioned.
If any more details were required, tell me to explain.
Good luck.

![image](https://user-images.githubusercontent.com/33845625/76297185-a6d44100-62cc-11ea-91aa-844eed49e3eb.png)

**Comment by danielaDESM** [comment]
Hi!
Thanks for your help. Just one more question. I do not have the folder "EpicGames/Unreal Engine/4.22" under HKEY_LOCAL_MACHINE/SOFTWARE. Instead, I have found it here:
![image](https://user-images.githubusercontent.com/12168864/76314306-d425ec80-62d6-11ea-9be1-b9a70021227c.png)
Can I add the value there?

**Comment by danielaDESM** [comment]
So I did change the value in "InstalledDirectory" under HKEY_LOCAL_MACHINE/SOFTWARE/WOW6432-node/EpicGames/Unreal Engine/4.0. The error that you mentioned, does not appear anymore. Nonetheless, previous errors are still there. 
I just ran make "make PythonAPI" and I have the  "class template optional is only available with C++17 or later" and the linking errors:
![image](https://user-images.githubusercontent.com/12168864/76317513-96c45d80-62dc-11ea-8fdd-6a4bf13f3155.png)

![image](https://user-images.githubusercontent.com/12168864/76317400-709ebd80-62dc-11ea-8bf3-0440f93eadd8.png)

**Comment by barasm-hita** [comment]
Hello again @danielaDESM 
The subject "class template optional is only available with C++17 or later" is not an error, it's just a warning and it doesn't make any problem in your work.

About LNK errors that you got, I'm not sure what has made them occur, but it's better to first check your **boost-install** folder in the **Build** directory. It shouldn't be empty!

**Comment by microbirdman** [comment]
Hi,

I am having the exact same problem with Boost not being linked properly. I tried to compile 0.9.5, 0.9.6, 0.9.7 and I am always getting that error. In fact, I was trying to compile 0.9.8 just now and it didn't work either. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/3456905/76345369-2416aa80-62fb-11ea-8e32-f068d95d53eb.png)

I tried different versions of Python and Cmake but still not working. Any ideas? Thanks in advance.

**Comment by Julian9875** [comment]
I'm having the same issue, it should has been fixed according to the documentation, but it's not :(

**Comment by danielaDESM** [comment]
I have download everything again and boost appears to be installed correctly. After make launch, unreal ask me to compile again some files and then it shows an error. I open the project in Visual Studio and after building it it only shows me this error. Do someone know how to tackle this?
![image](https://user-images.githubusercontent.com/12168864/76518280-1bd78000-645f-11ea-91bc-2b35ac510fe0.png)

(effectively if I look into the folder carla/Version.h does not exist)

**Comment by danielaDESM** [comment]
I have copied Version.h from another folder (it has a generic code) and it runs without problems. It opens Unreal with no issues. I play it and everything looks fine. When I continue with the make Python API, it shows me an error of not finding Version.h under carla/, so I check in the folder and there is a file "Version.h.in", so I just erased the ".in" extension and tried again to execute make PythonAPI, which leads me to error I was having previous times: the linking error.

![image](https://user-images.githubusercontent.com/12168864/76524941-3f082c80-646b-11ea-84d8-84f547345d5a.png)

**Comment by danielaDESM** [comment]
I have download everything again and boost appears to be installed correctly. After make launch, unreal ask me to compile again some files and then it shows an error. I open the project in Visual Studio and after building it it only shows me this error. Do someone know how to tackle this?
![image](https://user-images.githubusercontent.com/12168864/76518280-1bd78000-645f-11ea-91bc-2b35ac510fe0.png)

(effectively if I look into the folder carla/Version.h does not exist)

**Comment by OnTheStormx** [comment]
Did u find the solution of make PythonAPI @danielaDESM

**Comment by barasm-hita** [comment]
Hi @OnTheStormx 
If the error you are facing is about missing file 'Version.h', the solution is how she told us in her last comment. Let me briefly explain it to you.
There should be a file named **'Version.h.in'** in your CARLA directory. You have to just remove the **'.in'** from the end of its name (rename it to **'Version.h'**). Then your error must be fixed.

**Comment by estebanmoreno** [comment]
Hi @barasm-hita,

That's right. The Version.h.in has to be renamed. I had already done that on my previous post but still getting all the dependency errors I showed. Did you find a solution @danielaDESM?

**Comment by estebanmoreno** [comment]
Hi @barasm-hita,

Thanks for the prompt reply. Actually I ran the **make** command from the root CARLA folder. I was at that other directory in the screenshot because I was trying to manually build it using setup.py.
