### ISSUE TITLE
Doc: Debian packages: missing os version hint

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/carla#2571]
http://carla.org/2020/03/09/release-0.9.8/#carla-098-apt-installation should contain a note which versions of Ubuntu are supported.

In the commands "bionic" (18.04) is used.

**Comment by sergi-e** [comment]
Hello!
There is no OS dependency, it works for both Ubuntu 16 and 18. A codename was necessary to create the package, but it has been changed for clarity to "all main". 
The package works for Ubuntu 16 and later :)
