### ISSUE TITLE
Depth Camera 's depth value jumps

### ISSUE THREAD

**Issue by minrui-hust** [carla-simulator/carla#2572]
I am using depth camera, but the depth value of the depth camera seems split into two parts.
And there is a gap between them, as denoted by the blue line. The gap move with the ego car.
Any one know the reason?
![er](https://user-images.githubusercontent.com/42531084/76295063-f1ff4b80-62ee-11ea-8b0d-959831291acf.png)

**Comment by minrui-hust** [comment]
I found the reason! I am debug carla from vs code, some how, the asset corresponding to weather is not load correctly, which impose some strips on the view. I think the issue #2460 may be caused by the same reason.

**Comment by animareversed** [comment]
Hi,
How do you visualize the image? Which values does it have?

**Comment by minrui-hust** [comment]
I just use the PythonAPI example/manual_control.py, use 'N' to switch depth camera(default RGB).

**Comment by animareversed** [comment]
So, if I am not wrong, your image is in logarithmic mode, right?

**Comment by minrui-hust** [comment]
Yes, in logarithmic mode.

**Comment by animareversed** [comment]
Ok thanks

**Comment by TzabarDolev** [comment]
There is an small error in the formula which is given in the 'readthedocs' of the depth sensor.
I wrote about it the CarlaSimBlog - https://carlasimblog.wordpress.com/2023/09/16/sensors/
