### ISSUE TITLE
Carla from sources freezes after make launch (Ubuntu 18.04)

### ISSUE THREAD

**Issue by egorfolley** [carla-simulator/carla#2579]
I have successfully built Carla-simulator from sources using documentation. I have tested UE4 before carla installation and it works well. After I `make launch` and after `make PythonApi` (it all finished with success!) UE4Editor is freezes after 2-3 seconds after I launched it.
How could I resolve that problem?
I actually need to build a custom map, so I need editor at first.

**Comment by dishakamale** [comment]
I know it's been a while since this issue was posted, but is there a workaround for it? I am facing exactly the same problem. Thanks in advance!
