### ISSUE TITLE
Pedestrian, what is the algorithm to control pedestrain's path.

### ISSUE THREAD

**Issue by 5guo** [carla-simulator/carla#258]
Firstly, the code of carla-simulator/carla is so beautiful. I have a problem when I read it, where can I find the program about control pedestrain? When a pedestrain is generated with position and speed, then, how to calculate his next position?

**Comment by nsubiron** [comment]
Hi @5guo,

Pedestrian are using the built-in navigation system that comes with Unreal Engine. The trick is to add a `UCrowdFollowingComponent` to our `AWalkerAIController` class. Pedestrians avoid each other and find their way following the navmesh present in the maps, we just tell them where to go and their max speed. The map also has areas with different weights, so pedestrians prefer to walk on the sidewalk and cross the road only when necessary.

Just mention that this system has some issues, as in #6 or #7.

**Comment by 5guo** [comment]
Thank you so much for your attention and answer. The pedestrians can find their way in the maps and avoid each other, all of these are provided by Unreal Engine's algorithm? So, where can I find the algorithm's detail?

**Comment by nsubiron** [comment]
The navigation mesh is generated by adding a [navmesh volume](https://docs.unrealengine.com/latest/INT/Engine/AI/BehaviorTrees/QuickStart/2/) to the scene. Then the paths are calculated using an A* algorithm. You can find more details in Unreal Engine documentation or even their source code.

**Comment by 5guo** [comment]
All pedestrians can avoid collision from each other, was this function provided by UE4's AI Modules? Or It was implemented with Carla's algorithm?

**Comment by nsubiron** [comment]
All the pedestrian movement is done by Unreal Engine's methods, including avoidance.

The only thing we implement is a basic detection of vehicles, when a vehicle appears to be in the pedestrian route the pedestrian momentarily pauses its movement. We implement this to avoid #7 as much as possible.

**Comment by simmates** [comment]
It would be nice to be able to implement an interface to manage the control of pedestrians - especially to generate corner cases.

**Comment by nsubiron** [comment]
Controlling all the agents in the scene is a feature we have in our backlog, follow the progress at #184.

**Comment by slyer0009** [comment]
> Hi @5guo,
> 
> Pedestrian are using the built-in navigation system that comes with Unreal Engine. The trick is to add a `UCrowdFollowingComponent` to our `AWalkerAIController` class. Pedestrians avoid each other and find their way following the navmesh present in the maps, we just tell them where to go and their max speed. The map also has areas with different weights, so pedestrians prefer to walk on the sidewalk and cross the road only when necessary.
> 
> Just mention that this system has some issues, as in #6 or #7.

Can you explain how to add a UCrowdFollowingComponent to get this working? I'm unable to get my spawned pedestrians to move using the navmeshs in Town01
Thanks!

**Comment by jingluoquanergy** [comment]
@nsubiron I've observed pedestrians intermittently walk though vehicles for CARLA with commit id  5ce501d079981d931554b6bb0a9e39ed71d423a2. It tends to happen when the vehicles are at slow speed(e.g. making a turn).
