### ISSUE TITLE
sync server runs at max 23 fps

### ISSUE THREAD

**Issue by sapirbm** [carla-simulator/carla#2582]
when using carla in sync mode the maximum fps i can get is 23fps, regardless of the amount of vehicles in the simulation. 
i've read the explanations regarding the parallelism in async threads. 
my question is - is this the best sync performance we will get in the foreseeable future? or is there anything can be done with it? 

thanks,
sapir.

**Comment by minrui-hust** [comment]
I think it is, the bottleneck is moving data from gpu ram to cpu ram(as far as I know by reading the source of both carla and unreal engine). UE read gpu data on render thread(or RHI thread), which block the rendering, so you will find that the GPU usage is not very high, but fps is low.
