### ISSUE TITLE
Pedestrians are sinking down to half of their height in Carla Town03 and custom maps

### ISSUE THREAD

**Issue by chandeep11** [carla-simulator/carla#2587]
I've been testing the pedestrian spawning feature using manual control in Carla 0.9.7. In some areas of Town03, I can see that the pedestrians are not resting on the ground/road and instead they are sinking down to half of their height. Seems like a bug in this town.

Pedestrian spawning resting properly.
![carla_pedestrian](https://user-images.githubusercontent.com/48788649/76598396-c9fb2c80-6528-11ea-90e2-9c161b5d4ea3.png)

Pedestrian sinking down.
![carla_ped2](https://user-images.githubusercontent.com/48788649/76598419-d1bad100-6528-11ea-8306-1e630603ad63.png)

Even in the custom map I've created using road runner,I'm facing the same issue. Instead of the pedestrian resting properly/sinking to half (as it happens in Carla towns), here they are not resting on the ground and they are falling down through roads indefinitely. 
![own_map](https://user-images.githubusercontent.com/48788649/76598854-b8665480-6529-11ea-9b81-3998487bff8f.png)

I'm not using the landscapes in my custom map and only the meshes generated using road runner. Cars are spawning properly, colliding with the roads and working fine. The issue is only with the pedestrians. 
Can this issue be fixed by using the landscape along with my custom map? Temporarily I'm fixing this issue with invisible blocking volumes under the road (which is not as proper as the Carla towns). Please help me out with where I'm missing in my custom map.

**Comment by Zhuxy** [comment]
Same problem. 
Is that fixed?

**Comment by chandeep11** [comment]
@Zhuxy No, not yet found the solution/cause. @TheNihilisticRobot could you help on this?

**Comment by ptigas** [comment]
@chandeep11 "Temporarily I'm fixing this issue with invisible blocking volumes under the road (which is not as proper as the Carla towns)." - is this something you don on roadrunner or you're hacking Carla for that?

**Comment by chandeep11** [comment]
@ptigas Those blocking volumes are added via the UE4 Editor(It's a UE4 feature) in the source version Carla and then made a binary out of it. I don't think you can do the same in compiled version directly.

**Comment by germanros1987** [comment]
@XGodina this needs urgent attention.

**Comment by avishek-mondal** [comment]
This could be related to the issue I noticed here https://github.com/carla-simulator/carla/issues/2976

**Comment by XGodina** [comment]
@avishek-mondal @Zhuxy Hi, Sorry to answer late. I m working with that. There are some ways to check it, collisions, or the Spaw points where pedestrians are born. As soon as I can, I'll let you know.

**Comment by XGodina** [comment]
@Zhuxy @chandeep11. I advise you to use the current version of CARLA0.9.9. Does this only happen in Town03?

**Comment by chandeep11** [comment]
@XGodina Yes, This happens only in some parts of Town03 and the custom maps created with RoadRunner. I've a doubt, will the FBX from RoadRunner is used directly or some alterations do take place (like adding collision to road or landscape or any blocking volumes beneath the road) in Carla.?
P.S: I'm importing the RoadRunner model as it is without any modifications in UE4 and then testing the Pedestrian spawning feature which makes the pedestrians to sink down.

**Comment by firas-elhag** [comment]
Hi @XGodina has the issue related to importing fbx file of roadrunner into Carla has been identified as the issue to sinking pedestrians as I am facing the same issue is related to Carla or roadrunner?
