### ISSUE TITLE
Cannot find all the vehicles in carla simulator whose blueprints are present in Content Directory

### ISSUE THREAD

**Issue by Akshay-sudo-ux** [carla-simulator/carla#2590]
Carla version 0.9.6 
OS VERSION= Ubuntu 16.04.6 LTS (Xenial Xerus)
Hi,
I found that there is truck blueprint asset named BP_TRUCK under Content/Carla/static/vehicles/4Wheeled/Truck directory but when using PythonAPI with carla simulator to print the list of available vehicles I am able to get only the vehicles mentioned below
    vehicle.audi.a2
    vehicle.audi.etron
    vehicle.audi.tt
    vehicle.bh.crossbike
    vehicle.bmw.grandtourer
    vehicle.bmw.isetta
    vehicle.carlamotors.carlacola
    vehicle.chevrolet.impala
    vehicle.citroen.c3
    vehicle.diamondback.century
    vehicle.dodge_charger.police
    vehicle.ford.mustang
    vehicle.gazelle.omafiets
    vehicle.harley-davidson.low rider
    vehicle.jeep.wrangler_rubicon
    vehicle.kawasaki.ninja
    vehicle.lincoln.mkz2017
    vehicle.mercedes-benz.coupe
    vehicle.mini.cooperst
    vehicle.nissan.micra
    vehicle.nissan.patrol
    vehicle.seat.leon
    vehicle.tesla.model3
    vehicle.toyota.prius
    vehicle.volkswagen.t2
    vehicle.yamaha.yzf

how to add the truck vehicle to the above list?

**Comment by superying** [comment]
I have the same question, any solution?
