### ISSUE TITLE
Car head and break lights

### ISSUE THREAD

**Issue by najibghadri** [carla-simulator/carla#2592]
Hello! 
Are there any car lights in the simulator? If not what's the way to implement one easily? I think this is an essential part for car detection in dark, but even in daylight.

**Comment by adrigrillo** [comment]
Hi @najibghadri! You can have a look [here](http://carla.org/2020/03/09/release-0.9.8/#night-mode) where the night mode and the lights of the cars are mentioned.

Additionally, in [`manual_control.py`](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control.py) the state of the lights are modified.

**Comment by najibghadri** [comment]
Awesome thanks!
