### ISSUE TITLE
Carla freezes after running server

### ISSUE THREAD

**Issue by egorfolley** [carla-simulator/carla#2596]
I have installed Carla from the source for Linux ( I have Ubuntu 18.04 ) and everything was good until `make launch` command. 
I checked UE before starting building Carla and it works well. The problem seems to be in Carla. Is there any help here ???

**Comment by akssieg** [comment]
I am facing the similar problem. Did you find the solution?

**Comment by egorfolley** [comment]
@akssieg nope, I had to make a project 2 months ago, so now it's not relevant for me
