### ISSUE TITLE
carla-0.9.7 occur error when spawn vehicle

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#2600]
when I load map which I print in UE4 and  run spawn_npc.py ，computer memory has Increasing usage. and the cars will only go straight. However there is no this issue  in carla-0.9.6 .

**Comment by jackbart94** [comment]
Hi,

Things changed drastically from 0.9.6 to 0.9.7 with the introduction of the client-side Traffic Manager instead of the server-side autopilot, this is why you are experiencing this issue. Either revert to 0.9.6 or try with 0.9.8 (which also has a better Traffic Manager!)

**Comment by whuxhzhang** [comment]
Mr Bartiromo,
&nbsp;Thanks for your reply.
&nbsp;Now I have changed carla-0.9.8.
&nbsp;But when I build carla-0.9.8 , it will show&nbsp;Error: CDO Constructor (TrafficLightManager): Failed to find Blueprint'/Game/Carla/Blueprints/TrafficLight/BP_TLOpenDrive.BP_TLOpenDrive'
&nbsp;Could you tell me the reason for this phenomennon, or where is this file?


&nbsp;Thank you.
&nbsp;
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jacopo Bartiromo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上7:41
收件人:&nbsp;"carla-simulator/carla"<carla@noreply.github.com&gt;;
抄送:&nbsp;"张新红"<1141987921@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [carla-simulator/carla] carla-0.9.7 occur error when spawn vehicle (#2600)





 
Hi,
 
Things changed drastically from 0.9.6 to 0.9.7 with the introduction of the client-side Traffic Manager instead of the server-side autopilot, this is why you are experiencing this issue. Either revert to 0.9.6 or try with 0.9.8 (which also has a better Traffic Manager!)

**Comment by jackbart94** [comment]
Hi,

You shouldn't worry too much about that, it's for an upcoming feature and CARLA should work anyway!

**Comment by whuxhzhang** [comment]
Hi,


OK, I'll try again


thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jacopo Bartiromo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上8:16
收件人:&nbsp;"carla-simulator/carla"<carla@noreply.github.com&gt;;
抄送:&nbsp;"张新红"<1141987921@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [carla-simulator/carla] carla-0.9.7 occur error when spawn vehicle (#2600)





 
Hi,
 
You shouldn't worry too much about that, it's for an upcoming feature and CARLA should work anyway!
