### ISSUE TITLE
Get Traffic Manager waypoint as Prediction 

### ISSUE THREAD

**Issue by hsienyan** [carla-simulator/carla#2601]
Hi 

Traffic manager controls all the movement of actors in the world.

Could I get the traffic manager future waypoint result as my prediction to the other actors?

Thanks

**Comment by jackbart94** [comment]
Hi,

We have that scheduled for the actual release, so stay tuned! If you want to try it yourself, you need to expose the waypoint_buffer in Localization, it's pretty easy to do so as you should do what every parameter does, with a getter instead of a setter.

**Comment by hsienyan** [comment]
thank @jackbart94 ,i am looking forward to the next release.
