### ISSUE TITLE
chmod: changing permissions of '/opt/carla/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping': Operation not permitted

### ISSUE THREAD

**Issue by jediofgever** [carla-simulator/carla#2602]
* Linux, Ubuntu 18.04 LTS
* apt installation of Carla with version `0.9.7 `
* Nvidia driver `440.64 `

I just try to run `./CarlaUE4.sh `, but there is error occuring as follows; 

```
chmod: changing permissions of '/opt/carla/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping': Operation not permitted
4.22.3-0+++UE4+Release-4.22 517 0
Disabling core dumps.
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x3e00041
  Serial number of failed request:  377
  Current serial number in output stream:  383
Signal 11 caught.
Segmentation fault (core dumped)

```

**Comment by poumehrabi** [comment]
Hello, I have the same issue here. Still no solutions huh ?

**Comment by jediofgever** [comment]
There was another issue , same error,
nobody interested to look into this... 
a few people reported that they downgrade the GPU driver, but many cannot do that because the new generation gpus will cause other problems with outdated drivers like `390` or earlier

**Comment by ignaceHelsen** [comment]
I am experiencing the same problem.

**Comment by aliraeisdanaei** [comment]
> There was another issue , same error, nobody is interested to look into this... a few people reported that they downgrade the GPU driver, but many cannot do that because the new generation gpus will cause other problems with outdated drivers like `390` or earlier

My driver was above 390, and it was working fine.

**Comment by aliraeisdanaei** [comment]
My issue went away after I removed conflicting Nvidia drivers on Ubuntu. I am on Nvidia 510

**Comment by ZoeyW061** [comment]
> My issue went away after I removed conflicting Nvidia drivers on Ubuntu. I am on Nvidia 510

hi, I am struggling with the same problem. but even if I update my driver to 525, it still failed.

**Comment by ABD-01** [comment]
Any updates on this issue??
I too am facing this one
