### ISSUE TITLE
Opendrive and OpenScenario Editor

### ISSUE THREAD

**Issue by hsienyan** [carla-simulator/carla#2609]
Is there any Opendrive and OpenScenario editor available in Carla? for user to customize their environment.

Thank you . Appreciate developer creating such an amazing simulator.

**Comment by AIasd** [comment]
I am also interested in this question.

**Comment by bapukokare** [comment]
you can use the road editor opensource on GitHub to create an open drive std. 1.4  map 
https://github.com/fhwedel-hoe/OpenRoadEd
