### ISSUE TITLE
Carla Map/ Aerial view

### ISSUE THREAD

**Issue by prass-anyvision** [carla-simulator/carla#2620]
Hello,

I found #526 , asking about the aerial view for Carla. Not sure if it has been implemented yet.

I am ultimately looking for a map view (would be okay with an aerial view) of objects in the scene, and their positions. Is there something like, given the new architecture in https://github.com/carla-simulator/carla/pull/567 ?

Cheers!

**Comment by devansh20la** [comment]
As an example 
https://github.com/carla-simulator/carla/blob/fe86dc21d1e058fad80b581cef84197ff21295a9/PythonAPI/examples/synchronous_mode.py#L150-L160

Change x,z, and pitch here to get any view you need, 
x = 0, z = 10 and pitch = -85 get me what I need
