### ISSUE TITLE
sky segmentation label

### ISSUE THREAD

**Issue by Xcrid** [carla-simulator/carla#2628]
Dear Carla maintainers,

I would like to know if there is a way to add a class label for the sky when using a semantic segmentation camera.

Thanks

**Comment by Georgini82** [comment]
Hi.
I am also interested in this.

I can't test it now, but this is what I believe is the way to do it:
- Change the Tagger and CityscapesPalette.h files to identify the location of the sky file and call the correct cityscape object.

My issue is the following: 
There are multiple sm_skysphere files... 
In "UnrealEngine" folders, in "Carla/.../Cooked" and in "Dist/.../EngineSky".

Wich is the one used by carla when using the Unreal Editor?

Best regards

**Comment by XGodina** [comment]
Hi @Xcrid, @Georgini82 

We've implemented this tag in this latest release just as we have improved our semantic segmentation making it more detailed. I encourage you to try this release 9.10 to see what you think.
