### ISSUE TITLE
Clarification Vehicle Reference Point

### ISSUE THREAD

**Issue by FrageS** [carla-simulator/carla#2636]
Hi,

following this issue #2153 , it should be clarified and in my opinion standardized, which reference point is used for the standad vehicles in the database. 

The problem is, the current reference point is the center of geometry, which is not the case for all vehicles (0.9.6&7). The center of mass location is given relative to the center of geometry and the CoG position can be retrieved by the bounding box location.  This is quite vague.
i.e --> If you get the position of all 4 wheels, you can not derive the position of the CoG or CoM, as you don't get any information about the positon of the wheels relative to the bounding box or relative to the CoG/CoM. As well it highly depends on the creator of the blueprint to define the center point of the bounding box as the CoG. 

A standardization / guide-line for a reference point for all vehicles would clarify such things. Other simulation tools are using e.g the center of the rear or front axle, others the center of gravity, which is not the best choice as it changes with load or during dynamic maneuvers

**Comment by sshawn9** [comment]
mark, waiting for any updates
