### ISSUE TITLE
Using UE4 SetDriveTorque to move a vehicle 

### ISSUE THREAD

**Issue by Janmart10** [carla-simulator/carla#2643]
Hi, I'm trying to create a vehicle that steers using a differential drive, where one wheel spins in one direction and the other wheel spins in the opposite direction whilst steering. 

I've read the previous issue mentioned in this post: https://github.com/carla-simulator/carla/issues/339 
and am aware I will have to make some changes to the CarlaWheeledVehicle.cpp

I was just wondering if it would be possible to use the C++ function:
`void setDriveTorque(const PxU32 id, const PxReal driveTorque);  ` from the PhysX vehicle SDK
as a means of controlling a vehicle, particularly for steering?

I am aware this can be easily implemented when simply using the UE4 editor, but what I am interested in is if this would work after making a carla package using "make package"? 

That is, is it possible to implement steering and movement using setDriveTorque inside the CarlaWheeledVehicle.cpp file (or elsewhere) and have that behaviour be reflected in a vehicle after creating a carla package?

I am relatively new to Unreal so I apologise if anything that I had said is absurd. Any help would be greatly appreciated.

**Comment by sdwyc** [comment]
> Hi, I'm trying to create a vehicle that steers using a differential drive, where one wheel spins in one direction and the other wheel spins in the opposite direction whilst steering.
> 
> I've read the previous issue mentioned in this post: [#339](https://github.com/carla-simulator/carla/issues/339) and am aware I will have to make some changes to the CarlaWheeledVehicle.cpp
> 
> I was just wondering if it would be possible to use the C++ function: `void setDriveTorque(const PxU32 id, const PxReal driveTorque); ` from the PhysX vehicle SDK as a means of controlling a vehicle, particularly for steering?
> 
> I am aware this can be easily implemented when simply using the UE4 editor, but what I am interested in is if this would work after making a carla package using "make package"?
> 
> That is, is it possible to implement steering and movement using setDriveTorque inside the CarlaWheeledVehicle.cpp file (or elsewhere) and have that behaviour be reflected in a vehicle after creating a carla package?
> 
> I am relatively new to Unreal so I apologise if anything that I had said is absurd. Any help would be greatly appreciated.

Hi! Did you have done it now? I want to achieve similar function. Do you have any help?
