### ISSUE TITLE
A new vehicle has no gravity

### ISSUE THREAD

**Issue by annaornatskaya** [carla-simulator/carla#2644]
Hi
I added a new vehicle and it seems like my vehicle has no gravity. I followed the "How to add assets" tutorial to add the vehicle. But when I start a simulation my car just  takes off and starts circling in the sky. Then CARLA crashes. 
How to put the car on a road?
Thanks

**Comment by iAdidi** [comment]
Hello,

Maybe you can try setting the physics for your vehicle with this command:
https://carla.readthedocs.io/en/latest/python_api/#commandsetsimulatephysics

If the physics are not defined, you can do it with this method in carla.Vehicle:
apply_physics_control(self, physics_control)

Which parameters are defined here:
https://carla.readthedocs.io/en/latest/python_api/#carla.VehiclePhysicsControl

**Comment by germanros1987** [comment]
@annaornatskaya does this solve your problem?

**Comment by germanros1987** [comment]
I am considering this issue solved due to lack of activity.
