### ISSUE TITLE
How to save lane marking coordinate in form of world coordinate in text file

### ISSUE THREAD

**Issue by Shashikant255** [carla-simulator/carla#2646]
I have attached semantic segmented camera on vehicle. I am able to save those segmentation image. Now I want to save all lane marking (that are there in image) coordinate in some text file. These coordinate of lane should be in form of world coordinate.

@sergi-e  @bernatx   @jackbart94 
Thanks in advance for your help!

**Comment by sergi-e** [comment]
Try to overlap the semantic segmentation sensor with a depth camera so that you can retrieve pixel data consistently between both. The depth can be used to get the 3D position of the world, so that could make it.

**Comment by Shashikant255** [comment]
I have not worked on depth camera. Can you suggest some link that show how to get 3D position from depth camera?
