### ISSUE TITLE
How do we find out how the algorithm works?

### ISSUE THREAD

**Issue by jinkman** [carla-simulator/carla#2658]
Hello, Carla team:

I want to know how set_autopilot() and more functions work,But i just can find  carla-0.9.8-py3.7-win-amd64.egg.I want to know some principles of sensors,like LaneInvasionSensor.But there's only a function :world.spawn_actor(bp, carla.Transform(), attach_to=self._parent).Most of the principles seem to be carla-0.9.8-py3.7-win-amd64.egg.

![image](https://user-images.githubusercontent.com/50129609/77603822-ff9e0d80-6f4b-11ea-939f-56c9c50e9ad0.png)
Can you give me some advice?

**Comment by KasraMokhtari2112** [comment]
I have the same question, did you find anything?
