### ISSUE TITLE
Question about OpenDrive release note

### ISSUE THREAD

**Issue by gismo07** [carla-simulator/carla#2659]
The latest version has some interesting node added to the release:

> Added OpenDRIVE standalone mode that allows physical map generation from OpenDRIVE data

However, there is no more information about that specific feature. What exactly is meant by that?
How to work with OpenDrive data only?

Thanks

**Comment by germanros1987** [comment]
@sergi-e and @marcgpuig could you point out how to run the feature since there is no proper documentation for that yet?

**Comment by dineshresearch** [comment]
Yes even I am struck with the same, can you please help us by elaborating that? Can we use only the .xodr file and .fbx file is not required? (or) It will be generated automatically which was not the case before.

**Comment by sergi-e** [comment]
@gismo07 and @dineshresearch !
There is some information about it in the release post, http://carla.org/2020/03/09/release-0.9.8/, but let me sum it up for you. 

Basically CARLA can ingest an OpenDRIVE file describing a road without the need of a .fbx. The simulator will create a basic road mesh using the information that describes it. To test this feature, the config.py script in PythonAPI/util/ has a new argument, -x or --xodr-path, which is a string containing the path to the .xml file.
> python3 config.py -x path/to/some/file.xodr

The feature is still in development, and it has some limitations. Maybe @marcgpuig can provide you with a more detailed report of its current state.
