### ISSUE TITLE
Displaying multiple cameras at the same time

### ISSUE THREAD

**Issue by AmirHarvey** [carla-simulator/carla#2666]
Hello there,
I added multiple RGB cameras in manual_control.py, can anyone tell me how to display them at the same time in pygame?
I am using carla 0.9.8.

**Comment by Saminhasan5220** [comment]
Try this out - 

[mod.txt](https://github.com/carla-simulator/carla/files/4398098/mod.txt)

Modify the depth_render function to display another rgb camera

**Comment by AmirHarvey** [comment]
thanks but it gives me an error AttributeError: 'NoneType' object has no attribute 'get_settings'

**Comment by roserbatlle** [comment]
Hello @AmirHarvey, 
I'm also intending to reproduce the image above in my simulation. Were you able to solve this issue? If so, could you share some recommendations? 
Thanks! :)

**Comment by darld** [comment]
I also looking the method to run as similar to the @AmirHarvey attached. Hope anyone can give the helps.

**Comment by aamzhas** [comment]
Hi all, just checking in to see if anyone was able to make any progress on this issue?

**Comment by ruff-huettinger** [comment]
I also wanted to put another RGB camera output onto the screen. To implement a minimap.
