### ISSUE TITLE
How to get depth point cloud in terms of global co-ordinate frame.

### ISSUE THREAD

**Issue by Saminhasan5220** [carla-simulator/carla#2667]
I am collecting depth and pose data using this script - 
[mod.txt](https://github.com/carla-simulator/carla/files/4398111/mod.txt)

then i convert the depth image to pointcloud using this script - 
[PC.txt](https://github.com/carla-simulator/carla/files/4398118/PC.txt)

Here the pointcloud is in car reference frame and the pose data contains translation(x,y,z) and rotaion (roll,pitch,yaw) information of the car with respect to global reference frame.

How can i convert the pointcloud to global frame?

I want to merge the pointclouds in global frame to make a map. 
I am using carla 0.9.8. in windows 10.

**Comment by vinodrajendran001** [comment]
@saminhasan  May I know how you resolved the issue? It would be helpful if you could share the script. Thanks
