### ISSUE TITLE
Toggle ligths of NPC

### ISSUE THREAD

**Issue by Roosstef** [carla-simulator/carla#2668]
Hey,

Is there an Opportunity to toggle the low Beam lights of npcs at Night?

**Comment by sergi-e** [comment]
Hi, @Roosstef !

Actually there is, but it is not done automatically. 
1. Get a list with the vehicles which lights are going to be enabled/disabled. 
2. Create a carla.VehicleLightState, or a list of such to be applied. 
3. Apply them to the vehicles using Vehicle.set_light_state(your_light_state)
The class Vehicle.LightState is detailed here: https://carla.readthedocs.io/en/latest/python_api/#carlavehiclelightstate
And there is an example on how to use it here: https://carla.readthedocs.io/en/latest/core_actors/#vehicles
