### ISSUE TITLE
Fisheye camera support in carla

### ISSUE THREAD

**Issue by Shashikant255** [carla-simulator/carla#2669]
Is there any way to get fish eye image in Carla current version i.e in 0.9.8?
@cassfalg

**Comment by Axel1092** [comment]
Hi @Shashikant255, currently there is no fish eye lens available in Carla. However, there is a distortion mode that approximates the fish eye lens. You can check this by pressing the number 8 in the `manual_control.py`. You still need to change the FOV yourself in the script.
