### ISSUE TITLE
Reduce pedestrian's view distance of vehicle (CARLA 0.9.7)

### ISSUE THREAD

**Issue by Janmart10** [carla-simulator/carla#2670]
Hi, 
I was wondering if it was possible to reduce the distance in which a walker can detect and avoid a vehicle before it begins to stop.

I have tried reducing the BoxCollision components of both the vehicle (Vehicle Bounds) and pedestrian (Car Stopper) to very small sizes in Unreal Engine. However there still seems to be a large area between the walker and vehicle before they start to stop, and eventually turn the other way:

![vehicle bounds bicycle](https://user-images.githubusercontent.com/25430331/77866899-976b6680-7280-11ea-850e-ebedcd1b7817.png)

I was wondering if there was any other way of reducing this gap, so that the walker can approach the vehicle at a closer proximity before stopping. I have also tried reducing the Agent radius in the Nav mesh settings but this has had no effect.

**Comment by KasraMokhtari2112** [comment]
I just started to work with CARLA and have some basic questions:
1. How we can change CARLA predefined functions? I know there should be some cpp codes related to that but I can't find them in CARLA folders. 
2. How can you run CARLA through Unreal Engine?

I really appreciate it if you can help me with that. Thanks!

**Comment by germanros1987** [comment]
@KasraMokhtari2112 please, do not kidnap the thread. Open your own issues.

**Comment by germanros1987** [comment]
@jackbart94 could you help @Janmart10 with this issue?

**Comment by jackbart94** [comment]
Hi,

As far as I understand, he is trying to change some parameters in the pedestrian movements. Maybe @bernatx can help with this, since Traffic Manager has its own parameters for bounding boxes, but they only affect the vehicle's behaviors.

**Comment by bernatx** [comment]
Hi,
The management of the pedestrian is done inside the Recast&Detour library, with a modified version where we can add vehicles to be avoided by pedestrians dynamically. 

So it is complex to let change values for that. For sure we need to improve that part.
Probably in CARLA 0.9.7 the vehicles are not defined as a box but as a circle, that is why the bicycle has a so big area. Probably with CARLA 0.9.8 the collisions work better for pedestrians.
