### ISSUE TITLE
problems with Carla examples

### ISSUE THREAD

**Issue by yousinf** [carla-simulator/carla#2681]
I already worked with carla 0.9.7 without problem. Currently, I switched to carla 0.9.8, but the examples do not work. 
************for spawn_npc.py  . I have this problem:************
python3 spawn_npc.py 

destroying 0 vehicles

destroying 0 walkers

done.
Traceback (most recent call last):
  File "spawn_npc.py", line 269, in <module>
    main()
  File "spawn_npc.py", line 93, in main
    traffic_manager = client.get_trafficmanager(args.tm_port)
RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error.

************for tutorial.py  . I have this problem:************
python3 tutorial.py
created vehicle.carlamotors.carlacola
destroying actors
done.
Traceback (most recent call last):
  File "tutorial.py", line 128, in <module>
    main()
  File "tutorial.py", line 76, in main
    vehicle.set_autopilot(True)

**** your help, please***

**Comment by jackbart94** [comment]
Hi,

For the first one, how are you executing Unreal Engine? And are you using any flag for spawn_npc.py?

Unfortunately tutorial.py is a bit outdated, we need to change a few things to make it work correctly now..

**Comment by yousinf** [comment]
> Hi,
> 
> For the first one, how are you executing Unreal Engine? And are you using any flag for spawn_npc.py?
> 
> Unfortunately tutorial.py is a bit outdated, we need to change a few things to make it work correctly now..

@jackbart94 , did you mean, CarlaUE4.sh? yes I am.
 And are you using any flag for spawn_npc.py? NO

**Comment by jackbart94** [comment]
I can't replicate it, everything works fine here. Tell me exactly what you are executing, and what's your version of both CARLA and UE.

**Comment by yousinf** [comment]
I installed CARLA 0.9.8 as explained on getstrated. I want to test the examples. but none works.
how can I know UE version?
thanks a lot

**Comment by yousinf** [comment]
I installed the pre-compiled version. for my case, I think i don't need UE.

**Comment by jackbart94** [comment]
Hi,

This error often happens when you have a Python process hanging, something that didn't close correctly. Make sure that's not the case by accessing your task manager.

**Comment by yousinf** [comment]
I don't know whats the problem with Carla 0.9.8.  I reinstalled Carla 0.9.7. Its OK.
thanks @jackbart94 for all.
