### ISSUE TITLE
Incomplete road generation

### ISSUE THREAD

**Issue by zc804351220** [carla-simulator/carla#2685]
Version: 0.9.8
Hi,I using custom OpenDrive created by a OpenRoadEd
while click "Generation Roads",there is no error,but road network is not a closed loop

screenhot:
![Incomplete_road_generation](https://user-images.githubusercontent.com/50762787/78117671-85342880-7438-11ea-9bff-9d3e5ebc2452.png)
.xodr file:
[openroaded_20191224.xodr.zip](https://github.com/carla-simulator/carla/files/4413900/openroaded_20191224.xodr.zip)

**Comment by doterop** [comment]
This tool is just a simple visualizer to help to see if the OpenDrive is well-formed. If the OpenDrive is good, the simulation should run. I would suggest checking the OpenDrive to see if there are some information missing or not.

**Comment by germanros1987** [comment]
I am closing this. If the issue persists I will be happy to re-open it.
