### ISSUE TITLE
Parsing an OpenDRIVE file

### ISSUE THREAD

**Issue by Mechatrnk** [carla-simulator/carla#2687]
Hello, I am new to CARLA an I would like to ask you about the function 

`**generate_opendrive_world** ( **self** ,  **opendrive** ,  **parameters** =(2.0, 50.0, 1.0, 0.6, true, true))`

**Parameters:**

* `opendrive`  ( *str* ) – Content of an OpenDRIVE file as  `string` ,  **not the path to the  `.xodr`** .

How can I input the content as a string when the .xodr file is quite large and it uses special formatting and the file looks like this? (Just a snip of a short part of the .xodr file)

    <road name="Road 0" length="1.2333315103592568e+3" id="0" junction="-1">
        <link>
            <successor elementType="road" elementId="1" contactPoint="start"/>
        </link>
        <type s="0.0000000000000000e+0" type="town">
            <speed max="40" unit="mph"/>
        </type>
        <planView>

How can this be given to the function as a string? 

Thank you very much

**Comment by Mechatrnk** [comment]
If possible please delete this issue, I was able to solve it myself but I do not know how to flag this to delete (I am new to GitHub)

Thank you

**Comment by m-ayala** [comment]
I have newly started working on CARLA, it would be helpful if you could share your solution since I'm facing the same issue right now

**Comment by Mechatrnk** [comment]
Hi, what helped is this:

```
import glob
import os
import sys
import time
import xml.etree.ElementTree as ET
import random


myFile = ET.parse("DeadEndRoad.xodr")
root = myFile.getroot()
xodrStr = ET.tostring(root, encoding="utf8" ,method="xml")


try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

actor_list = []


try:

    client = carla.Client("localhost", 2000)
    client.set_timeout(10.0)
    world = client.generate_opendrive_world(opendrive=xodrStr)   
```

Where the most important part is this:

```
import xml.etree.ElementTree as ET

myFile = ET.parse("DeadEndRoad.xodr")
root = myFile.getroot()
xodrStr = ET.tostring(root, encoding="utf8" ,method="xml")
```

**Comment by m-ayala** [comment]
Hey there!
I'm still getting the same error i did before:

`world = client.generate_opendrive_world(opendrive=xodrStr)
RuntimeError: opendrive could not be correctly parsed
`

**Comment by hbanzhaf** [comment]
I experienced the same error and resolved it by switching from the deb package to the [latest package on Github (0.9.9.2)](https://github.com/carla-simulator/carla/releases/tag/0.9.9).

**Comment by m-ayala** [comment]
@hbanzhaf I tried installing it using the package installation method but it didn't work either
I'm getting the same error. Maybe theres a problem with my test code? Here's how it looks like:

`import glob
import os
import sys
import time
import xml.etree.ElementTree as ET
import random


myFile = ET.parse('/home/m_ayala/carla-simulator/PythonAPI/util/opendrive/TownBig.xodr')
root = myFile.getroot()
xodrStr = ET.tostring(root, encoding="utf8" ,method="xml")


try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

actor_list = []


try:

    client = carla.Client("localhost", 2000)
    client.set_timeout(10.0)
    world = client.get_world()
    blueprint_library = world.get_blueprint_library()

    bp = blueprint_library.filter("model3")[0]
    print(bp)

    map = world.get_map()
    spawn_point = random.choice(map.get_spawn_points())
    m = carla.Map('Town03', xodrStr)

finally:
    pass`

**Comment by m-ayala** [comment]
@hbanzhaf I tried installing it using the package installation method but it didn't work either
I'm getting the same error. Maybe theres a problem with my test code? Here's how it looks like:

`import glob
import os
import sys
import time
import xml.etree.ElementTree as ET
import random


myFile = ET.parse('/home/m_ayala/carla-simulator/PythonAPI/util/opendrive/TownBig.xodr')
root = myFile.getroot()
xodrStr = ET.tostring(root, encoding="utf8" ,method="xml")


try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

actor_list = []


try:

    client = carla.Client("localhost", 2000)
    client.set_timeout(10.0)
    world = client.get_world()
    blueprint_library = world.get_blueprint_library()

    bp = blueprint_library.filter("model3")[0]
    print(bp)

    map = world.get_map()
    print(str(map))
    spawn_point = random.choice(map.get_spawn_points())
    m = carla.Map('Town03', xodrStr)

finally:
    pass
`

**Comment by m-ayala** [comment]
@hbanzhaf I tried installing the packages and I'm getting the same error. Maybe there's a problem with my code if someone would like to check it out:

`import glob
import os
import sys
import time
import xml.etree.ElementTree as ET
import random


myFile = ET.parse('/home/m_ayala/carla-simulator/PythonAPI/util/opendrive/TownBig.xodr')
root = myFile.getroot()
xodrStr = ET.tostring(root, encoding="utf8" ,method="xml")

try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

actor_list = []


try:

    client = carla.Client("localhost", 2000)
    client.set_timeout(10.0)
    world = client.get_world()
    blueprint_library = world.get_blueprint_library()

    bp = blueprint_library.filter("model3")[0]
    print(bp)

    map = world.get_map()
    print(str(map))
    spawn_point = random.choice(map.get_spawn_points())
    m = carla.Map('Town03', xodrStr)

finally:
    pass
`

**Comment by m-ayala** [comment]
@hbanzhaf I tried installing the packages and I'm getting the same error. Maybe there's a problem with my code if someone would like to check it out:

```

import glob
import os
import sys
import time
import xml.etree.ElementTree as ET
import random

myFile = ET.parse('/home/m_ayala/carla-simulator/PythonAPI/util/opendrive/TownBig.xodr')
root = myFile.getroot()
xodrStr = ET.tostring(root, encoding="utf8" ,method="xml")

try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

actor_list = []


try:

    client = carla.Client("localhost", 2000)
    client.set_timeout(10.0)
    world = client.get_world()
    blueprint_library = world.get_blueprint_library()

    bp = blueprint_library.filter("model3")[0]
    print(bp)

    map = world.get_map()
    print(str(map))
    spawn_point = random.choice(map.get_spawn_points())
    m = carla.Map('Town03', xodrStr)

finally:
    pass
```

**Comment by ucbmpc2021** [comment]
@m-ayala I have a similar issue where I got a bunch of "... overlaps a driving lane" error messages after loading custom map. Did you manage to solve this issue?
