### ISSUE TITLE
Improve GPU utilization and ScenceCapture parallel computing

### ISSUE THREAD

**Issue by JarvanI** [carla-simulator/carla#2689]
Hello everyone, I want to run multiple clients at the same time, but the number of frames is not very satisfactory to me.
After I opened 5 clients, the number of frames was very low. After using the ProfileGPU command in UE4's console, I found that the bottleneck is on rendering. Below is a screenshot of my test. The ScenceCapture of these 5 clients is serial computing, which caused high latency. And I also tested the GPU data (the data is also below). The memory usage and GPU usage were not fully loaded. 
So I have two questions: 1. Is there any way to make carla improve the utilization of GPU? 2. Can ScenceCapture perform parallel calculations instead of serial calculations?
![微信图片_20200403205359](https://user-images.githubusercontent.com/36652059/78363055-b4d86180-75ed-11ea-8e24-e26f5a1aaf3f.png)
![微信图片_20200403205342](https://user-images.githubusercontent.com/36652059/78363068-ba35ac00-75ed-11ea-8d7a-6a1ba25dbf74.png)
![微信图片_20200403205416](https://user-images.githubusercontent.com/36652059/78363113-d0436c80-75ed-11ea-9660-c77172f69f76.png)

**Comment by doterop** [comment]
Hi @JarvanI!
Thanks for using Carla.
You are completely right, right now we are facing some bottlenecks on the rendering side. The good news is that we will try to improve this soon.
The quickest and easiest solution will be trying to render at a lower resolution with low settings enabled.

**Comment by emailweixu** [comment]
👍 It will be great if rendering for multiple cameras can be parallelized.
