### ISSUE TITLE
How to control gear shift in Carla?

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#269]
I was trying to implement a basic velocity control algorithm using PID, in carla. 
But I notice that the car keeps shifting the gears between kmph to 40kmph (1st and 2nd gear) and 50-60kmph (3rd gear). This is causing a fluctuating speed and control commands from my PID controller.

**Is there a way to control the gear shift or outright disable it?**

The following plots may help visualize the problem better.All plots are with the same tuning parameters:
![60_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045343-b463c446-218b-11e8-84a5-38cd6a4f62c3.png)
![55_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045341-b42b06ec-218b-11e8-8218-038edd518a47.png)
![50_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045339-b3f5cc66-218b-11e8-8a56-886f82822cb5.png)
![45_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045338-b3be7270-218b-11e8-8a0f-7a874d3aa6d3.png)
![40_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045337-b384e28a-218b-11e8-9cb5-515a969e3a37.png)
![35_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045336-b3409a12-218b-11e8-9a8f-ee8010a0e654.png)
![30_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045335-b30fab96-218b-11e8-9745-d0e0031c2df1.png)
![25_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045334-b2d9fc1c-218b-11e8-9abc-ea9b59fe1445.png)
![20_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045333-b2a3b116-218b-11e8-9658-0cf883f3cb10.png)
![15_0 120000_0 005000_0 600000_vc](https://user-images.githubusercontent.com/16332426/37045331-b23403e8-218b-11e8-859f-dabceba17bce.png)

**Comment by nsubiron** [comment]
> Is there a way to control the gear shift or outright disable it?

We don't have currently any way of shifting gears from the client side, it's just not added to the vehicle control. I'm actually surprised no one asked for this up until now :D I think is reasonable to add this to our backlog.

Meanwhile you can tune the vehicle's engine model inside Unreal Editor, would it work adding a single very long gear?

![screenshot from 2018-03-07 11-17-22](https://user-images.githubusercontent.com/4332953/37086960-3be8aa2c-21f9-11e8-8e05-735eeec25830.png)

**Comment by YashBansod** [comment]
Thanks @nsubiron. 
I think setting a very long gear may solve the purpose for now.

**Comment by fbuchinger** [comment]
+1 for the manual gear shift, would love to use my logitech g25 shifter for that.

**Comment by AlienTech83** [comment]
+1 for this, would really be good to be able to shift gears using manual control (either from keyboard or from a steering wheel)

**Comment by NYJiaxing** [comment]
@YashBansod  
Hello Sir,

Would you mind if you can share with me how you get the vehicle's speed data? And did you find where is the vehicle's yaw angle data?

Thank you so much

**Comment by Derekabc** [comment]
Hello, I am not sure what is the meaning of " setting a very long gear ", does that mean we can set munual_gear_shift = 10 (big number?). thank you very much!!
