### ISSUE TITLE
Camera Calibration Parameters

### ISSUE THREAD

**Issue by amrfarag** [carla-simulator/carla#2696]
Hello everyone,
Is there any way to calibrate the camera sensor? or any way to get the distortion and projection parameters? I need to calibrate the CARLA camera so as to use it visual odometry of vehicles.
Thanks in advance

**Comment by sergi-e** [comment]
Hi, @amrfarag!

The RGB camera sensor has quite a lot of parametrization available indeed. You can read about it in the sensors reference. 
https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera

**Comment by germanros1987** [comment]
@XGodina we should make a [calibration board](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2Fcalib-io-CB800600F-Camera-Calibration-800x600mm%2Fdp%2FB07Q21Q644&psig=AOvVaw3--Gc98tRZr0vnm5rDwtfx&ust=1593231077251000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMie77bOnuoCFQAAAAAdAAAAABAD) prop and add it to the library of blueprints, so that users can inject it in the simulator to calibrate their cameras.

Let's take care of this.

**Comment by elvircrn** [comment]
Hi guys, as part of my own research work, I created programmable checkerboard patterns via the material editor in Unreal. I just didn't go through the process of importing it as an asset. Would love to contribute to this issue if help is still needed.

**Comment by germanros1987** [comment]
Definitely. We would love to get a PR with this feature! Thanks for the help

**Comment by Doodle1106** [comment]
Hi @germanros1987 
Thanks for the great work!
Has calibration board been added to Carla?

**Comment by Doodle1106** [comment]
@elvircrn 
Have you found out how to import checker board to Unreal?

**Comment by AbanobSoliman** [comment]
Hello everyone, 
As part of our recent [research work](https://arxiv.org/abs/2206.13455), we needed to have exact (calibrated) values for all CARLA cameras' intrinsic parameters (RGB, Depth, DVS). Accordingly, we added calibration targets (Checkerboard and AprilGrid) to the Town3 map, and calibrated RGB, and DVS cameras using SOTA algorithms. Check out the repo here: [IBISCape](https://github.com/AbanobSoliman/IBISCape).
Thanks.

**Comment by Qdriving** [comment]
> @XGodina we should make a [calibration board](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2Fcalib-io-CB800600F-Camera-Calibration-800x600mm%2Fdp%2FB07Q21Q644&psig=AOvVaw3--Gc98tRZr0vnm5rDwtfx&ust=1593231077251000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMie77bOnuoCFQAAAAAdAAAAABAD) prop and add it to the library of blueprints, so that users can inject it in the simulator to calibrate their cameras.
> 
> Let's take care of this.

Hello, [germanros1987](https://github.com/germanros1987), is there any plan update about the calibration board.

**Comment by GabiShahmayster** [comment]
@Qdriving Could you please share an update about this feature? Will it make it's way into an upcoming release?
Thank you very much!
