### ISSUE TITLE
How to make python class which inherits carla.Vehicle class.

### ISSUE THREAD

**Issue by SUNGBEOMCHOI** [carla-simulator/carla#2698]
python : 3.7
carla version : 0.9.8
os : windows 10

I want to create new python class which inherits carla.Vehicle class. 

when I type like this.
```
class robot(carla.Vehicle):
    def __init__(self, vehicle=None):
        super().__init__()
        self.rgb_cam = None
        self.colsensor = None
        self.goal_loc = None
```

Then, it occurs RuntimeError at line 3
`RuntimeError: This class cannot be instantiated from Python`

How to make python class which inherits carla.Vehicle class.

**Comment by nsubiron** [comment]
I don't think you can. `carla.Vehicle` is a C++ class that can only be instantiated by the `carla.World` as a handle for an existing vehicle on the server side.

Try using composition instead. Make the vehicle a member variable of your class.
