### ISSUE TITLE
when I add a new sensor in server, how to use the variable(position, rotation) to initialize the sensor?

### ISSUE THREAD

**Issue by bxdd** [carla-simulator/carla#2706]
I am writing a new Lidar sensor in server. I can use two class called FLidarDescription  and FActorDescription to initialze the sensor. However, the variable(position, rotation) is not included in both FLidarDescription and FActorDescription. How to pass the variable (position, rotation) to my new Sensor?

**Comment by marcgpuig** [comment]
Hi @bxdd,
The transform of the sensor is sent on any sensor by default when you inherit from SensorData, check out [`LibCarla/source/carla/sensor/SensorData.h`](https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/sensor/SensorData.h).
So, you can just use `sensor_data.transform.position` and `sensor_data.transform.rotation` in the PythonAPI as descrived in the PythonAPI [docs](https://carla.readthedocs.io/en/latest/python_api/#carlasensordata).

Cheers!
