### ISSUE TITLE
generate_opendrive_world lane markings

### ISSUE THREAD

**Issue by AlexScheid** [carla-simulator/carla#2707]
Dear Carla Team,

is there a possibility to show the lane markings from the .xodr map in the Carla simulation by using the new generate_opendrive_world function? I only need a simple representation in my simulation and do not want to use UE4, because my simulation does not require a realistic representation. In the .xodr files some lane markings can be defined and I would like to use them. I am using Carla version 0.9.8 with ubuntu.
Thank you!

**Comment by sergi-e** [comment]
Hi, @AlexScheid !

Unfortunately, lane markings have not been added yet to the OpenDRIVE standalone mode. 
However, I would like to suggest you a workaround that you may find useful and that does not require UE4. 
1. Use a software such as RoadRunner to generate a .fbx for your .xodr. 
2. Create a package using the Docker pipeline. Explained here: https://carla.readthedocs.io/en/latest/tuto_A_add_map/#map-ingestion-in-a-carla-package
3. Import your map and use it. 

The process can be seen here: https://www.youtube.com/watch?v=dvPhN0Gbb0w&t=45s
As you can see, the new map does not have to be detailed at all. It may be empty aside from the road.
