### ISSUE TITLE
Carla RSS 3.0.0 Compilation Error

### ISSUE THREAD

**Issue by gitmaster3000** [carla-simulator/carla#2715]
Generating done
-- Build files have been written to: /home/carla/carla/Build/libcarla-client-build.rss.release
ninja: error: '../ad-rss-3.0.0/install/ad_rss/lib/libad_rss.a', needed by 'LibCarla/cmake/test/libcarla_test_client_release', missing and no known rule to make it
Util/BuildTools/Linux.mk:132: recipe for target 'LibCarla.client.rss.release' failed
make: *** [LibCarla.client.rss.release] Error 1

Hi Guys,
I get the following error when trying to compile the RSS variant.

**Comment by pengqiwang1** [comment]
Hello,Would you like to solve the problem

**Comment by abol-karimi** [comment]
I get the same error on the current dev branch. Any solutions?
