### ISSUE TITLE
Building C++ Client should include header dependencies

### ISSUE THREAD

**Issue by j-o-d-o** [carla-simulator/carla#2718]
When building and installing the c++ Client, it would great if the header dependencies (boost, rpc, recast), were to be included in the include folder.
My usecase: I build the Client automatically with CMakes `ExternalProject_Add()`, but it does not work out of the box as a stand-alone install.
After the build and install, I have to copy the include dependencies for boost, rpc and reacst from _<caral_root>/Build/_ folder into my _<install_dir>/includes_ folder. If these dependencies would be installed automatically by ninja, then it would work stand-alone.

Here is my CMake code:
```cmake
IF (NOT EXISTS ${EXTERNAL_INSTALL_DIR}/carla)
  ExternalProject_Add(CarlaPrj
    GIT_REPOSITORY "https://github.com/carla-simulator/carla"
    GIT_TAG "${CARLA_VERSION}"
    CONFIGURE_COMMAND cd <SOURCE_DIR> && make setup && cd Build && cmake
      -G "Ninja"
      -DCMAKE_BUILD_TYPE=Client
      -DLIBCARLA_BUILD_RELEASE=ON
      -DLIBCARLA_BUILD_DEBUG=OFF
      -DLIBCARLA_BUILD_TEST=OFF
      -DCMAKE_TOOLCHAIN_FILE=${ROOT_DIR}/compiler_flags.cmake
      -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_DIR}/carla
      <SOURCE_DIR>
    BUILD_COMMAND cd <SOURCE_DIR>/Build && ninja
    INSTALL_COMMAND cd <SOURCE_DIR>/Build && ninja install
  )
ENDIF()

SET(CARLA_INCLUDE_DIR ${EXTERNAL_INSTALL_DIR}/carla/include)
SET(CARLA_LIB_DIR ${EXTERNAL_INSTALL_DIR}/carla/lib)
```

Carla Version: 0.9.7

**Comment by nsubiron** [comment]
They do get copied, but under `<install-path>/include/system`. The docs in [CppClient](https://github.com/carla-simulator/carla/tree/master/Examples/CppClient) are outdated.
