### ISSUE TITLE
Custom Semantic Segmentations Tags

### ISSUE THREAD

**Issue by tapirnaserich** [carla-simulator/carla#2724]
Is it possible to have your own semantic segmentation tags? And can we have more than 12 Tags? How do we have to prepare our Model to be seen as a new class for semantic segmentation?
I think its not very clear from the documentary.

**Comment by marcgpuig** [comment]
Hi @tapirnaserich,
The current limitation of our semantic segmentation is 255 different tags (excluding the id 0).
You will find these tags here
https://github.com/carla-simulator/carla/blob/67684c5b0d56df1fe9fc54f59b650975afe6b759/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/Tagger.h#L13-L28

As explained in the [docs](https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-segmentation-camera):
```
Add a new label to the ECityObjectLabel enum in "Tagger.h", and its 
corresponding filepath check inside GetLabelByFolderName() function in "Tagger.cpp".
```
You will need to modify these files and create the folder to store the meshes insithe the unreal engine.
