### ISSUE TITLE
How to uninstall Carla Simulator completely from Ubuntu 18.04

### ISSUE THREAD

**Issue by nihar0602** [carla-simulator/carla#2725]
Hello, 
I have started working on a Carla Simulator on the laptop. However, I realized my laptop specifications are not sufficient to run the Unreal Engine and Carla. Thus I ordered Workstation and installed on that. 

Now I don't work on Carla from the laptop but I use the laptop for other purposes. Since Carla and Unreal Engine almost took 80GB of my hard disk. 

Can anyone help me with how to completely remove Carla Simulator? Your help will be much appreciated. 

Thank You

**Comment by jackbart94** [comment]
Hi,

Delete the CARLA repository and uninstall Unreal.

**Comment by nihar0602** [comment]
Hello, 

Thanks! Another question: How to uninstall Unreal.

**Comment by jackbart94** [comment]
Depending on your OS, find the answer on Google.
