### ISSUE TITLE
Importing RoadRunner data / left turn traffic lights issue

### ISSUE THREAD

**Issue by boldjin** [carla-simulator/carla#2726]
Dear CARLA Team.

**1. Importing RoadRunner data**

I imported GIS Data to create a real road and converted it to Carla format by using RoadRunner.
The DATA also contains information on traffic lights at intersections(Junciton).
​
But When data is imported to Carla and run as python api, it does not move according to the intersection traffic signal information.
(Go straight even when the traffic light is red at the intersection.)

**ScrenShot**
![RoadRunner_ExportingToCARLA2](https://user-images.githubusercontent.com/42859112/79077667-33e03f00-7d3e-11ea-8444-1e345dcef518.png)
![RunCARLA_AutoPilot](https://user-images.githubusercontent.com/42859112/79077675-393d8980-7d3e-11ea-9887-d3a3c489dc5e.png)

**2. Using Unreal Asset - left turn traffic lights**

I want to use a traffic light model with a left turn signal.

I downloaded a model with a left turn signal (no BoxTrigger) from the market place.
Can I add BoxTrigger in CARLA and use it with BP_TrafficLightGroup?
Ask for advice on the problem, the reason, and the solution.

**ScrenShot**
![left_trun](https://user-images.githubusercontent.com/42859112/79078275-3b094c00-7d42-11ea-9dae-22e0c150a0da.png)

----------------------------------
Platform(s): Ubuntu 16.04
Python version(s): 2.7 and 3.5
CARLA version: 0.9.7
Unreal 4.22
RoadRunner 2019.2.11

Thank you.

**Comment by XGodina** [comment]
Hi @boldjin 
In that version, you need to add trigger boxes in UE4 and also setup the BP_TrafficLightGroup.
However, in our last release 0.9.9 we have created a system "Automatic map ingestion to CARLA" with traffic lights from RoadRunner. 
Below, see the video to check our last updates
https://www.youtube.com/watch?v=dvPhN0Gbb0w
