### ISSUE TITLE
Download Assets!

### ISSUE THREAD

**Issue by KasraMokhtari2112** [carla-simulator/carla#2727]
Where can I download the assets for running CARLA through UE editor? It is said in the documentation:
"Only the assets package is yet to be downloaded. \Util\ContentVersions.txt contains the links to the assets for CARLA releases. These must be extracted in Unreal\CarlaUE4\Content\Carla. If the path doesn't exist, create it"

However, this link doesn't work! Thanks!

**Comment by nsubiron** [comment]
Running `Update.sh` should download and extract them for you.

**Comment by sergi-e** [comment]
Hi, @KasraMokhtari2112!

Were you eventually able to download the assets?

**Comment by KasraMokhtari2112** [comment]
> Running `Update.sh` should download and extract them for you.



> Hi, @KasraMokhtari2112!
> 
> Were you eventually able to download the assets?

Yes, I was. Thanks.
