### ISSUE TITLE
problem with get_all_landmarks()

### ISSUE THREAD

**Issue by yousinf** [carla-simulator/carla#2734]
Hi, every body.

I try to do that :
**list_marks = world.get_map().get_all_landmarks()**
but I have this error:
AttributeError: 'Map' object has no attribute 'get_all_landmarks'. 
Your help, please.

**Comment by yousinf** [comment]
Any one has this problem?

**Comment by Axel1092** [comment]
Hi @yousinf. You are finding this error because you are probably using an older version of Carla. This function is only available in the master branch and in the recently released 0.9.9 version of Carla, which you can find here: https://github.com/carla-simulator/carla/releases .

**Comment by yousinf** [comment]
Thanks, I'm going to test the 0.9.9 version.
