### ISSUE TITLE
Can‘t open project in ubuntu 16.04 with UE4.18

### ISSUE THREAD

**Issue by jinlukang1** [carla-simulator/carla#274]
Hi,
How can I solve this?
The UE4 says that the libUE4Editor-CarlaUE4.so and libUE4Editor-Carla.so are missing or built with a different engine version and ask me to rebuild them but when I click yes it says carlaUE4 could not be compiled and try rebuilding from source manually.

And the following  are the fatal error reported in the terminal.
```
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/CodeLiteSourceCodeAccess/Binaries/Linux/libUE4Editor-CodeLiteSourceCodeAccess.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/VisualStudioCodeSourceCodeAccess/Binaries/Linux/libUE4Editor-VisualStudioCodeSourceCodeAccess.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/UObjectPlugin/Binaries/Linux/libUE4Editor-UObjectPlugin.so (API version 0).
LogInit: Warning: Incompatible or missing module: libUE4Editor-CarlaUE4.so
LogInit: Warning: Incompatible or missing module: libUE4Editor-Carla.so
LogInit: Initializing SDL.
LogInit: Using SDL_WINDOW_OPENGL
LogInit: Initialized SDL 2.0.5 revision: 11184 (hg-11184:04063928c4a8 with EpicExtensions) (compiled against 2.0.5)
LogInit: Display metrics:
LogInit:   PrimaryDisplayWidth: 1920
LogInit:   PrimaryDisplayHeight: 1080
LogInit:   PrimaryDisplayWorkAreaRect:
LogInit:     Left=1920, Top=24, Right=3840, Bottom=1080
LogInit:   VirtualDisplayRect:
LogInit:     Left=0, Top=0, Right=3840, Bottom=1080
LogInit:   TitleSafePaddingSize: X=0.000 Y=0.000
LogInit:   ActionSafePaddingSize: X=0.000 Y=0.000
LogInit:   Number of monitors: 2
LogInit:     Monitor 0
LogInit:       Name: DELL SE2416HM 24"
LogInit:       ID: display0
LogInit:       NativeWidth: 1920
LogInit:       NativeHeight: 1080
LogInit:       bIsPrimary: true
LogInit:     Monitor 1
LogInit:       Name: DELL SE2416HM 24"
LogInit:       ID: display1
LogInit:       NativeWidth: 1920
LogInit:       NativeHeight: 1080
LogInit:       bIsPrimary: false
```
I know there is a similar one in these issues but it still can't help me solving my problem.
Can you help me figure out what's could be wrong?

**Comment by YashBansod** [comment]
can you post the shell command you are using to open the carla project?
are you using something like this:
```
cd ~/carla/Unreal/CarlaUE4/
~/UnrealEngine_4.18/Engine/Binaries/Linux/UE4Editor "$PWD/CarlaUE4.uproject"
```
or are you opening the UE4 Editor using something like this: 
```
cd ~/UnrealEngine_4.18/Engine/Binaries/Linux/
./UE4Editor
```
and opening the Carla project from there.

For me a similar warning came for the second method but still my system was able to compile it and I didn't face any fatal errors.

Are you following the installation procedures EXACTLY as mentioned in the Carla's documentation?

**Comment by jinlukang1** [comment]
I have tried the two methods.

$ cd Unreal/CarlaUE4
$ ~/UnrealEngine_4.18/Engine/Binaries/Linux/UE4Editor "$PWD/CarlaUE4.uproject"

or open project in the UE4Editor.

I think what I had done is exactly follow the Carla's documentation

And today when I rebuild it I found that my 'carla/carla_server.h' file not found.
and I tried $make 
after setup successfully just follow the Carla documentation.

but error still exist.

 depfile has multiple output paths
ninja: build stopped: subcommand failed.
Makefile:31: recipe for target 'build_linux' failed
make: *** [build_linux] Error 1

Can you help me figure out what's could be wrong?

**Comment by YashBansod** [comment]
Is it possible to post the logs generated (or some more part of the error printed on the terminal when failure occurs) when you are trying to rebuild the script?

Else you can try the following steps:
After UnrealEngine_4.18 installation is successful (really important that this happened successfully and did not fail).
1. Download the carla's latest repo in the $HOME directory: Open terminial:_Alt + Ctrl + T_
```
cd ~/
git clone https://github.com/carla-simulator/carla.git
```
2. Manually download the latest contents for carla:
Download from google drive:
https://drive.google.com/open?id=1_kSLT8Q05I7zC_X0q4ABMIB8gRd-W-ZF

3. After successful download: **Content_pre_8.0.0.tar.gz** should be available at **~/Downloads**
Just confirm earlier versions of Content for carla are not present in the Downloads folder if you had downloaded contents manually at an earlier time.
 Now 
Open terminial:_Alt + Ctrl + T_ and type:
```
tar xvf Content_*.tar.gz -C ~/carla/Unreal/CarlaUE4/Content/
mkdir ~/carla/Unreal/CarlaUE4/Content/.git/
cd ~/carla/
./Setup.sh
```
See that all this happened successfully.

Download the Automotive materials and extract it into the Contents folder at  **~/carla/Unreal/CarlaUE4/Content/**
At this time the content of Content folder should be:

> user@linuxpc:~/carla/Unreal/CarlaUE4/Content$ ls -la
> total 40
> drwxr-xr-x  9 user domain_users 4096 Mar  4 16:42 .
> drwxr-xr-x 11 user domain_users 4096 Mar  4 17:37 ..
> drwxr-xr-x  6 user domain_users 4096 Jan 10 22:13 AutomotiveMaterials
> drwxr-xr-x  7 user domain_users 4096 Mar  2 15:09 Blueprints
> drwxr-xr-x  2 user domain_users 4096 Mar  4 16:42 Collections
> drwxr-xr-x  3 user domain_users 4096 Mar  4 16:42 Developers
> drwxr-xr-x  2 user domain_users 4096 Mar  4 16:22 .git
> -rw-r--r--  1 user domain_users  251 Mar  2 15:09 LICENSE
> drwxr-xr-x  2 user domain_users 4096 Mar  6 12:41 Maps
> drwxr-xr-x 20 user domain_users 4096 Mar  2 15:09 Static

and the Automotive materials package should be:

> user@linuxpc:~/carla/Unreal/CarlaUE4/Content/AutomotiveMaterials$ ls -la
> total 24
> drwxr-xr-x  6 user domain_users 4096 Jan 10 22:13 .
> drwxr-xr-x  9 user domain_users 4096 Mar  4 16:42 ..
> drwxr-xr-x  6 user domain_users 4096 Mar  4 16:38 LevelContent
> drwxr-xr-x  2 user domain_users 4096 Feb 23 12:18 Maps
> drwxr-xr-x 17 user domain_users 4096 Feb 23 12:18 Materials
> drwxr-xr-x 14 user domain_users 4096 Mar  4 16:38 Textures

Confirm manually that the folders mentioned above are in their right place:

and then: `UE4_ROOT=~/UnrealEngine_4.18 ./Rebuild.sh`

**Comment by jinlukang1** [comment]
Thanks for the reply!
But I found my content of Content folder are

lukangjin@lukangjin-OptiPlex-7050:~/carla/Unreal/CarlaUE4/Content$ ls -la
total 16
drwxrwxr-x 4 lukangjin lukangjin 4096 Mar  11 16:45 .
drwxrwxr-x 6 lukangjin lukangjin 4096 Mar  11 16:28 ..
drwxrwxrwx 6 lukangjin lukangjin 4096 Mar   6 10:11 AutomotiveMaterials
drwxrwxr-x 2 lukangjin lukangjin 4096 Mar  11 16:28 .git

and the Automotive materials package is right.

I don't know which step I made mistake and what should I do then.

**Comment by YashBansod** [comment]
@jinlukang1 I think the problem happened while running the Setup.sh script. Please download the contents folder manually as mentioned in the above post.
Did you download the contents folder from
https://drive.google.com/open?id=1_kSLT8Q05I7zC_X0q4ABMIB8gRd-W-ZF
If so did you extract it to the correct folder?

If you are unable to get the contents folder contents right, just copy paste it there.

**Comment by simmates** [comment]
I had the same problem also on Ubuntu. I rebuilt Unreal Engine and Carla from the same terminal making sure

`$ sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-3.9/bin/clang++ 100
$ sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-3.9/bin/clang 100`

was set. Solved it for me.

**Comment by jinlukang1** [comment]
@YashBansod Thanks very much.
I did what you told me to do and I can run my Carla now.

**Comment by marcgpuig** [comment]
Awesome!
Your help in this kind of issues help us to have more time to work on CARLA.

@YashBansod @simmates 
Thanks so much for your contribution guys!

**Comment by lijecaru** [comment]
I have the same problem, how can I adapt @YashBansod solution to the latest Carla 0.9.3?

**Comment by RAMPRASATH29** [comment]
https://drive.google.com/open?id=1_kSLT8Q05I7zC_X0q4ABMIB8gRd-W-ZF
 Google Drive has not working ..
