### ISSUE TITLE
How to show navigation mesh?

### ISSUE THREAD

**Issue by Abanoub-G** [carla-simulator/carla#2746]
Hi,
I know in UE4 we can press "p" to show the navigable area in a Nav mesh bounding volume. I was wondering if there is a similar option to show carla's navigation meshes?

Thanks

**Comment by Axel1092** [comment]
Hi @Abanoub-G, in Carla we do not use navigation meshes for our vehicles but rather the definition of the road in OpenDRIVE files. You can visualize the driving lanes in the road by doing,
```
distance = 1 # distance in m
waypoints = world.get_map().generate_waypoints(distance)
for waypoint in waypoints:
    world.debug.draw_point(waypoint.transform.location, 0.1, carla.Color(255, 0, 0))
```
