### ISSUE TITLE
Independent steering for front and rear axle + follow a path

### ISSUE THREAD

**Issue by lisatenbo** [carla-simulator/carla#2748]
Hello,
I want to make a vehicle **follow a specific path** without manually contolling it while it drives. It should be possible, to **steer the rear axle** independently of the front steering. In the end, I only want to provide steering angles for front and rear wheels as well as the acceleration to follow the path. Can I fulfill this task with CARLA, and if yes, what would be the best way? 
Is it also possible if I do not use Unreal Engine for this?
Thank you in advance!

**Comment by germanros1987** [comment]
@lisatenbo you can't as the platform is right now. Do you really need to control the front and rear axles independently? What is your use case?

**Comment by germanros1987** [comment]
@lisatenbo are you still interested in this issue?

**Comment by lisatenbo** [comment]
I'm not interested anymore.

**Comment by dodosch** [comment]
Hi @germanros1987 , has this feature been implemented yet?

**Comment by CharlesXu1124** [comment]
@germanros1987 I am also interested, please feel free to tell us a way to control them separately!

**Comment by Nisarg236** [comment]
> 

I am trying to simulate a robot in carla that works on swerve drive. So is there any feature to control steering angles of each wheel through ROS bridge or python API. If not then how can I add it by changing the source code? can anyone help me on this please

**Comment by edmc25** [comment]
I'm also interested in the rear axle steering. Is it maybe already implemented?
