### ISSUE TITLE
Running through Docker 

### ISSUE THREAD

**Issue by PTorr** [carla-simulator/carla#2753]
Hi,

I'm using:  https://hub.docker.com/r/carlasim/carla/ 
to try and run CARLA(0.9.8).

using ./CarlaUE4.sh
I get this:

4.22.3-0+++UE4+Release-4.22 517 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found

And nothing happens (no new window, nothing).

Any Ideas what might be the problem?

**Comment by germanros1987** [comment]
Things do happen, the only thing is that you don't get a screen. Try to connect using a client. It should work.

By the way, you can ignore the xdg warning.
