### ISSUE TITLE
Pre-trained Driving models

### ISSUE THREAD

**Issue by eds89** [carla-simulator/carla#2762]
Dear all,

1) Has anyone ever tried to use a realistic trained driving model (eh Baidu) in Carla? How did it go?

2) the only public abailable models I could find were Apollo Baidu plus Comma.Aí.  Are you aware of any others?

Best regards.

**Comment by mrwesleycrusher** [comment]
Your question might find more attention in the discord server or the forums. Not many eyes outside the maintainers  peruse the issues for fun

**Comment by germanros1987** [comment]
@eds89 what about AutoWare? We have support for AutoWare and actually provide a basic stack here:  https://github.com/carla-simulator/carla-autoware

Soon we will include support for Comma.AI OpenPilot
