### ISSUE TITLE
hi |I am using a windows pc and i am trying to figure out how to reduce the graphics settings in Carla because my computer does not have enough computing power to run the epic simulation. I am using CARLA 0.98

### ISSUE THREAD

**Issue by NikhilSenthilkumaran** [carla-simulator/carla#2765]

**Comment by sergi-e** [comment]
Hi, @NikhilSenthilkumaran !

You have to options here. 
- Run CARLA with low quality: 
```sh
./CarlaUE4.sh -quality-level=Low
```
- Run CARLA with no rendering at all. First run CARLA, and then the following command. 
```sh
cd PythonAPI/util && ./config.py --no-rendering
```
Both are explained in detail in the docs: https://carla.readthedocs.io/en/latest/adv_rendering_options/

**Comment by NikhilSenthilkumaran** [comment]
Thank You @sergi-e. I will close the issue
