### ISSUE TITLE
Warning: cannot parse georeference: ''

### ISSUE THREAD

**Issue by praetorianer777** [carla-simulator/carla#2766]
Hello,
how can I get rid of this warning message? I am using Carla 0.9.8.

**Comment by sergi-e** [comment]
Hi, @praetorianer777 !

Could you provide with more information? When exactly does the message appear?

**Comment by praetorianer777** [comment]
Hello,

I get this message when I request the map from the world.

**Comment by sergi-e** [comment]
May I ask for a screenshot showing the terminal and the CARLA simulation running?

**Comment by praetorianer777** [comment]
The simulation is a custom map made with roadrunner, attached are the screenshots.

![georef_error](https://user-images.githubusercontent.com/6584303/80612177-e51fee00-8a3b-11ea-923d-a6e9e32bf452.JPG)
![simulator](https://user-images.githubusercontent.com/6584303/80612179-e5b88480-8a3b-11ea-9e0a-ddb25a47365a.JPG)

**Comment by germanros1987** [comment]
@praetorianer777 are you still having problems with this?

**Comment by praetorianer777** [comment]
Hello, no it seems fine now! Thanks

**Comment by patelchintan3112** [comment]
@praetorianer777 I am still facing this problem on Carla 0.9.11. How did you solve this problem?

**Comment by praetorianer777** [comment]
Hello, sorry this was long ago, I don't know how I did solve the issue :-/

**Comment by JoseZF** [comment]
i got the same warning when trying to create the navigation file for a custom map and when trying to run generate_traffic.py (only pedestrians) in the same map.
The function to get a random location from navigation returns None and therefore it cannot create a spawn point for pedestrians


![image](https://user-images.githubusercontent.com/103031956/184618554-6cd0e892-9bac-4560-a2e3-4977d6ee9670.png)

**Comment by bapukokare** [comment]
NEWS  direction not mentioned in open drive in file header description of xodr file respective map file
