### ISSUE TITLE
carla Ubuntu package already exists in newer Ubuntu versions (starting 19.04)

### ISSUE THREAD

**Issue by derFrickler** [carla-simulator/carla#2770]
In newer Ubuntu versions starting with 19.04 there is already a package named "carla" 
https://packages.ubuntu.com/de/disco/i386/carla

This makes it impossible to easily install the Carla debian packages from the repository as described in your documentation: https://carla.readthedocs.io/en/latest/start_quickstart/

Manually downloading the carla .deb and installing it via dpkg works, if the required packages are installed before. 

Maybe thing of renaming your package to sometging else like carla-simulator.

Thanks
       Johannes

**Comment by joel-mb** [comment]
Hi @derFrickler,
We have updated the package name to carla-simulator to avoid the conflict. We will change the documentation accordingly. Thank you for the information!
