### ISSUE TITLE
PTV-Vissim Co-simulation problem

### ISSUE THREAD

**Issue by kkyu725** [carla-simulator/carla#2777]
Hello
I'm trying to get running Carla in windows 10 and co-simulating with PTV-Vissim 11.00.
I have followed the instructions here: 
https://carla.readthedocs.io/en/latest/adv_ptv/

While I run the PTV -Vissim co-simulation, I got errors.
 "vissim type xxxxxx unknown. No vehicle will be spawned in carla" 

I find that vissim DS API always generate a new vehicle_id "0" when a vehicle drives across the link/connector but no vehicle spawned in vissim . That cause the set of vissim vehicle_ids be mess up. 

        num_vehicles = c_int(0)
        traffic_data = POINTER(VISSIM_Veh_Data)()
        self.ds_proxy.VISSIM_GetTrafficVehicles(byref(num_vehicles), byref(traffic_data))

        vehicles = {}
        for i in range(num_vehicles.value):
            vehicle_data = traffic_data[i]

            vehicles[vehicle_data.VehicleID] = VissimVehicle(
                vehicle_data.VehicleID, vehicle_data.VehicleType, vehicle_data.ModelFileName,
                vehicle_data.color,
                [vehicle_data.Position_X, vehicle_data.Position_Y, vehicle_data.Position_Z],
                [vehicle_data.Orient_Pitch, vehicle_data.Orient_Heading, 0.0], vehicle_data.Speed,
                vehicle_data.TurningIndicator)`

**Comment by jy723** [comment]
You can use vissim2020 and DrivingSimulatorProxy.dll,or change 
vissim_simulation.py class VISSIM_Veh_Data(Structure)

**Comment by joel-mb** [comment]
Hi @kkyu725, did the solution proposed by @jy723 solve your problem?
Thank you!

**Comment by kkyu725** [comment]
Yes, thanks so much~!

**Comment by AloneMusk** [comment]
@kkyu725 @jy723 what changes do we necessarily have to make to the VehData class in order to rectify this issue? Vissim 2020 seems to run smoothly but Vissim 2023 crashes whilst displaying the same error.

**Comment by firas-elhag** [comment]
@AloneMusk were you able to solve this error?
