### ISSUE TITLE
Which version of python is supported by Carla 0.9.8? Can i use python 3.7 with Carla 0.9.8?

### ISSUE THREAD

**Issue by praveenputhettu** [carla-simulator/carla#2780]

**Comment by pperle** [comment]
Yes a simple `easy_install carla/dist/carla-0.9.8-py3.5-linux-x86_64.egg` should do the trick **this is the command for version 0.9.8 on linux**.

After this, you can remove the part where it looks for the egg file.
https://github.com/carla-simulator/carla/blob/3fcc90585e1dd0feae584dddc0918f4849905ebb/PythonAPI/examples/tutorial.py#L13-L19

**Comment by praveenputhettu** [comment]
Thank you pperle
