### ISSUE TITLE
Feature request: Simulate the dynamic impact of wind on vehicles

### ISSUE THREAD

**Issue by severin-lemaignan** [carla-simulator/carla#2796]
Currently (carla 0.9.8), wind can be simulated, but only impact rain and foliage (parameter `wind_intensity` of `carla.WeatherParameters`.

It would be great to be able to model as well the impact of wind on vehicles (this is for instance important in one of our use-case where we cross a windy bridge).
As a first approximation, wind could be modelled as a lateral force on the vehicle, taking only into account the cross-section of the vehicle facing the wind direction.

**Comment by germanros1987** [comment]
Added to feature requests.
