### ISSUE TITLE
Listen to two sensors separately

### ISSUE THREAD

**Issue by AmirHarvey** [carla-simulator/carla#2798]
Hello there,
This is a part of the manual control code. I added those two lines and i can display them using tab button. What i am trying to do is to display them on two separate windows using numpy and opencv. So can i listen to those two lines separately?

I am using:
carla 0.9.8
python 3.7
os: windows

![sensors](https://user-images.githubusercontent.com/62814282/80533628-39749080-899e-11ea-89ff-d5dcd34f9e54.PNG)

**Comment by kevinmgamboa** [comment]
Hi @AmirHarvey so what did u do ? I sm trying the same .. please share
