### ISSUE TITLE
Carla crashing on Wubi-Ubuntu 16.04

### ISSUE THREAD

**Issue by prshnthrv** [carla-simulator/carla#28]
Hi, I tried to follow the instructions to run Carla as given by untarring the CARLA_0.6.0.tar.gz. However, it is crashing. I have attached the crash logs generated. Could you please let me know what I am missing?

I am using Wubi-Ubuntu 16.04 on my Windows machine. 
[CarlaUE4.log](https://github.com/carla-simulator/carla/files/1478709/CarlaUE4.log)
[Diagnostics.txt](https://github.com/carla-simulator/carla/files/1478710/Diagnostics.txt)

**Comment by nsubiron** [comment]
It looks like an incompatibility with your graphics device. Unreal is very unlikely to work on Wubi-Ubuntu. It normally doesn't work on virtual machines either. You may try to download and build Unreal Engine on Wubi and see if it starts, if so, you can probably compile CARLA from source. But I would recommend to get a machine with Ubuntu 16.04 installed to save you trouble and get better performance.
