### ISSUE TITLE
Create a new map or Map customization

### ISSUE THREAD

**Issue by EugenM121** [carla-simulator/carla#2805]
Hallo Carla,
I see a lot of such questions, but can not find an answer. My carla vesion is 0.9.8, My OS- Win10. Now I want to create a new map. But i can not get RoadRunner(wait about two weeks).

Is it possible to create a new map in CARLA using an Unreal Engine without using Roadrunner??? If it is possible, are instrucktions the same??

I want to customize existing maps. I need to remove every thing from the map except roads and grounds fro spawning vehicles. I went through https://carla.readthedocs.io/map_customization/ this but couldn't get this. Can you maybe write a small example?

Thank you)

**Comment by germanros1987** [comment]
@EugenM121 as long as you are able to provide an OpenDRIVE file along with your FBXs the CARLA simulator will be able to ingest it. Do you have a way to create an OpenDRIVE file that represents your map?

I guess the answer is "no". 

We should probably provide a tool in UE4 to produce/edit basic OpenDRIVEs... @XGodina @marcgpuig ?

**Comment by zhoushiyang12** [comment]
Hallo Carla,
I fllowed the Tutorials  https://carla.readthedocs.io/en/latest/tuto_A_add_map/
but when 

./build.sh map_file # map_file has no extension

I encounter "Limited Authority"  problem. So i  execute " source ./build.sh map_file",  but stil  encounter a problem like this :

XODR file doesn't exist, ignoring crosswalks from openDRIVE
Loading...
zsh: segmentation fault (core dumped)  ./RecastBuilder "$1.obj"

what's wrong? could you help me.

**Comment by germanros1987** [comment]
@bernatx could you please follow up on this?

**Comment by MichaelKlin** [comment]
Hi @germanros1987 i use unreal engine 4 to change your map und create new map. I have a small question. Can i add my Map in Release on Carla??
