### ISSUE TITLE
[Windows] project stoppts to load or fails to launch after build

### ISSUE THREAD

**Issue by MichaelKlin** [carla-simulator/carla#2806]
I followed all the instructions at "how_to_build_on_windows/ " very very closely.
I am trying to build Carla 0.9.9 (latest) with "make launch" using unreal 4.22.2 and Visual Studios 17.
I have all prerequisites installed (make, git, python 3.6 (x64)).
I am using the x64 Native Tool Command Prompt for Visual Studios 2017
The build itself is completed successfully, but when opening the project with the unreal editor I receive the message

![Fehlermeldung](https://user-images.githubusercontent.com/64699335/80869744-860fe280-8ca2-11ea-8e35-3ded02213d03.png)
![fehlermeldung2](https://user-images.githubusercontent.com/64699335/80869762-9d4ed000-8ca2-11ea-825f-95af138dfb5c.png)

If Editor opens, i can not see maps and other. What should i do??
Thanks you

**Comment by MichaelKlin** [comment]
Resolved

**Comment by VincentDupontAB** [comment]
Could you describe what was your process to resolve this issue?

**Comment by MichaelKlin** [comment]
@VincentDupontAB there were so many mistakes. I forget, what I have done. But i am sure, that in my projeckt was not such files like  ../static/road/.. . And i downloaded new project-zip file. And founded that files. and added to my projeckt
