### ISSUE TITLE
Missing Semantic Segmentation labels in OpenDrive generated maps

### ISSUE THREAD

**Issue by FrancescoPinto** [carla-simulator/carla#2807]
Hi,
I'm writing to point out that the semantic segmentation is not working properly with maps generated from .xodr files (Carla 0.9.9 in Ubuntu 18.04). Indeed, the road/sidewalks labels are not assigned to the road/sidewalks mesh (while they are to other objects). I guess a potential workaround could be to modify the Tagger.cpp TagActor method, however I can't figure out what's the component tree of the procedurally generated meshes.

**Comment by germanros1987** [comment]
@marcgpuig @Axel1092 this issue has your name on it.

**Comment by marcgpuig** [comment]
Hi @FrancescoPinto, this is in our roadmap and it will be addressed soon! Hopefully for the next release `0.9.10` or `0.9.11`. We also need to investigate how to properly do it, so if you make some progress make sure to report it here, it will be helpful, thanks!

**Comment by FrancescoPinto** [comment]
Hi @marcgpuig , I implemented a temporary fix in this [branch](https://github.com/FrancescoPinto/carla.git)

**Comment by marcgpuig** [comment]
That's great! We will take a look at your fork when we push for it. Thanks!
