### ISSUE TITLE
COOKED content error in Carla 0.9.9 on windows

### ISSUE THREAD

**Issue by MichaelKlin** [carla-simulator/carla#2808]
I have installed UnrealEngine_4.24 and Carla 0.9.9 on my Windows 10 system. During make I did not got any error. When I run "\carla\Unreal\CarlaUE4\Binaries\Win64\CarlaUE.exe" I got below error:-
The global shader cache file 'Program Files/Epic Games/UnrealEngine_4.24/Engine/GlobalShaderCache-PCD3D_SM5.bin' is missing.
Your application is built to load COOKED content. No COOKED content was found; This usually means you did not cook content for this build.
It also may indicate missing cooked data for a shared plateform(e.g., OpenGL under Windows): Make sure your platform's packaging settings include this Targeted RHI.

Alternatively build and run the UNCOOKED version instead.

Please let me know what needs to be done in this. @sergi-e
Thanks for helping!

**Comment by superying** [comment]
I have the same issue. Any solution?

**Comment by convenite** [comment]
It seems a common issue with Unreal Engine. Now I'm reading 
"https://forums.unrealengine.com/development-discussion/c-gameplay-programming/2105-globalshadercache-pc3d_sm5-bin-is-missing"

**Comment by germanros1987** [comment]
@sergi-e could you provide guidance on this issue and probably update the documentation?

**Comment by sergi-e** [comment]
Hi, @MichaelKlin! 

It would be great to know a bit more about how did you made the build. 
Did you downloaded the assets that appear in: `\Util\ContentVersions.txt`? If not, do so and extract them in `Unreal\CarlaUE4\Content\Carla`.

**Comment by EsquilliDev** [comment]
I'm having the same issues and yes, I have downloaded and extracted the assets to that folder.

**Comment by delenius** [comment]
I am also seeing this issue when running with the `-opengl3` flag, in a Linux VM/Mac OS host (I cannot run OpenGL 4 in this configuration), using the tar.gz bundle, release 0.9.9. This appears to be the same problem as #1253.

**Comment by zjzjg1280** [comment]
Has anyone solved this problem?
