### ISSUE TITLE
Controlling Pedestrian Traveling Path

### ISSUE THREAD

**Issue by KasraMokhtari2112** [carla-simulator/carla#2816]
Hi everyone! I have one question regarding pedestrians' traveling path. Should I use carla.WalkerControl for controlling the pedestrian? In this code,  "./manual_control.py --filter=walker",  carla.WalkerControl  is used to control the pedestrian. However,  in "spawn_npc.py" code the go_to_location  command is used to control their traveling path. What are the differences? 

As of now, I am using the same API as "spawn_npc.py" and give a pedestrian a specific target but the problem is that the pedestrian is not going exactly to that point. Does anyone know how I can make the controller more robust? Thanks a lot.

**Comment by germanros1987** [comment]
@KasraMokhtari2112 the pedestrian will go to that point if it's possible. It will try to find a way. If you want to have full control of the path, then you should use carla.WalkerControl.

@bernatx do you have anything to add?

**Comment by bernatx** [comment]
Hi,
We have two controllers to be applied to pedestrians:
- **WalkerController**: this is to manage the pedestrian as a vehicle in manual control. You can define the direction and speed to move, and also you can jump. This is used in the **manual_control.py** script.

- **WalkerAIController**: this is to manage the pedestrian to move automatically without user intervention and going to random locations in sequence. It is fine to populate the map. This is used with the **spawn_npc.py** script.

**Comment by chirudeep001** [comment]
@germanros1987 @bernatx  Can we also use WalkerAIController to trigger the walker when the vehcile reaches certain loctiaon.
Usually, for scenario generation. Does it work??
