### ISSUE TITLE
Stop lines locations

### ISSUE THREAD

**Issue by MohamedDaoud1** [carla-simulator/carla#2821]
Is there a way to get stop lines locations on the map like waypoints? 
I'm trying to know intersections locations so I can command the car to stop properly.

**Comment by germanros1987** [comment]
You can retrieve the stopping volume-boxes using the API. @glopezdiest could you provide a brief code example?

**Comment by glopezdiest** [comment]
Hey @MohamedDaoud1. Unfortunately no, there is no way to get the stop lines. The only thing that comes close to it is to get the last waypoint that is part of the road before the intersection starts. Here is an example code of how you'd do it ([traffic_waypoints.zip](https://github.com/carla-simulator/carla/files/4835695/traffic_waypoints.zip))

What this does is
1) Get all the traffic lights and stops
2) Get the trigger volume of the traffic light.
3) Separate it into points to get all the waypoints of the affected lanes
4) Move all the waypoints forward until an intersection is found.
5) Plot the waypoints and store them in a list

This is sometimes good, but depending on the intersection, this might not be accurate. For example, at Town03, the interior part is good, but the exterior fails to mark the stop lines.

![image](https://user-images.githubusercontent.com/58212725/85834925-81444800-b794-11ea-8be6-474e4a280b0e.png)

![image](https://user-images.githubusercontent.com/58212725/85834857-5eb22f00-b794-11ea-9c1f-26b969e45ae1.png)

**Comment by Khatere1373** [comment]
> Hey @MohamedDaoud1. Unfortunately no, there is no way to get the stop lines. The only thing that comes close to it is to get the last waypoint that is part of the road before the intersection starts. Here is an example code of how you'd do it ([traffic_waypoints.zip](https://github.com/carla-simulator/carla/files/4835695/traffic_waypoints.zip))
> 
> What this does is
> 
> 1. Get all the traffic lights and stops
> 2. Get the trigger volume of the traffic light.
> 3. Separate it into points to get all the waypoints of the affected lanes
> 4. Move all the waypoints forward until an intersection is found.
> 5. Plot the waypoints and store them in a list
> 
> This is sometimes good, but depending on the intersection, this might not be accurate. For example, at Town03, the interior part is good, but the exterior fails to mark the stop lines.
> 
> ![image](https://user-images.githubusercontent.com/58212725/85834925-81444800-b794-11ea-8be6-474e4a280b0e.png)
> 
> ![image](https://user-images.githubusercontent.com/58212725/85834857-5eb22f00-b794-11ea-9c1f-26b969e45ae1.png)

Hi, how can I get the location of each intersection on Carla map ?
