### ISSUE TITLE
Unexpected behavior with zero distortion at semantic segmentation and depth sensors

### ISSUE THREAD

**Issue by Sid1057** [carla-simulator/carla#2822]
Hello!

When in synchronous mode I set the distortion to zero for semantic segmentation and camera depth, I get a too strange result:
```
        self.bp.set_attribute('lens_k', str(0.0))
        self.bp.set_attribute('lens_circle_falloff', str(0.0))
```
BGR:
![rgb741354](https://user-images.githubusercontent.com/12153757/81176619-0dfd3180-8fae-11ea-9f33-1b4e8a06ede6.png)

Depth (BGR):
![depth741354](https://user-images.githubusercontent.com/12153757/81176654-1d7c7a80-8fae-11ea-9fc3-f15ca6c2a25c.png)

Semantic (cityscapes):
![sem741354](https://user-images.githubusercontent.com/12153757/81176660-1fded480-8fae-11ea-976e-ef914efe424f.png)

But if I try to set the distortion too small, but not zero:
```
        self.bp.set_attribute('lens_k', str(0.000001))
        self.bp.set_attribute('lens_circle_falloff', str(0.000001))
```
BGR:
![rgb728837](https://user-images.githubusercontent.com/12153757/81176432-d1313a80-8fad-11ea-93d4-e686cde0705a.png)
Depth (BGR):
![depth728837](https://user-images.githubusercontent.com/12153757/81176515-ead28200-8fad-11ea-969d-5695bc2a003c.png)

Semantic (cityscapes):
![sem728837](https://user-images.githubusercontent.com/12153757/81176486-e312dd80-8fad-11ea-843a-864f91202a45.png)

As you can see, color camera frames are ok in both cases, but something happens with another sensors.

Ubuntu 18.04; Carla 0.9.9 compiled release

**Comment by germanros1987** [comment]
@marcgpuig could you look into this?

**Comment by marcgpuig** [comment]
Hi @Sid1057, sorry for the late response.
I've tested it and it works as expected for me, and this
```py
self.bp.set_attribute('lens_k', str(0.0))
self.bp.set_attribute('lens_circle_falloff', str(0.0))
```
provides me with this single color screen in RGB, Sem seg, and depth that you reported (which is the expected output for these values).
If you want to _deactivate_ the effect, please consider setting the values to the default ones that you can find in our [documentation](https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera).
Yet another way to find these default values is using the `carla.ActorAttribute.recommended_values` where you can find a list of recommended values for the sensor, in this case, I set the default values as a recommended values so you will always find them there.
An example, getting the default value:
```py
self.bp.get_attribute('lens_circle_multiplier').recommended_values[0]
```

**Comment by marcgpuig** [comment]
Hi @Sid1057, sorry for the late response.
I've tested it and it works as expected for me, and this
```py
self.bp.set_attribute('lens_k', str(0.0))
self.bp.set_attribute('lens_circle_falloff', str(0.0))
```
provides me with this single color screen in RGB, Sem seg, and depth that you reported (which is the expected output for these values).
If you want to _deactivate_ the effect, please consider setting the values to the **actual** default ones that you can find in our [documentation](https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera).
Yet another way to find these default values is using the `carla.ActorAttribute.recommended_values` where you can find a list of recommended values for the sensor, in this case, I set the default values as a recommended values so you will always find them there.
An example, getting the default value:
```py
self.bp.get_attribute('lens_circle_falloff').recommended_values[0]
```
