### ISSUE TITLE
How to get distance (along the road) between two locations in CARLA?

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#2832]
I was working on a TSP problem and wanted to use CARLA's maps for my problem set.
However, I cannot find any API that can give me the distance between two locations (along the road) (not just the straight line euclidean distance).

Does any one have any idea how this can be done? Or maybe I am missing something?

I was trying to implement shortest path algorithm on the map topology, however, map topology itself doesn't provide distance between two nodes along the road.

**Comment by jackbart94** [comment]
Hi,

To do this, you need to get the nearest waypoint to both locations and then develop a heuristic to get the shortest path. There's an example in PythonAPI/agents/global_route_planner.py for our own agents, you can take a look at that. It basically builds a networkx graph from the map topology.

Let me know if this helps you!
