### ISSUE TITLE
ERROR: Spawn failed because of collision at spawn position

### ISSUE THREAD

**Issue by dustyujanin** [carla-simulator/carla#2835]
Hello.
I install 0.9.9 version
When trying to run python3 spawn_npc.py

Error:
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
spawned 80 vehicles and 33 walkers, press Ctrl+C to exit.

**Comment by jackbart94** [comment]
Hi,

This message is just a warning that either some vehicles or some walkers (in this case it's probably walkers) haven't spawned because the random location is too near to one of another walker.

So basically, nothing to worry about.

**Comment by adrigrillo** [comment]
How many vehicles are you trying to spawn at once? For me it seems, that you are trying to spawn more vehicles that spawn points are in the map.
