### ISSUE TITLE
Carla cv2.imshow() not working : white screen

### ISSUE THREAD

**Issue by dustyujanin** [carla-simulator/carla#2841]
Hello.
I'm trying to run this code: https://pastebin.com/wFM0z1vj
Carla 0.9.9
But cv2.imshow now working. I see only white screen
![image](https://user-images.githubusercontent.com/13289476/81565188-a413cc00-93a1-11ea-94a3-58d7ce00d585.png)

**Comment by pirate-lofy** [comment]
It might be irrelevant to Calra, but can u try 
    ```
    cv2.imshow("", i3)
    if cv2.waitKey(1)&0xFF==27:
        pass
```

**Comment by dustyujanin** [comment]
Still not working:(
![image](https://user-images.githubusercontent.com/13289476/81691096-f4079700-9464-11ea-8e6d-53f20669e107.png)
![image](https://user-images.githubusercontent.com/13289476/81691121-fd90ff00-9464-11ea-92bb-487699f5524e.png)

**Comment by wendersonj** [comment]
same here

**Comment by Hamptonjc** [comment]
I'm having this issue as well!

**Comment by wendersonj** [comment]
I don't have the code right now, but using some other code I had troubles with threads ! Even using a thread worker to do a secondary job, I can't display using either OpenCV or Matplotlib. I'm currently using PyGame, that comes with the basics scripts, but it's more difficult to use.

**Comment by GRFreire** [comment]
same here, did you found something?

**Comment by germanros1987** [comment]
This is not a CARLA issue. This refers to OpenCV usage.

**Comment by akssieg** [comment]
I am following the similar code from `https://pythonprogramming.net/control-camera-sensor-self-driving-autonomous-cars-carla-python/?completed=/introduction-self-driving-autonomous-cars-carla-python/`, opencv imshow shows a blank screen and If I try to do imwrite then the files are empty. Has anybody found solution for this problem?

**Comment by germanros1987** [comment]
Please, use forum.carla.org for this kind of questions, which are not "purely" about CARLA.
