### ISSUE TITLE
Tuning vehicle dynamics parameters of a new vehicle generated in Unreal Engine

### ISSUE THREAD

**Issue by daydin41** [carla-simulator/carla#2847]
Hi, 

We are creating our custom truck vehicle model in UE4 and importing it to CARLA. The tutorial https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/ specifies steps for CARLA import as well as some parameters for vehicle dynamics from blueprint. Are we limited to the vehicle dynamics parameters given in this tutorial? Can furher tuning be done in blueprint?

The built in vehicles seems to use UE4 vehicle's physics (based on PhysX vehicles). If the parameters in PhysX plugin is tuned in UE4 (using the guide: https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/Vehicles.html#tuning-guide) can these parameters be imported to CARLA?

Thanks,

**Comment by germanros1987** [comment]
@bernatx could you follow up on this?

**Comment by bernatx** [comment]
Hi, because we are starting to integrate vehicle dynamics into CARLA we will check how many of those parameters we can expose to CARLA. Some of those properties are related to art resources (like the wheels size), so it seems to be a complex addition. But we have the focus on it.

**Comment by yyab** [comment]
> Hi, because we are starting to integrate vehicle dynamics into CARLA we will check how many of those parameters we can expose to CARLA. Some of those properties are related to art resources (like the wheels size), so it seems to be a complex addition. But we have the focus on it.

Hi! Could you give some information on the integrated vehicle dynamics in Carla? Will that appear in the next Carla release? Are there going to a Pacejka tire model rather than the default tire model in the PhsicX? Thank you!

**Comment by bernatx** [comment]
We are working on Carsim integration, but it is not ready for the next release.

**Comment by yyab** [comment]
> We are working on Carsim integration, but it is not ready for the next release.

Thank you for your reply! But since Carsim is a licensed product, to use Carsim in Carla we will have to by Carsim license, right? Are there any open-source way to implement more realistic tire model in Carla?

**Comment by jimaldon** [comment]
@yyab What would be an open-source alternative to a physics engine for simulating vehicle dynamics like CarSim?
