### ISSUE TITLE
Traffic Signal made by RoadRunner is available?

### ISSUE THREAD

**Issue by MingooJ** [carla-simulator/carla#2854]
Hi, I'm using Carla for fun.

I am interested in road traffic and make some road.
But after 'road.fbx and road.xodr' import to carla well, no car stop to my traffic signals.

How can i stop the autopilot car at traffic light?

Thank you in advance.
![option1](https://user-images.githubusercontent.com/58928361/81938445-e3574c80-962f-11ea-933a-f6dde26ee111.png)
![option2](https://user-images.githubusercontent.com/58928361/81938454-e5b9a680-962f-11ea-92eb-09a13a6ce748.png)
![option3](https://user-images.githubusercontent.com/58928361/81938748-5496ff80-9630-11ea-9396-fdf9895d04dc.png)

**Comment by Mkarami3** [comment]
Hi MingooJ,
Did you manage to solve this issue? I have the same problem. Thanks

**Comment by MingooJ** [comment]
Hi Mkarami3,
Unfortunately, this problem still unsolved. but, i generate traffic light of UE4, it works. 
However, complex traffic can't create with it's traffic system. So, i still try solving it.
Thanks.

**Comment by germanros1987** [comment]
@MingooJ please provide further information. Which version of CARLA are you using? OS? etc.

@XGodina could you help with this?

**Comment by MingooJ** [comment]
Hi, @germanros1987 

I used CARLA 9.8 in Ubuntu18.04 and made map using RoadRunner.
I made a traffic light on the roadrunner, but it doesn't seem to work on the CARLA.
And my roadrunner was a trial version, so I can't do anything right now.

I wish it could be of help someone's help.

Thanks.

**Comment by germanros1987** [comment]
@MingooJ you need to use 0.9.9 to be able to ingest traffic lights automatically from OpenDRIVE (generated by RoadRunner). Then, you need to cook the contents using the docker provided by CARLA. 

@bernatx @sergi-e could you please add more details so that @MingooJ can have a smooth journey?

**Comment by sergi-e** [comment]
Hi, @MingooJ ! 
Indeed, the automatic ingestion of landmarks was added by CARLA 0.9.9. If you [download package 0.9.9](https://github.com/carla-simulator/carla/releases) and follow [this tutorial](https://carla.readthedocs.io/en/latest/tuto_A_add_map/#map-ingestion-in-a-carla-package) to add the map, you should be able to run your custom map in CARLA with traffic lights in it.
