### ISSUE TITLE
Playability - delay between actions and rendering

### ISSUE THREAD

**Issue by OlivierDelbeke** [carla-simulator/carla#2856]
I am investigating how to make Carla more playable (for example, I want to make it easier to stay within your driving lane). The first thing I want to do is to measure the delay between the frame creation (by UnrealEngine), and the moment when the frame is drawn (pygame.display.flip()). As the frames have a timestamp attribute, I assumed that this would be straightforward, but I see that this timestamp is relative to the creation of the Episode and not an absolute system clock value. Is there a way to know precisely when the Episode was created ? Or to measure the serialization time, RPC time, deserialization time, and finally the numpy conversion time. (By the way, in order to bypass the frame transmission, I also tried to "play in the world view" by changing the spectator's position at every frame using the hero's camera transform, but the result is very bad - is there a way to do that (rendering in the server only) ?) Thx.

**Comment by germanros1987** [comment]
@bernatx could you provide a simple mechanism to perform this action?
