### ISSUE TITLE
Running Carla on Google Colab

### ISSUE THREAD

**Issue by prateekstark** [carla-simulator/carla#2861]
Hi,
Is there a way to run Carla on Google Colab?

**Comment by khojir** [comment]
Hi,
There is a similar issue: [https://github.com/carla-simulator/carla/issues/2567](https://github.com/carla-simulator/carla/issues/2567)
I haven't tested it yet, But I think it'll work.

**Comment by Horcrux1** [comment]
The simulator itself runs in google colab through TurboVNC. However, I do not know how to set up a client in this situation.

```
# initiate the connection 
                self.client = carla.Client("localhost", 2000)

```

I get a tracebck. Anyone knows what to do?
