### ISSUE TITLE
semantic segmentation does not work properly on props ingestion- version 0.9.8 linux from source

### ISSUE THREAD

**Issue by omrizen** [carla-simulator/carla#2866]
Hello
working on carla release 0.9.8 on linux from source
after prop ingestion (using json file with tag e.g. -  {  
  "maps": [
  ],"props": [
    {      "name": "MyProp01",      "size": "big",      "source": "./props/prop01/prop01.fbx",      "tag": "Vehicles"} ]} )
the image that I get with semantic segmentation sensor colores the object in black (so my tag has no effect). 
I found out the "render custom" is disabled on  my prop after start playing , comparing to other constant actors in the scene,  so perhaps this should be fixed

Thanks

**Comment by germanros1987** [comment]
Did you try with 0.9.9? Any differences?

**Comment by Jabkowsky** [comment]
I have similar issue on 0.9.9 version
See: https://github.com/carla-simulator/carla/issues/3070
