### ISSUE TITLE
get_local_planner is not found in behavior_agent

### ISSUE THREAD

**Issue by Deio828** [carla-simulator/carla#2867]
Hi, I'm trying to use the behavior agent but when I run the automatic_control.py it gives me this error message:
`BehaviorAgent ovject has no attribute 'get_local_planner`' 
if you have added it please I need it to complete my project.
Thank you.

**Comment by jackbart94** [comment]
Hello,

Which version of CARLA are you using? How are you running ``automatic_control.py`` exactly?

**Comment by Deio828** [comment]
I am using Carla0.9.6, and I'm running the `automatic_control.py` you've implemented with the default arguments

I've tried to add this method to the `behavior_agent.py` and it actually worked. 
`def get_local_planner(self):
        return self.local_planner`

**Comment by jackbart94** [comment]
Yeah, if you are getting a script from a version after 0.9.6 make sure to import all the dependencies, because some of the stuff might've been changed.
