### ISSUE TITLE
Inverse Prespective Mapping for CARLA images 

### ISSUE THREAD

**Issue by cyndwith** [carla-simulator/carla#2869]
I'm trying to get inverse perspective mapping for some of the images I have taken from CARLA.
I tried to crop the images I have into (IMG_SIZE, IMG_SIZE) from the center to void any significant changes to camera parameters.

Data I have: image from camera and camera parameters (fov, focal lenght, principle point, rotation angles (pitch, yaw, roll, camera_height etc)
  
  IMG_SIZE = 420
  fx = IMG_SIZE /(2 * tan(params['fov'] * PI / 360))
  px = IMG_SIZE / 2
  py = IMG_SIZE / 2
  K  = [fx,  0,  px]
          [ 0, fx,  py]
          [ 0,  0,    1]
  Rx = rotationMatrix(pitch, 0) # along x-axis
  Ry = rotationMatrix(yaw, 1)  # along y-axis
  Rz = rotationMatrix(roll, 2)   # along z-axis
  
  R = Rz * Ry * Rx
  cz = params['camera_height']  # specified in meters
  C = ( 0, 0, -cz) # assuming z= 0 plane is the road / ground 
  t = - R * C
 
  Rt = [R[0,0], R[0,1],   t[0]],
          [R[1,0], R[1,1],   t[1]],
          [R[2,0], R[2,1],   t[2]]])
  P = K * Rt
  Pinv = inv(P)
  scaling for better resolution
  sx, sy = 10, 10
  Tscale = ([sx,  0,  0]
                 [ 0, sy,  0]
                 [ 0,  0,  1])
  Hscale = Tscale * Pinv 
  calculate transformation of the four corners of the image
  xmin, xmax, ymin, ymax = compute_corners(image, Hscale)
  width  = int(xmax - xmin) 
  height = int(ymax - ymin) 
  tx = -xmin 
  ty = (height - ymax)
  T = [[ 1,  0, tx],
         [ 0,  1, ty],
         [ 0,  0,  1]])
  Htrans = T * Hscale
  image_ipm = cv2.warpPerspective(image, Htrans, (width, height))

The results for IPM or after homography are distorted as shonw in attached images

![image](https://user-images.githubusercontent.com/11755434/82389613-8376f200-99f1-11ea-9a44-c3d89bc1ad81.png)

@marcgpuig 

What am I missing, I see some discussion on correcting for orientation, but I feel the rotation angles are as expected.

**Comment by germanros1987** [comment]
@cyndwith this seems to be not strictly related to CARLA. Your question could be rephrased as to "what is wrong in my coordinate system?" Help me with this CV function.

Please, take this to the CARLA forum to see if you get help from other users. That seems to be the right place. Let's keep github mainly for bugs and feature requests.
