### ISSUE TITLE
sensor.other.imu not found

### ISSUE THREAD

**Issue by a4zhangfei** [carla-simulator/carla#2870]
There is no sensor in my blueprint :sensor.other.imu and sensor.other.radar
`len(bp.filters('sensor.other.*')` is 4

**Comment by germanros1987** [comment]
Could you provide some information...? Version of CARLA, OS, etc..?

**Comment by a4zhangfei** [comment]
> Could you provide some information...? Version of CARLA, OS, etc..?

OS : `ubuntu 18.04`
Version of CARLA: `0.9.6 release`
The version I use is not compiled. But many methods and properties are missing. For example, `waypoint`'s method `previous_ until_ lane_ start`，`sensor.other.imu`

**Comment by germanros1987** [comment]
IMU and RADAR were not available in 0.9.6. They were introduced in more recent versions of CARLA. I would recommend you to upgrade to 0.9.9.
