### ISSUE TITLE
Certainty of pedestrian detection

### ISSUE THREAD

**Issue by AkramKalaee** [carla-simulator/carla#2873]
Hello Carla Team,

Does the perception module of Carla provide the percentage value indicating the probability that the detected object is a pedestrian?

- OS: win10
- CARLA Version: CARLA 0.9.9
- Python version: 3.7
- Version: 0.9.9

**Comment by germanros1987** [comment]
@AkramKalaee what perception module? CARLA is a simulator, not a perception stack. CARLA doesn't do any perception for you.

**Comment by AkramKalaee** [comment]
I mean, how does Carla avoid the collision with pedestrians?
