### ISSUE TITLE
IMU sensor got NaN

### ISSUE THREAD

**Issue by emailweixu** [carla-simulator/carla#2874]
Very occasionally, the IMU sensor gets nan for compass value. Is this expected or some bug? I thought it might be caused by bad orientation of the sensor (facing upward). But at the time as getting nan, it  seems normal:

pitch:0.032498039305210114
roll:1.3824284076690674
yaw:90.67381286621094

I am using carla 0.9.9 on ubuntu 18.04.

**Comment by germanros1987** [comment]
@marcgpuig could you please look into this?

**Comment by marcgpuig** [comment]
@emailweixu I'm not able to reproduce this, can you provide more information? Are you working on sync / async? Cold you provide the script that you are using to get this unexpected behavior?
