### ISSUE TITLE
Help! I can not get full LiDAR points in one frame of data

### ISSUE THREAD

**Issue by Charlie-lusie** [carla-simulator/carla#2886]
As shown in figure below, I set the LiDAR sensor config correctly:
```
		sensors_bp['lidar']=[blueprint.find('sensor.lidar.ray_cast'),carla.Location(x=1.0,z=4.0)]
		sensors_bp['lidar'][0].set_attribute('rotation_frequency','10')
		sensors_bp['lidar'][0].set_attribute('channels','16')

```
But I can't get full points at once. It looks like data is generated in half of a full circle:
![Screenshot from 2020-05-25 21-49-03](https://user-images.githubusercontent.com/10813880/82818683-a9106980-9ed1-11ea-8194-af4cf22732ba.png)

**Comment by germanros1987** [comment]
@joel-mb @fpasch could this be a problem in our interface with rviz?

**Comment by fpasch** [comment]
@Charlie-lusie Please ensure, that the rotation frequency equals the fixed_delta_seconds specified in carla_ros_bridge.

**Comment by Charlie-lusie** [comment]
> @Charlie-lusie Please ensure, that the rotation frequency equals the fixed_delta_seconds specified in carla_ros_bridge.

I set the rotation frequency = 10Hz, and all params in carla_ros_bridge is default. But I fixed the problem by running: python config.py --fps=10

**Comment by germanros1987** [comment]
@sergi-e before closing this issue, could you reflect this in the documentation, please?
