### ISSUE TITLE
ScanUnregisteredVehicles ignores vehicle orientation

### ISSUE THREAD

**Issue by BenAscent** [carla-simulator/carla#2889]
The `ScanUnregisteredVehicles` computes the four corner of the bounding shape of the vehicle its scanning, however it does not apply the current orientation of said vehicle, making those four points always oriented in the same direction. These points are used to find nearby waypoints, and while the difference is not large, it could lead to discrepancies between collision checks at different orientation.

The problem can be easily observed by drawing those 4 points in the loop that iterates on them:
```
          for (cg::Location &vertex: corners) {
            debug_helper.DrawPoint(vertex, 0.2f, {255, 255, 0}, 0.1f, false);
```
They won't follow the orientation of the car when it is turning.

A possible fix is to replace this:
```
          float bx = extent.x;
          float by = extent.y;
          std::vector<cg::Location> corners = {location + cg::Location(bx, by, 0.0f),
                                               location + cg::Location(-bx, by, 0.0f),
                                               location + cg::Location(bx, -by, 0.0f),
                                               location + cg::Location(-bx, -by, 0.0f)};
```

with this:

```
          cg::Location bx = vehicle_ptr->GetTransform().GetForwardVector() * extent.x;
          cg::Location by = vehicle_ptr->GetTransform().GetRightVector() * extent.y;
          std::vector<cg::Location> corners = {location + bx + by,
                                               location - bx + by,
                                               location + bx - by,
                                               location - bx - by};
```

**Comment by jackbart94** [comment]
Hi,

Sorry for answering so late, we took note of this suggestion and it was really appreciated. We recently changed the structure of Traffic Manager and applied this change too, thanks!
