### ISSUE TITLE
Changing the weather using a python client

### ISSUE THREAD

**Issue by natanielruiz** [carla-simulator/carla#289]
Is there any way to change the weather using a python client?

Thanks a lot!

**Comment by marcgpuig** [comment]
Hi @natanielruiz,

Sure!
You can change the weather and every carla setting that appear on [`CarlaSettings.ini`](https://github.com/carla-simulator/carla/blob/master/Docs/Example.CarlaSettings.ini).

Please take a look at the [`client_example.py`](https://github.com/carla-simulator/carla/blob/master/PythonClient/client_example.py)
https://github.com/carla-simulator/carla/blob/bb3e66d4421fdedc388b7a456fd9f86cf7bf18e3/PythonClient/client_example.py#L43-L53

**Comment by natanielruiz** [comment]
Yes I understand. Would it work if I set the settings to something different (thus changing the weather) while the game is playing?

**Comment by marcgpuig** [comment]
Well @natanielruiz, this is not currently possible without a "reset".

Anyway, if what you are aiming for is to change the weather each frame, a workaround could be making a blueprint in the editor that does exactly that, from the simulator itself.

Please, give us more details and we'll try our best to solve your problem :)

**Comment by marcgpuig** [comment]
@natanielruiz awesome! :open_mouth:

Maybe you could share your solution so people with similar issues can use it!
Regards.

**Comment by mhusseinsh** [comment]
@natanielruiz could you please clarify on how did you do that ? I want also to change the weather each frame using the python client, instead of pressing the C button

@marcgpuig any idea ?

**Comment by chase03** [comment]
Is possible changing weather parameters in Unreal Engine editor via widget slider? I can't find any interface
