### ISSUE TITLE
A Question about OpenDrive

### ISSUE THREAD

**Issue by lp249839965** [carla-simulator/carla#2890]
The RoadInfoLaneOffset element stores in Road according to 
https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/road/MapBuilder.cpp#L409
But it get from Lane in according to this code 
https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/road/Lane.cpp#L79

**Comment by germanros1987** [comment]
Could you formulate your question and perhaps elaborate a bit more?

**Comment by Axel1092** [comment]
Hi @lp249839965,
The RoadInfoLaneOffset is in a temporary container in https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/road/MapBuilder.cpp, which is then moved to the Lane object. Can you explain what problems are you having?

**Comment by germanros1987** [comment]
@lp249839965 are you still interested in this issue?
