### ISSUE TITLE
Lane Change (Wrong Flag?)

### ISSUE THREAD

**Issue by kbu9299** [carla-simulator/carla#2893]
Hi Carla teams,

I am testing the lane change of NPCs through `force_lane_change`. According to your manual, `True` for "Left" and `False` for "Right" but I observe that it works the way around in my experiment. 
I am wondering if my experiment is wrong or any typo in your document. 

Thanks.

**Comment by jackbart94** [comment]
Hi,

We recently fixed the documentation, thanks for pointing it out!
