### ISSUE TITLE
When it is expected to have more sophisticated LiDAR?

### ISSUE THREAD

**Issue by IbrahimSobh** [carla-simulator/carla#2895]
Dears

the current LiDAR is a very simple ray casting one. When it is expected to have a more sophisticated, more realistic LiDAR sensor based on ray-tracing?

Best Regards

**Comment by DSantosO** [comment]
Hello Ibrahim,
We are currently developing a new module for electromagnetic sensors based in physical interactions for both LiDAR and RADAR. We expect to have news about it in the following months.
Regards,
Daniel.

**Comment by IbrahimSobh** [comment]
Dears 

I am asking if there is any update? 

Thank you very much
