### ISSUE TITLE
Carla Traffic signs Information

### ISSUE THREAD

**Issue by aravindSwamy94** [carla-simulator/carla#2897]
Hi, 
      I suppose the traffic sign information in latest release can be obtained by 

map.get_all_landmarks()
.
I hope that this includes all the landmarks given in the 
carla.LandmarkType variables.

But when I run this .. The map.get_all_landmarks() returns an empty list. Am I doing some mistake for this API call? 
Please help me with this issue.

Thanks!

**Comment by germanros1987** [comment]
@Axel1092 could you please comment on this? I guess landmarks are not registered yet in our old maps...

**Comment by Axel1092** [comment]
Hi @aravindSwamy94, landmarks encode traffic signals defined in OpenDRIVE. However, our maps were created before the introduction of the landmark class and we are still working on combining the traffic signals that were already present in Carla. Therefore, landmarks are still not available in our maps but they are in the standalone mode, which is loading your own custom OpenDRIVE with traffic lights.
