### ISSUE TITLE
run carla0.9.9 error in ubuntu18.04

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#2917]
when I launch CarlaUE4.sh, it will report this error:

4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=127232 LargeMemoryPoolOffset=258368 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

**Comment by zkyxsq** [comment]
I have same question with you

**Comment by whuxhzhang** [comment]
> I have same question with you

I used my own carla_map, deleted some materials, recompiled it, and temporarily solved this problem.
But I don't think it's a good way.

**Comment by guyu2711** [comment]
I have the same error with my laptop (940m), but it works fine on my PC with GTX 970. So it might need a better graphics card.

**Comment by germanros1987** [comment]
@whuxhzhang do you care to provide more details, or should we just close this issue?

**Comment by zhoushiyang12** [comment]
> > I have same question with you
> 
> I used my own carla_map, deleted some materials, recompiled it, and temporarily solved this problem.
> But I don't think it's a good way.

I deleted some materials too, in UE editor. But, how to recompiled it, and apply it to the Carla-Release?

**Comment by whuxhzhang** [comment]
> > > I have same question with you
> > 
> > 
> > I used my own carla_map, deleted some materials, recompiled it, and temporarily solved this problem.
> > But I don't think it's a good way.
> 
> I deleted some materials too, in UE editor. But, how to recompiled it, and apply it to the Carla-Release?

click "save" button and "build" button in UE4.  Besides, you should download carla source code, then make package.

**Comment by zhoushiyang12** [comment]
I think i have build

> > > > I have same question with you
> > > 
> > > 
> > > I used my own carla_map, deleted some materials, recompiled it, and temporarily solved this problem.
> > > But I don't think it's a good way.
> > 
> > 
> > I deleted some materials too, in UE editor. But, how to recompiled it, and apply it to the Carla-Release?
> 
> click "save" button and "build" button in UE4. Besides, you should download carla source code, then make package.

Hello,  thank you for your help. I think i have buildt  it and i can run it in UE_edit .But where can i find the  compiled  files,  in which can i apply it to the Carla-Release?

**Comment by whuxhzhang** [comment]
> I think i have build
> 
> > > > > I have same question with you
> > > > 
> > > > 
> > > > I used my own carla_map, deleted some materials, recompiled it, and temporarily solved this problem.
> > > > But I don't think it's a good way.
> > > 
> > > 
> > > I deleted some materials too, in UE editor. But, how to recompiled it, and apply it to the Carla-Release?
> > 
> > 
> > click "save" button and "build" button in UE4. Besides, you should download carla source code, then make package.
> 
> Hello, thank you for your help. I think i have buildt it and i can run it in UE_edit .But where can i find the compiled files, in which can i apply it to the Carla-Release?

file locate in carla/Unreal/CarlaUE4/Saved/Cooked/LinuxNoEditor/CarlaUE4/Content/Carla/Maps, end with .uexp

**Comment by zhoushiyang12** [comment]
> > I think i have build
> > > > > > I have same question with you
> > > > > 
> > > > > 
> > > > > I used my own carla_map, deleted some materials, recompiled it, and temporarily solved this problem.
> > > > > But I don't think it's a good way.
> > > > 
> > > > 
> > > > I deleted some materials too, in UE editor. But, how to recompiled it, and apply it to the Carla-Release?
> > > 
> > > 
> > > click "save" button and "build" button in UE4. Besides, you should download carla source code, then make package.
> > 
> > 
> > Hello, thank you for your help. I think i have buildt it and i can run it in UE_edit .But where can i find the compiled files, in which can i apply it to the Carla-Release?
> 
> file locate in carla/Unreal/CarlaUE4/Saved/Cooked/LinuxNoEditor/CarlaUE4/Content/Carla/Maps, end with .uexp

Oh! That does work! Thank you so much!
