### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by Yiquan-lol** [carla-simulator/carla#2918]
Hello, I installed Carla on the Linux system by "Quick install", but when running "./ carlaue4.sh ", I was prompted "Can not create OpenGL context.Check out that the drivers and Hardware support at least OpenGL 4.3".What should I do, please

**Comment by zerone1996** [comment]
Hello, have you solved that? I have met the same problem.

**Comment by Yiquan-lol** [comment]
> 你好，你解决了吗？我遇到了同样的问题。

Sorry, I didn't solve it. This seems to be a common problem with Linux.

**Comment by Yiquan-lol** [comment]
> Hello, have you solved that? I have met the same problem.

Sorry, I didn't solve it. This seems to be a common problem with Linux.

**Comment by germanros1987** [comment]
@Yiquan-lol could you please provide us with more information about your system? For instance...version of CARLA, GPU that you are using, driver, etc.

**Comment by Yiquan-lol** [comment]
I've solved my problem.I plugged the display into the Nvidia graphics card and updated the Nvidia driver to the latest version.

**Comment by Yiquan-lol** [comment]
@zerone1996  You need to update the Nvidia driver to the latest version and have the display attached to the Nvidia graphics card

**Comment by carlaUE4new** [comment]
> @zerone1996 You need to update the Nvidia driver to the latest version and have the display attached to the Nvidia graphics card



> @zerone1996 You need to update the Nvidia driver to the latest version and have the display attached to the Nvidia graphics card

@Yiquan-lol , how do you have the display attached to the Nvidia graphics card?
