### ISSUE TITLE
set_autopilot() error in carla0.9.9 

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#2924]
When I use UE4 draw a route without a closed loop , the vehicle is set autopilot mode , and drives to the end of the route, carla0.9.9 will crash, but it wouldn't happen in carla0.9.6

**Comment by jackbart94** [comment]
Hi,

Since CARLA 0.9.7 the autopilot has been replaced by the Traffic Manager. A lot of things have changed ever since, such as Route Planners being deprecated. Check the documentation to know more about it.
