### ISSUE TITLE
Problem with adding new car 

### ISSUE THREAD

**Issue by villimikko** [carla-simulator/carla#2925]
Hello

I am having issues with adding new vehicle to Carla. I have downloaded genral4wheelskeleton and binded the bones (I think) to mesh with blender. Picture 1.  But when im trying to do import to UE4 carla,I cant find those bones picture 2.

What am I doing wrong?

![Capture](https://user-images.githubusercontent.com/61553242/83871907-a287ba80-a739-11ea-89ef-ebe5c5d79b4c.PNG)

![Capture2](https://user-images.githubusercontent.com/61553242/83871927-a9aec880-a739-11ea-8206-9af9e6208de3.PNG)

**Comment by germanros1987** [comment]
@XGodina @gsmario could you help with this?

**Comment by gsmario** [comment]
Hello @villimikko 
First, sorry for the delay, let me see if I can help you.
At first glance, I think that there was a problem exporting the model and the skeleton. 
You need to bind the bones to each different part of the car, and then export everything into an fbx. Please, make sure you have selected both the skeleton and the meshes. 
If that doesn't solve your problem, please take a screenshot of the software you are using to bind the bones, so I can check if there is another problem.
Thanks for  your time!

**Comment by villimikko** [comment]
**
![image](https://user-images.githubusercontent.com/61553242/85980533-45ef8680-b9eb-11ea-876a-68200a860412.png)
**

Here is my binding in blender.

**Comment by gsmario** [comment]
Hello @villimikko 
Sadly, we don't use blender, so I'm not able to guide you through this process step by step. 
I recommend you using autodesk maya (you can use a free student license) to bind the skeleton, this way, I'll be able to help you.
I'll try to bind the skeleton with blender as soon as I can, but as I said, I'm not a blender user, so I'll need some time.

Thank you again.

**Comment by germanros1987** [comment]
@gsmario I think this is a good opportunity for us. We should make the effort to create a basic vehicle in Blender in order to advise future users on how to do this.

@villimikko could you please provide the sources?

**Comment by maxime-derache** [comment]
Please find below a tutorial that I made on this subject. I hope it will help you to fix your issue!

## Create the armature
* **Shif+A** [Add/Armature]

![image](https://user-images.githubusercontent.com/57399440/86121780-ea022c00-bad6-11ea-87cb-2b39c93bb397.png)

* ViewportDisplay Shapes=yes, Infront=yes, Axes=yes, GroupColors=yes
* Rotation X=90
* Scale X=100, Y=100, Z=100

![image](https://user-images.githubusercontent.com/57399440/86121802-f7b7b180-bad6-11ea-9854-644dc4a01b38.png)

## Create the bones
* Select body (in Object Mode)  
* **Shift+S** (CSursor to selected)
* Select the **Armature**
* Right-clic [Snap/Selection to cursor]
* **Tab** (switch to **Edit Mode**)
* **E** (extrude)
* **Y** (Y-axis)
* **Alt+P** [Disconnect Bone]

![image](https://user-images.githubusercontent.com/57399440/86121831-0736fa80-bad7-11ea-9f5a-57b981f4f041.png)

* **G** (move)
* **X** (X-Axis)
* **Shift+D** (duplicate)
* **X** (X-Axis)
* Repeat the last 2 actions 3 times 

![image](https://user-images.githubusercontent.com/57399440/86121866-14ec8000-bad7-11ea-9c02-02807591ec67.png)

## Set position of bones to rotation origin of the wheels
* **Tab** (switch to **Edit Mode**)
* Repeat for each wheel: 
    * Set the cursor position to the wheel center
    * Select a bone for wheel
    * Right-clic [Snap/Selection to cursor]

![image](https://user-images.githubusercontent.com/57399440/86121919-29307d00-bad7-11ea-90ca-e998ead9ab3b.png)

* **Tab** (switch to **Object Mode**)
* **A** (select all)
* **Ctrl+A** [Apply/Rotation & scale]

![image](https://user-images.githubusercontent.com/57399440/86121979-41080100-bad7-11ea-839f-b912acdb138e.png)

## Join the armature to the meshes
* Select each object and set its name:
    * "Wheel_Front_Right"
    * "Wheel_Front_Left"
    * "Wheel_Rear_Right"
    * "Wheel_Rear_Left"
    * "Body"
    * ...
* Ctrl-select all objects in the list, with the armature at the end

![image](https://user-images.githubusercontent.com/57399440/86122010-51b87700-bad7-11ea-8748-972de337f898.png)

* **Ctrl+P** [Set parent to/Armature deform/With empty groups]
* Check that all meshes are under the armature in the tree view

![image](https://user-images.githubusercontent.com/57399440/86122034-5ed56600-bad7-11ea-90cd-408528716af0.png)

## Associate meshes to corresponding bones
* **Tab** (switch to **Edit Mode**)
* Select each bone and set its name:
    * "Root"
        * "Wheel_Front_Right"
        * "Wheel_Front_Left"
        * "Wheel_Rear_Right"
        * "Wheel_Rear_Left"

![image](https://user-images.githubusercontent.com/57399440/86122071-7280cc80-bad7-11ea-9cef-98d6a5dbff49.png)

* Associate each meshes to the corresponding bone:
    * **Tab** (switch to **Object Mode**)
    * Select an object
    * **Tab** (switch to **Edit Mode**)
    * Check that whole object meshes are well selected
    * Select the vertex group corresponding to the mesh
    * Press **Assign** button

![image](https://user-images.githubusercontent.com/57399440/86122189-abb93c80-bad7-11ea-8fc3-997f81d30779.png)

## Check the armature definition
* Select Armature/Pose to switch to **Pose Mode**
* Check each mesh association:
    * Select the bone
    * **R** (Rotate)
    * **Echap**

![image](https://user-images.githubusercontent.com/57399440/86123349-9f35e380-bad9-11ea-8b6b-b53d03c7a40c.png)

* Check the good axes orientation of the bones (X Forward, Z Up)

![image](https://user-images.githubusercontent.com/57399440/86122819-b922f680-bad8-11ea-8ba5-3cf886841a28.png)

## Export the FBX file with dynamic mesh and skeleton
* Menu [File/Export/FBX (.fbx)]
* Include/Object Types="Armature" and "Mesh" (shift-select)
* Transform/Forward="X Forward"
* Transform/Up="Z Up"
* Geometry/Smoothing="Face"
* Armature/Add Leaf Bones=*NO*
* Brake Animation=*NO*

![image](https://user-images.githubusercontent.com/57399440/86122936-e8396800-bad8-11ea-931d-a3be0b03628a.png)

**Comment by maxime-derache** [comment]
## Create the vehicle Blueprints folder in Carla project
* Open the Acvsare Unreal project simulation/avcsare/Unreal/CarlaUE4/CarlaUE4.uproject
* Create a new folder with the name of the vehicle "*MyVehicle*" in Content/Carla/Blueprints/Vehicles

## Import the mesh and skeleton in Carla project
* Press **Import** button and open the FBX file that contain the meshes and skeleton of the vehicle
* Check that **Skeleton** and **Mesh** are selected
* **Import all**
* The mesh and skeleton are displayed in the assets panel

![image](https://user-images.githubusercontent.com/57399440/86123594-12d7f080-bada-11ea-9358-7c7b5762c720.png)

## Configure the PhysicsAsset
* Open *MyVehicle*_PhysicsAsset
* Select the wheels in the **Skeleton Tree**

![image](https://user-images.githubusercontent.com/57399440/86123637-26835700-bada-11ea-8be5-addec0cdcc9c.png)

* **Suppr** (Remove the collision bodies)
* Thumbnail [Tools/Body Creation] Primitive Type=Sphere
* Thumbnail [Tools/Body Creation] Auto Oriented to Bone=*NO*
* **Re-generate Bodies**

![image](https://user-images.githubusercontent.com/57399440/86123681-3733cd00-bada-11ea-8018-dfc2edb26b79.png)

* **Save**
* Close the asset editor

## Add VehicleWheel Blueprint
* **Add New** Blueprint Class
* [Pick Parent Class/All Classes] Search="VehicleWheel"
* **Select**
* Rename the asset "*MyVehicle*_Wheel"

![image](https://user-images.githubusercontent.com/57399440/86123729-461a7f80-bada-11ea-94ee-7753f3699613.png)

* Open the asset
* **Class Defaults**
* [Details/Wheel] Shape Radius=#Radius measured in Blender#
* [Details/Wheel] Shape Width=#Width measured in Blender#
* [Detail/Tire] Tire Config="CommonTireConfig"

![image](https://user-images.githubusercontent.com/57399440/86123771-5894b900-bada-11ea-9c4b-a4f636cf1ae2.png)

* **Compile**
* **Save**
* Close the asset editor

## Add Animation Blueprint
* **Add New** Animation/Animation Blueprint
* [Create Animation Blueprint] Parent Class="VehicleAnimInstance"
* [Create Animation Blueprint] Target Skeleton="*MyVehicle*_Skeleton"
* **Select**
* Rename the asset "*MyVehicle*_Anim"

![image](https://user-images.githubusercontent.com/57399440/86123798-6a765c00-bada-11ea-95a1-a548e91753df.png)

* Open the asset
* Select the "Anim Graph" Tab
* Right-clic menu [All actions for this Blueprint/Skeletal Control Nodes/Wheel Handler for Wheeled Vehicle]
* Link the "Wheel Handler" to the "Final Animation Pose"
* Right-clic menu [All actions for this Blueprint/Identity/Mesh Space Ref Pose]
* Link the "Mesh Space Ref Pose" to the "Wheel Handler"

![image](https://user-images.githubusercontent.com/57399440/86123844-7a8e3b80-bada-11ea-8623-ecaca9a1986d.png)

* **Compile**
* **Save**
* Close the asset editor

## Add Vehicle Blueprint
* **Add New** Blueprint Class
* [Pick Parent Class/All Classes] Search="BaseVehiclePawn"
* **Select**
* Rename the asset "BP_*MyVehicle*"

![image](https://user-images.githubusercontent.com/57399440/86123875-87129400-bada-11ea-8b9f-88ea9c6990ee.png)

* Open the asset
* [Pawn] AutoPossessPlayer="Player0"
* Select Mesh(Inherited)
* Mesh="*MyVehicle*_Mesh"
* [Animation] AnimClass="*MyVehicle*_Anim"
* Set Vehicle Bounds X, Y, Z
* Select VehicleMovement(Inherited)
* Associate each bone with a vehicle wheel:
    * [Vehicle Setup/Wheel Setups/*0-3*] WheelClass="*MyVehicle*_Wheel"
    * [Vehicle Setup/Wheel Setups/0] Bone Name="Wheel_Front_Left"
    * [Vehicle Setup/Wheel Setups/0] Bone Name="Wheel_Front_Right"
    * [Vehicle Setup/Wheel Setups/0] Bone Name="Wheel_Rear_Left"
    * [Vehicle Setup/Wheel Setups/0] Bone Name="Wheel_Rear_Right"
* Disable steering for rear wheel if required

![image](https://user-images.githubusercontent.com/57399440/86123925-9a256400-bada-11ea-85da-27702635fa4d.png)

* **Compile**
* **Save**
* Close the asset editor

## Add Vehicle Camera (optional)
* **Add Component**
* Search="SpringArm"
* **Add Component**
* Search="Camera"

![image](https://user-images.githubusercontent.com/57399440/86123959-a6a9bc80-bada-11ea-8afa-3e81085ed240.png)

* Select the "ViewPort" tab
* [Transform/Location] X=-500, Z=500
* [Transform/Rotation] Y=-25
* Select the "Event Graph" tab
* Right-clic menu [All actions for this Blueprint/Input/Axis Event/CameraRight]
* Right-clic menu [All actions for this Blueprint/Input/Axis Event/CameraUp]
* Dra&Drop "SpringArm" in the "ViewPort"
* Start a link...
* Select [Utilities/Transformation/AddRelativeRotation]
* Right-clic on "AddRelativeRotation/DeltaRotation" [Pin Actions/Split Struct Pin]
* Link "InputAxis CameraRight" to "AddRelativeRotation" (Delta Rotation Z)
* Link "InputAxis CameraUp" to "AddRelativeRotation" (Delta Rotation Y)

![image](https://user-images.githubusercontent.com/57399440/86124003-b923f600-bada-11ea-8c08-a18fe4c5f301.png)

* **Compile**
* **Save**
* Close the asset editor

**Comment by gsmario** [comment]
Hi! First let me thank you for this awesome tutorial you've created, its a very good job.
I'll try this workflow later, some parts are different from our workflow, but so far, it seems very complete and accurate. 
Thanks again!

**Comment by villimikko** [comment]
Thanks very much for the guide it helped a lot. I have still some problem with the boundbox, for some reason i cant resize it. .
![image](https://user-images.githubusercontent.com/61553242/86375316-2e83f800-bc8e-11ea-9861-7871b2030fda.png)

**Comment by gsmario** [comment]
hi @villimikko try to expand the context menu, and search for the transform options, if pressing the R key in the viewport doesn't work. 
![a](https://user-images.githubusercontent.com/44405709/86387174-0f3b9980-bc93-11ea-9911-b9ffd0561f8c.png)

**Comment by villimikko** [comment]
Thanks for that! For some reason when i spawn vehicle, the wheels work but car wont move at all(even pygame windows show acceleration and the wheels are spinning). Otherwise i think it is working.

**Comment by villimikko** [comment]
![carla 2](https://user-images.githubusercontent.com/61553242/86598011-2c2ee000-bfa5-11ea-89bc-10636a09ed13.gif)
![carla 1](https://user-images.githubusercontent.com/61553242/86598014-2f29d080-bfa5-11ea-9a32-9f8e4ac78c9d.gif)
![capture 1](https://user-images.githubusercontent.com/61553242/86598048-3a7cfc00-bfa5-11ea-96ff-db0b1808f58e.PNG)

When i have "hull" box the car drops throught terrain, but when i dont have it it wont move?

What did I do wrong this time? 👎

**Comment by gsmario** [comment]
Hi @villimikko 
Please, be careful when creating and placing the collision boxes, if you put the wheels collision inside the bodywork (the car's general collision box) you'll have problems. Try to recreate this with your car: 
![image](https://user-images.githubusercontent.com/44405709/86604183-57193400-bfa5-11ea-849e-d5ceafc23f6e.png)

**Comment by villimikko** [comment]
Tried to do that still having thse kinds of physics bugs on Carla.
![ezgif com-optimize](https://user-images.githubusercontent.com/61553242/87905848-238cde00-ca6a-11ea-8eb9-061535652cc1.gif)

What could cause this?

**Comment by gsmario** [comment]
Hello @villimikko I'm asuming you're using blender, please, try to rig your wheels using only "rotation" as option, instead of "rotation and scale" and test it again. Also, set the wheels as kinematic in the physic asset.
I hope this helps.
![image](https://user-images.githubusercontent.com/44405709/87924949-e16e9700-ca7f-11ea-9bf6-109e32f3f68b.png)

**Comment by chandeep11** [comment]
Hello @villimikko, check [this](https://www.youtube.com/watch?v=w70w1o3nddg) link for detailed steps on adding a car in UE4 from Blender.

**Comment by villimikko** [comment]
I used this Blender addon to autorig my model  and after that i didint have any problems in carla.

Thanks everyone for helping me out!

https://continuebreak.com/creations/ue4-vehicle-rigging-addon-blender/

**Comment by gaohongfein** [comment]
Hi villimikko,
I try to add a new vehicle in carka according with your tutorial. Now I can conrol the vehicle in manual control. The wheel can rotation and steering. But the vehicle can not move. Do you know how to solve this problem?
![Uploading Screenshot from 2020-10-29 11-12-21.png…]()

**Comment by gaohongfein** [comment]
@villimikko

**Comment by gaohongfein** [comment]
![Screenshot from 2020-10-29 12-11-20](https://user-images.githubusercontent.com/26884060/97524532-e2e51f00-19df-11eb-81b2-6827395ff612.png)
The vehicle is above the ground!

**Comment by eslaaam3** [comment]
Hello,
I'm having a similar issue and I have posted an [issue](https://github.com/carla-simulator/carla/issues/5674) #5674
Can anyone help please?
Thanks!
@gsmario @maxime-derache

**Comment by gokcerSnmzck** [comment]
Hello, I am experiencing the same issue regarding the non moving vehicle. I have opened a new thread with the screenshots at this post #9695 . Can you check it please ? I would really appreciate your help @germanros1987 @gsmario @chandeep11 @maxime-derache @villimikko
