### ISSUE TITLE
dynamically scalable vehicles

### ISSUE THREAD

**Issue by AlexScheid** [carla-simulator/carla#2934]
Hello CARLA community,

first of all thank's for such a great simulator.
This is not a real issue, more a suggestion to an easy to implement feature with a small question at the end.

I try to play a dataset in my CARLA simulation and therefore I also use some of the available features of CARLA like the OpenDRIVE standalone mode. While implementing the clientside, there occurs the problem that CARLA does actually not provide scalable vehicles. My dataset consists of many different cars and trucks and the difference between the already existing CARLA vehicles and some of my desired vehicles is to great to neglect this.

To solve this problem I created two very simple vehicles (you can see below) like described [hier](https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/). Because the simulation is intended for decision making, these simple vehicles are good enough.
Next I added the attributes "extent_x" and "extent_y" (*) to the vehicle parameters located at /<carla_repo>/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ VehicleParameters.cpp
![vehicle_parameter](https://user-images.githubusercontent.com/62210888/84132440-2eedf200-aa46-11ea-8cac-6bb1be7f54b8.png)
To get access to these attributes and make them available for my vehicles I added the following lines to /<carla_repo>/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
![attribute_adding](https://user-images.githubusercontent.com/62210888/84132830-a1f76880-aa46-11ea-9b84-380c33618d2a.png)
Then I used _make clean_ and _make launch_.
To use this attributes only if one of my scalable vehicles is spawned I expand the "Spawn Actor" function of the "VehicleFactory" class in UE4 editor like shown in the picture below.
![spawn_actor_new_part](https://user-images.githubusercontent.com/62210888/84133865-ffd88000-aa47-11ea-8bef-70801f719138.png)
Then I added the function "Set Extent" (already used above) to the "BaseVehiclePawn" class to calculate the scaling factors and scale the actor.
![set_scale_function](https://user-images.githubusercontent.com/62210888/84134012-39a98680-aa48-11ea-91a5-475115af3c50.png)

This works quite well for spawning scaled vehicles during my simulation. I shared this here because I thought, that this is maybe a small feature needed by some more people.

One unsolved problem occurs in this process, marked with the star (*). I can only scale the x and y direction correctly. When I try to scale the actor in the z direction, the bounding box and the mesh of my actor got an offset towards each other. I think that is because the centers of scaling differ in z-direction like shown below.
![scale_both_view](https://user-images.githubusercontent.com/62210888/84134935-96597100-aa49-11ea-850b-f48f1b8b010d.png)
I tried to compensate this by shifting the bounding box dynamically responding to a z-scaling factor in the new function "Set Extent", but I cannot get access to its object. Maybe somebody knows a solution therefore and a scalable object can be taken into account for a future version.

**Comment by hbanzhaf** [comment]
Great new feature to accurately replay real-world data in CARLA. What's the CARLA team's (@glopezdiest, @sergi-e, @joel-mb) opinion on that? Would it make sense to turn this into a PR?

**Comment by germanros1987** [comment]
@bernatx what is your opinion on this?

**Comment by AlexScheid** [comment]
Update:
After some more tries, I found a more simple solution for this feature. I used the changes in the C++ Code shown above, but removed all the changes in the UE4-Editor files. A change of the transform used to spawn a vehicle in the "Spawn Actor" function of the "VehicleFactory" produces the same result. The part I added is shown below. It is like a summary of the old version combined with the integration in the transform.
![new_function](https://user-images.githubusercontent.com/62210888/86322944-2d29df80-bc3c-11ea-96e3-0b6a3210a67e.png)

Additionally I found one problem by scaling a vehicle in this way and I can give a possible solution for that. If you move a vehicle with the command "set_transform()" the CARLA-side implementation is using a location and a rotation while the UE4-side equivalent function is using also a scaling vector. This destroys the adapted scaling. To remove this problem, I had to change the C++ code of /<carla_repo>/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp at the function "BIND_SYNC(set_actor_transform)" like shown below.
![transform](https://user-images.githubusercontent.com/62210888/86324003-28662b00-bc3e-11ea-908a-1ffecea65b88.png)

**Comment by AlexScheid** [comment]
Update:
After some tests there were still some points that had to be improved. For example the collision bodies of UE4 did not match with the optical mesh ("pxvis collision" in UE4 cmd) and the x-direction was not scalable.
These problems are solved with the this update and the scalable vehicle can be used as expected.
Changes:
As described in the first two images of this issue, I added the "extent_z" attribute. 
Then I changed the  "Spawn Actor" function of the "VehicleFactory" again. The final result looks like this:
![32](https://user-images.githubusercontent.com/62210888/87055649-ea9c7000-c204-11ea-8e78-519f7d735cda.png)
The detailed changes are below.
![28](https://user-images.githubusercontent.com/62210888/87055680-f38d4180-c204-11ea-86ce-bc606b8837c9.png)
![29](https://user-images.githubusercontent.com/62210888/87055682-f4be6e80-c204-11ea-8697-f32bd2ae174b.png)
![30](https://user-images.githubusercontent.com/62210888/87055689-f5ef9b80-c204-11ea-9e84-10e17e907b56.png)
![31](https://user-images.githubusercontent.com/62210888/87055691-f720c880-c204-11ea-92e5-52631b525651.png)

Used float variables "scalable_vehicle_x", "scalable_vehicle_y" and "scalable_vehicle_z" are set to the unscaled dimensions of my model. The bool variable "scalable" distinguishes the scalable vehicle from the other vehicles. The vector variable "scaling vector" is used for clarity in the function.
Because of some problems with the wheel physics, I have to add some lines of code in the BeginPlay-function in the (<carla_repos>/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/) CarlaWheeledVehicle.cpp file
![111](https://user-images.githubusercontent.com/62210888/87056604-2421ab00-c206-11ea-9704-168374ee3dd2.png)

My last problem was the bounding box of the vehicle, which is referenced in some of the CARLA-functions. Its center is not shifted if a scaling was performed. Therefore I added a function to CarlaWheeledVehicle.cpp and CarlaWheeledVehicle.h to perform such a relative shift.
![112](https://user-images.githubusercontent.com/62210888/87056839-75ca3580-c206-11ea-9419-61fb4da7134a.png)

**Comment by KunanonxGithub** [comment]
@AlexScheid So, if we want to change some parameters or change our cars to be bigger and be more realistic, we need to use C++ to adjust PhyX Engine in UE4. Am I right?

**Comment by AlexScheid** [comment]
Hi @KunanonxGithub, as far as I remember you do not have to use C++ for a static change of the dimension or for the physical parameters at all. The issue should address a dynamic scalable vehicle, which means that you can use the same model to spawn vehicles with different dimensions (parameters are also conceivable) in one simulation. I had to change some C++ files of CARLA to get access to the newly created ability.
If you want to change the parameters once before you start a simulation (I called that static) and these parameters are fixed for all the vehicles of this type in your simulation, than you do not need any C++. All these things can be done in UE4. I can recommend you to look at the documentation [here](https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/). During this process you can change some physical parameters in the menus of UE4. (not done in this documentation) You do not have to use a new vehicle, you can get access to the already existing vehicles of CARLA and modify them.
Hope this will help you
