### ISSUE TITLE
Error: computer automatically shutdown by running CarlaUE4.sh on Ubuntu 20.04

### ISSUE THREAD

**Issue by happengor** [carla-simulator/carla#2935]
Hey guys, i followed the build instruction by https://carla.readthedocs.io/en/latest/start_quickstart on Ubuntu 20.04.

After Installation i went into folder /opt/carla-simulator/bin and tried to run CarlaUE4.sh. It requires also entering password of sudo. 
As the scene showed up, the computer was turned off automatically. Could anybody explain this issue? Is the carlar 0.99 with deb Installation not compatible with ubuntu 20.04?

**Comment by germanros1987** [comment]
@joel-mb could you try to launch the deb in a 20.04 distribution?

**Comment by joel-mb** [comment]
Hi @happengor ! I'll try to launch the deb package in Ubuntu 20.04 during this week to see if there is some kind of incompatibility. Regarding the issue entering the password, there is a PR fixing this (https://github.com/carla-simulator/carla/pull/2945). As soon as it gets merged I'll update the package.

**Comment by happengor** [comment]
Thanks, i have solved my problem with a bigger psu.

**Comment by happengor** [comment]
Thanks, guys, i have solved my problem with a bigger psu. Now i can launch the deb in 20.04.

**Comment by joel-mb** [comment]
Perfect! Thanks for the information!
