### ISSUE TITLE
IMUMeasurement gyroscope values in world-frame instead of body-frame

### ISSUE THREAD

**Issue by GabiShahmayster** [carla-simulator/carla#2939]
Hello,

First of all, thank you very much for this great simulator, I've been using it extensively for the last few days and so far it's been a great experience.
I'm currently focused on retrieving IMU data and feeding it into a GNSS/INS fusion algorithm, so the first thing is to ensure that I'm passing valid IMU data to the INS.
I'm using pre-built binaries, of version 0.9.9.1, on Ubuntu 18.04.04 LTS.

I'm encountering an issue related to the gyroscopes measurements. They seem to be output in the world frame, instead of the vehicle body frame. 
The accelerometers look ok. 
This issue can be easily reproduced by driving a vehicle in a straight line (I'm using VehiclePIDController to drive the vehicle for a few tens of meters). 
During the drive, the vehicle pitch fluctuates. This should be reflected in a corresponding Y axis rotation-rate, in the vehicle-frame. The vehicle experiences acceleration, which should be reflected mostly in X-axis acceleration, in the vehicle-frame. 
We can now drive the vehicle, in a straight line, in two different orientations:
1. Vehicle is east-bound (UE world yaw = 0[deg]). IMU-frame should be aligned with UE-frame.
2. Vehicle is south-bound (UE world yaw = 90[deg]). IMU-frame X should be UE-frame Y, IMU-frame Y is UE-frame (-X). 

In both scenarios, we would expect similar vehicle pitch profile and body-frame IMU measurements.
The actual results show a similar vehicle pitch profile and accurately reported body-frame IMU accelerometers values.
However it seems as though the gyroscopes report world-frame rotation-rates... 
We can see the issue in the following figures:
East-bound scenario has similar world/imu accelerations/rotation-rates, as expected.
South-bound scenario has different world/imu accelerations, as expected BUT similar rotation-rates, which shouldn't be the case, because the vehicle is rotated w.r.t the world.

I've retrieved the world-frame accelerations and rotation-rates using Actor's get_acceleration and get_angular_velocity() methods.

p.s I'm sorry if this is too much information for a very simple issue to describe...

Thank you very much!
Gabi Shahmayster

![Vehicle heading East acceleration](https://user-images.githubusercontent.com/66723225/84250470-c457b780-ab14-11ea-9ce0-a47f55909a01.png)
![Vehicle heading East gyro](https://user-images.githubusercontent.com/66723225/84250473-c588e480-ab14-11ea-9c2d-25624eebb3b0.png)
![Vehicle heading East pitch](https://user-images.githubusercontent.com/66723225/84250475-c588e480-ab14-11ea-8af1-db542d7640b7.png)
![Vehicle heading South acceleration](https://user-images.githubusercontent.com/66723225/84250477-c6217b00-ab14-11ea-8d10-b7228a1f69d1.png)
![Vehicle heading South gyro](https://user-images.githubusercontent.com/66723225/84250480-c6217b00-ab14-11ea-9bcb-1cd210ce6e21.png)
![Vehicle heading South pitch](https://user-images.githubusercontent.com/66723225/84250482-c6ba1180-ab14-11ea-9de3-d8c6f773d44e.png)

**Comment by GabiShahmayster** [comment]
Anyone from the Carla team? @ItsTimmy could you please take a look? 
Maybe I'm missing something fundamental regarding Carla or there's any non-standard IMU modelling going on...

**Comment by ItsTimmy** [comment]
I'm not actually part of the Carla team, but I can still take a look. This issue might actually explain some other problems I've been having with Carla...

**Comment by GabiShahmayster** [comment]
> I'm not actually part of the Carla team, but I can still take a look. But I don't have a lot of free time, so I probably will not get to it soon.
> 
> So if anyone else comes across this issue, don't wait for me to fix it!

@ItsTimmy Thank you very much. Unfortunately, I am not familiar with the official Carla team or the most effective ways of reporting such an issue... If you think that I should contact someone from the team, via Discord chat perhaps, or try to fix the issue and submit a PR, please tell me so...

**Comment by germanros1987** [comment]
@marcgpuig and @DSantosO could you take a look? I know it's a busy time... but this was supposed to be solved. It's not the first time we find similar problems.

**Comment by ItsTimmy** [comment]
I have a fix in #2998 . Still needs some testing though.

**Comment by DSantosO** [comment]
Thank you @GabiShahmayster for bringing the issue and @ItsTimmy for the fix. We will test it and hopefully merge it as soon as possible.

**Comment by wu0023** [comment]
Hi， I'm wondering whether this bug is fixed in the old version, (e.g., 0.9.9.4)?

**Comment by GabiShahmayster** [comment]
Hi @wu0023,
It was fixed in version 0.9.10 (https://github.com/carla-simulator/carla/releases/tag/0.9.10/)
