### ISSUE TITLE
Cannot find a Plugins folder

### ISSUE THREAD

**Issue by Mechatrnk** [carla-simulator/carla#2944]
Hello, I am new to CARLA and I am trying to implement a RoadRunner plugins to create a CARLA Map using RoadRunner.
I am trying to follow this [instructions](https://www.mathworks.com/help/roadrunner/ug/Exporting-to-CARLA.html), I downloaded CARLA 0.9.5 but there is no path carla/Unreal/CarlaUE4/Plugins.

Is it the reason behind this that I did not build CARLA from source but just downloaded it from [here](https://github.com/carla-simulator/carla/releases/tag/0.9.5)? I am not that experienced programmer to build something from source, but is it the only way how to be able to run RoadRunner maps in CARLA?

Thank you very much for any help

P. S. Because this is very important issue for me I posted this question on CARLA Forum as well. I know that this is not very good and I apologize for that

**Comment by whuxhzhang** [comment]
I suggest you download and compile the source code. In addition, you may need to download the “Content” package.
hope it works for you.
