### ISSUE TITLE
IndexError: blueprint 'sensor.other.radar' not found

### ISSUE THREAD

**Issue by hazemessamm** [carla-simulator/carla#2946]
I get IndexError everytime I try to get the radar sensor from the blueprint_library

front_radar = self.blueprint_library.find('sensor.other.radar')

IndexError: blueprint 'sensor.other.radar' not found

I am using Carla on windows 10 

Carla Version 0.9.5

**Comment by whuxhzhang** [comment]
I remember carla0.9.5 have no radar, 
carla-0.9.7 or 0.9.8 have radar

**Comment by germanros1987** [comment]
Correct.
