### ISSUE TITLE
I want to apply the steer and velocity values predicted by trained model to the car.. how can I do this ?

### ISSUE THREAD

**Issue by rehamessameltagoury** [carla-simulator/carla#2950]
I tried to apply the steer using apply_control and velocity using set_velocity but it doesn't work properly do anyone have another idea ?

**Comment by JMorceaux** [comment]
Quick look to at the doc and this should answers your question: https://carla.readthedocs.io/en/latest/core_actors/#vehicles

**Comment by germanros1987** [comment]
@rehamessameltagoury are you still having issues?

**Comment by rehamessameltagoury** [comment]
thank you so much
