### ISSUE TITLE
How to control the vehicle's steer and speed in CARLA 9.5 or CARLA 8.2 ?

### ISSUE THREAD

**Issue by mariam-khaled** [carla-simulator/carla#2952]
Hello, I have a model that predicts the steering angle and an acceleration command(Accelerate-Decelerate-Maintain). I want to control the vehicle by applying the steer angle and increasing, decreasing or maintaining its speed. Which APIs to use? If I want to increase the speed do I have to modify the forward_speed? Thanks in advance.

**Comment by germanros1987** [comment]
Hi @mariam-khaled 

I would recommend you to use newer versions of CARLA. For instance 0.9.9. Then, these questions can be easily resolved by reading our documentation: https://carla.readthedocs.io/en/latest/
