### ISSUE TITLE
Does the new release of carla has mapping coordinates on Town1 and Town2?

### ISSUE THREAD

**Issue by LoayMAmin** [carla-simulator/carla#296]
I just upgraded to the new carla release to use the LiDAR sensors.
However, In the old release, I used the 
x          =             measurements.player_measurements.transform.location.x
y          =             measurements.player_measurements.transform.location.y

Then 

x_pixel = (x + 1643) // 16.43 
y_pixel = (y + 1643) // 16.43 
pixel = Town_image[int(y_pixel), int(x_pixel)]

Which will give me the mapping of the exact pixel in the Town1 from the world coordinates.

Suddenly when I switched to the new Carla release this mapping factor does not work.

Please advice.

**Comment by nsubiron** [comment]
The measurements are now sent in meters (previously it was in centimeters) #273. That's probably it.

**Comment by LoayMAmin** [comment]
Fixed. Thank you.
