### ISSUE TITLE
Assertion failed: Wheels.Num() > 0

### ISSUE THREAD

**Issue by villimikko** [carla-simulator/carla#2961]
Did vehicle modelling acording to the documentation. When i try to spawn my own vehicle it will crash and this error pop up. What went wrong?

**Comment by germanros1987** [comment]
Could you please provide more information? The version of CARLA, environment, OS, etc.

**Comment by villimikko** [comment]
I'm running Carla 0.9.9 on windows build version. Map is Town 3 and no parameters have been changed except for modelling that vehicle.

**Comment by Axel1092** [comment]
Hi @villimikko,
The error suggest that the wheels are not properly defined, did you follow all the steps here: https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/ in addition to vehicle modelling?
