### ISSUE TITLE
RoadRunner 2019.2.12 on Ubunty 18.04 black screen

### ISSUE THREAD

**Issue by mvdstelt** [carla-simulator/carla#2963]
Tho whom it may concern,

I am running Ubuntu 18.04 and have installed in this distro VerctorZero Roadrunner 2019.2.12.
After starting RoadRunner without issues and going to the Editor page, the editor page is only black.
This also happens with the RoadRunner 2019.2.11 version.
last week it was working, untill Ubuntu crashed and I had tore-install Ubuntu and all Apps.
I am also running Unity3D, but now via the UnityHub.
Does anybody know how to solve the Black Screen issue for RoadRunner in Ubuntu?

![Screenshot from 2020-06-17 21-37-29](https://user-images.githubusercontent.com/64353614/84906504-9c53ef80-b0e4-11ea-909d-c31063ad4c8b.png)

**Comment by germanros1987** [comment]
Please, talk directly with VectorZero (now Mathworks). They should be able to help you.

**Comment by mvdstelt** [comment]
Thanks.

Kind regards and thanks,
Machiel van der Stelt

https://stelt-technologies.com.au/
https://archive.org/details/@machiel_van_der_stelt
