### ISSUE TITLE
Traffic Manager Problems

### ISSUE THREAD

**Issue by AlexScheid** [carla-simulator/carla#2966]
Hello Carla-Community,

I want to use the TrafficManager on my own map in the OpenDRIVE standalone mode to simulate some traffic. During some first tests with a single vehicle some problems occurred:

1. The vehicle did not change the lane in a curve with 2 existing lanes, both in the driving direction of the vehicle. The lanes are existing and the Client can get access to both of them. I checked that:
```
loc = self.vehicle.get_location()
waypoint = self.map.get_waypoint(loc, True)
left_lane = waypoint.get_left_lane()
right_lane = waypoint.get_right_lane()
```
Either right_lane or left_lane contains a waypoint, depending on the current lane of the vehicle. 

2. I want to change the velocity of the vehicle at specific positions. These informations are not provided in the .xodr-file, where the speed limit is defined (if I understand it right), therefore I want to change the percentage speed difference of the vehicle with the command:
`self.traffic_manager.vehicle_percentage_speed_difference(self.vehicle, self.speed_percentage)`
But this did not affect anything. Is there another way to perfom such a behaviour?

**Comment by jackbart94** [comment]
Hi,

Thanks for using the Traffic Manager, I hope I can shed some light on your doubts.

1. Traffic Manager has three different parameters for lane changes. The first one, which is active by default, is the automatic one, which basically activates lane change in different situations (for example, a car slower is in front so we change the lane to pass it). The one you might be looking for is the forced lane change (check among the parameters!) where you can decide to have the car move to the lane on the right or left at runtime. In addition to this, there's a "keep right" rule parameter, which is by default set to 0, where you can specify how much a car is likely to stay in the most-right lane. Finally, you can change the code yourself for the automatic lane change if you want a specific policy!

2. Setting the velocity in the Traffic Manager works in this way: you always have a speed limit affecting the vehicle, and you set the percentage of speed difference that you want your vehicle to go with respect to that limit. There's a vehicle-specific method (the one you are using) and also a global method, including all vehicles under that specific Traffic Manager, which is called ``global_percentage_speed_difference``. 

Let me know if this helps you!

**Comment by AlexScheid** [comment]
Hi,

thank you for the quick response!

1. For the point of time I want to force a lane change of a specif vehicle at a given location, therefore I turned off the automatic lane changes and force a lane change with:
`self.traffic_manager.force_lane_change(self.vehicle, direction)`
This command is working as expected, when my vehicle is on a straight road. But when it is driving in a curve it does not react on this command. I checked the map by using `waypoint.lane_change` and `waypoint.get_left_lane()` / `waypoint.get_right_lane()` and with both variants I get access to a neighbor lane in the expected direction. It is a quite long curve, which should give enough waypoints for the route planning. Do you have any clue what's going wrong in this case?

2. Because my traffic manager should handle a small swarm of vehicles with different velocities I would set the velocity for each vehicle with:
`self.traffic_manager.vehicle_percentage_speed_difference(self.vehicle, speed_percentage)`
At a specific location I want to change the velocity of a vehicle by applying the same command with the same vehicle and a different value for the variable `speed_percentage`. I tested this on a straight road, which is long enough to see some reactions, but they did to appear. Is it possible to change the percentage speed difference of a vehicle from time to time by using the traffic manager? I also looked at the last throttle command given by the traffic manager, which stays constant after a change of the speed percentage value. In this context I assume the throttle value is capped by 0.6999.., can it be changed by the PythonAPI?

**Comment by germanros1987** [comment]
@jackbart94 could you follow up?

**Comment by AlexScheid** [comment]
Concerning point 1: I take a closer look at the used map and I think the problem can be caused by the definition of the curve. It is assigned to a junction, what surprised me a bit, because it is a very long curve. I think lane changes are not possible at a junction, if I remember that right, therefore this part of my problem can be seen as solved. Sorry for that.

For the second question/problem I have not been able to find a solution.

**Comment by jackbart94** [comment]
Yeah, you're absolutely right about point 1.

For point 2, throttle is indeed capped at 0.7, but you'll have to change it in the Traffic Manager API. You just have to modify the constant MAX_THROTTLE in Constants.h and do ``make LibCarla`` to apply the changes. Having said so, it is possible to change the values of maximum velocity for vehicles at different times in the execution, via the PythonAPI as you're doing, but I'll need some more information (and possibly the code to test it on my computer) because it could be possible that, for example, you aren't setting the conditions appropriately.

**Comment by AlexScheid** [comment]
Thank you for the hint regarding the MAX_THROTTLE.
I also thought that it is possible to change the velocity in this way, but it does not affect anything. A short version of my problem with only one vehicle is given by the code below. It is on a map, which shows a highway situation.
`import glob
import os
import sys

try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    print('failed to import carla')
    print(sys.version_info.major)
    print(sys.version_info.minor)
    print('win-amd64' if os.name == 'nt' else 'linux-x86_64')

import carla
import numpy as np

def get_map():
    """ read in an openDrive file"""
    data = None

    return data

def get_valid_spawn_point(world):
    """
    used for my map to get valid spawn points
    """
    all_spawn_points = world.get_map().get_spawn_points()
    spawn_points = []
    for spawn_point in all_spawn_points:
        if 250. < spawn_point.location.y < 350.:
            if 250 < spawn_point.location.x < 350.:
                spawn_points.append(spawn_point)

            elif -250 > spawn_point.location.x > -350.:
                spawn_points.append(spawn_point)
    
    return spawn_points

class SingleVehicle(object):
    """
    test class for a single vehicle
    """
    def __init__(self, client, spawn_point, default_velocity):
        """
        set default parameters and activates the tm initialization
        """
        self.client = client
        self.world = self.client.get_world()
        self.map = self.world.get_map()
        self.spawn_point = spawn_point
        self.vehicle = None

        self.traffic_manager = None
        self._initialize_tm()

        self.target_velocity = default_velocity

    def _initialize_tm(self):
        """
        initialization of the tm
        """
        self.traffic_manager = self.client.get_trafficmanager(8000)
        self.traffic_manager.set_global_distance_to_leading_vehicle(2.0)

    def _target_reached(self):
        """
        used for my map to avoid that the vehicle leaves an restricted area
        """
        loc = self.vehicle.get_location()
        if loc.y < -300.:
            if loc.x < -250. or loc.x > 250.:
                self.lane_changed = False
                return True
        
        return False

    def _speed_percentage(self):
        """
        calculates the percentage speed difference used by the tm
        """
        sl = self.vehicle.get_speed_limit()
        if sl < 10 or sl > 200:
            sl = 30
        speed_percentage = - (self.target_velocity - sl) / sl * 100.
        return speed_percentage

    def set_new_target_velocity(self, new_vel):
        """
        change the target velocity
        """
        self.target_velocity = new_vel
        self.traffic_manager.vehicle_percentage_speed_difference(self.vehicle, self._speed_percentage())

    def get_location(self):
        """
        get the current location of the vehicle
        """
        return self.vehicle.get_location()

    def update(self):
        """
        spawn, destroy or print some informations about the vehicle
        """
        if not self.vehicle:
            bp = self.world.get_blueprint_library().find('vehicle.audi.a2')
            self.vehicle = self.world.try_spawn_actor(bp, self.spawn_point)
            if self.vehicle:
                print("vehicle successfully spawned")
                self.vehicle.set_autopilot(True, self.traffic_manager.get_port())
                print("set: " + str(self._speed_percentage()))
                self.traffic_manager.vehicle_percentage_speed_difference(self.vehicle, self._speed_percentage())
                self.traffic_manager.auto_lane_change(self.vehicle, False)
            else:
                print("vehicle not spawned")
        else:
            if self._target_reached():
                self.vehicle.destroy()
                self.vehicle = None
                print("vehicle destroyed")
            else:
                v = self.vehicle.get_velocity()
                v_abs = np.sqrt(v.x**2 + v.y**2 + v.z**2) * 3.6
                print("current/target velocity [km/h]: %1.2f/%1.2f with percentage %3.1f to %1.2f" % (v_abs, self.target_velocity, self._speed_percentage(), self.vehicle.get_speed_limit()))
                self._speed_percentage()

    def __del__(self):
        """
        destroy the vehicle
        """
        if self.vehicle:
            self.vehicle.destroy()
            self.vehicle = None

# ==============================================================================
# -- main function -------------------------------------------------------------
# ==============================================================================

def main():
    vehicle = None
    try:
        client = carla.Client('127.0.0.1', 2000)
        client.set_timeout(10.0)
        odd = get_map()
        world = client.generate_opendrive_world(odd)

        spectator = world.get_spectator()
        spectator_init_transform = carla.Transform(
            carla.Location(x=5, y=320, z=60),
            carla.Rotation(pitch=-2180, yaw=-132, roll=0))
        spectator.set_transform(spectator_init_transform)

        settings = world.get_settings()
        settings.fixed_delta_seconds = 0.05
        settings.synchronous_mode = True
        world.apply_settings(settings)

        spawn_points = get_valid_spawn_point(world)

        vehicle = SingleVehicle(client, spawn_points[0], 60)

        velocity_changed = False
        frame = 0
        while True:
            
            vehicle.update()

            veh_loc = vehicle.get_location()
            
            if veh_loc.y < 100 and not velocity_changed and frame > 5:
                print("change velocity")
                velocity_changed = True
                vehicle.set_new_target_velocity(90.)

            world.tick()
            frame += 1

            

    finally:
        if vehicle:
            del vehicle
        settings = world.get_settings()
        settings.synchronous_mode = False
        settings.fixed_delta_seconds = None
        world.apply_settings(settings)

# ==============================================================================
# -- start point ---------------------------------------------------------------
# ==============================================================================

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("shut down forced")

    finally:
        print("bye")`

**Comment by AlexScheid** [comment]
Thank you for the hint regarding the MAX_THROTTLE.
I also thought that it is possible to change the velocity in this way, but it does not affect anything. A short version of my problem with only one vehicle is given by the code below. It is on a map, which shows a highway situation. (Maybe relevant for stable driving at this velocity)
Sorry for the bad formatting of the last post, here is the code in a txt-file.
[simple_scenario.txt](https://github.com/carla-simulator/carla/files/4862403/simple_scenario.txt)

**Comment by jackbart94** [comment]
Sorry if it took a while to answer. I think there might be a bug for this particular parameter ``vehicle_percentage_speed_difference`` as it seems to be applying successfully only once. We will push a fix very soon and I'll let you know.

I've tested your script and then tried on another one to replicate the issue, and it kept happening. I'll make sure to mention this issue once the PR is open.

**Comment by AlexScheid** [comment]
thank you very much for all the help!

**Comment by dhiegomaga** [comment]
> 1. In addition to this, there's a "keep right" rule parameter, which is by default set to 0, where you can specify how much a car is likely to stay in the most-right lane.

What parameter is this? I can't find it in the documentation.

**Comment by jackbart94** [comment]
> > 1. In addition to this, there's a "keep right" rule parameter, which is by default set to 0, where you can specify how much a car is likely to stay in the most-right lane.
> 
> What parameter is this? I can't find it in the documentation.

Thanks for pointing it out, it's actually not in the documentation which we must update accordingly.

Anyway, the parameter is ``set_percentage_keep_right_rule``:

```
set_percentage_keep_right_rule(self, actor, perc)

During the localization stage, this method sets the percent chance that a vehicle changes lane to the right without any traffic or path implication.

    Parameters:
        actor (carla.Actor) – The actor that is going to move to the right lane.
        perc (float) – Between 0 and 100, chance that the actor might move to the right lane.
```

**Comment by jmoss7** [comment]
Hi @jackbart94 , Do you know if multiple calls to force_lane_change() will result in the same number of lane changes? I'm trying to do something where my agents perform X number of lane changes. I have a behavior tree for each vehicle, where X number of ForceLaneChangeBehavior nodes are added upon creation of their trees. I'm trying to have the nodes only return SUCCESS after the vehicle is fully in the new lane, so additional calls to force_lane_change don't happen prematurely. 

Right now, I can't seem to get the vehicles to do more than one lane change in quick succession.

Any help is greatly appreciated!
Thanks,
John
