### ISSUE TITLE
Could we substitute the xodr file for a map?

### ISSUE THREAD

**Issue by ZhengZhongyuan11** [carla-simulator/carla#2969]
Hi guys, I want to know how carla generate the waypoint from opendrive file? Is it possible that we replace the current xodr file of the map and regenerate the waypoint based on the new xodr file?

I have tried deleting the xodr file in carla/Unreal/CarlaUE4/Content/Carla/Maps/OpenDrive folder, and substitute it with the new one, but the waypoint didn't updated. So I wonder is it possible that we just renew the xodr file? 

Thanks!

**Comment by germanros1987** [comment]
That won't work. What are you trying to do exactly? Please, let us know about the higher-level use case you are trying to create.
