### ISSUE TITLE
timeout when pulling docker image from carla

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/carla#2973]
timeout error when I tried to pull the docker image from carlasim/carla:0.9.8
I ran the command as suggested by the carla docs:
**docker pull carlasim/carla:0.9.8**
and the error information was:

0.9.8: Pulling from carlasim/carla
9ff7e2e5f967: Pull complete
59856638ac9f: Pull complete
6f317d6d954b: Pull complete
a9dde5e2a643: Pull complete
b03d58f382f0: Pull complete
a7d5a9b04781: Pull complete
e9a5dfa2bfd8: Pull complete
1f4e2a05c2d1: Pull complete
5c71b18fedd7: Pull complete
831bd4a88578: Pull complete
ce1382aa3b42: Pull complete
f148dcd7767e: Pull complete
29a4a6e88a96: Pull complete
f0ee155eb69d: Pull complete
7a9b81f2b6d2: Pull complete
14b8c8c82705: Pull complete
cb3234d8aae2: Pull complete
1969e6e74b29: Pull complete
f06135b4549b: Pull complete
61c4d257a07c: Pull complete
36f02e1353e4: Pull complete
84db633c89e1: Pull complete
0307fc1486c7: Pull complete
09652ca683fd: Pull complete
e8e6d2a92a5b: Pull complete
cbb04c90d8ea: Extracting [==================================================>]  3.582GB/3.582GB
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I've tried severial times, but the process was stuck in the last extracting  process. My environment is as follows:
ubuntu 18.04
cuda 10.0
cudnn 7

**Comment by germanros1987** [comment]
@nuomizai this seems to be a problem with the configuration of your docker client. Not a problem on our side.
