### ISSUE TITLE
VehicleAI(Behavior tree)

### ISSUE THREAD

**Issue by xiaoyang666** [carla-simulator/carla#2979]
Hi,
   I always wanted to reproduce the automatic driving of the vehicle in my own scene.As far as I understand, the autonomous driving of UE4 can be constructed with a behavior tree.Does the automatic driving in Carla follow a fixed route set by people? I changed the position of Waypoints in the map, and the self-driving vehicles also changed, so I have the above questions. Or is vehicle autopilot related to UE4's behavior tree?
Thanks.

**Comment by germanros1987** [comment]
@xiaoyang666 are you referring to the Autopilot in CARLA? In other words, the Traffic Manager? I don't fully understand your question.

**Comment by germanros1987** [comment]
@xiaoyang666 is this still a problem?

**Comment by xiaoyang666** [comment]
Sorry to reply to you so late, I already understand that the carla simulator does not implement autonomous driving through behavior trees, thank you for your reply
