### ISSUE TITLE
Connect Carla with JavaScript

### ISSUE THREAD

**Issue by Shanmax1996** [carla-simulator/carla#2980]
Can I connect the Carla simulator with a javascript client?
Is it posible or imposible..

Example code in NodeJs...

const io = require('socket.io')();
var port = process.env.PORT || 2000;

io.on('connection', (socket) => {
  console.log('Simulator connected');
});

io.listen(port, function(){
  console.log('listening on *:' + port);
});

**Comment by germanros1987** [comment]
Definitely not trivial. The closest thing coming to my mind right now is this: https://github.com/carla-simulator/carlaviz
Please have a look at that.

**Comment by Shanmax1996** [comment]
okay..thank you soo much
