### ISSUE TITLE
Vulkan issue

### ISSUE THREAD

**Issue by yumianhuli2** [carla-simulator/carla#2984]
Hell0! I followed step
wget https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/UE_Patch/430667-13636743-patch.txt ~/430667-13636743-patch.txt
patch --strip=4 < ~/430667-13636743-patch.txt

and

./Setup.sh && ./GenerateProjectFiles.sh && make

when I used cd ~/UnrealEngine_4.24/Engine/Binaries/Linux && ./UE4Editor

I got below:

![Screenshot from 2020-06-23 11-30-00](https://user-images.githubusercontent.com/39210837/85357882-ee619e80-b544-11ea-859a-1be0972ce12b.png)

**Comment by maxc303** [comment]
Hi, If you are working on a device with Nvidia graphics card, you may try to install or upgrade your nvidia driver.

**Comment by germanros1987** [comment]
I am closing this. Please, re-open it if your issue persists.
