### ISSUE TITLE
Segfault when loading Open DRIVE maps

### ISSUE THREAD

**Issue by ThrashAbaddon** [carla-simulator/carla#2985]
Hello,

I've stumbled on two segfaults that happen when loading maps

* [Ex_Simple-LaneOffset.zip](https://github.com/carla-simulator/carla/files/4817690/Ex_Simple-LaneOffset.zip)
* [UC_Simple-X-Junction-TrafficLights.zip](https://github.com/carla-simulator/carla/files/4817692/UC_Simple-X-Junction-TrafficLights.zip)

I'm not sure are the bugs related but what I know is that `Map::CreateRtree` crashes on `Ex_Simple-LaneOffset`.

I'm using:
CARLA 0.9.9
Wndows 10 64bit.

**Comment by germanros1987** [comment]
@marcgpuig master of environments, could you look at this?
