### ISSUE TITLE
build error: CXX object LibCarla/cmake/server/CMakeFiles/c....dir/__/__/source/carla/opendrive/parser/GeometryParser.cpp. FAILED: 

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#2988]
hi
when i make launch, i got the 

**Building CXX object LibCarla/cmake/server/CMakeFiles/c....dir/__/__/source/carla/opendrive/parser/GeometryParser.cpp.
FAILED:** 

../../LibCarla/source/carla/opendrive/parser/GeometryParser.cpp:118:21: error: loop variable 'geo' of type 'const carla::opendrive::parser::Geometry' creates a copy from type 'const carla::opendrive::parser::Geometry' [-Werror,-Wrange-loop-construct]
    for (auto const geo : geometry) {
                    ^
../../LibCarla/source/carla/opendrive/parser/GeometryParser.cpp:118:10: note: use reference type 'const carla::opendrive::parser::Geometry &' to prevent copying
    for (auto const geo : geometry) {
         ^~~~~~~~~~~~~~~~

**Building CXX object LibCarla/cmake/server/CMakeFiles/c...rver.dir/__/__/source/carla/opendrive/parser/RoadParser.cpp.
FAILED:**

./../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:299:12: note: use reference type 'const carla::opendrive::parser::RoadTypeSpeed &' to prevent copying
      for (auto const s : r.speed) {
           ^~~~~~~~~~~~~~
                      &
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:310:23: error: loop variable 's' of type 'const carla::opendrive::parser::LaneSection' creates a copy from type 'const carla::opendrive::parser::LaneSection' [-Werror,-Wrange-loop-construct]
      for (auto const s : r.sections) {
                      ^
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:310:12: note: use reference type 'const carla::opendrive::parser::LaneSection &' to prevent copying
      for (auto const s : r.sections) {
           ^~~~~~~~~~~~~~
                      &
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:290:21: error: loop variable 'r' of type 'const carla::opendrive::parser::Road' creates a copy from type 'const carla::opendrive::parser::Road' [-Werror,-Wrange-loop-construct]
    for (auto const r : roads) {
                    ^
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:290:10: note: use reference type 'const carla::opendrive::parser::Road &' to prevent copying
    for (auto const r : roads) {
         ^~~~~~~~~~~~~~
                    &

**Building CXX object LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/road/element/Geometry.cpp.o
FAILED:**
../../LibCarla/source/carla/road/element/Geometry.cpp:196:28: error: implicit conversion from 'size_t' (aka 'unsigned long') to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
    double delta_p = 1.0 / number_intervals;

PS: i use clang++-10, ubuntu 20.04
i try to install clang++-8 on Ubuntu 20;04, but failed

any help are welcome

**Comment by germanros1987** [comment]
@Axel1092 could you please look into this?

**Comment by Axel1092** [comment]
Hi @gengtsh,
These errors are probably due to using clan10 instead of clang8. What problems did you find with installing clang8?
Unreal Engine is compiled with this version of clang and mixing version may produce errors. I suggest to try to find a way to use clang8.

**Comment by gengtsh** [comment]
hi, @Axel1092,
i remove everything related to clang10 and reinstall clang8, it looks like
this issues is fixed, but i encounter other issues: see the links below:
https://github.com/carla-simulator/carla/issues/3020
https://github.com/carla-simulator/carla/issues/3021
