### ISSUE TITLE
Are roadmarks available in opendrive standalone mode?

### ISSUE THREAD

**Issue by robin827** [carla-simulator/carla#2990]
Hi, I'm using the opendrive standalone mode and from what I have read, there are no possibilities to displaying roadmarks with this mode.
Am I missing something? If no, I was wondering if it is a potential feature in future releases?

Thank you!

**Comment by germanros1987** [comment]
We are not rendering lanemakrs, but if you visualize the map using the nonrendering_mode script: https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/no_rendering_mode.py

That should offer you more information.

In the future, we will provide the functionality to render lane markings and other road features.
