### ISSUE TITLE
OpenSCENARIO + Implemented Agent

### ISSUE THREAD

**Issue by lucasnmatias** [carla-simulator/carla#2993]
Hi,

I have one question about the support for OpenSCENARIO. I would like to know why we cannot run a scenario from OpenSCENARIO with an agent implemented?

`Agents are currently only compatible with route scenarios`

It would be interesting to define a scenario with OpenSCENARIO and test my agent on it.

**Comment by arjunsk07** [comment]
@lucasnmatias Did you find a solution to this?
