### ISSUE TITLE
Failed to open Descriptor File

### ISSUE THREAD

**Issue by pritishmishra703** [carla-simulator/carla#2995]
I have Installed **Carla 0.9.5** on my Windows PC. It has successfully installed and I have extracted all the files but when I open the CarlaUE4.exe File I am getting this error (See Image for more information).

![get_error](https://user-images.githubusercontent.com/55872694/85827582-2dd9f600-b7a4-11ea-8309-d513f3cdbc2a.PNG)

Please Help !! Even re-installed but the problem still persists.

**Comment by germanros1987** [comment]
First step...please update to CARLA 0.9.9. Does the problem persist?

**Comment by bernatx** [comment]
Hi, are you using the proper version of Unreal Engine for CARLA 0.9.5?

**Comment by pritishmishra703** [comment]
Yess !!
