### ISSUE TITLE
OpenAI-Gym-compliant environment

### ISSUE THREAD

**Issue by tgrel** [carla-simulator/carla#300]
I'm preparing an OpenAI-Gym-compliant RL environment for Carla. This should enable easier benchmarking of Reinforcement Learning algorithms on Carla. I will be documenting my progress in this issue and create a pull request once it's ready.

**Comment by nsubiron** [comment]
Awesome :) looking forward to it

**Comment by GokulNC** [comment]
Hello,
I have already done something similar to this:
**[Setting up CARLA for RL](https://github.com/GokulNC/Setting-Up-CARLA-RL)**

@tgrel Take a look into this if you're interested, or if you want to extend :)
