### ISSUE TITLE
make launch error: BuildLibCarla.sh: Building LibCarla "Server.Release" configuration.

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#3008]
hi, 
please help me out from these errors. i use ubuntu-20 and clang-10, thanks .

the details: 
Setup.sh: Success!
BuildLibCarla.sh: Building LibCarla "Server.Release" configuration.
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
-- Could not determine Eclipse version, assuming at least 3.6 (Helios). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build debug:   OFF
-- Build release: ON
-- Build test:    ON
-- Configuring done
CMake Warning in CMakeLists.txt:
  The build directory is a subdirectory of the source directory.

  This is not supported well by Eclipse.  It is strongly recommended to use a
  build directory which is a sibling of the source directory.

-- Generating done
-- Build files have been written to: /home/tgeng/work/carla/Build/libcarla-server-build.release
[6/52] Building CXX object LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/GeometryParser.cpp.o
FAILED: LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/GeometryParser.cpp.o 
/usr/bin/clang++  -DASIO_NO_EXCEPTIONS -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_NO_EXCEPTIONS -DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=true -DLIBCARLA_NO_EXCEPTIONS -DLIBCARLA_TEST_CONTENT_FOLDER=\"/home/aaaaa/work/carla/Build/test-content\" -DPUGIXML_NO_EXCEPTIONS -I../../LibCarla/cmake/../source -I../../LibCarla/cmake/../source/third-party -isystem ../boost-1.72.0-c10-install/include -isystem ../rpclib-v2.2.1_c2-c10-libcxx-install/include -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wpedantic -Wdeprecated -Wshadow -Wuninitialized -Wunreachable-code -Wpessimizing-move -Wold-style-cast -Wnull-dereference -Wduplicate-enum -Wnon-virtual-dtor -Wheader-hygiene -Wconversion -Wfloat-overflow-conversion -stdlib=libc++ -isystem /home/aaaaa/work/carla/Build/llvm-10.0-install/include/c++/v1 -fno-exceptions -fno-rtti -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wpedantic -Wdeprecated -Wshadow -Wuninitialized -Wunreachable-code -Wpessimizing-move -Wold-style-cast -Wnull-dereference -Wduplicate-enum -Wnon-virtual-dtor -Wheader-hygiene -Wconversion -Wfloat-overflow-conversion -stdlib=libc++ -isystem /home/aaaaa/work/carla/Build/llvm-10.0-install/include/c++/v1 -fno-exceptions -fno-rtti   -O3 -DNDEBUG -MD -MT LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/GeometryParser.cpp.o -MF LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/GeometryParser.cpp.o.d -o LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/GeometryParser.cpp.o -c ../../LibCarla/source/carla/opendrive/parser/GeometryParser.cpp
../../LibCarla/source/carla/opendrive/parser/GeometryParser.cpp:118:21: error: loop variable 'geo' of type 'const carla::opendrive::parser::Geometry' creates a copy from type 'const carla::opendrive::parser::Geometry' [-Werror,-Wrange-loop-construct]
    for (auto const geo : geometry) {
                    ^
../../LibCarla/source/carla/opendrive/parser/GeometryParser.cpp:118:10: note: use reference type 'const carla::opendrive::parser::Geometry &' to prevent copying
    for (auto const geo : geometry) {
         ^~~~~~~~~~~~~~~~
                    &
1 error generated.
[12/52] Building CXX object LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/RoadParser.cpp.o
FAILED: LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/RoadParser.cpp.o 
/usr/bin/clang++  -DASIO_NO_EXCEPTIONS -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_NO_EXCEPTIONS -DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=true -DLIBCARLA_NO_EXCEPTIONS -DLIBCARLA_TEST_CONTENT_FOLDER=\"/home/aaaaa/work/carla/Build/test-content\" -DPUGIXML_NO_EXCEPTIONS -I../../LibCarla/cmake/../source -I../../LibCarla/cmake/../source/third-party -isystem ../boost-1.72.0-c10-install/include -isystem ../rpclib-v2.2.1_c2-c10-libcxx-install/include -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wpedantic -Wdeprecated -Wshadow -Wuninitialized -Wunreachable-code -Wpessimizing-move -Wold-style-cast -Wnull-dereference -Wduplicate-enum -Wnon-virtual-dtor -Wheader-hygiene -Wconversion -Wfloat-overflow-conversion -stdlib=libc++ -isystem /home/aaaaa/work/carla/Build/llvm-10.0-install/include/c++/v1 -fno-exceptions -fno-rtti -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wpedantic -Wdeprecated -Wshadow -Wuninitialized -Wunreachable-code -Wpessimizing-move -Wold-style-cast -Wnull-dereference -Wduplicate-enum -Wnon-virtual-dtor -Wheader-hygiene -Wconversion -Wfloat-overflow-conversion -stdlib=libc++ -isystem /home/aaaaa/work/carla/Build/llvm-10.0-install/include/c++/v1 -fno-exceptions -fno-rtti   -O3 -DNDEBUG -MD -MT LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/RoadParser.cpp.o -MF LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/RoadParser.cpp.o.d -o LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/RoadParser.cpp.o -c ../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:299:23: error: loop variable 's' of type 'const carla::opendrive::parser::RoadTypeSpeed' creates a copy from type 'const carla::opendrive::parser::RoadTypeSpeed' [-Werror,-Wrange-loop-construct]
      for (auto const s : r.speed) {
                      ^
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:299:12: note: use reference type 'const carla::opendrive::parser::RoadTypeSpeed &' to prevent copying
      for (auto const s : r.speed) {
           ^~~~~~~~~~~~~~
                      &
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:310:23: error: loop variable 's' of type 'const carla::opendrive::parser::LaneSection' creates a copy from type 'const carla::opendrive::parser::LaneSection' [-Werror,-Wrange-loop-construct]
      for (auto const s : r.sections) {
                      ^
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:310:12: note: use reference type 'const carla::opendrive::parser::LaneSection &' to prevent copying
      for (auto const s : r.sections) {
           ^~~~~~~~~~~~~~
                      &
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:290:21: error: loop variable 'r' of type 'const carla::opendrive::parser::Road' creates a copy from type 'const carla::opendrive::parser::Road' [-Werror,-Wrange-loop-construct]
    for (auto const r : roads) {
                    ^
../../LibCarla/source/carla/opendrive/parser/RoadParser.cpp:290:10: note: use reference type 'const carla::opendrive::parser::Road &' to prevent copying
    for (auto const r : roads) {
         ^~~~~~~~~~~~~~
                    &
3 errors generated.
[15/52] Building CXX object LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/opendrive/parser/SignalParser.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Util/BuildTools/Linux.mk:120: LibCarla.server.release] Error 1

**Comment by germanros1987** [comment]
@bernatx any advice?
