### ISSUE TITLE
 ./autogen.sh: curl: not found

### ISSUE THREAD

**Issue by jithin90** [carla-simulator/carla#302]
Hi,
Got this error while installing Carla

Google Mock not present.  Fetching gmock-1.7.0 from the web...
./autogen.sh: 34: ./autogen.sh: curl: not found

Could anyone give me a solution?
Thank you..

**Comment by nsubiron** [comment]
Hi @jithin90,

You need to install `curl`. Check out the whole list of dependencies at the top of [How to build CARLA on Linux](http://carla.readthedocs.io/en/latest/how_to_build_on_linux/).

**Comment by jithin90** [comment]
Thank you.. nsubiron...
I am able to solve that..
