### ISSUE TITLE
More detailed documents of LibCarla

### ISSUE THREAD

**Issue by BigTailFox** [carla-simulator/carla#3025]
Hello,
I am using LibCarla to create a C++ client, however in the LibCarla documents little information was given, such as the units of variables, the world/vehicle/sensor coordinate systems. Is there any plan of a more detailed LibCarla document?

**Comment by germanros1987** [comment]
@BigTailFox tanks for your feedback

We are continuously working on improving the documentation. I am adding @sergi-e to this conversation so that he can hear directly from you about documentation improvements. Could you list the things that you would like to see improved?

Thanks.

**Comment by BigTailFox** [comment]
Thank you, below list my suggestions:
1. parameters' and arguments' descriptions in LibCarla, including units, coordinate systems.
2. detailed descriptions of some methods, such as `getID` and `getTypeID` in `carla::client::Actor`，`getID` in `ActorBlueprint`, a little bit confusion.

by the way, I compiled LibCarla of 0.9.9.4 version, and I want to get the bounding box of an actor, but `Actor` has a protected method `GetBoundingBox`, thus I can't access to it. In PythonAPI an `Actor` object is able to access it's bounding box directly by attribute `bbox`.

**Comment by sergi-e** [comment]
@BigTailFox  Thanks a lot for the suggestions! I will update this as soon as possible.
