### ISSUE TITLE
Default port 2000 unusable on Windows 10 with Hyper-V

### ISSUE THREAD

**Issue by lukase** [carla-simulator/carla#3029]
When running carla on a Windows 10 machine with latest updates and Hyper-V, it crashes due to an unhandled exception while trying to bind to port 2000 (TCP). This happens with release binaries as well as when running from the Unreal editor.

This is caused by a faulty W10 upgrade, to rectify and set reserved ports to the intended range, use `netsh int ipv4 set dynamic tcp start=49152 num=16384` [source](https://github.com/docker/for-win/issues/3171)

Could this be added to the documentation?

**Comment by germanros1987** [comment]
Why don't you launch it in a different port?

**Comment by badrow** [comment]
I don't even now what is Carla but I encounter a similar problem while listening on port 2000 on a linux machine running on hyper-v.

Port 2000 is not working outside the VM. Really weird hyper-v bug.
