### ISSUE TITLE
issues for ./UE4Editor--vulkan 

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#3030]
hi,
i encounter some issue  about ./UE4Editor, since vulkan is necessary for unrealengine 4.24, i install vulkan on the server
i use xshell (on windows 10) remote access ubuntu 18.04 server.
windows has 3 monitors
Ubuntu server have two nvidia Quadro P6000 cards
vulkaninfo: version: 1.2.141.2

  1. xshell: forward X11 connections to Xmanager
    when i run vulkaninfo, i got one line:
    ERROR at /root/sdk-build/1.2.141.2/source/Vulkan-Tools/vulkaninfo/vulkaninfo.h:240:vkEnumerateInstanceExtensionProperties failed with ERROR_INITIALIZATION_FAILED

    2. xshell : forward X11 X DISPLAY localhost:0.0
    when i run vulkaninfo, i get two lines:
    XCB failed to connect to the X server due to error:1.
    ERROR at /root/sdk-build/1.2.141.2/source/Vulkan-Tools/vulkaninfo/vulkaninfo.h:821: AppCreateXcbSurface failed to establish connection

3. when in turn off X11 Forward in xshell, login to ubuntu server though xshell and  run ./UE4Editor
i got: LogLinux: Warning: MessageBox: Failed to load Vulkan Driver which is required to run the engine.
The engine no longer fallbacks to OpenGL4 which has been deprecated.: Message:

when i run vulkaninfo, i can get some information in shell, but have some issues to run othe vulken tools. 
such as : when i run vkconfig & , i got the following errors:
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

then when i reset X11 DISPLAY to localhost:0.0, i got the following error: 
QXcbConnection: Failed to initialize XRandr
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

i guess there is something wrong with my X server, xcb or others, but i don't know how to fix it. 
i have struggled for two days, any help are welcome. thanks a lot

**Comment by germanros1987** [comment]
@gengtsh thanks for reporting your problem.

Let me try to make sense out of it since your description is a bit confusing. It seems you are describing a setup involving 2 machines? A Ubuntu 18.04 server and a Windows 10 node. 

Is the Ubuntu 18.04 running the server? Is the Windows 10 node running the client? Is that what you are trying to do?


P

**Comment by gengtsh** [comment]
Hi, germanros,
Yes, there are two machines, Ubuntu 18.04 server and windows 10 as client
,  which remotely access Ubuntu.

**Comment by germanros1987** [comment]
@gengtsh this has to do with the way the xserver is configured. A few points:

- Have you tried running the docker image of CARLA in the server?
- Do you really need X forwarding? Could you just set up a camera to receive images on the client?

**Comment by gengtsh** [comment]
thanks for your help @germanros1987.
i don't really need X forwarding, when i connection on monitor with ubuntu server and use teamviewer remotely access ubuntu and then i can run smoothly. 
and i will run docker image also in next step. thanks again.
