### ISSUE TITLE
How many Carla client can connect with one Carla Server? 

### ISSUE THREAD

**Issue by amitji-tech** [carla-simulator/carla#3039]
I want to use Carla in a typical client server architecture. Intend is to connect multiple client with one server.  So I can scale both client and server independently. Every client will act as a vehicle for simulation so I can run same/multiple scenario with different conditions simultaneously. So want to know Do we have any limit on how many Carla client can connect with Carla server?

**Comment by germanros1987** [comment]
@amitji-tech there are no specific limitations for the number of clients connected to a server. Limitations/constraints could arise when considering the amount of computation required by the server, in case multiple clients are requesting sensor simulation, etc.
