### ISSUE TITLE
How to get velocity at center of mass of ego vehicle?

### ISSUE THREAD

**Issue by gershom96** [carla-simulator/carla#3044]
I have been trying to get the velocity of the center of mass of my ego vehicle. 

1. I have tried to attach a center to the center of mass of the vehicle and then get its velocity. However, this failed. I assume this is due to the fact that you cannot obtain velocity at a specific point. 

I know you could use an accelerometer sensor and calculate this. However I am looking for a much elegant solution.

**Comment by germanros1987** [comment]
Hi @gershom96,

I don't believe the physics engine (PhysX) keeps the speed information at every point. Can't you just take the velocity of the vehicle as a rigid object?

@DSantosO should be able to add more to the topic.

**Comment by DSantosO** [comment]
Hello @gershom96,  
Like @germanros1987, I don't think you can recover the velocity at any point but, if all you need is the velocity in the center of mass, is there a reason why the get_velocity() of the actor is not good for you?
