### ISSUE TITLE
autoreconf: /usr/bin/autoconf failed with exit status: 1

### ISSUE THREAD

**Issue by jithin90** [carla-simulator/carla#305]
Hi,
Got this error while installing Carla

configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

Could anyone give me a solution?
Thank you..

**Comment by makan-dianka** [comment]
<h2>i'm getting the same error :</h2>         <h3>autoreconf: /usr/bin/autoconf failed with exit status: 1</h3>
