### ISSUE TITLE
Merging multiple point cloud from depth camera

### ISSUE THREAD

**Issue by Doodle1106** [carla-simulator/carla#3051]
Hi,

I am running the master branch of Carla on ubuntu 18.04 and I'm trying to build a lane mark map from depth camera and semantic segmentation camera on Sync Mode.

The process I followed is:

1. extract lane lines from segmentation;
2. project segmentation result to camera frame using pinhole camera model, call it **p3d_camera**;
3. transform **p3d_camera** to the vehicle frame according to https://github.com/carla-simulator/carla/issues/553, call the result
    **p3d_vehicle**;
4. transforming **p3d_vehicle** to the world frame using "self.car.get_transform()";
5. combine multiple captures and build the lane map;

I can get perfectly aligned map if the car goes straight (represented by the red dots in the image), however if I make a turn, I can see overlapping point clouds. 

![Screenshot from 2020-07-14 11-08-40](https://user-images.githubusercontent.com/26222197/87379271-69592a80-c5c2-11ea-83c4-fb7ccf205336.png)

![Screenshot from 2020-07-14 16-20-30](https://user-images.githubusercontent.com/26222197/87402419-201ed000-c5ee-11ea-970f-3138bca37140.png)

some transforms I used are:

1. Tvc:  camera to vehicle transform
                 [ [ 0, 0, 1,  0],
                 [ 1, 0, 0,  0],
                 [ 0, -1, 0, 0],
                 [ 0,  0, 0, 1]]

2. Twv: vehicle to world transform

```
    Twv = self.car.transform()
    Twv_matrix = get_matrix(Twv)
  
    def get_matrix(transform):
        rotation = transform.rotation
        location = transform.location
        c_y = np.cos(np.radians(rotation.yaw))
        s_y = np.sin(np.radians(rotation.yaw))
        c_r = np.cos(np.radians(rotation.roll))
        s_r = np.sin(np.radians(rotation.roll))
        c_p = np.cos(np.radians(rotation.pitch))
        s_p = np.sin(np.radians(rotation.pitch))
        matrix = np.matrix(np.identity(4))
        matrix[0, 3] = location.x
        matrix[1, 3] = location.y
        matrix[2, 3] = location.z
        matrix[0, 0] = c_p * c_y
        matrix[0, 1] = c_y * s_p * s_r - s_y * c_r
        matrix[0, 2] = -c_y * s_p * c_r - s_y * s_r
        matrix[1, 0] = s_y * c_p
        matrix[1, 1] = s_y * s_p * s_r + c_y * c_r
        matrix[1, 2] = -s_y * s_p * c_r + c_y * s_r
        matrix[2, 0] = s_p
        matrix[2, 1] = -c_p * s_r
        matrix[2, 2] = c_p * c_r
        return matrix
```
3. Twc: camera to world transform
    Twc = np.dot(Twv, Tvc)
             
4. finally, for each point in p3d_camera, p3d_world = np.dot(Twc, p3d_camera)

5. depth image is recovered by:
```     
image = self.depth_image
array = np.frombuffer(image.raw_data, dtype=np.dtype("uint8")) 
array = np.reshape(array, (image.height, image.width, 4)) # RGBA format
array = array[:, :, :3] #  Take only RGB
array = array[:, :, ::-1] # BGR
array = array.astype(np.float32) # 2ms
gray_depth  = ((array[:,:,0] + array[:,:,1]*256.0 + array[:,:,2]*256.0*256.0)/((256.0*256.0*256.0) - 1)) # 2.5ms
gray_depth = 1000 * gray_depth
```

Is there anything I am missing here?
Thanks for trying to help!
Joey

**Comment by Doodle1106** [comment]
the camera to world transform is from : Twv = self.camera.get_transform()

is it the right function to use?

**Comment by germanros1987** [comment]
@DSantosO could you help with this, please?

**Comment by DSantosO** [comment]
Sure, I will look into it.

**Comment by Doodle1106** [comment]
I can send a copy of my code if that helps. 
just let me know. Thanks for trying to help.

**Comment by DSantosO** [comment]
@Doodle1106 Yes, sure. Post it here or send it to me to daniel.santos@osvf.org and I will look into it as soon as I can.

**Comment by aczy118** [comment]
Hi there,

How did you project extracted lane lines information from segmentation camera to depth camera? Can you please share a snippet of your code?

**Comment by aczy118** [comment]
> I can send a copy of my code if that helps.
> just let me know. Thanks for trying to help.

Hi there,

How did you project extracted lane lines information from segmentation camera to depth camera? Can you please share a snippet of your code?
