### ISSUE TITLE
Masking road and roadlines using semantic segmentation

### ISSUE THREAD

**Issue by RadioGarret** [carla-simulator/carla#3053]
hi there!

I would like to ask you how to mask road and road lines using semantic segmentation. 

I'm doing multi-threading in python

here're some codes

def MultiThreading(queue):
     while exitFlag is not True:
          queue_item = queue.get()
          queue_item = queue_item[: ,: ,2] # this converts the image to grascale
          ...

Does anyone know how to mask road and road lines only? 
I've checked out the below images already

![image](https://user-images.githubusercontent.com/60842511/87369974-c0f49780-c5bc-11ea-8ebf-ff1c36982bb2.png)

![image](https://user-images.githubusercontent.com/60842511/87369961-b76b2f80-c5bc-11ea-9245-4fde05151618.png)

Thank you very much!

**Comment by Doodle1106** [comment]
I'm doing someting similar, and here is my implementation to extract lanes:

``` 
    # see https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/image/CityScapesPalette.h
    def extract_region(self, segmentation):
        
        H, W, C = segmentation.shape
        canvas = np.zeros((H, W), dtype=np.uint8)
        for v in range(H):
            for u in range(W):
                if segmentation[v, u, 0] == 50:
                    canvas[v, u] = 255
        
        return canvas
```

**Comment by germanros1987** [comment]
I don't believe this is the right place for this type of question. The forum is intended for that: [forum.carla.org](forum.carla.org). Please, create a question there. Leave GitHub for questions related to API behaviors and doubts. Use the forum for more general questions
