### ISSUE TITLE
new map: NPCs could not follow the way generated with RoutePlanner 

### ISSUE THREAD

**Issue by bosu3076** [carla-simulator/carla#3057]
Hello, I 'm trying to make new maps for Carla. As far as I know, new maps could be edicted in UE4, such as add created a new lane with Routeplanner. Although I have defined the route, which vehicles should follow, the NPCs with attribute"autopilot" seem like could not read those reference lines. 

Any ideas? Thank you~

**Comment by jackbart94** [comment]
Hi,

This changed after 0.9.7 with the introduction of Traffic Manager, which replaced the autopilot. Please, follow the new documentation for [making a new map](https://carla.readthedocs.io/en/latest/tuto_A_add_map/).
