### ISSUE TITLE
can i control the newly added vehicles light on or off？

### ISSUE THREAD

**Issue by pangxiao2013** [carla-simulator/carla#3067]

**Comment by glopezdiest** [comment]
Hey @pangxiao2013. Yes you definitely can. Take a look at [carla.VehicleLightState](https://carla.readthedocs.io/en/latest/python_api/#carlavehiclelightstate).

You can also use the [carla.LightManager](https://carla.readthedocs.io/en/latest/python_api/#carlalightmanager), to change the rest of the scene lights too
