### ISSUE TITLE
Semantic Tag for new props does not work Carla 0.9.9

### ISSUE THREAD

**Issue by Jabkowsky** [carla-simulator/carla#3070]
Window version build from source ( 0.9.9.3 ) 
I have add the new props to .json file : ( Default.Package.json )
Example:
		{
			"name": "PedCross",
			"path": "/Game/Carla/Static/Props/Street/SM_PedCross.SM_PedCross",
			"size": "Small",
			"tag": "TrafficSigns"
		},

After build I can spawn "PedCross" sign as i need, but this "actor" does not appear on camera semantic segmentation as "TrafficSigns". ( tag ). All new props added are visible on segmentation as Unlabeled = 0 even if i specified the tag in .json file.

Can you help me to fix this issue ? Am I doing something wrong ?

**Comment by germanros1987** [comment]
@marcgpuig since you are working on this, could you please provide a solution?

**Comment by Jabkowsky** [comment]
EDIT: i tried with properly tagged stop sign in town10hd and add the same stop sign to jason file with same tag. It look like this
![image](https://user-images.githubusercontent.com/44050097/87913995-49b57c80-ca70-11ea-8f6b-455c250de89c.png)
Originally added stop sign to town is segmented with TAG = 12 correctly but spawned same sign :
		{
			"name": "Stop",
			"path": "/Game/Carla/Static/TrafficSigns/Stop/SM_stopSign.SM_stopSign",
			"size": "Small",
			"tag": "TrafficSigns"
		}
Is not. It appears only with TAG = 0 :
![image](https://user-images.githubusercontent.com/44050097/87914193-9600bc80-ca70-11ea-9b59-02b07f7ec4d8.png)

And now difference in carlalic ( c++ ) i found :
Original stop sign is such actor -> 
![image](https://user-images.githubusercontent.com/44050097/87914318-c2b4d400-ca70-11ea-83ae-4c10201d9ca7.png)

It has and correct tag "semantic_tags"[1] = 12 

But props actor added to map while "playing" ->
![image](https://user-images.githubusercontent.com/44050097/87914444-eb3cce00-ca70-11ea-9f25-ab9c038d76d1.png)

has empty semantic_tags property.
