### ISSUE TITLE
labels for LiDAR data

### ISSUE THREAD

**Issue by tiger-bug** [carla-simulator/carla#3079]
Good afternoon,

I was curious if there will be a label feature added to the LiDAR sensor.  I know several other people have posted about this in [issue 1751](https://github.com/carla-simulator/carla/issues/1751) and [issue 516](https://github.com/carla-simulator/carla/issues/516), and that individual has a version of carla with labels for LiDAR.  Is this something that the developers are looking to do in the future?  I am using Carla, carla-ros-bridge, and SLAM to create point clouds for DL training.  Thank you!

**Comment by germanros1987** [comment]
Future versions of CARLA will provide ground truth for point clouds. We will visit this topic during next releases. If this has a high priority for you and you have some bandwidth, perhaps you could contribute a solution...? Contributions are very appreciated!

**Comment by germanros1987** [comment]
@tiger-bug good news. This feature has been recently developed and will be part of 0.9.10, expected in a few days.

**Comment by tiger-bug** [comment]
Thank you!!! That is awesome!

**Comment by marcgpuig** [comment]
Closing the issue since this has entered in master in #3131!

**Comment by visakhchikku** [comment]
Is it possible to save lidar data as .pcap file using carla?
