### ISSUE TITLE
Is that something wrong about IMU document and code in manual_control.py about compass?

### ISSUE THREAD

**Issue by JarvanI** [carla-simulator/carla#3081]
Hi, everyone, I found somthing that made me confused and I hope someone can help me.
Here is a piece of code in manual_control.py, from line 528 to line 532
`        compass = world.imu_sensor.compass `
       ` heading = 'N' if compass > 270.5 or compass < 89.5 else ''`
     `   heading += 'S' if 90.5 < compass < 269.5 else ''`
    `    heading += 'E' if 0.5 < compass < 179.5 else ''`
       ` heading += 'W' if 180.5 < compass < 359.5 else '' `
Is the east and west direction opposite to normal？If the right hand direction is north, then up is west, and down is east.  So in my opinion,     `    heading += 'W' if 0.5 < compass < 179.5 else ''`and ` heading += 'E' if 180.5 < compass < 359.5 else '' ` is right.

**Comment by germanros1987** [comment]
@marcgpuig could you take a look at this issue?

**Comment by marcgpuig** [comment]
Hi @JarvanI 
> If the right hand direction is north, then up is west, and down is east

I'm not sure to correctly understand your point.
If I've done it right I'm following the angle of a standard compass, where North is at 0° (or 360°), East at 90°, South at 180° and Weast at 270°.
