### ISSUE TITLE
How to set a  special middle point using basic_agent

### ISSUE THREAD

**Issue by HuangSecretKey** [carla-simulator/carla#3082]
The startpoint and endpoint can be set when using the basic_agent.py. But I also want the vehicle can pass through a special middle point. But how to realize it. The carla version is 0.9.8.

**Comment by germanros1987** [comment]
You can try to inject the point in the local plan created by the local planner. This is what is going on under the hood of the BasicAgent:

From the current point (starting point) and the provided target point, we invoke a global router, which provides a list of high-level waypoints. Then these waypoints are passed to the local_planner, which will command the vehicle to reach those waypoints. So, basically your best option would be to inject your point in the queue of the local_planner and let it execute it.

Hope this helps.
