### ISSUE TITLE
New maps with road construction zone: How to generate reference routes manually? 

### ISSUE THREAD

**Issue by bosu3076** [carla-simulator/carla#3084]
Hello guys. I'm trying to make new maps with some road constructions, that means I need to generate the routes by myself, since the automatically generated routes by OpenDRIVE Actor in UE4 could not be used. However, I tried RoutePlanner tool, I am quite confused about how does it work. 
![Bildschirmfoto vom 2020-07-20 16-02-08](https://user-images.githubusercontent.com/59999696/87948369-e560e000-caa4-11ea-9bd5-b6eca35daf57.png)
In this example, I drew a number of routes with RoutePlanner- the white splines, and kept some default routes- red ones, which were generated automatically by OpenDRIVE Actor.
My problems are:
1. Why the default and self-defined route look different? Is there anything I set wrong?
2. Those routes could not be followed by the vehicles with autopilot. The documentation about Traffic Manager has no description of this part. I wonder  whether the Traffic Manager could be used in this kind of situation.

Version Infos:
-Ubuntu 16.04
-Carla 0.9.8
-Unreal Engine 4.22
-RoadRunner 2020a

Thank you!

**Comment by germanros1987** [comment]
@marcgpuig do you have some cycles to help with a simple explanation of the RoutePlanner and/or the OpenDRIVE Actor?

**Comment by XieJinLiang** [comment]
What software are you using? roadrunner? Why does the interface look different from my roadrunner?

**Comment by bosu3076** [comment]
> What software are you using? roadrunner? Why does the interface look different from my roadrunner?

Hi, actually this is a screenshot of Unreal Engine 4 https://www.unrealengine.com/en-US/. I have imported the fbx-files into UE4 and want to edit them with  Carla plugins. However, it doesn't work well. These days I changed my plan generating routes directly in Roadrunner.

**Comment by marcgpuig** [comment]
Hi @bosu3076, sadly this is not possible within Unreal Engine, we strongly rely on OpenDRIVE right now to retrieve information from the road. The `RoutePlanners` and the `OpenDRIVE Actor` are not used anymore but for automatically placing the spawn points and visualizing the shape of the used OpenDRIVE. You need to do everything with RoadRunner.

**Comment by ehsankf** [comment]
How could we add work zone construction to the existing maps?
