### ISSUE TITLE
Carla wastes CPU ressources in sync mode between ticks

### ISSUE THREAD

**Issue by hh0rva1h** [carla-simulator/carla#3085]
Consider the following code snippet:
```
import carla
import time

client = carla.Client("localhost", 2000)
world = client.load_world("Town04")

settings = world.get_settings()
settings.fixed_delta_seconds = 0.05
settings.synchronous_mode = True
world.apply_settings(settings)

world.tick()
time.sleep(120)
world.tick()
```
Between the ticks Carla is frozen so I would expect it not to use much CPU resources, however actually Carla is always hogging the CPU:

![Screenshot from 2020-07-20 21-01-09](https://user-images.githubusercontent.com/61889859/87975948-962ea580-cacc-11ea-9533-77f3a5322283.png)

It would be great if Carla wouldn't waste resources when there is no simulation to do.

**Comment by germanros1987** [comment]
Hi,

@hh0rva1h we will definitely try to keep improving the performance of CARLA and reducing the amount of computation needed. Now, while you are not ticking the server, the server is still doing stuff. At a minimum is listening for other possible clients (there could be more than 1 client trying to get things done). 

We will try to make this aspect more efficient in the future. I will tag this issue as a feature request.

**Comment by hh0rva1h** [comment]
@germanros1987 Could you do something about stale bot closing issues that are triaged other than question? Imho it does not make much sense to close a issue triaged as bug or feature request automatically.
