### ISSUE TITLE
0.9.8 - Cannot create navigation bin file if import by Create one Blueprint asset

### ISSUE THREAD

**Issue by youngsend** [carla-simulator/carla#3092]
Hi, everyone.
I am new to carla. I am using 0.9.8 and I want to spawn walker on my own map.

What I have done:
When I import my test.fbx into carla Unreal Editor by _Create one Blueprint asset_, ***FbxScene*** blueprint is generated and all StaticMeshes are in it. I cannot generate the pedestrian navigation bin file.
When I import test.fbx into Editor by *Create Level Actors*, *FbxScene* is not generated (SceneNode is generated) and I succeed in generating bin file and spawning walkers on sidewalk (using the provided RecastBuilder).
However, I find that the latter import method loses RoadRunnerTrafficJunction information compared to the former method.

My question:
Can I generate pedestrian navigation bin file while importing by *Create one Blueprint asset*?
I think this should be possible, because all tutorials I found choose *Create one Blueprint asset*.
I'm confused because in those tutorials' screenshots, road static meshes appeared in World Outliner, while my static meshes are all in FbxScene blueprint class.

Thank you.

**Comment by youngsend** [comment]
I deleted the Sidewalk StaticMesh in FbxScene and added it (it is in Static folder) again in World Outliner.
After that I succeeded in creating pedestrian navigation file and spawning walker on sidewalk.

However, I still want to ask why navigation bin file cannot be created with FbxScene holding the Sidewalk StaticMesh.

**Comment by germanros1987** [comment]
@bernatx could you help with this?

**Comment by bernatx** [comment]
Hi,
Have you any file to share so we can test it?
I suppose the FBX has something that has problems when it is imported to Unreal (we use the FBX importer from Unreal).
