### ISSUE TITLE
Include LibCarla in Visual Studio project

### ISSUE THREAD

**Issue by AdelinaK** [carla-simulator/carla#3094]
Hello I wonder if it's possible to include the Carla C++ library in a Visual Studio project, use the methods it provides and also add another external libraries I need to work with in that project. If it's possible how can I exactly do that? Thank you.

**Comment by germanros1987** [comment]
@Axel1092 could you help with this?

**Comment by Axel1092** [comment]
Hi @AdelinaK, maybe you already solved your issue but you will find the library and include files of Carla in PythonAPI/carla/dependencies once you compile carla. You can link these to your application to enable carla.
