### ISSUE TITLE
How to add new light source on top of the vehicle? 

### ISSUE THREAD

**Issue by YunzeMan** [carla-simulator/carla#3097]
Hi,

I am currently work on adding new source light on top of the vehicle. For example a vehicle roof-mounted light.

I wonder is it possible to customize it in python API or i need to do it in Unreal engine?

I've been working on it in Unreal for a while. But I don't know if this is the right direction to go.

Thanks!

**Comment by germanros1987** [comment]
You need to do it from Unreal Engine. @XGodina could you help with this?

**Comment by YunzeMan** [comment]
Thanks for your reply! @germanros1987 
I did see the document [https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/](https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/), and I followed it to create a car model.

However, since I'm adding a new top-mounted light, and I want to be able to toggle it just like other light sources, I wonder what is the right way to do this. Do I have to somehow bound this light to the reserved light instance carla.VehicleLightState.Special1? Thanks

**Comment by germanros1987** [comment]
@Madecu you have worked on this. Could you help?

**Comment by Madecu** [comment]
Hi. You need to add a light inside the blueprints car and name it in the "Variable name" slot as 'special1-X'

![image](https://user-images.githubusercontent.com/54811869/88373226-bf368b00-cd97-11ea-960c-a321e80d7648.png)
