### ISSUE TITLE
ModuleNotFoundError: No module named 'libad_rss_python3'

### ISSUE THREAD

**Issue by vishal-246** [carla-simulator/carla#3099]
Hi, 

I've built RSS variant of carla and with python3 i have the libad_rss_python3 import error. error is shown below 

`$ python3 manual_control_rss.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "manual_control_rss.py", line 77, in <module>
    from rss_sensor import RssSensor # pylint: disable=relative-import
  File "/carla/carla-0.9.9.4/PythonAPI/examples/rss/rss_sensor.py", line 21, in <module>
    from rss_visualization import RssDebugVisualizer # pylint: disable=relative-import
  File "/carla/carla-0.9.9.4/PythonAPI/examples/rss/rss_visualization.py", line 26, in <module>
    import libad_rss_python3 as rss
ModuleNotFoundError: No module named 'libad_rss_python3'
` 

Please help me to solve this.

Thank you.

**Comment by germanros1987** [comment]
@fpasch could you please help with this?

**Comment by fpasch** [comment]
That error looks like you're using a Python Egg without RSS enabled. Please ensure, that
1. you've build it with rss enabled (e.g. `make PythonAPI.rss.2`)
2. the search order in your PYTHONPATH is pointing to the right egg.

**Comment by vishal-246** [comment]
Hi @fpasch  Sorry for the late replay.

A1. Yes i have built it with rss enabled only difference is i havent mentioned version like u have suggested. B'coz since `make PythoonAPI.rss` it self takes care of generating egg for python versions.

A2. For Python2 API its pointing to the right path as well as for Python3 if not it would have thrown the carla NoModule Found error.
