### ISSUE TITLE
Carla cpp client - RPC

### ISSUE THREAD

**Issue by meitalcohenyaacobi** [carla-simulator/carla#3100]
Hi ,
We would like to run a self-implemented client for connecting to the simulator server and receive sensory data from the simulator. The client will run on remote machine and will connect to CARLA via RPC calls. 

As far as I understand from the examples: 
1. The RPC server uses rpclib, which uses MsgPack for serialization (https://github.com/carla-simulator/rpclib , https://github.com/carla-simulator/carla/issues/555)
2. rpc of  LibCarla ([LibCarla\source\carla\rpc](http://carla.org/Doxygen/html/dir_83201f30ace02cdf218980110872f8a7.html))

what are the differences ?
what should we use?

Thank you.

**Comment by germanros1987** [comment]
@nsubiron @bernatx could you comment on this?

**Comment by bernatx** [comment]
Hi,
CARLA uses the RPCLib library for all the RPC commands.
The RPC folder in LibCarla is just the serialization of all commands that CARLA uses. There, we use the RPCLib for the serialization of our commands with MsgPack.
So, there is only one RPC library to use.

**Comment by meitalcohenyaacobi** [comment]
Thanks a lot :)
