### ISSUE TITLE
1 or 2 FPS with synchronous_mode on GPU while recording image

### ISSUE THREAD

**Issue by bender2po** [carla-simulator/carla#3101]
Hi,
I am running the 'synchronous_mode.py' with one change. That is, I am recording/saving images at 1280x720.
Normally, when i don't record the image, I get around 25-40 FPS. However, when I start recording the image then I get less than 5 FPS. Also, I observed that with less resolution, like 600x400, the performance improves to higher FPS.

Could you tell if there is anyway to get higher FPS for image-saving with 1280x720 ?

I am using: Carla 0.9.9, Windows 10, Quadro P5200, 32GB RAM.

**Comment by germanros1987** [comment]
@bender2po I believe this makes a lot of sense. That is a demo script, if you want better performance, write a new script to do the saving of frames in a separate thread.
