### ISSUE TITLE
Having Problem with Importing Carla Dependencies

### ISSUE THREAD

**Issue by HuangSecretKey** [carla-simulator/carla#3107]
when I implement a other's program, I found the following error when importing the dependencies, so is it related with the vision, and i use 0.9.8.

```
from carla import sensor
from carla.client import make_carla_client, VehicleControl
from carla.settings import CarlaSettings
from carla.tcp import TCPConnectionError)
```
I get the error that there is no sensor in carla.

**Comment by germanros1987** [comment]
Please, could you provide more information, e.g. the trace?

**Comment by Axel1092** [comment]
Hi @HuangSecretKey, maybe you are experiencing the same problem as in issue #3083. Check if that solution works for you.
