### ISSUE TITLE
RuntimeError: Resource temporarily unavailable after start and end of ~350 clients

### ISSUE THREAD

**Issue by AIasd** [carla-simulator/carla#3109]
Hi,

I encountered "RuntimeError: Resource temporarily unavailable" for the line initializing a new client `client = carla.Client('localhost', 2000)` after I start, run simulation, and end ~350 clients sequentially on the same carla server.

I noticed that the opened files by the carla server process will always increase by 2 after each start and end of one client. Meanwhile, TCP connection will increase by 1 each time. Thus, these numbers keep going up as I run more client sessions.

It seems that they are not used after the end of corresponding clients but are not destroyed properly. Is there a way to manually release these resources? Is it possible to run more client sessions (>350) sequentially on the same server?

Thanks!

**Comment by germanros1987** [comment]
@bernatx could you please look into this issue?
