### ISSUE TITLE
GNSS sensor problem

### ISSUE THREAD

**Issue by AndrewChaschin** [carla-simulator/carla#3113]
Hello dear community!
Where is the GNSS sensor located on the car model?
At what point (area)?
This is necessary to simulate antenna offset.
Sorry for my English (google translate)
![image](https://user-images.githubusercontent.com/24415915/88548633-32aef580-d041-11ea-9274-3db34f8ceae5.png)

**Comment by germanros1987** [comment]
@AndrewChaschin you can mount the GNSS sensor wherever you want. The API allows you to indicate where the GNSS sensor (or any other sensor) is located.
