### ISSUE TITLE
carla speed up play

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#3118]
Can Carla-0.9.9 speed up the play ？

**Comment by germanros1987** [comment]
Could you please elaborate your question?

**Comment by whuxhzhang** [comment]
> Could you please elaborate your question?
OK，
When I set the speed low, it takes a long time to see the results. So I wonder if we can speed up Carla and see the results quickly，like a video playing at double speed.

**Comment by germanros1987** [comment]
No, unfortunately, is not that simple.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
