### ISSUE TITLE
Changing and adding Actorspawnresult messages

### ISSUE THREAD

**Issue by gsujansai** [carla-simulator/carla#3121]
Hi 

I want to add a new Actorspawnresult message. As a first test, I modified the collision message as a sanity check. I modified the following file "carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorSpawnResult.cpp" [ActorSpawnResult](https://github.com/carla-simulator/carla/blob/a98406924d71ed77e0853150fb195d180a0b7e61/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorSpawnResult.cpp)

`case EActorSpawnResultStatus::Collision:
      return TEXT("Spawn failed because of collision at spawn position, ----addition----");`

I then rebuild using `make CarlaUE4Editor`. But the spawn message is still the default message. Am i modifying the wrong file or am i missing some step for the rebuild? I use `make CarlaUE4Editor` as the [build_system](https://carla.readthedocs.io/en/latest/build_system/) document states that this needs to be build to CarlaUE4 and CarlaPlugin

**Comment by germanros1987** [comment]
@bernatx could you please help with this?
