### ISSUE TITLE
Patch for Unreal in Linux build

### ISSUE THREAD

**Issue by yuanz4** [carla-simulator/carla#3125]
Hello,
I follow the step in "Linux build", but seems I can't patch with
`wget https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/UE_Patch/430667-13636743-patch.txt ~/430667-13636743-patch.txt
patch --strip=4 < ~/430667-13636743-patch.txt`
Is it some path problem? It just ask me the "File to patch"
Thanks!

**Comment by gsujansai** [comment]
Hey, The patch is probably downloaded inside your Unreal folder if you ran the wget from that location. Check the location of 430667-13636743-patch.txt and run the patch command at that location

**Comment by yuanz4** [comment]
Thanks! I run it again and it works
