### ISSUE TITLE
White image with default attributes

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/carla#3127]
Setting the default values (as described in the documentation) leads to a completely white camera image.,

                        bp.set_attribute('shutter_speed', '60.0')
                        bp.set_attribute('iso', '1200.0')
                        bp.set_attribute('fstop', '1.4')
                        bp.set_attribute('min_fstop', '1.2')
                        bp.set_attribute('exposure_mode', 'manual')
                        bp.set_attribute('exposure_compensation', '3.0')
                        bp.set_attribute('exposure_min_bright', '0.1')
                        bp.set_attribute('exposure_max_bright', '0.3')

**Comment by germanros1987** [comment]
@marcgpuig --master of sensors, ruler of blueprints, breaker of shaders-- do you care to comment?

**Comment by fpasch** [comment]
solved by #3115
