### ISSUE TITLE
PythonAPI world.get_lightmanager wrong name in documentation

### ISSUE THREAD

**Issue by gsujansai** [carla-simulator/carla#3138]
Hi, 

The documentation for LightManager in PythonAPI has the function name as get_light_manager [link](https://carla.readthedocs.io/en/latest/python_api/#carla.World.get_light_manager).

But the function name is 
`.def("get_lightmanager", CONST_CALL_WITHOUT_GIL(cc::World, GetLightManager))` in [world.cpp](https://github.com/carla-simulator/carla/blob/master/PythonAPI/carla/source/libcarla/World.cpp)

Will the documentation be updated?

**Comment by germanros1987** [comment]
@sergi-e could you please take care of this?

**Comment by sergi-e** [comment]
Hi, @gsujansai !

This issue was properly fixed. Thanks a lot for reporting it :)

**Comment by analog-cbarber** [comment]
This was only fixed for the python api doc for `World` there are still places in the documentation that refer to the incorrect name: https://github.com/carla-simulator/carla/search?q=get_light_manager

**Comment by sergi-e** [comment]
Hi, @analog-cbarber !

Completely true. These instances have been fixed in this branch: https://github.com/carla-simulator/carla/tree/sergi-e/warning-docs-version and will be merged as soon as possible, along with other minor changes.
