### ISSUE TITLE
[Request] Installation guide is required for MACOS users

### ISSUE THREAD

**Issue by Almaz-KG** [carla-simulator/carla#3140]
Hi, all! Hope you are well)

Guys, could you help me, please! I wanna make some stuff using Carla Simulator, but I'm struggling with installation process on my macOS. What can I do with installation? Is it possible to install a simulator on MacOS, or how can I run it (maybe using some docker-linux image or in cloud machine). I need the easiest way to install and start with your great project.

Thanks in advance. Also, after some research, I can add some guidance in documentation if needed.

**Comment by germanros1987** [comment]
@Almaz-KG We currently don't have proper MacOS support. The closest we got is this PR: #2433
