### ISSUE TITLE
Is it possible to limit cpu utilization for the client python process?

### ISSUE THREAD

**Issue by AIasd** [carla-simulator/carla#3157]
Hi,
I notice that the python process will take all the available cpu resources. 
In my case, I have 14 cores with 28 threads so 2800% cpu in total. When I run the simulator and a client process, the CarlaUE4-Linux process takes ~130% cpu while the client python process ~2600% cpu.
I I tried to set the worker_threads parameter of carla.Client to 1 but that seems to not have influence to cpu utilization. 
I wonder if it is possible to limit the cpu utilization of the client python process?

**Comment by germanros1987** [comment]
Sorry for the delay. We are in the middle of vacation season. @marcgpuig limiting the number of threads used by the libcarla makes a lot of sense. What do we know about this? Can we add this to the API?
