### ISSUE TITLE
specify which GPU to run Carla

### ISSUE THREAD

**Issue by carlaUE4new** [carla-simulator/carla#3159]
I am using Carla 0.9.9 version in Windows 10 and I have 3 GPUs. is there a way that I can specify Carla to run on Nvidia GPU?

**Comment by germanros1987** [comment]
I am not a Windows person, but have you tried this?

https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

**Comment by carlaUE4new** [comment]
> I am not a Windows person, but have you tried this?
> 
> https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

thank you, this works
