### ISSUE TITLE
ScenarioManager got Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by DevotionGit** [carla-simulator/carla#3165]
Hi,I got the flowing error,How can we fix it?

'''
Start Scenario map  config !
load opendrive map 'Road.xodr'.
set weather preset 'ClearNoon'.
Start Scenario runner !
Preparing scenario: ScenarioVehicles_2
ScenarioManager: Running scenario ScenarioVehicles
Segmentation fault      (core dumped) 
python scenario_runner.py --port 2000 --scenario ScenarioVehicles_2 --configFile ./ScenarioVehicles.xml --output
'''
ps:
CARLA Server Running  under docker
Scenario_runner  Running  under localhost

OS:ubuntu 18.04
CARLA:0.9.9
Scenario_runner:0.9.9
Docker:19.03.12, build 48a66213fe

**Comment by germanros1987** [comment]
@DevotionGit we are going to need some additional information. Are you using your own map (Road.xodr)? 
If so, can you run simple scripts, such as the spawn_npc and manual_control?
