### ISSUE TITLE
assertion error when trying to run carla on windows

### ISSUE THREAD

**Issue by omarchakroun** [carla-simulator/carla#3171]
Hi there,
i'm newby in carla really newby and just get it installed on windows based on the steps on the documentation. i was trying to run town03 example to make sure that everything is working but i got an assertion error. when generating the project and compiling it under VS there is no error. can someone please help.
thank you and best regards.

![Sans titre](https://user-images.githubusercontent.com/68866773/89558520-4ea15c80-d7e2-11ea-9956-5ed310b69c85.png)

**Comment by germanros1987** [comment]
Sorry for the delay, we are in the middle of the vacation season. @Axel1092 could you help with this?

**Comment by omarchakroun** [comment]
Hi germanros, 
Yesterday in fact, i was able to resolve the issue. I was using the wrong asset package. I was using the assets from the 0.9.9 with carla version 0.9.10. 
Thank you again for the support,
Omar
