### ISSUE TITLE
Weird dynamic performance of the vehicle

### ISSUE THREAD

**Issue by Glazyee** [carla-simulator/carla#3172]
Hi, as you can see in the diagram, VW and Kia are two vehicles that I have spawned in the scenario. For example, the value of the throttle of VW is almost set to 1 in this case, but the acceleration VW varies unreasonably (dark blue line) during this process. Could someone kindly explain to me, how come this happens? Thank you so much.
![Validierung_CarlaBaseline_Acc](https://user-images.githubusercontent.com/20241631/89629694-91286f00-d89e-11ea-98c2-8d69f1b7c0c8.jpg)

**Comment by BigTailFox** [comment]
Hello, 
I have also met this problem, I guess the relationship between `throttle` and `acceleration` of a Carla vehicle is nonlinear, and the auto gear-box may also have effection. I am now using a PID controller to follow the expected acceleration. Do you get accelerations from an IMU sensor or the Actor API, they don't match either.

**Comment by Glazyee** [comment]
Hi, thanks a lot for your information. I got the accelerations from Actor API and also set the auto gearbox as True. The velocity of the vehicle gets down from 140km/h to about 70km/h at full throttle, then start to accelerate a little bit. For me, it's still strange.
So, by using a PID controller, is the result acceptable for you now?

**Comment by BigTailFox** [comment]
A bit weird for the negative acc with the positive throttle in this graph. I haven't met this situation. Turning off auto gear-box and setting a fixed gear ratio, checking the brake/handbrake and the road gradient/friction might help.

**Comment by germanros1987** [comment]
Sorry for joining the party late. We are catching up after the summer break. @jackbart94 and your help is required to clarify this doubt.

**Comment by jackbart94** [comment]
Hi,

Sorry for taking some time, I was wondering what script are you using for this particular example? Is Traffic Manager involved, or are you using one of the agents? It's very important because the weird behavior of the throttle might be because the PID isn't tuned properly, and might be one of the older agents.

**Comment by Glazyee** [comment]
> A bit weird for the negative acc with the positive throttle in this graph. I haven't met this situation. Turning off auto gear-box and setting a fixed gear ratio, checking the brake/handbrake and the road gradient/friction might help.

Thanks a lot for the advice. And sorry for the late feedback. I've been stuck in other works in the last two months. It seems a little better but still problematic by adjusting the gearbox setting. As for the other parameter, they should not be causality.

**Comment by Glazyee** [comment]
> r

**Comment by Glazyee** [comment]
> Hi,
> 
> Sorry for taking some time, I was wondering what script are you using for this particular example? Is Traffic Manager involved, or are you using one of the agents? It's very important because the weird behavior of the throttle might be because the PID isn't tuned properly, and might be one of the older agents.

Hi,

sorry for the la.. late reply. I use also a package called scenario runner. And it offers a function to define behaviors of vehicle, such as waypointfollower, keepvelocity and so on. And in this context, a PID-controller for the velocity was applied.
I suppose that the problems should not come from the behavior of the throttle or the PID. Because even if the throttle was set to 100%, it came to a deceleration too.
