### ISSUE TITLE
Connection Error in Building

### ISSUE THREAD

**Issue by Gatsby23** [carla-simulator/carla#3177]
I'm new begininger in Carla, and follow the building process, I get this error, how to fix it ?
![Screenshot 2020-08-11 08:41:51](https://user-images.githubusercontent.com/18000675/89844683-e8845300-dbae-11ea-9915-1a915b424ec3.png)

**Comment by thytless** [comment]
Hey would you please provide detailed info about your problem such as in which step did this happen, and how could we reproduce it?
Looks like you are running into a network trouble though...

**Comment by germanros1987** [comment]
@Gatsby23 is this issue still bothering you or should we just close it?

**Comment by Gatsby23** [comment]
> @Gatsby23 is this issue still bothering you or should we just close it?

OK, I can build this it now, I close the issue.
