### ISSUE TITLE
fatal error: rpc/msgpack.hpp: No such file or directory

### ISSUE THREAD

**Issue by yumianhuli2** [carla-simulator/carla#3179]
Hello!Carla Team!
fatal error: rpc/msgpack.hpp: No such file or directory
 #include <rpc/msgpack.hpp>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

And I have run this repo: https://github.com/carla-simulator/rpclib.git
cmake and make:)

plz tell me how to fix this,thanks!

**Comment by germanros1987** [comment]
@bernatx could you help this user?

**Comment by xiaoyaodingchunqiu** [comment]
how to solve this problem, I also encountered this problem
