### ISSUE TITLE
How visualize the carla road network map on rviz?

### ISSUE THREAD

**Issue by XieJinLiang** [carla-simulator/carla#3182]
Hi,
Is there a way to visualize the carla opendrive map on rviz?What  message type should I use?Or can I only draw it line by line manually?

**Comment by germanros1987** [comment]
Hi @XieJinLiang there is no specific message for that, but you could take a look at this: https://github.com/carla-simulator/carlaviz

The message should be compatible with rviz, so that is your best starting point.

**Comment by Roosstef** [comment]
@XieJinLiang Did you find a way to visualize it on rviz?

**Comment by minhaj6** [comment]
@XieJinLiang @Roosstef did you guys figure out how to draw that on rviz? 

I need to visualize the vehicle trajectories. I was thinking about the Carla_Painter in CarlaViz, but unfortunately the project looks abandoned and the author hasn't implemented the functionality.
