### ISSUE TITLE
Creating maps using the new Google cloud platform!?

### ISSUE THREAD

**Issue by Abanoub-G** [carla-simulator/carla#3185]
Hi Carla Team,

I was wondering if you had in mind to include getting maps from the new Google cloud platform into CARLA in your future releases? [https://cloud.google.com/blog/products/maps-platform/google-maps-platform-gaming-services-now-available-everyone](url)

I think that would be a very powerful addition to CARLA... and will allow the uptake of CARLA by many of self-driving vehicles companies out there ;)

**Comment by germanros1987** [comment]
Hi @Abanoub-G,

Indeed. That is definitely a great API and we would love to have it integrated with CARLA. However, there are some constraints. It seems Google restricted the API to be used  with Unity and just on Android and iOS. We will have to wait until they extend the service.
