### ISSUE TITLE
Bounding boxes for non-vehicle and non-walker actors

### ISSUE THREAD

**Issue by dsche** [carla-simulator/carla#3186]
When extracting detectable objects from the simulation, it would be beneficial to be able to extract the bounding box/collider volume not only for Walker and Vehicle objects, but also for `static.prop.*`, traffic signs and other objects. Currently, these objects do not have a suitable attribute and there seems to be no way to extract the ground truth using the client API.

**Comment by germanros1987** [comment]
@dsche sorry for the delay. You are correct, that is a very needed feature. We will work on it as part of the 09.11 release.

**Comment by paperwhite** [comment]
Has this issue been addressed?
