### ISSUE TITLE
Not called on the RSS sensor callback

### ISSUE THREAD

**Issue by 33v33** [carla-simulator/carla#3187]
Hello Carla team,

I came across an issue while trying to use the RSS sensor, while attaching it to a vehicle and I have another car nearby, I am not getting called on the sensor callback, I am on version 0.9.9.4 both server and client, and my code looks something like this:
```      
    rss_blueprint = self._kinesim.world.get_blueprint_library().find("sensor.other.rss")
    transform = carla.Transform(carla.Location(x=self.x, y=self.y, z=self.z))
    self.sensor = self._kinesim.world.spawn_actor(rss_blueprint, transform, attach_to=vehicle._vehicle)
    self.sensor.listen(self._on_rss_responses)
```
and the callback:
```
    def _on_rss_responses(self, response):
        print(response.timestamp)
        print(response.response_valid)
        print(response.proper_response)
        print(response.acceleration_restriction)
        print(response.ego_dynamics_on_route)
```

Is there something I am missing?

Thanks

**Comment by germanros1987** [comment]
@fpasch could you please have a look at this?

**Comment by lucasnmatias** [comment]
I'm having the same problem, when attaching RSS sensor no error is thrown but the callback function is never called.

**Comment by fpasch** [comment]
Have you checked if the example script manual_control_rss.py is working as expected?
