### ISSUE TITLE
is there a semi-truck available

### ISSUE THREAD

**Issue by manonechu** [carla-simulator/carla#3192]
Hi, thank you for the great simulator.

I would like to know that is there a semi-truck available? Because I'd like to simulate autonomous driving for a semi-truck. If it is not available, is there a way to create or import it? Please kindly advise me.

Thank you so much for your help!

**Comment by germanros1987** [comment]
Hi,

We don't have semi-trucks yet. In general, we don't have vehicles with more than 4 wheels yet. This feature is planned for future releases.

**Comment by manonechu** [comment]
Hi @germanros1987, is there any good news on the development or release of semi-trucks? Thanks a lot.

**Comment by XGodina** [comment]
Hi @manonechu, not yet. Now, we are working on improving our current vehicles with new materials and geometry to make them more realistic. But we have it in mind to put semi-trucks

**Comment by manonechu** [comment]
Thank you for your response.

Do you have a timeline for releasing semi-trucks? Thank you! Regards

**Comment by XGodina** [comment]
Hi -manonechu 

To be honest for this release I'm totally sure not. Because we want to add new vehicles of service like a taxi, ambulance, etc. But is probably when we finish this we will working on that.

**Comment by nitschephil** [comment]
Hi, are there any updates regarding the implementation of more than four wheels? Our team would like to simulate a three-axle truck. Thanks!
