### ISSUE TITLE
Eeception "Disabling core dumps" was thrown while running "./CarlaUE4.sh"

### ISSUE THREAD

**Issue by tinmodeHuang** [carla-simulator/carla#3196]
**Configures:**
Ubuntu 18.04 LTS desktop
GTX 1660Ti 6G
Nvidia-driver-440
opengl4.6
vulkan1.1
Carla  release 0.9.9.4, 0.9.8, 0.9.7.4 and 0.9.6

**Exception as follow :**
```
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
```
**Problem: I couldn't key any command about Carla in either the terminal window or other one after above exception appeared**

Then enter "CTRL+C" to end up, only the following usually appears
```
FUnixPlatformMisc::RequestExitWithStatus
FUnixPlatformMisc::RequestExit
```
 Key "nvidia-smi" into the other terminial while running` ./CarlaUE4.sh` call
![2020-08-20 09-47-14屏幕截图](https://user-images.githubusercontent.com/65896325/90707834-03e81000-e2cb-11ea-926a-00e443fabcab.png)

**The ways tried & Corresponding results(ranked):**

1. To run commands "./CarlaUE4.sh", "./CarlaUE4.sh -vulkan", "./CarlaUE4.sh -opengl" and "DISPLAY=" followed by one of 
 those respectively.

that can't help improve the matter anymore.

2. To switch among all previous releases.

the same error still appears.

3. To switch among various graphics driver versions including 440, 435 and 418 that make sure the successful operation to CUDA 10.1  .

the same error still appears.

4. To install Vulkan and its dependencies and run "vulkaninfo" call successfully.

be alike.

**Some ways that haven't been tried:**

1. some people think that the issue is caused by the CarlaUE4.sh script does not pass in the arguments to the underlying binary ,refering to [nyukhalov's comment](https://github.com/carla-simulator/carla/issues/2138#issuecomment-616114548), which dosen't match my situation from my view.

2. the other people tried to delete some material in maps and then re-compile it, please refer to #2917, in my opinion, which have impact on completeness of files and further cause some unexpected issue, in addition, that solution isn't suitable for the new like me.

3. the way to edit allocation of memory size for running `./CarlaUE4.sh` call is proposed from my understand towards error reports and the first way above.

I spent clear 3 days doing all above and reading all about the error under issues tag, I'd appreciate it if anyone could help me, I'll clear my head during the next few days.
hey  @bernatx @germanros1987
I'm still new to the OS & Carla, could you help me with the problem or assign anyone to do?

**Comment by nagasanjay** [comment]
I have the same issue. Also the window with a car doesn't show up. only one window without car (looks like an FPP of a drone) opens up.
![carla colab](https://user-images.githubusercontent.com/43279026/90472758-e6863b00-e13e-11ea-8f5b-64fa85e0cf99.png)

**Comment by revikiran1991** [comment]
I built the new master branch on Ubuntu 18.04 and packaged it. It also throws the same error. 

`4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x7c0003e
  Serial number of failed request:  365
  Current serial number in output stream:  376
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Signal 6 caught.
Segmentation fault (core dumped)`

GPU: 1060 6GB

I tried running /PythonAPI/utils/config.py 

`  File "config.py", line 307, in <module>
    main()
  File "config.py", line 192, in main
    client = carla.Client(args.host, args.port, worker_threads=1)
AttributeError: module 'carla' has no attribute 'Client'
`

**Comment by germanros1987** [comment]
@tinmodeHuang sorry for the delay. 

As it has been mentioned already, the "disabling core dumps" message is just letting you know that CARLA won't generate a core dump. However, I understand from your message that you are having problems running the server or client (this part wasn't clear to me).

In order to help you, could you please provide us with more information? First, for simplicity, we are going to consider CARLA 0.9.9.4 and vulkan (-vulkan).

* Are you running the server in a local machine connected to a physical screen?
* Does the server window show up? Can you interact with it?
* If you run the manual_control.py script, does it work?

**Comment by tinmodeHuang** [comment]
> @tinmodeHuang sorry for the delay.
> 
> As it has been mentioned already, the "disabling core dumps" message is just letting you know that CARLA won't generate a core dump. However, I understand from your message that you are having problems running the server or client (this part wasn't clear to me).
> 
> In order to help you, could you please provide us with more information? First, for simplicity, we are going to consider CARLA 0.9.9.4 and vulkan (-vulkan).
> 
> * Are you running the server in a local machine connected to a physical screen?
> * Does the server window show up? Can you interact with it?
> * If you run the manual_control.py script, does it work?

I won't modify posted description of the issue anymore in order to help those being in the same situation realise that message isn't a matter.
my answer to the first two questions is "yes",

**Comment by RobinC94** [comment]
I have met the same problem with released pack carla0.9.6, which prints
`
4.22.1-0+++UE4+Release-4.22 517 0
Disabling core dumps.
sh: xdg-user-dir: command not found
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=44304 LargeMemoryPoolOffset=175440 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
`
For some reason, we are not able to run docker on server, so we have tried several machines we can borrow. We can only success with a Ubuntu16 server with 4 V100 GPUs. On the server we are using which is a Centos 7 server, it always return the above message. We have tried `-opengl`, `-opengl3` and even `-no-rendering` and nothing changes.
All these server has a GPU driver version 418.67 and cuda10.1
Does anyone knows what we can do next to make this issue fixed? We can do nothing because there are no coredump file to debug.
Many thanks!

**Comment by tinmodeHuang** [comment]
> I have met the same problem with released pack carla0.9.6, which prints
> `4.22.1-0+++UE4+Release-4.22 517 0 Disabling core dumps. sh: xdg-user-dir: command not found Signal 11 caught. Malloc Size=65538 LargeMemoryPoolOffset=65554 CommonUnixCrashHandler: Signal=11 Malloc Size=65535 LargeMemoryPoolOffset=131119 Malloc Size=44304 LargeMemoryPoolOffset=175440 Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.`
> For some reason, we are not able to run docker on server, so we have tried several machines we can borrow. We can only success with a Ubuntu16 server with 4 V100 GPUs. On the server we are using which is a Centos 7 server, it always return the above message. We have tried `-opengl`, `-opengl3` and even `-no-rendering` and nothing changes.
> All these server has a GPU driver version 418.67 and cuda10.1
> Does anyone knows what we can do next to make this issue fixed? We can do nothing because there are no coredump file to debug.
> Many thanks!

perhaps I couldn't have make it clear in the last comment, which the exception doesn't matter as germanros1987 said, thus you can open another terminal to run something relevant.

**Comment by debanik123** [comment]
use that
./CarlaUE4.sh -opengl

**Comment by honghua1998** [comment]
> use that
> ./CarlaUE4.sh -opengl
 
yes ! it works.but why does './CarlaUE4.sh'  fail to present the CarlaUE4 window continuesly?
thank you for your time

**Comment by kartikeyshaurya** [comment]
> use that
> ./CarlaUE4.sh -opengl

worked for me

**Comment by Derekabc** [comment]
![image](https://user-images.githubusercontent.com/25771207/130167598-4039cd9f-9ac3-43f2-8c16-2b98ad5701be.png)
I am still facing this problem and cannot figure out the reason!

**Comment by WangTianYuan** [comment]
@Derekabc Have you solved the problem? I have met the same problem and I find it has no error information. So I don't know where to fix

**Comment by pritesh604** [comment]
@tinmodeHuang  Have you found any solution because I am also facing the same issue.

**Comment by Inglam** [comment]
@tinmodeHuang Have you found any solution because I am also facing the same issue. Thanks!

**Comment by NaveedBhuiyan** [comment]
I have tried all the above but still cant find the solution. I am trying to run the Docker container for carla 9.13 on a windows 10 host. Maybe the issue is that I am using windows?

**Comment by KangChou** [comment]
./CarlaUE4.sh -opengl -carla-server -benchmark -fps=10

**Comment by Andrea010725** [comment]
Have you solved this problem? I'm having the same problem.

**Comment by lvxiangyu11** [comment]
> 使用 ./CarlaUE4.sh -opengl

works to me, thx

**Comment by FunKeen** [comment]
If you are using the method provided by Bench2Drive to install carla, then congratulations, the installation is complete, because the Bench2Drive author said
```
4.26.2-0+++UE4+Release-4.26 522 0 
Disabling core dumps. 
```
Only showing these two lines without termination is good.

**Comment by mx2013713828** [comment]
> If you are using the method provided by Bench2Drive to install carla, then congratulations, the installation is complete, because the Bench2Drive author said
> 
> ```
> 4.26.2-0+++UE4+Release-4.26 522 0 
> Disabling core dumps. 
> ```
> 
> Only showing these two lines without termination is good.

什么意思大佬，我是按照这bench2drive安装的，也是这个报错，这样是没问题的吗？

**Comment by Phoolore** [comment]
hi there. ChatGPT said I need vulcan
after
```
sudo apt install vulkan-tools
```
check with
```
vulkaninfo | less
```
and it worked, you can also try doing so with -nosound
```
./CarlaUE4.sh --quality-level=Low -nosound
```
