### ISSUE TITLE
Surface normals

### ISSUE THREAD

**Issue by Ulia-Demidova** [carla-simulator/carla#3199]
Hi!
Can i get the normal vector at any point, i.e. dense normal map such as depth map?

**Comment by germanros1987** [comment]
At the moment we don't have a normal map shader, although this is a relatively easy addition. It sounds perfect for a community contribution. Would you be interested in contributing to this?

**Comment by lcnature** [comment]
Hi, I wonder if there was any motivation to re-consider adding the surface norm? Or can you point to any direction of how to add it?
