### ISSUE TITLE
Crash on Town02 in Win

### ISSUE THREAD

**Issue by wzhAptiv** [carla-simulator/carla#320]
Carla will directly crash if I run with Town02 Map, but works fine with Town01. 
Neither Epic nor Low quality works. 

Carla 0.8.0, Win7 x64

**Comment by juaxix** [comment]
Hello @wzhAptiv , Windows releases are experimental yet. 
Can you share log from the Saved\Crashes\UE4CC--Windows-ID--\CarlaUE4.log ?
It is probably a bug with Unreal 4.19

**Comment by juaxix** [comment]
Yes, I can confirm this is a bug with Unreal 4.19 with landscapes:
`Assertion failed: LODScreenRatioSquared.IsValidIndex(InSelectedLODIndex) [File:D:\Build\++UE4+Release-4.19+Compile\Sync\Engine\Source\Runtime\Landscape\Private\LandscapeRender.cpp] [Line: 1698]`

I have updated the release 0.8.0 for Windows using 4.18 now without this bug.

**Comment by wzhAptiv** [comment]
Hello @juaxix , it works on my machine after this update. 

Thank you!
