### ISSUE TITLE
Saving sensor data when replaying a scenaio

### ISSUE THREAD

**Issue by hablu1** [carla-simulator/carla#3204]
Hi,

I am recording a scenario with a rgb camera mounted on an ego vehicle and saving the images to disk.
Now I want to replay this scenario with different weather conditions and save the images of the rgb camera to disk.
Is this actually possible?

**Comment by germanros1987** [comment]
@hablu1 please have a look at the logging and playback API: https://carla.readthedocs.io/en/latest/adv_recorder/
