### ISSUE TITLE
Is there a way to remove Sensors from manual_control.py ? Eg. Semantic Segmentation, LiDAR, etc.. If yes, is there a specific set of steps?

### ISSUE THREAD

**Issue by TheMaveric** [carla-simulator/carla#3206]
I want to see if I can increase the FPS by removing some sensors which I dont need for the work Im doing, I want to achieve this but am unable to figure out where to **begin.**

**Comment by thytless** [comment]
As far as I know, sensors are defined in a list(`self.sensors`) in `CameraManager` in manual_control.py, and modifying that should work . I have tried that for comparison between segmentation and RGB imgs.

**Comment by TheMaveric** [comment]
But according to the pipeline for carla, the client also has cpp code for it.. Is that also to be removed?

**Comment by thytless** [comment]
@TheMaveric If you do not care about image quality, you may as well try to set server quality as low.
