### ISSUE TITLE
Volkswagen van overturns

### ISSUE THREAD

**Issue by wzhAptiv** [carla-simulator/carla#321]
I see a really strange AI behaviour, that a van tumbles when turning right, because of the too-high speed. 
Is such behaviour intended since the AI is updated in Version 0.8.0? and I haven't seen it in 0.7.1. 

See the light-blue van in front of the police car. 
![strange ai](https://user-images.githubusercontent.com/37740387/38087781-b9be51ce-3359-11e8-92e7-952869ed2f89.png)

**Comment by nsubiron** [comment]
Yes, I can confirm this is happening in 0.8.0
