### ISSUE TITLE
How to import Town06/Town07 to precompiled build?

### ISSUE THREAD

**Issue by Kravcu** [carla-simulator/carla#3210]
Hi,
Could you provide a guide how to import Town06(and Town07) to precompiled Carla build? 
There are only 3 files for each of those maps(.xord, .bin and .pcd), and the guide in docs doesn't cover this.

I am using version 0.9.9.2 on Windows 10.

**Comment by germanros1987** [comment]
@Kravcu to add the additional towns into a pre-compiled CARLA build you just have to:
* Copy the **tarball** with the maps into the Import folder
* Run the ImportAssets.sh script

Enjoy!
