### ISSUE TITLE
how to destroy client 

### ISSUE THREAD

**Issue by SUNGWOOKYOO** [carla-simulator/carla#3212]
I have to connect and disconnect client with carla server many times.
However, previous connection keep continuously, As a result the running process continuously increase.

my carla version is 0.9.9.4

If I used the below code, previous connection disappeared. 
It ends properly in the following situations
```
host = '127.0.0.1'
port = 2000
carla_client = carla.Client(host=host, port=port)
del carla_client
carla_client = carla.Client(host=host, port=port)
del carla_client
```

Check the number of process 
```
lsof -i TCP:2000
```

However, In the following situations, it does not finish properly.

```
host = '127.0.0.1'
port = 2000
carla_client = carla.Client(host=host, port=port)
carla_client.set_timeout(5)
carla_world = carla_client.get_world()

del carla_world
del carla_client

carla_client = carla.Client(host=host, port=port)
carla_client.set_timeout(5)
carla_world = carla_client.get_world()

del carla_world
del carla_client

```
If you check the process,
```
lsof -i TCP:2000
```
the process is accumulated as follows.
```
COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
CarlaUE4- 11347 usaywook   39u  IPv4 106243      0t0  TCP *:cisco-sccp (LISTEN)
CarlaUE4- 11347 usaywook   44u  IPv4 121001      0t0  TCP localhost:cisco-sccp->localhost:51010 (ESTABLISHED)
CarlaUE4- 11347 usaywook   46u  IPv4 112391      0t0  TCP localhost:cisco-sccp->localhost:51016 (ESTABLISHED)
python    11569 usaywook   20u  IPv4 106268      0t0  TCP localhost:51010->localhost:cisco-sccp (ESTABLISHED)
python    11569 usaywook   42u  IPv4 114065      0t0  TCP localhost:51016->localhost:cisco-sccp (ESTABLISHED)
```
 How do we destroy the client and close client connection properly while maintaining server???

**Comment by germanros1987** [comment]
@bernatx could you take a look?

**Comment by baurst** [comment]
I stumbled upon this issue, thinking this might be related to a problem that I'm having with the simulator hanging after starting a new episode. In my case I thought some "dangling" synchronous clients might be preventing the simulator from continuing. But I was not able to reproduce this behavior with your code snippets on master...

For me lssof -i TCP:2000 just gives the following output for the second snippet you have provided:
COMMAND  PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
CarlaUE4 561 baurst   50u  IPv4 2640607      0t0  TCP *:cisco-sccp (LISTEN)
...which is fine I guess.

**Comment by baurst** [comment]
So despite being unable to reproduce this issue with the snippet you have provided, I was able to reproduce it using my own use case. I end up with dangling TCP connections. (lsof -i TCP:2000 says "CLOSE_WAIT" for my python client PID, while the same PID has one connection that is "ESTABLISHED").

My "dirty" workaround - using a seperate Process will kill all child TCP connections...

```python
from multiprocessing import Process
import carla

def do_stuff(x):
    host = '127.0.0.1'
    port = 2000
    carla_client = carla.Client(host=host, port=port)
    carla_client.set_timeout(5)
    carla_world = carla_client.get_world()
    # etc

p = Process(target=do_stuff, args=(some_args,))
p.start()
p.join()
if p.is_alive():
    p.kill()
```

**Comment by SwapnilPande** [comment]
Are there any updates on this? It would be nice to able to destroy a client without having to run it in a separate process. 

I am seeing this issue when trying to completely restart the server. In this case, when I restart the server and spawn a new client, I get the following error from the old client:

```
 terminate called after throwing an instance of 'carla::client::TimeoutException'
  what():  time-out of 45000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:12345
```

When debugging using `lsof`, I also find that the tcp connection associated with my python program has the `CLOSE_WAIT` status.

**Comment by varunjammula** [comment]
+1. Any updates on this issue?

**Comment by mvatcoff** [comment]
Any update? I have the same problem with version 0.9.13

**Comment by yhh-IV** [comment]
Any update? I have the same problem with version 0.9.15

**Comment by loganpeng** [comment]
Is there any update? I have tried the solution provided by @baurst, but it did not work. The process still existed. p.is_alive() can not monitor world and client properly.

**Comment by keishihara** [comment]
I’ve been facing the same issue for a long time:
```
terminate called after throwing an instance of 'carla::client::TimeoutException'
what(): time-out of 45000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:12345
```

It turned out that in my case the root cause was an uncleared Traffic Manager instance. Simply calling tm.shut_down() before discarding the client fixed it:
```python
def set_sync_mode(client, port, tm=None, sync=True):
    world = client.get_world()
    settings = world.get_settings()
    settings.synchronous_mode = sync
    settings.fixed_delta_seconds = 0.05
    settings.deterministic_ragdolls = True
    world.apply_settings(settings)
    if tm is None:
        tm = client.get_trafficmanager(port + 6000)
    tm.set_synchronous_mode(sync)
    return world, tm

client = carla.Client('localhost', 2000)
client.set_timeout(20.0)
world, tm = set_sync_mode(client)

# … perform your operations …

# When you're done
client = None
tm.shut_down()  # added
```
After adding tm.shut_down(), I can safely restart the server or reconnect without hitting the TimeoutException. Hope this helps!
