### ISSUE TITLE
Changing quality level [Windows]

### ISSUE THREAD

**Issue by wendersonj** [carla-simulator/carla#3213]
Hi ! I'm making some experiments with windows and I can't properly modify the quality level on Windows (can't use -quality-level=Low) or use parameters to run Carla. 
Could you help me ?

Cheers!

**Comment by wendersonj** [comment]
Didn't worked for me.

**Comment by thytless** [comment]
@wendersonj Would you please give some details? Which file did you edit and how did you confirm that it did not work?

**Comment by germanros1987** [comment]
@marcgpuig @bernatx do you have any suggestions?
