### ISSUE TITLE
Error when running "make package"

### ISSUE THREAD

**Issue by RicardoSakura** [carla-simulator/carla#3216]
I am using Carla 0.9.9. I have built the Unreal engine successfully, but got an error with the command of
make package in Ubuntu 18.0.4.
[errorlog.txt](https://github.com/carla-simulator/carla/files/5115482/errorlog.txt)

**Comment by germanros1987** [comment]
@RicardoSakura could you please provide more details about your setup?
@sergi-e could you try to help?

**Comment by sergi-e** [comment]
Hi @RicardoSakura!

It would be great if you could provide us with your log, so that we can track the error :)

**Comment by rebolomo** [comment]
I have the same issue when making package with carla 0.9.9. Any help will be appreciated.
[log.txt](https://github.com/carla-simulator/carla/files/5358602/log.txt)
[Cook-2020.10.10-15.36.43.txt](https://github.com/carla-simulator/carla/files/5358603/Cook-2020.10.10-15.36.43.txt)
