### ISSUE TITLE
control multi vehicles

### ISSUE THREAD

**Issue by carlaUE4new** [carla-simulator/carla#3219]
I am trying to control multiple vehicles seperately within the same world. Does Carla 0.9.9.4 support this? if supported, is there an example of how to do this? Do I need to set up each vehicle will communicate with world through different TCP ports?

Thanks

**Comment by thytless** [comment]
I believe that the answer is yes. Actually client sends control command to the server, and that is how vehicles are controlled. Prepare control commands for each actor. Learn more about it: https://carla.readthedocs.io/en/latest/python_api/#commandapplyvehiclecontrol

**Comment by germanros1987** [comment]
Indeed. The API lets you control as many vehicles as you need. You just need to follow the instructions, as indicated by @thytless
