### ISSUE TITLE
Can carla do distributed computing?

### ISSUE THREAD

**Issue by XieJinLiang** [carla-simulator/carla#3223]
Hello~
Can carla do distributed computing? We need to test autonomous driving vehicles on a very large map. We hope to divide the map into small maps, and then connect each carla server to a small map. We want to run multiple clients and multiple server to control different vehicles for algorithm testing. At the same time, servers can communicate with each other.Is this possible?

**Comment by germanros1987** [comment]
Hi,

Technically you could create arbitrary maps and then run each of those maps in different CARLA servers. However, CARLA does not provide a method to automatically sync all those instances. You would have to create this on top of the existing CARLA API
