### ISSUE TITLE
cannot open CarlaUE4 project with UE4 4.24.3

### ISSUE THREAD

**Issue by dingkailv** [carla-simulator/carla#3225]
I downloaded the carla 0.9.9 for windows. The binaries run perfectly, nothing weird happened. But when I want to open the CarlaUE4.uproject under CarlaUE4, it says the CarlaUE4 and Carla are missing or built with a different engine version. That I have to re-build them

I had this problem when trying to build Carla as well, I can build it. But cannot open the UE4 project.
What seems to be wrong?

**Comment by Lu7913** [comment]
Same here, couldn't solve the issue, building Carla from source solved the issue for me.

**Comment by germanros1987** [comment]
@dingkailv you can't build any version of CARLA with any version of UE4. Each version of CARLA is designed for a specific version of UE4.
