### ISSUE TITLE
Radar Velocity and Depth maintaining at zero

### ISSUE THREAD

**Issue by NgYinZhi1** [carla-simulator/carla#3228]
Hello there,

I am trying to make use of the radar sensor on the ego vehicle. I have been following the tutorial from https://carla.readthedocs.io/en/latest/tuto_G_retrieve_data/#radar-sensor and it seems to be working. However, when i call for data in the RadarDetection attribute, I am only getting azimuth and altitude data, whereas depth and velocity is constantly at zero for all radar measurement readings.

I am running on CARLA 0.9.9.4 release, and using Windows 10 OS. Any help with regards to this is much appreciated. Thanks!

**Comment by NurbekHalikulov** [comment]
Hey, did you find the solution? Could you please share with?
