### ISSUE TITLE
怎样获取传感器数据

### ISSUE THREAD

**Issue by errorJY** [carla-simulator/carla#323]

**Comment by errorJY** [comment]
我想做一个API接口，能够使外界获取传感器数据.

**Comment by nsubiron** [comment]
Could you explain in English please? :)

**Comment by errorJY** [comment]
soory,I want to make an API interface that enables the outside world to get sensor data.

**Comment by errorJY** [comment]
sorry,I want to make an API interface that enables the outside world to get sensor data.

**Comment by nsubiron** [comment]
As starting point, I'd suggest to take a look at [client_example.py](https://github.com/carla-simulator/carla/blob/master/PythonClient/client_example.py). Here we show how to connect to the simulator using our Python API.
