### ISSUE TITLE
can't get carlaviz in web

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#3231]
I am trying use carlaviz, and ss of this step, it's normal: docker run -it --network="host" -e CARLAVIZ_HOST_IP=localhost -e CARLA_SERVER_IP=localhost -e CARLA_SERVER_PORT=2000 <name_of_Docker_image>
but when I type in the browser " http://127.0.0.1 :8080/ ", the output is not like the tutorial shows.
![image](https://user-images.githubusercontent.com/38369239/91654685-8481ea00-eadd-11ea-9065-6a98bd592c88.png)

**Comment by wx9698** [comment]
Make sure that your localhost's 8080 port is not bound by another process. And by the way what is ss?

**Comment by whuxhzhang** [comment]
> Make sure that your localhost's 8080 port is not bound by another process. And by the way what is ss?

Sorry, it's my spelling mistake...

I'll check as you say，thank you very much.

**Comment by whuxhzhang** [comment]
> Make sure that your localhost's 8080 port is not bound by another process. And by the way what is ss?

If  the host's 8080 port is bound by another process, can I change the carlaviz's port ？

**Comment by wx9698** [comment]
If you want to specify the port, you need to build this project (at least fronend part) by yourself instead of running frontend in the docker container.

You need to modify the start command in the scripts section in file frontend/package.json. 
Add "--port PORT_YOU_WANT" in that command and run "yarn start".

I will add more configuration options in future releases.

**Comment by whuxhzhang** [comment]
> If you want to specify the port, you need to build this project (at least fronend part) by yourself instead of running frontend in the docker container.
> 
> You need to modify the start command in the scripts section in file frontend/package.json.
> Add "--port PORT_YOU_WANT" in that command and run "yarn start".
> 
> I will add more configuration options in future releases.

It works!!!
Turn off the use of this port on my computer， it working.
Thank you very much.
