### ISSUE TITLE
Co-simulation problem with Sumo

### ISSUE THREAD

**Issue by zwbai** [carla-simulator/carla#3232]
Hi,

I want to try the co-simulation with sumo. Following the tutorial, I ran the following code:
`python run_synchronization.py examples/Town04.sumocfg  --sumo-gui`
and when I click the play button in sumo, it showed "simulation ended":
![Screenshot from 2020-08-30 21-03-14](https://user-images.githubusercontent.com/23632221/91659907-5c0de600-eb05-11ea-9812-41384177393b.png)

so, could anyone tell me what;s the problem and what should I do?

Thanks!

**Comment by zwbai** [comment]
It said the reason is "TraCl requested termination", but I didn't find how to solve it.
 Here is the log:
![Screenshot from 2020-08-30 21-14-17](https://user-images.githubusercontent.com/23632221/91659991-dc344b80-eb05-11ea-9207-6729422fa2e6.png)

**Comment by joel-mb** [comment]
Hi @zwbai!
Which version of sumo are you using? You can check it by running `sumo --version`
Have you tested with other towns (e.g., Town01)?

**Comment by zwbai** [comment]
Hi @joel-mb !

Thank you for your attantion. My sumo version is 0.32.0.
In addition, I also tried Town01 with same command, but it shows the same error, which is shown as below:

![Screenshot from 2020-09-11 00-53-18](https://user-images.githubusercontent.com/23632221/92767276-8a26dc00-f3c9-11ea-9453-440318cc7f05.png)

hope that you can help to solve the problem, thank you very much!

**Comment by joel-mb** [comment]
Hi @zwbai  ! Are you using this version of SUMO for any specific reason? I would say that if you update SUMO to the latest version (at least to `1.5`) the issue should disappear.

**Comment by zwbai** [comment]
It worked! Thank you very much.

**Comment by HemaZ** [comment]
I'm still getting a similar issue running SUMO 1.6 
with `python spawn_npc_sumo.py --sumo-gui`
![image](https://user-images.githubusercontent.com/6087928/93236745-7a1f4b80-f77f-11ea-8a0a-05f3a591824e.png)

**Comment by joel-mb** [comment]
Hi @HemaZ! Which version of CARLA are you using? This issue was fixed here: https://github.com/carla-simulator/carla/pull/3129

**Comment by HemaZ** [comment]
> Hi @HemaZ! Which version of CARLA are you using? This issue was fixed here: #3129
Hi @joel-mb I'm using CARLA 9.9.4

**Comment by joel-mb** [comment]
Hi @HemaZ !
CARLA 0.9.9.4 is not containing the fix for this issue. You should use CARLA 0.9.10 or just update you `spawn_npc_sumo` script by this one: https://github.com/carla-simulator/carla/blob/master/Co-Simulation/Sumo/spawn_npc_sumo.py
