### ISSUE TITLE
CARLA 0.9.5 0 - Python3.5 - Syntax Error - File "Test_1.py", line 311     agent.model.save(f'models/{MODEL_NAME}__{max_reward:_>7.2f}max_{average_reward:_>7.2f}avg_{min_reward:_>7.2f}min__{int(time.time())}.model')

### ISSUE THREAD

**Issue by guruvishnuvardan** [carla-simulator/carla#3233]
Hi,

System specifications:
OS: Ubuntu 18.04,
Memory: 15.7 GiB,
Processor: AMD® Ryzen 7 3800x 8-core processor × 16,
GPU 4 GiB.
Python Version - 3.5
CARLA Version - 0.9.5

Please find the attached Test_1.py, I am attempting to run, while doing so, I am encountering syntax error - **File "Test_1.py", line 311     agent.model.save(f'models/{MODEL_NAME}__{max_reward:_>7.2f}max_{average_reward:_>7.2f}avg_{min_reward:_>7.2f}min__{int(time.time())}.model')** (Screenshot Attached).

I couldn't figure out the reason for the sytax error - I even tried to add -- agent.model.save('{}'.format(models/(MODEL_NAME)__(max_reward:_>7.2f)max_(average_reward:_>7.2f)avg_(min_reward:_>7.2f)min__(int(time.time())).model)), Still I encountered the same error.
[CARLA_Test_1_PY.pdf](https://github.com/carla-simulator/carla/files/5148949/CARLA_Test_1_PY.pdf)

Can you please help me resolve this problem.

Thanks
Guru
![2020-08-31](https://user-images.githubusercontent.com/31349523/91693740-1e52a100-eb89-11ea-9543-1a4d5510f547.png)

**Comment by germanros1987** [comment]
This is not a problem with CARLA, but a problem with your script. This is not the right place for this.
