### ISSUE TITLE
make launch [install_boost error], Windows 0.9.x

### ISSUE THREAD

**Issue by Inezzzz** [carla-simulator/carla#3245]
I'm building on Windows and keeps getting an error on boost. I've tried to remove boost folder completely from carla/Build and re-run "make launch" or "make LibCarla" multiple times, still the same error. I also tried to install boost directly into carla/Build which seemed to be successful but then I got same error after try "make launch" again.  All commands were in x64 command window.
![Screenshot (11)](https://user-images.githubusercontent.com/19997403/91887319-7e0b8380-ec3f-11ea-8737-0967cba40c33.png)

**Comment by H-Whisky** [comment]
You should go to "~/carla/Util/InstallersWin", then you can see install_boost.bat, rending the content of the file shows that you can go to https://dl.bintray.com/boostorg/release/ to download Specify version *.zip file, finally put the *.zip into "~/carla/Build", and run "make launch".

**Comment by Inezzzz** [comment]
> You should go to "~/carla/Util/InstallersWin", then you can see install_boost.bat, rending the content of the file shows that you can go to https://dl.bintray.com/boostorg/release/ to download Specify version *.zip file, finally put the *.zip into "~/carla/Build", and run "make launch".
Tried to render the install_boost.bat and this is what I got

C:\carla\Util\InstallersWin>install_boost
    -[install_boost]: [Batch params]:
    -[install_boost]: You must specify a boost version using [-v|--version]
    -[install_boost]: Exiting with error...

How do I specify the boost version? I downloaded a boost binary and put in /carla/Build

**Comment by H-Whisky** [comment]
> > You should go to "~/carla/Util/InstallersWin", then you can see install_boost.bat, rending the content of the file shows that you can go to https://dl.bintray.com/boostorg/release/ to download Specify version *.zip file, finally put the *.zip into "~/carla/Build", and run "make launch".
> > Tried to render the install_boost.bat and this is what I got
> 
> C:\carla\Util\InstallersWin>install_boost
> -[install_boost]: [Batch params]:
> -[install_boost]: You must specify a boost version using [-v|--version]
> -[install_boost]: Exiting with error...
> 
> How do I specify the boost version? I downloaded a boost binary and put in /carla/Build

Go to https://dl.bintray.com/boostorg/release/ , find and download *0.72.0*.zip, put it into ~/carla/Build/ when download finished.

**Comment by germanros1987** [comment]
@Inezzzz have you solved your problem? Otherwise, @marcgpuig could you please take a look?

**Comment by Inezzzz** [comment]
Nope. Still not working, kinda gave up on CARLA, but would love to try
again if the team’s going to take a look.

**Comment by nagasanjay** [comment]
Have you installed `c++ workload and .NET workload` from visual studio installer ?
