### ISSUE TITLE
Import RoadRunner Map in CARLA/ Build CARLA Ubuntu 16.04 

### ISSUE THREAD

**Issue by souvikboseGM** [carla-simulator/carla#3247]
I am  trying to build CARLA in Ubuntu 16.04  
and using this document  https://carla.readthedocs.io/en/stable/how_to_build_on_linux/#build-unreal-engine

Unreal Engine build is done. 
and Then I used "git clone https://github.com/carla-simulator/carla" to download CARLA 0.9.8 [No particular reason to download 0.9.8 . My main aim is to Import RoadRunner Map in CARLA]

Then While doing " ./Setup.sh ". I got below error 
![Screenshot from 2020-09-01 23-21-19](https://user-images.githubusercontent.com/61221837/91934970-3ef63480-ed0a-11ea-9092-fa7e41fa6f63.png)

The "https://carla.readthedocs.io/en/stable/how_to_build_on_linux/#build-unreal-engine" didnot asked for clang 7 ? .

Can you help me to solve this ?

**Comment by pergustav** [comment]
You are reading the docs for the stable version, which isn't 0.9.8.
You will probably have better luck with this one. https://carla.readthedocs.io/en/latest/build_linux/

**Comment by souvikboseGM** [comment]
@pergustav Thanks for the docs. I just moved to this doc. I am facing now new issue. Posted with Error No #3248 . If you could pls  check ,if you could help

**Comment by souvikboseGM** [comment]
Solved by https://carla.readthedocs.io/en/0.9.8/build_linux/
