### ISSUE TITLE
Tracking of  #3251

### ISSUE THREAD

**Issue by marcgpuig** [carla-simulator/carla#3252]
_This issue is intended to track #3251._

It must be tested in Windows (@bernatx and @XGodina) and Linux (@Axel1092).
- Make sure the client colors mimic the original UE4 colors.
- Make sure all the semantic tags are correctly displayed.

**Comment by Axel1092** [comment]
Works!

**Comment by bernatx** [comment]
Works for me also, in windows.

**Comment by pangxiao2013** [comment]
> _This issue is intended to track #3251._
> 
> It must be tested in Windows (@bernatx and @XGodina) and Linux (@Axel1092).
> 
> * Make sure the client colors mimic the original UE4 colors.
> * Make sure all the semantic tags are correctly displayed.



> Works for me also, in windows.

Where can we download 0.9.10?

**Comment by XGodina** [comment]
Hi @pangxiao2013 

You can download here: http://carla.org/2020/09/25/release-0.9.10/
