### ISSUE TITLE
E-scooter model in CARLA

### ISSUE THREAD

**Issue by kanakab** [carla-simulator/carla#3254]

**Comment by kanakab** [comment]
Currently there are no E-scooter model availabel in CARLA. It would be great to get E-scooter vehicle model as the no of E-scooter users has increased.

 -label:feature request.

**Comment by germanros1987** [comment]
Noted!

**Comment by XGodina** [comment]
Hi @kanakab,

Thanks for the comment I'll keep that in mind !!

**Comment by codegrafix** [comment]
What is needed to get a scooter model into CARLA?

**Comment by DongChen06** [comment]
@XGodina Hi team, any updates on the scooter model?
