### ISSUE TITLE
Cannot find "CarlaUE4.sh" after building through make launch ### how can I run server CarlaUE4.sh and attach Python API Client ###

### ISSUE THREAD

**Issue by souvikboseGM** [carla-simulator/carla#3265]
Carla 0.9.8,Ubuntu 16.04,Unreal Engine 4.22

After completing all the steps from https://carla.readthedocs.io/en/0.9.8/build_linux/ , and successful after make launch.
I could not find CarlaUE4.sh . Then how can I run server CarlaUE4.sh and connect Python API Client ?
Please Help ..

**Comment by qhaas** [comment]
`make package` should package CARLA up with said script similar to how the vendor distributes CARLA, try that.

**Comment by GarethZhang** [comment]
@souvikboseGM Did you figure out how to fix this?
