### ISSUE TITLE
How to retrieve simulation data in C++ (equivalent to read_data() on the pythonCli)

### ISSUE THREAD

**Issue by munirjojoverge** [carla-simulator/carla#3266]

**Comment by jimmyw404** [comment]
Compile and run this example to access Carla via C++:

https://github.com/carla-simulator/carla/tree/dev/Examples/CppClient

Note that I used a callback in this function to get simulation data updates on tick instead of retrieving it.

in carla::client::World:
    /// Register a @a callback to be called every time a world tick is received.
    ///
    /// @return ID of the callback, use it to remove the callback.
    size_t OnTick(std::function<void(WorldSnapshot)> callback);

**Comment by munirjojoverge** [comment]
Thanks Jimmy.
I was working on that example from the very begging. I'll try to implement that. Thanks.
