### ISSUE TITLE
opendrive could not be correctly parsed

### ISSUE THREAD

**Issue by HemaZ** [carla-simulator/carla#3269]
Hello CARLA Team, 
I'm having an issue running the opendrive standalone example in the documentation 
`python3 config.py -x opendrive/TownBig.xodr
`
I get the following error 
_**opendrive could not be correctly parsed**_
I'm using CARLA Patch Release 0.9.9.4
on Ubuntu 18.04 inside Docker
I've tried using python3.6 and python3.7 but I get the same issue. 
Thank You.

**Comment by germanros1987** [comment]
@HemaZ could you please check if you have the same problem in the nightly build? http://carla-releases.s3.amazonaws.com/Linux/Dev/CARLA_Latest.tar.gz

**Comment by HemaZ** [comment]
> @HemaZ could you please check if you have the same problem in the nightly build? http://carla-releases.s3.amazonaws.com/Linux/Dev/CARLA_Latest.tar.gz

Nightly build is working great 
![image](https://user-images.githubusercontent.com/6087928/94148502-ff3ceb80-fe76-11ea-93a2-26fd54e86b42.png)

**Comment by HemaZ** [comment]
@germanros1987 I've tried again using the nightly build and it returns the same error !!

**Comment by InterKnight** [comment]
I got the same error. Anyone can give a hint?
I'm using CARLA 0.9.11 from deb package on Ubuntu 18.04

**Comment by egreglee-bit** [comment]
Similar failure as in other reports, but from CARLA_0.9.11.tar.gz on Ubuntu 18.04
I verified with an independent viewer that the xodr can be parsed.

**Comment by bitekas** [comment]
I'm confirming the same bug, ubuntu 18.04

**Comment by HarnarayanSingh** [comment]
> I'm confirming the same bug, ubuntu 18.04; CARLA_0.9.11; the nightly build by the link is working

@bitekas Could you clarify if it worked or not for you? I got the same error in nightly build.

**Comment by bitekas** [comment]
@HarnarayanSingh Yes, the nightly build is working for me.

**Comment by LichuanRen** [comment]
I got the same error on Ubuntu 18.04, CARLA 0.9.10. 

The nightly build returns another error: RuntimeError: rpc::rpc_error during call in function load_new_episode
