### ISSUE TITLE
Import traffic signals but don't work.

### ISSUE THREAD

**Issue by wangludong** [carla-simulator/carla#3273]
Hi there

I made a map with traffic signals in RoadRunner.
When I imported the Opendrive and started the simulation, the traffic signals did't work.
The lights neither turned on nor switched.
I wonder what is the mechanism of traffic signals.Are they controlled by Opendrive or some other ways?

**Comment by thytless** [comment]
https://github.com/carla-simulator/carla/releases
Traffic lights auto-importing is supported since 0.9.9.1, please make sure you are using a higher version

**Comment by wangludong** [comment]
> https://github.com/carla-simulator/carla/releases
> Traffic lights auto-importing is supported since 0.9.9.1, please make sure you are using a higher version

Thank you.
But I have to use 0.9.8 because of the limit of my project.
Is there any way to work with traffic lights in this version?

**Comment by thytless** [comment]
Well, as far as I know you can always manually add traffic lights actors to your map in CarlaUE4 Editor.

**Comment by wangludong** [comment]
> Well, as far as I know you can always manually add traffic lights actors to your map in CarlaUE4 Editor.

Thank you.
I added some BP_TrafficLights to my scene and they can switch lights.
But the lights of different directions turned to the same light simultaneously, as you can see in the following capture.
![traffic signal](https://user-images.githubusercontent.com/167162/92885905-c730b400-f445-11ea-9685-0e3d05d6f779.JPG)

Do you know how to control them?

**Comment by wangludong** [comment]
I associated a TrafficLightGroup with these TrafficLights and it became better.
But these lights circulated one by one instead of synchronizing the opposite lights so as to turn on the same light.
Need I modify the blue print?Or any other way exists?

**Comment by germanros1987** [comment]
@wangludong you probably need to modify the BP, or you can update to 0.9.9...

**Comment by Axel1092** [comment]
Hi @wangludong, at the version you are working you would need to do more than modify the TrafficLightGroup Blueprint and even the C++ part of the traffic lights control. The only workaround I can think of is to create a new traffic light Blueprint with 2 traffic lights in it and then adjust their position in the world manually.

In the latest version in our current master this feature is still not supported but it is a lot easier to workarround by only modifying the TrafficLightGroup BP.

Another solution in 0.9.9 and up is to remove the traffic lights from the map and let it load from the OpenDRIVE at runtime. You can place a `TrafficLightManager` actor in the world and provided they are well defined from roadrunner they will load and behave as you expect.

**Comment by wangludong** [comment]
Okey, I get it. Thank you all!
