### ISSUE TITLE
Where can I find carla.egg's source code?

### ISSUE THREAD

**Issue by JarvanI** [carla-simulator/carla#3274]
I want to know how python api calls the c++ code in libcarla, so I want to read the source code of the egg file. Where can I find carla.egg's source code? Thanks

**Comment by jimmyw404** [comment]
Here's the source code for controls (VehicleControl, WalkerControl etc):

https://github.com/carla-simulator/carla/blob/dev/PythonAPI/carla/source/libcarla/Control.cpp

You'll need to understand https://www.boost.org/doc/libs/1_70_0/libs/python/doc/html/index.html before it really makes much sense.
