### ISSUE TITLE
Missing pyplusplus from Bitbucket URL (RSS Build docs)

### ISSUE THREAD

**Issue by kino3** [carla-simulator/carla#3278]
I'm trying to build RSS environment on my Ubuntu.
In https://carla.readthedocs.io/en/latest/adv_rss/ 
```
sudo apt-get install castxml
pip install --user pygccxml
pip install --user https://bitbucket.org/ompl/pyplusplus/get/1.8.1.zip
```
But we cannot get pyplusplus from this URL (404 Not found). Can we use the following one instead?
```
pip install --user pyplusplus==1.8.1
```

**Comment by germanros1987** [comment]
@fpasch could you have a look?

**Comment by berndgassmann** [comment]
See the latest docu here:
https://ad-map-access.readthedocs.io/en/latest/BUILDING/index.html
https://intel.github.io/ad-rss-lib/BUILDING/

just install via pip now ;-)
Will update the docu inside CARLA to fix this.
