### ISSUE TITLE
Question about depth Image and Segmentation Image.

### ISSUE THREAD

**Issue by gsp-27** [carla-simulator/carla#3282]
Hi,

Thanks for the wonderful open source simulator. I had a question regarding converting depth map to pointcloud and then obtaining the points belonging to the objects using the segmentation map in 3D.

I was following https://github.com/carla-simulator/carla/pull/100/commits/07c06f4f51bb221eb9675fda4213e9384fb0378e, to convert depth map to pointcloud.
Here 
```python 
u_coord = repmat(numpy.r_[image.width-1:-1:-1],
                     image.height, 1).reshape(pixel_length)
v_coord = repmat(numpy.c_[image.height-1:-1:-1],
                     1, image.width).reshape(pixel_length)
```
Why are the coordinates formed in reverse direction here? Sorry if I am missing something obvious here.

Furthermore, if I use *segmentation map* to get pixels belonging to a particular object and then I want to obtain points in *camera coordinate frame* for that object do I need to do *diagonal flipping*?

**Comment by germanros1987** [comment]
@marcgpuig could you help with this question?
