### ISSUE TITLE
How to add  new control message?

### ISSUE THREAD

**Issue by wangzhiqing** [carla-simulator/carla#329]
` client.send_control(
steer=random.uniform(-1.0, 1.0),
throttle=0.5,
brake=0.0,
hand_brake=False,
reverse=False)`
We can send control messages to server. 
**Then I want to know in which file that server receives these control messages. If I want to create a new control message, how can I know the server will receive it?**

**Comment by nsubiron** [comment]
Hi @wangzhiqing,

Adding a new message is not precisely straightforward. The control message travels a long way until it reaches the vehicle

  1. The data is serialized as protobuf message ([carla_server.proto](https://github.com/carla-simulator/carla/blob/d289125e98e0fd15882970e779f99d600b621441/Util/Proto/carla_server.proto#L117-L123)), then sent to the server through a TCP socket. This is done in [client.py](https://github.com/carla-simulator/carla/blob/d289125e98e0fd15882970e779f99d600b621441/PythonClient/carla/client.py#L129-L145).
  2. The [CarlaServer](http://carla.readthedocs.io/en/latest/carla_server/) module (in Util/CarlaServer) is the one in charge of receiving the messages and convert them to C++ classes, the control message is read asynchronously on a separate thread. The encoding is done in [CarlaEncoder.cpp](https://github.com/carla-simulator/carla/blob/d289125e98e0fd15882970e779f99d600b621441/Util/CarlaServer/source/carla/server/CarlaEncoder.cpp#L206-L221), all this is controlled by the [AgentServer](https://github.com/carla-simulator/carla/blob/d289125e98e0fd15882970e779f99d600b621441/Util/CarlaServer/source/carla/server/AgentServer.cpp#L44-L54).
  3. Then _CarlaUE4_, the Unreal project, consults _CarlaServer_ each frame to see if the control is available, this is done through a C-API ([carla_server.h](https://github.com/carla-simulator/carla/blob/d289125e98e0fd15882970e779f99d600b621441/Util/CarlaServer/include/carla/carla_server.h#L277-L285)).
  4. When a control is received, is applied to vehicle by the [ServerGameController](https://github.com/carla-simulator/carla/blob/d289125e98e0fd15882970e779f99d600b621441/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/ServerGameController.cpp#L140-L148).

Hope it helps!
