### ISSUE TITLE
Cannot download any release before 0.9.5

### ISSUE THREAD

**Issue by psesr** [carla-simulator/carla#3293]
Tried Chrome and Firefox, both in Incognito mode:

- Firefox just gives me a white screen
- Chrome: "Access to doc-14-2k-docs.googleusercontent.com was denied"
![Screenshot from 2020-09-14 18-11-17](https://user-images.githubusercontent.com/70888352/93110681-f0f01200-f6b5-11ea-991b-231bc086a966.png)

This happens for any Linux release before 0.9.5 from the [releases page](https://github.com/carla-simulator/carla/releases).

**Comment by germanros1987** [comment]
I can't reproduce this error. Could it be a temporary problem with google drive? Does the problem persist?

**Comment by psesr** [comment]
It seems to work again now.
