### ISSUE TITLE
Maximum nu of multi agents that can be supported

### ISSUE THREAD

**Issue by neeraj310** [carla-simulator/carla#3296]
Hi Support Team

I am working on a survey for Carla capabilities and need few clarifications regarding the number of supported agents.

a) What is the maximum number of agents that can be supported on a normal desktop(16GB RAM, GPU, Linux)

b) Is it possible to add custom vehicles. I want to design my own vehicle and use it inside simulation framework.

Neeraj

**Comment by neeraj310** [comment]
Hi Team

Can you please revert back on this issue

Neeraj

**Comment by germanros1987** [comment]
@pravinblaze could you please provide help with this question?
