### ISSUE TITLE
Get images from the game

### ISSUE THREAD

**Issue by Tak-Au** [carla-simulator/carla#33]
I am able to get the server and client to run.  I loook though the python example.py.  I am trying to have the image and user action save so I can try out behavior cloning.  However I can’t seem to get image save although I set save image to true in the python example file.  I

**Comment by nsubiron** [comment]
Yes, you are right, there is a bug in the current Python implementation. We will fix it asap. Sorry about this

**Comment by Tak-Au** [comment]
Is there anything i can help to solve this problem?

**Comment by nsubiron** [comment]
Hey, thanks for offering! At the moment we are discussing how to fix this, so not much you can help, but it's appreciated :) we'll come with a solution soon

**Comment by Tak-Au** [comment]
I edited the carla_manual_control.py to allow for image and data recording.  I am currently after imitation learning.  My goal is for be able to interface with Keras model to allow for the model to drive the car.

**Comment by naveen7v** [comment]
@nsubiron   I am unable to save the images too... what is the work-around to get the images ...

Thank you

**Comment by nsubiron** [comment]
Hi @naveen7v,

You can check the [client_example.py](https://github.com/carla-simulator/carla/blob/master/PythonClient/client_example.py) to see how is done. You can save the images there by running with the `-i` switch

    $ ./client_example.py -i

Internally, the images received from the simulator have a member function to save the image as png

```python
measurements, sensor_data = client.read_data()

for name, measurement in sensor_data.items():
    measurement.save_to_disk('filename.png')
```

**Comment by naveen7v** [comment]
@nsubiron 

Dear sir...the `client_example.py` is as you say and i ran it with the `-i` switch,
but the `client.read_data()` returns a empty `sensor_data` dict... but `measurements` are there

I just have rgb camera sensor enabled...is it a problem in my side?

Thank you

**Comment by vnmr** [comment]
here
