### ISSUE TITLE
Low mode camera over-exposed

### ISSUE THREAD

**Issue by pdrews** [carla-simulator/carla#330]
I am running Carla 0.8 release on Ubuntu 16.04, rendering on a TitanXp.  When adding an external camera in Low mode, the image looks very over-exposed (colors are washed out, does not match the game window render).  This in not the case when rendering in Epic mode.  Below are examples of Low mode and Epic mode comparisons, along with the code I use to add the camera.

Low mode comparison:
![lowmode](https://user-images.githubusercontent.com/506166/38204475-15a9a21c-3671-11e8-857e-1ad211bd05ce.png)

Epic mode comparison:
![epicmode](https://user-images.githubusercontent.com/506166/38204495-26b03882-3671-11e8-8ef5-176644434b44.png)

Below is the code I use to initialize the camera:
```
camera = Camera('CameraRGB')
camera.set_image_size(640,512)
camera.set_position(0.60,0,1.60) # position of the camera relative to the car in cm
settings.add_sensor(camera)
```

**Comment by juaxix** [comment]
Hello @pdrews please check out the Optimizations branch, I have modified it to change the scene capture camera source to HDRNoAlpha to avoid the problem (combination of gamma + post-fx).
Now it should looks something like this

![colors](https://user-images.githubusercontent.com/996806/38251718-88309084-3752-11e8-825d-8ebdfa2492f3.jpg)

**Comment by pdrews** [comment]
This works great, thanks for the quick fix!
