### ISSUE TITLE
rpc_error during call in function version

### ISSUE THREAD

**Issue by Sujit-kamat** [carla-simulator/carla#3300]
I tried to run the provided smaple CARLA py code, turned out to the runtime error "rpc_error during call in function version"
I checked with py version, I installed necessary packages as well. still not working
Any idea?

**Comment by germanros1987** [comment]
Could you please provide more details (many more details!!)? CARLA version, the OS, etc. 
@marcgpuig once details are provided, could you please try to help?

**Comment by yakkatisai** [comment]
File "spawn_npc.py", line 70, in main
    world = client.get_world()
RuntimeError: rpc::rpc_error during call in function version

i am getting this error please give me solution
