### ISSUE TITLE
[Testing] PR #3306, Fix for random camera crash

### ISSUE THREAD

**Issue by doterop** [carla-simulator/carla#3307]
This issue is intended to track #3306 .

Need to test:
- The cameras keep rendering all the time while the simulation is alive.
- Destroy and create multiple cameras of multiple types and resolutions does not affect the rendering.

**Comment by marcgpuig** [comment]
So far is working fine!
Maybe we can delete the current error message in UE4 since is related to how were working before and it's not an actual issue for the user.

**Comment by glopezdiest** [comment]
Same as @marcgpuig here, I haven't encountered this issue since the fix
