### ISSUE TITLE
Compile LibCarla to work with RSS Error

### ISSUE THREAD

**Issue by liuyandong1988** [carla-simulator/carla#3310]
I want to use the rss sensor in Carla. When i build the RSS  (make LibCarla.client.rss), some errors happened. I have installed the dependencies based on the carla simulator docs.

Have installed:
Ubuntu 16.04
python 3.7
Unreal Engine 4.24
carla 0.9.9

CMake Error at LibCarla/cmake/client/CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by germanros1987** [comment]
@fpasch could you please take a look at this issue?

**Comment by NikhilKalghatgi** [comment]
Hi, I am facing this issue too, please help.
