### ISSUE TITLE
How do you setup an object sensor in C++? How to you "create" and "register the callback"?

### ISSUE THREAD

**Issue by munirjojoverge** [carla-simulator/carla#3313]
How do you setup an object sensor in C++? How to you "create and "register the callback"?
In python is: 
# --------------
# Add Obstacle sensor to ego vehicle. 
# --------------

obs_bp = world.get_blueprint_library().find('sensor.other.obstacle')
obs_bp.set_attribute("only_dynamics",str(True))
obs_location = carla.Location(0,0,0)
obs_rotation = carla.Rotation(0,0,0)
obs_transform = carla.Transform(obs_location,obs_rotation)
ego_obs = world.spawn_actor(obs_bp,obs_transform,attach_to=ego_vehicle, attachment_type=carla.AttachmentType.Rigid)
def obs_callback(obs):
    print("Obstacle detected:\n"+str(obs)+'\n')
ego_obs.listen(lambda obs: obs_callback(obs))

**Comment by germanros1987** [comment]
@marcgpuig could you please provide the right way to do this through the C++ API?
