### ISSUE TITLE
[Testing] PR #3315 (Support OSM for Traffic Manager)

### ISSUE THREAD

**Issue by jackbart94** [carla-simulator/carla#3316]
This issue was raised to track possible issues with PR #3315

What needs to be controlled:

1. Traffic Manager raises an exception telling the user to activate the parameter ``set_osm_mode`` when using an OSM
2. When using this parameter (--osm in ``spawn_npc.py``) vehicles get destroyed when reaching a road that finishes into a void, before falling down.

**Comment by Axel1092** [comment]
I tested it and it works as intended.
