### ISSUE TITLE
Timestamps for camera frames

### ISSUE THREAD

**Issue by pdrews** [carla-simulator/carla#332]
I am running Carla 0.8 release on Ubuntu 16.04, rendering on a TitanXp. I am trying to get data out as fast as possible, so I am using asynchronous mode.  I see that I can get the internal game timestamps for the measurements with `measurements.game_timestamp`, but I don't see a corresponding field for the cameras.  The docs state the cameras may be delayed up to two frames from the measurements, so I would like to know the game timestamp when the frame was rendered.  Did I miss this, or is it something you could add in the future?

**Comment by nsubiron** [comment]
Hi @pdrews, 

Yes, it is something we plan to add. I'm marking this as feature request for 0.8.1 or 0.8.2.
