### ISSUE TITLE
Update docker image when a release is patched

### ISSUE THREAD

**Issue by qhaas** [carla-simulator/carla#3321]
We were encountering an issue that was fixed with CARLA 0.9.7.3, but then we saw that the CARLA 0.9.7 docker image wasn't upgraded to the latest binary release of CARLA 0.9.7.x.  Please rebuild the applicable docker images when a new patch is released.

```
$ docker pull carlasim/carla:0.9.7
0.9.7: Pulling from carlasim/carla
Digest: sha256:0828ebed3bd6c38e2fe27f93cb0b36e4342fa241407d1f64d1c18ac4b04aa201
Status: Image is up to date for carlasim/carla:0.9.7
docker.io/carlasim/carla:0.9.7
$ docker run --rm carlasim/carla:0.9.7 cat VERSION
0.9.7
$ tar -I pigz -xf CARLA_0.9.7.4.tar.gz 
$ cat VERSION 
0.9.7-12-g1f7669e
```

**Comment by germanros1987** [comment]
@qhaas you are right. We will take care of this. Sorry for the inconvenience.

Adding @bernatx to give this the right visibility.
