### ISSUE TITLE
Set the number of threads used for carla server

### ISSUE THREAD

**Issue by yiran98** [carla-simulator/carla#3322]
Hi, I'm using CARLA_0.9.9.4 and I find that, currrently, the amount of CPU resources used for carla server cannot be specified manually. I checked UE4 doc and find a parameter named USEALLAVAILABLECORES which forces the use of all available cores on the target platform, but it seems that this characteristic has not realized in CarlaUE4. So I would like to know if there are other ways to set the number of cores or make full use of CPU. Thanks!

**Comment by germanros1987** [comment]
Duplicate of #3157. We are working on it.
