### ISSUE TITLE
Question about obtaining scene flow information

### ISSUE THREAD

**Issue by gsp-27** [carla-simulator/carla#3323]
Hi,
Thanks for the amazing simulator. I had a question regarding obtaining scene flow information?

I am using CARLA version 0.9.9

* I have made a dummy environment where I have a placed a depth camera and semantic segmentation camera on a vehicle. This vehicle does not move.
* I also spawn one more vehicle right in front of the vehicle with cameras and for every ```tick``` I change the transform of this vehicle. Let's call this vehicle ```teleop_vehicle```
* For each timestep I also collect following information:
- Depth Image
- Semantic Segmentation Image
- Depth camera to world transform which I obtain using ```depth_camera.get_transform()```.
- Teleop vehicle to world transform which Iobtain using  ```teleop_vehicle.get_transform()```

Now my algorithm for obtaining ground truth scene flow between two ticks proceeds as follows:
1. From semantic map obtain pixels just belonging to ```teleop_vehicle```, at both timesteps.
2. Using inverse of intrinsic matrix converts these pixels to sensor coordinate system.
3. Using depth transform convert these points to world coordinate system.
4. Using inverse of teleop vehicle to world transform for timestep 1, convert points at timestep 1 from world coordinate to teleop vehicle coordinate system.
5. Using teleop_vehicle to world transform for timestep 2, obtain the corresponding points in world at timestep 2.

Now here I hope that the pointclouds obtained from step 3 and step 5 should match but they do not.

How would you recommend to obtain scene flow for the objects? Is there some flaw in this method? I would be grateful for any help with this topic.

Sorry if the question is too general.

**Comment by germanros1987** [comment]
Do you have any ideas @marcgpuig ?
