### ISSUE TITLE
carla_sever_pb2

### ISSUE THREAD

**Issue by Yiquan-lol** [carla-simulator/carla#3330]
"CARLA/Sever" is mentioned on the official website of Carla0.8.2. Is it "carla_sever_pb2.py"?
In addition, I found in the file carla_sever_pb2.py that the Settings of "non-player Agents Info" are different from those in the official website. May I ask how to use it

**Comment by germanros1987** [comment]
@Yiquan-lol CARLA server is the process that gets launched when you run the CarlaUE4 binary. It is not carla_server_pb2.py.

My recommendation is: DON'T USE CARLA 0.8.2. Move on and use any of the new versions: 0.9.9.Y.
