### ISSUE TITLE
TrafficLightState Attribute Error while running scenario_runner.py in Carla 0.9.8

### ISSUE THREAD

**Issue by NishanthShettyS** [carla-simulator/carla#3336]
Hi,
I am running carla 0.9.8 on Windows 10.
Carla simulator is working fine and I was able to run the example files given in PythonAPI folder.
But when I tried to run the scenarios from scenario runner (0.9.8 version), I faced the below error 

`File D:\Carla\CARLA_0.9.8\scenario_runner-0.9.8\srunner\scenariomanager\scenarioatomics\atomic_behaviors.py", line 1572, in TrafficLightManipulator
    RED = carla.TrafficLightState.Red
AttributeError: module 'carla' has no attribute 'TrafficLightState'`

I had followed the instruction given in "getting started.md" file and had set the Python paths as given before running the scenario. 
Could you please tell me how to solve this ? Thank you!

**Comment by germanros1987** [comment]
Is this still an issue in 0.9.9? @Axel1092 could you check this?

**Comment by glopezdiest** [comment]
Hey @NishanthShettyS. Seems like scenario runner can't retrieve the location of CARLA's PythonAPI. Could you share your PythonPath? you should have something like *${CARLA_ROOT}/PythonAPI* there
