### ISSUE TITLE
[Testing] API Change: SetVelocity -> SetTargetVelocity #3335

### ISSUE THREAD

**Issue by DSantosO** [carla-simulator/carla#3339]
The issue is for testing PR #3335 

The old function set_velocity and set_angular_velocity has been replace for the new ones set_target_velocity and  set_target_angular_velocity. Be careful if you are using it in the API or as a Command.

`set_velocity -> set_target_velocity`
`set_angular_velocity -> set_target_angular_velocity`
`ApplyVelocity -> ApplyTargetVelocity`
`ApplyAngularVelocity -> ApplyTargetAngularVelocity`

**Comment by bernatx** [comment]
All is working as expected
