### ISSUE TITLE
Multiple "SceneCaptureToDiskCamera" mix up saved images

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#334]
How to reproduce

  * Add at least two SceneCaptureToDiskCameras to the scene
  * Set their _"Save to Folder"_ different for each camera
  * Set their _"Post Process Effect"_ different for each camera
  * Play

Each camera saves in its own folder but the resulting images seem to be somehow mixed up.

**Comment by juaxix** [comment]
Ok @nsubiron the problem is that the Render Target is being shared because the property is defined as Transient. I've also fixed a bug in the constructor naming, btw, we will need to change this SaveToFolder to be checked in runtime because it is different in production than in editor.
