### ISSUE TITLE
MapBuilder: Lane change default value handling not as in open drive spec

### ISSUE THREAD

**Issue by hofbi** [carla-simulator/carla#3341]
There is a difference in the default value of the [MapBuilder](https://github.com/carla-simulator/carla/blob/dev/LibCarla/source/carla/road/MapBuilder.cpp#L198) and the [OpenDrive Spec p. 59](http://www.opendrive.org/docs/OpenDRIVEFormatSpecRev1.4H.pdf) which says for lane chane 

> allow a lane change in the indicated direction taking into account that lanes are numbered in ascending order from right to left. If the attribute is missing, “both” is assumed to be valid.

**Current behavior**

MapBuilder defaults to `none`

**Expected OpenDrive behavior**

MapBuilder defaults to `both`

**Comment by germanros1987** [comment]
@hofbi which version of CARLA are you using?

**Comment by germanros1987** [comment]
@glopezdiest stay alert for a response of the user

**Comment by hofbi** [comment]
The mismatch is for the latest master.

**Comment by Axel1092** [comment]
Hi @hofbi, thank you for pointing this discrepancy with OpenDRIVE standard. We have opened a pull request to address this issue.
