### ISSUE TITLE
object parser non compiling (wrong type cast)

### ISSUE THREAD

**Issue by amastrobera** [carla-simulator/carla#3348]
https://github.com/carla-simulator/carla/blob/f2c3b9fce6f1dbba1852996c546fb2127de93371/LibCarla/source/carla/opendrive/parser/ObjectParser.cpp#L73

should be `node_object.attribute("id").as_uint()` 

and the same here

https://github.com/carla-simulator/carla/blob/f2c3b9fce6f1dbba1852996c546fb2127de93371/LibCarla/source/carla/opendrive/parser/ObjectParser.cpp#L95

**Comment by germanros1987** [comment]
@amastrobera please provide more context. Is this master, dev, which branch?
@Axel1092 could you take a look?

**Comment by Axel1092** [comment]
Hi @amastrobera, it is parsed as string as the OpenDRIVE specifies that the object id is string type and not `uint` and only requires it to be unique: 
![image](https://user-images.githubusercontent.com/35765780/94122109-6a27fb80-fe52-11ea-880e-8b5ce3212eb6.png)

**Comment by amastrobera** [comment]
@germanros1987 it's in the master
@Axel1092 you declared the function AddSignal this way. It's expecting a SignId (alias for uint_32t). So, it's not a string and doesn't compile

```
    element::RoadInfoSignal* AddSignalReference(
        Road* road,
        const SignId signal_id,
        const double s_position,
        const double t_position,
        const std::string signal_reference_orientation);
```

https://github.com/carla-simulator/carla/blob/f2c3b9fce6f1dbba1852996c546fb2127de93371/LibCarla/source/carla/road/MapBuilder.h#L154

**Comment by Axel1092** [comment]
@amastrobera `SignId` is defined as string (see `RoadTypes.h`)
```
  using RoadId = uint32_t;

  using JuncId = int32_t;

  using LaneId = int32_t;

  using SectionId = uint32_t;

  using ObjId = uint32_t;

  using SignId = std::string;

  using ConId = uint32_t;

  using ContId = std::string;
```

**Comment by amastrobera** [comment]
Apologies, my repo must have lost track of the updates on the RoadType.h file. You did it in February.
