### ISSUE TITLE
How to get live vehicle control used during the simulation?

### ISSUE THREAD

**Issue by albe81x** [carla-simulator/carla#335]
Hi,
is there the chance to get the vehicle control parameters  (_steer, throttle, brake, hand_brake_ and _reverse_) from CARLA server - regardless if the simulation is driven by autopilot or manual controls? 
I need to store driving information in a ROS bag format to be used for simulation playback.

Thanks for your support,
Alberto

**Comment by YashBansod** [comment]
If the car was driven in autopilot mode during the simulation you can just use:
`measurements.player_measurements.autopilot_control` if you are not manually adding the noise yourself to it. 
If you are adding noise or you are running the simulation in manual mode, you can store the control command before sending it to the CARLA server in the specified step:
`self.client.send_control(control)`
