### ISSUE TITLE
Carla 0.8.0 benchmark distance error

### ISSUE THREAD

**Issue by TairuiWang** [carla-simulator/carla#336]
Hi,

Currently, I am testing my algorithm in benchmark of Carla 0.8.0. The success flag of each episode is from the Euclidean distance measurement to the end point. However, the distance measurement is not correct. I think this is because of wrong points location. This also gives us wrong time limit for each episode. 
One solution is to use the function '_planner.get_next_command' to decide the success flag.

So, how can we get the correct location from the latest Carla?

Thanks,
Tairui

**Comment by felipecode** [comment]
Hey @TairuiWang 
Yes, there are a few bugs on benchmark for 0.8. 
We are working on a new benchmark system to be released hopefully in the next two days

Thanks
