### ISSUE TITLE
Python cocumentation issue on carla.ActorList

### ISSUE THREAD

**Issue by dhiegomaga** [carla-simulator/carla#3364]
It says the on the [carla.ActorList Python documentation](https://carla.readthedocs.io/en/latest/python_api/#carlaactorlist) that the method `filter(self, wildcard_pattern)` returns a *list*. 

However, I'm trying to concatenate those lists, and getting the error: 

```python
self.world.get_actors().filter('vehicle.volkswagen.*') + self.world.get_actors().filter('vehicle.tesla.*')

Exception:  <class 'TypeError'> occurred.
unsupported operand type(s) for +: 'ActorList' and 'ActorList'
```

Because it's probably not a `list` but a `carla.ActorList`. 

I'm doing this because I want to combine filters, say, match for `'vehicle.volkswagen.*'` and `'vehicle.tesla.*'`, but it is not clear how to do this using only the `wildcard_pattern`.

**Comment by thytless** [comment]
You may use `itertools.chain` or simply convert both of them into list.
