### ISSUE TITLE
Capture images synchronized

### ISSUE THREAD

**Issue by ChiefAlu** [carla-simulator/carla#3370]
Hi,

I am searching for a solution to attach 2 cameras to a vehicle and capture the images at the exact same time.
I am using the sample code from 'examples/tutorial.py' and modified it:
```python
camera1_transform = carla.Transform(carla.Location(x=1.5, y=0, z=2.4))
camera2_transform = carla.Transform(carla.Location(x=1.5, y=0.1, z=2.4))
camera1 = world.spawn_actor(camera_bp, camera1_transform, attach_to=vehicle)
camera2 = world.spawn_actor(camera_bp, camera2_transform, attach_to=vehicle)
camera1.listen(lambda image: image.save_to_disk('out1/%06d.png' % image.frame))
camera2.listen(lambda image: image.save_to_disk('out2/%06d.png' % image.frame))
```

Is it possible to make sure that the cameras are synchronized?

Thanks

**Comment by danielrich** [comment]
There is a sensor sync example. https://github.com/carla-simulator/carla/blob/dev/PythonAPI/examples/sensor_syncronization.py shows you how to run things synchronous.
