### ISSUE TITLE
Exporting the map by myself causes UE4 to crash

### ISSUE THREAD

**Issue by xiaoyang666** [carla-simulator/carla#3372]
Thank you very much for this big update.
In the example file Townbig, using config.py, I have successfully imported it. But when I exported the osm file from the openstreet website and converted it into an xodr file, the following problems occurred.
Looking forward to the professional reply.
Thanks again.
![Screenshot from 2020-09-28 09-25-16](https://user-images.githubusercontent.com/37059168/94381932-81762a00-016d-11eb-82ef-f7fc0ca48d9d.png)
[Uploading demo_xodr.zip…]()

**Comment by Axel1092** [comment]
Hi @xiaoyang666, can you provide us with the error log in the console? Or at least the full message in the Unreal Engine crash reporter? I guess you are trying to load an osm file with `python3 config.py --osm-path=/path/to/osm` right?
