### ISSUE TITLE
Vehicle Dynamic Model

### ISSUE THREAD

**Issue by KasraMokhtari2112** [carla-simulator/carla#3387]
Hi everyone. Can somebody help me to have an idea about the dynamic models of the car? I know that they use Unreal's default vehicle dynamics, which is NVIDIA's PhysX vehicle model, but I cannot find anything helpful for that. For example, what is the maximum possible change in the car's angular velocity or forward velocity?

What I want to do is predicting the vehicle future position by knowing the throttle value, the current speed, and steering wheel value. How can I get the output of the dynamic model without running the simulation? Thanks!

**Comment by xiaoyang666** [comment]
I have the same problem.

**Comment by aquibrash87** [comment]
@KasraMokhtari2112 did you make any progress on the topic. I am also interested in it.

Thanks!

**Comment by castrong** [comment]
@KasraMokhtari2112 and @aquibrash87 I am also interested in this, did you have any progress?

**Comment by AOOOOOA** [comment]
> I guess you could make a 'phenomelogical' model using the quantities you mentioned for predicting the next velocity/position but it is not going to be a straigfoward formula, because the model of PhysX takes in account a lot of things like the engine throttle, the reaction ot the suspension and tires, and some drag/dumping terms.
> Sorry I cannot be more helpful with that.

Hi, same here. Do you guys have any progress? Thanks!
