### ISSUE TITLE
Framerate cap and no-rensering mode

### ISSUE THREAD

**Issue by pomputer** [carla-simulator/carla#3392]
Hi!
Is it possible to configure a framerate cap (60fps) in order to not waste resources for rendering useless frames. Also, is it possible to have the server in no-rendering mode, but the clients in normal rendering mode?

Thanks!

**Comment by Derekabc** [comment]
Hi Promputer, any progress on this problem?

**Comment by pomputer** [comment]
Sadly, no.

**Comment by pomputer** [comment]
> Hi Promputer, any progress on this problem?

Sadly, no.

**Comment by germanros1987** [comment]
@pomputer, you can set the simulation to synchronous mode, and then you can tick from the client-side at your preferred speed to produce the cap.

**Comment by germanros1987** [comment]
+@DSantosO to provide help

**Comment by DSantosO** [comment]
Hello @pomputer, @Derekabc,
As @germanros1987 explained, you can set the simulator in synchronous mode and set the delta seconds (1/fps) that you want. You can find all the information [here](https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/). 
In the same world settings, you can check the `no_rendering_mode = True` to do what you need.

**Comment by pomputer** [comment]
Thank you!
