### ISSUE TITLE
ExampleDeviceProfileSelector failed

### ISSUE THREAD

**Issue by yumianhuli2** [carla-simulator/carla#3397]
Hello Carla Team!
According to this https://carla.readthedocs.io/en/latest/build_linux/, I built the simulator in the Linux environment. All the steps were successful, but when I ran ./UE4Editor
I got this error message
![Screenshot from 2020-10-06 08-49-26](https://user-images.githubusercontent.com/39210837/95161682-668f5f80-07d6-11eb-8351-045e8626dba4.png)
How can I solve this problem?Thanks！

**Comment by FAM-vive** [comment]
hello, I meet the same error, how do you solve that? can you tell me? Thanks!

**Comment by FAM-vive** [comment]
@yumianhuli2
