### ISSUE TITLE
CARLA Rebuild failed on Ubuntu

### ISSUE THREAD

**Issue by LoSealL** [carla-simulator/carla#340]
>In file included from /home/xxxx/works/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/Carla/Module.Carla.cpp:52:
/home/xxxx/works/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerAIController.cpp:162:35: error: no
      matching member function for call to '__Internal_AddDynamic'
  Perception->OnPerceptionUpdated.AddDynamic(this, &AWalkerAIController::SenseActors);
  \~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime/Core/Public/Delegates/Delegate.h:380:44: note: expanded from macro 'AddDynamic'
#define AddDynamic( UserObject, FuncName ) __Internal_AddDynamic( UserObject, FuncName, STATIC_FUNCTION_FNAME...
                                           ^
/home/xxxx/works/UnrealEngine/Engine/Source/Runtime/Core/Public/Delegates/DelegateSignatureImpl.inl:1131:7: note: 
      candidate function [with UserClass = AWalkerAIController] not viable: no known conversion from 'void
      (AWalkerAIController::*)(TArray<AActor *>)' to 'typename
      FDelegate::TMethodPtrResolver<AWalkerAIController>::FMethodPtr' (aka 'void (AWalkerAIController::*)(const
      TArray<AActor *, FDefaultAllocator> &)') for 2nd argument
        void __Internal_AddDynamic( UserClass* InUserObject, typename FDelegate::template TMethodPtrResolver< ...
             ^
1 error generated.

The Setup.sh and Update.sh all succeeded. UE4 builds successfully too.
_P.S_ In the latest 0.8.1

**Comment by juaxix** [comment]
are you using UE4.18.3 or 4.19? if it's 4.19 you need to change AWalkerAIController::SenseActors like this [cpp](https://github.com/carla-simulator/carla/blob/ue-4.19/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerAIController.cpp#L228)  and [.h](https://github.com/carla-simulator/carla/blob/ue-4.19/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerAIController.h#L47)

**Comment by LoSealL** [comment]
Yeah, it's the version mismatch. Thanks @juaxix

**Comment by frestone** [comment]
I have the same problem when compiling carla 0.8.4 with UE4.19.2, and I found this page, unfortunately, I can't download the files (cpp and .h)that you provided.  @juaxix

**Comment by marcgpuig** [comment]
@frestone Please use UE4.18.x

**Comment by jhallier** [comment]
I am using UE4.18.3 and have the same problem. Is there another workaround?

**Comment by nsubiron** [comment]
Hi @jhallier,

The latest release 0.9.0 requires 4.19, that error appears because you are trying to build with 4.18. I think it's a problem of cached configuration, before switching between engine versions try cleaning intermediate files

```sh
make clean
export UE4_ROOT=~/UnrealEngine_4.19
make CarlaUE4Editor
```

**Comment by jhallier** [comment]
Hi @nsubiron ,
thanks, that actually worked! I thought I did compile with UE4.19 before, this was also shown in the make outputs, but I probably did not make clean after using UE4.18 before. Thanks for the hint!

**Comment by petevalle** [comment]
I ran into this same problem -- others who bump into this should be aware that [the instructions for building on Linux](https://carla.readthedocs.io/en/latest/how_to_build_on_linux/) suggest that it "may be best" to use the stable branch, but provides instructions that aren't currently compatible with the stable branch, for example the instructions:
  - say to use Unreal Engine 4.19 which is incompatible with the stable branch (results in the error reported in this thread).
  - mention commands like `make launch` and `make package` which aren't available in the stable branch.

**Comment by nsubiron** [comment]
The stable branch has its own documentation https://carla.readthedocs.io/en/stable/how_to_build_on_linux/

**Comment by ssooffiiaannee** [comment]
can anyone explain where I can find the rebuild.sh script? following this https://carla.readthedocs.io/en/stable/how_to_build_on_linux/ tutorial, and I can't find it in the unreal repo.
