### ISSUE TITLE
[Testing] PR #3399, Fixed sensor_tick on cameras

### ISSUE THREAD

**Issue by doterop** [carla-simulator/carla#3400]
This issue is intended to track PR #3399 .

Need to test:
- The cameras work without issues.
- The attribute sensor_tick works as expected.

To test it, add `bp.set_attribute("sensor_tick", str(2.5))` before spawning a camera. The value can be changed of course.

**Comment by guntherkrehl** [comment]
FYI: The implemented fix resolved the issues for me. Thanks!

**Comment by doterop** [comment]
Thanks to you  @guntherkrehl for confirming!

**Comment by OmarAbdElNaser** [comment]
the implemented fix doesn't solve the issue for me.
