### ISSUE TITLE
Unable to run PythonApi in Carla simulator

### ISSUE THREAD

**Issue by arvindvk555** [carla-simulator/carla#3405]
RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000

**Comment by nagasanjay** [comment]
I face the same issue. Let me elaborate it.
I use carla-from-source, in windows 10.

I built everything, opened a map in Unreal editor and clicked the play button.
I get the spectator view.

But when I run the manual_control.py (or any other files) it shows the error `RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000`.
