### ISSUE TITLE
PythonAPI/dependencies/lib/libboost_python27.a is not generated

### ISSUE THREAD

**Issue by gismo07** [carla-simulator/carla#3408]
Building the PythonAPI for the current carla version is failing for python 2.7.

After issuing the following commands:
```bash
make setup
make PythonAPI.2
```

we get the error, that `PythonAPI/dependencies/lib/libboost_python27.a` was not found.

**Comment by jonselling** [comment]
After running into the same issue, you need to run setup explicitly with python 2.
```
make setup ARGS="--python-version=2"
make PythonAPI.2
```
