### ISSUE TITLE
Question about switching controller (eg. switch from keyboard to steering wheel)

### ISSUE THREAD

**Issue by shiyuanzhu123** [carla-simulator/carla#3410]
Hi, I'm running the "manual_control.py" script (in example folder) in my own map and  I want to achieve one function: switch driving method from keyboard to steering wheel by pressing one button. Could you please give me some instructions on that? Thanks a lot!

Yuan Shi

**Comment by seuwcs** [comment]
if you had connected a steering wheel to carla?

**Comment by seuwcs** [comment]
But I am wondering how did you solve the problem, as I met the same problem.  Would you mind giving me some suggestions regarding this question. Very much thank!
I had a steering wheel but it can't be connected to Carla in Win10, How it can be solved?

**Comment by jadesop** [comment]
Hello, I'm curious about your steering wheel, do you use the Logitech steering wheel? Or series of Thrustmaster?
