### ISSUE TITLE
Example High FOV Lens Distortion Parameters

### ISSUE THREAD

**Issue by jimmyw404** [carla-simulator/carla#3412]
Thank you for making a Lens Distortion model! However I am having trouble using it to generate the kind of lens distortions I typically see in real-world lenses with high fields of view.

I am trying to simulate a wide angle lens and a fisheye lens. I understand that 180 degrees are annoying to render, so I don't need to go that high. 160 degrees is enough.

Below is a sample of a wide angle 160 degree lens from https://www.nytimes.com/wirecutter/reviews/best-dash-cam/

![image](https://user-images.githubusercontent.com/29664262/95492557-42b05300-0969-11eb-8918-338020760c39.png)

And here is a sample of a simulated fisheye lens (shown inset) from https://medium.com/cruise/cruise-simulation-sensor-development-be57a5991fe6

![image](https://user-images.githubusercontent.com/29664262/95492668-71c6c480-0969-11eb-8105-050bf8b9cbe9.png)

I tried quite a few different options to get this kind of lens distortion but everything I tried distorted it in unrealistic ways. I used this documentation to try and figure it out:

https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera

![image](https://user-images.githubusercontent.com/29664262/95493213-2b259a00-096a-11eb-9ea6-f0e830816cda.png)

Below is the distorted camera in the manual_control.py with a fov of 160:

![image](https://user-images.githubusercontent.com/29664262/95493128-092c1780-096a-11eb-9496-27af947d2115.png)

Would it be possible to get example parameters for the lens distortion that would produce something similar to the above wide angle / fisheye lens images? Or should I pursue a different lens model (ex: https://docs.unrealengine.com/en-US/API/Plugins/LensDistortion/FLensDistortionCameraModel/index.html or opencv lens distortion plugin: https://docs.unrealengine.com/en-US/API/Plugins/OpenCVLensDistortion/index.html )
        

@marcgpuig

**Comment by jimmyw404** [comment]
#776 Lens distortion shader
#2145 Lens distortion shader
#754 Lens distortion shader
#2669 Fisheye camera support in carla
#3130 Lens distortion attributes
#2048 Lens Distortion

**Comment by jimmyw404** [comment]
I'm still very interested in guidance on this issue!

**Comment by germanros1987** [comment]
@DSantosO @doterop I would like to provide an answer to this issue. Please, work on this.

**Comment by YifuTao** [comment]
Hi, I would be very interested as well in the fisheye camera model / hige fov camera by the distortion model. 

I found the [distortion model documentation ](https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera) does not currently provide enough information on guiding that. This is also mentioned also [in this issue](https://github.com/carla-simulator/carla/issues/3130#issuecomment-780353448)

**Comment by Glazyee** [comment]
> Hi, I would be very interested as well in the fisheye camera model / hige fov camera by the distortion model.
> 
> I found the [distortion model documentation ](https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera) does not currently provide enough information on guiding that. This is also mentioned also in #3130.

Hi, FYI, the RGB camera seems based only on the Scene Capture Component 2D, which doesn't include a distortion model. You might need to write a post-processing script to introduce the distortion or either create a blueprint using any other cinematic camera blueprint available in unreal engine editor.

**Comment by mittkongg** [comment]
> Thank you for making a Lens Distortion model! However I am having trouble using it to generate the kind of lens distortions I typically see in real-world lenses with high fields of view.
> 
> I am trying to simulate a wide angle lens and a fisheye lens. I understand that 180 degrees are annoying to render, so I don't need to go that high. 160 degrees is enough.
> 
> Below is a sample of a wide angle 160 degree lens from https://www.nytimes.com/wirecutter/reviews/best-dash-cam/
> 
> ![image](https://user-images.githubusercontent.com/29664262/95492557-42b05300-0969-11eb-8918-338020760c39.png)
> 
> And here is a sample of a simulated fisheye lens (shown inset) from https://medium.com/cruise/cruise-simulation-sensor-development-be57a5991fe6
> 
> ![image](https://user-images.githubusercontent.com/29664262/95492668-71c6c480-0969-11eb-8105-050bf8b9cbe9.png)
> 
> I tried quite a few different options to get this kind of lens distortion but everything I tried distorted it in unrealistic ways. I used this documentation to try and figure it out:
> 
> https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera
> 
> ![image](https://user-images.githubusercontent.com/29664262/95493213-2b259a00-096a-11eb-9ea6-f0e830816cda.png)
> 
> Below is the distorted camera in the manual_control.py with a fov of 160:
> 
> ![image](https://user-images.githubusercontent.com/29664262/95493128-092c1780-096a-11eb-9496-27af947d2115.png)
> 
> Would it be possible to get example parameters for the lens distortion that would produce something similar to the above wide angle / fisheye lens images? Or should I pursue a different lens model (ex: https://docs.unrealengine.com/en-US/API/Plugins/LensDistortion/FLensDistortionCameraModel/index.html or opencv lens distortion plugin: https://docs.unrealengine.com/en-US/API/Plugins/OpenCVLensDistortion/index.html )
> 
> @marcgpuig

Does k1 k2 k3 have anything to do with lens_circle_falloff lens_circle_multiplier？

**Comment by jimmyw404** [comment]
> Does k1 k2 k3 have anything to do with lens_circle_falloff lens_circle_multiplier？

I don't know. I don't know of any way to relate the lens distortion in CARLA to anything like OpenCV or real camera lenses.

**Comment by yuanhaorannnnnn** [comment]
@jimmyw404 Hi, I'm facing the same problem and just find this page, while at first I've a naive question. When you changed the distoration parmameters of the sensor.camera.rgb, and you can see the difference with running the manual_control.py, how did you make that? Which file you change to do this?
Many thanks in advance.

**Comment by danieleceUL** [comment]
In my case, CARLA doesn't have a distorted RGB view when I press number 8 to switch to camera distortion. Is it possible to find the example script for what is happening here?

**Comment by jimmyw404** [comment]
@yuanhaorannnnnn  @danieleceUL  

in this file: https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control.py#L1066

```
            ['sensor.camera.rgb', cc.Raw, 'Camera RGB Distorted',
                {'lens_circle_multiplier': '3.0',
                'lens_circle_falloff': '3.0',
                'chromatic_aberration_intensity': '0.5',
                'chromatic_aberration_offset': '0'}],
```

Change the fov to some high value, ex: 160 as per https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera ex:


```
            ['sensor.camera.rgb', cc.Raw, 'Camera RGB Distorted',
                {'lens_circle_multiplier': '3.0',
                'lens_circle_falloff': '3.0',
                'chromatic_aberration_intensity': '0.5',
                'chromatic_aberration_offset': '0',
                'fov':'160'}],
```

**Comment by danieleceUL** [comment]
Thank you @yuanhaorannnnnn. I tried it out there looks great!

**Comment by danieleceUL** [comment]
Sorry it was you @jimmyw404 who was so helpful! :-)

**Comment by abhay-707** [comment]
> Hello, Please, have you found an answer for this question? what is the relationship between OpenCV distortion model and CARLA model?

I would like to know the answer of this question
