### ISSUE TITLE
[Docker] How to get log when running a shipped docker

### ISSUE THREAD

**Issue by thytless** [carla-simulator/carla#3414]
Platform: Ubuntu 16.04
Carla version: 0.9.9.4
When I run carla in docker, I cannot get any log except:
`4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found`
Is there any options or settings for us to modify to enable UE4 and carla log?

**Comment by zzxaijs** [comment]
i have the same question!
