### ISSUE TITLE
Error when convert OSM to XODR

### ISSUE THREAD

**Issue by siraphopp** [carla-simulator/carla#3415]
## My code:

f = open('map.osm', 'r')
osm_data = f.read()
f.close()

settings = carla.Osm2OdrSettings()
xodr_data = carla.Osm2Odr.convert(osm_data, settings)

## Error:

RuntimeError: unable to open file 'https://sumo.dlr.de/xsd/types_file.xsd'
 In file 'built in type map'
 At line/column 1/0.

  The types could not be loaded from 'built in type map'.

## My OSM map:

[map.osm.zip](https://github.com/carla-simulator/carla/files/5354125/map.osm.zip)

**Comment by jakubLangr** [comment]
Hi @siraphopp we have the same issue—did you ever figure out the solution?

**Comment by ssuralcmu** [comment]
I am trying to load an OSM file to generate a Carla Map but have the exact same error. Has anyone figured this out yet?

**Comment by LVJ047** [comment]
I am also trying to obtain the same results but I am getting the following error while using Carla 0.9.10 :
![image](https://user-images.githubusercontent.com/48725411/98642382-69402000-2353-11eb-8ce8-1bd5922f8b29.png)

**Comment by karolmajek** [comment]
This was my error:
```
Warning: Cannot read local schema '../carla/data/xsd/types_file.xsd', will try website lookup.
Traceback (most recent call last):
  File "convert_osm2carla.py", line 17, in <module>
    xodr_data = carla.Osm2Odr.convert(osm_data, settings)
RuntimeError: unsupported protocol in URL
 In file 'built in type map'
 At line/column 1/0.

  The types could not be loaded from 'built in type map'.
```

# Solved it!!!

```
Warning: Cannot read local schema '../carla/data/xsd/types_file.xsd', will try website lookup.
```

run this from `CARLA_0.9.11/PythonAPI/examples` directory

**Comment by munirjojoverge** [comment]
I don't see how this has been solved? what did you run?
