### ISSUE TITLE
Wrong agent transformation location

### ISSUE THREAD

**Issue by wzhAptiv** [carla-simulator/carla#342]
New issue content in the comment below, which is located and solved in #345. 

~~'I followed #314 to plot bbox on my camera. '~~
~~'Using box_extend & location & rotation, I can get the 3d coordinate for vertices in all 3D bbox in the world space. Then I transform all vertices to my camera coordinate, then draw a box covering all eight vertices for each object. '~~

~~'Following the code in the issue above, I found I the transformation is wrong because of '~~
~~'get_unreal_transform() in carla.sensor.Sensor '~~
~~'the 'to_unreal_transform' will make unexpected transformation that the shape and size of the car will change in this space. '~~
~~'Other transformation will keep the shape and size of a car stable in its space. '~~

~~'I don't really understand why we need do this unreal_transform, with roll=-90, yaw=90, scale_x=-1. '~~

~~'Also, the wrong transformation only affects turning cars, significant when world_yaw is [+-45, +-135]. 
'~~
~~'Thank you!'~~

**Comment by wzhAptiv** [comment]
@marcgpuig screenshot added. 
The car in the red circle shows the wrong vertices, normally, it should be like in the yellow circle. 
The problem only occurs when it's turning. But the car in the space of 'to_unreal_transform' will have different shape & size according to its yaw. 

![wrong transform marked](https://user-images.githubusercontent.com/37740387/38612504-31ae97fc-3d87-11e8-9ba2-41c74ab5b63d.png)

**Comment by wzhAptiv** [comment]
@marcgpuig Hello, after some more experiment, I found that the box_extent from agent is not stable, and may contains negative value. 
Could you please explain what's the actual meaning of this measurement? 
I thought it was the metrics from 3D-model, and won't be affected by its location/orientation.

**Comment by wzhAptiv** [comment]
@marcgpuig Sorry for this issue, I've finally found that it's because of some bug in my script. 

But another problem is for this as well. I feel the z-axis in 'location' is not at the center but at the chassis of the car, when calculating the 3D-bbox for each object, I need to use location.z + 2*box_extend.z. And also need to minus the wheel height. 
Is this intended to be like this? 

Thank you!

**Comment by marcgpuig** [comment]
Hi @wzhAptiv, that sounds weird.

I will give you a better explanation when I investigate it later on, but for now I can tell you that the `box_extent` is explained at [Transform and bounding box](http://carla.readthedocs.io/en/latest/measurements/#non-player-agents-info), in the documentation.
It contains the 3D vector from the center of the car to one vertex of the bounding box.

> I found that the box_extent from agent is not stable, and may contains negative value

We are not able to reproduce your error, even with many agents. Our `box_extent` returns the same value each frame and it is not afected by the agent location/orientation. Which transformations are you makeing before getting that negative values?

Could you please tell us which version are you using?

**Comment by wzhAptiv** [comment]
Hi @marcgpuig , thank you for your reply. I made some mistake and is explained in the last comment. But I got some other question on the transform.location for each agent. Could you please check it?

**Comment by marcgpuig** [comment]
Well @wzhAptiv 
I send a message that I wrote yesterday but wanted to check a few things this morning. I sended it without reloading this page so I didn't read your last message, sorry for that, I just delete it.

Let me check this new information and I'll reply you soon :)

**Comment by marcgpuig** [comment]
Hi @wzhAptiv 
Thanks for your feedback!
We localized the problem, look at #345.

**Comment by wzhAptiv** [comment]
@marcgpuig Thank you for your help!

**Comment by lxtttt** [comment]
@wzhAptiv  I am currently working on drawing 2d bounding box. May i know how u find the vertex of the 3d bounding box and transfer them to camera coordinates? thanks a lot!!!

**Comment by wzhAptiv** [comment]
Hi @lxtttt , you need to convert the eight vertices of the 3D bounding box of the object vehicle into world coordinate, then apply the projection to camera. According to your screenshot, maybe you only consider four front vertices, not the complete eight ones.
