### ISSUE TITLE
The coordinates of the corner of the parking lot

### ISSUE THREAD

**Issue by jujuau** [carla-simulator/carla#3422]
Hi,
Thanks for the great simulator. I have a question.
Is it possible to get the coordinates of the corner of the parking lot?(uv, xyz,...)
For example, the red circle in the image below.

![temp](https://user-images.githubusercontent.com/72644509/95672036-5ca39d00-0bd8-11eb-8e74-21c8f3e32231.png)

**Comment by nagasanjay** [comment]
yes, you can. refer this [thread](https://github.com/carla-simulator/scenario_runner/issues/40)
After running the server, you will get into spectator mode. Move to your desired location to get the coordinates

**Comment by jujuau** [comment]
Thank you for your reply.


For example, does it mean that the location (x, y, z) on the map can be obtained by doing the following?

```
spectator = world.get_spectator()  
camera_bp = world.get_blueprint_library().find('sensor.camera.rgb')  
camera_transform = carla.Transform(carla.Location(x=-10,z=10), carla.Rotation(-45,0,0))  
camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)  
print(spectator.set_transform(camera.get_transform()))
```
output example
→Transform(Location(x=25.259499, y=-49.834530, z=1.488399), Rotation(pitch=-0.008087, yaw=-87.951607, roll=-0.741791))

In the same way, get the coordinates (x, y, z) of the parking lot.
And the UV coordinates can be calculated from the camera's coordinates and the parking lot's coordinates.
Is this understanding correct?

**Comment by PTorr** [comment]
Hi,
Where is the parking lot?

**Comment by jujuau** [comment]
Is it the place shown in the image above?
If so, it's in Town 05.

**Comment by PTorr** [comment]
Thank you

**Comment by omerler** [comment]
Hi!
I'm new at Carla as well. 
How did you extract the parking spot's corners, please?
can you extract the all the parking spots in a given image in the simulator? maybe as a mask? maybe as a mask of parking spots instances?

Thanks A lot!

**Comment by nagasanjay** [comment]
> Hi @nagasanjay
> I'm new at Carla as well.
> How did you extract the parking spot's corners, please?
> can you extract the all the parking spots in a given image in the simulator? maybe as a mask? maybe as a mask of parking spots instances?
> 
> Thanks A lot!

Hi @omerler. I was just giving a suggestion. I didn't do that myself.

**Comment by MariamEssam** [comment]
@jujuau can you please advise which town is this?
