### ISSUE TITLE
Additional Assets for nightly build missing

### ISSUE THREAD

**Issue by hh0rva1h** [carla-simulator/carla#3425]
Usually the assets for the nightly build were available here:
https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/Dev/AdditionalMaps_Latest.tar.gz

Now that link is not working anymore. How to obtain the additional Maps for the nightly build? @germanros1987

**Comment by XGodina** [comment]
Do you mean this?
https://github.com/carla-simulator/carla/releases
