### ISSUE TITLE
Lightning problem in case of a new map in the latest build 0.9.10

### ISSUE THREAD

**Issue by mercurylaci** [carla-simulator/carla#3426]
I'm using Carla 0.9.10, Unreal Engine 4.23.3 on Ubuntu 18.04.
On the previous build 0.9.9 I don't have this issue, when I import a map (which was created by roadrunner), in the Unreal Editor there is proper lightning, but when I hit the play button (or create a package), there is complete darkness.
![map](https://user-images.githubusercontent.com/63070010/95688046-9b048080-0c07-11eb-84d0-bf77e3c18d8e.png)
![black](https://user-images.githubusercontent.com/63070010/95688055-a5267f00-0c07-11eb-8932-f10eaccb8db5.png)

And I have this error:
![error](https://user-images.githubusercontent.com/63070010/95688060-ace62380-0c07-11eb-9ef9-572c6be0648a.png)

I tried to change the weather in Carla, add more lights to the map, removed the default one and add new one, none of them helped. I've imported these maps in previous Carla versions (0.9.8-0.9.9) and worked perfectly.

Does anyone knows the solution for this problem? 
Thanks in advance!

**Comment by Madecu** [comment]
Hi @mercurylaci, in the 0.9.10 release we had changed the lighting in the scene. We merged all the lighting assets inside a Blueprint.
To solve the issue you just need to delete the Light Source (Directional Light), ExponentialHeightFog, Skylight, and SkySphere from your scene and drag BP_Sky into it.

![image](https://user-images.githubusercontent.com/54811869/95855856-5f79cb80-0d59-11eb-8631-80f4964fecef.png)

**Comment by mercurylaci** [comment]
Thank you! It's working now.

**Comment by EchoYJJ** [comment]
Hi! @Madecu ,I do as you recommand.
The scene shows up when I am high. As I getting lower to approach the road, it get darker so that I can't view it.
Do you know how to solve it? Thanks in advance!
![image](https://user-images.githubusercontent.com/75726020/102878195-db437300-4482-11eb-99f6-f114e40f6af8.png)

**Comment by seuwcs** [comment]
> Hi @mercurylaci, in the 0.9.10 release we had changed the lighting in the scene. We merged all the lighting assets inside a Blueprint.
> To solve the issue you just need to delete the Light Source (Directional Light), ExponentialHeightFog, Skylight, and SkySphere from your scene and drag BP_Sky into it.
> 
> ![image](https://user-images.githubusercontent.com/54811869/95855856-5f79cb80-0d59-11eb-8631-80f4964fecef.png)

Hello, I have a small question that is which folder should the BP_sky dragged into? @Madecu  @mercurylaci

**Comment by seuwcs** [comment]
Hello Friends. After deleting the Light Source (Directional Light), ExponentialHeightFog, Skylight, and SkySphere from the scene and drag BP_Sky into the scene. I clicked Play, and run the scrip "manual_control.py" in  the folder "carla/PythonAPI/examples", a mistake occurrd that is :

WARNING: cannot parse georeference: ''. Using default values. 
No recommended values for 'speed' attribute
There are no spawn points available in your map/town.
Please add some Vehicle Spawn Point to your UE4 scene.
![2021-04-14 11-02-50屏幕截图](https://user-images.githubusercontent.com/65322137/114648416-54f0bc80-9d11-11eb-9f7c-4a19deec2052.png)

I'd like to know if it is useful to add some spawn points in my scene to solve my problem, as I have added some spawn points in the scene, but the questions still remains.
Does anyone knows the solution for this problem?
Thanks in advance!

@Madecu @mercurylaci

**Comment by xuhan417** [comment]
@seuwcs 
 This warning means your xodr file is missing georeference header. 
Also, your map does not have spawpoints. You can use "opendrive export preview tool" in roadrunner to check your export and look for any warnings. And you should use the "slip road tool" in the roadrunner to connect the intersections. Once you connect the roads properly the waypoint will be generated automatically.
