### ISSUE TITLE
Randomized vehicle license plates not working

### ISSUE THREAD

**Issue by ebadi** [carla-simulator/carla#3429]
The randomized license plate feature is not working. According to [CARLA 0.4.1 Changelog](https://github.com/carla-simulator/carla/blob/dev/CHANGELOG.md#carla-041), the "randomized vehicle license plates" is supported since 0.4.1. The documentation for [vehicle modeling](https://carla.readthedocs.io/en/latest/tuto_A_vehicle_modelling/) also mentions license plate texture and there is a blueprint (BaseVehiclePawn > License Plate) defined for license plates. There are license plate textures assets accessible from `/Content/Carla/Static/GenericMaterials/LicensePlates/Textures/` however I cannot find any documentation that explains how the default license plate can be changed.

![image](https://user-images.githubusercontent.com/1111940/95719554-48ab7a00-0c70-11eb-8eb3-f2a4f531c0f4.png)

![image](https://user-images.githubusercontent.com/1111940/95730552-b1015800-0c7e-11eb-8885-f1db5608a8d4.png)

**Comment by Madecu** [comment]
Hi @ebadi, I will look into it. I'll let you know if I find something.

**Comment by ebadi** [comment]
It is very much appreciated @Madecu.
I don't have much experience in unreal engine and 3D modelling but I would be glad to contribute as much as I can if pointers/references are provided.

**Comment by Madecu** [comment]
Hi @ebadi, I found that we had had this feature disabled for a while. If you want to enable it, you just need to do the next two steps:

First, connect the LicensePlate function to the EventGraph

![image](https://user-images.githubusercontent.com/54811869/96129199-a3560780-0ef6-11eb-8c62-2dbf660cf2ed.png)

Second, you need to delete a node that is no longer functioning and replaced it with "Random Integer"

![image](https://user-images.githubusercontent.com/54811869/96129434-e7490c80-0ef6-11eb-8881-9e02552a9c24.png)


Bonus track. If you want to change the player's license plate too, connect the "True" output to this node:

![image](https://user-images.githubusercontent.com/54811869/96129787-5b83b000-0ef7-11eb-95a7-e4b56ce8b759.png)

I hope this helps you

**Comment by ebadi** [comment]
Thank you. I tried it and it works now. :) 

I think there are other issues like some license plates keeping their default values. I close this issue and try to look deeper later. If it was relevant to this issue, I reopen this, otherwise I report a new issue and tag you there. 
Thank you so much @Madecu .
