### ISSUE TITLE
Problem running OpenScenario files

### ISSUE THREAD

**Issue by WhyTrouble** [carla-simulator/carla#3433]
Hi,

i am new to Carla and i want to simulate OpenScenarios. I've got the packaged version of Carla and the scenario runner, both same versions. 
Starting 'normal' with the scenario runner included scenarios is fine, but when I open OpenScenario files (also the included ones), I get an error everytime.
After starting the server I execute (as example):
'..\scenario_runner-0.9.10>python scenario_runner.py --openscenario C:\Users\windb\Desktop\scenario_runner-0.9.10\srunner\examples\PedestrianCrossingFront.xosc --output'

and the manual_control.py from the scenario runner.

My output is:

File "C:\Users\windb\Desktop\scenario_runner-0.9.10\srunner\scenariomanager\scenarioatomics\atomic_criteria.py", line 829, in update
    current_wp = self._map.get_waypoint(current_loc, lane_type=carla.LaneType.Any)
OverflowError: can't convert negative value to unsigned int
can't convert negative value to unsigned int
Destroying ego vehicle 259
ERROR: failed to destroy actor 259 : unable to destroy actor: not found
No more scenarios .... Exiting

Thanks for your help!

**Comment by glopezdiest** [comment]
Hey @WhyTrouble, that isn't related to OpenScenario, but to a Windows error. Check [this](https://github.com/carla-simulator/carla/issues/3119) issue here for more information. We are working on it.

In the meantime, if you don't care that ScenarioRunner doesn't correctly detect that the vehicle has entered the sidewalk, change that line to

> current_wp = self._map.get_waypoint(current_loc, lane_type=carla.LaneType.Any)

and the simulation won't give you any errors.
