### ISSUE TITLE
carla0.9.10-xdg-user-dir: not found

### ISSUE THREAD

**Issue by lz1159435992** [carla-simulator/carla#3444]
When executing 0.9.10 docker with

$ docker run -p 2000-2002:2000-2002 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=1 carlasim/carla:0.9.10
The following warning is reported:
sh: 1: xdg-user-dir: not found

and the container shut down at the same time.
what should I do to fix this ?

**Comment by zchrissirhcz** [comment]
You may try my solution

https://github.com/carla-simulator/carla/issues/3431#issuecomment-708786234

**Comment by badsmoke** [comment]
does not work for me

**Comment by zchrissirhcz** [comment]
@lz1159435992 Please consider close this issue if you already found a solution.

**Comment by lz1159435992** [comment]
I change computer and finally fix this, but still don't know why.

**Comment by pavanteja295** [comment]
> @lz1159435992 Please consider close this issue if you already found a solution.

Hello @zchrissirhcz. The problem still persists when using docker on headless server with vulkan library. Do you know if this can be fixed?

**Comment by zchrissirhcz** [comment]
Don't know vulkan stuff... For me, if using opengl is OK and vulkan easy to crash then pick opengl one.

**Comment by qhaas** [comment]
It is unlikely that the cause of the crash is due to `xdg-user-dir: not found`, see Issue #3514 

Quite the red herring
