### ISSUE TITLE
Carla Stops to load or fails while launching after successful execution of "make Launch" command

### ISSUE THREAD

**Issue by akshatamk** [carla-simulator/carla#3455]
Followed all the steps at windows Build to setup carla on windows VM
1.I’m trying to build Carla 0.9.10
2.Have all the prerequisites installed.
3.“make PythonAPI” cmd was built properly.
4.After successful execution of “make launch” cmd…the CarlaUE4 is launching with this error.
![WhatsApp Image 2020-10-15 at 6 55 59 PM](https://user-images.githubusercontent.com/43449016/96144630-0315d800-0f22-11eb-9d2d-cbeb0ce88642.jpeg)
Onclick of OK-option…the editor is opening but the screen is blank no map is visible.
Please help!

**Comment by nagasanjay** [comment]
Did you download the assets and kept it in `content` folder ? or did you run `update.sh`/`update.bat` ?

**Comment by akshatamk** [comment]
I downloaded the asset and kept it in content/carla folder

**Comment by nagasanjay** [comment]
> I downloaded the asset and kept it in content/carla folder

Did you extract it ?

**Comment by germanros1987** [comment]
@nagasanjay is this problem still bothering you?
