### ISSUE TITLE
basic_agent not moving the car

### ISSUE THREAD

**Issue by kochlisGit** [carla-simulator/carla#3459]
Hello everyone,

I am trying to make a vehicle start from the spawn point and end in the destination point, using the basic_agent class. The basic_agent class uses a function called "run_step" to navigate the vehicle. I am calling this function inside a While-True block, but still the vehicle doesn't seem to move. I've tried the following code, but the vehicle is not moving at all, even tho I get this message from the console:

**VehicleControl(throttle=0.750000, steer=-0.193401, brake=0.000000, hand_brake=False, reverse=False, manual_gear_shift=False, gear=0)**

```
vehicle_bp = blueprint_library.filter('vehicle.tesla.model3')[0]
spawn_point = world.get_map().get_spawn_points()[0]
vehicle = world.spawn_actor(vehicle_bp, spawn_point)
actor_list.append(vehicle)

dest_point = world.get_map().get_spawn_points()[100]
dest_location = (dest_point.location.x, dest_point.location.y, dest_point.location.z)

basic_agent = BasicAgent(vehicle, target_speed=60)
basic_agent.set_destination(dest_location)

i = 30

while not basic_agent.done() and i > 0:
    print( basic_agent.run_step(debug=True) )
    i -= 1
    time.sleep(1)

for actor in actor_list:
    actor.destroy()
```

**Comment by jackbart94** [comment]
Hi,

Why don't you try using the ``automatic_control.py`` script? It already implements what you are trying to achieve, and you can also use the Roaming or the Behavior agent which are better than the Basic agent.
