### ISSUE TITLE
nullptr cordumps in localizationstage

### ISSUE THREAD

**Issue by hellojql** [carla-simulator/carla#3466]
void LocalizationStage::ExtendAndFindSafeSpace(const ActorId actor_id,
                                               const bool is_at_junction_entrance,
                                               Buffer &waypoint_buffer) {
     ...
    // Extend buffer if safe point not found.
    if (!safe_point_found) {
      while (!past_junction) {
       ...
        current_waypoint = current_waypoint->GetNextWaypoint().front();
       ...
      }

      while (!safe_point_found) {
          ....
          current_waypoint = nex_t_waypoints.front();
         ...
        }
...
}

as we can see from ExtendAndFindSafeSpace in LocalizationStage,  the “current_waypoint” and "nex_t_waypoints" do not check null before use "front()" to get their item which will lead to coredump

**Comment by jackbart94** [comment]
https://github.com/carla-simulator/carla/pull/3484
