### ISSUE TITLE
Is there any way that I can place multiple camera like Tesla autopilots 8 camera setup ??

### ISSUE THREAD

**Issue by abidKiller** [carla-simulator/carla#3468]
I want to add multiple camera and place at exact location like the figure given below . 
![image](https://user-images.githubusercontent.com/43814196/96358172-f06bf080-1125-11eb-9542-e80b29e4261e.png)

how can I place at exact location and evaluate if it is placed correctly or not. Any drag and drop feature might have been better

**Comment by gismo07** [comment]
If you are using the carla ROS bridge have a look at the file https://github.com/carla-simulator/ros-bridge/blob/master/carla_ego_vehicle/config/sensors.json.

For example there is one RGB camera:

```json
"type": "sensor.camera.rgb",
"id": "front",
"x": 2.0, "y": 0.0, "z": 2.0, "roll": 0.0, "pitch": 0.0, "yaw": 0.0,
```

If you have your desired sensor locations then it's easy to add multiple cameras.
You could use the ROS tf tree to validate the positions.
