### ISSUE TITLE
[Testing] PR #3471, character in 2Wheeled BB

### ISSUE THREAD

**Issue by doterop** [carla-simulator/carla#3473]
This issue is intended to track PR #3471 .

Need to test:

- The 2 wheeled vehicles include the character inside the BB
- The 4 wheeled vehicles are not affected by this change.

Warning! Is possible that the BB visualization in UE editor seems to be wrong. It's important to test it in simulation time.

```
bboxes = world.world.get_level_bbs(carla.CityObjectLabel.Vehicles)
for box in bboxes:
    debug.draw_box(box, box.rotation, 0.01, carla.Color(0, 0, 142), 100)
```

**Comment by XGodina** [comment]
I've tested all the 2 wheeled vehicles in simulation and the positions are better than before.
