### ISSUE TITLE
Labeling issue of semantic point cloud generation with carla-ros-bridge

### ISSUE THREAD

**Issue by jjimin** [carla-simulator/carla#3480]
> CARLA version: 0.9.6 --> 0.9.9
> OS: Ubuntu 18.04
> ROS ver.: melodic

Hello.

I am trying to create a point cloud using depth images and semantic segmentation images as in the picture below.

![depth_image](https://user-images.githubusercontent.com/40253009/96580782-c4ae5d80-1313-11eb-9c27-3f24a8695dc2.png)
![semantic_image](https://user-images.githubusercontent.com/40253009/96580784-c546f400-1313-11eb-8365-0dfb070fbe7c.png)
![point_cloud](https://user-images.githubusercontent.com/40253009/96580776-c37d3080-1313-11eb-8e4a-e665ed30e4a3.png)

I use the `carla-ros-bridge`, `depth_image_proc`, and `pcl-ros` package in ROS.

However, the problem is when I use the user version of 0.9.6, the generated point cloud was OK, but after changing to the developer version of 0.9.9, the labeling did not work as shown in the picture below.

![errored_point_cloud_01](https://user-images.githubusercontent.com/40253009/96580786-c5df8a80-1313-11eb-886b-041106f17a53.png)
![errored_point_cloud_02](https://user-images.githubusercontent.com/40253009/96580788-c5df8a80-1313-11eb-9b6e-c0bc001a0775.png)

I would like to inquire about why this problem occurs.

**Comment by germanros1987** [comment]
@jjimin is this still an active problem for you?
