### ISSUE TITLE
Fog doesn't work - black sky

### ISSUE THREAD

**Issue by PyTorr** [carla-simulator/carla#3494]
I'm trying to create fog using environment.py --fog (also tried weather.py).
However all I get is black sky with no fog.
I've tried multiple configurations and towns but had no luck.
What can be the problem?

**Comment by Madecu** [comment]
Hi @PTorr, do you have the latest version of CARLA? You might have the same issue that they have here https://github.com/carla-simulator/carla/issues/3426

**Comment by PTorr** [comment]
Yes I do have the latest version.

**Comment by PTorr** [comment]
Thanks for the referral.

Going back to version 9.9.4 fixed the problem for now.

I hope that in the next release things will go back to normal.

Keep making CARLA great 😊.

Torr.

**Comment by corkyw10** [comment]
@Madecu could you follow up on this please?

**Comment by Madecu** [comment]
Hi @PTorr,

Have you tried the new version of CARLA? 
The problem you had is it still happening?

We appreciate your feedback and see if we can help you

**Comment by PTorr** [comment]
Still the same.

I do work in Ubuntu.

**Comment by Madecu** [comment]
Can you send an image of the problem? If you don't change the fog values, the sky is still black or it becomes black when changing fog density?

**Comment by PTorr** [comment]
![image](https://user-images.githubusercontent.com/8789891/109787590-0e3e7b80-7c17-11eb-9515-f14c48f900be.png)

When I'm not using fog parameter everything works fine.

**Comment by Madecu** [comment]
I can't reproduce your error. I do see the fog in Linux. Can you show me how do you change the fog value?
I used environment.py --fog 100 in this example

![image](https://user-images.githubusercontent.com/54811869/109806762-5ebcd580-7c25-11eb-9895-67f47675a722.png)

**Comment by PTorr** [comment]
exactly the same as you.
maybe because I'm using:`./CarlaUE4.sh -opengl`

**Comment by Madecu** [comment]
Yes, I could reproduce the error using the -opengl tag. I don't know exactly why openGL doesn't render the fog.
The sky turns black because we have to simulate that very dense fog would hide the sunlight. It is the same with clouds, they are not volumetric, so they don't project shadows. 
In the next release we have updated unreal engine to 4.26 and it won't support opengl anymore. I recommend you to use vulkan instead.

**Comment by PTorr** [comment]
Thanks for the detailed explanation.
