### ISSUE TITLE
Lanes ground truth

### ISSUE THREAD

**Issue by PyTorr** [carla-simulator/carla#3497]
Is there a way to get the ground truth of the lanes like in KITTI?

**Comment by wendersonj** [comment]
Check this:
[](https://carla.readthedocs.io/en/latest/python_api/#carla.Waypoint)
and
[](https://carla.readthedocs.io/en/latest/core_map/) section about 'Lanes'

**Comment by PTorr** [comment]
Hi,
thanks for the answer.
I tried this, it gives a waypoint of the lane but not all the coordinates.
Did you succeed to get the coordinates for the full lane?
Torr.

**Comment by wendersonj** [comment]
Sorry, can't help anymore... But I'm trying to use this just now. If a succeed, I'l share with u.

**Comment by wendersonj** [comment]
@PTorr , have you explored the sensor [Lane Invasion ](https://carla.readthedocs.io/en/latest/ref_sensors/#lane-invasion-detector) ?

**Comment by PTorr** [comment]
I look into it.

**Comment by wendersonj** [comment]
hi, @PTorr. I made some progress and I'm currently using this solution:
https://github.com/carla-simulator/carla/issues/1254
you can try retrieve the lanes (also left and right lanes) using waypoints and some arrangements in your code... you can also use OpenDrive API informations to retrieve something more specific.

**Comment by PTorr** [comment]
Thanks @wendersonj I think #1254 its the right direction.

**Comment by corkyw10** [comment]
@PTorr do you still need help with this issue?

**Comment by PTorr** [comment]
@corkyw10 Hi,
I wasn't able to solve it for now.

**Comment by corkyw10** [comment]
@doterop would you be able to have a look at this please?

**Comment by doterop** [comment]
Hi @PyTorr ,

Can you explain more in-depth about what exactly you need?

**Comment by PyTorr** [comment]
I wanted lanes segmentation.

**Comment by Axel1092** [comment]
Hi @PyTorr, I don't know for sure what you mean but perhaps you need the semantic segmentation sensor that gives you the tags in an image including lanes and other items in the scene.
