### ISSUE TITLE
How to make the ground-truth of the bounding box of the point cloud？

### ISSUE THREAD

**Issue by mmmmaomao** [carla-simulator/carla#3503]
Hi, I am a student who is new to computer science. Recently, my teacher gave me a task: Use Carla to make a dataset similar to Kitty 3D target detection. Using the official rosbridge, I can collect lidar data, image data and OBJECT files. So, how do I make the bounding box tags of vehicles and pedestrians in the point cloud? I am grateful for your help!

**Comment by ivannson** [comment]
You can use the semantic lidar sensor to get the ID for each point, then use something like DBSCAN (density-based clustering) to cluster all of the points with the same labels together. You might have some issues if the cars and pedestrians are very close together, as it might put two cars in one cluster, but tweak the hyperparameters to see how it works first. You might even want to use different parameters for different classes, e.g. separate clustering processes for pedestrians and cars. You're just making a dataset so I doubt the computational speed matters much. Then for each cluster get max and min coordinates to construct your bounding boxes.

Hope that helps!

**Comment by mmmmaomao** [comment]
> You can use the semantic lidar sensor to get the ID for each point, then use something like DBSCAN (density-based clustering) to cluster all of the points with the same labels together. You might have some issues if the cars and pedestrians are very close together, as it might put two cars in one cluster, but tweak the hyperparameters to see how it works first. You might even want to use different parameters for different classes, e.g. separate clustering processes for pedestrians and cars. You're just making a dataset so I doubt the computational speed matters much. Then for each cluster get max and min coordinates to construct your bounding boxes.
> 
> Hope that helps!

Thanks for your help!
