### ISSUE TITLE
Broken link in documentation, tutorial "Add new vehicle"

### ISSUE THREAD

**Issue by malixasyntronic** [carla-simulator/carla#3511]
Hello, the link in the "Add new vehicle" tutorial i 'broken' as it leads to a corrupt/empty file
(Line 20)
https://github.com/carla-simulator/carla/blob/master/Docs/tuto_A_add_vehicle.md
https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/

**Comment by corkyw10** [comment]
Hey @malixasyntronic, are you referring to the link https://carla-assets.s3.eu-west-3.amazonaws.com/fbx/VehicleSkeleton.rar? I just tried it and I get a folder that contains a `VehicleSkeleton.fbx` file

**Comment by malixasyntronic** [comment]
Yes! 
Weird, it works fine now, I got a currupt archieve when I tried to access it a few months back 
Guess this issue is resolved 


Från: "Corinne" <notifications@github.com> 
Till: "carla-simulator/carla" <carla@noreply.github.com> 
Kopia: "Mattias Lindgren" <malixa@syntronic.com>, "Mention" <mention@noreply.github.com> 
Skickat: onsdag, 24 feb 2021 13:03:52 
Ämne: Re: [carla-simulator/carla] Broken link in documentation, tutorial "Add new vehicle" (#3511) 





Hey [ https://github.com/malixasyntronic | @malixasyntronic ] , are you referring to the link [ https://carla-assets.s3.eu-west-3.amazonaws.com/fbx/VehicleSkeleton.rar | https://carla-assets.s3.eu-west-3.amazonaws.com/fbx/VehicleSkeleton.rar ] ? I just tried it and I get a folder that contains a VehicleSkeleton.fbx file
