### ISSUE TITLE
RGB Camera artifacts issue Carla 0.9.10.1

### ISSUE THREAD

**Issue by HoucemF** [carla-simulator/carla#3516]
Hi Carla Team,
I am using Carla 0.9.10.1 running on ubuntu 18.04 using python 3.7.9. I am collecting data from the RGB camera and from the semantic segmentation camera. I am using the Low Quality preset for rendering and rendering using Vulcan. The issue is the appearance of artifacts in the RGB images. These artifacts were not visible using the spectator camera.

RGB Image
![image](https://user-images.githubusercontent.com/72029066/97320396-20ad4080-1844-11eb-9f9a-ac4a63cbe1de.png)

Semantic Segmentation Image
![image](https://user-images.githubusercontent.com/72029066/97320476-36bb0100-1844-11eb-95a5-78874a9c632b.png)

**Comment by qhaas** [comment]
Reminds me of Issue ##3377

**Comment by HoucemF** [comment]
In that issue the artifacts appear in spectator mode while I only found them when using the camera
![0375](https://user-images.githubusercontent.com/72029066/97602135-58052400-19e1-11eb-9bcd-9c1edb80bba1.png)
 
This image was captured running with the -opengl flag.

**Comment by corkyw10** [comment]
@DSantosO could you have a look at this please?

**Comment by DSantosO** [comment]
Hello @HoucemF,

Can you still see this problem in the 0.9.11 release?

**Comment by qhaas** [comment]
We are still getting the artifacts with OpenGL + official/pre-built CARLA 0.9.11 (UE4.24), they are tiny black '+' if you zoom in.  They are most evident in 'HardRainSunset' weather.  They don't exist when we use Vulkan+UE4.25, but since we are x-server-less, we had to upgrade to UE 4.25 to get headless/xless vulkan support (see Issue #3800)
![rgb_c_005000](https://user-images.githubusercontent.com/34581474/109198335-19536080-776c-11eb-86d4-d05c883de477.png)

**Comment by Esquilli** [comment]
Bumping this. I'm still having this issue in the latest version of CARLA. It get worse when visualizing the data from the sensors (e.g depth, semantic, etc.). More info [here](https://github.com/carla-simulator/carla/issues/3865). 

I can upload more pictures if someone want them.

**Comment by HoucemF** [comment]
Sorry for the late response, I am still working with 0.9.10.1 and I have discovered another more serious issue with the camera. At some points, when the camera is collecting images it will turn blue and sometimes completely pitch black for a number of frames. 
![spawn_0_0008_2021-03-18_21-18-42-918743](https://user-images.githubusercontent.com/72029066/112232340-c6f04d00-8c0e-11eb-84f6-dba4a495cafd.png)
![spawn_0_0019_2021-03-18_21-18-43-680762](https://user-images.githubusercontent.com/72029066/112232358-cd7ec480-8c0e-11eb-8d25-adfe67bccd6b.png)
The occurrence of this issue is for 1 out of 10 simulations and if it happens once there is a high probability that it happens again in the same simulation.
