### ISSUE TITLE
Recommended IDE setting for sensor development under Linux

### ISSUE THREAD

**Issue by frqc** [carla-simulator/carla#3518]
Hi I'm following the tutorial to add a new sensor to Carla. While editing files within `./LibCarla` is quite smooth, I find it kind of cumbersome when doing things within `./unreal/CarlaUE4/`since I can't set up CLion correctly with type inferring and the `.generated.h`. 

I've generated project for `./unreal/CarlaUE4/`, tried some compile options to generate the intermediate files (*.generated.h) but still too many wavy lines. 

Could I ask about the recommended IDE and the corresponding settings for Carla development under Linux environment? Thanks

**Comment by mberoakoko** [comment]
Wow  , nearly 4 years later and no answer.
