### ISSUE TITLE
actor.get_traffic_light_state() gets stuck on 'Green'

### ISSUE THREAD

**Issue by pandyarohan** [carla-simulator/carla#3524]
When calling actor.get_traffic_light_state() for a stationary vehicle at an intersection, the traffic light status gets stuck at 'Green' regardless of the the actual state of the traffic light in the intersection. 

The _is_light_red function here seems to be using the traffic light's object's state which is more reliable.

**Comment by corkyw10** [comment]
@doterop could you follow up on this please?

**Comment by xrispa-m** [comment]
@Axel1092 is there any update on that? We are facing the same problem currently.
