### ISSUE TITLE
zero vector leads to cordump in GetBoundary

### ISSUE THREAD

**Issue by hellojql** [carla-simulator/carla#3527]
LocationVector CollisionStage::GetBoundary(const ActorId actor_id) {
 ...
  const auto perpendicular_vector = cg::Vector3D(-heading_vector.y, heading_vector.x, 0.0f).MakeUnitVector();
 ...
}

    Vector3D MakeUnitVector() const {
      const float length = Length();
      DEVELOPMENT_ASSERT(length > 2.0f * std::numeric_limits<float>::epsilon());
      const float k = 1.0f / length;
      return Vector3D(x * k, y * k, z * k);
    }

from the above we can see that zero heading vector will lead to cordump:

terminate called after throwing an instance of 'std::runtime_error'
  what():  length > 2.0f * std::numeric_limits<float>::epsilon()

**Comment by jackbart94** [comment]
Hi,

Please change the function to MakeSafeUnitVector(). This is already in master.
