### ISSUE TITLE
Is there no very hard raining like CARLA 0.8 in CARLA 0.9?

### ISSUE THREAD

**Issue by Kitsunetic** [carla-simulator/carla#3530]
![000280](https://user-images.githubusercontent.com/14368796/97805961-95490a80-1c9c-11eb-993d-3d75526d65a0.png)

I'm finding hard raining like this. This picture was taken on CARLA 0.8.4.

Now I have to use version 0.9.9.4, and I have tested with weather parameters to make hard raining condition like this picture but I can't find it.

I have tested with all weather presets in `carla.WeatherParameters` and I manually set `precipitation` as large value but I never get weather like this picture.

`HardRainSunset` was similar with that but not that much raining.

**Comment by Madecu** [comment]
Hi @Kitsunetic, we have changed the amount of rain particles with the new weather. Right now, to fully customize the rain, you have to go to Unreal find the PS_Rain and increase the maximum particles
![image](https://user-images.githubusercontent.com/54811869/99713719-f0546d00-2aa4-11eb-9868-0633e6e3cc7a.png)

You can also tweak the "color" of the raindrops to make them whiter and more visible as they were made before the update. 
![image](https://user-images.githubusercontent.com/54811869/99713951-3f9a9d80-2aa5-11eb-9e56-1486c77ec809.png)


I hope it helps

**Comment by Kitsunetic** [comment]
Great! Thank you!!

I'll close the issue

**Comment by QAbot-zh** [comment]
> Hi @Kitsunetic, we have changed the amount of rain particles with the new weather. Right now, to fully customize the rain, you have to go to Unreal find the PS_Rain and increase the maximum particles ![image](https://user-images.githubusercontent.com/54811869/99713719-f0546d00-2aa4-11eb-9868-0633e6e3cc7a.png)
> 
> You can also tweak the "color" of the raindrops to make them whiter and more visible as they were made before the update. ![image](https://user-images.githubusercontent.com/54811869/99713951-3f9a9d80-2aa5-11eb-9e56-1486c77ec809.png)
> 
> I hope it helps

How can I modify it? I open it on UE and it shows that the baked asset can not be modified. Is there another way to modify the parameters of PS_Rain?
