### ISSUE TITLE
[Testing] Change the state of static mesh and decals to help culling

### ISSUE THREAD

**Issue by XGodina** [carla-simulator/carla#3535]
It has changed the state "Movable" to "Static" of:
> - Decals
> - Static mesh (without buildings, because Dani is working at that level)
> - Spawn_points 

In order to win more performance and reduce calldraws, it has tweaked the values of Dynamic Shadow Distance MovableLight 50.000 to 10.000 for all towns.

You need to work in the branch of Daniel/Static_Buildings in art content. 

Need to test

> If it helps to culling work better or not
> If performance has improved with these changes

**Comment by doterop** [comment]
Everything OK
