### ISSUE TITLE
CarlaCppClient on Windows 10

### ISSUE THREAD

**Issue by ujjawal-kumar** [carla-simulator/carla#3537]
How do I run Example/CarlaCppClient in Windows?

**Comment by ujjawal-kumar** [comment]
> How do I run Example/CarlaCppClient in Windows?

I took the following steps for a successful run cppclient:-
1. make launch
2. make libcarla
3. create a new project in visual studio and copy main.cpp and add the include and lib folder path in CPP compiler and linker in visual studio project settings. 
and it builds Successfully.

**Comment by jemishGhoghari** [comment]
Hi @ujjawal-kumar, 

could you please steps more in detail? So, Where can I find include and lib folder?
Is it inside PythonAPI folder?

Appreciate any Help!

Thanks!
