### ISSUE TITLE
support for multiple agents/players? programmable non-players?

### ISSUE THREAD

**Issue by liangbright** [carla-simulator/carla#354]
The ideas is to simulate the events that may lead to accidents, which may be achieved by A or B

A. support multiple agents/players  for example,  
(1) simulate a drunk driving car on the road, and then simulate another car to avoid collison with that drunk 
(2) simulate a person that is crossing the street (not on crosswalk). then simulate a car to avoid collision.

B. support programmable non-players
pre-define the trajectory of a person/car

**Comment by nsubiron** [comment]
Hi @liangbright, this is already in our road map. please see issue #184.
