### ISSUE TITLE
Behavior mode of car NPC?

### ISSUE THREAD

**Issue by daohu527** [carla-simulator/carla#3558]
This is a question for help.

I read the carla code and found the walker has a behavior mode in `AWalkerAIController`, but I don't find the NPC cars behavior mode. 

Can you tell me how the behavior of the car is realized? Do they have some kind of intelligence, or rule-based, can point out where to look at these codes, thanks!

**Comment by jackbart94** [comment]
Hi,

I think you can find everything you need about Traffic Manager at [this link](https://carla.readthedocs.io/en/latest/adv_traffic_manager/#traffic-manager)
