### ISSUE TITLE
Traffic light binary format doc

### ISSUE THREAD

**Issue by philkr** [carla-simulator/carla#3562]
Hi all,

there is a minor typo in the doc of the binary format for the traffic light. In [RecorderTrafficLight.jpg](https://github.com/carla-simulator/carla/blob/master/Docs/img/RecorderTrafficLight.jpg), `state` and `isFrozen` are flipped compared to the code [CarlaRecorderState.h](https://github.com/carla-simulator/carla/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderState.h). It's not super urgent, but it tripped me up a bit parsing the format in python...

Keep up the awesome work!

**Comment by corkyw10** [comment]
@philkr Thanks for your patience and for filing the issue. I will update the image
