### ISSUE TITLE
How to disable two wheels vehicles like bicycle and motorbike in CARLA 0.9.10

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/carla#3564]
I found it is easy to disable two wheels vehicles in CARLA 0.8.x, but I didn't find any python interface to achieve this function in CARLA 0.9.10. Does anyone know how to solve this?

**Comment by glopezdiest** [comment]
Where are you planning on disabling them exactly? In general though, actor blueprints have a *number_of_wheels* attribute*, which allow you to filter them. Below is an image of how *spawn_npc.py* does it (check the first line after the conditional statement)

![image](https://user-images.githubusercontent.com/58212725/98686498-f0e45980-2368-11eb-9abc-9ece264f82cc.png)
