### ISSUE TITLE
Read Camera image on CARLA 0.9.X release

### ISSUE THREAD

**Issue by xpeedster** [carla-simulator/carla#3565]
Hi,

In the Carla 0.9.0 release the Python API was redefined and now sensors are treated differently.

I would like to know how can I take an image from the RGB camera (so that I can, for instance, do some computer vision stuff using OpenCV).

Thanks a lot for the help in advance.

**Comment by maro-ros** [comment]
# image := carla.Image
raw_data_flat = np.frombuffer(image.raw_data, dtype=np.dtype("uint8"))
raw_data_shape = np.reshape(raw_data_flat, (image.height, image.width, 4)) #  RGBA image

**Comment by xpeedster** [comment]
Thanks a lot for the help.
