### ISSUE TITLE
New release tag 0.9.10.2

### ISSUE THREAD

**Issue by guntherkrehl** [carla-simulator/carla#3571]
Hi Carla team,

I've been talking to @marcgpuig about the issue [#3385] which has been resolved but is still part of the latest release 0.9.10.1. Can you please add a new sub-release (0.9.10.2) so users can have a common hash (instead of a random dev-branch checkout) that includes this (and maybe more) bugfixe(s)?

Thank you,
Gunther

**Comment by FiodarKazhamiaka** [comment]
+1, eagerly awaiting semantic Lidar object id bug fix (#3396) :)
