### ISSUE TITLE
Is a box truck available in Carla? 

### ISSUE THREAD

**Issue by manonechu** [carla-simulator/carla#3574]
Hi there, is a box truck with four wheels available in Carla? Or is there a way to create it?
Thank you very much.

**Comment by corkyw10** [comment]
Hi @manonechu I don't think we have what you are looking for out of the box, you can find the list of vehicles available [here](https://carla.readthedocs.io/en/latest/bp_library/#vehicle). We are always working on new vehicles so keep an eye out for trucks being added in the future. 

There is also a tutorial for adding your own vehicle [here](https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/)
