### ISSUE TITLE
I wanna change Lidar attributes!

### ISSUE THREAD

**Issue by Jae-Seung-Jeon** [carla-simulator/carla#3577]
I use 0.9.8

![12](https://user-images.githubusercontent.com/68648280/98901654-831a6800-24f7-11eb-87a9-d956e4d83a0f.png)

And I do
make launch
make PythonAPI
make rebuild

![13](https://user-images.githubusercontent.com/68648280/98901755-a3e2bd80-24f7-11eb-8003-2ece757a3abf.png)

But it doesn't change.
What should I do?

**Comment by corkyw10** [comment]
@Jae-Seung-Jeon Are you still experiencing this issue? 

@DSantosO Could you follow up on this please?

**Comment by DSantosO** [comment]
Hello @Jae-Seung-Jeon,
The default values are not the ones in that file that you show but are defined in the file `ActorBlueprintFunctionLibrary.cpp` from line 820 .
