### ISSUE TITLE
How to sync in Multi-TM case?

### ISSUE THREAD

**Issue by yshen47** [carla-simulator/carla#3582]
In the docuemntation, even though it mentions that if two TM-server tick, sync will fail. But what's the right way to do syncronization when there are multiple TM-server then? The documention is ambiguous...

**Comment by corkyw10** [comment]
Documentation for the TM was [updated](https://carla.readthedocs.io/en/0.9.12/adv_traffic_manager/#running-multiple-traffic-managers), hopefully with a better explanation of how multi TM works. If you see any problems with it or have more questions, please open a new issue.
