### ISSUE TITLE
Docker carlasim/carla:0.9.10 exits after being created for few seconds 

### ISSUE THREAD

**Issue by yixiao1** [carla-simulator/carla#3588]
Hi @germanros1987 ,

I was trying to run docker carlasim/carla: 0.9.10 on Ubuntu 18.04, with the following command:

`docker run --privileged --rm --gpus all -it --net=host -e DISPLAY=:0.0 -v /tmp/.X11-unix:/tmp/.X11-unix:rw carlasim/carla:0.9.10 /bin/bash CarlaUE4.sh -vulkan`

The docker container seems to be successfully created, and lasts for about 1 minute. But then it exited automatically. 

<img width="1075" alt="Screen Shot 2020-11-16 at 10 24 07 AM" src="https://user-images.githubusercontent.com/32467324/99235870-519ee680-27ee-11eb-9c88-ab1914fb5840.png">

Any idea or solution will be very appreciated!! Thanks!!

**Comment by corkyw10** [comment]
Hi @yixiao1 are you still experiencing this issue?

@bernatx would you be able to follow up on this please?
