### ISSUE TITLE
No module name dCARLA (even though its there!)

### ISSUE THREAD

**Issue by AD1D1** [carla-simulator/carla#3591]
The matplotlib.backends.tkagg module is deprecated.
  "3.0", "The matplotlib.backends.tkagg module is deprecated.")
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "module_7.py", line 32, in <module>
    from carla            import sensor
ModuleNotFoundError: No module named 'carla'

Im using Py -3.7

**Comment by MisterioRemo** [comment]
Hello!
I'm not an expert at python but when I need to run carla's script in strange place I use `export PYTHONPATH`.
So it looks something like this:
```bash
export PYTHONPATH=$PYTHONPATH:path_to_egg_file/carla-0.9.10-py3.5-linux-x86_64.egg
python your_script.py
```

Maybe it helps.
