### ISSUE TITLE
Does the weather such as rainning in CARLA really affect data recieved from sensors? If it does, then where the data I can reference to put it in project reference? Any recommend pls.

### ISSUE THREAD

**Issue by KunanonxGithub** [carla-simulator/carla#3593]
If anyone know, pls help me.

**Comment by ebadi** [comment]
Not yet. as mentioned in #413, it is planned for 0.9.12 sprint.

**Comment by KunanonxGithub** [comment]
@ebadi thank you. But I think I should  really scope about weather in project. If not, I need to develop and test on many scene and many weather then. T T
