### ISSUE TITLE
exposure-mode auto - which gamma finally used

### ISSUE THREAD

**Issue by mawi42** [carla-simulator/carla#3594]
Question:
You set in Carla 0.9.10 the camera exposure-mode to histogram. From documentation I learned
"Auto exposure Modifies the image gamma to simulate the eye adaptation to darker or brighter areas."
When I render finally the images I read camera attributes, but it seems the gamma value is not changed, even if I see in my scene (no movement static position) that the images are getting darker - so the auto feature seems to be active.
Is there a chance to get current used parameter of the camera like gamma or exposure time? If not, this would be a feature request.

Thanks in advance
Matthias

![carla_auto_exposure](https://user-images.githubusercontent.com/26420496/99387915-0d3a4600-28d5-11eb-8cfb-91c82b3bc329.jpg)

**Comment by corkyw10** [comment]
@mawi42 thanks for your patience

@DSantosO could you have a look at this please

**Comment by mawiso** [comment]
Hello, is there any update on this issue?
