### ISSUE TITLE
Build error with 0.8.1

### ISSUE THREAD

**Issue by sandman** [carla-simulator/carla#360]
Hi,
I get a build error when I run the Rebuild.sh script for Carla 0.8.1. I suspect the error might have been because I ran Setup.sh before building UnrealEngine 4.18..?

Output of ./setup.sh: https://gist.github.com/sandman/8671b041a988e01441aba1754a21e0f1

Output of Rebuild: https://gist.github.com/sandman/0533120716229d17dc2ef9918586d8bf

There seems to be an issue with linking the python headers. Any ideas how to resolve this?

Thanks,
Sandip

**Comment by nsubiron** [comment]
Hi,
It seems a problem with your python installation, maybe you can try reinstalling the `python-dev` package.

**Comment by tomchen1000** [comment]
https://github.com/carla-simulator/carla/issues/199
