### ISSUE TITLE
Can we use neural network in CARLA to classify object from the data recieved from RGB camera or any camera?  

### ISSUE THREAD

**Issue by KunanonxGithub** [carla-simulator/carla#3603]
If we can do it, do we have to change FPS of simulation or sth to make it work?
My team would like to detect car and traffic light so I can simulate scenario and make car go through red and green traffic light in simulation. 
Pls clarify if you know it. Thank for advance.

**Comment by glopezdiest** [comment]
Hey @KunanonxGithub, yeah you definitely can. I'd recommend using the synchronous mode of CARLA to make sure all your calculus are done in time, but apart from that it is completely up to you.
