### ISSUE TITLE
pip install carla - ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by ccm24** [carla-simulator/carla#3604]
I try to use pip install carla and I get this error :

Collecting carla
Using cached carla-0.9.5.tar.gz (3.9 kB)
ERROR: Command errored out with exit status 1:
command: 'c:\users\f67886\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla\setup.py'"'"'; file='"'"'C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\F67886\AppData\Local\Temp\pip-pip-egg-info-6e19xs3q'
cwd: C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla
Complete output (7 lines):
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla\setup.py", line 114, in
ext_modules=get_libcarla_extensions(),
File "C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla\setup.py", line 75, in get_libcarla_extensions
libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies/lib'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I'm trying to do this because there is no "carla" folder in "\ Python \ Python37 \ Lib \ site-packages" and I think that's why when I run a matlab script it can't connect to the carla server and I get this error: "Unable to resolve the name py.carla.Client. "

There is someone who has encountered this problem ?

**Comment by kaoutarMdr** [comment]
HI @craciunescumarian  i faced th same problem can u help me to resolve it if u already find a solution 
thanks in advance
