### ISSUE TITLE
RuntimeError when triyng to spawn vehicles

### ISSUE THREAD

**Issue by salvatoresan** [carla-simulator/carla#3606]
Hi guys, I'm having issues with the spwan_npc script. I run several tests and only a few times I was able to spwan 5 vehicles without any problems. In general, I've got the following error:

![immagine](https://user-images.githubusercontent.com/57993602/99664521-933ac600-2a68-11eb-97d0-0c4e4bbc7f6f.png)

I have no issue  running the manual control script. Besides, I have been able to increase the number of spawned vehicles by increasing the timeout value in the spawn_npc.py script but this workaround does not always work.
Any suggestion?
I'm currently using Carla 0.9.10 built from source on ubuntu

**Comment by ChicagoPARK** [comment]
Did you solve it..? I still struggle with it for a long..

**Comment by salvatoresan** [comment]
Hi @ChicagoPARK , my workaround to solve this issue was to increse the timeout value in the spawn_npc.py script. 
`104        client.set_timeout(10.0)`
Try to change 10.0 (the default value) in 100.0 and then give it a try by spawning 20 or 30 vehicles. This worked for me but I've avoided to spawn pedestrians.

**Comment by ChicagoPARK** [comment]
Well, thank you for sharing your solution. In my case put the button for "play" is the solution. Thank you there
