### ISSUE TITLE
Failed to make PythonAPI in Windows

### ISSUE THREAD

**Issue by Yifanny** [carla-simulator/carla#3611]
Carla version: 0.9.10
OS: Windows 10
Compiler: MSVC 19.16.27044
CMake version: 3.12

Error messages are shown as the following figure. As shown at the bottom of the figure, I have installed python 3.7. The possible causes indicate that the python is not installed. Any help would be much appreciated.
![Screenshot 2020-11-20 at 20 22 45](https://user-images.githubusercontent.com/11888077/99799949-81dbe180-2b6e-11eb-9b8b-d6e969f97233.png)

**Comment by aadimator** [comment]
It's trying to execute the `py` command, while in windows, `python` command is used to access Python. I worked around this issue by going to the Python installation directory, making a copy of `python.exe`, and renaming it to `py.exe`, so I am able to run `py` command from the terminal. This solved the issue for me.

![image](https://user-images.githubusercontent.com/10383542/99868816-c79ea700-2b7a-11eb-858a-78034f6b061b.png)

**Comment by Yifanny** [comment]
> It's trying to execute the `py` command, while in windows, `python` command is used to access Python. I worked around this issue by going to the Python installation directory, making a copy of `python.exe`, and renaming it to `py.exe`, so I am able to run `py` command from the terminal. This solved the issue for me.
> 
> ![image](https://user-images.githubusercontent.com/10383542/99868816-c79ea700-2b7a-11eb-858a-78034f6b061b.png)

Many thanks for your help. There is still other error. The error is _failed to find XercesC(missing: XercesC_VERSION)_. I have no idea to solve it. Should I install XercesC manually? Have you encounter such a problem? Many thanks in advance.
![Screenshot 2020-11-21 at 14 49 11](https://user-images.githubusercontent.com/11888077/99869812-f3686e00-2c08-11eb-8c6b-fd27a2811a30.png)

**Comment by corkyw10** [comment]
@Yifanny thank you for your patience. Are you still experiencing this issue?
