### ISSUE TITLE
Does carla build towns reference to real towns? or they're just towns in simulation which dont exist? 

### ISSUE THREAD

**Issue by KunanonxGithub** [carla-simulator/carla#3613]
If they build towns reference from real towns, then where exactly the real towns they are referenced to make them?
such as town1 <= America
town2 <= California, some town in California
Pls help me if you know, thank for advance.

**Comment by BAROBA-3d** [comment]
As far as I know, they are all fictional.
On the discord server you can even add you own suggestions for town-names.
