### ISSUE TITLE
Segmented Image Is Red

### ISSUE THREAD

**Issue by FarukOzderim** [carla-simulator/carla#3622]
Hello;

$CARLA_ROOT/PythonAPI/examples/manual_control.py 
I run this example and look at semantic segmentation images at the 6th sensor by pressing 6. 
This is camera semantic segmentation (CityScapes Palette)
![image](https://user-images.githubusercontent.com/44067394/100079329-9281a580-2e55-11eb-86bd-4daff1a07c92.png)

But my image is red instead of correct segmentation like in this example:
https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-segmentation-camera

What is the problem, how can I solve it?
I want to collect semantic segmentation dataset from Carla in a active urban environment. Can you forward me to an example of this kind, or a dataset?

**Comment by corkyw10** [comment]
@FarukOzderim thanks for your patience. Are you still experiencing this issue? I just tested on Carla 0.9.10.1 and I saw the map as is expected from that sensor. what version of Carla are you using?
