### ISSUE TITLE
How can we know about the formula of relationship betweeen throttle and acceleration or velocity of many default cars in CARLA? Include information about max acceleration of that car.

### ISSUE THREAD

**Issue by KunanonxGithub** [carla-simulator/carla#3625]
I think I need this information to do my senior project, so if you know, pls help me.

**Comment by jackbart94** [comment]
There is a specific torque curve for each vehicles, but the relationship between throttle and velocity/acceleration is determined by many other factors (Max RPM, gear ratios and others). The only way to find out is for you to create an example that runs a specific throttle and see the acceleration/velocity for each vehicle, then draw your conclusions.
