### ISSUE TITLE
turn the on-board camera

### ISSUE THREAD

**Issue by Lunnor** [carla-simulator/carla#363]
First of all, I wish to tell you that Carla is amazing. 
I wish to use Carla to study driver behaviour. I need for that to move the on-board camera (like moving our head to see on our right or left. 
Is it possible ?

**Comment by marcgpuig** [comment]
Hi @Lunnor, 

Sadly It is not possible, but depending what are you trying to achieve, you can set multiple cameras with certain FOV to simulate a 360º omni camera.
