### ISSUE TITLE
Location inconsistency between traffic sign actors and the rendering in Town04

### ISSUE THREAD

**Issue by lian999111** [carla-simulator/carla#3630]
Hi,

I am performing my study on Localization using Carla's built-in maps, in which the traffic signs are important landmarks for my algorithm. While testing with different maps, I found that in Town04 the traffic sign actors are quite off from where they are rendered. The following pic shows an example where purple bars are drawn at the locations of the actors. This situation happens almost all over the place along the highway and I have checked it happens both in 0.9.9 and the latest 0.9.10. However it seems only Town04 has this issue.

![Screenshot from 2020-11-26 15-36-18](https://user-images.githubusercontent.com/7089695/100321814-40c84f00-2ffe-11eb-989d-b54e4f3ad133.png)

**Comment by corkyw10** [comment]
@Xavi would you be able to help with this please?
