### ISSUE TITLE
no road lines in semantic cloud for carla 0.9.10.1

### ISSUE THREAD

**Issue by SimonLeeGit** [carla-simulator/carla#3638]
hi, 
   I'm exciting to use the semantic cloud feature in carla 0.9.10.1. But something looks wrong, I can not find the semantic info for road line when using open3d script by follow the doc. Is that a bug or my mistake?

**Comment by germanros1987** [comment]
@SimonLeeGit is this still an issue with 0.9.11?

**Comment by fireofearth** [comment]
Hi @germanros1987, yes this is still a problem.
Many lane and street divider lines can be seen in semantic camera, but not semantic LIDAR.
Some street boundary lines and arrows on the road can be seen in semantic camera.

![carla-bug](https://user-images.githubusercontent.com/14065660/119268450-e6bcd680-bba7-11eb-9d39-6e27fdbab8d7.png)
