### ISSUE TITLE
I generated a pedestrian navigation mesh and the file path was correct, but the pedestrian could not be loaded

### ISSUE THREAD

**Issue by Yang-Zi97** [carla-simulator/carla#3639]
![navigation mesh](https://user-images.githubusercontent.com/69959752/100430348-a20d2280-30d1-11eb-9c39-d27a9dae5257.PNG)

**Comment by XGodina** [comment]
Hi@Yang-Zi97, 
Can you provide more information about it ? 
I suppose that you check our documentation right ?https://carla.readthedocs.io/en/latest/tuto_D_generate_pedestrian_navigation/#rebuild-the-navigation-binary

**Comment by Yang-Zi97** [comment]
hi！xavi.
Thank you for your reply. 

We made the map using 3DMAX. According to step in the document, we have changed the names of all models, which are similar to Road_Road_Mesh_1...,
 using NoExport to export the unwanted model.
Using the executable program for Recast&amp;Detour,run:python spawn_npc.py.But only vehicles are generated, no pedestrians。After debugging, I know that pedestrians can generate pedestrians, but they will not appear on the navigation grid. I think there is something wrong with recast &amp; detour .




I hope you can help me.thinks

 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xavi"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 凌晨1:41
收件人: "carla-simulator/carla"<carla@noreply.github.com&gt;; 
抄送: "阳子"<1658308385@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [carla-simulator/carla] I generated a pedestrian navigation mesh and the file path was correct, but the pedestrian could not be loaded (#3639)





 
Hi@Yang-Zi97,
 Can you provide more information about it ?
 I suppose that you check our documentation right ?https://carla.readthedocs.io/en/latest/tuto_D_generate_pedestrian_navigation/#rebuild-the-navigation-binary

**Comment by bernatx** [comment]
Hi, pedestrians can only spawn and walk on special areas (meshes) that have the proper nomenclature. So, you need to be sure that you have meshes starting with the name Road_Sidewalk, Road_Grass (optional) or Road_Crosswalk (optional). Pedestrians always spawn in areas named Road_Sidewalk, and they are the priorized ares where they walk. The Road_Grass are areas with less priority to walk but they will if the path is shorter walking on them, and the Road_Crosswalk are the areas they will walk if they need to cross a road. Be sure you have at least a Road_Sidewalk mesh. So:

- **Road_Sidewalk** is a must
- **Road_Grass** is optional
- **Road_Crosswalk** is optional

Regards,
Bernat
