### ISSUE TITLE
How to export map with all associating files

### ISSUE THREAD

**Issue by Ubledeli** [carla-simulator/carla#3642]
I would like to edit an existing map in CarlaUE4 editor and export it so it can be used in released carla package (version 0.9.10.1)

So far, I was only able to export .umap .uasset and .obj files
Also .bin file can be made from .obj file using RecastBuilder script if .obj is sufficiently small
that is achieved by exporting only grass, road, sidewalk and crosswalk form CarlaUE4 editor

There was a script in carla 0.9.4 for creating .uexp files that are now missing and here was a notion in the documents
This was mentioned in issue [#1998](https://github.com/carla-simulator/carla/issues/1998#issue-480852243)

Without these .uexp files map cannot be loaded (```client.load_world('Town06')```) into carla
even though it is showed with ```client.get_available_maps()```

What is the proper way of changing existing and possibly creating new maps ?

**Comment by corkyw10** [comment]
Sorry I let this issue go stale. There is new documentation on how to import maps and create packages [here](https://carla.readthedocs.io/en/0.9.12/tuto_M_custom_map_overview/) and [here](https://carla.readthedocs.io/en/0.9.12/tuto_A_create_standalone/). If you have any problems with the processes, please post on the [forum](https://github.com/carla-simulator/carla/discussions), discord or open a new issue.
