### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by AvivSham** [carla-simulator/carla#3649]
Realy awesome repo! shout out to all maintainers!
I have several questions related to Carla:

- Is it possible to create a deterministic scene? i.e. create a scene which will repeat itself in terms of movement directions of cars but with the ability to change car types, surrounding, etc.
- Is it possible to render videos of autonomous driving using Carla? or it functions as a computer game?
- If the latter is feasible can it be done in different resolutions and other parameters such as FPS?
- How long will it take to render and save 1 minute duration video on 3080ti (approximately)

Thank you in advance for helping.

**Comment by ebadi** [comment]
Replaying scenarios are possible. Search for "replay" in the documentations.

**Comment by AvivSham** [comment]
I expected the answer to the first question to be "yes," but what about the others?
@ebadi  are you one of the maintainers?

**Comment by ebadi** [comment]
No, I am not a maintainer.

**Comment by PTorr** [comment]
You can do all of the above.
The recording time depends on resolution/ num of actors etc.

**Comment by AvivSham** [comment]
@DSantosO | @PyTorr | @ebadi  Thank you for your response.
Another question - I want to integrate Carla with project acoustics to do so I need to work with Carla in UE. Is there any straight forward to use Carla in UE? (Addon or something like that?)
@dvirsamuel

**Comment by DSantosO** [comment]
Hello @AvivSham,
Yes, just download from the source and you can work directly in the Unreal Engine editor. Check in our [documentation website](https://carla.readthedocs.io) in the Linux/Windows build sections.

**Comment by AvivSham** [comment]
@DSantosO Thank you for the response.
If I understand you correctly I should follow [these instructions ](https://carla.readthedocs.io/en/0.9.11/build_linux/#unreal-engine) isn't it?
@dvirsamuel
