### ISSUE TITLE
[Testing] Mercedes Benz / Dodge Charge / Lincoln 

### ISSUE THREAD

**Issue by XGodina** [carla-simulator/carla#3666]
What must be tested?

- Check materials - Good nomenclature, are materials instanced?
- Wheels Physics - are correct?
- Car Physics - Did you see correct in Lidar?
- Set Light - All lights work? Check cast shadows and ticks.
- Vehicle Factory - Can you spawn with different colors?
- Wheels Suspension - They are correct?

Branch - Master

**Comment by XGodina** [comment]
So far tested I've seen some problems.

Vehicle Factory
The cars don't change the color when you spawn it

Lincoln2020 Lights
- The break lights there are too much glow
![BreaklightLincoln](https://user-images.githubusercontent.com/39989886/101341608-a085ec00-3881-11eb-97db-aa393877d704.png)

Mercedesccc Lights
There is no glow in the brake
![BreaklightMercedes](https://user-images.githubusercontent.com/39989886/101341809-ef338600-3881-11eb-9ded-82b67d02dd9e.png)

ChargeCop2020/Charge
The left beam doesn't work
There isn't light inside the car
There isn't light in the mesh
![ChargeCop](https://user-images.githubusercontent.com/39989886/101342179-7da80780-3882-11eb-9e4f-7540e165445b.png)

Improve nomenclature. We must have a better order of assets. It's not all SM_
![Screenshot from 2020-12-07 11-02-53](https://user-images.githubusercontent.com/39989886/101342448-dd061780-3882-11eb-8c64-8ce30586c99a.png)

Follow this link 
https://www.gamecoderblog.com/en/unreal-engine4/ue4-recommended-files-naming-convention

Add the good suspension - follow this link https://carla.readthedocs.io/en/latest/tuto_D_customize_vehicle_suspension/
If you have doubts about this ask Daniel Santos

**Comment by XGodina** [comment]
It seems that everything is fine. But a couple of things before to close.

1 -  I would like to know the feedback of the rest of the testers @DnDare  @DSantosO 
2 - @gsmario To have good discipline and organization, you should unify the nomenclature of "mesh Glass"
![Captura1](https://user-images.githubusercontent.com/39989886/101552527-49803400-39b3-11eb-9f3d-65bd8d2ea131.PNG)
![Captura3](https://user-images.githubusercontent.com/39989886/101552533-4be28e00-39b3-11eb-847d-31d0d2f95232.PNG)
![Captura12](https://user-images.githubusercontent.com/39989886/101552540-4dac5180-39b3-11eb-8469-41d94b06ef52.PNG)

**Comment by DSantosO** [comment]
The physics of the Dodge and Mercedes look good. The behavior of the Lincoln is a bit off, especially during the turns because it is very easy to lose control of the car.

**Comment by gsmario** [comment]
@DSantosO i've updated the car wheels width with the new values.

**Comment by XGodina** [comment]
I've updated the center of mass to improve the behavior of cars. Now don't lose control.
