### ISSUE TITLE
Obtaining Visualizations from Trailer Videos

### ISSUE THREAD

**Issue by jcyriac2** [carla-simulator/carla#367]
Hey! Great work on the new release 0.8.* We are really looking forward to the performance improvements

1) I just wanted to know how I can obtain the visualizations used in the 0.8.0 trailer video on Ray Cast based LIDAR (https://youtu.be/S_XbKHC_hN0?t=25s), depth-based point Cloud (https://youtu.be/S_XbKHC_hN0?t=46s). Is the code available in this repository?

2) Also, I was wondering how to get the overlay of the camera image, the steering wheel and the gas/brake level visualizations as seen in (https://youtu.be/cFtnflNe5fM?t=1m1s). Again, is this code available in the repository or do we have to implement it ourselves?

Thanks again!

**Comment by jcyriac2** [comment]
Thanks alot @felipecode.

**Comment by marcgpuig** [comment]
Hello @jcyriac2,

For your question 1. The code is full provided in this repository :)
To obtain the LIDAR visualization you must run the [`manual_control.py`](https://github.com/carla-simulator/carla/blob/master/PythonClient/manual_control.py) with the argument `--lidar` (or `-l`). If you are looking for the rendering implementation, please take a look at these lines:

https://github.com/carla-simulator/carla/blob/79c81bf3feacc532235358e2096a4dc015517a2c/PythonClient/manual_control.py#L324-L336

To get the depth-based point Cloud, you only need to run the [`point_cloud_example.py`](https://github.com/carla-simulator/carla/blob/master/PythonClient/point_cloud_example.py). It will generate [`.ply`](http://paulbourke.net/dataformats/ply/) files that you can easily open and edit with [MeshLab](http://www.meshlab.net/).

Regards!
