### ISSUE TITLE
Semantic Segmentation Camera results to black images

### ISSUE THREAD

**Issue by NurbekHalikulov** [carla-simulator/carla#3672]
Hello,

when I am running different types of camera sensor models, every of those cameras producing correct images except semantic segmentation camera. It is producing complete black images. I tried with pedestrians and vehicles in the surrounding, both with static and dynamic objects. However the results is same.

I am using Windows 10, CARLA 0.9.9, GPU is NVIDIA Quadro T2000, i7 9th Gen

Here is the script:

```
sem_cam = None
sem_bp = world.get_blueprint_library().find('sensor.camera.semantic_segmentation')
sem_bp.set_attribute("image_size_x",str(1920))
sem_bp.set_attribute("image_size_y",str(1080))
sem_bp.set_attribute("fov",str(105))
sem_location = carla.Location(2,0,1)
sem_rotation = carla.Rotation(0,123,0)
sem_transform = carla.Transform(sem_location,sem_rotation)
sem_cam = world.spawn_actor(sem_bp,sem_transform,attach_to=ego_vehicle, attachment_type=carla.AttachmentType.Rigid)

sem_cam.listen(lambda image: image.save_to_disk('tutorial/new_sem_output/%.6d.jpg' % image.frame,carla.ColorConverter.CityScapesPalette))
```

Source: https://carla.readthedocs.io/en/latest/tuto_G_retrieve_data/

Thanks for your attention and responds in advance

**Comment by corkyw10** [comment]
@NurbekHalikulov thanks for you patience, are you still facing this issue?

@DSantosO Are you able to have a look at this please?
