### ISSUE TITLE
Difference between the Carla RSS lib and the intel ad-rss-lib?

### ISSUE THREAD

**Issue by xgnit** [carla-simulator/carla#3679]
Hi folks. I am interested if anyone is familiar with these two libs? Are they different? It seems for me the ad rss lib has more completion. Correct me if wrong.

**Comment by corkyw10** [comment]
@fabianoboril could you follow up on this please?

**Comment by fabianoboril** [comment]
The CARLA RSS sensor uses the ad-rss-lib.

**Comment by xgnit** [comment]
thank you
