### ISSUE TITLE
Game screen freezes 

### ISSUE THREAD

**Issue by yanhuhu** [carla-simulator/carla#3685]
Graphics: GeForce RTX 2070

Carla was installed by build in ubuntu. When I run the automatic_control.py , Game screen freezes .
But when I run the same script in the server which was installed by Package installation will running smoothly.
The above two situations are on the same computer.

How to solve this problem？

**Comment by yanhuhu** [comment]
System: ubuntu 18.04.5 LTS
Processor:Intel Core i7-6700 CPU@3.40GHz x 8

**Comment by corkyw10** [comment]
@yanhuhu Thanks for your patience, are you still experiencing this issue?
