### ISSUE TITLE
How debug in LibCarla Server with IDE (e.g. VS studio 2017)

### ISSUE THREAD

**Issue by windcatcher** [carla-simulator/carla#3693]

**Comment by jy723** [comment]
windows:
1.compile carla_server.lib and carla_server.pdb to Unreal\CarlaUE4\Plugins\Carla\CarlaDependencies\lib
2.debug carlaUE4 project ,(make sure dep carla_server.lib)
good luck

**Comment by corkyw10** [comment]
@windcatcher are you still facing issues with debugging?
