### ISSUE TITLE
Minor bug in GetPreviousUntilLaneStart

### ISSUE THREAD

**Issue by philkr** [carla-simulator/carla#3695]
`Waypoint::GetPreviousUntilLaneStart` sometimes returns a point on the other end of the adjacent road because `remaining_length` is not computed correctly. There is a 1 character fix:
```
if(_waypoint.lane_id < 0) {
```
to
```
if(_waypoint.lane_id > 0) {
```
in https://github.com/carla-simulator/carla/blob/5bd3dab1013df554c0198662e0ceb50b7857feba/LibCarla/source/carla/client/Waypoint.cpp#L115

**Comment by corkyw10** [comment]
@philkr Thanks for the input

@Axel1092 could you follow up on this please?

**Comment by Axel1092** [comment]
@philkr thank you for the notice. We will fix this small issue.
