### ISSUE TITLE
Subdivision types of road line in segmentation camera with build-in carla map

### ISSUE THREAD

**Issue by jerryliu20001** [carla-simulator/carla#3698]
Hi all:
In my situation, I need to separate the rode line into single lines , double lines, zebra crossing, etc. for segmentation.
The problem is the road lines in CARLA map mostly seems to be combined together, looks like the yellow region selected in following picture:
![image](https://user-images.githubusercontent.com/69243907/101857953-9dea0600-3ba3-11eb-9cd9-c23bb1e7e48a.png)
Is it possible the separate the road lines, or it is just fixed when creating the map?
Currently, I just deleted the default road lines and drew the new ones, but it was extremely time-consuming ...
I thought it is related to the map creation.
Does anyone have any suggestion ?
Thanks in advance !!

**Comment by corkyw10** [comment]
@XGodina could you follow up on this please?

**Comment by XGodina** [comment]
Hi @jerryliu20001,
Yes, it is !! However, it's a long process. You shall all groups of lanes markings and export to a 3d software and after separately in any parts that you need. After that, you can import it again into the map. It's a surgical operation.

**Comment by jerryliu20001** [comment]
Hi @XGodina ,
Thanks for your reply, but I have another question 
I can export the lanemark into .fbx file but I am not sure is it possible to separate the .fbx into parts
Do you have any suggestion for the CAD software which is able to split .fbx file?
Or maybe the exported file is not .fbx?

Thanks!!
