### ISSUE TITLE
Behaviour agent bug: incoming_waypoint becoming None

### ISSUE THREAD

**Issue by dHonerkamp** [carla-simulator/carla#3701]
Hi, I am using the latest version of the pythonAPI, built from source.

It seems that due to the waypoint buffering the behaviour_agent can run into the case where `self.incoming_waypoint` is None, leading to a failure when checking `self.incoming_waypoint.is_junction` in line 417 of carla/PythonAPI/carla/agents/navigation/behavior_agent.py

Probably this is a one-line fix, though I am not sure I understand the difference between the waypoint buffer and the waypoint queue enough to know if this just an unhandled case or if this should never be possible.

**Comment by corkyw10** [comment]
@dHonerkamp thank you for your patience

@glopezdiest are you able to follow up on this please?

**Comment by glopezdiest** [comment]
Yeah, we'll take a look

**Comment by glopezdiest** [comment]
Ups, I completely forgot to report about this. Currently, that function is indeed badly created and returns none if the buffer is very small. We are improving the agents API and this will be solved when it comes out. As of right now, a check should be added after this function is used, to check if it returns None
