### ISSUE TITLE
Spectator display is abnormal while changing transform rotation

### ISSUE THREAD

**Issue by TianTianlove** [carla-simulator/carla#3711]
Hi Team,

    I tried to use spectator to show the driver's view. So I need to change the spectator rotation to follow the driver's view. I set up a camera that combines the vehicle, then change the spectator to the transform of the camera. But I found the spectator window keeps shaking. 

BRs,
TX

**Comment by corkyw10** [comment]
@doterop could you have a look at this please?

**Comment by doterop** [comment]
Hi @TianTianlove 

What do you mean by shaking? Can you share a small video?
