### ISSUE TITLE
Roadrunner issues: How to merge two-way lanes based on xodr into 'Freeway' pattern? 

### ISSUE THREAD

**Issue by EchoYJJ** [carla-simulator/carla#3726]
After importing xodr(OpenDrive file) into Roadrunner, I noticed that lanes in different directions are divided far apart.
![image](https://user-images.githubusercontent.com/75726020/102426738-df1e6200-404a-11eb-9f08-df3d14c3dfee.png)
However, for a more realistic simulation, what I really want is the 'Freeway' pattern provided by roadrunner itself.
![image](https://user-images.githubusercontent.com/75726020/102426749-e5144300-404a-11eb-9d6b-95fed4abe50a.png)
If you know how to merge two-way lanes based on xodr into 'Freeway' pattern, please give me some advices, thanks!

**Comment by XGodina** [comment]
Hi @EchoYJJ, 
The only thing that comes to mind is to edit manually in RoadRunner. In that way, you need to delete one of the directions and drop over another one the Freeway style from Roadrunner.
