### ISSUE TITLE
Carla 0.9.10 segmentation fault when simulating 1000 cameras and 400 cars in osm map exported from openstreetmap.

### ISSUE THREAD

**Issue by yangyueren** [carla-simulator/carla#3745]
I am using carla([Ubuntu] CARLA_0.9.10.1.tar.gz) with my own map imported from osm file,  the same osm in #https://github.com/carla-simulator/carla/issues/3686#issue-759431000 

The RGB camera number is 1000, and the vehicle number is 400. I want it to run for 30000 frames, but I got segmentation fault after rendering 2519 frames.

Is there any guide for rendering 1000 cameras?

![image](https://user-images.githubusercontent.com/26768698/102716617-fba2ee80-4317-11eb-9e2a-8cbab2fcf765.png)

![image](https://user-images.githubusercontent.com/26768698/102716628-107f8200-4318-11eb-8016-b3d6d4488288.png)

Here is my code:
![image](https://user-images.githubusercontent.com/26768698/102733212-a4cd0180-4377-11eb-8f45-78996e79efc5.png)
![image](https://user-images.githubusercontent.com/26768698/102733237-adbdd300-4377-11eb-823d-397326e84eb2.png)

I found that the code works well with Townbig.xdor map. But it fails with the osm map exported from openstreetmap website.

Could someone help me?

**Comment by corkyw10** [comment]
@Axel1092 could you have a look at this please?

**Comment by Axel1092** [comment]
I will take a look for issues with many cameras. We have made a number of changes to the OSM to OpenDRIVE converter which may fix the issue. A different matter is the size of the map. Currently Unreal Engine only accepts maps of limited sizes, if the cameras render out of bound it could cause stability issues, do you get segmentation fault on the client alone or is the server crashing as well?
