### ISSUE TITLE
Pygame window not working properly: "Warning: TF_REPEATED_DATA ignoring data with redundant timestamp"

### ISSUE THREAD

**Issue by anavc97** [carla-simulator/carla#3746]
I'm trying to run `roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch` but the pygame window does not work properly: sometimes it changes colours to different types of blue, other times it goes all to white or black. 
I've checked that this also happens for the RGB camera sensor and when I run manual_control.py. 
No errors are shown but there are warnings that keep showing. I dropped a screenshot below. From the warnings I assume it has something to do with pygame's buffers so I tried different versions of pygame with no luck. 

Any help would be appreciated. Thanks.

**My setup:**

-  Ubuntu 20.04.1 LTS
- ROS Noetic
- CARLA 0.9.10
- Egg: carla-0.9.10-py3.7-linux-x86_64.egg
- Pygame versions I've tried: 2.0.0, 2.0.0.dev24, 2.0.0.dev22, 2.0.0.dev20, 1.9.6
- carla-ros-bridge installed from source: https://github.com/carla-simulator/ros-bridge.git
- NVIDIA Corporation GM108M [GeForce 940MX]
- Nvidia drivers:  NVIDIA driver metapackage from nvidia-driver-455

![Selection_002](https://user-images.githubusercontent.com/57260454/102719177-7520e980-42e4-11eb-9c2f-00604fe9fb45.png)

EDIT:

I've fixed the issue with the pygame image by downgrading Carla to version 0.9.9.4 (I was not able to downgrade the ros-bridge however, which I assume it has to do with incompatibilities with ROS Noetic).
The warning is still there but the pygame image is working fine, so I assume the issue is with the version of Carla used.
Since then I've tried both Carla 0.9.10 and 0.9.11 but in any one of them the pygame image constantly blinks white, sometimes going fully blank for a few minutes. I also noticed that the Town map is much brighter than on version 0.9.9.4. Might be related.

**Comment by corkyw10** [comment]
@joel-mb could you have a look at this please?

**Comment by anavc97** [comment]
> @joel-mb could you have a look at this please?

Thank you for your time. I've edited my original post with some new information I found out since the post was made.
