### ISSUE TITLE
Traceback (most recent call last):   File "spawn_npc.py", line 26, in <module>     from carla import VehicleLightState as vls ImportError: cannot import name 'VehicleLightState' from 'carla' (../carla/dist/carla-0.9.10-py3.8-linux-x86_64.egg/carla/__init__.py)

### ISSUE THREAD

**Issue by KangChou** [carla-simulator/carla#3749]

**Comment by KangChou** [comment]
Traceback (most recent call last):
  File "spawn_npc.py", line 26, in <module>
    from carla import VehicleLightState as vls
ImportError: cannot import name 'VehicleLightState' from 'carla' (../carla/dist/carla-0.9.10-py3.8-linux-x86_64.egg/carla/__init__.py)

**Comment by Shubhamcl** [comment]
I faced the same error, so I moved to the stable version that is 0.8.2, that seems to work, and has documentation if you select stable version on readthedocs

**Comment by KangChou** [comment]
Have you solved this problem now?

**Comment by corkyw10** [comment]
Hi @KangChou are you still facing this issue? These problems often arise from using different versions of Python, did you install the API and dependencies with python 3.7?

**Comment by Datalux** [comment]
Same issue. Installed carla with Python 3.7. Anyone solved this error?

**Comment by ajdroid** [comment]
I'm seeing the same error with py3.8 and Carla 0.9.11 on Windows. My Pythonpath seems to point to the correct egg but it complains 
> ImportError: cannot import name 'VehicleLightState' from 'carla'
