### ISSUE TITLE
I'm trying to speed up the raycast lidar

### ISSUE THREAD

**Issue by SimonLeeGit** [carla-simulator/carla#3757]
Hi,
    I'm trying to speed up the raycast lidar. It really low when we use much more rays. I have found the scene lock is heavily costed from the unreal stat infos. I did some tests and nothing is helpful, util I removed the readlock. It seems work very well. I have checked the physx document, and it seems necessary when using raycast interface. This optimization maybe dangerous, but I've no idea about this. Do anyone has tried this?

**Comment by DSantosO** [comment]
Hello @SimonLeeGit,

I assume that you mean the lockRead happening in SimulateLidar() function, isn't it? 
This was helping in the Raycast that is performed in the ParalellFor so it can be dangerous. Have you tested the performance? Is it better?
You can checked both the performance and the correct behaviour of the raycast sensors using the check_raycast_sensors_determinism and the raycast_sensor_testing scripts in the util folder.
