### ISSUE TITLE
How to calculate focal length?

### ISSUE THREAD

**Issue by neokratia** [carla-simulator/carla#376]
Hi,

I want to know focal length.
Is it possible to calculate focal length from FOV and image size?
Or is there a fixed value of it?

Thanks in advance

**Comment by wzhAptiv** [comment]
I don't think there's focal length on the current camera, since no blur effect is found in any pixel, regardless of distance of the object.

**Comment by neokratia** [comment]
I found it in P matrix thanks

**Comment by YashBansod** [comment]
@neokratia can you please share where the P matrix is that you mention?

**Comment by SAmmarAbbas** [comment]
@neokratia  Where did you find the P matrix?

**Comment by wzhAptiv** [comment]
@SAmmarAbbas @YashBansod  try #56

**Comment by noahcao** [comment]
How about the calculation of focal length in carla 0.9.x?
