### ISSUE TITLE
[Feature Request] Server-Side Bounding Boxes

### ISSUE THREAD

**Issue by jbeck9** [carla-simulator/carla#3760]
The most common issue that makes the client side bounding box script not so useful is the fact that it can't detect whether the object is visible in scene or not #3601 #1743 ...

This issue is much easier to resolve on the server side with a handful of ray traces per object to check for visibility.

In my opinion, the most intuitive solution is a camera sensor that returns bounding boxes. Given a resolution and FOV, the sensor would return:
*Object type for each actor (vehicle, pedestrian, etc) detected.
*location, orientation, and dimension in 3D world space of all visible objects.
*location and dimension in 2D image space of all visible objects.
*Boolean whether the bounding box is truncated.
*Boolean whether the bounding box is occluded.

The above would allow a fully automated pipeline from simulation to object detector training data with no wonky segmentation steps in the middle.

I may end up doing this myself, but it is a common enough problem I wanted to reach out and see if anyone else had implemented anything along these lines. Thanks.

**Comment by PTorr** [comment]
I was just looking for a solution to this.

You can also use intersection with segmentation map.

**Comment by corkyw10** [comment]
@doterop could you have a look at this please?

**Comment by mittkongg** [comment]
> I was just looking for a solution to this.
> 
> You can also use intersection with segmentation map.

any results?

**Comment by Jaivra** [comment]
any solutions?
