### ISSUE TITLE
Access to wheels rotation angle in PythonAPI

### ISSUE THREAD

**Issue by unumkam** [carla-simulator/carla#3765]
This feature might be helpful for precise position estimation. Coupling position sensors with wheel odometry seems to be more intuitive way to build feedback-based control of car. I was wondered Carla not provides this data.
Locally I have done it through ACarlaWheeledVehicle, then filled ActorDynamicState from WorldObserver and get it accessible from Python Vehicle type

**Comment by corkyw10** [comment]
@DSantosO could you follow up on this please?

**Comment by DSantosO** [comment]
Hello @unumkam,

This is currently being implemented in PR #3868 and it will be soon in dev branch so I close the issue. Feel free to reopen if necessary.

**Comment by NishanthARao** [comment]
@DSantosO Hi.

From the PRs, I see that two new functions are added: SetWheelSteerAngle and GetWheelSteerAngle.

However, the question asks the rotation angle of the wheel and not the steer angle of the wheel right? Could we use the GetRotationAngle() that UVehcileWheel provides?
