### ISSUE TITLE
Documentation: Merge vehicle modeling and add a vehicle

### ISSUE THREAD

**Issue by BAROBA-3d** [carla-simulator/carla#3768]
Hi all,
I would like to suggest to merge 2 pages.
https://carla.readthedocs.io/en/latest/tuto_A_vehicle_modelling/
and 
https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/
Everything in "tuto_A_add_vehicle" can be put under Rigging in "tuto_A_vehicle_modelling".
The whole rigging part can be replaced as the same information is there too.
Maybe split off 2 wheels vehicles?

Kind regards,

Rob

**Comment by corkyw10** [comment]
Hi @BAROBA-3d Thank you for your input on this. I have rewritten the tutorial and integrated the modelling into the import tutorial and it's being reviewed. I still need to review the two wheeled vehicle section.
