### ISSUE TITLE
Carla 0.9.11 Make PythonAPI/Make Launch issue with Boost (no error code)

### ISSUE THREAD

**Issue by yaadram** [carla-simulator/carla#3769]
Windows 10
Visual Studio 2017
Python 3.7 x64
Carla 0.9.11

- **I used the same configuration to successfully build Carla 0.9.9**. 
- Was successful in compiling the UE2.4 patch for this version.
- Cloned Carla repository and added assests.

When running "make PythonAPI" or "make launch"  , after several stages the script freezes in the file copying sequence of **boost 1.72** . I tried various changes i saw in the issue page and the script always freezes on the same location:
![image](https://user-images.githubusercontent.com/29002095/103478584-5d5f6000-4dd0-11eb-816f-7c1f00ce48c4.png)
The final printout is :
 common.copy C:\carla\Build\boost-1.72.0-install\boost-1_72\boost\compatibility\cpp_c_headers\cwctype
C:\carla\Build\boost-1.72.0-source\boost\compatibility\cpp_c_headers\cwctype
        1 file(s) copied.

- I tried waiting for more than half an hour and eventually I need to stop the process (ctrl+c). 

Anything I missed ? Any tips? 

Thank you in advance! 
Yaad Grossman

**Comment by corkyw10** [comment]
@bernatx could you have a look at this please?

**Comment by slugdev** [comment]
Same thing happens on my build

**Comment by gutianchang** [comment]
same problem🤦‍♂️
