### ISSUE TITLE
Weird behavior with GNSS levar arm

### ISSUE THREAD

**Issue by roshambo919** [carla-simulator/carla#3770]
Using Carla 0.9.10 quickstart on Ubuntu. 

I'm adding a GNSS sensor to a vehicle and seeing what looks like weird behavior when I change the GNSS levar arm coordinates even with rigid attachments.
1. If I add GNSS to vehicle origin with z shift (0,0,any-z), event.transform matches vehicle.get_transform()
2. If I add GNSS with a levar arm (non-zero in at least x or at least y), event.transform *initially* matches vehicle.get_transform() but appears to drift over time with movement of the vehicle even with a "rigid" attachment.

Anyone know if this is a bug or user error? Code is below along with plots of difference between event.transform.location and vehicle.get_transform().location

```
class GnssSensor(object):
    def __init__(self, ego):
        self.sensor = None
        self._ego = ego
        self._parent = ego.actor
        self.levar_arm = [1.0, 0, 0]
        # self.levar_arm = [0, 0, 0]

        world = self._parent.get_world()
        bp = world.get_blueprint_library().find('sensor.other.gnss')
        tform_sensor = carla.Transform(carla.Location(x=self.levar_arm[0], y=self.levar_arm[1], z=self.levar_arm[2]))
        self.sensor = world.spawn_actor(bp, tform_sensor, attach_to=self._parent, attachment_type=carla.AttachmentType.Rigid)
        # We need to pass the lambda a weak reference to self to avoid circular
        # reference.
        weak_self = weakref.ref(self)
        self.sensor.listen(lambda event: GnssSensor._on_gnss_event(weak_self, event))

    @staticmethod
    def _on_gnss_event(weak_self, event):
        self = weak_self()
        if not self:
            return
        self.lat = event.latitude
        self.lon = event.longitude
        # hack for right now to get truth x-y
        self._ego.sensor_data_queue.put(
                np.array([event.transform.location.x - self.levar_arm[0],
                          event.transform.location.y - self.levar_arm[1]])
            )
```
Here, GNSS is running at tick rate of 20Hz

Case 1: GNSS at vehicle origin (blue and orange are x and y difference between event.transform and vehicle.get_transform() and both are 0)
![image](https://user-images.githubusercontent.com/20426598/103563996-c2c45700-4e8b-11eb-89e1-92c47339a7d8.png)

Case 2: GNSS with levar arm (blue and orange are x and y difference and are NOT 0 and also not just constant error)
![image](https://user-images.githubusercontent.com/20426598/103564192-18006880-4e8c-11eb-93a0-5766b1b5de8e.png)

**Comment by corkyw10** [comment]
@Axel1092 could you have a look at this please?
