### ISSUE TITLE
CarSim problem：no collision

### ISSUE THREAD

**Issue by JarvanI** [carla-simulator/carla#3777]
I built 0.9.11 on win10 and generated the .sim file according to the requirements of the official documentation. Then I run manual_control_carsim.py and pressed ctrl+k to enable carsim. But I found that the collision disappeared after turning on carsim, the vehicle could drive into the walls and the house, and even out the map. The accelerator and brake of the vehicle can be controlled normally, but the steering angle is very small compared to the original, and there is basically no way to steer normally. 
![图片](https://user-images.githubusercontent.com/36652059/103767180-251f8200-505b-11eb-9431-d463cbc43a88.png)
![图片](https://user-images.githubusercontent.com/36652059/103767237-3ff1f680-505b-11eb-8942-c6ddcfe8fbd7.png)
I want to know where this problem is my setting wrong? I generated the sim file according to the picture below
![图片](https://user-images.githubusercontent.com/36652059/103767336-63b53c80-505b-11eb-86cb-0e28bf3168cb.png)

**Comment by corkyw10** [comment]
@bernatx could you have a look at this please?

**Comment by wittenator** [comment]
Our team is thinking about investing in CarSim to use it in Carla. Is this still a problem in the newest release, @JarvanI ?
