### ISSUE TITLE
Vehicle spawns in the air for a custom map created in RoadRunner 

### ISSUE THREAD

**Issue by athulg** [carla-simulator/carla#3788]
Hello, I tried creating a custom map in RoadRunner and imported it in CARLA(Version: 4.24.3-0+++UE4+Release-4.24) using the plugins.

While spawning the vehicle in the custom map the vehicle is not spawned in the ground, I tried various values of z axis, but it throws an error(shown below) if the value of z is lower than a specific value(in this case z=10.0).

```
    actor1 = world.spawn_actor(blueprint,transform)
RuntimeError: Spawn failed because of collision at spawn position
```

I'm spawning the vehicle by using the slightly altered example of  PythonAPI tutorial.py

![Screenshot from 2021-01-11 11-09-34](https://user-images.githubusercontent.com/40862977/104168084-bbf29280-53fd-11eb-83db-dbcd11b26c23.png)

Thank you!

**Comment by XGodina** [comment]
Hi @athulg,
It seems that is a collision problem. Check the meshes from RoadRunner and change the Collisions Complexity to "Use Complex Collision As Simple. 

![image](https://user-images.githubusercontent.com/39989886/104204807-f2e09c80-542d-11eb-9e30-618fe25aa7ef.png)

**Comment by athulg** [comment]
@XGodina thank you very much for the help, it works perfectly now.
