### ISSUE TITLE
Adding new vehicle to CARLA

### ISSUE THREAD

**Issue by kubs0ne** [carla-simulator/carla#3789]
Hello!
I'm new to the CARLA simulator, and I wanted to add my own vehicle to this simulator. I created a model using this tutorial: https://continuebreak.com/articles/how-rig-vehicle-blender-28-ue4/ . Everything works fine, I created blueprints, physics assets and all the necessary components. The cars goes forward and turns as expected. But i'm confused with importing this model to CARLA. How do I do it? I read this tutorial: https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/ , but it doesn't tell where in CARLA there is an option to import blueprints etc. Also, I don't understand the 10th step of the tutorial. How do I open this "vehicle factory"? Any help would be great :).

**Comment by XGodina** [comment]
Hi @kubs0ne,
In CARLA there is a folder Carla/vehicles/ where we have all relative of cars. Inside the Blueprint "vehicle factory" there is a array of vehicles where you can put your car.

![image](https://user-images.githubusercontent.com/39989886/104215733-7a7fd880-5439-11eb-88e8-365729fc4f15.png)

**Comment by kubs0ne** [comment]
Thank you for quick response. So does it mean I have to open the CarlaUE4.uproj file as a project in UE4?

**Comment by BAROBA-3d** [comment]
Yes, you need that project to be able to use the functionality you need. Everything in the docs presumes that you use that project, something to keep it in mind.

**Comment by parth3153** [comment]
> Yes, you need that project to be able to use the functionality you need. Everything in the docs presumes that you use that project, something to keep it in mind.

hello, i am struggling with the same thing, but when i open CarlaUE4 Project file it does not open it says 
![image](https://user-images.githubusercontent.com/56869308/107895508-79cedc00-6ee8-11eb-96f2-f021949737da.png)


and then when i rebuild , it says rebuilding could not be compiled try building from source. btw i have UE 4.24.3.
thank you any help would be appreciated

**Comment by eslaaam3** [comment]
Hello,
I'm having a similar issue and I have posted an [issue](https://github.com/carla-simulator/carla/issues/5674) #5674
Can anyone help please?
Thanks!
