### ISSUE TITLE
bounding boxes for bended fences

### ISSUE THREAD

**Issue by jbmag** [carla-simulator/carla#3790]
Hello,
I'm using _carla.World.get_environment_objects_ to get and display the bounding boxes of objects, and I observed a problem with a few objects, in particular fences and Guardrails. When e.g. a fence is bended, the corresponding bounding box becomes really big to contain all of it (e.g. pink and yellow boxes in screenshot). Is there a way to avoid this?
![bounding_box_issue](https://user-images.githubusercontent.com/47941074/104179037-89e82d00-540b-11eb-8b50-eb00d0988908.PNG)

**Comment by corkyw10** [comment]
@doterop could you have a look at this please?
