### ISSUE TITLE
Extrinsic Matrix of Lidar to Camera fusion is not constant!

### ISSUE THREAD

**Issue by dupply** [carla-simulator/carla#3795]
As mentioned in lidar_to_camera.py, at first lidar points are converted to World frame than to Camera frame and finally to Image frame. 
`            # This (4, 4) matrix transforms the points from lidar space to world space.
            lidar_2_world = lidar.get_transform().get_matrix()
            

            # Transform the points from lidar space to world space.
            world_points = np.dot(lidar_2_world, local_lidar_points)

            # This (4, 4) matrix transforms the points from world to sensor coordinates.
            world_2_camera = np.array(camera.get_transform().get_inverse_matrix())

            # Transform the points from world space to camera space.
            sensor_points = np.dot(world_2_camera, world_points)`

Usually after the extrinsic matrix is constant because relative postion of the sensors are not changing but extrinsic matrix for projection of lidar point to camera frame ie `np.dot(world_2_camera, lidar_2_world)` is not constant.

Is there any way to find the extrinsic matrix for projection of lidar point to camera frame without transforming to world frame or is there any other way to find a constant extrinsic matrix?

I am asking this because I am writng a C++ ROS code for projection of lidar point cloud to image frame and I am subscribing only lidar and camera rostopics.

Thank you for your help in advance

**Comment by makaveli10** [comment]
@dupply did you get the lidar_2_cam matrix finally?

**Comment by jiheddachraoui** [comment]
@dupply  did you find an answer

**Comment by zhiranyan** [comment]
Hi, i am also curious about how to get extrinsic matrix between lidar and camera. Is there any way? Thanks a lot!
