### ISSUE TITLE
How to set vehicle speed in Carla

### ISSUE THREAD

**Issue by xty199636** [carla-simulator/carla#3796]
I found it on Carla's website Actor.set_ target_ The command velocity (self, velocity) is useless. Python reports an error and displays attributeerror: 'vehicle' object has no attribute 'set_ target_ .Can I ask how to set the vehicle speed.

**Comment by NishanthARao** [comment]
@xty199636 Hi. Do you mean ```Actor.set_target_speed()```? Like you mentioned, there is no function called ```set_target_```. However, ```set_target_speed()``` is present, and you can use that to set the desired speed of the vehicle.
