### ISSUE TITLE
Running carla0.9.11 docker on headless server with vulkan graphics api

### ISSUE THREAD

**Issue by pavanteja295** [carla-simulator/carla#3800]
Hello everyone,
I have been struggling to get carla.0.9.11 docker get running with **vulkan** api enabled on a **headless** server. I see multiple ways to enable a **headless** server run a Xapplication. However, none of the below worked for me. It would be great if someone can let me know if there is a way to actually work this out.

What I needand some background:

Run carla0.9.11 with **vulkan** option on a head less server(no monitor or vga adapter). According to my understanding `SDL_VIDEODRIVERS` can be set to `offscreen` or `x11`. Offscreen states that there is no display and  x11 specifically mentions that we are using a display. **Vulkan** cannot work in offscreen mode in UnrealEngine 4.24 (Check this [here](https://github.com/adamrehn/ue4-docker/issues/76)). However, opengl works with offscreen option which is why **most of the solutions** here in the issue page work with `offscreen` option.  UnrealEngine4.26 offers offscreen vulkan mode but its not a possiblity as carla is made on UnrealEngine4.24

What I already did:

1. Set a fake screen with no device using `sudo nvidia-xconfig --preserve-busid  --enable-all-gpus --use-display-device=None --virtual=1280x1024 `  and use the dockerfile [DockerFile](https://github.com/carla-simulator/carla/blob/master/Util/Docker/Release.Dockerfile). This did not work.
2. Also I tried this suggestion from nvidia-forum to run Xapplications without a display. Check this [out](https://forums.developer.nvidia.com/t/jetson-nano-headless-rendering/78660). Surprisingly, this gets **xclock** working which is a X application that usally runs only with a monitor, however,  carlaue4.sh crashes again which is very strange. This is the output I get 
```4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
``` 

3. I also tried my luck with vncservers that can connect to already existing x11server and provides a device for rendering. I tried this as I thought Carla defintely needs a device to render but this did not work as well. Try this out: [here](https://docs.nvidia.com/grid/9.0/grid-vgpu-user-guide/index.html#installing-configuring-x11vnc-on-linux-server) 
4. Lastly, I tried with seperate Xserver using xvfb like [this](https://unix.stackexchange.com/questions/119149/fake-monitor-in-a-headless-device). This **successfully** launches carla with vulkan **however**  does not use on nvidia-graphics card.

Also note x11 forwarding via ssh is not possible with vulkan apis only possible with opengl via VirtualGL so ssh -X option as well does not help you here.

Final remarks and question:
After spending almost a day to gain some understanding on how Xapplications work I still coudln't find a way. :( . The script provided [here](https://github.com/carla-simulator/carla/blob/master/Util/Docker/Release.Dockerfile) states that **it is possible** to run carla with vulkan on headless servers but i followed their method and it doesn't work. @germanros1987  could you please clarify if this script is tested on headless systems with vulkan?   If someone knows any other way let me know. Also let me know if I'm doing something wrong with one of the methods above or vulkan + headless is not possible at all. 

Thanks!

**Comment by qhaas** [comment]
I'm looking into this too.  OpenGL has artifacts in [ppc64le](https://github.com/carla-simulator/carla/issues/1567#issuecomment-700790499) and (different artifacts) in [x86-64](https://github.com/carla-simulator/carla/issues/3377), so I'd like to switch to vulkan.  We run CARLA in HPC environments, so we don't have x-servers running.

According to this [UnrealEngine container guide](https://unrealcontainers.com/docs/use-cases/cloud-rendering#offscreen-rendering-flags), headless vulkan rendering without an x-server wasn't added till UE 4.25.  Given we are stuck on UE 4.23 for ppc64le, I was hoping to find which commit Epic added this feature to UE and backport it to UE 4.23 and UE 4.24.  Unfortunately, their commit logs don't explicitly say where this feature was made and it doesn't seem to be in their [SDL2 fork](https://www.phoronix.com/scan.php?page=news_item&px=SDL-New-Vid-Driver-Offscreen).

I'm currently attempting to get [CARLA 0.9.11 working with UE 4.25.3](https://github.com/carla-simulator/carla/issues/3214) to see if headless vulkan without X works, and if it does, steadily add the vulkan changes between UE 4.24 and UE 4.25.3 until I hit on the right commit.

**Comment by corkyw10** [comment]
@bernatx could you follow up on this please?
