### ISSUE TITLE
Windows Build error Couldn't find parent type for 'SimpleWheeledVehicleMovementComponent' named 'UWheeledVehicleMovementComponent'

### ISSUE THREAD

**Issue by lynnrabbit** [carla-simulator/carla#3803]
OS:Windows10
VisualStudio 2019
Carla version : 0.9.11.release
UE4 version:4.24

Problem:
When I first time build UE4,get the following error:

ErrorLog:1>EXEC : error : Couldn't find parent type for 'SimpleWheeledVehicleMovementComponent' named 'UWheeledVehicleMovementComponent' in current module (Package: /Script/PhysXVehicles) or any other module parsed so far.

The git patch "UE4_patch_wheels.patch" has been apply,and it happend when build UE4 project in vs.
I try to use the cmd tool run the build.bat,and get the same error.

**Comment by corkyw10** [comment]
@bernatx could you have a look at this please?
