### ISSUE TITLE
carla server is not launched properly

### ISSUE THREAD

**Issue by quangsonle** [carla-simulator/carla#3805]
carla release : 0.911 (latest as it is sent) 
window 7
Unreal 4.24.3

i can launch carla.exe alone

but when i try to launch it as server:
CarlaUE4.exe -carla-server -carla-world-port=2003 -carla-fps=30

but when python api tried to connect to it, i got : RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2003

in order to debug it, i killed all processes of carla in task manager and launch server the same way
with netstat -an
i found first time 127.0.0.1:2003 's state is time_waiting
then netstat -an gain, no more 127.0.0.1:2003, but i got 0.0.0.0:2003 is listening

carla app is launched ok

**Comment by Axel1092** [comment]
Hi @quangsonle, the flags you are using are not the correct ones: At the end of this tutorial you will find a list of available Command-line options https://carla.readthedocs.io/en/latest/start_quickstart/.
