### ISSUE TITLE
IMPORT Radar Model in AirSim

### ISSUE THREAD

**Issue by tayabalik** [carla-simulator/carla#3815]
Hello, 
I am trying to build a radar model using Microsoft AirSim which runs on Unreal Engine. Is it possible to use the Radar model from Carla on AirSim. Any leads on the implementation of a Radar model would be appreciated.

**Comment by germanros1987** [comment]
I think this question belongs in the AirSim repository.

**Comment by ZifaZhu** [comment]
Hello, have you implemented this function?

**Comment by NedaRH** [comment]
Hi tayabalik, have you implemented this function?

**Comment by tayabalik** [comment]
Hello @NedaRH @ZifaZhu , I created a model using AirSim where I used the points from the Lidar function on AirSim and simulated it as Radar using a clustering algorithm DBSCAN.

**Comment by NedaRH** [comment]
Hi tayabali,

Thanks for replying and consideration my request. Can I ask if is possible you share your code? Honestly I am also want to use AirSim for radar.

Best,
Neda

**Comment by zhaozhiqing1** [comment]
Hi @tayabalik ,

Can I ask if is possible you share your code? Honestly I am also want to use AirSim for radar.

Best,
Zhaozhiqing1
