### ISSUE TITLE
Reinforcement learning tutorials

### ISSUE THREAD

**Issue by histfuture** [carla-simulator/carla#382]
Are there any reinforcement learning tutorials in carla?

**Comment by felipecode** [comment]
We would love to do them.
For sure an interesting feature request.
Community is super welcome to help us on that as well !

**Comment by felipecode** [comment]
Yes.
It should be easy. Check the RL repo :
https://github.com/carla-simulator/reinforcement-learning
You could also read about it on our latest blog post:
http://carla.org/2018/04/23/release-0.8.2/

**Comment by histfuture** [comment]
@felipecode  This is great , are there any schedule for releasing the training part?
