### ISSUE TITLE
Vehicles Spawn in the air whether on a default map or a map from RoadRunner

### ISSUE THREAD

**Issue by 5buy5bobee** [carla-simulator/carla#3821]
Hello, I tried to import a vehicle to the project using a default map, but my vehicle floated in the air. However if I tried another vehicle like mini, it worked perfectly. I have followed the steps from CARLA tutorials and checked them lots of times. How could I fix this problem? Thank you!

I read the tutorials to export a vehicle from blender.
https://continuebreak.com/articles/how-rig-vehicle-blender-28-ue4/

And I followed these steps to import to CarlaUE4.
https://carla.readthedocs.io/en/latest/tuto_A_add_vehicle/

Here is what we see in Client. It looks like on the ground but it actually floats in the air.
![image](https://user-images.githubusercontent.com/77049414/105443801-912ef680-5ca7-11eb-97b2-a0f3a0de1c3c.png)

The current progress is that the throttle, steer, brake seems working, but It can't move forward.

**Comment by 5buy5bobee** [comment]
I have read this but I do change the physics type to Kinematic.

https://github.com/carla-simulator/carla/issues/3821

**Comment by XGodina** [comment]
Hi, @5buy5bobee 
Do you still have the problem?
Do you change the shape radius of wheels?  If the radius is greater than your wheel it will float
![image](https://user-images.githubusercontent.com/39989886/105990083-4a277380-60a2-11eb-8a5d-9217432963c5.png)

**Comment by 5buy5bobee** [comment]
> Hi, @5buy5bobee
> Do you still have the problem?
> Do you change the shape radius of wheels? If the radius is greater than your wheel it will float
> ![image](https://user-images.githubusercontent.com/39989886/105990083-4a277380-60a2-11eb-8a5d-9217432963c5.png)

Yes I had tried it before but it had not worked then. Still a big thank to you!

**Comment by 5buy5bobee** [comment]
I have solved the problem since I found I set general collider as "Kinematic" instead of "default".

After I changed the settings the vehicle works now.

**Comment by XGodina** [comment]
Great I glad to hear that !!!
