### ISSUE TITLE
A caral server cannot use multiple GPUs at the same time

### ISSUE THREAD

**Issue by yuexishuihan** [carla-simulator/carla#3827]
#### A caral server cannot use multiple GPUs at the same time.
carla 0.9.11 docker+nvidia docker mod.
I can use one of the GPUs, which I can control, but I can’t use more than one at the same time, and the current GPU utilization rate is not high, only 30-40%.
command
```
sudo docker run -d -p 2000-2002:2000-2002 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 carlasim/carla:0.9.11 /bin/bash -c 'SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=0 ./CarlaUE4.sh -ResX=800 -ResY=600 -nosound -windowed -opengl'
```
NVIDIA_VISIBLE_DEVICES
Does anyone have the same problem as me？
Platform:Ubuntu 20.04.1 LTS
Carla version: 0.9.11
NVRM version: NVIDIA UNIX x86_64 Kernel Module  460.32.03  Sun Dec 27 19:00:34 UTC 2020
1d:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
1d:00.1 Audio device: NVIDIA Corporation Device 1aef (rev a1)
b4:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
b4:00.1 Audio device: NVIDIA Corporation Device 1aef (rev a1)
![image](https://user-images.githubusercontent.com/44515500/105789212-fbec7480-5fbc-11eb-8808-e5dce84ae8d9.png)

**Comment by qhaas** [comment]
I have noticed that a single carla process cannot effectively use multiple GPUs at once.  I'm not sure if [SLI](https://docs.unrealengine.com/en-US/RenderingAndGraphics/Nvidia/NVIDIAAlternateFrameRendering/index.html) is supported on Linux like it is on Windows with the underlying UnrealEngine, which would explain this.

Worse still, it will not automatically 'load balance' on multi-gpu systems and will just throw multiple server runs onto gpu 0, even if gpu 0 is pegged at 100% and the other GPUs are idle.  As you discovered, you can use [docker](https://carla.readthedocs.io/en/latest/adv_rendering_options/#docker-recommended-approach) or [SDL environment variables](https://github.com/carla-simulator/carla/issues/225) (outside of docker) to manually restrict it when running with OpenGL.  Unfortunately, using environment variables appears broken with vulkan, at least when using UE 4.25 (which, to be fair, is unsupported by CARLA).

To be fair, I think this is more of an UnrealEngine thing than a CARLA thing.

**Comment by yuexishuihan** [comment]
Okay, thank you for your answer. The bad thing is that it seems impossible to use multiple GPUs in a short time.

**Comment by qhaas** [comment]
Might want to ask over at [UnrealEngine Answers](https://answers.unrealengine.com/index.html), they recently helped me with UnrealEngine GPU selection questions.

**Comment by yuexishuihan** [comment]
Okay.This is a good idea, I will try

**Comment by corkyw10** [comment]
@bernatx could you have a look at this please?

**Comment by qhaas** [comment]
@yuexishuihan , did you discover anything about leveraging multiple GPUs for CARLA?  The closest we have come is just running multiple client/servers on the same GPU (i.e. larger number of independent simulations).

**Comment by yuexishuihan** [comment]
Not yet, I am currently exploring adding/modifying assets in carla, including cars,
Maps, weather, etc.

**Comment by jimmyw404** [comment]
I'm very interested in multi GPU or multi computer CARLA simulation! If anyone has gotten multippe gpus to work or has tried to distribute the carla computing please let us know!!!!

**Comment by gouchaoer** [comment]
any progress?
I am doing realtime 4 camera output in HIL, and I found it's impossible

**Comment by jimmyw404** [comment]
I'm still very interested in this! Unreal doesn't seem to handle multi-GPU simulation very well, so solving this problem is non-trivial.

**Comment by jimmyw404** [comment]
Still very interested in this feature and looking forward to https://github.com/carla-simulator/carla/tree/bernat/multi_gpu !!!
