### ISSUE TITLE
Behaviour agent stops permanently at 'stop sign' in an uncontrolled junction.

### ISSUE THREAD

**Issue by karthi0804** [carla-simulator/carla#3828]
Hi, I am facing a problem when using a behavior agent in Carla 0.9.11 in Ubuntu 18.04. The agent stops permanently at an uncontrolled junction located roughly at (143, 2), town 05.  The expected behavior is to wait for a while and cross the junction when the junction is free of vehicles. Please help me if I am missing something to configure.

**Comment by Esquilli** [comment]
@karthi0804 Did you figured out this issue? My "fix" was to set `ignore_tracffic_light` to `True`

**Comment by karthi0804** [comment]
> @karthi0804 Did you figured out this issue? My "fix" was to set `ignore_tracffic_light` to `True`

I didn't find the root cause. I also used the same workaround.

**Comment by corkyw10** [comment]
@glopezdiest could you have a look at this please?

**Comment by GarethZhang** [comment]
Hi @karthi0804 @Esquilli ,
I am facing the same problem here. Where can I find the option to set `ignore_traffic_light` to True?
Thanks!

**Comment by Esquilli** [comment]
@GarethZhang When you initialize an agent (i.e BehavioralAgent) you can set the `ignore_traffic_light` parameter to True like this `BehavioralAgent(ignore_traffic_light=True)`.

Check the class init parameters [here](https://github.com/carla-simulator/carla/blob/4c8f4d5f191246802644a62453327f32972bd536/PythonAPI/carla/agents/navigation/behavior_agent.py#L36).

**Comment by GarethZhang** [comment]
@Esquilli Thanks a lot!

**Comment by bsande6** [comment]
Has anyone found a solution that allows the agent to still follow normal traffic rules?

**Comment by glopezdiest** [comment]
@bsande6 Are you using 0.9.12 or higher? As far as I remember, the issue is that the behavior agent uses the `vehicle.is_at_traffic_light` function, which always returns True at stop signs, hence why the vehicle stops permanently. I think we fixed it for 0.9.12 though, but I may be wrong. I'll test it ASAP, and report back

**Comment by bsande6** [comment]
@glopezdiest  I was using 0.9.11 at the time but have upgraded since and solved the problem.
