### ISSUE TITLE
Building is not visible by LIDAR

### ISSUE THREAD

**Issue by zygfrydw** [carla-simulator/carla#3829]
Carla Version: 0.9.10
Platform:Ubuntu 20.04.1 LTS
Tested in ROS2 Foxy with carla-bridge. 

Lidar is passing through some buildings in `Town03`, not detecting a building wall, although the car is colliding with the building.
The white points are point cloud map recorded in Carla 0.9.9, the color points are points registered by 2 lidars.

Building 1
![Screenshot from 2021-01-25 17-13-24](https://user-images.githubusercontent.com/3630743/105844476-95298400-5fd9-11eb-8890-41da117a6b7b.png)

![screen_01](https://user-images.githubusercontent.com/3630743/105844798-15e88000-5fda-11eb-9ff3-92431730a2bb.png)
![screen_02](https://user-images.githubusercontent.com/3630743/105844805-184ada00-5fda-11eb-9252-56f27eaf1152.png)
![screen_03](https://user-images.githubusercontent.com/3630743/105844807-197c0700-5fda-11eb-82e9-eed864c3a7ab.png)

Building 2
![Screenshot from 2021-01-25 17-16-56](https://user-images.githubusercontent.com/3630743/105844498-9bb7fb80-5fd9-11eb-8602-20f31d8da820.png)
![screen_04](https://user-images.githubusercontent.com/3630743/105844829-21d44200-5fda-11eb-9366-1498f7f1b684.png)

**Comment by XGodina** [comment]
Hi, 

Sorry for the late answer. I will take look more deeply at it. Thanks to reported

**Comment by XGodina** [comment]
Hi @zygfrydw We know what happens there with the lidar and now we are working to fix it

**Comment by zygfrydw** [comment]
Great, thanks for your help!

**Comment by XGodina** [comment]
Hi @zygfrydw, We've discovered the problems. Some Blueprint in our buildings, there are with a wrong collision preset. Now we add a correct collision preset and now appear in the lidar. The PR is waiting to accept.

**Comment by yuvalHG** [comment]
Is there any new with this issue? is there any branch merged with those changes?
