### ISSUE TITLE
carla.WalkerControl.direction requires a norm vector, otherwise speed is wrong

### ISSUE THREAD

**Issue by ll7** [carla-simulator/carla#3846]
## Issue

the direction of carla.WalkerControl.direction (https://carla.readthedocs.io/en/latest/python_api/#carlawalkercontrol) needs to be a norm vector (length = 1). Otherwise, it affects the speed of the carla walker and the walker runs much faster.

Unfortunately, carla.Vector3D does not provide a method to norm the vector.

I used:
```python
def norm_vector(vector=carla.Vector3D):
    length = (vector.x**2 + vector.y**2 + vector.z**2)**(1/2)
    return vector/length
```

**Comment by corkyw10** [comment]
@bernatx could you have a look at this please?
