### ISSUE TITLE
Does Carla simulator support indoor environment?

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla#3848]
Hello，everyone!
Currently developing indoor and outdoor navigation systems, does carla support indoor scene navigation?

**Comment by qhaas** [comment]
Some of the towns have tunnels.

**Comment by JackRen88** [comment]
Thank you @qhaas   Carla provide an indoor environment model so that the robot can enter the indoor environment and navigate in an unstructured environment?

**Comment by XGodina** [comment]
Hi all,

What do you mean by an unstructured environment? off-road? indoor?

**Comment by KouWeiBin** [comment]
> Thank you @qhaas Carla provide an indoor environment model so that the robot can enter the indoor environment and navigate in an unstructured environment?

Hi JackRen88, could you please tell me where the indoor environment you mentioned? Thanks
