### ISSUE TITLE
object-list interface

### ISSUE THREAD

**Issue by NurbekHalikulov** [carla-simulator/carla#3849]
Hi,

I would like to get a ground truth object-list while using built-in sensor models in CARLA. How to practically visualize this object-list at the sensor models output in Python API or in somewhere else?

How to see ground truth data of all objects surrounding the vehicle in CARLA simulation environment?

**Comment by corkyw10** [comment]
@Axel1092 could you follow up on this please?

**Comment by Axel1092** [comment]
Hi @NurbekHalikulov, I don't really understand the question you would like to have access to a list of every single static or dynamic object in the scene? There is a feature `world.get_level_bbs()` to obtain a list of bounding boxes of all objects in the scene, perhaps this will help you.
