### ISSUE TITLE
Do not missuse CMAKE_BUILD_TYPE variable

### ISSUE THREAD

**Issue by johschmitz** [carla-simulator/carla#3851]
The CMake Layer of the CARLA build system uses the CMake variable `CMAKE_BUILD_TYPE` to distinguish between the client and the server build.
However, the variable `CMAKE_BUILD_TYPE` is officially intended to be used for `DEBUG|RELEASE|RELWITHDEBINFO|MINSIZEREL|...` as described in the CMake documentation:
https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

Hence, CARLA should specify its own variable for the purpose of distinguishing the client and the server build (something like `CARLA_BUILD_TYPE` or `BUILD_CLIENT` or so) and inside each should use `CMAKE_BUILD_TYPE` as intended.

**Comment by corkyw10** [comment]
@bernatx could you follow up on this please?
