### ISSUE TITLE
speed limit getter

### ISSUE THREAD

**Issue by jeanlucdeziel-leddartech** [carla-simulator/carla#3852]
Hi,

Is there a way to get the speed limit at a given point in the map? The only way I found is to use carla.Vehicle.get_speed_limit(), but it requires to have a vehicle at that point. And I'm not quite sure if this is the speed limit of the current road or if it is intrinsic to the vehicle.

It would be useful to have something like carla.Waypoint.get_speed_limit(). Or something similar. An exemple of where it would be useful is in the global path planner, where we could use the speed limit in the distance heuristic, so a highway would be prioritized instead of always picking the shortest path. It would pick the fastest path instead.

**Comment by Axel1092** [comment]
Hi @jeanlucdeziel-leddartech, you cannot query the speed of the road at a given point in the road. You can query the landmarks (road signs) of speed limits which might be useful for you https://carla.readthedocs.io/en/latest/core_map/#landmarks.
