### ISSUE TITLE
CARLA Simulator RGB camera output axes

### ISSUE THREAD

**Issue by ammar-n-abbas** [carla-simulator/carla#3854]
Why is the output of the camera perpendicular to the car's axes?

![tucaG](https://user-images.githubusercontent.com/28593585/106737758-e28c9d80-6638-11eb-8fe1-8f1398f257d9.png)

**Comment by joel-mb** [comment]
Closing the issue. Fixed here: https://github.com/carla-simulator/ros-bridge/issues/478#issuecomment-777960784
