### ISSUE TITLE
IndexError: sensor attribute not found

### ISSUE THREAD

**Issue by NurbekHalikulov** [carla-simulator/carla#3855]
Hello all,

My task was to add these sensor attributes:

sensor.set_attribute('dropoff_general_rate', str(0.2))
sensor.set_attribute('dropoff_intensity_limit', str(0.75))
sensor.set_attribute('dropoff_zero_intensity', str(0.25))
sensor.set_attribute('noise_stddev', str(0.2)) 

to sensor.lidar.ray_cast sensor, as I have an older version of carla version, so I had to add manually those attributes  to **Unreal\CarlaUE4\Plugins\Carla\Source\Carla\Actor - ActorBlueprintFunctionLibrary.cpp** 

So, I modiefied **ActorBlueprintFunctionLibrary.cpp** with such attributes. Also I gave corresponding default values and it looks like now:

......
// Horizontal FOV.
FActorVariation HorizontalFOV;
HorizontalFOV.Id = TEXT("horizontal_fov");
HorizontalFOV.Type = EActorAttributeType::Float;
HorizontalFOV.RecommendedValues = { TEXT("360.0") };
// Atmospheric Attenuation Rate.
FActorVariation AtmospAttenRate;
AtmospAttenRate.Id = TEXT("atmosphere_attenuation_rate");
AtmospAttenRate.Type = EActorAttributeType::Float;
AtmospAttenRate.RecommendedValues = { TEXT("0.004") };
// Noise seed
FActorVariation NoiseSeed;
NoiseSeed.Id = TEXT("noise_seed");
NoiseSeed.Type = EActorAttributeType::Int;
NoiseSeed.RecommendedValues = { TEXT("0") };
NoiseSeed.bRestrictToRecommended = false;
// Dropoff General Rate
FActorVariation DropOffGenRate;
DropOffGenRate.Id = TEXT("dropoff_general_rate");
DropOffGenRate.Type = EActorAttributeType::Float;
DropOffGenRate.RecommendedValues = { TEXT("0.45") };
// Dropoff intensity limit.
FActorVariation DropOffIntensityLimit;
DropOffIntensityLimit.Id = TEXT("dropoff_intensity_limit");
DropOffIntensityLimit.Type = EActorAttributeType::Float;
DropOffIntensityLimit.RecommendedValues = { TEXT("0.8") };
// Dropoff at zero intensity.
FActorVariation DropOffAtZeroIntensity;
DropOffAtZeroIntensity.Id = TEXT("dropoff_zero_intensity");
DropOffAtZeroIntensity.Type = EActorAttributeType::Float;
DropOffAtZeroIntensity.RecommendedValues = { TEXT("0.4") };
// Noise in lidar cloud points.
FActorVariation StdDevLidar;
StdDevLidar.Id = TEXT("noise_stddev");
StdDevLidar.Type = EActorAttributeType::Float;
StdDevLidar.RecommendedValues = { TEXT("0.0") };

if (Id == "ray_cast") {
Definition.Variations.Append({
Channels,
Range,
PointsPerSecond,
Frequency,
UpperFOV,
LowerFOV,
AtmospAttenRate,
NoiseSeed,
DropOffGenRate,
DropOffIntensityLimit,
DropOffAtZeroIntensity,
StdDevLidar,
HorizontalFOV });
}
else if (Id == "ray_cast_semantic") {
Definition.Variations.Append({
Channels,
Range,
PointsPerSecond,
Frequency,
UpperFOV,
LowerFOV,
HorizontalFOV });
}
else {
DEBUG_ASSERT(false);
}
........

Afterwards, I made "make rebuild" of carla. When I run my script, I am still getting **IndexError: attribute 'dropoff_general_rate' not found**

Could you please tell me, what could be the reason? Or should I change content of other files also?

Carla version:
carla 0.9.9
python 3.7.7

**Comment by corkyw10** [comment]
@Axel1092 could you have a look at this please?
