### ISSUE TITLE
Atmospheric attenuation rate value meaning is asked

### ISSUE THREAD

**Issue by NurbekHalikulov** [carla-simulator/carla#3863]
Hello, 

what does **Atmospheric Attenuation Rate:** AtmospAttenRate.RecommendedValues = { TEXT("0.004") } mean?

Carla version: 0.9.11
Windows 10
UE 4.24

Thanks and have a nice weekends!

**Comment by corkyw10** [comment]
This question has been addressed in the discord channel.
