### ISSUE TITLE
Source for RecommendedValues of lidar.ray_cast sensor

### ISSUE THREAD

**Issue by NurbekHalikulov** [carla-simulator/carla#3869]
Could you please provide the source for recommened values of lidar.ray_cast sensor attributes:

Atmospheric Attenuation Rate: AtmospAttenRate.RecommendedValues = { TEXT("0.004") };
Noise seed: NoiseSeed.RecommendedValues = { TEXT("0") };
Dropoff General Rate: DropOffGenRate.RecommendedValues = { TEXT("0.45") };
Dropoff intensity limit: DropOffIntensityLimit.RecommendedValues = { TEXT("0.8") };
Dropoff at zero intensity: DropOffAtZeroIntensity.RecommendedValues = { TEXT("0.4") };
Noise in lidar cloud points: StdDevLidar.RecommendedValues = { TEXT("0.0") };

I was using those attributes and would like to know more about them in detail, so that to be able to manipulate/modify those values based on external factors, e.g. weather, precipitation, etc.

Carla version: 0.9.11
Windows 10
UE 4.24

**Comment by corkyw10** [comment]
This question has been addressed in the discord channel
