### ISSUE TITLE
[Testing] Ambulance and Firetruck

### ISSUE THREAD

**Issue by XGodina** [carla-simulator/carla#3884]
That you have to test

- All regarding the set of vehicles: Lights, Physics, suspension, etc. (Mario and Xavi)

- Behavior of Vehicles. Report potential problems that may arise from their dimensions.

**Comment by XGodina** [comment]
@jackbart94 From our side, we test to spawn those vehicles and also drive with them and so far It's working. But I think you should test for your side if the traffic manager if work this that kind of vehicles.

**Comment by jackbart94** [comment]
They work just fine, sorry for mentioning it only now. I've been testing with them for quite a while.
