### ISSUE TITLE
Vehicle factory not loading up

### ISSUE THREAD

**Issue by parth3153** [carla-simulator/carla#3888]
so i created my vehicle and rigged the bones in blender, did the physics assessment as in documentation, now in the last step of documentation its unclear its written to open the vehicle factory and add the vehicle but in my case the file is not loading up. Please help team Carla and community. 
Thankyou

-->

**Comment by XGodina** [comment]
Hi,

I know, that our documentation about how to implement vehicles in CARLA is a bit confusing. Now we are working to update.
This file is in UnrealEngine. Is a Blueprint that you can open and then put your vehicle there.

![image](https://user-images.githubusercontent.com/39989886/108537507-fb09e280-72dd-11eb-91cd-9fc7e0b7ca51.png)

![image](https://user-images.githubusercontent.com/39989886/108537569-0f4ddf80-72de-11eb-89c3-8b4552d9efe7.png)

**Comment by parth3153** [comment]
no, thats 
![image](https://user-images.githubusercontent.com/56869308/108679492-7a93df00-74a1-11eb-86eb-1ad58d6b5d76.png)
not the problem i am not able to open the ue4 Editor to open the VehicleFactory asset


and i am not able to open it from the engine itself, it ask me to download carsim which is not free and not make sense because its not mentioned in the documentation, idk the reason for all of these

**Comment by XGodina** [comment]
I see,

From what I see in the picture.

Estas intentado abrir UE4, en una versión nuestra compilada. If you need to add vehicles you need to download whole project and UE4.

![image](https://user-images.githubusercontent.com/39989886/108733774-14ee3400-752f-11eb-81ba-ebc9c6a29768.png)

Here you have the documentation on how to download the project and UE4 with win and Linux

**Comment by XGodina** [comment]
https://carla.readthedocs.io/en/latest/#getting-started
