### ISSUE TITLE
ImportError: No module named util

### ISSUE THREAD

**Issue by Johanfanas** [carla-simulator/carla#3889]
Hi,

I built carla the developer mode and I am trying to roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch and I am getting "No module name util". When I run one of the example codes in the PythonAPI using python3 there is no issue. Therefore, I know that error is because the egg file for carla 0.9.10 is for python3.7 and my system is probably running it with python2.7, but I don't have the egg file for python2.7.

![Screenshot from 2021-02-14 18-28-35](https://user-images.githubusercontent.com/62773660/107892344-780a1600-6ef2-11eb-85e8-aa9bab47ca65.png)
. My pc has Ubuntu 18.04 and I am using ros melodic.

Any suggestions?

**Comment by jackbart94** [comment]
Just do ``make PythonAPI.2`` and you should have the .egg file for Python 2.7.

**Comment by Johanfanas** [comment]
The carla I downloaded from here https://github.com/carla-simulator/carla/releases/tag/0.9.10 doesn't have any make file or anything so I can't generate the egg file

**Comment by jackbart94** [comment]
> The carla I downloaded from here https://github.com/carla-simulator/carla/releases/tag/0.9.10 doesn't have any make file or anything so I can't generate the egg file

Please, download the `0.9.10.1` version, or also the `0.9.11` version, which also includes the .egg file for Python 2. The `0.9.10` is the only one that doesn't.

**Comment by Johanfanas** [comment]
Thanks, I got it working

**Comment by likith3611** [comment]
Hii I am facing the same error now, my system is running noetic with supports python3 alone and because of that I had set the egg file to python 3.7 version and am still facing the same issue any help here please?

**Comment by Arrigon88** [comment]
me too! =)

**Comment by AOOOOOA** [comment]
> Thanks, I got it working

Hi, May I ask how did you fix that? Thanks! @Johanfanas
