### ISSUE TITLE
How to compile package supporting Python2 in carla-0.9.11

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#3898]
Ubuntu18.04
carla-0.9.11

I downloaded the source code of carla-0.9.11 and compiled it，but it's only available in the python3 version .
How to compile package supporting Python2 ?

**Comment by lrstttl** [comment]
You can either use `make PythonAPI.2` or change line 15 in file Util/BuildTools/Setup.sh to `PY_VERSION_LIST=2,3` in order to always compile with Python2 support.

**Comment by corkyw10** [comment]
You should also be able to compile for Python 2 with the command `make PythonAPI ARGS="--python-version=2"`
