### ISSUE TITLE
[Testing] 

### ISSUE THREAD

**Issue by XGodina** [carla-simulator/carla#3900]
That you have to test

- Check how to see the distance of the camera.

1. - Motorbikes
2. - Bicycles
3. - Pedestrian
4. - Cars
5. - Van
6. - Assets

**Comment by XGodina** [comment]
I've tested the vehicles and I've seen one of the cameras on bicycles didn't see well.

**Comment by XGodina** [comment]
![bice](https://user-images.githubusercontent.com/39989886/108353663-b18b9b80-71e8-11eb-9ea1-6962e353b641.PNG)
![bice2](https://user-images.githubusercontent.com/39989886/108353666-b2243200-71e8-11eb-8da6-b6068faa648c.PNG)

**Comment by XGodina** [comment]
And I think the camera on the bike could be better.

**Comment by DSantosO** [comment]
You are right, I have modified the lateral camera to let the x parameter fixed, and then it is closer to what it was before.

![latcamera_yamaha](https://user-images.githubusercontent.com/5548733/108375506-4f3f9480-7202-11eb-859e-26c3956a424b.png)

**Comment by XGodina** [comment]
![camera1](https://user-images.githubusercontent.com/39989886/109835487-891d8b80-7c43-11eb-8f11-236e2027ee02.PNG)
![Captura2](https://user-images.githubusercontent.com/39989886/109835494-8a4eb880-7c43-11eb-84b7-317f2694b8f9.PNG)
![Captura3](https://user-images.githubusercontent.com/39989886/109835501-8ae74f00-7c43-11eb-912a-5fc48245047b.PNG)

I've tested de camera and I think the camera of pedestrians is far away from it. (Picture 1 and Picture 2)
Picture 3 It would be better if the camera position was 90 degrees overt to the pedestrian. This way we could better see the animations in silhouette. The current position doesn't help us.
