### ISSUE TITLE
I want to know how to many client can request to carla simulator at a time.

### ISSUE THREAD

**Issue by omkarshinde22** [carla-simulator/carla#3905]
Since carla is server-client architecture. I want to run carla simulator on different machine and request with that machine IP address from different machine. I want to know how many client requests carla simulator can handle at a time without fail.

Thanks

**Comment by Axel1092** [comment]
Hi @omkarshinde22, we have no internal limit to the amount of clients that CARLA supports so it will depend on your hardware and network. Please let us know if you find issues with a large amount of clients.
