### ISSUE TITLE
[CARLA_0.9.5] [Windows 10], BSOD follows when the agent appears on the map

### ISSUE THREAD

**Issue by Villiamos** [carla-simulator/carla#3908]
Hello I was following sendex tutorial https://www.youtube.com/watch?v=MynOPIJi4VY&feature=emb_title&ab_channel=sentdex and when I was running my own model using Carl's API, BSOD followed when the agent appeared on the map.

Link to script which I used
https://github.com/Villiamos/Carla-Api-Tensorflow 

**Software:**
Windows 10
Python 3.7
Tensorflow 2.4.1
CUDA 11.2
 cuDNN v8.0.5

**Hardware:**
GTX 760 4gb
i7-4790K

**Comment by corkyw10** [comment]
@bernatx could you follow up on this please?

**Comment by Villiamos** [comment]
Problem solved my cpu has to high temperature so I had to change CPU cooling
