### ISSUE TITLE
Is there a sampling resolution parameter in get_spawn_points()  function. Because I want to get more spawn-point in one road.

### ISSUE THREAD

**Issue by Zhuweilong123** [carla-simulator/carla#3909]
For generate_waypoints() funcation, there is a "distance " parameter can be used to adjust the number of waypoint. If the get_spawn_points()  function has the same parameter, it will be very useful.

**Comment by jackbart94** [comment]
Spawn points are fixed for each Town, and manually placed. You can get the list of spawn points and generate new ones in nearby locations, or create them yourself in Unreal. There are different ways to do this, but no sampling resolution parameter is available, sorry.

**Comment by Zhuweilong123** [comment]
@jackbart94 
Thanks for your reply! I will try those methods you mentioned.
