### ISSUE TITLE
Time out and connection problem when running benchmark example

### ISSUE THREAD

**Issue by Liangsyl** [carla-simulator/carla#391]
Hi, i am using CarlaUE4 which is built on Windows 10 environment.
And now, i am tring to follow the direction "Connecting a Python client".
I am using VS2015 x64 native tools command prompt to run the client example, and I can start running the autopilot example, but after it run a while, time out error occured, and the prompt showed that the distance host forced closing a existing connection.
After a while, a new episode started itself, and it did not run too long, the time out error occured agian.
![timeout](https://user-images.githubusercontent.com/26993983/39561291-58580c92-4ed7-11e8-93e4-a2e773637ef7.JPG)

![1](https://user-images.githubusercontent.com/26993983/39561299-61af9ff8-4ed7-11e8-832e-595423064873.JPG)
 
It never autopilot successfully.
Do you have any suggestions or way to solve this problem?

**Comment by Liangsyl** [comment]
hi，@marcgpuig.I am using CarlaUE4 0.8 which is built on Windows 10 environment.
I am tring ro run driving_benchmark_example.py. I opened _$./CarlaUE4.exe -carla-server_ at first, then, i opened _$./driving_benchmark_example.py_.
However, time out problem occured all the time, and it never connected sussesfully. 
And I tried to run _$./client_example.py --autopilot_, it can connected sussesfully.
What can i do to solve this problem? 
<img width="930" alt="1" src="https://user-images.githubusercontent.com/26993983/39693085-669e2de0-5215-11e8-8b4a-16cd946d51a8.png">

**Comment by felipecode** [comment]
@marcgpuig  @juaxix 
Can someone reproduce this in a windows system ?

**Comment by juaxix** [comment]
Hello all. @Liangsyl  i think there is a problem with the connection, looking to the errors: 10054,  10061...have you allowed the .exe files in your firewall?, have you tried using a different port instead of 2000? ([CarlaSettings.ini](https://github.com/carla-simulator/carla/blob/master/Docs/Example.CarlaSettings.ini#L16)) ,maybe you have this port used by other software.
