### ISSUE TITLE
set_hybrid_physics_radius instead of set_hybrid_mode_radius

### ISSUE THREAD

**Issue by i14d4** [carla-simulator/carla#3926]
Hello CARLA team,

I just wanted to report the following mismatch between documentation and code (CARLA 0.9.11):
in the Python API documentation _set_hybrid_mode_radius_ is listed as the function to change the hybrid mode radius of the traffic manager. 
Within the real Python API (TrafficManager.cpp) the function is called "set_hybrid_physics_radius".

Thanks in advance and kind regards

**Comment by corkyw10** [comment]
@i14d4 Thanks for pointing that out, I will update the documentation
