### ISSUE TITLE
New vehicle Manual control Error

### ISSUE THREAD

**Issue by parth3153** [carla-simulator/carla#3931]
![IMG_20210227_144649](https://user-images.githubusercontent.com/56869308/109389043-e8f5f880-790a-11eb-8f2e-be2c4543fedc.jpg)

When I run my python API to launch my new vehicle it crashes and shoes this error, and it's the same for normal manual control

**Comment by sagar-g-v** [comment]
Hi @parth3153 . This is because of the name used to filter is not matching
you can check the full name or starting string and aslo make sure you have added your vehicle in VehicleFactory blueprint

**Comment by Axel1092** [comment]
It is as @sagar-g-v says. Here is the list of vehicles in case you are having problems to find it https://carla.readthedocs.io/en/latest/bp_library/
