### ISSUE TITLE
How to achieve the effect?

### ISSUE THREAD

**Issue by guohaojie192** [carla-simulator/carla#3934]
[https://www.youtube.com/watch?v=eCWeU0RnnGg](url)
 I saw a video on YouTube which seem using CARLA Simulator, I want to ask how to achieve the effect in the video that all vehicles shuttle each other smoothly. Thanks!

**Comment by germanros1987** [comment]
You should ask the author. Perhaps it is just playing prerecorded trajectories. The vehicles don't seem to be using any physics.
