### ISSUE TITLE
Carla cannot run on a headless ubuntu server

### ISSUE THREAD

**Issue by zxqzhang** [carla-simulator/carla#3943]
Hi,
I have rented a ubuntu server that cannot use docker,  so I installed Carla following the official guidelines. After installing it and setting the environment variable SDL_VIDEODRIVER=offscreen, the carla simulator still doesn't run, and the output shows
 
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.

Please help.

**Comment by PTorr** [comment]
Try:
env SDL_VIDEODRIVER=offscreen bash -x /home/carla/CarlaUE4.sh -carla-server -world-port=2000 -opengl -quality-level=Epic -NOSOUND

**Comment by grazvydas** [comment]
We had similar problem with our Ubuntu server. 
Can you run `nvidia-smi ` inside container and show the output? If GPU is available and has proper drivers, then run `ldconfig -p | grep -E 'nvidia|cuda'`  and print the output.
 You may need to install something like `libnvidia-gl-{NVIDIA_DRIVER_VERSION` in your docker image.

**Comment by PTorr** [comment]
Additionally, I think that what you are getting is just a warning.
My server has the same output and it runs just fine.
