### ISSUE TITLE
XODR into Carla Simulator

### ISSUE THREAD

**Issue by alroar912** [carla-simulator/carla#3946]
Hi,
I'm have a map in a .xodr extension, I'm trying my best to upload it to Carla Simulator but end up in some problems such as:
ModuleNotFoundError: No module named 'carla'
When copying the folder into de \PythonAPI\util, I have this messsage:
AttributeError: module 'carla' has no attribute 'Client'
I'm getting all these messages by following the guide: https://carla.readthedocs.io/en/latest/adv_opendrive/
and the youtube video: https://www.youtube.com/watch?v=U25GhofVV1Q
Official information from Carla Simulator, can please somebody share their experience or help me solve this problem?
Thank you in advance

**Comment by kanakab** [comment]
Hi,

I believe this issue is due to different versions of Python. Check out the version of python required using the egg file of the Carla installed and check the default version of python you are using. Once you change this it should work.
