### ISSUE TITLE
How to adjust the position of 'fbx' network in CARLA : co-simulation between CARLA and SUMO.

### ISSUE THREAD

**Issue by EchoYJJ** [carla-simulator/carla#3949]
Hi, I meet some problems in the co-simulation between CARLA and SUMO.
I use Roadrunner to create the **fbx** file and import it to CARLA at the default position "0,0,0"
However, for some reasons, my **net** file in SUMO doesn't center "0,0,0". In other words, the 'convBoundary' in 'location' isn't "0.00,0.00,X,X" which states in the examples. As a result, my cars and network are in different position.
![image](https://user-images.githubusercontent.com/75726020/109953170-aa04e000-7d1a-11eb-90a5-631c311305bb.png)

So, I was wondering if the position of **fbx** file I import to CARLA can be changed from default "0,0,0" to others.

I've try to move  coordinate axis like below, but no position changes occur to my network and cars.
![image](https://user-images.githubusercontent.com/75726020/109952521-e3891b80-7d19-11eb-9611-f1621f0fb88f.png)

If you have some insights about how to adjust the position of network in CARLA, please give me some advises. Thank you in advance.

**Comment by corkyw10** [comment]
@XGodina could you have a look at this please?
