### ISSUE TITLE
Spawn_Objects

### ISSUE THREAD

**Issue by LuigiRu** [carla-simulator/carla#3950]
Hi everyone, 
I am using Carla 9.10 and the latest ros-bridge on Ubuntu Melodic 18.04. I am struggling to understand how does the carla_spawn_objects (carla_ros_bridge) works. More in detail I have the following problem: 

I want to add more vehicles (ego_vehicle, hero, hero01, etc...) in the simulation, by adding the vehicles in a objects.json file. At first I would like to spawn all the vehicles in random positions and then respawn the hero, hero01,... vehicles in front of the ego_vehicle. From [here](https://github.com/carla-simulator/ros-bridge/tree/master/carla_spawn_objects) I have read that it is possible to respawn the vehicles by publishing the new Pose on `/carla/<ROLE NAME>/<CONTROLLER_ID>/initialpose` topic. However if I do a `rostopic list`, I can only see that there is /initialpose topic (and I was expecting something like /carla/hero/control/initialpose). I think that /initialpose refers to the ego_vehicle, and not to the hero vehicles. Therefore, I am only able to respawn the ego vehicle, but not the heros. 
Any suggestion on how to solve this problem?

**Comment by corkyw10** [comment]
Hi @LuigiRu Have you attached the `actor.pseudo.control` pseudo-actor (with id `<CONTROLLER_ID`>) to the vehicles you want to respawn? There's an [example](https://github.com/carla-simulator/ros-bridge/blob/master/carla_spawn_objects/config/objects.json#L163) in the objects.json file if not.
