### ISSUE TITLE
Trying to learn more about Carla

### ISSUE THREAD

**Issue by bijayaniSMishra** [carla-simulator/carla#3958]
Hi Team, 

I am trying to build an autonomous taxi using the Carla Simulator as part of my college project.
I want to know, Is it possible to fetch the distance traveled by Car and set the source and destination for a car through an external API? 

Thanks

**Comment by jackbart94** [comment]
Check ``automatic_control.py`` and its related scripts. We don't have documentation about this, but there will soon be.
