### ISSUE TITLE
Windows .. Cannot change map

### ISSUE THREAD

**Issue by b-safwat** [carla-simulator/carla#3959]
No matter which map I pass in the arguments, I always get the same map
`CarlaUE4.exe "HDMaps/Town01.pcd"`
I even tried passing full map path but no luck.

![image](https://user-images.githubusercontent.com/33165067/110213524-21687a00-7ea9-11eb-8f9a-45f5016acaad.png)

**Comment by corkyw10** [comment]
@b-safwat Change the map after you have started CARLA by running the following command using the `PythonAPI/util/config.py` script:
`./config.py --map Town05`

The command line options are found [here](https://carla.readthedocs.io/en/latest/start_quickstart/#command-line-options).

You can also change the map in a script using the method `load_world()` from the [carla.Client](https://carla.readthedocs.io/en/latest/python_api/#carlaclient) class.
