### ISSUE TITLE
Carla rosbridge manual.py doesn't publishes control commands in autopilot mode

### ISSUE THREAD

**Issue by ImtiazUlHassan** [carla-simulator/carla#3965]
I'm trying to record the control commands i.e steer and throttle using Carla-Ros bridge. But when i launch Carla Ros bridge with ego vehicle example.Control commands are publish when  i drive manually. But when i set the auto-pilot on it no data is published on the topic.

when i set auto pilot off

![gifgit](https://user-images.githubusercontent.com/56826204/110431733-2df0fc00-807c-11eb-844d-60e8d23de9e8.png)

when i set auto pilot on

![bbbb](https://user-images.githubusercontent.com/56826204/110431795-4234f900-807c-11eb-83cd-eedcd4756489.png)

is there a way i can publish command in auto pilot mode ?

**Comment by joel-mb** [comment]
Hi @ImtiazUlHassan, actually this is the normal behaviour. When enabling the autopilot, the vehicle is controlled internally by the traffic manager so the vehicle commands are not published by the ROS bridge.
If you want to access that information you will have to publish it manually. Using the CARLA Python API you can get the last applied control via the `get_control` getter (https://carla.readthedocs.io/en/latest/python_api/#getters_16). **Take into account that the command you get is the one applied in the last frame.** There is no way to know the command that will be applied in the current frame without accessing the traffic manager code.

**Comment by ImtiazUlHassan** [comment]
> Hi @ImtiazUlHassan, actually this is the normal behaviour. When enabling the autopilot, the vehicle is controlled internally by the traffic manager so the vehicle commands are not published by the ROS bridge.
> If you want to access that information you will have to publish it manually. Using the CARLA Python API you can get the last applied control via the `get_control` getter (https://carla.readthedocs.io/en/latest/python_api/#getters_16). **Take into account that the command you get is the one applied in the last frame.** There is no way to know the command that will be applied in the current frame without accessing the traffic manager code.

I have figured it out. When we launch carla_ros_bridge_with_example_ego_vehicle it publishes a topic named ego_vehicle status. And in that topic there are all information available including throttle , steer , velocity etc
