### ISSUE TITLE
Can I use .umap made by Unrela in CARLA? (without xodr, osm, pcd)

### ISSUE THREAD

**Issue by peacekim86** [carla-simulator/carla#3969]
Hi, I'm PeaceKim.
I made an Map(environment) by Unreal.
It is a simply map consisting of batchs of .fbx.
The extensions of Map is .umap.

I want to use this as a map in CARLA.
If you can load it, Please let me know how.
Thank you.

**Comment by corkyw10** [comment]
Hi @peacekim86 you can find the tutorial on how to import maps in carla [here](https://carla.readthedocs.io/en/latest/tuto_A_add_map/)

**Comment by prateekstark** [comment]
Hi, did someone find any solution to this question?
