### ISSUE TITLE
Model modifications during running simulations

### ISSUE THREAD

**Issue by hiry27** [carla-simulator/carla#3970]
<
Hi, 
I'm Hiry
I wanted to know whether Carla allows obstacles to be spawned during a running simulation.
Thank you for your comments

**Comment by corkyw10** [comment]
Hi @hiry27 you can spawn anything from the [Blueprint library](https://carla.readthedocs.io/en/latest/bp_library/) during a simulation with the [spawn_actor()](https://carla.readthedocs.io/en/latest/python_api/#carla.World.spawn_actor) method.
