### ISSUE TITLE
Error when trying make package in Docker

### ISSUE THREAD

**Issue by siraphopp** [carla-simulator/carla#3974]
I try to do map ingestion in a CARLA package, and I followed this instruction [https://github.com/carla-simulator/carla/tree/master/Util/Docker](url) .

When I run this command "docker build -t carla -f Carla.Dockerfile ." I got this error

...
  LogTexture: Display: Building textures: T_FreewayLights01_op (AutoDXT, 2048X2048)
  LogTexture: Display: Building textures: T_v3Skin_SSS (AutoDXT, 8192X8192)
  LogShaderCompilers: Display: Worker (7/9): shaders left to compile 8489
  LogShaderCompilers: Display: Worker (3/9): shaders left to compile 8479
  LogShaderCompilers: Display: Worker (2/9): shaders left to compile 8469
  LogTexture: Display: Building textures: T_v3Skin__orm (AutoDXT, 8192X8192)
  LogTexture: Display: Building textures: T_v3Skin_c (AutoDXT, 8192X8192)
  LogTexture: Display: Building textures: T_FreewayLights01_orm (DXT1, 2048X2048)
Took 1207.721674s to run UE4Editor, ExitCode=137
ERROR: Cook failed.
       (see /home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt for full exception trace)
AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
RunUAT ERROR: AutomationTool was unable to run successfully.
Util/BuildTools/Linux.mk:16: recipe for target 'package' failed
make: *** [package] Error 25
The command '/bin/sh -c cd /home/ue4 &&   if [ -z ${GIT_BRANCH+x} ]; then git clone --depth 1 https://github.com/carla-simulator/carla.git;   else git clone --depth 1 --branch $GIT_BRANCH https://github.com/carla-simulator/carla.git; fi &&   cd /home/ue4/carla &&   ./Update.sh &&   make CarlaUE4Editor &&   make PythonAPI &&   make build.utils &&   make package &&   rm -r /home/ue4/carla/Dist' returned a non-zero code: 2

I think this error came from make package command in Carla.Dockerfile.

My OS is Ubuntu 18.04

**Comment by corkyw10** [comment]
@bernatx could you follow up on this please?
