### ISSUE TITLE
Augmenting icons to windshield & creating Heads-up Display

### ISSUE THREAD

**Issue by erfpak7** [carla-simulator/carla#3976]
I would like to create a heads-up display by augmenting some of the captured information to the windshield (similar to attached pic). CARLA is already showing HUD on the left hand side but is not showing it on the driver's view and it's quite far from the reality. So I was wondering whether there's a way that we could project those information (velocity, distance to obstacle, etc.) to the windshield and add some appealing icons to it?

![Augment_Headsup](https://user-images.githubusercontent.com/16671325/110800134-e5873900-8249-11eb-979c-a04ee6298ee2.png)

**Comment by erfpak7** [comment]
Is there any update on this? Has anybody ever created such a heads-up feature?

**Comment by XGodina** [comment]
Hi @erfpak7,
I know that UE4 provides some tools to customize your HUD. I advise you to start to familiarize yourself with that tools and later create a BluePrint to connect Hud with the information that you want.

**Comment by erfpak7** [comment]
Hi @XGodina,
Thanks for your recommendation. Sure thing, I'll work on it ;)

**Comment by XGodina** [comment]
Hi @erfpak7,

Any progress ?. I interested in that.

**Comment by Mikooman** [comment]
Hey everyone, 
anyone ever implemented a custom hud like mentioned in the original question? 
I would also be interested in it.
