### ISSUE TITLE
Pythonclient files throwing errors, -  orig_path.sort(key=position_in_sys_path) AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by zeroenergyhere** [carla-simulator/carla#398]

**Comment by uoyevoli** [comment]
hi  i have the same problem , how do you fix it ? thanks for your replying

**Comment by M-Hammod** [comment]
pythonClient code is for carla 0.8x if you are using carla 0.9 PythonAPI is what you may try to run.

**Comment by uoyevoli** [comment]
Thank you for your replying, i have solved the problem using suggestions from stackoverflow website.


Best Regards
James.C

M-Hammod <notifications@github.com>编写：


pythonClient code is for carla 0.8x if you are using carla 0.9 PythonAPI is what you may try to run.
