### ISSUE TITLE
How to add trees in batch in CarlaUE4?

### ISSUE THREAD

**Issue by EchoYJJ** [carla-simulator/carla#3981]
Hi! I'm new to CarlaUE4 and not familiar with the basic operation.
I can only add trees one by one. If you  know how to add trees in batch or where to find the guidance, please give me advises.
Thanks in advance.
![image](https://user-images.githubusercontent.com/75726020/111017257-3e430700-83ed-11eb-8197-c46a2442a731.png)

**Comment by XGodina** [comment]
Hi @EchoYJJ 

In UE4 you can select the Option of Foliage. In there, there are some options that you can play and deploy many trees really easily.
![image](https://user-images.githubusercontent.com/39989886/111171526-4d6cb500-85a5-11eb-9e6d-9d698ff2ce0a.png)

**Comment by EchoYJJ** [comment]
Hi! @XGodina 
Thanks a lot for your inspiration, and sorry for replying so late.
Except for the instrutions in UE4, I also learn from _https://www.youtube.com/watch?v=XYYfIYDqsDA_.
Two questions still confusing me, hope to receive your advices.

1.As a result of my fbx scene imported from Roadrunner not created in CARLA, the paint tool only shows up on what I create in CARLA(i.e. the buliding I drug from CARLA)
![image](https://user-images.githubusercontent.com/75726020/112712597-b5a78900-8f0b-11eb-924c-1e3270be2042.png)
I'm wondering maybe I should add a invisible horizontal plain at z=0 to provide adding space.

2.The Foilage-paint tool seems to focus on the range, but I hope to paint the trees in stright line with fixed gap as is shown in Town 0X.
![22bf49b9b139b5e745367d87c2a73c2](https://user-images.githubusercontent.com/75726020/112712757-3e262980-8f0c-11eb-892c-ac43f8ef0410.png)

Hope to receive your views, thanks in advance!
