### ISSUE TITLE
XIO:  fatal IO error 13 (Permission denied) on X server ":0"

### ISSUE THREAD

**Issue by abirbensoltane** [carla-simulator/carla#3999]
Hello! I have a problem while trying to launch the server . 
I tried 0.9.9.4 and 0.9.11 both give the same error 

$  ./CarlaUE4.sh
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
XIO:  fatal IO error 13 (Permission denied) on X server ":0"
      after 341 requests (339 known processed) with 26 events remaining.
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Signal 6 caught.

**Comment by abirbensoltane** [comment]
The cause of this problem is Nvidia driver because I have two graphic cards.Most of people have some issue with nvidia drivers under linux. This is frustrating . I can't open Xserver as a simple user under linux and I can't run ./CarlaUE4.sh as root as well so I switched to windows but I wish I could find a solution.

**Comment by Axel1092** [comment]
@abirbensoltane, this looks indeed a driver issue. Make sure that your discrete GPU has sufficient memory (we recommend 6GB although 4GB should work most of the time). You need to make sure to use that GPU and not the small one.

**Comment by abirbensoltane** [comment]
> @abirbensoltane, this looks indeed a driver issue. Make sure that your discrete GPU has sufficient memory (we recommend 6GB although 4GB should work most of the time). You need to make sure to use that GPU and not the small one.
Well I have GTX1650ti with 4 GO and the other one is amd but when I use the GTX  only the screen becomes dark that's why I think it's prob of driver

**Comment by abirbensoltane** [comment]
> @Axel1092  I've finally managed to solve the prob after installing the latest update of nvidia drivers today. But carla doesn't launch the whole pc freeze when I launch it
