### ISSUE TITLE
Closed parking lot in town10HD

### ISSUE THREAD

**Issue by PyTorr** [carla-simulator/carla#4002]
Hi,
Is there a way to go inside the closed parking lot in town10HD.

![image](https://user-images.githubusercontent.com/8789891/111903600-cbb8d380-8a4b-11eb-9632-715fd6d5eb2a.png)

**Comment by Madecu** [comment]
Hi @PyTorr ,

Those places weren't meant to be accessible, but if you want you can go to the unreal project and delete the barriers.

**Comment by PyTorr** [comment]
Thanks.
If I will be able to open CARLA in Unreal ever, I will do it.
