### ISSUE TITLE
Absolute determinism for apply_control

### ISSUE THREAD

**Issue by Stephanehk** [carla-simulator/carla#4004]
I have noticed that Carla.Vehicle.apply_control and world.spawn_actor is not completely deterministic (even in Carla 9.11). For example, in synchronous mode, I run

`Vehicle.apply_control(carla.VehicleControl(throttle=0.5, steer=0,brake=0))`

For my first run I get the velocity vector/spawn coordinates
timestep 1: 
'agent_x': [88.61997985839844], 'agent_y': [275.4779052734375], 'agent_z': [0.0015703010139986873]
'velocity_x': [2.9633368e-08], 'velocity_y': [-5.812376e-10]

timestep 2:
'agent_x': [88.61997985839844], 'agent_y': [275.4779052734375], 'agent_z': [0.0014941215049475431]
'velocity_x': [1.1473212e-08], 'velocity_y': [1.2927589e-09]

For my second run I get
timestep 1: 
'agent_x': [88.61997985839844], 'agent_y': [275.4779052734375], 'agent_z': [0.001629047328606248]
'velocity_x': [1.93825e-09], 'velocity_y': [6.7664435e-10]

timestep 2: 
'agent_x': [88.61997985839844], 'agent_y': [275.4779052734375], 'agent_z': [0.0015344810672104359]
'velocity_x': [-3.19796e-08], 'velocity_y': [2.3540284e-08]

For each run, the vehicle is spawned at the same position, but for some reason at different z coordinates. I am using a frame rate of 10hz, have set the weather to `carla.WeatherParameters.ClearNoon` with the same vehicle (model 3), the same map (Town 01), and reload the map every run. 

Does Carla currently support absolute determinism for apply_control, or does this lie in the physics engine?

Note: I am using Vehicle.get_velocity() to read the velocity values.

**Comment by Jk7913** [comment]
Hi @Stephanehk , I know it is an old issue, but still... what was your conclusion on this issue? I'm also experiencing similar problems with determinism, when applying control. The thing i found out that usually takes longer for the vehicle to respond to applied control only the first time after the spawning. I think it has to do something with physics engine, as well as some other issue which I'm trying to figure it out. 

Thanks
