### ISSUE TITLE
Gyroscope angular_velocity has opposite sign

### ISSUE THREAD

**Issue by jarvis-huang** [carla-simulator/carla#4008]
I am running a simulation on a right curve (see below image). Since the orientation of the IMU is X: forward, Y: left, Z: up, the angular velocity should have **negative z-component**, based on right-hand rule. However, I am getting positive. Am I missing anything here?

![imu](https://user-images.githubusercontent.com/13390566/112105517-bd60d980-8b69-11eb-983d-1db4eaf46cf5.png)

Version: Carla 0.9.8
OS: Ubuntu 18.04

I appreciate any input.

**Comment by corkyw10** [comment]
Hi @jarvis-huang CARLA uses left-hand rule

**Comment by jarvis-huang** [comment]
Thank you @corkyw10 
Just for reference, #1012 gives details about CARLA axes.
