### ISSUE TITLE
Car light brightness

### ISSUE THREAD

**Issue by TimLued** [carla-simulator/carla#4009]
Hello,

does Carla 0.9.11 support the increase of car light brightness? or of the illuminated area?
The following picture shows the cyber truck model with light_state = vls.Position | vls.LowBeam | vls.HighBeam

![carla_carlights](https://user-images.githubusercontent.com/50456467/112119386-9df39c00-8bbd-11eb-9f87-8eba15a8d139.jpg)

Best regards

**Comment by Madecu** [comment]
Hi @TimLued,

Unfortunately through API you can only turn the vehicle lights on and off. 
We are improving our vehicle gallery and we will implement the intensity and color customization in the future. We want them to work as streetlights and buildings do.

For now, you can edit the vehicle blueprint and change the intensity and attenuation radius for each vehicle.

![image](https://user-images.githubusercontent.com/54811869/112160018-0a849000-8bea-11eb-8054-21b0841e08c8.png)

**Comment by TimLued** [comment]
Thank you @Madecu !
