### ISSUE TITLE
How to make ego-vehicle invisible?

### ISSUE THREAD

**Issue by foamliu** [carla-simulator/carla#4020]
The front of the car takes up too much space.

You need:
![image](https://user-images.githubusercontent.com/14009435/112450134-05ad1100-8d8f-11eb-9ee4-5d9821451ad2.png)

You get:
![image](https://user-images.githubusercontent.com/14009435/112450235-237a7600-8d8f-11eb-9223-e46f82d31291.png)

**Comment by jackbart94** [comment]
You could move the camera upwards a bit and the result would be the same as in the picture above. Do you need help with that? The issue isn't very clear.

**Comment by foamliu** [comment]
Thanks @jackbart94 ，I moved the camera to new position (2.5, 0,1), in front of the car, now it is better. I was worried about the impact but seems it is under control.
