### ISSUE TITLE
Map's x and y coordinates.

### ISSUE THREAD

**Issue by cinjon** [carla-simulator/carla#4025]
Is there any guidance as to what are the maximum x and y coordinates in a map? I'd like to use this to normalize input to the model.

**Comment by corkyw10** [comment]
@cinjon I can see this question has been asked in the [forum](https://forum.carla.org/t/maps-x-and-y-coordinates/871/2) but you still need some information. I will close this issue after assigning to @XGodina for follow up in the forum.
