### ISSUE TITLE
How to run faster when importing fbx(by Roadrunner) to CARLA

### ISSUE THREAD

**Issue by EchoYJJ** [carla-simulator/carla#4030]
Hi! I use Roadrunner to generate the detailed 3D secne (fbx file).
![1616810189(1)](https://user-images.githubusercontent.com/75726020/112707060-65b4cc00-8ee3-11eb-8265-b064c9d62271.jpg)

However, when I export it to CARLA, about 6600 files needs to be imported(mainly road barriers for my scene).
![image](https://user-images.githubusercontent.com/75726020/112707046-546bbf80-8ee3-11eb-8a8a-9b09d09b0eea.png)
I ran for nine hours and didn't finish it.
If you know how to run faster(even sacrifice some accuracy), please give me some advices, thanks in advance!

**Comment by EchoYJJ** [comment]
I've tried to simplify my scene, and increase the scale to 550. However, the importing process seems to be stuck in certain point.
![image](https://user-images.githubusercontent.com/75726020/112707571-6b141580-8ee7-11eb-89d1-5fc5dfead95f.png)
It took just a little time to 258/551, but stayed unchanged for a long time.

**Comment by corkyw10** [comment]
hi @EchoYJJ have a read of this [post](https://forum.carla.org/t/importing-maps-from-roadrunner-to-carla-on-linux/839/8) in the forum to see if it helps to explain more about the map import process and how to handle the limitations plus some future plans. Let us know if you have any follow up questions.

**Comment by EchoYJJ** [comment]
Hi @corkyw10, thanks a lot for your advice. It seems that the map import process of complex scene still remains to be a time consuming task. Maybe in UE4.25 or UE4.26, the situation could be better.

I also trird to generate much vegetation in Roadrunner, then over 10000 files need to be imported, which is very time consuming and meaningless. As an alternative, I simplify my Roadrunner scene to only roads and grass, while spawn the vegetation and props in CARLA through **Foliage** which is suggested by XGodina in issue 3981.
https://github.com/carla-simulator/carla/issues/3981
Apart from the problem of  "how to paint the trees in stright line" in 3981, the most confusing issue to me is how to control the speed of co-simulation between SUMO and CARLA.

If my scene is simple, the simulation time equals to real world time. However, when my scene gets more complex, the simulation speed slows down(1s in real life≈5s in simulation). I also notice that vegetation in CARLA are dynamic which is unnecessary for me.  Whether the simulation speed will rise, if I change the mode from dynamic to static. 
Also, if you know other methods to speed up the simulation, please give us your advice.
Many thanks!
