### ISSUE TITLE
import carla problem for carla 0.9.10-2 with ros-bridge 0.9.10-1

### ISSUE THREAD

**Issue by Sibi-ROS-coder** [carla-simulator/carla#4033]
well i did the same thing the import Carla problem pops can you be specific what to do for pythin2 as well I am new to carla

**Comment by corkyw10** [comment]
To use Python 2 with the ROS bridge 0.9.10.1 you need to use [CARLA 0.9.10.1](https://github.com/carla-simulator/carla/releases/tag/0.9.10.1) to get the Python 2 `.egg` file and then export the path to that file to your PYTHONPATH:

` export PYTHONPATH=$PYTHONPATH:<path/to/carla/>/PythonAPI/<your_egg_file>`
