### ISSUE TITLE
carla client(cpp) coredump at GetServerVersion

### ISSUE THREAD

**Issue by SimonLeeGit** [carla-simulator/carla#4034]
I found a coredump at GetServerVersion when i run carla client cpp. Anybody who can help me about this.

E0329 10:03:08.336635   197 init.cc:64]  *** Aborted at 1616983388 (unix time) try "date -d @1616983388" if you are using GNU date ***
E0329 10:03:08.337338   197 init.cc:64]  PC: @                0x0 (unknown)
E0329 10:03:08.337410   197 init.cc:64]  *** SIGABRT (@0x3e8000000c5) received by PID 197 (TID 0x7fd18665dec0) from PID 197; stack trace: ***
E0329 10:03:08.337901   197 init.cc:64]      @     0x7fd17b5f6390 (unknown)
E0329 10:03:08.338279   197 init.cc:64]      @     0x7fd1475c5428 gsignal
E0329 10:03:08.338637   197 init.cc:64]      @     0x7fd1475c702a abort
E0329 10:03:08.339210   197 init.cc:64]      @     0x7fd147f148ae (unknown)
E0329 10:03:08.339772   197 init.cc:64]      @     0x7fd147f204b6 (unknown)
E0329 10:03:08.340147   197 init.cc:64]      @     0x7fd147f20521 std::terminate()
E0329 10:03:08.340593   197 init.cc:64]      @     0x7fd147f20775 __cxa_throw
E0329 10:03:08.342126   197 init.cc:64]      @           0xc16065 carla::throw_exception<>()
E0329 10:03:08.364765   197 init.cc:64]      @           0xc31834 _ZN5carla6client6detail6Client5Pimpl7RawCallIJEEEDaRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEDpOT_
E0329 10:03:08.365857   197 init.cc:64]      @           0xc28b07 _ZN5carla6client6detail6Client5Pimpl11CallAndWaitINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJEEEDaRKSA_DpOT0_
E0329 10:03:08.374186   197 init.cc:64]      @           0xc231ca _ZN5carla6client6detail6Client16GetServerVersionB5cxx11Ev

**Comment by JimmysCheapJeep** [comment]
Hi,
we had this is the beginning, too.
Looks like the client establishment takes some time.
We simply added a timeout after creation, and no crashes appear any more.
client.SetTimeout(std::chrono::seconds(10));
