### ISSUE TITLE
Modification of pedestrian clothing

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#4035]
Ubuntu18.04
carla-0.9.11

I want to add a pattern or picture of my own choice to the clothes of pedestrians. How should I operate? Does it have any requirements for these patterns?

**Comment by corkyw10** [comment]
@XGodina could you have a look at this please?

**Comment by XGodina** [comment]
Hi @whuxhzhang,
Well, you can add patterns to our pedestrian. But Maybé @DnDare to illustrate better than me how to do it.
