### ISSUE TITLE
Sensor measurements not correct

### ISSUE THREAD

**Issue by zhaoshan2** [carla-simulator/carla#4036]
Hello,
I am trying to export the position of the waypoints of a trajectory to a .txt file then read these waypoints and follow them, so that we can have the same route every time. Meanwhile the sensor measurements(gnss, imu, lidar) and the vehicle status are recorded. When in the waypoint navigation mode:

the velocity (returned by `vehicle.get_velocity(`)) seems not correct. 
This is the plotting of the velocity
<img width="514" alt="Screenshot 2021-03-29 at 10 45 53" src="https://user-images.githubusercontent.com/63495473/112811081-fc1bf580-907b-11eb-999d-8071a4315575.png">

Could you help figure what the problem is?
BR,

**Comment by corkyw10** [comment]
Hi @zhaoshan2 thank you for the question. 

@jackbart94 are you able to have a look at this please?

**Comment by jackbart94** [comment]
Please, could you provide us the script you're using (or a similar one for the vehicle recording and plotting) and which version of CARLA you are currently working with?

**Comment by zhaoshan2** [comment]
> Please, could you provide us the script you're using (or a similar one for the vehicle recording and plotting) and which version of CARLA you are currently working with?
Carla Version: Release carla 0.9.11
This script is developed from the tutorial.py. I have simplified the function and it is able to record the vehicle status such as position, velocity and acceleration and stored in the txt file. The script can be found here
https://github.com/zhaoshan2/Carla_RR/blob/794049b734cb29e09dc57cf1b0fbff5090cadfa8/PythonAPI/examples/RECORD.py
To run the script, first you need to create a folder named '_out', the recorded file will be stored in this folder. From the results you could notice that the velocity in x and y direction are all 0 (except for the first few rows)
Thanks for your time and look forward to your reply!

**Comment by jackbart94** [comment]
From what I have been able to see by running and analyzing your script, I can tell that if you are using the vehicle navigation controlled by waypoints, you are not actually applying any control to the vehicle in terms of throttle, brake or steering. You are just teleporting it to the next waypoint, and this is why you can't see any velocity. Instead, if you activate the Traffic Manager, there's your velocity. 

My suggestion would be to use any of the agents in the ``automatic_control.py`` scripts and try to feed your waypoints to them, so you actually have something that moves according to your trajectory.

Let me know if I can help with anything else!

**Comment by zhaoshan2** [comment]
Thanks a lot for the interpretation!
