### ISSUE TITLE
change duration of light state in traffic junction

### ISSUE THREAD

**Issue by cyber-loop** [carla-simulator/carla#4039]
Hi

I simply load a map and run the ego vehicle using manual_control.py script with autopilot. The ego vehicle crosses the junction traffic signal. Currently the traffic light takes alot of time to set to green. I want to reduce the duration of traffic light state in the junction.

How can I change the duration of traffic light state. Is there any API which does this action.

I am using CARLA 0.9.11 on Fedora33

**Comment by cyber-loop** [comment]
I think with set_green_time, set_yellow_time and set_red_time I can change the traffic light duration for all the traffic lights in the map. Can anyone confirm that?

https://carla.readthedocs.io/en/latest/python_api/#carlatrafficlight

**Comment by PisanoCohen** [comment]
Hi, 

Did you manage to set the duration of each light states at a traffic light junction? I went through the docs and tried changing it directly through Python but is faced with some errors as shown below. Hope you can shed some light on this. 

![image](https://user-images.githubusercontent.com/73422033/171076625-311396c5-686a-41d4-806d-694ad7a83512.png)

I am using CARLA 0.9.12 on Windows 10. Python version 3.8.10

**Comment by soumya997** [comment]
Check out this answer https://github.com/carla-simulator/carla/issues/876#issuecomment-1328671885
