### ISSUE TITLE
Bug in CARLA sensor tutorial

### ISSUE THREAD

**Issue by NishanthARao** [carla-simulator/carla#4042]
Greetings.

I am trying to write a CARLA sensor plugin to obtain wheel odometry, but since I am relatively new to CARLA and Unreal API's, I thought I'll just try to implement the `SafeDistanceSensor` that the [CARLA Documentation](https://carla.readthedocs.io/en/latest/tuto_D_create_sensor/) provides. 

Unfortunately, when I run the last command `make rebuild`, I get the following error:
```make
In file included from ../../LibCarla/source/carla/sensor/s11n/SafeDistanceSerializer.cpp:9:
../../LibCarla/cmake/../source/carla/sensor/data/SafeDistanceEvent.h:20:9: error: no matching constructor for initialization of 'Array<rpc::ActorId>' (aka 'Array<unsigned int>')
      : Array<rpc::ActorId>(std::move(data)) {}
        ^                   ~~~~~~~~~~~~~~~
../../LibCarla/cmake/../source/carla/sensor/data/Array.h:23:9: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'typename std::remove_reference<RawData &>::type' (aka 'carla::sensor::RawData') to 'const carla::sensor::data::Array<unsigned int>' for 1st argument
  class Array : public SensorData {
        ^
../../LibCarla/cmake/../source/carla/sensor/data/Array.h:127:14: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
    explicit Array(RawData &&data, FuncT get_offset)
             ^
../../LibCarla/cmake/../source/carla/sensor/data/Array.h:136:14: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    explicit Array(size_t offset, RawData &&data)
             ^
1 error generated.
[85/118] Building CXX object LibCarla/...arla/streaming/detail/tcp/Client.cpp.o
ninja: build stopped: subcommand failed.
Util/BuildTools/Linux.mk:36: recipe for target 'rebuild' failed
make: *** [rebuild] Error 1
```

I haven't changed any of the codes, I have just used the exact same codes that they have provided [here](https://gist.github.com/nsubiron/011fd1b9767cd441b1d8467dc11e00f9).

Could someone please help me fix this issue? Thanks in advance!

**Comment by qhaas** [comment]
A few questions:
1. Are you using the latest tagged release of CARLA (e.g. 0.9.11)?  Using a tagged release instead of the head of master is typically more stable
2. Did you successfully build it without any code changes first (with a `make package`)?  This will ensure your build environment is setup properly with a 'known good' codebase.
3. Are you using the correct tagged release of UnrealEngine for the tagged CARLA release codebase you are working with (e.g. CARLA 0.9.11 requires UE 4.24.x).  Using the 'wrong' UE version can cause errors like this as the APIs change upstream... don't let the 'minor' number change fool you, there is a significant difference between UE 4.24.x and 4.26.x

**Comment by NishanthARao** [comment]
@qhaas Hi, I am sorry, I forgot to mention the specifications

1. I am using 0.9.10 that is built from source on my system
2. Yes, I have built the code, and have run a lot of programs before. The simulation works flawlessly
3. I am using Unreal Engine 4.24 that is recommended for CARLA 0.9.10 

Could you please help me out? Thanks a lot!

**Comment by corkyw10** [comment]
@NishanthARao Thank you for the input.

@Axel1092 could you have a look at this please?

**Comment by ZhanYangFan** [comment]
Hi, I mission the same problem.are you has slove? please help me. very thank you
