### ISSUE TITLE
Carla version problems

### ISSUE THREAD

**Issue by Aarnnity** [carla-simulator/carla#4050]
Hi, I have a few questions to ask you.
1. As far as I know, the Carla 0.8.2 stable version does not have a vehicle lane change sensor, which is not available until version 0.9.x or higher, right?
2. If in the stable version of Carla 0.8.2, I set the scene to multi-lane. How should I add a vehicle (the vehicle included in the version) to a place in the multi-lane? At the same time, how to modify the attributes of these vehicles (for example: speed)? Do I need to compile after modification? Hope you can provide relevant information.
Thank you, and hope to hear from you!

**Comment by corkyw10** [comment]
@Aarnnity thank you for the question.

@bernatx could you follow up on this please?
