### ISSUE TITLE
Issue on CARLA 0.9.11 bulid on Windows.(fatal: repository 'https://github.com/EpicGames/UnrealEngine.git/' not found)

### ISSUE THREAD

**Issue by EchoYJJ** [carla-simulator/carla#4052]
Hi! I'm trying to build CARLA 0.9.11 on Windows.
I already link my GitHub account  to Unreal Engine's account.
![image](https://user-images.githubusercontent.com/75726020/113395976-4f1fe080-93cd-11eb-8dc5-4d2c66afb8bb.png)

However, when I run "git clone --depth=1 -b 4.24 https://github.com/EpicGames/UnrealEngine.git" and sign in my account like below.
![Uploading image.png…]()

I still receive the warning:
_PS F:\Unreal Engine> git clone --depth=1 -b 4.24 https://github.com/EpicGames/UnrealEngine.git
Cloning into 'UnrealEngine'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/EpicGames/UnrealEngine.git/' not found_

If you know how to solve this issue, please give me some advices, thanks in advance.

**Comment by EchoYJJ** [comment]
![image](https://user-images.githubusercontent.com/75726020/113396708-8c38a280-93ce-11eb-8497-da64d8e400d7.png)
I've found out the solution, must become a member of it.

**Comment by vibhoraggarwal** [comment]
For someone following this issue: There would be a link on the email id attached with the github profile with the link to become a member of the Epic Games community
