### ISSUE TITLE
make PythonAPI failure in Windows 10

### ISSUE THREAD

**Issue by huobinzy** [carla-simulator/carla#4059]
Hello!
Can anyone help me? I will be very grateful.
Question 1: why not use Windows SDK 8.1, instead of 10.0?
_The prompt is as follows:_
**-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.**

Question 2: what is ZLIB? It is missing. How can get it back?
_The prompt is as follows:_
**-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)**

Question 3: there may be something wrong with the CMake. How to fix it?
_The prompt is as follows:_
**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIBRARY
    linked by target "osm2odr" in directory C:/carla/Util/OSM2ODR/src**

Question 4: in fact, there is no folder "dependencies" and "lib" in my "c:\carla\PythonAPI\carla". Which step will build these two folder and inner files?
_The prompt is as follows:_
**FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'dependencies/lib'**

Question 5: finally, it shows me Carla lib has been successfully installed, but actually there is no "dist" folder or file in "c:\carla\PythonAPI\carla".
_The prompt is as follows:_
**-[BuildPythonAPI]: Carla lib for python has been successfully installed in "c:\carla\PythonAPI\carla\dist"!**

![捕获1](https://user-images.githubusercontent.com/43350717/113543295-a796ee00-9618-11eb-8362-341207aa5c42.PNG)
![捕获2](https://user-images.githubusercontent.com/43350717/113543306-acf43880-9618-11eb-8182-17da2b093111.PNG)

**Comment by corkyw10** [comment]
@bernatx could you follow up on this please?

**Comment by huobinzy** [comment]
> @bernatx could you follow up on this please?

Aha, thank you for conernatx could you follow up on this please?

Aha, thank you for con

**Comment by BuBleC** [comment]
@huobinzy Hello I currently have the same problem could you help me? I don't have a good understanding of GitHub so what does add fodler to repository and new commit mean?
