### ISSUE TITLE
Sensor minor change build (question)

### ISSUE THREAD

**Issue by yaadram** [carla-simulator/carla#4061]
[Carla 0.9.11 , Windows 10 , Python 3.7, Visual Studio 2017 ]

Hi All,
A short question : If **minor changes** are done in a specific sensor (Ray-cast Lidar's energy attenuation model for example),  Is a full rebuild of the Carla project required ? (make rebuild + make pythonAPI) or is there a way to only compile this sensor ?
![image](https://user-images.githubusercontent.com/29002095/113511626-64ca0d00-9569-11eb-8169-0f71f267ed02.png)

Thanks in advance,
Yaad G.

**Comment by Axel1092** [comment]
Hi @yaadram it depends on what part of the code you changed but usually code inside the Unreal folder is compiled with `make CarlaUE4Editor` or `make launch` if you work with the editor. For code inside the LibCarla folder you need to run `make PythonAPI` and `make launch` for it to take effect everywhere. Usually these commands will detect changes in the code and recompile only those files. The `make rebuild` command will recompile everything which works well for big changes and clean builds.
