### ISSUE TITLE
Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by naga-k** [carla-simulator/carla#4065]
Hey I'm trying to learn Carla and I am not able to install Carla on PIP. I tried using pip install carla, other commands to fetch carla and also used a venv. Got no where please help
![Screenshot (1)](https://user-images.githubusercontent.com/29381705/113766092-acec5980-973a-11eb-85c1-0b9d0a7c373c.png)

**Comment by corkyw10** [comment]
Hello @naga-k, you need to extract the `tar.gz` file. See [here](https://linuxize.com/post/how-to-extract-unzip-tar-gz-file/) for how to do that. Then follow the documentation [here](https://carla.readthedocs.io/en/0.9.5/getting_started/), assuming you are set on using the 0.9.5 version of CARLA.
