### ISSUE TITLE
object physical materials for scanning

### ISSUE THREAD

**Issue by NurbekHalikulov** [carla-simulator/carla#4069]
Hello! I am testing different sensor models from different manufacturers, including carla sensor models. Each sensor performs differently and its performance can be evaluated correctly if I know the type of physical materials in the environment. Lidar and radar sensor models  checks the returned signal characteristics based on object surface. My question is that: where I can get an information about the object materials in carla? I am testing now lidar sensor model from another manufacturer in the market and they have a list of materials (tree, steel, glass, plastic, concrete) with exact parameters ( roughness values, coefficients and constants) in the simulation. I want to evaluate the carla sensor model performance by comparing it with that another sensor model. In order to compare two different sensor models, I need to adjust same scenario with same materials. I am testing a lidar sensor model in Town04 in both simulation frameworks (another simulator is also built in UE4 game engine and support Town04 environment scenario). In order to compare the performance of both simulaor lidar sensor models, the only thing I should provide is the same materials parameters. 

Can someone help me on this issue?

**Comment by corkyw10** [comment]
Hello @NurbekHalikulov I am going to close this issue as I can see that it has been addressed in the Discord channel. Posting here for future interest:

"We use mostly PBR materials in UE4 , that means that material's parameters  are  found in their respective textures."
