### ISSUE TITLE
carla0.9.11 + carsim running problems

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#4070]
Ubuntu18.04
carla-0.9.11

I use carsim in carla-0.9.11：
self.player.enable_carsim("/home/zhangxinhong/CarSim_2020.0_Ubuntu_x86_64_128709_with_vsvisualizer/CarSim_2020.0/Example_Data/carla_sim.sim")
But I can't get the effect in the document：
![image](https://user-images.githubusercontent.com/38369239/113860019-22f2ce00-97d8-11eb-80b9-72ac66cece4e.png)

In addition, I want to know what method or interface is used by carla and carsim to transfer data described in the document：
![image](https://user-images.githubusercontent.com/38369239/113860506-b3311300-97d8-11eb-8fe8-33f1e9bd4739.png)

**Comment by FENGShuanglang** [comment]
你好，请问你是怎么在ubuntu中安装carsim的，是买的正版吗？

**Comment by panpan-77** [comment]
> 你好，请问你是怎么在ubuntu中安装carsim的，是买的正版吗？

Hi, I have the same problem. Have you solved it？

**Comment by whuxhzhang** [comment]
您好，


我是申请的试用版，申请成功会有操作文档，可以根据文档安装。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "carla-simulator/carla"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [carla-simulator/carla] carla0.9.11 + carsim running problems (#4070)





  
你好，请问你是怎么在ubuntu中安装carsim的，是买的正版吗？
  
Hi, I have the same problem. Have you solved it？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 263868161** [comment]
请问如何申请试用版？
