### ISSUE TITLE
Veloview for lidar data visualization

### ISSUE THREAD

**Issue by NurbekHalikulov** [carla-simulator/carla#4076]
Hello all,

Is it possible to visualize the lidar sensor data using VeloView (from Velodyne Lidar) tool?

Thanks

**Comment by DSantosO** [comment]
Hello @NurbekHalikulov,

Our lidar sensor has the method `save_to_disk` that saves the point cloud in `ply` format.
If VeloView does not support this format I see two options. One will be to convert his ply file to another format that VeloView recognoises. The other, and I think it can be better, is to write a callback for the lidar sensor in which you can get the data in raw format and write it to a file prepared to be read by VeloView.
