### ISSUE TITLE
Some parts are separated from the vehicle and are floating in the air

### ISSUE THREAD

**Issue by bpoebiapl** [carla-simulator/carla#4082]
I haven't yet been able to figure out exactly in which configuration bring ouit this issue.
I used synchronous mode and set the fixed delta seconds to 0.0005.
![23418](https://user-images.githubusercontent.com/18179088/114333850-41fcb180-9b84-11eb-8fd8-ea1f47ed7217.png)

**Comment by XGodina** [comment]
Hi @bpoebiapl,

Sorry, for the answer late.  Yes, we will check it and fix it for the next release. Thank you for notifying us.
@gsmario could you look into it.
