### ISSUE TITLE
mismatch between cpp and python

### ISSUE THREAD

**Issue by guygo12345** [carla-simulator/carla#4085]
Hey!

Running on carla docker 0.9.11.
When running the following code -
...
```
traffic_lights = world.get_actors().filter('traffic.traffic_light')
            for tl in traffic_lights:
                tl.set_state(carla.TrafficLightState.Green)
```
...
I'm getting this error - 
`tl.set_state(carla.libcarla.TrafficLightState.Green)
Boost.Python.ArgumentError: Python argument types in
    TrafficLight.set_state(TrafficLight, TrafficLightState)
did not match C++ signature:
    set_state(carla::client::TrafficLight {lvalue}, carla::rpc::TrafficLightState state)
`

Why would that happen? It seems like I'm using the function in the right way...

edit:
when I get the state from some get_state() output it does work.. just making the bug more odd..

Thanks for helping!

**Comment by guygo12345** [comment]
OK, I manged to get over the bug. It was something  about the way I imported carla.

**Comment by JasonBourne1998** [comment]
Hi @guygo12345 , could you please specify how to resolve this ?
