### ISSUE TITLE
Modifying existing Cars

### ISSUE THREAD

**Issue by jhermen-List** [carla-simulator/carla#4090]
Hi There, thanks a lot for the great work you are doing on Carla.

I found the documentation on how to create and add new vehicles, but is there a way to modify existing vehicles, like adding a lamp, replacing texture or similar smaller changes without redesigning a completely new car? 

Thanks a lot 
       Johannes

**Comment by onebitme** [comment]
Hi there,

For modifying mesh (e.g. you want to add a 3d model of a sensor to an already existing vehicle in Carla), simply export the vehicle in .fbx, import the file in blender, add 3d mesh (be sure that normals of the vertices are towards out) and then follow the guide.
For textures, google "how to change textures in UE4" will be sufficient for you :)
For more, simply check for the solutions which are not carla specific but for UE4.

Also, I might help if you can describe what you are trying to achieve in more detail :)

**Comment by jhermen-List** [comment]
Thanks a lot, that sound do-able! I wil ltry that.
The idea is to add a kind of signaling/lights to the front of the Car that can be triggered via the API.

i guess the VehicleLightState.Special vars can somehow be used for that.

**Comment by gsmario** [comment]
> Thanks a lot, that sound do-able! I wil ltry that.
> The idea is to add a kind of signaling/lights to the front of the Car that can be triggered via the API.
> 
> i guess the VehicleLightState.Special vars can somehow be used for that.

yeah you can add as many lights as you want, but remember to set also de lights in unreal engine. Rightnow our lights are controlled via API as well so you probably won't have any problem.

**Comment by jhermen-List** [comment]
> The idea is to add a kind of signaling/lights to the front of the Car that can be triggered via the API.
> i guess the VehicleLightState.Special vars can somehow be used for that.

So, i archived to modify the vehicle blueprint and add some meshes for the places where i want to show something. 
Now the question is how to exchange the material on this mesh via the VehicleLightState.Special vars to show one or another image on the front. Any hints for that?

![mod_vehicle](https://user-images.githubusercontent.com/60341011/126504153-8439d9e6-cbc4-407a-adc4-e84bab781a63.jpg)

Thanks a lot
       Johannes
