### ISSUE TITLE
Carla Performance Benchmarking 

### ISSUE THREAD

**Issue by Stephanehk** [carla-simulator/carla#4096]
I was wondering what settings were used to achieve the Carla benchmarking performance recorded in the table on the bottom of [this](https://carla.readthedocs.io/en/latest/adv_benchmarking/) page (ie: what sensors, map, weather, CARLA version, etc.). Also, it seems like the documentation on that page for the performance_benchmark.py script is a little out of date (at least for Carla 0.9.11).  I mainly ask this because the default settings described in the documentation are no longer the default settings in the benchmarking script.

**Comment by DSantosO** [comment]
Hello @Stephanehk,
The options and the results described on that page are related to the current version of the script present in the `dev` branch that incorporates a few improvements in relation to the version in the 0.9.11 release. You can take a look and download this script [here](https://github.com/carla-simulator/carla/blob/dev/PythonAPI/util/performance_benchmark.py). If you are interested, you should be able to use the 0.9.11 without a problem.
