### ISSUE TITLE
how to spawn multiple spectator

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/carla#4110]
I spawned multiple ego vehicles in one carla world through one carla client. And I wanted to check out every vehicles' state at the same time. But I found that the function CarlaDataProvider.get_world().get_spectator() only returned one spectator. Does anyone konw how can I use multiple spectators at the same time? Or I should spawn multiple cameras above each vehicles?

**Comment by glopezdiest** [comment]
Hey @nuomizai, as far as I know, the spectator is a camera which is the camera Unreal uses to show the scene, and there's only one. You can manually move and rotate it to your heart's content, which is definitely not something you can do with any other sensor.

If you want to show multiple ego vehicles, you are gonna have to create multiple cameras and render them using something like pygame (like the manual control does)

**Comment by nuomizai** [comment]
> Hey @nuomizai, as far as I know, the spectator is a camera which is the camera Unreal uses to show the scene, and there's only one. You can manually move and rotate it to your heart's content, which is definitely not something you can do with any other sensor.
> 
> If you want to show multiple ego vehicles, you are gonna have to create multiple cameras and render them using something like pygame (like the manual control does)

Thanks for your reply, @glopezdiest ! I've created multiple cameras as you suggested and use opencv-python to render them.

**Comment by SExpert12** [comment]
> I spawned multiple ego vehicles in one carla world through one carla client. And I wanted to check out every vehicles' state at the same time. But I found that the function CarlaDataProvider.get_world().get_spectator() only returned one spectator. Does anyone konw how can I use multiple spectators at the same time? Or I should spawn multiple cameras above each vehicles?

How did you spawn multiple vehicles? Can you please share your code. I want to spawn multiple vehicles with few distance apart and I am trying but not working.
