### ISSUE TITLE
Where can i find CarSimConfig.ini？

### ISSUE THREAD

**Issue by shanshan1405** [carla-simulator/carla#4117]
1> UnrealBuildTool : error : Unable to instantiate module 'Carla': System.IO.FileNotFoundException: 未能找到文件“D:\A_0collection\CARLA\Unreal\CarlaUE4\Config\CarSimConfig.ini”。

**Comment by todorovic1** [comment]
Hei, did you solve this issue? 

Error: Unable to instantiate module 'Carla': System.IO.FileNotFoundException: Could not find file 'C:\carla\Unreal\CarlaUE4\Config\CarSimConfig.ini'.
