### ISSUE TITLE
error：compiler/disable-ue4-macros.h

### ISSUE THREAD

**Issue by shanshan1405** [carla-simulator/carla#4118]
1>D:\A_0collection\CARLA\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Actor/ActorAttribute.h(9): fatal error C1083: 无法打开包括文件: “compiler/disable-ue4-macros.h”: No such file or directory

![捕获](https://user-images.githubusercontent.com/57471768/115528304-80047e80-a2c4-11eb-833c-9d67f745fa65.PNG)

**Comment by corkyw10** [comment]
Hi @shanshan1405, can you provide some more context please?
