### ISSUE TITLE
Pedestrian/Walker stopping at RED traffic signal

### ISSUE THREAD

**Issue by cyber-loop** [carla-simulator/carla#4125]
Hi all,

I want to know if there is way to control the pedestrian walking on the junction i.e. if traffic signal is red then pedestrian should stop crossing the road and when traffic signal is green then continue walking. Can someone point me out if there is any function for that in Python? Thanks

CL

**Comment by glopezdiest** [comment]
Hey @cyber-loop. There is not :slightly_frowning_face:, you'd have to implement it. If you are using the *WalkerAIController*, pedestrians will ignore traffic lights. You might be able to manage it using their *WalkerControl*, but it's not a trivial task.

**Comment by glopezdiest** [comment]
Seems solved, so closing the issue.

**Comment by bittuh** [comment]
> Seems solved, so closing the issue.

Hi Carla team,

I'm still looking for the way to enable a smarter walker control (e.g. stopping at red light) with carla 0.9.12,
could you provide more info about how this is solved?
