### ISSUE TITLE
Custom materials with xodr

### ISSUE THREAD

**Issue by NielsPichon** [carla-simulator/carla#4126]
Hi!
I am trying to build on top of the osm/xodr map loader to be able to train some AI agent with openScenarios which use the said xodr maps. However, my goal being to be able to navigate using vision as the primary source of information, I would need to improve on the graphics side of things.
After a bit of digging, it seems like when loading a xodr file with `generate_opendrive_world`, one of 2 materials is assigned, either "road" or "crosswalk" (in `MeshFactory::Generate` I believe).

But I am not sure where to go from here... Where are these materials defined? How could I add my own materials (possibly procedural), to add lane lines for instance or house textures on blocks I would spawn on the side of the road?

Thanks for the help,
Niels

**Comment by NielsPichon** [comment]
In the mean time I found this [AActor](https://github.com/carla-simulator/carla/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveGenerator.cpp). Am I right in assuming this is contained in the OpenDriveMap.umap and that this will generate a procedural mesh for the roads with no texture and default vertex color? 

This would mean that I could possibly add my textures in there for it to be loaded at runtime?

**Comment by algababr** [comment]
Hey Niels sorry for the late response, but we have been a bit busy lately preparing for the new release. Are you still looking into it?

**Comment by NielsPichon** [comment]
Hi Roel,
Yes this would still be of interest to me to be able to add custom materials to xodr maps. I haven't found the solution on my own just yet. Any clue?

**Comment by algababr** [comment]
When we use "make import" for importing maps into carla (along with the .xodr information), we specify the materials that are going to be applied through our [commandlet](https://github.com/carla-simulator/carla/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp) which derives from Unreal's commandlet. In the constructor we define those materials for the roads, the markings, sidewalks...That's how we modify anything imported into carla.

If you are using "generate_opendrive_world" separately from this process, I'll have to look into it. Let me know if this solution works for you :)

**Comment by algababr** [comment]
Hey Niels! Did you have the chance to test this out?

**Comment by NielsPichon** [comment]
Hi!
Yes it seems to have done the trick. Thanks for the help.

**Comment by NielsPichon** [comment]
Hi @brscholz. I am afraid I kind of gave up on this as I could not figure out a simple way to do it. Good luck
________________________________

**Comment by yaoweixiao-ux** [comment]
> 你好[@NielsPichon](https://github.com/NielsPichon)我也正在研究用 xodr 生成程序关卡。你最后是怎么做的？直接导入，提供 .xodr 文件，不用 .fbx 文件？

Hℹ I am also try using .xodr & .fbx to rebuild all map(with 3D picture) , did you solve this bug? or did you have any idea?
