### ISSUE TITLE
How to make a tunnel in CARLA?

### ISSUE THREAD

**Issue by EchoYJJ** [carla-simulator/carla#4131]
Hi! I'm trying to make a tunnel in CARLA as Town03 shows.
https://user-images.githubusercontent.com/75726020/115820632-cb896a80-a433-11eb-806c-bdd0599f67cd.MP4
I know in RoadRunner, the height of road can be adjusted to even negative value, but it's hard to adjust terrain in RoadRunner.

So, I turn to CARLA to use the assets in Town03 (e.g. SM_WallTunnel01, SM_ColumnTunnel). 
However, when I import fbx file from RoadRunner to CARLA, everything I created in RoadRunner will be seen as a whole fbx file (not Road_Road_XX in Town_0X), and it seems to be impossible for me to attach walls to roads precisely without any gap.
![image](https://user-images.githubusercontent.com/75726020/116038450-08579a80-a69c-11eb-8fbc-f2c5bed128cd.png)

So, I really wonder how tunnel in Town03 can be that perfect. If you know the reason, pls give me some advices, thanks!

**Comment by seuwcs** [comment]
good questions
