### ISSUE TITLE
Carla replay_file does not allow synchronous replay

### ISSUE THREAD

**Issue by egeonat** [carla-simulator/carla#4144]
Hello. I'm using Carla version 0.9.11 on Ubuntu to record a human driver, record their actions with the Carla logger, and then replay the recording with additional sensors following the tutorial at https://carla.readthedocs.io/en/latest/tuto_G_retrieve_data/

I need to use fixed time steps and synchronous mode to ensure the sensor data are all from the same time-step, with equal time between data samples. I have read the suggestions by @Axel1092 at https://github.com/carla-simulator/carla/issues/3624#issuecomment-800309256 regarding how to achieve this. However the `replay_file` function resets Carla to asynchronous mode when called, causing the simulation to proceed without waiting for a `world.tick()` command and making it impossible to collect data properly. Below is a minimal example that demonstrates the problem:

```
>>> import carla
>>> client = carla.Client("localhost", 2000)
>>> world = client.get_world()
>>> settings = world.get_settings()
>>> settings.synchronous_mode = True
>>> settings.fixed_delta_seconds = 1 / 20
>>> world.apply_settings(settings)
4697
>>> world.get_settings().synchronous_mode
True
>>> client.replay_file("/home/egeonat/projects/recordings/RouteScenario_0_rep0/recording.log", 0, 0, 0)
'Replaying File: /home/egeonat/projects/recordings/RouteScenario_0_rep0/recording.log
Loading map Town01
Replayer will start after map is loaded...
Total time recorded: 265.85
Replaying from 0 s - 265.85 s (265.85 s) at 1.0x\n'
>>> world.get_settings().synchronous_mode
False
```

This seems like a problem to me, especially since the documentation says synchronous mode with fixed time steps is recommended for replaying recordings: https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/ . Is this a bug with the simulator?

**Comment by Axel1092** [comment]
Hi @egeonat, sorry for taking so long to answer. I have investigated the issue and I think it only happens if you start replaying in a different map with respect to the one you want to replay. If you load the map beforehand with `client.load_world()` and then you run the `client.replay_file()` the settings shouldn't change.
