### ISSUE TITLE
coredump at client.GetWorld()

### ISSUE THREAD

**Issue by SimonLeeGit** [carla-simulator/carla#4147]
hi all,
    I found a coredump at client.GetWorld() when my carla client startup. All the details are below:

![lADPD26eO5w5cmrNC9DND8A_4032_3024](https://user-images.githubusercontent.com/11291381/116214800-a79e8f80-a779-11eb-9a49-362fcb1e2322.jpg)

**Comment by corkyw10** [comment]
Hi @SimonLeeGit, could you post the output of the error and the command you ran in text format here rather than a photo? What version of carla are you running?

**Comment by SimonLeeGit** [comment]
> Hi @SimonLeeGit, could you post the output of the error and the command you ran in text format here rather than a photo? What version of carla are you running?
