### ISSUE TITLE
when can I control npc cars ?

### ISSUE THREAD

**Issue by 18605973470** [carla-simulator/carla#415]
As mentioned in the title, it's very important for me to construct a specific scenario with npc cars controllable.
I noticed that this function is part of road map.
But I still want to know what time about its implementation or how it is going now ...

Thanks a lot   :)

**Comment by juaxix** [comment]
Hello @18605973470 we dont have an exact estimation of time, but right now we are designing this together with other systems directly connected to it.

**Comment by juaxix** [comment]
Take a look to this #145 and this #444
