### ISSUE TITLE
spawn walkers error with python exit code 139  (interrupted by signal 11: sigsegv)

### ISSUE THREAD

**Issue by lish0** [carla-simulator/carla#4155]
I tried to spawn walkers with spawn_npc.py, but found the process died at world.get_random_location_from_navigation(). Do I misconfigure something? I use python3.9.4 as interpreter.

**Comment by arihant2math** [comment]
Use python 3.7 instead, see #4087

**Comment by lish0** [comment]
> Use python 3.7 instead, see #4087 

Thanks for your reply. But I was able to install .egg file and import carla, In my carla workspace, vehicles can be successfully spawned while the pedestrian can't.

**Comment by arihant2math** [comment]
What is is run command, is it `python3 spawn_npc.py` (`python spawn_npc.py` for windows users)?

**Comment by corkyw10** [comment]
Hi @lish0, are you using a custom map or one of the CARLA maps? What version of CARLA are you using? What output do you get with `python3 spawn_npc.py -n 0 -w 10`?

**Comment by lish0** [comment]
> Hi @lish0, are you using a custom map or one of the CARLA maps? What version of CARLA are you using? What output do you get with `python3 spawn_npc.py -n 0 -w 10`?
> 
> 

Hi @corkyw10, I use official carla map, and the CARLA version is 0.9.11. When I try to spawn walkers, I get the only output is "python exit code 139  (interrupted by signal 11: sigsegv)", and   the UE4 editor gets stuck at the same time.
