### ISSUE TITLE
Lidar sensor is not considering ego-pitch&roll

### ISSUE THREAD

**Issue by wzhAptiv** [carla-simulator/carla#416]
Currently, the Lidar sensor is only considering the yaw of the ego-car, but not pitch or roll. 
Experiment can be easily conducted, by reading Lidar data points when the ego-car is turning. 
During turning, the car will have some roll degree, but the Lidar points is not showing this effect, while the ground points are still flat in the Lidar coordinates. 

I think this is a bug in `Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Lidar.cpp`

``` c++
  FVector LidarBodyLoc = GetActorLocation();
  FRotator LidarBodyRot = GetActorRotation();
  FRotator LaserRot (VerticalAngle, HorizontalAngle, 0);  // float InPitch, float InYaw, float InRoll
  FRotator ResultRot = UKismetMathLibrary::ComposeRotators(
    LaserRot,
    LidarBodyRot
  );
  const auto Range = Description->Range;
  FVector EndTrace = Range * UKismetMathLibrary::GetForwardVector(ResultRot) + LidarBodyLoc;
```
I'm not deep into the engine code, but I think the ego-car rotation may not be considered in `LidarBodyRot`.

**Comment by germanros1987** [comment]
This should now be fixed.
