### ISSUE TITLE
is it possible to stream the data to another client

### ISSUE THREAD

**Issue by zjh6252007** [carla-simulator/carla#4168]
Now I'm connecting two clients to one server use the manual_control.py.  Is it possible to stream the data such as speed, throttle, coordinates from one client to another client?

**Comment by joel-mb** [comment]
Hi @zjh6252007. Could you further explain which is your configuration? Are you using synchronous or asynchronous mode?
Yes, you can retrieve the current state of the simulation from any client. Actually, the stream does not happen directly between the clients, but the server sends the new snapshot with the updated status to each client every tick.
