### ISSUE TITLE
cannot Find "xdg-user-dir: not found"

### ISSUE THREAD

**Issue by OmarShawky1** [carla-simulator/carla#4193]
This issue was asked before but not answered [https://github.com/carla-simulator/carla/issues/3444](herel) but to no avail.

This is my containerRunFile:
```$ cat RunCarla.sh 
#!/bin/bash

# Name of docker container.
CONTAINER_NAME="carla"
#Adding X Server unix socket access. acceptable solution because cadence is not malicious.
xhost +local:

# Run The Container
docker run -it --rm carlasim/carla ./CarlaUE4.sh -opengl \
    -e DISPLAY="$DISPLAY" \
    -v "${XSOCK}:${XSOCK}" \
    --name carla \
    "${CONTAINER_NAME}"
#    -v /tmp/.X11-unix:/tmp/.X11-unix \ # from https://github.com/carla-simulator/carla/issues/3431#issuecomment-708786234 but it did not work

xhost -local:
```

this is the output of running `$./RunCarla.sh`:
```
$ ./RunCarla.sh 
non-network local connections being added to access control list
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
non-network local connections being removed from access control list
```

I tried to check the file Carla run file, but i couldn't reach out to the source of the problem.
```
#cat CarlaUE4.sh
#!/bin/sh
UE4_TRUE_SCRIPT_NAME=$(echo \"$0\" | xargs readlink -f)
UE4_PROJECT_ROOT=$(dirname "$UE4_TRUE_SCRIPT_NAME")
chmod +x "$UE4_PROJECT_ROOT/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping"
"$UE4_PROJECT_ROOT/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping" CarlaUE4 $@ 
```

**Comment by OmarShawky1** [comment]
I tried manipulating the Dockerfile and installing `RUN apt install xdg-user-dirs` and it succeed, but I ended up with these two errors: `DISPLAY=:0: No such file or directory` & `docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/home/carla/CarlaUE4.sh -opengl": stat /home/carla/CarlaUE4.sh -opengl: no such file or directory: unknown.`

my new run script file:
```
#!/bin/bash

# Name of docker container.
CONTAINER_NAME="carla"
# Context directory is a directory which contains a Dockerfile, cadence files.
CONTEXT_DIR=$(pwd)

#Adding X Server unix socket access. acceptable solution because cadence is not malicious.
xhost +

#DISPLAY=$DISPLAY
# Build docker image from Dockerfile. #decomment it when first installing the docker
docker build -t "${CONTAINER_NAME}" "${CONTEXT_DIR}"

# Run The Container
docker run -it --rm \
    -e DISPLAY=$DISPLAY \
    --name carla \
    "${CONTAINER_NAME}"

#docker run -it --rm "${CONTAINER_NAME}" /bin/bash \
#Removing Display Access
xhost -
```

my new Dockerfile:
```
FROM carlasim/carla:0.9.11

USER root
RUN apt-get update
RUN apt-get install xdg-user-dirs
RUN apt-get install nano sudo curl -y
RUN apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev mesa-utils -y
USER carla
CMD ["/home/carla/CarlaUE4.sh -opengl"]
```

Note:
1. I used 0.9.11 because i suspected that the latest might have issues.
2. When I run `docker run --name carla -e DISPLAY=$DISPLAY -it --rm carla /bin/bash` & then I run `./CarlaUE4.sh -opengl` the output is as following:
```
$ ./CarlaUE4.sh -opengl
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
```
and this is a screenshot to ease things up
![image](https://user-images.githubusercontent.com/51538094/117973099-3f7cab80-b32c-11eb-8615-6c83a0ecdba4.png)

**Comment by qhaas** [comment]
`xdg-user-dir: not found` is likely a red herring, see Issue #3514

**Comment by OmarShawky1** [comment]
> `xdg-user-dir: not found` is likely a red herring, see Issue #3514

I have mentioned that i bypassed the issue and it seems that it is not the problem
