### ISSUE TITLE
Possible to run carla on a remote machine using docker, and then connect via VNC on my mac?

### ISSUE THREAD

**Issue by vgoklani** [carla-simulator/carla#4194]
Hey there,

Is it possible to run carla in a docker container on my remote workstation and then VNC the video to my mac? It doesn't have to be VNC, etc, I just want to run the docker container headless, and then view the video/output my mac laptop. Thanks!

**Comment by qhaas** [comment]
You will need to use [OpenGL for this, not the default vulkan](https://carla.readthedocs.io/en/latest/adv_rendering_options/#vulkan-vs-opengl).  Further, you will need [VirtualGL](https://virtualgl.org/About/Introduction) on the remote workstation.  The process for doing remote rendering is not intuitive.  The old guide for doing this with CARLA is located [here](https://carla.readthedocs.io/en/0.9.7/carla_headless).
