### ISSUE TITLE
Fail to build Unreal Engine

### ISSUE THREAD

**Issue by SpakMiguel** [carla-simulator/carla#420]
Hi all,

I am trying to build CARLA from source on Ubuntu 16.04. I follow the steps and have managed to clone Unreal Engine but the ./Setup.sh command fails. It happens every time that it fails when updating dependencies. Suddenly stops at 99% and throws an error. I have done some research on google but I have not been able to find a suitable solution. The internet connection is ok.

I would appreciate some help. Thanks in advance.

The following is the terminal log:

```
MIGUEL:~$ sudo apt-get install build-essential clang-3.9 git cmake ninja-build python3-requests python-dev tzdata sed curl wget unzip autoconf libtool
[sudo] password for MIGUEL: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-9).
build-essential is already the newest version (12.1ubuntu2).
libtool is already the newest version (2.4.6-0.1).
python3-requests is already the newest version (2.9.1-3).
sed is already the newest version (4.2.2-7).
unzip is already the newest version (6.0-20ubuntu1).
ninja-build is already the newest version (1.5.1-0.1ubuntu1).
cmake is already the newest version (3.5.1-1ubuntu3).
curl is already the newest version (7.47.0-1ubuntu2.7).
git is already the newest version (1:2.7.4-0ubuntu1.3).
python-dev is already the newest version (2.7.12-1~16.04).
tzdata is already the newest version (2017c-0ubuntu0.16.04).
wget is already the newest version (1.17.1-1ubuntu1.4).
clang-3.9 is already the newest version (1:3.9.1-4ubuntu3~16.04.2).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
MIGUEL:~$ sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-3.9/bin/clang++ 100
MIGUEL:~$ sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-3.9/bin/clang 100
MIGUEL:~$ git clone --depth=1 -b 4.18 https://github.com/EpicGames/UnrealEngine.git ~/UnrealEngine_4.18
Cloning into '/home/MIGUEL/UnrealEngine_4.18'...
Username for 'https://github.com': SpakMiguel
Password for 'https://SpakMiguel@github.com': 
remote: Counting objects: 78600, done.
remote: Compressing objects: 100% (61677/61677), done.
remote: Total 78600 (delta 16208), reused 68294 (delta 14949), pack-reused 0
Receiving objects: 100% (78600/78600), 160.48 MiB | 528.00 KiB/s, done.
Resolving deltas: 100% (16208/16208), done.
Checking connectivity... done.
Checking out files: 100% (82677/82677), done.
MIGUEL:~$ cd ~/UnrealEngine_4.18
MIGUEL:~/UnrealEngine_4.18$ ./Setup.sh
Registering git hooks... (this will override existing ones!)

Github build
Checking / downloading the latest archives
Checking dependencies (excluding Win32, Win64, Mac, Android)...
Updating dependencies:  99% (28390/28391), 4870.5/4892.6 MiB | 14.78 MiB/s...
Failed to download 'http://cdn.unrealengine.com/dependencies/2839850-632f4ca3f7a5496781b581496d5328d0/c00facf08e7d27b584bb1a8fdb7dcd0388c228f6': Can't read from pack stream (CorruptPackFileException)
Result: 1
```

**Comment by YashBansod** [comment]
Hi @SpakMiguel,
This is more related to Unreal Engine so you would find much more support on the Unreal Page.

I had a similar problem, but I recognised that the cause of that was:
some of the dependencies needed to be installed from online but the web address they were accessing was blocked by my organisation. (For you, it may be blocked for some other reason).

I tried various ways to make it work and was successful with one method. So I decided to make a script file for my method. Although I cannot share the complete script file (It has other things I cannot share), I can paste the relevant part here:

```
cd ~/
CORES=$(nproc --all)
CORES=$((CORES / 2))
git clone --depth=1 -b 4.18 https://github.com/EpicGames/UnrealEngine.git ~/UnrealEngine_4.18
cd ~/UnrealEngine_4.18/
find ./ -type f -exec sed -i 's/http\:\/\/cdn\.unrealengine/https\:\/\/cdn\.unrealengine/g' {} \;
sudo ./Setup.sh
cd ~/
sudo chmod -R 777 UnrealEngine_4.18
cd ~/UnrealEngine_4.18/
./GenerateProjectFiles.sh
make -j ${CORES}
cd ~/
./UnrealEngine_4.18/Engine/Build/BatchFiles/Linux/Build.sh ShaderCompileWorker Linux Development -verbose
```

**Comment by marcgpuig** [comment]
Hi @SpakMiguel,

I'm not able to reproduce your error, I feel bad but seems a connection error to me :(
Have you achieved something new?

**Comment by SpakMiguel** [comment]
Hi @marcgpuig ,

It was a connection error yes, similar to what happened to @YashBansod (Thanks btw!). I managed to solve it though.
I have successfully built Unreal Engine but Carla crashes when executing CarlaUE4.sh from the already built version. I do not know why I am getting a Segmentation fault every time. My connection works fine and Carla files have all the right permissions. You can find attached the log to see if you can help me.

Thanks,

[LOG.txt](https://github.com/carla-simulator/carla/files/2034762/LOG.txt)

**Comment by SpakMiguel** [comment]
It was a graphic card drivers issue. Solved.

It worked for me to reinstall drivers. Carla runs fine now.

**Comment by marcgpuig** [comment]
@SpakMiguel 
I'm happy to hear that! 
Thanks for your feedback :)

**Comment by zeroenergyhere** [comment]
Unreal Engine 4.18 loads with opengl3 but Carla "./CarlaEu4.sh -opengl3 throws segmentation fault. Without opengl3 it throws an opengl4.3 error, could not open. 

Please help me solve this issue. I tested on multiple systems with GPU and without GPU but same error.

Operating system - Ubuntu 16.04
System 1 - i7 processor, 4gb ram, nvidia quadro 600 graphics (Dell T1500)
System 2 - i5 processor, 8gb ram, intel hd graphics ( Dell Vostro)

**Comment by marcgpuig** [comment]
Hi @zeroenergyhere, which drivers are you using?

**Comment by jaypee92** [comment]
I tried find ./ -exec sed -i 's#http://cdn.unrealengine/https://cdn.unrealengine#g' {} \;

but still the setup.sh stops after 99%. i have downloaded the gzip file of the missing depedency.
anyone can help me to fix this?

**Comment by jaypee92** [comment]
Failed to download 'https://cdn.unrealengine.com/dependencies/UnrealEngine-4690078-25be7614c4f74274adc1c3cb1d6e032e/d4b6bc525135e5f3997bc740127b9f8e5a064369': Error: TrustFailure (The authentication or decryption has failed.) (WebException)
Result: 1

**Comment by Instantnoodles-madman** [comment]
> Failed to download 'https://cdn.unrealengine.com/dependencies/UnrealEngine-4690078-25be7614c4f74274adc1c3cb1d6e032e/d4b6bc525135e5f3997bc740127b9f8e5a064369': Error: TrustFailure (The authentication or decryption has failed.) (WebException)
> Result: 1

have you resolved this problem，i  can download this file by html,but it failed when ./Setup.sh

**Comment by J160KU** [comment]
Hello @Instantnoodles-madman,

I just received the same error for  the first time, even I built CARLA with UE more then ten times before successfully. Did you find a solution to this already?

![image](https://github.com/user-attachments/assets/1bfea8ca-b806-498b-a573-772b681dd1c6)

**Comment by Instantnoodles-madman** [comment]
邮件已收到，谢谢。

**Comment by J160KU** [comment]
Can you speak english, pls?

**Comment by hdp-alt** [comment]
Could solve this by installing the latest version of Mono:
```
sudo apt install mono-runtime
```

**Comment by Hak-Y** [comment]
> SOLVED TrustFailure ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
> 
> Could solve this TrustFailure by installing the latest version of Mono:
> 
> ```
> sudo apt install mono-runtime
> ```

RUN apt-get -y install mono-runtime in dockerfile works like charm!!! thanks

**Comment by psr-ai** [comment]
`mono-runtime` was the issue for me as well. This can be a part of the documentation for a general linux build (maybe ubuntu comes preinstalled).
