### ISSUE TITLE
Pygame is very slow to plot images

### ISSUE THREAD

**Issue by felipecode** [carla-simulator/carla#421]
Now , with recent improvements in CARLA fps, pygame has become
one bottleneck when running the manual_control.py example.
Pygame seems a good solution for the joystick/keyboard controlling part,
but not for plotting images.

Does anyone knows a good library for that ?
 Is the current pygame implementation suboptimal ?

**Comment by marcgpuig** [comment]
I've not tried it, but maybe you can take a look at [pyglet](https://bitbucket.org/pyglet/pyglet).
