### ISSUE TITLE
CARLA 0.9.11 make PythonAPI and make launch problem

### ISSUE THREAD

**Issue by zyan003** [carla-simulator/carla#4213]
Hi all, I have some issues while I was trying to build CARLA. 
![123](https://user-images.githubusercontent.com/81597316/118415929-1a18d600-b67b-11eb-98cd-cf579577fdb7.png)

I have no idea to fix these issues. It is weird because rem is not found in batch file.

Thank you for your answer

**Comment by corkyw10** [comment]
Hi @zyan003, can you share the documentation you are following?
Are you running the command in the Visual studio x64 native tools Command prompt?

**Comment by zyan003** [comment]
Hi Corinne,

I solved this problem by resetting my Windows operating system. Then
everything works fine now. I did running the command in Visual Studio x64
native tools command prompt.

Best,
zyan003

**Comment by corkyw10** [comment]
I'm glad you got it sorted out!
