### ISSUE TITLE
[carla 0.9.10] Collision with ‘Unknown’ 

### ISSUE THREAD

**Issue by ChoByungSoo2** [carla-simulator/carla#4223]
operating system : window 10
carla version : 0.9.10
Unreal Engine : 4.24.3

There is no problem when load.fbx is uploaded, but the following problems occur when running the following mode for maps imported from objects fbx files such as trafficLight.fbx or building.fbx:  

PythonAPI : manual_control.py , no_rendering_mode.py , spawn_npc.py

Problem: 
1. Even if there is no object in the driving path, the car cannot drive forward as if it were hit by something. (It occurs in many parts of the map generated.) -> Show Collocation with 'Unknown'
2. Spawn point error occurs -> ex) If 300 vehicles are created, only 3 vehicles will be created.

This video is a video of a problem occurring.

[https://youtu.be/DA089Qfw3hk](url)

Note) I imported the fbx file with the following options

![image](https://user-images.githubusercontent.com/48274692/118613171-76a1ff80-b7f9-11eb-978a-1e4e9400494e.png)
![image](https://user-images.githubusercontent.com/48274692/118613196-7ace1d00-b7f9-11eb-8988-b994a7a78a5e.png)

**Comment by ChoByungSoo2** [comment]
Fixed the problem.

**Comment by corkyw10** [comment]
Hi @ChoByungSoo2  since you fixed the problem, I will close this issue. You can reopen if needed.
