### ISSUE TITLE
Lidar: Complex collisions for moving objects (vehicles)

### ISSUE THREAD

**Issue by ananiboenig** [carla-simulator/carla#423]
After creating a scene with moving objects (in this case non player vehicles), we try to capture it with both, Lidar and camera. In the next step, we fused the camera data with the Lidar data. It works perfectly with static objects, however for moving object, the simplification of the contour for moving objects (like the car in the attached image) doesn't correspond anymore to the image view. 

We think that it has something to do with simple collision boxes, that are automatically created for moving objects. Do you know if it is possible to create complex collision boxes for vehicles that matches the actual contours, as seen through the camera? Or are there other ways to detect the actual contour of the moving vehicle with the Lidar?

Thanks! 

<img width="653" alt="car_lidar" src="https://user-images.githubusercontent.com/32710654/40154522-8d1163a4-5943-11e8-8b62-8de220859c97.png">

**Comment by marcgpuig** [comment]
Hi @ananiboenig,

Yes this is a known issue.
We use raycast to generate the lidar pointcloud, but everything that is "dynamic" uses Unreal's SkeletalMeshes (which can use animations) and this kind of meshes have this issue with the raycast, that use the collision box as collision.
If Unreal change this, it will work fine. If not, we problably could make some image-depth-based-lidar-like sensor that will provide better results :)

Regards.

**Comment by nsubiron** [comment]
The problem might be related to the channel used for the ray-cast. We should investigate different channels and ray-cast methods to see if we can get the actual mesh as collision (though that might be slower).

See also the issues reported in #455.

**Comment by maxjaritz** [comment]
Hi @nsubiron, @marcgpuig,
Romanenko-Serhii in [this post](https://github.com/carla-simulator/carla/issues/835#issuecomment-440599234) was suggesting a solution. Have you tried that?

**Comment by marcgpuig** [comment]
@maxjaritz We didn't try it.
As it looks like it could work for the lidar issue, it may drastically drop the performance because of the hard-to-solve collision. Did you try it?

**Comment by maxjaritz** [comment]
@marcgpuig No, I didn't.

**Comment by germanros1987** [comment]
We are working on a new LIDAR model as part of the External Sensor Interface, which targets a physically-based laser model. We will follow-up soon.

**Comment by Yaccoub** [comment]
any news on the physically-based laser model ? thanks
