### ISSUE TITLE
Carla Transform Input Frame of Reference

### ISSUE THREAD

**Issue by BradleyBrown19** [carla-simulator/carla#4236]
Hello!

When using world.spawn_actor to place a camera in the scene, what frame of reference should we pass into carla.Transform. 

ex. if we have:

```
transform = carla.Transform(translation, rotation)
cam = world.spawn_actor(blueprint, transform, ...)
```

should the passed in translation and rotation be from the camera to the world reference or from the world reference to the camera. 

From the docs I would assume that it is the former but I just wanted to make sure.

Thanks in advance!

**Comment by DSantosO** [comment]
Hello @BradleyBrown19,
When spawning a sensor (or any other actor), the transform needs to be the position/rotation of this sensor in world coordinates (or in other's actors frame of references if you are attaching to another actor).
