### ISSUE TITLE
Engine RPM in Carla

### ISSUE THREAD

**Issue by HarishKumar051993** [carla-simulator/carla#4241]
How to Calculate the Engine RPM of a Carla Vehicle?

There is no API available to calculate Engine RPM.

**Comment by jackbart94** [comment]
If you look into carla.VehiclePhysicsControl and check max_rpm (float), it gives out the maximum RPM of the vehicle's engine. Then, if you apply a throttle of 0.7 you are actually setting an RPM of 70% with respect to the maximum.

**Comment by YuhengZhi** [comment]
> If you look into carla.VehiclePhysicsControl and check max_rpm (float), it gives out the maximum RPM of the vehicle's engine. Then, if you apply a throttle of 0.7 you are actually setting an RPM of 70% with respect to the maximum.

In PhysX_3.4, throttle scales the maximum torque given by torque_curve(current_RPM), not directly RPM itself.
