### ISSUE TITLE
filter non_player_agents that are occluded

### ISSUE THREAD

**Issue by mattangus** [carla-simulator/carla#425]
Is there any way to filter `measurments.non_player_agents` that are occluded?

I have extracted 3d bounding boxes from the simulator. Overlaying them on the image results in the following:

![carla](https://user-images.githubusercontent.com/5302804/40188325-acc89058-59c7-11e8-9083-032626a51230.png)

As you can see there is only one pedestrian in the scene, but there are a ton of bounding boxes extracted from the `measurments.non_player_agents` list.

I'm using version 0.8.2.

**Comment by marcgpuig** [comment]
Hi @mattangus 

Nice work! It looks cool.
As you can read in https://github.com/carla-simulator/carla/issues/314#issuecomment-379788542 we does not have this feature right now, but you can make an approach with the depth.

**Comment by marcgpuig** [comment]
Hey @mattangus 
Any updates?
Can I close the issue?

**Comment by lxtttt** [comment]
@mattangus Hi, do you fix this problem? Can you give me some hints?

**Comment by Nozomeister** [comment]
@marcgpuig Hi, can you explain more about the approach with depth solution? I'm curious and want to use that to cancel out unseen pedestrians/cars inside the camera FOV.

**Comment by marcgpuig** [comment]
Hi @Nozomeister.
I haven't tested it, but you can transform each one of the 8 bounding box points to 2d screen coordinates (point _p_). Then check if the depth of the 4 pixels that are around the point _p_ is less than the depth of _p_, if true, the point is occluded. If all 8 bounding box points are occluded, the object is occluded.
This is an approach until we have instance segmentation.

Cheers!

**Comment by sergiosanchoasensio** [comment]
Hi @mattangus, I am playing around with CARLA and I need to extract the 3d bounding boxes from the simulator. Could you please share the code snippet? Thank you!

**Comment by marcgpuig** [comment]
Hi @sergiosanchoasensio.
I recommend you to check #314, where I provide an explanation along with a modified client (tested in 0.8.1) that does exactly what you are searching for.
