### ISSUE TITLE
Map not change imput from osm

### ISSUE THREAD

**Issue by DanielTian90** [carla-simulator/carla#4255]
After run python3 config.py --osm-path=/path/to/OSM/file , map in carla not change, still the default one.
After run this command, outputs:
Warning: Found angle of 168.09 degrees at edge '482847293', segment 0.
Warning: Found sharp turn with radius 2.99 at the start of edge '482847293'.
Warning: Minor green from edge '24474354#0' to edge '24474442#1' exceeds 19.44m/s. Maybe a left-turn lane is missing.
Warning: Speed of straight connection '136752698_0->24474354#5-AddedOnRampEdge_2' reduced by 8.35 due to turning radius of 68.63 (length=10.34, angle=23.76).
Warning: Speed of straight connection '136752698_1->24474354#5-AddedOnRampEdge_3' reduced by 9.96 due to turning radius of 57.71 (length=8.67, angle=23.76).
Warning: Speed of straight connection '24474442#5_0->39676332_0' reduced by 7.76 due to turning radius of 38.00 (length=14.09, angle=36.82).
Warning: Speed of turning connection '482847293_1->24474354#4_1' reduced by 22.09 due to turning radius of 5.88 (length=6.29, angle=88.88).
Warning: Speed of straight connection '-24474442#6_0->-24474442#4_0' reduced by 7.01 due to turning radius of 42.08 (length=9.17, angle=27.79).
Warning: Could not write OpenDRIVE geoReference. Only unshifted Coordinate systems are supported (offset=-11558652.56,-3475173.93)
Warning: Could not compute smooth shape from lane '136752711#4_3' to lane '136752711#5_3'. Use option 'junctions.scurve-stretch' or increase radius of junction '4756333588' to fix this.
Warning: 9 total messages of type: Speed of % connection '%' reduced by % due to turning radius of % (length=%, angle=%).
load opendrive map

**Comment by zlg9folira** [comment]
Any update on this issue? Have you had any success addressing those warnings?
