### ISSUE TITLE
Cannot Run Automatic_control.py in Carla 

### ISSUE THREAD

**Issue by Michaelll268** [carla-simulator/carla#4259]
I tried everything with the pythonpath and stuffs but I still cant load automatic_control.py in carla,, the error that is mentioned is "No Module named agents.navigation". Please Help me,, thanks a lot<!--

I use:
Windows 10 64 bit
GTX 1660Ti

**Comment by jackbart94** [comment]
We need more information. Did you do ``make PythonAPI`` and ``make LibCarla`` ? Did you check that the path in the ``automatic_control.py`` script correctly points to your CARLA folder structure? Maybe you've made some changes there.

**Comment by Michaelll268** [comment]
@jackbart94  how to make pythonAPI and make LibCarla, is it directly on the CMD or in the corresponding folder of the file?

**Comment by jackbart94** [comment]
Your folder structure is probably wrong. Check the code in ``automatic_control.py`` and check out where it is trying to find the agents folder and why it is failing. Which version of CARLA are you using?
