### ISSUE TITLE
get_elapsed_time get zero when traffic light state is red

### ISSUE THREAD

**Issue by xujiahao97** [carla-simulator/carla#4266]
Hello, i am now using carla.Trafficlight class. i use get_red_light function and it returns 2,but actually red light red light shines 32 seconds. and i use get_elapsed_time function and its return value is correct during yellow light and green light.but it only counts first 2 seconds of red lights and then it returns 0.
I am wondering whether anyone run into same issues or does anyone know how to figure it out.

**Comment by corkyw10** [comment]
Hi @xujiahao97, could you provide a code example to help reproduce your issue?

**Comment by xujiahao97** [comment]
[GLOSA.txt](https://github.com/carla-simulator/carla/files/6620523/GLOSA.txt)

i wrote this python file according to automatic_control.py.

**Comment by zdx19981006** [comment]
meet the same issue

**Comment by GordenZhao** [comment]
Hi @corkyw10, is there any progress for this issue reproducing or fixing? I met the same issue. Thank you.

**Comment by flyico** [comment]
I got the same problem, anyone has some tips?

**Comment by kmeeey** [comment]
This problem still exists in 0.9.14, does anyone have a better way to get the remaining time of the signal light?

**Comment by smart-geng** [comment]
This problem still exists in 0.9.15
