### ISSUE TITLE
Version 0.9.6 and above does not support pip?

### ISSUE THREAD

**Issue by atusi-nakajima** [carla-simulator/carla#4287]
Version 0.9.6 and above does not support pip?

**Comment by qhaas** [comment]
CARLA's PythonAPI is provided as an [egg](https://packaging.python.org/discussions/wheel-vs-egg), which is installed via `python3 -m easy_install /path/to/egg`.  For a binary distribution of carla, that path is `CARLA_0.9.11/PythonAPI/carla/dist/carla-0.9.11-py3.7-linux-x86_64.egg`
