### ISSUE TITLE
Addition of a GetAllVisible Actors function?

### ISSUE THREAD

**Issue by And1210** [carla-simulator/carla#4299]
Hello,

I have been using CARLA for some graduate related research in the field of Pedestrian detection. I am trying to find a way to get all visible actors (in my case it would be pedestrians) from a camera view using the CARLA API. Unfortunately, the best method I have been able to use involves checking the positions of the actors relative to the camera and using this to determine if the actor is in view or not. This has many issues, most revolving around pedestrians being occluded by buildings, trees, cars, or even other pedestrians but still being recorded using their bounding box. 

I was wondering if a function could be implemented into the CARLA API that would return a list of all visible actors from a given RGB camera view?

Thank you

**Comment by FiodarKazhamiaka** [comment]
Hey, I've done something similar by using the semantic lidar sensor. Query each point to see if it corresponds to a pedestrian.
https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-lidar-sensor

**Comment by DSantosO** [comment]
Hello @And1210,
Thank you for the sugestion, we will study if we can add this functionality in the future.
As @FiodarKazhamiaka suggest, one workaround that is possible with the current tools of carla can be using the Semantic Lidar.
 - You can set a semantic lidar with a similar FOV of the camera
 - Check all the actors detected by the semantic lidar
 - Transform the actor's points to camera space to check if the are visible to the camera. You can find an example of this in the [`lidar_to_camera.py`](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/lidar_to_camera.py) example script.
Of course this can be a bit costly but it provides the solution to what you need.
