### ISSUE TITLE
LInux build setup.sh fail

### ISSUE THREAD

**Issue by anthonypan08** [carla-simulator/carla#430]
When I run Setup.sh for Carla on Linux Ubuntu 18.04, it said something about xlocal.h not found. I digged around and it seemed like it might be an issue with Unreal Engine, but my Unreal Engine setup was fine.

![screenshot from 2018-05-17 16-40-46](https://user-images.githubusercontent.com/20074651/40202791-19b31624-59f1-11e8-9dc4-996208750625.png)

**Comment by marcgpuig** [comment]
Hi @anthonypan08,

With a little search I found [this](https://answers.unrealengine.com/questions/705076/xlocaleh-not-found-on-linux.html) question in Unreal forums.
It doesn't looks like a problem in `Setup.sh` :(
Hope it help.

**Comment by anthonypan08** [comment]
So did anyone encounter the same problem and have a solution?

**Comment by 18605973470** [comment]
You can create a soft link by **`ln -s /usr/include/locale.h /usr/include/xlocale.h`** if locale.h exists

**Comment by marcgpuig** [comment]
Hey @anthonypan08 
Some good news?
Is the problem solved?

**Comment by anthonypan08** [comment]
SOLVED:
The problem was the driver on the Ubuntu machine. I had to change the driver to Nvidia driver instead of using the X.org driver through the "additional drivers" windows.  After that, the Carla worked

**Comment by J-Rojas** [comment]
@anthonypan08 That fix doesn't work for me. I have Nvidia drivers installed and enabled and still encounter this compiler bug.

**Comment by marcgpuig** [comment]
@J-Rojas are you using the correct version of everything (Unreal 4.18.x and so on)?

**Comment by J-Rojas** [comment]
Yes, 4.18.3, latest Clang 3.9.x. I'm using Ubuntu 18.04. The only workaround that worked for me was the symbolic link.
