### ISSUE TITLE
Randomness of trees for different simulation sessions

### ISSUE THREAD

**Issue by ttthl** [carla-simulator/carla#4311]
Hello,

I found that the trees and plants in the same map could be different when loading the world for several times. My goal is to have same scenarios for two running times with two different car models (the only difference is the material of the car), so I followed the structure of the example `/test/smoke/test_determinism.py` to get deterministic results of the total traffic and add camera sensor on one ego car to retrieve images. However, even when the location of the car is exactly the same for two set of image sequences, sometimes the shapes of the trees might have differences.

Here are several image pair examples.
![1_1](https://user-images.githubusercontent.com/57728465/121878289-d8c42680-cd0b-11eb-8aed-e8bb104c9e82.png) ![2_1](https://user-images.githubusercontent.com/57728465/121878296-da8dea00-cd0b-11eb-8e77-14aab0b76154.png)
You can see that due to the differences of the trees, the shadows on the building will also change.

![3_1](https://user-images.githubusercontent.com/57728465/121878212-bf22df00-cd0b-11eb-9e74-5ff74abb27e7.png) ![4_1](https://user-images.githubusercontent.com/57728465/121878221-c0540c00-cd0b-11eb-9460-8045f32ae459.png)
Here the distribution of the trees on the small mountain also changes.

![5_1](https://user-images.githubusercontent.com/57728465/121878716-525c1480-cd0c-11eb-9939-a6eea9a0f372.png) ![6_1](https://user-images.githubusercontent.com/57728465/121878725-5425d800-cd0c-11eb-93c9-60d8b0a0a4cd.png)
And the plants alongside the road can also be quite different.

So I'm wondering if there is any way to have the same generation of all trees and plants for each simulation? 

Implementation details:
Carla version: 0.9.11
Ubuntu 18.04

Thank you

**Comment by XGodina** [comment]
Hi @ttthl  The thing that causes that is the wind. Our Trees move depending on the strength of the wind. Use our script environment.py to reduce the strength of wind to 0.

**Comment by ttthl** [comment]
Hi @XGodina , thanks for the reply. However I've already set the strength of wind to 0. Is there any other reason can cause this?

**Comment by XGodina** [comment]
Hi, @ttthl 
First of all forgiveness for answering so late. Yes, @DSantosO discovered that determinism did not work well.
I guess this is what you're talking about. But I think he will explain better than me, what was the problem.

**Comment by XGodina** [comment]
Hi, @ttthl We fix this problem. The next release will be in a couple of weeks.

**Comment by ttthl** [comment]
Hi, @XGodina Thanks for the remind. That would be great, I'll try it for the next release.
