### ISSUE TITLE
npc speed with Behaviour Agent

### ISSUE THREAD

**Issue by ymurzello** [carla-simulator/carla#4336]
Hello!
I am unable to change the npc speed using the TrafficManager module. I have a client where the ego vehicle is controlled by the Behaviour Agent and the npcs are controlled by the default TrafficManager in spawn_npc.py (in the PythonAPI/examples folder). I am using v0.9.11 (Windows). When I change the traffic_manager.global_percentage_speed_difference(30.0) to -30 or 10, the npcs still continue to drive at the same speed that is faster than my ego vehicle.
How do I change the speed of the npcs? I need them to surround my ego vehicle and not drive faster.
Thanks in advance!

**Comment by jackbart94** [comment]
The global_percentage_speed_difference works so that if you set it to 30, vehicles go 30% slower than the limit. If you want vehicles to go even slower, you must increase that value, not decrease. If you want them to go faster than the limit, you need to set that value to a negative number.
