### ISSUE TITLE
AttributeError: 'ColorConverter' object has no attribute 'upper'

### ISSUE THREAD

**Issue by aczy118** [carla-simulator/carla#4340]
Hi there,
I am using Carla 0.9.10.1 on Windows.
I am trying to run lidar_to_camera.py, which is provided in the PythonAPI, with a depth camera instead of an rgb camera used  in the original script. To get the depth view I want to use **carla.ColorConverter.LogarithmicDepth** and save the projected lidar points on the depth images. However, I keep getting the following error:

C:\Users\Desktop\WindowsNoEditor\PythonAPI\examples>python tutorial1.py
(0/500) Simulation: 10234 Camera: 10234 Lidar: 10234 (1142400,)

tutorial1.py:251: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  u_coord = points_2d[:, 0].astype(np.int) #x
tutorial1.py:252: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  v_coord = points_2d[:, 1].astype(np.int) #y
tutorial1.py:260: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.interp(intensity, VID_RANGE, VIRIDIS[:, 2]) * 255.0]).astype(np.int).T
Traceback (most recent call last):
  File "tutorial1.py", line 376, in <module>
    main()
  File "tutorial1.py", line 368, in main
    tutorial(args)
  File "tutorial1.py", line 279, in tutorial
    image.save("_out/%08d.png" % image_data.frame, cc)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2135, in save
    if format.upper() not in SAVE:
AttributeError: 'ColorConverter' object has no attribute 'upper'

This is how I am trying to save images.
Save the image using Pillow module.

            cc = carla.ColorConverter.LogarithmicDepth
            image = Image.fromarray(im_array)
            image.save("_out/%08d.png" % image_data.frame, cc)

How can I fix this problem and project lidar points to the depth camera? Thanks in advance for your help and sorry if it is a simple question but I could not find the solution.

**Comment by DSantosO** [comment]
Hello @aczy118,

The problem is that you are using the carla.ColorConverter with the PIL image. 
The carla.ColorConverter needs to be used with a carla.Image so you should convert the image to the LogarithmicDepth before transforming the image to a numpy array.
