### ISSUE TITLE
Vehicle pass through the road on a map exported from RoadRunner to CARLA

### ISSUE THREAD

**Issue by ThibaultFy** [carla-simulator/carla#4343]
I am facing an issue after following the step from the "add map tutorial" with the standalone package method: [https://carla.readthedocs.io/en/0.9.11/tuto_A_add_map/](https://carla.readthedocs.io/en/0.9.11/tuto_A_add_map/)

After launching the command: 
`python3 docker_tools.py --input ~/path_to_input_folder --output ~/path_to_output_folder --packages map_package`
I obtain a file whith named **map_package_4c8f4d5-dirty.tar.gz**. 

When exporting it in the Carla package, some textures (grass or trees for instance) are not imported, and the vehicle fall through the road when it spawns. But I'm not facing particular error when launchin any python example script or loading the map using **util/config.py**.

The imported map is created using Roadrunner. I tried with an example map from Roadrunner and faced the same issue.

I can provide any more info with pleasure but I don't know what is really relevant for my issue...

Thank you very much in advance for your help!

Sincerely,

TF

**Comment by praetorianer777** [comment]
I have the same problem in version 0.9.13, was this fixed or is there a other solution?
