### ISSUE TITLE
Town with Parking lot

### ISSUE THREAD

**Issue by MariamEssam** [carla-simulator/carla#4355]
I am working with Carla version 0.8.4. Is there any town contains parking lot?

**Comment by XGodina** [comment]
Hi, @MariamEssam 
In that version, I think there are only 2 maps Town01 and Town02. On Town02 there is a space that simulates parking but in fact, But it's just a visualization. Those maps haven't parking lots.

**Comment by MariamEssam** [comment]
That's say I have to upgrade so starting from which version I can find it and in which town?
