### ISSUE TITLE
Issue with loading project from Unreal Engine?

### ISSUE THREAD

**Issue by anthonypan08** [carla-simulator/carla#436]
I am not sure if this is an issue with carla or Unreal Engine, but every time I try to open Carla on Unreal Engine, it crashes.
![screenshot from 2018-05-21 09-56-54](https://user-images.githubusercontent.com/20074651/40311269-52785b56-5cdd-11e8-8057-451c530171c6.png)

**Comment by nsubiron** [comment]
This is probably an issue with UE4, but it doesn't really show the problem in screenshot you sent. Try opening the editor without the Carla project

    ~/UnrealEngine_4.18/Engine/Binaries/Linux/UE4Editor

You can also check the log files for an earlier error (before signal 11, cause at that point it doesn't give much info).

**Comment by anthonypan08** [comment]
I opened the am able to open unreal editor window but if I try to open a new project or existing project, it just crashes. I am using a Linux 18.04 OS
