### ISSUE TITLE
Make launch error on Ubuntu18.04

### ISSUE THREAD

**Issue by seuwcs** [carla-simulator/carla#4375]
Hi, friends. I am installing carla on Ubuntu 18.04, carla version is 0.9.10, the UE4 version is 4.24
I have followed the instructions with ：https://carla.readthedocs.io/en/latest/build_linux/
and I have made PythonAPI sucessfully, but after that I run : make launch.
then the error occured.
The error is listed as the figure shows.

I am wondering if  I have missed some  dependencies? 

 I will appreciate it if someone can give me some help. Any suggestions will be appreciated. Thanks a lot !

@corkyw10 
Could you give me some help?

![error](https://user-images.githubusercontent.com/65322137/124767434-66411200-df6a-11eb-9307-196973ba6f21.jpg)

**Comment by corkyw10** [comment]
Hi @seuwcs, you are referencing the wrong documentation. Our docs are versioned. If you are installing 0.9.10 please start from scratch using `make clean` and follow the instructions [here](https://carla.readthedocs.io/en/0.9.10/build_linux/)

**Comment by seuwcs** [comment]
Thank you very much, the problem has been solved by your advice.
