### ISSUE TITLE
CarlaViz - all traffic lights are green

### ISSUE THREAD

**Issue by xrispa-m** [carla-simulator/carla#4390]
I'm trying to run Carla with Sumo and Carlaviz. I've managed to synchronize Carla and Sumo, so the vehicles move in Carla based on the routes from Sumo. However, all the traffic lights in Carlaviz are green instead of following the traffic light logic from Sumo. When I run the `run_synchronization.py` the traffic light manager is Sumo.

Shouldn't those changes be depicted on Carlaviz too?

Sumo version 1.7.0
Carla version 0.9.11

**Comment by MattRowe18** [comment]
@joel-mb could you take a look at this issue.

Thanks
