### ISSUE TITLE
Accessing current weather condition in the Lidar class ?

### ISSUE THREAD

**Issue by etibuteau** [carla-simulator/carla#440]
I want to use the weather condition to simulate the behavior of a Lidar in different condition. 

So, I want to know if there is a way to have access to these data (PrecipitationAmount, SunBrightness,etc.) in my Lidar object without having to load them from the setting file since they are UProperty.

Thank You

**Comment by nsubiron** [comment]
You can access the active weather description from the _ACarlaSettings_ object, it belongs to the game instance class

```cpp
UWorld *World = GetWorld();
check(World != nullptr);
UCarlaGameInstance *GameInstance = Cast<UCarlaGameInstance>(UGameplayStatics::GetGameInstance(World));
check(GameInstance != nullptr);
const UCarlaSettings &CarlaSettings = GameInstance->GetCarlaSettings();
const FWeatherDescription *Weather = CarlaSettings.GetActiveWeatherDescription();

if (Weather != nullptr) // It is null if the user didn't change the weather. (WeatherId=-1)
{
  // Parse here the FWeatherDescription.
}
```

**Comment by etibuteau** [comment]
Perfect thank you
