### ISSUE TITLE
Carla 0.9.11 Pygame shows that serve has a very low FPS at around 3

### ISSUE THREAD

**Issue by Kingsman1995** [carla-simulator/carla#4408]

**Comment by Kingsman1995** [comment]
Hi, I currently use the new version 0.9.11, here is the configuration of my laptop:
1. Ubuntu 18.04
2. Alienware m15 r4 (RTX 3080; intel core i9-10th gen)

It seems that my laptop has no problem with its configuration, but when I run the Carla simulator, it gets slow, the FPS of the server is around 3, and the client FPS is about 62. It runs slowly in the pygame when I start the manual_control.py. Does anyone know what's the reason causing this problem?

**Comment by jackbart94** [comment]
Are you using the packaged version, or are you in the Unreal Engine editor?

**Comment by KamazGraphics** [comment]
Possible solution: you need to open Unreal Engine Editor settings and find "Use less CPU in background" - uncheck the box and everything should be fine.

**Comment by wangchengkang** [comment]
Possible Solution, find /PythonAPI/Utils/config.py.  run this script, e.g.: python3 config.py --fps=20.
