### ISSUE TITLE
Any guideline to install roadrunner in ubuntu 20

### ISSUE THREAD

**Issue by Laudarisd** [carla-simulator/carla#4415]
Hello everyone

I have a roadrunner trial version.
 I didn't get any setup guideline to install it in ubuntu 20.

It would be a great help if anyone can provide me some hints to install roadrunner properly in ubuntu 20.

Thank you

**Comment by XGodina** [comment]
Hi @Laudarisd, sorry for the late reply, but on the RoadRunner website or Mathlabs there is information about it.

**Comment by Laudarisd** [comment]
Hi @XGodina I have already solved the problem. Thanks a lot for your reply.
