### ISSUE TITLE
Adding Sound to Simulator

### ISSUE THREAD

**Issue by FarzanehJafari** [carla-simulator/carla#442]
Hi, 

How to add environment, pedestrian and engine sounds to this simulator? Do you work about it?

Thanks,

**Comment by marcgpuig** [comment]
@FarzanehJafari 
Closing the issue, if you ever integrate something like this we will be happy to hear about it 😄

**Comment by FarzanehJafari** [comment]
I am working about it. If I got a result, I will tell to you too. 😉😉


Sent from Yahoo Mail for iPhone


On Wednesday, May 30, 2018, 14:29, Marc Garcia Puig <notifications@github.com> wrote:


@FarzanehJafari
Closing the issue, if you ever integrate something like this we will be happy to hear about it 😄

**Comment by mcstoffi** [comment]
Hi @FarzanehJafari ,

Have you made some results there? I am working with Carla in my Bachelor Thesis and it would be very helpful for me to have the Simulator sound.

Thanks a lot and Greetings

**Comment by owoschhodan** [comment]
It would be cool having an additional sensor for audio (microphone sensor) like the camera sensor.

As a workaround I use pygame to play sounds/music via the client.

modified manual_control_steeringwheel.py:
```
self.crashSound = pygame.mixer.Sound(scream.wav')

def _on_collision(weak_self, event):
......
    if isinstance(event.other_actor,carla.Walker):
        self.crashSound.play()
```

**Comment by aboozarroosta** [comment]
> It would be cool having an additional sensor for audio (microphone sensor) like the camera sensor.
> 
> As a workaround I use pygame to play sounds/music via the client.
> 
> modified manual_control_steeringwheel.py:
> 
> ```
> self.crashSound = pygame.mixer.Sound('scream.wav')
> 
> def _on_collision(weak_self, event):
> ......
>     if isinstance(event.other_actor,carla.Walker):
>         self.crashSound.play()
>

Hi,
Can this approach be done for playing multiple sound sources in the simulationf?

**Comment by dhdiagram4011** [comment]
Where can I find the scream.wav file? Sounds when the vehicle runs Are the sounds when colliding with other vehicles included in this file? If not, can you find these files too?
