### ISSUE TITLE
CARLA Architecture/Workflow 

### ISSUE THREAD

**Issue by CarlaaUser** [carla-simulator/carla#4435]
Dear All

I am new to the CARLA simulator. I need to draw the architecture/workflow of it. Can someone guide me or provide me with some sources.

Thanks

**Comment by MattRowe18** [comment]
@CarlaaUser hi, probably the best place to go is the CARLA YouTube page where we have numerous presentations from the CARLA Talks 2020 covering multiple features of the platform https://www.youtube.com/channel/UC1llP9ekCwt8nEJzMJBQekg
