### ISSUE TITLE
Need help regarding road designing from shp link file 

### ISSUE THREAD

**Issue by Laudarisd** [carla-simulator/carla#4436]
Hello everyone,

I am trying to design road in Roadrunner by following shp link file. 

Seems I can't generate road at once like opendrive file and road scanning attributes. 

Is there any idea to generate road at once  by following shp files link, node and lane data? I don't want to draw road and create link again. 
I already have link , node and lane data in shp file. I need to generate road mesh file and include all the lanes and line atomatically. 

Thank you

**Comment by MattRowe18** [comment]
@glopezdiest could you take a look at this question, thanks
