### ISSUE TITLE
CARLA dev Version - make PythonAPI Error

### ISSUE THREAD

**Issue by LucasFKobernic** [carla-simulator/carla#4437]
Hi everyone,

I’m trying to install CARLA dev version in my computer (Windows 10). I had already the version 0.9.11 in another computer. But now, I’m facing a new error. I already checked here and at Discord but couldn’t find any similar problem. 

The installation of the modified version from Unreal Engine 4.26 worked well. But when I try „make Python API“ I’m getting the following error:
 
 C:\Program Files\CARLA\carla-master\carla-master>make PythonAPI
-[Setup]: [Batch params]: --boost-toolset msvc-14.1
-[Setup]: Asynchronous jobs:  16
-[Setup]: Boost toolset:      msvc-14.1
-[Setup]: Install directory:  "C:\Program Files\CARLA\carla-master\carla-master\Build\"
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\"
    -[install_zlib]: A zlib installation already exists.
    -[install_zlib]: Delete "C:\Program Files\CARLA\carla-master\carla-master\Build\zlib-install\" if you want to force a rebuild.
    -[install_zlib]: Exiting...
-[Setup]: Installing libpng...
    -[install_libpng]: [Batch params]: --build-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\" --zlib-install-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\zlib-install\"
    -[install_libpng]: A libpng installation already exists.
    -[install_libpng]: Delete "C:\Program Files\CARLA\carla-master\carla-master\Build\libpng-1.2.37-install\" if you want to force a rebuild.
    -[install_libpng]: Exiting...
-[Setup]: Installing rpclib...
    -[install_rpclib]: [Batch params]: --build-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\"
    -[install_rpclib]: A rpclib installation already exists.
    -[install_rpclib]: Delete "C:\Program Files\CARLA\carla-master\carla-master\Build\rpclib-install\" if you want to force a rebuild.
    -[install_rpclib]: Exiting...
-[Setup]: Installing Google Test...
    -[install_gtest]: [Batch params]: --build-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\"
    -[install_gtest]: A Google Test installation already exists.
    -[install_gtest]: Delete "C:\Program Files\CARLA\carla-master\carla-master\Build\gtest-install\" if you want to force a rebuild.
    -[install_gtest]: Exiting...
-[Setup]: Installing "Recast & Detour"...
    -[install_recast]: [Batch params]: --build-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\"
    -[install_recast]: A "Recast & Detour" installation already exists.
    -[install_recast]: Delete "C:\Program Files\CARLA\carla-master\carla-master\Build\recast-cdce4e-install\" if you want to force a rebuild.
    -[install_recast]: Exiting...
-[Setup]: Installing Boost...
    -[install_boost]: [Batch params]: --build-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\" --toolset msvc-14.1 --version 1.72.0 -j 16
    -[install_boost]: A Boost installation already exists.
    -[install_boost]: Delete "C:\Program Files\CARLA\carla-master\carla-master\Build\boost-1.72.0-install\" if you want to force a rebuild.
    -[install_boost]: Exiting...
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
-[Setup]: Installing Xercesc...
    -[install_xercesc]: [Batch params]: --build-dir "C:\Program Files\CARLA\carla-master\carla-master\Build\"
    -[install_xercesc]: A xerces installation already exists.
    -[install_xercesc]: Delete "C:\Program Files\CARLA\carla-master\carla-master\Build\xerces-c-3.2.3-install\" if you want to force a rebuild.
    -[install_xercesc]: Exiting...
fatal: not a git repository (or any of the parent directories): .git
-[Setup]: Creating "CMakeLists.txt.in"...
-[Setup]:
   ###########
   # SUCCESS #
   ###########
 
   IMPORTANT!
 
   All the CARLA library dependences should be installed now.
   (You can remove all "*-src" folders in C:\Program Files\CARLA\carla-master\carla-master\Build\ directory)
 
   You only need the ASSET PACK with all the meshes and textures.
 
   This script provides the assets for CARLA 0.9.11:
   You can download the assets from here:
 
       http://carla-assets.s3.amazonaws.com/20201222_232b876.tar.gz
 
   Unzip it in the "C:\Program Files\CARLA\carla-master\carla-master\Unreal\CarlaUE4\Content\Carla\" folder.
   If you want another version, search it in C:\Program Files\CARLA\carla-master\carla-master\Util\ContentVersions.txt.
 
-[BuildLibCarla]: [Batch params]: --server --client
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
-- Build debug:   ON
-- Build release: ON
-- Build test:    ON
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Program Files/CARLA/carla-master/carla-master/Build/libcarla-visualstudio
Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
 
  carla_server.vcxproj -> C:\Program Files\CARLA\carla-master\carla-master\Build\libcarla-visualstudio\LibCarla\cmake\server\Release\carla_server.lib
  carla_server_debug.vcxproj -> C:\Program Files\CARLA\carla-master\carla-master\Build\libcarla-visualstudio\LibCarla\cmake\server\Release\carla_server_debug.lib
  -- Install configuration: "Release"
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
-- Build debug:   ON
-- Build release: ON
-- Build test:    ON
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Program Files/CARLA/carla-master/carla-master/Build/libcarla-visualstudio
Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
 
  Client.cpp
C:\Program Files\CARLA\carla-master\carla-master\LibCarla\source\carla\client\detail\Client.cpp(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "carla/Version.h": No such file or directory [C:\Program Files\CARLA\carla-master\carla-master\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client.vcxproj]
  Client.cpp
C:\Program Files\CARLA\carla-master\carla-master\Build\boost-1.72.0-install\include\boost/asio/buffer.hpp(34): warning C4005: "BOOST_ASIO_ENABLE_BUFFER_DEBUGGING": Makro-Neudefinition [C:\Program Files\CARLA\carla-master\carla-master\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  C:\Program Files\CARLA\carla-master\carla-master\LibCarla\source\carla\client\detail\Client.cpp: note: Siehe vorherige Definition von "BOOST_ASIO_ENABLE_BUFFER_DEBUGGING"
C:\Program Files\CARLA\carla-master\carla-master\LibCarla\source\carla\client\detail\Client.cpp(10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "carla/Version.h": No such file or directory [C:\Program Files\CARLA\carla-master\carla-master\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
-[BuildLibCarla]: LibCarla server has been successfully installed in "C:\Program Files\CARLA\carla-master\carla-master\Unreal\CarlaUE4\Plugins\Carla\CarlaDependencies\"!
-[BuildLibCarla]: LibCarla client has been successfully installed in "C:\Program Files\CARLA\carla-master\carla-master\PythonAPI\carla\dependencies\"!
-[BuildOSM2ODR]: [Batch params]: --build
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
-- CMAKE_BINARY_DIR: C:/Program Files/CARLA/carla-master/carla-master/Build/osm2odr-visualstudio
-- CMAKE_SOURCE_DIR: C:/Program Files/CARLA/carla-master/carla-master/Util/OSM2ODR
--
-- Platform:
--     Host: Windows-10.0.19042 AMD64
--     Target: Windows-10.0.19042 AMD64
--     CMake: 3.21.0
--     CMake generator: Visual Studio 15 2017 Win64
--     CMake build tool: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe
--     Compiler: MSVC 19.16.27032.1
--
-- Found Python: C:/Program Files/Python38/python.exe
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Enabled features: Windows-10.0.19042 AMD64 MSVC 19.16.27032.1 Release
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIBRARY
    linked by target "osm2odr" in directory C:/Program Files/CARLA/carla-master/carla-master/Util/OSM2ODR/src
 
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
 
  OutputDevice_File.cpp
C:\Program Files\CARLA\carla-master\carla-master\Util\OSM2ODR\src\utils\iodevices\OutputDevice_File.cpp(41): error C2027: Verwendung des undefinierten Typs "std::basic_ofstream<char,std::char_traits<char>>" [C:\Program Files\CARLA\carla-master\carla-master\Build\osm2odr-visualstudio\src\osm2odr.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\iosfwd(626): note: Siehe Deklaration von "std::basic_ofstream<char,std::char_traits<char>>"
C:\Program Files\CARLA\carla-master\carla-master\Util\OSM2ODR\src\utils\iodevices\OutputDevice_File.cpp(61): error C2065: "binary": nichtdeklarierter Bezeichner [C:\Program Files\CARLA\carla-master\carla-master\Build\osm2odr-visualstudio\src\osm2odr.vcxproj]
C:\Program Files\CARLA\carla-master\carla-master\Util\OSM2ODR\src\utils\iodevices\OutputDevice_File.cpp(61): error C2027: Verwendung des undefinierten Typs "std::basic_ofstream<char,std::char_traits<char>>" [C:\Program Files\CARLA\carla-master\carla-master\Build\osm2odr-visualstudio\src\osm2odr.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\iosfwd(626): note: Siehe Deklaration von "std::basic_ofstream<char,std::char_traits<char>>"
-[BuildOSM2ODR]: OSM2ODR has been successfully installed in "C:\Program Files\CARLA\carla-master\carla-master\PythonAPI\carla\dependencies\"
-[BuildPythonAPI]: [Batch params]: --py3
Building Python API for Python 3.
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    ext_modules=get_libcarla_extensions(),
  File "setup.py", line 119, in get_libcarla_extensions
    libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)]
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'dependencies/lib'

Reading the error, I think the problem is by the installation from osm2dr. So I try make osm2dr to see what happens, and I get the following error:

![image](https://user-images.githubusercontent.com/77980399/126941667-f0f0d862-a21f-448f-b2d7-5e0254f31d23.png)

I have unfortunately no idea, why this error is happening and how to solve it. I would be very grateful with any help,

Thanks,

**Comment by NagaPemmaraju** [comment]
Hi, 
I am also facing same issue. Were you able to resolve it? Let me know any steps I can try to solve this.

Thank you
