### ISSUE TITLE
autonomous driving agent/algorithm in build from source CARLA

### ISSUE THREAD

**Issue by sparklin1999** [carla-simulator/carla#4445]
Hello, I want to try the open source self-driving algorithm trained by others on CARLA. At the same time, I would like to use build from source CARLA (CARLA 0.9.11, OS: ubuntu 18.04).
I found that many others’ open source algorithms use binary CARLA as the platform. So it seems that because the difference between two CARLA, things are not going well. I'm wondering how can I run the agent/algorithm more smoothly. Any suggestions for this?

**Comment by MattRowe18** [comment]
@sparklin1999
Hi
Could you give us some more information about the errors you are getting when you try to run other people's code. There may be differences in the API functions from version to version.
