### ISSUE TITLE
Question: Camera vertical field of view

### ISSUE THREAD

**Issue by FranekStark** [carla-simulator/carla#4476]
A Question about the field of view of cameras in Carla.
When setting the fov parameter it sets both the horizontal as well as the vertical fov. Is there any possibility to set them individually?

**Comment by Madecu** [comment]
Hi @FranekStark,
We are using unreal's default cameras and the Field of View they allow to modify only changes horizontal fov 
![image](https://user-images.githubusercontent.com/54811869/128494322-114f04b5-4185-4f62-a608-b5dd1ff5147b.png)

The FOV is fixed, but as the viewport size changes, the aspect ratio is allowed to change, adjusting how much you see in the non-constrained axis. FOV can be expressed either as a fixed horizontal FOV or a fixed vertical FOV, and the engine currently uses fixed horizontal FOV, so the vertical FOV changes as the aspect ratio changes.

I found a video that might be helpful if you want to modify carla's unreal project. But for now, you can't set the vFOV individually from the API

https://www.youtube.com/watch?v=ZVEfspETs84&ab_channel=HarryPearce

**Comment by FranekStark** [comment]
@Madecu thanks a lot for your explanations. As the fov and the ratio are related to each other it makes indeed a lot of sense to set the v-fov via the image ratio.

**Comment by roshambo919** [comment]
Does this then imply square pixels?
