### ISSUE TITLE
how to use new large map in Carla 0.9.12

### ISSUE THREAD

**Issue by DailyL** [carla-simulator/carla#4480]
Hello Guys,
I am new in CARLA, and I just download CARLA 0.9.12 for my project.
Does anyone know how to use the large map(map 11 maybe?) in CARLA? 
I have tried the config.py methods, does not work.
Any help would be great!!!

CARLA version:0.9.12
Platform/OS:windows

**Comment by glopezdiest** [comment]
@DailyL You need to download and import the additional maps as Town11 isn't part of the default maps.
