### ISSUE TITLE
carla version 0.9.10-dirty

### ISSUE THREAD

**Issue by sparklin1999** [carla-simulator/carla#4486]
I noticed my carla version is 0.9.10-dirty when making launch, although CarlaUE4 and python API could be used normally. I tried to use make clean and make PythonAPI and make launch. But it still is 0.9.10-dirty. I wonder why and what problem it may cause? 

calra version: 0.9.10 (build from source)
os: Ubuntu 18.04

**Comment by wangchengkang** [comment]
I also noticed the dirty CARLA version in my computer, Have you figured out what does this "dirty" mean? why is it  @existing?
