### ISSUE TITLE
How can I control the non-player vehicles so that the vehicles can form into columns/teams controlled by some policy.

### ISSUE THREAD

**Issue by tjuHaoXiaotian** [carla-simulator/carla#451]
Can I control the other non-player vehicles?
How can I control the non-player vehicles so that the vehicles can form into columns/teams controlled by some policy (formation driving)?

**Comment by nsubiron** [comment]
Hi @tjuHaoXiaotian,

This is not yet possible but we are working on it (see #184), we expect to have it ready in the coming months.
