### ISSUE TITLE
problem was in make launch..

### ISSUE THREAD

**Issue by kekoukeleHanbin** [carla-simulator/carla#4523]
-[install_boost]: [B2 ERROR] An error ocurred while installing using "b2.exe".
    -[install_boost]: Exiting with error...

Multiple attempts have the same result.

**Comment by ThibaultFy** [comment]
Same problem with me...

**Comment by ThibaultFy** [comment]
My problem solved itself by removing the build folder and changing the path on my repo... I don't have more explanation than this...

**Comment by MattRowe18** [comment]
@SkandaNR did @ThibaultFy's solution work for you in the end?

**Comment by ThibaultFy** [comment]
It worked for me, even if I didn't understood why...
