### ISSUE TITLE
Cannot import .xodr to UE editor

### ISSUE THREAD

**Issue by ebadi** [carla-simulator/carla#4524]
CARLA version: carla-0.9.12
Platform/OS: Ubuntu 18.04.5
Problem you have experienced:  I have followed the instruction in this page to import a map (https://carla.readthedocs.io/en/0.9.12/tuto_M_add_map_alternative/) but I cannot import the corresponding .xodr file. 

![1](https://user-images.githubusercontent.com/1111940/129003845-b5559677-213a-48ff-9c45-e9a5ee438ffc.png)
![2](https://user-images.githubusercontent.com/1111940/129005133-3bb64ae0-e485-4fe2-9d74-1e65e7059eff.png)

**Comment by seuwcs** [comment]
> CARLA version: carla-0.9.12
> Platform/OS: Ubuntu 18.04.5
> Problem you have experienced: I have followed the instruction in this page to import a map (https://carla.readthedocs.io/en/0.9.12/tuto_M_add_map_alternative/) but I cannot import the corresponding .xodr file.
> 
> ![1](https://user-images.githubusercontent.com/1111940/129003845-b5559677-213a-48ff-9c45-e9a5ee438ffc.png)
> ![2](https://user-images.githubusercontent.com/1111940/129005133-3bb64ae0-e485-4fe2-9d74-1e65e7059eff.png)

Hello, if you have solved the problem, and how?
