### ISSUE TITLE
How to get the precise point-cloud models of the non-players?

### ISSUE THREAD

**Issue by YlugeR** [carla-simulator/carla#453]
Dear Carla Developers
     Through lidar simulation, I got the cloud-point models of non-players in Carla. However, I found that the models in point cloud are too simple, the vehicles are simplified into rectangles, and pedestrians are simplified into cylinders. This simplified model is not suitable for training samples. I want to know how to get the accurate non-player point-cloud models.
Thank you!

**Comment by marcgpuig** [comment]
Hi @YlugeR.
This is a duplicated question #423.

**Comment by YlugeR** [comment]
Dear @Marc Garcia Puig
I'm sorry for my duplicated question.In addtion, I have another question: how could I get the reflected intensity of lidar in the carla?

**Comment by marcgpuig** [comment]
Also another duplicated :) #327
