### ISSUE TITLE
Problem with DVS sensor

### ISSUE THREAD

**Issue by stephenjia** [carla-simulator/carla#4532]
Hi,

I run into a problem when using simulated DVS sensor. There is too much space between lines when the car is not driving slowly.

When it runs less than 30km/hr, it looks like this
![image](https://user-images.githubusercontent.com/9429707/129196210-fd41d143-70ea-4645-bb67-49f67b1d5387.png)

![image](https://user-images.githubusercontent.com/9429707/129196439-b9ba80c0-4864-443d-996b-cd8894721579.png)

When it runs at more than 100km/hr, it looks like this
![image](https://user-images.githubusercontent.com/9429707/129196586-f65bfc21-f7ad-4324-916d-427aeb37c147.png)

![image](https://user-images.githubusercontent.com/9429707/129196747-c5610d8b-d754-451a-9bf3-51e1fff778af.png)

I wonder whether this is normal? Is it caused due to the limitation of rendering speed?  How can I avoid rendering such kind of event data?

Thanks a lot!

**Comment by DSantosO** [comment]
Hello @stephenjia,

The DVS sensor compares the rendered image in the current frame with the one rendered in the previous one. When the car is going too fast the two images change a lot so the result that you see is the expected one. If you are using a variable time step you cannot control this, but if you are using a fixed delta time you can decrease it so you render images more often.

**Comment by stephenjia** [comment]
Hi @DSantosO ,

Thank you for your reply. So does it mean if we would like to get more continuous events, we should use fixed delta time and reduce it to a small number?

Thanks!

**Comment by DSantosO** [comment]
Yes, exactly.

**Comment by Shahid1Malik** [comment]
Hi @stephenjia. Can you help me in simulating DVS in carla?

**Comment by Shahid1Malik** [comment]
@DSantosO  does existing DVS EC simulator in Carla solely rely on RGB images to generate events, or it also uses other data like depth
