### ISSUE TITLE
@adityapatruni   if still matter, `./CarlaUE4.sh -opengl` worked for me

### ISSUE THREAD

**Issue by SaintArthurThomas** [carla-simulator/carla#4539]
@adityapatruni   if still matter, `./CarlaUE4.sh -opengl` worked for me

_Originally posted by @Unlingius in https://github.com/carla-simulator/carla/issues/3490#issuecomment-742845740_

I met this problem again in Carla0.9.12, which does not support OpenGL, Vulkan instead. I tried  `./CarlaUE4.sh -valkan` but got the same error.

**Comment by qhaas** [comment]
If running headless / no GUI, try `CarlaUE4.sh -vulkan -RenderOffscreen -graphicsadapter=0 -nosound`
