### ISSUE TITLE
Fog doesn't work - mosaic images

### ISSUE THREAD

**Issue by zengtaiping** [carla-simulator/carla#4542]
I'm trying to create a fog environment using the following configuration:
```
carla.WeatherParameters(cloudiness=0,
                        precipitation=0,
                        precipitation_deposits=0,
                        fog_density=50,
                        fog_distance=10,
                        sun_altitude_angle=-5)
```
However, the image from the camera is with mosaic:
<img width="802" alt="Screen Shot 2021-08-16 at 18 53 33" src="https://user-images.githubusercontent.com/33126567/129546259-e8424f85-5271-43a3-9f93-fc40704687ab.png">
What can be the problem? Is it the wrong configurations?

**Comment by XGodina** [comment]
@zengtaiping Could you provide me with some more information? What package is it? 9.12? The camera resolution is very low, isn't it?

**Comment by zengtaiping** [comment]
@XGodina Thanks for your reply. I am sorry for the incomplete information. I used the latest version. 
And I used the following camera parameters:
```
camera = world.get_blueprint_library().find('sensor.camera.rgb')
camera.set_attribute('image_size_x', '1280')
camera.set_attribute('image_size_y', '720')
camera.set_attribute('fov', '110')
camera.set_attribute('sensor_tick', '0.02')
```

**Comment by Madecu** [comment]
Hi @zengtaiping,
Sorry for the delayed respone. I've tried your weather configuration in Town01 and it works fine.

![image](https://user-images.githubusercontent.com/54811869/132373850-c8cc37f5-875d-4b58-8bb8-9c291b1fdfab.png)


Are you sure it is the fog who make the artifact? It only happens if you set the fog? Or it works with different amount of fog?

**Comment by zengtaiping** [comment]
Hi @Madecu, thanks for your reply. I tried different weathers, and only the fog one has this mosaic. And I found that more amount of fog makes it worse.

**Comment by Madecu** [comment]
I'm not able to reproduce those artifacts. I tried in windows and Linux, different towns but nothing. Can you try using the environment.py script that we have in PythonAPI/util to change the fog amount and see if it still causing that issue?
Maybe it is something related with your graphic card? I don't know

Let's keep trying different things so we can discard potential causes and figure out what is causing it

**Comment by zengtaiping** [comment]
@Madecu , I changed the fog amount, and it still causes this issue. I used this command `lspci | grep VGA`, and found that my gpu is `NVIDIA Corporation Device 2230 (rev a1)`. My driver version is `Driver Version: 470.63.01`. If you suddenly think of some commands I can try, please let me know. Thanks.

**Comment by Madecu** [comment]
@zengtaiping, Are you using the package verrion or editing unreal's project? Which version of Unreal Engine do you have installed? What graphic card do you have?

Thank you.

**Comment by zengtaiping** [comment]
@Madecu No, I did not edit the project. I use the NVIDIA A6000.

**Comment by Axel1092** [comment]
@zengtaiping Are you working with ubuntu or windows? Also, Are you using the package (if so what version) or are you compiling from source?
With the server running, could you run the `test_connection.py` script in the `PythonAPI/util` folder and report the output please?
