### ISSUE TITLE
"python3 netconvert_carla.py --Town04.xodr" error

### ISSUE THREAD

**Issue by parksanha** [carla-simulator/carla#4546]
Hello~

There was a problem running the code below. But I don't know how to solve it.

Can you give me some advice?
The operating environment is Ubuntu.

<code i wrote>
python3 netconvert_carla.py --Town04.xodr

<error message>
Warning: Mismatched geometry for edge '949' between geometry segments 3 and 4.

Warning: Ignoring road '21' without geometry.

Warning: Could not find fromEdge representation of '' in connection '888'.

Warning: Could not find fromEdge representation of '' in connection '888'.

Warning: Could not find fromEdge representation of '' in connection '886'.

Warning: Could not find fromEdge representation of '' in connection '477'.

Warning: Could not find fromEdge representation of '' in connection '482'.

Warning: Could not find fromEdge representation of '' in connection '482'.

Warning: Edge '31.0.00' has a grade of 14.07%.

Warning: Edge '34.0.00' has a grade of 11.44%.

Warning: Edge '44.0.00' has a grade of 10.49%.

Success.

free(): invalid pointer

Traceback (most recent call last):

  File "netconvert_carla.py", line 541, in <module>

    netconvert_carla(args.xodr_file, args.output, args.guess_tls)

  File "netconvert_carla.py", line 521, in netconvert_carla

    _netconvert_carla_impl(xodr_file, output, tmpdir, guess_tls)

  File "netconvert_carla.py", line 394, in _netconvert_carla_impl

    raise RuntimeError('There was an error when executing netconvert.')

RuntimeError: There was an error when executing netconvert.

**Comment by GittUser2021** [comment]
I been trying to figure out why I can’t fully convert town 4 using netconvert_carla.py. everything seems to look fine except for the road circled in the attached image. When I launch town04 in Carla, it is a gas station and it does show in the net file that is in the examples but when I try to convert it, it ignores it. 
I tired modifying the “opendrive_netconvert.typ.xml” but still no luck. Any advice on how to proceed with that? 

![Capture](https://user-images.githubusercontent.com/92377293/143807205-3c6fb0d0-8912-437e-8920-eaef82a418ba.PNG)
![image](https://user-images.githubusercontent.com/92377293/143807227-d40bb1b7-45a9-4af1-b0f3-5b996d524182.png)
