### ISSUE TITLE
Cannot get RoadLines label from a LiDAR sensor

### ISSUE THREAD

**Issue by EhsanCode** [carla-simulator/carla#455]
I am trying to get the object class for LiDAR. I have modified ALidar::ShootLaser and I have added this code:
`
uint8_t ObjectLabel  = static_cast<std::underlying_type<ECityObjectLabel>::type>(ATagger::GetTagOfTaggedComponent(*HitInfo.GetComponent()));
`

But it seems there is a problem to get Vehicles and RoadLines labels. By tracking the issue I realized  
`
 GetWorld()->LineTraceSingleByChannel(
    HitInfo,
    LidarBodyLoc,
    EndTrace,
    ECC_MAX,
    TraceParams,
    FCollisionResponseParams::DefaultResponseParam
  );
`
never hit RoadLines and HitInfo never contains any component of  Vehicles nor RoadLines.

In this visualization points are colored based on their labals, you can see there is no **RoadLine** label:

![objectclass](https://user-images.githubusercontent.com/22130114/40641666-bffe3c02-631a-11e8-9dc2-2e80e1abb772.jpg)

But I could get this information from a  'SemanticSegmentation' camera.  

![semanticsegmentationcamera](https://user-images.githubusercontent.com/22130114/40641719-e50cdd00-631a-11e8-9f70-cffb0c3d439c.png)

Thank you so much,
Best regards,
Ehsan

**Comment by nsubiron** [comment]
Hi @EhsanCode,

The ray-cast used by the lidar uses the collision channel, so only things with collision enabled will appear. Things like road-lines do not have collision for performance reasons. See also this issue with the vehicles #423. In the case of the vehicle the collision occurs with their physics asset instead of the mesh, I'm guessing that's the reason why they don't have a tag.

**Comment by EhsanCode** [comment]
Hi @nsubiron 
Thank you so much for your attention. I've enabled the collision on every roadLine content. Now, they have the same collision configuration as shown in this figure:
![image](https://user-images.githubusercontent.com/22130114/40829172-f65392ba-6582-11e8-81f9-953c49d843aa.png)

but still, no roadLine collision has been detected. Would you please let me know if I could do anything more to detect roadLine collision?
Thanks again.

**Comment by nsubiron** [comment]
Hi @EhsanCode,

Hmm I see the problem. Even if you set collision to BlockAll, the road lines do not have a collision mesh. You could add it manually but you'd have to do so for each road line, doesn't seem like a very optimal solution.

I'm suspecting we can change the lidar ray-cast configuration to go on the visibility channel, it is probably slower but it should hit the right item every time. If this works, it would fix the issues with the dynamic agents too. I'll try to get some time next week to experiment with this.

Btw, we were talking about different ray-cast options in the #cpp channel of our [Discord](https://discord.gg/vNVHXfb).

**Comment by EhsanCode** [comment]
Hi @nsubiron 
Thank you so much for consideration.
As you mentioned, It seems collision mesh is not able to present some material such as fences. For example, as shown in the following image:

![fence](https://user-images.githubusercontent.com/22130114/41161478-4e74f12c-6b33-11e8-8cba-f24ad931fac4.png)

fence structure is not detectable with this method. I do not know if it is possible on the visibility channel?

Thank you so much
Best regards,
Ehsan

**Comment by xuwenqian66** [comment]
> Hi @nsubiron
> Thank you so much for your attention. I've enabled the collision on every roadLine content. Now, they have the same collision configuration as shown in this figure:
> ![image](https://user-images.githubusercontent.com/22130114/40829172-f65392ba-6582-11e8-81f9-953c49d843aa.png)
> 
> but still, no roadLine collision has been detected. Would you please let me know if I could do anything more to detect roadLine collision?
> Thanks again.



> I am trying to get the object class for LiDAR. I have modified ALidar::ShootLaser and I have added this code:
> `uint8_t ObjectLabel = static_cast<std::underlying_type<ECityObjectLabel>::type>(ATagger::GetTagOfTaggedComponent(*HitInfo.GetComponent()));`
> 
> But it seems there is a problem to get Vehicles and RoadLines labels. By tracking the issue I realized
> `GetWorld()->LineTraceSingleByChannel( HitInfo, LidarBodyLoc, EndTrace, ECC_MAX, TraceParams, FCollisionResponseParams::DefaultResponseParam );`
> never hit RoadLines and HitInfo never contains any component of Vehicles nor RoadLines.
> 
> In this visualization points are colored based on their labals, you can see there is no **RoadLine** label:
> 
> ![objectclass](https://user-images.githubusercontent.com/22130114/40641666-bffe3c02-631a-11e8-9dc2-2e80e1abb772.jpg)
> 
> But I could get this information from a 'SemanticSegmentation' camera.
> 
> ![semanticsegmentationcamera](https://user-images.githubusercontent.com/22130114/40641719-e50cdd00-631a-11e8-9f70-cffb0c3d439c.png)
> 
> Thank you so much,
> Best regards,
> Ehsan

Hello, I'm a beginner for this software.
May I ask you, how did you plot this point cloud out? How could you combine the UE4 with the lidar?

**Comment by marcgpuig** [comment]
Road lanes are now detected by the new LiDAR introduced in #3131.
