### ISSUE TITLE
Could Carla export simulation data like *.mp4 or some sensor data?

### ISSUE THREAD

**Issue by iamweiweishi** [carla-simulator/carla#4559]
I found that Carla could retrieve data to *.log, and then we could read the *.log using Carla API. 

But, I am trying to export video (for example *.mp4) and sensor (radar) data from Carla simulation environment. And then these data could be fed into our own algorithms. 

Does Carla support this?

Thank you.

**Comment by MattRowe18** [comment]
Hi 

CARLA exports images in formats such as PNG, not to video formats, but it's simple to convert an image sequence to a video using a number of open source or free tools. Refer to the example scripts supplied with CARLA (such as tutorial.py) to see how the sensors output data. The sensors have a "listen" function which takes a callback to save the data on each simulation step. The image sequence is then saved to a folder on your hard drive. You can then convert this image sequence to video using another tool such as QuickTime.

Thanks for your question
