### ISSUE TITLE
Carla axis rotation question

### ISSUE THREAD

**Issue by carlaUE4new** [carla-simulator/carla#4565]
what is the sign convention of rotation in Carla? XYZ is using left handle rule, so forward is positive direction in X, right is positive direction in Y , and up is positive direction in Z. How about rotation for those axis? if based on left hand rule, it is supposed clockwise direction is positive. However, when I looked at the PythonAPI document on Carla website (https://carla.readthedocs.io/en/0.9.12/python_api/#carlarotation), it seems those pictures show counterclockwise is positive. So, get confused

**Comment by MattRowe18** [comment]
@Axel1092 could you answer this question about rotation

thanks
