### ISSUE TITLE
May i use some of the images from carla's documentation in a research project?

### ISSUE THREAD

**Issue by Eduard6421** [carla-simulator/carla#4572]
Greetings!
I want to include the diagram of the Carla's Traffic Manager Architecture alongside some more images which can be found at
https://arxiv.org/pdf/1711.03938v1.pdf in my master thesis;
I have developed an AI which predicts future paths for pedestrians by making use of Carla and I need to describe the technologies used in the project; 
I will include links to the both the paper and carla docs;
Is this allowed?

**Comment by MattRowe18** [comment]
@Eduard6421 hi, it is perfectly fine for you to include any of the material in CARLA publications in your thesis with appropriate source citation, make sure to cite both the publication and also the project website. Thank you for using CARLA in your work
