### ISSUE TITLE
How can I add another camera (RGB and Depth) during the simulation?

### ISSUE THREAD

**Issue by rak7045** [carla-simulator/carla#4575]

**Comment by rak7045** [comment]
I am trying to collect aerial images with bounding box information and class label with an RGB and depth camera. Now I want to add another camera to create a scene like drone is taking the pictures. For reference, I am attaching the picture of the view.  Now, I want to have another view on the side. How can I do that? Just add another camera or is there anyway to do that?
![004438](https://user-images.githubusercontent.com/45998629/130741633-18202a5c-9e89-4ded-ac00-4c6c80929e6a.png)

**Comment by MattRowe18** [comment]
@rak7045 yes you can spawn multiple cameras to collect data on a scene, just repeat the process you use to spawn your first camera. Make sure you keep separate references in your script for each camera and ensure that you separate the output with different file paths. Refer to the scripts provided with CARLA to see how camera sensors are spawned.

**Comment by husamhamu** [comment]
@rak7045 Hi, can you share your code to collect the data? thanks

**Comment by husamhamu** [comment]
Thanks for your response @rak7045, I am actually interested in collecting a dataset like KITTI-dataset to train a model for monocular 3d object detection. There has been a work on gathering data like this in the following repo [https://github.com/Ozzyz/carla-data-export?utm_source=pocket_mylist](url) . But it does not work with the newer version of CARLA and I thought you are trying to do the same thing here with the new version of CARLA
