### ISSUE TITLE
turning off the street lights on the highway

### ISSUE THREAD

**Issue by alibukharai** [carla-simulator/carla#4576]
Hi, I am wondering if somehow to turn off the street lights on the highway

**Comment by Madecu** [comment]
Hi @alibukharai,
you can use the environment.py script we have in PythonAPI/util turn off the lightgroup "Street".
For more information you can watch a video we recorded talking about that:

https://www.youtube.com/watch?v=ZZaHevsz8W8&t=992s&ab_channel=CARLASimulator

**Comment by alibukharai** [comment]
Thanks, man, You are a life saver.
