### ISSUE TITLE
I think this is a bug for log level! it should be INFO instead of ERROR

### ISSUE THREAD

**Issue by FENGShuanglang** [carla-simulator/carla#4578]
https://github.com/carla-simulator/carla/blob/d23f3dc1340e47265eeea2b1b33b2d3a2d6d4f42/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp#L1969

**Comment by bernatx** [comment]
Sure, thanks for the correction. We changed from **Error** category to **Log** category

**Comment by MattRowe18** [comment]
@bernatx can we close this issue now?

**Comment by bernatx** [comment]
yes, it is already fixed in the new outcoming release 0.9.13
