### ISSUE TITLE
make: Nothing to do for 'PythonAPI'

### ISSUE THREAD

**Issue by schissmantics** [carla-simulator/carla#4581]
CARLA version: 0.9.12
Platform/OS: Ubuntu 18
Problem you have experienced: Unable to build python client
What you expected to happen: the opposite
Steps to reproduce: check the [notebook](https://colab.research.google.com/drive/1RyKcpf1_zz30g_L-01MkZyEuqEUq6e4-?usp=sharing)

**Comment by MattRowe18** [comment]
@schissmantics the notebook you provided no longer exists, if this problem persists please raise a new issue
