### ISSUE TITLE
Docker: error while loading shared libraries: libomp.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by basilevh** [carla-simulator/carla#4582]
I am following [this guide](https://carla.readthedocs.io/en/0.9.12/build_docker/) in an attempt to start separate CARLA instances in parallel and map them to different GPUs.

CARLA version: 0.9.12

Platform/OS: Ubuntu 18.04.5 LTS

Problem you have experienced: Cannot run CARLA in a Docker container. It just says the following:
`/home/carla/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping: error while loading shared libraries: libomp.so.5: cannot open shared object file: No such file or directory`

What you expected to happen: It should start the CARLA server.

Steps to reproduce: First, run `docker pull carlasim/carla:0.9.12`. Then, run `sudo docker run --privileged --gpus all --net=host -v /tmp/.X11-unix:/tmp/.X11-unix:rw carlasim/carla:0.9.12 /bin/bash ./CarlaUE4.sh -RenderOffScreen`.

Other information (documentation you consulted, workarounds you tried): I double checked that OpenMP (libomp5) and its dependencies are installed. I'm no expert on Docker, but it seems that this library is somehow not being loaded into the container. CARLA 0.9.12 runs 100% fine outside of Docker.

Thanks in advance for any ideas or suggestions.

**Comment by basilevh** [comment]
I think we are getting somewhere! I added the `--interactive` flag to your first command, which makes the bash shell persist, and then I could run the apt update and install commands just fine. I then did `docker commit <alphanumeric_id> carlasim/carla:0.9.12`, and reran `sudo docker run --privileged --gpus all --net=host -v /tmp/.X11-unix:/tmp/.X11-unix:rw carlasim/carla:0.9.12 /bin/bash ./CarlaUE4.sh -RenderOffScreen`. It now gives a different error message from before: Refusing to run with the root privileges. Perhaps I did something wrong along the way permission-wise?

**Comment by qhaas** [comment]
> The machine I'm using doesn't have a display. 

I had to `unset SDL_VIDEODRIVER` and run with `./CarlaUE4.sh -vulkan -RenderOffscreen` to keep it from exiting immediately for headless runs, per [Issue #4498](https://github.com/carla-simulator/carla/issues/4498#issuecomment-898644166).

**Comment by basilevh** [comment]
> > The machine I'm using doesn't have a display.
> 
> I had to `unset SDL_VIDEODRIVER` and run with `./CarlaUE4.sh -vulkan -RenderOffscreen` to keep it from exiting immediately for headless runs, per [Issue #4498](https://github.com/carla-simulator/carla/issues/4498#issuecomment-898644166).

Wow! Inside that thread, the `-graphicsadapter=1` (or =N for GPU index N) option is **exactly** what I was looking for. Thank you so much for linking it! I've already spent so much time looking for ways to run multiple CARLA instances on different GPUs, only to have the solution turn out to be much simpler than painstakingly trying to get this Docker container to work.. ;-)

**Comment by GooVincent** [comment]
> Install libomp5 inside the docker:
> `sudo docker run -u root --privileged --gpus all --net=host -v /tmp/.X11-unix:/tmp/.X11-unix:rw carlasim/carla:0.9.12 /bin/bash`
> `#apt update`
> `#apt install libomp5`
> 
> Open a new terminal and commit your changes:
> `docker commit <CONTAINER_NAME> <IMAGE:TAG>`
> 
> `sudo docker run -u carla --privileged --gpus all --net=host -v /tmp/.X11-unix:/tmp/.X11-unix:rw carlasim/carla:0.9.12 /bin/bash ./CarlaUE4.sh -RenderOffScreen`

I tried the following cmd
`docker run --privileged --gpus all --net=host -e DISPLAY=$DISPLAY -it carlasim/carla:0.9.12 /bin/bash ./CarlaUE4.sh `
Could see the process with nvidia-smi.
But run
`docker run --privileged --gpus all -p 2000-2002:2000-2002 -e DISPLAY=$DISPLAY --net=hostcarlasim/carla:0.9.12 /bin/bash ./CarlaUE4.sh` Couldn't see any process in the output of nvidia-smi.

Please any ideas or advice, thanks.

**Comment by Pilex1** [comment]
Hi, how did you resolve the `Refusing to run with the root privileges`?
