### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by ItsXianqi** [carla-simulator/carla#4587]
**CARLA version**: 0.9.12
**Platform/OS: Ubuntu**: 16.04
Hello  developers, thanks for your work.
I'm trying to install Precompiled carla 0.9.12 on Ubuntu 16.04, when i excuted
`./CarlaUE4.sh`
I met the error message
`/home/hexianqi/opt/CARLA_0.9.12/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.27 not found (required by /home/hexianqi/opt/CARLA_0.9.12/CarlaUE4/Binaries/Linux/../../Plugins/Carla/CarlaDependencies/lib/libChronoEngine.so)
/home/hexianqi/opt/CARLA_0.9.12/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.27 not found (required by /home/hexianqi/opt/CARLA_0.9.12/CarlaUE4/Binaries/Linux/../../Plugins/Carla/CarlaDependencies/lib/libChronoEngine_vehicle.so)`

It seems carla 0.9.12 requires GLIBC_2.27, and Ubuntu 16.04 is GLIBC_2.23. Because some other packages require Ubuntu 16.04,  I don't want to upgrade to Ubuntu 18.04. How can I solve the problem without changing the editon of Ubuntu?

Thanks and best wishes.

**Comment by qhaas** [comment]
Given the [era of 'free' Ubuntu 16.04 updates has ended](https://ubuntu.com/about/release-cycle), doubtful the upstream team is testing new releases against it.  You can likely work-around glibc issues using docker or singularity containers.

**Comment by ItsXianqi** [comment]
> Given the [era of 'free' Ubuntu 16.04 updates has ended](https://ubuntu.com/about/release-cycle), doubtful the upstream team is testing new releases against it. You can likely work-around glibc issues using docker or singularity containers.

Got it, thanks

**Comment by zhaoyongqi2022** [comment]
Hi, I encounter the same issue. Did you successfully solve this problem? Thank you in advance!

**Comment by ItsXianqi** [comment]
> Hi, I encounter the same issue. Did you successfully solve this problem? Thank you in advance!

I changed to Ubuntu 20.04, sorry didn't fix it.

**Comment by zhaoyongqi2022** [comment]
> > Hi, I encounter the same issue. Did you successfully solve this problem? Thank you in advance!
> 
> I changed to Ubuntu 20.04, sorry didn't fix it.

Hi, sorry to bother you again. Did you mean that you didn't solve the problem even after updating the system to 20.04?

**Comment by ItsXianqi** [comment]
> > > Hi, I encounter the same issue. Did you successfully solve this problem? Thank you in advance!
> > 
> > 
> > I changed to Ubuntu 20.04, sorry didn't fix it.
> 
> Hi, sorry to bother you again. Did you mean that you didn't solve the problem even after updating the system to 20.04?

No, I change to 20.04 and it is fixed without extra modification

**Comment by zhaoyongqi2022** [comment]
> > > > Hi, I encounter the same issue. Did you successfully solve this problem? Thank you in advance!
> > > 
> > > 
> > > I changed to Ubuntu 20.04, sorry didn't fix it.
> > 
> > 
> > Hi, sorry to bother you again. Did you mean that you didn't solve the problem even after updating the system to 20.04?
> 
> No, I change to 20.04 and it is fixed without extra modification

Thanks for your reply!
