### ISSUE TITLE
CARLA 0.9.12 builds carla-0.9.11-py3.7-win-amd64.egg for 0.9.11

### ISSUE THREAD

**Issue by iklimchy** [carla-simulator/carla#4589]
CARLA version:  0.9.12 
Platform/OS: Win 10 64-bit
Problem you have experienced: CARLA 0.9.12 builds carla-0.9.11-py3.7-win-amd64.egg
What you expected to happen: CARLA 0.9.12 builds carla-0.9.12-py3.7-win-amd64.egg
Steps to reproduce: make PythonAPI

**Comment by Axel1092** [comment]
Hi @iklimchy, indeed due to an error the egg file was named incorrectly in 0.9.12 but it still contains the latest CARLA features. It is a naming issue only.
