### ISSUE TITLE
After compiling Carla server by "make launch" (windows) , the built UE4Editor.exe cannot work but only with path to CarlaUE4.uproject  

### ISSUE THREAD

**Issue by Yebihashu** [carla-simulator/carla#4591]
CARLA version:
Built version of 9.12
Building Carla was done exactly like instructed at : https://carla.readthedocs.io/en/0.9.12/build_windows with python 3.8.10

Platform/OS:
Windows 10

Problem you have experienced:
Building UE4Editor.exe using VS2019 was ok. I could then run UE4Editor.exe from prompt window and the editor runs
![image](https://user-images.githubusercontent.com/55840622/131572029-9540e4d1-ed48-4ccf-aa2a-ce81fcf5cd04.png)

But after compiling server using "make launch", I can't run UE4Editor.exe  anymore 
![image](https://user-images.githubusercontent.com/55840622/131572573-f66dfa78-6252-4cdc-95be-282b310b43e3.png)

The only thing I can do is to run it with a path to CarlaUE4.uproject  
![image](https://user-images.githubusercontent.com/55840622/131573219-532c1347-160a-4527-b9a7-4dc7aa6ba609.png)

this will open the editor with Carla as shown
![image](https://user-images.githubusercontent.com/55840622/131572753-d9e6b64a-a7d6-4d5c-8afd-7980c13cd866.png)

If I will compile UE4Editor.exe again in VS2019, then I will be able again,  to run UE4Editor.exe alone, 
but trying to run Carla with the editor failed

![image](https://user-images.githubusercontent.com/55840622/131573580-e4f1e76b-2713-4010-bfae-59340b4e61e0.png)

What you expected to have both possibilities:
To compile UE4Editor and Carla , and be able to:
(1) Use UE4Editor.exe  without Carla by running UE4Editor.exe  
(2) Use UE4Editor.exe  also with Carla by running UE4Editor.exe  [path to carla]/CarlaUE4.uproject  

Thanks

**Comment by MattRowe18** [comment]
@bernat could you take a look at this please

**Comment by hch-xmu** [comment]
Have you solve this,  I encounter this question aslo, Could you tell me how you do
