### ISSUE TITLE
How to convert a depth image to disparity

### ISSUE THREAD

**Issue by SaintArthurThomas** [carla-simulator/carla#4592]
CARLA version: 0.9.11
Platform/OS: Ubuntu 20.04
Problem you have experienced: To train a network for stereo matching, I designed a binocular system, in which RGB cameras are attached to a vehicle at **[x=1, y=-0.5, z=1.5]** and **[x=1, y=0.5, z=1.5]** respectively, and depth camera at **[x=1, y=-0.5, z=1.5]**. All configurations are default except locations described above. 
I am wondering how to convert the depth image to the disparity map.

**Comment by MattRowe18** [comment]
@SaintArthurThomas hi

The depth sensor in CARLA is calculated from the ground truth (virtual) distance of objects from the sensor, by measuring the distance traveled from rays cast from the sensor pixels. It is not calculated from a stereo camera pair, so it has no associated disparity map. You could calculate a disparity map from the stereo pair of cameras that you have attached to your vehicle, using openCV like here https://docs.opencv.org/3.4/dd/d53/tutorial_py_depthmap.html

Hope this helps
