### ISSUE TITLE
is it possible to change left hand drive in carla

### ISSUE THREAD

**Issue by 7grajesh** [carla-simulator/carla#4598]
i have created  own map  ( Indian drive ) and need to simulate left hand drive. can you help me out how to change left hand traffic rules in CARLA. one way road is working forward / backward but while simulate bidirectional is pick only right hand drive.
CARLA version: 0.9.12
Platform/OS: Ubuntu
Problem you have experienced: i created own map in left hand traffic rules like uk, india. while generate to waypoints its AV simulate right drive, so i am trying left hand drive 
What you expected to happen: Left hand drive

**Comment by jackbart94** [comment]
We don't support left hand drive yet, sorry.
