### ISSUE TITLE
Howto create a DLC for CARLA

### ISSUE THREAD

**Issue by juaxix** [carla-simulator/carla#460]
If you want to create additional content for CARLA, you have to create a plugin with downloadable content. 

This issue is designed to add more info about that particular process.

We will be using this [link](http://www.tomlooman.com/add-mod-support-to-your-unreal-engine-4-game/) as reference.

# Steps using Unreal Engine 4.18.3 and CARLA 0.8.2 for development
You need to download everything and have a working version of CARLA using the UE4 Editor. 
The overall of the process is this:

1. - Create launcher profile for the full version of CARLA (for Windows or Linux)
2.  - Cook CARLA
3.  - Create a DLC plugin and put the content inside
4.  - Create launcher profile for the DLC
5.  - Cook DLC 
6.  - Test the DLC pak by copying it in the CARLA paks folder

## ProjectLauncher - Profile
You need to create 2 profiles in the launcher, one to cook all the content in CARLA and another for any additional DLC you may want to add.
Open CARLA project with _Unreal Editor_ ( _CARLA/Unreal/CarlaUE4/CarlaUE4.uproject_ ) and go to the ProjectLauncher by using the menu: _Window -> Project Launcher_
![image](https://user-images.githubusercontent.com/996806/40907251-877634e8-67e3-11e8-9106-fe0920d5bde8.png)

### 1) Create the **Full version _Launcher Profile_**
In the UE4 Editor - _ProjectLauncher_ window go to the Custom Launch Profiles tab section and click in the plus "+" icon to add a new profile. 
These are the options to choose :

- **Name**: "CARLA - Full Game"

- **Project**: Any Project

- **Build**: Do you wish to build: checked ✔
  - Build Configuration: Development

- **Cook**: By the Book
    - Cooked Platforms: WindowsNoEditor (or LinuxNoEditor) 
    - Cooked Cultures: en
    - Cooked Maps: should be Town01, Town02, etc.
    - Release / DLC / Patching Settings:
        - Create a release version of the game for distribution: checked ✔
        - Name of the new release to create: 0.8.2
        - Release version this is based on: 0.8.2
        - Generate patch: not-checked ✘
        - Build DLC: not-checked ✘
        - Name of the DLC to build: <empty>
        - Include engine content: not-checked ✘
     - Advanced Settings: 
        - Iterative cooking : Only cook content modified from previous cook: 0.8.2
        - Stage base release pak files: not-checked ✘
        - Compress content: checked ✔
        - Add a new patch tier: not-checked ✘
        - Save packages without versions: checked ✔
        - Num cookers to spawn: 0
        - Store all content in a single file (Unreal Pak) : checked ✔
        - Encrypt ini files (only with use pak file): not-checked ✘
        - Generate Chunks: not-checked ✘
        - Don't include editor content in the build: checked ✔
        - Http Chunk Install Settings (by default, disabled)
        - Cooker build configuration: Development
        - Additional Cooker Options: <empty>

- **Package**
  - How would you like to package the build: Package & store locally
  - Local Directory Path: ...
  - Is this build for distribution to the public: not-checked ✘

- **Archive**
  - Do you wish to archive?: not-checked ✘

- **Deploy**
  - How would you like to deploy the build? : Do not deploy.

- **Launch**
  - The build is not being deployed.

One you created this launcher profile ,go Back to ProjectLauncher main screen by using the top-right button "Back" and in the Custom Launch Profiles tab there should be appeared a new profile named "CARLA - Full Game".
![image](https://user-images.githubusercontent.com/996806/40908566-79534ee2-67e7-11e8-81e5-18c282ccdb0b.png)

### 2) Launch the **Full version _Launcher Profile_**
Click now in the Launch profile button and it will run the automation tool to build the content.

If everything worked you should have something like this log screen:

![image](https://user-images.githubusercontent.com/996806/40909527-1334beea-67ea-11e8-8a06-9a6f52492233.png)
In my case the staging directory is: 
_E:\CARLA\Unreal\CarlaUE4\Saved\StagedBuilds\WindowsNoEditor_

and it is possible to launch this release version just using CarlaUE.exe from that dir.

![image](https://user-images.githubusercontent.com/996806/40909800-c627dcf8-67ea-11e8-950c-d929b2961025.png)

> CarlaUE4.exe -windowed -ResX=640 -ResY=480

_In my example I changed the default vehicle with a bike in the CarlaSettings.ini I used to pack the project._

## DLC Plugins - extending CARLA content
You can add maps (levels), cars, npcs, or other types of contents to CARLA using a DLC plugin, basically, it's a simple plugin with a content folder.

### 3) Create a DLC plugin
Go to the main screen of Unreal Editor and use the menu Edit -> Plugins
![image](https://user-images.githubusercontent.com/996806/40910004-4a474488-67eb-11e8-90f4-bbb6a3bcfbab.png)
in the plugins screen click on "_New Plugin_" button at the bottom right corner.
Select the "Content Only" and name it, for example, for me it's SimpleMap cause I want to add a simple level as additional content dlc.

![image](https://user-images.githubusercontent.com/996806/40910414-5bd3e55c-67ec-11e8-91fb-90b4be5ebf8c.png)

Hit "Create Plugin" button now, and it would add
![image](https://user-images.githubusercontent.com/996806/40910532-aa4f2660-67ec-11e8-8d81-2ffc7f4d8244.png)
In the main view of the Unreal Editor you should now see a new Content folder for your plugin name, in my case it is SimpleMap Content, if you don't see it, try to change the View Options of the Content Browser:
![image](https://user-images.githubusercontent.com/996806/40910622-eb28caa6-67ec-11e8-80f6-e3526d4582bf.png)

Put the content you want to cook inside that Content folder.
![image](https://user-images.githubusercontent.com/996806/40911063-1f0fea38-67ee-11e8-8e14-fb24a81b4360.png)

### 4) Create the **DLC _Launcher Profile_**
Go to the _ProjectLauncher_ window and create a new profile

These are the options to choose :

- **Name**: "CARLA DLC Simple Map"

- **Project**: CarlaUE4 (choose it from your hard drive)

- **Build**: Do you wish to build: checked ✔
  - Build Configuration: Development

- **Cook**: By the Book
    - Cooked Platforms: WindowsNoEditor (or LinuxNoEditor) 
    - Cooked Cultures: en
    - Cooked Maps: <nothing>
    - Release / DLC / Patching Settings:
        - Create a release version of the game for distribution: not-checked ✘
        - Name of the new release to create: <empty>
        - Release version this is based on: 1.0
        - Generate patch: not-checked ✘
        - Build DLC: checked ✔
        - Name of the DLC to build: <your dlc name> - for the sample here: SimpleMap
        - Include engine content: checked ✔
     - Advanced Settings: 
        - Iterative cooking : Only cook content modified from previous cook: 1.0
        - Stage base release pak files: not-checked ✘
        - Compress content: checked ✔
        - Add a new patch tier: not-checked ✘
        - Save packages without versions: checked ✔
        - Num cookers to spawn: 0
        - Store all content in a single file (Unreal Pak) : checked ✔
        - Encrypt ini files (only with use pak file): not-checked ✘
        - Generate Chunks: not-checked ✘
        - Don't include editor content in the build: checked ✔
        - Http Chunk Install Settings (by default, disabled)
        - Cooker build configuration: Development
        - Additional Cooker Options: <empty>

- **Package**
  - How would you like to package the build: Package & store locally
  - Local Directory Path: <dir to save your DLC plugin>
  - Is this build for distribution to the public: not-checked ✘

- **Archive**
  - Do you wish to archive?: not-checked ✘

- **Deploy**
  - How would you like to deploy the build? : Do not deploy.

- **Launch**
  - The build is not being deployed.

Go Back to the ProjectLauncher main screen.

### 5) Launch the **DLC _Launcher Profile_**

Click now in the Launch profile button of the DLC Launcher profile you have just created and it will run the automation tool to build the content of your DLC.
If the build fails in the package phase with an error like this:

Assertion failed: bSucceeded [File:D:\Build\++UE4+Release-4.18+Compile\Sync\Engine\Source\Editor\UnrealEd\Private\CookOnTheFlyServer.cpp] [Line: 5955] 

```
0x00000000E2CAF218 KERNELBASE.dll!UnknownFunction []
0x00000000BB4476D4 UE4Editor-ApplicationCore.dll!FWindowsErrorOutputDevice::Serialize() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\applicationcore\private\windows\windowserroroutputdevice.cpp:65]
0x00000000AABB330B UE4Editor-Core.dll!FOutputDevice::Logf__VA() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\misc\outputdevice.cpp:70]
0x00000000AAB447F9 UE4Editor-Core.dll!FDebug::AssertFailed() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:414]
0x00000000A70E9C37 UE4Editor-UnrealEd.dll!UCookOnTheFlyServer::StartCookByTheBook() [d:\build\++ue4+release-4.18+compile\sync\engine\source\editor\unrealed\private\cookontheflyserver.cpp:5957]
0x00000000A6F87B0C UE4Editor-UnrealEd.dll!UCookCommandlet::CookByTheBook() [d:\build\++ue4+release-4.18+compile\sync\engine\source\editor\unrealed\private\commandlets\cookcommandlet.cpp:870]
0x00000000A6FAF391 UE4Editor-UnrealEd.dll!UCookCommandlet::Main() [d:\build\++ue4+release-4.18+compile\sync\engine\source\editor\unrealed\private\commandlets\cookcommandlet.cpp:583]
0x0000000026E4D25F UE4Editor-Cmd.exe!FEngineLoop::PreInit() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:2167]
0x0000000026E4525A UE4Editor-Cmd.exe!GuardedMain() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\launch.cpp:127]
0x0000000026E454AA UE4Editor-Cmd.exe!GuardedMainWrapper() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:134]
0x0000000026E52379 UE4Editor-Cmd.exe!WinMain() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:210]
0x0000000026E53193 UE4Editor-Cmd.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253]
0x00000000E40A3034 KERNEL32.DLL!UnknownFunction []
0x00000000E6291551 ntdll.dll!UnknownFunction []
0x00000000E6291551 ntdll.dll!UnknownFunction []

```
it's because there is an engine bug, you need [this files to fix it](https://gist.github.com/juaxix/79ee102f159e1c92d93c6cd920d39d4c)

### 6) Test the DLC pak by copying it in the folder: 
Copy your cooked pak from the DLC plugin dir:
_SimpleMap\WindowsNoEditor\CarlaUE4\Plugins\SimpleMap\Content\Paks\WindowsNoEditor_
to
_CARLA/Unreal/CarlaUE4/Saved/StagedBuilds/WindowsNoEditor/_
where SimpleMap is the name of your DLC plugin 

Test this new level in the DLC pak by launching CARLA with the level name as first parameter.

> **Important** : you need to remove all the DLC plugins to make new builds of the full version of CARLA because the engine would not register the plugin twice if you cook the full version with the DLCs included. Right now, there is a bug in the engine that prevents the plugins to be loaded as DLCs, we are waiting for a patch.

To know more about how to make contents for CARLA, go to 
http://carla.readthedocs.io.

child of #438

**Comment by juaxix** [comment]
If you don't want to modify the Unreal Engine source code, there is another way, using patching.

These are the steps to do it.
1) Create ProjectLauncher profile to build the game in full (without additional assets) - FullGame
2) Do the cook of assets, build the game for Windows (or other platform), use the projeclauncher profile launch button for FullGame profile
3) Create additional assets now, cook them and create a projectlauncher profile for patching - Patch
4) launch the patch projectlauncher profile
5) copy the new patch pak _P (patch) in the FullGame build CarlaUE4/Content/Paks
6) the CARLA build in FullGame build dir will load the new assets from this pak 

FullGame profile:

![image](https://user-images.githubusercontent.com/996806/41028658-32998612-697a-11e8-9eca-b12bc81daa8e.png)

where your default map will be Town01 and Town02

![image](https://user-images.githubusercontent.com/996806/41028717-5098441e-697a-11e8-96a0-d1c7112fc154.png)

Patch profile:

![image](https://user-images.githubusercontent.com/996806/41028525-ec1830d0-6979-11e8-8a65-2e26c5048e68.png)

![image](https://user-images.githubusercontent.com/996806/41028601-161a345a-697a-11e8-96e9-837cbf377d35.png)

**Comment by KevinYuk** [comment]
How long does it take to build LinuxNoEditor release version?
