### ISSUE TITLE
 Simulate Tesla's cameras

### ISSUE THREAD

**Issue by xia0long** [carla-simulator/carla#4605]
Hi there,

This problem has nothing to do with carla itself, but I think maybe those who are using carla will have the answer. What I want to ask is where I can find the calibration parameters of the 8 cameras in Tesla model 3? I want to simulate its cameras in carla, and I think it would be OK if there were similar calibration parameters.

best regard

**Comment by Domsall** [comment]
Tesla is always publishing data/hardware specs of their cars. You could maybe try to ask them directly.
What I also just found are their triple front cameras:
https://www.eetasia.com/teslas-hardware-retrofits-for-model-3/
https://www.marklines.com/en/teardown/tesla_model3

**Comment by xia0long** [comment]
@Domsall 
Thanks a lot! I tried to set up the cameras with the parameters given by tesla, then I found that someone has already done this, here is the parameter data, hope it can help other people who also have this problem.

```py
CAMERA_CONFIGS = [
    ["front1", carla.Transform(carla.Location(x=1.5, y=-0.1, z=2.4), carla.Rotation(yaw=0)), 45, (0, 0), None],
    ["front2", carla.Transform(carla.Location(x=1.5, y=0, z=2.4), carla.Rotation(yaw=0)), 120, (UNIT_WIDTH, 0), None],
    ["front3", carla.Transform(carla.Location(x=1.5, y=0.1, z=2.4), carla.Rotation(yaw=0)), 90, (2*UNIT_WIDTH, 0), None],
    ["left_front", carla.Transform(carla.Location(x=0, y=-1.1, z=2.4), carla.Rotation(yaw=315)), 90, (0, UNIT_HEIGHT), None],
    ["right_front", carla.Transform(carla.Location(x=0, y=1.1, z=2.4), carla.Rotation(yaw=45)), 90, (2*UNIT_WIDTH, UNIT_HEIGHT), None],
    ["left_rear", carla.Transform(carla.Location(x=1.0, y=-1.1, z=1), carla.Rotation(yaw=225)), 120, (0, 2*UNIT_HEIGHT), None],
    ["rear", carla.Transform(carla.Location(x=-1.5, y=0, z=2.4), carla.Rotation(yaw=180)), 120, (UNIT_WIDTH, 2*UNIT_HEIGHT), None],
    ["right_rear", carla.Transform(carla.Location(x=1.0, y=1.1, z=1), carla.Rotation(yaw=135)), 120, (2*UNIT_WIDTH, 2*UNIT_HEIGHT), None]
]
```
