### ISSUE TITLE
firetruck gets stuck at intersections in Town01 when using autopilot

### ISSUE THREAD

**Issue by qhaas** [carla-simulator/carla#4606]
Related to Issue #3860

CARLA version: 0.9.12
Platform/OS: Ubuntu 18.04
Problem you have experienced: certain vehicle models (e.g. `vehicle.carlamotors.firetruck`) are too big for some intersections and will get stuck even with autopilot / traffic manager enabled
What you expected to happen: `vehicle.carlamotors.firetruck` is able to complete turns at all bundled map intersections with autopilot (traffic-manager) enabled.
Steps to reproduce:  run [carla_debug.txt](https://github.com/carla-simulator/carla/files/7107318/carla_debug.txt), watch for the firetruck to get stuck at an intersection in Town01, per the attached photo ![stuck_truck.png](https://user-images.githubusercontent.com/34581474/132038269-16b1d55d-a837-4708-9afd-e4aa0797e792.png).

**Comment by jackbart94** [comment]
Unfortunately, due to the guardrail placed there, and the route provided from the OpenDrive file, Firetrucks are not able to perform that turn in Town01. It's a known issue, but the map is fairly old and the model is new.
