### ISSUE TITLE
How to ingest a map in Carla windows package

### ISSUE THREAD

**Issue by tobu1** [carla-simulator/carla#4615]
Hi everyone,

I need to ingest a map in a Carla package on windows. I already ingest the map in the source version of Carla and created a packaged version with "make package". That worked but the new map was not available in the packaged version. Is it possible on windows? How can I do that? 

CARLA version: 0.9.12
Platform/OS: Windows 10

**Comment by bernatx** [comment]
Hi,
the **make package** command only makes a CARLA package with his standard maps, but not anything external. In your case, you need to make the package of your map using the command **make package ARGS="--packages=<your_package>"**. That will package your map in a ZIP or TAR.GZ file.
Then you need to import that map on your CARLA package. This means to decompress all what is inside the zip/gz  file into your package, replacing any file you need to overwrite.
For the Ubuntu platform there is an importAssets.sh script that will make that for you (if you copy the .gz into the import folder). For windows you need to decompress manually, but that is straightforward.

You have documentation here: https://carla.readthedocs.io/en/0.9.12/tuto_A_create_standalone/

I hope that helps.
