### ISSUE TITLE
I added a custom vehicle, but it shook left and right

### ISSUE THREAD

**Issue by ReCodeLife** [carla-simulator/carla#4618]
**CARLA version**:0.9.11
**Platform/OS**:win10
**Problem you have experienced:**
I tried to add a custom vehicle. This vehicle has only the simplest board and four wheels.When I finished, I put the vehicle into carlaue4, and he started to move by himself and sway left and right, but I didn't set the throttle and steering. How should I troubleshoot this problem.

**What you expected to happen:**
The vehicle stopped on the road.

![GIF](https://user-images.githubusercontent.com/48639311/132441237-c4e4dcce-99cf-4667-a09a-131baf52ca75.gif)

**Comment by gsmario** [comment]
Hi, thanks for reaching us for help.
Can you post a screenshot with the skeleton please?
Thanks again.
