### ISSUE TITLE
Use the Python script in the PythonAPI in the docker environment to access Carla sever outside the docker environment

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla#4623]
Hello,carla team!

I start carla server outside a docker environment,and start a Python script(manul_control.py) in Carla’s PythonAPI folder in the docker environment,so I get the message:
`time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000`

How should I establish communication between   the  docker's outside environment and its inside environment?

**Comment by nick-marnik** [comment]
To confirm, is the carla server running on the same machine that is running Carla in a Docker container?

**Comment by SH-Tan** [comment]
How to use the python in the Carla docker container, when I try to use python, it says there is no python command in this container?

**Comment by MattRowe18** [comment]
@JackRen88 can you clarify where you are running your Python scripts? Are you trying to run python from your local machine, or from within the docker container itself? If you are running from your local machine, you need to identify the IP address to reference the Docker container. If you are running scripts inside the container 'localhost' may map directly to the host machine and not to the container itself, depending on your configuration. 

See here for some information about Docker networking https://www.freecodecamp.org/news/how-to-get-a-docker-container-ip-address-explained-with-examples/
