### ISSUE TITLE
'C:\Program' not recognized as command in compiling server or PythonAPI

### ISSUE THREAD

**Issue by xilinzhou** [carla-simulator/carla#4628]
CARLA version: 0.9.12
Platform/OS: Windows 10
Problem you have experienced: unable to make PythonAPI or make launch

Hello! We're at the final step in the build (compiling PythonAPI and server). We're running into the error `NMAKE : fatal error U1077: 'C:\Program' : return code '0x1'`. Basically it's not recognizing 'C:\Program' as a command in our preset path to the make bin folder.

Here's the command output:
![image (1)](https://user-images.githubusercontent.com/21992873/132861001-4ede1809-b5ab-4d61-bdba-1b1290d36ac9.png)

**Comment by xilinzhou** [comment]
Hi, an update. We’ve downgraded to Carla 0.9.11 and are still encountering the exact same issue. Here’s the other part of the error message.
 
![9D00533A-8331-49CF-BFDE-3C40D4323AF8](https://user-images.githubusercontent.com/21992873/134178601-79cd055a-f58d-43dd-a269-d2c84d230e37.png)

**Comment by Axel1092** [comment]
Hi @xilinzhou, aparently your visual studio installation is broken. Cmake is not able to use it to compile the zlib library.
