### ISSUE TITLE
Is there any solution to create a custom map without using RoadRunner

### ISSUE THREAD

**Issue by ghostsun89** [carla-simulator/carla#4629]
I want to create some custom maps from the OpenStreetMap. But I don't have the license of using RoadRunner. So is there any other way to create the map info and convert to the Autoware map format?

**Comment by XGodina** [comment]
Hi @ghostsun89 

Create a custom map from OpenStreetMap, I don't think you can. Although, you can use the OpenStreetMap to create it in CARLA. You can select an area and CARLA turns it into a map. This is the link.

https://carla.readthedocs.io/en/0.9.13/tuto_G_openstreetmap/#generate-maps-with-openstreetmap
