### ISSUE TITLE
Whether carla can run in python 32 environment

### ISSUE THREAD

**Issue by DanielTian90** [carla-simulator/carla#4635]
Recently I built some .so files in 32-bit architecture, so change my python environment to python 32.
Then carla report this error: "/home/user/.cache/Python-Eggs/carla-0.9.11-py3.7-linux-x86_64.egg-tmp/carla/libcarla.cpython-37m-x86_64-linux-gnu.so: wrong ELF class: ELFCLASS64"
Whether carla can run in python 32 environment?

**Comment by jackbart94** [comment]
You're clearly building it for x86_64. That's not 32 bit. I don't know if CARLA can run on 32-bit architecture, but for sure we aren't really prepared to run on 32-bit. You'll probably need to change quite a few things, starting from generating an .egg compatible with 32-bit architecture.
