### ISSUE TITLE
when i was debugging my code,Carla crash.

### ISSUE THREAD

**Issue by errorJY** [carla-simulator/carla#464]
That's what happened:
![image](https://user-images.githubusercontent.com/34939340/40735514-eee3f738-646d-11e8-82d2-10974c9074ae.png)
And my driver is newest...
![image](https://user-images.githubusercontent.com/34939340/40735602-28e72f5e-646e-11e8-8dcd-8774ee825417.png)

**Comment by marcgpuig** [comment]
Hey @errorJY.
Have you tried `-opengl3` option?

**Comment by errorJY** [comment]
hello.@marcgpuig 
I'm looking the #85 .But i can't get it how to use -openg13...
Sad.

**Comment by marcgpuig** [comment]
@errorJY
Which part do you don't get?
