### ISSUE TITLE
How to run Carla unreal project from Carla package?

### ISSUE THREAD

**Issue by zeus-arval** [carla-simulator/carla#4650]
Hello!

I am newbie in Unreal engine.
Is there a possibility, to run Carla unreal project( CarlaUE4.uproject ) from Carla package(not from repository)?
I wanted to add a new vehicle to Carla simulations, and to run a server without running Unreal Engine.
When I run  CarlaUE4.uproject, i get an issue, that some modules are missing (CarlaUE4 and Carla).
![image](https://user-images.githubusercontent.com/72491384/133566106-6cef5e72-de46-4dda-a348-8cffe4a16ac1.png)

Could you suggest anything, please?

**Comment by XGodina** [comment]
Hello, @zeus-arval 

If you want to add a new vehicle you need to install Unreal and set the vehicle on the Unreal Editor.
