### ISSUE TITLE
Can Carla sensors detect sunlight condition?

### ISSUE THREAD

**Issue by aqvia** [carla-simulator/carla#4656]
CARLA version: 0.9.12
Platform/OS: WIndows10

Problem you have experienced:
Can Carla (with ScenarioRunner, OpenScenario) perform simulations that consider the effects of sunlight(the position of the sun, etc) and its reflection?

**Comment by MattRowe18** [comment]
@aqvia hi

Yes, the position of the sun in the CARLA simulation can be altered to any angle, you can set azimuth and elevation, so you can simulate a low sunset or high noon and anything in between. In the python API example scripts, you will find a script called dynamic_weather.py. If you run this script, you will see the sun and weather changing, take a look in the script for how to change the sun position. Also, take a look here https://carla.readthedocs.io/en/0.9.3/python_api_tutorial/

weather = carla.WeatherParameters(sun_azimuth_angle=50.0, sun_altitude_angle=70.0)
world.set_weather(weather)
print(world.get_weather())

Hope this helps
