### ISSUE TITLE
make launch carla 9.10

### ISSUE THREAD

**Issue by pantelmen** [carla-simulator/carla#4658]
Hello i am trying to make launch carla 9.10 on  ubuntu 20.04 but i had this problem 

fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 2 errors generated.
3 warnings and 20 errors generated.
make[1]: *** [Makefile:290: CarlaUE4Editor] Error 5
make[1]: Leaving directory '/home/pantel/carla/Unreal/CarlaUE4'
make: *** [Util/BuildTools/Linux.mk:7: launch] Error 2

any idea?? ty

**Comment by Axel1092** [comment]
Hi @pantelmen, we would need the entire log to see what errors you found to be able to help you.
