### ISSUE TITLE
Can I access Carla simultaneously using different ports?

### ISSUE THREAD

**Issue by 98luobo** [carla-simulator/carla#4659]
CARLA version: 0.9.11
Platform/OS: Windows and Linux

Problem: I am using Carla to conduct the multi-agent experiment. My idea is to access the server through different ports at the same time to achieve a more real parallel effect. However, I found that only one port was valid for simultaneous operations. So I would like to ask whether Carla has the ability of multi-port simultaneous access? If so, can you give us some ideas or suggestions? Thanks in advance!!!

**Comment by 98luobo** [comment]
P.S. I did this to be able to control the different vehicle at the same time.

**Comment by bernatx** [comment]
Hi, you can only connect to the same CARLA server through the same port, but you can connect multiple scripts that can do different things, like controlling different vehicles each. Just connect all the scripts to the same IP:PORT and you will be connected to the server, and can do different things.
I hope it helps
