### ISSUE TITLE
Stuck at "make launch" - make sure you build ShaderCompileWorker.

### ISSUE THREAD

**Issue by mimits** [carla-simulator/carla#4660]
CARLA version: 12
Platform/OS: windows
Problem you have experienced: can't launch, last thing I did was make PythonAPI
What you expected to happen: to launch
Steps to reproduce: I did everything as documentation told me
![Screenshot_1](https://user-images.githubusercontent.com/26203762/133925581-0cdece52-84f0-43af-98d9-2949e7048bc1.png)

**Comment by TrinhTuanHung2021** [comment]
I also got an error while making launch.  
there are 2 ways to run Carla. If you can't make launch, you can run it directly 

https://github.com/carla-simulator/carla/releases

**Comment by mimits** [comment]
Thank you, I did make it, I had a bug in Visual Studio, So I just did everything from the start and this time I waited for visual to build correctly. I got a new problem now, I can't get past "make import" which says that there is no module name "carla"

**Comment by TrinhTuanHung2021** [comment]
> Thank you, I did make it, I had a bug in Visual Studio, So I just did everything from the start and this time I waited for visual to build correctly. I got a new problem now, I can't get past "make import" which says that there is no module name "carla"

**Comment by mimits** [comment]
![image](https://user-images.githubusercontent.com/26203762/134769972-f6e1f03b-6b85-42fd-93ff-2d9983d08e61.png)
so I install Carla as u say. but not this happens

**Comment by TrinhTuanHung2021** [comment]
![image](https://user-images.githubusercontent.com/82990411/134770177-419e6ad5-22e6-4a26-acf0-18901b696b8d.png)

**Comment by mimits** [comment]
I installed Carla 
![image](https://user-images.githubusercontent.com/26203762/134770403-600e33d1-ff0f-41e0-8ea4-bfb608b4cccf.png)

**Comment by mimits** [comment]
But then I try to "make import" and the error comes again 
![image](https://user-images.githubusercontent.com/26203762/134770432-3d97955b-a551-4763-8030-ef0514e6a505.png)

**Comment by TrinhTuanHung2021** [comment]
I see no need to do "make python" or "make launch" commands. After executing the command "pip install carla", run the python files and Carla works

**Comment by mimits** [comment]
It is just how it is in documentation, and as I told u :) Carla does work fine, I just cant import any fbx or .xodr files, they way documentation states they should be imported

**Comment by TrinhTuanHung2021** [comment]
So I don't know. I also get error when executing "make python" and "make launch" commands.  If you can fix it later, please let me know

**Comment by mimits** [comment]
I can enter with "make launch" what error do u have?

**Comment by TrinhTuanHung2021** [comment]
Do you use facebook or something to make communication easier?

**Comment by mimits** [comment]
Andrej#7032 discord?

**Comment by TrinhTuanHung2021** [comment]
> Andrej#7032 discord?

is this a nickname or what? I searched but couldn't find it

**Comment by mimits** [comment]
I have sent u a request on FB

**Comment by MattRowe18** [comment]
@bernatx can you take a look at this
