### ISSUE TITLE
client fires "INFO: streaming client: failed to read header: End of file" - when using time.sleep or subprocess.run

### ISSUE THREAD

**Issue by Yebihashu** [carla-simulator/carla#4664]
CARLA version: 9.12
Platform/OS: Windows10
Problem you have experienced: Client fires Info:  "streaming client: failed to read header: End of file" when calling time.sleep or subprocess.run.

I tried even to delete the client object, but it doesn't help.

            client = carla.Client('localhost', 2000)
            client.set_timeout(4.0)
            do some work (moving a vehicle, listening to a sensor and writing its images down to files)
            del client
            sleep(1) # causes for warnings "streaming client: failed to read header: End of file"

What does it means and how to solve this?

**Comment by gustavomoers** [comment]
Same has happend to me, Carla version 0.9.12
I am running a reinforcement learning agente and the simulator crashes after exactly 1500 episodes with this message.
I runned a 2nd time and the simulator crashed again after exactly 1500 episodes.
