### ISSUE TITLE
Loading xodr file gives strange output

### ISSUE THREAD

**Issue by JoyMazumder** [carla-simulator/carla#4666]
Hello everyone, I am experimenting with xodr file and tried to load it into carla. I run the following command `python3 config.py -x opendrive/TownBig.xodr` and got the output something like this. The load are not aligned properly

![Screenshot from 2021-09-20 10-45-08](https://user-images.githubusercontent.com/43416538/134023446-f2fef761-f31f-4428-a66f-b166c88ffbaf.png)

I followed this tutorial to install Carla https://carla.readthedocs.io/en/latest/start_quickstart/#a-debian-carla-installation (Debian installation). OS linux 18.04, UE `4.26.2-0+++UE4+Release-4.26`

**Comment by JoyMazumder** [comment]
Running `manual_control.py` works fine
![Screenshot from 2021-09-20 11-23-48](https://user-images.githubusercontent.com/43416538/134028641-2f274d58-0564-47f1-a365-47d0b60fbf8b.png)

**Comment by barasm-hita** [comment]
After loading xodr map into CARLA, you can move camera via holding mouse click and WASD keys on keyboard.
You see roads as invisible because the camera is viewing them from bottom then just move camera upward and roads will show up correctly.

**Comment by CaffreyXu** [comment]
hello, I have the same question as you. The lane line can't be seen. Do you solve the question? Thank you so much

**Comment by CaffreyXu** [comment]
@JoyMazumder

**Comment by hitabm** [comment]
> hello, I have the same question as you. The lane line can't be seen. Do you solve the question? Thank you so much

Hi, you can draw string on each lane. It will show red signs for each lane in server side window. Use this code:
`way_points = world.get_map().generate_waypoints(distance=10)
for i, wp in enumerate(way_points):
        world.debug.draw_string(wp.transform.location, 'O', draw_shadow=False,
                                color=carla.Color(r=255, g=0, b=0), life_time=1200.0,
                                persistent_lines=True)`

**Comment by CaffreyXu** [comment]
@hitabm  Thank you so much! I saw many useful function in "debug" library, I will try to draw the line i want.
