### ISSUE TITLE
Carla: how to do the fault injection to camera (broken image, water drop, etc)

### ISSUE THREAD

**Issue by saina110** [carla-simulator/carla#4667]
CARLA version: 0.9.11
Platform/OS: Ubuntu 18.04

Dear everyone,

These days I am trying to do some fault injection to see the performance of autonomous driving system in Carla. But I haven't found useful tutorials about how to inject faults into camera (e.g., water drops, noise model, broken images, etc). Does anyone know how to do this kind of fault injection?

Thank you very much and look forward to your feedback

Best Regards,

**Comment by Axel1092** [comment]
Hi @saina110, just as @brscholz mentioned you can add posprocessing materials to the cameras and then add in the constructor of the sensor `AddPostProcessingMaterial(TEXT("Material'path/to/material'"));`.
You could also postprocess the images on the client side and store/use them after the changes you apply.
