### ISSUE TITLE
stubgen can't generate stub file for libcarla

### ISSUE THREAD

**Issue by julee** [carla-simulator/carla#4675]
CARLA version: 0.9.12

Platform/OS: Ubuntu 20.04 LTS 

Problem you have experienced:
I use vscode for carla python client development. VSCode use pylance as the language server. It requires a stub file for those python library which symbol coming from platform native libray.
For opencv, I can use 
```
stubgen -m cv2 
```
to generate the stub file. All types and symbols can be seen in generated file: cv2.pyi .

But for carla
command:
```
stubgen -m carla
```
generated carla/__init__.pyi .This file only contains one line: from .libcarla import *
No any valid symbol generated.

I can't find any way to solve this issue.

**Comment by Schuck84** [comment]
Hi @julee 
I'm also looking forward to get stub files, because I would like to have autocomplete working in VSCode. 

Could somebody comment on that issue how to get autocomplete working within VSCode (pylance) for Carla PYTHON package?

I think the stub file is required for that...
