### ISSUE TITLE
How to find out if a location is on road or not

### ISSUE THREAD

**Issue by barasm-hita** [carla-simulator/carla#4677]
I need to find some points that are on road in **OpenDRIVE** map. In other way, after loading xodr map into CARLA server, I need to find a point that is located on a lane in the map. Is there any way to find such a point? (It doesn't matter which part of road this point is located.)

CARLA version: 0.9.12
Platform/OS: Windows 10 v10.0.19043

**Comment by joel-mb** [comment]
Hi @barasm-hita,
Once loaded the map in the CARLA server there are several ways to retrieve waypoints located in lanes. For instance, you can use the `carla.Map.generate_waypoints(distance=1)` method that returns a list of waypoints within a certain distance between them for every lane and centered inside of it. Please take a look to the `carla.Map` API here: https://carla.readthedocs.io/en/0.9.13/python_api/#carla.Map
