### ISSUE TITLE
Hi I am having this issue can anyone help me:- RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to <ip address>

### ISSUE THREAD

**Issue by DonadiHarshith** [carla-simulator/carla#4678]

**Comment by DonadiHarshith** [comment]
Hi I am having this issue can anyone help me:- RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to my **ip address**

**Comment by barasm-hita** [comment]
Some times this happens to me. It is because I'm loading my simulator from HDD and this causes slow loading of simulator files. When I load it from SSD it works fine. In case of using HDD, after running CARLA simulator, wait a while to allow it finish loading its own modules.

**Comment by DonadiHarshith** [comment]
Thank you
