### ISSUE TITLE
How to run Carla version 8?

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [carla-simulator/carla#4679]
Hi. Currently I am using Carla version 0.9.12. But I have some examples that only work on version 8. Does anyone know any way to run Carla on version 8? I have tried but it's failed

**Comment by barasm-hita** [comment]
Have you take a look at official docs? [Link here](https://carla.readthedocs.io/en/0.8.4/)
Also, you can find its releases in [here](https://github.com/carla-simulator/carla/releases/tag/0.8.4).
