### ISSUE TITLE
Python API wheels for Linux and Windows for Python 3.9 on PyPi?

### ISSUE THREAD

**Issue by VonAncken** [carla-simulator/carla#4689]
CARLA version: 0.9.12
Platform/OS: Windows 10 and Ubuntu 20.04 LTS

Currently there are wheels for Python 2.7, 3.6, 3.7 and 3.8 available on PyPi for the CARLA Python API. Is it possible to provide wheels for Windows and Linux for Python 3.9 as well?
Could you extend the build for Python 3.9?
I know I could build the wheels myself, but I think I'm not the only one who needs them.

**Comment by joel-mb** [comment]
Hi @VonAncken,
We are planning to provide wheels for Windows and Ubuntu for Python 3.9 but it is not straightforward right now. We've detected some incompatibilities with the current version of boost we are using and Python 3.9. So probably we need to upgrade it. I'll leave this issue open to report any progress on this topic.

**Comment by dk42** [comment]
Hi @joel-mb,

could you elaborate on the incompatibilities? I managed to compile the CARLA Python API for Python 3.9. And it seems to work. Am I missing something?

**Comment by gdippolito** [comment]
I think @joel-mb is referring to the official Python wheel of carla available in pypi (https://pypi.org/project/carla/) not supporting Python 3.9

**Comment by gdippolito** [comment]
@bernatx would it be possible to provide a wheels for Python 3.9 whenever a new (0.9.14) release will be cut? 

At the moment there is no wheel available in Pypi (https://pypi.org/project/carla/) which support Python 3.9.

**Comment by Sultan91** [comment]
Still no support for python 3.9?

**Comment by xavisolesoft** [comment]
Thank you for your feedback!
We created a ticked to build python API for more python versions. Will fix this soon.

https://github.com/carla-simulator/carla/issues/7473
