### ISSUE TITLE
Example code bug

### ISSUE THREAD

**Issue by aifei7320** [carla-simulator/carla#4692]
CARLA version:0.9.12
Platform/OS:Ubuntu 18.04
Example code bug, in  visualize_multiple_sensors.py line 281, it should be "charger_2020" not "charger2020".
After change  "charger2020" to "charger_2020", the example worked.
``` python 
#bp = world.get_blueprint_library().filter('charger2020')[0]
bp = world.get_blueprint_library().filter('charger_2020')[0]
```

**Comment by glopezdiest** [comment]
@aifei7320 Indeed, we recently saw it and the `dev` branch already has it fixed. Too late for 0.9.12 though. Anyway, thanks for the report :slightly_smiling_face:
