### ISSUE TITLE
Location and rotation transform

### ISSUE THREAD

**Issue by GooVincent** [carla-simulator/carla#4693]
CARLA version: 0.9.12
Platform/OS: ubuntu1804
My Problem is:
1. How to transform Carla location and rotation information to Right-hand Z up coordinate system. Any guide on this? Confused me for a long time. Like if I have a right-hand coordinate system called cs, whose X: Right, Y: Forward, Z: Up, Then
cs.x = carla.postion.y
cs.y = carla.postion.x
cs.z = carla.postion.z
cs.roll = carla.rotation.roll
cs.pitch = -carla.rotation.pitch
cs.yaw =  -carla.rotation.yaw

Am I correct? I have referd to ros-bridge/carla_common/src/carla_common/transforms.py , but not very clear about the deep logic of  its processing.

2. If the Unreal Engine defined the yaw based on clockwise, and pitch/roll based on counterclockwise?

Appreciated for any ideas about this? Thanks

**Comment by glopezdiest** [comment]
Hey @GooVincent. To change from left hand to right hand, you have to invert the *y*, *pitch* and *yaw*. That would results in X: Forward, Y: Left and Z: Up. Then, you'd have to do a 90º rotation to match your reference.
