### ISSUE TITLE
Town with parking space

### ISSUE THREAD

**Issue by carola173** [carla-simulator/carla#4708]
Is there any version of Carla where any Town contains parking open street lots?

**Comment by glopezdiest** [comment]
Hey @carola173, what do you mean by parking street lots?
Most of our towns have parking spaces but none of them are part of the road topology, so no lanes pass through them.
Additionally, some towns (such as Town10HD or Town03) also have parking lanes next to the driving ones.

**Comment by glopezdiest** [comment]
This seems solved, closing the issue. Feel free to reopen it if needed
