### ISSUE TITLE
Texture Mask Missing in RoadMaster - My beautiful road wear lines are gone!!

### ISSUE THREAD

**Issue by jimmyw404** [carla-simulator/carla#4713]
CARLA version: 0.9.12

Platform/OS: Ubuntu / Windows
Problem you have experienced: Road wear lines are missing
What you expected to happen: Road wear lines to be present
Steps to reproduce: Load the Town10HD map from either the package or built from source, compare to prior versions.
Other information (documentation you consulted, workarounds you tried):

The RoadMaster-based Material Instances in the 0.9.12 version of CARLA are the Scalar Parameter Values / Texture Parameter Values that enable blending a Texture Mask to add road wear lines to the map are missing. This feature is documented in https://carla.readthedocs.io/en/0.9.12/tuto_M_custom_road_painter/#paint-the-road. The effect can readily be seen by comparing Town10HD in 0.9.12 to prior versions.

The below two images show the material instance + Town10HD map in CARLA 0.9.10, which shows off the road wear lines
![910_M_Road_03](https://user-images.githubusercontent.com/29664262/136264297-39748018-bcff-48c8-b7dd-913acb6bb693.png)
![910_Town10Corner](https://user-images.githubusercontent.com/29664262/136264300-840713de-e0a3-4c59-a095-8eb920cc3e5f.png)

The below two images show the material instance + Town10HD map in CARLA 0.9.12, which does not have road wear lines.
![912_M_Road_03](https://user-images.githubusercontent.com/29664262/136264303-ee50636c-7336-4edf-b05a-f9f5636e8457.png)
![912_Town10Corner_Package](https://user-images.githubusercontent.com/29664262/136264306-9316ce1d-d53c-4a50-8888-a8c7ee87e8f0.png)

**Comment by XGodina** [comment]
Hi @jimmyw404,

We are now working on finishing a maintenance release, which will soon come out. Where this problem will be fixed. If you need to fix it you just have to select the material of the road and put the mask of the Town10. 
![image](https://user-images.githubusercontent.com/39989886/137303831-b141a4a3-6aaa-417e-8653-87c04e07fd35.png)

Sorry for the inconvenience it may have caused.

**Comment by jimmyw404** [comment]
> Hi @jimmyw404,
> 
> We are now working on finishing a maintenance release, which will soon come out. Where this problem will be fixed. If you need to fix it you just have to select the material of the road and put the mask of the Town10. ![image](https://user-images.githubusercontent.com/39989886/137303831-b141a4a3-6aaa-417e-8653-87c04e07fd35.png)
> 
> Sorry for the inconvenience it may have caused.

Works great, thanks!!!!

Closing this ticket...
