### ISSUE TITLE
Release Dockerfile seems to be out of date

### ISSUE THREAD

**Issue by AzaelCicero** [carla-simulator/carla#4714]
**CARLA version:** 0.9.12
**Platform/OS:** Docker image
**Problem you have experienced:** 
https://github.com/carla-simulator/carla/blob/master/Util/Docker/Release.Dockerfile
Mentioned Dockerfile seems to be out of date. Especially it is missing some libraries now needed by Carla:

> docker run --privileged --gpus all --net=host -v /tmp/.X11-unix:/tmp/.X11-unix:rw carlasim/carla:0.9.12 /bin/bash ./CarlaUE4.sh                 
/home/carla/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping: error while loading shared libraries: libomp.so.5: cannot open shared object file: No such file or directory

Which can be resolved by installing **libomp5-10 libomp-10-dev**. 

Above that it contains invalid information about **opengl** flag.

**What you expected to happen:** Update file and deploy fixed Docker image.

I can create Pull Request for that if the file will remain and no other solution is not in the baking.

**Comment by bernatx** [comment]
Yes, the docker for version 0.9.12 (and latest) are built with the version 0.9.12 source code and the last Dockerfile that is in development branch, because it fixed several problems. So, it is still 0.9.12 version.
