### ISSUE TITLE
Adding .png transparent image as license plate

### ISSUE THREAD

**Issue by ebadi** [carla-simulator/carla#4723]
Hello,
I successfully followed the instruction in #4537 and #3429 and now I am tying to replace default license plates with transparent .png image files. 

![image](https://user-images.githubusercontent.com/1111940/136539748-61e8bdc7-1029-42d0-8953-373ab02ce171.png)

I therefore simply removed the old license plates and dragged the pngs into the directory, but now the license plates lost their transparency (as you see there is a black border around the license plate) 

![image](https://user-images.githubusercontent.com/1111940/136541159-391a1942-4b4e-4a02-bbae-06553cad7afd.png)

I tried to play with the properties of the texture in UE but I have not been successful so far. 

![image](https://user-images.githubusercontent.com/1111940/136781561-9fd2470b-7f9d-4c71-a8ba-b6eb4cbd3c25.png)
![image](https://user-images.githubusercontent.com/1111940/136781638-7da03974-b39d-497e-a5a5-0393aa5f3b9b.png)

**Comment by ebadi** [comment]
@Madecu  Thanks for assigning the issue and working on it. I now  found a solution which partially resolved the issue for me. (There are still vehicles that have black license plate holder)

Blend mode: Opaque -> Translucent
connect `A from LicenseText` to `Opacity in M_LicensePlate`

![image](https://user-images.githubusercontent.com/1111940/137624359-d6f4ed94-39ed-489b-a06f-eb91bcee10c2.png)

![image](https://user-images.githubusercontent.com/1111940/137624476-8deb1332-3388-4547-b2c1-eed0acc0087c.png)

![image](https://user-images.githubusercontent.com/1111940/137624513-7352b661-8106-4663-b54e-fe041bb5ff91.png)

**Comment by EricLangezaal** [comment]
Hello,
If this is not the right place please do let me know, but I have been attempting something similar and these threads have helped me a lot, so I thought I would pose my follow up question here.

I have been able to successfully add my images of license plates onto vehicles in CARLA, including transparency. Unfortunately however, the license plates seem to get cropped for some vehicles, like the volkswagen.t2_2021 for example. Below I have attached an image of what my license plate looks like, and another image of what it looks like once it is rendered on the vehicle, where you can see the cropping. 
![33_vehicle volkswagen t2_2021__12_49_MD](https://user-images.githubusercontent.com/57148808/168812828-c5402100-adfe-41a1-acba-405bcb98cf12.png)
![12-49-MD](https://user-images.githubusercontent.com/57148808/168812834-1183b948-e634-4ae8-b9e8-551ab788f2fc.png)

I have made sure that my license plate images are 256x256 pixels (partially transparent) like the provided texture set of license plates. Can anyone let me know how I prevent CARLA/Unreal Engine from cropping them when putting them on vehicles?
