### ISSUE TITLE
Delay on RGB camera data in v0.9.10

### ISSUE THREAD

**Issue by tamas-visy** [carla-simulator/carla#4757]
### CARLA version:
Specifically 0.9.10
### Platform/OS:
Windows 10
### Problem you have experienced:
The lambda listening to a camera (`sensor.camera.rgb`) receives data with a large delay (about 500-1000ms). Other sensors seem to be unaffected.
### What you expected to happen:
A lesser delay.
### Steps to reproduce:
Spawn an RGB camera, set the lambda with `.listen()`, then display images as soon as they arrive. In 0.9.10, the data has a delay compared to the simulation spectator camera or other sensors' data.
### Other information (documentation you consulted, workarounds you tried):
In other versions of CARLA (tested with 0.9.11 and 0.9.12) there is no noticeable delay.

**Comment by tamas-visy** [comment]
I found this piece of information in the ["Synchrony and time-step" documentation](https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/):

> Data coming from GPU-based sensors, mostly cameras, is usually generated with a delay of a couple of frames. Synchrony is essential here.

What I experience in `0.9.10` is a far longer delay than what "a couple of frames" would imply. Anyways, looks like synchronous mode could solve this.

I won't have time to do proper testing in synch mode, but I might revisit this issue later. Until then, I'll be using version `0.9.12` (I don't need specifically `0.9.10`).

**Comment by MattRowe18** [comment]
@tamas-visy the delay from sensors depends heavily on hardware configuration. The delay of a couple of frames is presuming very high performance graphics hardware (and also CPU). If you are using high performance GPUs from older generations or commodity graphics hardware, this would explain why your delay might be longer. Even though we do make the best of effort to optimise, CARLA is necessarily highly demanding on graphics hardware.

Can you give us some details of your hardware configuration?

**Comment by tamas-visy** [comment]
I'm using a regular CPU and GPU. However, please note that as per my original post
> In other versions of CARLA (tested with 0.9.11 and 0.9.12) there is no noticeable delay.

The issue exists in specifically 0.9.10, in the newer versions I tested I did not encounter a noticeable delay. However, I did not find any patch notes about a related fix or update. Also, I do not recall such a delay in a pre-0.9.10 version on my configuration either.
