### ISSUE TITLE
Fuzzy image retrieve from "camera.rgb" when replaying.

### ISSUE THREAD

**Issue by joeking11829** [carla-simulator/carla#4764]
Hi Carla Teams,

CARLA version: 0.9.12
Platform/OS: Ubuntu 18.04

I want to retrieve data from camera.rgb when replay the record.
the rgb images has some strange performance.

![image](https://user-images.githubusercontent.com/5969040/137856219-fea428c2-5058-4f4f-9a38-cd3fa9c41007.png)

Every images retrieve from replaying have same problem.
The moving vehicles produce fuzzy image.

Any idea to fix that ?
Thanks.

**Comment by MattRowe18** [comment]
@Axel1092 could this be an issue with motion blur parameters?

**Comment by wuhanstudio** [comment]
Same issue here (Carla 0.9.14). I disabled the motion blur:

Two vehicles on the left side are blurry.

```
# Create a RGB camera
camera_bp = bp_lib.find('sensor.camera.rgb')

camera_bp.set_attribute('image_size_x', '1392')
camera_bp.set_attribute('image_size_y', '1024')

# 72 degrees # Always fov on width even if width is different than height
camera_bp.set_attribute('fov', '72')
camera_bp.set_attribute('enable_postprocess_effects', 'True')
camera_bp.set_attribute('sensor_tick', '0.10')  # 10Hz camera
camera_bp.set_attribute('gamma', '2.2')
camera_bp.set_attribute('motion_blur_intensity', '0')
camera_bp.set_attribute('motion_blur_max_distortion', '0')
camera_bp.set_attribute('motion_blur_min_object_screen_size', '0')
camera_bp.set_attribute('shutter_speed', '1000')  # 1 ms shutter_speed
camera_bp.set_attribute('lens_k', '0')
camera_bp.set_attribute('lens_kcube', '0')
camera_bp.set_attribute('lens_x_size', '0')
camera_bp.set_attribute('lens_y_size', '0')
```
![0020](https://github.com/carla-simulator/carla/assets/15157070/f7408910-0cdd-4cf1-82e6-db534b49de06)

If I set  `camera_bp.set_attribute('enable_postprocess_effects', 'False)`:

![0016](https://github.com/carla-simulator/carla/assets/15157070/49674561-ff67-481d-b7c0-2cf969c0f04c)

**Comment by alexx-km** [comment]
I have the same issue in CARLA 0.9.15. Is there any fix for this issue? @Axel1092 Do you maybe have an idea how to solve this?
