### ISSUE TITLE
Fanatec steering wheel (ffb)?

### ISSUE THREAD

**Issue by WambJamb** [carla-simulator/carla#4766]
Hello together,

Is there anyone who got a different steering wheel than a g29 working with carla?

I am relatively new to vehicle simulation but I want to connect my fanatec wheel with carla and maybe even use force feedback.
Currently I am using Carla for Windows.

Would be great to get some feedback on this topic and if possible maybe some advice how to set up another wheel.

Thanks a lot for the great work.

**Comment by MattRowe18** [comment]
@WambJamb hi, thanks for your question. 

It's entirely possible to connect multiple hardware configurations to CARLA. It would, however, depend very specifically on the hardware and the associated SDK. You can retrieve data on collisions, speed and telemetry through the CARLA API and you can also send control instructions to the user controlled vehicle through the CARLA API. Please refer to the CARLA Python API https://carla.readthedocs.io/en/latest/python_api/ and look at the example scripts provided in the CARLA build or package in the PythonAPI/examples folder. The Manual Control script demonstrates how to send keyboard instructions to a live vehicle in the CARLA simulation. https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control.py you might be able to adapt these to your needs. The other part will be the Fanatec SDK please refer to that documentation. 

It will be challenging but possible. I would direct you to the CARLA Discord channels for this kind of question, you are more likely to find answers there.

Thanks

**Comment by WambJamb** [comment]
Fanatec states on their website that they use the same directInput interface as Logitech and that no SDK is needed for the basic functions like ffb and axis inputs. This means I would just need to somehow tell the python script to use the fanatec wheel instead of a G29. 
Currently the steering wheel example tries to find a Logitech wheel (which I do not have).
I would like to change that to fanatec. I imagine this could be possible since they use the same interface?!

Does anybody have an idea on how to do something like that?

**Comment by niezifei** [comment]
@WambJamb 
Hello, I am facing the same problem with yours. Trying to connect the Fanatec Steering Wheel and Carla.
Have you solved the problem?

**Comment by saicsk-deloitte** [comment]
Hi @WambJamb. Have u succeeded in making Fanatec steering wheel connection with CARLA?
If yes, can you please guide me

**Comment by WambJamb** [comment]
> Hi @WambJamb. Have u succeeded in making Fanatec steering wheel connection with CARLA? If yes, can you please guide me

Sadly I did not. Sorry.

**Comment by aiaxmaior** [comment]
You can do it using pygame, small transforming of values. I've had the most issues getting the vehiclecontrol object to apply. The vehicle object is reading the throttle brake and steering but wasn't working with the apply function in the API. I found out today that if I apply the physics control, I got results. Now I have to deal with creating the driver seat view 🥲

**Comment by aiaxmaior** [comment]
Happy to post code when I've finished and debugged.

**Comment by GoodarzMehr** [comment]
Hi, would it be possible to share your code? Thanks!

**Comment by doddsy2018** [comment]
This library could easily be integrated,  it's 100% python and supports Fanatec FFB features
https://github.com/doddsy2018/Python-Fanatec-FFB

**Comment by aiaxmaior** [comment]
@GoodarzMehr I haven't checcked comments in a while. Sorry. Do you still want some code refs?

**Comment by GoodarzMehr** [comment]
Yes, that would be great! Thanks.
