### ISSUE TITLE
SpawnActor failed because of collision at the spawn location

### ISSUE THREAD

**Issue by duongtran11** [carla-simulator/carla#4784]
I've created and imported a custom vehicle into Carla. I followed the Carla docs to create and import it. When I run `python3 manual_control.py --filter <my_vehicle_name>` I got this error. I couldn't spawn the vehicle.

CARLA version: latest (source build)
Platform/OS: Ubuntu 18.04
Problem you have experienced: Error: Actor not Spawned
What you expected to happen: Spawn a custom vehicle
Steps to reproduce: Run manual_control.py in PythonAPI/examples
Other information (documentation you consulted, workarounds you tried): 
![Screenshot from 2021-10-25 10-38-08](https://user-images.githubusercontent.com/67900559/138631407-ac43585d-63fb-4d56-9c19-d20dd3d2f9c6.png)

**Comment by eslaaam3** [comment]
Hello,
I'm having a similar issue and I have posted an [issue](https://github.com/carla-simulator/carla/issues/5674) #5674
Can anyone help please?
Thanks!
