### ISSUE TITLE
Difference between GNSS sensor data and transform_to_geolocation function 

### ISSUE THREAD

**Issue by werewolfdev** [carla-simulator/carla#4790]
Hi Team ,

is there any difference between the lat long alt values we obtain from GNSS sensor attached to vehicle and the transform to geo location function in maps not considering the offset with respect to parent actor

CARLA version:0.9.11
Platform/OS:Ubuntu 18.04

**Comment by glopezdiest** [comment]
As far as I know, supposing that the GNSS has no noise, the two are equivalent.

**Comment by werewolfdev** [comment]
Thanks

**Comment by AOOOOOA** [comment]
> rm to geo location function in maps not considering the offset with respect to parent actor

Hi, can we use the transform to geolocation function with lidar coordinate as input to get the object's GPS ?

Thanks！
