### ISSUE TITLE
Create Map from .xodr and import to Carla Package

### ISSUE THREAD

**Issue by joluko** [carla-simulator/carla#4798]
Hello, 
I'm trying to create a Carla map from an OpenDRIVE file and open it in a Carla package or import. I want to see not only the streets of the .xodr file but also to be able to add an environment to it. Can someone help me with this or is there anyone who has tried something similar?

Glad about any help!

CARLA version: 0.9.11
Platform/OS: Windows 10

**Comment by JoceilyhG** [comment]
Hi, I'm encountering the same issue. Do you have any update on this?
