### ISSUE TITLE
 Where to find the unreal engine 4.26 software of the carla branch？

### ISSUE THREAD

**Issue by liuxiaofang0312** [carla-simulator/carla#4802]

**Comment by RobTranquillo** [comment]
Did't you try it with the path from the docu: https://carla.readthedocs.io/en/0.9.12/build_windows/#unreal-engine?
`git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git .`

I did this and got UE version 4.26 as a result, but get an error (wrong version) when I try to load the project "CarlaUE4.uproject" from the Carla repo. So I don't really know if it is the right version.

**Comment by MattRowe18** [comment]
@liuxiaofang0312 you must use the CARLA fork of the Unreal Engine. Please download the latest version of the UE4 CARLA fork from the link provided in the Build documentation https://carla.readthedocs.io/en/0.9.13/build_windows/#unreal-engine
https://carla.readthedocs.io/en/0.9.13/build_linux/#unreal-engine

**Comment by xiaoqingnianbudadun** [comment]
> @liuxiaofang0312 you must use the CARLA fork of the Unreal Engine. Please download the latest version of the UE4 CARLA fork from the link provided in the Build documentation https://carla.readthedocs.io/en/0.9.13/build_windows/#unreal-engine https://carla.readthedocs.io/en/0.9.13/build_linux/#unreal-engine

The question is ， i can't find the carla branch of UnrealEngine

**Comment by MattRowe18** [comment]
> > @liuxiaofang0312 you must use the CARLA fork of the Unreal Engine. Please download the latest version of the UE4 CARLA fork from the link provided in the Build documentation https://carla.readthedocs.io/en/0.9.13/build_windows/#unreal-engine https://carla.readthedocs.io/en/0.9.13/build_linux/#unreal-engine
> 
> The question is ， i can't find the carla branch of UnrealEngine

The location of the GitHub repository is included in the clone command of the build instructions. 

git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git ~/UnrealEngine_4.26

you must link your GitHub account to the Epic Games account before you access this repository.

**Comment by NeuroDevOpsIncPub** [comment]
OK.

Follow up :

After posting this, Unreal sent me an invitation to join them on Github. After joining the organization, I was able to clone the repository with the command (with the Publisher license account; I didn't try the Creator license account).

The process to join didn't work exactly as it is described in the documentation.

**Comment by chenskye** [comment]
> > > @liuxiaofang0312 you must use the CARLA fork of the Unreal Engine. Please download the latest version of the UE4 CARLA fork from the link provided in the Build documentation https://carla.readthedocs.io/en/0.9.13/build_windows/#unreal-engine https://carla.readthedocs.io/en/0.9.13/build_linux/#unreal-engine
> > 
> > 
> > The question is ， i can't find the carla branch of UnrealEngine
> 
> The location of the GitHub repository is included in the clone command of the build instructions.
> 
> git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git ~/UnrealEngine_4.26
> 
> you must link your GitHub account to the Epic Games account before you access this repository.

this page is 404 now

**Comment by zhuzhouzhou** [comment]
yes ,it is 404 , where to find it now?

**Comment by spulivar** [comment]
I am getting the same error as below 

git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git ~/UnrealEngine_4.26
Cloning into 'C:/MinGW/msys/1.0/home/pamid/UnrealEngine_4.26'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/CarlaUnreal/UnrealEngine.git/' not found

Kindly provide the access to the repository and for the special privilege do we need to raise any ticket in the git hub portal as customer ticket.

Kindly advice the same for the error ?

**Comment by weizhii** [comment]
epic changes the  repository , first need to connect github account and epic account,join epic  
Organizations(access invite in mail link), mention in url  https://github.com/carla-simulator/carla/discussions/7774  . follow guide msg in https://www.unrealengine.com/ue-on-github  ,then you will access the repository.
