### ISSUE TITLE
How to georeference a custom 3D environment in Carla

### ISSUE THREAD

**Issue by duongtran11** [carla-simulator/carla#4810]
CARLA version: latest
Platform/OS: Ubuntu 18.04

Hi, I've created a 3d environment and imported it to Carla and I want it to have real-world coordinates. In the Transform/Location of every mesh in the environment, coordinates were set to default (0,0,0). I think there is some sort of "reference point" with real-world coordinates then mesh's coordinate would reference to it.
I want my environment to have real-world coordinates. How could I achieve that? Thank you.

**Comment by Axel1092** [comment]
Hi @duongtran11, I don't know what you mean with real world coordinates. You can set the georeference information in the OpenDRIVE file. 
All assets of a map need to be contained in a single FBX file to be imported by unreal, then the engine will place the meshes in the corresponding positions as defined in the FBX file.

**Comment by duongtran11** [comment]
Hi @Axel1092, I mean coordinates like latitude longitude or UTM. For example, if I import a New York city model to UE, I expect it to appear in the exact location of New York city. but I didn't know how to check it's locations (to make sure it was imported in the right place)
I'm using Cesium to import a satellite map layer to UE, then move my model to its correct location.

**Comment by ahaider1011** [comment]
I have a similar sort of query. I want to get accurate lat long from real world according to carla geo location for a custom map. I generated a custom map through OSM and then generated .xodr and .fbx files through road runner but when I look at the documentation for loading a current map it asks me to make the static meshes (0,0,0). Doing so removes the accurate world geo reference in carla world. How do I preserve the geo location? @Axel1092 @duongtran11 @XGodina
