### ISSUE TITLE
Question about adding container truck(a kind of vehicle) to carla

### ISSUE THREAD

**Issue by Xialinxuan** [carla-simulator/carla#4811]
I'm a beginner in carla, blender and UnrealEngine. I have read some related documentation and some issues.  I want to do some simulation about container truck runnnig in harbor. Container truck is different from all the existed 4-wheel vehicles in carla since there is a connection part inside the truck itself. This connection part make the physical process of truck  turning left or right become more complicated. I am wondering is it possible to add such a vehivle into carla.
![d4e1af9f5ba9995ab820bae22d0cbac9(2)](https://user-images.githubusercontent.com/39025197/139181500-40602fc8-98d2-4b7c-98e4-9b398036e4d9.jpg)
Above is a sketch about the mentioned container truck and it is typically a 6-wheel vehicle. Any advice about how to treat 6-wheel vehicles as 4-wheel vehicles or how to modify the source code to make 6-wheel vehicles perform normally?
Apologize for my poor English. Is anyone willing to help me?

**Comment by XGodina** [comment]
Hi @Xialinxuan,

This is one of the things that we would like to implement. But right now is not in our plan. There isn't much information about it. If you want to share your progress we can help you in your progress.
