### ISSUE TITLE
command.SetVehicleLightState() not working with client.apply_batch_sync()

### ISSUE THREAD

**Issue by roque2205** [carla-simulator/carla#4812]
Hi everyone,

I'm trying to set vehicle light states in a batch of commands in synchronous mode.

`[carla.command.SetVehicleLightState(self.carlaActor,self.current_light_state),carla.command.ApplyVehicleControl(self.carlaActor,self.current_control)]`

I do not get an error response, yet the light state remains unchanged. It works with 

`self.carlaActor.set_light_state(self.current_light_state)`

though, so I think I found a bug. :)

EDIT: It works if I set self.current_light_state to carla.VehicleLightState.NONE, but it does not for carla.VehicleLightState.LowBeam, carla.VehicleLightState.HighBeam etc.

Best regards
Robert

**Comment by glopezdiest** [comment]
Hey @roque2205, everything is working fine for me. From your code, is your `self.carlaActor` a `carla.command.FutureActor`? Here is the script I used to reproduce it ([base_spawn_actors.zip](https://github.com/carla-simulator/carla/files/7743980/base_spawn_actors.zip))

Closing this issue as it doesn't seem to be bugged, but if you have any more problem, feel free to reopen it
