### ISSUE TITLE
Custom Sensor causes seg fault after listen /source/carla/client/detail/EpisodeProxy.h:28

### ISSUE THREAD

**Issue by nparker2020** [carla-simulator/carla#4816]
I am having issues implementing a custom sensor. I have implemented a dead-simple sensor, that simply sends a carla::geom::Vector2D every Tick.

CARLA version: 0.9.12
Platform/OS: Ubuntu 20.04 LTS
Problem you have experienced: Creating a simple custom sensor causes the client to crash after listener registration. (presumably sometime during the receipt of the first message). The client-side seg fault also causes the server to hang.

What you expected to happen: The listen callback to fire and data to be received.
Steps to reproduce: 1.) Clone CARLA v0.9.12 2.) Add/merge provided sensor source. 3.) make PythonAPI and make launch 4.) run provided client script

Other information (documentation you consulted, workarounds you tried): I have re-read the [Create a sensor tutorial](https://carla.readthedocs.io/en/0.9.12/tuto_D_create_sensor/), and reviewed all of the existing Sensor implementations. I'm not sure exactly what is going on here/what I am missing... Some insight from a developer would be greatly appreciated.

Included GDB dump of client python script:

`
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Registered pretty printers for UE4 classes
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) run create_simple_sensor.py 
Starting program: /usr/bin/python3 create_simple_sensor.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4a90700 (LWP 12690)]
[New Thread 0x7fffeffff700 (LWP 12691)]
[New Thread 0x7fffe77fe700 (LWP 12692)]
[New Thread 0x7fffef7fe700 (LWP 12693)]
[New Thread 0x7fffeeffd700 (LWP 12694)]
[New Thread 0x7fffee7fc700 (LWP 12695)]
[New Thread 0x7fffedffb700 (LWP 12696)]
[New Thread 0x7fffed7fa700 (LWP 12697)]
[New Thread 0x7fffecff9700 (LWP 12698)]
[New Thread 0x7fffe7fff700 (LWP 12699)]
[New Thread 0x7fffe6ffd700 (LWP 12700)]
[New Thread 0x7fffe67fc700 (LWP 12701)]
[New Thread 0x7fffe5ffb700 (LWP 12702)]
[New Thread 0x7fffe57fa700 (LWP 12703)]
[New Thread 0x7fffe4ff9700 (LWP 12704)]
[New Thread 0x7fffb7fff700 (LWP 12705)]
[New Thread 0x7fffb77fe700 (LWP 12706)]
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.12-1-gbb4b95e0 
WARNING: Simulator API version  = 0.9.12-1-gbb4b95e0-dirty 
[New Thread 0x7fffb6ffd700 (LWP 12707)]
[New Thread 0x7fffb67fc700 (LWP 12708)]
[Thread 0x7fffb6ffd700 (LWP 12707) exited]
[Thread 0x7fffb67fc700 (LWP 12708) exited]
[New Thread 0x7fffb6ffd700 (LWP 12710)]
[New Thread 0x7fffb67fc700 (LWP 12711)]
FPS: 29.549081023580168
Thread 8 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffedffb700 (LWP 12696)]
0x00007ffff5c35de8 in carla::client::detail::EpisodeProxyImpl<std::weak_ptr<carla::client::detail::Simulator> >::operator= (this=0x18) at ../../LibCarla/cmake/../source/carla/client/detail/EpisodeProxy.h:28
28	  class EpisodeProxyImpl {
(gdb) c
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fffb67fc700 (LWP 12711) exited]
[Thread 0x7fffb6ffd700 (LWP 12710) exited]
[Thread 0x7fffb77fe700 (LWP 12706) exited]
[Thread 0x7fffb7fff700 (LWP 12705) exited]
[Thread 0x7fffe4ff9700 (LWP 12704) exited]
[Thread 0x7fffe57fa700 (LWP 12703) exited]
[Thread 0x7fffe5ffb700 (LWP 12702) exited]
[Thread 0x7fffe67fc700 (LWP 12701) exited]
[Thread 0x7fffe6ffd700 (LWP 12700) exited]
[Thread 0x7fffe7fff700 (LWP 12699) exited]
[Thread 0x7fffecff9700 (LWP 12698) exited]
[Thread 0x7fffed7fa700 (LWP 12697) exited]
[Thread 0x7fffedffb700 (LWP 12696) exited]
[Thread 0x7fffee7fc700 (LWP 12695) exited]
[Thread 0x7fffeeffd700 (LWP 12694) exited]
[Thread 0x7fffef7fe700 (LWP 12693) exited]
[Thread 0x7fffe77fe700 (LWP 12692) exited]
[Thread 0x7fffeffff700 (LWP 12691) exited]
[Thread 0x7ffff4a90700 (LWP 12690) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
`

Attached is a .zip with the source code for the custom sensor, as well as the requisite SensorRegistry.h and SensorData.cpp files.
[test_sensor.zip](https://github.com/carla-simulator/carla/files/7434364/test_sensor.zip)

**Comment by thbake** [comment]
Sorry for commenting on this closed issue but it seems to me that you were able to build Carla with Ubuntu 20.04 and are developing in C++. 

How did you enable header visibility across all files? I get error messages that clang doesn't find header files and, therefore, I cannot create a custom sensor such as in that guide you mention.

![screenshot](https://user-images.githubusercontent.com/23339310/139636942-23155b28-713e-46f4-9090-4d111e4c3698.png)

Thanks in advance!

**Comment by nparker2020** [comment]
@thbake , I have not encountered the same issue that you are describing.

It's not clear to me if that is an IDE issue, or an actual compiler issue. I do not use any fancy intellisense addons or anything like that, and I build from the command line.

My best guess would be to check your $UE4_ROOT environment variable, and make sure it's pointing to the Unreal 4.26 repo you cloned. Sorry I can't be more help.

**Comment by thbake** [comment]
So you are not using Visual Studio or something similar? You just rebuild the engine/Carla and it works? If that's the case I will do that as well. I launch Carla successfully, but I have those warnings more or less telling me that the files are not found. 

Thanks a lot for your answer!
