### ISSUE TITLE
how to find the camera location in world coordinates??

### ISSUE THREAD

**Issue by snowbrood** [carla-simulator/carla#4833]
hi there

I am trying to find the camera location in world coordinates?

I find the vehicle's coordinates by 

        print('vehicle at ',
              ego_vehicle.get_location().x,
              ego_vehicle.get_location().y,
              ego_vehicle.get_location().z)

this yields -85.21098327636719 , -126.87291717529297 , -0.05492006242275238

camera attached to this vehicle ,s relative position (x=2.5 y=0 z=0.7)

can I just add the camera's relative position and Vehicle coordinates to find the camera's location in real world?

**Comment by Madecu** [comment]
Hi @snowbrood 
Yes, in order to have the world position of the camera you just need to add its relative position with the world position of its parent, in your case, the vehicle world location.
