### ISSUE TITLE
about docker off-screen mode (runing docker on server without display)

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#4834]
hi, 
i try to run carla in a server (running with ubuntu 20.04, without a display, nvidia Quadro P6000, NVIDIA-SMI 495.44  Driver Version: 495.44   CUDA Version: 11.0 ) from local windows 10 MobaXterm.
i install docker and nvidia container toolkit following instruction. 
when i run : 
sudo docker run --privileged --gpus all --net=host -v /tmp/.X11-unix:/tmp/.X11-unix:rw carlasim/carla:0.9.12 /bin/bash ./CarlaUE4.sh -RenderOffScreen
output: 
sh: 1:xdg-user-dir: not found
Failed to establish dbus connection

i also check my status dbus.service status, using sudo systemctl status dbus.service, it looks fine, i list the part of output: 
● dbus.service - D-Bus System Message Bus
     Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
     Active: active (running) since Wed 2021-11-10 15:02:00 PST; 1 day 8h ago
TriggeredBy: ● dbus.socket
       Docs: man:dbus-daemon(1)
   Main PID: 1121 (dbus-daemon)
      Tasks: 1 (limit: 154144)
     Memory: 11.3M
     CGroup: /system.slice/dbus.service
             └─1121 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation ->
dbus-daemon[1121]: [system] Activating via systemd: service name='org.freedesktop.nm_disp>
dbus-daemon[1121]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'

but, when i run docker ps, i found image carlasim/carla:0.9.12 command "/bin/bash ./CarlaUE4.sh" are created 10 minutes ago. please see the output: 
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS          PORTS     NAMES
788eaaf20294   carlasim/carla:0.9.12   "/bin/bash ./CarlaUE…"   11 seconds ago   Up 10 seconds             blissful_yalow

is it successful or not? i suppose there is something wrong, but don't know how to fix it.

I download nvidia-driver 495.44 from nvidia website which should support vulkan. 

can someone help me out? 
i would be very appreciate if someone can provide all necessary package list and provide a simple tutorial (example) to run carla with docker on server without screen? do I need to install x11vnc onto ubuntu server and run realvnc on my windows for the  RenderOffScreen mode?

thanks in advance.

**Comment by LetStarFly** [comment]
do you slovle the problem？ I want to do same thing as you. It's too diffcult.

**Comment by Kin-Zhang** [comment]
I test about the carla 0.9.10.1 from docker hub with docker pull, and I find that with display the carla can run successfully
``bash
docker run -it -e DISPLAY=$DISPLAY --net=host --gpus all --name kin_carla2 carlasim/carla:0.9.10.1 /bin/bash
./CarlaUE4.sh -opengl
```
but When I tried to without display, it just exit and didn't run the carla without any error.
![image](https://user-images.githubusercontent.com/35365764/149772777-962abe23-071d-4785-b83d-75ca3ab40cf9.png)

**Comment by Kin-Zhang** [comment]
> I test about the carla 0.9.10.1 from docker hub with docker pull, and I find that with display the carla can run successfully
> 
> ```shell
> docker run -it -e DISPLAY=$DISPLAY --net=host --gpus all --name kin_carla2 carlasim/carla:0.9.10.1 /bin/bash
> ./CarlaUE4.sh -opengl
> ```
> 
> but When I tried to without display, it just exit and didn't run the carla without any error. Like here, I will try the 0.9.12 to see if it can run without display which is off-screen mode
> 
> ![image](https://user-images.githubusercontent.com/35365764/149772777-962abe23-071d-4785-b83d-75ca3ab40cf9.png)

OK, I just test on Carla 0.9.12 which won't have this problem.
