### ISSUE TITLE
Running Carla Server on Windows and client on Linux - Separate Machines

### ISSUE THREAD

**Issue by aadishdnaik** [carla-simulator/carla#4867]
I want to run the Carla Server on Windows and Client on Linux - on two separate machines. I would like to do this because my GPU is installed on a Windows machine (I want to keep it that way for other projects) and I want to use ROS which only works on Linux. The ability to publish sensor data as ROS Topics will allow me to use all available ROS packages (and develop more). I believe the Carla server uses ports 2000 and 2001 so in theory it should be possible - can someone point me to the step-by-step process to do this?

**Comment by Arch-suzuki-MB** [comment]
@aadishdnaik I have the same problem did you arrive to solve this issue?  I want to run the simulator on windows and I want the client side that retrieve data is a linux remote server . If you arrive to solve this issue can you please share
