### ISSUE TITLE
Tutorial.py crashes due to client = carla.Client('localhost', 2000) not working in Carla 0.9.12 and 0.9.11

### ISSUE THREAD

**Issue by newengineeeer** [carla-simulator/carla#4877]
What i did i download the exe from the github repository, pip installed all the requirements.txt and then ran tutorial.py and then it gave the error:
```
destroying actors
Traceback (most recent call last):
  File "tutorial.py", line 43, in main
    world = client.get_world()
RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tutorial.py", line 129, in <module>
    main()
  File "tutorial.py", line 122, in main
    camera.destroy()
UnboundLocalError: local variable 'camera' referenced before assignment
```
and so i tried checking which line of code was causing the error and to my surprise it was 
```
client = carla.Client('localhost', 2000)
```
as i did a try-except on it to see if it was working or not.
so to fix this i tried pip installing carla and then uninstalling it and then installing it again, i tried using carla 0.9.11 but i came across the same problem, i also manually set the port to 2000 and it still didn't connect but the weirdest part was manual_control.py is working and so is generate_traffic.py

**Comment by lzhhh93** [comment]
On next line: 
client.set_timeout(2.0)
change 2.0 to 5.0 and see how it works.
