### ISSUE TITLE
carla 0.9.12 and 0.9.11  client.get_world() won't run windows 10

### ISSUE THREAD

**Issue by newengineeeer** [carla-simulator/carla#4879]
My CARLA version is 0.9.12 but i also tried it 0.9.11, the Platform/OS i am using is Windows 10 the problem i have experienced is that client.get_world() in tutorial.py wont run for some reason. what i did is that i download carla 0.9.12 and then tried to run tutorial.py in my new venv after pip installing requirements.txt . the odd thing is that i can run both generate_traffic.py and manual_control.py but not tutorial.py due to client.get_world() not running.

**Comment by tamas-visy** [comment]
Hi, I've tested this (on Windows 10 with CARLA 0.9.12) and encountered what you have (`generate_traffic.py` working, but `tutorial.py` failing at `client.get_world()`).

The solution I found was to increase the client timeout in line 39 of `tutorial.py`:
```
[...]
client = carla.Client('localhost', 2000)  # L38
client.set_timeout(2.0)                   # L39  # Increase this to about 5.0
[...]
```

`generate_traffic.py` uses a timeout of 10 secs, while `manual_control.py` uses 20 seconds. This is overkill, I've found that connecting takes rarely longer than 3-4 seconds. So, a timeout of 5.0 is what I would recommend.
