### ISSUE TITLE
Add weather options

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#4883]
How do I add custom weather in Carla, such as snow, fog, etc.
And how to react to these different weathers in the control module ？

Thanks.

**Comment by Madecu** [comment]
Hi @whuxhzhang we don't have currently snow in CARLA but there are a few weather parameters you can tweak.

You can play with the weather when the simulation is running using environment.py for example. Here is a video showing how to use it at 12:30
https://www.youtube.com/watch?v=ZZaHevsz8W8&t=874s&ab_channel=CARLASimulator

You can also edit the weather default parameters in unreal's project:

1- you need to open CARLA's unreal engine project and find BP_Weather

![image](https://user-images.githubusercontent.com/54811869/142394253-80de3d05-a7ae-469e-bec9-589bee9f8a74.png)

2- then select "Default weathers" and edit Town01_Opt (or the one you are working on) and edit the parameters you want

![image](https://user-images.githubusercontent.com/54811869/142394444-aa9b73ad-7e7f-4791-9332-d5a853144e99.png)

3- once you have your weather configuration, click compile to save your changes
![image](https://user-images.githubusercontent.com/54811869/142394486-31274115-bbd8-44fe-a951-11493e286148.png)
