### ISSUE TITLE
Error carla_autoware.

### ISSUE THREAD

**Issue by Danis199** [carla-simulator/carla#4902]
![Снимок экрана от 2021-11-18 15-46-54](https://user-images.githubusercontent.com/73522138/142418003-d31bf4f7-b10c-4888-9120-1bebbd5085d2.png)

**Comment by joel-mb** [comment]
Hi @Danis199,
Please, provide more information about your issue. Which version of CARLA are you using? Are you using the CARLA autoware agent example (https://github.com/carla-simulator/carla-autoware)?

**Comment by joel-mb** [comment]
Closing this issue while waiting for more information. Feel free to reopen this issue if needed.
