### ISSUE TITLE
failed make launch to CARLA 0.9.13

### ISSUE THREAD

**Issue by Isak-toast** [carla-simulator/carla#4905]
CARLA version: 0.9.13
Platform/OS: Ubuntu 18.04
Problem you have experienced: Print error while make launch
What you expected to happen: make launch
Other information (documentation you consulted, workarounds you tried): 
Hello!
I knew that update new version CARLA on the current week.
So I was updating it yesterday, but it's not working. 

![Screenshot from 2021-11-19 10-32-50](https://user-images.githubusercontent.com/40036437/142540679-6367be17-2aca-46cb-b9f8-780a8f108c77.png)

Please give me an advice. Thank you.

**Comment by afterimagex** [comment]
i have the seem error.

**Comment by MaXiaoSIOM** [comment]
the same error

**Comment by Axel1092** [comment]
Hi all, for the new 0.9.13 version it is necessary to update the engine code. Otherwise you will find these compilation errors.

**Comment by Isak-toast** [comment]
What if can i reinstall Unreal Engine 4.26? Will it be clear?

I don't know exactly what you mean engine code..

**Comment by Isak-toast** [comment]
Yeah! It's work. 
I have reinstalled Unreal Engine 4.26.2

CARLA Version : 0.9.13 

Thanks.

**Comment by huangrainqi** [comment]
the same error

**Comment by huangrainqi** [comment]
@Isak-toast Where to download  Unreal Engine 4.26.2 ?  the lastest version is 4.26.1 ?
