### ISSUE TITLE
No collision info in the 0.8.3 version

### ISSUE THREAD

**Issue by minhaoxu1995** [carla-simulator/carla#491]
Hi, it is so exciting to see a new version of Carla! I just downloaded it and tested on my machine, it runs much faster!

However, I found that there is no collision info on HUD when I run Carla alone. It always shows 0 even if I hit other vehicles or pedestrians. Then I tried with a carla server and `client_example.py`, and there is no collision info on HUD and in the terminal either.

Version: Carla 0.8.3 on Ubuntu 16.04

![Alone](https://user-images.githubusercontent.com/26544895/41265571-7814f578-6e25-11e8-9bb7-b0dd178eda38.png)

![Server](https://user-images.githubusercontent.com/26544895/41265592-961fd088-6e25-11e8-9619-32f2100c66a9.png)

-- Update--
It might be related to the vehicle. When I change the setting to another vehicle rather than the default Mustang, the collision info in shown on the HUD.

**Comment by nsubiron** [comment]
I can confirm, the new Mustang model does not have hit events enabled.

This can be fixed by setting _"Simulation Generates Hit Events"_ in the base boxes of the physics asset to true. The Nissan Micra is also missing this.
