### ISSUE TITLE
spectator perspective problem

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#4928]
Ubuntu18.04  Carla-0.9.13

Set the spectator to be related to the ego vehicle, 
and the spectator perspective will swing greatly as the vehicle accelerates and decelerates.

code is:
spectator.set_transform(carla.Transform(ego_trans.location + carla.Location(x=0, y=0, z=1.3),
                                                                carla.Rotation(yaw=ego_yaw)))

**Comment by MattRowe18** [comment]
@whuxhzhang hi

could you provide us a little bit more information about what happens, it's not clear from your code how the problem is arising. Does the spectator swing from side to side? A couple of screenshots or a video would help a lot in debugging this issue

thanks

**Comment by whuxhzhang** [comment]
![image](https://user-images.githubusercontent.com/38369239/144155566-bf8a4f44-6094-4bfd-857e-136ad9f27b5f.png)
![image](https://user-images.githubusercontent.com/38369239/144155605-b508abac-1a9c-4da4-98e7-99f99c3e0ba3.png)

These two pictures are screenshots of the same car's perspective when accelerating and decelerating

code is:
spectator.set_transform(carla.Transform(ego_trans.location + carla.Location(x=0, y=0, z=1.3),
carla.Rotation(yaw=ego_yaw)))

**Comment by flyico** [comment]
I have same issue, have you resolved this?

**Comment by Jasmineyangyangyang** [comment]
I have same problem, have you resolved this?

**Comment by mamaduke21** [comment]
Same problem here and it is worst when using VR, help?
