### ISSUE TITLE
No leaves in segmentation

### ISSUE THREAD

**Issue by iohnishijima** [carla-simulator/carla#4930]
Hi, I have a problem now. I hope someone can help me!
I imported map that I make from RoadRunner.
In this map, Tree segmentation is shown, but no leaves.
Please let me know if you know how to display leaf segmentation or if you have any RoadRunner settings!
![00001663](https://user-images.githubusercontent.com/93071901/143402893-83d4a2b6-7be0-46fd-ad2d-de20295a54d8.png)
![00001665](https://user-images.githubusercontent.com/93071901/143403072-6aa634d2-a13e-4aee-b2a9-2d46ba0b9962.png)
thanks

CARLA version:0.9.12
Platform/OS:ubuntu18.0

**Comment by MattRowe18** [comment]
@Axel1092 is this expected behaviour?
