### ISSUE TITLE
Unreal Engine repository to build Carla on windows doesn't exist

### ISSUE THREAD

**Issue by RocaPiedra** [carla-simulator/carla#4932]
Hi, 

I started using Carla for my master's thesis and recently I've purchased a laptop (Gigabyte aero15xd) because my old PC couldn't handle Carla properly. So far, i've not been able to make the nvidia drivers work on ubuntu so I decided to build Carla on windows even though I prefer linux for programming. I've tried to build several versions of Carla but the unreal engine repository (https://github.com/CarlaUnreal/UnrealEngine.git/) doesn't exist:

![image](https://user-images.githubusercontent.com/69306294/143765810-96f8c7df-7588-4d77-8b88-928cb2797a95.png)

Do you know how can I solve this? Should I go for previous versions as 0.9.11?
I really need to start working with it asap, so if you have built Carla in windows recently or know how to solve the nvidia drivers issue properly (I've reinstalled ubuntu 3 times already), please answer.

**Comment by MattRowe18** [comment]
@RocaPiedra hi

Have you created an account on Epic Games, you need to connect your Github account with Epic Games and get a token for authentication before you can download the CARLA UE4 fork

**Comment by RocaPiedra** [comment]
Hi Matt, sorry I missed your answer.
I did it (checked with my epic account and it is linked), and git clonned with the x64 cmd too. I managed to use Carla with the precompiled .tar.gz folder.
The thing is, I have no clue which Unreal Engine is working as I have 4.24 and 4.26 versions installed nad not really know how I can access the uproject. I simply launch the exe file in the precompiled folder and I 'm ready to launch clients.

**Comment by hgc1** [comment]
@RocaPiedra hi，
I was checked with my epic account and it is linked, but it still no found. Can you elaborate on how you solved the problem？ Please answer.
![1644403364(1)](https://user-images.githubusercontent.com/68052239/153182293-710f58ca-ff5b-41ec-adb2-bdb2cb71fb94.png)
![1644403375(1)](https://user-images.githubusercontent.com/68052239/153182314-3a0fd6f6-4eb0-4b40-aaa1-21073fb818ed.png)

**Comment by FrenZ0810** [comment]
Hi RocaPiedra
I have encountered the same problem as you.May I ask how you specifically resolved it?I used two methods suggested to connect Github account and Epic Games, but it still doesn't work.
![6](https://github.com/carla-simulator/carla/assets/75529061/db2ca033-1f0b-4887-abef-fda91a63b23f)
![5](https://github.com/carla-simulator/carla/assets/75529061/ba0f1531-4985-499a-93c7-8317672bfe6b)
![4](https://github.com/carla-simulator/carla/assets/75529061/c619e97b-9454-45f7-aad1-cb4a406144e6)
![3](https://github.com/carla-simulator/carla/assets/75529061/38013cb1-7f60-49b0-bfdd-039fa3df7f63)

**Comment by Emilyhelin122** [comment]
I had the same problem with you. Do you solve the problem?
