### ISSUE TITLE
Setting high fps results in significantly more visually-slow simulation

### ISSUE THREAD

**Issue by tianqi-wang1996** [carla-simulator/carla#4939]
CARLA version: 0.9.13
Platform/OS: Ubuntu 18.4
Problem you have experienced:
After setting the fps via config.py, I observed very strange situations. If I set the fps to a relatively low number e.g. 10 fps, the cala server updates very quickly (cars run fast, traffic lights switch fast). On the other hand, setting  the fps to a relatively high number e.g. 100 fps, the carla server updates very slowly. I also executed the automatic_control.py / no_rendering_mode.py, and I found that the server fps does not change or correlates to the fps that I set before. From the calra documentation, I know that there exists a difference between the simualtion time and the real time. But I am confused about whether the fps calulation is based on the simulation time or the real time. 
What you expected to happen:
I expect the situation to be the opposite, setting fps high should make the carla server run fast instead of run slow. Since, I plan to collect a dataset in carla, I would like to figure out the setting of fps in carla.

**Comment by wowisfasfa** [comment]
same problem. did you solve it?
