### ISSUE TITLE
get  vehicle's ground truth

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/carla#4942]
I found that there are some vehicles on the Town04 map. How can I get the ground truth of these vehicles?

![image](https://user-images.githubusercontent.com/38369239/144416248-bae420cd-0612-4db7-a0df-9726b3e46d6a.png)

**Comment by MattRowe18** [comment]
@whuxhzhang hi

Can you expand on what you need as the "ground truth"?

**Comment by whuxhzhang** [comment]
> @whuxhzhang hi
> 
> Can you expand on what you need as the "ground truth"?

thank you for your reply，I have found a solution.
bboxes = world.get_level_bbs(carla.CityObjectLabel.Vehicles)
[https://github.com/carla-simulator/carla/issues/2343](url)

**Comment by whuxhzhang** [comment]
https://github.com/carla-simulator/carla/issues/2343
There is already a solution here.

**Comment by Chinese-Coding** [comment]
According to the documentation, this function returns an array of bounding boxes with location and rotation in world space. The method returns all the bounding boxes at the default level, but the query can be filtered by semantic tags with the `actor_type` argument. But how can I get only images of stationary vehicles?
