### ISSUE TITLE
Could not clone Unreal Engine

### ISSUE THREAD

**Issue by weijiepengx** [carla-simulator/carla#4948]
Hi,
       I have already connect my GitHub account to my Epic accout, but I still cannot clone Unreal Engine for CARLA.
       Any help?

**Comment by RobTranquillo** [comment]
Please give more information. What command are you executing and what was the error that occurred?

**Comment by weijiepengx** [comment]
issue closed. It's because that I didn't verify on [Github](https://github.com/EpicGames).
