### ISSUE TITLE
RGB Sensor stream to DNN

### ISSUE THREAD

**Issue by RocaPiedra** [carla-simulator/carla#4949]
CARLA version: 0.9.13
Platform/OS: Windows 10

Hello everybody,

I would like to access the output sensor from carla, for now, I just need the video stream from the RGB sensor. I think the easier way to do it is through ROS bridge but as far as I know, it is not compatible with windows 10. I prefer Linux for development but my new laptop's NVIDIA drivers do not work with Ubuntu (the laptop is an aero15 with the RTX 3070 and I tried version 18.04 and 20.04). I also tried to capture the window in order to stream it to my code but the generated window has no name and I haven't been able to reference it properly using win32gui.

Does anybody know the easier way to stream sensor data to other codes in Windows 10? For now, I only need it locally but in the future I expect to use a Jetson AGX Xavier to assist the data processing.

Thanks in advance :)

**Comment by roque2205** [comment]
I'd suggest that you create a script where you create a client, get the world, then get the camera you want to stream from and write a routine that get's the data from buffer and sends it to your DNN. Very much like it is done with pygame in the example manual_control.py.
