### ISSUE TITLE
CARLA 0.9.13 crashes with vulkan device error

### ISSUE THREAD

**Issue by varunjammula** [carla-simulator/carla#4958]
CARLA version: 0.9.13/0.9.12
Platform/OS: Ubuntu-18
Problem you have experienced: Carla release package: Using ./CarlaUE4.sh  crashes with not a compatible vulkan device found error. However, Carla 0.9.11 launches without an issue.

![image](https://user-images.githubusercontent.com/3236409/145777338-d71b256b-8066-42ac-95e8-3afe343b1f2b.png)

vulkaninfo | less gives me the following output

![image](https://user-images.githubusercontent.com/3236409/145481937-b0b8e931-7b52-4c1a-b25a-4f196c8be97c.png)

Edit: I think, the issue is caused by the new Unreal Engine version. I tried to find the vulkan version that Unreal 4.26 needs, I could not find any information.

**Comment by varunjammula** [comment]
Is CARLA 0.9.13 compatible with only Ubuntu 20 LTS?

**Comment by varunjammula** [comment]
Resolved the issue by downgrading the nvidia driver from 495.x to 465.x.

**Comment by varunjammula** [comment]
building from source make launch works, but when I package or use the already shipped version from the team, I always get the above error. Please let me know where I'm going wrong!

**Comment by YHao29** [comment]
I have the same issue. Have you solved that? Thanks a lot

**Comment by GPrathap** [comment]
I have the same issue
