### ISSUE TITLE
Add option to disable two-wheeled vehicles

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#497]
Seeing the issues at #496, add a temporary option to the settings file to disable bikes and motorbikes.

This is intended to be a quick workaround, a more robust solution should be implemented with the new API.

```ini
[CARLA/LevelSettings]
; Disable bikes and motorbikes, if true only four-wheeled vehicles will be
; spawned.
DisableTwoWheeledVehicles=true
```

**Comment by sandykalugdan** [comment]
Is this still applicable to 0.9.12 release?
