### ISSUE TITLE
How to remove the traffic lights and other signs in my map?

### ISSUE THREAD

**Issue by sparklin1999** [carla-simulator/carla#4987]
CARLA version: 0.9.10 build from source
Platform/OS: Ubuntu 18.04
Problem you have experienced: I removed the traffic lights and other signs on the UE4, but when simulation ran, there still were traffic signs and traffic lights.
What you expected to happen: I hope to modify the map to obtain a simple map without traffic signs.

**Comment by pushkar4501** [comment]
hi @sparklin1999 , did you find the solution for this problem?

**Comment by lshmouse** [comment]
+ 1 for this issue~

**Comment by Blyron** [comment]
Hi @kubs0ne 

For removing signals you will need to remove <signals> </signals>
