### ISSUE TITLE
Can Carla running on ubuntu21.1?

### ISSUE THREAD

**Issue by AOOOOOA** [carla-simulator/carla#4999]
Hi,

I'm using Ubuntu21.1 with RTX3080. I want to install Carla, but all the tutorials I can find using the ubuntu version <=20. So does anyone successfully install Carla on Ubuntu21?

Thanks

**Comment by Hardliu** [comment]
I install carla0.9.12 in ubuntu20.04 with rtx3080ti as your reference.

**Comment by AOOOOOA** [comment]
> I install carla0.9.12 in ubuntu20.04 with rtx3080ti as your reference.

Thanks!
