### ISSUE TITLE
Autopilot drives 10 km/h below speed limit

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#5]

**Comment by germanros1987** [comment]
Is this issue still open?

**Comment by marcgpuig** [comment]
@germanros1987 it is

**Comment by wlemkens** [comment]
Why exactly is this done? I see in the code that the speed is hard coded to be 10 km/h lower than the limit.

**Comment by nsubiron** [comment]
@wlemkens yes, you have a point. The autopilot is some legacy code we have full of magic numbers, and in my experience every time I have changed something there, the vehicles start having accidents all the time. Since so far hasn't been much of a priority and for now just works we haven't fixed it. But soon, with the addition with better support for more complex maps that we plan to add (multiple lanes, complex intersections, etc), this autopilot is going obsolete and we'll need to add a better one that understands the new map definitions. @marcgpuig and @germanros1987 are working on that, keep tuned ;)

**Comment by germanros1987** [comment]
The issue should be solved with the new Traffic Manager
