### ISSUE TITLE
Is it possible to subdivide the vehicle and pedestrian classes?

### ISSUE THREAD

**Issue by soo4826** [carla-simulator/carla#5003]
CARLA version: 0.9.13
Platform/OS: Ubuntu 18.04 LTS

Hi.

Carla's semantic camera, lidar sensor provides only one vehicle class including all of Cars, vans, trucks, motorcycles, bikes, buses, and trains.

But I need a subdivided class, so I want to subdivide the class.

In addition, the pedestrian class is expressed as a single pedestrian class, including cyclists, motorcyclists, and pedestrians on the sidewalk.

Likewise, pedestrian classes are intended to be subdivided.

I would like to change the source code so that I can subdivide the class, and I wonder if this is possible.

And I want to receive lidar and camera data using ROS. (Should I change carla-ros-bridge source code?)

The questions are summarized as follows.
1. Is it possible to subdivide the vehicle class?
2. Is it possible to subdivide pedestrian classes?
3. Should I change carla-ros-bridge source code or carla server source code?

Of course, I know that Instance segmentation is supported in this update, so it would be possible to post-process the data by class.

Please reply.

Thank you.

**Comment by tianqi-wang1996** [comment]
@soo4826 Hello, have you managed to achieve this function? Since I am also looking for a solution.

Best

**Comment by soo4826** [comment]
Yes.
I modify some code for subdivide semantic class

There is guideline in this repo: https://github.com/carla-simulator/carla/issues/4064#issue-851601056

Ask me question if you have problem!

**Comment by tianqi-wang1996** [comment]
@soo4826 
Hello, could you please tell me how to reorganize the newly created folder as well as the original Vehicles folder.

I am thinking of separating some vehicles from the Vehicles folder to the newly created Vans, Trucks, Motorcycles, and Bicycles folder.

Which files should I include in the new folders apart from the ones named as the vehicle types?  Is it necessary to keep the folder structure the same as the Vehicles folder, e.g. put all the files in the 2Wheeled or 4Wheeled folder? (I have tried to do this, the compiling process succeeded but whenever I spawn such a vehicle, the simulator crashes.)

![image](https://user-images.githubusercontent.com/50656401/170819015-8e83d5b3-ead4-414c-95e8-5d94fb3875e5.png)

**Comment by soo4826** [comment]
Hi

In my purpose, I separate 2 wheeled vehicle into motorcycle(PTW, Powered Two Wheeler), Bicycle). 
And separate 4 wheeled vehicle into Commercial vehicle and Vehicle

I do not create new folder, I hard-coded to recognize each class.

Heres's my Tagger.h file.

Also,I dont't and new object into simulator, i just subdivide Vehicle class into (PTW, Bicycle, Commercial Vehicle, Veicle)

If you do no solve your problem, I'll opn my private repo for subdividing vehicle class!

Feel free to ask your question!!

Thanks.

**Comment by tianqi-wang1996** [comment]
> 

@soo4826 
Hello, can you share the screen capture of your Vehicles folder, and the new folders inside it, such as the Bicycle folder? Did you just delete the 2wheeled and 4wheeled folder?

**Comment by tianqi-wang1996** [comment]
> Hi
> 
> In my purpose, I separate 2 wheeled vehicle into motorcycle(PTW, Powered Two Wheeler), Bicycle). And separate 4 wheeled vehicle into Commercial vehicle and Vehicle
> 
> I do not create new folder, I hard-coded to recognize each class.
> 
> Heres's my Tagger.h file.
> 
> Also,I don't and new object into simulator, i just subdivide Vehicle class into (PTW, Bicycle, Commercial Vehicle, Veicle)
> 
> If you do no solve your problem, I'll opn my private repo for subdividing vehicle class!
> 
> Feel free to ask your question!!
> 
> Thanks.

@soo4826 
I am sorry but I cannot see your tagger.h file, I guess I need to make some change in both Tagger.h and Tagger.cpp, right?

My current folder structure:
![image](https://user-images.githubusercontent.com/50656401/170861753-b5ece364-e555-4875-ac63-6183edeb7fb6.png)

![image](https://user-images.githubusercontent.com/50656401/170861773-c588086a-9364-482e-adf2-0550c48066f5.png)

![image](https://user-images.githubusercontent.com/50656401/170861791-f4a093b5-1f55-416b-ae96-5963cbd3d160.png)



In Tagger.h: (how should I code it?)
![image](https://user-images.githubusercontent.com/50656401/170861611-7be6862d-4411-410e-ace8-c89e747e3f17.png)

In Tagger.cpp:
![image](https://user-images.githubusercontent.com/50656401/170861699-bf35f308-928c-4635-afd5-66e6bbc1e0b4.png)

**Comment by Eisoc** [comment]
@soo4826 @tianqi-wang1996 
Sorry, but want to ask the solution about the issue.
If i changed the folder structure, for example if i move one mesh from 4-wheeled to another folder, it wll crash when spawning it using ros-bridge.
So what is the folder structure and what do i need to do with tagger.h?
