### ISSUE TITLE
config.py_UnboundLocalError

### ISSUE THREAD

**Issue by aslirey** [carla-simulator/carla#5006]
Hello,
I am trying to generate a map for carla by using openstreetmap. Could you help me to fix the error?
**python config.py -x map.xodr
file not found.**
**Traceback (most recent call last):**
  File "config.py", line 323, in <module>
    main()
  File "config.py", line 270, in main
    settings = world.get_settings()
UnboundLocalError: local variable 'world' referenced before assignment

**Comment by zlg9folira** [comment]
Any success on this ?
