### ISSUE TITLE
UE4 for Carlr 0.9.12 

### ISSUE THREAD

**Issue by Hardliu** [carla-simulator/carla#5008]
![image](https://user-images.githubusercontent.com/53360645/147220526-9968b86c-d99c-4428-a63b-022c02abf5a8.png)
Starting with version 0.9.12, CARLA uses a modified fork of Unreal Engine 4.26. This fork contains patches specific to CARLA.

I wondering where is the modified fork of Unreal Engine 4.26???
![Uploading image.png…]()

**Comment by TheMrGhostman** [comment]
yeah, i have the same question. I am not really experienced with all this. I just need to create modified map and i can not find right engine version

**Comment by Hardliu** [comment]
you can download this version of UE4:https://github.com/CarlaUnreal/UnrealEngine/tree/carla
it's for Carla













At 2021-12-31 18:29:57, "Matěj Zorek" ***@***.***> wrote:

yeah, i have the same question. I am not really experienced with all this. I just need to create modified map and i can not find right engine version

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
