### ISSUE TITLE
Stereo Image ,Left image

### ISSUE THREAD

**Issue by crazyzxd** [carla-simulator/carla#501]
Hi , I hope to extract stereo Image and depth image of left image(captured by the camera on the left).
How can i get that?
Can i just move the position of the cameras and sensors?

**Comment by marcgpuig** [comment]
Hi @crazyzxd.

Sure! check out the documentation about [cameras and sensors](http://carla.readthedocs.io/en/latest/cameras_and_sensors/).
Also there is more issues talking about the same topic, like #227.

**Comment by crazyzxd** [comment]
Ok i will check that.
Thanks a lot.

**Comment by marcgpuig** [comment]
Sure! You welcome!
