### ISSUE TITLE
Collision intentsity always zero.

### ISSUE THREAD

**Issue by imran514** [carla-simulator/carla#502]

**Comment by imran514** [comment]
I am running simulator in client-server mode with manual control and when i hit other cars and pedestrians i get collision intensity always zero. to Collision intensity always zero.

I am running the client_example.py that came with CARLA.

Do i need to enable anything to get collision intensities in settings.ini file ?

**Comment by imran514** [comment]
@marcgpuig can you please refer me to the original question ?

**Comment by marcgpuig** [comment]
Hey @imran514 thanks for your feedback but this is a known issue #491.
This is actually a bug. It will be fixed tomorrow :)
