### ISSUE TITLE
Ubuntu20.04 run UE4.26 has errors

### ISSUE THREAD

**Issue by Hardliu** [carla-simulator/carla#5027]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error:
LogOutputDevice: Error: Ensure condition failed: VendorId != EGpuVendorId::Unknown [File:/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanDevice.cpp] [Line: 182]
LogOutputDevice: Error:
LogOutputDevice: Error: Stack:
LogOutputDevice: Error: [Callstack] 0x00007fd735ce3f63 libUE4Editor-VulkanRHI.so!FVulkanDevice::FVulkanDevice(FVulkanDynamicRHI*, VkPhysicalDevice_T*) [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanDevice.cpp:182]
LogOutputDevice: Error: [Callstack] 0x00007fd735d7d986 libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::SelectAndInitDevice() [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanRHI.cpp:551]
LogOutputDevice: Error: [Callstack] 0x00007fd735d79cb3 libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::InitInstance() [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanRHI.cpp:694]
LogOutputDevice: Error: [Callstack] 0x00007fd735d798c8 libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::Init() [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanRHI.cpp:241]
LogOutputDevice: Error: [Callstack] 0x00007fdd23e7306d libUE4Editor-RHI.so!RHIInit(bool) [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/DynamicRHI.cpp:228]
LogOutputDevice: Error: [Callstack] 0x00000000002530a3 UE4Editor!FEngineLoop::PreInitPreStartupScreen(char16_t const*) [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:2555]
LogOutputDevice: Error: [Callstack] 0x0000000000249fcc UE4Editor!GuardedMain(char16_t const*) [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/Launch/Private/Launch.cpp:127]
LogOutputDevice: Error: [Callstack] 0x00007fdd20983286 libUE4Editor-UnixCommonStartup.so!CommonUnixMain(int, char**, int ()(char16_t const), void (*)()) [/home/zeng/Software/UnrealEngine_4.26/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
LogOutputDevice: Error: [Callstack] 0x00007fdd207a70b3 libc.so.6!__libc_start_main(+0xf2)
LogOutputDevice: Error: [Callstack] 0x0000000000233239 UE4Editor!_start()
LogOutputDevice: Error:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by LiangzgJlu** [comment]
your gpu is RTX 30XX?

**Comment by Yandong-Luo** [comment]
I also have the same issues

**Comment by chasingw** [comment]
same error with RTX 3080 on LEGION Y9000K notebook

**Comment by ElizabethSF** [comment]
Hello, have you found the solution to this problem? I've got it too with 4070Ti

**Comment by 0123gabriel** [comment]
Hello, does this problem gives any further complications? I got it too with a 4070 GPU laptop.

**Comment by Blyron** [comment]
This is known issue we are gonna try to look at it as soon as we can, but this issue should not block any issue

**Comment by astef3** [comment]
Hi, did anyone manage to solve this issue?
