### ISSUE TITLE
Not able to change Vehicletype

### ISSUE THREAD

**Issue by vsale** [carla-simulator/carla#5055]
Hello everyone,

I run Carla on a Windows 10 machine. Everything is working, I am even able to change the weathertype, but I am not able to change the vehicle type. I also tried to use #671, but I can not find the PlayerVehicle.
So how am I able to change the vehicle?

I hope someone can help me!

**Comment by DanielDoe** [comment]
Hey did you find a solution yet? I wanna run only vehicles(cars) but I do get cyclists which are undesirable for my experiments. Kindly let me know if you have an update.
