### ISSUE TITLE
Double force_lane_change Error

### ISSUE THREAD

**Issue by Miknow78** [carla-simulator/carla#5058]
Hi guys. 
I'm performing traffic_manager.force_lane_change(vehicle, True) at frame 10 and I want the car returns to the initial lane. 
So, I call traffic_manager.force_lane_change(vehicle, False) at frame 80 and the car continues in the same lane. 
Do you guys know why?

P.S I'm using autopilot mode and constant velocity.

**Comment by jackbart94** [comment]
It's because there's a timeout for lane changes, even forced ones.

**Comment by Miknow78** [comment]
There is no way to reset the timeout? 
To  make two lane changes in close frames?
