### ISSUE TITLE
Retrieving image data as float values

### ISSUE THREAD

**Issue by brscholz** [carla-simulator/carla#5070]
Hi there,

I want to retrieve image data from the rgb camera in full float precision. So I created my own pixel type with 4 float channels and a camera with 

Enable16BitFormat(true)
FPixelReader::SendPixelsInRenderThread(*this, true) 

similar to the optical flow camera. When I retrieve the data from buffer as type np.half, I get the strangest array with nan and negative float values. I also wrote a method similar to the creation of the FakeImage in the OpticalFlowCamera, that is supposed to deliver the 8bit representation of my float image, but this one crashes with SegmentationFault.

Hints on what I'm doing wrong would be highly appreciated.

@sshashank124 @Axel1092 Maybe you can help me out here?

HDRCamera.cpp
```
#include "Carla.h"
#include "Carla/Sensor/HDRCamera.h"

#include "Carla/Sensor/PixelReader.h"

FActorDefinition AHDRCamera::GetSensorDefinition()
{
  constexpr bool bEnableModifyingPostProcessEffects = true;
  return UActorBlueprintFunctionLibrary::MakeCameraDefinition(
      TEXT("hdr"),
      bEnableModifyingPostProcessEffects);
}

AHDRCamera::AHDRCamera(const FObjectInitializer &ObjectInitializer)
  : Super(ObjectInitializer)
{
  Enable16BitFormat(true);
  AddPostProcessingMaterial(
      TEXT("Material'/Carla/PostProcessingMaterials/PhysicLensDistortion.PhysicLensDistortion'"));
}

void AHDRCamera::PostPhysTick(UWorld *World, ELevelTick TickType, float DeltaSeconds)
{
  TRACE_CPUPROFILER_EVENT_SCOPE(AHDRCamera::PostPhysTick);
  FPixelReader::SendPixelsInRenderThread(*this, true);
}
```

HDRPixel in color.h
```
#pragma pack(push, 1)
  /// HDR pixel format. 4 channel float data.
  struct HDRPixel {
    HDRPixel() = default;
    HDRPixel(const HDRPixel &) = default;

    HDRPixel(float r, float g, float b, float a = 1.0f)
      : r(r), g(g), b(b), a(a) {}

    HDRPixel &operator=(const HDRPixel &) = default;

    bool operator==(const HDRPixel &rhs) const  {
      return (r == rhs.r) && (g == rhs.g) && (b == rhs.b);
    }

    bool operator!=(const HDRPixel &rhs) const  {
      return !(*this == rhs);
    }

    operator rpc::Color() const {
      return {static_cast<uint8_t>(r*255), static_cast<uint8_t>(g*255), static_cast<uint8_t>(b*255)};
    }
    operator rpc::FloatColor() const {
      return {r, g, b, a};
    }

    float r = 0.0f;
    float g = 0.0f;
    float b = 0.0f;
    float a = 0.0f;
    MSGPACK_DEFINE_ARRAY(r, g, b, a);
  };
#pragma pack(pop)

  static_assert(sizeof(HDRPixel) == 4*sizeof(float), "Invalid color size!");
```

HDRImageSerializer.cpp
```
#include "HDRImageSerializer.h"
#include "carla/sensor/s11n/HDRImageSerializer.h"

#include "carla/sensor/data/Image.h"

namespace carla {
  namespace sensor {
    namespace s11n {

      SharedPtr<SensorData> HDRImageSerializer::Deserialize(RawData &&data) {
        auto image = SharedPtr<data::HDRImage>(new data::HDRImage{std::move(data)});
        for (auto &pixel : *image) {
          pixel.a = 1.0f;
        }        
        return image;
      }

    } // namespace s11n
  } // namespace sensor
} // namespace carla
```
Best regards
Robert

**Comment by brscholz** [comment]
Okay, found the mistake by myself.
I suggest renaming the method "WriteFloatPixelsToBuffer_Vulkan" to "WriteFlowValuesToBuffer" as this is what it really does...

**Comment by IbrahimYang** [comment]
Hi brscholz,
I'm still struggling with rendering HDR images in Carla. May you tell me your modification is working or not? If yes, may you share this core with us? Thanks！

**Comment by manuelmaiorb** [comment]
Hello! I have a question related to the pixel values. What the range of float values per channel should be? As far as I know, for 16-bit floats, Unreal Engine outputs values between 0.0f - 65535.0f. Does this also apply in your implementation?

**Comment by brscholz** [comment]
Hi Manuel, for the HDR camera we transfer float values, not uint_16. That means, our outputs range between 0 and the maximum float value for HDR defined by UE4, I'm not 100% sure about that exakt value. You will need to apply some kind of tone mapping.

**Comment by manuelmaiorb** [comment]
Thank you for your answer! Meanwhile I have taken a look at what the range of values is for ETextureRenderTargetFormat::RTF_RGBA16f (which is set for the render target). According to [this resource](https://docs.unrealengine.com/4.26/en-US/API/Runtime/Engine/Engine/ETextureRenderTargetFormat/), even in 16-bit float format, per pixel values can get values up to ~65000. I have tested your implementation and more specifically the problem I have is that if I raise the camera exposure compensation to ~30.0 (which I need to do for the renders which I want to obtain), the pixel values are saturating at exactly (R=100.0625, G=99.9375, B=100.00). Also, for checking the values, I have captured the results by saving images directly from Carla plugin, from the corresponding render target, and not from Python API.

**Comment by Domsall** [comment]
A few things are not clear to me:
1. What is wrong with the current implementation? We actually just output the raw values from Unreal (which can be higher than 1.0). There is a default tone mapping on the clients side, but this can be changed. The values from Unreal come from `ReadSurfaceFloatData` and I doubt that those values will reach 2^16.
2. What is your "Scene Capture Component" reference doing? Can you share it? Can you compare the Carla picture with the reference picture? Are the scenes from the same Carla level? Is the tone mapping / post processing the same?

**Comment by manuelmaiorb** [comment]
I did not suppose that something is wrong with the implementation. I just expected it to output something different. If you say that the default tone mapping can be changed, then I think I might give a try changing something there. Could you tell me where can I access these tone mapping configurations?

**Comment by ztysdu** [comment]
Hi, I'm recently researching how to generate HDR images with carla, and I only found this [URL](https://docs.unrealengine.com/4.26/en-US/RenderingAndGraphics/HDRDisplayOutput/) and your issue on the web. Can you tell me how you set up HDR mode? Thank you very much!
