### ISSUE TITLE
Configuring collision sensor in synchronous mode

### ISSUE THREAD

**Issue by ivannson** [carla-simulator/carla#5082]
I was wondering how the collision sensor can be configured to work in synchronous mode?

I added it to the `CarlaSyncMode()` alongside other sensors and added some exception handling to deal with empty queue when there is no data (since there are no collisions), but adding the collision sensor that way makes the simulation run really really slowly (dropping from 20 fps to 0 fps).

This is what I'm currently using (I took bits which are not relevant to the collision sensor out)

```python
collision_sensor = world.spawn_actor(blueprint_library.find('sensor.other.collision'), carla.Transform(), attach_to=vehicle)
def collision_callback(event):
    print("COLLISION")

with CarlaSyncMode(world, camera_rgb, sem_lidar, radars['front'], radars['back'], collision_sensor, fps=10) as sync_mode:
    start = time.time()
    while True:
      if should_quit():
          return
      if render:
          clock.tick()
      # Advance the simulation and wait for the data.
      snapshot, image_rgb, sem_lidar, radars['front'], radars['back'], collision_sensor= sync_mode.tick(timeout=2.0)
                
      collision_sensor.listen(collision_callback)
      try:
          collision_sensor.listen(lambda event: collision_callback(event))
      except:
          pass
```

**Comment by gustavomoers** [comment]
I am facing the same issue, did u find any solution?
