### ISSUE TITLE
Identifying objects created by blueprints via semantic lidar

### ISSUE THREAD

**Issue by p0l0satik** [carla-simulator/carla#5094]
I am using IDs provided by semantic lidar to identify to which object each point belongs. However I faced an issue when a lot of objects(all non movable objects except signs and traffic lights) are given the same ID(0). I investigated the problem and found out that in RayCastSemanticLidar.cpp in function ComputeRawDetection an UE4 actor which was hit by a lidar ray is searched in FActorRegistry which in turn is filled in CarlaEpisode.cpp in InitializeAtBeginPlay function . If an UE4 actor which was hit by semantic lidar ray  was found in the mentioned Registry semantic lidar return its ID, in the other case a 0 is returned. I then found out that all objects for which semantic lidar was returning 0 were just not registered in  CarlaEpisode.cpp. I managed to fix the situation for unmovable StaticMeshes(by commenting condition, checking if a static mesh is movable) but have failed to do anything with blueprints. Meanwhile in maps used in Carla some building and objects are created as blueprints while some are created as static meshes. Therefore I would I be very grateful if you could help me to understand:
1. If there any way to register blueprints in CarlaEpisode so that they would get their unique IDs in the FActorRegistry used by semantic lidar?
2. Why some of the objects created by blueprints and some by static meshes? 
3. Does creating a building by static mesh influence sensor's outputs?
4. Is there a way to generate a map only using static meshes?
5. What actions would you recommend to take to get a unique ID of every object(buildings are the most important) from a semantic lidar?

Thanks for your attention and help!
CARLA version: 0.9.13-1-g8854804f-dirty
Platform/OS: Ubuntu 18.04.6

**Comment by DeepDuke** [comment]
Same problem. Did u solve it?
