### ISSUE TITLE
Custom Controller: Pedestrian unable to climb to sidewalks from road

### ISSUE THREAD

**Issue by adhocmaster** [carla-simulator/carla#5107]
CARLA version: 0.9.13
I made a custom map in Road Runner. WalkerAIController can crossroads, walk on sidewalks, everything is smooth. Now I am writing my own controller in python. Everything is good, except for one problem. When the pedestrian is on-road it cannot climb up a sidewalk. For the time being, I am jumping onto the sidewalk when the pedestrian is close to a sidewalk. Ideally, I would like it to climb up smoothly. Can anyone guide me to do it, please?

**Comment by LucasFKobernic** [comment]
I had the same problem in the past. What solved my problem was:

1. In the Unreal Engine editor select the curb;
2. Under Collision-> Collision Presets -> Choose "NoCollision"
3. save it

After that my pedestrian was able to climb up the sidewalk.
![curb_problem_carla](https://user-images.githubusercontent.com/77980399/151843603-d11ab6b1-5699-4cb0-a5f4-b1000f52a7b9.PNG)

**Comment by adhocmaster** [comment]
Need another solution which does not required rebuilding existing Carla maps

**Comment by zhz03** [comment]
HI, @adhocmaster  Did you solve this issue?

**Comment by adhocmaster** [comment]
I wrote my custom algorithm to avoid the collision as rebuilding the maps were not an option. Basically, I calculated whether there would be a collision soon. If true, I made the pedestrian jump onto the sidewalk.
