### ISSUE TITLE
Changing log level

### ISSUE THREAD

**Issue by p-schulz** [carla-simulator/carla#511]
Hi,

what is the easiest way to change the logging level? Is it necessary to rebuild the plugin/solution? I basically just want to debug the TCP connection.

Thanks :)

**Comment by marcgpuig** [comment]
Hi @p-schulz.

It is done in compilation time so (sadly) you need to rebuild it.
You can change it in:
https://github.com/carla-simulator/carla/blob/ab9a2c7cb524d279687e4f56228cb6244277a229/Util/CarlaServer/source/carla/Logging.h#L16-L22
Remember **NDEBUG** means **NO DEBUG**.

**Comment by p-schulz** [comment]
Thank you! This worked.
