### ISSUE TITLE
RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error

### ISSUE THREAD

**Issue by Zhenlin-Xu** [carla-simulator/carla#5111]
CARLA version: 0.9.13 RSS
Platform/OS: Ubuntu18.04 LTS
Problem you have experienced: **RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error**
What you expected to happen: I want to write a self-defined gym class of Carla for deep reinforcement learning. When I plan to initialise the traffic managers in the __init__(self, ...) function, I come up with this error. I also tried to run the automatic_control.py in the path `CARLA_DIRECTORY/PythonAPI/example`, it failed too with the same error. However, when I downloaded the package and ran the automatic_control.py file at the first time, the program ran successfully. 
Other information (documentation you consulted, workarounds you tried): I referred to other issues with the same problem, i.e. check the port and process. However, I am not sure about the detailed implementation of this in my computer.

**Comment by jackbart94** [comment]
It could be for a series of problems in your code. Can you give us some way to replicate this issue?

**Comment by Zhenlin-Xu** [comment]
I reinstalled the binary and it worked fine. Thx for your reply!

**Comment by zkailinzhang** [comment]
same error

**Comment by fah870599552** [comment]
> I reinstalled the binary and it worked fine. Thx for your reply!

hello, I get the same problem, How did you solve it ? with much thanks

**Comment by fah870599552** [comment]
> same error

me too, Did you solve it?

**Comment by Zhenlin-Xu** [comment]
> > I reinstalled the binary and it worked fine. Thx for your reply!
> 
> hello, I get the same problem, How did you solve it ? with much thanks

I remember I just downloaded a new binary package and it worked well. It is kinda of weird, to be honest.

**Comment by fah870599552** [comment]
> > > I reinstalled the binary and it worked fine. Thx for your reply!
> > 
> > 
> > hello, I get the same problem, How did you solve it ? with much thanks
> 
> I remember I just downloaded a new binary package and it worked well. It is kinda of weird, to be honest.

EXCEUSE ME COULD YOU TELL ME WHICH BINARY PACKAGE IT IS. THANKS

**Comment by Zhenlin-Xu** [comment]
> > > > I reinstalled the binary and it worked fine. Thx for your reply!
> > > 
> > > 
> > > hello, I get the same problem, How did you solve it ? with much thanks
> > 
> > 
> > I remember I just downloaded a new binary package and it worked well. It is kinda of weird, to be honest.
> 
> EXCEUSE ME COULD YOU TELL ME WHICH BINARY PACKAGE IT IS. THANKS

<img width="882" alt="carla1" src="https://user-images.githubusercontent.com/86121429/220279794-085ff66b-4dcb-40d9-b0a8-2cc385375d33.png">

just download the package that fits your OS. 😀
