### ISSUE TITLE
Error importing carla map from roadRunner. "ERROR: buildNavigation: Could not create solid heightfield"

### ISSUE THREAD

**Issue by kachoManzoor1996** [carla-simulator/carla#5122]
Hi, 
I am working on custom map. I have made the map in roadrunner. Unfortunately, I am experiencing "ERROR: buildNavigation: Could not create solid heightfield." error after last step in build from source [build.sh "my custom map"].
CARLA version: 0.9.13
Platform/OS: linux
Problem you have experienced: I am experience error while importing carla map exported from Raodrunner. 
What you expected to happen: I want to import custom map made in roadrunner. However, I am getting  "ERROR: buildNavigation: Could not create solid heightfield."

**Comment by ZXJohn** [comment]
the same problem i encounter ,have you resolve the problem
