### ISSUE TITLE
ImportError: cannot import name 'image_converter' from 'carla' - Carla 0.9.13, Windows 10, Human_Control code - G920 steering wheel

### ISSUE THREAD

**Issue by Shroculus** [carla-simulator/carla#5135]
Hi everyone!

**CARLA version:** 0.9.13
**Platform/OS**: Windows 10
**Problem you have experienced:** When I try to execute the human_control.py it throws me the error: "ImportError: cannot import name 'image_converter' from 'carla'". 
**What you expected to happen:** To successfully setup G920 steering wheel with manual controls.
**Steps to reproduce:** 

1. Imported and saved the file human_control.py in the path PythonAPI/examples from https://github.com/rohitgajawada/carla/blob/intern/PythonClient/human_control.py
2. Ran the human_control.py from the command prompt at example folder.
3. Simultaneously launched the CarlaUE4Editor and was in the play mode. 

**Other information (documentation you consulted, workarounds you tried):**

1. Tried to install the .egg in the PythonAPI/carla/dist folder using easy_install, pip and pip3 it results in error "'easy_install' is not recognized as an internal or external command operable program or batch file." 
2. With pip & pip3 it throws error "ERROR: Invalid requirement: 'C:\\Users\\hcelab\\carla\\PythonAPI\\carla\\dist\\carla-0.9.13-py3.8-win-amd64.egg' Hint: It looks like a path. The path does exist."
3. My setuptools are all updated and the requirement is satisfied too. 
4. I can even see easy_install.py under the setuptools/commands folder.

![image](https://user-images.githubusercontent.com/85901551/152427055-0aafd800-10ae-4917-99d1-df2ccf60e355.png)

**The full error w.r.t Carla is shown below:**
![image](https://user-images.githubusercontent.com/85901551/152427525-daf5d81c-4342-49a1-83d2-eeda6a94fb7b.png)

Could someone please help me or at least point me in the right direction. Any help is much appreciated.

Thanks in advance.

**Comment by i-kj** [comment]
Hello, 

I am also facing the same issue. Did you manage to fix it?

**Comment by ggambi0505** [comment]
where can i find carla\PythonAPI\carla\dist\carla-0.9.13-py3.8-win-amd64.egg ????
