### ISSUE TITLE
Rendering issues built from source

### ISSUE THREAD

**Issue by chrninja** [carla-simulator/carla#5138]
Rendering problems from first to second frame

CARLA version: 09.13 built from source
Platform/OS: Ubuntu 20.04

Ryzen 7 27000X
Nvidia GTX 1070Ti
32GB RAM

I am having problems with the rgb images when running my data collection script. When the world and all the vehicles spawn the first frame the images look fine, but all the subsequent frames have tire streaks or car roofs are just partially there.

Is there a way to improve rendering quality. Since this application is not meant for real time use I am not so interested in a high fps simulation but more about good rendering. 

I have already tried to slow down the simulation by changing the `fixed_delta_seconds` to 0.001 as outlined here but without success.

https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/#fixed-time-step

Below are the sample images:

![0000](https://user-images.githubusercontent.com/97633179/152510695-aeb41e25-7d54-446e-a328-0ee896e74b36.png)

First frame rendering nicely. Notice the red vehicle tail lights and the wall outlines on the right.

![0001](https://user-images.githubusercontent.com/97633179/152510692-626de794-6fa5-4763-8109-ec3d831951b6.png)
Second frame. Notice the tire streaks, faint tail lights and lost texture on the right wall.

Any suggestions would be greatly appreciated!

**Comment by zmz0130** [comment]
I have the same question. Did you find solutions?
