### ISSUE TITLE
Got error "fatal error: 'ActorAttribute.generated.h' file not found" while run "make launch" 

### ISSUE THREAD

**Issue by yihaozhangAD** [carla-simulator/carla#5146]
hello everyone, 
I got the error with  "fatal error: 'ActorAttribute.generated.h' file not found
" while building the carla simulator.  I want to know what I did is wrong. If anyone can provide any help, please let me know!

Thank you so much in advance.

**Comment by rexaaaa** [comment]
the same problem, and i try to install Carla 0.9.12 with UE-4.26.
