### ISSUE TITLE
Filtering the vehicles and walkers together into a list

### ISSUE THREAD

**Issue by werewolfdev** [carla-simulator/carla#5147]
Hi team , i would like to generate a player list with all the vehicles and the walkers together. The filter functionality associated with get_actors enable to filter only one type if I understood correctly. As the ActorList object doesnot have append functionality I cannot append the earlier generated list with one more filter('walker.*') as well. Could you kindly let em know if there is any way of filtering these objects together to an object.
CARLA version: 0.9.13
Platform/OS:Ubuntu 18.04

**Comment by MMNavetty** [comment]
hello, could you provide the solution please ? i'm having the same problem here.
Thanks in advance,
MM

**Comment by yhh-IV** [comment]
the same issue....
