### ISSUE TITLE
autopilot vehicle drives off road

### ISSUE THREAD

**Issue by makaveli10** [carla-simulator/carla#5179]
CARLA version: 0.9.13
Platform/OS: Ubuntu 20.04.3 LTS
Autopilot vehicle drives off road at the next junction or turn; no matter where it is spawned. I used 0.9.11 before this and everything works just fine.
Steps to reproduce: 
- Run carla server
- Create ego vehicle from client.
```
import os
import carla
import random

# connect client to carla server
import time
start = time.time()
while True:
    try:
        print("Waiting for CARLA")
        client = carla.Client('localhost, 2000)
        client.set_timeout(10.0)
        world = client.get_world()
        break
    except:
        import traceback
        traceback.print_exc()
        time.sleep(5)
        pass

# spawn an ego-vehicle randomly
spawn_points = world.get_map().get_spawn_points()
blueprints_vehicles = world.get_blueprint_library().filter("vehicle")
ego_transform = spawn_points[random.randint(0, len(spawn_points) - 1)]

blueprints_vehicles = [x for x in blueprints_vehicles if int(x.get_attribute('number_of_wheels')) == 4]

# let CarlaViz know this vehicle is the ego vehicle.
blueprints_vehicles[0].set_attribute('role_name', 'ego') # or set to 'hero'
batch = [carla.command.SpawnActor(blueprints_vehicles[0], ego_transform).then(carla.command.SetAutopilot(carla.command.FutureActor, True))]
results = client.apply_batch_sync(batch, True)
if not results[0].error:
    ego_vehicle = world.get_actor(results[0].actor_id)

while True:
    world.tick()
```

This code works as expected in 0.9.11. For 0.9.12+ the autopilot drives off road and is eventually destroyed.

**Comment by jackbart94** [comment]
Are you using synchronous mode when running the simulation?

**Comment by makaveli10** [comment]
No @jackbart94 . The code above is all that I used.

**Comment by jackbart94** [comment]
Asynchronous mode has been sort-of deprecated from TM in 0.9.12 and onwards. We always expect the simulation to be in synchronous mode.

**Comment by makaveli10** [comment]
Hi @jackbart94 I tired the synchronous mode i.e.
```
settings = world.get_settings()
settings.synchronous_mode = True # Enables synchronous mode
world.apply_settings(settings)
```
In 0.9.11 the off road is resolved when using this, in 0.9.12 the autopilot is driving very naively it seems on edge of lanes accelerating and decelerating very frequently. As for 0.9.13, it drives road on the next junction.

**Comment by jackbart94** [comment]
Could you also set fixed_time_step to 0.05, as per the tutorial, while setting synchronous mode?

**Comment by makaveli10** [comment]
@jackbart94 Even after setting ```fixed_time_step=0.05``` autopilot cannot stay on track in version ```0.9.13```. But the issue is fixed in previous version i.e ```0.9.12```.

**Comment by alexkutsan** [comment]
I have a very similar issue https://github.com/carla-simulator/carla/issues/5707#issuecomment-1271871350

**Comment by ronyshaji** [comment]
> I have a very similar issue [#5707 (comment)](https://github.com/carla-simulator/carla/issues/5707#issuecomment-1271871350)

Did you able to fix the issue ?

**Comment by makaveli10** [comment]
@ronyshaji yes... by using different traffic manager port for different clients.

**Comment by hexrefugee** [comment]
> @ronyshaji yes... by using different traffic manager port for different clients.
Is that means :
terminal 1: ./CarlaUE4.sh -carla-rpc-port=4000
terminal 2: python3 spawn_npc.py --port 4000 --tm-port 4050 # TM-Server
terminal 3: python3 spawn_npc.py --port 4000 --tm-port 4050 # TM-Client
Is this way to fix your problem ?

In my problems, The code that I want spawn 10 vehicles without sensors is in terminal2. And the code that spawn one vehicle with lidar is in terminal 3.

**Comment by makaveli10** [comment]
> @ronyshaji yes... by using different traffic manager port for different clients.

Use different port for traffic manager in different clients. And that should solve the issue of vehicles going wild.
