### ISSUE TITLE
How to correctly insert path to my own CarlaSettings.ini?

### ISSUE THREAD

**Issue by Robomate** [carla-simulator/carla#52]
I am trying to include the Example.CarlaSettings.ini into bash server config. The sim starts, but  I cannot execute any commands in the window.

`./CarlaUE4.sh /Game/Maps/Town01 -carla-settings=</home/student/Desktop/Carla/CARLA_0.6.0/Example.CarlaSettings.ini> -carla-no-networking -carla-no-hud -windowed -ResX=800 -ResY=600`

**Comment by nsubiron** [comment]
The path to the Example.CarlaSettings.ini must be written without the `<>` (it is like this in the docs, sort of convention to say `<put here your settings>`, I will change it, I admit can be prone to mistakes). Just call the server with

    -carla-settings="/home/student/Desktop/Carla/CARLA_0.6.0/Example.CarlaSettings.ini"
