### ISSUE TITLE
Server Protocol

### ISSUE THREAD

**Issue by p-schulz** [carla-simulator/carla#524]
Hi,
I know the network architecture is beeing redesigned... But according to the Server Documentation the protocol for the measurements and controls is only write and only read (measurements are written, controls are read). Every message is prepended by 4 bytes uint32 message size. 
My C++ client successfully connects and reads (around 3000 bytes measurements, 1920000 bytes image data)/writes data so far. But I'm a little bit confused about a buffer of length 4 which is sent by the sensor port from the server:

```
[2018.06.21-12.31.34:781][811]LogCarlaServer: Ready to play, notifying client
DEBUG: tcpserver 2000 : sending from buffer of length 6 
DEBUG: tcpserver 2000 : receiving to buffer of length 4 
INFO:  tcpserver 2001 : connected 
INFO:  tcpserver 2002 : connected 
DEBUG: tcpserver 2002 : receiving to buffer of length 4 
[2018.06.21-12.31.34:782][811]LogCarla: Found 23 PlayerStart positions for spawning vehicles
[2018.06.21-12.31.34:887][811]LogSpawn: Warning: SpawnActor failed because of collision at the spawn location [X=-71259.641 Y=77125.609 Z=246.785] for [ChevroletImpala_C]
[2018.06.21-12.31.35:897][811]LogCarla: Spawned all 23 requested vehicles
[2018.06.21-12.31.35:897][811]Cmd: g.TimeoutForBlockOnRenderFence 300000
[2018.06.21-12.31.35:898][811]g.TimeoutForBlockOnRenderFence = "300000"
[2018.06.21-12.31.35:898][811]LogLoad: Took 4.644012 seconds to LoadMap(/Game/Maps/UEDPIE_0_Ulm04)
DEBUG: allocating sensor buffer of 1920032 bytes 
INFO:  allocating agents buffer of 4128 bytes 
DEBUG: tcpserver 2001 : sending from buffer of length 3033 
DEBUG: tcpserver 2001 : sending from buffer of length 1920032 
DEBUG: tcpserver 2001 : sending from buffer of length 4 
DEBUG: tcpserver 2002 : receiving to buffer of length 10 
DEBUG: tcpserver 2002 : receiving to buffer of length 4 
DEBUG: allocating sensor buffer of 1920032 bytes 
INFO:  allocating agents buffer of 4128 bytes 
DEBUG: tcpserver 2001 : sending from buffer of length 3228 
DEBUG: tcpserver 2001 : sending from buffer of length 1920032 
DEBUG: tcpserver 2001 : sending from buffer of length 4 
DEBUG: tcpserver 2002 : receiving to buffer of length 10 
DEBUG: tcpserver 2002 : receiving to buffer of length 4 
DEBUG: tcpserver 2001 : sending from buffer of length 3228 
DEBUG: tcpserver 2001 : sending from buffer of length 1920032 
DEBUG: tcpserver 2001 : sending from buffer of length 4 
```

At client side I got this:

```
[LOG] (TCP 2001) receiving: 3029
[LOG] (TCP 2001) receiving: 1920028, frame: 563, width: 800, height: 600, type: 1, FOV: 90
[LOG] (TCP 2002) sending: 10
[LOG] (TCP 2001) receiving: 0
[LOG] (TCP 2001) receiving: 3224
[LOG] (TCP 2001) receiving: 1920028, frame: 564, width: 800, height: 600, type: 1, FOV: 90
[LOG] (TCP 2002) sending: 10	
[LOG] (TCP 2001) receiving: 0
[LOG] (TCP 2001) receiving: 140733193391235
[LOG] (TCP 2001) receiving: 2399095145, frame: 10231977596128545129, width: 2382317928, height: 2399095144, type: 2399095145, FOV: -6.2933e-30
[LOG] (TCP 2002) sending: 10	
[LOG] (TCP 2001) receiving: 2550991378
[LOG] (TCP 2001) receiving: 140733558253572
[LOG] (TCP 2001) receiving: 218169088, frame: 280375465148160, width: 65280, height: 218169088, type: 218169088, FOV: 1.04202e-25
```

It seems that after two frames the buffers which I'm reading are shifted or corrupted - the length of the measurements and image messages are way too big after the third frame, the measurements and image properties are wrong data. What are these 4 bytes?
EDIT: Casting the 4 bytes to an uint32 returns 0 (see client output).

Also (from the documentation):

> Every image is an array of uint32's:
> [width, height, type, FOV, color[0], color[1],...]

Is this actually prepended by an int64 as framenumber, like in the python client?

Thanks in advance :)

**Comment by nsubiron** [comment]
:grimacing: you are right, we recently started tagging images with the frame number (uint64) and forgot to update the documentation.

This is where the images are encoded in the server side 
https://github.com/carla-simulator/carla/blob/c4dd6794fc8a2eb32025425cc322d28a578692d3/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp#L46-L53

and here parsed in the Python client
https://github.com/carla-simulator/carla/blob/c4dd6794fc8a2eb32025425cc322d28a578692d3/PythonClient/carla/client.py#L190-L196

Really sorry about that.

**Comment by p-schulz** [comment]
No problem! Thank you ;-)
