### ISSUE TITLE
Error compiling server, carla 0.9.13 Ubuntu 20.4

### ISSUE THREAD

**Issue by FernandoGarImb** [carla-simulator/carla#5244]
![image](https://user-images.githubusercontent.com/95289723/157724238-28cf002f-f26f-4bb1-91c9-cf79c0323329.png)
When I do "make launch" this error appears in the terminal, I don't know if it is a python error or if I am missing a package to install.
Thanks in advance for your help.

**Comment by jayanshuagrawal** [comment]
Hi 

Did you got some solution for this issue, I am also facing this issue while trying to do make launch 

Thanks in advance

**Comment by jayanshuagrawal** [comment]
Hi 
Found the solution for this problem, I noticed that Python3 was installed. so I used the below command to link python and python3 

**sudo apt install python-is-python3**

It worked for me. Hope it will work for others too

**Comment by Blyron** [comment]
Are you happy to close this issue as you have found the solution?
