### ISSUE TITLE
issue when building carla on windows with "make launch"

### ISSUE THREAD

**Issue by LeMarcoPaulo** [carla-simulator/carla#5259]
Hi I'm trying to build Carla on Windows 11 and an error occurs each type I run "make launch" in the cmd
It says :
-[install_boost]: [B2 ERROR] An error ocurred while installing using "b2.exe".
-[install_boost]: Exiting with error...
I don't know what the problem is, if anyone has an idea it would help me immensely
Thanks !

**Comment by gpelaez2958** [comment]
Try downgrading Python. I used 3.8.10 and didn't have that error anymore.
