### ISSUE TITLE
Request to fix installation issues

### ISSUE THREAD

**Issue by JEO-96** [carla-simulator/carla#5304]
I have installed carla 0.9.13 several times before. But this time, a problem occurred during installation.
An error occurred while installing CARLA 0.9.13 on Windows 10.
The file with the error is carla\Util\InstallersWin\install-zib.bat.
Please fix it

D:\carla>make launch                                                                                                    -[Setup]: [Batch params]: --boost-toolset msvc-14.2 --all                                                               -[Setup]: Asynchronous jobs:  28                                                                                        -[Setup]: Boost toolset:      msvc-14.2                                                                                 -[Setup]: Install directory:  "D:\carla\Build\"
-[Setup]: Creating "D:\carla\Build\" folder...
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "D:\carla\Build\"
    -[install_zlib]: Retrieving zlib.
"2"개의 인수가 있는 "DownloadFile"을(를) 호출하는 동안 예외가 발생했습니다. "원격 서버에서 (404) 찾을 수 없음 오류를 반
환했습니다."
위치 줄:1 문자:1
+ (New-Object System.Net.WebClient).DownloadFile('http://www.zlib.net/z ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

    -[install_zlib]: Extracting zlib from "zlib-1.2.11.zip".
Expand-Archive : 'D:\carla\Build\zlib-1.2.11.zip' 경로가 없거나 유효한 파일 시스템 경로가 아닙니다.
위치 줄:1 문자:1
+ Expand-Archive 'D:\carla\Build\zlib-1.2.11.zip' -DestinationPath 'D:\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (D:\carla\Build\zlib-1.2.11.zip:String) [Expand-Archive], InvalidOperat
   ionException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

    -[install_zlib]: Removing "zlib-1.2.11.zip"
D:\carla\Build\zlib-1.2.11.zip을(를) 찾을 수 없습니다.
지정된 파일을 찾을 수 없습니다.
    -[install_zlib]: Creating "D:\carla\Build\zlib-source\build"
CMake Error: The source directory "D:/carla/Build/zlib-source" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

    -[install_zlib]: [CMAKE ERROR] An error ocurred while executing cmake command.
    -[install_zlib]: [CMAKE ERROR] Possible causes:
    -[install_zlib]:                - Make sure "CMake" is installed.
    -[install_zlib]:                - Make sure it is available on your Windows "path".
    -[install_zlib]:                - Make sure you have cmake 3.12.4 or higher installed.
    -[install_zlib]: Exiting with error...

-[Setup]:
   Ok, and error ocurred, don't panic!
   We have different platforms where you can find some help :)

   - Make sure you have read the documentation:
       http://carla.readthedocs.io/en/latest/how_to_build_on_windows/

   - If the problem persists, you can ask on our Github's "Building on Windows" issue:
       https://github.com/carla-simulator/carla/issues/21

   - Or just use our Discord channel!
       We'll be glad to help you there :)
       https://discord.gg/42KJdRj
make: *** [setup] 오류 1

**Comment by Niobium1** [comment]
I had a same issue.
so I rewrited the file
`ZLIB_VERSION=1.2.11`
to
`ZLIB_VERSION=1.2.12`

it worked :)

**Comment by shh1v** [comment]
@Niobium1 Solution worked. Thank you

**Comment by mihir7714** [comment]
@Niobium1 worked for me, thanks!
