### ISSUE TITLE
An error occurred while opening CarlaUE4.exe

### ISSUE THREAD

**Issue by ShihKuanChen** [carla-simulator/carla#5316]
# An error occurred while opening CarlaUE4.exe
I get an error when opening CarlaUE4.exe

CARLA version:0.9.13
Platform/OS:windows 11

Here are the logs:
```
Fatal error!


Crash in runnable thread TaskGraphThreadNP 0
Crash in runnable thread TaskGraphThreadNP 3
Crash in runnable thread TaskGraphThreadNP 1
Crash in runnable thread TaskGraphThreadNP 2
```
Hope to solve
Thanks!

**Comment by Z0184859** [comment]
i got fatal error while running "Make Launch" command after build.
![image](https://user-images.githubusercontent.com/114233628/195016399-83f5d029-bceb-4c1a-b6df-b644828f8639.png)

can anybody help what we can do ?

**Comment by Z0184859** [comment]
it got solved after extracted correctly the assets to the folder "C:\carla\Unreal\CarlaUE4\Content\Carla"

![image](https://user-images.githubusercontent.com/114233628/195084895-cd9d14b4-b81d-4ef2-976f-47aa7779a7d0.png)


should look something like this....

**Comment by thiriveedhisai** [comment]
can you please elaborate on how did you extract contents?
