### ISSUE TITLE
update carla  and carlaUnreal to latest, make launch fail, directly run ./UE4Editor (pull from CarlaUnreal) also fail

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#5317]
os: ubuntu 20.04,
remote vncserver access 
carla and carlaUnreal are both in latest version.
when run make launch, it stuck in 95% forever, the terminal output LogLinux: could not get DPI information for monitor #0, assuming 1.0f.

then, i go to unrealengine folder which i pull from "https://github.com/CarlaUnreal/UnrealEngine.git", and directly run ./UE4Editor  
pop out a window showing: 
ExampleDeviceProfileSelector failed to load because module "ExampleDeviceProfileSelector" could not be found, please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project

can someone help me out, thanks

**Comment by gengtsh** [comment]
also encounter error: 
[2022.04.04-23.12.03:946][  0]Error: CDO Constructor (LoadAssetMaterialsCommandlet): Failed to find Blueprint'/Game/Carla/Blueprints/LevelDesign/RoadPainterPreset.RoadPainterPreset'

[2022.04.04-23.12.03:946][  0]Error: CDO Constructor (LoadAssetMaterialsCommandlet): Failed to find Blueprint'/Game/Carla/Blueprints/LevelDesign/RoadPainterPreset.RoadPainterPreset'

Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Signal 11 caught.

**Comment by lsangreg** [comment]
Has someone solved this issue? I have the same identical one.

**Comment by JohnnyZZhao** [comment]
Same issue here. Using Ubuntu 20.04.5, Nvidia GeForce RTX2070.

**Comment by lsangreg** [comment]
@JohnnyZZhao  I solved the issue by running         ./Update.sh , because I missed this step thinking to  have to download just the assets for a specific version of CARLA:

> also encounter error: [2022.04.04-23.12.03:946][ 0]Error: CDO Constructor (LoadAssetMaterialsCommandlet): Failed to find Blueprint'/Game/Carla/Blueprints/LevelDesign/RoadPainterPreset.RoadPainterPreset'
> 
> [2022.04.04-23.12.03:946][ 0]Error: CDO Constructor (LoadAssetMaterialsCommandlet): Failed to find Blueprint'/Game/Carla/Blueprints/LevelDesign/RoadPainterPreset.RoadPainterPreset'
> 
> Signal 11 caught. Malloc Size=65538 LargeMemoryPoolOffset=65554 CommonUnixCrashHandler: Signal=11 Signal 11 caught.
