### ISSUE TITLE
Destroying NPC in Unreal Engine?

### ISSUE THREAD

**Issue by anthonypan08** [carla-simulator/carla#532]
I am curious about how to destroy an NPC in Unreal Engine (when it hits a trigger box for example).

![screenshot from 2018-06-25 10-36-52](https://user-images.githubusercontent.com/20074651/41856695-b936ced0-7863-11e8-8810-52eda97fd099.png)

This is what I have currently but whenever Unreal Engine tries to destroy the NPC the entire editor shutdown.

**Comment by marcgpuig** [comment]
Hi @anthonypan08.
Try to destroy the controller before the actor.

**Comment by anthonypan08** [comment]
How would I do that? I tried looking for the destroy controller action in blueprint but couldn't find it

**Comment by marcgpuig** [comment]
Sorry for the late response!
Have you tried [this](https://answers.unrealengine.com/questions/557499/ai-controller-can-never-be-destroyed-or-be-garbage.html) solution from Unreal Forums?
