### ISSUE TITLE
Bounding Boxes are too large

### ISSUE THREAD

**Issue by aeon0** [carla-simulator/carla#5329]
CARLA version: 0.9.13
Platform/OS: win10
Problem you have experienced: Boundingboxes are too large
What you expected to happen: Boundingboxes to fit tighter to the vehicle
Steps to reproduce: Show any boundingboxes in your vis (e.g. from examples run client_bounding_boxes.py)
Other information (documentation you consulted, workarounds you tried): The root seems to be within https://carla.readthedocs.io/en/latest/python_api/#carla.Vehicle bounding_box

Carla Box:
![image](https://user-images.githubusercontent.com/15958535/161937132-5bca8755-1579-4d73-b167-6da7393c5261.png)

I was hoping for sth closer to the green box:
![image](https://user-images.githubusercontent.com/15958535/161937703-f38748df-ad1c-4fb7-b22a-3c2f9d7ba5fd.png)

Any way to improve on this? E.g. for semseg output it seems to get the edges of the vehicle pixel perfect.

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

Does 0.9.15 solve your problem?

Marcel

**Comment by aeon0** [comment]
> Hi,
> 
> Does 0.9.15 solve your problem?
> 
> Marcel

Hi, if I remember correctly it was a human vision/perception error. I checked the pointcloud and boundingbox in 3D and it fits. The image projection also is fine.
So in the end its just a misinterpretatiom from how I perceive 2D to 3D.
