### ISSUE TITLE
Update CARLA

### ISSUE THREAD

**Issue by Hanss8** [carla-simulator/carla#5333]
CARLA version: 0.9.11
Platform/OS: Microsoft

Problem you have experienced: I wanted to update CARLA. I did same as in https://carla.readthedocs.io/en/0.9.13/build_update/. I deleted all files from Unreal\CarlaUE4\Content\Carla. Then i download content for 0.9.11 Carla, but no default maps (Town01,02,...) are imported. Why?
And second question, when i want to update to 0.9.13 from 0.9.11, have i to delete all files from CARLA and istall it from beginning according to https://carla.readthedocs.io/en/latest/build_windows/.
Thanks

**Comment by Blyron** [comment]
We suggest just to make a full rebuild. It may be more easier. Maps should be have been downloaded easier. 
Please take care that we have changed our storage host and most of the link change break, so we recommend to use dev branch.
