### ISSUE TITLE
help: how to debug carla in vscode (ubuntu)

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#5336]
can someone provide a tutorial to explain how to setup a carla project in vscode (ubuntu OS) and how to debug the code?
i did the following step: 
1. change the UE editor preferences to visual studio code, 
2. press play button in the UE4,  
3. open visual studio code in CaralUE4
4. run and debug in vs,
5. in the vs terminal, run the python tutorial.py, however, it is said ImportError: no module named carla

what i try to do is to build carla project in vs and try to trace how functions in both server and client side work, thanks a lot.

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

Did you run make PythonAPI?

Marcel
