### ISSUE TITLE
How to create more than 256 new semantic tags?

### ISSUE THREAD

**Issue by ghh116553** [carla-simulator/carla#5338]
I tried to change the enum class 'CityObjectLabel' from uint_8 to uint_16.
 Then I found the Value was reset by function 'Component.SetCustomDepthStencilValue(CastEnum(Label))', 
And In the funciton, Label Value would be clamped to 0-255;

**Comment by Blyron** [comment]
Why would you make that? 
In that case you would need to change the semantic tags in all places that appears in this tutorial;
https://carla.readthedocs.io/en/latest/tuto_D_create_semantic_tags/

**Comment by Blyron** [comment]
I am closing the issue feel free to reopen
