### ISSUE TITLE
make launch:  No rule to make target 'CarlaUE4Editor'.  Stop.

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#5340]
hi,
environment:
os: ubuntu20.04
carla: latest
unreal engine: 4.26.2

when run make launch, the output is 
BuildCarlaUE4.sh: Build CarlaUE4 project.
make[1]: Entering directory 'xx/carla/Unreal/CarlaUE4'
make[1]: *** No rule to make target 'CarlaUE4Editor'.  Stop.
make[1]: Leaving directory 'xx/carla/Unreal/CarlaUE4'
make: *** [Util/BuildTools/Linux.mk:7: launch] Error 2

can someone tell me what's wrong?

**Comment by gengtsh** [comment]
the issue is gone when  re-pull unreal engine .

**Comment by SExpert12** [comment]
I am facing the same error can you please tell me how you resolve it?
