### ISSUE TITLE
how to profile carla client-server performance

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#5341]
hi,
can someone explain or provide a tutorial about how to profile carla performance and how to step by step in vscode trace carla both client and server sides?

**Comment by Blyron** [comment]
Hi you can profile CarlaServer as other UE packages;
https://docs.unrealengine.com/4.26/en-US/TestingAndOptimization/PerformanceAndProfiling/
For that you will need a development package or build carla from source.
