### ISSUE TITLE
how to debug libcarla in vscode

### ISSUE THREAD

**Issue by gengtsh** [carla-simulator/carla#5353]
can someone explain how to debug libcarla in vscode?

**Comment by Blyron** [comment]
Open code by going to CARLA_ROOT and type in console code . to open solution of entire project
Use Visual Code debugger: 
Click on Run and debug. 

Open custom launch options. launch.json will be opened. There we will have possibility to add some configurations. Add next ones:  

This to launch a package standalone 

{ 
    "name": "(gdb) Launch package", 
    "type": "cppdbg", 
    "request": "launch", 
    "program": "/[PathToYourPackage]/carla/Dist/CARLA_Development_0.9.13-123-gd429cbeb6-dirty/LinuxNoEditor/CarlaUE4/Binaries/Linux/CarlaUE4", 
    "args": [], 
    "stopAtEntry": false, 
    "cwd": "${fileDirname}", 
    "environment": [], 
    "externalConsole": false, 
    "MIMode": "gdb", 
    "setupCommands": [ 
        { 
            "description": "Enable pretty-printing for gdb", 
            "text": "-enable-pretty-printing", 
            "ignoreFailures": true 
        } 
    ] 
  } 

 

This to launch Attach to editor 

   { 
      "name": "(gdb) Attach Editor", 
      "type": "cppdbg", 
      "request": "attach", 
      "program": "/[Your UE4Carla Path]/Engine/Binaries/Linux/UE4Editor", 
      "processId": "${command:pickProcess}", 
      "MIMode": "gdb", 
      "setupCommands": [ 
          { 
              "description": "Enable pretty-printing for gdb", 
              "text": "-enable-pretty-printing", 
              "ignoreFailures": true 
          } 
      ] 
    } 

This to launch Attach to Python 

    { 

      "name": "(gdb) Attach Python", 

      "type": "cppdbg", 

      "request": "attach", 

      "program": "/usr/bin/python3", 

      "processId": "${command:pickProcess}", 

      "MIMode": "gdb", 

      "setupCommands": [ 

          { 

              "description": "Enable pretty-printing for gdb", 

              "text": "-enable-pretty-printing", 

              "ignoreFailures": true 

          } 

      ] 

    } 

Once you have saved changes on launch.json you should have those options 
![image](https://github.com/carla-simulator/carla/assets/53337103/72b7c6c8-8183-441a-b171-c236e0fc49be)

Then open the editor and play it. Then you are gonna be able to attach to editor the code and debug
