### ISSUE TITLE
Driving vehicle with residual shadow

### ISSUE THREAD

**Issue by Wuhang92522** [carla-simulator/carla#5366]
Hello all.

CARLA version: 0.9.13
Platform/OS: Windows 10
I want to draw a running vehicle with carla.
But in map 10th there had present residual shadow on driving vehicle. like pic.
![image](https://user-images.githubusercontent.com/103575952/163296321-d9aab9a3-e7fc-4c9f-be78-4ab9b74acfbb.png)
I couldn't find the reason than residual shadow happend。
If anyone has an idea to solve my problem, I would appreciate it if you could let me know。

**Comment by XGodina** [comment]
Hi @Wuhang92522, This is caused by temporary anti-aliasing (TAA). We have been working on this for a long time, and we hope that we will have an anti-aliasing approach of our own. But that takes a long time.
