### ISSUE TITLE
CarSim Integration does not work

### ISSUE THREAD

**Issue by Reyen994** [carla-simulator/carla#5379]
Hello,

I have a Problem with the integration of CarSim in Carla. I use Carsim 2021.0 an Carla 0.9.13 with Unreal Engine 4.26 (Windows Build).  After downloading Carsim, I moved the PlugIn to the appropriate folder an start carla with "make launch". Then I enabled the Plugin and restarted the program. So i got the following error message:

![Fehlermeldung](https://user-images.githubusercontent.com/103037026/164396927-609d6f6a-61d5-404d-bdc5-aa23d03bd0b0.PNG)

Also I tried to start Carla with "make launch ARGS="--carsim" ", but this did not work. 

I hope somone can help me!

**Comment by jy723** [comment]
you shoule build carla-unreal first.
https://carla.readthedocs.io/en/latest/build_carla/
