### ISSUE TITLE
How to change default map when make launch?

### ISSUE THREAD

**Issue by Utopialjp** [carla-simulator/carla#5382]
How to change default map when run "make launch"?

**Comment by kubs0ne** [comment]
Did you manage to find the answer?

**Comment by Daraan** [comment]
This is one of the first search results coming up for this question.

Has someone found a solution?

**Comment by command-z-z** [comment]
I don't know how to change default map by `make launch` command. But another way can also do it, when you launch carla in UE. You can click the menu in bottom, Carla->Maps->Town01 to load the Town01 map.

**Comment by Daraan** [comment]
I found the answer in `<Carla>/Unreal/CarlaUE4/Config/Default.Engine.ini`

there are the following settings:

```
[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Carla/Maps/Town04.Town04
GameDefaultMap=/Game/Carla/Maps/Town04.Town04
ServerDefaultMap=/Game/Carla/Maps/Town04.Town04
GlobalDefaultGameMode=/Game/Carla/Blueprints/Game/CarlaGameMode.CarlaGameMode_C
GameInstanceClass=/Script/Carla.CarlaGameInstance
TransitionMap=/Game/Carla/Maps/Town04.Town04
GlobalDefaultServerGameMode=/Game/Carla/Blueprints/Game/CarlaGameMode.CarlaGameMode_C
```

I did not look deeper into the 4 different settings, especially not TransitionMap.  
I changed the Town10_Opt vs Town04 and everything `make launch` loaded Town04 without problems.

**Comment by tarynnielsen** [comment]
After you run `make launch` go to Edit->Project Settings

Once you're there under 'Project' go to 'Maps & Modes' and there you can change the default Editor Startup Map and the Game Default Map.

Then if you exit and rerun `make launch` it should load the new default map that you chose.
