### ISSUE TITLE
Conditional includes and UnityBuilds

### ISSUE THREAD

**Issue by brscholz** [carla-simulator/carla#5404]
Hi,

once more I am losing my mind over UnityBuild issues. I have added some code to Carla, which apparently led to a rearrangement of UnityBuild units and now WorldObserver.cpp throws errors:

```
  D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(42): error C2440: "<function-style-cast>": "const FVehicleControl" kann nicht in "carla::rpc::VehicleControl" konvertiert werden
  D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(42): note: Quelltyp konnte von keinem Konstruktor angenommen werden, oder die 喘erladungsaufl敗ung des Konstruktors ist mehrdeutig
  D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(77): error C2440: "<function-style-cast>": "const FWalkerControl" kann nicht in "carla::rpc::WalkerControl" konvertiert werden
  D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(77): note: Quelltyp konnte von keinem Konstruktor angenommen werden, oder die 喘erladungsaufl敗ung des Konstruktors ist mehrdeutig
  D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(175): error C2440: "<function-style-cast>": "const FVehicleControl" kann nicht in "carla::rpc::VehicleControl" konvertiert werden
  D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(175): note: Quelltyp konnte von keinem Konstruktor angenommen werden, oder die 喘erladungsaufl敗ung des Konstruktors ist mehrdeutig
```
The problem occurs with constructors like carla::rpc::VehicleControl(FVehicleControl), which are defined in the LibCarla code, but as conditional includes depending on LIBCARLA_INCLUDED_FROM_UE4. The respective rpc-Files are included such as this:

```
#include <compiler/disable-ue4-macros.h>
#include <carla/rpc/String.h>
#include <carla/sensor/SensorRegistry.h>
#include <carla/sensor/data/ActorDynamicState.h>
#include <carla/rpc/VehicleControl.h>
#include <carla/rpc/WalkerControl.h>
#include <compiler/enable-ue4-macros.h>
```
Still it says, that the required constructor is not available. I really need help from one of you developer guys to fix this, **please**.

**Comment by mixeur5** [comment]
Hi,

Sorry but I have a hard time translating this from german to english :( . Could you translate all the erros you are getting?

**Comment by brscholz** [comment]
Hi mixeur5,

of course I can, sorry. :) The error is the same for all three mentioned code lines except for the fact that the third one is a function-style cast of WalkerControl instead of VehicleControl.

`D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(42): error C2440: "<function-style-cast>": cannot convert from "const FVehicleControl" to "carla::rpc::VehicleControl"
  D:/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp(42): note: No constructor could take the source type, or constructor overload resolution was ambiguous

Please note that I have changed the braces in this line of code into brackets in an attempt to solve the problem. In the stock version of the Carla code the failed conversion would be from "initializer list" to "carla::rpc::VehicleControl".

**Comment by mixeur5** [comment]
Could you try to add the following at the top of the WorldObserver.cpp file?

`#include <compiler/disable-ue4-macros.h>
#include <carla/rpc/VehicleControl.h>
#include <compiler/enable-ue4-macros.h>`

**Comment by brscholz** [comment]
I had already added these lines where the other rpc includes were located and then noticed that
#include <carla/sensor/data/ActorDynamicState.h> implicitly includes this file, too. Moving the existing rpc includes to the top of WorldObserver.cpp, however, solves my problem.
Now I get linker errors, I guess I have to make clean and rebuild. :)

**Comment by brscholz** [comment]
Anyone else get's trapped with this: You will definitely want to add "#include "Carla/Sensor/AsyncDataStream.cpp" to your Sensor.h! That said, I do have a non-UnityBuild version running now. :)
