### ISSUE TITLE
Will epic mode and low mode change the observed LiDAR sensor data?

### ISSUE THREAD

**Issue by XHwind** [carla-simulator/carla#5406]
Will the rendering quality (epic mode vs low mode) influence the observed LiDAR sensor data? For example, I only want to collect LiDAR data, as a result, I want the rendering to be fast but I still want accurate LiDAR data as epic mode. Thus will using the low mode change the quality of observed LiDAR data?
After searching the doc, I still couldn't find the answer. Any help will be appreciated!
Thanks!

**Comment by Blyron** [comment]
No Lidar will only be affected by LineTraces as geometry,. LIDAR won't be affected by visual changes
