### ISSUE TITLE
Carla autoware support

### ISSUE THREAD

**Issue by tecena** [carla-simulator/carla#5419]
Hello,

In the document of Carla-autowrae AV stack https://github.com/carla-simulator/carla-autoware/blob/master/README.md it mentioned that the supported carla version is Carla-0.9.10. But this is not the latset version of carla. So does the autoware AV stack support latest version of Carla 0.9.13. or should we go with Carla-0.9.10

Thank you

**Comment by Jk7913** [comment]
Check [https://github.com/casper-auto/carla-autoware](url), works with 0.9.11.

**Comment by Blyron** [comment]
Autoware will have some news soon about carla, stay tuned
