### ISSUE TITLE
Velocity cordinates are negative

### ISSUE THREAD

**Issue by sbv198** [carla-simulator/carla#5426]
CARLA version: 0.9.13
Platform/OS: windows 10
Problem you have experienced: i used a command **get_velocity()** based on that igot velocity in x y and z cordinates but some things that i am not able to understand is that it gives velocity in negative values like -5.12489?

does anyone have idea about that

Thanks in advance

**Comment by glopezdiest** [comment]
The velocity is a vector, so you might get negative values depending on the direction of your movement
