### ISSUE TITLE
Traffic light and speed limit taking effect

### ISSUE THREAD

**Issue by petroolg** [carla-simulator/carla#544]
Hi,
is there a way how to get a traffic light and speed limit taking effect? This information is printed in simulator window (4th and 5th line). 

![simulator_window](https://user-images.githubusercontent.com/28491207/42059731-b377f9ec-7b24-11e8-98a0-63e75edcaed0.png)

It can be done using measurements API http://carla.readthedocs.io/en/latest/measurements/ by determining the nearest traffic light/speed sign, but maybe there's a simpler solution I'n not aware of. 

Thanks

**Comment by marcgpuig** [comment]
Hi @petroolg.
Sorry but this is the only way right now :(
We are currently changing the server so we will keep this in mind.

**Comment by kbarbora** [comment]
Does anyone know how to get the speed limit and traffic light status as in the image for version 9.6?
Thanks for your help
