### ISSUE TITLE
The C Compiler "...\cl.exe" is not able to compile a simple test programm on "make PythonAPI" (Windows 11)

### ISSUE THREAD

**Issue by AuberDjine** [carla-simulator/carla#5469]
Hey People,

Im trying to Build Carla, but when I try and type "make PythonAPI" I get the Error displayed in the Screenshot:

![2022-05-24 17_29_27-x64 Native Tools Command Prompt for VS 2019](https://user-images.githubusercontent.com/97905349/170074700-2cf677d2-d402-4327-9973-8b5377e71196.png)

Now I guess its a Problem with the Visual Studio Compiler. However I dont know what to do as I already tried reinstalling Visual Studio...

Does anyone know what I could try to Fix the Issue?

**Comment by Reyen994** [comment]
Carla doesn't work on Windows11. I had the same Problem. If i used Win10 it works.

**Comment by sp2150** [comment]
I do have the same issue ... 

Any news how to fix it using Windows 11 ?

**Comment by PatroSV19** [comment]
I believe that I came across the same error.

This thread seems to have had the same issue and came up with a solution: #5351

**Comment by Blyron** [comment]
Are you ok with closing this issue as you have found a solution?
