### ISSUE TITLE
./CarlaUE4.sh 4.26.2-0+++UE4+Release-4.26 522 0 Disabling core dumps. I have this issue and when the window CarlaUE4 shows just the see. what should I do for the next step?

### ISSUE THREAD

**Issue by ElishBanani** [carla-simulator/carla#5503]

**Comment by GittUser2021** [comment]
having the same issue, any solution to this ?

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

I'm closing this issue.
Feel free to reopen it, but please provide more info.

Marcel

**Comment by ak-maker** [comment]
Hi! I have met the same issue on windows11, WSL2, ubuntu22.04. I have followed the linux package installation instruction on installing carla-0.9.15 from https://carla.readthedocs.io/en/latest/start_quickstart/.  
![图片](https://github.com/user-attachments/assets/dea4fc5b-2103-43ba-91ca-e1de81d147b1)

**Comment by MarcelPiNacy-CVC** [comment]
Hi @ak-maker,

Could you share the output of the vulkaninfo and nvidia-smi commands?

**Comment by Revathy2025** [comment]
did anyone solved this problem.. kindly tell solution for this

**Comment by lzy886** [comment]
I encounter the same problem on Ubuntu
