### ISSUE TITLE
Manual Control

### ISSUE THREAD

**Issue by mhusseinsh** [carla-simulator/carla#551]
Hello,
I am running the server mode, with manual_control.py, however, in the manual_control, I am trying to get the car moving with the WASD keys and it is not responding at all

**Comment by marcgpuig** [comment]
Did you modified the manual_control.py? Do you have the focus on the pygame window?

**Comment by mhusseinsh** [comment]
no the manual_control is not modifed, and yes the focus is on the pygame window of the simulator

**Comment by mhusseinsh** [comment]
Ok now I got it working, there are 2 pygame windows. One for the car, and one a view for the cameras, when I am on the car one, it doesn't drive, I have to be on the other one

**Comment by marcgpuig** [comment]
Cool!

**Comment by morningsky** [comment]
@mhusseinsh @marcgpuig  I met this same problem on latest 0.9.5 version， when I run ./CarlaUE4.sh ，it creates a camera pygame window, after that, I run manual_control.py then it creates a game window, but the keyboard always focuses on the camera windows. When I click the game window and press WASD, I can't control the car, but the camera keeps move. what should I do?

**Comment by marcgpuig** [comment]
@morningsky Did you tried to change your keyboard to English?

**Comment by morningsky** [comment]
@marcgpuig  Yes, it's ok when I changed it! Thanks!
