### ISSUE TITLE
OSM convert Opendrive direction error

### ISSUE THREAD

**Issue by fangchaooo** [carla-simulator/carla#5510]
CARLA version: 0.9.13
Platform/OS: Ubuntu20
Problem you have experienced:
Using carla to convert osm to opendrive, then convert this opendirve to sumo net, found the direction is error.

What you expected to happen:
The correct map is 

using sumo netconvert, osm to sumo net map

![image](https://user-images.githubusercontent.com/19619745/173480715-42a86b98-e510-42a3-80fc-3cd1848fc802.png)

The carla convert map is (ignore some map details, focus on direction)
1.  using carla osm2odr
2.  using sumo opendirve to sumo net (the netconvert command same as co-simulation code)
![image](https://user-images.githubusercontent.com/19619745/173480945-84f2b7e0-f3d3-4d2d-bc73-d2be2440d645.png)

**The opendirve map direction between carla  convert and sumo netconvert result same as above** 
![image](https://user-images.githubusercontent.com/19619745/173482695-acd12487-5537-46ba-9342-db87f8ea35cf.png)
![image](https://user-images.githubusercontent.com/19619745/173482779-a7b3ce97-6322-4441-af9c-df6424e22d8f.png)

Steps to reproduce:
Other information (documentation you consulted, workarounds you tried):

**Comment by fangchaooo** [comment]
One point(x,y) (carla is -y, sumo y) has one lat lon in two direction maps. So there is no problem with the latitude and longitude corresponding to the local coordinates of two map

**Comment by fangchaooo** [comment]
I have solved this problem. I'll pull request to carla

**Comment by CHILLed144** [comment]
i think i am having this same problem
