### ISSUE TITLE
Updating the Readme wrt. Unreal Patch by Carla for Vulkan.

### ISSUE THREAD

**Issue by ll7** [carla-simulator/carla#5512]
I was wondering if the following aspect of the readme is still relevant. Unreal 4.24 doesn't actually match the master branch, which uses 4.26.

https://github.com/carla-simulator/carla/blob/8854804f4d7748e14d937ec763a2912823a7e5f5/README.md?plain=1#L74-L82

**Comment by lidongyv** [comment]
same question, but it seems this repo is out of reach now

**Comment by Blyron** [comment]
Since no response,
I am closing the issue, feel free to reopen

**Comment by ll7** [comment]
> Hello! We have updated the readme. Are you ok with closing this issue?

Hey, @Blyron thank you for updating the readme. I have been on vacation. Closing the issue is fine. Thank you.
