### ISSUE TITLE
How can I import BehaviorAgent into my code?

### ISSUE THREAD

**Issue by wang233work** [carla-simulator/carla#5529]
i use from agents.navigation.behavior_agent import BehaviorAgent bug it is fault

**Comment by ar4development** [comment]
You need you `PYTHONPATH` to hold both carla egg and folder where `agents.navigation.behavior_agent`. For example you are using Linux and your Carla **0.9.13** build is under `/carla`

Then your `PYTHONPATH` would be `/carla/PythonAPI/carla/dist/carla-0.9.13-py3.7-linux-x86_64.egg:/carla/PythonAPI/carla`

now you can install requirements (e.g. `pip3 install -r /carla/PythonAPI/carla/requirements.txt`) and in python console call

`from agents.navigation.behavior_agent import BehaviorAgen`

**Comment by wang233work** [comment]
thanks
