### ISSUE TITLE
Transform

### ISSUE THREAD

**Issue by Archiewyq** [carla-simulator/carla#553]
hello,
i find the function **get_unreal_transform** in 

> ~/PythoClient/carla/sensor.py

but cannot understand the values in _`to_unreal_transform = Transform(Rotation(roll=-90, yaw=90), Scale(x=-1))`_, such as -90,-1

besides, i find in #56 : 

> Given a 2D point p2d = [u,v,1], your world point position P = [X,Y,Z] will be: 
> P = ( inv(K) * p2d ) * depth

In my understanding, it gives the Transform from Pixel coordinate to Camera coordinate 
so if i want to get results in  World  coordinate , i need the extrinsic matrix of my camera.
Is it correct?
thanks!

**Comment by marcgpuig** [comment]
@Archiewyq Sorry for the late response.

Your thoughts are correct.
As you can see in the `point_cloud_example.py` on 0.8.X, we use this function to get the _camera to car_ transform:

![to_unreal_transform](https://user-images.githubusercontent.com/15848712/45426980-fc12a080-b69d-11e8-9457-21fca292964e.png)

Cheers!

**Comment by zrfreya** [comment]
> @Archiewyq Sorry for the late response.
> 
> Your thoughts are correct.
> As you can see in the `point_cloud_example.py` on 0.8.X, we use this function to get the _camera to car_ transform:
> 
> ![to_unreal_transform](https://user-images.githubusercontent.com/15848712/45426980-fc12a080-b69d-11e8-9457-21fca292964e.png)
> 
> Cheers!

@marcgpuig   Does this still work for carla 0.9.1 ?

**Comment by marcgpuig** [comment]
Hi @zrfreya, sorry for the late response.

>  Does this still work for carla 0.9.1 ?

Yes, it does still the same :)

**Comment by gxd1994** [comment]
> Hi @zrfreya, sorry for the late response.
> 
> > Does this still work for carla 0.9.1 ?
> 
> Yes, it does still the same :)

Does this still work for carla 0.9.5?

**Comment by jnd77** [comment]
Hi.
This graph is great. Would it be possible to add one section about transformations and axis system in the documentation, and include this graph ? I think every newcomer to Carla spends some time initially to figure it out by going through github issues. Would be really helpful to have it in one place. :)

Thanks !

**Comment by marcgpuig** [comment]
Hi @jnd77, I quickly made it a long time ago :grinning:
I'm sure that @sergi-e, our super docs guy, can do something better to add in our official docs.
Cheers!
