### ISSUE TITLE
AttributeError: module 'libcarla.command' has no attribute 'ApplyVelocity'

### ISSUE THREAD

**Issue by omega1497** [carla-simulator/carla#5535]
Code:
<img width="956" alt="Screenshot 2022-06-23 at 11 59 43" src="https://user-images.githubusercontent.com/56640079/175273227-d9665b8a-08e6-4843-865c-1ad25033f08c.png">

def pause_time(prev_save,client):
    now=ceil(time.time())
    if (now-prev_save)>=SAVE_GAP-1:
        vehicles = [x for x in client.get_world().get_actors().filter('vehicle.*')]
        batch = [carla.command.SetAutopilot(x.id, False) for x in vehicles]
        batch+=[carla.command.ApplyVelocity(x.id, carla.Vector3D()) for x in vehicles]
        client.apply_batch(batch)
        print("Freezed all cars at " + (time.asctime( time.localtime(now ))))
    return

**Comment by omega1497** [comment]
I am trying to apply velocity to the actor reading the carla docs but it gives me the error above.

**Comment by ar4development** [comment]
I believe that starting from API version 0.9.10 you should use `command.ApplyTargetVelocity` instead of `command.ApplyVelocity`

**Comment by omega1497** [comment]
Thanks @ar4development it worked i might have misread the document. Thanks for your time.
