### ISSUE TITLE
error: invalid command 'bdist_wheel' after install of "wheel" package on windows10

### ISSUE THREAD

**Issue by ohashi3399** [carla-simulator/carla#5542]
Hi, I appreciate for your great work.
I have an issue the above title.
I have stucked the problem a couple of days ago. 
@bernatx
@corkyw10
@marcgpuig
It would be very helpful if you could provide any information.
Details are listed as below. Thanks in advance.

---
**CARLA version:** 0.9.13
**Platform/OS:** Windows10 Pro
**Problem you have experienced: error:** invalid command 'bdist_wheel' after install of "wheel" package on windows10
**What you expected to happen:** something mistake when I installed "wheel" package (Do I need to run setup.py? but I didn't find such file. I found PythonAPI/setup.py in old issue but now cannot be used. https://github.com/carla-simulator/carla/issues/976#issuecomment-440293377)
**Steps to reproduce:** 
  1) Installing Unreal Engine 4.26
  2) git clone -b 0.9.13 --depth=1  https://github.com/carla-simulator/carla
  3) cd carla
  4) make PythonAPI
then I got this error

![error](https://user-images.githubusercontent.com/87519834/175990381-d4536f54-7ba8-4711-a4d0-076e992cf712.png)
full error message shows here.
[full_error_message.txt](https://github.com/carla-simulator/carla/files/8994072/full_error_message.txt)

**Other information:** 
- I have installed UnrealEngine4.24 on same laptop before, but I removed directly folder. Since there may be some sort of cache left over, I already tried "make clean" command.
- I entered "make launch" to proceed anyway, the error message " make: *** [CarlaUE4Editor] error 6 " is shown. (this details are ommited because error message written by Japanese)

**Comment by bernatx** [comment]
Hi,
It seems you need to install the **wheel** and **bdist_wheel** on all your python versions. Try:

```
pip install wheel
python setup.py bdist_wheel
```

and

```
pip3 install wheel
python3 setup.py bdist_wheel

```

Also, remember that version Carla 0.9.13 works only with our forked Unreal Engine 4.26

**Comment by ohashi3399** [comment]
Thanks for your quick response! @bernatx

```
It seems you need to install the wheel and bdist_wheel on all your python versions. Try:

pip install wheel
python setup.py bdist_wheel
and

pip3 install wheel
python3 setup.py bdist_wheel

Also, remember that version Carla 0.9.13 works only with our forked Unreal Engine 4.26
```

"setup.py bdist_wheel" was done in both python and python3 as you pointed out.
Here are the results. 
[python setup.py bdist_wheel.txt](https://github.com/carla-simulator/carla/files/8999915/python.setup.py.bdist_wheel.txt)
[python3 setup.py bdist_wheel.txt](https://github.com/carla-simulator/carla/files/8999920/python3.setup.py.bdist_wheel.txt)
But same error remains.
[make PythonAPI.txt](https://github.com/carla-simulator/carla/files/8999975/make.PythonAPI.txt)
 
I always installed UE4.26 via this document. https://carla.readthedocs.io/en/0.9.13/build_windows/
It would be glad if you could point out my mistake.

**Comment by joel-mb** [comment]
@ohashi3399 Do you have more than one python3 version installed? During `make import` we use the python launcher `py` that may be selecting another version of python.

I would try installing the `wheel` package in the following way:

```sh
py -3 -m pip install wheel
```  

Also, Python2 is deprecated for Windows so `make PythonAPI` only builds the wheel for Python3.

**Comment by ohashi3399** [comment]
Thanks also for quick response @joel-mb -san!
```
I would try installing the wheel package in the following way:
py -3 -m pip install wheel
```
I tried the above command, it worked! I really appreciate both variable advices @bernatx -san and @joel-mb -san.
However ```make launch``` command, there's another issue w.r.t. ```make: *** [CarlaUE4Editor] error 6```. At first, I am looking for the other issues to solve new error. I would like to close this issue. Thanks again.
