### ISSUE TITLE
Add multiple cameras (fish-eye camera will be great!!) on the vehicle through Python. Also, how can I save the vehicle data in the csv file?

### ISSUE THREAD

**Issue by NYJiaxing** [carla-simulator/carla#557]
Hello,
I want to add three more cameras on the vehicle, on in the rear, two on the side. Also, how can I save the vehicle data in the .csv file? I'm more confident with python, so using python will be great.

Thanks a lot

**Comment by NYJiaxing** [comment]
@marcgpuig 
Thank you so much for the reply. I'll check those history issues.

**Comment by marcgpuig** [comment]
Cool!
Considere to close this issue if your question was answered! :)
