### ISSUE TITLE
Does Carla support CAN-data simulation now?

### ISSUE THREAD

**Issue by Fin-Del-Mundo** [carla-simulator/carla#5585]
I wanna do HIL simulation with Carla, but with docs i can't find anything about CAN sensor,does Carla support CAN-data simulation now?Or has some solution about it?

**Comment by fangchaooo** [comment]
No. Carla doesn't support creating CAN signal.

**Comment by Fin-Del-Mundo** [comment]
> No. Carla doesn't support creating CAN signal.

Thanks.
