### ISSUE TITLE
client example

### ISSUE THREAD

**Issue by mhusseinsh** [carla-simulator/carla#559]
what is the difference between running the example with and without autopilot ?

and also what is the idea of running autopilot in manual control ? what is the difference, I can still cannot control the car, right ?

**Comment by nsubiron** [comment]
In "client_example.py", with autopilot the car drives following traffic rules. Without autopilot, it just generates random input. This file is there as an example on how to write your own client, we recommend taking a look at the code.

In "manual_control.py", without autopilot you can drive using the keyboard, but if you prefer to just take a look at the city while the car drives on its own, use the autopilot.

**Comment by marcgpuig** [comment]
@mhusseinsh if your question was answered, please, close the issue.
