### ISSUE TITLE
make package

### ISSUE THREAD

**Issue by FBanani** [carla-simulator/carla#5592]
CARLA version:9.13
Platform/OS: windows
The problem you have experienced: making package
I want to make some changes in town04 and then make package, but I work in windows what should I do? there is no clear guide for this issue in Carla could you guide me

**Comment by XGodina** [comment]
Hi, @FBanani .There are some ways to do it. Have you consulted our documentation?

https://carla.readthedocs.io/en/latest/tuto_A_create_standalone/#export-a-package-from-the-ue4-editor
