### ISSUE TITLE
Import left hand drive custom map

### ISSUE THREAD

**Issue by StephanieMussi** [carla-simulator/carla#5594]
CARLA version: 0.9.12
Platform/OS: Ubuntu 18.04
Problem you have experienced: I am trying to import a custom map from RoadRunner R2021b with left-hand driving direction. The map is exported to OpenDrive 1.4 with Driving Side "Left". However, after import the map to Carla, it's shown that the routes are still perceived as right hand driving. Any suggestion on how to make Carla work with left hand driving? Thanks!

Map in RoadRunner (OpenDrive view):
![Left_OpenDrive](https://user-images.githubusercontent.com/44252274/179441767-67550c0c-fb66-40ea-af3e-78fef8119337.png)

Map in Carla:
![Left_Carla](https://user-images.githubusercontent.com/44252274/179441802-be3f3873-82c6-46b2-9173-4b5f60cad7b7.png)

Export settings:
![export](https://user-images.githubusercontent.com/44252274/179441810-99c9e0d5-ada6-4965-a6bc-939065d024dd.png)

**Comment by StephanieMussi** [comment]
With reference to issue #2442, I managed to get the route planners generated at expected positions. The direction of spawn points, however, still follows right-hand drive manners. 
Even after rotating every spawn point for 180 degrees, the vehicles spawned with *generate_traffic.py* will try to make U-turn and disappear after a short while.

**Comment by JIANGZhengm** [comment]
@

> With reference to issue #2442, I managed to get the route planners generated at expected positions. The direction of spawn points, however, still follows right-hand drive manners. Even after rotating every spawn point for 180 degrees, the vehicles spawned with _generate_traffic.py_ will try to make U-turn and disappear after a short while.

hello, have you ever resolved this issue? I am using CARLA 0.9.15, I am looking forward to your reply.

**Comment by powderly12** [comment]
@SafeDL I am now facing the same issue and did you find a solution? (also on CARLA 0.9.15) Thank you for any help

**Comment by Abhilashsabhi** [comment]
Is there any solution anyone has? I am using Carla 0.9.15.
please help

**Comment by powderly12** [comment]
@Abhilashsabhi Hi, I fixed my problem by exporting the road runner file to Carla using the Carla filmbox method. I was modelling a highway scenario, and for some reason, when I specified right-hand driving while exporting the Carla file, it would produce a left-hand driving Carla map after it was imported. I am not sure why, but it allowed left-hand driving in my case. I hope this helps
