### ISSUE TITLE
how to generate a custom scenario from real world data/autonomous driving dataset?

### ISSUE THREAD

**Issue by markusmat97** [carla-simulator/carla#5615]
I was researching on how can i generate a sceraio from autonomous drivng dataset in carla?
I want to execute this scenario for Hardaware in loop testing?

It would be very helpful if someone can give some resources to do the same?

**Comment by Shreyas-dotcom** [comment]
Hey Mathews, 

You can try using Roadrunner. Inside Roadrunner, there are 2 features: 
1. The Map / Road maker. You can use this to make your own maps / road 
2. The Scenario maker. You can use this to place cars, and set certain drive paths on the map you make with Roadrunner Open Drive. 

Here is the link: https://www.mathworks.com/products/roadrunner-scenario.html#:~:text=RoadRunner%20Scenario%E2%84%A2%20is%20an,the%20scenario%20in%20the%20editor.
