### ISSUE TITLE
Problem importing CAR Model from Blender to Carla UE4. Bone not found.

### ISSUE THREAD

**Issue by KaiPonel** [carla-simulator/carla#5634]
Hello,

I've been trying to import a vehicle into carla for a while now and kept running into problems. After a long time and countless Threads later I decided to just post my problem here, maybe one of you sees a quick fix.

My problem is that the Wheel_Front_Left is not showing up / working like the rest of the bones.

I have to following car Model, for which I added the bones according to Carla's Documentation:

![Screenshot from 2022-07-30 12-40-28](https://user-images.githubusercontent.com/82947121/181906688-23ac61fa-c42e-42a3-b697-aff32b0ae905.png)

With the Structure of the bones looking like this:
![Screenshot from 2022-07-30 12-42-08](https://user-images.githubusercontent.com/82947121/181906717-aa97c632-f1e8-4c70-8ac3-cc437c8a51f0.png)

I can export the model to a fbx just fine. However, when I import the model in UE with the following settings, only 3 out of 4 bones show up in the phsysics asset, and are clickable in the Vehicle_Base file.

Settings of the import (Import does not generate warning etc.):
![Screenshot from 2022-07-30 12-44-17](https://user-images.githubusercontent.com/82947121/181906780-d626970e-2243-40f8-9b9f-8f0eb0d15a60.png)
![Screenshot from 2022-07-30 12-44-08](https://user-images.githubusercontent.com/82947121/181906782-6b0ffec4-612b-45ac-be79-a4f57a540543.png)

VehicleBase after import (Note: Wheel_Front_Left is NOT CLICKABLE, but all other bones are!) :
![Screenshot from 2022-07-30 12-44-56](https://user-images.githubusercontent.com/82947121/181906833-25783a0e-5975-4566-8d95-afbba9636985.png)

VehicleBase_Physics after import (Here the Wheel_Front_Left does not even show up):
![Screenshot from 2022-07-30 12-46-16](https://user-images.githubusercontent.com/82947121/181906865-ec579178-2112-4dce-b7a7-f8623905b0e6.png)

I've been trying to resolve this issue for a long time now. I tried readding the bones and looked very closely, if there are any differences between the one Bone which is causing problems and the rest - but I have not found any...

Altough I've seen a lot of similar issues, I've never seen exactly this bug, which is why I decided so start this thread. I'm thankful for every advice.

**Comment by gsmario** [comment]
Hello! Cold you upload the fbx of the vehicle rigged, so I can have a look.
I can see your bones are named in a different way than in the documentation. (some have a 1 at the end)
This won't work, since the bones need to be named exactly as we say in the documentation.
Also, when you're importing your model, you're assigning it a custom skeleton (named UMD_VehicleBase_skeleton).
This is not necessary, since the bones you rig in the first place are enough, this can give you problems.

Sorry for the long wait, but I'm here to help if I can.
Thanks in advance for your time.
