### ISSUE TITLE
Doea carla support unreal engine 5?

### ISSUE THREAD

**Issue by SalahSoliman** [carla-simulator/carla#5641]

**Comment by Shreyas-dotcom** [comment]
Hey Salah, 


No - Carla does not yet support Unreal Engine 5. It was discussed on discord by German Ros. 

He said: 
`I'm not sure of the benefits of UE5 in terms of applications to vehicles
We are planning to transition eventually, aka when it actually works in all platforms`


https://github.com/carla-simulator/carla/issues/5318

Hope this Helps!

**Comment by SalahSoliman** [comment]
Hi Shreyas,

Thanks, that’s helpful indeed.
Do you mind sharing the discord server/link?

Best,

Salah

**Comment by Shreyas-dotcom** [comment]
Hi Salah,

Here is the link to the Carla Discord: https://discord.com/invite/vNVHXfb
[https://cdn.discordapp.com/icons/444206285647380482/128a0cd902ac8e4fa6b58b15a85f6ec7.jpg?size=256]<https://discord.com/invite/vNVHXfb>
Join the carlasim Discord Server!<https://discord.com/invite/vNVHXfb>
Check out the carlasim community on Discord - hang out with 4,324 other members and enjoy free voice and text chat.
discord.com
Here is where I got the link from: https://twitter.com/carlasimulator/status/995944150402043905?lang=en

Hope this Helps!

Best Regards,
Shreyas



________________________________

**Comment by SalahSoliman** [comment]
Thanks, see you there I guess!

Best,

Salah

**Comment by glopezdiest** [comment]
Closing this as it has been answered already
