### ISSUE TITLE
More Intelligent Update.sh Script

### ISSUE THREAD

**Issue by Bonifatius94** [carla-simulator/carla#5651]
Hi guys,

Your current Update.sh script copies files like crazy. Idk if it's intended, but apparently you're killing disks with it ^^

It's easily possible to pipe the tar.gz download stream of *wget* into the unzipping program *tar*. That way the tar.gz file would never hit the disk because it's streamed via RAM. This allows to download and unzip at the same time which means huge time savings for e.g. the Docker build, etc.

I'm working on a better script and let you know once it's finished.

Best wishes,
Marco

**Comment by Blyron** [comment]
Update files will be deprectaed in UE5, if you still want to contribute to UE4 branch we will be pleased

**Comment by Bonifatius94** [comment]
@Blyron Why did it take you 2 years to write this simple reply? You could have told me a lot earlier xD
