### ISSUE TITLE
./boost/python/detail/wrap_python.hpp:57:11: fatal error: 'pyconfig.h' file not found

### ISSUE THREAD

**Issue by Merealtea** [carla-simulator/carla#5652]
CARLA version: 0.9.13
Platform/OS: Ubuntu:20.04/18.04 
                                    python3.7

Problem you have experienced:
     ![image](https://user-images.githubusercontent.com/67770232/183241685-03b47aa5-e488-4aff-b79b-bf49d1e579e3.png)
    ./boost/python/detail/wrap_python.hpp:57:11: fatal error: 'pyconfig.h' file not found
    I met the problem when I typed the make PythonAPI ARGS=python3.7. I tried in both Ubuntu20.04 and Ubuntu18.04, and they both showed me this problem. 

Steps to reproduce:
      I totally follow the official tutorial here https://carla.readthedocs.io/en/latest/build_linux/. And I successfully built up the UnrealEngin_4.26. And I also successfully finished ./Update.sh. I tried both make PythonAPI and PythonAPI ARGS=python3.7

**Comment by Merealtea** [comment]
I noticed that there is no  -I"/home/luban/anaconda3/envs/Carla/include/python3.7" in my environment, but  -I"/home/luban/anaconda3/envs/Carla/include/python3.7m", I guess this caused this problem, but I don`t know how to solve this problem yet.
![image](https://user-images.githubusercontent.com/67770232/183241926-bb040601-6ed2-4823-951a-fd825d99812c.png)

**Comment by Merealtea** [comment]
Well, I fixed it by 
> ln -s path/to/include/python{version}m path/to/include/python{version}. 
Only add a soft link can avoid this problem, It`s not a big deal. Thanks, I had successfully installed carla right now

**Comment by leishi23** [comment]
> Well, I fixed it by
> 
> > ln -s path/to/include/python{version}m path/to/include/python{version}.
> > Only add a soft link can avoid this problem, It`s not a big deal. Thanks, I had successfully installed carla right now

Same issue, and solved by the soft link. Thanks!

**Comment by 2019211753** [comment]
> Well, I fixed it by
> 
> > ln -s path/to/include/python{version}m path/to/include/python{version}.
> > Only add a soft link can avoid this problem, It`s not a big deal. Thanks, I had successfully installed carla right now

also meet this issue, and solved it! thanks a lot.  i installed python interpreter with multithreading，then the pythonx.x'name turned into pythonx.xm

**Comment by zhuabaguai** [comment]
great work
