### ISSUE TITLE
Custom vehicle being continuously and infinitely spawned 

### ISSUE THREAD

**Issue by eslaaam3** [carla-simulator/carla#5674]
**CARLA version**: 0.9.13
**Platform/OS**: Ubuntu 20.04
**Problem you have experienced**: Custom vehicle is being continuously spawned 
**What you expected to happen**: Custom vehicle spawned properly and only once
**Steps to reproduce**: run `python3 manual_control.py --filter <vehicle>`
**Other information** (documentation you consulted, workarounds you tried):

- [This answer](https://github.com/carla-simulator/carla/issues/2925#issuecomment-651749779) on this [issue](https://github.com/carla-simulator/carla/issues/2925) #2925 for rigging the vehicle and creating its blueprint.
- [This issue](https://github.com/carla-simulator/carla/issues/4784) #4784 because it has a similar error to the one I had, but unfortunately it didn't help.
- #3789

I have created a custom vehicle in Blender and used the above mentioned resources to create the blueprint in Carla.
But when I try to use `manual_control.py` to spawn the vehicle, it keeps showing the errors shown in pictures below and keeps spawning the vehicle continuously and infinitely. I think every time the spawning fails, a new vehicle is spawned!
I tried running `python3 manual_control.py --filter a2` and the Audi A2 works perfectly.
I also tried modifying Audi A2 in VehicleFactory to add my vehicle's blueprint and ran `python3 manual_control.py --filter a2` again, but the same issue persists.

![Unreal Engine after spawning the vehicle](https://user-images.githubusercontent.com/96038568/184869013-2e80c536-46c8-496c-ac2a-91e540493b6e.png)

![Unreal2](https://user-images.githubusercontent.com/96038568/184871472-4cf3d31d-09d6-47ab-8c1d-395b737f04af.png)

![Error1](https://user-images.githubusercontent.com/96038568/184872070-3764914a-0cc2-4097-9f7e-a361831d7d67.png)

![Error2](https://user-images.githubusercontent.com/96038568/184869730-20ff5ce9-bb94-46e6-9eec-3cb65a688aaa.png)

**Comment by gsmario** [comment]
Hello, sorry for the long time to answer.
Did you solve your problem? If you still need help let me know.

**Comment by gsmario** [comment]
I'm closing this issue, feel free to reopen it if you need more help.
Thanks.
