### ISSUE TITLE
Hero vehicle doesnt perform lane change from centrelane to right/left

### ISSUE THREAD

**Issue by darrel1** [carla-simulator/carla#5679]
CARLA version: 0.9.11
Platform/OS:Ubuntu 18.04
Problem you have experienced: In a 3 lane map, when the hero vehicle is in the centre lane, it doesnt perform a lane change towards right/left even when indicator state is on.
What you expected to happen: expecting the hero vehicle to perform a lane change
Steps to reproduce:
Other information (documentation you consulted, workarounds you tried): Tried placing the hero vehicle in the centre and rightmost lane, but it did not perform a lane change even when the indicator was turned on.

![Screenshot from 2022-08-18 13-52-38](https://user-images.githubusercontent.com/61737303/185347078-c267db38-f59c-4099-9592-b57c26bd6b7f.png)

**Comment by glopezdiest** [comment]
Hey @darrel1, I'ma  bit confused by your question, so can you please provide more information? How are you controlling the ego vehicle? What indicator are you talking about?
