### ISSUE TITLE
How to get the information of actors in the field of view.

### ISSUE THREAD

**Issue by Basavaraj-PN** [carla-simulator/carla#5699]
Hello, is there any virtual sensor that gives actor information in certain field of view?
If it is available can we customize other senor parameter like range of the sensor and sensor position on ego.

**Comment by TR-Monash** [comment]
Have a look at [this](https://github.com/carla-simulator/carla/issues/5691#issuecomment-1226833269).

**Comment by glopezdiest** [comment]
Hey @Basavaraj-PN, unfortunately, CARLA doesn't have a way to do that, but the solution proposed by @TR-Monash seems to be a good one.

Closing this issue as it seems fixed, but feel free to reopen it if needed

**Comment by Basavaraj-PN** [comment]
@glopezdiest  @TR-Monash 
hey, better solution for this issue:  [actor sensor](https://github.com/Basavaraj-PN/actor-sensor-for-carla-simulator/blob/main/README.md)
