### ISSUE TITLE
assert numpy.sum(point_count_by_channel) == len(point_cloud.array) AssertionError

### ISSUE THREAD

**Issue by zhang261007** [carla-simulator/carla#570]
assert numpy.sum(point_count_by_channel) == len(point_cloud.array)
AssertionError
![error01_carla](https://user-images.githubusercontent.com/17513480/42431498-6dad14c2-8378-11e8-997d-73731036b4c2.png)

**Comment by marcgpuig** [comment]
Hello @zhang261007.
Did you modified the original code?
