### ISSUE TITLE
Feature request : add native support M1 to Carla simulator

### ISSUE THREAD

**Issue by MaherJendoubi** [carla-simulator/carla#5700]
CARLA version: 0.9.13
Platform/OS: macOS Monterey 12.5.1
Problem you have experienced: Can not run carla simulator on M1
What you expected to happen: Add native support M1 to carla simulator

**Comment by RaviBeagle** [comment]
Sorry if this is a noob doubt I have. CARLA uses Vulkan as I understand. Does the M1 not have Vulkan implemented ?

**Comment by Explosion-Scratch** [comment]
I also need this @stale please re-open

**Comment by Explosion-Scratch** [comment]
thanks

**Comment by Blyron** [comment]
We are not gonna support macOS, there are community aimming to do that but there won't be official support in short term
