### ISSUE TITLE
Unable to edit level: Level is locked in CARLA Unreal project

### ISSUE THREAD

**Issue by snehanjalikalamkar** [carla-simulator/carla#5717]
I require adding some custom objects in the CARLA maps for larger towns. Whenever I drag any object into the map editor, I get an error: The requested operation could not be completed because the level is locked (see image). This does not happen with the map of Town01 and Town10. However, I required larger maps, how could I unlock the rest of the maps (please note: I am still a newbie at Unreal Engine)?

![Screenshot (1)](https://user-images.githubusercontent.com/92789678/187955861-92efc297-3970-4d16-aae8-95391845b095.png)

**Comment by ishaan95** [comment]
Have a look at "add assets to a level" [in the CARLA docs here](https://carla.readthedocs.io/en/latest/tuto_M_custom_layers/). It mentions unlocking the level by toggling a lock icon.

**Comment by glopezdiest** [comment]
As @ishaan95 said, the docs provided should have all the information needed. Closing this issue as it seems answered but feel free to reopen it if there are still some issues
