### ISSUE TITLE
How to make autopilot vehicle take the same route at intersection every time?

### ISSUE THREAD

**Issue by snehanjalikalamkar** [carla-simulator/carla#5729]
I am required to capture 15-minute simulation images using 6 RGB cameras at 24fps. Many frames (~10%) are lost if I attach all 6 RGB cameras and record from them simultaneously. 
So, I spawned the autopilot vehicle at the same position each time and captured it from 2 cameras at a time. I ran the simulation thrice to get images from all 6 cameras. 
Since the paths of the vehicle are non-deterministic, the 3 simulations produce different results. 

I looked into `set_random_device_seed` using the traffic manager to solve this problem, but it didn't work.
1. How could we make the car take the same route in every simulation?
2. How to use `set_random_device_seed` ? What are the expected values of `seed_value`?

**Comment by glopezdiest** [comment]
Hey @snehanjalikalamkar. What version of CARLA are you using? I don't remember if this was added before or after 0.9.13, but the traffic manager has a `set_path` function, that can help you do that. [Here](https://carla.readthedocs.io/en/latest/tuto_G_traffic_manager/#specify-routes-for-vehicles) are the docs on how to do it.

Closing the issue, but feel free to reopen it if this doesn't fully solve your question
