### ISSUE TITLE
Many buildings are not perceived by the LiDAR sensor

### ISSUE THREAD

**Issue by vbrebion** [carla-simulator/carla#5732]
Hi!

As part of my research work, I am currently generating perception data with CARLA for learning purposes.
However, it appears that the LiDAR sensor (which is a key component for me) is unable to perceive many buildings, and thus returns erroneous data.

Would it be possible for you to take a look at this issue?

Best,
Vincent

---

**CARLA versions:**
0.9.13; nightly

**Platform/OS:**
Ubuntu 20.04

**Problem you have experienced:**
When I use the LiDAR sensor, many buildings appear to be completely invisible, while they are correctly perceived by other sensors.

- A first example, in the Town01 map:

  ![town01_rgb](https://user-images.githubusercontent.com/61004974/188665704-377ebe43-ecdd-4fe3-af53-d74e58e775e4.png)
  RGB reference

  ![town01_depth](https://user-images.githubusercontent.com/61004974/188665821-63e9fbc3-8cbf-4dde-97b5-212a5689f032.png)
  Depth reference

  ![town01_lidar](https://user-images.githubusercontent.com/61004974/188665972-c95df038-a3b6-4f4b-b351-2653724ae562.png)
  Projected LiDAR data

  ![town01_depth_lidar](https://user-images.githubusercontent.com/61004974/188666105-34fc87c9-1e74-44b0-9cbd-3e4e5d0bb6a8.png)
  Superimposed depth and LiDAR data. Notice the incorrect superimposition for the two large buildings on the right, as well as the two distant buildings on the center-left.

- Another example, in the Town10HD map:

  ![town10hd_rgb](https://user-images.githubusercontent.com/61004974/188666932-5e8107f4-2f6c-41ae-9fa7-c7f8e107c454.png)
  RGB reference

  ![town10hd_depth](https://user-images.githubusercontent.com/61004974/188667029-01415f0e-4983-4848-9b37-1de4089d4584.png)
  Depth reference

  ![town10hd_lidar](https://user-images.githubusercontent.com/61004974/188667074-0a0c36de-229c-4f1a-a2e1-ec948974f560.png)
  Projected LiDAR data

  ![town10hd_depth_lidar](https://user-images.githubusercontent.com/61004974/188667138-4d359f1f-18bf-48e6-8382-7a86e8247208.png)
  Superimposed depth and LiDAR data. This time, all the buildings are missing, as well as some other elements, like the flags on the poles *(edit: the issue with the flags seems to have already been fixed in the development version)*.

**Steps to reproduce:**
- Load any map with buildings in them (Town10HD is where the issue seems to appear the most)
- Spawn a LiDAR (I configured it here with a large FOV and many channels for a good visualization of the issue)
- Spawn a depth camera
- Compare the buildings in the projected LiDAR data and in the depth images

**Other information (documentation you consulted, workarounds you tried):**
- I tested the latest development version to see if this issue had already been fixed since the release of the 0.9.13 version, but the issue is still present.
- I know two other similar issues already exist (<https://github.com/carla-simulator/carla/issues/3829> and <https://github.com/carla-simulator/carla/issues/3953>), but they were opened in early 2021, and it appears the source of the error was found at the time (but never merged?)

**Comment by DarrenWong** [comment]
I also encounter a similar issue using Town10HD with Carla 0.9.11,
![image](https://user-images.githubusercontent.com/5771106/191402274-7169971a-1c6b-47ea-a103-b1ff686c75ee.png)

**Comment by glopezdiest** [comment]
Hey @vbrebion, that is indeed the case, thanks for reporting this :+1: . Apparatenly, due to some missconfigurations, some assets are invisible for the LIDAR. We'll be checking all our towns, making sure this is no longer the case, and I'll report back once it's fixed.

**Comment by heiwang1997** [comment]
Any update on this? Thanks!

**Comment by glopezdiest** [comment]
Yes, we just fixed it last week and it is already in master.

Feel free to reopen the issue if you see any assets that aren't detected by the LIDAR

**Comment by heiwang1997** [comment]
@glopezdiest Thank you for your work! This sounds great!

Could you please inform me where can I see the latest changes? For me the latest commit in `master` is still [8854804](https://github.com/carla-simulator/carla/commit/8854804f4d7748e14d937ec763a2912823a7e5f5), which is November last year...

**Comment by DarrenWong** [comment]
I tried today's dev branch should be ok to detect the building in Town10. Thanks a lot!

![image](https://user-images.githubusercontent.com/5771106/203024797-01846f2b-8c61-4252-be5b-f47a86b52466.png)


> I also encounter a similar issue using Town10HD with Carla 0.9.11, ![image](https://user-images.githubusercontent.com/5771106/191402274-7169971a-1c6b-47ea-a103-b1ff686c75ee.png)
