### ISSUE TITLE
CARLA takes 100% GPU without running a simulation

### ISSUE THREAD

**Issue by RaviBeagle** [carla-simulator/carla#5749]
Hello CARLA-Developers,

Please see this issue below

_CARLA version_ :  0.9.12
_Platform/OS_  Ubuntu 20.04 on HP ZBook Z8, NVIDIA RTX A3000 GPU, NVIDIA-SMI 510.85.02    Driver Version: 510.85.02 
__Problem I experienced_ :  CARLA server takes 100% GPU without even running a simulation
What I expected to happen_ :  It should not consume GPU resource until we run a simulation using a client
_Steps to reproduce_ :  Just run ./CarlaUE4.sh -carla-server -RenderOffScreen on such a system and I see the GPU at constant 99% utilization and laptop fan runs continuously. 

Workaround. The only workaround I can see is that I disable rendering at the end of the simulation. But my simulation script needs to set that explicitly at the start of the script.

```
    finally:
        print("Elapsed total time : ", time.time() - start_record_full)
        init_settings.no_rendering_mode = True
        world.apply_settings(init_settings)
        time.sleep(2.0)
```
With this I see the GPU utilization drop down to 20% or maybe less.

**Comment by RaviBeagle** [comment]
Is this normal ?

**Comment by RaviBeagle** [comment]
After some analyzing myself, I found that CARLA by default loads the Town10HD Map and runs asynchronously which is causes 100% GPU utilization.

This level of utilization is also true when running CARLA with any other town map at a high fps (say 1000 or even 100 fps) in synchronous mode. 
When I run the simulation at 10fps the GPU utilization drops between 20-40%

**Comment by huangmingguang** [comment]
hi, I have the same problem. How to do it to solve this problem.
