### ISSUE TITLE
Changing camera position and orientation during simulation

### ISSUE THREAD

**Issue by sergiocaccamo** [carla-simulator/carla#575]
Hi,

I'm trying to modify the position and rotation of a given camera in the scene without restarting the episode. Similar questions have been asked (#58 and #256) where you specify that it is not directly possible to do so with the current version. Since you are now working on a new server I wonder whether you plan to include this functionality. If not, do you have any suggestion for how to convert _request_new_episode() into _update_episode(settings). 

Thanks

**Comment by marcgpuig** [comment]
Hi @sergiocaccamo.
It will be available in the next release and I recommend you to wait for it ;)

**Comment by sergiocaccamo** [comment]
Wonderful! Release date? :D

**Comment by marcgpuig** [comment]
@nsubiron did not seem very convinced while he was saying... _this month_

**Comment by nsubiron** [comment]
This month, most probably :wink:

**Comment by sergiocaccamo** [comment]
Great, thanks!

**Comment by kylop** [comment]
Well done delivering in time ;)

**Comment by marcgpuig** [comment]
As you said, the 0.9.0 is here! 
So I'm closing the issue :)
