### ISSUE TITLE
wheel run freely but vehicle can not move

### ISSUE THREAD

**Issue by YanggangZhang** [carla-simulator/carla#5778]
CARLA version:0.9.12
Platform/OS:18.04

I  made a simulation scene by roadrunner and import it into carla with UE roadrunner plugin freely. when i run "python generate_traffic.py" to test this map, some errors happened. the vehicle wheel overlap with road surface but run freely and the vehicle can not move. someone has meet with the same proplem too? how to fix it? thx! 

problem:
![765bf613d89b3ad038ae27077c523a8](https://user-images.githubusercontent.com/66670433/191693746-685f8282-ddb3-4f42-aac2-1eeb1faaae13.jpg)

road collision setting:
![7cb6439917d2ee81d1db4ae4a2c7fc4](https://user-images.githubusercontent.com/66670433/191693375-b3c5f61a-8340-46a7-ae76-1b7384d8384d.jpg)

**Comment by boxwayne** [comment]
Had you solved this problem? I got the same problem and look for a solution.

**Comment by yu-ju-chiu** [comment]
Have you solved the issue?
The CarlaUE4 gets stuck every time, when I run python file.

**Comment by gsmario** [comment]
Hello, sorry for the long time answer, do you still need help with this?
Let me know, I'm trying to reproduce this problem but i can't.

**Comment by gsmario** [comment]
I'm closing this issue, feel free to reopen it if you need help.
Thanks.
