### ISSUE TITLE
Strange neon lighting

### ISSUE THREAD

**Issue by kazimpal87** [carla-simulator/carla#5801]
Hi,

Sometimes when running carla, the lighting will go strange and produce images like this:

![Town07_1_00000000](https://user-images.githubusercontent.com/22006696/193039954-f5ce1766-8c44-42ca-b1cd-fe0885890363.jpg)

I don't really know why/when this happens.

I'm using carla 0.9.13 on Ubuntu.

**Comment by XGodina** [comment]
This is because Vulkan runs out of memory and produces these effects.

**Comment by kazimpal87** [comment]
why would that happen?

I am running a script which captures images from static cameras. Periodically the script loads a new map and spawns a load of new vehicles. If this is a memory thing, I guess either theres a memory leak or (more likely) I'm not properly cleaning up before loading the new map?

**Comment by XGodina** [comment]
Yes, we always have memory problems with Vulkan, When loading to many assets usually happens this or directly crashes.

**Comment by kazimpal87** [comment]
is there an alternative to Vulkan, or some other way to avoid this problem?

**Comment by Blyron** [comment]
Hello!
We only support Vulkan in Ubuntu. Some users tried OpenGL, but we do not support that. Otherwise you could reduce your content quality.

https://carla.readthedocs.io/en/latest/adv_rendering_options/#setting-off-screen-mode-version-0912

Are you happy with this answer?
