### ISSUE TITLE
How to manipulate car on the Carla using Can-Utils 

### ISSUE THREAD

**Issue by aterzgar** [carla-simulator/carla#5844]
Hi all, 

I would like to send and receive CAN bus data to control the car on the Carla by Can-Utils. I am able to read data(speed, steering wheel etc.) from Carla, but I cant manipulate behaviour of the car over Can-Utils. Where should I send my CAN bus data to be able to control the car as an external actor?

**Comment by donatoaz** [comment]
Hi @aterzgar, I am interested in reading from the simulated can bus. Would you be willing to share part of your code that shows how to do that?

**Comment by donadelden** [comment]
Hi everyone! Any update on this?

**Comment by aterzgar** [comment]
Hi @donatoaz, I have replicated code from https://youtu.be/oISCmgtoNbI?feature=shared according to my own purpose, maybe it might be helpful for your project too.

**Comment by theSoyboii** [comment]
@donatoaz @aterzgar
I may be late to the party, but have the exact same question. Do you guys have anything to share that shows how to read from simulated CAN bus? The link above is broken :(

**Comment by gsmario** [comment]
Sorry, we do not currently support CAN communication with CARLA. 
I'm afraid you will have to create your own bridge to make it work.

**Comment by gsmario** [comment]
Sorry, we do not currently support CAN communication with CARLA.
I'm afraid you will have to create your own bridge to make it work.
