### ISSUE TITLE
Rebuild error in UE4 4.18

### ISSUE THREAD

**Issue by ghost** [carla-simulator/carla#585]
The UE4 version is 4.18 in Ubuntu16.04 and the Setup is success. But in the Rebuild process, it got the following error:

```
ERROR: UBT ERROR: Failed to produce item: /home/carla/Unreal/CarlaUE4/Plugins/Carla/Binaries/Linux/libUE4Editor-Carla.so
Makefile:620: recipe for target 'CarlaUE4Editor' failed
make: *** [CarlaUE4Editor] Error 5
```

What should i do to deal with this problem.
thank you.

**Comment by nsubiron** [comment]
Hi @dosthwrong,

That's some compilation error, check the log (before that) to see the actual error.
