### ISSUE TITLE
Issue building CARLA during make CarlaUE4Editor: cannot find xerces 3.2.3 since they upgraded to 3.2.4

### ISSUE THREAD

**Issue by sebastienmascha** [carla-simulator/carla#5852]
CARLA version: 0.9.13
Platform/OS: Ubuntu 18

Problem you have experienced: Impossible to build the dependency xerces 3.2.3

What you expected to happen: 
- Cannot download the archived 3.2.3 version: https://ftp.cixug.es/apache/xerces/c/3/sources/xerces-c-3.2.3.tar.gz
- This file doesn't exist since they released a new version on October 17th 2022

Steps to reproduce: 
- Build the Carla.Dockerfile using master or 0.9.13 branches.
- This happens when running `cd Util/BuildTools && make setup` (bash Util/BuildTools/Setup.sh)

Other information (documentation you consulted, workarounds you tried):
- We can replace `https://ftp.cixug.es/apache/xerces/c/3/sources/` by `https://archive.apache.org/dist/xerces/c/3/sources/`

**Comment by sebastienmascha** [comment]
It has been fixed in the latest develop. Thanks!

**Comment by hexrefugee** [comment]
3q
