### ISSUE TITLE
where can I see the source code in UE4 Editor?

### ISSUE THREAD

**Issue by yumianhuli2** [carla-simulator/carla#591]
Hello,I have not seen the source code in UE4 Editor,where can I see the source code in UE4 Editor?

**Comment by marcgpuig** [comment]
Hi @yumianhuli2, make sure you have the following active

![853e5e4c8ccc21fa901125d2c0f4a94e](https://user-images.githubusercontent.com/15848712/42812528-40920384-89be-11e8-9b9d-d4133948f4a0.png)

**Comment by yumianhuli2** [comment]
thanks，help me a lot！

**Comment by marcgpuig** [comment]
Glad it worked!
