### ISSUE TITLE
Question about render graphic API on 0.9.13

### ISSUE THREAD

**Issue by yuanhaorannnnnn** [carla-simulator/carla#5918]
CARLA version: 0.9.13
Background: In fact, it's more like a question not an issue, I did a deep search on web also some trails by myself but no luck, so I decide to put it here and really hope some insights even solution from you guys.
Platform/OS: Linux 20.04
Problem I have experienced: Recently I use **Renderdoc** (a graphics debugger) to capture some render data like **GBuffer**, here are some my expriments results.
| Test ID | Executable launch with Renderdoc | Command | Graphic API recognized | Capture status |
| - | - | - | - | - |
| 1 | UE4Editor | ./UE4Editor ./path-to-my-CaralUE4.uproject | Vulkan(Acitve) OpenGL(Unsupported) | success |
| 2 | CarlaUE4-Linux-Shipping | sh CarlaUE4.sh | Vulkan(Acitve) with warning | success |
| 3 | manual_control.py(launch server with **sh ./CarlaUE4.sh** ahead) | python manual_control.py | OpenGL(Unsupported) | fail | 
| 4 | manual_control.py(launch server with **make launch** ahead) | python manual_control.py | OpenGL(Unsupported) | fail | 
| 5 | manual_control.py(launch server with **./UE4Editor ./path-to-my-CaralUE4.uproject** ahead) | python manual_control.py | OpenGL(Unsupported) | fail | 

What I expected to happen: Surely I want the last three tests work and I can **capture the render data from a camera-in-vehicle view**. Also I noticed the reason of OpenGL is unsuported is an issue of version(cuz Renderdoc only support OpenGL3.2+). So I hope I can **get result rendered by Vulkan on the client side**, maybe it make more sense?

Here is the attach the screenshot of the error.
![2022-10-31 17-20-51屏幕截图](https://user-images.githubusercontent.com/37274406/200260500-6b9c7651-4d10-4118-a86d-ae338498681c.png)

Steps to reproduce: 

1. For first two tests, we need to configure some paths in Renderdoc and press launch
2. For the rest, we need launch server ahead and configure some path in Renderdoc as well and press launch

here are the attaches the screenshots of my Renderdoc launch configurations.

server
![2022-11-07 16-21-58 的屏幕截图](https://user-images.githubusercontent.com/37274406/200261820-529debcc-b8c9-4154-8891-6d06f73b865a.png)

client
![2022-11-07 16-22-24 的屏幕截图](https://user-images.githubusercontent.com/37274406/200261780-d8cf3c6c-dda0-4652-b456-ea860122fcaa.png)

Other information: 
workarounds I tried:
1. The expriments I mentioned above;
2. Modify the macro **LINUX_USE_OPENGL_3_2**  of UE4 source code from 0 to 1 and re-build the UE;
4. Use pygame API to change driver on manual_control.py.

**Comment by Blyron** [comment]
We only support Vulkan officially you can try to use OpenGL but Vulkan will be our main RHI in Linux
