### ISSUE TITLE
Is there a way to set the start and goal position? (+ know street coordinates x y z)

### ISSUE THREAD

**Issue by danielcomas25** [carla-simulator/carla#592]
Hello,

I really like the simulator, I think it is one of the best around. However, I have been trying to run with the driving benchmark example, and I know that by using that I can set the start and ending position (it can be found here, I followed all the instructions  (http://carla.readthedocs.io/en/latest/benchmark_creating/). However, I encountered problems running that code with some errors as 'Can't find the server' or 'Timeout', other codes like client_example.py and manual_control.py work perfectly. In addition, the members wrote in an issue that the driving benchmark is not available for the current released version. 

However, **I would like to know if there is a hint for setting the start and goal position**. Furthermore, is there a way to know the road coordinates of the towns? or do I need to move around Unreal Engine and find it myself, that solution would not be appropriate for my experiment since I need the range of accurate street coordinates where the car should go. There has to be a way to know those street range coordinates for each town since there is a off-road percentage which it is calculated. I will really appreciate some hints in these.

Thank you,

**Comment by felipecode** [comment]
Hey @danielcomas25 
The benchmark is ready starting from 0.8.2. Could you point me the issue that say it is not released yet ?
This issue should be closed.

The start and goal positions are predefined list of start points. Unfortunately, we still cannot 
spawn agents anywhere. However that is work in progress, and is likely to be released this summer.

We have developed some tool to visualize the possible start positions. You can see more about it
on our blog post. http://carla.org/2018/04/05/release-0.8.1/

Cheers,

Felipe
