### ISSUE TITLE
Does GTX 4090 is available to install Carla 0.9.13?

### ISSUE THREAD

**Issue by hexrefugee** [carla-simulator/carla#5943]
CARLA version:0.9.13
Platform/OS: ubuntu20.04
Problem you have experienced: I decided to buy NVIDIA GeForce GTX 4090, and I have a question, is it adequate to install Carla?
What you expected to happen: Install Carla

Thank you!

**Comment by TR-Monash** [comment]
Shouldn't be an issue. I'm running Carla ona 3080 without any issues.

**Comment by hexrefugee** [comment]
> 

3q
