### ISSUE TITLE
Is there any way to change position when player vehicle is running?

### ISSUE THREAD

**Issue by mznw** [carla-simulator/carla#595]
Is there any way to change position when player vehicle is running? Just changing the position and heading，and speed remains the same

**Comment by marcgpuig** [comment]
Hi @mznw.

This is not currently possible right now, but it will be possible with the changes in the nex release :)
Take a look at #439.

**Comment by marcgpuig** [comment]
@mznw This is currently possible on 0.9.0!

**Comment by SuperShinyEyes** [comment]
> @mznw This is currently possible on 0.9.0!

Hi Marc, thanks for the great work. It'd be helpful for us if you could point a specific PR which resolved this issue. :)

**Comment by Himverma2012** [comment]
Hi, I want to read the location of vehicle CG from a file and change the vehicle location accordingly. I also want to change the rotation of the vehicle at each timestamp while carla simulation is running. How to do that? get_transform() is there but there's no 'set_transform()' function. What's the workaround?
