### ISSUE TITLE
How to search and spawn a .uasset from the content folder in CARLA?

### ISSUE THREAD

**Issue by ronyshaji** [carla-simulator/carla#5952]
Hallo
I created a custom .uasset blueprint to include in CARLA. Now I am looking for a solution to include the .uasset blueprint with python API. How can I do this as blueprint library gives the build in carla content ?

**Comment by buaali** [comment]
I have the same problem. Help, please

**Comment by Blyron** [comment]
You can have now the BlueprintFactory to add your blueprints and spawn those in using Python
