### ISSUE TITLE
Does dragging the vehicle blueprint to world consider as an actor ?

### ISSUE THREAD

**Issue by ronyshaji** [carla-simulator/carla#6003]
Hallo
I am having a doubt. I dragged and dropped a car from the carla blueprint.
Then I run the simulation and get the list of actors using the python API.
But it doesnot have the car in it ? Do you have any idea why this is happening ?

Anyway to access the car i just dragged into the world using python ?

**Comment by glopezdiest** [comment]
What you are doing is drop a blueprint into the scene, not creating an actor, hence why the API doesn't see it. For you to see it, it has to be spawned on runtime (either through the server, your client, or another one). You might be able to use the [world.get_level_bbs()](`https://carla.readthedocs.io/en/latest/python_api/#carla.World.get_level_bbs`) function to get its information, but again, it's not an actor, so you won't be able to treat it as one
