### ISSUE TITLE
The planned path is close to the roadside

### ISSUE THREAD

**Issue by fentuoli** [carla-simulator/carla#6018]
Hi, I encountered a problem when I ran carla_ad_demo.launch, I found that the planned path is always close to the roadside, as shown below, but I want the ego_vehicle could run in the center of the road. 
I think this may be because the path planned by the `global_route_planner` is close to the roadside. So what can I do to make the vehicle drive in the middle of the road?

![Screenshot 2022-12-06 22:41:04](https://user-images.githubusercontent.com/36686362/205944047-3dcf6253-c020-445d-96bf-93bac5b8e414.png)

**Comment by glopezdiest** [comment]
Hey, that road turns left, so the leftmost lane is the shortest one, hence why the global route planner choses it. There really isn't a solution apart from adding intermediate points, and joining the different global route planner into one later
