### ISSUE TITLE
Lidar can't sense the moving Sphere Actor in UE4

### ISSUE THREAD

**Issue by jystin** [carla-simulator/carla#6036]
Hello together,

CARLA version: 9.13
Platform/OS: Ubuntu 18.04
Problem you have experienced:  Lidar can't sense the moving Sphere Actor in UE4

I am currently experiencing a problem regarding the LiDAR point clouds with CARLA, running on Ubuntu 18.04.
As shown in the attached screenshot,  Moving Sphere is on the left, stationary Sphere is on the right. I set a movable Sphere on the map, but the Lidar can't sense it. But it can sense the stationary Sphere actor.

Is this some configuration problem?

Looking forward hearing from you.

Best Regards

Xin JIANG
![2022-12-12 11-36-24 的屏幕截图](https://user-images.githubusercontent.com/72262187/207024740-01a82e54-b2c8-4501-8ca0-87fa5451da4c.png)
![image](https://user-images.githubusercontent.com/72262187/207023996-519a3469-df34-46c2-8c4d-f0199b12ec77.png)

**Comment by Blyron** [comment]
This problem must be related with channel responses settings.
