### ISSUE TITLE
A "make launch" error on Ubuntu 18.04

### ISSUE THREAD

**Issue by ParaWold** [carla-simulator/carla#6040]
Hello everyone:

I am building Carla 0.9.12 on my Ubuntu 18.04.
I am almost succeeding until the following error.
The error is similar to https://github.com/carla-simulator/carla/issues/5244, while it seems that I went further.

Before the error, 
![Screenshot from 2022-12-13 14-38-32](https://user-images.githubusercontent.com/120151841/207247030-fcf23105-18ed-4aee-9e66-13b1828f7630.png)

The detailed error information:
![Screenshot from 2022-12-13 14-39-01](https://user-images.githubusercontent.com/120151841/207247111-8274b899-4a79-4d3c-9916-ac0e6607f2ae.png)

The related document(carla/Util/BuildTools/BuildCarlaUE4.sh):
![Screenshot from 2022-12-13 14-40-04](https://user-images.githubusercontent.com/120151841/207247250-9bd40ae9-3548-4bd9-8c27-32ec9b268ff5.png)

Does anybody have any idea?
Thanks very much:)

**Comment by Blyron** [comment]
Yeah getting stucked at 95% is common for Unreal Engine, please retry again until that percetange is passed. Vulkan may be creating isuses during the 1st times openning Carla. 

If you already have solved this issue are you happy to close it?
