### ISSUE TITLE
frame skipping - dataset

### ISSUE THREAD

**Issue by mhusseinsh** [carla-simulator/carla#605]
when i start the client example or whatever python client, and I have the option of saving the images to disk, firstly, the car is not directly on the road, it starts above the road and goes down, then start driving

Accordingly, I am not interested in the sensors data that are logged at this period.  Is there a way to let the sensors start logging data when the car is on the street, so something maybe like frame skipping, that it skips the first 10-20 frames when the car is moving down.

Attached is an example for what I just said

![ezgif-4-d2b12e3e55](https://user-images.githubusercontent.com/33177438/42888796-4640d544-8aa9-11e8-964a-474eab833da2.gif)

**Comment by marcgpuig** [comment]
Hi @mhusseinsh.
This happens to avoid collisions between the wheels and the road at the start of the episode.
Try saving only the images after the frame 20 ;)
