### ISSUE TITLE
Initializing car at a specified location and a specified speed

### ISSUE THREAD

**Issue by hs105** [carla-simulator/carla#607]
How to set our car to a given position? It seems we're able to select from a list of pos_start defined in Unreal editor. So we just go ahead adding a playerstart in Unreal and use a new ID for it. Then we can compile and use this new playerID to start the car from there. Correct?

Can we set the car's speed to a given value?

**Comment by marcgpuig** [comment]
Hi @hs105!

> So we just go ahead adding a playerstart in Unreal and use a new ID for it. Then we can compile and use this new playerID to start the car from there. Correct?

That's correct!

> Can we set the car's speed to a given value?

Not right now, but this will change in the next release, take a look at #595

**Comment by hs105** [comment]
even starting the car at a given speed is not possible when an episode starts? Just the initial speed we want to set it.

**Comment by marcgpuig** [comment]
Hey @hs105.

This is not possible with our code as it is, but you can test it using Unreal Engine editor. We haven't test anything like that currently.

**Comment by hs105** [comment]
Got it. 

thanks!

**Comment by marcgpuig** [comment]
You welcome!

**Comment by gut-yu** [comment]
@hs105 
Could you please tell me your method to gain an initial speed when an episode starts ?
