### ISSUE TITLE
N-wheeled vehicle from release blog post

### ISSUE THREAD

**Issue by Sid1057** [carla-simulator/carla#6074]
Hello! First of all thanks for the last release!

I am very interested in the car from carla release blog post.

I thought it would be in release, but after checking the blueprint info and outputting the vehicle gallery script, I realize that this vehicle is not integrated into the current release.

Will you add them in some patch?

![image](https://user-images.githubusercontent.com/12153757/210187553-e948203e-c168-431b-b055-6c1192ef376c.png)

**Comment by KPicherit** [comment]
I'm also interested in this model !

**Comment by Madecu** [comment]
Hi @Sid1057 ,

The 6 wheeled truck has been added into Carla source. You can download it from there.

Thanks for open an issue here and I apologize for the answer delay.

**Comment by Sid1057** [comment]
@Madecu thanks a lot!

**Comment by KPicherit** [comment]
Got it, thanks a lot ! :+1:
