### ISSUE TITLE
Question about set_desired_speed

### ISSUE THREAD

**Issue by icerooqiu** [carla-simulator/carla#6079]
CARLA version: latest
Platform/OS: Windows
Problem you have experienced: set_desired_speed in the traffic manager doesn't work, the NPC simply freezes.
What you expected to happen: /
Steps to reproduce: /

**Comment by SternSu** [comment]
Have you used actor's function 'set_autopilot(True)'? When you are using traffic manager to control actor's motion, if you don't conduct the operation mentioned above, the actor will just freeze as you said.
