### ISSUE TITLE
Camera output distorted

### ISSUE THREAD

**Issue by AlvaroRausell** [carla-simulator/carla#6085]
CARLA version: 0.9.14
Platform/OS: Windows 11 using a GTX 1080ti
Problem you have experienced: Camera (tried depth and rgb) output distorted as shown below
![043794](https://user-images.githubusercontent.com/33221237/210809810-6fa5dead-c685-4fc6-b8c3-ed57acc252df.png)
What you expected to happen: Image showing the world without distortion
Steps to reproduce: Follow the quick start guide until `camera.listen(lambda image: image.save_to_disk('out/%06d.png' % image.frame))`. Output images come with distortion.
Other information (documentation you consulted, workarounds you tried): Tried playing around with camera settings or other maps to no avail.

**Comment by MatthiasWildeBusiness** [comment]
Hi, 
I discovered a similar problem, which might be also your problem. When I changed my camera resolution to a aligned value (I used multiple of 64 pixels) I could solve it. It was needed to align for both, width and height:

I used width = 600  ==> stride problem
Align width to 640 ==> OK

Hope this helps you also.

**Comment by vadim7s** [comment]
I have the same camera distortion problem after going to v 0.9.14. Then I went back to v0.9.13, everything works again. To test quickly you can run visualise_multiple_sensors.py in the examples folder in v13 vs.14. Does this mean it is v14 issue?

**Comment by mawistc** [comment]
> I have the same camera distortion problem after going to v 0.9.14. Then I went back to v0.9.13, everything works again. To test quickly you can run visualise_multiple_sensors.py in the examples folder in v13 vs.14. Does this mean it is v14 issue?

And is your resolution aligned?

**Comment by bernatx** [comment]
The problem happens only in Windows (DirectX) for resolutions not aligned to 256.
DirectX add some extra bytes to each row.
We have made a PR to fix that.

**Comment by kevintsq** [comment]
Will you be releasing a version of this bug fix in the near future, as it is indeed a serious bug?

**Comment by kevintsq** [comment]
Thank you, then I’ll wait for your new build instead of building my own version or reverting to the old one:)

**Comment by TzabarDolev** [comment]
I just wrote a short blog post about this issue on my Carla research blog - https://carlasimblog.wordpress.com/2023/09/16/the-64-division-curse/. And added a short code snippet to fix this.

**Comment by Noubissie** [comment]
[https://github.com/carla-simulator/carla/issues/6565#issuecomment-1722974703]this may be of help

**Comment by SExpert12** [comment]
Solution for this given here:
https://github.com/TzabarDolev/carlablog/blob/main/fix_image_distortion.py

**Comment by Blyron** [comment]
Is this problem fixed now?
