### ISSUE TITLE
Large map import failing

### ISSUE THREAD

**Issue by brscholz** [carla-simulator/carla#6096]
EDIT: A non-geolocated version of my map was working, so I only need to find out what's wrong with the geolocation.

---------------------------------------------------------------------------------------------

Hi everyone,

I created a large map in RoadRunner and followed the instructions given in the docs.
So I end up with 48 tiles, an .xodr and the following json file:

```
{
  "maps": [
      {
        "name": "A1_Vilnius_Kaunas_Endstueck",
        "xodr": "./A1_Vilnius_Kaunas_Endstueck.xodr",
        "use_carla_materials": true,
        "tile_size": 2000,
        "tiles": [ 
        "./A1_Vilnius_Kaunas_Endstueck_Tile_0_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_0_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_0_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_0_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_0_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_0_5.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_1_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_1_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_1_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_1_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_1_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_1_5.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_2_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_2_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_2_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_2_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_2_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_2_5.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_3_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_3_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_3_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_3_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_3_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_3_5.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_4_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_4_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_4_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_4_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_4_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_4_5.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_5_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_5_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_5_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_5_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_5_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_5_5.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_6_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_6_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_6_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_6_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_6_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_6_5.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_7_0.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_7_1.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_7_2.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_7_3.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_7_4.fbx",
        "./A1_Vilnius_Kaunas_Endstueck_Tile_7_5.fbx"
        ]
      }
  ],
  "props": []
}
```
I run _make import ARGS="--package=A1_Vilnius_Kaunas_Endstueck"_ and the process finishes without error.
The map is available in the content folder. It is empty and the map origin z value is about -27000.

![image](https://user-images.githubusercontent.com/74357309/211339752-a012f9bd-f706-44e5-bedb-9263dc3831f8.png)

Hints or help would be very much appreciated.

Best, Robert

**Comment by brscholz** [comment]
@bernatx, I think you're the large map god, aren't you?

**Comment by FBanani** [comment]
> EDIT: A non-geolocated version of my map was working, so I only need to find out what's wrong with the geolocation.
> 
> Hi everyone,
> 
> I created a large map in RoadRunner and followed the instructions given in the docs. So I end up with 48 tiles, an .xodr and the following json file:
> 
> ```
> {
>   "maps": [
>       {
>         "name": "A1_Vilnius_Kaunas_Endstueck",
>         "xodr": "./A1_Vilnius_Kaunas_Endstueck.xodr",
>         "use_carla_materials": true,
>         "tile_size": 2000,
>         "tiles": [ 
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_0_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_0_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_0_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_0_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_0_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_0_5.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_1_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_1_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_1_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_1_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_1_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_1_5.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_2_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_2_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_2_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_2_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_2_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_2_5.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_3_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_3_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_3_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_3_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_3_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_3_5.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_4_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_4_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_4_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_4_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_4_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_4_5.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_5_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_5_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_5_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_5_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_5_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_5_5.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_6_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_6_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_6_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_6_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_6_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_6_5.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_7_0.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_7_1.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_7_2.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_7_3.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_7_4.fbx",
>         "./A1_Vilnius_Kaunas_Endstueck_Tile_7_5.fbx"
>         ]
>       }
>   ],
>   "props": []
> }
> ```
> 
> I run _make import ARGS="--package=A1_Vilnius_Kaunas_Endstueck"_ and the process finishes without error. The map is available in the content folder. It is empty and the map origin z value is about -27000.
> 
> ![image](https://user-images.githubusercontent.com/74357309/211339752-a012f9bd-f706-44e5-bedb-9263dc3831f8.png)
> 
> Hints or help would be very much appreciated.
> 
> Best, Robert

Hi
Did you solve it?
I have this issue. Could you help me?
