### ISSUE TITLE
Default `gamma` value for the RGB/DVS camera has changed in version 0.9.14

### ISSUE THREAD

**Issue by vbrebion** [carla-simulator/carla#6103]
Hi!

Following the release of the 0.9.14 version of CARLA, I have noted that the default `gamma` setting for the RGB (and DVS) camera has changed, from a value of `2.2` to a value of `2.4`.

I don't know if this change was intended, as the documentation (<https://carla.readthedocs.io/en/0.9.14/ref_sensors/#rgb-camera>) still indicates that the default value is `2.2`. Furthermore, this value of `2.4` results in highly noisy DVS data at night, while `2.2` appears more realistic (see below).

Would it be possible for you to take a look at this issue?

Best,
Vincent

---

**CARLA versions:**
0.9.13 / 0.9.14

**Platform/OS:**
Ubuntu 22.04

**Problem you have experienced:**
As described above, the default `gamma` value seems to have changed.\
This change is especially visible with the DVS camera for a night scene:
- in version 0.9.13:
  ![rgb00000](https://user-images.githubusercontent.com/61004974/211835739-3d55a8d5-4fad-4a29-a069-bfbd29caef8f.png)\
  ![evts00000](https://user-images.githubusercontent.com/61004974/211835544-5c15ceb4-68c5-43fb-8a83-090d596114e2.png)

- in version 0.9.14 with the default settings:
  ![rgb00004](https://user-images.githubusercontent.com/61004974/211836097-b6d66211-59b6-4dff-915f-2e1d45e6e9db.png)\
  ![evts00004](https://user-images.githubusercontent.com/61004974/211836031-64ee933e-f72f-487c-b189-4b839d6b2f67.png)

- in version 0.9.14 after setting `gamma` to `2.2`:
  ![rgb00004](https://user-images.githubusercontent.com/61004974/211836990-69ef131f-584a-4e36-b520-8cfa3375fbfd.png)\
  ![evts00004](https://user-images.githubusercontent.com/61004974/211836869-854341dc-51ce-4c88-925f-6794fa98fc59.png)

**Steps to reproduce:**
- Load the `sensor.camera.rgb` or the `sensor.camera.dvs` blueprint with default values
- Print its `gamma` attribute (should output `2.2` in version 0.9.13, `2.4` in version 0.9.14)

**Other information (documentation you consulted, workarounds you tried):**
/

**Comment by Madecu** [comment]
Hi @vbrebion,

I'll check that out and see what happened with the gamma value.

Thanks for your report

**Comment by Madecu** [comment]
Hi @vbrebion,

We have restored the default value to 2.2. This has been merge in dev and it will be in the next build.

Thank your for reporting the issue.
