### ISSUE TITLE
Carla 0.9.14 Windows Build error trying to use examples

### ISSUE THREAD

**Issue by mamaduke21** [carla-simulator/carla#6116]
Hi

I'm having a problem running generate_traffic.py. I follow every step of the Windows build and when i try to run an example always return an error. 
I notice that the API version is 0.9.12 but i don't know how to update to 0.9.14. Can someone help me please?

![Sem título](https://user-images.githubusercontent.com/76569758/212397009-16f226eb-bd28-4876-bed6-4efeedeb8617.png)

**Comment by bernatx** [comment]
Hi, probably you have more than one file .egg into this folder:
`carla/PythonAPI/carla/dist/`
Check that you have only the .egg file for the 0.9.14 version

Another option is that you installed the .egg file. Then you need to uninstall that and install the new one.

**Comment by mamaduke21** [comment]
Hi! 
Thank you for the help. 
Indeed there was more than one file .egg on that folder and it was causing the problem.
