### ISSUE TITLE
Camera maximum FoV

### ISSUE THREAD

**Issue by SpakMiguel** [carla-simulator/carla#612]
I am currently working in order to bring fish eye lens effects into CARLA. 

The idea would be not only to apply distortion to the images, but to simulate the whole behaviour of that kind of lens. That includes a big field of view.

I have been doing some research and it looks like Unreal does not support that kind of lenses for the cameras and only allows a maximum field of view of 170º in perspective projection.

Also have taken some sample pictures from CARLA with different fields of view ranging from 90º to 240º. All images look very similar after 170º but no error occurs during code execution. If I force a FoV above 170º, CARLA will automatically set it to 170º?

Is there a way to increase that maximum FoV or should I work directly in Unreal at low level?

I have seen in planner.py a method of the Converter class called convert_to_pixel. What does it do exactly? 

Thanks!

**Comment by marcgpuig** [comment]
Hi @SpakMiguel 
You cannot set a FOV bigger than 180º. This is a limitation of the render itself. I will investigate the same topic to implement it in CARLA by the next year.
If you have some progress share it with the community!

Cheers!
