### ISSUE TITLE
UE$.26.2 Carla, doesn't build on Ubuntu 20.04 with AMD 7900 xt graphics drivers installed

### ISSUE THREAD

**Issue by shott92** [carla-simulator/carla#6123]
CARLA version:
Platform/OS: Ubuntu 20.04.5 (Focal Fossa)
Problem you have experienced: running Setup.sh, GenerateProjectFiles.sh and make appears successful however UE4 doesn't launch
What you expected to happen: Expect UE4 to launch Successfully
Steps to reproduce: Clean installation of Ubuntu 20.04.05, install amdgpu-install, clone carla UE4 git, build, generate project files, and make, then try to launch UE4editor. launch fails
Other information (documentation you consulted, workarounds you tried):

`$ inxi -Fxxx
System:
  Host: xzenner-AMD-PC Kernel: 5.15.0-58-generic x86_64 bits: 64 
  compiler: N/A Desktop: Gnome 3.36.9 wm: gnome-shell dm: GDM3 3.36.3 
  Distro: Ubuntu 20.04.5 LTS (Focal Fossa) 
Machine:
  Type: Desktop Mobo: ASRock model: X670E Steel Legend 
  serial: <superuser/root required> UEFI: American Megatrends LLC. v: 1.11 
  date: 10/21/2022 
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard 
  serial: 4023-e6-32-2b-ff charge: 55% (should be ignored) rechargeable: yes 
  status: Discharging 
CPU:
  Topology: 8-Core model: AMD Ryzen 7 7700X bits: 64 type: MT MCP 
  arch: Zen 3 rev: 2 L2 cache: 8192 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 143726 
  Speed: 2953 MHz min/max: 400/5573 MHz boost: enabled Core speeds (MHz): 
  1: 2945 2: 2954 3: 2953 4: 2948 5: 2953 6: 2949 7: 2953 8: 2952 9: 2953 
  10: 2954 11: 2952 12: 2953 13: 2954 14: 2954 15: 2890 16: 2949 
Graphics:
  Device-1: AMD vendor: Tul driver: amdgpu v: 5.18.13 bus ID: 03:00.0 
  chip ID: 1002:744c 
  Device-2: AMD driver: amdgpu v: 5.18.13 bus ID: 18:00.0 chip ID: 1002:164e 
  Display: x11 server: X.Org 1.20.13 driver: ati,fbdev 
  unloaded: modesetting,radeon,vesa compositor: gnome-shell 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: GFX1036 (gfx1036 LLVM 15.0.3 DRM 3.49 5.15.0-58-generic) 
  v: 4.6 Mesa 22.3.0-devel direct render: Yes 
Audio:
  Device-1: AMD driver: snd_hda_intel v: kernel bus ID: 03:00.1 
  chip ID: 1002:ab30 
  Device-2: AMD driver: snd_hda_intel v: kernel bus ID: 18:00.1 
  chip ID: 1002:1640 
  Device-3: AMD Family 17h HD Audio vendor: ASRock driver: snd_hda_intel 
  v: kernel bus ID: 18:00.6 chip ID: 1022:15e3 
  Sound Server: ALSA v: k5.15.0-58-generic 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASRock driver: r8169 v: kernel port: d000 bus ID: 07:00.0 
  chip ID: 10ec:8168 
  IF: enp7s0 state: down mac: a8:a1:59:ee:03:40 
  Device-2: MEDIATEK driver: mt7921e v: kernel port: d000 bus ID: 09:00.0 
  chip ID: 14c3:0616 
  IF: wlp9s0 state: up mac: ac:50:de:fe:b0:6b 
  Device-3: Realtek RTL8125 2.5GbE vendor: ASRock driver: r8169 v: kernel 
  port: c000 bus ID: 0a:00.0 chip ID: 10ec:8125 
  IF: enp10s0 state: down mac: a8:a1:59:ee:03:42 
Drives:
  Local Storage: total: 1.36 TiB used: 113.67 GiB (8.1%) 
  ID-1: /dev/nvme0n1 vendor: Samsung model: 980 PRO with Heatsink 1TB 
  size: 931.51 GiB speed: 63.2 Gb/s lanes: 4 serial: S6WSNS0RB63138E 
  rev: 5B2QGXA7 scheme: GPT 
  ID-2: /dev/sda vendor: Samsung model: SSD 850 EVO 500GB size: 465.76 GiB 
  speed: 6.0 Gb/s serial: S21JNXAGA26716B rev: 2B6Q scheme: MBR 
Partition:
  ID-1: / size: 915.32 GiB used: 113.66 GiB (12.4%) fs: ext4 
  dev: /dev/nvme0n1p2 
Sensors:
  Message: No sensors data was found. Is sensors configured? 
Info:
  Processes: 386 Uptime: 3h 05m Memory: 61.93 GiB used: 4.98 GiB (8.0%) 
  Init: systemd v: 245 runlevel: 5 Compilers: gcc: 9.4.0 alt: 7/9 
  Shell: bash v: 5.0.17 running in: gnome-terminal inxi: 3.0.38 `

[Diagnostics.txt](https://github.com/carla-simulator/carla/files/10436426/Diagnostics.txt)
[UE4.log](https://github.com/carla-simulator/carla/files/10436427/UE4.log)

**Comment by Blyron** [comment]
Please if this UE4 Related refer to Epic Games repo please
