### ISSUE TITLE
Why I obtain different bounding boxes using different APIs?

### ISSUE THREAD

**Issue by lsangreg** [carla-simulator/carla#6134]
Hello, I am experiencing an issue with bounding boxes and traffic light.
I obtain correct bounding boxes around traffic light when I compute them as 
```
bounding_box_set = self.world.get_level_bbs(carla.CityObjectLabel.TrafficLight)
[...]
 verts = [v for v in bb.get_world_vertices(carla.Transform()) 
 ```
 While if I obtain bounding boxes as 
 ```
  traffic_light_list= actor_list.filter('traffic.traffic_light*')
  for tl in traffic_light_list:
      bb = tl.bounding_box
     verts = [v for v in bb.get_world_vertices(tl.get_transform())]
```
they are wrong and different. I need the second method because I want to retrieve also the state of the traffic light.

**Comment by xswings** [comment]
Hello, I found It sames that the bounding_box are the same of corresponding trigger_volume. I don't know if it's as expected or a bug. Btw, do you know how to get the actor id of  bounding box obtained from get_level_bbs() function?
