### ISSUE TITLE
RuntimeError: get_light_boxes does not find the traffic lights - but they exist -

### ISSUE THREAD

**Issue by lsangreg** [carla-simulator/carla#6147]
CARLA version: 0.9.12
Platform/OS: ubuntu 20
Problem you have experienced: Responding error from function get_light_boxes: Actor could not be found in the registry.  Actor Id: 94

What you expected to happen: Obtaining bounding box list from get_light_boxes
Steps to reproduce:
```
 
    actor_list = world.get_actors()
    for actor in actor_list:
        if isinstance(actor, carla.TrafficLight):   
            try:
                light_box=actor.get_light_boxes()
                print(light_box)
            except RuntimeError as e:
                   print(e)
```
#4553 This issue is related and did not receive a proper answer

**Comment by glopezdiest** [comment]
Hey, what town are you using? I just did a quick test in Town10 and everything works fine for me

**Comment by lsangreg** [comment]
> Hey, what town are you using? I just did a quick test in Town10 and everything works fine for me. Also, have you tried with newer versions of CARLA?

I tried with older town, like town05.. maybe this is the problem
