### ISSUE TITLE
Compilation error on Ubuntu 17.10: Undeclared identifier 'labs'

### ISSUE THREAD

**Issue by mikebentley15** [carla-simulator/carla#615]
I am compiling Carla on Ubuntu 17.10.  I have followed the instructions from [readthedocs](http://carla.readthedocs.io/en/latest/how_to_build_on_linux/).  I ran into the problem with `xlocale.h`, but solved that with a symbolic link.  After that, I get the following error when compiling LLVM:

```
common.mkdir stage
common.mkdir bin.v2/libs
common.mkdir stage/lib
common.mkdir bin.v2/libs/system
common.mkdir bin.v2/libs/system/build
common.mkdir bin.v2/libs/system/build/clang-linux-3.9
common.mkdir bin.v2/libs/system/build/clang-linux-3.9/release
common.mkdir bin.v2/libs/system/build/clang-linux-3.9/release/threading-multi
common.mkdir bin.v2/libs/system/build/clang-linux-3.9/release/link-static
common.mkdir bin.v2/libs/system/build/clang-linux-3.9/release/link-static/threading-multi
clang-linux.compile.c++.without-pth bin.v2/libs/system/build/clang-linux-3.9/release/threading-multi/error_code.o
In file included from libs/system/src/error_code.cpp:16:
In file included from ./boost/system/error_code.hpp:14:
In file included from ./boost/system/config.hpp:13:
In file included from ./boost/config.hpp:57:
In file included from ./boost/config/platform/linux.hpp:15:
In file included from ../llvm-install/include/c++/v1/cstdlib:86:
../llvm-install/include/c++/v1/stdlib.h:115:82: error: use of undeclared identifier 'labs'; did you mean 'abs'?
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
...
```

I looked in the `stdlib.h` file that it talks about, and sure enough, `labs()` is used but never declared in the LLVM source code present.  But, it does have `#include_next <stdlib.h>` at the top.  Assuming that should then include `/usr/include/stdlib.h`, then we should be fine.  How can I check to see if that is the other `stdlib.h` that is included rather than some other one?  Has anyone seen this error before?

I get this problem both compiling Carla on the current master branch and on the 0.8.4 tag.

**Comment by overlapjho** [comment]
I also experience this problem in Ubuntu 18, how to fix this issue?
