### ISSUE TITLE
Town11 and Town12 cannot load

### ISSUE THREAD

**Issue by Miknow78** [carla-simulator/carla#6173]
I'm using the new realease 0.9.14 on ubuntu.
Everything works fine except the 2 new worlds: Town11 and Town12. 
It just loads the sky and I already tried to spawn a hero vehicle but the map still doesn't load. What do I do?
![image_2023-02-02_114129215](https://user-images.githubusercontent.com/47362393/216315513-26cd02e5-3621-4e71-804f-48082ac387d4.png)

**Comment by DnDare** [comment]
Hi, Town11 and Town12 are big maps, they are divided in sublevels that are loaded according the camera's or vehicle's  position.

try to hit play and execute a Manual_control.py 

If you want to find each sublevel
![image](https://user-images.githubusercontent.com/57799121/216372203-62c19e10-9a32-41bd-8872-c611e6c44a4f.png)

**Comment by SExpert12** [comment]
Hi, my system configuration are:
12 GB GPU
Ubuntu 20.04 (focal)
Carla 0.9.14
I have included assets of Town11 and Town12.  Now every time I load map of Town11 and Town12 I get this and it got stuck.

How to access these towns?
I want to check intersection area in town11 and town12.
![Screenshot from 2023-06-05 11-49-07](https://github.com/carla-simulator/carla/assets/113903215/06b7bdd7-6cc8-445e-8de0-198dce1a2b7f)

**Comment by Alphacool123** [comment]
> Hi, my system configuration are: 12 GB GPU Ubuntu 20.04 (focal) Carla 0.9.14 I have included assets of Town11 and Town12. Now every time I load map of Town11 and Town12 I get this and it got stuck.
> 
> How to access these towns? I want to check intersection area in town11 and town12. ![Screenshot from 2023-06-05 11-49-07](https://user-images.githubusercontent.com/113903215/243267944-06b7bdd7-6cc8-445e-8de0-198dce1a2b7f.png)

I met the same question, do you fix it?

**Comment by viola521** [comment]
how could fix it ? I meet  the same problem.

**Comment by viola521** [comment]
> Manual_control.py

how could I open the configuration tool?

**Comment by SExpert12** [comment]
I am getting your question? Can you please explain what you want to do?

**Comment by Smarome** [comment]
> I'm using the new realease 0.9.14 on ubuntu. Everything works fine except the 2 new worlds: Town11 and Town12. It just loads the sky and I already tried to spawn a hero vehicle but the map still doesn't load. What do I do? ![image_2023-02-02_114129215](https://user-images.githubusercontent.com/47362393/216315513-26cd02e5-3621-4e71-804f-48082ac387d4.png)

Have you solved the problem? I can't open the map with 3090

**Comment by SExpert12** [comment]
No. It's not getting loaded.

**Comment by WenYanger** [comment]
The problems is due to the large size of Town11 and Town12 map.

The solution is to spawn an actor with role_name 'hero', then Carla will load the map tile around the actor.

For example,
      bp=random.choice(world.get_blueprint_library().filter('*vehicle*'))
      bp.set_attribute('role_name', 'hero')
      spawn_point = random.choice(world.get_map().get_spawn_points())
      ego = world.try_spawn_actor(bp, spawn_point)

**Comment by SExpert12** [comment]
Okay. Thanks.

**Comment by Blyron** [comment]
Is okay to get stucked for a while. The map needs to load heavily. 
Are you okay with this answer?

**Comment by TomoCoder123** [comment]
Hello, I am on 9.15, and when I try spawning in a hero vehicle, it just spawns me under the map
I used this script.
`client = carla.Client('localhost', 2000)
client.set_timeout(60.0)  
world = client.load_world('Town12')

bp=random.choice(world.get_blueprint_library().filter('vehicle'))
bp.set_attribute('role_name', 'hero')
spawn_point = random.choice(world.get_map().get_spawn_points())
ego = world.try_spawn_actor(bp, spawn_point)`

**Comment by Kin-Zhang** [comment]
> RuntimeError: Map 'Town12' not found

For this error, maybe we need first import the Additional Assets, I saw there are some docs is for Town12 etc. For import additional maps: https://carla.readthedocs.io/en/latest/core_map/#additional-maps
