### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by MubeenAfzal343** [carla-simulator/carla#6181]
can anyone tell me how to solve it
git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git ~/UnrealEngine_4.26
Cloning into '/home/dlinano/UnrealEngine_4.26'...
Username for 'https://github.com': MubeenAfzal343
Password for 'https://MubeenAfzal343@github.com': 
remote: Enumerating objects: 111593, done.
remote: Counting objects: 100% (111593/111593), done.
remote: Compressing objects: 100% (85031/85031), done.
remote: Total 111593 (delta 23477), reused 111478 (delta 23460), pack-reused 0
Receiving objects: 100% (111593/111593), 240.00 MiB | 1.91 MiB/s, done.
Resolving deltas: 100% (23477/23477), done.
error: unable to write file Engine/Plugins/Importers/USDImporter/Source/ThirdParty/USD/include/boost/typeof/vector200.hpp
error: unable to write file Engine/Plugins/Importers/USDImporter/Source/ThirdParty/USD/include/boost/typeof/vector50.hpp
fatal: cannot create directory at 'Engine/Plugins/Importers/USDImporter/Source/ThirdParty/USD/include/boost/unordered': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by wx983** [comment]
Obviously, you don't have enough disk space in your computer....
