### ISSUE TITLE
Scenario runner version for carla 0.9.14

### ISSUE THREAD

**Issue by Tejas-Deo** [carla-simulator/carla#6188]
No scenario runner version is specified for Carla 0.9.14.

In the documentation, it is explicitly mentioned that the scenario runner version and the Carla version should match. But there is no runner of version 0.9.14!

Which scenario runner version should be used for Carla 0.9.14?

**Comment by glopezdiest** [comment]
Hey, we didn't release SR 0.9.14 yet, but you can use either the `0.9.13` tag or `master`, and both will work just fine
