### ISSUE TITLE
Image's Reality.

### ISSUE THREAD

**Issue by crazyzxd** [carla-simulator/carla#619]
Hi ,thanks a lot for the community. Your previous help me a lot,now i had already get enough data from the carla to train my model ,but unfortunately the rgb image procuced by the carla similator is not as real as real world .I find the SYNTHIA Dataset is much more real than carla,i ve'been told that the SYNTHIA is also using UE4 engine,how can it get image that real.Or is there any parameter i can change to control the image noise of the carla  similator ,or anything that can make  carla Produce more real pictures.

**Comment by germanros1987** [comment]
Hi, @crazyzxd thanks for your feedback. Let me comment on this. SYNTHIA is not more realistic than CARLA, on the contrary. SYNTHIA was done with Unity and the rendering is not PBR. The good thing about SYNTHIA for perception is the variability that we built in. It has a lot of different scenes with many different assets, weather conditions, etc. That is what makes SYNTHIA good, not the image quality.

We are currently working to get the same in CARLA. I hope this helps.

**Comment by crazyzxd** [comment]
Hi @germanros1987 thanks a lot for your comment.
Actually I was train a model .When the model trained by SYNTHIA dataset (around 2000 pictures ,just the SYTHIA-SF dataset,only consisit sunny day) transfer to the kitti(a real picture dataset ) ,it works well. while the model trained by carla(around 30000 ,also ,only in sunny day) ,can work extremely well on its test datast (also produced by carla),but transfer to kitti ,the result is frustrating.
 I understand what you say,  and i agree with you, the carla PBR rendering is supposed to be better than SYNTHIA, the failure reason for my carla model is the variability of the carla city environment.
 But I also find another thing,the assets in SYNTHIA ,like the road is more rough,is more real than carla, i think its because the texture of SYNTHIA is carefully designed.

 So I think its nothing about the rendering engine, its about the textures of assets and the variability of assets.
Maybe i can buy a environment, i find [this](http://www.polypixel3d.com/downtown-3d-city-environment-models/).
Can i run carla on this? If i want to  use carla autopilot ,do I need to add some intersection route planner to the new map ?Or anything else?
