### ISSUE TITLE
CARLA running at 2-3 FPS in Nvidia Tesla T4 GPU

### ISSUE THREAD

**Issue by asa7007** [carla-simulator/carla#6204]
Actually my system is having NVIDIA Tesla T4 GPU, with all updated drivers. still CARLA is running only at 2- FPS
Thanks for contributing to CARLA!

If you are reporting an issue, please use the following outline:

CARLA version: 0.9.13
Platform/OS: Windows 10
Problem you have experienced: Unable to increase CARLA fps
What you expected to happen: increase fps to 30 at least
Steps to reproduce:
Other information (documentation you consulted, workarounds you tried):

**Comment by 6NeverGiveup** [comment]
你应该是没有配置好同步或异步模式，尝试在运行时添加 --sync 参数？

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

Are you running CARLA in the UE editor?

Marcel
