### ISSUE TITLE
Semantic Segmentation Network

### ISSUE THREAD

**Issue by mhusseinsh** [carla-simulator/carla#621]
Hello,

![image](https://user-images.githubusercontent.com/33177438/43061625-3ba82b7c-8e56-11e8-98b6-7080566c3e64.png)

You mentioned here on your paper that you trained a semantic segmentation network on dataset from CARLA. Is there by any chance a possibility that you can have this network published, or an open-source code ?

I want also to train a semantic segmentation network on CARLA dataset, and I didn't find a good one to start with that I can adapt on CARLA. I mean I found ones for cityscape but it is difficult to get it adapted on CARLA.

**Comment by felipecode** [comment]
It is not yet published. Unfortunately.
But some people have been able to adapt semantic segmentation networks successfully
before like the ErfNet.
Check this paper:
https://arxiv.org/abs/1804.09364

**Comment by mhusseinsh** [comment]
@felipecode Thanks a lot
If there will be any update with a Semantic Segmentation network published by your side, then this will be really great
