### ISSUE TITLE
Availibility of 4D Imaging Radar sensor?

### ISSUE THREAD

**Issue by kvnptl** [carla-simulator/carla#6212]
Hello,

Is there support for a 4D Radar sensor in the CARLA simulator? There are few datasets available with real 4D Radar sensors; I would like to explore the simulation of the 4D radar sensor. Please let me know if it's available or if there are any plans for this sensor.  

Reference: [What is 4D Imaging Radar](https://www.aptiv.com/en/insights/article/what-is-4d-imaging-radar)

Thanks,
Kevin

**Comment by PabloVD** [comment]
We do not support this kind of sensor currently.
