### ISSUE TITLE
Bug Report: Behavior agent makes collision with a wall

### ISSUE THREAD

**Issue by Kim-mins** [carla-simulator/carla#6219]
## Environment
**CARLA version**: `nightly (installed on 2023.02.14)`
**Platform/OS**: `ubuntu 18.04`
**Problem Statement**:
I wrote my own code for the simulation, and the car collides when I simply ran the simulation with `BehaviorAgent` with the following configurations. I expected the ego vehicle to steer to the right slightly for the avoidance, but it didn't.

## Configuration
**Starting point**: 
`Transform(Location(x=239.623291, y=92.175323, z=0.573433), Rotation(pitch=0.000000, yaw=-88.605339, roll=0.000000))`
**Destination**:`Transform(Location(x=234.623291, y=-57.824677, z=0.573433), Rotation(pitch=0.000000, yaw=-88.605339, roll=0.000000))`
**Ego vehicle asset**: `vehicle.mercedes.coupe`

## Video

https://user-images.githubusercontent.com/50267797/218995267-2e639482-5202-4713-ac00-2dd4260d848d.mp4

**Comment by cdefg** [comment]
How do you generate the blingbling Xs in the simulator? They are so cool. Do you develop with Unreal Editor or is it a internal api from carla?

**Comment by Kim-mins** [comment]
@cdefg They are arrows in 3D. You may enable those by switching `debug` option of the function `run_step` as `True`. In my case,
```python
...
agent = BehaviorAgent(..., behavior='aggressive')
control = self.__agent.run_step(debug=True)
```

**Comment by glopezdiest** [comment]
This is really more of a map design issue rather than a behavior agent one. As for why the behavior agent doesn't detect this, agents are designed to only look for vehicle / pedestrians as possible obstacles, so any otehr assets (such as props in the middle of the road) will be ignored.

**Comment by Kim-mins** [comment]
@glopezdiest Thank you for the comment! Then I wonder if I should not report any of the collision between behavior agent and vehicles or pedestrians.
