### ISSUE TITLE
IMU Data

### ISSUE THREAD

**Issue by sameernegi17** [carla-simulator/carla#623]
hello,
I am sameer. 
I have few question to ask.
- I want IMU and GPS data from carla. So that i can try my algorithim to fuse data to generate a path for car.
- Then I want to integrate my fusion code to Carla
I want to know How to get IMU and GPS data from carla simulator and where to integrate my fusion Code.

It will much appreciated if you can help. Thanks

**Comment by marcgpuig** [comment]
Hi @sameernegi17.

Please, take a look at the documentation about [measurements](https://carla.readthedocs.io/en/latest/measurements/). Also I recommend you to play arround with the python clients like [client_example.py](https://github.com/carla-simulator/carla/blob/master/PythonClient/client_example.py), it is well documented and will help you to undesrtando how to get the measurements.
