### ISSUE TITLE
Is it possible to export a custom vehicle from CARLA?

### ISSUE THREAD

**Issue by mathiaswold** [carla-simulator/carla#6231]
Hi! 

I have created, imported and set up a custom vehicle in Unreal Engine using the [vehicle content authoring guide](https://carla.readthedocs.io/en/latest/tuto_content_authoring_vehicles/) on Ubuntu 20.04. 

All the relevant files lives in a directory `Kia` in the content folder (next to the `Carla` folder), as seen here:
![SCR-20230221-h14](https://user-images.githubusercontent.com/45951843/220333168-982c65af-e0e4-4103-b3ce-ee67c2b549aa.png)

This is the content of the `Kia`-directory:
![SCR-20230221-h1q](https://user-images.githubusercontent.com/45951843/220333211-196d18cc-0ce1-4981-a918-cea846f5fc44.png)

And it works to spawn it with autopilot in the simulator (don't mind the missing textures):
![SCR-20230221-h4h](https://user-images.githubusercontent.com/45951843/220333635-7d2c229b-24eb-4535-b098-69426d28c7cd.jpeg)

Is it possible to create and export a standalone package of this vehicle, so that it can be shared and imported into CARLA later on other computers? I tired `make package ARGS="--packages=Kia"` as described [in the docs](https://carla.readthedocs.io/en/latest/tuto_A_create_standalone/#export-a-package-from-the-ue4-editor), but it errors.

I think the relevant error message is `Error: Package json file not found.`, but I don't see any documentation on how to create this json and where to store it?

[full-make-package-log.txt](https://github.com/carla-simulator/carla/files/10793024/make-package-log.txt)

Thank you for any answers! :)

**Comment by burnout2k** [comment]
I have the same problem...
Everything works great in Unreal Editor but how do I export it for a prebuilt version?

**Comment by sunup494-pixel** [comment]
I also want to ask this question.
