### ISSUE TITLE
connect from laptop to server

### ISSUE THREAD

**Issue by DanqingZ** [carla-simulator/carla#624]
Hi 
I started Carla on my server
`~/CarlaUE4/Binaries/Linux$ ./CarlaUE4 /Game/Maps/Town01 -carla-server`
I have done ssh tunnel forwarding
`ssh -N -f -L localhost:3000:localhost:2000 username@servername`
And I have on my laptop
`./manual_control.py --port 3000`

However, there is always a connection refused error. Could someone help me with it? Thank you!

**Comment by micmarty** [comment]
@DanqingZ 
AFAIK you need to open multiple ports and use Remote Port Forwarding not Local Port Forwarding!

Your remote host may block such traffic (check tutorials and articles related to `GatewayPorts yes` in `/etc/ssh/sshd_config` or see [unix.stackexchange](https://unix.stackexchange.com/questions/115897/whats-ssh-port-forwarding-and-whats-the-difference-between-ssh-local-and-remot)

It worked for me:

```bash
# Tested on stable branch - 0.8.2
ssh -R 2000:localhost:2000 -R 2001:localhost:2001 -R 2002:localhost:2002 <my_remote_host>

# Logged in to remote machine
cd carla
git checkout stable 
cd PythonClient
python client_example.py --autopilot
```
BTW I got terrible performance (GTX 660 - server-side, GTX 1060 with i7 client-side).
I don't know if gRPC solved this problem, but it's not related to this issue.
#### Let me know if it works for you!

**Comment by karthi0804** [comment]
Hi,
I get an error when using carla 0.9.4. Please let me know how to fix it.
```
Failed to find symbol file, expected location:
"/home/karthik/Documents/Software/carla/CarlaUE4/Binaries/Linux/CarlaUE4.sym"
Fatal error: [File:/var/lib/jenkins/workspace/carla-simulator_carla_0.9.4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.cpp] [Line: 102] 
Exception thrown: bind: Address already in use
[2019.04.03-03.36.53:412][  0]LogCore: Error: appError called: Assertion failed:  [File:/var/lib/jenkins/workspace/carla-simulator_carla_0.9.4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.cpp] [Line: 102] 
Exception thrown: bind: Address already in use
```
