### ISSUE TITLE
Converter Node/Pixel mixup

### ISSUE THREAD

**Issue by rowanmcallister** [carla-simulator/carla#627]
https://github.com/carla-simulator/carla/blob/860dbe908e7a81232bdba6853943707f6b0102c2/PythonClient/carla/planner/converter.py#L148-L149

The above lines output an int list. It should be a float list. For example, this causes the following error:

`converter._check_input_type(map.convert_to_pixel([10.,10.,10.])) == NODE`  # returns `True`, but should return `False`

Possibly due to a python2/python3 mixup where `math.floor` returns float/int respectively

**Comment by felipecode** [comment]
Very good ! I will try to update that now. 
Thanks.
