### ISSUE TITLE
No spawn_npc.py file 

### ISSUE THREAD

**Issue by zillur-av** [carla-simulator/carla#6282]
CARLA version: 0.9.13
Platform/OS: Ubuntu 20
Problem you have experienced: In [ros_bridge](https://carla.readthedocs.io/projects/ros-bridge/en/latest/carla_ad_demo/), it says to spawn vehicles or pedestrian, we can use `python3 spawn_npc.py` inside `./PythonAPI/example/ `directory. But there is no such python script on `master` branch.

**Comment by hfr2015** [comment]
It seems that spawn_npc is replaced by generate_traffic.
see issue #4965(closed) for more details.
