### ISSUE TITLE
attach props to walkers

### ISSUE THREAD

**Issue by LuisGF93** [carla-simulator/carla#6295]
CARLA version: 0.9.13
Platform/OS: ubuntu 18.04

Hi, is there any option to attach some props from blueprint_library to some of the spawned pedestrians? I'd like to spawn some of them with a briefcase, some shoppingbags, helmets or things like that, but I'm not sure If I can do that with a normal attach like a sensor attached to a car or similar stuff. 

Thanks in advance.

**Comment by Blyron** [comment]
In latest dev version of carla you have the option to attach anything to anything with a bone;


https://github.com/carla-simulator/carla/blob/dev/PythonAPI/carla/source/libcarla/World.cpp#L330
