### ISSUE TITLE
Broken images from camera sensors

### ISSUE THREAD

**Issue by JonasDoubleU** [carla-simulator/carla#6315]
CARLA version: 0.9.14
Platform/OS: Windows 10
GPU: GTX 1070

When running the tutorial.py file that came with CARLA, the images being saved look like this:

![00077519](https://user-images.githubusercontent.com/92020817/225288171-ab3b90f5-d2b1-422b-b046-813af44eb2ae.png)

They also look like that when I try using the RGB sensor in my own code like this
`camera_RGB_bp = blueprint_library.find("sensor.camera.rgb")
camera_transform = carla.Transform(carla.Location(x=1.5, z=2.4))
camera = world.spawn_actor(camera_RGB_bp, camera_transform, attach_to=vehicle, attachment_type=carla.AttachmentType.Rigid)
camera.listen(lambda image: image.save_to_disk('_out/%06d.png' % image.frame, carla.ColorConverter.CityScapesPalette))`

However, when I run the file manual_control.py, that also came with CARLA, and I use the record function, the saved images look like they should, i.e.:

![00050299](https://user-images.githubusercontent.com/92020817/225289779-8fa7fc98-15c3-4edc-b0f2-7a3003f7e6c5.png)

What can I do to solve this?

**Comment by mawi42** [comment]
see https://github.com/carla-simulator/carla/issues/6225

**Comment by TzabarDolev** [comment]
I wrote a short blog post about this issue on the Carla simulator research blog - https://carlasimblog.wordpress.com/2023/09/16/the-64-division-curse/. And added a short code snippet to fix this.
