### ISSUE TITLE
How to modify the vehicle in the environment？

### ISSUE THREAD

**Issue by cuiyonghao** [carla-simulator/carla#632]
Thanks for Carla team hard work.
I want to training a vehicle following the front vehicle in the environment based on Carla.

So I want to konw how to generate the front vehicle :
1.How to modify the randomly generated vehicle's begining and ending point in the environment.
2.How to modify the front vehicle's dynamic parameter.

**Comment by marcgpuig** [comment]
Hi @cuiyonghao 
This will be possible in the next CARLA release!
