### ISSUE TITLE
Empty level can't apply carla plugin

### ISSUE THREAD

**Issue by yangzuyuanhao** [carla-simulator/carla#635]
Hi all, I got a problem when creating a new map. 
When I directly create a new empty level(not duplicate from demo) under the same folder, carla can't plug into it. Anybody knows what setting changes required? Thanks!

**Comment by nsubiron** [comment]
Hi @yangzuyuanhao, could you be more specific on what steps you followed and what sort of errors are you getting?

**Comment by yangzuyuanhao** [comment]
@nsubiron Hi, I created a new level in the Carla demo project, but when I click play, the ego car and Carla parameters won't show up on editor, and client couldn't receive anything from server.
Attachment 1 is the Carla demo, and 2 is my new level. 
![carlademo](https://user-images.githubusercontent.com/36458664/43358141-21a9ca1a-925b-11e8-9b7b-8d7ccd890622.png)
![newlevel](https://user-images.githubusercontent.com/36458664/43358142-21b8349c-925b-11e8-9638-0e2d9df7e715.png)

**Comment by nsubiron** [comment]
Check out the output log to see if any errors appear. Have you put _player starts_ in your map? those are necessary to spawn vehicles.

**Comment by yangzuyuanhao** [comment]
@nsubiron  I found the route reason is that my new level missed CarlaMapGenerator. 
So, must I use carlamapgenerator to create road?
But I want to create my own map, not randomly generated by map generator.

**Comment by yangzuyuanhao** [comment]
It seems to be another issue? I submitted it in #636
