### ISSUE TITLE
how to replay with spectator on?

### ISSUE THREAD

**Issue by AOOOOOA** [carla-simulator/carla#6356]
CARLA version: 0.9.13
Platform/OS: ubuntu 20

Problem you have experienced:
Hi, when I use the carla recorder function, I found out that when I run the client.replay_file() function the server won't change to a spectator view like shown in the Carla recorder tutorial. 
This is what I got while running replay_file:
![image](https://user-images.githubusercontent.com/38175747/228536036-f3aba3ae-200f-40fa-9d11-fd6ca457226f.png)

This is what shown in tutorial:
![image](https://user-images.githubusercontent.com/38175747/228536243-db4cc255-0536-4927-adb6-f84a91340510.png)

My question is how to gain the view shown in tutorial? Could you please help me with that? Since I want to extract the log data of ego vehicle and check what happened during the simulation.  @germanros1987 @bernatx @Axel1092 Thanks so much!

**Comment by bernatx** [comment]
Hi,

You need to know the id of the **hero** vehicle, so the spectator camera can follow that actor. 
In the tutorial it was the 173 parameter.
To know that, you can use the script **PythonAPI\examples\show_recorder_file_info.py** that will show all the actors with its id's. Find the one who has the **hero** role and use that id.
I hope it works fine.

Regards

**Comment by ChaoTan201** [comment]
> Hi,
> 
> You need to know the id of the **hero** vehicle, so the spectator camera can follow that actor. In the tutorial it was the 173 parameter. To know that, you can use the script **PythonAPI\examples\show_recorder_file_info.py** that will show all the actors with its id's. Find the one who has the **hero** role and use that id. I hope it works fine.
> 
> Regards

Hello, 

> Hi,
> 
> You need to know the id of the **hero** vehicle, so the spectator camera can follow that actor. In the tutorial it was the 173 parameter. To know that, you can use the script **PythonAPI\examples\show_recorder_file_info.py** that will show all the actors with its id's. Find the one who has the **hero** role and use that id. I hope it works fine.
> 
> Regards

Hi， 
I encountered the same problem. Would you have any good suggestions? I have tried this solution, but the ID of Hero cannot be found.  as shown in following diagram:
![1713446600(1)](https://github.com/carla-simulator/carla/assets/71108879/1f0deba2-6558-4ba7-a443-93bac15e681b)
