### ISSUE TITLE
how to enable vulkan validation layer?

### ISSUE THREAD

**Issue by gouchaoer** [carla-simulator/carla#6374]
I want to enable vulkan validation layers to debug vulkan api.
But after so much effort, I failed.
plz help me.
thanks!

**Comment by abol-karimi** [comment]
I'm having some problems with Vulkan too (on an HPC cluster). Were you able to enable the validation layers?

**Comment by Blyron** [comment]
You can use this. 
https://gcmiao.github.io/2020/04/26/UnrealEngine/DebugTips/enable_vulkan_validation/

**Comment by abol-karimi** [comment]
For anyone else having a similar problem with vulkan: The cause was that Apptainer was not mounting the Vulkan drivers into my singularity container properly. The admins updated Apptainer to 1.3, and the problem was solved.
