### ISSUE TITLE
Walker.get_bones() is slow

### ISSUE THREAD

**Issue by fezsid** [carla-simulator/carla#6388]
CARLA version: 0.9.13
Platform/OS: Ubuntu 20.04
Problem you have experienced: Walker.get_bones() takes too long to compute

Hi,
I am trying to publish  Walker.get_bones() in the world coordinate frame as a topic in carla-ros-bridge. I am able to get the correct values, but because the get_bones() function is very slow, it causes other messages to slow down, and thus my topics arrive delayed. Is there a way to reduce the message size/ computation speed of get_bones()? It is providing pose in 3 coordinate frames and I only need it with respect to the world.

**Comment by Blyron** [comment]
Now we have avilable for all actors https://github.com/carla-simulator/carla/blob/dev/PythonAPI/carla/source/libcarla/Actor.cpp

get bones functions and their transforms. Feel free to use them in latest dev branch
