### ISSUE TITLE
Saving images with manual_control.py

### ISSUE THREAD

**Issue by Nozomeister** [carla-simulator/carla#640]
Hi, I want to save the images to disk using the same feature in the client_example.py, but unluckily manual_control.py doesn't have it. Is there any way to export the images to disk when driving the car manually?
Thank you.

**Comment by marcgpuig** [comment]
Hi @Nozomeister, this is an already answered question.
You must implment it yourself (we provide all the functions you need in Carla module).
Take a look at:
#462
#560
https://github.com/carla-simulator/carla/issues/165#issuecomment-360152455
