### ISSUE TITLE
Z coordinate (height) of a point on the road surface?

### ISSUE THREAD

**Issue by leeaccy** [carla-simulator/carla#6405]
Hi everyone!

I want to get the height of a point on the road surface in Carla. Given the x and y coordinates of a certain point on the road surface, can I get the z coordinate of that point? Is there any API that can return information about the road surface?

Thanks!

**Comment by vollkornholztuer** [comment]
Question: How did you manage to do it? I'd like to have cars spawned directly at the ground level and avoid having the cars to fall down to the ground, before they can drive.
