### ISSUE TITLE
the dynamic model of the vehicle

### ISSUE THREAD

**Issue by leeaccy** [carla-simulator/carla#6407]
Hi, Everyone!

I really appreciate Carla's work. I would like to know the specifics of the dynamic model of the vehicle in Carla. Is there documentation for this?

**Comment by filipthoen2** [comment]
Take a look under the "Vehicles" section of the CARLA tutorial and the 'VehiclePhysicsControl' & 'WheelPhysicsControl' objects:

https://carla.readthedocs.io/en/0.9.4/python_api_tutorial/

Filip
