### ISSUE TITLE
Edit to the Documentation for Linux Build

### ISSUE THREAD

**Issue by kashwp7** [carla-simulator/carla#6423]
CARLA version: 0.9.14
Platform/OS: Linux Ubuntu
Problem you have experienced: the git clone command in the Linux build documentation use HTTPS which doesn't work any more
What you expected to happen: Suggest changing it to 'git clone --depth 1 -b carla git@github.com:CarlaUnreal/UnrealEngine.git ~/UnrealEngine_4.26'

**Comment by Blyron** [comment]
We have changed that recently to each user use their personal token. 
Are you happy to close this issue?
