### ISSUE TITLE
LabelledPoint

### ISSUE THREAD

**Issue by ywyeli** [carla-simulator/carla#6432]
Hello, everyone!

Can anyone tell me how to read LabelledPoint?
![aa7fe2a4df6486f4107f8df9d71be01](https://user-images.githubusercontent.com/79050502/235012201-db8732a8-33ce-4510-a51a-4e434288af49.jpg)

**Comment by amstrudy** [comment]
Check the carla API for information: [https://carla.readthedocs.io/en/latest/python_api/#carlalabelledpoint](https://carla.readthedocs.io/en/latest/python_api/#carlalabelledpoint). `LabelledPoint` has 2 member variables, `location` and `label`.
