### ISSUE TITLE
carla 0.9.11 quality-level low get white sensor data

### ISSUE THREAD

**Issue by KongouMitsuko** [carla-simulator/carla#6434]
CARLA version: 0.9.11
Platform/OS: ubuntu 18.04
Problem you have experienced: sensor sometime get whole white image data
What you expected to happen: normal data
Steps to reproduce:   ./CarlaUE4.sh -opengl -quality-level=Low
Other information (documentation you consulted, workarounds you tried):
i want to get a high fps , so i use Low quality renderer setting, but sometime my sensor get whole white image data, that 's a bad thing for me

**Comment by Blyron** [comment]
You cannot get both. One or the other. Or use a very powerful machine
