### ISSUE TITLE
Repository missing (?) Unable to clone CARLA's modified fork of Unreal Engine 4.26

### ISSUE THREAD

**Issue by masterthesishci** [carla-simulator/carla#6442]
I'm unable to clone the repository as described in the documentation "git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git".

"fatal: repository `https://github.com/CarlaUnreal/UnrealEngine.git/` not found."
The account "CarlaUnreal" doesn't have any public repositories.

Can anyone help?

Thanks

**Comment by Bo-Yu-Columbia** [comment]
Hi, were you able to solve this problem?
