### ISSUE TITLE
Detectors (e.g. collision_sensor) does not work properly during replay

### ISSUE THREAD

**Issue by Morphlng** [carla-simulator/carla#6444]
- CARLA version: 0.9.13

- Platform/OS: Windows/Ubuntu

- Problem you have experienced: 
   I'm trying to collect data for RL training from a list of replay files. I'm setting the world to synchronous mode once the replay is fully loaded. I'll retrieve the sensors to collect the data for RL algorithm, such as RGB image and semantic information. The problem right now is that the Collision Sensor and LaneInvasion Sensor does not call the callback function at the point where the event happened. Actually, it seems to me that these two camera doesn't call the callback at all during the replay stage. The RGB sensor on the other hand, is doing just fine.

- What you expected to happen:
   The sensor should call the callback function at once when a corresponding event happens.

- Steps to reproduce:
   Below code is how I retrieve the actors and register callbacks, you'll need a record file to replay though:

```python
def parse_replay_file(client, record_file):

	# Get raw string info
	info = client.show_recorder_file_info(record_file, True)
	clean_text = []
	for line in info.splitlines():
		clean_text.append(line.strip())

	# Parse actor information
	actor_raw_info = [line.strip() for line in info.splitlines()]
	total_duration = float(actor_raw_info[-1].split(' ')[1].strip())
	vehicle_pattern = r'Create (\d+): vehicle\.([\w.]+) \(\d+\) at \((\-?\d+(?:\.\d+)?), (\-?\d+(?:\.\d+)?), (\-?\d+(?:\.\d+)?)\)'
	vehicle_match = [match for match in [re.match(vehicle_pattern, line) for line in actor_raw_info] if match is not None]

	actors = [{
		'id': int(actor_info[0]),
		'blueprint': 'vehicle.' + actor_info[1],
		'location': (float(actor_info[2]), float(actor_info[3]), float(actor_info[4]))
		} for actor_info in [match.groups() for match in vehicle_match]]

	sensor_pattern = r'Create (\d+): sensor\.([\w.]+) \(\d+\) at \((\-?\d+(?:\.\d+)?), (\-?\d+(?:\.\d+)?), (\-?\d+(?:\.\d+)?)\)'
	sensor_match = [match for match in [re.match(sensor_pattern, line) for line in actor_raw_info] if match is not None]

	sensors = [{
		'id': int(sensor_info[0]),
		'blueprint': 'sensor.' + sensor_info[1],
		'location': (float(sensor_info[2]), float(sensor_info[3]), float(sensor_info[4]))
	} for sensor_info in [match.groups() for match in sensor_match]]

	for i in range(len(actors)):
		if i == len(actors) - 1:
			actors[i].update({'sensors': [sensor for sensor in sensors if sensor['id'] > actors[i]['id']]})
		else:
			actors[i].update({'sensors': [sensor for sensor in sensors if actors[i]['id'] < sensor['id'] < actors[i+1]['id']]})
			
	return actors

def toggle_sync_mode(world, mode):
    settings = world.get_settings()
    settings.synchronous_mode = mode
    settings.fixed_delta_seconds = 0.05 if mode else None
    world.apply_settings(settings)

def main():
	client = carla.Client("localhost", 2000)
	client.replay_file(RECORD_FILE, 0, 0, 0, True)
	world = client.get_world()
	toggle_sync_mode(world, True)

	for _ in range(5):
		world.tick()
		
	actors = parse_replay_file(client, "2023-05-08_20-19-41_792087.log")
	
	# Register sensor callback
	def collision_callback(event):
		print(f"Collision between {event.other_actor.type_id} and {event.actor.type_id}")

	def lane_invasion_callback(event):
		print(f"Lane invasion by {event.crossed_lane_markings.type}")

	def rgb_callback(image):
		print(f"RGB image received: {image.frame_number}")

	sensors = {}
	for actor in actors:
		for sensor in actor["sensors"]:
			sensor_actor = world.get_actor(sensor["id"])
			sensors[sensor["id"]] = sensor_actor

			if sensor["blueprint"] == "sensor.other.collision":
				sensor_actor.listen(lambda event: collision_callback(event))
				print(f"sensor {sensor['id']} is listening to collision event")
			elif sensor["blueprint"] == "sensor.other.lane_invasion":
				sensor_actor.listen(lambda event: lane_invasion_callback(event))
				print(f"sensor {sensor['id']} is listening to lane invasion event")
			elif sensor["blueprint"] == "sensor.camera.rgb":
				sensor_actor.listen(lambda image: rgb_callback(image))
				print(f"sensor {sensor['id']} is listening to rgb event")

	for _ in range(400):
		world.tick()
```

**Comment by Morphlng** [comment]
It seems like if both the record and replay is in synchronized mode, this wouldn't be a problem. But I also found that it occasionally happened that the actor id in the record does not match when actual replaying.

**Comment by AOOOOOA** [comment]
> It seems like if both the record and replay is in synchronized mode, this wouldn't be a problem. But I also found that it occasionally happened that the actor id in the record does not match when actual replaying.

Hi, does the "sync mode in record" mean the Carla world is in sync mode while calling the recorder? Is there any method to check if the log file is recorded under the sync mode if we only have the recorded log file?

**Comment by Morphlng** [comment]
> Hi, does the "sync mode in record" mean the Carla world is in sync mode while calling the recorder? Is there any method to check if the log file is recorded under the sync mode if we only have the recorded log file?

Synchronous mode is usually used in combination of "fixed_delta_seconds" (If not, Carla will warn you). So the simplest way to check whether the replay file is recorded under sync mode, is to check the frame time between each two frame, which should be constant.

```python
import carla

client = carla.Client("localhost", 2000)
filepath = "path_to_replay"
with open("replay_info.txt", "w") as f:
    f.write(client.show_recorder_file_info(filepath, True))
```
