### ISSUE TITLE
CARLA 0.8.4 Windows Download File does not exist (anymore)

### ISSUE THREAD

**Issue by Pointifix** [carla-simulator/carla#6447]
The download link for CARLA 0.8.4 Windows is broken:
https://github.com/carla-simulator/carla/releases/tag/0.8.4
https://drive.google.com/file/d/1CSdQAP2FwvEqQE5Opaq-tVReeW991bR2/view?usp=sharing

Is there a updated link somewhere, can someone post it or fix the link in the release?

![image](https://user-images.githubusercontent.com/35230128/236284046-c782c44a-2897-4f5c-8121-fd1bde5531b4.png)

**Comment by Blyron** [comment]
We do not support 0.8.4 anymore. If you want you could clone 0.8.4 tag repo and try to build yourself, but as I say we do not support that anymore

**Comment by Blyron** [comment]
Are you happy to close this issue?

**Comment by Pointifix** [comment]
I "solved" the problem by switching to Ubuntu. Thank you for the reply though!
