### ISSUE TITLE
Is there a way to run multiple clients as using UR editor?

### ISSUE THREAD

**Issue by maverick-long** [carla-simulator/carla#645]
I made some modifications in the Town01 environment using UR editor. Then I can play the server through editor and launch a client to connect to it. It works perfectly. But, if I want to run multiple clients as using UR editor, is there a way to do that? Does carla 0.9.0 provide the method? Thank you very much!!

**Comment by marcgpuig** [comment]
Hi @maverick-long.
Yes, using 0.9.0 you are able to have 1 instance of UE4 editor running with multiple clients.
