### ISSUE TITLE
Carla Release Quality

### ISSUE THREAD

**Issue by doganulus** [carla-simulator/carla#6484]
It is obvious that the Carla project struggles to keep her base and releases updated and maintained. 

- Still recommends Ubuntu 18.04 (end-of-life)
- Still no support for Ubuntu 22.04
- Debian images are not updated (no 0.9.14 currently)
- Python packages support only 3.7 (end-of-life next month), 3.8
- Docker documentation is not updated. 

What is the root problem?
What is the strategy of the Carla team to improve release engineering?
When is the next release?

**Comment by xavisolesoft** [comment]
Hi,

We introduced Ubuntu 22.04 support for the build few months ago in the official doc.
https://carla.readthedocs.io/en/latest/build_linux/

We created a ticked to build python API for more python versions. Will fix this soon.
https://github.com/carla-simulator/carla/issues/7473
