### ISSUE TITLE
Query Blueprint dimensions without spawning an actor

### ISSUE THREAD

**Issue by abol-karimi** [carla-simulator/carla#6489]
Is it possible to query the simulator for the properties of each available blueprint (e.g. width and length) in the blueprint library without spawning any actors?

**Comment by Blyron** [comment]
Not right now in the PythonAPI.
Are you happy to close this issue as it is not possible to do it?

**Comment by abol-karimi** [comment]
Not a big problem. Right now, I store all the dimensions in a file and use that.
