### ISSUE TITLE
CARLA build support on Ubuntu 22.04

### ISSUE THREAD

**Issue by jfqureshi** [carla-simulator/carla#6494]
Hello everyone,

I am recently switched to Ubuntu 22.04 and I am trying to build Carla on Ubuntu 22.04. I am facing a lot of issues while building and actually could not Build it. 

Do you have any plans to have support for Carla on Ubuntu 22.04?

If not, is there any way around which I can successfully build Carla on Ubuntu 22.04?

Thank you!

**Comment by markomiz** [comment]
There is already a similar issue here: https://github.com/carla-simulator/carla/issues/6381

**Comment by Blyron** [comment]
We already have updated docs for Ubuntu 22; 
https://carla.readthedocs.io/en/latest/build_linux/ 
I'll be closing this issue
