### ISSUE TITLE
Changing map from the client side.

### ISSUE THREAD

**Issue by felipecode** [carla-simulator/carla#65]
Right now the town has to be loaded previously when you start
the server, e.g:
_sh CarlaUE4.sh /Game/Maps/Town02_

When you call for episode restarts on the client side, it is not possible
to change the town, for that you need to manually restart  the server
and select another town.
This reduces the autonomy of training, testing and benchmarking.

I suggest another line on the settings file.
```
[CARLA/LevelSettings]
Map= Town02
```
The server should detect a change in the map and do a full reload.

**Comment by juaxix** [comment]
Did you test the [level_transition](https://github.com/carla-simulator/carla/tree/level_transition) branch already @felipecode ?

**Comment by felipecode** [comment]
@juaxix 
Check my PR #472

**Comment by juaxix** [comment]
It was merged and you can try now, with this PR #482

**Comment by felipecode** [comment]
Still have some errors:
Check my comment on the PR
[2018.06.16-14.53.42:497][ 91]LogCarla: Error: The map in CarlaSettings is not the current one: Town02 !

**Comment by felipecode** [comment]
It passes the test, but after some time running , after changing the town. It crashes. with error above

**Comment by juaxix** [comment]
I see, this is a problem with the [initgame](https://github.com/carla-simulator/carla/blob/level_transition/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp#L75) function then... needs some test + research

**Comment by Danmou** [comment]
Is this still on the roadmap? It would be nice to be able to change map from the client without restarting the server.

**Comment by nsubiron** [comment]
Yup, it's almost done in #1272.
