### ISSUE TITLE
Problem with the latest release 0.9.0

### ISSUE THREAD

**Issue by AbuZekry** [carla-simulator/carla#650]
I've downloaded the latest release 0.9.0 and tried running the manual_control.py script to check the new multi_client feature. First of all there is no PythonClient folder with the release, so i took one from an older release. then when i run the script, i get this error "AttributeError: module 'carla' has no attribute 'Transform'". 

So I fix the import problem, but then i get another error "AttributeError: module 'carla' has no attribute 'Location'".

how can i run the manual_control script without facing all these problems ?

**Comment by meixialin** [comment]
hello，I faced with the same problem ，can you tell me how you solve it?
