### ISSUE TITLE
CarlaUE4 could not be compiled. 

### ISSUE THREAD

**Issue by Deepank308** [carla-simulator/carla#651]
Hello all,
I am trying to build Carla 0.8.4 on Windows 10. 
I have UE4.19 and Visual Studio 17.
I followed the steps provided the link : [http://carla.readthedocs.io/en/latest/how_to_build_on_windows/](http://carla.readthedocs.io/en/latest/how_to_build_on_windows/)

Setup.bat ran successfully.
I added the content for Carla 0.8.4.
Ran Rebuild.bat. It was also successful.

But Upon rebuilding the .dll files(UE4Editor-CarlaUE4.dll, UE4Editor-Carla.dll), encountered an error : 
![screenshot 20](https://user-images.githubusercontent.com/32814077/43680535-4a279622-9867-11e8-88aa-6e0afdf8e35f.png)

I have also tried for Carla 0.8.2 but it has no Setup batch file(Setup.bat) : ( 

Please help!!
Thank you!

**Comment by marcgpuig** [comment]
Hi @Deepank308.

Read closely at the content of the link you provided!

> Necessary software:
Unreal Engine **(v4.18.x)**

Hope it solves your problem.

Cheers.
