### ISSUE TITLE
Spectator view swing

### ISSUE THREAD

**Issue by mamaduke21** [carla-simulator/carla#6520]
Hi

I have a problem when i set the spectator view. 
The view is from the inside of the car and when the car accelerates or decelerates the view swing back and front.

The code i use to change the view is:
 def spectator_view(self):
        spectator = self.__world.get_spectator()
        transform = self.player.get_transform()
        spectator.set_transform(carla.Transform(transform.location + carla.Location(x=0.4,y=0.5, z=0.4), carla.Rotation(0,90,0)))

Here's a gif:         
![ezgif com-video-to-gif](https://github.com/carla-simulator/carla/assets/76569758/76862068-0e77-4dac-b12f-d067f3881b7d)

**Comment by Blyron** [comment]
Are you running in sync mode?

**Comment by Blyron** [comment]
As we have recieved no respond, we are closing this issue. If something comes up, please, feel free to reopen it
