### ISSUE TITLE
Mic -> Carla -> Zoom ?

### ISSUE THREAD

**Issue by Golddouble** [carla-simulator/carla#6534]
Hello

I am very new to Carla.

Is it possible with Carla to alienate voice, before the voice goes into the video conferencing software "Zoom"?

If yes: What do I have to do?

Carla looks like this:
![k20230603-200537](https://github.com/carla-simulator/carla/assets/13977359/9ed67472-2d68-449b-bacc-1928052308da)
![k20230603-200148](https://github.com/carla-simulator/carla/assets/13977359/ac0c9b55-c223-47f1-b970-dec91b1a2a71)

I guess I have to connect my microphone with a plugin. After I guess I would have to connect the plugin with Zoom. But I do not find a Zoom Box in Carla.

What are the correct steps?

Would appreciate some answer. Thank you.

**Comment by Blyron** [comment]
I think you are in wrong carla repo, this is autonomus driving carla

**Comment by Blyron** [comment]
A
