### ISSUE TITLE
Black window with manual_drive.py

### ISSUE THREAD

**Issue by grafandreas** [carla-simulator/carla#654]
Hello all,

I have successfully built Carla on Windows and run the example.py. Works fine.
However, when running manual_drive.py (sorry if it is not the correct name, I am away from that computer), the new window just opens and stays black. Nothing seems to happen.

I am running the carla server in Window mode on the same machine as the python program.

Any suggestions?

Thanks,

Andreas

**Comment by marcgpuig** [comment]
Hello, @grafandreas.
Sorry for the late response, we were on vacations :)

Which version of Carla are you using? How about the log? 
I have no idea what could be happening.
