### ISSUE TITLE
Different road surface type? 

### ISSUE THREAD

**Issue by yaxinluan** [carla-simulator/carla#655]
Hello,

I was wondering, does different weather condition changes the road surface condition (i.e traction coeff, drag coeff ect.)? 
If it does, how can I find out what those coefficients are? 
If not, is there a way to mimic different types of road surface? (sand, asphalt, concrete ect.)

Thank you!

**Comment by marcgpuig** [comment]
Hi @yaxinluan.

I'm sure you can change the friction coefficient and so on, but right now we are not taking into consideration this kind of information, sorry about that.

Cheers.
