### ISSUE TITLE
windows Low graphics or no rendering mode

### ISSUE THREAD

**Issue by prabanjan2419** [carla-simulator/carla#6558]
Does anyone know how to run CarlaUE4.exe in windows in no rendering or low graphics mode?

**Comment by prabanjan2419** [comment]
As well as off screen mode please!

**Comment by Bsornapudi** [comment]
i have the same issue , my system has directx12 which is not helping CarlaUE4.exe.
as a work around i am running carla exe from cmd with -dx11 flag

**Comment by Blyron** [comment]
We have available -RenderOffScreen option plus other stuff related with rendering. Please look at docs:
https://carla.readthedocs.io/en/latest/adv_rendering_options/#setting-off-screen-mode-version-0912
