### ISSUE TITLE
Custom semantic tag generation

### ISSUE THREAD

**Issue by seungtae-Han** [carla-simulator/carla#6569]
CARLA version: 0.9.14
Platform/OS: Ubuntu 20.04
Problem you have experienced: Semantic tag is not generated.
Steps to reproduce:

Hello?
I'm trying to create a Semantic LiDAR dataset using a custom map created with 'roadrunner'.
I have been trying to generate a custom tag for tree objects in the custom map by referring to the Carla document (https://carla.readthedocs.io/en/latest/tuto_D_create_semantic_tags/), but i am encountering some issues.
Let me list the steps i have taken so far.

1. I moved the exported '.fbx' and '.xodr' files from the custom map to '~/carla/Import/'. 
2. I entered the 'make import' command in the terminal.
3. As instructed in the document, I made the following codes modifications to add the 'Tree' tag:
- 'LibCarla/source/carla/rpc/ObjectLabel.h'
![image](https://github.com/carla-simulator/carla/assets/70038690/eadf2293-3a80-42a7-b1cf-a44ec0727863)

- '/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/Tagger.cpp'
![image](https://github.com/carla-simulator/carla/assets/70038690/3b365d37-bf8c-4658-aed8-20ca2fb05380)
![image](https://github.com/carla-simulator/carla/assets/70038690/028dd4cd-a3c9-4dd7-921d-65068ec4b22e)

- 'LibCarla/source/carla/imge/CityScapesPalette.h'
![image](https://github.com/carla-simulator/carla/assets/70038690/ba43cbca-fda5-4453-9753-f13174ca24b7)

4. I create a folder named 'Tree' inside the '/Static/' directory within the map_package folder, which was generated using the 'make import' command. The path to the map_package folder is '/Unreal/CarlaUE4/Content/map_package'.
![image](https://github.com/carla-simulator/carla/assets/70038690/3ea2b553-a86f-4c0d-acc9-419034ac1417)

5. I create a folder named 'Test_1', which has the smae name as the custom map. and I moved the tree-related uasset files from '/Static/Terrain/Test_1/' to '/Static/Tree/Test_1/'.

So, the map_package directory has the following structure:
![image](https://github.com/carla-simulator/carla/assets/70038690/23588309-2590-4b42-a0fc-94211268c3e7)

6. After launching the Unreal Engine by entering the 'make launch' command, when importing map, none of the tree objects appear as shown in the image below.
![image](https://github.com/carla-simulator/carla/assets/70038690/924d7b6a-de82-4c6c-8f5e-fba1307b3315)

If i move the tree-related uasset files back to their original location at 'Static/Terrain/Test_1/', trees appears as shaown in the image below.
![image](https://github.com/carla-simulator/carla/assets/70038690/6ac750b7-bb6d-4c6d-b509-c0c0a03d700d)

Is there anyone who can help me identify what i might have misconfigured during this process?
I welcome any response or assistance !!!!

**Comment by ronyshaji** [comment]
@seungtae-Han Did you already found a solution ?
