### ISSUE TITLE
Intersection stop signs and stop sign autopilot

### ISSUE THREAD

**Issue by nrhine1** [carla-simulator/carla#657]
Currently, the behavior at intersections is governed by a traffic light group, which is a triplet of signs with <=2 of them green (all intersections are currently three-way intersections). However, it would be useful to support stop signs at intersections, with controlled agents respecting the rules of stop signs via autopilot. According to the `0.9.0` release blogpost, which mentions future support of "traffic control tools", it appears this may be in the goals of future development already.

In the meantime, is there a simple approach to adding stop signs into the map and autopilot framework? For instance, removing 2/3 of a traffic light triplet corresponding to the straightaway, and keeping 1 of the triplet as a 'stop sign' that signals to the turning vehicle that it cannot turn unless its path through the intersection is clear. I believe this could be implemented via some collision checking (and if it's fancier, depend on the speed limit of the straightaway), although it would need to be along the planned path spline instead of the ray casting proximity checking of the `IsThereAnObstacleAhead` function.

**Comment by nsubiron** [comment]
Hi @nrhine1, sorry for taking so long to reply.

Yes, we want to extend both the variety of traffic rules and signs, and being able to control them at run-time. But doing a general approach for this is complicated and will take us some time to have a working version (plus we have a few things with higher priority to address first).

So in the meantime, I think your approach is right. You can easily do this in blueprints. You can create a new blueprint that adds an invisible box in front of the vehicle. As long as this box is marked as movable, the `IsThereAnObstacleAhead` function will detect it and the car will stop. Then you remove the box when you want the vehicle to keep going. For instance, this is used by walkers, they have a pretty big invisible box around them, so when they walk towards a road they are detected by vehicles before they get there.
