### ISSUE TITLE
SUMO Co-Simulation with manual control not working

### ISSUE THREAD

**Issue by mariusschueller** [carla-simulator/carla#6585]
Hi, 

CARLA version: 0.9.14
Platform/OS: Ubuntu 20.04.5

I'm having an issue where whenever I run manual_control.py my con-simulation stops working and gives me Error: Answered with error to command 0xc4: MoveToXY vehicle should obtain: edgeID, lane, x, y, angle and optionally keepRouteFlag.

In the past, I have been able to simultaneously run both, but I'm not sure what has changed. 

I think that one possible reason this occurs is because I needed to change line 304 in sumo_simulation.py to sumo_net = sumolib.net.readNet(net_file) from .readNet(net_file), but I had to make this change or else my co-simulation wouldn't work at all.

**Comment by yunhaohu** [comment]
Have you fix it ? the same problem happens to me

**Comment by mariusschueller** [comment]
I manually installed an older version of traci using pip and that appears to have fixed the issue.
