### ISSUE TITLE
Scenario Runner - Openscenario, How to find road_ID of a junction in the carla map

### ISSUE THREAD

**Issue by prabanjanGITHUB** [carla-simulator/carla#6595]
I am trying to write a custom openscenario to use it with scenario runner 9.13.

I want to spawn the vehicle near a junction in the Carla town01.  How can I find the "road_ID" and "S" and "t" values to define in my openscenario file?

Is trial and error the only way?

**Comment by demirciogl** [comment]
You can use an online OpenDRIVE viewer. For example:  https://odrviewer.io/

**Comment by prabanjanGITHUB** [comment]
This is a cool tool. Thanks a lot for sharing. But, may I know where can I find the openDrive files of carla towns for example carla town10HD!

**Comment by prabanjanGITHUB** [comment]
oh Never Mind, I found it. The path is: WindowsNoEditor\CarlaUE4\Content\Carla\Maps\OpenDrive.  Thanks
