### ISSUE TITLE
Start position indexing is different for the first episode requested

### ISSUE THREAD

**Issue by Ajk4** [carla-simulator/carla#662]
CARLA version - 0.8.4

I want to always start episode from the same location so I pass the same start location index every time to game.start_episode function.

However the very first episode requested seems to have different index-to-start_location mapping - I get different location in the first episode.

**Comment by marcgpuig** [comment]
Hi @Ajk4, sorry for the late response, we were on holidays :)

Sadly this is a known problem, please take a look at #310.
The issue is closed because using 0.9.0 this is not a problem anymore.
