### ISSUE TITLE
CARLA_0.9.14.zip is broken

### ISSUE THREAD

**Issue by ChanCody** [carla-simulator/carla#6623]
I've downloaded the released package CARLA_0.9.14.zip for twice in windows and I cannot unzip both using WinRAR:
![image](https://github.com/carla-simulator/carla/assets/138865092/53458351-aefb-45a9-ae56-4ecc67f0bbc6)
Looks like the zip file is broken.
I've also tryied 0.9.11, it works fine.

**Comment by siddharthjain38** [comment]
@ChanCody I downloaded carla from (https://github.com/carla-simulator/carla/releases/tag/0.9.14/) and its working absolutely fine for me on windows machine. Make sure you download zip file in single go, network should not disconnect in between.
