### ISSUE TITLE
[CarlaUE4Editor] Error 6

### ISSUE THREAD

**Issue by SushilaRatre** [carla-simulator/carla#6637]
Hello All,

I am getting the same error after multiple reinstallations of CARLA while executing the command "make launch".
Please provide the solution for this. Thank you so much.

I am trying to install Carla 0.9.14 on windows 11 as per the instructions mentioned in the official document. 
[https://carla.readthedocs.io/en/latest/build_windows/]
Unearl Engine 4.26.2
Visual Studio 19

![image](https://github.com/carla-simulator/carla/assets/137510646/89a63d4e-6bf9-43e7-945b-973d4abab21c)
It is working properly till make pythonAPI. 

![image](https://github.com/carla-simulator/carla/assets/137510646/873cc2a1-8fe6-42f1-9042-0282994e3695)

C:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Sensor/SceneCaptureSensor.h(15): fatal error C1083: Cannot open include file: 'Renderer/Public/GBufferView.h': No such file or directory
make: *** [CarlaUE4Editor] Error 6
!

**Comment by Chang-byte** [comment]
I have encountered the same problem, have you solved it?
![image](https://github.com/carla-simulator/carla/assets/77491961/fde490ff-04f9-42e2-a10c-d0a98a5ff7fa)

**Comment by SushilaRatre** [comment]
Yes, I have successfully installed the Carla simulator after reinstallation
of the software.

**Comment by SushilaRatre** [comment]
Hi! Try to follow the following link to solve the problem of fatal error.

https://www.drivereasy.com/knowledge/how-to-fix-unreal-engine-crash-quickly-and-easily/

**Comment by SushilaRatre** [comment]
> I have encountered the same problem, have you solved it? ![image](https://user-images.githubusercontent.com/77491961/255507127-fde490ff-04f9-42e2-a10c-d0a98a5ff7fa.png)

Hi!, Try to use the following link to solve the problem of fatal error.
https://www.drivereasy.com/knowledge/how-to-fix-unreal-engine-crash-quickly-and-easily/

**Comment by Chang-byte** [comment]
Thanks a lot,I'll try it

**Comment by Blyron** [comment]
Those issues happens because u are trying to use a Vanilla version of Unreal instead of CARLA version. Please stick to build instructions.
