### ISSUE TITLE
RADAR Sensor Implementation

### ISSUE THREAD

**Issue by Estivio** [carla-simulator/carla#6674]
Hi, 

I am currently working on a project where I need a proper radar simulation.
I found the following issue, where the current implementation is called a "placeholder": https://github.com/carla-simulator/carla/issues/2831. Indeed after looking into the code, this is not much more than randomly distributed raycasting. How is the current status on a proper radar simulation? The issue mentions an "External Sensor Interface". Are there any documents on what was to be implemented regarding radar? 

Under certain circumstances I would start implementing a radar myself, so it might be helpful if there were already documented considerations.

**Comment by Blyron** [comment]
Hi
This is our current RADAR implementation, https://github.com/carla-simulator/carla/blob/dev/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Radar.cpp

If you want to create new sensor or more acurate RADAR we will be glad to have that implemented on our code base. 
Here you have how to create new sensor: 
https://carla.readthedocs.io/en/latest/tuto_D_create_sensor/
