### ISSUE TITLE
fatal: repository 'https://github.com/CarlaUnreal/UnrealEngine.git/' not found

### ISSUE THREAD

**Issue by northbigpanda** [carla-simulator/carla#6681]
I tried to install Carla by the process of below link:
https://carla.readthedocs.io/en/0.9.14/build_linux/#unreal-engine,

when I proceeded to the step of installing UE4.26, i linked the UE account and Github account per the request of below instruction:
https://www.unrealengine.com/en-US/ue-on-github

then i continued with below command:
git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git ~/UnrealEngine_4.26

then an error emerged as below:
"remote: Repository not found.
fatal: repository 'https://github.com/CarlaUnreal/UnrealEngine.git/' not found",

so how to find the address of UE4.26, thanks a lot.

**Comment by 2019211753** [comment]
did u receive a email to conform the link? u can check it

**Comment by northbigpanda** [comment]
> did u receive a email to conform the link? u can check it

yes, I received the mail and confirmed the link, still cannot git the clone…

**Comment by 2019211753** [comment]
emm..,do u have a organizations badge 'EPIC' in your github overview page?

**Comment by northbigpanda** [comment]
> emm..,do u have a organizations badge 'EPIC' in your github overview page?

no, i cannot find it, could you send me a screenshot so that i can see what it is, thanks.

**Comment by 2019211753** [comment]
> > emm..,do u have a organizations badge 'EPIC' in your github overview page?
> 
> no, i cannot find it, could you send me a screenshot so that i can see what it is, thanks.

![image](https://github.com/carla-simulator/carla/assets/65377379/7d9a0b61-4e43-4be8-93c5-ccf7decc86cd)

**Comment by northbigpanda** [comment]
> > > emm..,do u have a organizations badge 'EPIC' in your github overview page?
> > 
> > no, i cannot find it, could you send me a screenshot so that i can see what it is, thanks.
> 
> ![image](https://github.com/carla-simulator/carla/assets/65377379/7d9a0b61-4e43-4be8-93c5-ccf7decc86cd)
> 
I don't have this badge, how did you get it?

**Comment by 2019211753** [comment]
> > > > emm..,do u have a organizations badge 'EPIC' in your github overview page?
> > > 
> > > 
> > > no, i cannot find it, could you send me a screenshot so that i can see what it is, thanks.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/65377379/258102991-7d9a0b61-4e43-4be8-93c5-ccf7decc86cd.png)
> 
> I don't have this badge, how did you get it?

sorry for my late reply. just follow the instructions step by step.

**Comment by Blyron** [comment]
The clone link should be this one 
https://github.com/CarlaUnreal/UnrealEngine.git

**Comment by Blyron** [comment]
And you have joined Epic Games organziation? 
If you have fixed this issue, are you happy to close this issue?

**Comment by northbigpanda** [comment]
> And you have joined Epic Games organziation? If you have fixed this issue, are you happy to close this issue?

Yes, I have joined the Epic Games organination, thanks.

**Comment by northbigpanda** [comment]
> And you have joined Epic Games organziation? If you have fixed this issue, are you happy to close this issue?

Yes, I'm happy to close this issue, thank you.
