### ISSUE TITLE
 Change pedestrian stop distance in front of vehicle

### ISSUE THREAD

**Issue by tgieruc** [carla-simulator/carla#6688]
Hi all!
I would like to be able to change the distance at which pedestrians stop in front of a vehicle when it is on their way. 
I am building Carla 0.9.14 from source on Linux, I have tried to change the 6.0f here:
https://github.com/carla-simulator/carla/blob/43b5e7064872bb6a9529664c2218e29df38dca04/LibCarla/source/carla/nav/WalkerEvent.cpp#L43
as well as reducing this marge:
https://github.com/carla-simulator/carla/blob/43b5e7064872bb6a9529664c2218e29df38dca04/LibCarla/source/carla/nav/Navigation.cpp#L539
but it hasn't changed the behavior.

Would you have an idea what should I change in order to reduce the distance at which pedestrians stop in front of vehicles?
I have seen that there is a similar issue from three years ago there : https://github.com/carla-simulator/carla/issues/2670#issuecomment-652508968. Is it still the case today with 0.9.14?
Thank you in advance for your support!

**Comment by DnDare** [comment]
Hello,  if you have acces to UE4 project, you can access the walker Blueprint,
Ther's a box collider named CarStopper,   you can scale the box to reduce the stop distance.
If you want to change all pedestrians change BP_Walker, the parent class.
Or you can reduce each pedestrian's inherited CarStopper.

![image](https://github.com/carla-simulator/carla/assets/57799121/a902b5b3-f0b6-425a-aa88-2b62af94cf49)
