### ISSUE TITLE
How to use the self-compiled carla-0.9.0

### ISSUE THREAD

**Issue by WillenPeng** [carla-simulator/carla#669]
Hi,

I found out that the interface of self-compiled carla-0.9.0 is very different from the 0.8.2 pre-compiled version. In 0.9.0 I cannot see the car as well as other sensor measurement. Is there any tutorial about how to use carla-0.9.0?

**Comment by nsubiron** [comment]
Hi @WillenPeng,

Yes, a lot of things drastically changed with Carla 0.9.0. This is a development version, and many things are not well documented yet. You can find an introduction on how the new API works in our latest blog entry: [CARLA 0.9.0: Multi-client multi-agent support](http://carla.org/2018/07/30/release-0.9.0/).

I'm also linking #660 as it's somehow related.
