### ISSUE TITLE
Capability of cameras capturing images at the same time

### ISSUE THREAD

**Issue by mgao97** [carla-simulator/carla#6713]
CARLA version: 0.9.13
Platform/OS: Linux Ubuntu
Problem you have experienced: Low Image Quality (too bright)

Hi, thanks for your great work!

Assuming I have assigned 10 cameras to 10 vehicles, I want to know whether these cameras can capture images at the same time. 

Otherwise, what should I do to make it possible?

**Comment by MichelleSchaaf** [comment]
Hey,

check out this example script: [sensor_synchronization.py](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/sensor_synchronization.py). It uses a queue in the sensor callback. I have adapted the sensor_callback method, so it saves the generated images:
```python
    def sensor_callback(self, sensor_data, sensor_queue, sensor_name,cc):
        # Do stuff with the sensor_data data like save it to disk
        # Then you just need to add to the queue
        save_path = os.path.join(self._args.outputImg, sensor_name, str(sensor_data.frame)+".png")
        sensor_queue.put((sensor_data.save_to_disk(save_path, cc), sensor_data.frame))
```
you then only need to call this method when your camera "listens":
```python
cam.listen(lambda data: self.sensor_callback(data, sensor_queue, sensor_name, carla.ColorConverter.Raw))
```

**Comment by mgao97** [comment]
Thank you for your message!

I also need to record the positions and rotations of cameras during capturing each image, could this be achieved by the sensor_callback? Another question is about the relationship between the setting of 30 fps and the driving speeds of vehicles. 

Thank you so much!

**Comment by Blyron** [comment]
You can get each camera transform on each frame so yeah. FPS determines simulation speed. No driving speeds

**Comment by Blyron** [comment]
Are you happy to close this issue with the answer given?
