### ISSUE TITLE
How to cross compile LibCarla for android/qnx ?

### ISSUE THREAD

**Issue by rohitrnath** [carla-simulator/carla#6716]
I'm trying to develop a c++ application running on QNX/Android which listen to Carla sensors. I can able to make the application on linux using LibCarla client libraries. Is it possible to cross compile the client libraries for ARM toolchains?

**Comment by Blyron** [comment]
We have not develop that feature, feel free to do it yourself. It should be possible but you will need to create a new Build System on your own.
