### ISSUE TITLE
Compiled Version vs Source

### ISSUE THREAD

**Issue by Gaduu** [carla-simulator/carla#672]
Hi,

Just quick probably trivial question regarding using CARLA. Is there any difference between using the compiled version of carla vs the one build from source apart from the obvious fact of having access to the stuff inside UE4? 

Regards,

**Comment by iFuSiiOnzZ** [comment]
Hi

There is no difference. The good of using a binary (compiled version already) is that you don't have to deal with the possibles problems during the compilation.
