### ISSUE TITLE
annotation 

### ISSUE THREAD

**Issue by wangwz6666** [carla-simulator/carla#6723]
May I ask why there are strange boxes when visualizing？
![000040](https://github.com/carla-simulator/carla/assets/44573624/9f8e4ab3-e9f4-45f5-adb4-5151faae6183)

**Comment by u-sj** [comment]
Look like the same issue that is fixed by this PR: https://github.com/carla-simulator/carla/pull/6630

**Comment by Blyron** [comment]
Hi
We are closing this issue, please reopen again if something comes up and the PR is merged
