### ISSUE TITLE
Failed to launch CARLA v0.9.0 on Linux

### ISSUE THREAD

**Issue by atinfinity** [carla-simulator/carla#673]
##### System information (version)
- CARLA => v0.9.0(Compiled version) 
- Operating System / Platform => Ubuntu 16.04 64bit
- Graphics Driver => nvidia-387
- Graphics Card => GeForce GTX 1060

##### Detailed description
I tried to launch CARLA v0.9.0 using `CarlaUE4.sh`.
But, vehicle is flying in the sky. And, I can not control vehicle.

![carla090](https://user-images.githubusercontent.com/2630323/44038197-2f32280a-9f51-11e8-997b-dc41a52889ff.png)

On the other hand, I can control vehicle in previous version(v0.8.4).
![calra084](https://user-images.githubusercontent.com/2630323/44038326-836e7b4e-9f51-11e8-9b39-9c7af77ee8c5.png)

##### Steps to reproduce
```shell
$ ./CarlaUE4.sh
```

**Comment by KevinYuk** [comment]
Any update?

**Comment by nsubiron** [comment]
This is the intended behaviour of 0.9.0 API, please check out #660.
