### ISSUE TITLE
broken lens when conducting 'visualize_multiple_sensors.py' in carla0.9.14

### ISSUE THREAD

**Issue by jingyue01** [carla-simulator/carla#6734]
![image](https://github.com/carla-simulator/carla/assets/139851803/128e7de5-50d5-445b-8f1a-53d875e6e019)

CARLA version: 0.9.14
Platform/OS: windows10
Problem you have experienced: camera works unexpected
What you expected to happen: clear camera view
Steps to reproduce: python 3.7
Other information (documentation you consulted, workarounds you tried): When I try the same python exmaple in Carla 0.9.13, it successfully worked.

![image](https://github.com/carla-simulator/carla/assets/139851803/e7196207-1fbd-4221-a950-9f090526c937)

**Comment by jingyue01** [comment]
#6565 same problem, solved now

**Comment by TzabarDolev** [comment]
I just wrote a short blog post about this issue on the Carla simulator research blog - https://carlasimblog.wordpress.com/2023/09/16/the-64-division-curse/. And added a short code snippet to fix this.
