### ISSUE TITLE
Building 0.8.4 on windows - missing Setup.bat

### ISSUE THREAD

**Issue by nwsweet** [carla-simulator/carla#674]
Hi,

I am trying to build version 0.8.4 on windows. I have cloned the repository and switched to the stable branch, but there is no Setup.bat in this branch. I'm not really sure how to proceed without this. Thanks for any help.

**Comment by marcgpuig** [comment]
Hi @nwsweet.
Sorry for the late response, we were on vacations :)

This is really strange, please try this git command:

    git clone -b 0.8.4 https://github.com/carla-simulator/carla.git

This will download directly the 0.8.4.
