### ISSUE TITLE
Accident detector in CARLA

### ISSUE THREAD

**Issue by AOOOOOA** [carla-simulator/carla#6741]
Hi,

I notice there is a collision detector in Carla sensor used for detecting the collision event. But I haven't found the corresponding code block for the collision detector implementation. Could you please tell me where I can find it? 
And I'm also curious about whether Carla has other accident detectors besides the collision detector. Could you please help me with that? @krmartin @sunpochin @Jazzinghen @cesarsouza @armando-fandango 
Thanks!

**Comment by TzabarDolev** [comment]
Hi, 
I just wrote a short blog post about collision detectors on the Carla simulator research blog - https://carlasimblog.wordpress.com/2023/09/18/collision-detection-systems-in-cars-enhancing-safety-and-realism-in-carla-simulator/, and added a code example for it.

**Comment by AOOOOOA** [comment]
> Hi, I just wrote a short blog post about collision detectors on the Carla simulator research blog - https://carlasimblog.wordpress.com/2023/09/18/collision-detection-systems-in-cars-enhancing-safety-and-realism-in-carla-simulator/, and added a code example for it.

Thanks so much. Your blog is clear and helps a lot. But I want to know how the collision sensor works in Carla. i.e. how does the collision sensor know there is a collision happened? I have searched the code but didn't find the corresponding code snippet.

**Comment by TzabarDolev** [comment]
> > Hi, I just wrote a short blog post about collision detectors on the Carla simulator research blog - https://carlasimblog.wordpress.com/2023/09/18/collision-detection-systems-in-cars-enhancing-safety-and-realism-in-carla-simulator/, and added a code example for it.
> 
> Thanks so much. Your blog is clear and helps a lot. But I want to know how the collision sensor works in Carla. i.e. how does the collision sensor know there is a collision happened? I have searched the code but didn't find the corresponding code snippet.

Hi, Actually it was answered here - https://github.com/carla-simulator/carla/issues/4409

**Comment by AOOOOOA** [comment]
> > > Hi, I just wrote a short blog post about collision detectors on the Carla simulator research blog - https://carlasimblog.wordpress.com/2023/09/18/collision-detection-systems-in-cars-enhancing-safety-and-realism-in-carla-simulator/, and added a code example for it.
> > 
> > 
> > Thanks so much. Your blog is clear and helps a lot. But I want to know how the collision sensor works in Carla. i.e. how does the collision sensor know there is a collision happened? I have searched the code but didn't find the corresponding code snippet.
> 
> Hi, Actually it was answered here - #4409

Thank U so much!

**Comment by Blyron** [comment]
Hi
We are closing this issue, please reopen again if something comes up
