### ISSUE TITLE
Unable to build UnrealEngine_4.26

### ISSUE THREAD

**Issue by j-cyoung** [carla-simulator/carla#6744]
I'm building UnrealEngine_4.26, but when run './Setup.sh', I encountered download failure.
![image](https://github.com/carla-simulator/carla/assets/54196410/e6b9c074-d2d1-4c17-a3a7-b7b84398a01e)

or by https
![image](https://github.com/carla-simulator/carla/assets/54196410/020a135c-e910-4edc-bc39-f6dc36f2f5b1)

But I can download the file from the url, so how can I download the file by `Setup.sh` or put already downloaded file in the local cache?

Thanks so much !

**Comment by FinCreWorld** [comment]
The network error is still not fixed. But I tried to identify the exact location of the cache file. And then I put the downloaded file in the folder manually.
![image](https://github.com/carla-simulator/carla/assets/54196410/7156e0d2-cb5c-4a50-9e3c-46126d8e22fa)

**Comment by Yin-xiongjie** [comment]
Hello friends, I met the same problem, do you know the cause of the problem? And how did you solve it? If I download the file manually, where should I put it?

**Comment by j-cyoung** [comment]
> Hello friends, I met the same problem, do you know the cause of the problem? And how did you solve it? If I download the file manually, where should I put it?
![image](https://github.com/carla-simulator/carla/assets/54196410/2a722dec-60c2-488c-80b2-161fb76b02e4)

I don't know the cause of this problem. But I tried to get the location of the file by checking update time of all related folders, and then I found the cache folder shown in the image above. You can see this folder (`.git/ue4-gitdeps/c3`) sharing the same prefix with the missing file (`c33ef...`). I downloaded the file manually and put it intot he folder.

**Comment by Blyron** [comment]
Please if the issues are related with Unreal Engine, please refer to Epic Games forum. 
If you follow carla build that should be working

**Comment by Blyron** [comment]
I am closing this issue, feel free to reopen if something comes up
