### ISSUE TITLE
CarlaUE4/Plugins/StreetMap/Source/StreetMapRuntime/Private/StreetMapComponent.cpp:15:10: fatal error: 'Carla/BlueprintLibary/MapGenFunctionLibrary.h' file not found

### ISSUE THREAD

**Issue by aidenyao** [carla-simulator/carla#6745]
CARLA version:0.9.14
Platform/OS:ubuntu18.04.5
Unreal Engine Version: 4.26.2
Problem you have experienced:
I want to use StreetMap unreal plugins (https://github.com/carla-simulator/StreetMap),but when i make launch, it show errors:
carla-0.9.14/Unreal/CarlaUE4/Plugins/StreetMap/Source/StreetMapRuntime/Private/StreetMapComponent.cpp:15:10: fatal error: 'Carla/BlueprintLibary/MapGenFunctionLibrary.h' file not found。How to solve it?

**Comment by zhaozhiqing1** [comment]
请问一下这个问题你解决了吗

**Comment by Blyron** [comment]
That Plugin depends completely on CARLA so is installed with carla when you make a make launch. Please, try to use it with CARLA itself. if you do not want to, please refer to original plugin https://github.com/ue4plugins/StreetMap

**Comment by Blyron** [comment]
No, we are not supporting 4.27 in short term


Aaron Samaniego Diaz
