### ISSUE TITLE
Vehicle audio does not produce in Carla Client (In Pygame window)

### ISSUE THREAD

**Issue by inrkumar22** [carla-simulator/carla#6749]
Thanks for contributing to CARLA!

If you are reporting an issue, please use the following outline:

CARLA version: 0.9.14

Platform/OS: Windows

Problem you have experienced: I have integrated engine audio with one of the Carla car model using UnrealEngine Editor. When I executed 'generate_traffic.py' file with the same car model, we heard the engine sound in Carla Simulator inside the UnrealEngine. But when I executed the 'manual_control.py' with the same car model, it does not produce any engine audio on the PyGame Window.

What you expected to happen: I was expecting the engine sound on the PyGame Window for that car model.

Steps to reproduce: 
1. Integrate the audio file using Sound Cue. You can take help from the youtube vidoe : https://www.youtube.com/watch?v=0X2KgGakK24
2. Once you are done. You can execute generate_traffic.py script in carla simulator inside unreal engine 4.27.2.
3. You can hear the car engine sound in between if run for few minutes.
4. Now run the manual_control.py script with the same car model. It pops out the PyGame window, You can play with the car but NO audio.

Other information (documentation you consulted, workarounds you tried): I gone through the Client PythonApi to fetch any additonal sensor data which can help here.

If you are asking a question please make sure your question was not asked before
by searching among the existing issues and checking the CARLA forum https://github.com/carla-simulator/carla/discussions. Also make sure you have read ourdocumentation and FAQ at http://carla.readthedocs.io. 

If your question is about creating content (assets, levels) you'll most likely
have all the info you need in the Unreal Engine's documentation
https://docs.unrealengine.com

Please, keep the threads focused and single-themed. Make them easy to find
for everyone.

Any kind of help is really appreciated.

**Comment by chirudeep001** [comment]
@bernatx @germanros1987 
 can you please help me with that i am also facing the same issue.

Does pygame is compatible with the unreal editor changes.

**Comment by Blyron** [comment]
Hello!
We are not transmitting audio to the carla client. It is not expected to implement this feature. 
If someone in the community contributes to it, we will appreciate it.
