### ISSUE TITLE
terrible lagging on windows

### ISSUE THREAD

**Issue by jianghe01** [carla-simulator/carla#677]
i create a solution on windows with GTX1080-Ti.
when i try to run it, it lags terriblely. how can i make it fluently ?
thank u very much.

**Comment by jianghe01** [comment]
but it more fluently when i run the released version. 0.8.4

**Comment by marcgpuig** [comment]
Hi @jianghe01.

Which client are you using?
Which is your question?
Can you reformulate it, please?

Also take a look at #485, #606
