### ISSUE TITLE
Lidar support

### ISSUE THREAD

**Issue by parilo** [carla-simulator/carla#68]
Hi, All.
I've added Lidar support and now cleaning my code and fixing minor problems. Soon I will be able to make cross repo pull request. Will my code be useful for Carla project?

What is supported:
- adding any number of lidars through configuration ini file
- for individual lidars set number of lasers and vertical angles, number of points per second, position, orientation
- currently lidar returns XYZ coordinates in lidar frame
- points are serialized and available in python client and visualized in ./carla_manual_control.py

**Comment by felipecode** [comment]
Hey Parilo !
Thank you a lot for your contribution ! We are definitely looking into your code and trying to add it to the release 0.7.2.

**Comment by parilo** [comment]
I've created pull request with my changes. I've updated the code with recent master. Now it is ready for review.

**Comment by nsubiron** [comment]
Thanks @parilo! We might take a couple of weeks to review it since now we are very busy, but we are definitively interested.
