### ISSUE TITLE
Start_index position mismatching

### ISSUE THREAD

**Issue by lihanxiang0309** [carla-simulator/carla#680]
![town01_allstartpoint](https://user-images.githubusercontent.com/42187291/44276481-9570a300-a215-11e8-9694-2bd6565af700.png)
![town02_allstartposition](https://user-images.githubusercontent.com/42187291/44276491-9dc8de00-a215-11e8-89ed-5e7672693419.png)

Hi,

These two images about the starting index position are generated using the provided view_start_positions.py function. However, we found the starting index position is wrong: For example, in Town1's image, you can see that the position of index 16 and index 18 are very close to each other. However, their world coordinates are very different from each other: 18 -> (299,199,38), 16 -> (154,19,38). So the mismatching problem is clear.

We are interested in two possible solutions:
1. Provide us the correct Town01 and Town02 starting index image files.
2. Directly set the starting position via x-y coordinates instead of starting index.

Any help will be appreciated.

Thanks,

Hanxiang

**Comment by marcgpuig** [comment]
Hi @lihanxiang0309, sorry for the late response, we were on holidays :)

> Provide us the correct Town01 and Town02 starting index image files.

Please take a look at #310, #662.

> Directly set the starting position via x-y coordinates instead of starting index.

This is currently available using CARLA 0.9.0.
