### ISSUE TITLE
if want to use Python 3.10, where can the *.whl file for Python 3.10 and Carla 9.14 be downoladed? 

### ISSUE THREAD

**Issue by ZhangChao573** [carla-simulator/carla#6806]

**Comment by gezp** [comment]
i have built carla python client package in ubutnu22.04 by Github CI (refer to https://github.com/gezp/carla_ros/releases), you can download it directly, but it's unofficial.

**Comment by xavisolesoft** [comment]
Thank you for your feedback!
We created a ticked to build python API for more python versions. Will fix this soon.

https://github.com/carla-simulator/carla/issues/7473
