### ISSUE TITLE
world coordinates of obstacles in Occupancygrid not match with real one

### ISSUE THREAD

**Issue by WillenPeng** [carla-simulator/carla#682]
Hi,

I tried to transfer the pixel coordinate of obstacles from topic of map into world coordinates, but I found it's not right. I set 18 as my start position index and it shows on the right lane. But after I obtain the world coordinates of obstacle and also plot start position by a simple python code.(yellow point is start position with world coordinates x = 89, y = 15) The start position shows on the left lane. I don't know whether it's due to the error accumulation?
![obstacle_minx_maxy](https://user-images.githubusercontent.com/31708131/44358961-79bf0400-a484-11e8-86d4-87c5a8533903.png)

Thanks,

**Comment by marcgpuig** [comment]
Hi @WillenPeng.
Make sure this not related to #310 #662 #680
