### ISSUE TITLE
Simulator and ROS Returns Different Player Position

### ISSUE THREAD

**Issue by hxlee309** [carla-simulator/carla#683]
Hi,

![img_1813](https://user-images.githubusercontent.com/33882690/44360480-f81da500-a488-11e8-9d6d-3ce14c716eb2.JPG)
![img_1814](https://user-images.githubusercontent.com/33882690/44360484-fc49c280-a488-11e8-9f79-e57878cd1b76.JPG)

The first image attached is about the player info we get from the simulator, and the second image attached is about the player info we get from a ROS topic called /player_vehicle. We can see that the sign of y-position is different. What might go wrong in this case?

Thank,

Hanxiang

**Comment by danil-tolkachev** [comment]
As far as I know this is due to the fact that the Carla uses left handed coordinate system, and ROS uses right handed one.

**Comment by frk1993** [comment]
Hi,

Is the coordinate system in the newest version also left-handed?

Thanks!

**Comment by werewolfdev** [comment]
@frk1993 yes CARLA still uses the UE4 left handed coordinate system
