### ISSUE TITLE
How do I import UE4 scenes into carla

### ISSUE THREAD

**Issue by kuangzh123** [carla-simulator/carla#6833]
hi,everyone
I tried to create the new scene in carla, but ran into some problems:
How to import a new map in carla? For example, I built a scene with UE4, what is the method to import this scene into carla? The UE4 can only export.fbx files, not.xodr files

**Comment by eggman-1024** [comment]
Maybe you can copy the .xdor file from other folder

**Comment by kuangzh123** [comment]
@eggman-1024 
Copy.xodr files from another folder? What I've learned is that the.xodr file must correspond to the.fbx file,the .xodr files in the other folder do not match.
