### ISSUE TITLE
LookAt Transformation form Camera Sensors

### ISSUE THREAD

**Issue by dibenedetto** [carla-simulator/carla#6839]
I didn't find a working solution for a classical camera method, known as "look-at":

https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/gluLookAt.xml

The above function takes the camera position, the point the camera is looking at, and the up vector.

Do we have a practical implementation of that?

**Comment by Blyron** [comment]
What do you want to have exactly? Possibility of getting look at sensor in Python?
