### ISSUE TITLE
Player Vehicle and Non-player Agents Not visible

### ISSUE THREAD

**Issue by ptiwari0664** [carla-simulator/carla#684]
Hello all,

I am a newbie in carla simulator. I have build carla from the source and also able to make binary out of it. 

Platform: Ubuntu 16.04 LTS
CMAKE version: 3.12.0
ROS Version: Kinetic

**Problem:** While executing the command "make launch", Unreal Engine's Editor launches and I am able to see town01 in it. However, player vehicle and other cars and pedestrians are not visible.

**Query 1:** Does anyone has a solution of it or knows how can i import player vehicle and non-player agents??
**Query 2:** How can i add already defined vehicle in the map (like tesla or mustang or truck)??
I will be glad to receive any help. Thanks in advance.

**Comment by ptiwari0664** [comment]
hi Marc,

Thanks for replying. I checked the reference which you gave. 
Yes, I am using 0.9.x version, however it seems, this version is not going to work for me as the ROS support is not there. 

Thanks.

**Comment by christianjcc** [comment]
Anyone know what the default CARLA driver model (e.g. car-following, lane-change modeling)  is based on? Are the non-player agents/vehicles based on say the Intelligent Driver Model (IDM) or Optimal Velocity Model (OVM) for car-following model? Could not track down any document explicitly describing what the AI non-player vehicles model is modeled after. Any information that can be provided is greatly appreciated.
