### ISSUE TITLE
Generating buildings and other features present in the osm file to include in xodr file.

### ISSUE THREAD

**Issue by Maheshmirje** [carla-simulator/carla#6840]

**Comment by Maheshmirje** [comment]
I need to generate buildings and other features present in the osm file to include in the xodr file. There's a github repo that does this: https://github.com/JHMeusener/osm2xodr. This only generates the road networks and produces a mesh for the road. Can we generate the buildings present in the osm file automatically via a python script or do we need to manually build using softwares such as unreal engine?

i am totally new to unreal engine so i dont know how to use it. I thought of using osmnx (github link:https://osmnx.readthedocs.io/en/stable/getting-started.html) to include the buildings and other features present in the osm file but i dont know how to use it too. Please drop your help.

**Comment by Blyron** [comment]
We have digital twin tool for this process, you can drop your osm file to the tool to generate buildings and roads
