### ISSUE TITLE
Mesh Distance Fields

### ISSUE THREAD

**Issue by zjangjeong** [carla-simulator/carla#6859]
CARLA version: 0.9.13
UE version : 4.26
Platform/OS: Windows 10

![image](https://github.com/carla-simulator/carla/assets/39556090/5c56c689-6e08-4c01-9de4-fd4cbdf06ffb)
Hi. I have an issue that turning on mesh distance fields makes this artifact like the picture above.
If mesh distance fields turned off, there will be no gradation on shadow which makes scene look non-realistic.
I want realistic AO and shadow, not the spotted one. 
Has someone any solution for this? Thanks in advance.

**Comment by Madecu** [comment]
Hi @zjangjeong 
First of all, we apologize for the delay in responding to the issues. We have been investing the majority of our resources in other tasks. However, we will now return to providing more support to the community. We apologize for any inconvenience this may have caused.

You have to disable MDF for each road mesh. We did that for all Carla Towns. Open the road mesh, find "Distance Field Resolution", set it as 0 and hit Apply Changes

![image](https://github.com/carla-simulator/carla/assets/54811869/5303a340-5b2a-41dd-9c60-bc6ffe18fa50)
