### ISSUE TITLE
Misalignment between Town10HD and Town10HD_Opt

### ISSUE THREAD

**Issue by BlueNine9** [carla-simulator/carla#6861]
CARLA version: 0.9.14
Platform/OS: Windows
Problem you have experienced: There seem to be a misalignment between the map Town10HD and Town10HD_Opt, the images are listed below.
Other information (documentation you consulted, workarounds you tried):
![image](https://github.com/carla-simulator/carla/assets/37988562/99dd4e7a-6d0c-4ef7-870d-31843178e7c5)
The misalignment happened in the red circle.
In Town10HD, there's a gap between the two buildings, but in Town10HD_Opt, the gap vanishes.
Town10HD:
![image](https://github.com/carla-simulator/carla/assets/37988562/91e18a35-df9c-45d1-a6c9-311765d5597c)
Town10HD_Opt:
![image](https://github.com/carla-simulator/carla/assets/37988562/e7651656-6f14-4b54-9f8e-bbf251d90cc0)

**Comment by RodrigoVillarias** [comment]
Thanks for the heads up and sorry for the late reply, this problem will be corrected quickly
