### ISSUE TITLE
Python packages and releases again

### ISSUE THREAD

**Issue by doganulus** [carla-simulator/carla#6897]
Thank you for the new Carla release.

Yet I see the release quality problems continue as I have brought in this issue: https://github.com/carla-simulator/carla/issues/6484 

Particularly;
- how long will you continue with Ubuntu 18.04?
- when will you support Python releases greater than 3.8 on PyPi?

These are frustration points, and unfortunately it's disappointing that this great product is in this shape when it comes to the release engineering.

**Comment by xavisolesoft** [comment]
Thank you for your feedback!
We created a ticked to build python API for more python versions. Will fix this soon.

https://github.com/carla-simulator/carla/issues/7473
