### ISSUE TITLE
Update: C++ client using Qt

### ISSUE THREAD

**Issue by p-schulz** [carla-simulator/carla#690]
Hi everyone,
due to some requests I decided to setup a Qt project containing the source files (with small fixes). This way it is also easy to wrap the code for a Qt-Widgets-Application.

It's available at: https://github.com/p-schulz/CarlaClientCpp

Some notes: 
You need to get the protobuf library and (in most cases) build it yourself. You then need to rebuild the carla_server.pb.h and carla_server.pb.cc by invoking the protobuf compiler 'protoc' for carla_server.proto. This way the protobuf version stays consistent. Finally adjust the path to your protobuf library in the protobuf.pri file.

Good luck!

**Comment by nsubiron** [comment]
Cool :)

**Comment by nsubiron** [comment]
I can't manage to connect in linux though

    connect: Transport endpoint is already connected

**Comment by p-schulz** [comment]
@nsubiron, thats weird  Are you using 0.8.2? Do you get the error at the client or the server? And what port is affected?

**Comment by nsubiron** [comment]
I tried with 0.8.4. It didn't say the port but I'm guessing was in the world port (2000). I also tried on different ports.
