### ISSUE TITLE
Can't install in Ubuntu 22.04 to 0.9.15 ver.

### ISSUE THREAD

**Issue by diaa-woo** [carla-simulator/carla#6901]
CARLA version: 0.9.15
Platform/OS: Ubuntu 22.04
Problem you have experienced: It occurred below errors during building B2 engine in make PythonAPI.

```
Setup.sh: Extracting boost for Python 3.
Building B2 engine..

A C++11 capable compiler is required for building the B2 engine.
Toolset 'clang' does not appear to support C++11.

> clang++ -x c++ -std=c++11  check_cxx11.cpp
check_cxx11.cpp:14:10: fatal error: 'thread' file not found
#include <thread>
         ^~~~~~~~
1 error generated.


** Note, the C++11 capable compiler is _only_ required for building the B2
** engine. The B2 build system allows for using any C++ level and any other
** supported language and resource in your projects.


You can specify the toolset as the argument, i.e.:
    ./build.sh [options] gcc

Toolsets supported by this script are:
    acc, clang, como, gcc, intel-darwin, intel-linux, kcc, kylix, mipspro,
    pathscale, pgi, qcc, sun, sunpro, tru64cxx, vacpp

For any toolset you can override the path to the compiler with the '--cxx'
option. You can also use additional flags for the compiler with the
'--cxxflags' option.

A special toolset; cxx, is available which is used as a fallback when a more
specific toolset is not found and the cxx command is detected. The 'cxx'
toolset will use the '--cxx' and '--cxxflags' options, if present.

Options:
    --help                  Show this help message.
    --verbose               Show messages about what this script is doing.
    --debug                 Build b2 with debug information, and no
                            optimizations.
    --guess-toolset         Print the toolset we can detect for building.
    --cxx=CXX               The compiler exec to use instead of the detected
                            compiler exec.
    --cxxflags=CXXFLAGS     The compiler flags to use in addition to the
                            flags for the detected compiler.



Failed to build B2 build engine
make: *** [Util/BuildTools/Linux.mk:142: setup] Error 1

```

In previous version, I had similar problem but I solved to change `Util/BuildTools/Linux.sh` from this #6381. But this version, I don't have ideas to it can build. I tried to install llvm-10 in Ubuntu 22.04, but it doesn't allow it. 

What should I do?

**Comment by zhengxh-git** [comment]
I have same problem
![image](https://github.com/carla-simulator/carla/assets/67199090/947f4961-1d95-4692-8dca-ac749d6d6af3)

**Comment by ABCSchuetze** [comment]
i have similar problems, but i still get an error even when i install g++-10 and clang-12 

the error i have:
`~/carla/Build/boost-1.80.0-c10-source/tools/build/src/tools/common.jam:1140: in common.find-compiler from module common
error: toolset clang-linux initialization:
error: version '10.0' requested but 'clang++-10.0' not found and version '12.0.1' of default 'clang++' does not match
error: initialized from
`

Does anyone know how to solve the problem?

Ubuntu 22.04
Carla 0.9.15

**Comment by katcinskiy** [comment]
@diaa-woo The problem is in clang - it can't find std lib, to fix it, check 

https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found

and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.

**Comment by xavisolesoft** [comment]
We added additional steps about how to build for Ubuntu22.04 in CARLA build official documentation.
Please, consider following this link from now to build CARLA for Ubuntu 22.04:
[](https://carla.readthedocs.io/en/latest/build_linux/)

**Comment by xavisolesoft** [comment]
We added additional steps about how to build for Ubuntu22.04 in CARLA build official documentation.
Please, consider following this link from now to build CARLA for Ubuntu 22.04:
[https://carla.readthedocs.io/en/latest/build_linux/](https://carla.readthedocs.io/en/latest/build_linux/)

**Comment by xavisolesoft** [comment]
We added additional steps about how to build for Ubuntu22.04 in CARLA build official documentation.
Please, consider following this link from now to build CARLA for Ubuntu 22.04:
[https://carla.readthedocs.io/en/latest/build_linux/](https://carla.readthedocs.io/en/latest/build_linux/)

**Comment by Billthekidz** [comment]
> @diaa-woo Your solution did not help me, here my way to fix it.
> 
> The problem is in clang - it can't find std lib, to fix it, check
> 
> https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> 
> and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.

Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang. 
```
clang -v
```
Based on the output, we know that clang is selecting g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. 
We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.

**Comment by hotmedal** [comment]
> > @diaa-woo Your solution did not help me, here my way to fix it.
> > The problem is in clang - it can't find std lib, to fix it, check
> > https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> > and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.
> 
> Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang.
> 
> ```
> clang -v
> ```
> 
> Based on the output, we know that clang is selecting gcc/g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.

`sudo apt install g++-12`  should be in the official instructions. It worked for me.

**Comment by xavisolesoft** [comment]
> > > @diaa-woo Your solution did not help me, here my way to fix it.
> > > The problem is in clang - it can't find std lib, to fix it, check
> > > https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> > > and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.
> > 
> > 
> > Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang.
> > ```
> > clang -v
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Based on the output, we know that clang is selecting gcc/g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.
> 
> `sudo apt install g++-12` should be in the official instructions. It worked for me.

Thank you for sharing it.

Note that we are already installing g++-7 in the official instructions to maintain the same official toolchain for all Ubuntu versions. As you can see in the next snapshot, g++7 also contains libstdc++.a:
![image](https://github.com/carla-simulator/carla/assets/20727166/8afc050f-f0f5-466d-86d3-ba2886cd83e7)

**Comment by JQUP20** [comment]
> > > @diaa-woo Your solution did not help me, here my way to fix it.
> > > The problem is in clang - it can't find std lib, to fix it, check
> > > https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> > > and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.
> > 
> > 
> > Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang.
> > ```
> > clang -v
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Based on the output, we know that clang is selecting gcc/g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.
> 
> `sudo apt install g++-12` should be in the official instructions. It worked for me.

Good job,it works.

**Comment by donghaiwang** [comment]
I have similar problems when i install corresponding g++ version in Ubuntu 24.04.

**Comment by CaMi1le** [comment]
> > > > @diaa-woo Your solution did not help me, here my way to fix it.
> > > > The problem is in clang - it can't find std lib, to fix it, check
> > > > https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> > > > and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.
> > > 
> > > 
> > > Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang.
> > > ```
> > > clang -v
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Based on the output, we know that clang is selecting gcc/g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.
> > 
> > 
> > `sudo apt install g++-12` should be in the official instructions. It worked for me.
> 
> Thank you for sharing it.
> 
> Note that we are already installing g++-7 in the official instructions to maintain the same official toolchain for all Ubuntu versions. As you can see in the next snapshot, g++7 also contains libstdc++.a: ![image](https://private-user-images.githubusercontent.com/20727166/305357497-8afc050f-f0f5-466d-86d3-ba2886cd83e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTA1NDYsIm5iZiI6MTcyOTQ5MDI0NiwicGF0aCI6Ii8yMDcyNzE2Ni8zMDUzNTc0OTctOGFmYzA1MGYtZjBmNS00NjZkLTg2ZDMtYmEyODg2Y2Q4M2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA1NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDMzY2JhZmUwMjJkNzI3ZDA3Yzk3YmFjYTA0YzQ0YjIzMzE1NGVkZGYwYTZiNmNlZmI3MzI3NjZmYzI5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CEA_HIsIW2DQwlWg4IV1NLpT6zFf6HYhZQUoQuyX55Y)

it turns out by 2024/10/21, the Ubuntu 22.04 user following the official guide still have to look back to this issue and use `sudo apt install g++-12` , maybe add a line to tutorial will help, saving 30 mins of time.

**Comment by RandyWangRaining** [comment]
> > > > > [@diaa-woo](https://github.com/diaa-woo) Your solution did not help me, here my way to fix it.
> > > > > The problem is in clang - it can't find std lib, to fix it, check
> > > > > https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> > > > > and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.
> > > > 
> > > > 
> > > > Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang.
> > > > ```
> > > > clang -v
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Based on the output, we know that clang is selecting gcc/g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.
> > > 
> > > 
> > > `sudo apt install g++-12` should be in the official instructions. It worked for me.
> > 
> > 
> > Thank you for sharing it.
> > Note that we are already installing g++-7 in the official instructions to maintain the same official toolchain for all Ubuntu versions. As you can see in the next snapshot, g++7 also contains libstdc++.a: ![image](https://private-user-images.githubusercontent.com/20727166/305357497-8afc050f-f0f5-466d-86d3-ba2886cd83e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTA1NDYsIm5iZiI6MTcyOTQ5MDI0NiwicGF0aCI6Ii8yMDcyNzE2Ni8zMDUzNTc0OTctOGFmYzA1MGYtZjBmNS00NjZkLTg2ZDMtYmEyODg2Y2Q4M2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA1NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDMzY2JhZmUwMjJkNzI3ZDA3Yzk3YmFjYTA0YzQ0YjIzMzE1NGVkZGYwYTZiNmNlZmI3MzI3NjZmYzI5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CEA_HIsIW2DQwlWg4IV1NLpT6zFf6HYhZQUoQuyX55Y)
> 
> it turns out by 2024/10/21, the Ubuntu 22.04 user following the official guide still have to look back to this issue and use `sudo apt install g++-12` , maybe add a line to tutorial will help, saving 30 mins of time.

20.04also helps

**Comment by Cynthia11281128** [comment]
> > [@diaa-woo](https://github.com/diaa-woo) Your solution did not help me, here my way to fix it.
> > The problem is in clang - it can't find std lib, to fix it, check
> > https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> > and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.
> 
> Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang.
> 
> ```
> clang -v
> ```
> 
> Based on the output, we know that clang is selecting gcc/g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.

I an using g++-13, and this also works for me! Thanks!

**Comment by pdaelm** [comment]
I had the problem with carla 0.9.15 on a fresh install of ubuntu 20.04.

`
Setup.sh: Extracting boost for Python 3.
Building B2 engine..

A C++11 capable compiler is required for building the B2 engine.
Toolset 'clang' does not appear to support C++11.

> clang++ -x c++ -std=c++11  check_cxx11.cpp
check_cxx11.cpp:14:10: fatal error: 'thread' file not found
#include <thread>
`


Removing g++13 so clang cannot select it, as libstdc++ latest version is 11 on ubuntu 20.04 ...
thx @katcinskiy !

**Comment by zt282** [comment]
> > > > > [@diaa-woo](https://github.com/diaa-woo) Your solution did not help me, here my way to fix it.
> > > > > The problem is in clang - it can't find std lib, to fix it, check
> > > > > https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found
> > > > > and delete folder under "Selected GCC installation:" if it does not contain libstdc++.a file. After these steps you will be able to run it.
> > > > 
> > > > 
> > > > Thank you for providing the link. We resolve the issue by finding out the g++/gcc version being used by clang.
> > > > ```
> > > > clang -v
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Based on the output, we know that clang is selecting gcc/g++ version 12. Then we found out our installation of version 12 does not have `libstdc++.a` in `/usr/lib/gcc/x86_64-linux-gnu/12`. We resolved it using `sudo apt install g++-12` that installs `libstdc++.a` to the folder.
> > > 
> > > 
> > > `sudo apt install g++-12` should be in the official instructions. It worked for me.
> > 
> > 
> > Thank you for sharing it.
> > Note that we are already installing g++-7 in the official instructions to maintain the same official toolchain for all Ubuntu versions. As you can see in the next snapshot, g++7 also contains libstdc++.a: ![image](https://private-user-images.githubusercontent.com/20727166/305357497-8afc050f-f0f5-466d-86d3-ba2886cd83e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTA1NDYsIm5iZiI6MTcyOTQ5MDI0NiwicGF0aCI6Ii8yMDcyNzE2Ni8zMDUzNTc0OTctOGFmYzA1MGYtZjBmNS00NjZkLTg2ZDMtYmEyODg2Y2Q4M2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA1NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDMzY2JhZmUwMjJkNzI3ZDA3Yzk3YmFjYTA0YzQ0YjIzMzE1NGVkZGYwYTZiNmNlZmI3MzI3NjZmYzI5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CEA_HIsIW2DQwlWg4IV1NLpT6zFf6HYhZQUoQuyX55Y)
> 
> it turns out by 2024/10/21, the Ubuntu 22.04 user following the official guide still have to look back to this issue and use `sudo apt install g++-12` , maybe add a line to tutorial will help, saving 30 mins of time.

in2025.05.14 we still need that

**Comment by PabloVD** [comment]
I also needed to set consistent clang and g++ versions using `update-alternatives`:

```
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-10/bin/clang++ 180 &&
sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-10/bin/clang 180 &&
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 180
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100
```

**Comment by jiehelin** [comment]
2025-8-28
clang -12 and gcc instructions are still not included in the documentation. The first few commands may be fatally misleading to users.

<img width="739" height="243" alt="Image" src="https://github.com/user-attachments/assets/98c11582-7485-4171-8a3d-c133a93bac24" />

**Comment by JiBingdong** [comment]
我发现Setup.sh使用的UE4.26自带的Clang10.0，所以只要我们把UE4的路径设置正确，就完全可以避免Clang 12 和Clang 10的冲突问题。So，open your .bashrc file, then:
export UE4_ROOT=/home/ubuntu/UnrealEngine_4.26
export CARLA_UE4_ROOT=/home/ubuntu/carla
