### ISSUE TITLE
Semantic segmenation raws labels are not coherent with the documentation

### ISSUE THREAD

**Issue by NnaYelsel** [carla-simulator/carla#6902]
_CARLA version_: 0.9.14
_Platform/OS_: Windows
_Problem you have experienced:_
By saving the semantic segmentation label into npy, I didn't get the label value written in the documentation: https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-segmentation-camera but those from https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/image/CityScapesPalette.h 

Example: label of the road is 1 and not 7 in my case.

These when, I use a basic function labels_to_cityscapes_palettes in python (ex: https://github.com/carla-simulator/data-collector/blob/master/carla/image_converter.py) the colors are wrong

_Steps to reproduce:_
np_image = np.reshape(np.copy(data.raw_data), (data.height, data.width, 4))
label = np_image[:, :, 2] # class Id is stored in B channel
np.save(npy_file, label)

Then, do we agree that the labels of the raw data are not those of the cityscape palette or did I miss something ?

**Comment by yyxssm** [comment]
The same question to me, I think the documentation has not been updated.

I choose to use the label in [https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/image/CityScapesPalette.h](url)

**Comment by qhaas** [comment]
Noticed this as well in 0.9.15, 11 is sky and 14 is vehicle, which differs from the documentation.

I do like [this comment](https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/image/CityScapesPalette.h#L19)
`// Please update documentation if you change this.`

**Comment by dorn-gerhard** [comment]
I just experienced the same issue - I just made a pull request PR #7112 (https://github.com/carla-simulator/carla/pull/7112) to update the docs.
Here you can find the new labels including color code:

https://github.com/carla-simulator/carla/blob/d7b45c1e159e6d13296f7a3a4e8b13e6c2d62c18/LibCarla/source/carla/image/CityScapesPalette.h#L35

Hope that helps :)
