### ISSUE TITLE
Support newer python versions

### ISSUE THREAD

**Issue by CRD716** [carla-simulator/carla#6903]
The latest version of python supported by CARLA is stated to be python 3.8, however this version of python is EOS and no longer even has a released installer. Many improvements have been made in newer python versions that would help performance. In my opinion, it makes zero sense to continue developing for a dead version of python.

**Comment by MattRoweEAIF** [comment]
Thank you for your comments, we now have updated the wheels so that version 0.9.15 supports Python versions 3.9 and 3.10. 3.11 will come soon.
