### ISSUE TITLE
Custom Map ingestion offsets map origin

### ISSUE THREAD

**Issue by aamzhas** [carla-simulator/carla#6919]
CARLA version: 0.9.13
Platform/OS: Ubuntu 22.04
Problem you have experienced: 
I'm running the sumo synchronized co-simulation with a custom map. 

I made the map in roadrunner - 
its a simple ring/circle of radius 100m centered at (0,0) -> the edges are at (100,0), (-100, 0), (0, 100), (0, -100).
 
After ingesting using the docker method, I noticed that the map is offset - the center of the circle is no longer at (0, 0) and but one the edges is now at (0, 0) -> essentially the map as a whole is offset by about 100m. 

The offset is throwing off the velocity calculation which is leading to different velocities in sumo and carla and messing with metrics. 

What you expected to happen:
Circle would still be centered at (0, 0) and not offset.

**Comment by RodrigoVillarias** [comment]
Hi, have you checked if the Location of the Transform is all at 0,0,0 and there is no yellow arrow on the border?

![Captura de pantalla 2024-04-26 125709](https://github.com/carla-simulator/carla/assets/86314729/4b738807-db0d-45e1-8a68-7cad3443799e)
