### ISSUE TITLE
Plugin 'CarlaTools' failed to load because module 'CarlaTools' could not be loaded: make launch issue

### ISSUE THREAD

**Issue by saitejeswar1** [carla-simulator/carla#6926]
CARLA version: 0.9.15
Platform/OS: Windows 10
Problem you have experienced: not able to launch carla after building it from source
What you expected to happen: Carla should open
Steps to reproduce: Follow the documentation and if error occurs in cmake then check the issue #6898 
Other information (documentation you consulted, workarounds you tried): #6898 

@Lyanyv do you have any suggestions for this?

![image](https://github.com/carla-simulator/carla/assets/80686447/24c8f421-785f-4cff-8715-d8c01a8531ea)

**Comment by Lyanyv** [comment]
Sorry, but i didn't encounter this issue and have no idea...

**Comment by chirudeep001** [comment]
I got this issue when i removed the Houdini engine plugin and restarted the unreal engine

**Comment by SUEN18** [comment]
I have this problem too

**Comment by javageek68** [comment]
Has anyone found a solution for this?  Or at least have an idea on how to troubleshoot it?  Does Unreal create logs for plugins it fails to load?

**Comment by mhvicom** [comment]
I am currently having this issue too.
OS: Windows 11

**Comment by OYan60718** [comment]
Same problem
Windows 11, Carla 0.9.15, VS 2019

**Comment by teoctopus** [comment]
Try to check the file libsqlite3.so, I replaced the file downloaded from the official website and it doesn't report this error

**Comment by teoctopus** [comment]
> Try to check the file libsqlite3.so, I replaced the file downloaded from the official website and it doesn't report this error

carla/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/lib/libsqlite3.so

**Comment by l-show** [comment]
> > Try to check the file libsqlite3.so, I replaced the file downloaded from the official website and it doesn't report this error
> 
> carla/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/lib/libsqlite3.so

I also encountered the same problem, but I couldn't find the document you mentioned either myself or the official document

**Comment by l-show** [comment]
<img width="696" height="256" alt="Image" src="https://github.com/user-attachments/assets/0bc72f18-4d0d-4542-85c4-891d4e38ba5e" />
