### ISSUE TITLE
Compute the 3D Bounding box orientation

### ISSUE THREAD

**Issue by sergiosanchoasensio** [carla-simulator/carla#693]
Hi everyone!,

I am trying to get the bounding box of each vehicle. So far, I have computed each point (this is: 8 points for a 3D bounding box) individually using the following code:

```
if agent.HasField('vehicle'):
                    pos = agent.vehicle.transform.location                    
                    
                    bbox3d = agent.vehicle.bounding_box.extent

                    # Compute the 3D bounding boxes
                    # f contains the 4 points that corresponds to the bottom
                    f = np.array([[[pos.x + bbox3d.x], [pos.y - bbox3d.y], [pos.z], [1.0]],
                                 [[pos.x + bbox3d.x], [pos.y + bbox3d.y], [pos.z], [1.0]],
                                 [[pos.x - bbox3d.x], [pos.y + bbox3d.y], [pos.z], [1.0]],
                                [[pos.x - bbox3d.x], [pos.y - bbox3d.y], [pos.z], [1.0]]])
    
                    # u contains the 4 points that corresponds to the top
                    u = np.array([[[pos.x + bbox3d.x], [pos.y - bbox3d.y], [pos.z + bbox3d.z], [1.0]],
                                 [[pos.x + bbox3d.x], [pos.y + bbox3d.y], [pos.z + bbox3d.z], [1.0]],
                                 [[pos.x - bbox3d.x], [pos.y + bbox3d.y], [pos.z + bbox3d.z], [1.0]],
                                 [[pos.x - bbox3d.x], [pos.y - bbox3d.y], [pos.z + bbox3d.z], [1.0]]])  
```

The problem that I have now is the following one: when a car changes its orientation, the bounding box should update, but it does not. So my question is, how can I solve this issue? I have seen that one can use: agent.vehicle.transform.rotation and agent.vehicle.transform.orientation (which seems deprecated), but I am not sure what is the right way to apply the transformation to these points.

Thank you!

EDIT:

I solved it by simply computing the vehicle transform:

`vehicle_transform = Transform(agent.vehicle.transform)`

And computing the transform for each point using:

`vehicle_transform.transform_points(points)`

**Comment by mhusseinsh** [comment]
@sergiosanchoasensio Hello Sergio, and then where do you use this transform afterwards ?
