### ISSUE TITLE
Semantic information: assign a different class per object

### ISSUE THREAD

**Issue by sergiosanchoasensio** [carla-simulator/carla#694]
Hello all,

For research purposes, I would need to modify the given semantic information, since it provides 12 semantic classes and my project requires a different color or class for each object. For example, each vehicle uses [0, 0, 255] color, can I use a different color for each vehicle?

Is possible to develop a Python client for that purposes or do I need to modify the project from the Unreal Engine?

Thank you! :)

**Comment by marcgpuig** [comment]
Hi @sergiosanchoasensio.
There is an open discussion in #76.
Try to read it and check if there is something that you can implement.
