### ISSUE TITLE
Support for map creation based on HERE or TomTom HD maps

### ISSUE THREAD

**Issue by ghazalmatt3r** [carla-simulator/carla#6945]
Hi!

I was wondering if you have plans to add the ability to create real-world maps from sources other than OpenStreetMap.

As you may be aware, there are instances where OpenStreetMap contains incomplete or inaccurate data, which affects the quality of the generated map. Other high-definition map sources, such as [HERE](https://www.here.com/) or [TOMTOM](https://www.tomtom.com/), are more accurate and can improve the fidelity of generated maps in simulation. 
I was wondering if you have any plans to add this functionality in the future?

Thank you very much!

**Comment by Blyron** [comment]
For now we are sticking with opensource basedatas and formats, that's why we are sticking with OSM for now. So, currently there is no plans for it
