### ISSUE TITLE
Why we must transform from UE4 coordinate system to a "standard" one (x,y,z) -> (y, -z, x)

### ISSUE THREAD

**Issue by littlevu** [carla-simulator/carla#6948]
Hi everyone,

I am investigating to get vehicle's bounding boxes from script client_bounding_boxes.py in PythonAPI/examples/client_bounding_boxes.py. My confuse in line 128:

```
# Now we must change from UE4's coordinate system to a "standard" one (x, y ,z) -> (y, -z, x)
cords_y_minus_z_x = np.concatenate([cords_x_y_z[1, :], -cords_x_y_z[2, :], cords_x_y_z[0, :]]) 
```

My question is:
1/ what is the standard coordinate system? Is this right-handed coordinate system?
2/ why transform (x, y, z) to (y, -z, x), i really don't understand why carla do this. 
3/ If standard coordinate system is right-handed coordinate system, the transformation should be (x, y, z) -> (x, -y, z) and rotation 90 degrees, right?

Thank you all,

**Comment by datvuthanh** [comment]
Converts the 3D object location from CARLA coordinates and saves them as KITTI coordinates in the object
            In Unreal, the coordinate system of the engine is defined as, which is the same as the lidar points
            z
            ▲   ▲ x
            |  /
            | /
            |/____> y
            This is a left-handed coordinate system, with x being forward, y to the right and z up 
            See also https://github.com/carla-simulator/carla/issues/498
            However, the camera coordinate system for KITTI is defined as
                ▲ z
               /
              /
             /____> x
            |
            |
            |
            ▼
            y 
            This is a right-handed coordinate system with z being forward, x to the right and y down
            Therefore, we have to make the following changes from Carla to Kitti
            Carla: X   Y   Z
            KITTI: Y  -Z   X
