### ISSUE TITLE
CARLA UE4  Not responding 

### ISSUE THREAD

**Issue by hossam-elsayed** [carla-simulator/carla#6949]
CarlaUE4-Win64-Shipping.exe is going to be Not responding every time after launching : 
roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch host:=192.168.1.140 timeout:=60000 town:='Town03' spawn_point:=-25,-134,0.5,0,0,-90
 
![image](https://github.com/carla-simulator/carla/assets/28265450/1df7cbba-ed84-46ce-8c17-5dfda9235bec)

**Comment by LuisPoveda** [comment]
We know there is a bug in town3 and we are currently working on it, for the next release it will be fixed.
