### ISSUE TITLE
OSM browser

### ISSUE THREAD

**Issue by ravagl94** [carla-simulator/carla#6951]
CARLA version: 0.9.15

Platform/OS: ubuntu 22.04

Problem you have experienced:
Currently trying to use the Procedural Building Generation, from the documentation it is unclear on how to access the OSM browser, could more information be shared? 

What you expected to happen:
Steps to reproduce:
Other information (documentation you consulted, workarounds you tried):
https://carla.readthedocs.io/en/0.9.15/adv_digital_twin/

If you are asking a question please make sure your question was not asked before
by searching among the existing issues and checking the CARLA forum https://github.com/carla-simulator/carla/discussions. Also make sure you have read our documentation and FAQ at http://carla.readthedocs.io. 

If your question is about creating content (assets, levels) you'll most likely
have all the info you need in the Unreal Engine's documentation
https://docs.unrealengine.com

Please, keep the threads focused and single-themed. Make them easy to find
for everyone.

-->

**Comment by filipthoen2** [comment]
@ravagl94 - see https://github.com/carla-simulator/carla/issues/6927 ticket, which explains the steps on how to access the OSM browser (the steps are for Windows, but I expect them to be identical on ubuntu).
