### ISSUE TITLE
Issues About Move Spectator Freely in the Replay

### ISSUE THREAD

**Issue by zyan003** [carla-simulator/carla#6955]
CARLA version: 0.9.14
Platform/OS: Windows 10
Problem you have experienced: The spectator cannot be moved during replay using the mouse and keyboard
What you expected to happen: Move the spectator freely during the replay

Hi, I am trying to move the spectator during replay in CARLA 0.9.14 and I realize that `set_replayer_ignore_spectator` is no longer available. Here is part of my code and camera is set to `0`:

```
client = carla.Client('localhost', 2000)
client.set_timeout(10.0)
start = 0
duration = 0
camera = 0
client.set_replayer_ignore_spectator(True)
# client.set_replayer_ignore_hero(True)

client.replay_file(selectedReplayFile, start, duration, camera)
```
Is there any way I can move the spectator during replay? Thank you very much!

**Comment by Blyron** [comment]
Hey I have been able to repro your bug and we are aware of it... I have found in my case if i do not call client.set_replayer_ignore_spectator(True) it is ignored by default. Is strange behaviour we will look at it
