### ISSUE TITLE
Digital twin map generation crash

### ISSUE THREAD

**Issue by AbdelrhmanRady** [carla-simulator/carla#6979]
My team wants to build a map for our campus(which is not realtively big at all)  using the new digital twin application for a graduation project, we've been trying for weeks to get it running, on linux/windows with different computers (with good specs), the output is always the same, the unreal engine crashes at the end with no usable output

We followed the documentation(https://carla.readthedocs.io/en/latest/adv_digital_twin/#digital-twin-tool)  carefully and thoroughly, so If there's someone who managed to get it running we would appreciate any tips or tricks

**Comment by dylanyd** [comment]
I also got the unreal engine crash when I tried to generate the map from OpenStreetMap URL, I got the following error:
![image](https://github.com/carla-simulator/carla/assets/60207837/8ecbf508-c938-4bd3-bfe6-e365074c97bb)

**Comment by Blyron** [comment]
It should be fixed now with latest dev version.
