### ISSUE TITLE
Cannot change the vehicle color of  micro.microlino

### ISSUE THREAD

**Issue by yhh-IV** [carla-simulator/carla#6983]
CARLA version: 0.9.15
Platform/OS: Windows

I tried to use set_attribute('color', '0, 0, 0') to change the body color of vehicle micro.microlino, however, the color is always the blue. 
![Weixin Image_20231207200020](https://github.com/carla-simulator/carla/assets/89769935/a22943f1-6d12-44c4-aa53-7459ac4f6ed8)

I found its color can be changed in one paper, so, how can I change the vehicle body color of micro.microlino.
![Weixin Image_20231207200414](https://github.com/carla-simulator/carla/assets/89769935/9aea180a-a249-4e3a-bb82-f0001846e6d4)

Many thanks for the help!!

**Comment by Madecu** [comment]
Hi @yhh-IV ,

First of all, we apologize for the delay in responding to the issues. We have been investing the majority of our resources in other tasks. However, we will now return to providing more support to the community. We apologize for any inconvenience this may have caused.

Microlino is a car from the early generations, and we hadn't modified the material slot name. We have now corrected this. Thank you very much for addressing the issue.

**Comment by yhh-IV** [comment]
Thanks very much for your help! Many thanks!
