### ISSUE TITLE
Bounding box for truncated vehicles

### ISSUE THREAD

**Issue by ghost** [carla-simulator/carla#6985]
Hi guys, 

I'm in the process of drawing the 2D bounding boxes in the simulator. For this I used client_bounding_boxes.py. I've noticed that the bounding boxes of cropped vehicles become extremely enlarged as they leave the image frame. If the vehicle is too far from the ego vehicle, this problem does not exist. But when the objects especially drive past the ego vehicle and are very close to the camera, I have this problem. What should I change in client_bounding_boxes.py to solve this problem? thanks in advance

![000085](https://github.com/carla-simulator/carla/assets/73448622/89864219-3753-4cb8-9162-2abbd2267279)
![000110](https://github.com/carla-simulator/carla/assets/73448622/d70da65f-b83f-4a7a-ad7c-627c06d1fd9c)

**Comment by Madecu** [comment]
Hi,
This issue has been resolved by a user in this commit  #6630. It has already been merged into the dev branch. I hope this helps.

Thank you.
