### ISSUE TITLE
A custom map created in RoadRunner cannot generate Route Planner instances around junctions when importing

### ISSUE THREAD

**Issue by RealCntAyumu** [carla-simulator/carla#6987]
CARLA version: 0.9.15(I also tried in 0.9.13 & 0.9.14)
Platform/OS: Ubuntu 20.04
Python version: 3.7.17
Problem you have experienced: A custom map created in roadrunner cannot generate Route Planner instances around junctions. 
What you expected to happen: Route Planner instances around junctions would be generated when importing. 

Hi carla community, I'm trying to import a custom map in carla. The map is created in Road Runner to define the OpenDRIVE network with the road mesh models. When I import it, only the network around the junctions cannot be generated.
I tried a multiple way to import the map according to[ this page](https://carla.readthedocs.io/en/0.9.15/tuto_M_add_map_source/) of the carla documents. However, for all ways, the Route Planner around the junctions are not generated. 
This is the picture of the map in carla below.
![naha_test2_routes](https://github.com/carla-simulator/carla/assets/95387137/01741f56-ea17-43a6-aba7-3f086baa5aec)
The OpenDRIVE network seems to be defined without any problem but since this is Japanese roads map where a car goes in the left lane, there may be something I couldn't notice to import the map properly. 
A junciton in the OpenDRIVE map in Online OpenDrive Viewer looks like below. 
![openDRIVE map](https://github.com/carla-simulator/carla/assets/95387137/85832d9e-94fa-486e-95db-7284b967cdcf)

It used to generate the route planner instances in junctions too BEFORE I redefine the network but since the network is messed up and not perfect, I defined the openDRIVE routes in Road Runner as it supposed to be and export it again as .fbx and .xodr. After that, when I import these files in carla, it loses the route planner instances. 
This is the picture of the map in carla BEFORE I fix the openDRIVE network in Road Runner. 
![map_before_fixing](https://github.com/carla-simulator/carla/assets/95387137/6fa42f7b-116a-45d0-9c73-8f0bbc1bc571)

I'm not sure that this error happens due to the bad creation of the Road Runner map or options when exporting, if anyone tries the custom map importing in carla and know tips to resolve this issue, I would very appreciate your help. Thank you in advance.

**Comment by ronyshaji** [comment]
@RealCntAyumu Did you found out a solution why some parts of OpenDRIVE are missing ?

**Comment by RealCntAyumu** [comment]
> @RealCntAyumu Did you found out a solution why some parts of OpenDRIVE are missing ?

No, I couldn't. I think it's because the map is based on left-lane roads. I could import right-lane roads map.

**Comment by leilai125** [comment]
Hello, may I ask how you created such a large map in RoadRunner? Do you create the map manually, or do you use some automated process or code to generate it? If it's the latter, could you kindly share any tutorials or resources on how to do so? Thank you very much!
