### ISSUE TITLE
Question about extract steering angle from manul control

### ISSUE THREAD

**Issue by NYJiaxing** [carla-simulator/carla#699]
Hello All,

I have a question about extract the steering angle when I manually control the vehicle. From other contributors, I know that the range of the manual control by the keyboard is **[-1, +1]** but this is not actual angle value that I can save for further learning and output. Secondly, I just fully read the paper: CARLA: An Open Urban Driving Simulator, in the article, the MP method mentioned that the steering angle controlled via **PID algorithm**, so I believe there must be a two digit number that I can expect lol. 

- Could you please tell me where to get this angle? Like the **measurements, sensor_data = self.client.read_data()** function in the client class.

- My second question is in the article you mentioned I can extract following information from Carla server,

**Non-Client-Controlled agents information:** The positions, orientations and bounding boxes
for all pedestrians and cars present in the environment.
**Traffic Lights information:** The position and state of all traffic lights.
**Speed Limit Signs information**: Position and readings from all speed limit signs.

Could you please provide sample code that can help extract this information?

Thank you so much for your reply.

**Comment by p-schulz** [comment]
@NYJiaxing 
you can easily create a control message, where you can **set** a steering value [-1, +1]. The actual steering angle depends on the selected vehicle, you can get the maximum angles in the front wheel blueprint of a vehicle (default Mustang is 70°). 
But I don't know if there's a field for retrieving the steering angle while manually controlling a player.

**Comment by link-er** [comment]
@felipecode  @marcgpuig  @p-schulz  my question is related to the current issue - do I understand correctly that if I want to transform steering angle to degrees value I should simply multiply it by 70 (at least for default Mustang)? And how can I access the values for other cars (where is the Blueprint information)? Thanks!

**Comment by chengjinjack** [comment]
Hello, everyone!
How can I get the steering angle?

**Comment by sheelabhadra** [comment]
Hi @JackRen88, were you able to figure out a way to obtain the current wheel angle?
