### ISSUE TITLE
Implementing a new vehicle type

### ISSUE THREAD

**Issue by HykeLuka** [carla-simulator/carla#6996]
Hi!
I am implementing a new vehicle type in carla which is different from 4 or 2 - wheeled vehicles available now.
I have managed to create duplicate classes of anything related to a carla vehicle class both on client and server side and everything builds ok with stub functions.

I am getting lost when it comes to implementing dynamics for the new class. Following carla's code leads me deep into physx vehicle code which I am not really interested in using.

My question is, if I have a custom class which is on the same level as CarlaWheeledVehicle, but instead of deriving from physx's wheeledvehicle it derives directly from pawn, is it ok to use the Pawn's Tick function for handling the custom vehicles dynamics? Can I directly use unreals physics to apply forces to the object? Would this be compatible with syncronous mode?

Thanks for any help!

**Comment by Blyron** [comment]
Unreal Physics depends directly on PhysX for UE4 and on Chaos for UE5.
If you want to create own dynamics stuff, try to follow Code like our Chrono bridge.  
But it won't be easy.  Yeah everything should be sync mode compatible as sync makes python wait for pythonapi and then UE wait for python
