### ISSUE TITLE
Pedestrians crash against stopped cars

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#7]
Consequence of #6

**Comment by juaxix** [comment]
fixed in Commit: a2a6105c0ec5853e1ac81eb97a6657c4ded046c3 [a2a6105]

**Comment by juaxix** [comment]
Another problem related to this is the way the pedestrian detects vehicles in the world. The perception angle is too wide sometimes so they could be walking inside the road and detects a car, thus making the walker to stop and wait 10 seconds until the next decision makes the vehicle to wait for the walker.

**Comment by germanros1987** [comment]
Related to this, pedestrians tend to stand by cars and then die dramatically.

**Comment by juaxix** [comment]
Yes, that's what I was explaining in the issue #381 ,a game design decision is involved at this moment

**Comment by nsubiron** [comment]
No longer relevant, pedestrians are now controlled from client-side.
