### ISSUE TITLE
Is it possible to build it on CentOS VM or physical machine

### ISSUE THREAD

**Issue by yiakwy** [carla-simulator/carla#70]
Most Cloud infrastructure providers suggest companies to build their servies on CentOS VMs. And most of our teams resources of machine are of CentOS. We want to build them on CentOS based machine (docker image is also welcome) without touching VitualBox or VMware. Is it possible?

**Comment by felipecode** [comment]
Hello @yiakwy 
Currently no compilation was  tested on CentOS. 
However since unreal engine also works for CentOS, maybe you are able to
compile without any major problems. 
We really would like to hear about your progress on that !
Cheers.

**Comment by yiakwy** [comment]
@felipecode Thanks for your reply! I will work on it.
