### ISSUE TITLE
Cannot build the Unreal Engine 4.26 Carla branch from source files

### ISSUE THREAD

**Issue by Zhenlin-Xu** [carla-simulator/carla#7008]
CARLA version: 0.9.15
Platform/OS: Windows 10
Problem you have experienced: Cannot build the Unreal Engine 4.26 from source files.
What you expected to happen: I hope to compile the UE4 from source files.
Steps to reproduce: I just run the two .bat scripts and build the UE4 project in Visual Studio 2019 as the documentation instructs.
Other information (documentation you consulted, workarounds you tried):

Hello! I am trying to compile the UE4.26 from scratch. However, there are some errors when I try to compile it.

I am using the official repository provided in the CARLA documentation:
```
git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git .
```

Here is the error I encounter:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2487	'SpillCellID': member of dll interface class may not be declared with dll interface	UE4	
U:\UnrealEngine\Engine\Plugins\Experimental\GeometryProcessing\Source\GeometricObjects\Public\Spatial\SparseDynamicOctree3.h	291	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 6.	UE4	
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets	45	
```

![image](https://github.com/carla-simulator/carla/assets/86121429/973a31b7-b4d6-470a-b0dc-c8e0c873bcac)

**Comment by ronyshaji** [comment]
@Zhenlin-Xu I am facing the same issue. Did you get any resolution?

**Comment by Zhenlin-Xu** [comment]
Nop.

**Comment by ronyshaji** [comment]
@Zhenlin-Xu I think the Unreal Engine source code has been changed from the repo, and it no longer builds with the new branch. Maybe it's a bug. Can you add the bug tag to this post so that somebody checks it?

**Comment by Zhenlin-Xu** [comment]
I think only the contributor of the repo can add a tag/label to the issue. Am I correct or is there another way to add the label by myself.

**Comment by ronyshaji** [comment]
@germanros1987 Can you please have a look into this issue?

**Comment by Patrone411** [comment]
haveing the exact same issue.

**Comment by andrejfsantos4** [comment]
I have the same issue.

A temporary workaround which seems to work for me is to revert one of the changes in [this commit](https://github.com/CarlaUnreal/UnrealEngine/commit/c48d13957dd607bd6f42dde61140c70ec4eca24e):
Change the line 138 of _Engine/Plugins/Experimental/GeometryProcessing/Source/GeometricObjects/Public/Spatial/SparseDynamicOctree3.h_ from
`class GEOMETRICOBJECTS_API FSparseDynamicOctree3`
back to
`class FSparseDynamicOctree3`

However I face other issues when trying to build the CARLA server, as mentioned in #7012.

**Comment by Blyron** [comment]
We are aware of this we should be fixing soon

**Comment by chirudeep001** [comment]
@andrejfsantos4  The issue was resolved after 
Change the line 138 of Engine/Plugins/Experimental/GeometryProcessing/Source/GeometricObjects/Public/Spatial/SparseDynamicOctree3.h from
class GEOMETRICOBJECTS_API FSparseDynamicOctree3
back to
class FSparseDynamicOctree3


but i am encountering new error when i do make pythonAPI

**Comment by andrejfsantos4** [comment]
> @andrejfsantos4 @Blyron The issue was resolved after Change the line 138 of Engine/Plugins/Experimental/GeometryProcessing/Source/GeometricObjects/Public/Spatial/SparseDynamicOctree3.h from class GEOMETRICOBJECTS_API FSparseDynamicOctree3 back to class FSparseDynamicOctree3
> 
> but i am encountering new error when i do make pythonAPI

@chirudeep001 Sorry, for my application I just installed the client with `pip install carla` since I don't need to make custom changes to it, so I can't help you there

**Comment by Blyron** [comment]
Should be fixed now with the merge of 
https://github.com/CarlaUnreal/UnrealEngine/pull/16 into Engine code

**Comment by ronyshaji** [comment]
@Zhenlin-Xu It's building now. You can close the issue.

**Comment by Bniultu** [comment]
Hi ,all .
when i installation Carla editor there has some error can any one help me with that.
(>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5): error MSB3073: The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "UE4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========)
