### ISSUE TITLE
BOOTSTRAP ERROR

### ISSUE THREAD

**Issue by rahaf2001yousef** [carla-simulator/carla#7040]
C:\carla>    make PythonAPI
-[BuildUE4Plugins]: [Batch params]: --build --all
HEAD is now at 260273d Correct descriptor
-[BuildUE4Plugins]: STREETMAP has been successfully installed in "C:\carla\Unreal\CarlaUE4\Plugins\"
-[Setup]: [Batch params]: --boost-toolset msvc-14.2 --generator "" --all
-[Setup]: Asynchronous jobs:  12
-[Setup]: Boost toolset:      msvc-14.2
-[Setup]: Generator:          "Visual Studio 16 2019"
-[Setup]: Install directory:  "C:\carla\Build\"
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_zlib]: A zlib installation already exists.
    -[install_zlib]: Delete "C:\carla\Build\zlib-install\" if you want to force a rebuild.
    -[install_zlib]: Exiting...
The system cannot find the path specified.
        0 file(s) copied.
-[Setup]: Installing libpng...
    -[install_libpng]: [Batch params]: --build-dir "C:\carla\Build\" --zlib-install-dir "C:\carla\Build\zlib-install\"
    -[install_libpng]: A libpng installation already exists.
    -[install_libpng]: Delete "C:\carla\Build\libpng-1.2.37-install\" if you want to force a rebuild.
    -[install_libpng]: Exiting...
-[Setup]: Installing rpclib...
    -[install_rpclib]: [Batch params]: --build-dir "C:\carla\Build\" --generator "Visual Studio 16 2019"
    -[install_rpclib]: A rpclib installation already exists.
    -[install_rpclib]: Delete "C:\carla\Build\rpclib-install\" if you want to force a rebuild.
    -[install_rpclib]: Exiting...
-[Setup]: Installing Google Test...
    -[install_gtest]: [Batch params]: --build-dir "C:\carla\Build\" --generator "Visual Studio 16 2019"
    -[install_gtest]: A Google Test installation already exists.
    -[install_gtest]: Delete "C:\carla\Build\gtest-install\" if you want to force a rebuild.
    -[install_gtest]: Exiting...
-[Setup]: Installing "Recast & Detour"...
    -[install_recast]: [Batch params]: --build-dir "C:\carla\Build\" --generator "Visual Studio 16 2019"
    -[install_recast]: A "Recast & Detour" installation already exists.
    -[install_recast]: Delete "C:\carla\Build\recast-install\" if you want to force a rebuild.
    -[install_recast]: Exiting...
-[Setup]: Installing Boost...
    -[install_boost]: [Batch params]: --build-dir "C:\carla\Build\" --toolset msvc-14.2 --version 1.80.0 -j 12
    -[install_boost]: Retrieving boost.
    -[install_boost]: Extracting boost from "boost_1_80_0.zip", this can take a while...

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:
1 file, 11534 bytes (12 KiB)

Extracting archive: C:\carla\Build\boost_1_80_0.zip
ERROR: C:\carla\Build\boost_1_80_0.zip
C:\carla\Build\boost_1_80_0.zip
Open ERROR: Cannot open the file as [zip] archive

ERRORS:
Is not archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
    -[install_boost]: Removing "boost_1_80_0.zip"
The system cannot find the file specified.
The system cannot find the path specified.
    -[install_boost]: Generating build...
'bootstrap.bat' is not recognized as an internal or external command,
operable program or batch file.

    -[install_boost]: [BOOTSTRAP ERROR] An error ocurred while executing "bootstrap.bat".
    -[install_boost]: Exiting with error...

-[Setup]:
   Ok, and error ocurred, don't panic
   We have different platforms where you can find some help :)

   - Make sure you have read the documentation:
       http://carla.readthedocs.io/en/latest/how_to_build_on_windows/

   - If the problem persists, you can ask on our Github's "Building on Windows" issue:
       https://github.com/carla-simulator/carla/issues/21

   - Or just use our Discord channel
       We'll be glad to help you there :)
       https://discord.gg/42KJdRj
make: *** [setup] Error 1
![Screenshot 2024-01-02 041447](https://github.com/carla-simulator/carla/assets/155392844/9c07c1e9-9914-4484-9276-86945bce7313)

CAN ANYONE HELP PLZ :(

**Comment by MrPure3D** [comment]
Same problem here with new install, didnt happen last week for some reason...

**Comment by jimmyw404** [comment]
Uhoh. Looks like Boost didn't pay their jfrog bills.

https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.zip and https://www.boost.org/users/history/version_1_80_0.html

redirects to https://landing.jfrog.com/reactivate-server/boostorg

CARLA's windows batch script at https://github.com/carla-simulator/carla/blob/master/Util/InstallersWin/install_boost.bat#L92 has a backup to handle this case that directs to https://carla-releases.s3.eu-west-3.amazonaws.com/Backup/boost_1_80_0.zip , but unfortunately the failed jfrog download creates a 12KB zip file with a bunch of HTML, so that backup is never downloaded.


The install_boost.bat script should be updated to handle that exception. In the mean time you can use the link at https://carla-releases.s3.eu-west-3.amazonaws.com/Backup/boost_1_80_0.zip to download a zip file to the carla/Build folder (next to the zlib-source and recast-0b13b0-src folders) and and then run

make PythonAPI

**Comment by Blyron** [comment]
We have updated links so please, use dev branch. Additionally, you can change s3.eu-west-3.amazonaws.com for s3.us-east-005.backblazeb2.com
