### ISSUE TITLE
the map created with Truevision lost the lane when import into carla!

### ISSUE THREAD

**Issue by electronicYH** [carla-simulator/carla#7041]
the map in the truevision:
![Screenshot from 2024-01-03 10-55-07](https://github.com/carla-simulator/carla/assets/11705091/7a48c5fb-ad85-49e4-a10c-07b93138a04f)
the map in the carla:
![Screenshot from 2024-01-03 10-56-53](https://github.com/carla-simulator/carla/assets/11705091/b2bec1d5-d998-4d31-bb45-8de69b874202)
please help me!
the lane lost in the carla!

**Comment by Madecu** [comment]
Hi @electronicYH .
Do you have a road mesh in the scene? It seems that you have the mesh but without a road texture
