### ISSUE TITLE
OSM2OD-visualstudio error 

### ISSUE THREAD

**Issue by rahaf2001yousef** [carla-simulator/carla#7042]
Hi,

I am trying to build the Carla on Windows 11.

When I do Update.bat , the process stops
at OSM2OD-visualstudio with CMAKE error.
 
 Can anyone help me with this issue please 🥹

**Comment by martatro** [comment]
This could be an issue with the file BuildOSM2ODR.bat that's under carla\Util\BuildTools.

In line 112
`cmake -G %GENERATOR% %PLATFORM%^`
should be changed to
`cmake -G %GENERATOR% -A x64^`

(source: https://github.com/carla-simulator/carla/issues/6898#issuecomment-1807921422)

**Comment by Blyron** [comment]
Yeah thanks for answer this. Are you happy to close this issue?

**Comment by Blyron** [comment]
I am closing the issue, feel free to reopen
