### ISSUE TITLE
multi lidar simulate and visualiza issue

### ISSUE THREAD

**Issue by tdcsu** [carla-simulator/carla#7045]
Hi, there,

I am trying to simulate a 16 line raycast lidar and a 64 raycast lidar on a vehicle, but there is a problem.
My script was adapted from CARLA-0.9.10/PythonAPI/examples/open3d_lidar.py
the whole code is below:
[script.txt](https://github.com/carla-simulator/carla/files/13825975/script.txt)

As you can see, to simulate two lidars, I just copied the existing lidar setup but changed some attributes.
However, when I start the CARLAUE4 and run my script, the visualise result is:
![Screenshot from 2024-01-04 11-55-58](https://github.com/carla-simulator/carla/assets/56823449/174aeca4-6590-4138-ba45-f44ae6104cb6)

That means the second lidar works not well.

And when I stop the script, there said:
![image](https://github.com/carla-simulator/carla/assets/56823449/b2553577-84a5-406a-ac5d-8a4baa2391fb)
But when I only simulate one lidar, it works well.

Anyone can help me ?
Thanks with my appreciation

**Comment by PatrickPromitzer** [comment]
The function you give the listener is in a subprocess, and Python makes a copy of the class/variables if you send them in a subprocess.
``` 
lidar1.listen(lambda data1: semantic_lidar_callback(data1, point_list1))
# semantic_lidar_callback() called in a subprocess
```

I can't say how o3d.geometry.PointCloud() works with the listener, but you can try using Queue.
Queue is made for handling data between the main-process and sub-process.

```python
from queue import Queue
data_queue = Queue()
...
# lidar
lidar1.listen(lambda data1: semantic_lidar_callback(data1, data_queue))

...
# in semantic_lidar_callback
# put data in the Queue
data_queue.put(point_cloud.raw_data)

...
# in while loop
# get data from the Queue
lidar_data = data_queue.get()
```

**Comment by tdcsu** [comment]
您好，我已收到您的邮件，会尽快处理~

**Comment by tdcsu** [comment]
> The function you give the listener is in a subprocess, and Python makes a copy of the class/variables if you send them in a subprocess.
> 
> ```
> lidar1.listen(lambda data1: semantic_lidar_callback(data1, point_list1))
> # semantic_lidar_callback() called in a subprocess
> ```
> 
> I can't say how o3d.geometry.PointCloud() works with the listener, but you can try using Queue. Queue is made for handling data between the main-process and sub-process.
> 
> ```python
> from queue import Queue
> data_queue = Queue()
> ...
> # lidar
> lidar1.listen(lambda data1: semantic_lidar_callback(data1, data_queue))
> 
> ...
> # in semantic_lidar_callback
> # put data in the Queue
> data_queue.put(point_cloud.raw_data)
> 
> ...
> # in while loop
> # get data from the Queue
> lidar_data = data_queue.get()
> ```
@PatrickPromitzer Thanks for your reply and your detailed suggestion. This issue has been solved. And I'll close this issue.
