### ISSUE TITLE
Carla Tool Content folder missing

### ISSUE THREAD

**Issue by matejm42** [carla-simulator/carla#7053]
CARLA version: 0.9.15
Platform/OS: Ubuntu 20.04
Problem you have experienced: In the `Content Browser` in `Unreal Engine Editor` is only folder *Content* and the *Carla Content*, *Carla C++ Classes*, *Carla Tools Content*, *HoudiniEngine Content*, *StreetMap Content* etc. are missing.
![Image from documentation](https://carla.readthedocs.io/en/latest/img/digital_twins_widget.png)

I was following the steps from [Digital Twin Tool guide](https://carla.readthedocs.io/en/latest/adv_digital_twin/). When I got to the part: 
"To open the OSM browser, open the content browser and navigate to CarlaToolsContent/OnroadMapGenerator. Right click on UW_OnRoadMainWidget and select Launch Editor Utility Widget from the context menu." 
And I realized, there is no Carla Tools Content in my Contend Browser
![content](https://github.com/carla-simulator/carla/assets/116560704/534b2d69-cada-43fa-828f-a68163833824)
![opened content](https://github.com/carla-simulator/carla/assets/116560704/3a89f417-15ba-433a-9106-561f94fe028f)

I found *UW_OnRoadMainWidget* in *Plugins* folder and solved this issue by creating a symlink to this folder inside of Content folder I could see in the `Content Browser`

I ran from the `CALRA_ROOT/Unreal/CarlaUE4/Content` Folder
```
ln -s /full/path/to/carla_root/Unreal/CarlaUE4/Plugins Plugins
```

![content of plugin](https://github.com/carla-simulator/carla/assets/116560704/6b2bc175-1384-4523-b56a-70d70b5835db)

**Comment by matejm42** [comment]
I was not able to successfully use the Digital Twin Tool anyway, but that is already described in #6913

**Comment by Sivagopinathreddy-Vinta** [comment]
in ContentBrowser Right clivk and select all views to see all folders in content view

**Comment by leilai125** [comment]
I have the same issue. Have you solved it?

**Comment by matejm42** [comment]
@leilai125 I "solved" it by creating the symlink to Plugins inside of the Content folder.

> I found UW_OnRoadMainWidget in Plugins folder and solved this issue by creating a symlink to this folder inside of Content folder I could see in the Content Browser
> I ran from the CALRA_ROOT/Unreal/CarlaUE4/Content Folder
> 
>```
>   ln -s /full/path/to/carla_root/Unreal/CarlaUE4/Plugins Plugins
>```

**Comment by leilai125** [comment]
Hi,

Thanks! It works! Did you eventually generate a map from openstreetmap like the link (https://carla.org/2023/11/10/release-0.9.15/) shows? I am still struggling in generating the same result as the link shows.

**Comment by matejm42** [comment]
@leilai125 I was able to generate some map.  I had to choose map without buildings, otherwise it crashes. It still threw errors and the product was not accurate :( 
https://github.com/carla-simulator/carla/issues/6913#issuecomment-1881058612

**Comment by Blyron** [comment]
To see Plugins content you can 
UE5: https://www.youtube.com/watch?v=G3Q3I3-gH3A&ab_channel=Algosyntax
UE4: https://www.youtube.com/watch?v=05Ch89wQabk&ab_channel=AntonIovbak

If you have issues with other features please open other issue.

I am closing this issue. Please feel free to reopen it

**Comment by Sephiroth1118** [comment]
Hi, I have the same problem but stranger. I even don't have the plugin folder in my content. My content is like this.
![Screenshot from 2024-09-03 22-06-02](https://github.com/user-attachments/assets/cab5d0db-ee0f-4d1f-b148-e46b1fed3914)
I tried to run Update.sh to update the content. But it told me content is already up-to-date.

**Comment by SkatingReimu** [comment]
Hi all, this was a simple solution to my issue (I was trying to figure out to get the plugins to show up, not sure if you guys have tried this)
On the bottom right of the Content Browser, there should be a "View Options" menu that you can click on. Clicking on "Show Plugin Content" allowed me to access the folder. 
![Screenshot_2024-09-18_09-50-32](https://github.com/user-attachments/assets/8f6aff60-07c8-48f2-b286-aa4110db3de3)
