### ISSUE TITLE
Wrong Windows release files linked for 0.9.15!?

### ISSUE THREAD

**Issue by lein1013** [carla-simulator/carla#7054]
When I go to https://github.com/carla-simulator/carla/releases/tag/0.9.15 and want to download the Windows version the 0.9.14 is linked instead of 0.9.15
![grafik](https://github.com/carla-simulator/carla/assets/72338417/b5e6205c-1139-44c5-b226-b42684a2821b)

It seems that the text is correct, but 3 of 4 links point to the old version - Why did no one notice this?

- [Ubuntu] [CARLA_0.9.15.tar.gz] (https://carla-releases.s3.us-east-005.backblazeb2.com/Linux/CARLA_0.9.15.tar.gz) -> correct
- [Ubuntu] [AdditionalMaps_0.9.15.tar.gz] (https://carla-releases.s3.us-east-005.backblazeb2.com/Linux/AdditionalMaps_0.9.14.tar.gz) -> wrong
-    [Windows] [CARLA_0.9.15.zip] (https://carla-releases.s3.us-east-005.backblazeb2.com/Windows/CARLA_0.9.14.zip) ->wrong
-    [Windows] [AdditionalMaps_0.9.15.zip] (https://carla-releases.s3.us-east-005.backblazeb2.com/Windows/AdditionalMaps_0.9.14.zip) -> wrong

BWT - just modifying the link works
- https://carla-releases.s3.us-east-005.backblazeb2.com/Windows/CARLA_0.9.15.zip
- https://carla-releases.s3.us-east-005.backblazeb2.com/Windows/AdditionalMaps_0.9.15.zip

**Comment by xavisolesoft** [comment]
We fixed this issue.
Thank you for letting us know.
