### ISSUE TITLE
where can I find the https://github.com/CarlaUnreal/UnrealEngine.git 

### ISSUE THREAD

**Issue by zczjx** [carla-simulator/carla#7067]
in the https://carla.readthedocs.io/en/0.9.15/build_linux/

we need the  https://github.com/CarlaUnreal/UnrealEngine.git for the next step libCarla build
then can we build pythonAPI for python 3.8

but where can we find the lib, without it, we cannot build the next steps

**Comment by PatrickPromitzer** [comment]
You need to link an Unreal Engine's account linked to your GitHub account.

> 
> Unreal Engine
> 
> Starting with version 0.9.12, CARLA uses a modified fork of Unreal Engine 4.26. This fork contains patches specific to CARLA.
> 
> **Be aware that to download this fork of Unreal Engine, you need to have a GitHub account linked to Unreal Engine's account.** If you don't have this set up, please follow [this guide](https://www.unrealengine.com/en-US/ue4-on-github) before going any further.
> 
Here the link to the guid.
[https://www.unrealengine.com/en-US/ue-on-github](https://www.unrealengine.com/en-US/ue-on-github)

**Comment by zczjx** [comment]
let me try, thanks @PatrickPromitzer

**Comment by zczjx** [comment]
verified and closed
