### ISSUE TITLE
Unable to see the Blueprint modifications that are edited in the Unreal Editor

### ISSUE THREAD

**Issue by chirudeep001** [carla-simulator/carla#7078]
Not able to see the changes that are made in the blueprints of the vehicles in unreal editor.
For example: i have removed the doors of the gen 2 car and saved the changes, and the changes can be seen in the editor. now i am using editor as a server and trying to run the scenario runner and the changes are not reflectiong in the car.

**Comment by gsmario** [comment]
Hello, can you post some images about how you've modified the blueprint? Also, have you make sure on what blueprint are being called by the sceneario runner?
Thanks in advance
