### ISSUE TITLE
make launch error

### ISSUE THREAD

**Issue by chirudeep001** [carla-simulator/carla#7097]
UnrealBuildTool: ERROR: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
                        (referenced via Target -> NativizedAssets.Build.cs -> CarlaTools.Build.cs -> AssetTools.Build.cs)
make: *** [CarlaUE4Editor] Error 6

**Comment by LuisPoveda** [comment]
Hi! Can you share more information about this?
Which OS are you using?
Do you have installed the carla unreal and have been able to open the editor?
https://carla.readthedocs.io/en/latest/build_linux/

**Comment by LuisPoveda** [comment]
Since there is no response I am going to close this issue, feel free to reopen it.
