### ISSUE TITLE
Anybody got a simple map?

### ISSUE THREAD

**Issue by JakobJar** [carla-simulator/carla#7150]
Hey,
I'm searching for a map as simple as possible, preferably only with one lane, just some curves and straights. The setup for building an own map is quite difficult so maybe anyone has map they could send me.

Best regards,
Jakob

**Comment by csonthomisi** [comment]
Hi Everybody!

Here I Shared 2 Maps recently!
[https://github.com/carla-simulator/carla/discussions/7181](https://github.com/carla-simulator/carla/discussions/7181)
