### ISSUE TITLE
What is the concept of spawn points?

### ISSUE THREAD

**Issue by Anhar2** [carla-simulator/carla#7175]
I'm using CARLA with leaderboard, carla version 0.9.14, scenario runner version 0.9.13 on Ubuntu 18

First I thought we use get_spawning_points() method to generated all possible coordinates that are legit, "i.e. a road, not intersecting with a building, not colliding with the ground etc"

For me to choose one to spawn  vehicles for a scenario, I decided to use carla manual_control.py to roam around the city, choose a fine point, and record its coordinate.
It works just fine for non-ego vehicles, the problem is it never works when used for the ego vehicles, only the spawn points list generated by get_spawning_points() is the one that allows spawning ego vehicles which is weird and problematic, moreover some spawn points aren't even legit.

an example: in Town 3
these spawn points:

Transform(Location(x=-77.985069, y=-30.239780, z=0.275307), Rotation(pitch=-0.348271, yaw=-90.156235, roll=-0.000000)) 

Transform(Location(x=-88.456612, y=-33.568760, z=0.275307), Rotation(pitch=-0.471802, yaw=89.843742, roll=0.000000)) 

Transform(Location(x=-74.485085, y=-44.049332, z=0.275307), Rotation(pitch=-0.348271, yaw=-90.156235, roll=-0.000000)) 

spawn the ego vehicles INSIDE a ramp, inside the asphalt road itself, even when I leave the ramp, I find it as if it's drowning in the road.

I'd be very grateful if someone can explain this.

**Comment by Daraan** [comment]
I cannot say anything specific to the spawn points in Town 3 or the ones you mentioned.

From my experience SpawnPoints are hand-choosen positions that are nice starting points for vehicles, so they are a subset of possible coordinates. If you are using the build-version with the editor you can see them as black circles with white outlines, like here:

![grafik](https://github.com/carla-simulator/carla/assets/27899926/2ac336be-b787-455c-b80f-3bead445ba1a)

From my experience you should increase the z value of the choosen spawn point by a few meters.
