### ISSUE TITLE
Spawned vehicle floats in place on marcel/ue5.3 branch, need some suggestions to fix it.

### ISSUE THREAD

**Issue by citrusboy1997** [carla-simulator/carla#7180]
Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool!
I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin?
![screenshot-20240223-204222](https://github.com/carla-simulator/carla/assets/49858506/b2587612-3c24-486d-a2b4-f17ece85ab39)
carla version: branch marcel/ue5.3
Python API version: 0.9.14
Platform: Ubuntu 20.04
cmake version: 3.28.3
clang version: 16.0.6
The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin

**Comment by citrusboy1997** [comment]
> > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjU0NjMsIm5iZiI6MTcwODk2NTE2MywicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYmYxZWI0Mzk2OGM4OTYxZDQ4MDc5MDY3ZmRkMWQ0Yzk3ZDE1N2M5ZTQxMjhjOTdlMThlZGY3MDM1OTYwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlijhrr3o35PkAstq5bJ9rq2j5mOh4ASJleVBzvc3lw) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> 
> Will you be so kind to tell us how to compile this ue5 branch? i have spent two more weeks and can't resolve the compiling errors, especially for the CarlaUE4Editor. i ma using the same build tools as yours.

Hi, I compiled with the Configure.py in carla root with

**Comment by matthew-rococo** [comment]
> > > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjU0NjMsIm5iZiI6MTcwODk2NTE2MywicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYmYxZWI0Mzk2OGM4OTYxZDQ4MDc5MDY3ZmRkMWQ0Yzk3ZDE1N2M5ZTQxMjhjOTdlMThlZGY3MDM1OTYwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlijhrr3o35PkAstq5bJ9rq2j5mOh4ASJleVBzvc3lw) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> > 
> > 
> > Will you be so kind to tell us how to compile this ue5 branch? i have spent two more weeks and can't resolve the compiling errors, especially for the CarlaUE4Editor. i ma using the same build tools as yours.
> 
> Hi, I compiled with the Configure.py in carla root with `pip3 install -r requirements.txt`
> 
> `python3 Configure.py --update-ue-assets`
> 
> `python3 Configure.py --update-deps --osm2odr`
> 
> `python3 Configure.py --build-deps --osm2odr`
> 
> `python3 Configure.py --libcarla-server --libcarla-client`
> 
> `python3 Configure.py --carla-ue` You'd better not to use conda env and have to fix some bugs according to the build logs Tips: Compare marcel/ue5.3 branch with master branch with IDE will help you figure out what has changed

Thanks a lot , i will try it at once.

**Comment by MarcelPiNacy** [comment]
Hi

> Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTYwNzUsIm5iZiI6MTcwOTA1NTc3NSwicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE3NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGU5ZTFkMThiYzViNzU3MTVhYzgzZDEyZTQzNDYxYTcwNDlmYzVkMmEyZDBkMDNjNjk3ODc4MDhhNGZkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_azyYJQXXOqfuBliBrsUFpXk2C4S9YyLe5jXLLMD98) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin

Hi, currently almost all physics-related code is temporarily disabled due to the migration from PhysX to Chaos. I want to also note that we're switching to CMake, so the Configure.py script will be removed soon.

**Comment by MarcelPiNacy** [comment]
> > > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjU0NjMsIm5iZiI6MTcwODk2NTE2MywicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYmYxZWI0Mzk2OGM4OTYxZDQ4MDc5MDY3ZmRkMWQ0Yzk3ZDE1N2M5ZTQxMjhjOTdlMThlZGY3MDM1OTYwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlijhrr3o35PkAstq5bJ9rq2j5mOh4ASJleVBzvc3lw) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> > 
> > 
> > Will you be so kind to tell us how to compile this ue5 branch? i have spent two more weeks and can't resolve the compiling errors, especially for the CarlaUE4Editor. i ma using the same build tools as yours.
> 
> Hi, I compiled with the Configure.py in carla root with `pip3 install -r requirements.txt`
> 
> `python3 Configure.py --update-ue-assets`
> 
> `python3 Configure.py --update-deps --osm2odr`
> 
> `python3 Configure.py --build-deps --osm2odr`
> 
> `python3 Configure.py --libcarla-server --libcarla-client`
> 
> `python3 Configure.py --carla-ue` You'd better not to use conda env and have to fix some bugs according to the build logs Tips: Compare marcel/ue5.3 branch with master branch with IDE will help you figure out what has changed

Btw if you're sufficiently up to date, there should be a --all option. You also need to pass --ue-path=<UE5_ROOT>, since we're no longer going to use environment variables.

**Comment by citrusboy1997** [comment]
> Hi
> 
> > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTYwNzUsIm5iZiI6MTcwOTA1NTc3NSwicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE3NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGU5ZTFkMThiYzViNzU3MTVhYzgzZDEyZTQzNDYxYTcwNDlmYzVkMmEyZDBkMDNjNjk3ODc4MDhhNGZkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_azyYJQXXOqfuBliBrsUFpXk2C4S9YyLe5jXLLMD98) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> 
> Hi, almost all physics-related code is temporarily disabled due to the migration from PhysX to Chaos. I want to also note that we're switching to CMake, so the Configure.py script will be removed soon.

Thanks a lot. It is glad to receive a reply from you!
It seems like the following work will be done: 
- Refactor all the PhysX-related contents commented by '@CARLAUE5' in CarlaWheeledVehicle.cpp and WheeledVehicleMovementComponentNW.cpp with Chaos
- Regenerate the BaseVehiclePawn BP, the cars PB and wheels PB of all vehicles in UE project contents

Is that right? I'm still a starting developer and not familiar with the whole UE project yet.

And can you tell me how soon the vehicle refactoring will be done? I'm so desperate to get the car moving in UE5.3!

**Comment by citrusboy1997** [comment]
> Hi
> 
> > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTYwNzUsIm5iZiI6MTcwOTA1NTc3NSwicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE3NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGU5ZTFkMThiYzViNzU3MTVhYzgzZDEyZTQzNDYxYTcwNDlmYzVkMmEyZDBkMDNjNjk3ODc4MDhhNGZkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_azyYJQXXOqfuBliBrsUFpXk2C4S9YyLe5jXLLMD98) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> 
> Hi, almost all physics-related code is temporarily disabled due to the migration from PhysX to Chaos. I want to also note that we're switching to CMake, so the Configure.py script will be removed soon.

Hi, with some modifications, my vehicle is able to move properly in UE5! But I find another problem that the image always lack of 12 elements in a numpy array.

**Comment by MarcelPiNacy** [comment]
> > Hi
> > > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTYwNzUsIm5iZiI6MTcwOTA1NTc3NSwicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE3NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGU5ZTFkMThiYzViNzU3MTVhYzgzZDEyZTQzNDYxYTcwNDlmYzVkMmEyZDBkMDNjNjk3ODc4MDhhNGZkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_azyYJQXXOqfuBliBrsUFpXk2C4S9YyLe5jXLLMD98) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> > 
> > 
> > Hi, almost all physics-related code is temporarily disabled due to the migration from PhysX to Chaos. I want to also note that we're switching to CMake, so the Configure.py script will be removed soon.
> 
> Thanks a lot. It is glad to receive a reply from you! It seems like the following work will be done:
> 
> * Refactor all the PhysX-related contents commented by '@CARLAUE5' in CarlaWheeledVehicle.cpp and WheeledVehicleMovementComponentNW.cpp with Chaos
> * Regenerate the BaseVehiclePawn BP, the cars PB and wheels PB of all vehicles in UE project contents
> 
> Is that right? I'm still a starting developer and not familiar with the whole UE project yet.
> 
> And can you tell me how soon the vehicle refactoring will be done? I'm so desperate to get the car moving in UE5.3!

Yeah, this and many more changes...

**Comment by MarcelPiNacy** [comment]
> > Hi
> > > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTYwNzUsIm5iZiI6MTcwOTA1NTc3NSwicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE3NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGU5ZTFkMThiYzViNzU3MTVhYzgzZDEyZTQzNDYxYTcwNDlmYzVkMmEyZDBkMDNjNjk3ODc4MDhhNGZkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_azyYJQXXOqfuBliBrsUFpXk2C4S9YyLe5jXLLMD98) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> > 
> > 
> > Hi, almost all physics-related code is temporarily disabled due to the migration from PhysX to Chaos. I want to also note that we're switching to CMake, so the Configure.py script will be removed soon.
> 
> Hi, with some modifications, my vehicle is able to move properly in UE5! But I find another problem that the image always lack of 12 elements in a numpy array. After running visualize_multiple_sensors.py, the expection is: ValueErrorValueError: : cannot reshape array of size 613428 into shape (360,426,4) cannot reshape array of size 613428 into shape (360,426,4)

It's perfectly possible that the PythonAPI is being built incorrectly in the marcel/ue5.3 branch. I will merge a branch into it soon that should fix this.

**Comment by MarcelPiNacy** [comment]
> > Hi
> > > Hi, it is surprising to find there is a UE5.3 branch! It is pretty cool! I am trying to follow Marcel's UE5.3 migration work. I successed compling UE5.3 carla on Ubuntu20.04 and it works well with 0.9.14 python API package. After starting manual_control.py, the traffic light works fine, but the spawned vehicle floats there. If I want to fix it, where should I begin? ![screenshot-20240223-204222](https://private-user-images.githubusercontent.com/49858506/307323834-b2587612-3c24-486d-a2b4-f17ece85ab39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTYwNzUsIm5iZiI6MTcwOTA1NTc3NSwicGF0aCI6Ii80OTg1ODUwNi8zMDczMjM4MzQtYjI1ODc2MTItM2MyNC00ODZkLWEyYjQtZjE3ZWNlODVhYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE3NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGU5ZTFkMThiYzViNzU3MTVhYzgzZDEyZTQzNDYxYTcwNDlmYzVkMmEyZDBkMDNjNjk3ODc4MDhhNGZkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_azyYJQXXOqfuBliBrsUFpXk2C4S9YyLe5jXLLMD98) carla version: branch marcel/ue5.3 Python API version: 0.9.14 Platform: Ubuntu 20.04 cmake version: 3.28.3 clang version: 16.0.6 The using SeatLeon blueprint is edited in UE5 editor with ChaosVehicle plugin
> > 
> > 
> > Hi, almost all physics-related code is temporarily disabled due to the migration from PhysX to Chaos. I want to also note that we're switching to CMake, so the Configure.py script will be removed soon.
> 
> Hi, with some modifications, my vehicle is able to move properly in UE5! But I find another problem that the image always lack of 12 elements in a numpy array. After running visualize_multiple_sensors.py, the expection is: ValueErrorValueError: : cannot reshape array of size 613428 into shape (360,426,4) cannot reshape array of size 613428 into shape (360,426,4)

If you want to try this to-be-merged branch, you can take a look at marcel/5.3/python-api-overhaul. It may not build correctly on Ubuntu yet though.
