### ISSUE TITLE
0.9.10.1 Release Package and Content Not Available

### ISSUE THREAD

**Issue by btcreater** [carla-simulator/carla#7196]
![image](https://github.com/carla-simulator/carla/assets/12061594/970ff1fa-884f-4bb1-9b0e-e6a5bbb35815)

**Comment by No4x** [comment]
I had the same issue.

**Comment by kovendijozsef** [comment]
I have faced the same issue. According to this response(https://github.com/carla-simulator/carla/issues/7192#issuecomment-1974866723), the URL has changed and the correct one is on the dev branch.

The 50th line in Update.sh should be:
`CONTENT_LINK=https://carla-assets.s3.us-east-005.backblazeb2.com/${CONTENT_ID}.tar.gz`

**Comment by Haobo-Liu** [comment]
https://carla-releases.s3.us-east-005.backblazeb2.com/Linux/CARLA_0.9.13.tar.gz
try it,change 0.9.13 to your own version
