### ISSUE TITLE
Enter fullscreen mode in client view (manual control with/without steering)

### ISSUE THREAD

**Issue by FilipMari** [carla-simulator/carla#7216]
CARLA version: 0.9.15
Platform/OS: Windows 11
Problem: When running the manual_control.py script the display is in windowed mode, very small, and I want it in full screen. Neither pressing F11 nor alt+enter does anything. The issue persists when running manual_control_steeringwheel.py with Logitech controller, but entering fullscreen works fine in the server view. I have looked through the docs, git issues and the scripts but can't figure out how to make the screen full. Otherwise the controls work rather fine. Please help!

**Comment by siddharthjain38** [comment]
@FilipMari manual_control uses pygame for rendering the output and resizing is not directly possible. For resigning pygame window you have to update pygame window height and width in manual_control script. 

`pygame.display.set_mode((args.width, args.height),pygame.HWSURFACE | pygame.DOUBLEBUF)`
