### ISSUE TITLE
Carla 0.9.10.1 link is not available

### ISSUE THREAD

**Issue by NimaMeghdadi** [carla-simulator/carla#7235]
when I try to get 

```
wget https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/CARLA_0.9.10.1.tar.gz
```

Link is not available

--2024-03-11 12:13:06--  https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/CARLA_0.9.10.1.tar.gz
Resolving carla-releases.s3.eu-west-3.amazonaws.com (carla-releases.s3.eu-west-3.amazonaws.com)... 16.12.20.10, 52.95.156.48
Connecting to carla-releases.s3.eu-west-3.amazonaws.com (carla-releases.s3.eu-west-3.amazonaws.com)|16.12.20.10|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-11 12:13:07 ERROR 404: Not Found.

**Comment by Blyron** [comment]
https://github.com/carla-simulator/carla/issues/7196
