### ISSUE TITLE
PythonAPI - List of undocumented (or outdated ) documentation

### ISSUE THREAD

**Issue by Daraan** [carla-simulator/carla#7236]
Certain functions/classes are missing from https://carla.readthedocs.io/en/latest/python_api

I am currently aware of these:

- [ ] `Client.load_world`, `Client.reload_world` Missing Return Type: `World`
- [ ] `CityObjectLabel`; see #6216
- [ ] `command.FutureActor` Undocumented (referenced by some examples)
- [ ] `Client.load_world_if_different` Undocumented; see #6651

**Comment by MattRoweEAIF** [comment]
Thank you for raising this issue with the docs, these have now been fixed.
