### ISSUE TITLE
Some vehicles are not visible in LiDAR when I replay the recording

### ISSUE THREAD

**Issue by shejiadeji** [carla-simulator/carla#7238]
When I was using a LiDAR sensor, I found that LiDAR did not work perfectly in the repalyfile.
Some cars are visible in LiDAR sensors, while others are invisible.The category of visible cars is mesh, while the category of invisible cars is vehicle.

**Comment by shejiadeji** [comment]
ubuntu 20.04
carla 0.9.14

**Comment by LuisPoveda** [comment]
Thanks for posting the issue, we will look at it

**Comment by Blyron** [comment]
Hello, we will need more info about what vehicles are invisible

**Comment by fcheng-cv** [comment]
> Hello, we will need more info about what vehicles are invisible

During replay file, actors have no point cloud due to missing physics simulation, env objs are OK

**Comment by LuisPovedaCano** [comment]
This issue has been fixed, please update to with the latest dev. Feel free to reopen it if it occurs again.
