### ISSUE TITLE
20211112_d5cfa12.tar.gz

### ISSUE THREAD

**Issue by edugh02** [carla-simulator/carla#7255]
CARLA version: 0.9.13
OS: Windows 10

Hi, i am trying to download the 20211112_d5cfa12.tar.gz because i am doing a proyect with carla 0.9.13. The problem is that when I try to do the Update.bat within the carla repository, the following error appears:

Downloading "http://carla-assets.s3.amazonaws.com/20211112_d5cfa12.tar.gz"...
Excepción al llamar a "DownloadFile" con los argumentos "2": "Error en el servidor remoto: (404) No se encontró."
En línea: 1 Carácter: 1

(New-Object System.Net.WebClient).DownloadFile('http://carla-assets.s/ ...
  + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  + FullyQualifiedErrorId : WebException

Exiting with error...

I tried to download with the link of Util/ContentVersions.txt file. In that file says that i have to search the link http://carla-assets.s3.amazonaws.com/20211112_d5cfa12.tar.gz, but the lin can be found.
What i have to do?

**Comment by Blyron** [comment]
We have changed our storagin system from aws to backblaze
https://github.com/carla-simulator/carla/issues/7196
Please change your link
