### ISSUE TITLE
Xerces-C++ library link test failed

### ISSUE THREAD

**Issue by xiaoxiao-zhou-q** [carla-simulator/carla#7256]
CMake Error at cmake/XercesChecks.cmake:61 (message):
  Xerces-C++ library link test failed
Call Stack (most recent call first):
  CMakeLists.txt:86 (include)

**Comment by xavisolesoft** [comment]
Hi,

Could you share the full log, please? We will need more information to analyze the source of the issue.

**Comment by xavisolesoft** [comment]
We will close this issue for now, due inactivity.
Feel free to reopen it.
