### ISSUE TITLE
Houdini and Digital Twin tool

### ISSUE THREAD

**Issue by NnaYelsel** [carla-simulator/carla#7262]
CARLA version: **0.9.15**
Platform/OS: **Windows**
Problem you have experienced: **Could only build Carla by disable Houdini and have Carla shutdown when using UW_OnRoadMainWidget** 

Hello,

Previously, I had some problem to compile Carla on my computer because I had the following problem:
![image](https://github.com/carla-simulator/carla/assets/49529118/d72121bf-b6e2-40ef-93f1-e0953e2667b0)

I could finally compile by following the indications of this thread: https://github.com/carla-simulator/carla/issues/7012 

But, now that I'm trying to use the digital twin tool, I got UE crashing when I'm trying to use UW_OnRoadMainWidget.

Do you think that's it's related ? 

Best regards

**Comment by lightlefter** [comment]
hi,I still traped in your first question.
 #7012 didn't work well, could you explain more specific?
just delete the two codeline of  carla tool?

**Comment by NnaYelsel** [comment]
Hi, 
Applying #7012 worked well to compile Carla, but then I struggle to use the Digital Twin tool, and I was wondering if the fact that I couldn't make Digital Twin Tool work was related to the modification I had to do to compile Carla, i.e disable Houdini for example.
