### ISSUE TITLE
Can I build carla with unreal engine 4.27?

### ISSUE THREAD

**Issue by DesayHiL** [carla-simulator/carla#7272]
Can I build carla with unreal engine 4.27?

**Comment by DesayHiL** [comment]
![3a501d3f7bb095a206aadcfe733a1a64](https://github.com/carla-simulator/carla/assets/94581016/1ab6b635-f8f9-4705-a4da-a8e82c00947d)
who can help me？

**Comment by DesayHiL** [comment]
![image](https://github.com/carla-simulator/carla/assets/94581016/0a9b341c-1bb8-48d0-b23b-c89f4c3618b6)
who can help me

**Comment by Blyron** [comment]
We do not support UE4_27

**Comment by utkuoguzman** [comment]
> We do not support UE4_27

Can you please support UE4.27 as 4.26 is full of landscape bugs and you will continue adding main features on ue4-dev branch?
