### ISSUE TITLE
 how to get the groundtruth value for roadmark

### ISSUE THREAD

**Issue by limanman302** [carla-simulator/carla#7276]

**Comment by DriveSlowly** [comment]
hello carla teams.

by using API "[laneMarking](https://carla.readthedocs.io/en/latest/python_api/#carlalanemarking)" I can not get the geometry infomation of the roadmark,  do you have any idea of getting the groundtruth value for roadmark?

**Comment by PatrickPromitzer** [comment]
You can try looking in the openDRIVE of the MAP to get the Roadmarks.

carla_root/Unreal/CarlaUE4/Content/Carla/Maps/Town11/OpenDrive/Town11.xodr
The openDRIVE file should have every road information you may need from the MAP.
