### ISSUE TITLE
Assertion failed (I think it is at the level of lidar listen function)

### ISSUE THREAD

**Issue by Someone22333** [carla-simulator/carla#7295]
CARLA version: 0.9.14
I will like to use the lidar sensor and collect the lidar data to detect the object infront of the ego vehicle.

But when I spawn the lidar and I use the function:

**lidar.listen(lambda point_cloud: point_cloud.save_to_disk('Unitest/new_lidar_output/%.6d.ply' % point_cloud.frame))**

Or

**points = lidar.listen(lambda point_cloud: point_cloud)**

I get an error: Assertion failed: (_clients.find(token.get_stream_id())) == (_clients.end()), file C:\workspace\carla\LibCarla\cmake\..\source\carla/streaming/low_level/Client.h, line 56

Any idea on how to resolve this error ??

**Comment by Lostness-Wf** [comment]
Have you solved this problem, how to achieve it
