### ISSUE TITLE
Internal parameter matrix and external parameter matrix of camera

### ISSUE THREAD

**Issue by Etiennejiang** [carla-simulator/carla#7297]
I am using carla0.9.15.
 how do I get the internal and external parameter matrix of the camera？

**Comment by LuisPoveda** [comment]
Hello, I hope this helps you with the issue
https://carla.readthedocs.io/en/latest/ref_sensors/#basic-camera-attributes_1

**Comment by LuisPoveda** [comment]
Since there is no response I am going to close this issue, feel free to reopen it.
