### ISSUE TITLE
Unreal Engine's recommended hardware is a dead link

### ISSUE THREAD

**Issue by mimi89999** [carla-simulator/carla#7304]
Hello,

It seems that https://github.com/carla-simulator/carla/blob/master/Docs/build_faq.md?plain=1#L79 is a dead link.

**Comment by Blyron** [comment]
Yeah. Epic Games is making transition to new webpage, we are gonna change it. Thanks for telling us. This will be the new link:
https://dev.epicgames.com/documentation/en-us/unreal-engine/hardware-and-software-specifications-for-unreal-engine

**Comment by Blyron** [comment]
Yeah. Epic Games is making transition to new webpage, we are gonna change it. Thanks for telling us. This will be the new link:
https://dev.epicgames.com/documentation/en-us/unreal-engine/hardware-and-software-specifications-for-unreal-engine

**Comment by MattRoweEAIF** [comment]
@mimi89999 thanks for alerting us to this, it has been fixed, closing this issue
