### ISSUE TITLE
Performance Discrepancy: Python Execution Speed in CARLA Build Version vs. Quick Installation

### ISSUE THREAD

**Issue by evoevo07** [carla-simulator/carla#7306]
CARLA version: 9.15
Platform/OS: Ubuntu 22.04

Hey folks,

I've successfully built CARLA and also performed the quick installation. However, I've noticed that executing Python commands in the build version (UE4 editor) is significantly slower compared to the quick installation. Is this normal, or could there be an issue on my system?
Thanks!

**Comment by Blyron** [comment]
Hey evoevo!

Sorry for the delay. It is expected that UE4Editor version is much slower than a package version as it contains more debug symbols and UE4 Editor itself with contains more subsystems that are not included in Packages
