### ISSUE TITLE
Custom Vehicle Head Lights and Adjustable vehicle light parameters through Python API as future features

### ISSUE THREAD

**Issue by AyumuOshiro-RCI** [carla-simulator/carla#7311]
Hi, Thank you for developing a great simulator.

I am interested in utilizing CARLA specifically for car headlights simulation with MATLAB/Simulink models. 
In order to imitate ADB(Adaptive Driving Beam) and AFS(Adaptive Front Lighting System) in CARLA, I'm very happy that if CARLA has a feature such as adjusting the head lights parameters like the Light intensity through Python API as same as the street light does. Can I achieve this by editing the c++ codes before building the carla?

Do you plan to add such a feature for a future release?

![lightPram](https://github.com/carla-simulator/carla/assets/84761257/3c0f2b8a-2b63-439b-82e9-d75c1048710f)

 
Also, maybe it is already possible but I would like to add head lights onto the custom vehicle added to carla and make it turn on/off through python API during the simulation . If it is possible, I would appreciate if anyone helps me to do this.

**Comment by GoodarzMehr** [comment]
The Python API only lets you change the light state (turn on/off low beam, high beam, fog lights, etc). AFAIK you have to write your own C++ code to change the intensities.

You can add lights to a custom vehicle (I've done it successfully for a Mustang I imported), the full instructions are in the tutorial for adding a new vehicle but basically, you first need to create a mesh shaped like the lights, then apply the proper UV texture, export it to .fbx, import it in UE4, apply the light material to the mesh, add the mesh to the blueprint and tag it as emissive, and finally add spot lights similar to the ones in existing blueprints.

**Comment by gsmario** [comment]
Hello! You can follow the documentation to add new lights to your vehicles: 
https://carla.readthedocs.io/en/latest/tuto_content_authoring_vehicles/#lights
Regarding the lights intensity, for now, you can only change the streetlights, if you want to change the vehicle intensity, you should modify the vehicle blueprint, rightnow you can't use the api for that, sadly.

**Comment by gsmario** [comment]
I'm closing the issue, since the problem seems solved.
Thanks for your time.
