### ISSUE TITLE
Issue of low fps inspite of proper architecture

### ISSUE THREAD

**Issue by SoumiDas** [carla-simulator/carla#732]
Hi,

I am facing an issue in running the simulator in server mode. I have a system with the following specs:

Xeon Processor
RAM 32GB
Graphics GeForce GTX 1080Ti
OS: Ubuntu 18.04

The simulator gives a **fps of above 60fps in standalone mode**, but when it's being executed as a **server and client is getting connected to it, the fps is dropping to 3fps** when autopilot mode and images-to-disk option is used and to 6 fps when only autopilot mode is used.

Can you please help me in getting this through?

**Comment by ashwinbhy** [comment]
Please try this with multi-threading , it gives higher fps : [https://drive.google.com/open?id=1JwbcvDaJLKNWtfy4sV0oF2XP32OI1Kgj](url)

**Comment by SoumiDas** [comment]
Thanks!
