### ISSUE TITLE
carla can't run on GPU

### ISSUE THREAD

**Issue by Morizb** [carla-simulator/carla#7324]
Hi, I installed carla in a conda environment on a remote server, installed openGL in a docker container, and used ssh to remotely connect to Mabaxterm and configure X11-forwarding for visualization.

Execute the following command to run carla: CUDA_VISIBLE_DEVICES=0 . /carla/CarlaUE4.sh -prefernvidia -opengl -carla-server -benchmark -fps=5 -nosound --world-port=15302
![image](https://github.com/carla-simulator/carla/assets/44572048/1b37fc0a-38e5-48ef-acf2-2698d3dec5a8)

![image](https://github.com/opendilab/LMDrive/assets/44572048/d876d8df-f7ca-44d8-b36e-290de179650b)

But carla runs without GPU, resulting in rendering no environment.
![image](https://github.com/opendilab/LMDrive/assets/44572048/d229a9a7-a2f7-40f9-afc0-a2a723d9c8d2)

Can you please tell me how to solve this problem？

**Comment by Blyron** [comment]
We recommend to use vulkan, have you tried with it?

**Comment by Morizb** [comment]
> We recommend to use vulkan, have you tried with it?

Thanks for your reply.
I downloaded vulkan, but it reports an error: Cannot find a compatible yulkan driver (ICD)
![0080dfad4054914b9408a31df74368c](https://github.com/carla-simulator/carla/assets/44572048/001953fe-cecc-4c4e-b98c-286f31d56325)

The driver version on the server is: NVIDIA-SMI 515.65.01 Driver Version: 515.65.01 CUDA Version: 11.7
This seems to be because there is a fixed version requirement for the vulkan 1.3 driver, but I don't have permission to change the nvidia driver version on the school server.
Is there any other way to resolve this issue please?

**Comment by joel-mb** [comment]
Hi @Morizb 
It seems that the loader is not finding your Vulkan drivers. Could you try sharing with your docker container the `icd` JSON files:

```bash
--volume=/usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
```

**Comment by joel-mb** [comment]
Closing the issue. Please, feel free to reopen the issue if needed.

**Comment by IranQin** [comment]
> Hi, I installed carla in a conda environment on a remote server, installed openGL in a docker container, and used ssh to remotely connect to Mabaxterm and configure X11-forwarding for visualization.
> 
> Execute the following command to run carla: CUDA_VISIBLE_DEVICES=0 . /carla/CarlaUE4.sh -prefernvidia -opengl -carla-server -benchmark -fps=5 -nosound --world-port=15302 ![image](https://private-user-images.githubusercontent.com/44572048/319617035-1b37fc0a-38e5-48ef-acf2-2698d3dec5a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDUxNDQsIm5iZiI6MTcyNDE0NDg0NCwicGF0aCI6Ii80NDU3MjA0OC8zMTk2MTcwMzUtMWIzN2ZjMGEtMzhlNS00OGVmLWFjZjItMjY5OGQzZGVjNWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNjVlMGVkNWU3Y2U5OWNlMWZiMTlmNTM5ODllM2Y0MmI2MWQxZWE2MDc4YmM0YmQ3YWMyMzJjMDkxMzVhMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nDnvc3OMW86q6SjJLYpoNF5ppsT8eui6dGlXt-Da0L4)
> 
> ![image](https://private-user-images.githubusercontent.com/44572048/319614828-d876d8df-f7ca-44d8-b36e-290de179650b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDUxNDQsIm5iZiI6MTcyNDE0NDg0NCwicGF0aCI6Ii80NDU3MjA0OC8zMTk2MTQ4MjgtZDg3NmQ4ZGYtZjdjYS00NGQ4LWIzNmUtMjkwZGUxNzk2NTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMTU1MTFkZjc4NTQ5YmE5ZGRkNzU3Y2ZlMzI3NzMwZTBhYWVlN2Y3YThkNzFkYjFlY2U2OGY4NTM4OTJiOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DAxFLLkynvcusI_iLMWOTcoKQZR9o14VUPert4eW5gc)
> 
> But carla runs without GPU, resulting in rendering no environment. ![image](https://private-user-images.githubusercontent.com/44572048/319614981-d229a9a7-a2f7-40f9-afc0-a2a723d9c8d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDUxNDQsIm5iZiI6MTcyNDE0NDg0NCwicGF0aCI6Ii80NDU3MjA0OC8zMTk2MTQ5ODEtZDIyOWE5YTctYTJmNy00MGY5LWFmYzAtYTJhNzIzZDljOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOTlkZjRkMWY2ZTMzNTg4MDAxZDU3M2EzZDNjZDhjNjE0ZDAxYTliNGQxYjZjNDU1NjQ4Y2YxYWFhYTY4OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ghT_c-UisvJdmMBW7mFrxJj3xqeQ4gvZBUka__Gdre4)
> 
> Can you please tell me how to solve this problem？

15/5000

Hello, may I ask how you finally solved this problem？
