### ISSUE TITLE
Problem while loading CARLA server

### ISSUE THREAD

**Issue by eds89** [carla-simulator/carla#734]
Hello,

I'm not being able to run CARLA server. The server connection closes 1-2 seconds after being started.  Why does that happen? The ini settings file seems to be loaded correctly as the server correctly binds to the port number specified in it, which in my case is 3997. I'm using the following command line:

``
CarlaUE4.exe -carla-server /Game/Maps/Town01  -carla-settings=settings.ini -benchmark -windowed -resX=480 -resY=240
``

Please see attached pictures.

![carla_server_startingup](https://user-images.githubusercontent.com/17108409/44777230-f54e3e80-ab71-11e8-891d-87a597635da2.PNG)

![carla_server_shutdown](https://user-images.githubusercontent.com/17108409/44777206-dd76ba80-ab71-11e8-803b-ea111800604a.PNG)

Regards,
Eduardo

**Comment by nsubiron** [comment]
Hi @eds89,

Make sure to use the same version of the client and the simulator and only one simulator running in the same port. Check also that no other application is using that port, or the firewall is not blocking it.

**Comment by eds89** [comment]
Hi. How would we go about checking the firewall is not blocking it?

**Comment by eds89** [comment]
Where is CARLA's event log?

**Comment by nsubiron** [comment]
The logs are saved under the same folder as the exe at `CarlaUE4/Saved/` (not 100% sure in Windows is the same path, but otherwise something similar).
