### ISSUE TITLE
Setup.sh Syntax Error

### ISSUE THREAD

**Issue by chandler-scott** [carla-simulator/carla#7348]
Carla build fails after fresh install on Ubuntu 20. Line 262 in $CARLA_ROOT/Util/BuildTools/Setup.sh gives a syntax error. By commenting out the echo, I was able to build successfully.

**Comment by Blyron** [comment]
Hey! We are fixing it in the next pull request
https://github.com/carla-simulator/carla/pull/7412
Are you ok closing the Issue?
