### ISSUE TITLE
UE5/UE4 carla.Client.get_required_files and happens in UE4 too

### ISSUE THREAD

**Issue by Blyron** [carla-simulator/carla#7378]
Reported by Guillermo

**Comment by jorge-kabuto** [comment]
get_required_files was not correctly documented.
The first parameter "folder" is used to look for files in the specified folder inside "CarlaUE4\Content\Maps", and not to specify a place to download the required files. 
The description has been changed to reflect this, recommending leaving the parameter blank ("") if unsure of the server map folder structure. Additionally, a note about the download folder for the required files has been added, that being carlaCache in the user or home root, depending on the OS being used.

https://github.com/carla-simulator/carla/pull/7763
