### ISSUE TITLE
Accessing Map of Simulator

### ISSUE THREAD

**Issue by ajax98** [carla-simulator/carla#740]
How can we access the base map used in Carla 0.9.0? Is there a way to do this using the Python API? I looked at the previous examples which stated to look into the Game directory but I do not have that locally. I am using the pre-compiled version of Carla.

**Comment by ajax98** [comment]
Is there any way I can get the files of thse maps (.umap/png)?

**Comment by nsubiron** [comment]
If you compile Carla from source, the maps are stored in `Unreal/CarlaUE4/Content/Carla/Maps/*.umap`. You can open them from Unreal Editor.
