### ISSUE TITLE
I want to package custom map

### ISSUE THREAD

**Issue by ckad31** [carla-simulator/carla#7432]
CARLA version: 0.9.15
Platform/OS: Ubuntu

I made my own map using a roadrunner.

I ran it successfully in the build version of carla using the make import command.

I want to package this map and run it in Docker environment as well, but I'm not sure about the process.

Please explain it to me.

**Comment by Blyron** [comment]
Here you have in docs;
https://carla.readthedocs.io/en/latest/tuto_content_authoring_maps/#exporting-a-map
You are interested in exporting Exporting a map as part of a complete CARLA package

**Comment by Blyron** [comment]
I am closing this issue, feel free to reopen if something comes up
