### ISSUE TITLE
Why is there no ground point for point cloud data?

### ISSUE THREAD

**Issue by miyangy** [carla-simulator/carla#7434]
When I use Carla to collect point cloud data, why does the visualized point cloud data have no points on the ground?
Thanks!!!

**Comment by JoseM98** [comment]
Hi miyangy,

Can you explain in more detail what configuration you are using so I can help you. For example: what branch of CARLA are you on or what version of CARLA are you using? How are you getting the data from the point cloud?

Thanks,
Jose

**Comment by JoseM98** [comment]
As there has been no response I close the issue. Feel free to reopen it.
