### ISSUE TITLE
Error in carla.readthedocs

### ISSUE THREAD

**Issue by kk2491** [carla-simulator/carla#745]
Hi Guys,

Thanks for providing this awesome project.

I have started building this by following the document in [link](https://carla.readthedocs.io/en/stable/connecting_the_client/) by using the pre-compiled files.

I have noticed a minor error, document says

```
$ ./client_example.py --autopilot
```

This gives runtime error even if the dependency packages are already installed.  

So I tried the below and it works fine.

```
python client_example.py --autopilot
```

Thank you,
KK

**Comment by kk2491** [comment]
@nsubiron Thanks for the quick clarification

**Comment by nsubiron** [comment]
Updated in latest push to documentation.
