### ISSUE TITLE
CarlaUE4.sh fails with segmentation fault

### ISSUE THREAD

**Issue by JasmineDeng** [carla-simulator/carla#747]
I'm running (or trying to run) CARLA on an Ubuntu machine, version 16.04. My openGL version is 3.0. (The OpenGL version string is 3.0 Mesa 18.0.5, and core profile version string is 3.3.)

I installed the last stable release (CARLA 0.8.2), and tried running the script with the command "./CarlaUE4.sh -opengl3", only to get a segfault without a clear error. It fails before any window opens. I'm running it with the flag -opengl3 because of the aforementioned openGL version I have. I'm unclear if it's failing because of some hardware limitations or some other problem.

A full stacktrace is here: https://pastebin.com/6PL3a6gr.

**Comment by nsubiron** [comment]
Hi @JasmineDeng! This is a common issue we see, unfortunately we don't have a solution that works for everyone. Check out issue #757.
