### ISSUE TITLE
Installation and Execution Errors with Carla on WSL

### ISSUE THREAD

**Issue by eyabesbes** [carla-simulator/carla#7482]
Hi,
after following Carla's documentation for installation, I encountered the following errors while executing 
`` ./CarlaUE4.sh: `` on WSL:

``
chmod: changing permissions of '/content/carla/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping': Operation not permitted
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps. ``

I attempted to resolve this issue by running:
`` unset SDL_VIDEODRIVER
./CarlaUE4.sh -vulkan -RenderOffscreen -nosound `` 

I also tried using the [xorg-less / headless]
(https://carla.readthedocs.io/en/0.9.12/adv_rendering_options/#setting-off-screen-mode-version-0912) with `` ./CarlaUE4.sh -vulkan -RenderOffscreen ``
Still, I'm having the same error.

**Comment by joel-mb** [comment]
Hi @eyabesbes 
Could you explain your issue in more detail?
It seems you have permissions issues when making `CarlaUE4-Linux-Shipping` executable. But the server seems to be running.

**Comment by joel-mb** [comment]
Closing the issue. Please, feel free to reopen the issue if needed.
