### ISSUE TITLE
Request to Modify Vehicle Controls During Record Playback

### ISSUE THREAD

**Issue by yagol2020** [carla-simulator/carla#7512]
**CARLA version:** 0.9.13
**Platform/OS:** Linux, Ubuntu 20.04
**Problem you have experienced:** Try to modify the control of Ego during record playing, but not work.
**What you expected to happen:** Ego vehicle change its control, and stop playing record.

I used Carla's video [recording](https://carla.readthedocs.io/en/latest/tuto_G_retrieve_data/#record-and-retrieve-data) function to record a simulation process. The content of this record is roughly a Ego vehicle controlled by `BasicAgent` driving on the `Town02` map.

I use the `client.replay_file` to play this record and obtain the behavior (control) of the Ego vehicle at each time point (tick). However, when I tried to modify the Ego vehicle's controls via the following code, this did not take effect. The Ego vehicle still follows the control in the record.

```python

def replay():
    client = carla.Client("localhost", 2000)
    client.set_timeout(Settings.client_timeout)
    client.load_world(Settings.map)
    world = client.get_world()
    settings = world.get_settings()
    settings.synchronous_mode = True
    settings.fixed_delta_seconds = 1 / Settings.fps
    world.apply_settings(settings)

    # set tm to be sync (async default)
    tm = client.get_trafficmanager()
    tm.set_synchronous_mode(True)
    world.tick()
    client.replay_file(
        "recording.recd", 0, 0, 0
    )
    world.tick()

    vehicle = None
    actors = world.get_actors()
    for actor in actors:
        if actor.type_id.startswith("vehicle"):
            vehicle = actor
            break

    if not vehicle:
        print("[ERROR] Failed to find vehicle actor")
        raise ValueError
    while True:
        spectator = world.get_spectator()
        transform = vehicle.get_transform()
        spectator_transform = carla.Transform(
            transform.location + carla.Location(z=30), carla.Rotation(pitch=-90)
        )
        spectator.set_transform(spectator_transform)

        vehicle_control = vehicle.get_control()
        vehicle_control.steer = 0.5 # Just set the direction to turn left
        vehicle.apply_control(vehicle_control)

        world.tick()
```

So, is there any way to modify the Control of the Ego vehicle during the record playback process? Or switch to **manual control** mode after a certain point in time?

**Related issues:** #3624

**Comment by glopezdiest** [comment]
No, the point of the replay, as it's name implies, is to play something again, exactly as it was recorder in the first place. Any attempt to control a replayed actor is overwritten by the replayer itself
