### ISSUE TITLE
Clean Up Pedestrian folders and BPs

### ISSUE THREAD

**Issue by Blyron** [carla-simulator/carla#7525]
Clean Up Pedestrian folders and BPs

**Comment by DnDare** [comment]
Animations and non-used skeletals have been cleaned up.
We **MUST test and review** with a proper working **manual_control,** (not yet in UE5)
*Node "man_xfull_anim" when removed from BP_walker , offsets the position for GEN2 pedestrians - not removed yet

**Comment by DnDare** [comment]
Gen3 pedestrians have no  DeathAnim yet, first we must modify the BP_walker, so that it can pick different animation sets depending on it's generation


![Image](https://github.com/carla-simulator/carla/assets/57799121/670a33ca-d68a-47c3-94d6-dc704e6cb441)
