### ISSUE TITLE
Dataset for imitation learning

### ISSUE THREAD

**Issue by SExpert12** [carla-simulator/carla#7529]
I want to create a dataset for imitation learning. As my scenario is very specific I want to create a dataset in CARLA myself. How to create the csv file from the RGB images?
Thanks in advance.

**Comment by MarcelPiNacy** [comment]
Hi,

You could use this as a reference for your case.
[](https://stackoverflow.com/questions/67831382/obtaining-rgb-data-from-image-and-writing-it-to-csv-file-with-the-corresponding)

Marcel
