### ISSUE TITLE
Lens distortion shader

### ISSUE THREAD

**Issue by marcgpuig** [carla-simulator/carla#754]
Create a lens distortion post-processing shader.
- [x] For simplicity, only modifies the image. No transform matrix modification (for now).
- [x] Must be able to modify other post-processing effects (like semantic segmentation or depth) if needed.
- [x] Optional [chromatic aberration](https://en.wikipedia.org/wiki/Chromatic_aberration) where the distortion is applied.

**Comment by eds89** [comment]
This is useful. Are you going to make it open-source?

**Comment by marcgpuig** [comment]
Sure! You can find it in branch `issue#754`.
