### ISSUE TITLE
Sidewalk Shader

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7541]
Enhance the sidewalks shaders and textures to make them more photorealistic

**Comment by AinaRoca** [comment]
Improved sidewalks, curbs and gutters using textures from megascans:

(sidewalk and curb) After/Before:

![Image](https://github.com/carla-simulator/carla/assets/119680845/5b5c3e59-65e2-49f0-b0cb-61882fda4d2d)

Examples of the different sidewalks:


![Image](https://github.com/carla-simulator/carla/assets/119680845/0a27ce53-d5fc-4278-9cf6-be12cd92d694)



![Image](https://github.com/carla-simulator/carla/assets/119680845/4aee7406-d27d-410f-a41b-01a14fc796b1)



![Image](https://github.com/carla-simulator/carla/assets/119680845/2fff9245-0480-4913-9e46-3285aab78cf4)



![Image](https://github.com/carla-simulator/carla/assets/119680845/8d3ea891-141c-4989-9416-e730c141e8d4)



![Image](https://github.com/carla-simulator/carla/assets/119680845/f768d320-8782-4728-be71-4dace6be78b4)



![Image](https://github.com/carla-simulator/carla/assets/119680845/757f10fa-db7b-41df-b41d-3d572d2dc6b4)



![Image](https://github.com/carla-simulator/carla/assets/119680845/1784a97a-802e-4631-b174-d24e25ed5cc1)



![Image](https://github.com/carla-simulator/carla/assets/119680845/33d18e16-28e6-4996-9af2-6fecadd23ea4)
