### ISSUE TITLE
Match BP_Sky behaviour with BP_Weather

### ISSUE THREAD

**Issue by AntonioMata1** [carla-simulator/carla#7546]
-Be sure the "BP_Weather_Opt" works exactly like the "BP_CarlaSunSky" at runtime.
- Match Scene Capture from C++ with the postprocces volume values
-

**Comment by Madecu** [comment]
On Paused:

The new lighting system in UE5 currently doesn't use dynamic lighting. Therefore, the BP_Weather behavior doesn't align properly and needs to be simplified to avoid warnings about functionalities that are currently disabled.
