### ISSUE TITLE
Skin Shader

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7548]
Enhance pedestrian's skin shader

Create a new workflow to get better textures to feed metahuman skin shader.

We are going to use a mix between Zbrush and SubstancePainter

**Comment by Madecu** [comment]
Textures to achieve:

Diffuse:

![Image](https://github.com/carla-simulator/carla/assets/54811869/86f10d10-fd96-46a3-82fe-894defc82c3f)

Normal:

![Image](https://github.com/carla-simulator/carla/assets/54811869/913e8cd0-ee96-4957-a425-88a3075f69df)

Roughness:

![Image](https://github.com/carla-simulator/carla/assets/54811869/3c558267-6ed6-4436-ae74-595e028a6dd6)

Cavity:

![Image](https://github.com/carla-simulator/carla/assets/54811869/1f5d1bff-c8eb-4a37-933a-7f7754a004a2)


Masks:

![Image](https://github.com/carla-simulator/carla/assets/54811869/cc33ef3b-da71-4341-bda9-bb2b78db6ed9)

![Image](https://github.com/carla-simulator/carla/assets/54811869/720d0a4e-f662-42c0-aac3-57191faeb078)

**Comment by DnDare** [comment]
There's a new skin master shader and a new SubstancePainter master file.  
Playing with the values we can get a range of skin variation. 
Zbrush pipeline remains the same.
![unnamed](https://github.com/carla-simulator/carla/assets/57799121/2860f8b8-1f8c-44e4-b370-b2c5f4189eed)
![unnamed (1)](https://github.com/carla-simulator/carla/assets/57799121/3bdd225a-02d8-4f4d-85d0-7765b32fb2c4)
![unnamed (2)](https://github.com/carla-simulator/carla/assets/57799121/f2052521-376f-4dc0-a84a-a0dd4a1a8be2)
