### ISSUE TITLE
Ensure condition failed, can't launch Carla

### ISSUE THREAD

**Issue by flschnepf** [carla-simulator/carla#7580]
Hello everyone,

I am currently trying to install carla under ubuntu. I have followed the steps in the instructions and am now faced with the problem that I get error messages when starting unreal and carla. 
![Screenshot from 2024-05-02 13-10-55](https://github.com/carla-simulator/carla/assets/158583663/b1f8fdca-e44e-44bc-8d45-ab55c6603f95)

[carla_errors.txt](https://github.com/carla-simulator/carla/files/15219113/carla_errors.txt)

UE4 opens, but Carla won't start, both with the same error message.
I have installed the latest driver for the RTX 2080 ti and Vulkan also recognizes the graphics card according to "vkcube". 

Does anyone know what the problem is and how I can solve it?

CARLA version: 0.9.15
Platform/OS: Ubuntu 20.04

**Comment by Blyron** [comment]
This issue is known and Carla should start if you press play in editor

**Comment by Blyron** [comment]
What happens when you make launch?
It gets stuck at 95%?

**Comment by flschnepf** [comment]
Yes,

Ensure condition failed: VendorId != EGpuVendorId::Unknown [File:/home/florian/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanDevice.cpp] [Line: 182] 

/home/florian/carla/Util/BuildTools/BuildCarlaUE4.sh: line 205: 13389 Killed                  ${GDB} ${UE4_ROOT}/Engine/Binaries/Linux/UE4Editor "${PWD}/CarlaUE4.uproject" ${RHI} ${EDITOR_FLAGS}
make: *** [Util/BuildTools/Linux.mk:8: launch] Error 137
`Ensure condition failed: VendorId != EGpuVendorId::Unknown [File:/home/florian/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanDevice.cpp] [Line: 182] 

/home/florian/carla/Util/BuildTools/BuildCarlaUE4.sh: line 205: 13389 Killed                  ${GDB} ${UE4_ROOT}/Engine/Binaries/Linux/UE4Editor "${PWD}/CarlaUE4.uproject" ${RHI} ${EDITOR_FLAGS}
make: *** [Util/BuildTools/Linux.mk:8: launch] Error 137`

**Comment by flschnepf** [comment]
![Screenshot from 2024-05-06 13-16-23](https://github.com/carla-simulator/carla/assets/158583663/c9f62c08-b7c3-4e68-b635-2455700fec90)
It loads up to 95% and then the UE loading screen disappears. I do not stop the process.

**Comment by Blyron** [comment]
That issue is related to Unreal Engine with vulkan. I suggest you to retry until it works and shaders are compiled or downgrade nvidia drivers and continue trying,

**Comment by Blyron** [comment]
Please have patient. Those are warnings, not error messages. They are not important. Then, please wait 10-15 mins before pressing play, Unreal is still compiling when it starts, make launch, wait for 15 mins or until console says is not compiling shaders and try again

**Comment by Blyron** [comment]
Are you happy to close this issue? 
Have you fixed your issue?

**Comment by flschnepf** [comment]
Couldn't solve the problem. I think there is an issue witch my pc

**Comment by Blyron** [comment]
We are gonna close this issue as more info is provided
