### ISSUE TITLE
Add new Palm tree

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7584]
![Image](https://github.com/carla-simulator/carla/assets/54811869/17f7a540-0206-4362-8754-633ab96fcdcf)

**Comment by ahlamiki** [comment]
![1](https://github.com/carla-simulator/carla/assets/112707899/678ff97d-7c57-4e14-811d-cf4e74587333)
![2](https://github.com/carla-simulator/carla/assets/112707899/f9a72fed-fd48-472b-8b81-3985b039e630)

**Comment by ahlamiki** [comment]
![3](https://github.com/carla-simulator/carla/assets/112707899/3a8a201c-f119-4307-8492-b9ef156f0a21)

Improved version of the palm tree asset.
