### ISSUE TITLE
Add new FanPalm

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7587]
![Image](https://github.com/carla-simulator/carla/assets/54811869/4f0d07e9-d74a-45fc-a212-2b03ebea732f)

**Comment by ahlamiki** [comment]
![5](https://github.com/carla-simulator/carla/assets/112707899/565f67f4-2efc-4a1a-9888-49dacb162f74)

Improved version of FanPalm asset among the new vegetation.
