### ISSUE TITLE
Add new Bush

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7588]
![Image](https://github.com/carla-simulator/carla/assets/54811869/67d5e105-b0c5-45c9-b792-39c869bf6fdb)

**Comment by ahlamiki** [comment]
![6](https://github.com/carla-simulator/carla/assets/112707899/d306ba76-8732-4adb-9fc1-fed721bd49c5)

Improved version of the bush asset. The top image shows how it was looking before and the bottom image how it looks now.
