### ISSUE TITLE
Add new FlowerPot 1

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7589]
![Image](https://github.com/carla-simulator/carla/assets/54811869/89e7b84a-0ece-4f4b-be8e-38106819b5a7)

**Comment by ahlamiki** [comment]
![2](https://github.com/carla-simulator/carla/assets/112707899/fa9f424d-8b01-4d69-ab6b-c17e8bcff091)

FlowerPot asset replaced by an improved version.
