### ISSUE TITLE
Can we import custom maps using OpenDRIVE maps in CARLA using OSC 2.0?

### ISSUE THREAD

**Issue by saiteja3009** [carla-simulator/carla#7595]
Map (.xodr) not found error.

CARLA version: 0.9.15
Platform/OS: Windows

Problem you have experienced: Not able to import the map exported from RoadRunner (.xodr) in CARLA using OSC 2.0

What you expected to happen: To simulate the scenario by exporting .osc exported code from RoadRunner in CARLA.

Steps to reproduce: Create a scenarion in RoadRunner, import the .osc file in CARLA.

Other information (documentation you consulted, workarounds you tried): Tried with different maps, but only could use the default Town maps provided by CARLA. tried adding the (.xodr) exported map file in all folders of CARLA, but still the map not found error persists.

**Comment by glopezdiest** [comment]
@saiteja3009 Have you tried using the [OpenDRIVE standalone mode](https://carla.readthedocs.io/en/0.9.11/adv_opendrive/#run-a-standalone-map)
