### ISSUE TITLE
Fix Clothes materials

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7604]
![Image](https://github.com/carla-simulator/carla/assets/57799121/089fdbaf-1489-4aaa-a8e7-d6e64ab22363)

![Image](https://github.com/carla-simulator/carla/assets/57799121/fc95deaf-ab2c-4acf-92ed-3a4db4f660c1)

![Image](https://github.com/carla-simulator/carla/assets/57799121/e9823d2e-3bf6-4eb7-ba18-82c2cc363635)

![Image](https://github.com/carla-simulator/carla/assets/57799121/99f7253c-bc83-40f6-955d-89d961da7fc2)

**Comment by DnDare** [comment]
We've changed AsiaM_Ovw,  shirt and pants have been fixed

We didn't found anything wrong with the rest of pedestrianas, no changes made

**Comment by DnDare** [comment]
Not yet merged in Master,  changes are Animations_CleanUp##  branch
