### ISSUE TITLE
Road Decals

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7605]
Create new decals for the road material (oil spills, tire skid marks, tar patches, mud splatters, paint spills, etc)

**Comment by Madecu** [comment]
Done:

- Added decals

ToDo:

- Create a material shader master unique for all decals

**Comment by AinaRoca** [comment]
Road decals finished with the correct master shader assigned.
Those are some of the decals added:


![Image](https://github.com/carla-simulator/carla/assets/119680845/7c929423-d017-48ee-ba2f-13a111d506a9)
