### ISSUE TITLE
Cannot Change Motorcycle/Bicycle Driver

### ISSUE THREAD

**Issue by GoodarzMehr** [carla-simulator/carla#7612]
CARLA version: 0.9.15
Platform/OS: Ubuntu 22.04
Problem you have experienced: I am using the following piece of code to change the driver of motorcycles/bicycles:
```Python
if v_blueprint.has_attribute('driver_id'):
    v_blueprint.set_attribute(
        'driver_id',
        random.choice(v_blueprint.get_attribute('driver_id').recommended_values)
    )
```
However, I have noticed that in practice nothing changes and each motorcycle/bicycle is spawned with the same driver. Could you please confirm if this is the case or if I am doing something wrong?

**Comment by Blyron** [comment]
Yeah. We haven't implemented that yet. We will need to do that in Editor. For now at least

**Comment by 00bix** [comment]
Out of curiosity: When is spawn this bike: https://carla.readthedocs.io/en/0.9.15/catalogue_vehicles/#diamondback-century
I get this rider : 
![Screenshot from 2024-05-10 13-44-51](https://github.com/carla-simulator/carla/assets/73523180/48958a3d-9152-4966-925b-74ad8fc20771)

... How come the vehicles in the catalgoue are not the vehicles i can spawn? Am I missing something?

**Comment by DnDare** [comment]
It's the same vehicle, but we updated the rider.

**Comment by GoodarzMehr** [comment]
Thanks! I saw it in multiple example scripts so I was under the impression that it would change the rider.

I'll leave this issue open for now. Please let me know if/when it gets implemented, since it would help diversify scenarios a tiny bit more.
