### ISSUE TITLE
Boost.Python.ArgumentError: Python argument types in     VehicleControl.__init__(VehicleControl) did not match C++ signature:     __init__(struct _object * __ptr64, float throttle=0.0, float steer=0.0, float brake=0.0, bool hand_brake=False, bool reverse=False, bool manual_gear_shift=False, int gear=0)     __init__(struct _object * __ptr64)

### ISSUE THREAD

**Issue by catarinam93** [carla-simulator/carla#7614]
CARLA version: 0.9.15
Platform/OS: Windows 11

I am implementing an RL algorithm in order to make the car learn to follow a certain route but in my step function I am facing this error:

```
Traceback (most recent call last):
  File "C:\Users\Caty\Documents\Transfer-Reinforcement-Learning-for-Enhanced-Autonomy-in-Vehicles\main.py", line 81, in <module>
    main()
  File "C:\Users\Caty\Documents\Transfer-Reinforcement-Learning-for-Enhanced-Autonomy-in-Vehicles\main.py", line 74, in main
    ppo.learn(total_timesteps=100) # Train the PPO algorithm
  File "C:\Users\Caty\Documents\Transfer-Reinforcement-Learning-for-Enhanced-Autonomy-in-Vehicles\ppo.py", line 315, in learn
    return super().learn(
  File "C:\Users\Caty\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 300, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "C:\Users\Caty\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 195, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "C:\Users\Caty\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 206, in step
    return self.step_wait()
  File "C:\Users\Caty\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 58, in step_wait
    obs, self.buf_rews[env_idx], terminated, truncated, self.buf_infos[env_idx] = self.envs[env_idx].step(
  File "C:\Users\Caty\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stable_baselines3\common\monitor.py", line 94, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
  File "C:\Users\Caty\Documents\Transfer-Reinforcement-Learning-for-Enhanced-Autonomy-in-Vehicles\environment.py", line 276, in step
    ego_vehicle_control = carla.VehicleControl(throttle=linear_velocity, steer=angular_velocity) # DEU ERRO PORQUE PASSEI PARA FLOAT
Boost.Python.ArgumentError: Python argument types in
    VehicleControl.__init__(VehicleControl)
did not match C++ signature:
    __init__(struct _object * __ptr64, float throttle=0.0, float steer=0.0, float brake=0.0, bool hand_brake=False, bool reverse=False, bool manual_gear_shift=False, int gear=0)
    __init__(struct _object * __ptr64) 
```

The step function is the following:

```
    def step(self, action):
        print(action)
        linear_velocity = action[0]  # Access the first element of the action array
        angular_velocity = action[1]  # Access the second element of the action array
        print(type(linear_velocity), type(angular_velocity)) # <class 'numpy.float32'>
        # Apply the control to the ego vehicle
        ego_vehicle_control = carla.VehicleControl(throttle=linear_velocity, steer=angular_velocity) 
        self.ego_vehicle.apply_control(ego_vehicle_control)

        # Get the observations
        observation = self.get_obs()
        distance_to_next_waypoint = observation[0]
        angle_toward_next_waypoint = observation[1] 
        len_route = observation[2]
        collision_occured = observation[3]

        self.calculate_reward(linear_velocity, distance_to_next_waypoint, angle_toward_next_waypoint, len_route, collision_occured)

        return observation, self.reward, self.terminated
```

What should I do?

**Comment by GoodarzMehr** [comment]
The arguments to VehicleControl should be float values, seems like you are passing float arrays to it instead.

**Comment by catarinam93** [comment]
> The arguments to VehicleControl should be float values, seems like you are passing float arrays to it instead.

In that case I get the following:
`Assertion failed: (_clients.find(token.get_stream_id())) ==(_clients.end()), file C:\workspace\carla\LibCarla\cmake\..\source\carla/streaming/low_level/Client.h, line 56` 
:/

**Comment by joel-mb** [comment]
@catarinam93 As @GoodarzMehr has said this error means there is a mismatch in the python arguments types your are sending to the `carla.VehicleControl`. 

From your code it seems you are using a `numpy.float32` type instead of `float`. Please, convert these values to `float` first:

```python
ego_vehicle_control = carla.VehicleControl(throttle=float(linear_velocity), steer=float(angular_velocity)) 
```

**Comment by catarinam93** [comment]
> @catarinam93 As @GoodarzMehr has said this error means there is a mismatch in the python arguments types your are sending to the `carla.VehicleControl`.
> 
> From your code it seems you are using a `numpy.float32` type instead of `float`. Please, convert these values to `float` first:
> 
> ```python
> ego_vehicle_control = carla.VehicleControl(throttle=float(linear_velocity), steer=float(angular_velocity)) 
> ```

Passing as floats I get the following:
Assertion failed: (_clients.find(token.get_stream_id())) ==(_clients.end()), file C:\workspace\carla\LibCarla\cmake\..\source\carla/streaming/low_level/Client.h, line 56

What should I do?

**Comment by GoodarzMehr** [comment]
Can you print the full stack trace please? It's hard to know what happened based on a single line of error.

**Comment by catarinam93** [comment]
> Can you print the full stack trace please? It's hard to know what happened based on a single line of error.

`C:\Users\Caty\Documents\Transfer-Reinforcement-Learning-for-Enhanced-Autonomy-in-Vehicles>python main.py
INFO:  Found the required file in cache!  Carla/Maps/Nav/Town01.bin
INFO: Connection has been setup successfully.
INFO:  Found the required file in cache!  Carla/Maps/TM/Town01.bin
Car Spawned
Path Generated
Sensors Spawned
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Assertion failed: (_clients.find(token.get_stream_id())) == (_clients.end()), file C:\workspace\carla\LibCarla\cmake\..\source\carla/streaming/low_level/Client.h, line 56`

I am using a gymnasium environment btw

**Comment by GoodarzMehr** [comment]
Since the error is somewhat coming out of nowhere, using the [traceback](https://docs.python.org/3/library/traceback.html) package might be helpful in debugging the code. You can use something like this in your main file:

```Python
try:
    ...
except Exception:
    print(traceback.format_exc())
```

Given where the error is coming from, there is a good chance it is unrelated to `VehicleControl` and perhaps more related to how you've set up your Gymnasium environment. I've used `VehicleControl` in a Gymnasium environment before and everything worked fine (I was using Ubuntu though, don't know about Windows).

**Comment by catarinam93** [comment]
> Since the error is somewhat coming out of nowhere, using the [traceback](https://docs.python.org/3/library/traceback.html) package might be helpful in debugging the code. You can use something like this in your main file:
> 
> ```python
> try:
>     ...
> except Exception:
>     print(traceback.format_exc())
> ```
> 
> Given where the error is coming from, there is a good chance it is unrelated to `VehicleControl` and perhaps more related to how you've set up your Gymnasium environment. I've used `VehicleControl` in a Gymnasium environment before and everything worked fine (I was using Ubuntu though, don't know about Windows).

I did that (I think:)) in my main file:
`...
try:
       
        
    # ----------------------------------------------- PPO Algorithm ----------------------------------------------
        ppo = PPO(policy="MlpPolicy", env=env, verbose=1) # Instantiate PPO algorithm
        ppo.learn(total_timesteps=100) # Train the PPO algorithm

        # ppo.save("trained_ppo_model") # Save the trained model
        # ppo.evaluate(env, n_eval_episodes=10) # Evaluate the trained model
    except Exception:
        print(traceback.format_exc())`
        
but the outcome on the cmd was exactly the same :/

**Comment by GoodarzMehr** [comment]
I'm not really sure what to make of this, perhaps someone like @joel-mb from the CARLA team can help you better. There isn't a lot of information in that specific `Client.h` [file](https://github.com/carla-simulator/carla/blob/dev/LibCarla/source/carla/streaming/low_level/Client.h) apart from the fact that a client cannot subscribe twice to the same stream. I also found #7295 but there isn't much information in that either. Based on these two, the only thing I can think of is that perhaps your client is somehow listening to a sensor's datastream twice.

I doubt this new error is related to your use of `VehicleControl`, so one thing you could do is use a debugger (e.g. VSCode's Python Debugger) to see how your code progresses and where the problematic line is. Or you can just put `print()` lines along your code and see what gets printed and what doesn't to see which lines get executed and which line throws out the error.

**Comment by GoodarzMehr** [comment]
This seems ok to me. Since you mentioned the problem comes from the `get_obs()` function (which I don't see in the code you printed), you may want to look further into that function and see if you find anything problematic.

**Comment by catarinam93** [comment]
> This seems ok to me. Since you mentioned the problem comes from the `get_obs()` function (which I don't see in the code you printed), you may want to look further into that function and see if you find anything problematic.

The strangest thing is that the get_obs function is called in the reset function (in the beginning) without any problem. Then it is called inside the step function and that is when the error occurs. 
I will share it anyway:

```
    # Get the observations of the environment
    def get_obs(self):
        distance, angle = self.distance_angle_towards_waypoint()
        self.camera.listen(lambda data: self.process_img(data))
        self.collision_sensor.listen(lambda event: self.on_collision())
        
        while len(self.features_accumulator) == 0:
            time.sleep(0.05)

        if self.features_accumulator:
            average_features = sum(self.features_accumulator) / len(self.features_accumulator) # Get the average of the features
            self.features_accumulator = [] # Reset the accumulator

        # Concatenate and flatten all observation components into a single array
        observation = np.concatenate([average_features.cpu().numpy().flatten(), np.array([distance, angle, len(self.route), self.collision_occured])])
        
        return observation
```

**Comment by GoodarzMehr** [comment]
Ok, I think I've figured out what's going on. You only need to define the `listen()` method for each sensor once, telling it what to do with the data stream. This is why the `get_obs()` function works fine the first time around. When you try to define the `listen()` method a second time around in the 'step()' function you get the error because as I said earlier 'a client cannot subscribe twice to the same stream'.

**Comment by catarinam93** [comment]
That solved the problem!!! Thank you so much!! <3
