### ISSUE TITLE
Alternative download link for Assets

### ISSUE THREAD

**Issue by CaveCCG** [carla-simulator/carla#7622]
CARLA version: 0.9.15
Platform/OS: Windows 11

Hello,

I am in the process of compiling CARLA on my windows machine and I need to download the CARLA assets from the github link. However, the blackbaze server domain where the assets are stored is marked as "potentially malicious" by my organization's firewall, and is refusing access for download.

I already talked to the network security department, and they said that I would need to obtain the archive from another source. 

Could it be possible to provide an alternative download link for the “AdditionalMaps_0.9.15.zip” folder?

Thank you very much and best regards

**Comment by Blyron** [comment]
No there is no alternative, of zipping, 

The alternative is to download source Carla and source assets and build it from source. 

This is the content repo:
https://bitbucket.org/carla-simulator/carla-content/src/master/
This repo should be cloned into:
$CARLA_ROOT/Unreal/CarlaUE4/Content/Carla
