### ISSUE TITLE
light need to be rebuilt in night in 0.9.15

### ISSUE THREAD

**Issue by zhoujiawei3** [carla-simulator/carla#7630]

**Comment by zhoujiawei3** [comment]
CARLA version: 0.9.15
Platform/OS:windows11
Problem you have experienced: when time change to night, not all the light is on. The UE4 editor appears"light need to be rebuilt",and light behavior is different from that in 0.9.14
0.9.14:
![image](https://github.com/carla-simulator/carla/assets/144128162/3f061a30-5b91-4820-9042-9da40ab0a640)

0.9.15:
![image](https://github.com/carla-simulator/carla/assets/144128162/f71516e1-4039-4047-a603-72557549e602)

**Comment by Blyron** [comment]
Use this to fix:
https://www.youtube.com/watch?v=iPN2hWzfmP8&ab_channel=qubodupDev
This does not happen if you makes a package due to Lightning is built during the packaging process

**Comment by zhoujiawei3** [comment]
when I follow the instruction in the video, it appears ![image](https://github.com/carla-simulator/carla/assets/144128162/0778c11e-4ea6-4dec-af0f-364df20e29bd) And the problem still happens.
