### ISSUE TITLE
Update.bat: https://carla-assets.s3.us-east-005.backblazeb2.com/${CONTENT_ID}.tar.gz not work

### ISSUE THREAD

**Issue by HoldenHuan9** [carla-simulator/carla#7644]
![image](https://github.com/carla-simulator/carla/assets/150361238/ec24d1a1-32bb-4792-982c-124224bfe4bb)
![image](https://github.com/carla-simulator/carla/assets/150361238/0b2783b8-0a3e-40d9-aa7d-86fdf194fd7f)

**Comment by Blyron** [comment]
Could you try again, it works fine for me
