### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by Wangkaifeng-2021** [carla-simulator/carla#7649]
CARLA version: 0.9.15
Platform/OS: ubuntu 22.04
Problem you have experienced: When I use /CarlaUE4.sh to launch carla, it flashed and then backed out.
![1](https://github.com/carla-simulator/carla/assets/96483749/4f49f7f5-8ddd-4e46-aeb9-c6744b2d4c8a)

What you expected to happen: Start carla successful.
Steps to reproduce: I followed the steps in the documentation on the official website to install carla (https://carla.readthedocs.io/en/latest/start_quickstart/). After the installation, when I started with the command "./CarlaUE4.sh ", it flashed and then backed out. However, when I launch it with the command "./CarlaUE4.sh -RenderOffscreen", it can launch successful. Can you help me to resolve this problem? Thank you very much!

**Comment by Wangkaifeng-2021** [comment]
I have solved this problem by turning off dGPU-only, hopefully to help some people who have encountered this problem.

**Comment by PabloVD** [comment]
May you also try running with the flag `sh CarlaUE4.sh -prefernvida`?
