### ISSUE TITLE
CarlaUnreal repository not found

### ISSUE THREAD

**Issue by ShruthiVM** [carla-simulator/carla#7654]
Hello all,

**CARLA version:** 0.9.13

**Platform/OS:** Windows

**Problem you have experienced**: I have been trying to clone the Carla fork unreal engine using the syntax git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git but it keeps throwing the error repository not found. Is there a change in the path to this repository?

**What you expected to happen:** Download successfully after GitHub authentication.

**Steps to reproduce:** The steps are as follows in the command prompt run as an administrator
![Error](https://github.com/carla-simulator/carla/assets/169941023/77750009-7dce-4617-82b1-881b3508c5a2)

Thank you for the help in advance.

Best regards,
Shruthi

-->

**Comment by seominseoktech** [comment]
Please use this file. It's a file I received in the Carla Discord channel.

https://drive.google.com/file/d/1zWEoCWDDwuPRZjTK3Q1YY4KA-b3B2iCX/view?usp=sharing

**Comment by PabloVD** [comment]
The repository is still the same as before. Have you linked your github account to the Unreal Engine's account?
If not, please follow [this guide](https://www.unrealengine.com/en-US/ue-on-github) for that.

**Comment by ShruthiVM** [comment]
Hello Seominseokt

> Please use this file. It's a file I received in the CARLA Discord channel.
> 
> https://drive.google.com/file/d/1zWEoCWDDwuPRZjTK3Q1YY4KA-b3B2iCX/view?usp=sharing

Thank you very much for the link. I'll use it if this issue does not get solved.

**Comment by ShruthiVM** [comment]
Hello Pablo,

> The repository is still the same as before. Have you linked your github account to the Unreal Engine's account? If not, please follow [this guide](https://www.unrealengine.com/en-US/ue-on-github) for that.

I had connected my github account to the Unreal engine's account.

Below is the screenshot of the account linking.

![Github](https://github.com/carla-simulator/carla/assets/169941023/53c57424-a251-4f34-9f06-1c390fbbc195)

Also, before the download, the authentication is successful from the github to proceed with the download. Screen shot below for the same.

![authentication](https://github.com/carla-simulator/carla/assets/169941023/95ac26b7-c1f9-4729-a33c-863982d77be1)

I have installed Carla many times before and I have never faced this issue. That is why I want to know if I'm missing out anything new or if anything has changed from before. 

Thank you for your response and the help.

**Comment by ShruthiVM** [comment]
Hello Pablo,

Could you at least provide a zip file of the cloning folder so I can continue with other steps? The one provided by Seominseokt has some missing files in the build file and throws error in GenerateProjectFiles.bat

**Comment by ShruthiVM** [comment]
Hello Pablo,

I resolved the issue. The problem was that I had not joined the epic games organization through the link provided though I had linked the accounts. Now that I did, the download worked perfectly. Thank you for the help.

**Comment by SimonSaysGiveMeSmile** [comment]
> Please use this file. It's a file I received in the CARLA Discord channel.
> 
> https://drive.google.com/file/d/1zWEoCWDDwuPRZjTK3Q1YY4KA-b3B2iCX/view?usp=sharing

Thank you, Pablo! This is really helpful, God bless you!

**Comment by krikitup** [comment]
> Hello Pablo,
> 
> I resolved the issue. The problem was that I had not joined the epic games organization through the link provided though I had linked the accounts. Now that I did, the download worked perfectly. Thank you for the help.

Hi, could you share which link you are talking about? I am trying to install Carla, and having similar issue

**Comment by AbdessamadElK** [comment]
Hello, for anyone facing this problem, please thoroughly follow [https://www.unrealengine.com/en-US/ue-on-github](this guide) until the last step before trying to clone the repository. You should receive an email from GitHub containing a link to join @EpicGames.
