### ISSUE TITLE
Sensors in CARLA unaffected by weather conditions

### ISSUE THREAD

**Issue by TMN11** [carla-simulator/carla#7671]
CARLA version: 0.9.15
Problem you have experienced: Semantic LIDAR sensor seems to be unaffected by weather conditions
What you expected to happen: all sensors data to be influenced by weather conditions, fog and rain in lidar's case
Steps to reproduce: - 

What to do to simulate real life conditions in your realistic simulator?

**Comment by Madecu** [comment]
Hi @TMN11 ,

so far, the weather conditions are just visual representations, they don't affect other sensors yet.

**Comment by qhaas** [comment]
Is this still the case with 0.9.16?  Would be quite useful to have the 'noise' from rain and fog in the other sensors (e.g. DVS)
