### ISSUE TITLE
Carla crash with quality mode low and RenderOffScreen

### ISSUE THREAD

**Issue by Ahmed-Radwan094** [carla-simulator/carla#7675]
CARLA version: 0.9.15
Platform/OS: linux 20.04, NVIDIA GeForce RTX 3080, Driver Version: 535.171.04   CUDA Version: 12.2
The problem you have experienced:
-  Carla repeatedly crashes when running in low-quality mode and rendering off-screen (./CarlaUE4.sh -quality-level=Low -RenderOffScreen). 
- I reproduced the same issue with different machines (GPUs and Cuda versions) running the same OS. 
- On the other hand, Carla doesn't crash with ( ./CarlaUE4.sh -quality-level=Low, ./CarlaUE4.sh, ./CarlaUE4.sh -RenderOffScreen) while running the exact same code.

Can someone direct me to what could be the issue as running Carla in low quality with no screen would help me train RL agents more efficiently?

Thank you.

**Comment by Blyron** [comment]
Which maps are you trying?

**Comment by Ahmed-Radwan094** [comment]
Town10, towno4

**Comment by Ahmed-Radwan094** [comment]
Yes, as I remove some few layers from the map.

**Comment by Blyron** [comment]
NVIDIA Drivers?
Could you share the script you are using to use maps? are you using sensor.imagetodisk function?

**Comment by Ahmed-Radwan094** [comment]
NVIDIA Driver Version: 535.171.04

**Comment by Ahmed-Radwan094** [comment]
`# save world and map from Carla
        self.world = self.client.load_world(self.config['carla']['desired_map'])
        # remove the prop from map to avoid occlusions in bev images
        self.world.unload_map_layer(carla.MapLayer.Props)
        self.world.unload_map_layer(carla.MapLayer.Foliage)
        # remove the traffic lights and poles from map to avoid occlusions in bev images
        traffic_lights_in_the_map = self.world.get_environment_objects(carla.CityObjectLabel.TrafficLight)
        traffic_lights_in_the_map_ids = {traffic_light.id for traffic_light in traffic_lights_in_the_map}
        self.world.enable_environment_objects(traffic_lights_in_the_map_ids, False)
        poles_in_the_map = self.world.get_environment_objects(carla.CityObjectLabel.Poles)
        poles_in_the_map_ids = {pole.id for pole in poles_in_the_map}
        self.world.enable_environment_objects(poles_in_the_map_ids, False)
        # get map information from carla
        self.map = self.world.get_map()
`

**Comment by Ahmed-Radwan094** [comment]
Is there any additional information I can provide?

**Comment by Blyron** [comment]
Logs on the crash. Sorry for being late, we are busy with ue5 migration
