### ISSUE TITLE
How to calculate when the red light will change, considering the traffic light cycles of the traffic light groups?

### ISSUE THREAD

**Issue by seominseokt** [carla-simulator/carla#7684]
CARLA version: 0.9.15
Platform/OS: Windows

- [The traffic light remains red for longer than the time observed with get_red_time() #7625](https://github.com/carla-simulator/carla/issues/7625)

> Traffic lights operate in groups, and when one group's cycle ends, it waits at a red light until the other group's cycle finishes, resulting in a longer duration of the red light.
> For example, if there are two groups (Group 1 and Group 2) and each maintains green for 10 seconds, yellow for 3 seconds, and red for 2 seconds:
> When Group 1's cycle ends, Group 2's cycle begins, during which Group 1 stays on red.
> Thus, Group 1's red light lasts for 2 seconds (Group 1's red) + 10 seconds (Group 2's green) + 3 seconds (Group 2's yellow) + 2 seconds (Group 1's red) = 17 seconds.

I found out that in CARLA, traffic lights stay on longer than the set time.

How to accurately calculate how much time is left until the red light changes, considering the cycles of other traffic lights within the traffic group, as shown in the example?

**Comment by DnDare** [comment]
Hi, 
Please review this answer:
https://github.com/carla-simulator/carla/issues/6121#issuecomment-2129469353

**Comment by seominseokt** [comment]
@DnDare Thank you for your response.
