### ISSUE TITLE
Allow the vehicle to go back

### ISSUE THREAD

**Issue by cmpute** [carla-simulator/carla#77]
I'm unable to back the player car in the simulator, please add support for reversing.

**Comment by felipecode** [comment]
Hey @cmpute 

Actually reverse is supported !  Please check the documentation.
http://carla.readthedocs.io/en/latest/measurements/
Basically you just need to set reverse=True on the
 control message that is sent to the server.
The manual_control.py example on the python client shows the use of reverse.

**Comment by cmpute** [comment]
ok, thank you!

**Comment by maisonhai3** [comment]
The car can go backward.

First, you press `Q` to toggle reverse, then `W` to go backward.
