### ISSUE TITLE
Specify the target operating system type through parameters when make pythonapi

### ISSUE THREAD

**Issue by Czl0223** [carla-simulator/carla#7703]
CARLA version:0.9.14
Platform/OS: ubuntu20.04
I built Carla based on source code in ubuntu20.04 environment and added some custom PythonApi, so the egg and whl files need to be regenerated, but in windows10 environment I need to get both files at the same time because I have some images The recognition algorithm is configured in the Windows environment. Can you add parameters to specify the operating system type when executing make pythonapi?

**Comment by Blyron** [comment]
We do not support Crossplatform compile. So, if we are on Linux we will compile for linux and then if we are on windows we are gonna compile for windows. So currently we are not gonna support this.
