### ISSUE TITLE
Create Fake Interior Building Shader

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7706]
Create new fake interior shadr that simulates glass in front of it for the new nanite buildings

**Comment by DnDare** [comment]
Custom new FakeInterior textures, generated with StableDiffusion.
And  Bottom Store building WIP

Interiors generated:  Convenience Store, Kitchen room, apartmen room, coffe shop

![image01](https://github.com/user-attachments/assets/80874b33-4584-4951-ba86-44ee409c6501)
![image03](https://github.com/user-attachments/assets/9abb47a7-74e7-4d13-9113-7a656abe1ea2)
![image02](https://github.com/user-attachments/assets/4a669f27-f06b-4afb-ac5c-919dae500f04)
![image06](https://github.com/user-attachments/assets/67e88915-690d-4a27-a201-bae29e858b42)
![image05](https://github.com/user-attachments/assets/0ceefb3b-6a66-4b6e-b803-25cf4f93cc8e)

**Comment by DnDare** [comment]
Those that give a better result, are the limited to a Cube space,  deeper rooms or alleys, can give a worse perspective effect

**Comment by DnDare** [comment]
![ScreenShot00008](https://github.com/user-attachments/assets/a6f5af9d-4316-412f-b382-dae1f997c656)
![ScreenShot00007](https://github.com/user-attachments/assets/fb3186f3-98ee-4d49-a034-051757007d28)
HDRI  interior  in Door and Corner nodes ,  bottomStore building
