### ISSUE TITLE
what():  Responding error from function set_actor_simulate_physics: Actor could not be found in the registry.  Actor Id: 2377

### ISSUE THREAD

**Issue by allishawidi** [carla-simulator/carla#7726]
it shows while running my driving autopilot program, also with Aborted (core dumped). i use Carla 0.9.15 and Ubuntu 22.04 anyway.

**Comment by PabloVD** [comment]
Could you provide us with more information on what exactly are you running, with the problematic lines of code?

**Comment by PabloVD** [comment]
Closed due to inactivity. Please feel free to reopen if the issue persists.
