### ISSUE TITLE
Step by step Carla UE5.3

### ISSUE THREAD

**Issue by SiiliMaciej** [carla-simulator/carla#7754]
Hi! I've been trying to set up Carla for 4 days now. I keep encountering some strange errors.

I'm following the guide here: https://docs.google.com/document/d/1aWcoJr-9z_wE6S442UhzC32jUGmN1o42REE7C-4aGYA/edit#heading=h.5piein3604b7

At first, I was downloading Unreal Engine 5.3.0 from source and setting the path to the installation location in environment variables.

Now I'd like to start over to confirm if I'm doing it right.

To begin with, I'd like to make sure I'm doing the following correctly:

    I start with:

`git clone -b ue5-dev https://github.com/carla-simulator/carla.git CarlaUE5`

Then I click Setup.bat.

![Zrzut ekranu 2024-06-04 235233](https://github.com/carla-simulator/carla/assets/171743186/a5adc0f4-0589-48e3-8f72-70037a5be003)

According to the instructions, Unreal Engine with Carla's fork should automatically download after running Setup.bat, but unfortunately, it doesn't happen. Only Carla gets downloaded.

Could I please have the link to Carla Unreal Engine fork? Because I can't find it. I only found it for version 5.1.

So, to summarize, I'd like an explanation of how to download the Carla Unreal Engine fork 5.3. Additionally, please inform me if I should have the Carla Unreal Engine fork 5.3 (approximately 225GB) installed in the CarlaUE5 folder?

Screenshots: from one my attemps from the end of installation

![Zrzut ekranu 2024-06-04 235412](https://github.com/carla-simulator/carla/assets/171743186/5bcc1865-f77b-4d92-8424-897fa7ed055d)

I understand that I didn't have the Carla Unreal Engine fork installed.

Additionally, I encountered these errors:

`FAILED: build.ninja
"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -SC:\CarlaUE5 -BC:\CarlaUE5\Build`

```
CARLA version:  **Carla for UE5**
Platform/OS: **Windows**
Problem you have experienced:
What you expected to happen:
Steps to reproduce:
Other information (documentation you consulted, workarounds you tried):

**Comment by WilliamFlinchbaugh** [comment]
Follow the instructions here to fix your first issue: https://github.com/carla-simulator/carla/issues/4543#issuecomment-2017157107

**Comment by Blyron** [comment]
It's have been issues with the unreal repo.
![image](https://github.com/carla-simulator/carla/assets/53337103/2b311038-f13e-4517-8256-e9ca752067ff)
Now if you follow the UE5.3 build instructions you should be okay 
https://docs.google.com/document/d/1aWcoJr-9z_wE6S442UhzC32jUGmN1o42REE7C-4aGYA/edit#heading=h.5piein3604b7
