### ISSUE TITLE
Issue while Packaging the Custom Map Created Using Digital Twin Tool

### ISSUE THREAD

**Issue by NidhinPPramod** [carla-simulator/carla#7759]
CARLA version:0.9.15 (dev branch)
Platform/OS:Ubuntu 20.04
Problem you have experienced:Automation Tool exit while packaging
![image](https://github.com/carla-simulator/carla/assets/89122094/72d7b70b-7665-4482-ab8c-3a544433d969)
I have created a CustomMap using Digital Twin Tool feature...I'm facing issue while packaging that Map for Ubutnu.
below is my packaging settings:
![image](https://github.com/carla-simulator/carla/assets/89122094/49055711-3fd7-4488-bc60-c2cd1d3d8ee2)

Needed a standalone carla server for my custom map

**Comment by Blyron** [comment]
you have to use make package command, with the DefaultGame.ini edited to use your map. Remember including /CustomMaps/YourMap/Opendrive/ folder as it is need to launch the maps.

**Comment by NidhinPPramod** [comment]
> you have to use make package command, with the DefaultGame.ini edited to use your map. Remember including /CustomMaps/YourMap/Opendrive/ folder as it is need to launch the maps.

Should I add the opendrive path in the Additional non asset directories

**Comment by Blyron** [comment]
Change default map in DefaultGameMode.ini and add your maps to cook, then do a make package

**Comment by NidhinPPramod** [comment]
> Change default map in DefaultGameMode.ini and add your maps to cook, then do a make package
This is my packaging error looks like:
![errrorunreakll](https://github.com/carla-simulator/carla/assets/89122094/4658bf9c-e409-4058-a318-f136bce34a32)
Packaging and Game Mode settings:
![gamemode](https://github.com/carla-simulator/carla/assets/89122094/9d5f8751-47e6-431e-a63f-915489febe6d)
![package sett](https://github.com/carla-simulator/carla/assets/89122094/12b7ad27-f201-4b6f-8313-792b8eabd540)

**Comment by Blyron** [comment]
Look how the ini file is set... 
![image](https://github.com/carla-simulator/carla/assets/53337103/58224a4d-1477-4bf1-95e7-b62ea2213712)

**Comment by Blyron** [comment]
Something on your map is broken we need more info about the packaging

**Comment by NidhinPPramod** [comment]
> Look how the ini file is set... ![image](https://private-user-images.githubusercontent.com/53337103/337214828-58224a4d-1477-4bf1-95e7-b62ea2213712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Njc3MTUsIm5iZiI6MTcxNzY2NzQxNSwicGF0aCI6Ii81MzMzNzEwMy8zMzcyMTQ4MjgtNTgyMjRhNGQtMTQ3Ny00YmYxLTk1ZTctYjYyZWEyMjEzNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5NTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZDU0ZWIwNDI2NjYxNDcxOGIxNDQ2MmRkMWFjOGRiMTFjNmYxZGYzOGE5MjlmYzY2YWVlZDk4NDQxMjIzODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._R4GKI3Y4s8Vcuo2cXTENSpcwn_YUrEzZ7ucJpxhNQc)

**This is my .ini file**


[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=675BF8694238308FA9368292CC440350
ProjectName=CARLA UE4
CompanyName=CVC
CopyrightNotice="Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma de Barcelona (UAB). This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>."
ProjectVersion=0.9.15

[/Script/Carla.CarlaSettings]
+LowRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapRoad.CheapRoad"',MaterialSlotName="Tileroad_Road",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))
+LowRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapSideWalkCurb.CheapSideWalkCurb"',MaterialSlotName="TileRoad_Curb",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))
+LowRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapSideWalk_00.CheapSideWalk_00"',MaterialSlotName="Tileroad_Sidewalk",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))
+LowRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/Ground/SimpleRoad/CheapLaneMarking.CheapLaneMarking"',MaterialSlotName="TileRoad_LaneMarkingSolid",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))
LowLightFadeDistance=1000.000000
LowStaticMeshMaxDrawDistance=10000.000000
LowRoadPieceMeshMaxDrawDistance=15000.000000
+EpicRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/WetPavement/WetPavement_Complex_Road_N2.WetPavement_Complex_Road_N2"',MaterialSlotName="Tileroad_Road",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))
+EpicRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/WetPavement/WetPavement_Complex_Concrete.WetPavement_Complex_Concrete"',MaterialSlotName="TileRoad_Curb",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))
+EpicRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/Ground/SideWalks/SidewalkN4/WetPavement_SidewalkN4.WetPavement_SidewalkN4"',MaterialSlotName="Tileroad_Sidewalk",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))
+EpicRoadMaterials=(MaterialInterface=MaterialInstanceConstant'"/Game/Carla/Static/GenericMaterials/LaneMarking/Lanemarking.Lanemarking"',MaterialSlotName="TileRoad_LaneMarkingSolid",ImportedMaterialSlotName="",UVChannelData=(bInitialized=False,bOverrideDensities=False,LocalUVDensities[0]=0.000000,LocalUVDensities[1]=0.000000,LocalUVDensities[2]=0.000000,LocalUVDensities[3]=0.000000))

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
BuildConfiguration=PPBC_Development
BuildTarget=
StagingDirectory=(Path="")
FullRebuild=False
ForDistribution=False
IncludeDebugFiles=True
BlueprintNativizationMethod=Disabled
bIncludeNativizedAssetsInProjectGeneration=False
bExcludeMonolithicEngineHeadersInNativizedCode=False
UsePakFile=True
bUseIoStore=False
bGenerateChunks=False
bGenerateNoChunks=False
bChunkHardReferencesOnly=False
bForceOneChunkPerFile=False
MaxChunkSize=0
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path="")
PakFileCompressionFormats=
PakFileAdditionalCompressionOptions=
HttpChunkInstallDataVersion=
IncludePrerequisites=True
IncludeAppLocalPrerequisites=False
bShareMaterialShaderCode=False
bDeterministicShaderCodeOrder=False
bSharedMaterialNativeLibraries=False
ApplocalPrerequisitesDirectory=(Path="")
IncludeCrashReporter=False
InternationalizationPreset=English
-CulturesToStage=en
+CulturesToStage=en
LocalizationTargetCatchAllChunkId=0
bCookAll=False
bCookMapsOnly=False
bCompressed=False
bSkipEditorContent=False
bSkipMovies=False
-IniKeyBlacklist=KeyStorePassword
-IniKeyBlacklist=KeyPassword
-IniKeyBlacklist=rsa.privateexp
-IniKeyBlacklist=rsa.modulus
-IniKeyBlacklist=rsa.publicexp
-IniKeyBlacklist=aes.key
-IniKeyBlacklist=SigningPublicExponent
-IniKeyBlacklist=SigningModulus
-IniKeyBlacklist=SigningPrivateExponent
-IniKeyBlacklist=EncryptionKey
-IniKeyBlacklist=IniKeyBlacklist
-IniKeyBlacklist=IniSectionBlacklist
+IniKeyBlacklist=KeyStorePassword
+IniKeyBlacklist=KeyPassword
+IniKeyBlacklist=rsa.privateexp
+IniKeyBlacklist=rsa.modulus
+IniKeyBlacklist=rsa.publicexp
+IniKeyBlacklist=aes.key
+IniKeyBlacklist=SigningPublicExponent
+IniKeyBlacklist=SigningModulus
+IniKeyBlacklist=SigningPrivateExponent
+IniKeyBlacklist=EncryptionKey
+IniKeyBlacklist=IniKeyBlacklist
+IniKeyBlacklist=IniSectionBlacklist
+MapsToCook=(FilePath="/Game/CustomMaps/Hoodi2Btp/Hoodi2Btp")
+MapsToCook=(FilePath="/Game/CustomMaps/Hoodi2Btp/Hoodi2Btp/OpenDrive")
+DirectoriesToAlwaysCook=(Path="/Game/Carla/Static/GenericMaterials/Licenseplates/Textures")
+DirectoriesToAlwaysCook=(Path="/Game/Carla/Static/Car/4Wheeled/ParkedVehicles")
+DirectoriesToAlwaysStageAsUFS=(Path="Carla/Maps/OpenDrive")
+DirectoriesToAlwaysStageAsUFS=(Path="Carla/Maps/Nav")
+DirectoriesToAlwaysStageAsUFS=(Path="Carla/Maps/TM")
+DirectoriesToAlwaysStageAsUFS=(Path="Carla/Config")

**Comment by Blyron** [comment]
+MapsToCook=(FilePath="/Game/CustomMaps/Hoodi2Btp/Hoodi2Btp/OpenDrive")
this incorrect, this should be a DirectoriesToAlwaysStageAsUFS
+DirectoriesToAlwaysStageAsUFS=("CustomMaps/Hoodi2Btp/Hoodi2Btp/OpenDrive")

**Comment by NidhinPPramod** [comment]
> Something on your map is broken we need more info about the packaging
**cook file**
[Cook-2024.06.06-15.33.48.txt](https://github.com/user-attachments/files/15613361/Cook-2024.06.06-15.33.48.txt)
**log file**
[Log.txt](https://github.com/user-attachments/files/15613362/Log.txt)

**Comment by Blyron** [comment]
This is an issue related with Unreal itself, i won'tbe able to help you. Is related with the seettings of the generated mesh. 
Sorry for this. Look for help in Unreal forum

**Comment by Blyron** [comment]
The issue is the mesh itself, one of the generated meshes seems to have an issue. We are still working on DT tool as it was a very first version. We are not able to help right now. But now we are aware of this issue we will look into that in next revisions of DT Tool.

**Comment by NidhinPPramod** [comment]
> The issue is the mesh itself, one of the generated meshes seems to have an issue. We are still working on DT tool as it was a very first version. We are not able to help right now. But now we are aware of this issue we will look into that in next revisions of DT Tool.

Is there any alternate solution I can use ,to run this custom map as a standalone server

**Comment by Blyron** [comment]
Not right now. Sorry. The workaround it make it run in editor mode.

**Comment by NidhinPPramod** [comment]
> Not right now. Sorry. The workaround it make it run in editor mode.

Is there any option like i can run this map server in my pc and the client from other pc can use it..like using IP address or something

**Comment by Blyron** [comment]
Which is your GPU?

**Comment by NidhinPPramod** [comment]
> Which is your GPU? You cannot connect from another computer.

Nvidia RTX A5000
Is there any way like i can use this custom map in another pc?

**Comment by NidhinPPramod** [comment]
> > Which is your GPU? You cannot connect from another computer.
> 
> Nvidia RTX A5000 Is there any way like i can use this custom map in another pc?Also, when can i expect the fix in DT Tool

**Comment by Blyron** [comment]
> > Which is your GPU? You cannot connect from another computer.
> 
> Nvidia RTX A5000 Is there any way like i can use this custom map in another pc?Also, when can i expect the fix in the DT Tool

You can use the map in editor mode. What you cannot do is create a package with it. If you want to, you have to fix the conflict mesh on your own. ( I do not know how to fix it, look at Unreal forum):

When can you expect the fix for DT Tool? 
Do not know. Not time determined.
