### ISSUE TITLE
Does CARLA work on MacOS?

### ISSUE THREAD

**Issue by shyamalschandra** [carla-simulator/carla#7762]
CARLA version: latest
Platform/OS: MacOS Sonoma
Problem you have experienced: compatibility
What you expected to happen: work
Steps to reproduce: use the steps with the brew instead of the apt required packages
Other information (documentation you consulted, workarounds you tried): n/a

**Comment by Madecu** [comment]
Hi @shyamalschandra ,
there is no official support for MacOS. The community has been trying to implement a MacOS compatibility.

**Comment by shyamalschandra** [comment]
Thanks, @Madecu, for your response!  I would love to port it to MacOS very soon.
