### ISSUE TITLE
fatal: repository 'https://github.com/CarlaUnreal/UnrealEngine.git/' not found

### ISSUE THREAD

**Issue by ExPl0i** [carla-simulator/carla#7775]
Hi, everyone!
I have a problem with intalling CARLA on Windows. I used the instructions from the official website https://carla.readthedocs.io/en/latest/build_windows/
At the Unreal Engine installation stage, I have this error:
![image](https://github.com/carla-simulator/carla/assets/116000343/b21232f8-e140-46a8-b45b-4400d92f14db)
I authorized my GitHub account with my Epic Games account and accepted the organization's invitation. At this point, I have been added to the secondary organization https://github.com/EpicGames-Mirror-A like all new users.
So, can someone help me? I would be very grateful for any help in solving this problem. Thank you in advance.

**Comment by ExPl0i** [comment]
> I'm having exactly the same problem. Could this post be related to the problem? https://forums.unrealengine.com/t/maintenance-on-the-epic-games-github-organization-june-2024/1891135

Hi jhensantos! I think this post and the problem may be related. If that is indeed the case, then all we have to do is wait. I created this issue in the hope that some of the people who are able to solve this problem will pay attention to it or will be able to suggest a solution.

**Comment by sonorousduck** [comment]
Yeah, it looks like I have the same issue. Since they created a new team on Monday that uses a different forked Unreal Version it isn't working with the original Unreal Engine. Hopefully, they fix this soon...

**Comment by Bingyu-Huang** [comment]
Same problem... I tried to download the original unreal 4.26 but there's something different from carla version.

**Comment by rmrtcla** [comment]
Is there any way for the Carla maintainers to add the https://github.com/CarlaUnreal/UnrealEngine.git repo to the https://github.com/EpicGames-Mirror-A Org on Github?

**Comment by rmrtcla** [comment]
Or, different idea: Fork UE from here https://github.com/EpicGames-Mirror-A/UnrealEngine to let's say https://github.com/CarlaUnreal/UnrealEngine-Mirror-A.git and then push there from https://github.com/CarlaUnreal/UnrealEngine.git once in a while?

**Comment by ExPl0i** [comment]
Hi rmrtcla! You suggested some good ideas. I hope the Carla maintainers will pay attention to them and try to implement them.

**Comment by Blyron** [comment]
![image](https://github.com/carla-simulator/carla/assets/53337103/cdd4fcac-2c4b-4dd7-b341-cf94e8e414f2)
