### ISSUE TITLE
Questions about tools and Carla in Docker

### ISSUE THREAD

**Issue by Alexcel-Harry** [carla-simulator/carla#7776]
Hi everyone,

I have a couple of questions regarding tools and Carla built in Docker (the Carla that is built according to this tutorial: [https://carla.readthedocs.io/en/latest/build_docker_unreal/]).

1. **Digital Twin Tool for Docker:**
   - Is the Digital Twin Tool available for use with the Carla in Docker? If not, are there any plans or workarounds to integrate it with Docker?

2. **UE5 Engine for Docker Release:**
   - Is the new integration of UE5 available for Carla in Docker? If it is not currently available, could you provide an estimated timeline or any relevant details regarding its potential Docker support?

Thank you！

**Comment by Blyron** [comment]
1 Digital Twin can be run only in Editor Mode. So if you get to build Carla from source in Docker you should be able to run it. 
2 Not right now, no timeline esitmated
