### ISSUE TITLE
Question about traffic light control

### ISSUE THREAD

**Issue by lindsaymorgan** [carla-simulator/carla#7779]
Hello~ I am new to carla and I'm currently learning about setting up traffic lights in scenes. I understand that traffic lights affect cars through bounding boxes.  My question is, is it possible for carla to implement a multi-directional lane scenario where the traffic lights allow traffic in one direction while disallowing traffic in the other? I draw an example in sumo, as shown below.
![image](https://github.com/carla-simulator/carla/assets/25105493/26913924-aea5-4084-b441-40ac2c87ee35)

**Comment by Madecu** [comment]
Hi @lindsaymorgan ,
What you mentioned seems very interesting. We are keen to implement new intersections to have more varied scenarios that are not currently in CARLA. We will certainly consider the example you provided. Unfortunately, at the moment, implementing these changes is not in our short-term roadmap, but it is something we intend to add in the future.

Thank you very much.
