### ISSUE TITLE
Depth map information

### ISSUE THREAD

**Issue by mhusseinsh** [carla-simulator/carla#778]
I read in the [documentation](https://carla.readthedocs.io/en/latest/cameras_and_sensors/#camera-depth-map) that the maximum depth is 1 km, so this means that any object after 1 km is not detected with the depth sensor, is this also the same for `CameraRGB `and `CameraSemanticSegmentation`, so all objects far than 1 km are not logged in the 3 cameras ?

**Another question:**
How do you deal with the size, action of objects for the depth information ?
I will give two examples here:
**_Vehicle_**
If a vehicle is coming towards my agent from the opposite direction (assuming I can see the whole vehicle), does the front of the vehicle has a different depth that its rear ? or the whole vehicle is logged as one object in depth wise ?

**_Pedestrian_**
If a pedestrian is coming towards me also, and he is walking, so one leg is leading the other, does every pixel for the person has its own depth ? because in this case, one leg will be closer than the other, or the whole pedestrian is logged as a single object also ?

**Comment by nsubiron** [comment]
The 1km mentioned in the documentation only applies to the depth codification, but in any case our cities are way shorter than one kilometer. The draw distance of the cameras depends on the quality settings and LOD of each object, in Epic mode (default) we tried to adjust them to meet a good balance between performance and visual quality.

You can see in the generated images that the depth is calculated per pixel and not per object.
