### ISSUE TITLE
Why does this white lane line separate the bidirectional traffic in Town07?

### ISSUE THREAD

**Issue by lingyixia** [carla-simulator/carla#7789]
![Screenshot from 2024-06-17 10-23-58](https://github.com/carla-simulator/carla/assets/32219730/efeda827-5ba2-44b1-b2ae-a726aa240d51)

**Comment by AinaRoca** [comment]
Dashed lane markings indicate that it is safe and permissible to pass other vehicles. On a bidirectional road, this means that drivers can temporarily cross into the opposite lane to overtake slower vehicles, provided it is safe to do so. It prevents slow-moving traffic from causing delays.
