### ISSUE TITLE
When using a remote headless server to host the Carla server and running the client locally, an issue arises. 

### ISSUE THREAD

**Issue by ccconquer** [carla-simulator/carla#7791]
When running manual_control.py, the pygame window displays correctly on the local machine. However, when running programs like generate_traffic.py that do not involve pygame display, only text output appears locally with no image display. How can I achieve image display locally in such cases? Do you have any suggestions or solutions?
![2024-06-17_17-22](https://github.com/carla-simulator/carla/assets/111716969/ea65c4d8-3b33-41a2-a767-85705a46a479)

**Comment by PatrickPromitzer** [comment]
You could run both scripts.
1.) start carla server
2.) start generate_traffic.py
3.) start manual_control.py

You are not limited to only one client connection.

**Comment by glopezdiest** [comment]
By default, the spectator is the only way to have visual feedback of the simulation. The manual control is just a special client that transforms the sensor data into image for you to see. The solution proposed by @PatrickPromitzer is the best and most common one used
