### ISSUE TITLE
when the CARLA server is hosted on a remote headless server and the Python API client runs locally

### ISSUE THREAD

**Issue by ccconquer** [carla-simulator/carla#7792]
In CARLA, when the CARLA server is hosted on a remote headless server and the Python API client runs locally, where should the environment be set up if the Python API program involves deep learning (the server or the local) ? Which GPU and computational resources are used, the ones on the server or the ones on the local machine?

**Comment by Aperiss** [comment]
The simulation is run on the server side, so it will use the resources of the server for that part of the environment, but all the deep learning logic will be handled locally in the machine that runs the Python API.
