### ISSUE TITLE
Can a headless remote server serve as both the CARLA server and the CARLA client?

### ISSUE THREAD

**Issue by ccconquer** [carla-simulator/carla#7793]
Can a headless remote server serve as both the CARLA server and the CARLA client, effectively hosting the entire CARLA setup on the remote headless server?

**Comment by ccconquer** [comment]
Running ./CarlaUE4.sh -carla-rpc-port=2000 -RenderOffScreen -graphicsadapter=1 -quality-level=Low on a headless server can start the server. When the client runs python3 generate_traffic.py --host 10.80.42.158 -p 2000, it produces results but no image is displayed. Are there any methods or suggestions to display the running images/videos, similar to remote streaming to some software?
![2024-06-17_18-53](https://github.com/carla-simulator/carla/assets/111716969/ad431822-9b74-4ffd-a846-682a0af9973a)
![2024-06-17_18-53_1](https://github.com/carla-simulator/carla/assets/111716969/a6630bb1-e449-427f-ab69-b472ebeb77b6)
![2024-06-17_18-53_2](https://github.com/carla-simulator/carla/assets/111716969/c25bc45e-1ca8-4cc6-ba4e-9a03613af119)

**Comment by PatrickPromitzer** [comment]
I guess you connect to the server with shh.

if you use Linux, try using 
```
ssh -X user@IP
```
The "-X" will forward X11 to the client.
I have an different command saved, but I forgot the behavior of the "-C" flag
```
ssh –Y –C user@IP
```

You need to set the forwarding permission on the server, or it will give an error.
```
xhost +
``` 

on windows, you need to install a software to emulate the X11 server.
[VcXsrv Windows X Server](https://sourceforge.net/projects/vcxsrv/)

**Comment by ccconquer** [comment]
Thank you so much!! I'll try it.

**Comment by Aperiss** [comment]
Thanks @PatrickPromitzer for the answer, we are closing this issue, but feel free to open if you run into any other issues.
