### ISSUE TITLE
Gen2 Female Euro Overweihgt

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7811]
Redo skin textures with the new workflow

![Image](https://github.com/carla-simulator/carla/assets/54811869/d0e099c0-769e-4ddd-a089-f1ba56ecbe5f)

**Comment by DnDare** [comment]
![Image](https://github.com/carla-simulator/carla/assets/57799121/abeb932a-d397-4b60-bc42-a17bd1e581d5)
![Image](https://github.com/carla-simulator/carla/assets/57799121/62893769-942a-467e-ae4d-f7d7b36d6f60)

Old shader (lower) vs New shader (higher)
