### ISSUE TITLE
Gen2 Female Afro Overweight

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7812]
Redo skin textures with the new workflow

![Image](https://github.com/carla-simulator/carla/assets/54811869/03e20521-b7b1-4e51-8299-96d4b35e66ed)

**Comment by DnDare** [comment]
![Image](https://github.com/carla-simulator/carla/assets/57799121/944e15dd-2ae1-41f1-a080-0a564dade2c9)

from left to right,
new shader with no make-up values, 
new shder with strong makeup, 
new shader with light makeup, 
old shader

**Comment by Madecu** [comment]
Fixing the shadows in direct daylight
