### ISSUE TITLE
Gen2 Female Afro 02

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7814]
Redo skin textures with the new workflow

![Image](https://github.com/carla-simulator/carla/assets/54811869/61bbdbd8-1c55-4ae9-8188-c565d1728cf0)

**Comment by DnDare** [comment]
![Image](https://github.com/user-attachments/assets/135aa53a-eb77-4049-8d2f-fd7450ff1837)
![Image](https://github.com/user-attachments/assets/04121a64-d167-4e04-a2c9-985140ae7e85)
