### ISSUE TITLE
Gen2 Female Euro

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7815]
Redo skin textures with the new workflow

![Image](https://github.com/carla-simulator/carla/assets/54811869/6cf9ff86-5c43-4346-a1f3-1cc60a69056b)

**Comment by DnDare** [comment]
Left : Updated skin shader  vs Right, Old shader

![Image](https://github.com/user-attachments/assets/19c89a32-52e0-4ee3-9c7f-14500bbb4525)
![Image](https://github.com/user-attachments/assets/530ef35c-dcb4-481a-b582-f67e02715621)

**Comment by DnDare** [comment]
Both variations with updated skin shader

![Image](https://github.com/user-attachments/assets/c945ac5f-1f33-4279-869e-91a3c92eb6dd)
