### ISSUE TITLE
Gen2 Male Asian

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7817]
Redo skin textures with the new workflow

![Image](https://github.com/carla-simulator/carla/assets/54811869/00b77f6b-0349-489a-bf51-0b2d75cfbce1)

**Comment by DnDare** [comment]
Updated skin shader 


![Image](https://github.com/user-attachments/assets/f10ac7a8-fd74-4ba6-af02-031c4237a332)
![Image](https://github.com/user-attachments/assets/74ebc6ec-2d2e-48ef-b554-93c7b7a02c09)
