### ISSUE TITLE
Gen2 Male Euro Overweight

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7818]
Redo skin textures with the new workflow

![Image](https://github.com/carla-simulator/carla/assets/54811869/9772beb0-0d7a-4b34-bd2c-1f6f877fef01)

**Comment by DnDare** [comment]
![Image](https://github.com/user-attachments/assets/d87a2a11-958d-4b99-aa74-11e7389d2dd1)
![Image](https://github.com/user-attachments/assets/dd212ef1-093e-4999-a0d3-3b78a4e54ffe)

Updated Skin shader to G23,  UE5   linux
