### ISSUE TITLE
Time consumption of the first "make launch"

### ISSUE THREAD

**Issue by JingyanXing** [carla-simulator/carla#7825]
CARLA version: 0.9.12
Platform/OS: Ubuntu20.04
Problem you have experienced: When I use the 'make launch' command, the CPU runs at full capacity for the first few minutes. However, when the progress reaches 95%, the CPU usage drops sharply, but there are no error messages. Is this normal? Also, how long does the first compilation usually take?
![20240619-221756](https://github.com/carla-simulator/carla/assets/122534171/3446bbfd-ef9a-4f86-b043-3dc028231d10)

**Comment by Blyron** [comment]
Yes it's normal
https://www.reddit.com/r/unrealengine/comments/n1c4zk/ue_4261_stuck_at_95/
Just let it work
