### ISSUE TITLE
Cloning into 'UnrealEngine'... remote: Repository not found. fatal: repository 'https://github.com/CarlaUnreal/UnrealEngine.git/' not found

### ISSUE THREAD

**Issue by omegaxy1124** [carla-simulator/carla#7826]
Dear people:
OS: Windows 11
can not run this thing:   git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git 
issue: Cloning into 'UnrealEngine'...
remote: Repository not found.
fatal: repository 'https://github.com/CarlaUnreal/UnrealEngine.git/' not found
I am connected to my Git from Unreal Engine as it shows in the apps and accounts and I followed the instruction to a T and I have the organization badge on my profile but i just can't get it working it keeps giving me the same error: C:\>    git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git
Cloning into 'UnrealEngine'...
remote: Repository not found.
fatal: repository 'https://github.com/CarlaUnreal/UnrealEngine.git/' not found
any help would be appreciated

**Comment by JingyanXing** [comment]
the same for me

**Comment by omegaxy1124** [comment]
Yeah hopefully they fix this soon cause i spent about 3 hours wracking my brain thinking i messed something up before i figured out this was outside my control.

**Comment by PatrickPromitzer** [comment]
For me, it only works with a personal access token, but the last time I tried to clone CarlaUnreal was last week.
[https://github.com/settings/tokens](https://github.com/settings/tokens)

**Comment by omegaxy1124** [comment]
Yep still broken, no clue if there is an alternative way to do this.

**Comment by Fitz-Lee** [comment]
Hey Brothers. the Unreal Engine author replied!
![image](https://github.com/carla-simulator/carla/assets/57517997/942b3a2c-a425-4c84-9c22-ac3a92785410)

**Comment by rmrtcla** [comment]
Works for me now. I didn't get the invite to join the original EpicGames org on Github automatically (or maybe I was just too impatient), so I tried unlinking and then linking again my Epic account back to Github, and then it worked (about 3h ago). Thanks all.

**Comment by omegaxy1124** [comment]
thank you everyone the problem is now fixed.
