### ISSUE TITLE
question for importing custom maps in CARLA

### ISSUE THREAD

**Issue by SongKun2023** [carla-simulator/carla#7829]
<!--

Thanks for contributing to CARLA!

If you are reporting an issue, please use the following outline:

CARLA version: 0.9.15
Platform/OS: win10
Problem you have experienced:
Hello , sir. When I import my road network into CARLA. I would like to know if it is possible to import the .xodr file and the .fbx file into the release version of CARLA

**Comment by RodrigoVillarias** [comment]
Hello! yes it is possible to import custom maps at the moment, I leave the link to the documentation, so you can use it as a guide.

https://carla.readthedocs.io/en/latest/tuto_M_custom_map_overview/

**Comment by SongKun2023** [comment]
OK,  thank you for you reply. I see the documentation, which shows that it can not to import a custom map if  I use a package version of CARLA in Windows.
