### ISSUE TITLE
Modify the effective detection range of the depth camera

### ISSUE THREAD

**Issue by Czl0223** [carla-simulator/carla#7835]
The current effective detection distance of the depth camera is 1000m, and I need to modify the maximum detection distance of the depth camera to 5000m in the scene I built myself, how should I change it? I didn't find the corresponding algorithm logic in the depthcamera.cpp of the Carla source code, where should I make the corresponding changes?

**Comment by Blyron** [comment]
DepthCamera uses the depth buffer of Unreal Engine itself. You can find depth values in post process materials at 
/Carla/PostProcessingMaterials/DepthEffectMaterial
