### ISSUE TITLE
Procedural generation of cities

### ISSUE THREAD

**Issue by truncs** [carla-simulator/carla#7836]
Is there any tool available that allows for quick generation of cities from scratch? Blender seems to have a tool called [ICity](https://blendermarket.com/products/icity) ([youtube](https://www.youtube.com/watch?v=qF5LU70M8Qo&t=376s)). Would it be possible to support this by importing the cities generated in this tool to Carla or having a similar tool for Carla?

**Comment by Blyron** [comment]
We have https://carla.readthedocs.io/en/latest/adv_digital_twin/ which is very early development
