### ISSUE TITLE
Add VR to CarlaUE

### ISSUE THREAD

**Issue by Ikaros520520** [carla-simulator/carla#7837]
Hello everyone.

What I want to do: the experimenter wears a motion capture device to control a pedestrian blueprint model walking.
I place the camera at the pedestrian blueprint head position. When the experimenter starts walking, the pedestrian model starts walking as well. But the VR camera remains in place. It does not follow the pedestrian model.
What can I do to make the VR camera bound to the pedestrian blueprint?

Device:
PNS(https://www.noitom.com/)
VR headset: htc vive pro2 
UE: 4.26

**Comment by Blyron** [comment]
Hello you will need to create a special sensor to implement this. 
Moreover we are not aimming to support VR applicattions, there is VR implementation from the community;
look at https://github.com/carla-simulator/carla/discussions/5667

**Comment by donghwan-shin** [comment]
Hi, I also looked for the same and found this: https://github.com/HARPLab/DReyeVR
I haven't tried it yet, but it looks like a solution.

**Comment by ajay1606** [comment]
@donghwan-shin Unfortunately, VIVE doesnt provides any support SDK for UE 4.26.

Do you have any alternative suggestions ?

**Comment by donghwan-shin** [comment]
Sorry, I don't have any more good suggestions.
