### ISSUE TITLE
Control over multiple vehicles in batch mode

### ISSUE THREAD

**Issue by kloud1989** [carla-simulator/carla#784]
With the latest version (0.9.0), it is now possible to generate vehicles from the client side and control each one of them. But there is no way to control them in a single RPC call. I noticed that the RPC calls issued to control vehicles are high performance cost ops. If there are multiple vehicles to control in one client, the performance is not so good. Maybe control in a batch mode can help? Also it is weird to see changes of vehicles one after another. With batch sync mode, it would be more realistic to see the changes of all vehicles at the same time.

Child of #630.

**Comment by nsubiron** [comment]
This is planned, but not yet implemented.

**Comment by nsubiron** [comment]
Still not implemented, but on next release 0.9.1 apply control/transform functions are non-blocking and thus much cheaper. It's something.

**Comment by kloud1989** [comment]
It seems great. Thanks for your effort @nsubiron ! What I mostly concerned about is the simulation performance. This fix should solve my problem. 

By the way, I'm curious about if sync mode is supported in the next release?

**Comment by nsubiron** [comment]
Sync mode is not yet ready. There is though a method for the client to wait for a simulator update, 
```py
timestamp = world.wait_for_tick()    # block until an update is received
# or
world.on_tick(lambda timestamp: ...) # execute callback on each new update
```
but not yet the other way around. We definitively want to add it, but having a sync mode in a multi-client environment is a bit more complicated that what we had.

**Comment by kloud1989** [comment]
If it is not possible to support sync mode with multiple clients, is it possible to configure the server in single-client mode, and support sync mode with that? In my case, I only need 1 client, but with multiple controllable vehicles. I'm not sure if this suggestion agrees with your roadmap, but without sync mode, it seems not possible to integrate Carla with other traffic simulators like SUMO.

**Comment by Sakrust** [comment]
This is indeed a key feature to use Carla with any other tool.
