### ISSUE TITLE
Issues when attempting to compile API Client

### ISSUE THREAD

**Issue by AlexMiamiACN** [carla-simulator/carla#7840]
<!--

Thanks for contributing to CARLA!

If you are reporting an issue, please use the following outline:

CARLA version: 1.2.37
Platform/OS: Windows
Problem you have experienced: 

C:\Carla\carla-dev>make PythonAPI
-[BuildUE4Plugins]: [Batch params]: --build --all
HEAD is now at 260273d Correct descriptor
-[BuildUE4Plugins]: STREETMAP has been successfully installed in "C:\Carla\carla-dev\Unreal\CarlaUE4\Plugins\"
-[Setup]: [Batch params]: --boost-toolset msvc-14.2 --generator "" --all
-[Setup]: Asynchronous jobs:  16
-[Setup]: Boost toolset:      msvc-14.2
-[Setup]: Generator:          "Visual Studio 16 2019"
-[Setup]: Install directory:  "C:\Carla\carla-dev\Build\"
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\"
    -[install_zlib]: A zlib installation already exists.
    -[install_zlib]: Delete "C:\Carla\carla-dev\Build\zlib-install\" if you want to force a rebuild.
    -[install_zlib]: Exiting...
The system cannot find the path specified.
        0 file(s) copied.
-[Setup]: Installing libpng...
    -[install_libpng]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --zlib-install-dir "C:\Carla\carla-dev\Build\zlib-install\"
    -[install_libpng]: A libpng installation already exists.
    -[install_libpng]: Delete "C:\Carla\carla-dev\Build\libpng-1.2.37-install\" if you want to force a rebuild.
    -[install_libpng]: Exiting...
-[Setup]: Installing rpclib...
    -[install_rpclib]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
    -[install_rpclib]: A rpclib installation already exists.
    -[install_rpclib]: Delete "C:\Carla\carla-dev\Build\rpclib-install\" if you want to force a rebuild.
    -[install_rpclib]: Exiting...
-[Setup]: Installing Google Test...
    -[install_gtest]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
    -[install_gtest]: Not cloning Google Test because already exists a folder called "gtest-src".
    -[install_gtest]: Generating build...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
CMake Deprecation Warning at googlemock/CMakeLists.txt:42 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at googletest/cmake/internal_utils.cmake:239 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  googletest/CMakeLists.txt:84 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (0.3s)
-- Generating done (0.4s)
-- Build files have been written to: C:/Carla/carla-dev/Build/gtest-src/build
    -[install_gtest]: Building...
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  1>Checking Build System
  gmock.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\Release\gmock.lib
  gmock_main.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\Release\gmock_main.lib
  gtest.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\gtest\Release\gtest.lib
  gtest_main.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\gtest\Release\gtest_main.lib
  Building Custom Rule C:/Carla/carla-dev/Build/gtest-src/CMakeLists.txt
  1>
  -- Install configuration: "Release"
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-cardinalities.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-actions.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-function-mockers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-function-mockers.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-matchers.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-nice-strict.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-nice-strict.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-more-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-more-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-spec-builders.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-generated-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-generated-actions.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/README.md
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-generated-internal-utils.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-generated-internal-utils.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-internal-utils.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gmock.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gmock_main.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gmock.pc
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gmock_main.pc
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestTargets.cmake
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestTargets-release.cmake
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestConfigVersion.cmake
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestConfig.cmake
  -- Up-to-date: C:/Carla/carla-dev/Build/gtest-install/include
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-death-test.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-message.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-param-test.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-param-test.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-printers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-spi.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-test-part.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-typed-test.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest_pred_impl.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest_prod.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/gtest-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/gtest-printers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/gtest.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/README.md
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-death-test-internal.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-filepath.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-internal.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-linked_ptr.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-param-util-generated.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-param-util-generated.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-param-util.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-port-arch.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-string.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-tuple.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-tuple.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-type-util.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-type-util.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gtest.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gtest_main.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gtest.pc
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gtest_main.pc
neq was unexpected at this time.

    -[install_gtest]: Google Test has been successfully installed in "C:\Carla\carla-dev\Build\gtest-install\"
    -[install_gtest]: Exiting...
-[Setup]: Installing "Recast & Detour"...
    -[install_recast]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
    -[install_recast]: A "Recast & Detour" installation already exists.
    -[install_recast]: Delete "C:\Carla\carla-dev\Build\recast-install\" if you want to force a rebuild.
    -[install_recast]: Exiting...
-[Setup]: Installing Boost...
    -[install_boost]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --toolset msvc-14.2 --version 1.80.0 -j 16
The system cannot find the batch label specified - arg-parse

-[Setup]:
   Ok, and error ocurred, don't panic
   We have different platforms where you can find some help :)

   - Make sure you have read the documentation:
       http://carla.readthedocs.io/en/latest/how_to_build_on_windows/

   - If the problem persists, you can ask on our Github's "Building on Windows" issue:
       https://github.com/carla-simulator/carla/issues/21

   - Or just use our Discord channel
       We'll be glad to help you there :)
       https://discord.gg/42KJdRj
make: *** [setup] Error 1

C:\Carla\carla-dev>make PythonAPI
-[BuildUE4Plugins]: [Batch params]: --build --all
HEAD is now at 260273d Correct descriptor
-[BuildUE4Plugins]: STREETMAP has been successfully installed in "C:\Carla\carla-dev\Unreal\CarlaUE4\Plugins\"
-[Setup]: [Batch params]: --boost-toolset msvc-14.2 --generator "" --all
-[Setup]: Asynchronous jobs:  16
-[Setup]: Boost toolset:      msvc-14.2
-[Setup]: Generator:          "Visual Studio 16 2019"
-[Setup]: Install directory:  "C:\Carla\carla-dev\Build\"
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\"
    -[install_zlib]: A zlib installation already exists.
    -[install_zlib]: Delete "C:\Carla\carla-dev\Build\zlib-install\" if you want to force a rebuild.
    -[install_zlib]: Exiting...
The system cannot find the path specified.
        0 file(s) copied.
-[Setup]: Installing libpng...
    -[install_libpng]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --zlib-install-dir "C:\Carla\carla-dev\Build\zlib-install\"
    -[install_libpng]: A libpng installation already exists.
    -[install_libpng]: Delete "C:\Carla\carla-dev\Build\libpng-1.2.37-install\" if you want to force a rebuild.
    -[install_libpng]: Exiting...
-[Setup]: Installing rpclib...
    -[install_rpclib]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
    -[install_rpclib]: A rpclib installation already exists.
    -[install_rpclib]: Delete "C:\Carla\carla-dev\Build\rpclib-install\" if you want to force a rebuild.
    -[install_rpclib]: Exiting...
-[Setup]: Installing Google Test...
    -[install_gtest]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
    -[install_gtest]: Not cloning Google Test because already exists a folder called "gtest-src".
    -[install_gtest]: Generating build...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
CMake Deprecation Warning at googlemock/CMakeLists.txt:42 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at googletest/cmake/internal_utils.cmake:239 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  googletest/CMakeLists.txt:84 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (0.3s)
-- Generating done (0.2s)
-- Build files have been written to: C:/Carla/carla-dev/Build/gtest-src/build
    -[install_gtest]: Building...
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  gmock.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\Release\gmock.lib
  gmock_main.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\Release\gmock_main.lib
  gtest.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\gtest\Release\gtest.lib
  gtest_main.vcxproj -> C:\Carla\carla-dev\Build\gtest-src\build\googlemock\gtest\Release\gtest_main.lib
  1>
  -- Install configuration: "Release"
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-cardinalities.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-actions.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-function-mockers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-function-mockers.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-matchers.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-nice-strict.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-generated-nice-strict.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-more-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-more-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock-spec-builders.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/gmock.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-generated-actions.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-generated-actions.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-matchers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/gmock-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/custom/README.md
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-generated-internal-utils.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-generated-internal-utils.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-internal-utils.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gmock/internal/gmock-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gmock.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gmock_main.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gmock.pc
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gmock_main.pc
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestTargets.cmake
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestTargets-release.cmake
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestConfigVersion.cmake
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/cmake/GTest/GTestConfig.cmake
  -- Up-to-date: C:/Carla/carla-dev/Build/gtest-install/include
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-death-test.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-message.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-param-test.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-param-test.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-printers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-spi.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-test-part.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest-typed-test.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest_pred_impl.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/gtest_prod.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/gtest-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/gtest-printers.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/gtest.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/custom/README.md
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-death-test-internal.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-filepath.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-internal.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-linked_ptr.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-param-util-generated.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-param-util-generated.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-param-util.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-port-arch.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-port.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-string.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-tuple.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-tuple.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-type-util.h
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/include/gtest/internal/gtest-type-util.h.pump
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gtest.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/gtest_main.lib
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gtest.pc
  -- Installing: C:/Carla/carla-dev/Build/gtest-install/lib/pkgconfig/gtest_main.pc
neq was unexpected at this time.

    -[install_gtest]: Google Test has been successfully installed in "C:\Carla\carla-dev\Build\gtest-install\"
    -[install_gtest]: Exiting...
-[Setup]: Installing "Recast & Detour"...
    -[install_recast]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
    -[install_recast]: A "Recast & Detour" installation already exists.
    -[install_recast]: Delete "C:\Carla\carla-dev\Build\recast-install\" if you want to force a rebuild.
    -[install_recast]: Exiting...
-[Setup]: Installing Boost...
    -[install_boost]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --toolset msvc-14.2 --version 1.80.0 -j 16
The system cannot find the batch label specified - arg-parse

-[Setup]:
   Ok, and error ocurred, don't panic
   We have different platforms where you can find some help :)

   - Make sure you have read the documentation:
       http://carla.readthedocs.io/en/latest/how_to_build_on_windows/

   - If the problem persists, you can ask on our Github's "Building on Windows" issue:
       https://github.com/carla-simulator/carla/issues/21

   - Or just use our Discord channel
       We'll be glad to help you there :)
       https://discord.gg/42KJdRj
make: *** [setup] Error 1

C:\Carla\carla-dev>make PythonAPI
-[BuildUE4Plugins]: [Batch params]: --build --all
HEAD is now at 260273d Correct descriptor
-[BuildUE4Plugins]: STREETMAP has been successfully installed in "C:\Carla\carla-dev\Unreal\CarlaUE4\Plugins\"
-[Setup]: [Batch params]: --boost-toolset msvc-14.2 --generator "" --all
-[Setup]: Asynchronous jobs:  16
-[Setup]: Boost toolset:      msvc-14.2
-[Setup]: Generator:          "Visual Studio 16 2019"
-[Setup]: Install directory:  "C:\Carla\carla-dev\Build\"
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\"
    -[install_zlib]: A zlib installation already exists.
    -[install_zlib]: Delete "C:\Carla\carla-dev\Build\zlib-install\" if you want to force a rebuild.
    -[install_zlib]: Exiting...
The system cannot find the path specified.
        0 file(s) copied.
-[Setup]: Installing libpng...
    -[install_libpng]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --zlib-install-dir "C:\Carla\carla-dev\Build\zlib-install\"
    -[install_libpng]: A libpng installation already exists.
    -[install_libpng]: Delete "C:\Carla\carla-dev\Build\libpng-1.2.37-install\" if you want to force a rebuild.
    -[install_libpng]: Exiting...
-[Setup]: Installing rpclib...
    -[install_rpclib]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
    -[install_rpclib]: A rpclib installation already exists.
    -[install_rpclib]: Delete "C:\Carla\carla-dev\Build\rpclib-install\" if you want to force a rebuild.
    -[install_rpclib]: Exiting...
-[Setup]: Installing Google Test...
    -[install_gtest]: [Batch params]: --build-dir "C:\Carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
The system cannot find the batch label specified - already_build

-[Setup]:
   Ok, and error ocurred, don't panic
   We have different platforms where you can find some help :)

   - Make sure you have read the documentation:
       http://carla.readthedocs.io/en/latest/how_to_build_on_windows/

   - If the problem persists, you can ask on our Github's "Building on Windows" issue:
       https://github.com/carla-simulator/carla/issues/21

   - Or just use our Discord channel
       We'll be glad to help you there :)
       https://discord.gg/42KJdRj
make: *** [setup] Error 1

What you expected to happen: Should proceed without saying this. 
Steps to reproduce:
Other information (documentation you consulted, workarounds you tried):

**Comment by Blyron** [comment]
We need a description of the issue. Otherwise it will be closed inmmediatly
