### ISSUE TITLE
Skyscrapers - Office

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7845]
Redo this office skyscrapper

![Image](https://github.com/carla-simulator/carla/assets/54811869/9bd0f79c-4ed5-42c1-904d-0426c87107b8)

Replace with "all glass" office skyscrapper

![Image](https://github.com/carla-simulator/carla/assets/54811869/66d9096c-a983-4f2f-8740-4ef04b14a1e4)

Bottom

![Image](https://github.com/carla-simulator/carla/assets/54811869/7d1764d6-d10c-4db7-ad66-8e8010169976)

![Image](https://github.com/carla-simulator/carla/assets/54811869/c7c50905-89ab-4de0-a535-a6314a78cfca)

**Comment by gsmario** [comment]
![Image](https://github.com/user-attachments/assets/91a6e32f-3e11-4aee-9ced-2fe904739848)



![Image](https://github.com/user-attachments/assets/2a789bb4-e55f-48c6-b3c8-4b720bb889d5)
