### ISSUE TITLE
Skyscrapers - Classic

### ISSUE THREAD

**Issue by AinaRoca** [carla-simulator/carla#7858]
![Image](https://github.com/carla-simulator/carla/assets/54811869/8af93543-65d1-4046-b97b-c4475662e820)

![Image](https://github.com/carla-simulator/carla/assets/54811869/ab6f425f-1cde-4f4c-bf0a-7edd4da18a55)

**Comment by Madecu** [comment]
![Image](https://github.com/user-attachments/assets/6bf503c8-7d5b-46c7-b19a-6065b5a8d268)
