### ISSUE TITLE
Adding two Player in Carla Version 0.8.4

### ISSUE THREAD

**Issue by FarzanehJafari** [carla-simulator/carla#786]
Hi,
I want to add an other vehicle as a main car in Carla Version 0.8.4. How am I adding Two player in Carla? Is this possible?

**Comment by marcgpuig** [comment]
Hello @FarzanehJafari.
This is not possible in CARLA 0.8.x, but is included in the current _experimental_ 0.9.0!

**Comment by FarzanehJafari** [comment]
Thanks


Sent from Yahoo Mail for iPhone


On Wednesday, September 19, 2018, 14:05, Marc Garcia Puig <notifications@github.com> wrote:


Hello @FarzanehJafari.
This is not possible in CARLA 0.8.x, but is included in the current experimental 0.9.0!
