### ISSUE TITLE
UE4 Error after closing client and server carla 0.9 windows

### ISSUE THREAD

**Issue by Atlunch** [carla-simulator/carla#787]
It isn't a big error, but i thought maybe it can help the dev team.

I built carla 0.9 on windows, following the instruction "how to build on windows".
I can start the server and also the Python example "manual_control".

When I first close the Python Client and after that the Carla Server, following Error occur.

![unbenannt](https://user-images.githubusercontent.com/31853843/45704079-574d0300-bb76-11e8-92a5-435f7a1483ef.PNG)

**Comment by nsubiron** [comment]
Thanks for the report! unfortunately there is no much info in that crash, we'll try to reproduce it here, it may be related to #767 too.
