### ISSUE TITLE
Spawn and control traffic lights from a client

### ISSUE THREAD

**Issue by kloud1989** [carla-simulator/carla#788]
Hi,
The current traffic light logic is controlled by blueprint of a traffic light group. To sync with traffic simulators like SUMO, it is a very important feature that traffic light control is supported. Is it possible for Carla to support spawn and control traffic lights from a client in future Carla releases? 
Thanks!

**Comment by IronicallySerious** [comment]
Is there a running solution for this? Or do we have any existing SUMO integrations with Carla?
