### ISSUE TITLE
Rework of Semantic Segmentation sensor

### ISSUE THREAD

**Issue by Blyron** [carla-simulator/carla#7889]
Our way to label actors is too "hardcoded" by having to follow a folder structure. 
Look at  crp::CityObjectLabel GetLabelByPath (by the way this shouldn't be a template, it should be an UObject parameter

We need to remove this. The 1st approach should be using Material IDs, for this we will need to create master material for each type of object. Art and Core will need to work closely.

**Comment by utkuoguzman** [comment]
This isn't done, why closed as done?

**Comment by Blyron** [comment]
Is done; The work has ben done for ue5

**Comment by utkuoguzman** [comment]
But it still uses the meshes inside the folder structure for the semantic. UE5 version don't return anything with material ID. Am I wrong? Is there any explanation somewhere?

**Comment by Blyron** [comment]
Yeah and for the moment it will use. The rework was to use a render pass instead of mesh proxys to make it cheaper. We are not gonna use material ids, for now
