### ISSUE TITLE
about "world.debug.draw_line"

### ISSUE THREAD

**Issue by ccconquer** [carla-simulator/carla#7894]
CARLA version:  0.9.15
Platform/OS:   ubuntu20.04
Problem you have experienced:  When using world.debug.draw_line(start_point, end_point, thickness=thickness, color=color, life_time=1000), the drawn line looks like a laser. Can it be a regular solid line or other line styles?
Other questions: Does Carla have a function to fill a region with color?

![2024-07-02_20-47](https://github.com/carla-simulator/carla/assets/111716969/b6567b8a-57d2-4e07-a589-2406bc8fbe9b)

**Comment by CurryChen77** [comment]
Hello, I have also encountered a similar issue, whether using “draw_line” or “draw_box”, this laser lane occurs. However, according to [#7833](https://github.com/carla-simulator/carla/issues/7833) you didn't seem to have this problem on version 0.9.14, while I have it on 0.9.13. I am also very confused about this.
