### ISSUE TITLE
About detection of collision events

### ISSUE THREAD

**Issue by Nancy22-NJ** [carla-simulator/carla#7901]
Hello, I'm wandering how to stop the current simulation when collision events are caught by the collision detector sensor, and then run the next simulation?
Thank you for your reply!!!

**Comment by Blyron** [comment]
Right now we do not have pause function in the simulator but you have an example of how to do a pause in the manual control.

**Comment by PatrickPromitzer** [comment]
Hi,
I guess you mean that the collision sensor keep getting data, and the Python API is keeping open the program?
Or do you mean something else?

You can stop listening to the sensor and destroy it.
```python
sensor.stop()
sensor.destroy()
```
