### ISSUE TITLE
Opening .xodr file in Carla Standalone time-out error

### ISSUE THREAD

**Issue by AlexMiamiACN** [carla-simulator/carla#7903]
CARLA version: 0.9.13
Platform/OS: Windows
Problem you have experienced: I am trying to import an .xodr file into Carla, using the procedure described in this article for ingesting into carla: https://carla.readthedocs.io/en/latest/tuto_G_openstreetmap/. l am using method b) from the artcile to ingest an .xodr file into CARLA. The command I am using is:

**C:\Carla_0.9.13\PythonAPI\util>python3 config.py -x=C:\OPENMAP\newmap.xodr**

 
What you expected to happen: I would expect for the command to work and for the map to be ingested into Carla. Here is my current output issue:

**C:\Carla_0.9.13\PythonAPI\util>python3 config.py -x=C:\OPENMAP\newmap.xodr**

**load opendrive map 'newmap.xodr'.**

**INFO:  Found the required file in cache!  Carla/Maps/Nav/Town10HD_Opt.bin**

**time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000**

I have CARLA already open and running as I do this command and have no clue why it won't work. I also have already clicked "Play" in CARLA, if I don't, then the  "load opendrive map 'newmap.xodr'. INFO:  Found the required file in cache!  Carla/Maps/Nav/Town10HD_Opt.bin"  messages will not run and it will just time out. So need a fix on this timing-out issue! NOTE: I am running Python 3.7.10 and Carla was installed with this  (I.e. my .egg files are py37)

**Comment by daxjiang** [comment]
same question
