### ISSUE TITLE
Remove traffic sign

### ISSUE THREAD

**Issue by Ikaros520520** [carla-simulator/carla#7905]
CARLA version:0.9.12
Platform/OS:Windows

I removed some traffic signs like traffic lights and speed limit signs in the default map "Town2". 
![image](https://github.com/carla-simulator/carla/assets/100818847/7d2f9d39-1f76-4acb-9b4e-06870ebdf0b0)
![image](https://github.com/carla-simulator/carla/assets/100818847/95f6c886-be43-4600-beed-b93a17c4a36c)

But when I clicked PLAY in UE to start running, I found that the traffic signs appeared again. Just changed the sign.
![image](https://github.com/carla-simulator/carla/assets/100818847/e2c1611e-57e5-4a90-bb1d-6257e9e41daf)

I want to actually remove these traffic signs from the map. Can anyone tell me how to do this? Thank you so much!

**Comment by Blyron** [comment]
You need to remove the signs and traffic lights from the OpenDrive file, otherwise, you can look and modify this function
ATrafficLightManager::RegisterLightComponentFromOpenDRIVE in Unreal\CarlaUnreal\Plugins\Carla\Source\Carla\Traffic\TrafficLightManager.cpp

**Comment by Ikaros520520** [comment]
> You need to remove the signs and traffic lights from the OpenDrive file, otherwise, you can look and modify this function ATrafficLightManager::RegisterLightComponentFromOpenDRIVE in Unreal\CarlaUnreal\Plugins\Carla\Source\Carla\Traffic\TrafficLightManager.cpp

For Carla and python I'm still learning. Not really sure how to modify .cpp files. I found an easy way. Just move the traffic sign underground.

**Comment by CoderXuans** [comment]
@Ikaros520520 
Hello.Even though I moved them underground and ran the evaluation code for the leaderboard, the traffic lights still appear. I moved the nearby low houses underground, and they disappeared, but when I tried to back up the map data and delete the traffic lights, clicking play caused Unreal Engine to crash.
