### ISSUE TITLE
Manual camera timing

### ISSUE THREAD

**Issue by LeonardMendicantBias** [carla-simulator/carla#7909]
Dear Carla developers, contributors, and users.

I would like to set up a scenario in Carla where multiple RGB cameras capture images at different times. I have noticed that the images captured by the cameras have different times according to `image.frame`. However, is there a way that I can set the camera to start capturing images at an exact time?

**Comment by PatrickPromitzer** [comment]
You can use "synchronous-mode"
https://carla.readthedocs.io/en/latest/adv_traffic_manager/#synchronous-mode

With the "synchronous-mode" Carla waits until you tell Carla to continue.

If you want the frames 10-20 for the first camera, you can ignore the sensor data before frame 10, or add the listener at frame 9.

Example Script
https://github.com/carla-simulator/carla/blob/dev/PythonAPI/examples/sensor_synchronization.py
