### ISSUE TITLE
Old build instructions?

### ISSUE THREAD

**Issue by anthonypan08** [carla-simulator/carla#791]
Can someone post the old build instructions of Carla? It seems that the doc on the website is for the newest release but I need the old version of Carla

**Comment by iFuSiiOnzZ** [comment]
Hi @anthonypan08,

Sorry for the late response, the old documentation is found in the stable branch, `Docs -> Home` there is a disclaimer. Keep in mind that some information may be missing or points to github issues.

Link: https://carla.readthedocs.io/en/stable/

**Comment by marcgpuig** [comment]
@anthonypan08 Also you can check #21 if you have some troubles!
