### ISSUE TITLE
Remake VehiclePhysicsControl and WheelPhysicsControl

### ISSUE THREAD

**Issue by glopezdiest** [carla-simulator/carla#7912]
VehiclePhysicsControl and WheelPhysicsControl are a 1-to-1 match of the vehicle and wheels PhysX parameters. As Chaos is now used for UE5, these have to be changed to match the new parameters

**Comment by EmmettJZK** [comment]
In fact, in UE4 version of the CARLA project, the carla.VehiclePhysicsControl class in the PythonAPI also lacks some PhysX dynamic parameters.
 For example, the differential parameters shown below
Official Document:
![image](https://github.com/user-attachments/assets/744fbd4a-33e1-4449-97e0-5bbbc897dbe8)
The red box surrounds the missing parameters:
![image](https://github.com/user-attachments/assets/af4a9120-f175-42c5-8013-d77ed76e8213)
