### ISSUE TITLE
Fix Invisible collision

### ISSUE THREAD

**Issue by glopezdiest** [carla-simulator/carla#7913]
There seems to be an invisible collision in Town10, seen by that perpendicular line to road in the middle of the image 

![Image](https://github.com/carla-simulator/carla/assets/58212725/4cb41ea2-c1b1-4594-b6bc-61ee8dd8f717)

![Image](https://github.com/carla-simulator/carla/assets/58212725/7b0e0acf-ed1d-4e29-9e07-494a0c71aa62)

**Comment by AinaRoca** [comment]
Because the lane markings are not totally flat anymore, the simple collision was taking in account the highest and lowest points to create the collision box. I've put use complex collision as simple.
