### ISSUE TITLE
Issue with opening Carla 

### ISSUE THREAD

**Issue by andrster** [carla-simulator/carla#792]
![screenshot from 2018-09-20 10-50-50](https://user-images.githubusercontent.com/22357321/45826794-1e6e7480-bcc3-11e8-95a9-50c94ef4b184.png)
getting this issue when trying to use carla. Any help would be great.

**Comment by marcgpuig** [comment]
Hi @andrster.
Can you provide more information?
How many versions of Unreal do you have installed? Which version are you using? Are you rebuilding CARLA?

**Comment by andrster** [comment]
I believe 4.18 and yes I was rebuilding carla.

**Comment by nsubiron** [comment]
If you press "Yes" does it give any error? I've seen this happening sometimes, usually pressing yes it recompiles and launches the editor just fine.

**Comment by andrster** [comment]
Yes it won't recompile and to try manually, which also won't work.  Also my symbol for the project looks off and make rebuild in carla gives that error
![screenshot from 2018-09-21 09-08-48](https://user-images.githubusercontent.com/22357321/45883064-014aac00-bd7e-11e8-8016-7c13cb80b591.png)

**Comment by andrster** [comment]
and this happens on Rebuild.sh
![screenshot from 2018-09-21 09-17-12](https://user-images.githubusercontent.com/22357321/45883455-25f35380-bd7f-11e8-9229-8b29180acf3f.png)

**Comment by andrster** [comment]
issue resolved
