### ISSUE TITLE
UE5 memory leak when trying to Save images

### ISSUE THREAD

**Issue by Blyron** [carla-simulator/carla#7923]
More info on 
https://docs.google.com/document/d/1elDrbtYjHyMpLSzUMtd3MUz0G5fPyULQGz9TGWJb6kE/edit

**Comment by syo093c** [comment]
Oh, I have the same problem!!
How can I fix it? Use a lower version of carla?

**Comment by syo093c** [comment]
I am using sensors to collect data for training, but meet memory leak problem. I will try carla 0.9.13. Thank you for your information!

**Comment by syo093c** [comment]
I have confirmed that carla 0.9.13 does not have memory leak, thank you again!
