### ISSUE TITLE
the speed limits in Town04

### ISSUE THREAD

**Issue by ccconquer** [carla-simulator/carla#7929]
CARLA version:  0.9.15
Platform/OS: ubuntu
Problem you have experienced: Regarding the speed limits in Town04, why are the speed limits so high? There are no speed limits for roads after Road_ID52. Is there an issue?
Code: 
xodr_content = self.map.to_opendrive()
root = ET.fromstring(xodr_content)
speed_limit = None
for road in root.iter('road'):
    print(f"Road ID: {road.attrib['id']}, Name: {road.attrib['name']}, Length: {road.attrib['length']}")
    for speed in road.iter('speed'):
        speed_limit = float(speed.attrib['max']) * 3.6  # 转换为 km/h
        print(f"Speed limit: {speed_limit} km/h")
 Result:
![道路限速](https://github.com/carla-simulator/carla/assets/111716969/627fd02e-e201-4d92-9a70-3606a82626b9)

**Comment by GoodarzMehr** [comment]
For the roads that have a speed limit, I think the values are already in km/h and not in m/s, so you get the wrong values when multiplying by 3.6.

**Comment by RodrigoVillarias** [comment]
Hello, as GoodarzMehr says, the speeds in Carla are applied in km/h and not in m/s, by changing this data the speeds should match well

![image](https://github.com/user-attachments/assets/7c630da0-047f-4ddb-81a1-0057796724f2)
![image](https://github.com/user-attachments/assets/7903a23b-a7e9-42be-8e5e-6b7f292fdfce)
![image](https://github.com/user-attachments/assets/90c6d2a0-214a-4443-aa20-f154a126d9ea)

**Comment by RodrigoVillarias** [comment]
Hello, this solved your question? the issue will be closed, in any case if something happens feel free to reopen the issue
