### ISSUE TITLE
Issue about do experiments from start point to end point

### ISSUE THREAD

**Issue by chensg1919** [carla-simulator/carla#793]
https://carla.readthedocs.io/en/latest/benchmark_creating/

From the link I know how to do experiments from start point to end point. However, the vehicle can only go straight. One test is [140,134]. But the vehicle cannot arrive at 134 because it will collide and stop. In PythonAPI, I see there is only foward agent. Is there any way to drive a car from start point to end point even there is a turn?

**Comment by chensg1919** [comment]
And also, I want to know whether I could replace coordinate number with (x,y) coordinate, such as replace 140 with (662,1305)

**Comment by chensg1919** [comment]
Any solution to solve it?

**Comment by felipecode** [comment]
Hey @chensg1919 We are currently have an agent to do that
The agent is for version 0.8.4. It is placed on the client_agent_improving_pedestrians branch.
The agent is called command follower, you can see an example of it in the control_example.py python code.

**Comment by chensg1919** [comment]
@felipecode 
Sry, I'm now using 0.8.4, but I cannot find this branch. Could you tell me the specific location?

**Comment by felipecode** [comment]
https://github.com/carla-simulator/carla/tree/client_agents_improving_pedestrians

and the code ( example)

https://github.com/carla-simulator/carla/blob/client_agents_improving_pedestrians/PythonClient/control_example.py

The actual agent code

https://github.com/carla-simulator/carla/blob/client_agents_improving_pedestrians/PythonClient/carla/agent/command_follower.py

**Comment by chensg1919** [comment]
@felipecode Thank you. I have downloaded this branch, but there are still some questions. 
Firstly, I cannot run Package.sh. "fatal: Not a git repository (or any of the parent directories): .git"
And also, when I run driving_benchmark_example.py, it shows me ImportError: No module named 'pid_controller'.

How to fix it?
