### ISSUE TITLE
Suggestions for Improving Visual Appearance of Vehicle Lights

### ISSUE THREAD

**Issue by GoodarzMehr** [carla-simulator/carla#7930]
Hi,

I have a few suggestions for enhancing the visual appearance of vehicle lights in some small ways based on my recent experience with adding new cars to CARLA.

1) Some cars (especially American-made ones) have red rear blinkers instead of amber ones, but this is not currently supported by CARLA. My solution to this was to split the indicator lights section of the UV map in half (similar to the fog and position lights), as seen below, and update the light material (and the actor blueprint) in UE4 by splitting the blinkers in two for front and back, similar to what is done for the fog/position lights.

![LightColors](https://github.com/carla-simulator/carla/assets/23568549/d4efeb2b-3d41-427d-ab5f-c3574f90a201)

The end result is something similar to the images below. I've also attached the UE material in case anyone is interested.

![Screenshot from 2024-07-08 23-28-51](https://github.com/carla-simulator/carla/assets/23568549/3ee37d11-b361-49dc-b8f9-8a40393a8976)
![Screenshot from 2024-07-08 23-29-09](https://github.com/carla-simulator/carla/assets/23568549/cebf1bc1-cef3-4232-b9bd-fa2a80308e1a)
![Screenshot from 2024-07-08 23-29-34](https://github.com/carla-simulator/carla/assets/23568549/bd5960ff-2de9-4b7c-b986-95de0fb7f5db)

[M_VehicleLights.zip](https://github.com/user-attachments/files/16138558/M_VehicleLights.zip)

2) A lot of cars use the same bulb for several light types, for instance low/high beam and brake/position, but my understanding is that in CARLA's vehicle models a single mesh is separated across different light types in the UV map. What I've found to be a bit more realistic is to duplicate the light mesh (with the duplicate translated across the longitudinal axis of the car by a very samll amount) and assign each mesh to a separate light type in the UV map, as shown in the image below where rear position/fog/break lights are all duplicates of the same mesh.

![Screenshot from 2024-07-08 23-34-25](https://github.com/carla-simulator/carla/assets/23568549/c648034d-7c4d-4b21-beb0-ba4af154b772)

It ends up looking something like this (first image only position, second one position+brake).

![Screenshot from 2024-07-08 23-31-03](https://github.com/carla-simulator/carla/assets/23568549/4a4f7e53-5746-4746-be74-fbae94feeea7)
![Screenshot from 2024-07-08 23-31-26](https://github.com/carla-simulator/carla/assets/23568549/6938a8e8-a37b-43d0-bc0f-a92c75280803)

**Comment by gsmario** [comment]
Hello!
Thank you very much for your suggestion; we will take it into account for future vehicles.

I have a question regarding the overlapping geometry planes: is the opacity affecting how the ones behind are seen? Did you have to adjust the light intensity to make them look better?

That's all. Thank you for your time!

**Comment by GoodarzMehr** [comment]
You are very welcome!

To answer your question, yes, opacity does impact how the lights are seen, but in my experience this has really only been the case for rear lights, since the multi-layer front lights are usually the low/high beam ones that are bright enough that changing the opacity doesn't make a lot of difference (unless you use a very high or low value). For the rear lights, my rule of thumb has been to set the opacity to about 1/(max number of layers) and play around a bit with the intensities, though you can obviously have materials with different opacity for each layer.

I'll use the 2016 Mustang I added as an example of a somewhat extreme case, since the rear lights have four layers (position/fog/brake/blinker from back to front) I've set the opacity to 0.24. These are the light intensities I use:
![Screenshot from 2024-07-12 19-03-24](https://github.com/user-attachments/assets/6cb7816b-8c1a-4ce3-8ecd-23e47d016ecc)

Both blinkers + position + fog + low beam:
![Screenshot from 2024-07-12 19-11-08](https://github.com/user-attachments/assets/ef314696-2a62-4980-a540-edcabd4bce33)

Both blinkers + position + fog + low beam + high beam:
![Screenshot from 2024-07-12 19-11-31](https://github.com/user-attachments/assets/58860871-4891-4a44-9963-9c0e793986b8)

High beam only:
![Screenshot from 2024-07-12 19-13-53](https://github.com/user-attachments/assets/a98e6c4c-fa0c-40f5-b3db-67fb6ccb9beb)

No lights:
![Screenshot from 2024-07-12 19-16-35](https://github.com/user-attachments/assets/0e5096a6-b079-48e3-99f7-f7a3c6917cde)

Brake only:
![Screenshot from 2024-07-12 19-16-44](https://github.com/user-attachments/assets/c1653acf-0b4e-4f27-a565-92199c4dea93)

Left blinker only:
![Screenshot from 2024-07-12 19-16-57](https://github.com/user-attachments/assets/4dbe882f-111c-40d3-96ea-3cfbe3247fed)

Left blinker + position:
![Screenshot from 2024-07-12 19-18-56](https://github.com/user-attachments/assets/cedd5ec9-961b-4e4b-9d74-0679b08da39c)

Left blinker + position + fog:
![Screenshot from 2024-07-12 19-19-15](https://github.com/user-attachments/assets/b8bedf28-080e-43eb-ba3f-918f408beb48)

Left blinker + position + fog + brake:
![Screenshot from 2024-07-12 19-19-43](https://github.com/user-attachments/assets/9bf09969-df53-4e67-9e62-6b7161510043)

Left blinker + position + brake:
![Screenshot from 2024-07-12 19-20-10](https://github.com/user-attachments/assets/f21e7916-5f62-4d75-a66f-53485308dea2)

BTW I've been working on adding lights to CARLA's older vehicles, if you'd like I can send my content library over in case you'd want to use any of it.

**Comment by gsmario** [comment]
Wow thanks! really nice work!
Feel free to create a pull request with all these changes, we can have a look and see if we can merge it!
Thanks again :)

**Comment by GoodarzMehr** [comment]
Hi @gsmario 

I've been looking at submitting my changes as a pull request to the content repo, but Bitbucket seems to have a 5 GB cap on repo size. Given the size of the content library I can't push my local changes to my fork to then create a pull request. Is there any other way of doing this? I can upload it to GDrive along with a changelog if that works for you guys.
