### ISSUE TITLE
Missing Instance segmentation material

### ISSUE THREAD

**Issue by Bvallon-sl** [carla-simulator/carla#7938]
CARLA version: UE5.3 Dev
Platform/OS: Win10
Problem you have experienced:
I wanted to try the new Instance segmentation implementation added by #7935 but the InstanceSegmentation material is missing.

I'm facing this error 
![image](https://github.com/carla-simulator/carla/assets/60651082/fdc673a1-66ff-4f88-b1af-040cbe2895c9)
and indeed the material is missing from the project.

Many thanks for considering my request.

Best regards,

**Comment by Blyron** [comment]
Please, update content repository. 
For that go to Carla_Root/Unreal/CarlaUnreal/Content/Carla/ 
and put a git pull there, it may ask for a user and token of bitbucket

**Comment by Bvallon-sl** [comment]
Ok, I missed that part. Thanks for the help!
