### ISSUE TITLE
Skyscrapers - Classic III

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#7957]
Bottom / Mid/ Top

![Image](https://github.com/carla-simulator/carla/assets/54811869/d04ee923-b301-4a9b-8d4f-02d45be26833)

**Comment by ahlamiki** [comment]
![Image](https://github.com/user-attachments/assets/ea077831-4d57-486b-b84d-26f038a2e8cd)
![Image](https://github.com/user-attachments/assets/b3efe081-b04f-4a54-a9d9-cd72f81b166a)
![Image](https://github.com/user-attachments/assets/82454feb-680c-42f8-a5df-59c5bd153f78)
![Image](https://github.com/user-attachments/assets/549d4aad-e2b1-44dd-b334-78592d61be68)

Created a new version of the Skyscraper classic 3 taking as a reference the images above.
