### ISSUE TITLE
Run carlaUE4 crash while draging Traficlights into the scene

### ISSUE THREAD

**Issue by chuanye-Wang** [carla-simulator/carla#7961]
0.9.15-dev  
Ubuntu 20.04
issue: CarlaUE4 crashed when added trafficlights into the scene and play.
expectation: I wanna add trafficlights to my custom map exported from Roadrunner.

I import a custom map from RoadRunner, I have placed traficlights in the Roadrunner, but none of them showed up in carlaUE4. So I follow these step to place Trafficlights using CarlaUE4
![image](https://github.com/user-attachments/assets/9704afce-0f41-41ec-a214-84070df01aaa)

After I draged the trafficlights into the scene, and I Play, then CarlaUE4 crashed!
![img_v3_02cs_2e554647-900c-42eb-b926-212b87ffa85g](https://github.com/user-attachments/assets/e0434d2d-94ff-4477-aab0-b713a97fe72d)

Is there solution for this? Or, anyother way to add trafficlights to my custom map exported from Roadrunner?
tks!

**Comment by chuanye-Wang** [comment]
Thanks, it works

**Comment by gsmario** [comment]
I'm glad it worked!
Then i'll close the issue.
Thanks again!

**Comment by SExpert12** [comment]
Hi,
I am also facing the same issue. Earlier I followed the steps given by @chuanye-Wang but traffic lights not working and now I it server is getting crashed. 
How to go to this sublevel  as given in this step 
"First, move to the correct sublevel for traffic lights (double click sublevel "layout")"

Thanks
