### ISSUE TITLE
Markovian state of vehicle in empty world?

### ISSUE THREAD

**Issue by nrhine1** [carla-simulator/carla#798]
What information comprises the Markovian state for the vehicle dynamics (of a vehicle in an empty world)? It would be useful to characterize the system and ensure that the information in the player measurements is sufficient to construct Markovian state.

I am not sure if the information in the player measurements is sufficient -- from skimming [the PhysX vehicle dynamics](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/Vehicles.html), which [#115](https://github.com/carla-simulator/carla/issues/115) suggests is the dynamics model, I think wheel pose and its derivatives may be necessary.

 Additionally, the vehicle's pose currently only has first and second order derivatives for its position, but no derivatives for the orientation, which I think may also be necessary for full observability. These can be constructed manually by using the history of states, as opposed to the wheel states.

**Comment by nsubiron** [comment]
It is difficult to say what is necessary to fully determine the state of a vehicle. PhysX vehicles have tons of parameters to configure the vehicle's engine, physics asset, and even tires.

Now if you just care about repeatability, the simulation is quite repeatable if you fix the frame-rate and the random seeds. Eventually it diverges if pedestrians are enabled though, but even with them, you can easily get 10 min of simulation reproducible pixel-by-pixel, [see video](https://youtu.be/xU80o0Bdh-U).

As the issue you mention suggests, we plan to add support for other vehicle models like CarSim in the future (although we don't have a date planned for that).

There was a PR that enabled sending the wheels state to the client (#549), unfortunately its contributor never finished it and eventually it was closed by the stale bot.
