### ISSUE TITLE
about town01

### ISSUE THREAD

**Issue by ccconquer** [carla-simulator/carla#7990]
CARLA version: 0.9.15
Platform/OS: ubuntu20.04
Problem you have experienced: Why can't waypoints be generated and drawn in a certain section of 'town01'? How can I get the coordinates of the road selected in the red box as shown in the picture?
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=767403596344569926 skey=@crypt_480cdcc4_9ca205e4d386cf52e46dee7c6037e8f9 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/df4571d0-3673-4370-a94e-c1c99150b673)

**Comment by Blyron** [comment]
Waypoints are there. Please use Town01_Opt in order to have better experience, it may be the case you are not getting them properly
![image](https://github.com/user-attachments/assets/5d78634d-8333-43f0-8d3a-68bbfe64f14c)
