### ISSUE TITLE
【UE5】【build on windows】failed with undefine symbol of carla::throw_exception

### ISSUE THREAD

**Issue by chaoer** [carla-simulator/carla#7996]
**CARLA version**: ue5_dev
**Platform/OS**: Windows 11
**Problem you have experienced**: cmake --bulid Build failed
**What you expected to happen**:
```
LINK: command "D:\Tools\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\carla-server.rsp /out:LibCarla\carla-server.dll /implib:LibCarla\carla-server.lib /pdb:LibCarla\carla-server.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO /MANIFEST:EMBED,ID=2" failed (exit code 1120) with the following output:
ServerSession.cpp.obj : error LNK2001: undefine symbol "void __cdecl carla::throw_exception(class std::exception const &)" (?throw_exception@carla@@YAXAEBVexception@std@@@Z)
StreamStateBase.cpp.obj : error LNK2001: undefine symbol "void __cdecl carla::throw_exception(class std::exception const &)" (?throw_exception@carla@@YAXAEBVexception@std@@@Z)
```
**Steps to reproduce**:
Other information (documentation you consulted, workarounds you tried):
following the instruction on at https://docs.google.com/document/d/1aWcoJr-9z_wE6S442UhzC32jUGmN1o42REE7C-4aGYA/edit

**Possible reason**:
I noticed that in the [CMakeLists.txt under LibCala](https://github.com/carla-simulator/carla/blob/543f02ea0ef09a4bd11b92c6ecac9c50b95b12de/LibCarla/CMakeLists.txt#L30), it tried to include source file "carla/Exception.cpp". 
However, there is no "Exception.cpp" file in branch "ue5_dev".
What should I do to fix this?

**Comment by Blyron** [comment]
Now this should be fixed. Get latest and try again
