### ISSUE TITLE
Cameras suddenly got messed up

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#8]
In in middle of driving all the cameras suddenly got messed up. After the next reset the issue was solved. See screenshots.
![screenshot from 2017-10-26 11-48-24](https://user-images.githubusercontent.com/4332953/32336884-cff2c308-bff0-11e7-8bd6-3fa3cf8cb723.png)
![screenshot from 2017-10-26 11-48-30](https://user-images.githubusercontent.com/4332953/32336888-d25e0ed6-bff0-11e7-966a-dd8fc44c7c53.png)
![screenshot from 2017-10-26 11-48-42](https://user-images.githubusercontent.com/4332953/32336894-d47f68f4-bff0-11e7-8716-ee6887269f23.png)
![screenshot from 2017-10-26 11-47-52](https://user-images.githubusercontent.com/4332953/32336868-c47e592e-bff0-11e7-9abc-9d33bc8c7817.png)

**Comment by marcgpuig** [comment]
We are going to update the Unreal version from 4.17 to 7.18 and we believe that should fix this issue.
If the problem persist, please, reopen this issue.

Thanks.
