### ISSUE TITLE
Change in Server

### ISSUE THREAD

**Issue by FarzanehJafari** [carla-simulator/carla#800]
Hi,
I am going to change the server quiet a bit. I would like both of client and server control vehicles with keyboard. What do I  do about this problem? Could you help me?
Thanks,

**Comment by FarzanehJafari** [comment]
Hi,
I added a parameter to Player_Carla_Measurements and sent to client. Client Could read this data, but after a second, Carla crashed. 
What do you think about this problem?

**Comment by FarzanehJafari** [comment]
[
![untitled](https://user-images.githubusercontent.com/38608730/45946081-9929df00-bfa4-11e8-8290-f1c0f0bd427d.png)
](url)

**Comment by nsubiron** [comment]
Hi @FarzanehJafari,

We provide a Python script that allows controlling the player vehicle with the keyboard: `manual_control.py`, wouldn't that work for you?

**Comment by FarzanehJafari** [comment]
Hi, this python code woked fo me, but I want driving both with client and sometimes with server sach as change weathers with server. Does it work possible? and Which classes should be change on server side?Another problem is about benchmark driving. python code doesnt work for me and there isnt run_driving_benchmark in directory. Thanks a lot,


Sent from Yahoo Mail for iPhone


On Tuesday, September 25, 2018, 10:35, Néstor Subirón <notifications@github.com> wrote:


Hi @FarzanehJafari,

We provide a Python script that allows controlling the player vehicle with the keyboard: manual_control.py, wouldn't that work for you?

**Comment by nsubiron** [comment]
Having both inputs simultaneously is a bit tricky since they will interfere with each other, as both inputs are being applied to the vehicle continuously every frame.

Take a look at WheeledVehicleController.cpp, there is where we suppress the input from the simulator window when the client is active.

**Comment by FarzanehJafari** [comment]
which function of wheeledvehiclecontroller.cpp is doing this work? I dont found it.


Sent from Yahoo Mail for iPhone


On Tuesday, September 25, 2018, 11:41, Néstor Subirón <notifications@github.com> wrote:


Having both inputs simultaneously is a bit tricky since they will interfere with each other, as both inputs are being applied to the vehicle continuously every frame.

Take a look at WheeledVehicleController.cpp, there is where we suppress the input from the simulator window when the client is active.

**Comment by nsubiron** [comment]
The `Set*Input()` functions at the bottom of the file,

```cpp
if (bAllowUserInput && !IsAutopilotEnabled()) {
  // set input here.
}
```
if Carla is running in server mode, `bAllowUserInput` is false.

**Comment by FarzanehJafari** [comment]
I set constant value for bAllowUserInput  = true, but yet, I couldnt
control vehicle with server. 🙁🙁
Whats your suggestion about it? Are there any parameters, I should be
changed?

**Comment by nsubiron** [comment]
As I mention, probably the input coming from the client is overwriting the input from the server, you'd need to find a way of merging both inputs.

**Comment by FarzanehJafari** [comment]
Excuse me for my questions. You tired to answer them and I am sorry about
it. last question, which classes can I see this Input functions for server
and standalone modes?
Thanks a lot for your help.😳

**Comment by nsubiron** [comment]
Hi @FarzanehJafari, no worries. The input from the keyboard comes from that class, WheeledVehicleController.cpp; and the input from the client-side comes from `DataRouter::ApplyVehicleControl` in DataRouter.h. But every frame you get control from both sides (including 0.0 if the key is not pressed), so the last one writing is the one that actually applies. The tricky part is how to combine these two so the vehicle control still makes sense.

**Comment by FarzanehJafari** [comment]
Hi, Thank you very much. I could use from Client and Server for control Vehicle. but, I have another question about add a parameter to measurements and send to client. I add an integer parameter to void FCarlaEncoder::Encode() function and run. but I have this Error

**Comment by FarzanehJafari** [comment]
[Desktop/45946081-9929df00-bfa4-11e8-8290-f1c0f0bd427d.png](url)

**Comment by FarzanehJafari** [comment]
![45946081-9929df00-bfa4-11e8-8290-f1c0f0bd427d](https://user-images.githubusercontent.com/38608730/46254365-088b4d00-c443-11e8-8a60-e007de0e40cf.png)

**Comment by nsubiron** [comment]
That's not an error, those are variables optimized by the compiler. If you change the configuration to debug in Visual Studio you'll see those variables.

**Comment by FarzanehJafari** [comment]
I dont understand exactly? could you explain about it for me with more
details? Thanks

**Comment by nsubiron** [comment]
Sorry, those are general programming issues we cannot give support to.

I would recommend reading more about how the compiler optimizes code, and how Visual Studio debugging works, e.g.

- https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-optimized-code?view=vs-2017
- https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-debug-and-release-configurations?view=vs-2017

Hope those links are a good starting point.

**Comment by FarzanehJafari** [comment]
Thaks a lot


Sent from Yahoo Mail for iPhone


On Sunday, September 30, 2018, 12:36, Néstor Subirón <notifications@github.com> wrote:


Sorry, those are general programming issues we cannot give support to.

I would recommend reading more about how the compiler optimizes code, and how Visual Studio debugging works, e.g.
   
   - https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-optimized-code?view=vs-2017
   - https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-debug-and-release-configurations?view=vs-2017

Hope those links are a good starting point.
