### ISSUE TITLE
Lacking model details of car interiors

### ISSUE THREAD

**Issue by JamareGitHub** [carla-simulator/carla#8002]
Hey,
I'm using Carla to simulate driving a Car from a Driver Perspective with Smart HUD Elements and noticed a lot of vehicles look very good from outside but appear to be unfinished on the inside, like see-through side panels, very simple squary steering wheels or missing elements like a rear-view-mirror holder but no mirror attached to it. Are there any plans to finish/rework those models? I'd be happy to provide a list of errors that I noticed.
Best Regards

**Comment by RodrigoVillarias** [comment]
Hello, right now we are working on the rework of some of the vehicles, especially focusing on the exterior. The newer models (the latest generation of vehicles) that we are working on do have a more detailed interior, but right now we are not focusing on that part. If you feel like it at some point, feel free to make any kind of contribution, you can upload the geometry improvements of any vehicle and make us a pull request. Have a nice day!

![image](https://github.com/user-attachments/assets/26229ac1-3e97-459d-b44a-87abd11b6c6f)
![image](https://github.com/user-attachments/assets/d5c504ce-4a93-42ae-8b03-5c40570d126e)
![image](https://github.com/user-attachments/assets/f6d18bc3-5595-4ea5-b21a-82cd44d1acf2)
![image](https://github.com/user-attachments/assets/912e201b-adb7-46fe-aa10-bd1f948487bf)
