### ISSUE TITLE
Skyscrapers - Office II

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#8008]
Skyscraper atoms

![Image](https://github.com/carla-simulator/carla/assets/54811869/23985812-e977-4f99-a098-4dc67f41abb6)

**Comment by gsmario** [comment]
![Image](https://github.com/user-attachments/assets/76613810-7ce4-4c79-9d9d-509afaad7fad)

**Comment by gsmario** [comment]
Fix reflection zfighting moving the geometry.
