### ISSUE TITLE
How can I import Town12 and packaing all the maps build from source on branch ue5.3 ?

### ISSUE THREAD

**Issue by RobotiX101** [carla-simulator/carla#8012]
![screenshot-20240801-184039](https://github.com/user-attachments/assets/a47a45ab-3be4-4be9-9a74-882298b8c45f)

Try to add it into edit->project settings->map list. but got 
'''
 ERROR: unable to parse the OpenDRIVE XML string
'''
while using 
```
python config.py --map Town12
```

**Comment by Blyron** [comment]
Is not supported yet. Only Town10 is available

**Comment by RobotiX101** [comment]
> Is not supported yet. Only Town10 is available

Hi，do you have plan for supporting all maps? Or todo list that I can help ?

**Comment by Blyron** [comment]
We are planning to support them, we need to redo tons of assets to make them nannite lumen compatible and get proper visuals
