### ISSUE TITLE
velocity of nonplayer vehicle

### ISSUE THREAD

**Issue by nberinpa** [carla-simulator/carla#802]
Hi,

is it possible to set the velocity of a non-player vehicle? Is it possible to change the acceleration of a non-player vehicle? Currently, I set the max speed in WheeledVehicleAIController to 100 and compiled it. However, the non-player vehicle still drives around 25 km/h even though I changed all the speed signs to 100 km/h (see image: at the start point the vehicle is in standstill and at the end point it has a velocity around 25 km/h. The player agent is at marked coordinate position and it is not in movement). 

![screenshot from 2018-09-23 10-05-14](https://user-images.githubusercontent.com/26043007/45930750-bb761b00-bf18-11e8-8f26-cf3208c42171.png)

Best wishes,
Niji

**Comment by nsubiron** [comment]
@nberinpa, I think by default the vehicles start with a speed limit of 30km/h, but the moment they enter the trigger box of a 100 speed limit they should start increasing the speed. Isn't that working?

@SoumiDas, this is the view from the Unreal Editor, you need to compile Carla from source to start the editor.
