### ISSUE TITLE
Unable to install clang-5.0, lld-5.0 and g++-7

### ISSUE THREAD

**Issue by Abanoub-G** [carla-simulator/carla#803]
Hi,
    I am trying to install CARLA on a raspberry pi. However, I am stuck at trying to run this command:

sudo apt-get install build-essential clang-5.0 lld-5.0 g++-7 ninja-build python python-pip python-dev tzdata sed curl wget unzip autoconf libtool

I get this error:
E: Unable to locate package clang-5.0
E: Couldn't find any package by glob 'clang-5.0'
E: Couldn't find any package by regex 'clang-5.0'
E: Unable to locate package lld-5.0
E: Couldn't find any package by glob 'lld-5.0'
E: Couldn't find any package by regex 'lld-5.0'
E: Unable to locate package g++-7
E: Couldn't find any package by regex 'g++-7'

I have tried doing everything I can do but I am not sure what is going wrong. Without the clang-5.0 I can not build the Unreal Engine. It is worth mentioning that I am doing this through ssh i.e. on a headless raspberry pi. 

Many Thanks
Abanoub

**Comment by nsubiron** [comment]
Hi @Abanoub-G, 

You can probably download the packages from their release pages. But seriously, I wouldn't bother, Unreal Engine is not going to work on a raspberry pi, check out their [recommended hardware](https://wiki.unrealengine.com/Recommended_Hardware); and Carla uses a lot more resources on top of that. Unfortunately, Carla requires a relatively expensive graphics card to run smoothly.

If you still want to give it a try, I would download a [pre-compiled Carla](https://github.com/carla-simulator/carla/releases) and try to run it before getting into the trouble of compiling it yourself.
