### ISSUE TITLE
Confusion about recommended Ubuntu version (20 or 22?) to build CARLA with UE5

### ISSUE THREAD

**Issue by J160KU** [carla-simulator/carla#8042]
Hello everybody,

On GitHub **Ubuntu 20** is recommended:

<kbd>![image](https://github.com/user-attachments/assets/a9a6a58f-d1df-4346-8fbf-40f7de8e2157)</kbd>
Source: https://github.com/carla-simulator/carla/tree/ue5-dev

Following the link further down to the official CARLA docs not **Ubuntu** 20 but **22** is recommended:

<kbd>![image](https://github.com/user-attachments/assets/1363faf3-51a4-4d36-8f67-1d6668b49cca)</kbd>
Source: https://carla.readthedocs.io/en/latest/build_linux_ue5/

<br></br>
**Question**: Could you please define this clearly? Otherwise I would expect that both versions Ubuntu 20 and 22 are recommended.

**Comment by DnDare** [comment]
HI, 
If you wany to try UE5.3  you've better use Ubuntu 22.04

**Comment by gsmario** [comment]
Yes, as @DnDare said, you should use ubuntu 22.04 to install carla on ue5.
Thank you for leting us know about this, we will update the documentation!

**Comment by MattRoweEAIF** [comment]
README.md is now updated, thank you for pointing this out. Closing this issue
