### ISSUE TITLE
Vehicle Physics in Carla

### ISSUE THREAD

**Issue by AOOOOOA** [carla-simulator/carla#8046]
Hi,
I have a question regarding vehicle physics in CARLA. It's known that CARLA utilizes Nvidia PhysX in Unreal Engine 4 and Chaos in Unreal Engine 5 for physics simulation. My inquiry is: Do all vehicles provided in CARLA share a uniform physics and dynamics model, or do they have distinct physical properties based on their individual sizes and characteristics?

**Comment by RodrigoVillarias** [comment]
Hello, yes, each vehicle depending on the size and model has different physical properties, right now we are trying to study the real models in the real models for differences in weight, traction, braking type, etc.. adapting it to chaos

**Comment by AOOOOOA** [comment]
> Hello, yes, each vehicle depending on the size and model has different physical properties, right now we are trying to study the real models in the real models for differences in weight, traction, braking type, etc.. adapting it to chaos

I'm interested in how different vehicle types are set up in CARLA using the PhysX model. I searched through the CARLA code but couldn't find the specific implementation in UE4 or the NVIDIA PhysX SDK. How is the configuration for different vehicle models achieved? Thanks.
