### ISSUE TITLE
ERROR: Platform Linux is not a valid platform to build. Check that the SDK is installed properly.

### ISSUE THREAD

**Issue by ShinSar** [carla-simulator/carla#8047]
CARLA version:0.9.15.2
Platform/OS:ubuntu 20.04
I am trying to build CARLA 0.9.15.2 following the https://carla.readthedocs.io/en/0.9.13/build_linux/ documentation. I have reached until the unreal engine setup and when I am running the  ./Setup.sh && ./GenerateProjectFiles.sh && make command, I see the following error: 
make
bash "/home/shinjinisarkar/UnrealEngine_4.26/Engine/Build/BatchFiles/Linux/Build.sh" CrashReportClient Linux Shipping  
Fixing inconsistent case in filenames.
Setting up Mono
Running command : Engine/Binaries/DotNET/UnrealBuildTool.exe CrashReportClient Linux Shipping
Using 'git status' to determine working set for adaptive non-unity build (/home/shinjinisarkar/UnrealEngine_4.26).
Creating makefile for CrashReportClient (no existing makefile)
ERROR: Platform Linux is not a valid platform to build. Check that the SDK is installed properly.
make: *** [Makefile:302: CrashReportClient-Linux-Shipping] Error 6

My this path:UnrealEngine_4.26/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64 is empty. How can I install SDK propely? I dwonloaded the appropriate toolchain from here https://dev.epicgames.com/documentation/en-us/unreal-engine/cross-compiling-for-linux?application_version=4.27 . But that is a .exe file. I unzipped it and ran the toolchain: UnrealEngine_4.26/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/build/scripts$ ./build_linux_toolchain.sh. But that also throws some error.

when I tried installing clang-8, it throws the following error:
The following packages have unmet dependencies:
 clang-8 : Depends: libllvm8 (>= 1:8~svn298832-1~) but it is not going to be installed
           Depends: libstdc++-5-dev but it is not installable
           Depends: libgcc-5-dev but it is not installable
           Depends: libobjc-5-dev but it is not installable
           Depends: libclang-common-8-dev (= 1:8.0.1+svn369350-1~exp1~20200112113617.82) but it is not going to be installed
           Depends: libclang1-8 (= 1:8.0.1+svn369350-1~exp1~20200112113617.82) but it is not going to be installed
           Recommends: llvm-8-dev but it is not going to be installed
           Recommends: libomp-8-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

This cannot be solved with sudo apt --fix-broken install

Please help me solve this issue.

**Comment by nithinkashyap-nikola** [comment]
Were you able to resolve this issue?

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

I have seen this issue come up a couple of times. It appears that the clang toolset is not being downloaded correctly when running the UE setup script. A workaround is to download `Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64` manually from the link that can be found in the corresponding script.
