### ISSUE TITLE
make launch failed

### ISSUE THREAD

**Issue by ShahzebTUMBachelor** [carla-simulator/carla#8048]
getting this error:
/media/shahzeb/Volume/UnrealEngine_4.26/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:234:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
4 warnings generated.
3 warnings generated.
[58/66] Compile CarlaUE4.cpp
8 warnings generated.
15 warnings generated.
8 warnings generated.
[59/66] Link (lld) libUE4Editor-Carla.so
[60/66] Link (lld) libUE4Editor-StreetMapRuntime.so
[61/66] Link (lld) libUE4Editor-CarlaUE4.so
[62/66] Link (lld) libUE4Editor-StreetMapImporting.so
make[1]: *** [Makefile:315: CarlaUE4Editor] Error 6
make[1]: Leaving directory '/media/shahzeb/Volume/new_carla/carla/Unreal/CarlaUE4'
make: *** [Util/BuildTools/Linux.mk:8: launch] Error 2

What is the problem and how can I solve it?

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

This does not show the actual error. Could you share the entire build log?
