### ISSUE TITLE
cant launch scenario runner

### ISSUE THREAD

**Issue by Turuu1124** [carla-simulator/carla#8051]
Hello,
OS: windows11
carla version: 0.9.15
python: 3.7 anaconda prompt

i am having a problem getting scenario runner working, i cant get it to open and it keeps giving me different errors as shown below, guided by this [thread](https://github.com/carla-simulator/scenario_runner/issues/896) i tried setting PYTHONPATH as shown in the images. i feel like i have tried everything and nothing seems to be working, any help would be greatly appreciated.

![Screenshot 2024-08-13 140138](https://github.com/user-attachments/assets/8366c7b4-2a52-4fa0-8e56-35e61ca17153)
![Screenshot 2024-08-13 140139](https://github.com/user-attachments/assets/03e94760-28ad-42b5-9fa0-2d0fd149ba9a)
![Screenshot 2024-08-13 140220](https://github.com/user-attachments/assets/f8d35128-3c2a-4331-83c4-fec7dbe7df30)
![Screenshot 2024-08-13 140221](https://github.com/user-attachments/assets/7b3f7e03-f2b4-4ace-871e-272ce41bb947)
![Screenshot 2024-08-13 140244](https://github.com/user-attachments/assets/3d875ebf-4fe6-41bb-96ac-244b4348ad42)

**Comment by PatrickPromitzer** [comment]
Hi,
you can try installing numpy version 1.22
```
path/to/python -m pip install numpy==1.22
```

**Comment by Turuu1124** [comment]
thank you for your input, the issue has been fixed.
