### ISSUE TITLE
LightManager Not Working Properly in Large Maps

### ISSUE THREAD

**Issue by GoodarzMehr** [carla-simulator/carla#8057]
CARLA version: 0.9.15
Platform/OS: Ubuntu 22.04

In my experiments I noticed that LightManager is only able to access and control (turn on/off, change color etc.) some of the street/building lights in Town15 and not all of them, where the lights are unaffected by changes applied through the LightManager.

It seems the problem comes from the fact that in Town15 the light IDs are all set to -1, and clicking Update Light IDs seems to have resolved the issue by assigning a unique ID to each light.

Another issue is that a lot of building lights seem to have been misclassified as street lights. I think this can be resolved by changing the light type in BP_Building from Street to Building.

BTW any plans on adding building lights to Town12?

**Comment by AntonioCarla** [comment]
Same way with the buildings, check your lights have a BP Lights component set to street light.
