### ISSUE TITLE
Error running ./Update.sh

### ISSUE THREAD

**Issue by SpakMiguel** [carla-simulator/carla#806]
Hello,

I have removed old CARLA version and want to build version 0.9 from scratch and UE4.19. Unreal builds fine, no problems here. I complete all the steps until the one I have to download the assets. When running the script ./Update.sh I get the following:
```

Backing up existing Content...
'/home/f80lab1/UnrealEngine_4.19/carla/Unreal/CarlaUE4/Content/Carla' -> '/home/f80lab1/UnrealEngine_4.19/carla/Unreal/CarlaUE4/Content/Carla_20180926180632'
Downloading Content.tar.gz...    32.77KB                                        Done.

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I have followed the links of the message and they are all empty. It looks like the script creates a folder each time it runs but if it downloads something it is not shown or uncompressed.

Any ideas?

Thanks,

**Comment by nsubiron** [comment]
Somehow it is not really downloading the content, only 32KB but should be around 3GB. Maybe Google Drive is blocked in your network.

As workaround you can download manually the package and extract it to `Unreal/CarlaUE4/Content/Carla`. You can find the link to the latest version in our [ContentVersions.txt](https://github.com/carla-simulator/carla/blob/master/Util/ContentVersions.txt).

Or alternatively, if Google Drive is too slow you can clone our repo with git-lfs.

    git lfs clone -b 0.9.0 https://bitbucket.org/carla-simulator/carla-content
