### ISSUE TITLE
Skyscraper - Bottom Shops

### ISSUE THREAD

**Issue by Madecu** [carla-simulator/carla#8060]
![Image](https://github.com/carla-simulator/carla/assets/54811869/542fb5ec-12a8-4660-98e6-2e602fa8fb4c)

**Comment by DnDare** [comment]
![ScreenShot00005](https://github.com/user-attachments/assets/85c177c1-c24d-4a72-83b0-c13de3febd8d)
![ScreenShot00003](https://github.com/user-attachments/assets/757ec649-625d-44a4-a3dc-2b467d504050)
![ScreenShot00006](https://github.com/user-attachments/assets/f2258d62-eb84-449e-a2c5-7868eef73326)
