### ISSUE TITLE
Carla crushes out after exactly a minute

### ISSUE THREAD

**Issue by Marquinhios** [carla-simulator/carla#8067]
CARLA version: modified binary of the version 0.8.4 CARLA

Platform/OS: Windows 11 Home

Problem you have experienced: It crushed out exactly after a minute of use

What you expected to happen: At first, I expected it to run without a limit. Then with a timeout of 1000.

Steps to reproduce: run Start-Process -FilePath "CarlaUE4.exe" -ArgumentList "/Game/Maps/RaceTrack", "-quality-level=Low -windowed -ResX=1280 -ResY=720" on the cmd

Other information (documentation you consulted, workarounds you tried): I tried to use the -carla-timeout=1000 command but it didn't work. Also tried to check for the details on the crush report:
[CrashReportClient]
bHideLogFilesOption=false
bIsAllowedToCloseWithoutSending=true
CrashConfigPurgeDays=2

**Comment by jorge-kabuto** [comment]
I would need a crash report to have visibility on the error, but changes are that with such an old version of CARLA (0.8.4 is six years old) we can't offer much support, since the codebase has radically changed. It should located under Unreal/Saved/Crashes
