### ISSUE TITLE
CARLA 0.9.X performance analysis

### ISSUE THREAD

**Issue by germanros1987** [carla-simulator/carla#807]
Hi,

We should run a performance analysis (FPS) for the 0.9.x branch for Town01, Town02 and Town03, with the following sensor configurations:

- 1 camera resolution 800x600, fov 90 deg
- 1 camera resolution 800x600, fov 110 deg
- 1 camera resolution 1280×720, fov 90 deg
- 1 camera resolution 1280×720, fov 110 deg
- 1 camera resolution 1920×1080, fov 90 deg
- 1 camera resolution 1920×1080, fov 110 deg
- 1 camera resolution 2048×1080, fov 90 deg
- 1 camera resolution 2048×1080, fov 110 deg

- 2 cameras resolution 800x600, fov 90 deg
- 2 cameras resolution 800x600, fov 110 deg
- 2 cameras resolution 1280×720, fov 90 deg
- 2 cameras resolution 1280×720, fov 110 deg
- 2 cameras resolution 1920×1080, fov 90 deg
- 2 cameras resolution 1920×1080, fov 110 deg
- 2 cameras resolution 2048×1080, fov 90 deg
- 2 cameras resolution 2048×1080, fov 110 deg

- 3 cameras resolution 800x600, fov 90 deg
- 3 cameras resolution 800x600, fov 110 deg
- 3 cameras resolution 1280×720, fov 90 deg
- 3 cameras resolution 1280×720, fov 110 deg
- 3 cameras resolution 1920×1080, fov 90 deg
- 3 cameras resolution 1920×1080, fov 110 deg
- 3 cameras resolution 2048×1080, fov 90 deg
- 3 cameras resolution 2048×1080, fov 110 deg

I guess we would need to come up with the right Near and Far values.
We need to have a table with these results.

**Comment by nsubiron** [comment]
There is a Python script for benchmarking the simulator in different situations (cameras, weather, number of NPCs), [benchmark_server.py](https://github.com/carla-simulator/carla/blob/master/PythonClient/test/benchmark_server.py). It haven't been ported to 0.9 yet though.

There is also a benchmark of the streaming library (standalone) that is run on every Jenkins job, e.g. see profiler.csv file in the [artifacts section](http://158.109.9.218:8080/blue/organizations/jenkins/carla/detail/issue%23750/24/artifacts).

It would be great if we can port the Python benchmark to 0.9 API and run it on Jenkins.
