### ISSUE TITLE
availibility of truck with trailer

### ISSUE THREAD

**Issue by ahsan155** [carla-simulator/carla#8074]
I need a vehicle for my use case where the vehicle is attached to a trailer. Carla now has a semi truck. Is there a way to attach it to a trailer and make it work in the simulation. It would be great if I can get a walk through of how to make it work by using blender and unreal engine.

**Comment by GoodarzMehr** [comment]
Hi, #5476 may be helpful.

**Comment by RodrigoVillarias** [comment]
Right now we don't have truck with trailer available, but as GoodarzMehr pointed out, you can follow the thread of issue [https://github.com/carla-simulator/carla/discussions/5476](url)
