### ISSUE TITLE
vulkan run error

### ISSUE THREAD

**Issue by hellojql** [carla-simulator/carla#8088]
CommonUnixCrashHandler: Signal=11
[2024.08.29-04.56.45:409][ 97]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000088

[2024.08.29-04.56.45:409][ 97]LogCore: Fatal error!

0x00000000048b5124 CarlaUE4-Linux-Shipping!FPackedUniformBuffers::Init(FVulkanShaderHeader const&, unsigned long long&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanResources.h:1429]
0x00000000048b5a7e CarlaUE4-Linux-Shipping!FVulkanGraphicsPipelineDescriptorState::FVulkanGraphicsPipelineDescriptorState(FVulkanDevice*, FVulkanRHIGraphicsPipelineState*) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanPipelineState.cpp:234]
0x00000000048a7d56 CarlaUE4-Linux-Shipping!FVulkanPendingGfxState::SetGfxPipeline(FVulkanRHIGraphicsPipelineState*, bool) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanPendingState.cpp:937]
0x00000000048b5f5c CarlaUE4-Linux-Shipping!FVulkanCommandListContext::RHISetGraphicsPipelineState(FRHIGraphicsPipelineState*, bool) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanPipelineState.cpp:361]
0x00000000049a9b19 CarlaUE4-Linux-Shipping!FRHICommandListExecutor::ExecuteInner_DoExecute(FRHICommandListBase&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHICommandList.cpp:373]
0x00000000049ab61f CarlaUE4-Linux-Shipping!FRHICommandListExecutor::ExecuteInner(FRHICommandListBase&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHICommandList.cpp:658]
0x00000000049ac5ec CarlaUE4-Linux-Shipping!FRHICommandListExecutor::ExecuteList(FRHICommandListBase&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHICommandList.cpp:682]
0x00000000049cc1f9 CarlaUE4-Linux-Shipping!FRHICommandListBase::~FRHICommandListBase() [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHICommandList.cpp:923]
0x00000000049cdd49 CarlaUE4-Linux-Shipping!FRHICommandWaitForAndSubmitSubList::Execute(FRHICommandListBase&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHICommandList.cpp:1109]
0x00000000049cd3f9 CarlaUE4-Linux-Shipping!FRHICommand<FRHICommandWaitForAndSubmitSubList, FRHICommandWaitForAndSubmitSubListString1075>::ExecuteAndDestruct(FRHICommandListBase&, FRHICommandListDebugContext&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Public/RHICommandList.h:763]
0x00000000049a9b19 CarlaUE4-Linux-Shipping!FRHICommandListExecutor::ExecuteInner_DoExecute(FRHICommandListBase&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHICommandList.cpp:373]
0x00000000049d4a06 CarlaUE4-Linux-Shipping!FExecuteRHIThreadTask::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHICommandList.cpp:428]
0x00000000049d433b CarlaUE4-Linux-Shipping!TGraphTask<FExecuteRHIThreadTask>::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/Core/Public/Async/TaskGraphInterfaces.h:886]
0x00000000033a6e08 CarlaUE4-Linux-Shipping!FNamedTaskThread::ProcessTasksNamedThread(int, bool) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/Core/Private/Async/TaskGraph.cpp:709]
0x00000000033a5afe CarlaUE4-Linux-Shipping!FNamedTaskThread::ProcessTasksUntilQuit(int) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/Core/Private/Async/TaskGraph.cpp:600]
0x0000000004a078cc CarlaUE4-Linux-Shipping!FRHIThread::Run() [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/RenderCore/Private/RenderingThread.cpp:319]
0x0000000003405e03 CarlaUE4-Linux-Shipping!FRunnableThreadPThread::Run() [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.cpp:25]
0x00000000033e6450 CarlaUE4-Linux-Shipping!FRunnableThreadPThread::_ThreadProc(void*) [/home/helloliu/work/code/UnrealEngine_4.26/Engine/Source/Runtime/Core/PriMalloc Size=131160 LargeMemoryPoolOffset=196744 
Malloc Size=131160 LargeMemoryPoolOffset=327928 
Malloc Size=140854 LargeMemoryPoolOffset=468806 
vate/HAL/PThreadRunnableThread.h:185]
0x00007f28d1d1cac3 libc.so.6!UnknownFunction(0x94ac2)
0x00007f28d1dae850 libc.so.6!UnknownFunction(0x12684f)

[2024.08.29-04.56.45:419][ 97]LogExit: Executing StaticShutdownAfterError
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

This log does not give enough information. What CARLA version is this? In which map were you?

Marcel
