### ISSUE TITLE
Build a package with CARLA UE5 Error!!

### ISSUE THREAD

**Issue by qq1183713118** [carla-simulator/carla#8091]
CARLA version:0.9.15
Platform/OS:WIN10
Problem you have experienced:
What you expected to happen:When building a package, an error message is always displayed.
There is a lot of repetitive information

``
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDirectionalLightCSMAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cooked packages 8002 Packages Remain 434 Total 8436
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDirectionalLightAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FLocalVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64SkylightLOCAL_LIGHTS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64LOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cooked packages 8002 Packages Remain 434 Total 8436
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FGeometryCollectionVertexFactory/TMobileBasePassPSFMobileDirectionalLightAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDirectionalLightCSMAndLightMapPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsAndLQLightMapPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cooker has been blocked from saving the current packages for 1201 seconds.
LogCook: Display: 434 packages in the savequeue:
LogCook: Display:     /Engine/EngineMaterials/DefaultTextMaterialOpaque
LogCook: Display:     /Game/Carla/Static/Car/GeneralMaterials/MaterialRedirectors/DummyCar
LogCook: Display:     /Game/Carla/Static/GenericMaterials/Masters/M_BasicMaterial
LogCook: Display:     /Game/Carla/Static/GenericMaterials/Vehicles/M_CarLightsGlass_Master
LogCook: Display:     /Game/Carla/Static/Static/Materials/PlantPot03/M_PlantPot03
LogCook: Display:     /Game/Carla/Static/Particles/Leaves/M_Leaf_falling
LogCook: Display:     /Game/Carla/Static/Dynamic/PedestrianProps/Materials/Phone/M_Mobile
LogCook: Display:     /Game/Carla/Static/Dynamic/Trash/Materials/GarbageAtlas/M_GarbageAtlas
LogCook: Display:     /Game/Carla/Static/Car/4Wheeled/Jeep/Textures_Shadders/JeepWranglerRubicon_White_Mat
LogCook: Display:     /Game/Carla/Static/GenericMaterials/Vehicles/M_CarInteriorAlpha_Master
LogCook: Display:     ...
LogCook: Display: 177 objects that have not yet returned true from IsCachedCookedPlatformDataLoaded:
LogCook: Display:     Material /Engine/EngineMaterials/DefaultTextMaterialOpaque.DefaultTextMaterialOpaque
LogCook: Display:     Material /Game/Carla/Static/Car/GeneralMaterials/MaterialRedirectors/DummyCar.DummyCar
LogCook: Display:     Material /Game/Carla/Static/GenericMaterials/Masters/M_BasicMaterial.M_BasicMaterial
LogCook: Display:     Material /Game/Carla/Static/GenericMaterials/Vehicles/M_CarLightsGlass_Master.M_CarLightsGlass_Master
LogCook: Display:     Material /Game/Carla/Static/Static/Materials/PlantPot03/M_PlantPot03.M_PlantPot03
LogCook: Display:     Material /Game/Carla/Static/Particles/Leaves/M_Leaf_falling.M_Leaf_falling
LogCook: Display:     Material /Game/Carla/Static/Dynamic/PedestrianProps/Materials/Phone/M_Mobile.M_Mobile
LogCook: Display:     Material /Game/Carla/Static/Dynamic/Trash/Materials/GarbageAtlas/M_GarbageAtlas.M_GarbageAtlas
LogCook: Display:     Material /Game/Carla/Static/Car/4Wheeled/Jeep/Textures_Shadders/JeepWranglerRubicon_White_Mat.JeepWranglerRubicon_White_Mat
LogCook: Display:     Material /Game/Carla/Static/GenericMaterials/Vehicles/M_CarInteriorAlpha_Master.M_CarInteriorAlpha_Master
LogCook: Display:     ...
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cooked packages 8002 Packages Remain 434 Total 8436
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cook Diagnostics: OpenFileHandles=8439, VirtualMemory=14844MiB
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FGeometryCollectionVertexFactory/TMobileBasePassPSFMobileDirectionalLightCSMAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FGeometryCollectionVertexFactory/TMobileBasePassPSFMobileDirectionalLightCSMAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64SkylightLOCAL_LIGHTS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDirectionalLightCSMAndLightMapPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsAndLQLightMapPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cooker has been blocked from saving the current packages for 1321 seconds.
LogCook: Display: 434 packages in the savequeue:
LogCook: Display:     /Engine/EngineDebugMaterials/DebugEditorMaterial
LogCook: Display:     /Engine/EngineMaterials/PhAT_JointLimitMaterial
LogCook: Display:     /ControlRig/M_Manip
LogCook: Display:     /Engine/EngineDebugMaterials/M_VolumeRenderSphereTracePP
LogCook: Display:     /Engine/VREditor/TransformGizmo/TransformGizmoMaterial
LogCook: Display:     /HairStrands/Materials/HairDebugMaterial
LogCook: Display:     /Game/Carla/Static/GenericMaterials/Asphalt/Old/M_Asphalt01
LogCook: Display:     /Game/Carla/Static/Static/Materials/Stairs_T10/M_Stairs
LogCook: Display:     /Game/Carla/Static/Static/Materials/Add_2/M_Add_2
LogCook: Display:     /Game/Carla/Static/Hair/HairShaders/ProceduralHairCardsShader
LogCook: Display:     ...
LogCook: Display: 177 objects that have not yet returned true from IsCachedCookedPlatformDataLoaded:
LogCook: Display:     Material /Engine/EngineDebugMaterials/DebugEditorMaterial.DebugEditorMaterial
LogCook: Display:     Material /Engine/EngineMaterials/PhAT_JointLimitMaterial.PhAT_JointLimitMaterial
LogCook: Display:     Material /ControlRig/M_Manip.M_Manip
LogCook: Display:     Material /Engine/EngineDebugMaterials/M_VolumeRenderSphereTracePP.M_VolumeRenderSphereTracePP
LogCook: Display:     Material /Engine/VREditor/TransformGizmo/TransformGizmoMaterial.TransformGizmoMaterial
LogCook: Display:     Material /HairStrands/Materials/HairDebugMaterial.HairDebugMaterial
LogCook: Display:     Material /Game/Carla/Static/GenericMaterials/Asphalt/Old/M_Asphalt01.M_Asphalt01
LogCook: Display:     Material /Game/Carla/Static/Static/Materials/Stairs_T10/M_Stairs.M_Stairs
LogCook: Display:     Material /Game/Carla/Static/Static/Materials/Add_2/M_Add_2.M_Add_2
LogCook: Display:     Material /Game/Carla/Static/Hair/HairShaders/ProceduralHairCardsShader.ProceduralHairCardsShader
LogCook: Display:     ...
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDirectionalLightCSMAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64LOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cooked packages 8002 Packages Remain 434 Total 8436
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileMovableDirectionalLightCSMWithLightmapPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cooker has been blocked from saving the current packages for 1441 seconds.
LogCook: Display: 434 packages in the savequeue:
LogCook: Display:     /Engine/EngineMaterials/DefaultMaterial
LogCook: Display:     /Game/Carla/Static/GenericMaterials/Masters/LowComplexity/M_WaterMaster
LogCook: Display:     /Game/Carla/UE5UseOnly/Materials/MasterMaterials/M_Master_Generic
LogCook: Display:     /Game/Carla/Static/Particles/rain/M_Rain
LogCook: Display:     /Paper2D/OpaqueUnlitSpriteMaterial
LogCook: Display:     /Interchange/gltf/MaterialInstances/MI_Sheen_Opaque_DS
LogCook: Display:     /Game/Carla/Static/GenericMaterials/Emission/M_EmissionMaster
LogCook: Display:     /Game/Carla/Static/Other/M_Cable
LogCook: Display:     /Engine/EngineMaterials/WorldGridMaterial
LogCook: Display:     /Game/Carla/Static/Road/RoadsTown10HD/Concrete1_Sidewalk
LogCook: Display:     ...
LogCook: Display: 177 objects that have not yet returned true from IsCachedCookedPlatformDataLoaded:
LogCook: Display:     Material /Engine/EngineMaterials/DefaultMaterial.DefaultMaterial
LogCook: Display:     Material /Game/Carla/Static/GenericMaterials/Masters/LowComplexity/M_WaterMaster.M_WaterMaster
LogCook: Display:     Material /Game/Carla/UE5UseOnly/Materials/MasterMaterials/M_Master_Generic.M_Master_Generic
LogCook: Display:     Material /Game/Carla/Static/Particles/rain/M_Rain.M_Rain
LogCook: Display:     MaterialInstanceConstant /Paper2D/OpaqueUnlitSpriteMaterial.OpaqueUnlitSpriteMaterial
LogCook: Display:     MaterialInstanceConstant /Interchange/gltf/MaterialInstances/MI_Sheen_Opaque_DS.MI_Sheen_Opaque_DS
LogCook: Display:     Material /Game/Carla/Static/GenericMaterials/Emission/M_EmissionMaster.M_EmissionMaster
LogCook: Display:     Material /Game/Carla/Static/Other/M_Cable.M_Cable
LogCook: Display:     Material /Engine/EngineMaterials/WorldGridMaterial.WorldGridMaterial
LogCook: Display:     Material /Game/Carla/Static/Road/RoadsTown10HD/Concrete1_Sidewalk.Concrete1_Sidewalk
LogCook: Display:     ...
LogCook: Display: Cooked packages 8002 Packages Remain 434 Total 8436
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64LOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FLocalVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FGeometryCollectionVertexFactory/TMobileBasePassPSFMobileDirectionalLightAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_PREPASS_ENABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogCook: Display: Cook Diagnostics: OpenFileHandles=8439, VirtualMemory=14846MiB
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_17b68316f6fea10a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Freeway_Asphalt_28b092c24f487deb/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDirectionalLightCSMAndSHIndirectPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
LogShaderCompilers: Warning: Last Error 206: Failed to create directory for shader debug info 'E:/UGit/Carla/Unreal/CarlaUnreal/Saved/ShaderDebugInfo/PCD3D_ES3_1/M_Fabric_Master_9b3e027c5b14630a/Default/FInstancedStaticMeshVertexFactory/TMobileBasePassPSFMobileDistanceFieldShadowsLightMapAndCSMLightingPolicyHDRLinear64SkylightLOCAL_LIGHTS_DISABLED/0'. Try enabling large file paths or r.DumpShaderDebugShortNames.
``

**Comment by jorge-kabuto** [comment]
Reading the error code, this seems to be a problem with long file paths, exceeding the maximum supported by your system.

**Comment by lt-wang** [comment]
hello, I also have the same problem. Did you solve it?

**Comment by qq1183713118** [comment]
> 你好，我也有同样的问题。您解决了吗？



> hello, I also have the same problem. Did you solve it?

No, I ignored it because it didn't affect the operation.

**Comment by qq1183713118** [comment]
Thanks for your answers. I didn't compile Unreal on WSL, but used Linux instead. Thank you very much for your help.
