### ISSUE TITLE
build carla UE5 on win11(PythonAPI ERROR)

### ISSUE THREAD

**Issue by lt-wang** [carla-simulator/carla#8096]
CARLA version: 0.9.15
Platform/OS: win11
Problem you have experienced:
"cmake --build Build --target carla-python-api-install" error

What you expected to happen:
Steps to reproduce:
![image](https://github.com/user-attachments/assets/7fe018ce-ed1a-49bb-affb-2a85c76a30ae)
![image](https://github.com/user-attachments/assets/d02c177e-2574-49ec-b25b-d7b57392aba5)

Other information (documentation you consulted, workarounds you tried):

**Comment by MarcelPiNacy-CVC** [comment]
Hi, have you run `python -m pip install -r requirements.txt`?

**Comment by lt-wang** [comment]
> Hi, have you run `python -m pip install -r requirements.txt`?

I run this command and the problem is solved. Thanks for your reply.
