### ISSUE TITLE
Including LibCarla in a C++ project

### ISSUE THREAD

**Issue by harlowja** [carla-simulator/carla#810]
Due to how LibCarla (especially the client) builds its own version of boost and rpclib and cstdlib and clang and ... ? I am wondering if this code was made to be included by other C++ applications. It does not really appear that it is possible to use it as is (due to the bundled libraries and such) so I am wondering if there needs to be some kind of documentation saying yes this is possible, or no it isnt.

**Comment by nsubiron** [comment]
We have now an example [Examples/CppClient](https://github.com/carla-simulator/carla/tree/master/Examples/CppClient).

**Comment by jemishGhoghari** [comment]
> We have now an example [Examples/CppClient](https://github.com/carla-simulator/carla/tree/master/Examples/CppClient).

Hello @nsubiron,

How to build this Example on Windows? or Do you have any lead how to do that?

Any Help appreciated!

Thanks
