### ISSUE TITLE
How to build libcarla-unit-tests project?

### ISSUE THREAD

**Issue by donghaiwang** [carla-simulator/carla#8100]
There is no [.bat script](https://github.com/carla-simulator/carla/tree/dev/Util/BuildTools) and documents to generate libcarla-unit-tests project file according to [CMakeList.txt](https://github.com/carla-simulator/carla/blob/dev/LibCarla/cmake/test/CMakeLists.txt) .
CARLA version: 0.9.15
Platform/OS: Windows 10

**Comment by Blyron** [comment]
Unit tests are only available in Linux, you can generate your own if you wish. Look at make check
