### ISSUE TITLE
Access error when make launch

### ISSUE THREAD

**Issue by Sephiroth1118** [carla-simulator/carla#8103]
CARLA version: 0.9.15
Platform/OS: Ubuntu 20.04
Problem you have experienced: 
This is the log.
![Screenshot from 2024-09-03 14-36-00](https://github.com/user-attachments/assets/1d502db2-f525-4145-b4b6-d528210e00d7)
It should be a network error. But the strange thing is this link is 404 Page not found now. Amd yesterday when I run make launch it does not have this problem. I check the Plugins folder in carla and StreetMap does exist. What might be the problem? Does carla need to access this link everytime running make launch?
![Screenshot from 2024-09-03 14-50-41](https://github.com/user-attachments/assets/599f559a-b44f-457c-ab27-a9a594a6a389)
What you expected to happen:
Tell me what's happening.
Steps to reproduce:
No idea. Just run make launch.

**Comment by Sephiroth1118** [comment]
Another strange thing. Although I can not access this link in web browser, I can access it by git clone.

**Comment by Blyron** [comment]
Repository is still there https://github.com/carla-simulator/StreetMap
Try again

**Comment by Sephiroth1118** [comment]
> Repository is still there https://github.com/carla-simulator/StreetMap Try again

Thank you very much for your reply! I delete my carla folder and remake another one, it works again. But I'm confused that each time I run make launch, it will try to access ths Repo. If I do not connect to internet, make launch won't work. Is this normal? I'm new to Carla, it is kind of wierd that I can not run UE editor if I do not have internet connection.

**Comment by Blyron** [comment]
Our build system is not the best one. We are open to contributios while dealing with other stuff. Sorry for inconveniences
