### ISSUE TITLE
Segmentation Fault while executing CarlaUE4.sh

### ISSUE THREAD

**Issue by RogerAylagas** [carla-simulator/carla#811]
Hi,
While executing ./CarlaUE4.sh in Xubuntu to run Carla the terminal prints me the following error:

_Increasing per-process limit of core file size to infinity.
Signal 11 caught.
Malloc Size=131076 LargeMemoryPoolOffset=131092
CommonLinuxCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=196655
Malloc Size=78304 LargeMemoryPoolOffset=274976
Segmentation fault (core dumped)_

Do you know what's happening and why do I get this error?

**Comment by nsubiron** [comment]
That doesn't give much info, could it be related to this #757?

**Comment by RogerAylagas** [comment]
Sorry I finaly solve it.
Thank you!

**Comment by jingzhao3200** [comment]
> Sorry I finaly solve it.
> Thank you!

How do you solve it then? I have the similar problem as you...
Thanks!

**Comment by iamycee** [comment]
Hey @RogerAylagas, how did you solve it?

@jingzhao3200 did you end dup solving it?
