### ISSUE TITLE
Building CarlaUnrealEditor failed under WSL

### ISSUE THREAD

**Issue by qq1183713118** [carla-simulator/carla#8115]
I tried to build Carla's dev-ue5 branch under WSL but it failed.
I followed the UE5_BUILD_README file but it failed in Building CarlaUnrealEditor 

![1](https://github.com/user-attachments/assets/20b9425d-1244-4fd5-93c9-ae04f337f74f)
![2](https://github.com/user-attachments/assets/f351a567-d84c-4812-a7a4-b2a1ec038d3e)
![3](https://github.com/user-attachments/assets/98be353b-900e-41b9-9c2c-bda43175ae29)

**Comment by PatrickPromitzer** [comment]
Hi,
this is from the CarlaUE5 doc.
![image](https://github.com/user-attachments/assets/49e7a2c2-345d-4a08-a4c5-02412a677b6e)

I can see you use "/mnt/e/", which is the default path of an external drive.

**Comment by merryHunter** [comment]
I somehow missed this doc, but I faced similar issue trying to run Carla from WSL... and docker on windows didn't go well either :(

**Comment by qq1183713118** [comment]
> Hi, this is from the CarlaUE5 doc. ![image](https://private-user-images.githubusercontent.com/152880896/365143604-49e7a2c2-345d-4a08-a4c5-02412a677b6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODExODUsIm5iZiI6MTcyNTg4MDg4NSwicGF0aCI6Ii8xNTI4ODA4OTYvMzY1MTQzNjA0LTQ5ZTdhMmMyLTM0NWQtNGEwOC1hNGM1LTAyNDEyYTY3N2I2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMTIxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWYwMjc5NGQ0NWE4Yzk4NTUxZTk4MjJlOGExMDEzZDQzNmM4YmYwY2JkODE0YzU0MmVkZTg3NTczMGViNDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tS9NT-Chrl0pmuQF6P_L2gBmjXY1yB5F_qSq9GmtI5U)
> 
> I can see you use "/mnt/e/", which is the default path of an external drive.

Thanks, I'll try again

**Comment by PatrickPromitzer** [comment]
Don't use sudo.
The output is telling you "Refusing to run with the root privileges."
If you have a permission problem, you set them to 777 to make sure it works (755 would be better)
```
chmod -R 777 path/to/carla

or

sudo chmod -R 777 path/to/carla
```

I used this commands, because I had a problem with the ros installation

``` 
git clone -b ue5-dev https://github.com/carla-simulator/carla.git CarlaUE5

cd CarlaUE5

env GIT_LOCAL_CREDENTIALS=your_git_user@your_git_token bash -x CarlaSetup.sh

cmake -G Ninja -S . -B Build --toolchain=$PWD/CMake/LinuxToolchain.cmake -DLAUNCH_ARGS="-prefernvidia" -DCMAKE_BUILD_TYPE=Release -DBUILD_CARLA_UNREAL=ON -DCARLA_UNREAL_ENGINE_PATH=$CARLA_UNREAL_ENGINE_PATH

cmake --build Build --target launch
```

**Comment by qq1183713118** [comment]
> 不要使用 sudo。输出告诉您 “Refusing to run with the root privileges”。如果你有权限问题，你可以将它们设置为 777 以确保它有效（755 会更好）
> 
> ```
> chmod -R 777 path/to/carla
> 
> or
> 
> sudo chmod -R 777 path/to/carla
> ```
> 
> 我使用了这个命令，因为我在 ros 安装时遇到了问题
> 
> ```
> git clone -b ue5-dev https://github.com/carla-simulator/carla.git CarlaUE5
> 
> cd CarlaUE5
> 
> env GIT_LOCAL_CREDENTIALS=your_git_user@your_git_token bash -x CarlaSetup.sh
> 
> cmake -G Ninja -S . -B Build --toolchain=$PWD/CMake/LinuxToolchain.cmake -DLAUNCH_ARGS="-prefernvidia" -DCMAKE_BUILD_TYPE=Release -DBUILD_CARLA_UNREAL=ON -DCARLA_UNREAL_ENGINE_PATH=$CARLA_UNREAL_ENGINE_PATH
> 
> cmake --build Build --target launch
> ```

I tried this command and it seems to be useful. But there was an error when running UE5Editor. And I ensure that the GPU driver and Vulkan have been installed, and information can be queried using nvidia-smi and vulkaninfo
![a](https://github.com/user-attachments/assets/d894a9dd-7b64-48ee-adeb-b54066402f49)

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

What Patrick said should indeed work. Could you share the output of both nvidia-smi and vulkaninfo? Btw, please attach logs using text files instead of images if possible.

Marcel

**Comment by PatrickPromitzer** [comment]
Do you have an CPU with graphics card?

Maybe your computer is using the CPU instead of the Nvidia graphic card (a guess)
```sudo nvidia-settings```
![image](https://github.com/user-attachments/assets/69ff7c71-d75a-489c-9d2f-4bd5c2b39d4d)
