### ISSUE TITLE
make: *** [Util/BuildTools/Linux.mk:137: setup] Error 1

### ISSUE THREAD

**Issue by SirMichcik** [carla-simulator/carla#8119]
Hi! I have encountered an error while trying to make launch in carla root folder, here are my specs:

Ubuntu 20.04
Carla 0.9.13
UnrealEngine_4.26

I was using linux build guide, fixed some errors on the way and now im stuck on this:

cstring:77:9: error: no member named 'strcmp' in the global namespace; did you mean 'strchr'?
using ::strcmp;
cstring:76:9: error: no member named 'memcmp' in the global namespace; did you mean 'memchr'?
using ::memcmp;
cstring:74:9: error: no member named 'strcat' in the global namespace; did you mean 'strchr'?
using ::strcat;
cstring:73:9: error: no member named 'strncpy' in the global namespace
using ::strncpy;

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ninja: build stopped: subcommand failed.
make: *** [Util/BuildTools/Linux.mk:137: setup] Error 1

There were of course 20 error messages, all about namespaces like this, i think it has something to do with compiler even though I am using clang 8 as requested.

**Comment by MarcelPiNacy-CVC** [comment]
Hi,

If you write `clang --version` on a terminal what do you get?

Marcel

**Comment by SirMichcik** [comment]
Hi, thanks for replying, to be honest i just gave up and reinstalled whole OS and installed the setup from scratch. It helped, but there is another issue:

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Failed to find XercesC (missing: XercesC_VERSION)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindXercesC.cmake:99 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:71 (find_package)


-- Configuring incomplete, errors occurred!
See also "/media/michal/7eeeb763-63f0-425a-88b3-041b93352d7a/carla/Build/libosm2dr-build/CMakeFiles/CMakeOutput.log".
make: *** [Util/BuildTools/Linux.mk:152: osm2odr] Error 1

I will be making another thread for it in a second. Thanks.
