### ISSUE TITLE
Adding a Person in a Wheelchair or with a Stroller in Carla

### ISSUE THREAD

**Issue by Sondosmohamed1** [carla-simulator/carla#8143]
Can anyone help me figure out how to add a person in a wheelchair or with a stroller on the street? Is it possible to add this type of pedestrian in Carla? Thank you!

**Comment by PabloVD** [comment]
We have already added pedestrians blueprints in wheelchair in the UE4 version of CARLA.Would that work for you or you want to add your own asset?

**Comment by Sondosmohamed1** [comment]
Thank you very much! I noticed that you’ve already added pedestrian blueprints in wheelchairs . This might work well for my needs, thank you

**Comment by Sondosmohamed1** [comment]
Thank you very much! I noticed that you’ve already added pedestrian blueprints in wheelchairs in the UE4 version of CARLA. This might work well for my needs, thank you
