### ISSUE TITLE
Making copy of blueprint

### ISSUE THREAD

**Issue by andrster** [carla-simulator/carla#816]
Is it possible to make a copy of a blueprint in carla (ie vehicleSpawner) so I can keep the original one and also have a more customized version. Linux environment and Carla .84

**Comment by nsubiron** [comment]
Hi @andrster,

Well, Ctrl+C and Ctrl+V should work in editor, then you can rename it as you want. Just make sure you have registered in the Game Mode the blueprint you want to use as Vehicle Spawner.
![image](https://user-images.githubusercontent.com/4332953/46254402-3e562300-c48f-11e8-8540-76deda294510.png)

You can modify the Game Mode to use your own classes.
