### ISSUE TITLE
Safe to delete Intermediate folder?

### ISSUE THREAD

**Issue by ShahzebTUMBachelor** [carla-simulator/carla#8170]
CARLA version: 0.9.15
Platform/OS: Ubuntu 22.04

Hey, I was running make package to get a new distribution with a new map I created in RoadRunner. Unfortunately, I ran out of memory. Is it safe to delete the content from the "Intermediate" folder in Carla under carla/Unreal/CarlaUE4/Intermediate?

**Comment by MarcelPiNacy-CVC** [comment]
Yes, but you could interfere with the package build process. How much memory do you have available?
