### ISSUE TITLE
Is importing of .xodr map files (already) possible in CARLA-UE5?

### ISSUE THREAD

**Issue by XLR8-VISION** [carla-simulator/carla#8175]
Hello everyone,

**CARLA version:**
CARLA-UE5 0.10.0

**Platform/OS:**
Ubuntu 22.04

**Problem you have experienced:** 
'make import' for importing .fbx and .xodr maps is not working (yet). The makefile says this function is disabled.

**What you expected to happen:** 
Import of .osm maps (or .fbx and .xodr files) into CARLA 

**Steps to reproduce:** 
See: https://carla.readthedocs.io/en/latest/tuto_content_authoring_maps/#importing-your-road-network-into-carla

**Other information (documentation you consulted, workarounds you tried):** 
Ingesting .osm., .fbx and .xodr in CARLA like described in following offical doc is not working as well in CARLA-UE5 (See: https://github.com/carla-simulator/carla/blob/master/Docs/tuto_G_openstreetmap.md#ingest-into-carla )

**My question:** 
Is there another possibility to get .xodr files as map into CARLA / Unreal Editor 5 ?

**Comment by Blyron** [comment]
No, is not possible atm

**Comment by Blyron** [comment]
Not right now.

**Comment by bututou777** [comment]
> 现在不行。
Is there a way now?
