### ISSUE TITLE
~/CARLA_0.9.15$ . /CarlaUE4.sh Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by DongLING** [carla-simulator/carla#8198]

**Comment by PatrickPromitzer** [comment]
Hi,
The "Illegal instruction (core dumped)" text is telling nothing, because it is a default text for errors.

You can check if the port 2000-2002 is free, and if the file permissions are set right.

For more help, we need to know what you did and/or try to do.

**Comment by minhaj6** [comment]
This is an excellent example of how you should not ask for help on the internet.
