### ISSUE TITLE
Carla windows zip file installed

### ISSUE THREAD

**Issue by tafusen** [carla-simulator/carla#8228]
Hi, I get this error while I run
 **world = client.get_world()**
I just downloaded windows zip file. My carla version is 0.9.15

[I 18:42:00.027 NotebookApp] Kernel started: c8b8aad2-fca0-40f3-89f4-a009d64ca83d, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: cc47d9ab-9d5e-4bb1-8c08-82f59357588e
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API
WARNING: Client API version     = 0.9.13
WARNING: Simulator API version  = 0.9.15
Assertion failed: px != 0, file C:\workspace\carla\Build\boost-1.72.0-install\include\boost/smart_ptr/shared_ptr.hpp, line 728

**Comment by PatrickPromitzer** [comment]
Hi,
try using the right Carla package version.

```
path/to/python.exe -m pip install carla==0.9.15
```
