### ISSUE TITLE
4.26.2-0+++UE4+Release-4.26 522 0 Disabling core dumps. Exiting abnormally (error code: 1)

### ISSUE THREAD

**Issue by Eng-Sdl** [carla-simulator/carla#8244]
showing this error while trying to open the exported build package from Carla Unreal engine 4. Plz help!

**Comment by MarcelPiNacy-CVC** [comment]
Hi, can you provide the log?

**Comment by lxd1010** [comment]
sh ./simbev.sh
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
/home/lixudong/carla_installation/carla/CarlaUE4.sh -RenderOffScreen -nosound --carla-rpc-port=31799 -quality-level=Epic
Connecting to server on port 31799...
Connected to server.
Loading Town01...
Traceback (most recent call last):
  File "simbev.py", line 220, in main
    core.load_map('Town01')
  File "/home/lixudong/carla_installation/SimBEV-1.0.0/SimBEV-1.0.0/simbev/carla_core.py", line 198, in load_map
    self.client.load_world(map_name)
RuntimeError: time-out of 80000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:31799

Killing all servers...
Done.
运行sh ./simbev.sh出现错误。请求帮忙解疑！
