### ISSUE TITLE
How can I change the limit of the number of the Static meshes ?

### ISSUE THREAD

**Issue by quanheng123** [carla-simulator/carla#825]
Hello,all.
 I've seen in CityMapMeshTag.cpp that there is a maximal limit (255) for the number of meshes in Carla meshes, How can change the limit?

**Comment by marcgpuig** [comment]
This is the maximum number of semantic segmentation **different** labels. You can't increase this number without modifying the engine, and that is exactly what we are trying to avoid.

**Comment by marcgpuig** [comment]
Oops! I totally misunderstood your question, sorry about that.
Anyway, this is just how we made the road generator in the past.
You can add all the meshes you want in Unreal!

**Comment by quanheng123** [comment]
Hi,  @marcgpuig . Thanks for the answers, but now I‘m confused, can I add meshes without limit or not?  
Here is what I want: create a mesh and add it in Citymapgenerator and in citymeshtag code file and give every mesh a lane information in roadmap code file and rebuild CARLA, Is there a limit for these meshes in CARLA?

**Comment by quanheng123** [comment]
I mean :is there a limit for the number of the different types of the meshes in CARLA?

**Comment by nsubiron** [comment]
@quanheng123 What are you trying to accomplish? Although this class is called CityMapGenerator can only generate roads (this is some legacy class that was supposed to do more but was never implemented). The tags defined there are used to define the meshes that are going to be tagged as different lanes and so. This is used for generating the 2D road map that vehicles use to drive in autopilot. But this some sort of workaround solution for solving a very specific problem, if you change the number of meshes chances are that the autopilot won't work well. The 255 limit is a limitation of UE4 enums, so no, with that enum you cannot add more than 255 items. But why do you want to have more than 255 road pieces?

As a note, I must add that this system will be discarded in the coming months. We are looking for more scalable solutions and road definitions based on OpenDrive.

**Comment by quanheng123** [comment]
Thanks for the answers, @nsubiron .
Sorry it was my mistake to say the wrong thing. Yes, what I want to have is to add more than 255 road pieces in CityMapmeshTag.cpp , not citymapgenerator thing . And yes, I’ve just found out the enum in UE4,if you want to expose them to blueprint the unit8 is your only choice. 
Now What I want to is to generate the real road from reality, as you know the the road from the real world is much complicated than the default road in CARLA, so the one road piece can be different from another, so there will be far more 255 type of Road piece once generated, and also After generating real road, I would like to try to added lane information (the autopilot thing ) in them. I‘ve made some example incline road and add it to Carla and rebuild it ,so far success, the maxi limit is what I want to break.
Speak of the new version for the next month , is there a big changing in Mapgen for next version？will the whole Carla map generation will be completely redesigned? If it is convenient, if you give me a short description about it , that will be very nice.

**Comment by quanheng123** [comment]
Thanks. @nsubiron 
I've already add my new Tags in URoadMap in RoadMap.cpp to generating like this.
![screenshot from 2018-09-27 23-59-52](https://user-images.githubusercontent.com/42386922/46421764-20a8e800-c733-11e8-8a10-f91fbdb24ac6.png)
Is that what you mention to ?
So general speaking there is no way to change the maximal limit directly?
But thanks anyway.

**Comment by nsubiron** [comment]
That looks good :)

Well, you could just drop support for UE4 in the enum. I don't think it's really used in the editor except for visualization. Try removing the U-macros, (`UENUM`, `UMETA`, `UPROPERTY`, etc) and try compiling and removing the ones that fail.

**Comment by quanheng123** [comment]
Thanks, that helps, appreciated. : )
