### ISSUE TITLE
example.py timesout

### ISSUE THREAD

**Issue by adarsh9975** [carla-simulator/carla#826]
Platform: Windows 10
Carla : 0.9.0

The example.py times out. with following message:

![image](https://user-images.githubusercontent.com/31591230/46340051-f92e1e80-c651-11e8-8a67-823de9a57cdd.png)

I have already done following:
1) build and install python API using setup.py
 
I have already tried following:
1) Allowing ports 2000 and 2001 in firewall settings
2) Turning on/off the firewall
3) Increasing the timeout duration to upto 10 seconds

**Comment by iFuSiiOnzZ** [comment]
Just to be sure, do you have Carla running, `make launch`? Or maybe the ports are used by another program, try to change the port  `-carla-port=xxx`, the executable file can be found in `Unreal\CarlaUE4\Binaries\Win64\`

**Comment by adarsh9975** [comment]
changing the port worked. Thanks @iFuSiiOnzZ . Can't wait to get my hands dirty :)
