### ISSUE TITLE
Carla ue5-dev / Missing doc? / How to start the server ?

### ISSUE THREAD

**Issue by HO4X** [carla-simulator/carla#8261]
Hey there, 

i just wanted to checkout the current state of the carla simulator with the UE5 engine. 
Somehow i was wondering how to start the server?

I would like to contribute on the documentation, so maybe someone can enlighten me..

**Comment by PatrickPromitzer** [comment]
Hi,
this is the only documentation I have currently.

https://docs.google.com/document/d/1aWcoJr-9z_wE6S442UhzC32jUGmN1o42REE7C-4aGYA/edit?tab=t.0#heading=h.5piein3604b7
