### ISSUE TITLE
Calculate Energy efficiency/ fuel consumption

### ISSUE THREAD

**Issue by ToastedAvenger** [carla-simulator/carla#8307]
Carla version: 0.9.15
Ros 2 Humble
Platform: windows 10/ ubuntu 22.04

I am using carla for my project, i want to see how fuel can i save by implementing different algorithms. I have found some papers related to this topic but they don't mention the methodolgy. I would be great if i can get this data eiter from carla or using  ros bridge.

This issue was also posted in the past
[https://github.com/carla-simulator/carla/issues/1267](https://github.com/carla-simulator/carla/issues/1267)

**Comment by Blyron** [comment]
Currently we have not methods no do this. We are open to contributions if someone implements it.
