### ISSUE TITLE
Sample Rate - Data Training

### ISSUE THREAD

**Issue by jptavares1606** [carla-simulator/carla#831]
Hello everyone, 

Could you please share the sample rate of the training data provided [here](https://github.com/carla-simulator/imitation-learning)?

I am trying to pre-train a ML algorithm based on this dataset and I didn't find this information anywhere. 
Thanks!

**Comment by jptavares1606** [comment]
Anyone?

**Comment by felipecode** [comment]
Hey ! It is 10 fps !
