### ISSUE TITLE
RGB Noise under Rain and Fog Conditions in CARLA 0.9.10

### ISSUE THREAD

**Issue by TianYifan-Vincent** [carla-simulator/carla#8324]
When simulating rain and fog conditions in CARLA 0.9.10, noticeable noise and pixelation appear in the background environment, particularly on distant buildings and landscapes, as shown in the attached figures. This affects the clarity of the images, making it challenging to achieve high-quality visuals in these weather conditions.

I’ve attempted to mitigate the issue by adjusting parameters, such as increasing ScreenPercentage, disabling motion blur, and disabling depth of field, but unfortunately, these adjustments haven’t fully resolved the problem.

Anyone's guidance would be greatly appreciated. Thank you very much for your time and assistance!
![image](https://github.com/user-attachments/assets/0356dccf-b1cf-4dd7-a0cc-2440f3af07c9)
![image](https://github.com/user-attachments/assets/6f1180f2-b6de-458c-8837-9fa9f2af9e78)

**Comment by PabloVD** [comment]
We do not officially support CARLA versions below 0.9.12 anymore, please try with versions from 0.9.12 onwards and let us know if the problem persist there.
