### ISSUE TITLE
ValueError: role_name: colors must have 3 channels (R,G,B) when running generate_traffic.py

### ISSUE THREAD

**Issue by prateeknagar146** [carla-simulator/carla#8328]
CARLA version: 0.9.15
Platform/OS: Windows10
Problem you have experienced: After successful installation I can only run dynamic_weather.py. If I want to run any other example python script like manual_control.py or generate_traffic.py I will get the following ValueError: 

![image](https://github.com/user-attachments/assets/15ae7595-1219-498e-a36f-beeac8b223d6)

I still cannot figure out where the "ERROR: invalid color autopilot" comes from? 
Has someone experienced the same error and how to resolve this? 

Kind regards! 

![ValueError_generate_traffic_py](https://github.com/user-attachments/assets/30acd00c-8183-4c83-bbaa-2e211a00c61d)

**Comment by Blyron** [comment]
Hey folks,
Commented a solution here: https://github.com/carla-simulator/carla/issues/8035#issuecomment-2320778135 
Closing this as duplicated issue
