### ISSUE TITLE
Build on Linux installation problem

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/carla#833]
Hi,
Thanks for an amazing car simulator.

In Ubunto 18:

1) I am able to run `./CarlaUE4.sh /Game/Maps/Town0X` and see the car navigates...

2) However, I have trouble with PythonClient. When I run `python manual_control.py` in a terminal and `./CarlaUE4.sh /Game/Maps/Town01 -carla-server -benchmark -fps=15 -windowed -ResX=800 -ResY=600 -carla-world-port=PORT` in another terminal, I see the car cannot navigate at all (assuming that I do not have any firewall). It floats between the earth and sky without movement...

3) I am not able to run `python example.py` by getting `ImportError: No module named carla`. I am a bit confused here as I followed instruction to build on Linux and also the quick start video.

Do I miss something here? Any thought for this appreciated.

**Comment by nsubiron** [comment]
I think you are using the 0.9.0 client with a 0.8.x simulator https://github.com/carla-simulator/carla/issues/805#issuecomment-424625783.
