### ISSUE TITLE
 fatal error: tf2_eigen/tf2_eigen.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by leidi1989** [carla-simulator/carla#8342]
In file included from /mnt/ubuntu_data/self/self_tool/ros-bridge/pcl_recorder/src/mainROS2.cpp:7:
/mnt/ubuntu_data/self/self_tool/ros-bridge/pcl_recorder/include/PclRecorderROS2.h:13:10: fatal error: tf2_eigen/tf2_eigen.h: 没有那个文件或目录
   13 | #include <tf2_eigen/tf2_eigen.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/pcl_recorder_node.dir/build.make:90：CMakeFiles/pcl_recorder_node.dir/src/mainROS2.cpp.o] 错误 1
gmake[2]: *** 正在等待未完成的任务....
In file included from /mnt/ubuntu_data/self/self_tool/ros-bridge/pcl_recorder/src/PclRecorderROS2.cpp:13:
/mnt/ubuntu_data/self/self_tool/ros-bridge/pcl_recorder/include/PclRecorderROS2.h:13:10: fatal error: tf2_eigen/tf2_eigen.h: 没有那个文件或目录
   13 | #include <tf2_eigen/tf2_eigen.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/pcl_recorder_node.dir/build.make:76：CMakeFiles/pcl_recorder_node.dir/src/PclRecorderROS2.cpp.o] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:137：CMakeFiles/pcl_recorder_node.dir/all] 错误 2
gmake: *** [Makefile:146：all] 错误 2

how to solve the problem?

**Comment by wjx052333** [comment]
how to solve this problem?
I have the same issue here.
