### ISSUE TITLE
About Carla UE5 docs

### ISSUE THREAD

**Issue by uuauto2024** [carla-simulator/carla#8361]
Hi there,

I am currently using Carla-UE5.5 with ROS2 for simulating autonomous driving. I am facing some confusion regarding the ROS2 interface. Could you kindly assist me in locating the API explanations or direct me to the specific documentation for Carla-UE5.5?

Thank you.

**Comment by PabloVD** [comment]
Hi, [here](https://carla-ue5.readthedocs.io/en/latest/) is the Carla UE5 documentation, which differs from the UE4 version docs. Note that this is still a work in progress and some aspects may still be missing, incomplete or inaccurate.

**Comment by uuauto2024** [comment]
thanks a lot!
