### ISSUE TITLE
UE5.5 Bugs with Semantic LIDAR sensor！

### ISSUE THREAD

**Issue by uuauto2024** [carla-simulator/carla#8367]
The semantic LiDAR sensor in CARLA UE5 has a bug where it only outputs point cloud points of category 0, as shown in this image. Please tell me how to solve this problem. Thank you!
![image](https://github.com/user-attachments/assets/f0a66d35-8973-4546-bf65-da962ebbc78e)

where this image is generate by open3d_lidar.py (examples)

**Comment by PabloVD** [comment]
Thanks for sharing, we are aware of that problem and we are working in fixing it, hopefully we will get a solution soon.

**Comment by Blyron** [comment]
https://github.com/carla-simulator/carla/discussions/8323 As you can see in this discussion, there is a spreedsheet with supported features and ones with issues, We are having issues solving that. So please, wait. We are doing our best. 

Remember we are always open to contributions. Closing this issue as it is known issue
