### ISSUE TITLE
Missing Setup.bat file in GitHub repo

### ISSUE THREAD

**Issue by JudgeKP** [carla-simulator/carla#8370]
I was trying to build Carla with UE5 on windows following the docs at https://carla.readthedocs.io/en/latest/build_windows_ue5/
The **Setup.bat** command was asked to execute ,but unfortunately I did not found it in the repo and hence can't proceed further, without exact specifications. Kindly add the required file.

**Comment by ronyshaji** [comment]
@JudgeKP You can use [CarlaSetup.bat](https://github.com/carla-simulator/carla/blob/ue5-dev/CarlaSetup.bat) instead of Setup.bat. I think they will update the README in the future.
