### ISSUE TITLE
Make Launch Error

### ISSUE THREAD

**Issue by shahbazsiddique69** [carla-simulator/carla#8390]
Parameters.cpp
D:\carla\LibCarla\source\carla\Buffer.h(13,10): error C1083: Cannot open include file: 'boost/asio/buffer.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/sensor/s11n/SensorHeaderSerializer.cpp')

  SimpleWaypoint.cpp
D:\carla\LibCarla\source\carla\Time.h(11,10): error C1083: Cannot open include file: 'boost/date_time/posix_time/posix_time_types.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/multigpu/primaryCommands.cpp')

  SimulationState.cpp
D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/LocalizationUtils.cpp')

  TrackTraffic.cpp
D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp')

D:\carla\LibCarla\source\carla\Buffer.h(13,10): error C1083: Cannot open include file: 'boost/asio/buffer.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/multigpu/router.cpp')

  TrafficLightStage.cpp
  TrafficManager.cpp
D:\carla\LibCarla\source\carla\Buffer.h(13,10): error C1083: Cannot open include file: 'boost/asio/buffer.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/multigpu/secondary.cpp')

  TrafficManagerLocal.cpp
D:\carla\LibCarla\source\carla\Buffer.h(13,10): error C1083: Cannot open include file: 'boost/asio/buffer.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/multigpu/secondaryCommands.cpp')

  TrafficManagerRemote.cpp
D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/CachedSimpleWaypoint.cpp')

  VehicleLightStage.cpp
D:\carla\LibCarla\source\carla\Buffer.h(13,10): error C1083: Cannot open include file: 'boost/asio/buffer.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/CollisionStage.cpp')

  ROS2.cpp
D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/LocalizationStage.cpp')

D:\carla\LibCarla\source\carla\Buffer.h(13,10): error C1083: Cannot open include file: 'boost/asio/buffer.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/SimpleWaypoint.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\geometry.hpp(17,10): error C1083: Cannot open include file: 'boost/geometry/geometry.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/InMemoryMap.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/SimulationState.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/Parameters.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/TrafficLightStage.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/TrackTraffic.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/TrafficManagerRemote.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/VehicleLightStage.cpp')

D:\carla\LibCarla\source\carla\Buffer.h(13,10): error C1083: Cannot open include file: 'boost/asio/buffer.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/ros2/ROS2.cpp')

D:\carla\Build\boost-1.80.0-install\include\boost\enable_shared_from_this.hpp(16,10): error C1083: Cannot open include file: 'boost/smart_ptr/enable_shared_from_this.hpp': No such file or directory [D:\carla\Build\libcarla-visualstudio\LibCarla\cmake\client\carla_client_debug.vcxproj]
  (compiling source file '../../../../../LibCarla/source/carla/trafficmanager/TrafficManager.cpp')

-[BuildLibCarla]: LibCarla server has been successfully installed in "D:\carla\Unreal\CarlaUE4\Plugins\Carla\CarlaDependencies\"!
-[BuildLibCarla]: LibCarla client has been successfully installed in "D:\carla\PythonAPI\carla\dependencies\"!
-[BuildOSM2ODR]: [Batch params]: --generator "Visual Studio 17 2022" --build --all
CMake Warning (dev) at CMakeLists.txt:33 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
CMake Deprecation Warning at CMakeLists.txt:35 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- CMAKE_BINARY_DIR: D:/carla/Build/osm2odr-visualstudio
-- CMAKE_SOURCE_DIR: D:/carla/Build/osm2odr-source
--
-- Platform:
--     Host: Windows-10.0.19045 AMD64
--     Target: Windows-10.0.19045 AMD64
--     CMake: 3.31.0
--     CMake generator: Visual Studio 17 2022
--     CMake build tool: C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe
--     Compiler: MSVC 19.42.34433.0
--
-- Found Proj: D:/carla/Build/proj-install/lib/proj.lib
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Enabled features: Windows-10.0.19045 AMD64 MSVC 19.42.34433.0 Release Proj
-- Configuring done (0.3s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIBRARY
    linked by target "osm2odr" in directory D:/carla/Build/osm2odr-source/src

-- Generating done (0.2s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
MSBuild version 17.12.6+db5f6012c for .NET Framework

  OutputDevice_File.cpp
D:\carla\Build\osm2odr-source\src\utils\iodevices\OutputDevice_File.cpp(43,41): error C2027: use of undefined type 'std::basic_ofstream<char,std::char_traits<char>>' [D:\carla\Build\osm2odr-visualstudio\src\osm2odr.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\iosfwd(207,7):
      see declaration of 'std::basic_ofstream<char,std::char_traits<char>>'

D:\carla\Build\osm2odr-source\src\utils\iodevices\OutputDevice_File.cpp(66,37): error C2027: use of undefined type 'std::basic_ofstream<char,std::char_traits<char>>' [D:\carla\Build\osm2odr-visualstudio\src\osm2odr.vcxproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\iosfwd(207,7):
      see declaration of 'std::basic_ofstream<char,std::char_traits<char>>'

The system cannot find the path specified.
The system cannot find the path specified.
-[BuildOSM2ODR]: OSM2ODR has been successfully installed in "D:\carla\PythonAPI\carla\dependencies\"
-[BuildCarlaUE4]: [Batch params]: --build --all
--build
--all
ECHO is off.
-[BuildCarlaUE4]: Building Unreal Editor...
Using 'git status' to determine working set for adaptive non-unity build (D:\UnrealEngine).
Waiting for 'git status' command to complete
Building CarlaUE4Editor...
Using Visual Studio 2019 14.42.34433 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
[Upgrade]
[Upgrade] Using backward-compatible build settings. The latest version of UE4 sets the following values by default, which may require code changes:
[Upgrade]     bLegacyPublicIncludePaths = false                 => Omits subfolders from public include paths to reduce compiler command line length. (Previously: true).
[Upgrade]     ShadowVariableWarningLevel = WarningLevel.Error   => Treats shadowed variable warnings as errors. (Previously: WarningLevel.Warning).
[Upgrade]     PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs   => Set in build.cs files to enables IWYU-style PCH model. See https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/IWYU/index.html. (Previously: PCHUsageMode.UseSharedPCHs).
[Upgrade] Suppress this message by setting 'DefaultBuildSettings = BuildSettingsVersion.V2;' in CarlaUE4Editor.Target.cs, and explicitly overriding settings that differ from the new defaults.
[Upgrade]
Building 25 actions with 12 processes...
  [1/25] Module.Carla.3_of_4.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Sensor/AsyncDataStream.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [2/25] Module.Carla.1_of_4.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Actor/ActorAttribute.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [3/25] Module.CarlaTools.cpp
  D:/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/CarlaTools.cpp(24): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [4/25] Module.Carla.gen.2_of_8.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Actor/ActorAttribute.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [5/25] Module.Carla.gen.7_of_8.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/OpenDrive/OpenDriveMap.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [6/25] Module.Carla.gen.1_of_8.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Util/ActorAttacher.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [7/25] Module.Carla.gen.5_of_8.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Settings/QualityLevelUE.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [8/25] Module.Carla.gen.4_of_8.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/OpenDrive/OpenDriveMap.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [9/25] Module.Carla.gen.8_of_8.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Walker/WalkerController.h(16): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [10/25] Module.Carla.4_of_4.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Game/CarlaHUD.h(63): warning C4996: 'UWheeledVehicleMovementComponent': PhysX is deprecated. Use the UChaosWheeledVehicleMovementComponent fron the ChaosVehiclePhysics Plugin. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Game/CarlaHUD.h(64): warning C4996: 'UWheeledVehicleMovementComponent': PhysX is deprecated. Use the UChaosWheeledVehicleMovementComponent fron the ChaosVehiclePhysics Plugin. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Actor/ActorAttribute.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [11/25] Module.Carla.gen.6_of_8.cpp
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(603): warning C4005: 'TEXT': macro redefinition
  D:\UnrealEngine\Engine\Source\Runtime\Core\Public\HAL/Platform.h(1082): note: see previous definition of 'TEXT'
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Actor/ActorAttribute.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [12/25] Module.Carla.2_of_4.cpp
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(603): warning C4005: 'TEXT': macro redefinition
  D:\UnrealEngine\Engine\Source\Runtime\Core\Public\HAL/Platform.h(1082): note: see previous definition of 'TEXT'
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/Actor/ActorAttribute.h(9): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [13/25] Module.Carla.gen.3_of_8.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla\Vehicle\WheeledVehicleMovementComponentNW.h(120): warning C4996: 'UWheeledVehicleMovementComponent': PhysX is deprecated. Use the UChaosWheeledVehicleMovementComponent fron the ChaosVehiclePhysics Plugin. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla\Vehicle\WheeledVehicleMovementComponentNW.h(148): warning C4996: 'UVehicleWheel': PhysX is deprecated. Use the UChaosVehicleWheel from the ChaosVehiclePhysics Plugin. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla\Vehicle\CarlaWheeledVehicle.h(39): fatal error C1083: Cannot open include file: 'carla/rpc/VehicleFailureState.h': No such file or directory
  [14/25] Module.CarlaTools.gen.2_of_2.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\CarlaTools\Source\CarlaTools/Public/MapPreviewUserWidget.h(9): fatal error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory
  [15/25] Module.CarlaTools.gen.1_of_2.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\CarlaTools\Source\CarlaTools/Public/Commandlet/GenerateTileCommandlet.h(12): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
  [16/25] Module.StreetMapRuntime.cpp
  D:\carla\Unreal\CarlaUE4\Plugins\Carla\Source\Carla/OpenDrive/OpenDriveGenerator.h(12): fatal error C1083: Cannot open include file: 'compiler/disable-ue4-macros.h': No such file or directory
make: *** [CarlaUE4Editor] Error 6
![error](https://github.com/user-attachments/assets/661af4b5-7aa7-4d6e-9e86-bc59e209666f)
****

**Comment by shahbazsiddique69** [comment]
Most probably I am mainly facing error with the boost installed. I have download the boost-1.80.0-install file and unzipped it and pasted in the D:\carla\Build\boost-1.80.0-install. Because there was only boost-1.80.0-source file. this solved my boost installation error which was specifically "...skipped 63 targets...
...updated 16474 targets...

    -[install_boost]: [B2 ERROR] An error ocurred while installing using "b2.exe".
    -[install_boost]: Exiting with error..."
    but i think my approach didn't end well and have mistakes. please rectify me with solutions if you have.

**Comment by lakhanqurban** [comment]
I am facing the same issue please update if you have found any solution.

**Comment by lakhanqurban** [comment]
I had to start from scratch by cloning both repositories (Unreal and Carla) again and you are right it only works with the visual studio 2019.

**Comment by shahbazsiddique69** [comment]
Glad it helped
