### ISSUE TITLE
Enable benchmark for 0.9.x

### ISSUE THREAD

**Issue by kloud1989** [carla-simulator/carla#846]
Hi,

In 0.9.0 release, the benchmark is not enabled. When I tried to enable imitation-learning, I found that metrics of the player is not available. Is it possible to enable benchmark in the 0.9.x releases?

Thanks

**Comment by felipecode** [comment]
We will work on that. However it is possible that the results wouldn't be exactly the same.
Watch our new driving benchmarks repository. https://github.com/carla-simulator/driving-benchmarks
