### ISSUE TITLE
Vehicle start position - relation to other non-player agents

### ISSUE THREAD

**Issue by mhusseinsh** [carla-simulator/carla#863]
I have a question concerning the start position of a the player
Is there a rule or something that when the vehicle (agent) is spawned, the other non-player agent have to be within a certain distance from the agent ?
As an example, a vehicle cannot start where there is another vehicle directly in front of it ? can the vehicle be spawned in a traffic jam for example ?

I tried to run multiple episodes, and for every episode, the vehicle always start, and I can never find in front of it directly a non-player agent, there is always a distance (maybe this is happening to me randomly)
But anyways, my question would go in the direction of, is there a way to somehow specify the number of vehicles/pedestrians around me when I start the episode ?

I know they are spawned based on a seed or randomly, but if there is a way, this would be really great

Any clarification about this matter ?

**Comment by Romanenko-Serhii** [comment]
You can create this scenario in UnrealEngine projects, like a new map. 

They have not spawned randomly. There are N points for spawn, and in this list randomly chosen the place. So, you can delete all spawned point in projects and create your scenario.

For more about spawned and moving car after it you can read https://github.com/carla-simulator/carla/issues/504
