### ISSUE TITLE
Carla WeatherId

### ISSUE THREAD

**Issue by dhernandez0** [carla-simulator/carla#865]
I'm using carla 0.8.2 (stable version), I modify manual_control.py (line 81=5, MidRainyNoon), and it is not raining in the simulator, see attached image. 
![150](https://user-images.githubusercontent.com/9977702/46824051-c674dc00-cd5d-11e8-9df1-5977f79b9402.png)

**Comment by marcgpuig** [comment]
Hi @dhernandez0! how are you? :)
So you are doing:
```py
WeatherId=5,
```
and is not raining, right?
Did you changed anythig from the client? Make sure you are calling `scene = self.client.load_settings(self._carla_settings)` inside `_on_new_episode()`.
Also, did you deleted `self._carla_settings.randomize_weather()`?

Cheers!

**Comment by dhernandez0** [comment]
according to https://carla.readthedocs.io/en/latest/carla_settings/#weather-presets

5 is MidRainyNoon, then rainy is not rain? but likely to rain?

Oh! I didn't remove "self._carla_settings.randomize_weather()" that could be the problem, I'll check that

**Comment by marcgpuig** [comment]
@dhernandez0 Acording to @TheNihilisticRobot, "Rainy" is a bit of rain.

**Comment by dhernandez0** [comment]
It works now.was because of the "self._carla_settings.randomize_weather()" line. Thanks 👍
