### ISSUE TITLE
how can I get pixel depth?

### ISSUE THREAD

**Issue by yangzuyuanhao** [carla-simulator/carla#868]
Hi,

A quick question about pixel depth:

What I want to do is that, I projected some points from world coordinate to pixel coordinate and get their
corresponding depth value, and I want to compare their depth with their nearby pixels. 
So, How can I know the nearby pixels' depth? I saw a function "depth_to_array()", does it work? thanks

**Comment by marcgpuig** [comment]
Hi @yangzuyuanhao. Sorry for the late response.
As the [documentation](https://carla.readthedocs.io/en/stable/cameras_and_sensors/#camera-depth-map) says, we have depth per pixel. You can find `depth_to_array()` function here: 
https://github.com/carla-simulator/carla/blob/13b9723c4681c8a456ce95e98224d780f76be5b4/PythonClient/carla/image_converter.py#L81-L91
And yes, it works :wink:
