### ISSUE TITLE
Vehicle speed in 0.9.0 version

### ISSUE THREAD

**Issue by yaxinluan** [carla-simulator/carla#869]
Hello,

I'm using CARLA 0.9 since it has the ability to control multiple vehicles. But this version only has location feedback for the actors (let me know if I'm wrong about this). So I'm trying to get the speed of the vehicle by doing a derivative of the location wrt to time. However, how do I know the time step in between each location feedback I get - is it just how long I wait until I call get_location() again? 
Another question: when will the measurements  feature be available in 0.9.0 so that I can get velocity and acceleration feedback directly like in version 0.8? :)

**Comment by jeffersonfs** [comment]
I have the same question about CARLA 0.9.

**Comment by yaxinluan** [comment]
That's great! Thanks @nsubiron ! Would the measurements include time step as well?

**Comment by guersoy** [comment]
Hi! When can we expect the 0.9.1 release?

**Comment by nsubiron** [comment]
Hi @guersoy,

Release 0.9.1 was expected for last week but we are having some difficulties :sweat:
This is the work-in-progress API that will be available on 0.9.1 --> [python_api.md (branch `com`)](https://github.com/carla-simulator/carla/blob/com/Docs/python_api.md). Most of the measurements are already there, plus a few more extra we didn't have. We are missing the lane/road detection most significantly. I'll open a pull-request with all these changes very soon.

The ROS bridge haven't been ported yet to the new API. This will happen after 0.9.1.
