### ISSUE TITLE
Adding point to spline in SplineMeshRepeater

### ISSUE THREAD

**Issue by curantil** [carla-simulator/carla#87]
I'm trying to use the SplineMeshRepeater, but I cannot add points to the spline. 

I tried right clicking and selecting "Add point" when a segment was selected and also selecting an existing point and duplicating it, but in both cases, it seems to create a point that is not connected to the spline or do nothing at all. The disconnect point also disappears when selecting anything else other than the point.

**Comment by nsubiron** [comment]
Hi @curantil,
You can drag and drop spline points while holding "alt" key

![gif](https://user-images.githubusercontent.com/4332953/33991240-2b79b8e6-e0ce-11e7-800d-270ec9089e9c.gif)

**Comment by curantil** [comment]
Thanks! That works indeed.
