### ISSUE TITLE
RGB images are saved to disk as white images on Mac

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#884]
This seems to be an issue of the alpha channel. See thread https://github.com/carla-simulator/carla/issues/851#issuecomment-430922105.

Ideally we want to find a method to ignore the alpha channel while saving the images to disk that works on Windows, Linux, and Mac and doesn't affect performance significantly (not modifying the alpha channel of the buffer if possible).

**Workaround**
```python
def save_to_disk(image):
    """Save this image to disk (requires PIL installed)."""
    #image.convert(ColorConverter.CityScapesPalette)
    #print image.raw_data
    array = np.frombuffer(image.raw_data, dtype=np.dtype("uint8"))
    array = np.reshape(array, (image.height, image.width, 4))
    array = array[:, :, :3]
    array = array[:, :, ::-1]
    scipy.misc.imsave('_out/{}_rgb.png'.format(image.frame_number), array)
```

**Comment by micmarty** [comment]
`imsave` is deprecated, hence `scipy` documentation recommends using `imageio.imwrite` instead. 
This is extremely slow solution. Tried to buffer 600 images in memory and dump at once, but this can take a few minutes even on SSD drive. **Important fact is that I'm having this issue on Ubuntu 16.04!**

Anyone with idea what's happening (native carla method: `iamge.save_to_disk` works only on my second machine with exact specification)?
