### ISSUE TITLE
Hi @analog-cbarber ! I tried ``` make launch ``` on your fork of carla with XCode Version 9.4.1 , but I get ``` clang 5.0 is required, but it's not installed.

### ISSUE THREAD

**Issue by shin2suka** [carla-simulator/carla#892]
I have the same issue as yours. How did you fix this?

make sure you build Unreal Engine with clang 5.0 too.
make: *** [setup] Error 1 ```. What's the recommended setup here? Should I install llvm via homebrew?

_Originally posted by @mariaka in https://github.com/carla-simulator/carla/issues/150#issuecomment-416045592_

**Comment by analog-cbarber** [comment]
I am not using the 0.9 branch of CARLA yet, so I have not used it since I wrote up the instructions, but you should not need llvm at all. The real work is done in the .command files in Util/BuildTools. It seems that you are invoking linux .sh files instead of the Mac .command files.
