### ISSUE TITLE
Mixed reality overlay

### ISSUE THREAD

**Issue by sandman** [carla-simulator/carla#90]
Hi,
Would it be possible to overlay the semantic segmented map on top of the Post-processed camera view to create a mixed-reality view?

**Comment by nsubiron** [comment]
I think this should be done in the client side, it shouldn't be too difficult to blend the two images in Python

**Comment by felipecode** [comment]
I don't exactly understand your objective.  What do you mean by mixed-reality view ?
Just a simple merge between labels and rgb ? This could be easy to be done on the client
side. If you do it, maybe it is a good function to eventually add to the client.

**Comment by sandman** [comment]
I'm exploring shared semi-autonomous control where a human driver is assisted by local-AI in the car. Here's a reference: http://ieeexplore.ieee.org/abstract/document/6232153/

In this case, a simple merge with a transparency layer should work, right?

**Comment by felipecode** [comment]
Yes ! It should work! 
Please share with us after you do it !

**Comment by sandman** [comment]
Sorry, I mistakenly tried to commit to the master! I got this working with a simple 1-line change. You can view the gist --> https://gist.github.com/sandman/9549ebc5188e493cc4091fe268accdb5

**Comment by sandman** [comment]
And here's a screenshot:
![mixed_reality](https://user-images.githubusercontent.com/11884/35345632-6a62db6e-0130-11e8-9a42-5cafe8aff43f.png)

**Comment by nsubiron** [comment]
Hi @sandman, thanks for sharing! :)
