### ISSUE TITLE
weird Segmentation picture

### ISSUE THREAD

**Issue by yangzuyuanhao** [carla-simulator/carla#900]
Hi,
For some research reasons, I used the Segmentation camera in this way:

imagedata = sensor_data.get('CameraRGB',None)                 
bgra_data = to_bgra_array(imagedata)
rgb_img= bgra_data[:,:,:3]      #change to rgb
cv2.imwrite("../test3.jpg",rgb_img)
                 
semsegdata = sensor_data.get('CameraSegmentation',None)
semseg_bgra = to_bgra_array(semsegdata)                 
semseg_img = semseg_bgra[:,:,:3]   #change to rgb
cv2.imwrite("../test3.jpg",semseg_img)

But when I use OpenCV to generate the image, the RGB images looks okay, but the corresponding Segmentation image becomes weird, see below:
![test3](https://user-images.githubusercontent.com/36458664/47377887-7afaf000-d6c4-11e8-9693-db808352a129.jpg)
![test3_sem](https://user-images.githubusercontent.com/36458664/47377913-9534ce00-d6c4-11e8-8c53-20e813d9ec6d.jpg)
Any one knows why? Many thanks!

**Comment by yangzuyuanhao** [comment]
Figured it out, close

**Comment by Capuz93** [comment]
Hi,
I have your same problem. I'm using: 

> ./image_converter -c semseg -i ../input_folder -o ../output_folder 

to generate the correct semantic images, but it doesn't work.
How did you fix this problem?
Thanks

**Comment by Capuz93** [comment]
Ok. I figured it out. It is a graphic card problem.
Close
