### ISSUE TITLE
Error with `make PythonAPI`

### ISSUE THREAD

**Issue by nicolebd** [carla-simulator/carla#901]
I have built Carla from source on Ubuntu 16.04. Whenever I try to run `make PythonAPI`, I get the following:

In file included from source/libcarla/libcarla.cpp:38:
In file included from source/libcarla/SensorData.cpp:9:
In file included from dependencies/include/carla/image/ImageIO.h:9:
In file included from dependencies/include/carla/image/ImageIOConfig.h:50:
In file included from dependencies/include/boost/gil/extension/io/png_io.hpp:35:
In file included from /usr/include/png.h:321:
/usr/include/pngconf.h:383:12: error: unknown type name '__pngconf'
           __pngconf.h__ in libpng already includes setjmp.h;
           ^
/usr/include/pngconf.h:383:21: error: cannot use dot operator on a type
           __pngconf.h__ in libpng already includes setjmp.h;
                    ^
/usr/include/pngconf.h:384:12: error: unknown type name '__dont__'
           __dont__ include it again.;
           ^
/usr/include/pngconf.h:384:28: error: expected ';' after top level declarator
           __dont__ include it again.;
                           ^
4 errors generated.
error: command 'clang-5.0' failed with exit status 1
Util/BuildTools/Linux.mk:47: recipe for target 'PythonAPI' failed
make: *** [PythonAPI] Error 1

EDIT: Setting `-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=false` in the setup.py file works for my purpose.

**Comment by nsubiron** [comment]
Hi @nicolebd,

You need to install `libpng16-dev`. Last merges into master require these new dependencies

    sudo apt-get install libpng16-dev libtiff5-dev libjpeg-dev

**Comment by Unlingius** [comment]
@nsubiron    I try to install libpng16-dev, it depends on libpng16-devtools - this lib conflicts with many other libs in my system, including ros. In ros I use libpng12.  Is that possible to change version in carla to 12? How difficult it will be for me?

**Comment by nsubiron** [comment]
Hi @Unlingius, yes, it's a known issue, unfortunately our image library (Boost.GIL) does not support libpng12. You can apply the changes in #924 for now and save the images in TIFF.

**Comment by Unlingius** [comment]
Thank you so mush! It works fine!

**Comment by Unlingius** [comment]
@nsubiron  i try to compile newest release 0.9.2 and this instruction doesn't work now. Compilation crashes with that error:
/usr/include/pngconf.h:383:12: error: unknown type name '__pngconf'
           __pngconf.h__ in libpng already includes setjmp.h;
           ^
/usr/include/pngconf.h:383:21: error: cannot use dot operator on a type
           __pngconf.h__ in libpng already includes setjmp.h;
                    ^
/usr/include/pngconf.h:384:12: error: unknown type name '__dont__'
           __dont__ include it again.;
           ^
/usr/include/pngconf.h:384:28: error: expected ';' after top level declarator
           __dont__ include it again.;

How can i fix it?

**Comment by Unlingius** [comment]
fixed. see extra_compile_args += ['-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=false']  in PythonAPI/setup.py

**Comment by hynkis** [comment]
Thanks, Unlingius. Changing 'true' to 'false' makes it work!

**Comment by soulslicer** [comment]
I dont see the file seutp.py anywhere!
