### ISSUE TITLE
Mustang' wheel slip?

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla#914]
Hello,carla team!
During the simulation,I found that there is wheel slip problem about the Mustang ,can this problem be solved?
platform:
              Ubuntu 16.04
               CARLA 0.8.4

Thanks!

**Comment by nsubiron** [comment]
Hi @chengjinjack, could you elaborate a bit more? What sort of problem are you observing?

**Comment by chengjinjack** [comment]
@nsubiron,Hi
I  maked Mustang travel in a circle,and subscribed the topic(/play_ odometry),plotd the vehicle trajectory,I found that the vehicle trajectories of multiple travels did not coincide.so I think that the car is slipping.Can this problem be solved?

**Comment by nsubiron** [comment]
If you open the carla project with Unreal Editor you can adjust all the parameters of the vehicles, including the tire friction, maybe you can experiment with that and see if that's really the problem.
