### ISSUE TITLE
Runnig CARLA on cloud (AWS EC2)

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/carla#917]
Hi,

Dose anyone run CARLA on AWS EC2. How can I get CARLA run on AWS? Is there any toturial or documentation in this regard. The old issues did not help a lot.

Best,

**Comment by analog-cbarber** [comment]
Yes, you can run it on EC2. I don't think there are explicit instructions for that but there is this:
https://carla.readthedocs.io/en/stable/carla_headless/

**Comment by wendersonj** [comment]
Hi ! I want to reopen this issue. I'm trying to use the tutorial to carla_headless in the latest (0.9.3), but everytime I get stucked in `sudo nohup Xorg :7 & ` it says that the command Xorg doens't exist ! Could anyone help me ?

Last lines of log:
![captura de tela de 2019-02-13 06-40-04](https://user-images.githubusercontent.com/15368591/52702111-62a42f00-2f5a-11e9-893e-24359ab1c782.png)

[Full Log](https://pastebin.com/7XYt7n2X)

**Comment by thefatbandit** [comment]
Thank Jbnunn https://github.com/jbnunn/CARLADesktop.
Succesfully run carla on AWS EC2.

**Comment by jbnunn** [comment]
I'll be updating this soon to run with v 0.9.13
