### ISSUE TITLE
Split off ros-bridge into carla-ros repo

### ISSUE THREAD

**Issue by harlowja** [carla-simulator/carla#920]
IMHO it should be its own repo with its own requirements and its own tests and...

I can even (maybe) contribute our ros usage as a starting point (and work to integrate the other ros functionality that exists into that).

**Comment by laurent-george** [comment]
Could be a good idea (it will allow to track issues related to ros bridge more easily in my opinion).

**Comment by nsubiron** [comment]
We will discuss it here with the team to see all the pros and cons, but yeah IMO feels a bit disconnected from the rest of the repo, seems like it deserves its own.

**Comment by harlowja** [comment]
I can also figure out how to contribute a dedicated ros<->manual_control(like) program that I am building/working on that should I think act as a good collaboration area for all ros folks (right now most of the ros folks I think are POCing with 0.8, which I am not doing, I am using 0.9 even though that moves more). When that happens it starts to feel like it deserves its own repo and such (though that may be more of a PITA than its worth, idk).

**Comment by danil-tolkachev** [comment]
It sounds reasonable. It would also be a more convenient way to install ros bridge without symlinks.
