### ISSUE TITLE
Can we change the view of camera image which is Saved? 

### ISSUE THREAD

**Issue by kouya-marino** [carla-simulator/carla#922]
I want the camera view to be on top of windshield which will give a first-person view(what drivers sees while driving)???

**Comment by kouya-marino** [comment]
![parallel-domain](https://user-images.githubusercontent.com/31544383/47618249-e266d480-daf6-11e8-9749-c5654e73afde.gif)

**Comment by nsubiron** [comment]
Hi @kouya-marino, you set the camera position when you start a new episode, either in Python or in the _"CarlaSettings.ini"_ file. Please take a look at our [documentation](https://carla.readthedocs.io/en/stable/cameras_and_sensors/) for examples on how to do it.

**Comment by analog-cbarber** [comment]
Note that the correct offset will depend on which player vehicle you are using.
