### ISSUE TITLE
how to interact carla 0.9.0 with PythonAPI using python3 ?

### ISSUE THREAD

**Issue by 18605973470** [carla-simulator/carla#929]
only python2 can work ?

**Comment by nsubiron** [comment]
Python 3 is also available in master branch already. You can get a nightly build from [our Jenkins server](http://158.109.9.218:8080/blue/organizations/jenkins/carla/detail/master/30/artifacts). Though this is still experimental.

**Comment by 18605973470** [comment]
Hi nsubiron:
I download PythonAPI/dist/carla-0.9.0-py3.5-linux-x86_64.egg on this Jenkins server.
But I failed to start manual_control.py with this API version.

Error message are :

**Comment by nsubiron** [comment]
You need to update the simulator too, in the same link you can download the release package.
