### ISSUE TITLE
attach/detach spectator to vehicle

### ISSUE THREAD

**Issue by Camouflager** [carla-simulator/carla#930]
Child of #630.

I can implement this behavior from client by calling SetActorTransform. But there will be lags and the vehicle being monitored will be twitching in the middle of the screen.

The ideal way to do this is to setup some sort of attachment between the PlayerControl and the target Actor from inside the gameloop. There is the "attach_actors" api that's not fully exposed but I doubt it would work for the PlayerController. So I googled around and found that you could do SetViewTarget but it doesn't say anything about "RelativeTransform" so I got confused and decided to post this issue...

I see that the 0.9.1 is not likely to support this feature. I wonder if there's any cheap way to eliminate the twitches. Any help will be appreciated.

**Comment by nsubiron** [comment]
I don't think there is any hack around this, but I'd like to add this behaviour too, I think can be very handy for visualizing, debugging, etc. Also, it would be great if can add a "spring arm" attachment type, that looks much better visually for 3rd person cameras.
