### ISSUE TITLE
fatal: repository 'https://github.com/EpicGames/UnrealEngine.git/' not found

### ISSUE THREAD

**Issue by fcagroupj** [carla-simulator/carla#940]
When I tried to build carla as https://carla.readthedocs.io/en/latest/how_to_build_on_linux/, I have the problems shown:
fatal: repository 'https://github.com/EpicGames/UnrealEngine.git/' not found

**Comment by fcagroupj** [comment]
I found and fixed, thanks:)
https://answers.unrealengine.com/questions/422750/why-cant-i-find-repository.html

**Comment by faizan002** [comment]
I have the same issue when I go to https://github.com/EpicGames
I do not see UnrealEngine there. :(

**Comment by iscanGH** [comment]
> I have the same issue when I go to https://github.com/EpicGames I do not see UnrealEngine there. :(

Did you find the solution? I have the same problem

**Comment by xiaoqingnianbudadun** [comment]
I get the code here, https://github.com/CarlaUnreal/UnrealEngine
there is another repository

**Comment by debipe20** [comment]
I have the same issue, could someone add me to the group?

Thanks.
