### ISSUE TITLE
How to read data in CARLA 0.9?

### ISSUE THREAD

**Issue by antoniodvc** [carla-simulator/carla#943]
After changes in the API in CARLA 0.9, I'd like to know if there's a way to read dynamic measurements of vehicle or sensors data.

**Comment by marcgpuig** [comment]
Hi @antoniodvc, sorry for the late response.

We will add more documentation soon, meanwhile, you can take a look at current examples that you can find in [`carla/PythonAPI/`](https://github.com/carla-simulator/carla/tree/master/PythonAPI).

Cheers.
