### ISSUE TITLE
Request for Documentation on car simulation 

### ISSUE THREAD

**Issue by priyankagade552** [carla-simulator/carla#967]
Hi,
I'm working in a project related to autonomous vehicle program and the code till date used was simulated in Gazebo and we would further want to know whether CARLA could be made as a simulator for the work as it has more realistic features.

I'm working with CARLA for the first time. I've installed 0.8.4 and tried out 0.7.1 tutorial in which the autopilot mode is present. And i wanted to know whether the documents for the following are available.

1. Stable recent version of CARLA and tutorials available on it?
2.  Is customized Car Simulation in CARLA possible?
3. Is there any architectural flow diagram of the modules implemented?

The basic documentation for the car simulation would help so that we could check whether we could use it for the project we are working.

Thank you.

**Comment by felipecode** [comment]
Hello @priyankagade552 

I think you refer CAR simulation as the aspects related to physics.
For that you could dig into unreal engine. 
Unfortunately, on current versions of CARLA
we do not expose to the API any posibility of changing aspects from the physical simulation.
