### ISSUE TITLE
Lane and poles are the same color in semantic segmentation

### ISSUE THREAD

**Issue by Capuz93** [carla-simulator/carla#969]
Hi,
I obtained the images from Camera Segmentation but I discovered that "RoadLines" and "Poles" classes have the same color in the images (153, 153, 153).

How can I fix this problem?

Thanks

**Comment by nsubiron** [comment]
Hi @Capuz93,

You're right! The road lines used to be (157, 234, 50). It can be modifies in [CityScapesPalette.h](https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/image/CityScapesPalette.h).

I'm not sure what's the color in CityScapes, can't seem to find road lines there. When I did that I was using the labels [here](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py).

**Comment by Capuz93** [comment]
Thanks.
I changed the values in CityScapesPalette.h but the color of lanes and poles are still the same.
 What should I have to do?

Thanks

**Comment by Capuz93** [comment]
Ok I fixed it. I changed label_pixel_converter.h.

Thanks

**Comment by nsubiron** [comment]
Wait, don't close it until we fix it too :sweat_smile:
