### ISSUE TITLE
How to get vehicle rotation matrix?

### ISSUE THREAD

**Issue by jingleFun** [carla-simulator/carla#97]
what is the meaning of orientation in your proto file ? how can i get the rotation matrix? 
---------------------
"The transform contains two Vector3D objects, location and orientation. Currently, the orientation is represented as the Cartesian coordinates X, Y, Z. We will probably change this in the future to Roll, Pitch, and Yaw."

**Comment by nsubiron** [comment]
Hi @jingleFun,
The orientation is defined as the forward vector of the vehicle
![](http://carla.readthedocs.io/en/latest/img/vehicle_bounding_box.png)

We are about to change it however to roll, pitch and yaw. This is already in the dev branch and will come into master in the coming release.

**Comment by coolKeen** [comment]
@nsubiron @jingleFun  I don't know whether I truly understand what the orientation  means? I wander whether the coordinate of orientation is the same as the coordinate of the location?If so, when the orientation is (0.0,1.0,0.0) for example,will the car  only increase its location's y value(what I see in the carla is that the car still increase its location's x value )?

**Comment by nsubiron** [comment]
If the orientation were exactly (0.0, 1.0, 0.0) the car would only move in the Y axis. But in practice the car is not perfectly oriented so you get some small variation in the X axis too.

**Comment by soulslicer** [comment]
how do i get the orinetation?
