### ISSUE TITLE
Vehicle spawned  in Town03 with autopilot mode keeps moves in circle

### ISSUE THREAD

**Issue by Kevin199Q** [carla-simulator/carla#971]
Hello, when i spawn a vehicle in town03 using tutorial.py, the vehicle keeps moving in circle.  And it doesn't work when i spawn vehicle in other positions.

Does anyone encounter with the same situation. Thank you!

**Comment by Kevin199Q** [comment]
Hi @iFuSiiOnzZ ,
Thank you for the replay. 
How could I get the certain positions in Town03 where i can spawn the autopilot vehicle with python?

**Comment by Kevin199Q** [comment]
Thank you very much. I will try it.

**Comment by YDSh510** [comment]
@Kevin199Q and @iFuSiiOnzZ 

I tried running tutorial.py but my camera is never focus to the ego or npc vehicle and its some where else in the scene and I and not able to see any of the ego or npc vehicle spawning or moving. Do we need to do any change in script?
