### ISSUE TITLE
How to change first person's view in game mode?

### ISSUE THREAD

**Issue by grzechm** [carla-simulator/carla#974]
Hi, we got a question regarding changing camera view in manual mode(we are using carla 0.8.4).
We want to move camera(not talking about RGB camera) a little bit forward so that when we drive a car in manual mode we do not see the car mask. 
It would be also helpful to know as we are going to use a little bigger vehicle and in first view mode we cannot see anything as camera is in the car.

![carla_screen](https://user-images.githubusercontent.com/23620527/48701759-8839ca80-ebef-11e8-99e1-1dad4f6c149e.png)

**Comment by marcgpuig** [comment]
Hi @grzechm.
Take a look at these lines of the configuration file:
https://github.com/carla-simulator/carla/blob/cddb98282c44481194bf7d96faccc02beb716387/Docs/Example.CarlaSettings.ini#L85-L88
For more info about the config file take a look at the [0.8.4 documentation](https://carla.readthedocs.io/en/0.8.4/) about [carla settings](https://carla.readthedocs.io/en/0.8.4/carla_settings/) and [configuring the simulation](https://carla.readthedocs.io/en/0.8.4/configuring_the_simulation/).
