### ISSUE TITLE
make PythonAPI error win10 

### ISSUE THREAD

**Issue by nicksunyang** [carla-simulator/carla#975]

**Comment by sriharshakunda** [comment]
I am having an issue while building PythonAPI.
Below is my error log.

c:\carla\pythonapi\source\libcarla\Blueprint.cpp(155): error C2672: 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def': no matching overloaded function found                                                                                                                                                                                                       c:\carla\pythonapi\source\libcarla\Blueprint.cpp(155): error C2780: 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified> &boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def(const char *,Fn,const A1 &,const A2 &,const A3 &)': expects 5 arguments - 1 provided                                                                                                                                                                                                                                    dependencies/include\boost/python/class.hpp(261): note: see declaration of 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def'                                                                                                                                                                                                                                       c:\carla\pythonapi\source\libcarla\Blueprint.cpp(155): error C2780: 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified> &boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def(const char *,Fn,const A1 &,const A2 &)': expects 4 arguments - 1 provided  dependencies/include\boost/python/class.hpp(245): note: see declaration of 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def'                                                                                                                                                                                                                                       c:\carla\pythonapi\source\libcarla\Blueprint.cpp(155): error C2780: 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified> &boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def(const char *,A1,const A2 &)': expects 3 arguments - 1 provided             dependencies/include\boost/python/class.hpp(238): note: see declaration of 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def'                                                                                                                                                                                                                                       c:\carla\pythonapi\source\libcarla\Blueprint.cpp(155): error C2780: 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified> &boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def(const char *,F)': expects 2 arguments - 1 provided                         dependencies/include\boost/python/class.hpp(229): note: see declaration of 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def'                                                                                                                                                                                                                                       c:\carla\pythonapi\source\libcarla\Blueprint.cpp(155): error C2784: 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified> &boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def(const boost::python::def_visitor<Derived> &)': could not deduce template argument for 'const boost::python::def_visitor<Derived> &' from 'const char [12]'                                                                                                                                                              dependencies/include\boost/python/class.hpp(219): note: see declaration of 'boost::python::class_<carla::client::BlueprintLibrary,boost::noncopyable,boost::shared_ptr<carla::client::BlueprintLibrary>,boost::python::detail::not_specified>::def'                                                                                                                                                                                                                                       c:\carla\pythonapi\source\libcarla\Blueprint.cpp(156): error C2228: left of '.def' must have class/struct/union                                                                                                                              c:\carla\pythonapi\source\libcarla\Blueprint.cpp(156): fatal error C1003: error count exceeds 100; stopping compilation                                                                                                                      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2                                                                                                                                                                                                                                                                                                                                                              -[BuildPythonAPI]: Carla lib for python has been successfully installed in "C:/carla/PythonAPI\dist"!         

However, when I look for "dist" folder in PythonAPI folder, there is none. 

Can someone point me what am I doing wrong?

I did fresh installations twice and couldnt find whats wrong.
