### ISSUE TITLE
How to save map as opendrive format?

### ISSUE THREAD

**Issue by tanglrHello** [carla-simulator/carla#979]
In the full list of changes for release 0.9.1, the document mentioned a change: "Added methods for converting and saving the map as OpenDrive format". 
But I didn't find the api which seems to related to this. There is a static member function named "Dump()" in class OpenDrive (carla/LibCarla/source/carla/opendrive/OpenDrive.h) , and it recieve a Map object as input, and looks like to achieve the "converting". But this function is unimplemented. So how can I make use of the "converting and saving as OpenDrive format" ?

**Comment by iFuSiiOnzZ** [comment]
Hi,

The map object has a function called `save_to_dis(...)`, this will save the OpenDrive of the current loaded city to the given path.

```python
world = client.get_world()
world.get_map().save_to_disk(".\opendrive.xml")
```
