### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/carla#983]
I  am a bit confused about the data set presented [here](https://github.com/carla-simulator/imitation-learning).

In this dataset the value of **throttle is always 0.5 or 1**, while the value of steer angle is **uniform**. This does not make sense. Dose this data has used in the CARLA's paper?

**Comment by felipecode** [comment]
Being discussed on 
https://github.com/carla-simulator/imitation-learning/issues/44
