### ISSUE TITLE
No module named 'carla' after tutorial.py execution

### ISSUE THREAD

**Issue by erivera1802** [carla-simulator/carla#990]
Hello Everyone,
I am triying to drive manually a car with the 0.9.0 version of carla, I have read that it isnt just running it in Unreal, but you have to execute the python files for it. So I tried exactly that, but  it doesnt find the carla python modules:
```

esteban@esteban-Hyrican-PC:~/carla/PythonAPI$ ./tutorial.py
Traceback (most recent call last):
  File "./tutorial.py", line 21, in <module>
    import carla
ModuleNotFoundError: No module named 'carla'
```
The same error appeared when I executed manual_control.py (I think that is what I wan now, to manually control a vehicle). 

I have already followed the instructions of the readthedocs page, and can already see carla working over unreal, basically exactly like this:
https://github.com/carla-simulator/carla/issues/660

-----
Update:
I made make check, and the following error appeared
gcc: error: /home/esteban/carla/PythonAPI/dependencies/lib/libboost_python37.a: No such file or directory
I checked the directory, and saw that I had libboost_python27.a. Maybe could I somehow point to that file?

My Carla Version is 0.9.0
Ubuntu 16.04
GPU RTX 2080
Does anyone know what am I missing?

**Comment by fabianoboril** [comment]
Hi,

if you want to use the Python clients you should run "make PythonAPI". This will build the carla modules (you can find them in PythonAPI/dists/*.egg). Then you either install them (e.g. with easy_install) or for testing extend your PYTHON_PATH to include these. Hope it works.

Bests

**Comment by tanglrHello** [comment]
Hi, you can run "make package" at the root path of carla. If succeed, you will get a 'Dist' directory under this path. Enter it and you will find the .py files. Run the .py files at this place and it should be ok.

**Comment by erivera1802** [comment]
Hi, @fabianoboril and @tanglrHello,
I tried the 'make PythonAPI' and 'make package' commands, but again i get the same error: carla/PythonAPI/dependencies/lib/libboost_python37.a: No such file or directory.
Until now, my workaround has been executing them with python2, but I though this 0.9.1 version was already compatible with python3.

**Comment by fabianoboril** [comment]
Can you maybe post a compile log that we could look into? Thanks!

**Comment by yyuuliang** [comment]
Maybe try the setup.py in the PythonAPI folder.

**Comment by coreper** [comment]
> Hi, @fabianoboril and @tanglrHello,
> I tried the 'make PythonAPI' and 'make package' commands, but again i get the same error: carla/PythonAPI/dependencies/lib/libboost_python37.a: No such file or directory.
> Until now, my workaround has been executing them with python2, but I though this 0.9.1 version was already compatible with python3.

Same issue for me.

**Comment by manishthani** [comment]
Hi everyone,
Having Anaconda installed for Python3 shows exactly the same error when trying to run `make PythonAPI` command. Solved the problem by uninstalling it following the steps described in this [link](https://stackoverflow.com/questions/22585235/python-anaconda-how-to-safely-uninstall) and executing the command again.
Hope this helps!

**Comment by MaxHBor** [comment]
Hello. Got the same problem with compiled 0.9.4 version for Windows.
