### ISSUE TITLE
How to get the distance of the vehicle from the center of the lane and the angle between the vehicle orientation and the road tangent

### ISSUE THREAD

**Issue by HubFire** [carla-simulator/carla#992]
Thanks for Carla team hard work.
I  want to train a reinforcement learning agent based on CARLA.
How to get the distance of the vehicle from the center of the lane and the angle between the vehicle orientation and the road tangent？

**Comment by marcgpuig** [comment]
Hi @HubFire.

Using [0.9.1](https://github.com/carla-simulator/carla/releases/tag/0.9.1) you are able to get a `carla.Waypoint` (based on the OpenDrive) using:
```py
waypoint = client.get_world().get_map().get_waypoint(carla.Location, project_to_road=True)
```
As you have specified `project_to_road=True`, this waypoint will be on the center of the (nearest) road.
A `carla.Waypoint` have a `carla.Transform` that have a `carla.Location` and a `carla.Rotation`.
You can use this transform to get the distance of the center of the road and the orientation difference.

Cheers!

**Comment by YashBansod** [comment]
@marcgpuig I wanted to know more about the **Waypoints**. Here are my doubts on the matter:
(I do not expect direct answers to all of them, but it would be great if you could direct me to the relevant document / literature where I could find the answers).

- How are waypoints represented in the Map.

- When you call `get_waypoint(Location)`:
    - Is the returned waypoint the nearest waypoint (from a list of waypoints in the map) to the Location?
**or**
    - Is it the transform of the nearest waypoint (point normal to the nearest road network) ?

- How do I compute road curvature?
    - My present idea is to get the next few waypoints, fit a cubic spline over these points and get the curvature.
    - But, If you can direct me to literature regarding the road network and the waypoints used, I think there might be a better way to go about it.

- When we call `map.generate_waypoints(distance)`:
    - Why aren't the waypoints generated near the vicinity of the vehicle / spectator. How to make that happen?

- When we call `waypoint.next(distance)`:
    - Is the new waypoint precisely that euclidean distance away from the present point or is it the distance along the route.

**Comment by silviaman** [comment]
Hi @marcgpuig I was wondering if there was any news on how to access the road geometry through the Python API. I would also need to compute the road curvature, maybe you can give me a hint on that? Thanks!

**Comment by aakashsehgal** [comment]
@YashBansod Did you finally get through with the calculating the curvature ? If yes then maybe you could pass on the knowledge :)

**Comment by kannidekan** [comment]
I use this approximation method. 
curvature = distance_degree / distance_route.
"""python
def calcu_c(host_waypoint, route_distance, min_angel_dif):
            previous_waypoint = host_waypoint.previous(route_distance)[0]
            next_waypoint = host_waypoint.next(route_distance)[0]
            total_route_distance = 2*route_distance
            angel_dif = next_waypoint.transform.rotation.yaw-previous_waypoint.transform.rotation.yaw
            # if angel_dif < min_angel_dif:
            #     c_0 = 0
            # else:
            c_0 = radians(angel_dif) / total_route_distance
            return c_0 
"""

**Comment by mamaduke21** [comment]
> I use this approximation method.
> 
> ```python
>         def calcu_c_1(host_waypoint, route_distance):
>             previous_waypoint = host_waypoint.previous(route_distance)[0]
>             next_waypoint = host_waypoint.next(route_distance)[0]
>             _transform = next_waypoint.transform
>             _location, _rotation  = _transform.location, _transform.rotation
>             x1, y1 = _location.x, _location.y
>             yaw1 = _rotation.yaw
> 
>             _transform = previous_waypoint.transform
>             _location, _rotation  = _transform.location, _transform.rotation
>             x2, y2 = _location.x, _location.y
>             yaw2 = _rotation.yaw
> 
>             c = 2*sin(radians((yaw1-yaw2)/2)) / sqrt((x1-x2)**2 + (y1-y2)**2)
>             return c
> ```
> 
> std and mean with different route_distance. ![Figure_1](https://user-images.githubusercontent.com/22550160/102713997-f2f5ec80-4306-11eb-8e41-42d1369e5d26.png)

Hello! I'm having some problems implementing this method to calculate the road curvature. What do you mean with 'route_distance'? Has someone been able to implement this method or another similar one? 

Thanks to everyone!

**Comment by Morphlng** [comment]
> Hello! I'm having some problems implementing this method to calculate the road curvature. What do you mean with 'route_distance'? Has someone been able to implement this method or another similar one?

That waypoint api requires a distance argument to specify how far the `previous` or `next` waypoint you want. Based on the script @kannidekan provided, it is used to get the desired waypoint in "route_distance" ahead or behind.
