### ISSUE TITLE
how to get offroad info of vehicles in new release from Python API 

### ISSUE THREAD

**Issue by zj-gm** [carla-simulator/carla#993]
hey, Carla team, I am trying to detect the offroad event of vehicles in simulator. is there a way to get from current Python APIs ? Thxs

**Comment by nsubiron** [comment]
Hi @zj-gm,

At this point the event only tells you if you crossed a solid lane marking, that currently happens only if you either go off-road (to the right of your lane) or to the opposite lane (to the left of your lane).

**Comment by noahcao** [comment]
Hi @nsubiron ,
I can get the lane type of a waypoint from carla 0.9.4. I tried to detect offroad by checking whether current vehicle's waypoint is of "driving" lane type. But there is some issue that the lane type is always "driving" even if the vehicle is on the garden grass. Can you provide a solution to it or any other solution to detect offroad? Thank you.

**Comment by Rustypp** [comment]
Vibration increases as you leave the road, constantly monitor vibrations then look for changes?
