### ISSUE TITLE
Prepare a dataset for RL

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/carla#998]
Hi CARLA team!

My goal is to prepare a dataset to test a reinforcement algorithm. To achieve that goal it seems I can use one of the two scripts `manual.py` or `client_example.py` in autopilot mode. I read in one issue that the autopilot mode is not a good option for data collection? Can someone please clarify why? 
If one need to use `manual.py` is it necessary to use joystick or logitech?

Thanks in advance.

**Comment by felipecode** [comment]
Hey, what do you mean by dataset for RL ? Shouldnt you try to learn directly by interaction ?
I think the best way to perform data collection is to have an "oracle" a hardcoded programmed agent that has priveledge information and drive perfectly on the CARLA scenarios.

**Comment by felipecode** [comment]
check this repository 
https://github.com/carla-simulator/data-collector

**Comment by felipecode** [comment]
It does not have bounding boxes on the image data directly. However it comes with semantic segmentation images and the world position for all the objects.
